Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-02, with the labels that each got.

#5800 {math}[foss/2017b] Ipopt 3.12.9
  easybuild/easyconfigs/a/AMPL-MP/AMPL-MP-3.1.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/i/Ipopt/Ipopt-3.12.9-foss-2017b.eb
Labels: new

#5807 {math}[foss/2017b] Mmg v5.3.9
  easybuild/easyconfigs/m/Mmg/Mmg-5.3.9-foss-2017b.eb
Labels: new

#5811 {data,math}[foss/2017b] Keras v2.1.3, Theano v1.0.1, h5py v2.7.1, ...
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/k/Keras/Keras-2.1.3-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/t/Theano/Theano-1.0.1-foss-2017b-Python-3.6.3.eb
Labels: update

#5815 {data}[GCCcore/6.4.0] Perl 5.26.1, XML-Parser 2.44_01
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-6.4.0-Perl-5.26.1.eb
Labels: update

#5818 {tools}[GCCcore/6.4.0] pstoedit v3.70
  easybuild/easyconfigs/p/pstoedit/pstoedit-3.70-GCCcore-6.4.0.eb
Labels: new

#5768 {toolchain}[dummy/dummy] goolfc v2017b
  easybuild/easyconfigs/c/CUDA/CUDA-9.0.176-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.6-gompic-2017b.eb
  easybuild/easyconfigs/g/gcccuda/gcccuda-2017b.eb
  easybuild/easyconfigs/g/gompic/gompic-2017b.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2017b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2017b-OpenBLAS-0.2.20.eb
Labels: update

#5812 {vis}[foss/2017b] scikit-image v0.13.1, matplotlib v2.1.1
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2017b-Python-3.6.3.eb
Labels: update

#5822 fix hardcoded version in scikit-image easyconfigs
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-intel-2017b-Python-2.7.14.eb
Labels: bug fix

#5781 {cae}[foss/2017b,intel/2017b] OpenFOAM v1712
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1712-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1712-foss-2017b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1712-intel-2017b.eb
Labels: update

#5817 fix pkgconfig moduleclass, 'data' doesn't make much sense
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016a-Python-3.5.1.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2015a-Python-2.7.9.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2015b-Python-2.7.10.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2015b-Python-2.7.11.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017b-Python-3.6.3.eb
Labels: change

#5824 {devel}[dummy] ant 1.10.1
  easybuild/easyconfigs/a/ant/ant-1.10.1-Java-1.8.0_162.eb
  easybuild/easyconfigs/j/JUnit/JUnit-4.12-Java-1.8.0_162.eb
Labels: update

#5757 {lib}[foss/2017b] MATIO v1.5.11
  easybuild/easyconfigs/m/MATIO/MATIO-1.5.11-foss-2017b.eb
Labels: update

#5762 {compiler}[GCCcore/6.4.0] LLVM v5.0.1
  easybuild/easyconfigs/l/LLVM/LLVM-5.0.1-GCCcore-6.4.0.eb
Labels: update

#5746 {math}[GCCcore/5.4.0,GCCcore/6.3.0] libcerf v1.5, libcerf v1.5
  easybuild/easyconfigs/l/libcerf/libcerf-1.5-GCCcore-5.4.0.eb
  easybuild/easyconfigs/l/libcerf/libcerf-1.5-GCCcore-6.3.0.eb
Labels: update

#5318 {lib}[foss/2017b] TensorFlow v1.4.0 w/ Python 3.6.3 (built from source)
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.4.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.4.0_no-enum34.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.4.0_swig-env.patch
  easybuild/easyconfigs/w/wheel/wheel-0.30.0-foss-2017b-Python-3.6.3.eb
Labels: enhancement, update

#5804 {tools}[GCC/6.4.0-2.28] libMemcached v1.0.18
  easybuild/easyconfigs/l/libMemcached/libMemcached-1.0.18-GCCcore-6.4.0.eb
Labels: new

#5786 Update emacs 25.3 to gcccore 6.4
  easybuild/easyconfigs/e/Emacs/Emacs-25.3-GCCcore-6.4.0.eb
Labels: update

#5846 {data}[foss/2018a] HDF5 v1.10.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-foss-2018a.eb
Labels: update

#5777 {tools}[giolf/2018a] HPL v2.2
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gimpi-2018a.eb
  easybuild/easyconfigs/g/gimpi/gimpi-2018a.eb
  easybuild/easyconfigs/g/giolf/giolf-2018a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-giolf-2018a.eb
  easybuild/easyconfigs/i/impi/impi-2018.1.163-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gimpi-2018a-OpenBLAS-0.2.20.eb
Labels: update

#5769 {lib}[goolfc/2017b] TensorFlow 1.5.0 w/ Python 3.6.3 (built from source)
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.0.5.15-goolfc-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-goolfc-2017b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0-goolfc-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0_dont_expand_cuda_path.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0_dont_expand_cudnn_path.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0_swig-env.patch
  easybuild/easyconfigs/w/wheel/wheel-0.30.0-goolfc-2017b-Python-3.6.3.eb
Labels: update

#5844 {compiler}[dummy/] PGI v17.4
  easybuild/easyconfigs/p/PGI/PGI-17.4-GCC-6.4.0-2.28.eb
Labels: update

#5814 {lib}[foss/2017b] TensorFlow v1.4.1 w/ Python 3.6.3 (built from source)
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.4.1-foss-2017b-Python-3.6.3.eb
Labels: update

#5857 {lib}[intel/2017a] rpy2 v2.8.2
  easybuild/easyconfigs/r/rpy2/rpy2-2.8.2-intel-2017a-Python-2.7.13.eb
Labels: update

#5828 {devel}[dummy/dummy] Gradle v4.5.1
  easybuild/easyconfigs/g/Gradle/Gradle-4.5.1.eb
Labels: new

#5850 {data}[intel/2018a] PostgreSQL v10.2
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-10.2-intel-2018a-Python-2.7.14.eb
Labels: update

#5880 add extensions to R 3.4.3 & Bioconductor 3.6 bundle + fix extension versions for Bioconductor
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.6-intel-2017b-R-3.4.3.eb
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
Labels: bug fix, enhancement, update

#5879 {mpi}[GCC/7.2.0-2.29] MPICH v3.2
  easybuild/easyconfigs/m/MPICH/MPICH-3.2-GCC-7.2.0-2.29.eb
Labels: update

#5883 {mpi}[GCC/7.2.0-2.29] MPICH v3.2.1
  easybuild/easyconfigs/m/MPICH/MPICH-3.2.1-GCC-7.2.0-2.29.eb
Labels: update

#5864 {bio}[foss/2017a] scikit-allel v1.1.8, bcolz v1.1.1, zarr v2.1.4, ...
  easybuild/easyconfigs/b/Blosc/Blosc-1.12.1-foss-2017a.eb
  easybuild/easyconfigs/b/bcolz/bcolz-1.1.1-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/d/dask/dask-0.17.0-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2017a.eb
  easybuild/easyconfigs/n/numexpr/numexpr-2.6.4-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.4.2-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.8.1-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/scikit-allel/scikit-allel-1.1.8-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.19.1-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/z/zarr/zarr-2.1.4-foss-2017a-Python-2.7.13.eb
Labels: new, update

#5886 {devel}[intel/2017b] protobuf-python v3.4.0
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.4.0-intel-2017b-Python-2.7.14.eb
Labels: update

#5890 {devel}[intel/2017b] LevelDB v1.18
  easybuild/easyconfigs/l/LevelDB/LevelDB-1.18-intel-2017b.eb
Labels: update

#5889 {devel}[intel/2017b] gflags v2.2.1
  easybuild/easyconfigs/g/gflags/gflags-2.2.1-intel-2017b.eb
Labels: update

#5888 {devel}[intel/2017b] glog v0.3.5
  easybuild/easyconfigs/g/glog/glog-0.3.5-intel-2017b.eb
Labels: update

#5891 {lib}[intel/2017b] snappy v1.1.7
  easybuild/easyconfigs/s/snappy/snappy-1.1.7-intel-2017b.eb
Labels: update

#5878 {toolchain} iomkl/2018a
  easybuild/easyconfigs/h/HPL/HPL-2.2-iomkl-2018a.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iompi-2018a.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2018a.eb
  easybuild/easyconfigs/i/iompi/iompi-2018a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
Labels: update

#5689 Add Tkinter sanity check to matplotlib (foss toolchains)
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.2-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.3-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.3-foss-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.0-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-foss-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-foss-2017b-Python-3.6.2.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.6-foss-2017a.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.13-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.1-foss-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.2-foss-2017b-Python-3.6.2.eb
Labels: enhancement

#5741 {lib}[intel/2018a] FoX v4.1.2
  easybuild/easyconfigs/f/FoX/FoX-4.1.2-intel-2018a.eb
Labels: update

#5896 add sanity check command in matplotlib easyconfigs built with intel toolchain to ensure Tkinter is available
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.2-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.2-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.3-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.3-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.1-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-2.7.13-Qt-4.8.7.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-2.7.13-libpng-1.6.29.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-3.6.1-libpng-1.6.29.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.14-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.1-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.3-intel-2017b-Python-3.6.3.eb
Labels: bug fix, enhancement

#5760 [foss/2016b] ABINIT - Correct MPI path when building with 'foss' toolchain
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.0.8b-foss-2016b.eb
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.2.2-foss-2016b.eb
Labels: bug fix

#5875 {bio}[intel/2018a] cutadapt v1.16 w/ Python 3.6.4
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-intel-2018a-Python-3.6.4.eb
Labels: update

#5884 {tools}[GCCcore/6.3.0] pstoedit v3.70
  easybuild/easyconfigs/p/pstoedit/pstoedit-3.70-GCCcore-6.3.0.eb
Labels: update

#5885 {math}[GCCcore/6.3.0] snaphu v1.4.2
  easybuild/easyconfigs/s/snaphu/snaphu-1.4.2-GCCcore-6.3.0.eb
Labels: update

#5642 patch Hyperopt to make it work with networkx 2.0
  easybuild/easyconfigs/h/Hyperopt/Hyperopt-0.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/h/Hyperopt/Hyperopt-0.1_networkx-2.0.patch
Labels: bug fix, enhancement

#5691 Add Tkinter sanity check to ASE (foss toolchain).
  easybuild/easyconfigs/a/ASE/ASE-3.13.0-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/a/ASE/ASE-3.15.0-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/a/ASE/ASE-3.15.0-foss-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/a/ASE/ASE-3.15.0-foss-2017b-Python-3.6.2.eb
Labels: bug fix, enhancement

#5688 {bio}[foss/2018a] ABySS 2.0.2
  easybuild/easyconfigs/a/ABySS/ABySS-2.0.2-foss-2018a.eb
Labels: update

#5718 git: include autotools as build dep
  easybuild/easyconfigs/g/git/git-2.12.2-foss-2016b.eb
  easybuild/easyconfigs/g/git/git-2.13.1-foss-2016b.eb
  easybuild/easyconfigs/g/git/git-2.14.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/git/git-2.16.1-foss-2018a.eb
Labels: bug fix

#5821 switch to using TensorFlow as backend for recent versions of Keras
  easybuild/easyconfigs/k/Keras/Keras-2.1.3-foss-2017b-Python-3.6.3.eb
Labels: change

#5813 {vis}[foss/2017b] OpenCV v3.3.0, GTK+ v2.24.32, ATK v2.27.1, ...
  easybuild/easyconfigs/a/ATK/ATK-2.27.1-foss-2017b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2017b.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-foss-2017b.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.0-foss-2017b.eb
Labels: update

#5897 JasPer - Fix sanity check paths for Debian OS
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.10-intel-2016b.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.12-GCCcore-6.4.0.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.12-foss-2016b.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.12-intel-2017a.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-GCCcore-6.4.0.eb
Labels: bug fix

#5725 {math}[foss/2017b] HIPS v1.2b-rc5
  easybuild/easyconfigs/h/HIPS/HIPS-1.2b-rc5-foss-2017b.eb
Labels: new

#5874 {bio}[foss/2017a] methylpy v1.1.9, cutadapt v1.14, SAMtools v1.6
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.14-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/m/methylpy/methylpy-1.1.9-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.6-foss-2017a.eb
Labels: update

#5908 fix source_urls for recent versions of ABINIT
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.0.8b-foss-2016b.eb
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.0.8b-intel-2016b.eb
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.2.2-foss-2016b.eb
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.2.2-intel-2016b.eb
Labels: bug fix

#5825 {math,vis}[foss/2017b] faceswap v20180212, Keras v2.1.2
  easybuild/easyconfigs/f/faceswap/faceswap-20180212-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/k/Keras/Keras-2.1.2-foss-2017b-Python-3.6.3.eb
Labels: new, update

#5854 {bio}[foss/2017a] RNAcode v0.3
  easybuild/easyconfigs/r/RNAcode/RNAcode-0.3-foss-2017a.eb
Labels: new

#5909 Add Tkinter sanity check to ASE (intel toolchain, take 2).
  easybuild/easyconfigs/a/ASE/ASE-3.11.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/a/ASE/ASE-3.13.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/a/ASE/ASE-3.15.0-intel-2017b-Python-2.7.14.eb
Labels: bug fix, enhancement

#5905 {lib}[intel/2017b] igraph v0.7.1, python-igraph 0.7.1.post6, PyCairo 1.16.2 w/ Python 2.7.14
  easybuild/easyconfigs/i/igraph/igraph-0.7.1-intel-2017b.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.16.2-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.7.1.post6-intel-2017b-Python-2.7.14.eb
Labels: new, update

#5915 add patch for recent GDAL easyconfigs using intel toolchain to fix icc get stuck on compiling ceos.c
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.2-intel-2017b-Python-2.7.14-HDF5-1.8.19.eb
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.2-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.2_O1-ceos.patch
Labels: bug fix

#5877 {math}[intel/2017b] gbs2ploidy v1.0, rjags v4-6, JAGS v4.3.0 w/ R 3.4.3
  easybuild/easyconfigs/g/gbs2ploidy/gbs2ploidy-1.0-intel-2017b-R-3.4.3.eb
  easybuild/easyconfigs/j/JAGS/JAGS-4.3.0-intel-2017b.eb
  easybuild/easyconfigs/r/rjags/rjags-4-6-intel-2017b-R-3.4.3.eb
Labels: new, update

#5910 {lib}[intel/2017b] TensorFlow v1.5.0 w/ Python 3.6.3 (built from source)
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0_icc-fixes.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.5.0_remove-msse-hardcoding.patch
Labels: update

#5881 {data,geo}[intel/2017b] GMT v5.4.3, GDAL v2.2.3
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/g/GMT/GMT-5.4.3-intel-2017b.eb
Labels: update

#5907 {tools}[intel/2017b] networkx v1.11 + v2.1 w/ Python 2.7.14
  easybuild/easyconfigs/n/networkx/networkx-1.11-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/n/networkx/networkx-2.1-intel-2017b-Python-2.7.14.eb
Labels: update

#5627 {bio}[intel/2017a] EvidentialGene 2018.01.01 (REVIEW)
  easybuild/easyconfigs/e/EvidentialGene/EvidentialGene-2018.01.01-intel-2017a-Perl-5.24.1.eb
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-intel-2017a.eb
Labels: new, update

#5810 {vis}[foss/2018a] X11 20180131
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.6-GCCcore-6.4.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.9-GCCcore-6.4.0.eb
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-6.4.0-Perl-5.26.1.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.34-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/X11/X11-20180131-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/X11/libxcb-1.12_indent.patch
Labels: update

#5797 [foss/2017b] Tkinter 3.6.3 - Add explicit zlib dependency
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.3-foss-2017b-Python-3.6.3.eb
Labels: bug fix

#5924 {lib}[GCCcore/6.4.0] snappy 1.1.7
  easybuild/easyconfigs/s/snappy/snappy-1.1.7-GCCcore-6.4.0.eb
Labels: update

#5927 fix source URLs & homepage in Singularity easyconfigs
  easybuild/easyconfigs/s/Singularity/Singularity-1.0-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/s/Singularity/Singularity-2.2.1-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/s/Singularity/Singularity-2.3.1-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/s/Singularity/Singularity-2.4.2-GCC-5.4.0-2.26.eb
Labels: bug fix
