Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-04, with the labels that each got.

#6071 {bio}[intel/2018a] Stacks v2.0Beta9, SAMtools v1.7
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.7-intel-2018a.eb
  easybuild/easyconfigs/s/Stacks/Stacks-2.0Beta9-intel-2018a.eb
Labels: update

#6091 {chem}[foss/2017a] propy v1.0
  easybuild/easyconfigs/p/propy/propy-1.0-foss-2017a-Python-2.7.13.eb
Labels: new

#6110 {debugger}[intel/2018a] Valgrind v3.13.0
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.13.0-intel-2018a.eb
Labels: update

#6105 {tools}[foss/2018a] amask v20171106
  easybuild/easyconfigs/a/amask/amask-20171106-foss-2018a.eb
Labels: new

#6117 {bio}[intel/2018a] SAMtools v1.8
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.8-intel-2018a.eb
Labels: update

#6115 {math}[goolf/1.5.16, intel/2018a] SCOTCH 6.0.4 (REVIEW)
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.4-goolf-1.5.16.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.4-intel-2018a.eb
Labels: update

#6118 fix checksums for R extensions that were updated in place in easyconfigs for R versions 3.4.3 & 3.4.4
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: bug fix

#6083 {lang}[intel/2018a] R v3.4.4
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2018a.eb
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
Labels: update

#6120 {data}[intel/2018a] dask v0.17.2 w/ Python 3.6.4
  easybuild/easyconfigs/d/dask/dask-0.17.2-intel-2018a-Python-3.6.4.eb
Labels: update

#6122 include pkg-config as build dep in recent R easyconfigs (required for atleast nloptr)
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: bug fix

#6104 {lib}[intel/2017b] spectral.methods v0.7.2.133 w/ R 3.4.3
  easybuild/easyconfigs/s/spectral.methods/spectral.methods-0.7.2.133-intel-2017b-R-3.4.3.eb
Labels: new

#6101 {math}[intel/2017b] ncdf4 v1.16 w/ R 3.4.3
  easybuild/easyconfigs/n/ncdf4/ncdf4-1.16-intel-2017b-R-3.4.3.eb
Labels: update

#6129 {toolchain}[dummy/dummy] goolfc v2018a
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gompic-2018a.eb
  easybuild/easyconfigs/g/gcccuda/gcccuda-2018a.eb
  easybuild/easyconfigs/g/gompic/gompic-2018a.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2018a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-gcccuda-2018a.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2018a-OpenBLAS-0.2.20.eb
Labels: update

#6126 add svd, Rssa, JBTools, RUnit, DistributionUtils and gapfill extensions for R 3.4.4
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: enhancement

#5847 {numlib}[foss/2018a, intel/2018a] Triangle v1.6 (REVIEW)
  easybuild/easyconfigs/t/Triangle/Triangle-1.6-foss-2018a.eb
  easybuild/easyconfigs/t/Triangle/Triangle-1.6-intel-2018a.eb
Labels: update

#5853 {devel}[intel/2018a] Boost v1.66.0 (REVIEW)
  easybuild/easyconfigs/b/Boost/Boost-1.66.0-intel-2018a.eb
Labels: update

#5759 {data}[foss/2016b,intel/2016b] netCDF-Fortran v4.4.1, netCDF-Fortran v4.4.1
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.1-foss-2016b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.1-intel-2016b.eb
Labels: update

#5849 {data}[intel/2018a] netCDF-C++4 v4.3.0
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.0-intel-2018a.eb
Labels: update

#5899 {chem}[intel/2018a] ABINIT v8.6.3
  easybuild/easyconfigs/a/ABINIT/ABINIT-8.6.3-intel-2018a.eb
Labels: update

#6132 add configopt --without-matlab/octave to all NLopt easyconfigs
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2015a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2015b.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2016a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2016b.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2017b.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2018a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-goolf-1.4.10.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-goolf-1.7.20.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2015a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2015b.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2016a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2016b.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2017a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2017b.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2018a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-iomkl-2018a.eb
Labels: bug fix

#5856 {vis}[intel/2018a] motif v2.3.8
  easybuild/easyconfigs/m/motif/motif-2.3.8-intel-2018a.eb
Labels: update

#6147 fix checksum for TensorFlow 1.7.0 after sneaky re-release
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-foss-2018a-Python-3.6.4.eb
Labels: bug fix

#6145 {data}[intel/2017b] SALib v1.1.3
  easybuild/easyconfigs/s/SALib/SALib-1.1.3-intel-2017b-Python-2.7.14.eb
Labels: new

#6136 Add missing extensions to Bioconductor
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.6-intel-2017b-R-3.4.3.eb
Labels: enhancement

#6149 {lang}[dummy/dummy] Anaconda2 v5.1.0
  easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.1.0.eb
Labels: update

#6141 {bio}[foss/2018a] Biopython v1.71 w/ Python 3.6.4
  easybuild/easyconfigs/b/Biopython/Biopython-1.71-foss-2018a-Python-3.6.4.eb
Labels: update

#6143 {toolchain} - gmpich 2017.08
  easybuild/easyconfigs/g/gmpich/gmpich-2017.08.eb
Labels: update

#6156 {tools}[foss/2018b] imbalanced-learn 0.3.3 (imblearn) w/Python 3.6.4
  easybuild/easyconfigs/i/imbalanced-learn/imbalanced-learn-0.3.3-foss-2018a-Python-3.6.4.eb
Labels: update

#6150 {bio}[foss/2018a] Augustus 3.3 and dependencies
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3-foss-2018a.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3_bamtools_includepath.patch
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3_no_symlinks_install.patch
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-foss-2018a.eb
  easybuild/easyconfigs/l/lpsolve/lpsolve-5.5.2.5-foss-2018a.eb
Labels: update

#6158 {bio}[intel/2018a] Bowtie v1.2.2, Bowtie2 v2.3.4.1, tbb v2018_U3
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.2.2-intel-2018a.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.4.1-intel-2018a.eb
  easybuild/easyconfigs/t/tbb/tbb-2018_U3-GCCcore-6.4.0.eb
Labels: update

#6159 {bio}[intel/2018a] R-bundle-Bioconductor v3.6 w/ R 3.4.4 (+ dep)
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-intel-2018a.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.6-intel-2018a-R-3.4.4.eb
Labels: update

#6157 {vis}[intel/2018a] FFmpeg v3.4.2
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4.2-intel-2018a.eb
Labels: update

#6160 {bio}[intel/2018a] Trinity v2.6.6
  easybuild/easyconfigs/t/Trinity/Trinity-2.6.6-intel-2018a.eb
  easybuild/easyconfigs/t/Trinity/Trinity-2.6.6_icpc-openmp.patch
Labels: update

#6155 {math}[intel/2017b] Keras v2.1.3
  easybuild/easyconfigs/k/Keras/Keras-2.1.3-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/t/Theano/Theano-1.0.1-intel-2017b-Python-3.6.3.eb
Labels: update

#6163 {bio}[foss/2018a] Stacks v2.0Beta10a, SAMtools v1.7
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.7-foss-2018a.eb
  easybuild/easyconfigs/s/Stacks/Stacks-2.0Beta10a-foss-2018a.eb
Labels: update

#6162 add xlrd extension to Python
  easybuild/easyconfigs/p/Python/Python-2.7.13-foss-2017a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.13-intel-2017a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2018a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-iomkl-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-goolfc-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2018.01.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2017a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-golf-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
Labels: enhancement

#6153 {toolchain} GCC 7.3.0 + binutils 2.30
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-7.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/GCC/GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-7.3.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.3.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-7.3.0.eb
Labels: update

#6170 also consider lib64 in sanity_check_paths for Bison 3.0.4
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCC-4.9.2-binutils-2.25.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCC-4.9.2.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCC-4.9.3-binutils-2.25.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCC-4.9.3.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCC-5.1.0-binutils-2.25.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-4.9.2.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-4.9.3.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-4.9.4.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-5.3.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-5.4.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-5.5.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-6.1.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-6.2.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-6.3.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-7.1.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-7.2.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-system.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-foss-2015a.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-foss-2015b.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-foss-2016a.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-foss-2016b.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-gimkl-2.11.5.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-gimkl-2017a.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-intel-2015a.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-intel-2015b.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-intel-2016.02-GCC-4.9.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-intel-2016a.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-intel-2016b.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-iomkl-2016.07.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-iomkl-2016.09-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.4.eb
Labels: bug fix

#6167 {lang}[GCCcore/6.4.0] Nim v0.18.0
  easybuild/easyconfigs/n/Nim/Nim-0.18.0-GCCcore-6.4.0.eb
Labels: new

#6168 {bio}[intel/2018a] HTSlib v1.8
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.8-intel-2018a.eb
Labels: update

#6169 {bio}[intel/2018a] mosdepth v0.2.2
  easybuild/easyconfigs/m/mosdepth/mosdepth-0.2.2-intel-2018a.eb
Labels: new

#6176 {bio}[GCCcore/6.4.0] BEDTools v2.27.1
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.27.1-GCCcore-6.4.0.eb
Labels: update

#6085 {lang}[foss/2018a] Mono v5.10.0.160
  easybuild/easyconfigs/m/Mono/Mono-5.10.0.160-foss-2018a.eb
Labels: update

#6184 {lib}[GCCcore/6.4.0] libyaml v0.1.6
  easybuild/easyconfigs/l/libyaml/libyaml-0.1.6-GCCcore-6.4.0.eb
Labels: update

#6183 {lib}[GCCcore/6.4.0] libsodium v1.0.12
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.12-GCCcore-6.4.0.eb
Labels: update

#6186 {devel}[GCCcore/6.4.0] ncurses v6.1
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-6.4.0.eb
Labels: update

#6188 {vis}[GCCcore/6.4.0] x264 v20180325
  easybuild/easyconfigs/x/x264/x264-20180325-GCCcore-6.4.0.eb
Labels: update

#6189 {vis}[GCCcore/6.4.0] x265 v2.7
  easybuild/easyconfigs/x/x265/x265-2.7-GCCcore-6.4.0.eb
Labels: update

#6181 {lang}[GCCcore/6.4.0] FriBidi v1.0.2
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.2-GCCcore-6.4.0.eb
Labels: update

#6198 {tools}[intel/2018a] distributed v1.21.6 w/ Python 3.6.4
  easybuild/easyconfigs/d/distributed/distributed-1.21.6-intel-2018a-Python-3.6.4.eb
Labels: update

#6056 {bio} [Anaconda3] Roary 3.12
  easybuild/easyconfigs/r/Roary/Roary-3.12.0.eb
Labels: new

#6139 {bio} [dummy] tbl2asn
  easybuild/easyconfigs/t/tbl2asn/tbl2asn-20180227-linux64.eb
Labels: new

#6193 {bio}[dummy/] supernova v2.0.1
  easybuild/easyconfigs/s/supernova/supernova-2.0.1.eb
Labels: new

#6130 remove Intel-specific workaround for 'undefined symbol: __stack_chk_guard' issue from Python 3.6.4 foss/2018a easyconfig
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb
Labels: bug fix

#6208 don't use libyaml built with dummy as dep for PyYAML
  easybuild/easyconfigs/l/libyaml/libyaml-0.1.7-GCCcore-6.3.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12.eb
Labels: bug fix

#6216 add missing pkg-config build dep in recent GObject-Introspection, GLib & cairo easyconfigs
  easybuild/easyconfigs/c/cairo/cairo-1.14.10-GCCcore-6.3.0.eb
  easybuild/easyconfigs/c/cairo/cairo-1.14.10-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/cairo/cairo-1.14.10-intel-2017b.eb
  easybuild/easyconfigs/c/cairo/cairo-1.14.12-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/cairo/cairo-1.14.8-intel-2017a.eb
  easybuild/easyconfigs/g/GLib/GLib-2.52.0-foss-2017a.eb
  easybuild/easyconfigs/g/GLib/GLib-2.52.0-intel-2017a.eb
  easybuild/easyconfigs/g/GLib/GLib-2.53.5-GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.53.5-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.54.2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.54.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.52.0-intel-2017a.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.53.5-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.53.5-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.53.5-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.53.5-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.54.1-foss-2018a-Python-2.7.14.eb
Labels: bug fix

#6222 {data}[intel/2018a] Rtree v0.8.3 w/ Python 2.7.14 + libspatialindex v1.8.5
  easybuild/easyconfigs/l/libspatialindex/libspatialindex-1.8.5-intel-2018a.eb
  easybuild/easyconfigs/r/Rtree/Rtree-0.8.3-intel-2018a-Python-2.7.14.eb
Labels: new, update

#6220 {vis}[foss/2018a,intel/2018a] FFmpeg v4.0
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.0-foss-2018a.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.0-intel-2018a.eb
Labels: update

#6172 {tools}[foss/2018a] SimpleITK 1.1.0 w/Python-3.6.4 (REVIEW)
  easybuild/easyconfigs/g/gtest/gtest-1.8.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/s/SimpleITK/SimpleITK-1.1.0-foss-2018a-Python-3.6.4.eb
Labels: new, update

#6224 {vis}[GCCcore/6.4.0] fontconfig v2.13.0
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.0-GCCcore-6.4.0.eb
Labels: update

#6182 {lib}[GCCcore/6.4.0] libpthread-stubs v0.3
  easybuild/easyconfigs/l/libpthread-stubs/libpthread-stubs-0.3-GCCcore-6.4.0.eb
Labels: update

#6185 {devel}[GCCcore/6.4.0] likwid v4.2.0
  easybuild/easyconfigs/l/likwid/likwid-4.2.0-GCCcore-6.4.0.eb
Labels: update

#6187 {numlib}[GCCcore/6.4.0] qrupdate v1.1.2
  easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCCcore-6.4.0.eb
Labels: update

#6211 {devel}[GCCcore/6.4.0] SQLite v3.23.0
  easybuild/easyconfigs/s/SQLite/SQLite-3.23.0-GCCcore-6.4.0.eb
Labels: update

#6191 {lib}[GCCcore/6.4.0] libxml2 v2.9.8
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-GCCcore-6.4.0.eb
Labels: update

#6218 {bio} [dummy] SMRT-Link-5.1.0.26412-cli-tools-only
  easybuild/easyconfigs/s/SMRT-Link/SMRT-Link-5.1.0.26412-cli-tools-only.eb
Labels: new

#6219 use $CFLAGS rather than hardcoding compiler flags in ARAGORN easyconfig file
  easybuild/easyconfigs/a/ARAGORN/ARAGORN-1.2.38-foss-2016b.eb
Labels: bug fix

#5901 {devel}[intel/2017b] Caffe v1.0
  easybuild/easyconfigs/c/Caffe/Caffe-1.0-intel-2017b-CUDA-9.1.85-Python-2.7.14.eb
Labels: update

#5403 {chem}[intel/2017b] Multiwfn v3.4.1
  easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.4.1-intel-2017b.eb
Labels: new

#6072 {bio}[foss/2018a] BEDOPS v2.4.32
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.32-foss-2018a.eb
Labels: update

#6073 {bio}[intel/2018a] BEDOPS v2.4.32
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.32-intel-2018a.eb
Labels: update

#6108 {devel}[dummy/dummy] Spack v0.11.2
  easybuild/easyconfigs/s/Spack/Spack-0.11.2.eb
Labels: update

#5912 {bio}[foss/2016a] TEToolkit v1.5.1 w/ Python 2.7.11
  easybuild/easyconfigs/t/TEToolkit/TEToolkit-1.5.1-foss-2016a-Python-2.7.11.eb
Labels: new

#6228 add --without-ada configure option in recent ncurses easyconfigs
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-4.9.3.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-5.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-5.4.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016.04.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016a.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016b.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-gimkl-2017a.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-goolf-1.4.10.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016.02-GCC-4.9.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016a.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016b.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-iomkl-2016.07.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0-iomkl-2016.09-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-7.2.0.eb
Labels: bug fix

#6226 add missing XML-LibXML dependency in recent BioPerl easyconfigs
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.0-foss-2016b-Perl-5.24.0.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.1-intel-2016b-Perl-5.24.0.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.1-intel-2017a-Perl-5.24.1.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.2-intel-2017b-Perl-5.26.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-foss-2016b-Perl-5.24.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-intel-2016b-Perl-5.24.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-intel-2017a-Perl-5.24.1.eb
Labels: bug fix

#6225 don't include (ancient version of) Time::HiRes as Perl extension, since it's a core Perl module
  easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb
  easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.22.1-intel-2016a.eb
  easybuild/easyconfigs/p/Perl/Perl-5.22.2-goolf-1.7.20.eb
  easybuild/easyconfigs/p/Perl/Perl-5.22.2-intel-2016a.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-4.9.3.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-5.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.0-foss-2016b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.0-intel-2016b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.1-foss-2017a.eb
  easybuild/easyconfigs/p/Perl/Perl-5.24.1-intel-2017a.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-foss-2017b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2017b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.00.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.01.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
Labels: bug fix

#6154 {math}[foss/2018a] magma v2.3.0
  easybuild/easyconfigs/m/magma/magma-2.3.0-fix-makefile.patch
  easybuild/easyconfigs/m/magma/magma-2.3.0-foss-2018a-CUDA-9.1.85.eb
Labels: update

#6175 {bio}[intel/2016b] EasyQC v9.2
  easybuild/easyconfigs/e/EasyQC/EasyQC-9.2-intel-2016b-R-3.3.1.eb
Labels: new

#6230 add patch for snaphu to fix segmentation fault due to use of short integer
  easybuild/easyconfigs/s/snaphu/snaphu-1.4.2-GCCcore-6.3.0.eb
  easybuild/easyconfigs/s/snaphu/snaphu-1.4.2-intel-2016b.eb
  easybuild/easyconfigs/s/snaphu/snaphu-1.4.2-intel-2017a.eb
  easybuild/easyconfigs/s/snaphu/snaphu-1.4.2_fix-short-long.patch
Labels: bug fix

#6231 {geo}[foss/2018a] Doris v4.04beta4
  easybuild/easyconfigs/d/Doris/Doris-4.04beta4-foss-2018a.eb
  easybuild/easyconfigs/d/Doris/Doris-4.04beta4_fix-segfault.patch
  easybuild/easyconfigs/d/Doris/Doris-4.04beta4_fix-toupper.patch
Labels: update

#5770 {tools}[foss/2017b] udocker 1.1.1 w/ Python 2.7.14
  easybuild/easyconfigs/u/udocker/udocker-1.1.1-foss-2017b-Python-2.7.14.eb
Labels: new

#6089 add patch for Tensorflow 1.6 & 1.7 to include missing -lrt link flag (needed in CentOS6)
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_lrt-flag.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-foss-2018a-Python-3.6.4.eb
Labels: bug fix

#6232 bump version to 3.6.0 & update release notes
  RELEASE_NOTES
  setup.py
Labels: update

#6240 sync with master + bump version to v3.6.1dev
  RELEASE_NOTES
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_lrt-flag.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-foss-2018a-Python-3.6.4.eb
  setup.py
Labels: update

#6241 {tools}[dummy/dummy] EasyBuild v3.6.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.6.0.eb
Labels: update

#6001 {phys}[intel/2018a] BerkeleyGW v1.2.0
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-1.2.0-intel-2018a.eb
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-1.2.0_fix_intent.patch
Labels: update

#6243 libdrm: add `pkg-config` as build dependency
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.88-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.91-GCCcore-6.4.0.eb
Labels: bug fix

#6237 {tools}[foss/2018a] ZeroMQ 4.2.5, PyZMQ 17.0.0
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.16-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/PyZMQ/PyZMQ-17.0.0-foss-2018a-Python-2.7.14-zmq4.eb
  easybuild/easyconfigs/p/PyZMQ/PyZMQ-17.0.0-foss-2018a-Python-3.6.4-zmq4.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.32-GCCcore-6.4.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.5-foss-2018a.eb
Labels: update

#6244 add pkg-config build dep to most recent libdrm easyconfigs
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-GCCcore-5.4.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-foss-2016b.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-intel-2016b.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.76-GCCcore-6.3.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.76-intel-2017a.eb
Labels: bug fix

#6239 {bio}[foss/2018a,intel/2018a] Stacks v2.0
  easybuild/easyconfigs/s/Stacks/Stacks-2.0-foss-2018a.eb
  easybuild/easyconfigs/s/Stacks/Stacks-2.0-intel-2018a.eb
Labels: update

#6235 {tools}[intel/2018a] ecCodes v2.7.3
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.7.3-intel-2018a.eb
Labels: new

#6234 consistently specify 'intel-mkl' component in recent Intel MKL easyconfigs
  easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-pompi-2016.04.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.0.098-iimpi-2017.00-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.1.132-gimpi-2017a.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iimpi-2017.01-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iimpi-2017a.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iompi-2017.01.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iompi-2017a.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.2.174-iimpi-2017.02-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.3.196-gompi-2017b.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.3.196-iimpi-2017b.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.3.196-iompi-2017b.eb
  easybuild/easyconfigs/i/imkl/imkl-2017.4.239-iimpi-2017.09.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.0.128-iimpi-2018.00.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iimpi-2018.01.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iimpi-2018a.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iompi-2018a.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.2.199-iimpi-2018.02.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.2.199-iompi-2018.02.eb
Labels: bug fix

#6242 {vis}[intel/2018a] Nipype v1.0.2, NiBabel v2.2.1 w/ Python 3.6.4
  easybuild/easyconfigs/n/NiBabel/NiBabel-2.2.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/Nipype/Nipype-1.0.2-intel-2018a-Python-3.6.4.eb
Labels: update

#6247 {tools}[dummy/] Pandoc v2.1.3
  easybuild/easyconfigs/p/Pandoc/Pandoc-2.1.3.eb
Labels: new

#6248 {bio}[GCCcore 6.4.0] MCL 14.137 /w Perl 5.26.1 (REVIEW)
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-6.4.0-Perl-5.26.1.eb
Labels: update

#5664 {numlib}[foss/2017b] PETSc v3.8.3 download deps
  easybuild/easyconfigs/p/PETSc/PETSc-3.8.3-foss-2017b-downloaded-deps.eb
Labels: update

#5763 {bio}[foss/2018a] GROMACS v2018
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018-foss-2018a.eb
Labels: update

#6084 {lang}[foss/2018a] Ruby v2.5.0
  easybuild/easyconfigs/r/Ruby/Ruby-2.5.0-foss-2018a.eb
Labels: update

#6015 {bio}[foss/2018a] BLAST+ v2.7.1 + Boost v1.63
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1_boost_backport.patch
Labels: update

#6254 fix source spec for networkx 2.1 extension in scikit-image easyconfig
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb
Labels: bug fix

#5929 {bio}[intel/2017a] KmerGenie v1.7044
  easybuild/easyconfigs/k/KmerGenie/KmerGenie-1.7044-intel-2017a.eb
Labels: new

#6227 {bio}[foss/2017a] HOME v0.9
  easybuild/easyconfigs/h/HOME/HOME-0.9-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/h/HOME/HOME-0.9_setup.patch
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.16.1-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.6.1-foss-2017a-Python-2.7.13.eb
Labels: new

#6019 {vis}[foss/2018a] SIMPLE v2.5
  easybuild/easyconfigs/s/SIMPLE/SIMPLE-2.5-foss-2018a.eb
Labels: new

#6251 fix installation of Libint 2.4.2 by building with -std=c++11
  easybuild/easyconfigs/l/Libint/Libint-2.4.2-intel-2018a.eb
Labels: bug fix
