Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-03, with the labels that each got.

#5933 {bio}[intel/2017b] InterProScan v5.27-66.0
  easybuild/easyconfigs/i/InterProScan/InterProScan-5.27-66.0-intel-2017b.eb
Labels: update

#5940 temporarily disable test suite runs for environment modules
  .travis.yml
Labels: change

#5937 bump version to 3.5.2 & update release notes
  RELEASE_NOTES
  setup.py
Labels: update

#5942 {tools}[dummy/dummy] EasyBuild v3.5.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.5.2.eb
Labels: update

#5943 sync with master + bump to 3.6.0dev
  .travis.yml
  RELEASE_NOTES
  easybuild/easyconfigs/s/Singularity/Singularity-1.0-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/s/Singularity/Singularity-2.2.1-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/s/Singularity/Singularity-2.3.1-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/s/Singularity/Singularity-2.4.2-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017b-Python-3.6.3.eb
  setup.py
Labels: update

#5944 re-enable testing against environment modules, bump Lmod to 7.7.16
  .travis.yml
Labels: change

#5948 {bio}[GCC/5.4.0-2.26] SOAPdenovo2 vr240
  easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r240-GCC-5.4.0-2.26.eb
Labels: update

#5945 add missing --enable-ld-version-script configure option for LibTIFF 4.0.9 built with GCCcore/6.4.0
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-GCCcore-6.4.0.eb
Labels: bug fix

#5951 {lib}[foss/2018a] TensorFlow v1.6.0 w/ Python 3.6.4 + Bazel v0.11.0
  easybuild/easyconfigs/b/Bazel/Bazel-0.11.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_remove-msse-hardcoding.patch
  easybuild/easyconfigs/w/wheel/wheel-0.30.0-foss-2018a-Python-3.6.4.eb
Labels: update

#5957 Perl: add Math::CDF perl module
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-foss-2017b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2017b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.00.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.01.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
Labels: enhancement

#5949 hard disable UCX support in recent OpenMPI versions, to dance around bug in OpenMPI configure script
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-gcccuda-2017.01.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017.02.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
Labels: bug fix

#5953 add cghFLasso extension to R 3.4.3 easyconfigs
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
Labels: enhancement

#5950 {numlib}[intel/2018a] FFTW v3.3.7
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-intel-2018a.eb
Labels: update

#5959 {math}[intel/2018a] Gurobi v7.5.2 w/ Python 3.6.3
  easybuild/easyconfigs/g/Gurobi/Gurobi-7.5.2-intel-2018a-Python-3.6.4.eb
Labels: update

#5961 {tools}[dummy/] worker v1.6.8
  easybuild/easyconfigs/w/worker/worker-1.6.8-intel-2018a.eb
Labels: update

#5954 {bio}[intel/2017b] CNVkit v0.9.2, hmmlearn v0.2.0, Biopython v1.70, ...
  easybuild/easyconfigs/b/Biopython/Biopython-1.70-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CNVkit/CNVkit-0.9.2-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/h/hmmlearn/hmmlearn-0.2.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pillow/Pillow-5.0.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2017b-Python-2.7.14.eb
Labels: new, update

#5743 {vis}[foss/2018a] matplotlib 2.1.2 w/ Python 2.7.14 + 3.6.4
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.8-foss-2018a.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.14-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.4-foss-2018a-Python-3.6.4.eb
Labels: update

#5965 bump version to 3.5.3 & update release notes
  RELEASE_NOTES
  setup.py
Labels: update

#5966 release EasyBuild v3.5.3
  .travis.yml
  RELEASE_NOTES
  easybuild/easyconfigs/b/Bazel/Bazel-0.11.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/b/Biopython/Biopython-1.70-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CNVkit/CNVkit-0.9.2-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.5.2.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-intel-2018a.eb
  easybuild/easyconfigs/g/Gurobi/Gurobi-7.5.2-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/h/hmmlearn/hmmlearn-0.2.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/i/InterProScan/InterProScan-5.27-66.0-intel-2017b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-gcccuda-2017.01.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017.02.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-foss-2017b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2017b.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.00.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.01.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
  easybuild/easyconfigs/p/Pillow/Pillow-5.0.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
  easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r240-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_remove-msse-hardcoding.patch
  easybuild/easyconfigs/t/Tk/Tk-8.6.8-foss-2018a.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.14-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.4-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/w/wheel/wheel-0.30.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/w/worker/worker-1.6.8-intel-2018a.eb
  setup.py
Labels: update

#5968 {tools}[dummy/dummy] EasyBuild v3.5.3
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.5.3.eb
Labels: update

#5967 sync with master after EasyBuild v3.5.3 release
  RELEASE_NOTES
Labels: update

#5960 {vis}[iomkl/2018a] Mesa 17.3.6 + libGLU 9.0.0 (+ deps)
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-iomkl-2018a.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.91-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-iomkl-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-iomkl-2018a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6_fix-strip-llvm-flags.patch
  easybuild/easyconfigs/n/nettle/nettle-3.4-iomkl-2018a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-iomkl-2018a.eb
Labels: update

#5921 {bio}[foss/2017b] SPAdes v3.11.1
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.11.1-foss-2017b.eb
Labels: update

#5963 {lib}[intel/2017b] psutil v5.4.3 for Python 2.7.14
  easybuild/easyconfigs/p/psutil/psutil-5.4.3-intel-2017b-Python-2.7.14.eb
Labels: update

#5972 {bio}[intel/2017b] CODEX2 v20180227 + required Bioncoductor extensions w/ R 3.4.3
  easybuild/easyconfigs/c/CODEX2/CODEX2-20180227-intel-2017b-R-3.4.3.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.6-intel-2017b-R-3.4.3.eb
Labels: enhancement, new

#5928 {bio}[intel/2017b] Stacks v2.0Beta8c
  easybuild/easyconfigs/s/Stacks/Stacks-2.0Beta8c-intel-2017b.eb
Labels: update

#5973 {vis}[foss/2018a,intel/2018a] Mesa v17.3.6
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-foss-2018a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-intel-2018a.eb
  easybuild/easyconfigs/n/nettle/nettle-3.4-foss-2018a.eb
  easybuild/easyconfigs/n/nettle/nettle-3.4-intel-2018a.eb
Labels: update

#5977 {data}[foss/2018a,intel/2018a] h5py v2.7.1 w/ Python 3.6.4
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-intel-2018a-Python-3.6.4.eb
Labels: update

#5984 {tools}[dummy/dummy] Inspector v2018_update1
  easybuild/easyconfigs/i/Inspector/Inspector-2018_update1.eb
Labels: update

#5985 {perf}[dummy/dummy] Advisor v2018_update1
  easybuild/easyconfigs/a/Advisor/Advisor-2018_update1.eb
Labels: update

#5986 {tools}[dummy/dummy] itac v2018.1.017
  easybuild/easyconfigs/i/itac/itac-2018.1.017.eb
Labels: update

#5979 {vis}[GCCcore/6.4.0] cairo v1.14.12, GLib v2.54.3 + deps
  easybuild/easyconfigs/c/cairo/cairo-1.14.12-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.54.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0-libxml2-2.9.7.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.31.1-GCCcore-6.4.0.eb
Labels: update

#5939 {phys}[intel/2017b] FDS v6.6.0
  easybuild/easyconfigs/f/FDS/FDS-6.6.0-intel-2017b.eb
  easybuild/easyconfigs/f/FDS/FDS-6.6.0_fix-version.patch
Labels: update

#5962 {lang}[intel/2017b] numba v0.37.0 w/ Python 2.7.14
  easybuild/easyconfigs/n/numba/llvmlite-0.22.0_fix-ffi-Makefile.patch
  easybuild/easyconfigs/n/numba/numba-0.37.0-intel-2017b-Python-2.7.14.eb
Labels: update

#5991 fix moduleclass & add custom sanity_check_paths in gettext easyconfigs
  easybuild/easyconfigs/g/gettext/gettext-0.18.2-foss-2015b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.18.2-goolf-1.4.10.eb
  easybuild/easyconfigs/g/gettext/gettext-0.18.2-goolf-1.5.14.eb
  easybuild/easyconfigs/g/gettext/gettext-0.18.2-ictce-5.2.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.18.2-ictce-5.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.18.2.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.2-goolf-1.5.14.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.2-goolf-1.7.20.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.2-intel-2014.06.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.2-intel-2014b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.2-intel-2015a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.2-intel-2015b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.4-GCC-4.9.2.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.4-foss-2015a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.4-intel-2015a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.4.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.6-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.6-foss-2016a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.6-gimkl-2.11.5.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.6-intel-2015b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.6-intel-2016a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.6.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.7-foss-2015b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.7-foss-2016a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.7-intel-2016a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.7.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-GCCcore-4.9.3.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-GCCcore-5.4.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2015a.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016.04.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-intel-2016b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0-libxml2-2.9.7.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.eb
Labels: bug fix, enhancement

#5988 {lang,lib}[GCCcore/6.4.0] libjpeg-turbo v1.5.3, NASM v2.13.03
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.5.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.13.03-GCCcore-6.4.0.eb
Labels: update

#5987 {devel}[foss/2018a] GObject-Introspection v1.54.1
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.54.1-foss-2018a-Python-2.7.14.eb
Labels: update

#5981 {devel,vis}[intel/2018a] Qt5 v5.10.1, libGLU v9.0.0
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2018a.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-intel-2018a.eb
Labels: update

#5964 {tools}[intel/2017b] coverage v4.5.1 w/ Python 2.7.14
  easybuild/easyconfigs/c/coverage/coverage-4.5.1-intel-2017b-Python-2.7.14.eb
Labels: new

#5749 {vis}[foss/2018a] MIGRATE-N 4.2.14
  easybuild/easyconfigs/m/MIGRATE-N/MIGRATE-N-4.2.14-foss-2018a.eb
  easybuild/easyconfigs/m/MIGRATE-N/migrate-4.2.14_install.patch
  easybuild/easyconfigs/m/MIGRATE-N/migrate-4.2.14_xlocale.patch
Labels: update

#5958 {bio}[foss/2018a] MaSuRCA v3.2.4
  easybuild/easyconfigs/m/MaSuRCA/MaSuRCA-3.2.4-foss-2018a.eb
Labels: update

#5975 {tools}[intel/2017b] XCfun v20180122
  easybuild/easyconfigs/x/XCfun/XCfun-20180122-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/x/XCfun/XCfun-20180122-shared_library-intel.patch
Labels: new

#5980 {devel,vis}[foss/2018a] Qt5 v5.10.1, libGLU v9.0.0
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2018a.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018a.eb
Labels: update

#5994 bump hwloc dep for OpenMPI 2.1.2 that is part of iomkl/2018a to v1.11.8
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
Labels: change

#5982 {tools,vis}[foss/2018a] GraphicsMagick v1.3.28, Ghostscript v9.22
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.22-GCCcore-6.4.0-cairo-1.14.12.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.28-foss-2018a.eb
Labels: update

#5993 use gettext 0.19.8.1 on top of libxml2 2.9.7 as dep for git built with foss/2018a
  easybuild/easyconfigs/g/git/git-2.16.1-foss-2018a.eb
Labels: change

#5920 {bio}[intel/2017b] Oases v0.2.08 -kmer_101
  easybuild/easyconfigs/o/Oases/Oases-0.2.08-intel-2017b-kmer_101.eb
Labels: update

#5997 add custom sanity_check_paths for GraphicsMagick consistently
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.21-intel-2015b.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.23-foss-2016a.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.23-intel-2016a.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.25-intel-2016b.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.25-intel-2017a.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.28-foss-2018a.eb
Labels: enhancement

#5998 add custom sanity_check_paths to recent Ghostscript easyconfigs
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.20-foss-2016b.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.20-intel-2016b.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.21-intel-2017a.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.22-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.22-foss-2017b.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.22-intel-2017b.eb
Labels: enhancement

#5970 add test to ensure there's only one variant for each dependency in dep graph of easyconfigs using particular toolchains (REVIEW)
  test/easyconfigs/easyconfigs.py
Labels: enhancement

#5999 use latest libjpeg-turbo 1.5.3 in GraphicsMagick/Ghostscript foss/2018a easyconfigs
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.22-GCCcore-6.4.0-cairo-1.14.12.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.28-foss-2018a.eb
Labels: change

#5990 {compiler}[GCCcore/6.4.0] LLVM v6.0.0
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0-GCCcore-6.4.0.eb
Labels: update

#6000 {bio}[intel/2018a] BBMap v37.93
  easybuild/easyconfigs/b/BBMap/BBMap-37.93-intel-2018a.eb
Labels: update

#5761 {devel}[foss/2018a] SWIG 3.0.12 w/ Python 2.7.14 + 3.6.4
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018a-Python-3.6.4.eb
Labels: update

#6003 {bio}[foss/2018a] BBMap 37.93
  easybuild/easyconfigs/b/BBMap/BBMap-37.93-foss-2018a.eb
Labels: update

#6002 {bio }[foss/2018a] SPAdes 3.11.1
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.11.1-foss-2018a.eb
Labels: update

#6013 {geo}[foss/2018a] SpiceyPy v2.1.0 w/ Python 3.6.4
  easybuild/easyconfigs/s/SpiceyPy/SpiceyPy-2.1.0-foss-2018a-Python-3.6.4.eb
Labels: update

#5887 {chem}[intel/2018a] CP2K v5.1, PLUMED v2.4.0 (+ deps)
  easybuild/easyconfigs/c/CP2K/CP2K-5.1-intel-2018a.eb
  easybuild/easyconfigs/l/Libint/Libint-1.1.6-intel-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-intel-2018a.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.8.3-intel-2018a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-intel-2018a.eb
Labels: update

#5955 {vis}[foss/2018a] gnuplot v5.2.2
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.1-foss-2018a.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-foss-2018a.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.7.5-foss-2018a.eb
  easybuild/easyconfigs/l/libgd/libgd-2.2.5-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/nettle/nettle-3.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.1-foss-2018a.eb
Labels: update

#5992 Added easyconfig for ELPA-2017.11.001 with intel 2018a. Ported patch.
  easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-intel-2018a.eb
Labels: update

#6008 {math}[foss/2018a] GEOS v3.6.2 w/ Python 2.7.14
  easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-foss-2018a-Python-2.7.14.eb
Labels: update

#6012 {data}[foss/2018a,intel/2018a] netCDF v4.6.0
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.0-foss-2018a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.0-intel-2018a.eb
Labels: update

#6014 {chem}[foss/2018a] CP2K v5.1 + PLUMED v2.4.0 + deps
  easybuild/easyconfigs/c/CP2K/CP2K-5.1-foss-2018a.eb
  easybuild/easyconfigs/l/Libint/Libint-1.1.6-foss-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-foss-2018a.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.8.3-foss-2018a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-foss-2018a.eb
Labels: update

#6023 allow two dependency variants if one is for Python 2.x, other is for Python 3.x
  test/easyconfigs/easyconfigs.py
Labels: enhancement, priority:high

#5823 {vis}[foss/2018a] FFmpeg 3.4.2
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4.2-foss-2018a.eb
  easybuild/easyconfigs/x/x264/x264-20180128-GCCcore-6.4.0.eb
Labels: update

#5925 {vis}[foss/2018a] scikit-image 0.13.1 + Pillow 5.0 0 w/ Python 3.6.4
  easybuild/easyconfigs/p/Pillow/Pillow-5.0.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb
Labels: update

#6022 {data,lib,math}[foss/2018a] GDAL v2.2.3, GEOS v3.6.2, PROJ v5.0.0 w/ Python 3.6.4
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/PROJ/PROJ-5.0.0-foss-2018a.eb
Labels: update

#5438 {data}[intel/2018a] GDAL v2.2.3 w/ Python 3.6.4
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/PROJ/PROJ-5.0.0-intel-2018a.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-intel-2018a-Python-3.6.4.eb
Labels: update

#6020 {data}[foss/2018a,intel/2018a] h5py v2.7.1 w/ Python 2.7.14
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/h/h5py/h5py-2.7.1-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-intel-2018a-Python-2.7.14.eb
Labels: update

#6026 {data}[foss/2018a,intel/2018a] netCDF-Fortran v4.4.4
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-foss-2018a.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-intel-2018a.eb
Labels: update

#6025 {chem}[foss/2018a,intel/2018a] packmol v18.013
  easybuild/easyconfigs/p/packmol/packmol-18.013-foss-2018a.eb
  easybuild/easyconfigs/p/packmol/packmol-18.013-intel-2018a.eb
Labels: update

#6021 {lib}[foss/2018a,intel/2018a] phonopy 1.12.6.66 (+ deps) w/ Python 2.7.14
  easybuild/easyconfigs/l/lxml/lxml-4.2.0-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/l/lxml/lxml-4.2.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/phonopy/phonopy-1.12.6.66-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/phonopy/phonopy-1.12.6.66-intel-2018a-Python-2.7.14.eb
Labels: update

#5902 {devel}[GCCcore-7.2.0] Doxygen v1.8.14 (with dependencies)
  easybuild/easyconfigs/c/CMake/CMake-3.10.2-GCCcore-7.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-7.2.0.eb
Labels: update

#6024 use non-interactive plotting backend by default for matplotlib 2.1.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-3.6.4.eb
Labels: change

#6034 {chem}[foss/2018a,intel/2018a] phono3py v1.12.7.55
  easybuild/easyconfigs/p/phono3py/phono3py-1.12.7.55-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/phono3py/phono3py-1.12.7.55-intel-2018a-Python-2.7.14.eb
Labels: update

#6031 {numlib}[foss-2018a] Armadillo 8.400.0 (REVIEW)
  easybuild/easyconfigs/a/Armadillo/Armadillo-8.400.0-foss-2018a.eb
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.5.0-foss-2018a.eb
Labels: update

#6035 {bio}[foss/2018a] FRANz 2.0.0
  easybuild/easyconfigs/f/FRANz/FRANz-2.0.0-foss-2018a.eb
Labels: new

#6004 {numlib}[foss/2018a] NLopt v2.4.2
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2018a.eb
Labels: update

#6040 {bio,lib}[intel/2018a] biobambam2 v2.0.87, libmaus2 v2.0.453
  easybuild/easyconfigs/b/biobambam2/biobambam2-2.0.87-intel-2018a.eb
  easybuild/easyconfigs/l/libmaus2/libmaus2-2.0.453-intel-2018a.eb
Labels: new

#5827 {vis}[foss/2018a] GTK+ 2.24.32
  easybuild/easyconfigs/a/ATK/ATK-2.28.1-foss-2018a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018a.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-foss-2018a.eb
Labels: update

#6043 {tools}[intel/2018a] wheel v0.30.0
  easybuild/easyconfigs/w/wheel/wheel-0.30.0-intel-2018a-Python-3.6.4.eb
Labels: update

#6039 {vis}[foss/2018a] OpenCV 3.4.1 w/ Python {2.7.14, 3.6.4} (REVIEW)
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-3.6.4.eb
Labels: update

#6046 {vis}[intel-2017] gnuplot 5.2.2 (REVIEW)
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.53.5-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-intel-2017b.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.7.1-intel-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.14-intel-2017b.eb
Labels: update

#6036 {vis}[foss-2018b] Grace 5.1.25-5build1 (REVIEW)
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-5build1.patch
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2018a-5build1.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2018a.eb
Labels: new, update

#6029 {chem}[intel/2018a] AmberTools v17
  easybuild/easyconfigs/a/AmberTools/AmberTools-17-intel-2018a.eb
Labels: update

#6047 {bio}[dummy/] MiGEC v1.2.8
  easybuild/easyconfigs/m/MiGEC/MiGEC-1.2.8-Java-1.8.0_162.eb
Labels: new

#6045 {bio}[dummy/] MiXCR v2.1.9
  easybuild/easyconfigs/m/MiXCR/MiXCR-2.1.9-Java-1.8.0_162.eb
Labels: new

#6052 {bio} [foss/2016b] Abyss-2.0.2
  easybuild/easyconfigs/a/ABySS/ABySS-2.0.2-foss-2016b.eb
  easybuild/easyconfigs/s/sparsehash/sparsehash-2.0.3-foss-2016b.eb
Labels: update

#6053 {bio} [dummy] Bandage 0.8.1 static binaries
  easybuild/easyconfigs/b/Bandage/Bandage-0.8.1_Centos.eb
  easybuild/easyconfigs/b/Bandage/Bandage-0.8.1_Ubuntu.eb
Labels: new

#5785 config file for https://pre-commit.com/
  .pep8
  .pre-commit-config.yaml
Labels: enhancement

#6051 {bio} [foss/2016b] Porechop 0.2.3 w/ Python 3.5.2
  easybuild/easyconfigs/p/Porechop/Porechop-0.2.3-foss-2016b-Python-3.5.2.eb
Labels: new

#6058 don't use bare Perl as dependency for 'git' with foss/2018a, use variant with extensions
  easybuild/easyconfigs/g/git/git-2.16.1-foss-2018a.eb
Labels: change

#6033 {vis}[foss-2018a] MathGL 2.4.1 (REVIEW)
  easybuild/easyconfigs/m/MathGL/MathGL-2.4.1-foss-2018a.eb
  easybuild/easyconfigs/m/MathGL/MathGL-2.4.1_FL.patch
Labels: new, update

#6060 drop use of --disable-dlopen in (recent) OpenMPI easyconfigs due to negative performance impact
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.1-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-6.1.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.3-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.4-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-6.1.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-PGI-16.7-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-iccifort-2016.3.210-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
Labels: bug fix

#5490 {bio}[goolf/1.7.20] BamBam v1.4
  easybuild/easyconfigs/b/BamBam/BamBam-1.4-goolf-1.7.20.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.3.1-goolf-1.7.20.eb
Labels: new, update

#6065 add missing XZ dep in Python 3.6.4 easyconfigs built with */2018a toolchain
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
Labels: bug fix

#6016 {lib}[foss/2018a] TensorFlow v1.6.0 + Python-3.6.4 + CUDA-9.1.85
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_dont_expand_cuda_cudnn_path.patch
Labels: update

#6041 {lib}[intel/2018a] TensorFlow v1.6.0 w/ Python 3.6.4
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_icc-fixes.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_icc-type_casting.patch
Labels: update

#6068 {vis}[foss/2018a] VTK v8.1.0
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-foss-2018a-Python-2.7.14.eb
Labels: update

#6069 {data}[foss/2018a] ITK v4.13.0
  easybuild/easyconfigs/i/ITK/ITK-4.13.0-foss-2018a-Python-2.7.14.eb
Labels: update

#6050 {bio}[foss/2016b] Filtlong 0.2.0
  easybuild/easyconfigs/f/Filtlong/Filtlong-0.2.0-foss-2016b.eb
Labels: new

#4444 {bio}[goolf/1.7.20] LUMPY v0.2.13 + gawk v4.0.2
  easybuild/easyconfigs/g/gawk/gawk-4.0.2-goolf-1.7.20.eb
  easybuild/easyconfigs/l/LUMPY/LUMPY-0.2.13-goolf-1.7.20.eb
Labels: update

#5723 {bio}[foss/2016b] BEDOPS v2.4.30
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.30-foss-2016b.eb
Labels: update

#6063 {math}[foss/2018a] Octave v4.2.2
  easybuild/easyconfigs/o/Octave/Octave-4.2.2-foss-2018a.eb
Labels: update

#6074 {vis}[foss/2018a] elastix v4.9.0
  easybuild/easyconfigs/e/elastix/elastix-4.9.0-foss-2018a.eb
Labels: new

#5974 {lang}[iomkl/2018a] R 3.4.4 (+ deps)
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-6.4.0.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-iomkl-2018a.eb
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-iomkl-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-iomkl-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-iomkl-2018a.eb
  easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-iomkl-2018a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.0-iomkl-2018a.eb
  easybuild/easyconfigs/p/PROJ/PROJ-5.0.0-iomkl-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-iomkl-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.8-iomkl-2018a.eb
Labels: update

#6077 {toolchain} intel/2018.02
  easybuild/easyconfigs/h/HPL/HPL-2.2-intel-2018.02.eb
  easybuild/easyconfigs/i/icc/icc-2018.2.199-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2018.2.199-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/i/ifort/ifort-2018.2.199-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/i/ifort/ifort_2018.2.199_no_mpi_mic_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2018.02.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.2.199-iimpi-2018.02.eb
  easybuild/easyconfigs/i/impi/impi-2018.2.199-iccifort-2018.2.199-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/i/intel/intel-2018.02.eb
Labels: update

#6076 {phys}[intel/2018a] UDUNITS v2.2.26
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018a.eb
Labels: update

#6087 {data}[foss/2018a] scikit-learn 0.19.1
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.19.1-foss-2018a-Python-3.6.4.eb
Labels: update

#6086 {data}[foss/2018a] GDAL v2.2.3
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018a-Python-2.7.14.eb
Labels: update

#6075 {bio,lang}[dummy/,dummy/dummy] QIIME2 v2018.2, Miniconda3 v4.4.10
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.4.10.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2018.2.eb
Labels: update

#6094 {vis}[foss/2018a] VTK v8.1.0 w/ Python 3.6.4
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-foss-2018a-Python-3.6.4.eb
Labels: update

#6095 {data}[foss/2018a] ITK v4.13.0 w/ Python 3.6.4
  easybuild/easyconfigs/i/ITK/ITK-4.13.0-foss-2018a-Python-3.6.4.eb
Labels: update

#6099 add svd, Rssa, JBTools, RUnit, DistributionUtils and gapfill extensions for R 3.4.3
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
Labels: enhancement

#6102 {phys}[foss/2016b,intel/2016b] vartools v1.35
  easybuild/easyconfigs/v/vartools/vartools-1.35-foss-2016b.eb
  easybuild/easyconfigs/v/vartools/vartools-1.35-intel-2016b.eb
  easybuild/easyconfigs/v/vartools/vartools-1.35_Fix_numpy_header_path.patch
Labels: new

#6103 {bio}[foss/2017a] Biopython v1.70 w/ Python 2.7.13 (REVIEW)
  easybuild/easyconfigs/b/Biopython/Biopython-1.70-foss-2017a-Python-2.7.13.eb
Labels: update

#6093 {cae}[dummy/] ABAQUS v2018
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2018-hotfix-1806.eb
Labels: update

#6096 re-add extensions for R 3.4.4 that were overlooked
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: bug fix

#6100 {chem,devel}[intel/2018a] Libint v2.4.2 + Boost v1.66.0 w/ Ptyhon 2.7.14 as dep
  easybuild/easyconfigs/b/Boost/Boost-1.66.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/l/Libint/Libint-2.4.2-intel-2018a.eb
Labels: update
