Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-06, with the labels that each got.

#6403 {bio} [intel/2018a] PANDASeq 2.11
  easybuild/easyconfigs/p/PANDAseq/PANDAseq-2.11-intel-2018a.eb
Labels: update

#6399 {cae}[foss/2018a] OpenFOAM-5.0
  easybuild/easyconfigs/c/CGAL/CGAL-4.11.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-foss-2018a.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.4.1-foss-2018a-mpi.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.5-foss-2018a.eb
Labels: update

#6413 {bio}[foss/2018a] RELION v2.1
  easybuild/easyconfigs/r/RELION/RELION-2.1-foss-2018a-CUDA-9.1.85.eb
  easybuild/easyconfigs/r/RELION/RELION-2.1_cuda_capabilities.patch
Labels: update

#6418 {math}[foss/2018a] Theano
  easybuild/easyconfigs/t/Theano/Theano-1.0.2-foss-2018a-Python-3.6.4.eb
Labels: update

#6419 {bio}[foss/2018a] HTSlib 1.8
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.8-foss-2018a.eb
Labels: update

#6405 {tools}[foss/2018a] ANTLR 2.7.7
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-foss-2018a-Python-2.7.14.eb
Labels: update

#6425 {bio}[foss/2018a]Beast 2.5.0
  easybuild/easyconfigs/b/Beast/Beast-2.5.0-foss-2018a.eb
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.0.1-foss-2018a.eb
Labels: update

#6404 {vis}[intel/2018a] VTK v8.1.1 w/ MPI support
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-intel-2018a-Python-2.7.14-mpi.eb
Labels: update

#6433 {tools}[dummy/dummy] vsc-mympirun v4.1.4, vsc-base v2.8.0, vsc-install v0.11.1
  easybuild/easyconfigs/v/vsc-base/vsc-base-2.8.0.eb
  easybuild/easyconfigs/v/vsc-install/vsc-install-0.11.1.eb
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-4.1.4.eb
Labels: update

#6415 {tools}[foss/2018a] IPython v5.7.0
  easybuild/easyconfigs/i/IPython/IPython-5.7.0-foss-2018a-Python-2.7.14.eb
Labels: update

#6420 {devel}[foss/2018a] Boost v1.63.0
  easybuild/easyconfigs/b/Boost/Boost-1.63.0-foss-2018a-Python-2.7.14.eb
Labels: update

#6434 {tools}[GCCcore/6.4.0] Coreutils v8.29
  easybuild/easyconfigs/c/Coreutils/Coreutils-8.29-GCCcore-6.4.0.eb
Labels: update

#6435 {debugger}[foss/2018a] GDB v8.1
  easybuild/easyconfigs/g/GDB/GDB-8.1-foss-2018a-Python-2.7.14.eb
Labels: update

#6436 {tools}[dummy/dummy] vsc-mympirun v4.1.5, vsc-base v2.8.1, vsc-install v0.11.2
  easybuild/easyconfigs/v/vsc-base/vsc-base-2.8.1.eb
  easybuild/easyconfigs/v/vsc-install/vsc-install-0.11.2.eb
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-4.1.5.eb
Labels: update

#6417 {chem}[foss/2018a] Molden 5.8
  easybuild/easyconfigs/m/Molden/Molden-5.8-foss-2018a.eb
Labels: update

#6438 {lib,math}[foss/2018a] Keras v2.2.0, PyYAML v3.12
  easybuild/easyconfigs/k/Keras/Keras-2.2.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-foss-2018a-Python-3.6.4.eb
Labels: update

#6441 {vis}[foss/2018a] opencv_contrib v3.4.1
  easybuild/easyconfigs/o/opencv_contrib/opencv_contrib-3.4.1-foss-2018a-Python-3.6.4.eb
Labels: new

#6431 stop including GCCcore 6.4.0 as build dep for GCCcore 8.1.0
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0.eb
Labels: bug fix

#6423 {bio}[intel/2018a] Clustal-Omega 1.2.4 (REVIEW)
  easybuild/easyconfigs/a/argtable/argtable-2.13-intel-2018a.eb
  easybuild/easyconfigs/c/Clustal-Omega/Clustal-Omega-1.2.4-intel-2018a.eb
Labels: update

#6422 {phys}[intel/2018a] fullrmc 3.2.0 w/Python 2.7.14 (REVIEW)
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.4-intel-2018a.eb
  easybuild/easyconfigs/f/fullrmc/fullrmc-3.2.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0-Ghostscript-9.22-cairo-1.14.12.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018a-Python-2.7.14.eb
Labels: new, update

#6432 add patch for GCCcore 6.4.0 to fix compilation problems on glibc 2.26 systems
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0_fix-linux-unwind-fix-ucontext.patch
Labels: bug fix

#6421 {bio,lang,lib,vis}[foss/2018a] EMAN2 v2.21a, PyQt v4.12.1, SIP v4.19.8, ...
  easybuild/easyconfigs/e/EMAN2/EMAN2-2.21a-foss-2018a-Python-2.7.14-Boost-1.63.0.eb
  easybuild/easyconfigs/e/EMAN2/EMAN2-2.21a_fix-custom-install-prefix.patch
  easybuild/easyconfigs/f/FTGL/FTGL-2.1.3-rc5-foss-2018a.eb
  easybuild/easyconfigs/p/PyQt/PyQt-4.12.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/SIP/SIP-4.19.8-foss-2018a-Python-2.7.14.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#6444 also check for multiple dependency variants in easyconfigs using GCCcore 7.3.0 & newer
  test/easyconfigs/easyconfigs.py
Labels: change

#6429 drop '-mpi' versionsuffix for VTK 8.1.1
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-intel-2018a-Python-2.7.14.eb
Labels: change

#5918 {math}[foss/2017b] FreeFem++ v3.58
  easybuild/easyconfigs/f/FreeFem++/FreeFem++-3.58-foss-2017b-downloaded-deps.eb
Labels: new

#6376 add 'gee' extension to R 3.4.4 easyconfigs
  easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: enhancement

#6318 {bio}[intel/2018a] Kraken v1.0, Jellyfish v2.2.10, wget v1.19.4
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.2.10-intel-2018a.eb
  easybuild/easyconfigs/k/Kraken/Kraken-1.0-intel-2018a-Perl-5.26.1.eb
  easybuild/easyconfigs/k/Kraken/Kraken-1.0_CXX-CXXFLAGS.patch
  easybuild/easyconfigs/l/libidn/libidn-1.34-GCCcore-6.4.0.eb
  easybuild/easyconfigs/w/wget/wget-1.19.4-GCCcore-6.4.0.eb
Labels: update

#6449 {lib}[GCCcore/5.4.0] zstd v1.3.4
  easybuild/easyconfigs/g/gzip/gzip-1.8-GCCcore-5.4.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.8.2-GCCcore-5.4.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.3.4-GCCcore-5.4.0.eb
Labels: new

#6446 fix checksums for pkgmaker/rngtools/RWeka/RcppProgress extensions in R 3.4.4 easyconfigs
  easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: bug fix

#6448 {bio}[foss/2016a] fastStructure 1.0 w/ Python 2.7.11
  easybuild/easyconfigs/f/fastStructure/fastStructure-1.0-foss-2016a-Python-2.7.11.eb
Labels: new

#4241 fastStructure 1.0 built using the foss-2016a toolchain.
  easybuild/easyconfigs/f/fastStructure/fastStructure-1.0-foss-2016a-Python-2.7.11.eb
Labels: new

#6452 Move zstd from GCCcore to foss
  easybuild/easyconfigs/z/zstd/zstd-1.3.4-foss-2016b.eb
Labels: change

#6450 {debugger}[foss/2016b] heaptrack v1.1.0
  easybuild/easyconfigs/h/heaptrack/heaptrack-1.1.0-foss-2016b.eb
  easybuild/easyconfigs/l/libdwarf/libdwarf-20150310-GCCcore-5.4.0.eb
  easybuild/easyconfigs/l/libelf/libelf-0.8.13-GCCcore-5.4.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-foss-2016b.eb
Labels: new, update

#6458 {lang} [intel/2018a] Ruby v2.5.1
  easybuild/easyconfigs/r/Ruby/Ruby-2.5.1-intel-2018a.eb
Labels: update

#6453 {bio}[foss/2018a] angsd 0.921
  easybuild/easyconfigs/a/angsd/angsd-0.921-foss-2018a.eb
Labels: update

#6461 build hwloc 1.11.10 with -fno-tree-vectorize to avoid segfaulting lstopo on Intel Skylake
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.10-GCCcore-7.3.0.eb
Labels: bug fix

#6462 {devel}[intel/2018a] Boost v1.67.0
  easybuild/easyconfigs/b/Boost/Boost-1.67.0-intel-2018a.eb
Labels: update

#6457 Guile 1.8.8: added necessary compiler flag
  easybuild/easyconfigs/g/Guile/Guile-1.8.8-GCCcore-6.4.0.eb
Labels: bug fix

#6464 {bio}[intel/2018a] nanopolish v0.9.2
  easybuild/easyconfigs/n/nanopolish/nanopolish-0.9.2-intel-2018a.eb
Labels: new

#6468 {lib} [GCCcore/6.4.0, intel/2018a] FANN v2.2.0
  easybuild/easyconfigs/f/FANN/FANN-2.2.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/f/FANN/FANN-2.2.0-intel-2018a.eb
Labels: new

#6459 {data} [intel/2018a] PnetCDF v1.9.0
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.9.0-intel-2018a.eb
Labels: update

#6439 {lib,perf}[intel/2018a] mympingpong v0.8.0, mpi4py v3.0.0
  easybuild/easyconfigs/m/mpi4py/mpi4py-3.0.0-intel-2018a-Python-2.7.14-timed-pingpong.eb
  easybuild/easyconfigs/m/mpi4py/mpi4py-3.0.0_timed-pingpong.patch
  easybuild/easyconfigs/m/mympingpong/mympingpong-0.8.0-intel-2018a-Python-2.7.14.eb
Labels: update

#6467 {bio}[intel/2018a] poretools v0.6.0, Seaborn v0.8.1 w/ Python 2.7.14
  easybuild/easyconfigs/p/poretools/poretools-0.6.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.8.1-intel-2018a-Python-2.7.14.eb
Labels: new, update

#6476 {bio}[foss/2018a] GATK 4.0.5.1
  easybuild/easyconfigs/g/GATK/GATK-4.0.5.1-foss-2018a-Python-3.6.4.eb
Labels: update

#6042 Hint on file name differences between downloaded and expected by config
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.0.5.15-goolfc-2017b.eb
Labels: enhancement

#6477 {bio}[intel/2018a] PRC v1.5.6
  easybuild/easyconfigs/p/PRC/PRC-1.5.6-intel-2018a.eb
Labels: new

#6463 add patch for binutils 2.30 to fix assertion failure
  easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-7.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-8.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30_fix-assertion-fail-elf.patch
Labels: 2018b, bug fix

#6481 {bio}[intel/2018a] HH-suite v3.0-beta.3
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.0-beta.3-intel-2018a.eb
Labels: update

#6471 sync extensions in Python-3.6.4-iomkl-2018a.eb easyconfig with other Python 3.6.4 easyconfigs using 2018a toolchain
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
Labels: bug fix, enhancement

#6127 {math}[intel/2018a] ncdf4 v1.16 w/ R 3.4.4
  easybuild/easyconfigs/n/ncdf4/ncdf4-1.16-intel-2018a-R-3.4.4.eb
Labels: update

#6010 {vis}[foss/2018a] ImageMagick v7.0.7-26, LittleCMS v2.9
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-26-foss-2018a.eb
  easybuild/easyconfigs/l/LittleCMS/LittleCMS-2.9-foss-2018a.eb
Labels: update

#5429 {lib}[intel/2017b] libgpuarray v0.7.5 w/ Python 3.6.3
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.5-intel-2017b-Python-3.6.3.eb
Labels: new

#6440 {vis}[intel/2018a] gnuplot v5.2.2
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.1-intel-2018a.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.54.1-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-intel-2018a.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.7.5-intel-2018a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.1-intel-2018a.eb
Labels: update

#6428 skip installing of documentation in easyconfig for jemalloc 5.0.1
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.0.1-GCCcore-6.4.0.eb
Labels: bug fix

#6447 {lang}[iomkl/2018.02] Python v3.6.4, Tkinter v3.6.4, matplotlib v2.1.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-iomkl-2018.02-Python-3.6.4.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018.02.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.4-iomkl-2018.02-Python-3.6.4.eb
Labels: update

#6485 enable checking/setting of unlimited stack limit in Python 3.6.x easyconfigs using an 'intel' toolchain
  easybuild/easyconfigs/p/Python/Python-3.6.1-intel-2017a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2018.00.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2018.01.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
Labels: bug fix

#5983 {bio}[intel/2018a] MAJIQ v1.1.1, Pysam v0.14 w/ Python 3.6.4 (REVIEW)
  easybuild/easyconfigs/c/Cython/Cython-0.25.2-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/m/MAJIQ/MAJIQ-1.1.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/m/MAJIQ/numpy-1.12.0-mkl.patch
  easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2018a-Python-3.6.4.eb
Labels: new, update

#6491 bump Pysam dep for MAJIQ to 0.14.1 to fix compatibility with other 2018a easyconfigs
  easybuild/easyconfigs/m/MAJIQ/MAJIQ-1.1.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-intel-2018a-Python-3.6.4.eb
Labels: bug fix, change, update

#6478 {chem}[iomkl/2018.02] ASE v3.16.2
  easybuild/easyconfigs/a/ASE/ASE-3.16.2-iomkl-2018.02-Python-3.6.4.eb
Labels: update

#6492 Fix compilation of Python's hashlib with iomkl/2018a.
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
Labels: bug fix

#6494 {chem,lang,vis}[iomkl/2018a] ASE v3.16.2, matplotlib v2.1.2, Tkinter v3.6.4
  easybuild/easyconfigs/a/ASE/ASE-3.16.2-iomkl-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-iomkl-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.4-iomkl-2018a-Python-3.6.4.eb
Labels: update

#6469 {bio,lang}[GCCcore/6.4.0,intel/2018a] Scrappie v1.3.2, CUnit v2.1-3
  easybuild/easyconfigs/c/CUnit/CUnit-2.1-3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/s/Scrappie/Scrappie-1.3.2-intel-2018a.eb
  easybuild/easyconfigs/s/Scrappie/Scrappie-1.3.2_fix-cblas-include.patch
Labels: new

#6460 enable building of MPI libraries in VTK 8.1.0 easyconfigs
  easybuild/easyconfigs/v/VTK/VTK-8.0.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-intel-2018a-Python-2.7.14.eb
Labels: enhancement

#6495 use complete patch for unwind issue in GCCcore 6.4.0
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0_fix-linux-unwind-fix-ucontext.patch
Labels: enhancement

#6466 R 3.5.0 for iomkl 2018a
  easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/imager-0.41.1_icpc-wd308.patch
Labels: update

#6201 {vis}[intel/2018a] graphviz 0.8.2 w/ Python 3.6.4 + GraphViz 2.40.1 + deps
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-intel-2018a.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-intel-2018a.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_Qt5.patch
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_icc_vmalloc.patch
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_skip-install-data-hook.patch
  easybuild/easyconfigs/g/graphviz/graphviz-0.8.2-intel-2018a-Python-3.6.4.eb
Labels: update

#6451 {lib}[intel/2018a] phonopy v1.13.0.64 w/ Python 2.7.14
  easybuild/easyconfigs/p/phonopy/phonopy-1.13.0.64-intel-2018a-Python-2.7.14.eb
Labels: update

#6472 {lang}[GCCcore/7.3.0] Perl v5.28.0
  easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
Labels: 2018b, update

#6498 add missing libxml2 dependency for HDF5 1.10.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-foss-2018a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-intel-2018.00.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-intel-2018.01.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-intel-2018a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-iomkl-2018a.eb
Labels: bug fix

#6496 {geo}[foss/2018a] GMT v4.5.17
  easybuild/easyconfigs/g/GMT/GMT-4.5.17-foss-2018a.eb
Labels: update

#6475 {*}[GCCcore/7.3.0] X11 v20180604, Bison v3.0.5, intltool v0.51.0, XML-Parser v2.44_01 w/ Perl 5.26.2
  easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-7.3.0.eb
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-7.3.0-Perl-5.28.0.eb
  easybuild/easyconfigs/x/X11/X11-20180604-GCCcore-7.3.0.eb
  easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-7.3.0-Perl-5.28.0.eb
Labels: 2018b, update

#6502 fix changed checksum for mgcv in R 3.4.4 easyconfigs
  easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: bug fix

#6499 {cae}[intel/2018a] meshio v2.0.2 w/ Python 2.7.14 & 3.6.4
  easybuild/easyconfigs/m/meshio/meshio-2.0.2-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/meshio/meshio-2.0.2-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-intel-2018a-Python-3.6.4.eb
Labels: update

#6508 {tools}[foss/2018a] Ninja 1.8.2 , Meson 0.46.1
  easybuild/easyconfigs/m/Meson/Meson-0.46.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.8.2-foss-2018a.eb
Labels: update

#6507 {bio}[dummy/] FastQC v0.11.7
  easybuild/easyconfigs/f/FastQC/FastQC-0.11.7-Java-1.8.0_162.eb
Labels: update

#5396 {bio}[foss/2016b] fastq-tools 0.8
  easybuild/easyconfigs/f/fastq-tools/fastq-tools-0.8-foss-2016b.eb
Labels: new

#6511 {bio}[intel/2018a] minimap2 v2.11
  easybuild/easyconfigs/m/minimap2/minimap2-2.11-intel-2018a.eb
Labels: update

#6506 {bio}[intel/2018a] RSEM v1.3.1
  easybuild/easyconfigs/r/RSEM/RSEM-1.3.1-intel-2018a.eb
Labels: update

#6513 {bio}[intel/2018a] eggnog-mapper v1.0.3, Biopython v1.71
  easybuild/easyconfigs/b/Biopython/Biopython-1.71-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/e/eggnog-mapper/eggnog-mapper-1.0.3-intel-2018a-Python-2.7.14.eb
Labels: new, update

#6512 {bio}[foss/2016b] BLAT v3.5, GLIMMER v3.02b, HMMER v3.1b2, ...
  easybuild/easyconfigs/b/BLAT/BLAT-3.5-foss-2016b.eb
  easybuild/easyconfigs/g/GLIMMER/GLIMMER-3.02b-foss-2016b.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-foss-2016b.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.2-foss-2016b.eb
  easybuild/easyconfigs/s/STAR/STAR-2.5.4b-foss-2016b.eb
  easybuild/easyconfigs/t/TopHat/TopHat-2.1.1-foss-2016b.eb
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.15-foss-2016b-Perl-5.24.0.eb
Labels: update
