Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-12, with the labels that each got.

#7213 {bio}[foss/2017b] Bowtie2 v2.3.4.1
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.4.1-foss-2017b.eb
Labels: update

#7208 {chem}[intel/2017b] spglib v1.9.9
  easybuild/easyconfigs/s/spglib/spglib-1.9.9-intel-2017b.eb
Labels: update

#7211 {base}[foss/2017b] Gerris v20131206, GTS v20121130
  easybuild/easyconfigs/g/GTS/GTS-20121130-foss-2017b.eb
  easybuild/easyconfigs/g/Gerris/Gerris-20131206-foss-2017b.eb
Labels: update

#7225 {bio}[foss/2018b] SKESA v2.9.3, NGS v2.9.3, ncbi-vdb v2.9.3
  easybuild/easyconfigs/f/file/file-5.35-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NGS/NGS-2.9.3-foss-2018b-Java-1.8.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-2.9.3-foss-2018b.eb
  easybuild/easyconfigs/s/SKESA/SKESA-2.9.3-foss-2018b.eb
Labels: update

#7171 {toolchain} intel/2018.04
  easybuild/easyconfigs/h/HPL/HPL-2.2-intel-2018.04.eb
  easybuild/easyconfigs/i/icc/icc-2018.5.274-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2018.5.274-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/ifort/ifort-2018.5.274-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/ifort/ifort-2018.5.274_no_mpi_mic_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2018.04.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.4.274-iimpi-2018.04.eb
  easybuild/easyconfigs/i/impi/impi-2018.4.274-iccifort-2018.5.274-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/intel/intel-2018.04.eb
Labels: update

#7230 {numlib}[intel/2018b] FFTW v2.1.5
  easybuild/easyconfigs/f/FFTW/FFTW-2.1.5-intel-2018b.eb
Labels: update

#7235 {tools}[intel/2018b] networkx 2.2 w/Python 3.6.6 (REVIEW)
  easybuild/easyconfigs/n/networkx/networkx-2.2-intel-2018b-Python-3.6.6.eb
Labels: update

#7236 {vis}[GCCcore/7.3.0] FFmpeg v4.1, x264 v20181203, LAME v3.100, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.1-intel-2018b.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-7.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20181203-GCCcore-7.3.0.eb
  easybuild/easyconfigs/x/x265/x265-2.9-GCCcore-7.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-7.3.0.eb
Labels: update

#7212 {data}[foss/2017b] PostgreSQL v10.3
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-10.3-foss-2017b-Python-2.7.14.eb
Labels: update

#7221 {bio}[foss/2017b] BamTools v2.5.1
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-foss-2017b.eb
Labels: update

#7240 fix source_urls in CP2K easyconfigs (for official releases)
  easybuild/easyconfigs/c/CP2K/CP2K-2.4.0-goolf-1.4.10-ipi.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.4.0-goolf-1.4.10.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.4.0-ictce-5.5.0.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.5.1-intel-2014b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-2015.06.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-2015.11.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-intel-2015a.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.6.1-foss-2015b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-2.6.1-intel-2015b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-CrayGNU-2015.11-cuda-7.0.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-CrayGNU-2015.11.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016a.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016b-psmp.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2017b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2018a.eb
  easybuild/easyconfigs/c/CP2K/CP2K-4.1-foss-2016b-psmp.eb
  easybuild/easyconfigs/c/CP2K/CP2K-4.1-intel-2016b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-5.1-foss-2018a.eb
  easybuild/easyconfigs/c/CP2K/CP2K-5.1-intel-2017b.eb
  easybuild/easyconfigs/c/CP2K/CP2K-5.1-intel-2018a.eb
Labels: bug fix

#7238 {bio}[foss/2017b,intel/2017b] MultiQC v1.6
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.6-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.6-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.6-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.6-intel-2017b-Python-3.6.3.eb
Labels: update

#7241 add missing dependencies in OpenJPEG easyconfig (cfr. #7216)
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.3.0-GCCcore-7.3.0.eb
Labels: bug fix

#7237 {vis}[GCCcore/7.3.0,intel/2018b] VMD v1.9.3, FLTK v1.3.4, ACTC v1.1, ...
  easybuild/easyconfigs/a/ACTC/ACTC-1.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.4-intel-2018b.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/x/xprop/xprop-1.2.3-GCCcore-7.3.0.eb
Labels: update

#7244 {bio}[foss/2017b,intel/2017b] Seaborn v0.9.0
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.9.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.9.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.9.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.9.0-intel-2017b-Python-3.6.3.eb
Labels: update

#7218 {toolchain} intel/2019.00
  easybuild/easyconfigs/h/HPL/HPL-2.2-intel-2019.00.eb
  easybuild/easyconfigs/i/icc/icc-2019.0.117-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2019.0.117-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/ifort/ifort-2019.0.117-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/ifort/ifort-2019.0.117_no_mpi_mic_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2019.00.eb
  easybuild/easyconfigs/i/imkl/imkl-2019.0.117-iimpi-2019.00.eb
  easybuild/easyconfigs/i/impi/impi-2019.0.117-iccifort-2019.0.117-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/intel/intel-2019.00.eb
Labels: update

#7219 {toolchain} intel/2019.01
  easybuild/easyconfigs/h/HPL/HPL-2.2-intel-2019.01.eb
  easybuild/easyconfigs/i/icc/icc-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/ifort/ifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/ifort/ifort-2019.1.144_no_mpi_mic_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2019.01.eb
  easybuild/easyconfigs/i/imkl/imkl-2019.1.144-iimpi-2019.01.eb
  easybuild/easyconfigs/i/impi/impi-2019.1.144-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/intel/intel-2019.01.eb
Labels: update

#7243 deprecate easyconfigs for goolf(c) + corresponding gompi(c) subtoolchains
  easybuild/easyconfigs/g/gompi/gompi-1.4.10.eb
  easybuild/easyconfigs/g/gompi/gompi-1.5.14.eb
  easybuild/easyconfigs/g/gompi/gompi-1.5.16.eb
  easybuild/easyconfigs/g/gompi/gompi-1.6.10.eb
  easybuild/easyconfigs/g/gompi/gompi-1.7.20.eb
  easybuild/easyconfigs/g/gompic/gompic-2016.08.eb
  easybuild/easyconfigs/g/gompic/gompic-2016.10.eb
  easybuild/easyconfigs/g/gompic/gompic-2017.01.eb
  easybuild/easyconfigs/g/gompic/gompic-2017.02.eb
  easybuild/easyconfigs/g/goolf/goolf-1.4.10.eb
  easybuild/easyconfigs/g/goolf/goolf-1.5.14.eb
  easybuild/easyconfigs/g/goolf/goolf-1.5.16.eb
  easybuild/easyconfigs/g/goolf/goolf-1.6.10.eb
  easybuild/easyconfigs/g/goolf/goolf-1.7.20.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2016.08.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2016.10.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2017.01.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2017.02.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2017b.eb
  easybuild/easyconfigs/g/goolfc/goolfc-2018a.eb
Labels: change

#7242 {bio}[dummy/dummy] CellRanger v3.0.0
  easybuild/easyconfigs/c/CellRanger/CellRanger-3.0.0.eb
Labels: new

#7234 {devel}[dummy] Spark 2.4.0 (pre-build Hadoop 2.7)
  easybuild/easyconfigs/s/Spark/Spark-2.4.0-Hadoop-2.7-Java-1.8.eb
Labels: update

#7247 {lib}[intel/2018b] CFITSIO v3.45
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.45-intel-2018b.eb
Labels: update

#7248 {tools][foss/2018b] IPython 7.2.0 (+ deps) w/ Python 3.6.6
  easybuild/easyconfigs/i/IPython/IPython-7.2.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.16-GCCcore-7.3.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-7.3.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.5-foss-2018b.eb
Labels: update

#7159 update SCOTCH 6.0.5 easyconfigs in-place to 6.0.6 to fix wrong download URL
  easybuild/easyconfigs/d/DOLFIN/DOLFIN-2018.1.0.post1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-foss-2018a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-intel-2018a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-foss-2018b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-intel-2018a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1806-foss-2018b.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.9.3-foss-2018a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-foss-2018a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-foss-2018b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-intel-2018a.eb
  easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-foss-2018a-Python-3.6.4.eb
Labels: bug fix, change

#7251 fix checksum in Molden-5.8-foss-2018a.eb (cfr. #7223)
  easybuild/easyconfigs/m/Molden/Molden-5.8-foss-2018a.eb
Labels: bug fix, change

#7258 #7256 fixed URL for ADMIXTURE
  easybuild/easyconfigs/a/ADMIXTURE/ADMIXTURE-1.3.0.eb
Labels: bug fix

#7257 {numlib}[foss/2017b] Trilinos v12.12.1
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.1.2-foss-2017b-METIS-5.1.0.eb
  easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-foss-2017b-Python-2.7.14.eb
Labels: update

#7255 {vis}[foss/2018b] GTK+ 2.24.32 (REVIEW)
  easybuild/easyconfigs/a/ATK/ATK-2.28.1-foss-2018b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018b.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.12-foss-2018b.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.2.0-foss-2018b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.42.4-foss-2018b.eb
Labels: update

#7268 {chem}[foss/2018b] QuTiP v4.3.1
  easybuild/easyconfigs/q/QuTiP/QuTiP-4.3.1-foss-2018b-Python-3.6.6.eb
Labels: update

#7266 {toolchain} GCC/7.4.0-2.31.1
  easybuild/easyconfigs/b/Bison/Bison-3.2.2-GCCcore-7.4.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.31.1-GCCcore-7.4.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.4.0.eb
  easybuild/easyconfigs/g/GCC/GCC-7.4.0-2.31.1.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-7.4.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.8-GCCcore-7.4.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.4.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-7.4.0.eb
Labels: update

#7259 {vis}[foss/2018b] PyGTK 1.18.0 w/ Python 2.7.15 (REVIEW)
  easybuild/easyconfigs/l/libglade/libglade-2.6.4-foss-2018b.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.18.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-2.28.7-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/PyGTK/PyGTK-2.24.0-foss-2018b-Python-2.7.15.eb
Labels: update

#7270 {tools}[GCCcore/8.2.0] Szip v2.1.1
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-8.2.0.eb
Labels: update

#6276 {bio}[foss/2018b] HMMER 3.1b2
  easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-foss-2018a.eb
Labels: update

#7269 {bio}[intel/2018b] Infernal v1.1.2
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.2-intel-2018b.eb
Labels: update

#6266 {bio}[intel/2018a] AFNI v18.1.09 + deps
  easybuild/easyconfigs/a/AFNI/AFNI-18.1.09-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/a/AFNI/AFNI-18.1.09_omp-pragma-statement-fix.patch
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.10.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/SIP/SIP-4.19.8-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/tcsh/tcsh-6.20.00-GCCcore-6.4.0.eb
Labels: update

#7294 stick to PyQt5 5.9.2 as dep for AFNI 18.1.09
  easybuild/easyconfigs/a/AFNI/AFNI-18.1.09-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.9.2-intel-2018a-Python-3.6.4.eb
Labels: bug fix

#7275 fix source URLs & versions + build procedure for SKESA
  easybuild/easyconfigs/s/SKESA/SKESA-2.2-foss-2018a.eb
  easybuild/easyconfigs/s/SKESA/SKESA-2.3.0-foss-2018b.eb
  easybuild/easyconfigs/s/SKESA/SKESA-2.9.1-foss-2018a.eb
  easybuild/easyconfigs/s/SKESA/SKESA-2.9.1_fix-include.patch
  easybuild/easyconfigs/s/SKESA/SKESA-2.9.3-foss-2018b.eb
  easybuild/easyconfigs/s/shovill/shovill-0.9.0-foss-2018a-Python-2.7.14.eb
Labels: bug fix

#7250 Oxford Nanopore Fast5 files
  easybuild/easyconfigs/f/fast5/fast5-0.6.5.eb
Labels: new

#7293 add missing zlib dependency for NSS
  easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-7.3.0.eb
Labels: bug fix

#7271 {numlib}[GCC/8.2.0-2.31.1] OpenBLAS v0.3.4
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.4-GCC-8.2.0-2.31.1.eb
Labels: update

#7249 {vis}[foss/2018b] PyQt5 v5.11.3 (+ SIP v4.19.13) w/ Python 3.6.6
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.11.3-foss-2018b-Python-3.6.6.eb
Labels: update

#7300 [foss/2018a,foss/2018b] Qt5 - Add required build deps for QtWebEngine
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018a.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018b.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.11.2-foss-2018b.eb
Labels: bug fix

#7216 {vis}[GCCcore/6.4.0] OpenJPEG v2.3.0
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.3.0-GCCcore-6.4.0.eb
Labels: update

#7285 {numlib}[intel/2017b] Trilinos v12.12.1
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.1.2-intel-2017b-METIS-5.1.0.eb
  easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-intel-2017b-Python-2.7.14.eb
Labels: update

#7278 fix checksum for TRF 4.09
  easybuild/easyconfigs/t/TRF/TRF-4.09-linux64.eb
Labels: bug fix

#7301 fix ImageMagick source URLs: use launchpad.net for old versions, switch to GitHub for 7.0.8-* onwards
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.5-10-foss-2016b.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.5-4-intel-2017a.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-14-foss-2017b.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-14-intel-2017b.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-15-GCCcore-6.4.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-26-foss-2018a.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0-Ghostscript-9.22-cairo-1.14.12.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-39-GCCcore-6.4.0-Ghostscript-9.23-cairo-1.14.12.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-8-intel-2017a-JasPer-1.900.1.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.8-11-GCCcore-7.3.0.eb
Labels: bug fix

#7058 {bio}[foss/2018b] AFNI v18.3.00, tcsh v6.20.00
  easybuild/easyconfigs/a/AFNI/AFNI-18.3.00-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/tcsh/tcsh-6.20.00-GCCcore-7.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#7286 +download URL for impi 2018.3
  easybuild/easyconfigs/i/impi/impi-2018.3.222-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
Labels: enhancement

#7291 +download URL for imkl 2018.3 - imkl-iompi
  easybuild/easyconfigs/i/imkl/imkl-2018.3.222-iompi-2018b.eb
Labels: enhancement

#7292 +download URL for icc 2018.3
  easybuild/easyconfigs/i/icc/icc-2018.3.222-GCC-7.3.0-2.30.eb
Labels: enhancement

#7288 +download URL for ifort 2018.3
  easybuild/easyconfigs/i/ifort/ifort-2018.3.222-GCC-7.3.0-2.30.eb
Labels: enhancement

#7287 +download URL for imkl 2018.3
  easybuild/easyconfigs/i/imkl/imkl-2018.3.222-iimpi-2018b.eb
Labels: enhancement

#6797 {tools} [foss/2018a] ipyparallel v6.2.2 for Python/3.6.4
  easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.2-foss-2018a-Python-3.6.4.eb
Labels: new

#6582 {chem}[foss/2016b] GAMESS-US v20180214-R1
  easybuild/easyconfigs/g/GAMESS-US/GAMESS-US-20180214-R1-foss-2016b-sockets.eb
  easybuild/easyconfigs/g/GAMESS-US/GAMESS-US-20180214-R1-foss-2016b.eb
  easybuild/easyconfigs/g/GAMESS-US/GAMESS-US-20180214-R1_openblas.patch
Labels: update

#6761 {bio}[GCCcore/7.3.0] Add DCMTK v3.6.3
  easybuild/easyconfigs/d/DCMTK/DCMTK-3.6.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.15-GCCcore-7.3.0.eb
Labels: new, update

#6750 {numlib}[foss-2017b] ARPACK++ 2018.03.26 (REVIEW)
  easybuild/easyconfigs/a/ARPACK++/ARPACK++-2018.03.26-foss-2017b.eb
  easybuild/easyconfigs/a/ARPACK++/ARPACK++-2018.03.26_find-deps.patch
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.6-foss-2017b-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuperLU/SuperLU-5.2.1-foss-2017b.eb
Labels: new, update

#5504 GROMACS 2016.4 for multiple toolchains.
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-giolf-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-goolfc-2017.02.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-intel-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4_fix_search_for_nvml_include.patch
Labels: update

#6932 {bio}[dummy/] supernova v2.1.1
  easybuild/easyconfigs/s/supernova/supernova-2.1.1.eb
Labels: update

#7282 {bio}[intel/2018b] BLAST+ v2.7.1
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-intel-2018b.eb
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.22-GCCcore-7.3.0.eb
Labels: update

#7263 add gamlss + gamlss.tr extensions to R 3.5.1 easyconfigs
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
Labels: enhancement

#7140 add grpreg extension to R 3.5.1 easyconfigs
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
Labels: enhancement

#7281 {bio}[intel/2018b] RepeatMasker v4.0.8
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.0.8-intel-2018b-Perl-5.28.0-HMMER.eb
Labels: new

#6693 {data}[foss/2018a] datamash 1.3
  easybuild/easyconfigs/d/datamash/datamash-1.3-foss-2018a.eb
Labels: new

#7316 fix checksum for VMD 1.9.3 patch file
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb
Labels: bug fix

#7325 update release notes + bump version for EasyBuild v3.8.0
  RELEASE_NOTES
  setup.py
Labels: update

#7327 {tools}[dummy/dummy] EasyBuild v3.8.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.8.0.eb
Labels: update

#7328 sync with master + update version to 3.8.1dev
  RELEASE_NOTES
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb
  setup.py
Labels: update

#7313 {tools}[intel/2018a] psrecord v1.1 w/ Python 2.7.14 + 3.6.4
  easybuild/easyconfigs/p/psrecord/psrecord-1.1-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/psrecord/psrecord-1.1-intel-2018a-Python-3.6.4.eb
Labels: new

#7330 {math}[binary] MCR R2018a (REVIEW)
  easybuild/easyconfigs/m/MCR/MCR-R2018a.eb
Labels: update

#7331 {tools}[intel/2018b] psrecord v1.1 w/ Python 2.7.15 + 3.6.6
  easybuild/easyconfigs/p/psrecord/psrecord-1.1-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/psrecord/psrecord-1.1-intel-2018b-Python-3.6.6.eb
Labels: update

#7335 {vis}[foss/2018b] matplotlib v3.0.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.2-foss-2018b-Python-3.6.6.eb
Labels: update

#7324 fix source URL in Doxygen easyconfigs
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.1.1-goalf-1.1.0-no-OFED.eb
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.1.1-ictce-3.2.2.u3.eb
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.1.1-ictce-4.0.6.eb
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.1.1-ictce-4.1.13.eb
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.2-ictce-4.1.13.eb
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.3.1-ictce-4.1.13.eb
  easybuild/easyconfigs/__archive__/d/Doxygen/Doxygen-1.8.3.1-iqacml-3.7.3.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.1.1-goolf-1.4.10.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.1.1-ictce-5.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.1.1-ictce-5.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.10-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.10-foss-2015b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.10-intel-2015b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.10-intel-2016.02-GCC-4.9.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-GCC-4.9.2.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-GCCcore-5.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-foss-2015a.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-foss-2016a.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-foss-2016b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-intel-2016a.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-intel-2016b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-iomkl-2016.07.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-iomkl-2016.09-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.13-GCCcore-6.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.13-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.13-gimkl-2017a.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.2-ictce-5.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.3.1-goolf-1.4.10.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.3.1-goolf-1.5.14.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.3.1-ictce-5.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.3.1-ictce-5.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.3.1-ictce-5.5.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.3.1-ictce-6.1.5.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.5-ictce-5.5.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.5-intel-2014b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.6-ictce-5.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.6-ictce-5.5.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.7-foss-2014b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.7-foss-2015a.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.7-intel-2014b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.7-intel-2015a.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.8-ictce-7.1.2.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.8-intel-2014b.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.9.1-GCC-4.9.2.eb
Labels: bug fix
