Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-05, with the labels that each got.

#6261 fix typo in Nipype & NiBabel causing failure in test suite due to triggering typo detection
  easybuild/easyconfigs/n/NiBabel/NiBabel-2.2.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/Nipype/Nipype-1.0.2-intel-2018a-Python-3.6.4.eb
Labels: bug fix

#6260 {numlib}[foss/2017b] SLEPc v3.8.3
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.8.3-foss-2017b.eb
Labels: update

#6249 {math}[foss/2017b] gmsh v3.0.6
  easybuild/easyconfigs/g/gmsh/gmsh-3.0.6-foss-2017b-Python-2.7.14.eb
Labels: update

#6265 consistently include patch for FLTK 1.3.4
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.4-foss-2017b.eb
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.4-intel-2017a.eb
Labels: bug fix

#6273 {math}[dummy/dummy] Maple v2017.2
  easybuild/easyconfigs/m/Maple/Maple-2017.2.eb
Labels: update

#6269 fix Perl shebang in MCL v14.137 scripts
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-6.4.0-Perl-5.26.1.eb
  easybuild/easyconfigs/m/MCL/MCL-14.137-foss-2016a.eb
  easybuild/easyconfigs/m/MCL/MCL-14.137-intel-2016b.eb
  easybuild/easyconfigs/m/MCL/MCL-14.137_fixperl.patch
Labels: bug fix

#6285 add py_expression_eval extension to (recent) Python 2.7.14 & 3.6.4 easyconfigs
  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2018a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-iomkl-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2017a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-golf-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
Labels: enhancement

#6264 {data}[intel/2018a] xarray v0.10.3 w/ Python 3.6.4
  easybuild/easyconfigs/x/xarray/xarray-0.10.3-intel-2018a-Python-3.6.4.eb
Labels: update

#6286 TensorFlow 1.8.0 for intel/2018a
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_use_64b_alignment.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0_remove_DATE_defines.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0_icc-fixes.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0_no_boringssl.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0_no_grpc.patch
Labels: update

#6291 Add pkg-config build dependency to FFmpeg >= 3.3.1
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.3.1-foss-2016b.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.3.4-intel-2017a.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4.1-foss-2017b.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4.1-intel-2017b.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4.2-foss-2018a.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.4.2-intel-2018a.eb
Labels: bug fix

#6293 {dummy} Java v1.8.0_172
  easybuild/easyconfigs/j/Java/Java-1.8.0_172.eb
Labels: update

#6289 {tools}[GCCcore/6.4.0] Ghostscript v9.23
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.23-GCCcore-6.4.0.eb
Labels: update

#6290 {vis}[GCCcore/6.4.0] ImageMagick v7.0.7-30
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0.eb
Labels: update

#6255 {lib}[foss/2018a] TensorFlow v1.7.0 w/ Python 3.6.4 + CUDA 9.1.85
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
Labels: update

#6300 {vis}[GCCcore/6.4.0] feh v2.26, Imlib2 v1.5.1
  easybuild/easyconfigs/f/feh/feh-2.26-GCCcore-6.4.0.eb
  easybuild/easyconfigs/i/Imlib2/Imlib2-1.5.1-GCCcore-6.4.0.eb
Labels: new

#6301 {data}[foss/2017b] ncview v2.1.7, netCDF v4.4.1.1, netCDF-Fortran v4.4.4, ...
  easybuild/easyconfigs/n/ncview/ncview-2.1.7-foss-2017b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-foss-2017b-HDF5-1.8.19.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017b-HDF5-1.8.19.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.25-foss-2017b.eb
Labels: update

#6305 change back checksum for libdap 3.19.1
  easybuild/easyconfigs/l/libdap/libdap-3.19.1-intel-2017b.eb
Labels: bug fix

#6304 {tools}[foss/2017b] NCO v4.7.4, ANTLR v2.7.7, libdap v3.19.1
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-foss-2017b.eb
  easybuild/easyconfigs/l/libdap/libdap-3.19.1-foss-2017b.eb
  easybuild/easyconfigs/n/NCO/NCO-4.7.4-foss-2017b.eb
Labels: update

#6306 {bio}[foss/2016b] gffread v0.9.12
  easybuild/easyconfigs/g/gffread/gffread-0.9.12-foss-2016b.eb
Labels: new

#6292 also include patch + use -mno-avx512f to fix TensorFlow 1.8.0 built with foss/2018a on Intel Skylake (AVX512)
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0-foss-2018a-Python-3.6.4.eb
Labels: bug fix

#6310 {geo}[intel/2018a] ESMF v7.1.0r
  easybuild/easyconfigs/e/ESMF/ESMF-7.1.0r-intel-2018a.eb
Labels: update

#6277 {bio}[intel/2018a] BioPerl v1.7.2
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.2-intel-2018a-Perl-5.26.1.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-GCCcore-6.4.0-Perl-5.26.1.eb
Labels: update

#6279 {bio}[intel/2018a] PRANK v170427, MAFFT v7.397
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.397-intel-2018a-with-extensions.eb
  easybuild/easyconfigs/p/PRANK/PRANK-170427-intel-2018a.eb
Labels: update

#6280 {bio}[intel/2018a] CD-HIT v4.6.8
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.6.8-intel-2018a.eb
Labels: update

#6281 {tools}[intel/2018a] parallel v20180422
  easybuild/easyconfigs/p/parallel/parallel-20180422-intel-2018a.eb
Labels: update

#6282 {bio}[intel/2018a] FastTree v2.1.10
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.10-intel-2018a.eb
Labels: update

#6283 {bio}[intel/2018a] BLAST+ v2.7.1
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-intel-2018a-Python-2.7.14.eb
Labels: update

#6297 add several extensions to Perl 5.26.1 easyconfigs, incl Dist::Zilla & dependencies
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
Labels: enhancement

#6288 remove Python dependency from BLAST+ 2.7.1 easyconfig using foss/2018a toolchain
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-foss-2018a.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-intel-2018a.eb
Labels: change

#6309 {data}[foss/2017b] netcdf4-python v1.4.0, cftime v1.0.0b1
  easybuild/easyconfigs/c/cftime/cftime-1.0.0b1-foss-2017b-Python-3.6.2.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.4.0-foss-2017b-Python-3.6.2-HDF5-1.8.19.eb
Labels: new, update

#6294 add README for Java with information on downloading source tarball
  easybuild/easyconfigs/j/Java/README.md
Labels: enhancement

#6321 {tools}[dummy/dummy] Inspector v2018_update2
  easybuild/easyconfigs/i/Inspector/Inspector-2018_update2.eb
Labels: update

#6323 {compiler} PGI v18.4 (REVIEW)
  easybuild/easyconfigs/p/PGI/PGI-18.4-GCC-6.4.0-2.28.eb
Labels: update

#6320 {devel}[GCCcore/6.4.0] likwid v4.3.2
  easybuild/easyconfigs/l/likwid/likwid-4.3.2-GCCcore-6.4.0.eb
Labels: update

#6337 {data}[intel/2018a] netcdf4-python v1.4.0, cftime v1.0.0 w/ Python 3.6.4
  easybuild/easyconfigs/c/cftime/cftime-1.0.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.4.0-intel-2018a-Python-3.6.4.eb
Labels: update

#6336 {data}[intel/2018a] scikit-learn v0.19.1 w/ Python 3.6.4
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.19.1-intel-2018a-Python-3.6.4.eb
Labels: update

#6334 {math}[intel/2018a] Bottleneck v1.2.1
  easybuild/easyconfigs/b/Bottleneck/Bottleneck-1.2.1-intel-2018a-Python-3.6.4.eb
Labels: new

#6332 {phys}[intel/2016b] BAGEL v1.1.1
  easybuild/easyconfigs/b/BAGEL/BAGEL-1.1.1-intel-2016b.eb
Labels: new

#6213 {tools}[GCCcore/6.4.0] cURL v7.59.0
  easybuild/easyconfigs/c/cURL/cURL-7.59.0-GCCcore-6.4.0.eb
Labels: update

#6343 {tools}[foss/2018a,intel/2018a] REMORA v1.8.2
  easybuild/easyconfigs/r/REMORA/REMORA-1.8.2-foss-2018a.eb
  easybuild/easyconfigs/r/REMORA/REMORA-1.8.2-intel-2018a.eb
Labels: update

#6348 {bio}[intel/2018a] DIAMOND v0.9.22
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.22-intel-2018a.eb
Labels: update

#6299 {tools}[intel/2018a] behave v1.2.6
  easybuild/easyconfigs/b/behave/behave-1.2.6-intel-2018a-Python-3.6.4.eb
Labels: update

#6303 {perf}[GCCcore/6.4.0] PAPI v5.6.0
  easybuild/easyconfigs/p/PAPI/PAPI-5.6.0-GCCcore-6.4.0.eb
Labels: update

#6349 {bio}[intel/2018a] STIR v3.0
  easybuild/easyconfigs/s/STIR/STIR-3.0-intel-2018a.eb
  easybuild/easyconfigs/s/STIR/STIR-3.0_fix-CMakeLists.patch
Labels: new

#6270 {devel}[foss/2018a,intel/2018a] SCons v3.0.1
  easybuild/easyconfigs/s/SCons/SCons-3.0.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/SCons/SCons-3.0.1-intel-2018a-Python-3.6.4.eb
Labels: update

#6271 {devel}[foss/2018a,intel/2018a] SCons v3.0.1
  easybuild/easyconfigs/s/SCons/SCons-3.0.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/SCons/SCons-3.0.1-intel-2018a-Python-2.7.14.eb
Labels: update

#6272 {math}[foss/2018a,intel/2018a] SUNDIALS v2.7.0
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-2.7.0-foss-2018a.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-2.7.0-intel-2018a.eb
Labels: update

#6253 {compiler}[dummy] icc v2017.7.259, ifort v2017.7.259
  easybuild/easyconfigs/i/icc/icc-2017.7.259-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/i/ifort/ifort-2017.7.259-GCC-6.4.0-2.28.eb
Labels: update

#6178 {toolchain}[gmpolf-2017.10]
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gmpich-2017.08.eb
  easybuild/easyconfigs/g/gmpolf/gmpolf-2017.10.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-gmpolf-2017.10.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.20-GCC-7.2.0-2.29.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmpich-2017.08-OpenBLAS-0.2.20.eb
Labels: update

#5799 {toolchain}[dummy/dummy] giolfc v2017b
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.6-gimpic-2017b.eb
  easybuild/easyconfigs/g/gimpic/gimpic-2017b.eb
  easybuild/easyconfigs/g/giolfc/giolfc-2017b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-giolfc-2017b.eb
  easybuild/easyconfigs/i/impi/impi-2017.3.196-gcccuda-2017b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gimpic-2017b-OpenBLAS-0.2.20.eb
Labels: new, update

#6333 {bio}[foss/2018a] Proteinortho v5.16b
  easybuild/easyconfigs/p/Proteinortho/Proteinortho-5.16b-foss-2018a-Python-3.6.4-Perl-5.26.1.eb
Labels: new

#6353 {bio}[foss/2018a] minimap2 2.10
  easybuild/easyconfigs/m/minimap2/minimap2-2.10-foss-2018a.eb
Labels: update

#5791 {bio}[foss/2018a] QUAST 4.6.3
  easybuild/easyconfigs/q/QUAST/QUAST-4.6.3-foss-2018a-Python-3.6.4.eb
Labels: update

#6262 {lang}[foss/2018a] R 3.4.4
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.4.2-foss-2018a.eb
  easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
Labels: new, update

#6358 add patch for Automake 1.15 to fix issue with recent Perl versions
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-4.7.2.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-4.8.4.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-4.9.2.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-4.9.3.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-5.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-4.9.2.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-4.9.3.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-5.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-5.4.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-6.1.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-6.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-6.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GNU-4.9.2-2.25.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-GNU-5.1.0-2.25.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-fix-brace.patch
  easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2015a.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2015b.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2016.04.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2016a.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2016b.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-gimkl-2.11.5.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-ictce-5.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-ictce-5.5.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-intel-2015a.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-intel-2015b.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-intel-2016.02-GCC-4.9.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-intel-2016a.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-intel-2016b.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-iomkl-2016.07.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15-iomkl-2016.09-GCC-4.9.3-2.25.eb
Labels: bug fix

#6278 add patch to build particular source file of matrixStats extension in R 3.4.4 easyconfig with -O1 to work around ICE in Skylake systems
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/matrixStats-0.53.1_O1.patch
Labels: bug fix

#6356 {bio}[foss/2018a] RELION v2.1
  easybuild/easyconfigs/r/RELION/RELION-2.1-foss-2018a.eb
Labels: update

#6360 fix glog skylake intel internal error
  easybuild/easyconfigs/g/glog/glog-0.3.5-intel-2017a.eb
  easybuild/easyconfigs/g/glog/glog-0.3.5-intel-2017b.eb
  easybuild/easyconfigs/g/glog/glog-0.3.5_intel.patch
Labels: bug fix

#6359 {tools}[GCCcore/6.4.0] tcsh v6.20.00
  easybuild/easyconfigs/t/tcsh/tcsh-6.20.00-GCCcore-6.4.0.eb
Labels: update

#6347 {bio}[GCCcore/6.4.0] Pisces v5.2.7.47
  easybuild/easyconfigs/p/Pisces/Pisces-5.2.7.47-GCCcore-6.4.0.eb
Labels: new

#6357 {devel}[foss/2018a] Boost v1.67.0 w/ Python 2.7.14
  easybuild/easyconfigs/b/Boost/Boost-1.67.0-foss-2018a-Python-2.7.14.eb
Labels: update

#6365 {bio}[foss/2016b] SPAdes v3.12.0
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.12.0-foss-2016b.eb
Labels: update

#6361 {numlib}[GCC/6.4.0-2.28] OpenBLAS v0.3.0
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.0-GCC-6.4.0-2.28.eb
Labels: update

#6317 Create README.md file for installing icc/ifort
  easybuild/easyconfigs/i/icc/README.md
  easybuild/easyconfigs/i/ifort/README.md
Labels: enhancement

#6215 {chem}[foss/2018a,gimkl/2017a,intel/2018a] WIEN2k v17.1 (REVIEW)
  easybuild/easyconfigs/a/Autotools/Autotools-20150215-gimkl-2017a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2015.02.002-foss-2018a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2015.02.002-gimkl-2017a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2015.02.002-intel-2018a.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gimkl-2017a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-gimkl-2017a.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-17.1-foss-2018a.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-17.1-gimkl-2017a.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-17.1-intel-2018a.eb
Labels: update

#6364 {data}[foss/2017b] pyshp v1.2.12
  easybuild/easyconfigs/p/pyshp/pyshp-1.2.12-foss-2017b-Python-3.6.2.eb
Labels: new

#6367 {bio}[intel/2018a] GMAP-GSNAP v2018-05-11
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2018-05-11-intel-2018a.eb
Labels: update

#6296 {compiler}[dummy] GCC 8.1.0 + binutils 2.30
  easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-8.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-8.1.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.1.0.eb
  easybuild/easyconfigs/g/GCC/GCC-8.1.0-2.30.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.6-GCCcore-8.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-8.1.0.eb
Labels: update

#6371 include ICU as dependency in recent R easyconfigs (v3.4.3 & v3.4.4)
  easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
Labels: bug fix

#6369 {math}[dummy/dummy] Mathematica v11.3.0
  easybuild/easyconfigs/m/Mathematica/Mathematica-11.3.0.eb
Labels: update

#6352 {bio}[intel/2018a] GATK v4.0.4.0 w/ Python 3.6.4
  easybuild/easyconfigs/g/GATK/GATK-4.0.4.0-intel-2018a-Python-3.6.4.eb
Labels: update

#6370 {vis}[foss/2018a] cisTEM v1.0.0-beta, wxWidgets v3.0.3
  easybuild/easyconfigs/c/cisTEM/cisTEM-1.0.0-beta-foss-2018a.eb
  easybuild/easyconfigs/c/cisTEM/cisTEM-1.0.0-beta_fix_wxWidgets_version.patch
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.0.3-foss-2018a.eb
Labels: new

#6379 fix checksum for RSEM 1.3.0 after sneaky re-release
  easybuild/easyconfigs/r/RSEM/RSEM-1.3.0-intel-2017a.eb
Labels: bug fix

#6380 bump version to 3.6.1 & update release notes
  RELEASE_NOTES
  setup.py
Labels: update

#6386 {tools}[dummy/dummy] EasyBuild v3.6.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.6.1.eb
Labels: update

#6385 {bio}[dummy/dummy] SRA-Toolkit v2.9.0
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-2.9.0-centos_linux64.eb
Labels: update

#6387 sync with master & bump version to 3.6.2dev
  RELEASE_NOTES
  easybuild/easyconfigs/r/RSEM/RSEM-1.3.0-intel-2017a.eb
  setup.py
Labels: update

#6384 {bio}[intel/2018a] sickle v1.33
  easybuild/easyconfigs/s/sickle/sickle-1.33-intel-2018a.eb
Labels: update

#6377 {bio}[intel/2018a] Canu v1.7
  easybuild/easyconfigs/c/Canu/Canu-1.7-intel-2018a.eb
Labels: update

#6373 {devel}[GCCcore/7.3.0] Autotools v20180311
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-7.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-7.3.0.eb
Labels: update

#6389 rename 'Canu' to 'canu' for v1.7
  easybuild/easyconfigs/c/canu/canu-1.7-intel-2018a.eb
Labels: change

#6388 {devel} [intel/2018a] Add SWIG v3.0.12 for intel-2018a and Python/2.7.14
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-intel-2018a-Python-2.7.14.eb
Labels: update

#6382 [GCCcore/7.2.0] bzip2 v1.0.6, CMake v3.10.3, libreadline v7.0
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-7.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.3-GCCcore-7.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-7.0-GCCcore-7.2.0.eb
Labels: update

#6391 {bio}[dummy/dummy] picard v2.18.5
  easybuild/easyconfigs/p/picard/picard-2.18.5-Java-1.8.0_162.eb
Labels: update

#6394 {devel}[foss/2018a] Qt 4.8.7
  easybuild/easyconfigs/q/Qt/Qt-4.8.7-foss-2018a.eb
Labels: update

#6395 {numlib}[intel/2017b] pystran 2017.04.20 (REVIEW)
  easybuild/easyconfigs/p/pystran/pystran-2017.04.20-intel-2017b-Python-2.7.14.eb
Labels: new

#6393 {bio}[intel/2018a] BWA v0.7.17
  easybuild/easyconfigs/b/BWA/BWA-0.7.17-intel-2018a.eb
Labels: update

#6392 {numlib}[GCC/7.3.0-2.30] OpenBLAS v0.3.0
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.0-GCC-7.3.0-2.30.eb
Labels: update

#6390 {bio}[intel/2018a] BEDTools v2.27.1
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.27.1-intel-2018a.eb
Labels: update

#6397 {bio}[intel/2018a] STAR v2.6.0c
  easybuild/easyconfigs/s/STAR/STAR-2.6.0c-intel-2018a.eb
Labels: update

#6400 {bio}[foss/2018a] MUSCLE 3.8.31
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.31-foss-2018a.eb
Labels: update

#6330 {data}[PGI/18.4] HDF5 v1.10.2 (REVIEW)
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.2-PGI-18.4-GCC-6.4.0-2.28.eb
Labels: update

#6406 {devel}[dummy/dummy] Spark 2.3.0
  easybuild/easyconfigs/s/Spark/Spark-2.3.0-Hadoop-2.7-Java-1.8.0_162.eb
Labels: update
