Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-07, with the labels that each got.

#6509 update existing easyconfigs for OpenCV 3.4.1 to use new custom easyblock for OpenCV
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-3.6.4.eb
Labels: change

#6523 {vis}[intel/2018a] OpenCV v3.4.1 + deps
  easybuild/easyconfigs/a/ATK/ATK-2.28.1-intel-2018a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2018a.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-intel-2018a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-intel-2018a-Python-3.6.4.eb
Labels: update

#6518 {numlib}[GCC/7.3.0-2.30] OpenBLAS v0.3.1
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.1-GCC-7.3.0-2.30.eb
Labels: 2018b, update

#6521 {bio}[intel/2018a] Scoary v1.6.16 w/ Python 2.7.14
  easybuild/easyconfigs/s/Scoary/Scoary-1.6.16-intel-2018a-Python-2.7.14.eb
Labels: new

#6520 {bio}[intel/2018a] prokka v1.13
  easybuild/easyconfigs/p/prokka/prokka-1.13-intel-2018a-BioPerl-1.7.2.eb
Labels: update

#6519 {mpi}[GCC/7.3.0-2.30] OpenMPI v3.1.1
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-GCC-7.3.0-2.30.eb
Labels: 2018b, update

#6522 also copy eggnog-mapper scripts
  easybuild/easyconfigs/e/eggnog-mapper/eggnog-mapper-1.0.3-intel-2018a-Python-2.7.14.eb
Labels: bug fix

#6531 {vis}[foss/2018a] PyOpenGL v3.1.1a1
  easybuild/easyconfigs/p/PyOpenGL/PyOpenGL-3.1.1a1-foss-2018a-Python-2.7.14.eb
Labels: update

#6504 {devel}[foss/2017a] makedepf90 2.8.8
  easybuild/easyconfigs/m/makedepf90/makedepf90-2.8.8-foss-2017a.eb
Labels: new

#6409 {toolchain} intel/2018b
  easybuild/easyconfigs/h/HPL/HPL-2.2-intel-2018b.eb
  easybuild/easyconfigs/i/icc/icc-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/ifort/ifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/ifort/ifort_2018.3.222_no_mpi_mic_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2018b.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.3.222-iimpi-2018b.eb
  easybuild/easyconfigs/i/impi/impi-2018.3.222-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/i/intel/intel-2018b.eb
Labels: 2018b, update

#6424 {toolchain} foss/2018b
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2018b.eb
  easybuild/easyconfigs/f/foss/foss-2018b.eb
  easybuild/easyconfigs/g/gompi/gompi-2018b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-foss-2018b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018b-OpenBLAS-0.3.1.eb
  test/easyconfigs/easyconfigs.py
Labels: 2018b, update

#6539 {phys}[intel/2018a] WannierTools v2.3.0
  easybuild/easyconfigs/w/WannierTools/WannierTools-2.3.0-intel-2018a.eb
Labels: new

#6555 {toolchain} fosscuda/2018b
  easybuild/easyconfigs/c/CUDA/CUDA-9.2.88-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompic-2018b.eb
  easybuild/easyconfigs/f/fosscuda/fosscuda-2018b.eb
  easybuild/easyconfigs/g/gcccuda/gcccuda-2018b.eb
  easybuild/easyconfigs/g/gompic/gompic-2018b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-fosscuda-2018b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-gcccuda-2018b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2018b-OpenBLAS-0.3.1.eb
Labels: 2018b, update

#6535 {system}[dummy/dummy] CUDA v9.2.88
  easybuild/easyconfigs/c/CUDA/CUDA-9.2.88.eb
Labels: update

#6557 fix software name in Bsoft easyconfig
  easybuild/easyconfigs/b/Bsoft/Bsoft-1.8.8-goolf-1.5.14.eb
Labels: change

#6479 {lang}[foss/2018b,intel/2018b] Python 2.7.15 + deps
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-7.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.15-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.15-intel-2018b.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.24.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.8-GCCcore-7.3.0.eb
Labels: 2018b, update

#6532 fix missing dependencies for Perl modules included as extensions for Perl 5.26.1
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
Labels: bug fix

#6533 fix missing dependencies for Perl modules included as extensions for Perl 5.28.0
  easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
Labels: bug fix

#6482 {vis}[foss/2018b,intel/2018b] Mesa 18.1.1 + deps
  easybuild/easyconfigs/c/CMake/CMake-3.11.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.92-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-foss-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-intel-2018b.eb
  easybuild/easyconfigs/n/nettle/nettle-3.4-foss-2018b.eb
  easybuild/easyconfigs/n/nettle/nettle-3.4-intel-2018b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-7.3.0-bare.eb
Labels: 2018b, update

#6538 {phys}[intel/2018a] BerkeleyGW v2.0.0
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.0.0-intel-2018a.eb
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.0.0_fix_path.patch
Labels: update

#6534 {system}[GCC/6.4.0-2.28] CUDA v9.2.88
  easybuild/easyconfigs/c/CUDA/CUDA-9.2.88-GCC-6.4.0-2.28.eb
Labels: update

#6528 {bio}[intel/2018a] KmerGenie v1.7048
  easybuild/easyconfigs/k/KmerGenie/KmerGenie-1.7048-intel-2018a.eb
Labels: update

#5930 Only SAMtools < 1.0 works for ChimPipe
  easybuild/easyconfigs/c/ChimPipe/ChimPipe-0.9.5-foss-2016b-Python-2.7.12.eb
Labels: bug fix, change

#6525 {bio}[intel/2018a] preseq v2.0.3
  easybuild/easyconfigs/p/preseq/preseq-2.0.3-intel-2018a.eb
Labels: update

#6530 {math}[foss/2018a] R-keras v2.1.6
  easybuild/easyconfigs/r/R-keras/R-keras-2.1.6-foss-2018a-R-3.4.4.eb
Labels: new

#6524 {bio}[intel/2018a] WISExome v20180517 w/ Python 2.7.14
  easybuild/easyconfigs/w/WISExome/WISExome-20180517-intel-2018a-Python-2.7.14.eb
Labels: new

#6456 {bio}[intel/2018a] BamUtil v1.0.14
  easybuild/easyconfigs/b/BamUtil/BamUtil-1.0.14-intel-2018a.eb
Labels: update

#6529 {bio}[intel/2018a] FastQ_Screen v0.12.0, GD v2.68
  easybuild/easyconfigs/f/FastQ_Screen/FastQ_Screen-0.12.0-intel-2018a-Perl-5.26.1.eb
  easybuild/easyconfigs/g/GDGraph/GDGraph-1.54-intel-2018a-Perl-5.26.1.eb
Labels: new, update

#6564 {devel}[fosscuda/2018b] Python 2.7.15 + SCons v3.0.1
  easybuild/easyconfigs/p/Python/Python-2.7.15-fosscuda-2018b.eb
  easybuild/easyconfigs/s/SCons/SCons-3.0.1-fosscuda-2018b-Python-2.7.15.eb
Labels: 2018b, update

#6561 {bio}[foss/2018b,fosscuda/2018b] GROMACS v2018.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-foss-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-fosscuda-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018_amend_search_for_nvml_lib.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018_dont_do_gpu_tests_on_cpu_build.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018_fix_incorrect_cuda_target_single_multiple_compilation_unit.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018_fix_search_for_nvml_include.patch
Labels: 2018b, update

#6562 {data}[GCCcore/7.3.0,foss/2018b,intel/2018b] HDF5 v1.10.2, Szip v2.1.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.2-foss-2018b.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.2-intel-2018b.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-7.3.0.eb
Labels: 2018b, update

#6566 {data}[fosscuda/2018b] HDF5 v1.10.2
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.2-fosscuda-2018b.eb
Labels: update

#6563 Fix gtest 1.8.0 - compile gtest
  easybuild/easyconfigs/g/gtest/gtest-1.8.0-GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/gtest/gtest-1.8.0-GCCcore-6.4.0.eb
Labels: bug fix

#6480 {lang}[foss/2018b,intel/2018b] Python v3.7.0
  easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb
Labels: 2018b, update

#6497 Bioconductor 3.7 iomkl 2018a R 3.5.0
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-iomkl-2018a.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.7-iomkl-2018a-R-3.5.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#6573 {data}[foss/2018b,intel/2018b] netCDF v4.6.1, netCDF-C++4 v4.3.0, netCDF-Fortran v4.4.4
  easybuild/easyconfigs/c/cURL/cURL-7.60.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.0-foss-2018b.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.0-intel-2018b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-foss-2018b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-intel-2018b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.1-foss-2018b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.1-intel-2018b.eb
Labels: update

#6574 bump version to 3.6.2 & update release notes
  RELEASE_NOTES
  setup.py
Labels: update

#6578 {tools}[dummy/dummy] EasyBuild v3.6.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.6.2.eb
Labels: update

#6579 sync with master & bump version to 3.6.3dev
  RELEASE_NOTES
  easybuild/easyconfigs/c/cURL/cURL-7.60.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-iomkl-2018a.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.0-foss-2018b.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.0-intel-2018b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-foss-2018b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-intel-2018b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.1-foss-2018b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.1-intel-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.7-iomkl-2018a-R-3.5.0.eb
  setup.py
  test/easyconfigs/easyconfigs.py
Labels: update

#6455 {bio}[intel/2018a] cutadapt v1.16
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-intel-2018a-Python-2.7.14.eb
Labels: update

#5932 {compiler}[dummy/] PGI v18.1
  easybuild/easyconfigs/p/PGI/PGI-18.1-GCC-7.2.0-2.29.eb
Labels: update

#6604 (data) [PGI/18.4-GCC-6.4.0-2.28] netCDF v4.6.1 and netCDF-Fortran v4.4.4 (REVIEW)
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-PGI-18.4-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.6.1-PGI-18.4-GCC-6.4.0-2.28.eb
Labels: new

#6608 {devel} [Java/1.8.0_162] Saxon-HE v9.7.0.21
  easybuild/easyconfigs/s/Saxon-HE/Saxon-HE-9.7.0.21-Java-1.8.0_162.eb
Labels: update

#6600 {bio}[foss/2016b] MetaPhlAn2 v2.7.8
  easybuild/easyconfigs/m/MetaPhlAn2/MetaPhlAn2-2.7.8-foss-2016b-Python-2.7.12.eb
Labels: new

#6599 {bio}[intel/2018a] parasail v2.2
  easybuild/easyconfigs/p/parasail/parasail-2.2-intel-2018a.eb
Labels: new

#6597 {bio}[foss/2018a] Cutadapt 1.16
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-foss-2018a-Python-3.6.4.eb
Labels: update

#6572 {bio}[foss/2018a] BayeScan 2.1
  easybuild/easyconfigs/b/BayeScan/BayeScan-2.1-foss-2018a.eb
Labels: update

#6556 {geo}[intel/2018a] earthengine-api v0.1.143
  easybuild/easyconfigs/e/earthengine-api/earthengine-api-0.1.143-intel-2018a-Python-2.7.14.eb
Labels: new

#6548 {bio}[foss/2018a] ncbi-vdb v2.9.1-1, NGS v2.9.1, file v5.33
  easybuild/easyconfigs/f/file/file-5.33-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/NGS/NGS-2.9.1-foss-2018a-Java-1.8.0_162.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-2.9.1-1-foss-2018a.eb
Labels: update

#6546 {bio}[foss/2018a] MEGAHIT v1.1.3
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.1.3-foss-2018a-Python-2.7.14.eb
Labels: update

#6545 {bio}[foss/2018a] SPAdes v3.12.0
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.12.0-foss-2018a.eb
Labels: update

#6544 {tools}[foss/2018a] pigz v2.4
  easybuild/easyconfigs/p/pigz/pigz-2.4-foss-2018a.eb
Labels: update

#6526 {bio}[intel/2018a] RSeQC v2.6.4, bx-python v0.8.1 w/ Python 2.7.14
  easybuild/easyconfigs/b/bx-python/bx-python-0.8.1-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/r/RSeQC/RSeQC-2.6.4-intel-2018a-Python-2.7.14.eb
Labels: update

#6454 {bio}[intel/2018a] LoFreq v2.1.3.1
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.7-intel-2018a.eb
  easybuild/easyconfigs/l/LoFreq/LoFreq-2.1.3.1-intel-2018a-Python-2.7.14.eb
Labels: update

#6284 {bio}[intel/2018a] Roary v3.12.0
  easybuild/easyconfigs/r/Roary/Roary-3.12.0-intel-2018a-Perl-5.26.1.eb
Labels: update

#6559 {chem}[intel/2018a] Cantera v2.3.0 w/ Python 2.7.14
  easybuild/easyconfigs/c/Cantera/Cantera-2.3.0-intel-2018a-Python-2.7.14.eb
Labels: update

#6621 {numlib}[intel/2018a] arpack-ng v3.6.2
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.6.2-intel-2018a.eb
Labels: update

#6620 {tools,vis}[GCCcore/6.4.0] ImageMagick v7.0.7-39, Ghostscript v9.23
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.23-GCCcore-6.4.0-cairo-1.14.12.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-39-GCCcore-6.4.0-Ghostscript-9.23-cairo-1.14.12.eb
Labels: update

#6616 {data} [foss/2018a; Python/2.7.14] PostgreSQL v10.3 (REVIEW)
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-10.3-foss-2018a-Python-2.7.14.eb
Labels: update

#6611 googletest - Add checksums
  easybuild/easyconfigs/g/googletest/googletest-1.8.0-GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/googletest/googletest-1.8.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/googletest/googletest-1.8.0-foss-2016b.eb
  easybuild/easyconfigs/g/googletest/googletest-1.8.0-intel-2016b.eb
Labels: bug fix

#6575 {chem}[intel/2018a] GIMIC 2018.04.20 (REVIEW)
  easybuild/easyconfigs/g/GIMIC/GIMIC-2018.04.20-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/g/GIMIC/GIMIC-2018.04.20_git.patch
Labels: new

#6569 {bio}[foss/2018a] Kraken2 2.0.6-beta (REVIEW)
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.6-beta-foss-2018a-Perl-5.26.1.eb
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.6-beta_CXXFLAGS.patch
Labels: new

#6624 {math}[foss/2016b,intel/2016b] ParMETIS v4.0.3
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-foss-2016b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-intel-2016b.eb
Labels: update

#6625 {numlib}[foss/2016b,intel/2016b] SuiteSparse v4.5.3
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.3-foss-2016b-ParMETIS-4.0.3.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.3-intel-2016b-ParMETIS-4.0.3.eb
Labels: update

#6626 {lib}[GCCcore/5.4.0] MATIO v1.5.9
  easybuild/easyconfigs/m/MATIO/MATIO-1.5.9-GCCcore-5.4.0.eb
Labels: update
