Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2018-10, with the labels that each got.

#6929 {lib}[GCCcore/6.4.0] XMLSec v1.2.26
  easybuild/easyconfigs/x/XMLSec/XMLSec-1.2.26-GCCcore-6.4.0.eb
Labels: new

#6933 {bio}[intel/2018a] GMAP-GSNAP v2018-07-04
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2018-07-04-intel-2018a.eb
Labels: update

#6930 {mpi}[GCCcore/6.4.0,GCCcore/7.3.0] PMIx v1.2.5, PMIx v2.1.3, PMIx v3.0.1
  easybuild/easyconfigs/l/libevent/libevent-2.1.8-GCCcore-7.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-1.2.5-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.1.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.0.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.0.1-GCCcore-7.3.0.eb
Labels: new

#6921 {lib}[foss/2018b] mkl-dnn v0.16
  easybuild/easyconfigs/m/mkl-dnn/mkl-dnn-0.16-foss-2018b.eb
Labels: update

#6936 Update gromacs 2016.3 for nvml patches
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-foss-2016b-GPU-enabled.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-goolfc-2017.01.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3_amend_search_for_nvml_lib.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3_fix_search_for_nvml_include.patch
Labels: enhancement

#6938 {lang}[intel/2018a] pandas-datareader v0.7.0
  easybuild/easyconfigs/p/pandas-datareader/pandas-datareader-0.7.0-intel-2018a-Python-3.6.4.eb
Labels: new

#6934 R-3.5.1-foss-2018b: fix uroot installation
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
  easybuild/easyconfigs/r/R/uroot-2.0-9_CUDA.patch
Labels: bug fix

#6942 Add missing dep for Szip in 2017b builds of netCDF.
  easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.5.0-intel-2017b.eb
Labels: bug fix

#6943 Fix missing comment from OpenBabel-2.4.1-fix-link-path-tests.patch
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-2.4.1-fix-link-path-tests.patch
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-2.4.1-intel-2017b-Python-2.7.14.eb
Labels: bug fix

#6941 {bio}[foss/2018b] Jellyfish v2.2.10
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.2.10-foss-2018b.eb
Labels: update

#6944 {bio}[dummy/dummy] novoalign v3.09.00
  easybuild/easyconfigs/n/novoalign/novoalign-3.09.00.eb
Labels: new

#6951 {tools}[intel/2018a] PyDatastream v0.5.1, suds v1.3.3.0 w/ Python 3.6.4
  easybuild/easyconfigs/p/PyDatastream/PyDatastream-0.5.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/suds/suds-1.3.3.0-intel-2018a-Python-3.6.4.eb
Labels: new

#6950 {tools}[intel/2018a] Quandl v3.4.2 w/ Python 3.6.4
  easybuild/easyconfigs/q/Quandl/Quandl-3.4.2-intel-2018a-Python-3.6.4.eb
Labels: new

#6949 {tools}[gompi/2018b] pFUnit v3.2.9
  easybuild/easyconfigs/p/pFUnit/pFUnit-3.2.9-gompi-2018b.eb
Labels: new

#6948 {tools}[intel/2018a] fbm v0.2.0 w/ Python 3.6.4
  easybuild/easyconfigs/f/fbm/fbm-0.2.0-intel-2018a-Python-3.6.4.eb
Labels: new

#6952 Use make=make in ParMGridGen easyconfigs.
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gimkl-2.11.5.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-goolf-1.4.10.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-intel-2016a.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-intel-2017a.eb
Labels: enhancement

#6947 {math,vis}[intel/2018a] NeuroKit v0.2.7, CVXOPT v1.2.1 w/ Python 3.6.4
  easybuild/easyconfigs/c/CVXOPT/CVXOPT-1.2.1-fix-setup-py.patch
  easybuild/easyconfigs/c/CVXOPT/CVXOPT-1.2.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/NeuroKit/NeuroKit-0.2.7-intel-2018a-Python-3.6.4.eb
Labels: new, update

#6954 {devel}[GCCcore/7.3.0] likwid v4.3.2
  easybuild/easyconfigs/l/likwid/likwid-4.3.2-GCCcore-7.3.0.eb
Labels: update

#6957 {chem}[foss/2018b] ASAP3 v3.10.10, ASE v3.16.2, matplotlib v3.0.0, ...
  easybuild/easyconfigs/a/ASAP3/ASAP3-3.10.10-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/ASE/ASE-3.16.2-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/o/OpenKIM-API/OpenKIM-API-1.9.7-foss-2018b.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.6-foss-2018b-Python-3.6.6.eb
Labels: update

#6958 {chem}[intel/2018b] ASAP3 v3.10.10, ASE v3.16.2, OpenKIM-API v1.9.7
  easybuild/easyconfigs/a/ASAP3/ASAP3-3.10.10-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/ASE/ASE-3.16.2-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/o/OpenKIM-API/OpenKIM-API-1.9.7-intel-2018b.eb
Labels: update

#6960 {chem,lang}[iomkl/2018b] ASAP3 v3.10.10, ASE v3.16.2, matplotlib v3.0.0, ...
  easybuild/easyconfigs/a/ASAP3/ASAP3-3.10.10-iomkl-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/ASE/ASE-3.16.2-iomkl-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-iomkl-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/o/OpenKIM-API/OpenKIM-API-1.9.7-iomkl-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.6-iomkl-2018b.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.6-iomkl-2018b-Python-3.6.6.eb
Labels: update

#6955 {lang}[foss/2018b] R v3.5.1
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018b-Python-2.7.15.eb
Labels: update

#6618 {chem}[intel/2017b] Amber-16-Ambertools-17-patchlevel-8-12
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix-cpptraj-dont-use-static.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix_incorrect_omp_directive_rism.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix_intel_mpi_compiler_version_detection.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix_missing_do_parallel_in_checkrismunsupported.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix_missing_openmp_at_link.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix_mkl_include_path.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-fix_sander_link_with_external_fftw.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-use_CUSTOMBUILDFLAGS_for_nab.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-use_FFTW_FFT_instead_of_PUBFFT.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17-use_fftw_from_mkl_or_external.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17_cpptraj_use_mkl_fft.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17_fix-hardcoding.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17_fix_fixed_size_cmd_in_nab.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17_fix_rism_fftw_lib.patch
  easybuild/easyconfigs/a/Amber/Amber-16-AT-17_ignore_X11_checks.patch
  easybuild/easyconfigs/a/Amber/Amber-16-dont_use_ipo.patch
  easybuild/easyconfigs/a/Amber/Amber-16-fix_missing_build_target.patch
  easybuild/easyconfigs/a/Amber/Amber-16-intel-2017b-AmberTools-17-patchlevel-8-12.eb
Labels: update

#6959 Issue 6484 had returned in the newest Python builds.
  easybuild/easyconfigs/p/Python/Python-3.6.6-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.6-intel-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-iomkl-2018b.eb
Labels: bug fix

#6963 Eliminate dependency on problematic LibUUID library.
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.0-GCCcore-7.3.0.eb
Labels: bug fix

#6896 {math}[intel/2018a] Sympy 1.3 w/ Python 2.7.14 (REVIEW)
  easybuild/easyconfigs/m/mpmath/mpmath-1.0.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/sympy/sympy-1.3-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/sympy/sympy-1.3_symlink.patch
Labels: update

#6962 solve 'version UUID_1.0 not found' problem in LibUUID easyconfigs
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-foss-2016a.eb
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-intel-2015a.eb
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-intel-2015b.eb
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-intel-2017a.eb
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-intel-2017b.eb
Labels: bug fix

#6971 fix broken installation for Python 3.6.2 & 3.6.3 with PyNaCl as dep for paramiko extension by explicitely including previous PyNaCl version as extension
  easybuild/easyconfigs/p/Python/Python-3.6.2-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2018.00.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-goolfc-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2018.01.eb
Labels: bug fix

#6940 add missing extensions for TensorFlow 1.10.1 (REVIEW)
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.6.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.6.0-fosscuda-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/protobuf/protobuf-3.6.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.10.0-fosscuda-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.10.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.10.1-fosscuda-2018b-Python-2.7.15.eb
Labels: bug fix

#6964 {bio}[intel/2018a] OrthoFinder v2.2.7 (w/ Python 2.7.14), MMseqs2 v5-9375b, MCL v14.137, FastME 2.1.6.1
  easybuild/easyconfigs/f/FastME/FastME-2.1.6.1-intel-2018a.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-5-9375b-intel-2018a.eb
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.2.7-intel-2018a-Python-2.7.14.eb
Labels: new, update

#6937 {bio}[GCC/6.4.0-2.28,iccifort/2017.4.196-GCC-6.4.0-2.28] PEAR v0.9.10
  easybuild/easyconfigs/p/PEAR/PEAR-0.9.10-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/p/PEAR/PEAR-0.9.10-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
Labels: update

#6966 {bio}[foss/2018b] ViennaRNA 2.4.10 w/ Python 2.7.15 (REVIEW)
  easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.10-foss-2018b-Python-2.7.15.eb
Labels: update

#5793 binutils-2.26: Inhibit -Werror as new system GCC has case fallthrough warnings
  easybuild/easyconfigs/b/binutils/binutils-2.26.eb
Labels: bug fix

#6855 {chem}[intel/2018a] Cantera v2.4.0 w/ Python 2.7.14
  easybuild/easyconfigs/c/Cantera/Cantera-2.4.0-intel-2018a-Python-2.7.14.eb
Labels: update

#6857 {devel}[dummy/] ant v1.10.5
  easybuild/easyconfigs/a/ant/ant-1.10.5-Java-1.8.eb
Labels: update

#6974 Easyconfig for Globus Connect Personal 2.3.6.
  easybuild/easyconfigs/g/GlobusConnectPersonal/GlobusConnectPersonal-2.3.6.eb
Labels: new

#6778 {vis}[intel/2018a] PyGTS v0.3.1
  easybuild/easyconfigs/p/PyGTS/PyGTS-0.3.1-intel-2018a-Python-2.7.14.eb
Labels: update

#6982 fix source URL for ADMIXTURE (no https) + add SHA256 checksum
  easybuild/easyconfigs/a/ADMIXTURE/ADMIXTURE-1.3.0.eb
Labels: bug fix

#6442 {bio}[intel/2018a] FASTX-Toolkit v0.0.14, libgtextutils v0.7
  easybuild/easyconfigs/f/FASTX-Toolkit/FASTX-Toolkit-0.0.14-intel-2018a.eb
  easybuild/easyconfigs/l/libgtextutils/libgtextutils-0.7-intel-2018a.eb
  easybuild/easyconfigs/l/libgtextutils/libgtextutils-0.7_fix-bool.patch
Labels: update

#6862 {bio}[dummy/] RTG-Tools v3.9.1
  easybuild/easyconfigs/r/RTG-Tools/RTG-Tools-3.9.1-Java-1.8.eb
Labels: new

#6983 removed dead source of bzip2 tarball from bzip.org
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2015.06.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2015.11.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2016.03.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.1.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.2.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.4.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.9.2.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-4.9.3.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-5.4.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-6.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-6.4.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-7.2.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-7.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2014b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015.05.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016.04.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gimkl-2.11.5.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gimkl-2017a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gompi-1.5.16.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.4.10.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.5.14.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.5.16.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.7.20.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.2.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.4.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.5.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-6.2.5.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-7.1.2.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2014.06.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2014b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2015a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2015b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016.02-GCC-4.9.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-iomkl-2016.07.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-iomkl-2016.09-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6.eb
Labels: change

#6986 {vis}[foss/2017b,intel/2017b] GST-plugins-base v0.10.36
  easybuild/easyconfigs/b/Bison/Bison-2.7-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-0.10.36-foss-2017b.eb
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-0.10.36-intel-2017b.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-0.10.36-foss-2017b.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-0.10.36-intel-2017b.eb
Labels: update

#6979 MUMmer-4.0.0beta2-foss-2018b
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0beta2-foss-2018b.eb
Labels: update

#6989 wheel 0.31.0 for fosscuda 2018a and Python 2.7.14
  easybuild/easyconfigs/w/wheel/wheel-0.31.0-fosscuda-2018a-Python-2.7.14.eb
Labels: update

#6990 Bazel 0.16.0 with GCCcore 6.4.0
  easybuild/easyconfigs/b/Bazel/Bazel-0.16.0-GCCcore-6.4.0.eb
Labels: update

#6906 {bio}[foss/2018b] R-bundle-Bioconductor v3.7 w/ R 3.5.1
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.7-foss-2018b.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.7-foss-2018b-R-3.5.1.eb
Labels: update

#6970 {bio}[intel/2018a] GenomeTester4 v4.0
  easybuild/easyconfigs/g/GenomeTester4/GenomeTester4-4.0-intel-2018a.eb
Labels: new

#4292 {bio}[dummy] FreeSurfer 6.0.0
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-6.0.0-centos6_x86_64.eb
Labels: update

#6994 {bio}[dummy/dummy] FreeSurfer v6.0.1
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-6.0.1-centos6_x86_64.eb
Labels: update

#6992 toolchain foss/2018.08 with GCC/8.2.0
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.0.5.eb
  easybuild/easyconfigs/b/binutils/binutils-2.31.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.31.1.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2018.08.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/f/foss/foss-2018.08.eb
  easybuild/easyconfigs/g/GCC/GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GCCcore/gcc-8.2.0-isl-0.20-missing-include.patch
  easybuild/easyconfigs/g/gompi/gompi-2018.08.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-foss-2018.08.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.7-GCCcore-8.2.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.11-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.14-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.2.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.12-GCCcore-8.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.3-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.2-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018.08-OpenBLAS-0.3.3.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-8.2.0.eb
Labels: update

#6969 {bio}[foss/2018b] seq2HLA v20180802
  easybuild/easyconfigs/s/seq2HLA/seq2HLA-2.3-foss-2018b-Python-2.7.15.eb
Labels: update

#6967 force building of ccmake for CMake 3.12.1 + fix deps
  easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-7.3.0.eb
Labels: change request

#6975 {bio}[foss/2018b] GATK-4.0.10.0 w/ Python 3.6.6
  easybuild/easyconfigs/g/GATK/GATK-4.0.10.0-foss-2018b-Python-3.6.6.eb
Labels: update

#7006 {bio}[foss/2018b,Python/2.7.15] cutadapt v1.18
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.18-foss-2018b-Python-2.7.15.eb
Labels: update

#6977 {bio}[foss-2018b] BBMap 38.26, BEDOPS 2.4.35, BWA 0.7.17, Beast 2.5.1, beagle-lib 3.0.2
  easybuild/easyconfigs/b/BBMap/BBMap-38.26-foss-2018b.eb
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.35-foss-2018b.eb
  easybuild/easyconfigs/b/BWA/BWA-0.7.17-foss-2018b.eb
  easybuild/easyconfigs/b/Beast/Beast-2.5.1-foss-2018b.eb
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.0.2-foss-2018b.eb
Labels: update

#7004 GIMIC - Add Perl module Data::Dump dependency
  easybuild/easyconfigs/g/GIMIC/GIMIC-2018.04.20-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
Labels: enhancement

#7005 add missing NSS/DBus dependencies to Qt 5.10.1 easyconfigs built with foss toolchain to ensure that QtWebEngine component gets installed
  easybuild/easyconfigs/d/DBus/DBus-1.13.6-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.13.6-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NSPR/NSPR-4.20-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/NSPR/NSPR-4.20-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.39_pkgconfig.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018a.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018b.eb
Labels: bug fix

#7014 {bio}[foss/2018b] AdapterRemoval v2.2.2
  easybuild/easyconfigs/a/AdapterRemoval/AdapterRemoval-2.2.2-foss-2018b.eb
Labels: update

#7016 {bio}[GCCcore/7.3.0] SeqPrep v1.3.2
  easybuild/easyconfigs/s/SeqPrep/SeqPrep-1.3.2-GCCcore-7.3.0.eb
Labels: update

#7018 {bio}[foss/2018b] SPAdes v3.12.0
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.12.0-foss-2018b.eb
Labels: update

#7013 {phys}[foss/2018b] BerkeleyGW v2.0.0
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.0.0-foss-2018b.eb
Labels: update

#6999 {data,vis}[foss/2018b] scikit-learn v0.20.0 w/ Python 3.6.6
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.0-foss-2018b-Python-3.6.6.eb
Labels: update

#6996 {devel,vis}[dummy/dummy,foss/2018b] motif v2.3.8, xbitmaps v1.1.2
  easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2018b.eb
  easybuild/easyconfigs/x/xbitmaps/xbitmaps-1.1.2.eb
Labels: update

#7000 {*}[foss/2018b] scikit-image v0.14.1, dask v0.19.4, Pillow v5.3.0 w/ Python 3.6.6 + Qhull v2015.2
  easybuild/easyconfigs/d/dask/dask-0.19.4-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/Pillow/Pillow-5.3.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/q/Qhull/Qhull-2015.2-GCCcore-7.3.0.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.14.1-foss-2018b-Python-3.6.6.eb
Labels: update

#7012 {numlib}[GCC/7.3.0-2.30,iccifort/2018.3.222-GCC-7.3.0-2.30] GSL v2.5
  easybuild/easyconfigs/g/GSL/GSL-2.5-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/g/GSL/GSL-2.5-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/GSL/GSL-2.5-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
Labels: update

#7030 add missing extensions to Python 3.6.4 easyconfigs using Intel-based toolchain
  easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018.02.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
Labels: bug fix

#7029 add missing extensions to Python 3.6.4 easyconfigs using foss* toolchain
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2017a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-fosscuda-2018a.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-golf-2018a.eb
Labels: bug fix

#7022 add missing extensions to Python 2.7.14 easyconfigs using toolchain of 2017b generation
  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb
Labels: bug fix

#6956 {bio}[intel/2018a] Stampy v1.0.32
  easybuild/easyconfigs/s/Stampy/Stampy-1.0.32-intel-2018a-Python-2.7.14.eb
Labels: update

#7008 add openssl OS deps in Perl 5.28.0 easyconfig for Net::ssleay
  easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
Labels: bug fix

#7032 create default configuration for RTG-Tools
  easybuild/easyconfigs/r/RTG-Tools/RTG-Tools-3.9.1-Java-1.8.eb
Labels: bug fix

#7033 add missing checksums for ipaddress Python extension (+ reformatting)
  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb
Labels: bug fix

#7034 also run checks on changed files when target branch for PR is something different than 'develop'
  .travis.yml
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#7020 {bio}[dummy/] Trimmomatic v0.38
  easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.38-Java-1.8.eb
Labels: update

#7038 {lang}[GCCcore/7.3.0] FriBidi v1.0.5
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.5-GCCcore-7.3.0.eb
Labels: update

#7044 bump version to 3.7.1 & update release notes
  RELEASE_NOTES
  setup.py
Labels: update

#7050 {tools}[dummy/dummy] EasyBuild v3.7.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.7.1.eb
Labels: update

#7049 {data}[intel/2018b] scikit-learn v0.20.0
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.0-intel-2018b-Python-3.6.6.eb
Labels: update

#6997 {vis}[foss/2018b] VTK v8.1.1 w/ Python 3.6.6
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-foss-2018b-Python-3.6.6.eb
Labels: update

#7054 {tools}[GCCcore/7.3.0] DB v18.1.25
  easybuild/easyconfigs/d/DB/DB-18.1.25-GCCcore-7.3.0.eb
Labels: update

#7055 {lib}[GCCcore/7.3.0] libxslt v1.1.32
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.32-GCCcore-7.3.0.eb
Labels: update

#7039 {lang}[foss/2018b] GObject-Introspection v1.54.1
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.54.1-foss-2018b-Python-2.7.15.eb
Labels: update

#7053 {tools}[foss/2018b] VIM 8.1.0483 w/ Python 2.7.15
  easybuild/easyconfigs/v/Vim/Vim-8.1.0483-foss-2018b-Python-2.7.15.eb
Labels: update

#7045 {bio}[foss/2018b] FSL v5.0.11 w/ Python 3.6.6
  easybuild/easyconfigs/f/FSL/FSL-5.0.11-foss-2018b-Python-3.6.6.eb
Labels: update

#6978 {bio}[foss/2018b] DIAMOND 0.9.22, FLASH 1.2.11, FLASH 2.2.0, FastQC 0.11.8, FastTree 2.1.10 w/ Java 1.8
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.22-foss-2018b.eb
  easybuild/easyconfigs/f/FLASH/FLASH-1.2.11-foss-2018b.eb
  easybuild/easyconfigs/f/FLASH/FLASH-2.2.00-foss-2018b.eb
  easybuild/easyconfigs/f/FastQC/FastQC-0.11.8-Java-1.8.eb
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.10-foss-2018b.eb
Labels: update

#7062 add libXp component to X11 bundle for GCCcore 6.4.0
  easybuild/easyconfigs/x/X11/X11-20180131-GCCcore-6.4.0.eb
Labels: enhancement

#7063 {bio}[foss/2018b] HMMER 3.2.1
  easybuild/easyconfigs/h/HMMER/HMMER-3.2.1-foss-2018b.eb
Labels: update

#7065 {lib}[foss/2018b] libwebp v1.0.0
  easybuild/easyconfigs/l/libwebp/libwebp-1.0.0-foss-2018b.eb
Labels: new

#7067 {tools}[foss/2018b] Ninja v1.8.2, Meson v0.48.1
  easybuild/easyconfigs/m/Meson/Meson-0.48.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.8.2-foss-2018b.eb
Labels: update

#7046 {bio}[foss/2018b] strelka v2.9.9
  easybuild/easyconfigs/s/strelka/strelka-2.9.9-foss-2018b.eb
Labels: update

#7064 {tools}[GCCcore/8.2.0] bzip2 v1.0.6
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-8.2.0.eb
Labels: update

#7057 {devel}[dummy/] ctags v5.8, cscope v15.9
  easybuild/easyconfigs/c/cscope/cscope-15.9.eb
  easybuild/easyconfigs/c/ctags/ctags-5.8.eb
Labels: new

#7073 also install shared libraries for LZO
  easybuild/easyconfigs/l/LZO/LZO-2.06-goolf-1.4.10.eb
  easybuild/easyconfigs/l/LZO/LZO-2.06-ictce-5.3.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.09-intel-2016b.eb
  easybuild/easyconfigs/l/LZO/LZO-2.09-intel-2017b.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2016a.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2016b.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2017a.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2018a.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2018b.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-intel-2017a.eb
Labels: enhancement

#7074 {devel}[GCCcore/6.4.0] MySQL v5.7.21
  easybuild/easyconfigs/l/libedit/libedit-20180525-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/MySQL/MySQL-5.7.21-GCCcore-6.4.0-clientonly.eb
  easybuild/easyconfigs/m/MySQL/MySQL-5.7.21_Fix_ndb_dir_error.patch
Labels: update

#7080 {bio}[foss/2018b] iCount v20180820, psutil v5.4.7, pybedtools v0.7.10 & more w/ Python 3.6.6
  easybuild/easyconfigs/i/iCount/iCount-20180820-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.15.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/psutil/psutil-5.4.7-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/pybedtools/pybedtools-0.7.10-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/s/STAR/STAR-2.6.1c-foss-2018b.eb
  easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.1-foss-2018b-Python-3.6.6.eb
Labels: update

#7076 {chem}[foss/2017b] NAMD v2.12
  easybuild/easyconfigs/n/NAMD/NAMD-2.12-foss-2017b-mpi.eb
Labels: update

#7066 GC3Pie/2.5.0 - Add missing dependencies
  easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.5.0.eb
Labels: bug fix

#7075 {lib}[foss/2018b] TensorFlow v1.11.0
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.11.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.11.0_fix-ToString.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.11.0_remove-msse-hardcoding.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.11.0_swig-env.patch
Labels: update

#7077 {tools}[intel/2018a] Meson v0.48.1, Ninja v1.8.2
  easybuild/easyconfigs/m/Meson/Meson-0.48.1-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.8.2-intel-2018a.eb
Labels: update

#7071 {bio}[intel/2018a] mosdepth v0.2.3
  easybuild/easyconfigs/m/mosdepth/mosdepth-0.2.3-intel-2018a.eb
Labels: update

#7061 fix installation of scikit-image 0.13.x by including missing required PyWavelets extension
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-intel-2017b-Python-2.7.14.eb
Labels: bug fix

#7084 {compiler}[dummy/] GCCcore v6.5.0
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.5.0.eb
  easybuild/easyconfigs/g/GCCcore/mpfr-3.1.6-allpatches-20171215.patch
Labels: update

#7009 {chem}[intel/2018a] CP2K v3.0, libxc v2.2.3
  easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2018a.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#7060 {chem}[intel/2018a] PLUMED v2.5b w/ Python 2.7.14
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5b-intel-2018a-Python-2.7.14.eb
Labels: update

#7037 {bio}[foss/2018b] SPAdes v3.13.0
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.13.0-foss-2018b.eb
Labels: update

#6702 {cae}[intel/2018a] OpenFOAM v6
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-intel-2018a.eb
Labels: update

#7091 {bio}[dummy/dummy] MRIcron v1.0.20180614
  easybuild/easyconfigs/m/MRIcron/MRIcron-1.0.20180614.eb
Labels: update

#7097 update Java/1.8 wrapper to Java 1.8.0_192
  easybuild/easyconfigs/j/Java/Java-1.8.0_192.eb
  easybuild/easyconfigs/j/Java/Java-1.8.eb
Labels: change, update

#7083 {tools}[foss/2017b,intel/2017b] Subversion v1.10.0
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/a/APR/APR-1.6.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.8.2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-foss-2017b.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-intel-2017b.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9_Fix_zlib_variable.patch
  easybuild/easyconfigs/s/Subversion/Subversion-1.10.0-foss-2017b.eb
  easybuild/easyconfigs/s/Subversion/Subversion-1.10.0-intel-2017b.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.2.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.2.0_Fix_install_path.patch
Labels: update

#7096 add missing checksums in X11/2017* easyconfigs
  easybuild/easyconfigs/x/X11/X11-20170129-GCCcore-6.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20170129-gimkl-2017a.eb
  easybuild/easyconfigs/x/X11/X11-20170314-GCCcore-6.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20171023-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/X11/X11-20180131-GCCcore-6.4.0.eb
Labels: bug fix
