Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2019-09, with the labels that each got.

#7296 VTK8: Make sure that right Python wrapper is used
  easybuild/easyconfigs/v/VTK/VTK-8.0.1-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.0.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-intel-2018a-Python-2.7.14.eb
Labels: bug fix

#7227 {bio}[foss/2018b] LOHHLA 2018.11.05 w/ R-3.5.1 (REVIEW)
  easybuild/easyconfigs/l/LOHHLA/LOHHLA-2018.11.05-foss-2018b-R-3.5.1.eb
  easybuild/easyconfigs/l/LOHHLA/LOHHLA-2018.11.05_add_shebang.patch
Labels: new

#8872 {lang}[foss/2019a] R v3.6.0: Apply patch to R package uroot
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
Labels: bug fix

#8881 {lang}[foss/2019a,intel/2019a] R v3.6.0: Add packages clue, bdsmatrix, fftwtools, imagerExtra, MALDIquant, threejs, LaplacesDemon, sampling, jiebaR, ...
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
Labels: enhancement

#8882 {bio}[foss/2019a] R-bundle-Bioconductor v3.9: Add pRoloc
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.9-foss-2019a-R-3.6.0.eb
Labels: enhancement

#8879 Install iccifort directly using the "composer" tarball.
  easybuild/easyconfigs/i/iccifort/iccifort-2019.4.243.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2019.4.243_no_mpi_rt_dependency.patch
Labels: change, update

#8886 {vis}[foss/2019a] corner v2.0.1 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/c/corner/corner-2.0.1-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/c/corner/corner-2.0.1-foss-2019a-Python-3.7.2.eb
Labels: new

#8883 {astro}[foss/2019a] emcee v2.2.1 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/e/emcee/emcee-2.2.1-foss-2019a.eb
Labels: update

#8884 {astro}[foss/2019a] ptemcee v1.0.0 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/p/ptemcee/ptemcee-1.0.0-foss-2019a.eb
Labels: new

#8868 {bio}[intel/2019a] RAxML v8.2.12
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-intel-2019a-hybrid-avx2.eb
Labels: update

#8845 {math}[foss/2019a] statsmodels v0.10.1 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.10.1-foss-2019a.eb
Labels: update

#8857 {tools}[intel/2019a] RBFOpt v4.1.1 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/r/RBFOpt/RBFOpt-4.1.1-intel-2019a.eb
Labels: update

#8855 {math}[intel/2019a] Ipopt v3.12.13, Bonmin v1.8.7
  easybuild/easyconfigs/b/Bonmin/Bonmin-1.8.7-intel-2019a.eb
  easybuild/easyconfigs/i/Ipopt/Ipopt-3.12.13-intel-2019a.eb
Labels: new, update

#8885 {data}[GCCcore/8.2.0] dill v0.3.0 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/d/dill/dill-0.3.0-GCCcore-8.2.0.eb
Labels: new

#8849 {perf}[gompi/2019a] OSU-Micro-Benchmarks v5.6.2
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.2-gompi-2019a.eb
Labels: update

#8867 angsd: Add missing deps for zlib, bzip2, and XZ
  easybuild/easyconfigs/a/angsd/angsd-0.921-foss-2018a.eb
  easybuild/easyconfigs/a/angsd/angsd-0.925-foss-2018b.eb
Labels: bug fix

#8839 {perf}[intel/2019a] Extrae v3.7.1
  easybuild/easyconfigs/e/Extrae/Extrae-3.7.1-intel-2019a.eb
  easybuild/easyconfigs/l/libdwarf/libdwarf-20190529-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libelf/libelf-0.8.13-GCCcore-8.2.0.eb
Labels: update

#8846 likwid: Update homepage info
  easybuild/easyconfigs/l/likwid/likwid-4.2.0-GCCcore-6.3.0.eb
  easybuild/easyconfigs/l/likwid/likwid-4.2.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/likwid/likwid-4.3.2-GCCcore-6.4.0.eb
Labels: bug fix

#8820 VMD: Add patch to plugins/Make-arch to use the correct tcl library version.
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3_plugins.patch
Labels: bug fix

#8837 {bio}[system/system] QIIME2 v2019.7
  easybuild/easyconfigs/q/QIIME2/QIIME2-2019.7.eb
Labels: update

#8148 {bio}[foss/2018b] Porechop v0.2.4 w/ Python 3.6.6
  easybuild/easyconfigs/p/Porechop/Porechop-0.2.4-foss-2018b-Python-3.6.6.eb
Labels: update

#8892 avoid that easy_install installs easyconfigs package as a zipped egg
  setup.cfg
Labels: bug fix

#8889 clean up OpenMPI 3.1.* easyconfigs to use custom OpenMPI easyblock
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.0-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-gcccuda-2018b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.2-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-gcccuda-2019a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0-2.32.eb
Labels: code cleanup

#8890 clean up OpenMPI 4.* easyconfigs to use custom OpenMPI easyblock
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1-hpcx.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1-GCC-8.3.0-2.32.eb
Labels: code cleanup

#8894 add back 'zip_safe = False' in setup.py to avoid that easy_install installs zipped egg
  setup.py
Labels: bug fix

#8841 {lib}[GCCcore/8.2.0] JsonCpp v0.10.7
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-0.10.7-GCCcore-8.2.0.eb
Labels: new

#8824 {tools}[intel/2018a] pytest v3.8.0 w/ Python 3.6.4
  easybuild/easyconfigs/p/pytest/pytest-3.8.0-intel-2018a-Python-3.6.4.eb
Labels: update

#8895 {vis}[fosscuda/2019a,intelcuda/2019a] matplotlib v2.2.4 w/ Python 2.7.15
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-fosscuda-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-intelcuda-2019a-Python-2.7.15.eb
Labels: update

#8897 consider archive source URL for all extensions in R-tesseract easyconfig
  easybuild/easyconfigs/r/R-tesseract/R-tesseract-4.0-foss-2018b-R-3.5.1.eb
Labels: bug fix

#8871 {data}[foss/2019a] causalml v0.3.0-20180610 w/ Python 3.7.2
  easybuild/easyconfigs/c/causalml/causalml-0.3.0-20180610-foss-2019a-Python-3.7.2.eb
Labels: new

#8840 {bio}[foss/2019a] AGFusion v1.2 w/ Python 3.7.2
  easybuild/easyconfigs/a/AGFusion/AGFusion-1.2-foss-2019a-Python-3.7.2.eb
Labels: new

#8838 fix issue where 'print_qiime_config.py -t' sanity check command fails for QIIME 1.9.1 because of subdir missing in $PYTHONPATH
  easybuild/easyconfigs/q/QIIME/QIIME-1.9.1.eb
Labels: bug fix

#8898 Add pkg-config to tesseract v4.0.0
  easybuild/easyconfigs/t/tesseract/tesseract-4.0.0-GCCcore-7.3.0.eb
Labels: bug fix

#8664 {vis}[GCCcore/8.2.0] gifsicle v1.92
  easybuild/easyconfigs/g/gifsicle/gifsicle-1.92-GCCcore-8.2.0.eb
Labels: new

#8818 {bio}[intel/2019a] kallisto v0.46.0
  easybuild/easyconfigs/k/kallisto/kallisto-0.46.0-intel-2019a.eb
Labels: update

#8826 {geo}[foss/2019a] rgdal 1.4-4 w/ R 3.6.0
  easybuild/easyconfigs/r/rgdal/rgdal-1.4-4-foss-2019a-R-3.6.0.eb
Labels: new

#8754 {chem,math}[intel/2019a] molmod v1.4.4, yaff v1.5.0 w/ Python 3.7.2
  easybuild/easyconfigs/m/molmod/molmod-1.4.4-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/y/yaff/yaff-1.5.0-intel-2019a-Python-3.7.2.eb
Labels: update

#8800 {bio}[intel/2019a] bcl2fastq2 v2.20.0
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-intel-2019a.eb
Labels: update

#8766 {cae}[intel/2019a] OpenFOAM v2.4.0
  easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-8.2.0.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.4.0-intel-2019a.eb
Labels: update

#8713 {bio}[iccifort/2019.1.144-GCC-8.2.0-2.31.1] Dsuite v20190713
  easybuild/easyconfigs/d/Dsuite/Dsuite-20190713-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: new

#8694 {tools}[gompi/2019a] REMORA v1.8.3
  easybuild/easyconfigs/r/REMORA/REMORA-1.8.3-gompi-2019a.eb
Labels: update

#8914 memory profiler 0.55.0 for Python 3.7.2 and 2.7.15
  easybuild/easyconfigs/m/memory-profiler/memory-profiler-0.55.0-foss-2019a.eb
Labels: update

#8899 fix source_urls in byacc 20170709 easyconfig file
  easybuild/easyconfigs/b/byacc/byacc-20170709-GCCcore-6.4.0.eb
Labels: bug fix

#8908 fix source_urls in (old) byacc easyconfigs
  easybuild/easyconfigs/b/byacc/byacc-20160324-intel-2016a.eb
  easybuild/easyconfigs/b/byacc/byacc-20160606-foss-2016b.eb
  easybuild/easyconfigs/b/byacc/byacc-20160606-intel-2016b.eb
Labels: bug fix

#8913 {vis}[foss/2019a] scikit-image v0.15.0 w/ Python 3.7.2
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.15.0-foss-2019a-Python-3.7.2.eb
Labels: update

#8567 {toolchain} foss/2019b
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2019b.eb
  easybuild/easyconfigs/f/foss/foss-2019b.eb
  easybuild/easyconfigs/g/GCC/GCC-8.3.0.eb
  easybuild/easyconfigs/g/gompi/gompi-2019b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2019b.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7-GCC-8.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2019b.eb
Labels: update

#8368 {bio}[foss/2018b] cytosim v20190117
  easybuild/easyconfigs/c/cytosim/cytosim-20190117-3D.patch
  easybuild/easyconfigs/c/cytosim/cytosim-20190117-detachment.patch
  easybuild/easyconfigs/c/cytosim/cytosim-20190117-gomkl-2019a-mkl.eb
  easybuild/easyconfigs/c/cytosim/cytosim-20190117-mkl.patch
  easybuild/easyconfigs/c/cytosim/cytosim-20190117-png.patch
Labels: new

#8830 {bio}[GCCcore/8.2.0] Longshot 0.3.4
  easybuild/easyconfigs/l/Longshot/Longshot-0.3.4-GCCcore-8.2.0.eb
Labels: new

#8681 {toolchain} intel/2019b
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2019b.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2019.5.281.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2019.5.281_no_mpi_rt_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2019b.eb
  easybuild/easyconfigs/i/imkl/imkl-2019.5.281-iimpi-2019b.eb
  easybuild/easyconfigs/i/impi/impi-2018.5.288-iccifort-2019.5.281.eb
  easybuild/easyconfigs/i/intel/intel-2019b.eb
Labels: update

#7500 {base}[intel/2019.01] pubtcrs v20180622
  easybuild/easyconfigs/p/pubtcrs/pubtcrs-20180622-intel-2019a.eb
Labels: new

#8915 {lang}[GCCcore/8.3.0] Python v2.7.16
  easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0.eb
Labels: update

#8909 {lang}[GCCcore/8.3.0] Perl v5.30.0
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
Labels: update

#8911 {lang}[GCCcore/8.3.0] Python v3.7.4
  easybuild/easyconfigs/p/Python/Python-3.7.4-GCCcore-8.3.0.eb
Labels: update

#8910 {system}[GCCcore/8.3.0] OpenSSL v1.1.1d
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.1d-GCCcore-8.3.0.eb
Labels: update

#8918 {devel,vis}[GCCcore/8.3.0] X11 v20190717, intltool v0.51.0
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20190717-GCCcore-8.3.0.eb
Labels: update

#8613 Rename SALMON to SALMON-TDDFT
  easybuild/easyconfigs/s/SALMON-TDDFT/SALMON-TDDFT-1.2.1-foss-2018b.eb
  easybuild/easyconfigs/s/SALMON-TDDFT/SALMON-TDDFT-1.2.1-intel-2018b.eb
Labels: change

#8900 {vis}[foss/2018b] ParaView v5.5.2 w/ Python 2.7.15
  easybuild/easyconfigs/p/ParaView/ParaView-5.5.2-foss-2018b-Python-2.7.15-mpi.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.5.2_fix-H5detect.c.patch
  easybuild/easyconfigs/p/ParaView/ParaView-5.5.2_fix-missing-doc.patch
  easybuild/easyconfigs/p/ParaView/ParaView-5.5.2_fix-missing-include.patch
  easybuild/easyconfigs/p/ParaView/ParaView-5.5.2_fix-serial-vtk-with-mpi.patch
Labels: update

#8833 {quantum}[foss/2019a] Qiskit v0.12.0 w/ Python 3.7.2
  easybuild/easyconfigs/q/Qiskit/Qiskit-0.12.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/q/Qiskit/qiskit-terra-0.9.0_fix-qiskit-version-env.patch
Labels: update

#8677 {bio}[iimpi/2019a] guenomu v2019.07.05
  easybuild/easyconfigs/a/argtable/argtable-2.13-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/guenomu/guenomu-2019.07.05-iimpi-2019a-mpi.eb
Labels: new, update

#8876 {tools}[GCCcore/8.2.0] csvkit v1.0.4 w/ Python 3.7.2
  easybuild/easyconfigs/c/csvkit/csvkit-1.0.4-GCCcore-8.2.0.eb
Labels: new

#8921 {tools}[GCCcore/8.2.0] parallel v20190622
  easybuild/easyconfigs/p/parallel/parallel-20190622-GCCcore-8.2.0.eb
Labels: update

#8916 fix homepage & description in scikit-image easyconfigs
  easybuild/easyconfigs/d/dask/dask-0.11.0-foss-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/d/dask/dask-0.12.0-foss-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/d/dask/dask-0.16.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/d/dask/dask-0.16.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/d/dask/dask-0.16.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/d/dask/dask-0.17.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/d/dask/dask-0.17.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/d/dask/dask-0.17.2-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-foss-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-foss-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.14.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.14.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.14.1-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.14.1-intel-2018b-Python-3.6.6.eb
Labels: bug fix

#8920 {tools}[GCCcore/8.3.0] Ninja v1.9.0
  easybuild/easyconfigs/n/Ninja/Ninja-1.9.0-GCCcore-8.3.0.eb
Labels: update

#8922 switch to PythonBundle & enable use_pip in old dask easyconfig files
  easybuild/easyconfigs/d/dask/dask-0.11.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/d/dask/dask-0.11.0-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/d/dask/dask-0.12.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/d/dask/dask-0.12.0-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/d/dask/dask-0.16.0-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/d/dask/dask-0.17.0-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/d/dask/dask-0.17.2-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/d/dask/dask-0.19.4-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/d/dask/dask-0.19.4-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/d/dask/dask-0.19.4-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/d/dask/dask-0.8.2-intel-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/d/dask/dask-0.8.2-intel-2016a-Python-3.5.1.eb
Labels: code cleanup

#8767 {tools}[dummy/] Nextflow v19.07.0
  easybuild/easyconfigs/n/Nextflow/Nextflow-19.07.0.eb
Labels: update

#8927 {devel}[GCCcore/8.2.0] gtest v1.8.1
  easybuild/easyconfigs/g/gtest/gtest-1.8.1-GCCcore-8.2.0.eb
Labels: update

#8925 {tools}[system/system] Aspera-Connect v3.9.6
  easybuild/easyconfigs/a/Aspera-Connect/Aspera-Connect-3.9.6.eb
Labels: update

#8665 {math}[foss/2019a] qpth v0.0.13_20190626 w/ Python 3.7.2
  easybuild/easyconfigs/q/qpth/qpth-0.0.13-20190626-foss-2019a-Python-3.7.2.eb
Labels: new

#8923 {tools}[GCCcore/8.3.0] cURL v7.66.0, git v2.23.0
  easybuild/easyconfigs/c/cURL/cURL-7.66.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/git/git-2.23.0-GCCcore-8.3.0.eb
Labels: update

#8860 {chem}[intel/2019a] pyiron v0.2.5, nglview v2.7.0, phonopy v2.2.0, spglib-python v1.14.1.post0 w/ Python 3.7.2
  easybuild/easyconfigs/n/nglview/nglview-2.7.0-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.2.0-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/pyiron/pyiron-0.2.5-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.14.1.post0-intel-2019a-Python-3.7.2.eb
Labels: new, update

#8848 {perf}[foss/2019a] Paraver v4.8.1
  easybuild/easyconfigs/p/Paraver/Paraver-4.8.1-foss-2019a.eb
Labels: new

#8850 {data}[GCCcore/6.4.0] ](Yahoo) MDBM v4.13.0 {REVIEW}
  easybuild/easyconfigs/m/MDBM/MDBM-4.13.0-GCCcore-6.4.0.eb
Labels: new

#8751 {chem}[foss/2018b,intel/2018b] ASE v3.18.0, GPAW v19.8.1 w/ Python 3.6.6
  easybuild/easyconfigs/a/ASE/ASE-3.18.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/ASE/ASE-3.18.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/g/GPAW/GPAW-19.8.1-foss-2018b-ASE-3.18.0-Python-3.6.6.eb
  easybuild/easyconfigs/g/GPAW/GPAW-19.8.1-intel-2018b-ASE-3.18.0-Python-3.6.6.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#8896 {bio}[foss/2019a] FSL v6.0.1
  easybuild/easyconfigs/f/FSL/FSL-6.0.1-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/f/FSL/FSL-6.0.1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/f/FSL/FSL-6.0.1_Build_extras.patch
  easybuild/easyconfigs/f/FSL/FSL-6.0.1_Makefile_fixes.patch
  easybuild/easyconfigs/f/FSL/FSL-6.0.1_Melodic-use-ifstream-good.patch
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.49.7-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.49.7_Fix_gobject_type.patch
  easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libxml++/libxml++-2.40.1-GCCcore-8.2.0.eb
Labels: new, update

#8753 [foss/2019a] PyTorch 1.2.0 w/ Python 3.7.2
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_disable-tests-ppc64le.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_disable-tests-sandybridge.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_fix-findAVX.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_fix_ideep_avx2_issue.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_fix_slogdet_issue.patch
Labels: update

#8926 {tools}[GCCcore/8.2.0] cram v0.7 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/c/cram/cram-0.7-GCCcore-8.2.0.eb
Labels: new

#8934 comment out libsecret OS dep in WebKitGTK+ easyconfig
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.24.1-GCC-8.2.0-2.31.1.eb
Labels: bug fix

#8832 Adding faulthandler patches to Python 3.7.0 easyconfigs
  easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-iomkl-2018b.eb
Labels: bug fix

#8880 {bio}[foss/2019a] CNVkit v0.9.6 w/ Python 3.7.2
  easybuild/easyconfigs/c/CNVkit/CNVkit-0.9.6-foss-2019a-Python-3.7.2-R-3.6.0.eb
Labels: update

#8940 {vis}[GCCcore/8.2.0] jbigkit v2.1
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1_shlib.patch
Labels: update

#8944 update CrayCCE, CrayGNU, CrayIntel and CrayPGI toolchains to 19.06
  easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.06.eb
  easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.06.eb
  easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.06.eb
  easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.06.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-CrayCCE-19.06.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-CrayGNU-19.06.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-CrayIntel-19.06.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#8951 update release notes & bump version for EasyBuild v4.0.0 release
  RELEASE_NOTES
  setup.py
Labels: update

#8943 {numlib}[system/system] cuDNN v7.6.2.24
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.6.2.24-CUDA-10.1.243.eb
Labels: update

#8954 {tools}[dummy/dummy] EasyBuild v4.0.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.0.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#8955 sync with master and bump version to 4.0.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#8938 {bio}[GCC/8.2.0-2.31.1] HMMER v3.2.1
  easybuild/easyconfigs/h/HMMER/HMMER-3.2.1-GCC-8.2.0-2.31.1.eb
Labels: update

#8952 {tools}[foss/2019a] Horovod v0.18.1 w/ Python 3.7.2
  easybuild/easyconfigs/h/Horovod/Horovod-0.18.1-foss-2019a-Python-3.7.2.eb
Labels: update

#8937 {bio}[GCC/8.2.0-2.31.1] MAFFT v7.429
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.429-GCC-8.2.0-2.31.1-with-extensions.eb
Labels: update

#8936 {bio}[GCC/8.2.0-2.31.1] minimap2 v2.17
  easybuild/easyconfigs/m/minimap2/minimap2-2.17-GCC-8.2.0-2.31.1.eb
Labels: update

#8746 {chem}[gompi/2019b] ORCA v4.2.0
  easybuild/easyconfigs/o/ORCA/ORCA-4.2.0-gompi-2019b.eb
Labels: update

#8960 {tools}[GCCcore/8.3.0] Meson v0.51.2 w/ Python 3.7.4
  easybuild/easyconfigs/m/Meson/Meson-0.51.2-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#8961 {devel}[GCCcore/8.3.0] Mako v1.1.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/m/Mako/Mako-1.1.0-GCCcore-8.3.0.eb
Labels: update

#8863 {data}[foss/2019a] ITK v5.0.1 w/ Python 3.7.2
  easybuild/easyconfigs/i/ITK/ITK-5.0.1-foss-2019a-Python-3.7.2.eb
Labels: update

#8966 {lib}[GCCcore/8.3.0] nettle v3.5.1
  easybuild/easyconfigs/n/nettle/nettle-3.5.1-GCCcore-8.3.0.eb
Labels: update

#8967 {lib}[GCCcore/8.3.0] libdrm v2.4.99
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.99-GCCcore-8.3.0.eb
Labels: update

#8969 {lang}[system/system] Julia v1.2.0
  easybuild/easyconfigs/j/Julia/Julia-1.2.0-linux-x86_64.eb
Labels: update

#8965 {devel}[GCCcore/8.3.0] PCRE v8.43
  easybuild/easyconfigs/p/PCRE/PCRE-8.43-GCCcore-8.3.0.eb
Labels: update

#8928 {bio}[gompi/2019a] BLASR v5.3.3, pbcopper v1.3.0, pbbam v1.0.6
  easybuild/easyconfigs/b/BLASR/BLASR-5.3.3-gompi-2019a.eb
  easybuild/easyconfigs/p/pbbam/pbbam-1.0.6-gompi-2019a.eb
  easybuild/easyconfigs/p/pbcopper/pbcopper-1.3.0-gompi-2019a.eb
Labels: new, update

#8956 {devel}[system/system] ReFrame v2.19
  easybuild/easyconfigs/r/ReFrame/ReFrame-2.19.eb
Labels: update

#8842 {lib}[gompi/2019a] WebSocket++ v0.8.1
  easybuild/easyconfigs/w/WebSocket++/WebSocket++-0.7.0-cmake_noarch.patch
  easybuild/easyconfigs/w/WebSocket++/WebSocket++-0.7.0-disable-test_transport-test_transport_asio_timers.patch
  easybuild/easyconfigs/w/WebSocket++/WebSocket++-0.8.1-boost_1.70.patch
  easybuild/easyconfigs/w/WebSocket++/WebSocket++-0.8.1-cmake-configversion-compatibility-anynewerversion.patch
  easybuild/easyconfigs/w/WebSocket++/WebSocket++-0.8.1-fix_CMakeLists.txt_version_number.patch
  easybuild/easyconfigs/w/WebSocket++/WebSocket++-0.8.1-gompi-2019a.eb
Labels: new

#8957 add patch for gettext 0.19.8* to avoid picking up global git config that could break the installation
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-GCCcore-4.9.3.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-GCCcore-5.4.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016.04.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8-intel-2016b.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0-libxml2-2.9.7.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.1.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8.eb
  easybuild/easyconfigs/g/gettext/gettext-0.19.8_fix-git-config.patch
Labels: bug fix

#8962 {devel}[GCCcore/8.3.0] CMake v3.15.3
  easybuild/easyconfigs/c/CMake/CMake-3.15.3-GCCcore-8.3.0.eb
Labels: update

#8968 {vis}[GCCcore/8.3.0] GLib v2.62.0
  easybuild/easyconfigs/g/GLib/GLib-2.62.0-GCCcore-8.3.0.eb
Labels: update

#8982 add EBImage extension to easyconfig for R-bundle-Bioconductor 3.9
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.9-foss-2019a-R-3.6.0.eb
Labels: enhancement

#8964 {compiler}[GCCcore/8.3.0] LLVM v9.0.0
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.0-GCCcore-8.3.0.eb
Labels: update

#8981 {lang,lib}[GCCcore/8.3.0] libjpeg-turbo v2.0.3, NASM v2.14.02
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.3-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.14.02-GCCcore-8.3.0.eb
Labels: update

#8975 {lib}[GCCcore/8.3.0] libunwind v1.3.1
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-8.3.0.eb
Labels: update

#8949 {geo}[foss/2019a] GMT v5.4.5
  easybuild/easyconfigs/g/GMT/GMT-5.4.5-foss-2019a.eb
Labels: update

#8939 {bio}[gompi/2019a] Metaxa2 v2.2
  easybuild/easyconfigs/m/Metaxa2/Metaxa2-2.2-gompi-2019a.eb
Labels: new

#8986 add patch for PyTorch 1.2.0 to use version of torchvision that is compatible with Python 1.2.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_fix_torchvision_test.patch
Labels: bug fix

#8963 {lang}[GCCcore/8.3.0] Rust v1.37.0
  easybuild/easyconfigs/r/Rust/Rust-1.37.0-GCCcore-8.3.0.eb
Labels: update

#8991 {data}[foss/2019a] ITK-5.0.1: Clarify the comment regarding the optarch setting
  easybuild/easyconfigs/i/ITK/ITK-5.0.1-foss-2019a-Python-3.7.2.eb
Labels: bug fix

#8980 fix source_urls in GlimmerHMM easyconfigs
  easybuild/easyconfigs/g/GlimmerHMM/GlimmerHMM-3.0.4-foss-2016b.eb
  easybuild/easyconfigs/g/GlimmerHMM/GlimmerHMM-3.0.4-foss-2018b.eb
Labels: bug fix

#8990 {data}[GCCcore/8.2.0] Pysolar v0.8 w/ Python 3.7.2
  easybuild/easyconfigs/p/Pysolar/Pysolar-0.8-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#8993 fix homepage & description in easyconfig file for YAPS
  easybuild/easyconfigs/y/YAPS/YAPS-1.1.0-foss-2018b-R-3.5.1.eb
Labels: bug fix

#8994 {bio}[intel/2019a] YAPS v1.1.0
  easybuild/easyconfigs/y/YAPS/YAPS-1.1.0-intel-2019a-R-3.6.0.eb
Labels: update

#8976 {bio,data}[GCCcore/8.3.0] BioPerl v1.7.2, XML-LibXML v2.0201
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0201-GCCcore-8.3.0.eb
Labels: update

#9003 {devel}[GCCcore/8.3.0] SCons v3.1.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/s/SCons/SCons-3.1.1-GCCcore-8.3.0.eb
Labels: update

#8996 {bio}[GCC/8.3.0] Exonerate v2.4.0
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-8.3.0.eb
Labels: update

#9000 {bio}[GCC/8.3.0] SNAP v2013-11-29
  easybuild/easyconfigs/s/SNAP/SNAP-2013-11-29-GCC-8.3.0.eb
  easybuild/easyconfigs/s/SNAP/SNAP_2013-11-29_makefile_correction.patch
Labels: update

#8693 {tools}[dummy/] vsc-mympirun v4.1.9
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-4.1.9.eb
Labels: update

#9009 {devel}[GCCcore/8.3.0] DBus v1.13.12
  easybuild/easyconfigs/d/DBus/DBus-1.13.12-GCCcore-8.3.0.eb
Labels: update

#9002 {tools}[GCCcore/8.3.0] re2c v1.2.1
  easybuild/easyconfigs/r/re2c/re2c-1.2.1-GCCcore-8.3.0.eb
Labels: update

#8997 {bio}[gompi/2019b] HMMER v3.2.1
  easybuild/easyconfigs/h/HMMER/HMMER-3.2.1-gompi-2019b.eb
Labels: update

#8958 {lib}[fosscuda/2019a] TensorFlow v1.14.0 w/ Python 3.7.2
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0_fix-cuda-build.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0_fix-cuda-mpi.patch
Labels: update

#9010 add patch for PyTorch 1.2.0 to fix failing softmax test on Intel Sandy Bridge
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_fix-softmax-SandyBridge.patch
Labels: bug fix

#9013 {lib}[GCCcore/8.3.0] snappy v1.1.7
  easybuild/easyconfigs/s/snappy/snappy-1.1.7-GCCcore-8.3.0.eb
Labels: update

#9014 {lib}[GCCcore/8.3.0] double-conversion v3.1.4
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.4-GCCcore-8.3.0.eb
Labels: update

#9017 {devel}[GCCcore/8.3.0] PCRE2 v10.33
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.33-GCCcore-8.3.0.eb
Labels: update

#9020 {devel}[GCCcore/8.3.0] Doxygen v1.8.16
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.16-GCCcore-8.3.0.eb
Labels: update

#9018 {lib}[GCCcore/8.3.0] libevent v2.1.11
  easybuild/easyconfigs/l/libevent/libevent-2.1.11-GCCcore-8.3.0.eb
Labels: update

#9015 {lib}[GCCcore/8.3.0] NSPR v4.21, NSS v3.45
  easybuild/easyconfigs/n/NSPR/NSPR-4.21-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.45-GCCcore-8.3.0.eb
Labels: update

#8742 {lib}[GCCcore/8.2.0] libdap v3.20.4
  easybuild/easyconfigs/l/libdap/libdap-3.20.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libtirpc/libtirpc-1.1.4-GCCcore-8.2.0.eb
Labels: update

#9019 {data,tools}[GCCcore/8.3.0,gompi/2019b] HDF5 v1.10.5, Szip v2.1.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.5-gompi-2019b.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-8.3.0.eb
Labels: update

#8978 {devel}[gompi/2019b] Boost v1.71.0
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-gompi-2019b.eb
Labels: update

#9012 add check for http:// URLs in easyconfig files added/changed in PRs
  test/easyconfigs/easyconfigs.py
Labels: change, enhancement

#8999 {cae}[intel/2019a] OpenFOAM v2.2.x
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.2.x-intel-2019a.eb
  easybuild/easyconfigs/o/OpenFOAM/cleanup-OpenFOAM-2.2.x.patch
Labels: update

#9022 {vis}[GCCcore/8.3.0] FFmpeg v4.2.1, FriBidi v1.0.5, LAME v3.100, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20190925-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-8.3.0.eb
Labels: update

#8891 [fosscuda/2019a] PyTorch 1.2.0 and magma 2.5.1
  easybuild/easyconfigs/m/magma/magma-2.5.1-fosscuda-2019a.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-fosscuda-2019a-Python-3.7.2.eb
Labels: update

#9027 {chem}[intel/2019a] PLUMED v2.5.2 w/ Python 3.7.2
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.2-intel-2019a-Python-3.7.2.eb
Labels: update

#9032 {lang}[GCCcore/8.3.0] Nim v1.0.0
  easybuild/easyconfigs/n/Nim/Nim-1.0.0-GCCcore-8.3.0.eb
Labels: update

#9006 {data,math}[intel/2019a] GEOS v3.7.2, GDAL v3.0.0 w/ Python 3.7.2
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0_fix-python-CC-CXX.patch
  easybuild/easyconfigs/g/GEOS/GEOS-3.7.2-intel-2019a-Python-3.7.2.eb
Labels: update

#9011 {bio,lib}[GCCcore/8.3.0,gompi/2019b] BLAST+ v2.9.0, LMDB v0.9.24
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0-gompi-2019b.eb
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.24-GCCcore-8.3.0.eb
Labels: update

#8929 {math}[gompi/2019a] pbmm2 v1.1.0
  easybuild/easyconfigs/p/pbmm2/pbmm2-1.1.0-gompi-2019a.eb
Labels: new

#8985 {data}[intel/2019a] xarray v0.13.0 w/ Python 3.7.2
  easybuild/easyconfigs/x/xarray/xarray-0.13.0-intel-2019a-Python-3.7.2.eb
Labels: update

#8992 {vis}[GCCcore/8.3.0] Mesa v19.1.7
  easybuild/easyconfigs/m/Mesa/Mesa-19.1.7-GCCcore-8.3.0.eb
Labels: update

#9030 {vis}[GCCcore/8.2.0] Leptonica v1.78.0, tesseract v4.1.0
  easybuild/easyconfigs/l/Leptonica/Leptonica-1.78.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/t/tesseract/tesseract-4.1.0-GCCcore-8.2.0.eb
Labels: update

#8834 {math}[intel/2019a] cma v2.7.0 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/p/pycma/pycma-2.7.0-intel-2019a.eb
Labels: new

#8769 {perf}[foss/2019a,intel/2019a] mympingpong v0.8.0, mpi4py v3.0.2 w/ Python 2.7.15
  easybuild/easyconfigs/m/mpi4py/mpi4py-3.0.2-gompi-2019a-timed-pingpong.eb
  easybuild/easyconfigs/m/mpi4py/mpi4py-3.0.2-iimpi-2019a-timed-pingpong.eb
  easybuild/easyconfigs/m/mympingpong/mympingpong-0.8.0-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/m/mympingpong/mympingpong-0.8.0-intel-2019a-Python-2.7.15.eb
Labels: update

#8972 {bio}[GCCcore/8.3.0] GATK v4.1.3.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/g/GATK/GATK-4.1.3.0-GCCcore-8.3.0-Java-1.8.eb
Labels: update
