Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2019-12, with the labels that each got.

#9397 {bio}[iccifort/2019.5.281] fastp v0.20.0
  easybuild/easyconfigs/f/fastp/fastp-0.20.0-iccifort-2019.5.281.eb
Labels: update

#9403 {lib}[GCC/8.2.0-2.31.1] ncl v2.1.18
  easybuild/easyconfigs/n/ncl/ncl-2.1.18-GCC-8.2.0-2.31.1.eb
Labels: new

#9404 {bio}[gompi/2019a] GARLI v2.01
  easybuild/easyconfigs/g/GARLI/GARLI-2.01-gompi-2019a.eb
Labels: new

#9406 {chem}[intel/2019a] QuickFF v2.2.4 w/ Python 3.7.2
  easybuild/easyconfigs/q/QuickFF/QuickFF-2.2.4-intel-2019a-Python-3.7.2.eb
Labels: update

#9405 {bio}[gompi/2019a] HyPhy v2.5.1
  easybuild/easyconfigs/h/HyPhy/HyPhy-2.5.1-gompi-2019a.eb
Labels: new

#9418 update release notes for EasyBuild v4.1.0
  RELEASE_NOTES
  setup.py
Labels: update

#9411 {bio}[foss/2019a] Qualimap v2.2.1
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2019a-R-3.6.0.eb
Labels: new

#9421 {bio}[GCCcore/8.2.0] pyBigWig v0.3.17 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/p/pyBigWig/pyBigWig-0.3.17-GCCcore-8.2.0.eb
Labels: update

#9427 {bio}[GCCcore/8.3.0] gffread v0.11.6
  easybuild/easyconfigs/g/gffread/gffread-0.11.6-GCCcore-8.3.0.eb
Labels: update

#9429 {bio}[foss/2019b] GROMACS v2019.4
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-foss-2019b.eb
Labels: update

#9430 {bio}[foss/2019b,fosscuda/2019b] GROMACS v2019.3
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.3-foss-2019b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.3-fosscuda-2019b.eb
Labels: update

#9303 {bio}[foss/2018b] MACS2 v2.2.5 w/ Python 3.6.6
  easybuild/easyconfigs/m/MACS2/MACS2-2.2.5-foss-2018b-Python-3.6.6.eb
Labels: update

#9439 {tools}[dummy/dummy] EasyBuild v4.1.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.1.0.eb
Labels: update

#9422 {bio}[foss/2019a] bx-python v0.8.4 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/b/bx-python/bx-python-0.8.4-foss-2019a.eb
Labels: update

#9381 {bio}[GCC/8.2.0-2.31.1] TreeShrink v1.3.2 w/ Python 3.7.2
  easybuild/easyconfigs/t/TreeShrink/TreeShrink-1.3.2-GCC-8.2.0-2.31.1-Python-3.7.2.eb
Labels: new

#9441 {astro}[foss/2019a] CRPropa v3.1.5 w/ Python 3.7.2
  easybuild/easyconfigs/c/CRPropa/CRPropa-3.1.5-foss-2019a-Python-3.7.2.eb
Labels: new

#9444 sync develop with master and bump version to 4.1.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#9440 {cae}[foss/2019b] OpenFOAM v6
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-foss-2019b.eb
Labels: update

#9390 {cae}[foss/2019b] OpenFOAM 7
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-foss-2019b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-mpi-compilation.patch
Labels: update

#9449 {lib}[GCCcore/8.3.0] libxslt v1.1.34, lxml v4.4.2 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/lxml/lxml-4.4.2-GCCcore-8.3.0.eb
Labels: update

#9453 {tools}[GCCcore/8.2.0] cytoolz v0.10.1 w/ Python 3.7.2
  easybuild/easyconfigs/c/cytoolz/cytoolz-0.10.1-GCCcore-8.2.0-Python-3.7.2.eb
Labels: new

#9438 {chem}[GCC/8.3.0,iccifort/2019.5.281] IGMPlot v2.4.2
  easybuild/easyconfigs/i/IGMPlot/IGMPlot-2.4.2-GCC-8.3.0.eb
  easybuild/easyconfigs/i/IGMPlot/IGMPlot-2.4.2-iccifort-2019.5.281.eb
Labels: new

#9456 {bio}[GCC/8.2.0-2.31.1] barrnap v0.9
  easybuild/easyconfigs/b/barrnap/barrnap-0.9-GCC-8.2.0-2.31.1.eb
Labels: update

#9457 {bio}[GCC/8.2.0-2.31.1] seqtk v1.3
  easybuild/easyconfigs/s/seqtk/seqtk-1.3-GCC-8.2.0-2.31.1.eb
Labels: update

#9459 {bio}[GCC/8.2.0-2.31.1] fastp v0.20.0
  easybuild/easyconfigs/f/fastp/fastp-0.20.0-GCC-8.2.0-2.31.1.eb
Labels: update

#9460 {bio}[GCC/8.2.0-2.31.1] EMBOSS v6.6.0
  easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-GCC-8.2.0-2.31.1.eb
Labels: update

#9461 {bio}[foss/2019a] QUAST v5.0.2 w/ Python 3.7.2
  easybuild/easyconfigs/q/QUAST/QUAST-5.0.2-foss-2019a-Python-3.7.2.eb
Labels: update

#9462 {devel}[system/system] ReFrame v2.20
  easybuild/easyconfigs/r/ReFrame/ReFrame-2.20.eb
Labels: update

#9458 {bio}[GCC/8.2.0-2.31.1] KMC v3.1.1 w/ Python 3.7.2
  easybuild/easyconfigs/k/KMC/KMC-3.1.1-GCC-8.2.0-2.31.1-Python-3.7.2.eb
Labels: update

#9464 {numlib}[foss/2019b] arpack-ng v3.7.0
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.7.0-foss-2019b.eb
Labels: update

#9463 {numlib}[foss/2019b] SuiteSparse v5.6.0
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.6.0-foss-2019b-METIS-5.1.0.eb
Labels: update

#9447 {lang}[system/system] Anaconda2 and Anaconda3 version 2019.10
  easybuild/easyconfigs/a/Anaconda2/Anaconda2-2019.10.eb
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.10.eb
Labels: update

#9445 {cae}[foss/2018b] OpenFOAM v6: add warning about OF bug 3071
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-foss-2018b.eb
Labels: update

#9473 {lib,tools}[GCCcore/8.2.0,foss/2019a] snakemake v5.7.1, GitPython v3.0.3 w/ Python 3.7.2
  easybuild/easyconfigs/g/GitPython/GitPython-3.0.3-GCCcore-8.2.0-Python-3.7.2.eb
  easybuild/easyconfigs/s/snakemake/snakemake-5.7.1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/s/snakemake/snakemake-5.7.1_fix_jobs.patch
Labels: update

#9424 add missing 'wheel' extensions to Spark 2.4.0 easyconfig using intel/2018b toolchain
  easybuild/easyconfigs/s/Spark/Spark-2.4.0-intel-2018b-Hadoop-2.7-Java-1.8-Python-3.6.6.eb
Labels: bug fix

#9469 fix CMake 3.15.3 build on Power (+ enable building in parallel)
  easybuild/easyconfigs/c/CMake/CMake-3.15.3-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.15.3-fix-toc-flag.patch
Labels: bug fix

#9442 [CUDA] Add power9 support to CUDA 10.1 ECs
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.105-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.105.eb
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.168.eb
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.243-GCC-8.3.0.eb
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.243.eb
Labels: enhancement

#9474 {chem}[intel/2019b] MDTraj v1.9.3 w/ Python 3.7.4
  easybuild/easyconfigs/m/MDTraj/MDTraj-1.9.3-intel-2019b-Python-3.7.4.eb
Labels: update

#9470 {lib}[GCCcore/8.3.0] ICU v65.1
  easybuild/easyconfigs/i/ICU/ICU-65.1-GCCcore-8.3.0.eb
Labels: update

#9467 {chem,math}[intel/2019b] yaff v1.6.0, molmod v1.4.5 w/ Python 3.7.4
  easybuild/easyconfigs/m/molmod/molmod-1.4.5-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-intel-2019b-Python-3.7.4.eb
Labels: update

#8748 {vis}[system] Fiji v20170530, Fiji v20191119-2057
  easybuild/easyconfigs/f/Fiji/Fiji-20170530.eb
  easybuild/easyconfigs/f/Fiji/Fiji-20191119-2057.eb
Labels: new

#9479 add missing wcwidth extension to Python 2.7.15 + 2.7.16 easyconfigs & enable 'pip check' in sanity check
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0.eb
Labels: bug fix

#9492 disable running of 'sudo apt-get update' in GitHub CI config, since it's failing (and we don't really need it)
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#9489 {vis}[GCCcore/8.2.0] OpenSlide v3.4.1
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1-GCCcore-8.2.0.eb
Labels: new

#9494 {data}[gompic/2019b,iimpi/2019b,iimpic/2019b] netCDF v4.7.1 (+ missing HDF5 v1.10.5)
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.5-iimpic-2019b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.1-gompic-2019b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.1-iimpi-2019b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.1-iimpic-2019b.eb
Labels: update

#9480 {bio,vis}[intel/2019b] deepTools v3.3.1, plotly.py v4.4.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/d/deepTools/deepTools-3.3.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/plotly.py/plotly.py-4.4.1-intel-2019b.eb
Labels: update

#9472 {devel}[GCCcore/8.3.0] texinfo v6.7
  easybuild/easyconfigs/t/texinfo/texinfo-6.7-GCCcore-8.3.0.eb
Labels: update

#9493 {vis}[foss/2019b] torchvision 0.4.2 w/ Python 3.7.4 (+ Pillow-SIMD dep)
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-6.0.x.post0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.4.2-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#7085 {geo}[*/2018b] WRF + WPS 4.0.1 (intel/2018b) + 4.0.2 (foss/2018b)
  easybuild/easyconfigs/w/WPS/WPS-4.0.1-intel-2018b-dmpar.eb
  easybuild/easyconfigs/w/WPS/WPS-4.0.1_find-wrfdir.patch
  easybuild/easyconfigs/w/WPS/WPS-4.0.2-foss-2018b-dmpar.eb
  easybuild/easyconfigs/w/WPS/WPS-4.0.2_find-wrfdir.patch
  easybuild/easyconfigs/w/WPS/WPSv4_netCDF-Fortran_seperate_path.patch
  easybuild/easyconfigs/w/WRF/WRF-4.0.1-intel-2018b-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-4.0.2-foss-2018b-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRFv4_netCDF-Fortran_separate_path.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#9496 {tools}[GCCcore/8.3.0] tcsh v6.22.02
  easybuild/easyconfigs/t/tcsh/tcsh-6.22.02-GCCcore-8.3.0.eb
Labels: update

#9497 {data}[iimpi/2019b] netCDF-Fortran v4.5.2
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-iimpi-2019b.eb
Labels: update

#9471 {lib}[GCCcore/8.3.0] LibTIFF v4.1.0
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.1.0-GCCcore-8.3.0.eb
Labels: update

#9490 {vis}[GCCcore/8.2.0] pydicom v1.2.2 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/p/pydicom/pydicom-1.2.2-GCCcore-8.2.0.eb
Labels: update

#9514 {vis}[GCCcore/8.3.0] cairo v1.16.0, pixman v0.38.4
  easybuild/easyconfigs/c/cairo/cairo-1.16.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/pixman/pixman-0.38.4-GCCcore-8.3.0.eb
Labels: update

#9510 {lib}[GCCcore/8.3.0] PROJ v6.2.1
  easybuild/easyconfigs/p/PROJ/PROJ-6.2.1-GCCcore-8.3.0.eb
Labels: update

#9508 {devel}[GCCcore/8.3.0] makedepend v1.0.6, xproto v7.0.31
  easybuild/easyconfigs/m/makedepend/makedepend-1.0.6-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-8.3.0.eb
Labels: update

#9507 {phys}[GCCcore/8.3.0] UDUNITS v2.2.26
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.3.0.eb
Labels: update

#9506 {data}[GCCcore/8.3.0] g2clib v1.6.0, g2lib v3.1.0
  easybuild/easyconfigs/g/g2clib/g2clib-1.6.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/g2lib/g2lib-3.1.0-GCCcore-8.3.0.eb
Labels: update

#9505 {data}[GCCcore/8.3.0] HDF v4.2.14
  easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-8.3.0.eb
Labels: update

#9504 {numlib}[GCC/8.3.0,iccifort/2019.5.281] GSL v2.6
  easybuild/easyconfigs/g/GSL/GSL-2.6-GCC-8.3.0.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-iccifort-2019.5.281.eb
Labels: update

#9518 {chem}[system/system] ORCA v4.2.1
  easybuild/easyconfigs/o/ORCA/ORCA-4.2.1-gompi-2019b.eb
Labels: update

#9525 {numlib}[intel/2019b] FFTW v3.3.8
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-intel-2019b.eb
Labels: update

#9521 {vis}[GCCcore/8.2.0] PyCairo v1.18.0 w/ Python 3.7.2
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.18.0-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#9483 {bio}[foss/2019a] CrossMap v0.3.9 w/ Python 3.7.2
  easybuild/easyconfigs/c/CrossMap/CrossMap-0.3.9-foss-2019a-Python-3.7.2.eb
Labels: new

#9454 add missing OS dependencies in Java 1.8 easyconfig used on POWER systems
  easybuild/easyconfigs/j/Java/Java-1.8_191-b26-OpenJDK.eb
Labels: bug fix

#9435 {math}[foss/2018b,intel/2018b] Gurobi v9.0.0 w/ Python 3.6.6
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.0-intel-2018b-Python-3.6.6.eb
Labels: update

#9466 {tools}[intel/2019b] worker v1.6.11
  easybuild/easyconfigs/w/worker/worker-1.6.11-intel-2019b.eb
Labels: update

#9539 {lib}[GCCcore/8.2.0] libiconv v1.16
  easybuild/easyconfigs/l/libiconv/libiconv-1.16-GCCcore-8.2.0.eb
Labels: update

#9532 {lib}[GCCcore/8.3.0] freeglut v3.2.1
  easybuild/easyconfigs/f/freeglut/freeglut-3.2.1-GCCcore-8.3.0.eb
Labels: update

#9534 {lib}[GCCcore/8.3.0] Qwt v6.1.4
  easybuild/easyconfigs/q/Qwt/Qwt-6.1.4-GCCcore-8.3.0.eb
Labels: update

#9516 require that sanity_pip_check is enabled in new/changed easyconfigs
  test/easyconfigs/easyconfigs.py
Labels: change

#9533 {lib}[GCCcore/8.3.0] libgd v2.2.5
  easybuild/easyconfigs/l/libgd/libgd-2.2.5-GCCcore-8.3.0.eb
Labels: update

#9485 {bio}[system/system] tbl2asn v25.8
  easybuild/easyconfigs/t/tbl2asn/tbl2asn-25.8-linux64.eb
Labels: update

#9540 {lib}[GCCcore/8.2.0] libxml2-python v2.9.8 w/ Python 3.7.2
  easybuild/easyconfigs/l/libxml2-python/libxml2-python-2.9.8-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#9551 {math}[GCC/8.3.0] lpsolve v5.5.2.5
  easybuild/easyconfigs/l/lpsolve/lpsolve-5.5.2.5-GCC-8.3.0.eb
Labels: update

#9531 {numlib}[GCCcore/8.3.0] NLopt v2.6.1
  easybuild/easyconfigs/n/NLopt/NLopt-2.6.1-GCCcore-8.3.0.eb
Labels: update

#9553 {devel}[GCCcore/8.3.0] Faber v0.3 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/f/Faber/Faber-0.3-GCCcore-8.3.0.eb
Labels: new

#9535 {bio}[foss/2019b] MRtrix v3.0_RC4 w/ Python 2.7.16
  easybuild/easyconfigs/m/MRtrix/MRtrix-3.0_RC4-foss-2019b-Python-2.7.16.eb
Labels: update

#9511 {devel}[GCCcore/8.3.0] SWIG v4.0.1
  easybuild/easyconfigs/s/SWIG/SWIG-4.0.1-GCCcore-8.3.0.eb
Labels: update

#9502 {geo}[intel/2019b] WRF v4.1.3 + WPS v4.1
  easybuild/easyconfigs/t/time/time-1.9-GCCcore-8.3.0.eb
  easybuild/easyconfigs/w/WPS/WPS-4.1-intel-2019b-dmpar.eb
  easybuild/easyconfigs/w/WPS/WPS-4.1_netCDF-Fortran_seperate_path.patch
  easybuild/easyconfigs/w/WRF/WRF-4.1.3-intel-2019b-dmpar.eb
Labels: update

#9526 {vis}[GCCcore/8.2.0] GtkSourceView v3.24.11, GtkSourceView v4.4.0
  easybuild/easyconfigs/g/GtkSourceView/GtkSourceView-3.24.11-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GtkSourceView/GtkSourceView-4.4.0-GCCcore-8.2.0.eb
Labels: new

#9550 {compiler}[system/system] iccifort v2020.0.166
  easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166_no_mpi_rt_dependency.patch
Labels: update

#9499 {vis}[GCCcore/8.2.0] openslide-python v1.1.1 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/o/openslide-python/openslide-python-1.1.1-GCCcore-8.2.0.eb
Labels: new

#9555 {data}[GCCcore/8.3.0] TinyDB v3.15.2 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/t/TinyDB/TinyDB-3.15.2-GCCcore-8.3.0.eb
Labels: new

#9378 {bio}[foss/2018b] FSL 6.0.2
  easybuild/easyconfigs/f/FSL/FSL-6.0.1_Fix_fsl_exec_script.patch
  easybuild/easyconfigs/f/FSL/FSL-6.0.2-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/f/FSL/FSL-6.0.2_Build_extras.patch
  easybuild/easyconfigs/f/FSL/FSL-6.0.2_Makefile_fixes.patch
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.49.7-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libxml++/libxml++-2.40.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/q/Qwt/Qwt-6.1.4-foss-2018b.eb
Labels: update

#9562 use NCCL for GPU ops in Horovod 0.18.2 easyconfig
  easybuild/easyconfigs/h/Horovod/Horovod-0.18.2-fosscuda-2019b-TensorFlow-2.0.0-Python-3.7.4.eb
Labels: enhancement

#9569 add correct 'old-versions' source URL to all Mesa easyconfigs
  easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-foss-2016a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-gimkl-2.11.5.eb
  easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-intel-2016a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-11.2.1-foss-2016a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-11.2.1-intel-2016a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-12.0.2-foss-2016b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-12.0.2-intel-2016b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.0.2-foss-2017a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.0.2-intel-2017a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.2.4-intel-2017b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.2.4-intelcuda-2017b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.2.5-foss-2017b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.2.5-fosscuda-2017b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-foss-2018a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-fosscuda-2018a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-intel-2018a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.3.6-iomkl-2018a.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-foss-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-fosscuda-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-intel-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.0.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.1.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.2.1-GCCcore-8.3.0.eb
Labels: bug fix

#9565 {data}[GCCcore/8.3.0] Globus-CLI v1.11.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/g/Globus-CLI/Globus-CLI-1.11.0-GCCcore-8.3.0.eb
Labels: new

#9574 {data}[intel/2019a] GDAL v3.0.0 w/ Python 2.7.15
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-intel-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.7.2-intel-2019a-Python-2.7.15.eb
Labels: update

#9573 {mpi}[iccifort/2020.0.166] impi v2019.6.166
  easybuild/easyconfigs/i/iimpi/iimpi-2020.00.eb
  easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166.eb
Labels: update

#9576 only require sanity_pip_check if use_pip is enabled too (fixes #9563)
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#9570 {tools}[intel/2019b] CDO v1.9.8, YAXT v0.6.2, ecCodes v2.15.0
  easybuild/easyconfigs/c/CDO/CDO-1.9.8-intel-2019b.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.15.0-iimpi-2019b.eb
  easybuild/easyconfigs/y/YAXT/YAXT-0.6.2-iimpi-2019b.eb
Labels: update

#9572 add missing checksums for Armadillo
  easybuild/easyconfigs/a/Armadillo/Armadillo-7.600.2-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/a/Armadillo/Armadillo-7.800.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/a/Armadillo/Armadillo-7.950.1-intel-2016b-Python-2.7.12.eb
Labels: bug fix

#9577 Revert "WORKAROUND: Remove check for Python suffix to make CI pass fo…
  test/easyconfigs/easyconfigs.py
Labels: change

#9578 fix source URLs in xorg-macros easyconfigs
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-foss-2016a.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-foss-2016b.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-gimkl-2.11.5.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-intel-2016a.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-intel-2016b.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-7.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-7.3.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-8.3.0.eb
Labels: bug fix

#9548 fix lpsymphony extension for R-bundle-Bioconductor
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.9-foss-2019a-R-3.6.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/lpsymphony-1.12.0_zlib.patch
Labels: bug fix

#9575 {numlib,toolchain}[system/system] imkl v2020.0.166, intel v2020.00
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2020.00.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.0.166-iimpi-2020.00.eb
  easybuild/easyconfigs/i/intel/intel-2020.00.eb
Labels: update

#9522 {vis}[GCCcore/8.2.0] PyGObject v3.34.0 w/ Python 3.7.2
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.34.0-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#9455 fix build of recent Bazel versions on Power9 + stick to Java/1.8 as dependency
  easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1_fix-zip-d-on-power.patch
  easybuild/easyconfigs/b/Bazel/Bazel-1.1.0-GCCcore-8.3.0.eb
Labels: bug fix

#9546 use xorg-macros as dependency in X11 easyconfigs (rather than installing it as a bundle component)
  easybuild/easyconfigs/x/X11/X11-20160819-foss-2016b.eb
  easybuild/easyconfigs/x/X11/X11-20160819-intel-2016b.eb
  easybuild/easyconfigs/x/X11/X11-20170129-GCCcore-6.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20170314-GCCcore-6.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20171023-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/X11/X11-20180131-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/X11/X11-20180604-GCCcore-7.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20190311-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/X11/X11-20190717-GCCcore-8.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#9579 also define $AUGUSTUS_BIN_PATH and $AUGUSTUS_SCRIPTS_PATH in generated module file for AUGUSTUS
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.2.3-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3-foss-2018a.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.2-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.2-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.2-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.2-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.2-intel-2019a.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#9552 {lib}[gompi/2019b] Boost.Python v1.71.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/b/Boost.Python/Boost-1.71.0_fix-Python3.patch
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-gompi-2019b.eb
Labels: update

#9584 adding easyconfigs: Java-1.8.0_231.eb
  easybuild/easyconfigs/j/Java/Java-1.8.0_231.eb
Labels: update

#9585 update Java/1.8 to Java/1.8.0_231 (for x86_64)
  easybuild/easyconfigs/j/Java/Java-1.8.eb
Labels: update

#9529 {vis}[GCCcore/8.2.0] gsettings-desktop-schemas v3.34.0
  easybuild/easyconfigs/g/gsettings-desktop-schemas/gsettings-desktop-schemas-3.34.0-GCCcore-8.2.0.eb
Labels: new

#9560 {bio}[foss+fosscuda/2019a] CSBDeep v0.4.1 w/ Python 3.7.2
  easybuild/easyconfigs/c/CSBDeep/CSBDeep-0.4.1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/c/CSBDeep/CSBDeep-0.4.1-fosscuda-2019a-Python-3.7.2.eb
Labels: new

#9587 add missing jupyter_contrib_core extension for IPython 7.7.0+ + consistently include jupyter_nbextensions_configurator extension
  easybuild/easyconfigs/i/IPython/IPython-7.7.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.7.0-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.7.0-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.9.0-foss-2019b-Python-3.7.4.eb
Labels: bug fix

#9537 {lib}[GCCcore/8.3.0] jemalloc v5.2.1
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.2.1-GCCcore-8.3.0.eb
Labels: update

#9580 {lib}[GCCcore/8.3.0] libmatheval v1.1.11, Guile v1.8.8, libunistring v0.9.10, ...
  easybuild/easyconfigs/g/Guile/Guile-1.8.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/gc/gc-7.6.12-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libunistring/libunistring-0.9.10-GCCcore-8.3.0.eb
Labels: update

#9541 {tools}[GCCcore/8.2.0] ITSTool v2.0.6 w/ Python 3.7.2
  easybuild/easyconfigs/i/ITSTool/ITSTool-2.0.6-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#9509 {vis}[intel/2019b] ncview v2.1.7
  easybuild/easyconfigs/n/ncview/ncview-2.1.7-intel-2019b.eb
Labels: update

#9488 {compiler}[foss/2019b] pythran v0.9.4.post1 w/ Python 3.7.4
  easybuild/easyconfigs/n/networkx/networkx-2.4-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/pythran/pythran-0.9.4.post1-foss-2019b-Python-3.7.4.eb
Labels: new, update

#9484 {bio}[gompi/2019a] prokka v1.14.5
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019a.eb
Labels: update

#9419 {chem}[iccifort/2019.5.281] NCIPLOT v4.0-20190718
  easybuild/easyconfigs/n/NCIPLOT/NCIPLOT-4.0-20190718-iccifort-2019.5.281.eb
Labels: new

#9512 {data,lib,math}[GCCcore/8.3.0,iccifort/2019.5.281,intel/2019b] GDAL v3.0.2, GEOS v3.8.0, libgeotiff v1.5.1 w/ Python 3.7.4
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.8.0-iccifort-2019.5.281-Python-3.7.4.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.5.1-GCCcore-8.3.0.eb
Labels: update

#9366 fix remote launch of broker and workers for SCOOP
  easybuild/easyconfigs/s/SCOOP/SCOOP-0.7.1.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/s/SCOOP/SCOOP-0.7.1.1_fix-remote-launch.patch
Labels: bug fix

#9323 {bio,lib}[GCC/8.2.0-2.31.1] CNT-ILP v20171031, LEMON v1.3.1
  easybuild/easyconfigs/c/CNT-ILP/CNT-ILP-20171031-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/LEMON/LEMON-1.3.1-GCC-8.2.0-2.31.1.eb
Labels: new

#9571 {bio,devel,lib,vis}[GCCcore/8.3.0] FSL v6.0.3, libxml++ v2.40.1, GLibmm v2.49.7, ...
  easybuild/easyconfigs/f/FSL/FSL-6.0.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.49.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libxml++/libxml++-2.40.1-GCCcore-8.3.0.eb
Labels: update

#9536 {bio}[GCC/8.2.0-2.31.1] Jellyfish v2.3.0
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-8.2.0-2.31.1.eb
Labels: update
