Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2019-05, with the labels that each got.

#8024 {tools}[fosscuda/2018b] nvtop v1.0.0
  easybuild/easyconfigs/n/nvtop/nvtop-1.0.0-fosscuda-2018b.eb
Labels: new

#8068 {vis}[GCCcore/8.2.0] FFmpeg v4.1.3, x264 v20190413, LAME v3.100, Yasm v1.3.0, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.1.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/x264/x264-20190413-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/x265/x265-3.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-8.2.0.eb
Labels: update

#8196 {devel}[gompi/2019a,gompic/2019a,iimpi/2019a,iimpic/2019a] Boost v1.70.0
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-gompi-2019a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-gompic-2019a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-iimpi-2019a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-iimpic-2019a.eb
Labels: update

#7136 {math,numlib}[intel/2018a] Trilinos v12.12.1, ParMETIS v4.0.3
  easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-intel-2018a-Python-3.6.4.eb
Labels: update

#8194 {numlib}[intel/2019a] FFTW v3.3.8
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-intel-2019a.eb
Labels: update

#8205 {numlib}[foss/2019a,intel/2019a] SuiteSparse v5.4.0
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.4.0-foss-2019a-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.4.0-intel-2019a-METIS-5.1.0.eb
Labels: update

#8204 {numlib}[foss/2019a,intel/2019a] Hypre v2.15.1
  easybuild/easyconfigs/h/Hypre/Hypre-2.15.1-foss-2019a.eb
  easybuild/easyconfigs/h/Hypre/Hypre-2.15.1-intel-2019a.eb
Labels: update

#7761 {chem}[foss-2018b] PCMSolver-1.2.3 w/ Python 3.6.6
  easybuild/easyconfigs/p/PCMSolver/PCMSolver-1.2.3-foss-2018b-Python-3.6.6.eb
Labels: update

#8198 {lib}[intel/2019a] pyFFTW v0.11.1 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/p/pyFFTW/pyFFTW-0.11.1-intel-2019a.eb
Labels: new

#7229 {bio}[fosscuda/2017b,intelcuda/2017b] GROMACS v2018.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-fosscuda-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-intelcuda-2017b.eb
Labels: update

#8192 {vis}[intel/2019a] NiBabel v2.4.0 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/n/NiBabel/NiBabel-2.4.0-intel-2019a.eb
Labels: update

#8177 {tools}[intel/2018b] simpy v3.0.11 w/ Python 3.6.6
  easybuild/easyconfigs/s/simpy/simpy-3.0.11-intel-2018b-Python-3.6.6.eb
Labels: new

#8105 {vis}[foss/2018b] LUSCUS v0.8.6
  easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6-foss-2018b.eb
Labels: update

#8220 allow use of 'use_pip = False' in easyconfigs if pip doesn't work
  test/easyconfigs/easyconfigs.py
Labels: change

#7228 {bio}[foss/2017b,intel/2017b] GROMACS v2018.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-foss-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-intel-2017b.eb
Labels: update

#8221 Add gettext as build dep for Mesa v19.0.1
  easybuild/easyconfigs/m/Mesa/Mesa-19.0.1-GCCcore-8.2.0.eb
Labels: bug fix

#8099 Use kernel in installation path with IRkernel
  easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-foss-2017b-R-3.4.3-Python-2.7.14.eb
  easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-intel-2017b-R-3.4.3-Python-2.7.14.eb
Labels: bug fix

#8211 {tools}[intel/2019a] networkx v2.3 w/ Python 3.7.2
  easybuild/easyconfigs/n/networkx/networkx-2.3-intel-2019a-Python-3.7.2.eb
Labels: update

#8222 Add X11 dependency for Gdk-Pixbuf v2.38.1
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-GCCcore-8.2.0.eb
Labels: bug fix

#8133 {devel}[GCCcore/8.2.0] pkgconfig v1.5.1
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.5.1-GCCcore-8.2.0-python.eb
Labels: update

#8206 {lib}[GCCcore/8.2.0] fmt v5.3.0
  easybuild/easyconfigs/f/fmt/fmt-5.3.0-GCCcore-8.2.0.eb
Labels: update

#8210 {lib}[GCCcore/8.2.0] PyYAML v5.1 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-5.1-GCCcore-8.2.0.eb
Labels: update

#8208 {lib}[GCCcore/7.3.0] fmt v5.3.0
  easybuild/easyconfigs/f/fmt/fmt-5.3.0-GCCcore-7.3.0.eb
Labels: update

#8142 {data}[foss/2018b] scikit-multilearn v0.2.0
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.67.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/c/CGAL/CGAL-4.11.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/c/cairomm/cairomm-1.12.2-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/graph-tool/graph-tool-2.27-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/s/scikit-multilearn/scikit-multilearn-0.2.0-foss-2018b-Python-3.6.6.eb
Labels: new, update

#8201 {devel}[GCCcore/8.2.0] Qt5 v5.12.3
  easybuild/easyconfigs/q/Qt5/Qt5-5.12.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.12.3_fix-avx2.patch
Labels: update

#8226 {vis}[GCCcore/8.2.0] Harfbuzz v2.4.0, Add missing dependency on ICU.
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.4.0-GCCcore-8.2.0.eb
Labels: bug fix, enhancement

#8118 {lib}[GCC/8.2.0-2.31.1] WebKitGTK+ v2.24.1
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.24.1-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.24.1_turn_off_various_problematic_features.patch
Labels: new

#6426 {devel} [foss/2018a] libutempter v1.1.6
  easybuild/easyconfigs/l/libutempter/libutempter-1.1.6.2-GCC-6.4.0-2.28.eb
Labels: new

#7525 {vis} [intel-2018a] PyQtGraph v0.10.0 - Python/3.6.4
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-intel-2018a-Python-3.6.4.eb
Labels: new

#7474 {bio}[foss/2018b] FastQ_Screen v0.13.0
  easybuild/easyconfigs/f/FastQ_Screen/FastQ_Screen-0.13.0-foss-2018b-Perl-5.28.0.eb
  easybuild/easyconfigs/g/GDGraph/GDGraph-1.54-foss-2018b-Perl-5.28.0.eb
Labels: update

#8234 fix homepage/description in OrthoFinder easyconfig
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.2.7-intel-2018a-Python-2.7.14.eb
Labels: bug fix

#7465 {bio,lib}[GCCcore/7.3.0] FASTX-Toolkit v0.0.14, libgtextutils v0.7
  easybuild/easyconfigs/f/FASTX-Toolkit/FASTX-Toolkit-0.0.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/f/FASTX-Toolkit/FASTX-Toolkit-0.0.14_fix-gcc7.patch
  easybuild/easyconfigs/l/libgtextutils/libgtextutils-0.7-GCCcore-7.3.0.eb
Labels: update

#8216 {toolchain}[dummy/dummy] gomkl v2018b
  easybuild/easyconfigs/g/gomkl/gomkl-2018b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-gomkl-2018b.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.3.222-gompi-2018b.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#8178 {tools}[intel/2018b] RBFOpt v4.1.1
  easybuild/easyconfigs/r/RBFOpt/RBFOpt-4.1.1-intel-2018b-Python-3.6.6.eb
Labels: new

#8191 {data}[intel/2019a] scikit-learn v0.20.3 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.3-intel-2019a.eb
Labels: update

#8207 {phys}[foss/2019a] ADDA v1.3b4
  easybuild/easyconfigs/a/ADDA/ADDA-1.3b4-foss-2019a.eb
  easybuild/easyconfigs/a/ADDA/ADDA-1.3b4_add_install_target.patch
  easybuild/easyconfigs/a/ADDA/ADDA-1.3b4_fix_bad_cmd_name_code.patch
  easybuild/easyconfigs/a/ADDA/ADDA-1.3b4_remove_bad_MPI_detection_code.patch
  easybuild/easyconfigs/a/ADDA/ADDA-1.3b4_remove_xxOPTSFILE_targets.patch
Labels: new

#8203 {numlib}[foss/2019a,intel/2019a] PETSc v3.11.1
  easybuild/easyconfigs/p/PETSc/PETSc-3.11.1-foss-2019a.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.11.1-intel-2019a.eb
Labels: update

#8233 {lib}[intel/2018b] scp v0.13.2 w/ Python 2.7.15
  easybuild/easyconfigs/s/scp/scp-0.13.2-intel-2018b-Python-2.7.15.eb
Labels: update

#8200 Added support for pkg-config via pkgconfig/bzip2.pc
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2015.06.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2015.11.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2016.03.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.1.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.2.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.4.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.9.2.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-4.9.3.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-5.4.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-6.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-6.4.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-7.2.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-7.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2014b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015.05.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016.04.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gimkl-2.11.5.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gimkl-2017a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-gompi-1.5.16.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.4.10.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.5.14.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.5.16.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-goolf-1.7.20.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.2.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.4.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-5.5.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-6.2.5.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-ictce-7.1.2.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2014.06.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2014b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2015a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2015b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016.02-GCC-4.9.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016a.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016b.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-iomkl-2016.07.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-iomkl-2016.09-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-pkgconfig.patch
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.6.eb
Labels: enhancement

#8218 {toolchain}[dummy/dummy] gomkl v2019a
  easybuild/easyconfigs/g/gomkl/gomkl-2019a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-gomkl-2019a.eb
  easybuild/easyconfigs/i/imkl/imkl-2019.1.144-gompi-2019a.eb
Labels: new

#8240 {math}[GCCcore/8.2.0] MPFR v4.0.2
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.2-GCCcore-8.2.0.eb
Labels: update

#8230 {vis}[fosscuda/2018b] gnuplot v5.2.6
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6-fosscuda-2018b.eb
  easybuild/easyconfigs/n/nettle/nettle-3.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-fosscuda-2018b.eb
Labels: update

#8227 {numlib}[GCC/8.2.0-2.31.1] OpenBLAS v0.3.5, disable the AVX512 DGEMM kernel
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5_disable_AVX512_dgemm_kernel.patch
Labels: bug fix

#8239 {lang}[GCCcore/8.2.0] Ruby v2.6.3
  easybuild/easyconfigs/r/Ruby/Ruby-2.6.3-GCCcore-8.2.0.eb
Labels: update

#8236 {toolchains} GCC 9.1.0 + binutils 2.32
  easybuild/easyconfigs/b/Bison/Bison-3.3.2-GCCcore-9.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-9.1.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-9.1.0.eb
  easybuild/easyconfigs/g/GCC/GCC-9.1.0-2.32.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.1.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.10-GCCcore-9.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-9.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-9.1.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#8225 {vis}[foss/2019a,intel/2019a] VTK v8.2.0 w/ Python 3.7.2
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-intel-2019a-Python-3.7.2.eb
Labels: update

#8243 fix source URLs for libcerf 1.7
  easybuild/easyconfigs/l/libcerf/libcerf-1.7-GCCcore-7.3.0.eb
Labels: bug fix

#8213 {bio}[GCCcore/7.3.0] ARWEN v1.2.3
  easybuild/easyconfigs/a/ARWEN/ARWEN-1.2.3-GCCcore-7.3.0.eb
Labels: new

#8212 {bio}[foss/2018b] MEGAHIT v1.1.4 w/ Python 3.6.6
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.1.4-foss-2018b-Python-3.6.6.eb
Labels: update

#8217 {devel,lib}[GCCcore/8.2.0] freeglut v3.0.0, glew v2.1.0
  easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/glew/glew-2.1.0-GCCcore-8.2.0.eb
Labels: update

#8127 {lang}[dummy/dummy] Anaconda2 v2019.03, Anaconda3 v2019.03
  easybuild/easyconfigs/a/Anaconda2/Anaconda2-2019.03.eb
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.03.eb
Labels: update

#8246 $GI_TYPELIB_PATH must be set for GTK+
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.28-intel-2016a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.30-foss-2016a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.30-intel-2016a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-foss-2016b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-intel-2016b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-intel-2017a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2017b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2017b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2018a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.22.30-fosscuda-2018b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.8-GCCcore-8.2.0.eb
Labels: bug fix

#8199 {bio}[fosscuda/2019a] GROMACS v2019.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.2-fosscuda-2019a.eb
Labels: update

#8244 {vis}[GCCcore/8.2.0] PyQt5 v5.12.1 w/ Python 3.7.2
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.12.1-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#8135 {data}[foss/2019a,fosscuda/2019a,intel/2019a,intelcuda/2019a] h5py v2.9.0
  easybuild/easyconfigs/h/h5py/h5py-2.9.0-foss-2019a.eb
  easybuild/easyconfigs/h/h5py/h5py-2.9.0-fosscuda-2019a.eb
  easybuild/easyconfigs/h/h5py/h5py-2.9.0-intel-2019a.eb
  easybuild/easyconfigs/h/h5py/h5py-2.9.0-intelcuda-2019a.eb
Labels: update

#8250 {tools}[intel/2019a] simpy v3.0.11 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/s/simpy/simpy-3.0.11-intel-2019a.eb
Labels: update

#8090 {lib}[GCCcore/7.3.0] lz4 v1.9.0
  easybuild/easyconfigs/l/lz4/lz4-1.9.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.9.0_fix_test.patch
Labels: update

#8224 GRASS: add zstd compression, {lib}[foss/2018b] zstd v1.4.0
  easybuild/easyconfigs/g/GRASS/GRASS-7.6.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/z/zstd/zstd-1.4.0-foss-2018b.eb
Labels: enhancement, update

#8162 {devel}[GCCcore/8.2.0] protobuf v3.7.1
  easybuild/easyconfigs/p/protobuf/protobuf-3.7.1-GCCcore-8.2.0.eb
Labels: update

#8215 {tools}[GCCcore/8.2.0] deepdiff v4.0.6 w/ Python 3.7.2
  easybuild/easyconfigs/d/deepdiff/deepdiff-4.0.6-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#8247 Perl: add Parallel::ForkManager
  easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.28.1-GCCcore-8.2.0.eb
Labels: enhancement

#8008 {vis}[foss/2018b] VirtualGL v2.6.1
  easybuild/easyconfigs/v/VirtualGL/VirtualGL-2.6.1-foss-2018b.eb
Labels: new

#7818 {tools}[foss/2018b] NCO v4.7.9, ANTLR v2.7.7, libdap v3.20.3
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-foss-2018b.eb
  easybuild/easyconfigs/l/libdap/libdap-3.20.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NCO/NCO-4.7.9-foss-2018b.eb
Labels: update

#8258 replace LibUUID dependencies with util-linux (cfr. #6963)
  easybuild/easyconfigs/d/davix/davix-0.6.6-intel-2017a.eb
  easybuild/easyconfigs/l/libdap/libdap-3.18.1-foss-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/l/libdap/libdap-3.18.1-intel-2017a.eb
  easybuild/easyconfigs/l/libdap/libdap-3.19.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libdap/libdap-3.19.1-foss-2017b.eb
  easybuild/easyconfigs/l/libdap/libdap-3.19.1-intel-2017b.eb
  easybuild/easyconfigs/l/libdap/libdap-3.20.3-GCCcore-7.3.0.eb
Labels: bug fix

#8048 add an additional env variable $GRACE_HOME to Grace easyconfigs, so that font dir can be located
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2017b-5build1.eb
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2018a-5build1.eb
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2017b-5build1.eb
Labels: bug fix

#8251 temporarily only test with Python 2.6 + Lmod
  .travis.yml
Labels: change, merge sprint

#8238 {bio}[intel/2018b] MAFFT v7.427
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.427-intel-2018b-with-extensions.eb
Labels: update

#8255 {tools}[intel/2019a] memory-profiler v0.55.0 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/m/memory-profiler/memory-profiler-0.55.0-intel-2019a.eb
Labels: new

#8253 {vis}[intel/2019a] PyQtGraph v0.10.0 w/ Python 3.7.2
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-intel-2019a-Python-3.7.2.eb
Labels: update

#8131 fix conflict with easybuild/system curl for SAMtools
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.4-foss-2016b.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.4-goolf-1.4.10.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.4-intel-2016b.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.4-intel-2017a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.4.1-intel-2017a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.5-foss-2016b.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.5-intel-2017a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.6-foss-2017a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.6-intel-2017b.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.7-foss-2018a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.7-intel-2018a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.8-intel-2018a.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.9-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.9-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.9-foss-2018b.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.9-intel-2018b.eb
Labels: bug fix

#8214 {chem}[intel/2019a] CheMPS2 v1.8.9
  easybuild/easyconfigs/c/CheMPS2/CheMPS2-1.8.9-intel-2019a.eb
Labels: update

#8261 Use CMake from GCCcore when installing Eigen 3.3.4+
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.4.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.5.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.7.eb
Labels: bug fix, change

#8268 {bio}[foss/2018a] psmc 0.6.5
  easybuild/easyconfigs/p/psmc/psmc-0.6.5-foss-2018a.eb
Labels: update

#5858 {data}[foss/2016b,foss/2017a] xmlf90 v1.5.3
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.3-foss-2016b.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.3-foss-2017a.eb
Labels: new

#8263 Update patch for disabling AVX512 DGEMM kernels on OpenBLAS 0.3.5
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5_disable_AVX512_dgemm_kernel.patch
Labels: bug fix

#5839 {vis}[intel/2017b] GTK+ 2.24.32 wxPython 3.0.2.0 (REVIEW)
  easybuild/easyconfigs/a/ATK/ATK-2.26.1-intel-2017b.eb
  easybuild/easyconfigs/d/DBus/DBus-1.13.0-intel-2017b.eb
  easybuild/easyconfigs/d/dbus-glib/dbus-glib-0.110-intel-2017b.eb
  easybuild/easyconfigs/g/GConf/GConf-3.2.6-intel-2017b.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-0.10.36-intel-2017b.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-disable-gio-sniffing.patch
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-intel-2017b.eb
  easybuild/easyconfigs/w/wxPython/wxPython-3.0.2.0-intel-2017b-Python-2.7.14.eb
Labels: update

#5859 {data}[foss/2016b,foss/2017a] libpsml v1.1.7
  easybuild/easyconfigs/l/libpsml/libpsml-1.1.7-foss-2016b.eb
  easybuild/easyconfigs/l/libpsml/libpsml-1.1.7-foss-2017a.eb
Labels: new

#7716 added Canvas and .Net-core dependency
  easybuild/easyconfigs/c/Canvas/Canvas-1.39.0.1598.eb
  easybuild/easyconfigs/n/Net-core/Net-core-2.1.8.eb
Labels: new

#5502 New version of FDTD_Solutions with patches for hardcoded paths etc.
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.16-fix-install-paths.patch
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.16-fix-interconnect-api-path.patch
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.16-fix-which-skip-alias.patch
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.16.982.eb
Labels: update

#8209 {lib}[fosscuda/2019a] libgpuarray v0.7.6 w/ Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2019a.eb
Labels: update

#8193 {bio}[foss/2018b] INTEGRATE v0.2.6
  easybuild/easyconfigs/i/INTEGRATE/INTEGRATE-0.2.6-GCCcore-8.2.0.eb
Labels: new

#8176 {tools}[foss/2018b] ncdu v1.14
  easybuild/easyconfigs/n/ncdu/ncdu-1.14-GCCcore-7.3.0.eb
Labels: update

#8245 {tools}[dummy/dummy] py-cpuinfo v5.0.0
  easybuild/easyconfigs/p/py-cpuinfo/py-cpuinfo-5.0.0.eb
Labels: new

#8259 {tools}[GCCcore/8.2.0] hunspell v1.7.0
  easybuild/easyconfigs/h/hunspell/hunspell-1.7.0-GCCcore-8.2.0.eb
Labels: update

#7704 {system}[GCCcore/8.2.0] Hello v2.10
  easybuild/easyconfigs/h/Hello/Hello-2.10-GCCcore-8.2.0.eb
Labels: new

#8249 {chem}[dummy/dummy] Molcas v8.2
  easybuild/easyconfigs/m/Molcas/Molcas-8.2-centos-mkl-par.eb
  easybuild/easyconfigs/m/Molcas/Molcas-8.2-centos-par.eb
Labels: update

#8083 {tools}[GCCcore-7.2.0] - Patchelf 0.10
  easybuild/easyconfigs/p/patchelf/patchelf-0.10-GCCcore-7.2.0.eb
Labels: update

#8254 {compiler}[GCCcore/8.2.0] Clang v8.0.0
  easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCCcore-8.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#8272 fix MAJIQ easyconfig by fixing order of extensions + avoid numpy test hang
  easybuild/easyconfigs/m/MAJIQ/MAJIQ-1.1.1-intel-2018a-Python-3.6.4.eb
Labels: bug fix

#7252 {compiler}[GCCcore/7.2.0] LLVM 7.0.0
  easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-7.2.0.eb
  easybuild/easyconfigs/c/cURL/cURL-7.60.0-GCCcore-7.2.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-7.0.0-GCCcore-7.2.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-7.2.0-bare.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.24.0-GCCcore-7.2.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.8-GCCcore-7.2.0.eb
Labels: update

#8241 add missing Ruby dep (& Python build dep) for WebKitGTK+ v2.24.1
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.24.1-GCC-8.2.0-2.31.1.eb
Labels: bug fix

#7562 {bio}[intel/2018b] Trim_Galore v0.5.0, cutadapt v1.18 w/ Python 3.6.6
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.18-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.5.0-intel-2018b-Python-3.6.6.eb
Labels: update

#8235 {bio}[intel/2018b] OrthoFinder v2.3.3 w/ Python 2.7.15 (+ deps)
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.22-intel-2018b.eb
  easybuild/easyconfigs/f/FastME/FastME-2.1.6.1-intel-2018b.eb
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-7.3.0-Perl-5.28.0.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-8-fac81-intel-2018b.eb
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.3.3-intel-2018b-Python-2.7.15.eb
Labels: update

#7988 {bio}[foss/2018b] cutadapt v2.1 w/ Python 3.6.6
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.1-foss-2018b-Python-3.6.6.eb
Labels: update

#8093 {bio}[foss/2018b] bam-readcount v0.8.0
  easybuild/easyconfigs/b/bam-readcount/bam-readcount-0.8.0-foss-2018b.eb
Labels: update

#7989 {astro}[foss/2018b,intel/2018b] emcee v2.2.1
  easybuild/easyconfigs/e/emcee/emcee-2.2.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/e/emcee/emcee-2.2.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/e/emcee/emcee-2.2.1-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/e/emcee/emcee-2.2.1-intel-2018b-Python-3.6.6.eb
Labels: new

#6483 {lang} [intel/2018a] PyCUDA v2017.1.1 (REVIEW)
  easybuild/easyconfigs/p/PyCUDA/PyCUDA-2017.1.1-intel-2018a-Python-2.7.14.eb
Labels: update

#8130 [*/2017b] fix missing extensions in cutadapt v1.16
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-intel-2017b-Python-3.6.3.eb
Labels: bug fix

#8022 {bio}[dummy/dummy] Kent_tools v20190326
  easybuild/easyconfigs/k/Kent_tools/Kent_tools-20190326-linux.x86_64.eb
Labels: update

#6909 {bio}[foss/2018b] Seurat v2.3.4 w/ R 3.5.1
  easybuild/easyconfigs/s/Seurat/Seurat-2.3.4-foss-2018b-R-3.5.1.eb
Labels: update

#8097 {chem}[intel/2017b] NBO v7.0
  easybuild/easyconfigs/n/NBO/NBO-7.0-intel-2017b.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0_make.patch
Labels: update

#7305 VMD 1.9.3: Adding patches for Surf and Stride
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.3_stride_MAX_AT_IN_RES.patch
  easybuild/easyconfigs/v/VMD/VMD-1.9.3_stride_Makefile.patch
  easybuild/easyconfigs/v/VMD/VMD-1.9.3_surf_Makefile.patch
  easybuild/easyconfigs/v/VMD/VMD-1.9.3_surf_bad_printfs.patch
Labels: enhancement

#8145 {vis}[GCC/8.2.0-2.31.1] FLTK v1.3.5
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.5-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/x/xprop/xprop-1.2.4-GCCcore-8.2.0.eb
Labels: update

#7264 {bio}[foss/2018b] zingeR v20180131 w/ R 3.5.1
  easybuild/easyconfigs/z/zingeR/zingeR-20180131-foss-2018b-R-3.5.1.eb
Labels: new

#7683 {bio}[foss/2018b] MaSuRCA v3.3.1 w/ Perl 5.28.0
  easybuild/easyconfigs/m/MaSuRCA/MaSuRCA-3.3.1-foss-2018b-Perl-5.28.0.eb
Labels: update

#7970 {tools}[foss/2018b] cdsapi v0.1.4 w/ Python 3.6.6
  easybuild/easyconfigs/c/cdsapi/cdsapi-0.1.4-foss-2018b-Python-3.6.6.eb
Labels: new

#8124 {vis}[GCC/8.2.0-2.31.1] GST-plugins-base v1.16.0
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.16.0-GCC-8.2.0-2.31.1.eb
Labels: update

#8182 {chem}[foss/2019a] CP2K v6.1
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-foss-2019a.eb
Labels: update

#7969 {bio}[foss/2018b] CD-HIT v4.8.1
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-foss-2018b.eb
Labels: update

#8092 {bio}[foss/2018b] vt v0.57721
  easybuild/easyconfigs/v/vt/vt-0.57721-foss-2018b.eb
Labels: update

#7156 {data}[foss/2018a] netcdf4-python v1.4.2 w/ Python 3.6.4
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.4.2-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.4.2_fix-opendap-test.patch
Labels: update

#7961 {data}[fosscuda/2018b] dask v1.1.4
  easybuild/easyconfigs/d/dask/dask-1.1.4-fosscuda-2018b-Python-2.7.15.eb
Labels: update

#7938 {bio}[foss/2018b] VAtools v3.0.1
  easybuild/easyconfigs/v/VAtools/VAtools-3.0.1-foss-2018b-Python-3.6.6.eb
Labels: new

#7953 {vis}[foss/2018b] OpenCV v4.0.1 w/ Python 3.6.6
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.0.1-foss-2018b-Python-3.6.6.eb
Labels: update

#7971 Pysam - Add XZ dependency for versions > 0.12
  easybuild/easyconfigs/p/Pysam/Pysam-0.12.0.1-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.12.0.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.12.0.1-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.13-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.13.0-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-intel-2018a-Python-3.6.4.eb
Labels: bug fix

#8223 R: make sure hdf5r picks up HDF5 from EB + fix checksum
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
  easybuild/easyconfigs/r/R/R-3.5.1-intel-2018b.eb
Labels: bug fix

#7530 Remove xbitmaps dependency from motif
  easybuild/easyconfigs/m/motif/motif-2.3.7-intel-2017a.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2018a.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2018b.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-intel-2017b.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-intel-2018a.eb
Labels: change, code cleanup

#7088 {cae}[dummy/dummy] FDTD_Solutions v8.20.1731
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.20-fix-pbs-template.patch
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.20-fix-which-skip-alias.patch
  easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.20.1731.eb
Labels: update

#8275 add missing ptyprocess extension in FlexiDot easyconfig
  easybuild/easyconfigs/f/FlexiDot/FlexiDot-1.06-foss-2018b-Python-2.7.15.eb
Labels: bug fix

#8229 {lib}[foss/2018b] imgaug v0.2.8
  easybuild/easyconfigs/i/imgaug/imgaug-0.2.8-foss-2018b-Python-3.6.6.eb
Labels: new, update

#8252 restore Travis configuration to test with both Python 2.6 & 2.7 with Lmod/Tmod
  .travis.yml
Labels: change, merge sprint

#8277 Make the requirement on Python clear for GLib. Fix python shebang.
  easybuild/easyconfigs/g/GLib/GLib-2.60.1-GCCcore-8.2.0.eb
Labels: bug fix

#8280 {bio}[foss/2018b] Trim_Galore v0.6.2
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.2-foss-2018b-Python-2.7.15.eb
Labels: update

#8273 {devel}[GCCcore/8.2.0] GConf v3.2.6
  easybuild/easyconfigs/d/dbus-glib/dbus-glib-0.110-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GConf/GConf-3.2.6-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GConf/GConf-3.2.6_call-dbus_g_thread_init.patch
  easybuild/easyconfigs/g/GConf/GConf-3.2.6_fix_wrong_return_value.patch
  easybuild/easyconfigs/g/GConf/GConf-3.2.6_gconf-path-max-hurd.patch
  easybuild/easyconfigs/g/GConf/GConf-3.2.6_readd_gconf_engine_key_is_writable.patch
Labels: update

#8281 {bio}[foss/2018b] Trim_Galore v0.6.2 w/ Python 3.6.6
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.2-foss-2018b-Python-3.6.6.eb
Labels: update

#8279 {bio}[foss/2018b] Trim_Galore v0.6.1 w/ Python 2.7.15 + 3.6.6
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.1-foss-2018b-Python-3.6.6.eb
Labels: update

#8125 {vis}[GCC/8.2.0-2.31.1] wxWidgets v3.0.4
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.0.4-GCC-8.2.0-2.31.1.eb
Labels: update

#8202 {chem}[foss/2017b,intel/2017b] charmm v43b2
  easybuild/easyconfigs/c/charmm/charmm-43b2-foss-2017b.eb
  easybuild/easyconfigs/c/charmm/charmm-43b2-intel-2017b.eb
  easybuild/easyconfigs/c/charmm/charmm-43b2_Use_xhost.patch
Labels: new

#8264 add jemalloc & pkg-config as build deps for Salmon 0.12.0
  easybuild/easyconfigs/s/Salmon/Salmon-0.12.0-foss-2018b.eb
Labels: bug fix

#8248 {numlib}[foss/2019a,intel/2019a] CGAL v4.14
  easybuild/easyconfigs/c/CGAL/CGAL-4.14-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/c/CGAL/CGAL-4.14-intel-2019a-Python-3.7.2.eb
Labels: update

#7896 {bio}[foss/2018b] metaWRAP v1.2 w/ Python 2.7.15
  easybuild/easyconfigs/m/metaWRAP/metaWRAP-1.2-foss-2018b-Python-2.7.15.eb
Labels: new

#8285 prevent LUSCUS from installing it's configuration into $HOME/.luscus
  easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6-foss-2018b.eb
  easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6-intel-2018a.eb
  easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6_config-dir.patch
Labels: bug fix

#5803 {chem}[iomkl/2017b] QuantumEspresso v6.2.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-iomkl-2017b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2.1-iomkl-2017b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2.1_fix_building_fox.patch
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2.1_fix_missing_include_dir_in_COUPLE.patch
Labels: update

#8287 {toolchain}[dummy/dummy] gimkl v2018b, gimpi v2018b, imkl v2018.3.222, ...
  easybuild/easyconfigs/g/gimkl/gimkl-2018b.eb
  easybuild/easyconfigs/g/gimpi/gimpi-2018b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-gimkl-2018b.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.3.222-gimpi-2018b.eb
  easybuild/easyconfigs/i/impi/impi-2018.3.222-GCC-7.3.0-2.30.eb
Labels: update

#8132 {vis}[GCC/8.2.0-2.31.1] wxPython v4.0.4
  easybuild/easyconfigs/w/wxPython/wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-2.7.15.eb
  easybuild/easyconfigs/w/wxPython/wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-3.7.2.eb
  easybuild/easyconfigs/w/wxPython/wxPython-4.0.4_fix_install_path.patch
  easybuild/easyconfigs/w/wxPython/wxPython-4.0.4_use_bang_env_python.patch
Labels: update

#8288 {vis}[GCCcore/8.2.0] gnuplot v5.2.6
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6_fix_missing_dep_for_gobject_to_cairopdf.patch
Labels: update

#8283 DBus: Add `pkg-config` and `expat` as (build) dependency
  easybuild/easyconfigs/d/DBus/DBus-1.10.12-intel-2016b.eb
  easybuild/easyconfigs/d/DBus/DBus-1.10.20-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.10.8-foss-2016a.eb
  easybuild/easyconfigs/d/DBus/DBus-1.10.8-intel-2016a.eb
  easybuild/easyconfigs/d/DBus/DBus-1.11.20-intel-2017a.eb
  easybuild/easyconfigs/d/DBus/DBus-1.13.0-intel-2017b.eb
  easybuild/easyconfigs/d/DBus/DBus-1.13.6-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.13.6-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.13.8-GCCcore-8.2.0.eb
Labels: bug fix

#8094 {bio}[foss/2018b] INTEGRATE-Neo v1.2.1, HLAminer v1.4, netMHC v4.0a
  easybuild/easyconfigs/h/HLAminer/HLAminer-1.4-foss-2018b-Perl-5.28.0.eb
  easybuild/easyconfigs/i/INTEGRATE-Neo/INTEGRATE-Neo-1.2.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/n/netMHC/netMHC-4.0a.eb
Labels: new

#8293 Old style exceptions are syntax errors in Python 3
  setup.py
Labels: python3

#8286 Add missing $GI_TYPELIB_PATH to Pango module. Everything that uses GObject-Introspection should have this set.
  easybuild/easyconfigs/p/Pango/Pango-1.39.0-foss-2016a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.39.0-intel-2016a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.1-foss-2016a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.1-intel-2016a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.12-intel-2017a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.14-foss-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.14-intel-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.3-foss-2016b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.3-intel-2016b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.40.5-intel-2017a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.0-foss-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.0-intel-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.1-foss-2018a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.1-intel-2018a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.42.4-foss-2018b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.42.4-fosscuda-2018b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.43.0-GCCcore-8.2.0.eb
Labels: bug fix

#8298 setup.py: Update the PyPI trove classifiers
  setup.py
Labels: bug fix, update

#8299 fix Python classifiers in setup.py, should be (only) Python 2.6 & 2.7
  setup.py
Labels: bug fix

#8302 {math}[fosscuda/2019a] Theano v1.0.4
  easybuild/easyconfigs/t/Theano/Theano-1.0.4-fosscuda-2019a.eb
Labels: update

#8304 INTEGRATE: use CMakeMakeCp easyblock
  easybuild/easyconfigs/i/INTEGRATE/INTEGRATE-0.2.6-GCCcore-8.2.0.eb
Labels: code cleanup

#8307 {tools}[GCCcore/8.2.0] hypothesis v4.23.4
  easybuild/easyconfigs/h/hypothesis/hypothesis-4.23.4-GCCcore-8.2.0.eb
Labels: new

#8195 {tools}[dummy/] Nextflow v19.04.0
  easybuild/easyconfigs/n/Nextflow/Nextflow-19.04.0.eb
Labels: new

#8163 {lib}[fosscuda/2019a] TensorFlow v1.13.1 w/ Python 3.7.2
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_dont_expand_cuda_cudnn_path.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_fix_cudalib_version_for_cuda10.1.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_fix_protobuf_problem.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_protobuf-3.6.1.2_fix_26155.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_remove_usrbin_from_linker_bin_path_flag.patch
Labels: update

#8305 {tools}[GCCcore/8.2.0] socat v1.7.3.3
  easybuild/easyconfigs/s/socat/socat-1.7.3.3-GCCcore-8.2.0.eb
Labels: new

#8301 {lib}[foss/2019a] TensorFlow v1.13.1 w/ Python 3.7.2
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-foss-2019a-Python-3.7.2.eb
Labels: update

#8303 {math}[fosscuda/2019a] Keras v2.2.4
  easybuild/easyconfigs/k/Keras/Keras-2.2.4-fosscuda-2019a-Python-3.7.2.eb
Labels: update
