Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2019-04, with the labels that each got.

#7681 {lib}[GCC/7.3.0-2.30] pocl v1.2
  easybuild/easyconfigs/p/pocl/pocl-1.2-GCC-7.3.0-2.30.eb
Labels: new

#7685 {devel}[foss/2018b] glew v2.1.0
  easybuild/easyconfigs/g/glew/glew-2.1.0-foss-2018b.eb
Labels: new

#7725 HPCX: add configs to build OSS part of HPCX
  easybuild/easyconfigs/h/HPCX/HPCX-2.3.0-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1-hpcx.eb
  easybuild/easyconfigs/u/UCX/UCX-1.5.0rc1-GCCcore-8.2.0-hpcx.eb
Labels: new

#7755 New EasyConfig for gnuplot serial with the foss-2018b toolchain
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6-foss-2018b.eb
Labels: update

#7800 extra patch for TensorFlow 1.12.0 to remove -B/usr/bin from linker_bin_path_flag in cuda_configure.bzl
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.12.0-fosscuda-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.12.0-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.12.0_remove_usrbin_from_linker_bin_path_flag.patch
Labels: bug fix

#7813 {bio}[intel/2018b] MultiQC v1.7 w/ Python 2.7.15 + 3.6.6
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.7-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.7-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-3.13-intel-2018b-Python-2.7.15.eb
Labels: update

#7921 {lang}[foss/2019a] SciPy-bundle v2019.03 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-foss-2019a.eb
Labels: new

#7922 {lang}[intel/2019a] SciPy-bundle v2019.03 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-intel-2019a.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.12.0-mkl.patch
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.16.1_fix-ifort-V-stderr.patch
Labels: new

#7771 {bio}[foss/2018b] SqueezeMeta v0.4.3 w/ Python 2.7.15
  easybuild/easyconfigs/s/SqueezeMeta/SqueezeMeta-0.4.3-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/SqueezeMeta/SqueezeMeta-0.4.3_fix-hardcoding.patch
Labels: new

#7862 {vis}[intel/2018b] matplotlib v2.2.3 w/ Python 3.6.6
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.3-intel-2018b-Python-3.6.6.eb
Labels: update

#7909 {data}[intel/2018b] slidingwindow v0.0.13 w/ Python 2.7.15
  easybuild/easyconfigs/s/slidingwindow/slidingwindow-0.0.13-intel-2018b-Python-2.7.15.eb
Labels: update

#7910 {lib}[intel/2018b] LIBSVM v3.23
  easybuild/easyconfigs/l/LIBSVM/LIBSVM-3.23-intel-2018b.eb
Labels: update

#7911 {lib}[intel/2018b] scp v0.13.1 w/ Python 2.7.15
  easybuild/easyconfigs/s/scp/scp-0.13.1-intel-2018b-Python-2.7.15.eb
Labels: update

#7926 {compiler}[GCCcore/7.3.0] Go v1.12.1
  easybuild/easyconfigs/g/Go/Go-1.12.1-GCCcore-7.3.0.eb
Labels: update

#7928 {bio,lang}[dummy/,dummy/dummy] ACT v18.0.2, Java v11
  easybuild/easyconfigs/a/ACT/ACT-18.0.2-Java-11.eb
  easybuild/easyconfigs/j/Java/Java-11.eb
Labels: new, update

#7923 {devel}[GCCcore/8.2.0] SWIG v3.0.12
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#7932 {vis}[GCCcore/7.3.0] tesseract v4.0.0, Leptonica v1.77.0
  easybuild/easyconfigs/l/Leptonica/Leptonica-1.77.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/t/tesseract/tesseract-4.0.0-GCCcore-7.3.0.eb
Labels: new

#7991 {data}[foss/2018b,intel/2018b] scikit-learn v0.20.0
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.0-intel-2018b-Python-2.7.15.eb
Labels: update

#7948 prefer https:// over ftp:// for source_urls in recent GROMACS easyconfigs
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016-foss-2016b-hybrid.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016-foss-2016b-mt.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.1-foss-2017a-PLUMED.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.2-foss-2017a.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-foss-2016b-GPU-enabled.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-foss-2017a.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-goolfc-2017.01.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-intel-2017a.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-foss-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-fosscuda-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-giolf-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-goolfc-2017.02.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-intel-2017a.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-intel-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.4-intelcuda-2017b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2016.5-intel-2018a.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018-foss-2018a.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.1-foss-2018b-PLUMED.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-foss-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.2-fosscuda-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-foss-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-fosscuda-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.4-foss-2018b-PLUMED-2.5.0.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2018.4-fosscuda-2018b-PLUMED-2.5.0.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019-foss-2018b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019-fosscuda-2018b.eb
Labels: enhancement

#7930 expat: add configure option --without-docbook to avoid docbook2X dependency
  easybuild/easyconfigs/e/expat/expat-2.2.6-GCCcore-8.2.0.eb
Labels: bug fix

#7997 {vis}[foss/2017b,intel/2017b] Sphinx v1.8.1
  easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.1-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.1-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.1-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.1-intel-2017b-Python-3.6.3.eb
Labels: update

#7993 {lang}[foss/2018a] Mono v5.18.1.0
  easybuild/easyconfigs/m/Mono/Mono-5.18.1.0-foss-2018a.eb
Labels: update

#8007 Rename arrow to Arrow for old easyconfig
  easybuild/easyconfigs/a/Arrow/Arrow-0.7.1-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/b/bat/bat-0.3.3-fix-pyspark.patch
  easybuild/easyconfigs/b/bat/bat-0.3.3-intel-2017b-Python-3.6.3.eb
Labels: bug fix

#7994 Fix LWM2, OTF2, OPARI2, and Score-P download URLs
  easybuild/easyconfigs/__archive__/l/LWM2/LWM2-1.1-gompi-1.4.12-no-OFED.eb
  easybuild/easyconfigs/__archive__/o/OPARI2/OPARI2-1.0.7-gompi-1.4.12-no-OFED.eb
  easybuild/easyconfigs/__archive__/o/OPARI2/OPARI2-1.1.1-gompi-1.4.12-no-OFED.eb
  easybuild/easyconfigs/__archive__/o/OTF2/OTF2-1.2.1-gompi-1.4.12-no-OFED.eb
  easybuild/easyconfigs/__archive__/s/Score-P/Score-P-1.2.1-gompi-1.4.12-no-OFED.eb
  easybuild/easyconfigs/l/LWM2/LWM2-1.1-ictce-5.3.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.1-goolf-1.5.14.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.2-foss-2015a.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.2-goolf-1.5.14.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0-foss-2016a.eb
  easybuild/easyconfigs/o/OTF2/OTF2-1.2.1-goolf-1.5.14.eb
  easybuild/easyconfigs/o/OTF2/OTF2-1.2.1-ictce-5.3.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-1.5.1-foss-2015a.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.0-foss-2016a.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.0-foss-2017a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-1.2.1-goolf-1.5.14.eb
  easybuild/easyconfigs/s/Score-P/Score-P-1.2.3-goolf-1.5.14.eb
  easybuild/easyconfigs/s/Score-P/Score-P-1.4-foss-2015a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-2.0.1-foss-2016a.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#7957 {bio}[GCC/6.4.0-2.28,iccifort/2017.4.196-GCC-6.4.0-2.28] HMMER v3.1b2, RepeatMasker v4.0.8
  easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.0.8-GCC-6.4.0-2.28-Perl-5.26.0-HMMER.eb
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.0.8-iccifort-2017.4.196-GCC-6.4.0-2.28-Perl-5.26.0-HMMER.eb
Labels: update

#8000 add missing configopts in GATE 8.1 easyconfig to enable Davis feature
  easybuild/easyconfigs/g/GATE/GATE-8.1.p01-foss-2018b-Python-2.7.15.eb
Labels: enhancement

#8010 MEME v5.0.4 - Fix missing Python and Perl dependencies
  easybuild/easyconfigs/m/MEME/MEME-5.0.4-foss-2017b-Perl-5.26.0-Python-2.7.14.eb
  easybuild/easyconfigs/m/MEME/MEME-5.0.4-foss-2017b-Perl-5.26.0-Python-3.6.3.eb
  easybuild/easyconfigs/m/MEME/MEME-5.0.4-intel-2017b-Perl-5.26.0-Python-2.7.14.eb
  easybuild/easyconfigs/m/MEME/MEME-5.0.4-intel-2017b-Perl-5.26.0-Python-3.6.3.eb
Labels: bug fix

#8013 use https:// in homepage & source_urls for recent OpenMPI 2.x, 3.x & 4.x easyconfigs
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-gcccuda-2017.01.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017.02.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-gcccuda-2018a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.3-iccifort-2018.2.199-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.0-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-gcccuda-2018b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.2-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1-hpcx.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1-GCC-8.3.0-2.32.eb
Labels: bug fix

#8014 use https:// in homepage & source_urls for recent hwloc 1.11.x easyconfigs
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.0-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.1-GCC-4.9.3.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.1-iccifort-2015.3.187-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.10-GCCcore-7.3.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.11-GCCcore-8.2.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.2-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.2-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-GCC-5.2.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-GCC-6.1.0-2.27.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-PGI-16.3-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-PGI-16.4-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-gcccuda-2016.08.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-iccifort-2016.3.210-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-intel-2016a.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-intel-2016b.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-GCC-6.2.0-2.27.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-PGI-16.7-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-gcccuda-2016.10.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-iccifort-2017.1.132-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.5-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.5-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.5-iccifort-2017.1.132-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.6-GCC-6.3.0-2.28.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.7-GCCcore-5.4.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.7-GCCcore-6.4.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-GCCcore-6.4.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-GCCcore-7.2.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-intel-2017a.eb
  easybuild/easyconfigs/h/hwloc/hwloc-2.0.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-2.0.3-GCCcore-8.3.0.eb
Labels: bug fix

#8015 use https:// in homepage & source_urls for old hwloc 1.x easyconfigs
  easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-GCC-4.9.2.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-iccifort-2015.1.133-GCC-4.9.2.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-iccifort-2015.2.164-GCC-4.9.2.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.10.1-GCC-4.8.4.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.10.1-GNU-4.9.2-2.25.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.5.1-GCC-4.6.3.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.5.1-ictce-5.3.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.6-ictce-5.3.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.6.4.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.7.2.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-ictce-5.3.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.7.2-GCC-4.8.2.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.7.2-ictce-5.3.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.7.2-ictce-5.5.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.8.1-GCC-4.8.2.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.8.1-GCC-4.8.3.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.8.1-iccifort-2013_sp1.2.144.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.9-GCC-4.8.3.eb
  easybuild/easyconfigs/h/hwloc/hwloc-1.9-iccifort-2013_sp1.4.211.eb
Labels: bug fix

#8016 use https:// in homepage & source_urls for old OpenMPI 1.x easyconfigs
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.1-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-6.1.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.3-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.4-GCC-5.3.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-6.1.0-2.27.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-gcccuda-2016.08.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-PGI-16.7-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-iccifort-2016.3.210-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.4.5-GCC-4.6.3-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.4.5-GCC-4.6.3.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.4.5-ictce-5.5.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-GCC-4.6.4.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-GCC-4.7.2-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-GCC-4.7.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.7.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.7.3-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.1-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.2-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.3.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-iccifort-2013_sp1.2.144.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-iccifort-2013_sp1.4.211-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-iccifort-2013_sp1.4.211.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.7.3-GCC-4.8.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.1-GCC-4.8.3.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-GCC-4.9.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-iccifort-2013_sp1.4.211-no-OFED.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-iccifort-2013_sp1.4.211.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.9.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.1.133-GCC-4.9.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.2.164-GCC-4.9.2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.5-GNU-4.9.2-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.6-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.8-GNU-4.9.3-2.25.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.8-iccifort-2015.3.187-GNU-4.9.3-2.25.eb
Labels: bug fix

#8001 {bio}[foss/2017b,intel/2017b] PANDAseq v2.11
  easybuild/easyconfigs/p/PANDAseq/PANDAseq-2.11-foss-2017b.eb
  easybuild/easyconfigs/p/PANDAseq/PANDAseq-2.11-intel-2017b.eb
Labels: update

#8002 {vis}[foss/2017b,intel/2017b] Grace v5.1.25
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2017b-5build1.eb
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2017b-5build1.eb
Labels: update

#8004 {bio}[GCC/6.4.0-2.28,iccifort/2017.4.196-GCC-6.4.0-2.28] PAML v4.9i
  easybuild/easyconfigs/p/PAML/PAML-4.9i-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/p/PAML/PAML-4.9i-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
Labels: update

#8009 {bio}[intel/2018b] RNAIndel v0.3.0, Pysam v0.15.1 w/ Python 3.6.6
  easybuild/easyconfigs/p/Pysam/Pysam-0.15.1-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/r/RNAIndel/RNAIndel-0.3.0-intel-2018b-Python-3.6.6.eb
Labels: new, update

#8011 {lib}[intel/2018b] POT v0.5.1 w/ Python 3.6.6
  easybuild/easyconfigs/p/POT/POT-0.5.1-intel-2018b-Python-3.6.6.eb
Labels: new

#8027 {chem}[foss/2017b] libxc v4.0.1
  easybuild/easyconfigs/l/libxc/libxc-4.0.1-foss-2017b.eb
Labels: update

#7966 {bio}[intel/2018b] FastTree v2.1.10
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.10-intel-2018b.eb
Labels: update

#7984 {bio}[foss/2018b] Stacks v2.3e
  easybuild/easyconfigs/s/Stacks/Stacks-2.3e-foss-2018b.eb
Labels: update

#7985 {bio,devel}[GCCcore/7.3.0,intel/2018b] Stacks v1.48, sparsehash v2.0.3
  easybuild/easyconfigs/s/Stacks/Stacks-1.48-intel-2018b.eb
  easybuild/easyconfigs/s/sparsehash/sparsehash-2.0.3-GCCcore-7.3.0.eb
Labels: update

#7536 {vis}[foss/2018b,intel/2018b] Mesa-18.1.1: add patch to detect MIT-SHM
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-foss-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-fosscuda-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-intel-2018b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-query-mit-shm.patch
Labels: bug fix

#8036 {system}[GCCcore/8.2.0] OpenSSL v1.1.1b
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.1b-GCCcore-8.2.0.eb
Labels: update

#7992 {bio}[foss/2018b,intel/2018b] FastANI 1.1
  easybuild/easyconfigs/f/FastANI/FastANI-1.1-foss-2018b.eb
  easybuild/easyconfigs/f/FastANI/FastANI-1.1-intel-2018b.eb
  easybuild/easyconfigs/f/FastANI/FastANI-1.1-memcpy.patch
Labels: new

#7365 FastANI foss-2018b, with patch
  easybuild/easyconfigs/f/FastANI/FastANI-1.1-foss-2018b.eb
  easybuild/easyconfigs/f/FastANI/FastANI-1.1-memcpy.patch
Labels: new

#7986 {chem}[foss/2018b] TINKER v8.6.1
  easybuild/easyconfigs/t/TINKER/TINKER-8.6.1-foss-2018b.eb
Labels: update

#7999 {cae}[foss/2018b] GATE v8.2
  easybuild/easyconfigs/g/GATE/GATE-8.2-foss-2018b-Python-2.7.15.eb
Labels: update

#7995 {bio}[intel/2018b] GTDB-Tk v0.2.2, DendroPy v4.4.0 w/ Python 2.7.15
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.4.0-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-0.2.2-intel-2018b-Python-2.7.15.eb
Labels: new, update

#8034 {data}[intel/2018b] Pyke3 v1.1.1
  easybuild/easyconfigs/p/Pyke3/Pyke3-1.1.1-intel-2018b-Python-3.6.6.eb
Labels: new

#8031 {bio}[foss/2018b] cyvcf2 v0.10.10
  easybuild/easyconfigs/c/cyvcf2/cyvcf2-0.10.10-foss-2018b-Python-3.6.6.eb
Labels: new

#8023 {tools}[foss/2018b] amask v20190404
  easybuild/easyconfigs/a/amask/amask-20190404-foss-2018b.eb
Labels: update

#8035 {bio}[foss/2017b,intel/2017b] RELION v3.0.4
  easybuild/easyconfigs/r/RELION/RELION-3.0.4-foss-2017b.eb
  easybuild/easyconfigs/r/RELION/RELION-3.0.4-intel-2017b.eb
Labels: update

#7965 {bio,lib}[intel/2018b] argtable v2.13, Clustal-Omega v1.2.4
  easybuild/easyconfigs/a/argtable/argtable-2.13-intel-2018b.eb
  easybuild/easyconfigs/c/Clustal-Omega/Clustal-Omega-1.2.4-intel-2018b.eb
Labels: update

#7956 {devel}[GCCcore/7.3.0] LevelDB v1.20
  easybuild/easyconfigs/l/LevelDB/LevelDB-1.20-GCCcore-7.3.0.eb
Labels: update

#7955 {lib}[GCCcore/7.3.0] KyotoCabinet v1.2.77
  easybuild/easyconfigs/k/KyotoCabinet/KyotoCabinet-1.2.77-GCCcore-7.3.0.eb
Labels: new

#7952 {tools}[intel/2018b] Cheetah v2.4.4
  easybuild/easyconfigs/c/Cheetah/Cheetah-2.4.4-intel-2018b-Python-2.7.15.eb
Labels: new

#7950 {lib}[GCCcore/7.3.0] libconfig v1.7.2
  easybuild/easyconfigs/l/libconfig/libconfig-1.7.2-GCCcore-7.3.0.eb
Labels: update

#7954 {perf}[GCCcore/7.3.0] PAPI v5.7.0
  easybuild/easyconfigs/p/PAPI/PAPI-5.7.0-GCCcore-7.3.0.eb
Labels: update

#7973 {chem}[intel/2018b] RDKit v2018.09.3 w/ Python 3.6.6 (+ Boost.Python dep)
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.67.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/r/RDKit/RDKit-2018.09.3-intel-2018b-Python-3.6.6.eb
Labels: new, update

#8038 fix checking of binutils build dep in easyconfig tests
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#8042 {tools}[GCCcore/8.2.0] Meson v0.50.0
  easybuild/easyconfigs/m/Meson/Meson-0.50.0-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#8025 {tools}[fosscuda/2018b] gpustat v0.5.0 w/ Python 2.7.15
  easybuild/easyconfigs/g/gpustat/gpustat-0.5.0-fosscuda-2018b-Python-2.7.15.eb
Labels: new

#8028 {lib}[fosscuda/2018b] psutil v5.6.1 w/ Python 2.7.15
  easybuild/easyconfigs/p/psutil/psutil-5.6.1-fosscuda-2018b-Python-2.7.15.eb
Labels: update

#8043 Remove MKLFFT from RELION v3.0.4 in foss-2017b
  easybuild/easyconfigs/r/RELION/RELION-3.0.4-foss-2017b.eb
Labels: bug fix

#8041 {chem}[intel/2018b] PyRETIS v2.1.0 + MDTraj v1.9.2 w/ Python 3.6.6
  easybuild/easyconfigs/m/MDTraj/MDTraj-1.9.2-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyRETIS/PyRETIS-2.1.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.1-intel-2018b-Python-3.6.6.eb
Labels: new, update

#8017 {tools}[(foss|intel/2018b)] pytest v4.4.0
  easybuild/easyconfigs/p/pytest/pytest-4.4.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/pytest/pytest-4.4.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/pytest/pytest-4.4.0-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/pytest/pytest-4.4.0-intel-2018b-Python-3.6.6.eb
Labels: update

#7987 {lib}[GCCcore/7.3.0] libjpeg-turbo v2.0.2
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.2-GCCcore-7.3.0.eb
Labels: update

#7977 {bio}[foss/2018b] Trinity v2.8.4
  easybuild/easyconfigs/t/Trinity/Trinity-2.8.4-foss-2018b.eb
Labels: update

#7968 {lib}[intel/2018b] GDAL v2.2.3, PROJ v5.0.0, libgeotiff v1.4.2
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.4.2-intel-2018b.eb
  easybuild/easyconfigs/p/PROJ/PROJ-5.0.0-intel-2018b.eb
Labels: update

#7762 {chem,tools}[foss-2018b,intel-2018b] CheMPS2-1.8.9, deepdiff-3.3.0, pytest-4.3.0
  easybuild/easyconfigs/c/CheMPS2/CheMPS2-1.8.9-foss-2018b.eb
  easybuild/easyconfigs/c/CheMPS2/CheMPS2-1.8.9-intel-2018b.eb
  easybuild/easyconfigs/d/deepdiff/deepdiff-3.3.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/d/deepdiff/deepdiff-3.3.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/pytest/pytest-4.3.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/pytest/pytest-4.3.0-intel-2018b-Python-3.6.6.eb
Labels: update

#8033 {math}[foss/2018b,intel/2018b] statsmodels v0.9.0 w/ Python 2.7.15
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.9.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.9.0-intel-2018b-Python-2.7.15.eb
Labels: update

#8049 {tools}[foss/2017b,intel/2017b] IPython v5.8.0
  easybuild/easyconfigs/i/IPython/IPython-5.8.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/i/IPython/IPython-5.8.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/i/IPython/IPython-5.8.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/i/IPython/IPython-5.8.0-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.13-GCCcore-6.4.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.2-foss-2017b.eb
Labels: update

#8054 fix checksums for boot/nlme extensions in R easyconfigs
  easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
  easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
Labels: bug fix

#8052 fix checksum for nlme in R 3.5.* easyconfigs
  easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
Labels: bug fix

#8055 {bio}[foss/2017b] MEGAHIT v1.1.3
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.1.3-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.1.3-foss-2017b-Python-3.6.3.eb
Labels: update

#8056 {tools}[foss/2017b] parallel v20171122
  easybuild/easyconfigs/p/parallel/parallel-20171122-foss-2017b.eb
Labels: update

#8057 {tools}[foss/2017b,intel/2017b] CheckM v1.0.13
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/p/prodigal/prodigal-2.6.3-GCCcore-6.4.0.eb
Labels: update

#8051 {bio}[foss/2017b] CONCOCT v1.0.0
  easybuild/easyconfigs/c/CONCOCT/CONCOCT-1.0.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CONCOCT/CONCOCT-1.0.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.19.1-foss-2017b-Python-2.7.14.eb
Labels: update

#8058 update release notes for EasyBuild v3.9.0 release + bump version to 3.9.0
  RELEASE_NOTES
  setup.py
Labels: update

#8060 {tools}[dummy/dummy] EasyBuild v3.9.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.9.0.eb
Labels: update

#8061 sync with master & bump version to 3.9.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#7972 {data}[intel/2018b] NCL v6.6.2 + deps
  easybuild/easyconfigs/g/g2clib/g2clib-1.6.0-intel-2018b.eb
  easybuild/easyconfigs/g/g2lib/g2lib-3.1.0-intel-2018b.eb
  easybuild/easyconfigs/g/g2lib/g2lib-3.1.0_makefile.patch
  easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/makedepend/makedepend-1.0.6-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NCL/NCL-6.6.2-intel-2018b.eb
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-7.3.0.eb
Labels: update

#8050 {tools}[foss/2017b,intel/2017b] IRkernel v0.8.15
  easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-foss-2017b-R-3.4.3-Python-2.7.14.eb
  easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-intel-2017b-R-3.4.3-Python-2.7.14.eb
Labels: new

#8063 {toolchain}[dummy/dummy] fosscuda v2019a
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.105-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompic-2019a.eb
  easybuild/easyconfigs/f/fosscuda/fosscuda-2019a.eb
  easybuild/easyconfigs/g/gcccuda/gcccuda-2019a.eb
  easybuild/easyconfigs/g/gompic/gompic-2019a.eb
  easybuild/easyconfigs/l/libevent/libevent-2.1.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-gcccuda-2019a.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.0.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2019a-OpenBLAS-0.3.5.eb
  easybuild/easyconfigs/u/UCX/UCX-1.5.1-GCCcore-8.2.0.eb
Labels: update

#8079 {vis}[GCCcore/8.2.0] GLib v2.60.1, GObject-Introspection v1.60.1, cairo v1.16.0
  easybuild/easyconfigs/c/cairo/cairo-1.16.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.60.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.60.1-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#7947 {vis}[GCCcore/8.2.0] Mesa v19.0.1, libunwind v1.3.1, libGLU v9.0.0
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.0.1-GCCcore-8.2.0.eb
Labels: update

#8080 {vis}[GCCcore/8.2.0] ATK v2.32.0, at-spi2-core v2.32.0, at-spi2-atk v2.32.0
  easybuild/easyconfigs/a/ATK/ATK-2.32.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.32.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.32.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.32.0_remove-subdir-prefix.patch
Labels: update

#8081 {vis}[GCCcore/8.2.0] GTK+ v3.24.8, Gdk-Pixbuf v2.38.1, libepoxy v1.5.3, Pango v1.43.0, HarfBuzz v2.4.0
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-post-install-bin.patch
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.4.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.43.0-GCCcore-8.2.0.eb
Labels: update

#8065 {lang}[fosscuda/2019a] SciPy-bundle v2019.03
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-fosscuda-2019a.eb
Labels: update

#8069 {toolchain}[dummy/dummy] intelcuda v2019a
  easybuild/easyconfigs/c/CUDA/CUDA-10.1.105-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/i/iccifortcuda/iccifortcuda-2019a.eb
  easybuild/easyconfigs/i/iimpic/iimpic-2019a.eb
  easybuild/easyconfigs/i/imkl/imkl-2019.1.144-iimpic-2019a.eb
  easybuild/easyconfigs/i/impi/impi-2018.4.274-iccifortcuda-2019a.eb
  easybuild/easyconfigs/i/intelcuda/intelcuda-2019a.eb
Labels: update

#8072 {lang}[intelcuda/2019a] SciPy-bundle v2019.03
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-intelcuda-2019a.eb
Labels: update

#7647 {tools}[fosscuda/2018b] IPython v5.8.0
  easybuild/easyconfigs/i/IPython/IPython-5.8.0-fosscuda-2018b-Python-2.7.15.eb
Labels: update

#8087 {cae}[foss/2017b,intel/2017b] GATE v8.2
  easybuild/easyconfigs/g/GATE/GATE-8.2-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/g/GATE/GATE-8.2-intel-2017b-Python-2.7.14.eb
Labels: update

#8077 {vis}[foss/2017b,intel/2017b] POV-Ray v3.7.0.7
  easybuild/easyconfigs/p/POV-Ray/POV-Ray-3.7.0.7-foss-2017b.eb
  easybuild/easyconfigs/p/POV-Ray/POV-Ray-3.7.0.7-intel-2017b.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.8-foss-2017b.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.8-intel-2017b.eb
Labels: update

#8074 {data}[foss/2018b] unixODBC v2.3.7
  easybuild/easyconfigs/u/unixODBC/unixODBC-2.3.7-foss-2018b.eb
Labels: new

#8040 {bio}[foss/2018b] GMAP-GSNAP v2019-03-15, rnaQUAST v1.5.2
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2019-03-15-fix-avx512.patch
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2019-03-15-foss-2018b.eb
  easybuild/easyconfigs/r/rnaQUAST/rnaQUAST-1.5.2-foss-2018b-Python-2.7.15.eb
Labels: new, update

#8039 {lang,phys,vis}[GCCcore/7.3.0] ARGoS v3.0.0-beta53, FreeImage v3.18.0, Lua v5.2.4
  easybuild/easyconfigs/a/ARGoS/ARGoS-3.0.0-beta53-foss-2018b-Lua-5.2.4.eb
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-fix-makefile.patch
  easybuild/easyconfigs/l/Lua/Lua-5.2.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/Lua/Lua-5.2.4-fix-makefile.patch
  test/easyconfigs/easyconfigs.py
Labels: new, update

#7933 {vis}[foss/2018b] R-tesseract v4.0
  easybuild/easyconfigs/r/R-tesseract/R-tesseract-4.0-foss-2018b-R-3.5.1.eb
Labels: new

#8101 add check for custom sanity_check_paths in easyconfigs touched in PRs when generic easyblock is used
  test/easyconfigs/easyconfigs.py
Labels: enhancement

#7959 {bio}[GCC/6.4.0-2.28,iccifort/2017.4.196-GCC-6.4.0-2.28] snap v2013-11-29
  easybuild/easyconfigs/s/SNAP/SNAP-2013-11-29-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/s/SNAP/SNAP-2013-11-29-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/s/SNAP/SNAP_2013-11-29_makefile_correction.patch
Labels: new

#8104 correctly register CMake as a build dependency in ARGoS easyconfig file
  easybuild/easyconfigs/a/ARGoS/ARGoS-3.0.0-beta53-foss-2018b-Lua-5.2.4.eb
Labels: bug fix

#7191 {vis}[intel/2018a] LUSCUS v0.8.6
  easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6-intel-2018a.eb
  easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6_fix-X11-link.patch
Labels: new

#8106 add (back) custom sanity_check_paths in recent Pango easyconfigs
  easybuild/easyconfigs/p/Pango/Pango-1.41.0-foss-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.0-intel-2017b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.1-foss-2018a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.41.1-intel-2018a.eb
  easybuild/easyconfigs/p/Pango/Pango-1.42.4-foss-2018b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.42.4-fosscuda-2018b.eb
  easybuild/easyconfigs/p/Pango/Pango-1.43.0-GCCcore-8.2.0.eb
Labels: enhancement

#8084 {data}[foss/2017b,intel/2017b] ANTs v2.3.0
  easybuild/easyconfigs/a/ANTs/ANTs-2.3.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/a/ANTs/ANTs-2.3.0-intel-2017b-Python-2.7.14.eb
Labels: update

#8076 {bio}[GCC/6.4.0-2.28,iccifort/2017.4.196-GCC-6.4.0-2.28] PLINKSEQ v0.10
  easybuild/easyconfigs/p/PLINKSEQ/PLINKSEQ-0.10-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/p/PLINKSEQ/PLINKSEQ-0.10-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
Labels: update

#8078 {bio}[foss/2017b,intel/2017b] cutadapt v1.16
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-intel-2017b-Python-3.6.3.eb
Labels: update

#8066 {lang}[GCCcore/8.2.0] Tkinter v2.7.15, Tkinter v3.7.2
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.15-GCCcore-8.2.0.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.7.2-GCCcore-8.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#8103 Pango 1.43.0 should have FriBidi as a runtime dep
  easybuild/easyconfigs/p/Pango/Pango-1.43.0-GCCcore-8.2.0.eb
Labels: bug fix

#8108 {phys}[GCCcore/8.2.0] UDUNITS v2.2.26
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.2.0.eb
Labels: update

#8070 {cae}[dummy/dummy] LS-PrePost v4.6
  easybuild/easyconfigs/l/LS-PrePost/LS-PrePost-4.6-centos6.eb
  easybuild/easyconfigs/l/LS-PrePost/LS-PrePost-4.6-centos7.eb
Labels: new

#8089 $XDG_DATA_DIRS must be set for GTK+
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.28-intel-2016a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.30-foss-2016a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.30-intel-2016a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-foss-2016b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-intel-2016b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-intel-2017a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2017b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2017b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2018a.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.22.30-fosscuda-2018b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.8-GCCcore-8.2.0.eb
Labels: bug fix

#8117 {lib}[GCCcore/8.2.0] OpenJPEG v2.3.1
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.3.1-GCCcore-8.2.0.eb
Labels: update

#8102 {mpi,system}[GCC/8.3.0-2.32,GCCcore/8.3.0] OpenMPI v3.1.4, hwloc v1.11.12
  easybuild/easyconfigs/h/hwloc/hwloc-1.11.12-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0-2.32.eb
Labels: update

#8123 PythonBundle already has a decent customised sanity_check_paths for bundles of Python packages
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#8122 {vis}[GCC/8.2.0-2.31.1] GStreamer v1.16.0
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.16.0-GCC-8.2.0-2.31.1.eb
Labels: update

#8120 {lib}[GCCcore/8.2.0] SDL2 v2.0.9
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.9-GCCcore-8.2.0.eb
Labels: update

#7996 {data}[foss/2017b,intel/2017b] RStan v2.18.2 w/ R 3.4.3
  easybuild/easyconfigs/r/RStan/RStan-2.18.2-foss-2017b-R-3.4.3.eb
  easybuild/easyconfigs/r/RStan/RStan-2.18.2-intel-2017b-R-3.4.3.eb
Labels: new

#8134 {data}[gompic/2019a,iimpic/2019a] HDF5 v1.10.5
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.5-gompic-2019a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.5-iimpic-2019a.eb
Labels: update

#8119 {bio}[intel/2018b] RNAIndel v1.0.0
  easybuild/easyconfigs/r/RNAIndel/RNAIndel-1.0.0-intel-2018b-Python-3.6.6.eb
Labels: update

#8121 {data}[GCCcore/8.2.0] openpyxl v2.6.2 (+ lxml v4.3.3, Pillow v6.0.0) for Python 2.7.15 & 3.7.2
  easybuild/easyconfigs/l/lxml/lxml-4.3.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/o/openpyxl/openpyxl-2.6.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.0.0-GCCcore-8.2.0.eb
Labels: new, update

#8139 adding easyconfig for vtune2019u3, +download URL for vtune2018u3
  easybuild/easyconfigs/v/VTune/VTune-2018_update3.eb
  easybuild/easyconfigs/v/VTune/VTune-2019_update3.eb
Labels: new, update

#8109 {lib}[GCCcore/8.2.0] ICU v64.2
  easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.2.0.eb
Labels: update

#8112 {system}[GCCcore/8.2.0] libgcrypt v1.8.4
  easybuild/easyconfigs/l/libgcrypt/libgcrypt-1.8.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.36-GCCcore-8.2.0.eb
Labels: update

#8113 {lib}[GCCcore/8.2.0] libpsl v0.21.0
  easybuild/easyconfigs/l/libpsl/libpsl-0.21.0-GCCcore-8.2.0.eb
Labels: update

#8114 {lib}[GCCcore/8.2.0] libtasn1 v4.13
  easybuild/easyconfigs/l/libtasn1/libtasn1-4.13-GCCcore-8.2.0.eb
Labels: update

#8115 {lib}[GCCcore/8.2.0] libwebp v1.0.2
  easybuild/easyconfigs/g/giflib/giflib-5.1.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libwebp/libwebp-1.0.2-GCCcore-8.2.0.eb
Labels: update

#8062 IGV 2.5 Java-11
  easybuild/easyconfigs/i/IGV/IGV-2.5.0-Java-11.eb
Labels: update

#8107 {vis}[foss/2019a,fosscuda/2019a,intel/2019a,intelcuda/2019a] matplotlib v3.0.3 w/ Python 3.7.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-intel-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-intelcuda-2019a-Python-3.7.2.eb
Labels: update

#8164 add singledispatch extension to Python 2.7.15 easyconfig using GCCcore/8.2.0
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb
Labels: enhancement

#8175 {devel,lib,math}[fosscuda/2018b] Theano v1.0.4, libgpuarray v0.7.6, Mako v1.0.9
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/Theano/Theano-1.0.4-fosscuda-2018b-Python-3.6.6.eb
Labels: update

#8165 {lang}[intel/2019a] numba v0.43.1 for Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/n/numba/llvmlite-0.26.0_fix-ffi-Makefile.patch
  easybuild/easyconfigs/n/numba/numba-0.43.1-intel-2019a.eb
Labels: update

#8173 {math}[GCCcore/8.2.0] METIS v5.1.0
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-8.2.0.eb
Labels: update

#8110 {lib}[GCCcore/8.2.0] PROJ v6.0.0
  easybuild/easyconfigs/p/PROJ/PROJ-6.0.0-GCCcore-8.2.0.eb
Labels: update

#8168 {tools}[GCCcore/8.2.0] Vim v8.1.1209
  easybuild/easyconfigs/v/Vim/Vim-8.1.1209-GCCcore-8.2.0-Python-3.7.2.eb
Labels: update

#8143 {lib}[GCCcore/8.2.0] libsndfile v1.0.28
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-8.2.0.eb
Labels: update

#8170 {lib}[GCCcore/8.2.0] lz4 v1.9.1
  easybuild/easyconfigs/l/lz4/lz4-1.9.1-GCCcore-8.2.0.eb
Labels: update

#8169 {lib}[GCCcore/8.2.0] utf8proc v2.3.0
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.3.0-GCCcore-8.2.0.eb
Labels: update

#8172 {devel}[GCCcore/8.2.0] SCons v3.0.5 for Python 3.7.2 + 2.7.15
  easybuild/easyconfigs/s/SCons/SCons-3.0.5-GCCcore-8.2.0.eb
Labels: update

#8174 {math}[gompi/2019a,iimpi/2019a] ParMETIS v4.0.3
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2019a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2019a.eb
Labels: update

#8141 {numlib}[GCC/8.2.0-2.31.1] GSL v2.5
  easybuild/easyconfigs/g/GSL/GSL-2.5-GCC-8.2.0-2.31.1.eb
Labels: update

#8180 {math}[gompi/2019a,iimpi/2019a] SCOTCH v6.0.6
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-gompi-2019a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-iimpi-2019a.eb
Labels: update

#8181 {numlib}[iccifort/2019.1.144-GCC-8.2.0-2.31.1] GSL v2.5
  easybuild/easyconfigs/g/GSL/GSL-2.5-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: update

#8171 {tools}[GCCcore/8.2.0] Subversion 1.12.0 + deps Serf v1.3.9, APR v1.7.0, ...
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-8.2.0.eb
  easybuild/easyconfigs/s/Subversion/Subversion-1.12.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/s/Subversion/Subversion-1.12.0-no_swig.patch
Labels: update

#8190 {numlib}[gcccuda/2019a] cuDNN v7.4.2.24
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.4.2.24-gcccuda-2019a.eb
Labels: update

#8183 {chem}[GCC/8.2.0-2.31.1,iccifort/2019.1.144-GCC-8.2.0-2.31.1] Libint v1.1.6
  easybuild/easyconfigs/l/Libint/Libint-1.1.6-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/Libint/Libint-1.1.6-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: update

#8185 {chem}[GCC/8.2.0-2.31.1,iccifort/2019.1.144-GCC-8.2.0-2.31.1] libxc v4.3.4
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: update

#8189 {devel}[GCCcore/8.2.0] protobuf v3.6.1.2
  easybuild/easyconfigs/p/protobuf/protobuf-3.6.1.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/protobuf/protobuf-3.6.1.2_make_include_file_CUDA_10.1_friendly.patch
Labels: update

#8184 {chem}[foss/2019a, intel/2019a] PLUMED v2.5.1
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-foss-2019a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-intel-2018b.eb
Labels: update

#8187 {math}[GCC/8.2.0-2.31.1,iccifort/2019.1.144-GCC-8.2.0-2.31.1] libxsmm v1.10
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.10-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.10-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: update

#7983 {math}[foss/2018b] PETSc 3.11.0, SLEPc 3.11.0, gmsh 3.0.6, gmsh 4.2.2
  easybuild/easyconfigs/g/gmsh/gmsh-3.0.6-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.2.2-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.11.0-foss-2018b-downloaded-deps.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.11.0-foss-2018b.eb
Labels: update

#8116 {lib}[GCCcore/8.2.0] LibSoup v2.66.1
  easybuild/easyconfigs/l/LibSoup/LibSoup-2.66.1-GCCcore-8.2.0.eb
Labels: new
