Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-06, with the labels that each got.

#10728 {data}[GCCcore/8.3.0] hl7apy v1.3.3 w/ Python 3.7.4
  easybuild/easyconfigs/h/hl7apy/hl7apy-1.3.3-GCCcore-8.3.0-Python-3.7.4.eb
Labels: new

#10718 {numlib}[foss/2019b] Trilinos v12.12.1 w/ Python 3.7.4
  easybuild/easyconfigs/g/GLM/GLM-0.9.9.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GLM/GLM-0.9.9.8_fix_missing_install.patch
  easybuild/easyconfigs/m/MATIO/MATIO-1.5.17-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1_py3_fixes_and_more.patch
Labels: update

#10682 {bio}[system/system] snpEff v4.3t
  easybuild/easyconfigs/s/snpEff/snpEff-4.3t-Java-1.8.eb
Labels: update

#10683 {bio}[system/system] Trimmomatic v0.39
  easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.39-Java-1.8.eb
Labels: update

#10684 {bio}[system/system] VarScan v2.4.4
  easybuild/easyconfigs/v/VarScan/VarScan-2.4.4-Java-1.8.eb
Labels: update

#10733 New EC for PRSice-2.3.1
  easybuild/easyconfigs/p/PRSice/PRSice-2.3.1-GCCcore-9.3.0.eb
Labels: update

#10734 {lang}[system/system] Julia v1.4.2
  easybuild/easyconfigs/j/Julia/Julia-1.4.2-linux-x86_64.eb
Labels: update

#10680 {bio}[system/system] FastQC v0.11.9
  easybuild/easyconfigs/f/FastQC/FastQC-0.11.9-Java-1.8.eb
Labels: update

#10727 {tools}[foss/2020a] IPython v7.15.0 w/ Python 3.8.2
  easybuild/easyconfigs/i/IPython/IPython-7.15.0-foss-2020a-Python-3.8.2.eb
Labels: update

#10679 {bio}[GCC/7.3.0-2.30] Control-FREEC v11.5
  easybuild/easyconfigs/c/Control-FREEC/Control-FREEC-11.5-GCC-7.3.0-2.30.eb
Labels: update

#10735 {devel}[GCCcore/8.3.0,intel/2019b] hyperopt v0.2.4, Spark v2.4.5, Hadoop v2.10.0, ... w/ Python 3.7.4
  easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0-GCCcore-8.3.0-native.eb
  easybuild/easyconfigs/h/hyperopt/hyperopt-0.2.4-intel-2019b-Python-3.7.4-Java-1.8.eb
  easybuild/easyconfigs/p/protobuf/protobuf-2.5.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/Spark/Spark-2.4.5-intel-2019b-Python-3.7.4-Java-1.8.eb
Labels: 2020a, new, update

#10736 make sure WHAM is built with correct compiler
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.9.1-intel-2019a-kj_mol.eb
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.9.1-intel-2019a.eb
Labels: bug fix

#10738 {bio}[foss/2019b] MultiQC v1.8 w/ Python 3.7.4
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.8-foss-2019b-Python-3.7.4.eb
Labels: update

#10746 {data}[fosscuda/2019b] GDAL v3.0.2 w/ Python 3.7.4
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10743 {lang}[foss/2020a] rstudio v1.3.959
  easybuild/easyconfigs/a/ant/ant-1.10.8-Java-11.eb
  easybuild/easyconfigs/r/rstudio/rstudio-1.3.959-foss-2020a-Java-11-R-4.0.0.eb
  easybuild/easyconfigs/r/rstudio/rstudio-1.3.959_fix-rslave.patch
Labels: update

#10752 {bio}[gompi/2019b] manta v1.6.0 w/ Python 2.7.16
  easybuild/easyconfigs/m/manta/manta-1.6.0-gompi-2019b-Python-2.7.16.eb
Labels: update

#10710 Add Rgraphviz patch into Bioconductor ecs
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.10-foss-2019b.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: bug fix

#10750 {bio}[foss/2019b,foss/2020a] MultiQC v1.9 w/ Python 3.7.4 + 3.8.2
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.9-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.9-foss-2020a-Python-3.8.2.eb
Labels: update

#10740 {bio}[GCC/8.3.0] StringTie v2.1.3
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.3-GCC-8.3.0.eb
Labels: update

#10737 {bio}[GCCcore/8.3.0] cutadapt v2.10 w/ Python 3.7.4
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.10-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10758 {bio}[gompi/2020a] Centrifuge v1.0.4-beta, ncbi-vdb v2.10.7, NGS v2.10.5, file 5.38
  easybuild/easyconfigs/c/Centrifuge/Centrifuge-1.0.4-beta-gompi-2020a.eb
  easybuild/easyconfigs/c/Centrifuge/Centrifuge-1.0.4-beta_fix-SRA.patch
  easybuild/easyconfigs/f/file/file-5.38-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/NGS/NGS-2.10.5-GCC-9.3.0.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-2.10.7-gompi-2020a.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-2.10.7_fix-LD_LIBRARY_PATH.patch
Labels: update

#10759 {lib}[GCCcore/8.3.0] zstd v1.4.4
  easybuild/easyconfigs/z/zstd/zstd-1.4.4-GCCcore-8.3.0.eb
Labels: update

#10760 {devel}[GCCcore/8.3.0] dbus-glib v0.110
  easybuild/easyconfigs/d/dbus-glib/dbus-glib-0.110-GCCcore-8.3.0.eb
Labels: update

#10761 {lib}[GCCcore/8.3.0] FreeXL v1.0.5
  easybuild/easyconfigs/f/FreeXL/FreeXL-1.0.5-GCCcore-8.3.0.eb
Labels: update

#10763 {lib}[GCCcore/8.3.0] giflib v5.2.1
  easybuild/easyconfigs/g/giflib/giflib-5.2.1-GCCcore-8.3.0.eb
Labels: update

#10765 {system}[GCCcore/8.3.0] libgcrypt v1.8.5, libgpg-error v1.38
  easybuild/easyconfigs/l/libgcrypt/libgcrypt-1.8.5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.38-GCCcore-8.3.0.eb
Labels: update

#10768 {lib}[GCCcore/8.3.0] libtasn1 v4.16.0
  easybuild/easyconfigs/l/libtasn1/libtasn1-4.16.0-GCCcore-8.3.0.eb
Labels: update

#10754 {devel}[system] ReFrame v3.0
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.0.eb
Labels: update

#10677 Remove X86 hardcoding in LLVM
  easybuild/easyconfigs/l/LLVM/LLVM-10.0.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-7.0.0-GCCcore-7.2.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-7.0.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-7.0.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-8.0.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-GCCcore-9.3.0.eb
Labels: bug fix, change

#10762 {devel}[GCCcore/8.3.0] GConf v3.2.6
  easybuild/easyconfigs/g/GConf/GConf-3.2.6-GCCcore-8.3.0.eb
Labels: update

#10764 {lib}[GCCcore/8.3.0] libwebp v1.1.0
  easybuild/easyconfigs/l/libwebp/libwebp-1.1.0-GCCcore-8.3.0.eb
Labels: update

#10767 {lib}[GCC/8.3.0] libspatialite v4.3.0a
  easybuild/easyconfigs/l/libspatialite/libspatialite-4.3.0a-GCC-8.3.0-Python-3.7.4.eb
Labels: update

#10774 {vis}[foss/2019b] tensorboardX v2.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/tensorboardX/tensorboardX-2.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.4.2-foss-2019b-Python-3.7.4.eb
Labels: new, update

#10785 {bio}[GCCcore/9.3.0] MCL v14.137
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-9.3.0.eb
Labels: update

#10781 {data}[GCCcore/9.3.0] XML-LibXML v2.0205
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0205-GCCcore-9.3.0.eb
Labels: update

#10776 adding easyconfigs: BamTools-2.5.1-GCC-9.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-GCC-9.3.0.eb
Labels: update

#10780 {data}[GCCcore/9.3.0] DB_File v1.835
  easybuild/easyconfigs/d/DB_File/DB_File-1.835-GCCcore-9.3.0.eb
Labels: update

#10786 {tools}[GCCcore/9.3.0] parallel v20200522
  easybuild/easyconfigs/p/parallel/parallel-20200522-GCCcore-9.3.0.eb
Labels: update

#10773 {phys}[intel/2019b] Elk v6.3.2
  easybuild/easyconfigs/e/Elk/Elk-6.3.2-intel-2019b.eb
  easybuild/easyconfigs/e/Elk/Elk-6.3.2_dont_build_blas_lapack_fft.patch
Labels: update

#10790 fix source URL in recent ant easyconfigs
  easybuild/easyconfigs/a/ant/ant-1.10.6-Java-1.8.eb
  easybuild/easyconfigs/a/ant/ant-1.10.7-Java-11.eb
  easybuild/easyconfigs/a/ant/ant-1.10.8-Java-11.eb
Labels: bug fix

#10783 {lib}[GCCcore/9.3.0] libidn v1.35
  easybuild/easyconfigs/l/libidn/libidn-1.35-GCCcore-9.3.0.eb
Labels: update

#10782 {bio}[GCCcore/9.3.0] FastTree v2.1.11
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.11-GCCcore-9.3.0.eb
Labels: update

#10784 {bio}[GCC/9.3.0] MAFFT v7.453
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.453-GCC-9.3.0-with-extensions.eb
Labels: update

#10791 bump versions of GO.gb/org.Hs.eg.db/PFAM.db extensions in Bioconductor 3.11 bundle, since sources for old versions have disappeared
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: bug fix

#10792 {bio,tools}[intel/2020a] MultiQC v1.9, networkx v2.4 w/ Python 3.8.2
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.9-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/networkx/networkx-2.4-intel-2020a-Python-3.8.2.eb
Labels: update

#10793 {bio}[foss/2020a] QUAST v5.0.2 w/ Python 3.8.2
  easybuild/easyconfigs/q/QUAST/QUAST-5.0.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/q/QUAST/QUAST-5.0.2_fix-Python-3.8.patch
Labels: update

#10795 {math}[foss/2020a] numexpr v2.7.1 w/ Python 3.8.2
  easybuild/easyconfigs/n/numexpr/numexpr-2.7.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10770 {lib}[GCC/8.3.0] WebKitGTK+ v2.27.4
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.27.4-GCC-8.3.0.eb
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.27.4_turn_off_various_problematic_features.patch
Labels: update

#10778 {vis}[GCC/8.3.0] wxPython v4.0.7.post2 w/ Python 3.7.4
  easybuild/easyconfigs/w/wxPython/wxPython-4.0.7.post2-GCC-8.3.0-Python-3.7.4.eb
Labels: update

#10796 {bio}[gompi/2020a] BLAST+ v2.10.1
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.10.1-gompi-2020a.eb
Labels: update

#10777 {bio}[foss/2020a] CD-HIT v4.8.1
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-GCC-9.3.0.eb
Labels: update

#10828 {lib}[GCCcore/8.3.0] Unidecode v1.1.1 w/ Python 3.7.4
  easybuild/easyconfigs/u/Unidecode/Unidecode-1.1.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: new

#10827 {lib}[GCCcore/8.3.0] attrdict v2.0.1 w/ Python 3.7.4
  easybuild/easyconfigs/a/attrdict/attrdict-2.0.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: new

#10818 {bio}[GCC/9.3.0] StringTie v2.1.3
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.3-GCC-9.3.0.eb
Labels: update

#10817 {bio}[GCC/9.3.0] BCFtools v1.10.2
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.10.2-GCC-9.3.0.eb
Labels: update

#10826 {numlib}[GCC/9.3.0] beagle-lib v3.1.2
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.1.2-GCC-9.3.0.eb
Labels: update

#10832 {bio}[GCC/9.3.0] BEDTools v2.29.2
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.29.2-GCC-9.3.0.eb
Labels: update

#10824 {bio}[system/system] PLINK v1.9b_6.17-x86_64
  easybuild/easyconfigs/p/PLINK/PLINK-1.9b_6.17-x86_64.eb
Labels: update

#10821 {bio}[GCC/9.3.0] PRANK v170427
  easybuild/easyconfigs/p/PRANK/PRANK-170427-GCC-9.3.0.eb
Labels: update

#10815 {bio}[GCCcore/9.3.0] cutadapt v2.10 w/ Python 3.8.2
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.10-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#10816 {bio}[GCC/9.3.0] STAR v2.7.3a, STAR v2.5.3a
  easybuild/easyconfigs/s/STAR/STAR-2.5.3a-GCC-9.3.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.3a-GCC-9.3.0.eb
Labels: update

#10822 {vis}[GCCcore/9.3.0] plotly.py v4.8.1 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/p/plotly.py/plotly.py-4.8.1-GCCcore-9.3.0.eb
Labels: update

#10833 add drgee and stdReg extensions to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#10809 {math}[foss/2019b] SUNDIALS v5.1.0
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.1.0-foss-2019b.eb
Labels: update

#10794 {devel}[GCCcore/9.3.0] wget v1.20.3
  easybuild/easyconfigs/w/wget/wget-1.20.3-GCCcore-9.3.0.eb
Labels: update

#10835 {bio}[GCC/8.3.0] MAGMA v1.07bb
  easybuild/easyconfigs/m/MAGMA/MAGMA-1.07bb-GCC-8.3.0.eb
Labels: update

#10801 {data}[foss/2020a] PyTables v3.6.1 w/ Python 3.8.2
  easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10797 {data,tools}[foss/2020a] dask v2.18.1, bokeh v2.0.2 w/ Python 3.8.2
  easybuild/easyconfigs/b/bokeh/bokeh-2.0.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/d/dask/dask-2.18.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10802 {bio}[foss/2020a] Seaborn v0.10.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.10.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10803 {data}[foss/2020a] zarr v2.4.0 w/ Python 3.8.2
  easybuild/easyconfigs/z/zarr/zarr-2.4.0-foss-2020a-Python-3.8.2.eb
Labels: update

#10800 {data}[foss/2020a] scikit-learn v0.23.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10819 {bio}[gompi/2020a] Kraken2 v2.0.9-beta
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.9-beta-gompi-2020a-Perl-5.30.2.eb
Labels: update

#10798 {bio}[foss/2020a] bcolz v1.2.1 w/ Python 3.8.2
  easybuild/easyconfigs/b/bcolz/bcolz-1.2.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/b/bcolz/bcolz-1.2.1_fix-deprecation.patch
Labels: update

#10804 {bio}[foss/2020a] scikit-allel v1.2.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/scikit-allel/scikit-allel-1.2.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10837 {chem}[gompi/2019b] OpenBabel v3.1.1 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1_fix-distgeom-test.patch
Labels: update

#10830 {bio}[system/system] PAUP v4.0a166
  easybuild/easyconfigs/p/PAUP/PAUP-4.0a166-centos64.eb
Labels: new

#10841 {lang}[GCCcore/7.3.0] flex v2.5.39
  easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-7.3.0.eb
Labels: update

#10840 add BSgenome.Cfamiliaris.UCSC.canFam3 extension to Bioconductor 3.11 easyconfig
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#10814 {bio}[foss/2019b] SHAPEIT4 v4.1.3
  easybuild/easyconfigs/s/SHAPEIT4/SHAPEIT4-4.1.3-foss-2019b.eb
  easybuild/easyconfigs/s/SHAPEIT4/SHAPEIT4_use_EB_settings.patch
Labels: new

#10820 {bio}[GCCcore/9.3.0] BioPerl v1.7.7
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.7-GCCcore-9.3.0.eb
Labels: update

#10775 {tools}[foss/2019b] Ray v0.8.4: add dm-tree and lz4 as dependencies
  easybuild/easyconfigs/d/dm-tree/dm-tree-0.1.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/Ray/Ray-0.8.4-foss-2019b-Python-3.7.4.eb
Labels: enhancement, new

#10844 {bio}[GCCcore/9.3.0] Kraken v1.1.1
  easybuild/easyconfigs/k/Kraken/Kraken-1.1.1-GCCcore-9.3.0.eb
Labels: update

#10716 {vis}[foss/2020a] GTS v0.7.6
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-foss-2020a.eb
Labels: update

#10808 {math}[foss/2018b] SUNDIALS v2.7.0
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-2.7.0-foss-2018b.eb
Labels: update

#10709 {vis}[GCCcore/9.3.0,intel/2018a] GLFW v3.2.1, GLFW v3.3.2
  easybuild/easyconfigs/g/GLFW/GLFW-3.2.1-intel-2018a.eb
  easybuild/easyconfigs/g/GLFW/GLFW-3.3.2-GCCcore-9.3.0.eb
Labels: new

#10681 {bio}[system/system] picard v2.20.6
  easybuild/easyconfigs/p/picard/picard-2.20.6-Java-1.8.eb
Labels: update

#10739 {bio}[foss/2019b] STAR v2.5.3a
  easybuild/easyconfigs/s/STAR/STAR-2.5.3a-GCC-8.3.0.eb
Labels: update

#10706 {bio}[GCCcore/8.2.0] fastqsplitter v1.2.0 w/ Python 3.7.2
  easybuild/easyconfigs/f/fastqsplitter/fastqsplitter-1.2.0-GCCcore-8.2.0-Python-3.7.2.eb
Labels: new

#10787 {bio}[GCC/9.3.0] Pysam v0.16.0.1 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/p/Pysam/Pysam-0.16.0.1-GCC-9.3.0.eb
Labels: update

#10799 {tools}[dummy/dummy] itac v2019.4.036
  easybuild/easyconfigs/i/itac/itac-2019.4.036.eb
Labels: update

#10856 {tools}[system/system] git-lfs v2.11.0
  easybuild/easyconfigs/g/git-lfs/git-lfs-2.11.0.eb
Labels: update

#10852 {bio}[GCC/9.3.0] SPAdes v3.14.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.14.1-GCC-9.3.0-Python-3.8.2.eb
Labels: update

#10825 {bio}[foss/2020a] UMI-tools v1.0.1 w/ Python 3.8.2
  easybuild/easyconfigs/u/UMI-tools/UMI-tools-1.0.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10857 {bio}[foss/2020a] deepTools v3.3.1 w/ Python 3.8.2
  easybuild/easyconfigs/d/deepTools/deepTools-3.3.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10858 {bio}[foss/2018b] MEME v5.1.1 w/ Python 3.6.6
  easybuild/easyconfigs/m/MEME/MEME-5.1.1-foss-2018b-Python-3.6.6.eb
Labels: update

#10851 {data}[gompi/2019b] h4toh5 v2.2.3, HDF-EOS5 v1.16, HDF-EOS v2.20
  easybuild/easyconfigs/h/HDF-EOS/HDF-EOS-2.20-GCCcore-8.3.0.eb
  easybuild/easyconfigs/h/HDF-EOS5/HDF-EOS5-1.16-gompi-2019b.eb
  easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.3-foss-2018b.eb
  easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.3-gompi-2019b.eb
Labels: update

#10860 add missing kerneltree extension in FLAIR easyconfig
  easybuild/easyconfigs/f/FLAIR/FLAIR-1.5-foss-2019b-Python-3.7.4.eb
Labels: bug fix

#10850 {bio}[GCCcore/9.3.0] move NGS v2.10.5 from GCC to GCCcore
  easybuild/easyconfigs/n/NGS/NGS-2.10.5-GCCcore-9.3.0.eb
Labels: change

#10849 {perf}[foss/2019b] MUST v1.6 w/ Python 3.7.4
  easybuild/easyconfigs/m/MUST/MUST-1.6-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/MUST/MUST-1.6-foss-2019b-Python-3.7.4.eb
Labels: new

#10861 {numlib}[foss/2020a] Armadillo v9.900.1
  easybuild/easyconfigs/a/Armadillo/Armadillo-9.900.1-foss-2020a.eb
Labels: update

#10862 {lang}[foss/2020a,intel/2020a] numba v0.50.0 w/ Python 3.8.2
  easybuild/easyconfigs/n/numba/numba-0.50.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/numba/numba-0.50.0-intel-2020a-Python-3.8.2.eb
Labels: update

#10859 {bio}[intel/2020a] SimPEG v0.14.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/SimPEG/SimPEG-0.14.1-intel-2020a-Python-3.8.2.eb
Labels: update

#10869 fix source URLs in Eigen 3.3.* easyconfigs
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.2-foss-2016b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.2-intel-2016b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.3-GCCcore-6.3.0.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.3-intel-2016b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.4.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.5.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.7-GCCcore-9.3.0.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.7.eb
Labels: bug fix

#10872 fix source URLs for Eigen 3.2.*
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.10-intel-2016b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.3-foss-2016a.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.3-foss-2016b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.5.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.6.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-foss-2016a.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-intel-2016a.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.8-foss-2016a.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.8-intel-2016a.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.8.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.9-foss-2016b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.2.9-intel-2016b.eb
Labels: bug fix

#10873 refer to issue in GitHub repo in configparser patch, since Bitbucket repo is disappearing
  easybuild/easyconfigs/c/configparser/configparser-3.5.0-foss-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/c/configparser/configparser-3.5.0-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/c/configparser/configparser-3.5.0-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/c/configparser/configparser-3.5.0-intel-2016b-Python-3.5.2.eb
  easybuild/easyconfigs/c/configparser/configparser-3.5.0-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/c/configparser/configparser-3.5.0_no-backports-namespace.patch
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#10876 switch to GitHub source URL for HPDBSCAN
  easybuild/easyconfigs/h/HPDBSCAN/HPDBSCAN-20171110-foss-2017b.eb
Labels: bug fix

#10874 switch to github.com source URL for MetaPhlAn
  easybuild/easyconfigs/m/MetaPhlAn2/MetaPhlAn2-2.7.8-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/MetaPhlAn2/MetaPhlAn2-2.7.8-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/MetaPhlAn2/MetaPhlAn2-2.7.8_fix-download-db.patch
Labels: bug fix

#10875 switch to GitHub sources for ScientificPython 2.9.4
  easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-foss-2016a-Python-2.7.11.eb
  easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-intel-2016a-Python-2.7.11.eb
Labels: bug fix

#10881 {bio}[foss/2018b] HISAT2 2.2.0
  easybuild/easyconfigs/h/HISAT2/HISAT2-2.2.0-foss-2018b.eb
Labels: update

#10789 {bio}[intel/2019b] TopHat v2.1.2
  easybuild/easyconfigs/t/TopHat/TopHat-2.1.2-iimpi-2019b.eb
Labels: update

#10842 {bio}[gompi/2019b] MIRA v4.0.2
  easybuild/easyconfigs/g/gperftools/gperftools-2.6.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/MIRA/MIRA-4.0.2-foss-2018b.eb
  easybuild/easyconfigs/m/MIRA/MIRA-4.0.2-gompi-2019b.eb
  easybuild/easyconfigs/m/MIRA/MIRA-4.0.2_fix-ads-include.patch
Labels: update

#10847 {debugger}[gompi/2019b] Valgrind v3.16.1
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.16.1-gompi-2019b.eb
Labels: update
