Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-07, with the labels that each got.

#10877 {tools}[GCCcore/9.3.0] awscli v1.18.89 w/ Python 3.8.2
  easybuild/easyconfigs/a/awscli/awscli-1.18.89-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#10883 {data,geo,math}[foss/2019a] geopandas v0.8.0, Fiona v1.8.13.post1, Shapely v1.7.0 w/ Python 3.7.2
  easybuild/easyconfigs/f/Fiona/Fiona-1.8.13.post1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/g/geopandas/geopandas-0.8.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/s/Shapely/Shapely-1.7.0-foss-2019a-Python-3.7.2.eb
Labels: update

#10894 {lib}[gompi/2020a,iimpi/2020a] lwgrp v1.0.2
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.2-gompi-2020a.eb
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.2-iimpi-2020a.eb
Labels: update

#10892 {data}[gompi/2020a,iimpi/2020a] HDF5 1.12.0
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.0-gompi-2020a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.0-iimpi-2020a.eb
Labels: update

#10891 {numlib}[gompi/2020a] CGAL v4.14.3 w/ Python 3.8.2
  easybuild/easyconfigs/c/CGAL/CGAL-4.14.3-gompi-2020a-Python-3.8.2.eb
Labels: update

#10888 {bio}[GCC/9.3.0] seqtk v1.3
  easybuild/easyconfigs/s/seqtk/seqtk-1.3-GCC-9.3.0.eb
Labels: update

#10887 {tools}[system/system] vsc-mympirun v5.1.0
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.1.0.eb
Labels: update

#10268 {cae}[foss/2019b] OpenFOAM v7 (20200508)
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-20200508-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-foss-2019b-20200508.eb
Labels: update

#10878 Add Array::Transpose to Perl
  easybuild/easyconfigs/p/Perl/Perl-5.28.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: enhancement

#10895 {lib}[gompi/2020a,iimpi/2020a] dtcmp v1.1.0
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.0-gompi-2020a.eb
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.0-iimpi-2020a.eb
Labels: update

#10884 {tools}[foss/2020a,intel/2020a] poetry v1.0.9 w/ Python 3.8.2
  easybuild/easyconfigs/p/poetry/poetry-1.0.9-GCCcore-9.3.0-Python-3.8.2.eb
Labels: new

#10885 {math}[intel/2020a] PyBerny v0.6.2 w/ Python 3.8.2
  easybuild/easyconfigs/p/PyBerny/PyBerny-0.6.2-intel-2020a-Python-3.8.2.eb
Labels: new

#10889 {bio}[SYSTEM] IgBLAST v1.15.0
  easybuild/easyconfigs/i/IgBLAST/IgBLAST-1.15.0-x64-linux.eb
Labels: new

#10905 download x265 3.2/3.3 sources from bitbucket.org/multicoreware/x265_git
  easybuild/easyconfigs/x/x265/x265-3.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.3-GCCcore-9.3.0.eb
Labels: bug fix

#10901 {bio}[gompi/2020a] SRA-Toolkit v2.10.8
  easybuild/easyconfigs/s/SRA-Toolkit/NCBI-VDB-2.10.8_fix-LD_LIBRARY_PATH.patch
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-2.10.8-gompi-2020a.eb
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-2.10.8_fix-LD_LIBRARY_PATH.patch
Labels: update

#10886 {bio}[fosscuda/2019b] Bonito v0.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/b/Bonito/Bonito-0.2.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10904 add SingleR extension to Bioconductor 3.11 easyconfig
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#10890 {vis}[foss/2020a,intel/2020a] ParaView v5.8.0 w/ Python 3.8.2
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-foss-2020a-Python-3.8.2-mpi.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-intel-2020a-Python-3.8.2-mpi.eb
Labels: update

#10879 {data}[foss/2020a,intel/2020a] Arrow v0.17.1 w/ Python 3.8.2
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020a-Python-3.8.2.eb
Labels: update

#10902 add missing dependencies for geopandas 0.8.0 + fix pyproj version (2.2+ is required)
  easybuild/easyconfigs/g/geopandas/geopandas-0.8.0-foss-2019a-Python-3.7.2.eb
Labels: bug fix

#10882 {tools}[foss/2020a] arrow v0.17.1 w/ R 4.0.0
  easybuild/easyconfigs/a/arrow/arrow-0.17.1-foss-2020a-R-4.0.0.eb
Labels: new

#10900 {cae}[foss/2020a] OpenFOAM v2006
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2006-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2006-foss-2020a.eb
Labels: update

#10893 {perf}[gompi/2020a] Scalasca v2.5
  easybuild/easyconfigs/c/CubeGUI/CubeGUI-4.4.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.4.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.4.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PAPI/PAPI-6.0.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.6-GCCcore-9.3.0-tools.eb
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.5-gompi-2020a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompi-2020a.eb
Labels: update

#10911 add copCAR extension to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#10913 add ngspatial extension to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#10912 {lib}[GCCcore/9.3.0] CFITSIO v3.48
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.48-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.48_install_test_data.patch
Labels: update

#10806 {data}[fosscuda/2019b] pycocotools v2.0.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/pycocotools/pycocotools-2.0.0-fosscuda-2019b-Python-3.7.4.eb
Labels: new

#10788 {bio}[foss/2019b] TopHat v2.1.2
  easybuild/easyconfigs/t/TopHat/TopHat-2.1.2-gompi-2019b.eb
Labels: update

#10779 {geo}[fosscuda/2019b] GRASS v7.8.3 w/ Python 3.7.4
  easybuild/easyconfigs/g/GRASS/GRASS-7.8.3-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10595 {bio}[foss/2019b] ichorCNA v0.2.0
  easybuild/easyconfigs/i/ichorCNA/ichorCNA-0.2.0-foss-2019b.eb
Labels: new

#10580 {vis}[foss/2019a] OpenSlide v3.4.1
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1-GCCcore-8.2.0-largefiles.eb
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1_large_file_support.patch
Labels: update

#10576 {math}[foss/2019b] inferCNV v1.2.1, rjags v4-10, JAGS v4.3.0 w/ Python 3.7.4
  easybuild/easyconfigs/i/inferCNV/inferCNV-1.2.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/j/JAGS/JAGS-4.3.0-foss-2019b.eb
  easybuild/easyconfigs/r/rjags/rjags-4-10-foss-2019b.eb
Labels: update

#10843 {bio}[foss/2020a] Roary v3.13.0
  easybuild/easyconfigs/r/Roary/Roary-3.13.0-foss-2020a.eb
  easybuild/easyconfigs/r/Roary/Roary-3.13.0_fix-CD-HIT-regexp.patch
Labels: update

#10914 add drugCombo extension to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#10526 {vis}[intel/2019b] NiBabel v3.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.1.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/n/Nipype/Nipype-1.4.2-intel-2019b-Python-3.7.4.eb
Labels: update

#10903 {chem}[intel/2020a] cclib v1.6.3 w/ Python 3.8.2
  easybuild/easyconfigs/c/cclib/cclib-1.6.3-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/c/cclib/cclib-1.6.3-intel-2020a-Python-3.8.2.eb
Labels: update

#10471 {math}[intel/2019b] gmsh v4.5.6 w/ Python 2.7.16
  easybuild/easyconfigs/g/gmsh/gmsh-4.5.6-intel-2019b-Python-2.7.16.eb
Labels: update

#10440 {tools}[foss/2016a] git-extras v5.1.0
  easybuild/easyconfigs/g/git-extras/git-extras-5.1.0-foss-2016a.eb
Labels: new

#10514 {data,lib}[GCCcore/8.3.0,foss/2019b] ROOT v6.20.04, CFITSIO v3.47 w/ Python 3.7.4
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.47-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.20.04-foss-2019b-Python-3.7.4.eb
Labels: update

#10267 {math}[intel/2019b] statsmodels v0.9.0 w/ Python 2.7.16
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.9.0-intel-2019b-Python-2.7.16.eb
Labels: update

#10523 {cae,numlib,phys}[foss/2019b] GATE v9.0, Geant4 v10.6, CLHEP v2.4.1.3
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.1.3-foss-2019b.eb
  easybuild/easyconfigs/g/GATE/GATE-9.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.6-foss-2019b.eb
Labels: update

#10917 {lib}[GCCcore/9.3.0] fix sanity_check_paths of CFITSIO-3.48-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.48-GCCcore-9.3.0.eb
Labels: bug fix

#10897 {bio}[foss/2018b,gompi/2019b] MITObim v1.9.1
  easybuild/easyconfigs/m/MITObim/MITObim-1.9.1-foss-2018b.eb
  easybuild/easyconfigs/m/MITObim/MITObim-1.9.1-gompi-2019b.eb
Labels: new

#10915 {lib}[GCCcore/8.3.0,GCCcore/9.3.0] gc v7.6.12: fix download URL for libatomic
  easybuild/easyconfigs/g/gc/gc-7.6.12-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/gc/gc-7.6.12-GCCcore-9.3.0.eb
Labels: bug fix

#10909 {bio}[foss/2020a] TEtranscripts 2.2.0 w/ Python 2.7.18 & 3.8.2
  easybuild/easyconfigs/t/TEtranscripts/TEtranscripts-2.2.0-foss-2020a.eb
Labels: new

#10916 {data}[GCCcore/8.3.0] OpenPyXL v2.6.4: rename to openpyxl
  easybuild/easyconfigs/f/FusionCatcher/FusionCatcher-1.20-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/o/openpyxl/openpyxl-2.6.4-GCCcore-8.3.0-Python-2.7.16.eb
Labels: change

#10864 add intel/2020.06 toolchain: based one intel/2020a but with impi 2018 update 5
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2020.06-impi-18.5.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2020.06-impi-18.5.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.1.217-iimpi-2020.06-impi-18.5.eb
  easybuild/easyconfigs/i/impi/impi-2018.5.288-iccifort-2020.1.217.eb
  easybuild/easyconfigs/i/intel/intel-2020.06-impi-18.5.eb
Labels: update

#10671 add -fPIC to toolchainopts for Lua-5.3.5
  easybuild/easyconfigs/l/Lua/Lua-5.3.5-GCCcore-9.3.0.eb
Labels: bug fix

#9743 {bio}[foss/2019a,fosscuda/2019a] mhcnuggets v2.3 w/ Python 3.7.2
  easybuild/easyconfigs/m/mhcnuggets/mhcnuggets-2.3-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/m/mhcnuggets/mhcnuggets-2.3-fosscuda-2019a-Python-3.7.2.eb
Labels: new

#10836 {math}[system/system] Mathematica v12.1.1
  easybuild/easyconfigs/m/Mathematica/Mathematica-12.1.1.eb
Labels: update

#10846 {math}[system/system] Mathematica v12.1.1 (orig)
  easybuild/easyconfigs/m/Mathematica/Mathematica-12.1.1-orig.eb
Labels: update

#10772 {devel}[multiple] Define MAX_JOBS in easyconfigs of PyTorch from v1.1.0 to v1.4.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.1.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.3.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.3.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#10921 Add sanity check commands to TEtranscripts-2.2.0-foss-2020a easyconfig
  easybuild/easyconfigs/t/TEtranscripts/TEtranscripts-2.2.0-foss-2020a.eb
Labels: enhancement

#10923 add missing dependencies for geopandas 0.7.0
  easybuild/easyconfigs/g/geopandas/geopandas-0.7.0-foss-2019b-Python-3.7.4.eb
Labels: bug fix

#10930 remove easyconfig for original Mathematica 12.1.1 release, to avoid confusion
  easybuild/easyconfigs/m/Mathematica/Mathematica-12.1.1-orig.eb
Labels: change

#10712 {chem}[intel/2020a] LAMMPS v3Mar2020 w/ Python 3.8.2
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2020a-Python-3.8.2-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020_fix-docs-build.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#10936 Whitelist CUDA bundles from sanity_check_paths requirement
  test/easyconfigs/easyconfigs.py
Labels: change

#10937 prepare release notes for EasyBuild v4.2.2
  RELEASE_NOTES
  setup.py
Labels: update

#10855 {lib}[GCCcore/8.3.0] Xerces-C++ v3.2.2
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.2-GCCcore-8.3.0.eb
Labels: update

#10939 {tools}[dummy/dummy] EasyBuild v4.2.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.2.2.eb
Labels: update

#10942 sync develop with master + bump version to 4.2.3dev
  RELEASE_NOTES
  setup.py
Labels: update

#10927 also build Python libraries for ParaView 5.8.0
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-foss-2020a-Python-3.8.2-mpi.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-intel-2020a-Python-3.8.2-mpi.eb
Labels: enhancement

#10943 {bio}[foss/2019b] Telescope v1.0.3 w/ Python 3.7.4
  easybuild/easyconfigs/t/Telescope/Telescope-1.0.3-foss-2019b-Python-3.7.4.eb
Labels: new

#10956 {lib,tools}[GCCcore/9.3.0] cdsapi v0.3.0, tqdm v4.47.0 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/c/cdsapi/cdsapi-0.3.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.47.0-GCCcore-9.3.0.eb
Labels: update

#10953 {astro}[foss/2020a] CRPropa v3.1.6 w/ Python 3.8.2
  easybuild/easyconfigs/c/CRPropa/CRPropa-3.1.6-foss-2020a-Python-3.8.2.eb
Labels: update

#10934 {bio}[gompi/2020a] manta v1.6.0 w/ Python 2.7.18
  easybuild/easyconfigs/m/manta/manta-1.6.0-gompi-2020a-Python-2.7.18.eb
Labels: update

#10957 {bio}[foss/2019b] Portcullis v1.2.2 w/ Python 3.7.4
  easybuild/easyconfigs/p/Portcullis/Portcullis-1.2.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/Portcullis/Portcullis-1.2.2_fix-datadir-path.patch
Labels: new

#10926 {cae}[system/system] LS-PrePost v4.6.24, LS-PrePost v4.7.15
  easybuild/easyconfigs/l/LS-PrePost/LS-PrePost-4.6.24.eb
  easybuild/easyconfigs/l/LS-PrePost/LS-PrePost-4.7.15.eb
Labels: update

#10919 {vis}[GCCcore/9.3.0] jbigkit v2.1
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1-GCCcore-9.3.0.eb
Labels: update

#10867 {bio}[foss/2019b] arcasHLA v0.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/arcasHLA/arcasHLA-0.2.0-foss-2019b-Python-3.7.4.eb
Labels: new

#10966 {bio}[GCCcore/9.3.0] GD v2.71, Circos v0.69-9
  easybuild/easyconfigs/c/Circos/Circos-0.69-9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GD/GD-2.71-GCCcore-9.3.0.eb
Labels: update

#10963 {bio}[foss/2019b,fosscuda/2019b] ctffind v4.1.14
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2019b.eb
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-fosscuda-2019b.eb
Labels: update

#10964 {bio}[GCCcore/8.3.0] MotionCor2 v1.3.2
  easybuild/easyconfigs/m/MotionCor2/MotionCor2-1.3.2-GCCcore-8.3.0.eb
Labels: update

#10931 {chem}[intel/2019b] rickflow v0.7.0-20200529 w/ Python 3.7.4
  easybuild/easyconfigs/r/rickflow/rickflow-0.7.0-20200529-intel-2019b-Python-3.7.4.eb
Labels: update

#10947 {compiler}[GCCcore/9.3.0] Clang v10.0.0
  easybuild/easyconfigs/c/Clang/Clang-10.0.0-GCCcore-9.3.0.eb
Labels: update

#10960 OpenBLAS-0.3.9: Fix lapack.h for use with C++
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.9-GCC-9.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.9_fix-lapack_h.patch
Labels: bug fix

#10848 Patch to fix exporting images with PyQtGraph v0.10.0
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-ImageExporter.patch
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-intel-2019a-Python-3.7.2.eb
Labels: bug fix

#10829 {bio}[GCCcore/9.3.0] Bracken v2.6.0
  easybuild/easyconfigs/b/Bracken/Bracken-2.6.0-GCCcore-9.3.0.eb
Labels: new

#10975 {devel}[GCCcore/9.3.0] makedepend v1.0.6 and xproto v7.0.31
  easybuild/easyconfigs/m/makedepend/makedepend-1.0.6-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-9.3.0.eb
Labels: update

#10972 netCDF-Fortran: Add missing build dep on M4 for 2019b versions
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompi-2019b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-iimpi-2019b.eb
Labels: bug fix

#10732 {astro,math,phys}[foss/2020a] PlasmaPy v0.3.1, mpmath v1.1.0, astropy v4.0.1 w/ Python 3.8.2
  easybuild/easyconfigs/a/astropy/astropy-4.0.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/mpmath/mpmath-1.1.0-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/p/PlasmaPy/PlasmaPy-0.3.1-foss-2020a-Python-3.8.2.eb
Labels: new, update

#10979 {data}[gompic/2019b,iimpic/2019b] netCDF-Fortran v4.5.2
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompic-2019b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-iimpic-2019b.eb
Labels: update

#10982 {vis}[fosscuda/2019b] matplotlib v2.2.4 w/ Python 2.7.16
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-fosscuda-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-fosscuda-2019b-Python-2.7.16.eb
Labels: update

#10981 {lib}[gompic/2019b,iimpi/2019b,iimpic/2019b] Boost.Python v1.71.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-gompic-2019b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-iimpi-2019b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-iimpic-2019b.eb
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-iimpic-2019b.eb
Labels: update

#10929 [magma] Use CMakeMake to avoid C++11 related failures on Power
  easybuild/easyconfigs/m/magma/magma-2.5.1-fosscuda-2019a.eb
  easybuild/easyconfigs/m/magma/magma-2.5.1-fosscuda-2019b.eb
Labels: change

#10022 {devel}[intelcuda/2019b] PyFR v1.9.0 w/ Python 3.7.4
  easybuild/easyconfigs/c/CGNS/CGNS-4.1.0-intelcuda-2019b.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-intelcuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.0.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/PyCUDA/PyCUDA-2019.1.2-intelcuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyFR/PyFR-1.9.0-intelcuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-iimpic-2019b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-intelcuda-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#10958 {math}[foss/2019b] itpp v4.3.1
  easybuild/easyconfigs/i/itpp/itpp-4.3.1-foss-2019b.eb
Labels: new

#10928 {tools}[SYSTEM] JUBE v2.4.0
  easybuild/easyconfigs/j/JUBE/JUBE-2.4.0.eb
Labels: update

#10987 {system}[gompi/2020a] ADOL-C v2.7.2
  easybuild/easyconfigs/a/ADOL-C/ADOL-C-2.7.2-gompi-2020a.eb
Labels: update

#10971 {chem}[foss/2019b] NAMD v2.13
  easybuild/easyconfigs/n/NAMD/NAMD-2.13-foss-2019b-mpi.eb
Labels: update

#10974 {lib}[GCCcore/9.3.0] lxml v4.5.2 and libxslt v1.1.34 {REVIEW}
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/lxml/lxml-4.5.2-GCCcore-9.3.0.eb
Labels: update

#10986 {bio}[GCCcore/8.3.0] PennCNV v1.0.5
  easybuild/easyconfigs/p/PennCNV/PennCNV-1.0.5-GCCcore-8.3.0.eb
Labels: new

#10969 {lang}[GCCcore/8.3.0] move intervaltree and sortedcontainers to main Python easyconfigs
  easybuild/easyconfigs/d/dask/dask-2.8.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/d/dask/dask-2.8.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/f/FLAIR/FLAIR-1.5-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/i/igv-reports/igv-reports-0.9.8-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.7.4-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/Telescope/Telescope-1.0.3-foss-2019b-Python-3.7.4.eb
Labels: change

#10996 {vis}[foss/2020a] scikit-image v0.17.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.17.1-foss-2020a-Python-3.8.2.eb
Labels: update

#10995 {data}[GCCcore/9.3.0] BeautifulSoup v4.9.1 w/ Python 3.8.2
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.9.1-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#10955 {data}[foss/2019b] pycocotools v2.0.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/pycocotools/pycocotools-2.0.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10959 {tools}[gompi/2019b] ioapi v3.2-2020111
  easybuild/easyconfigs/i/ioapi/ioapi-3.2-2020111-gompi-2019b-nocpl.eb
Labels: new

#10998 {lang}[GCCcore/9.3.0] expect v5.45.4
  easybuild/easyconfigs/e/expect/expect-5.45.4-GCCcore-9.3.0.eb
Labels: update

#10999 {chem}[fosscuda/2019b] ASE v3.19.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11001 {bio}[gompi/2019b] Cufflinks v2.2.1
  easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.2.1-gompi-2019b.eb
Labels: update

#10997 {bio}[gompi/2020a] Salmon v.1.3.0
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.2.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/Salmon/Salmon-1.3.0-gompi-2020a.eb
Labels: update

#11004 OpenBabel-3.1.1 still uses 3.1.0 for the name of a couple directories, so symlink from them to 3.1.1 in postinstallcmds so BABEL_LIBDIR and BABEL_DATADIR work properly.
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2019b-Python-3.7.4.eb
Labels: bug fix

#10990 {lib}[foss/2020a] HeFFTe v1.0
  easybuild/easyconfigs/h/HeFFTe/HeFFTe-1.0-foss-2020a.eb
Labels: new

#11008 use travis_wait to extend 10m timeout when no output is produced
  .travis.yml
Labels: bug fix

#11003 Pandoc version 2.10
  easybuild/easyconfigs/p/Pandoc/Pandoc-2.10.eb
Labels: update

#11010 {lib}[foss/2020a] tidymodels v0.1.0
  easybuild/easyconfigs/t/tidymodels/tidymodels-0.1.0-foss-2020a-R-4.0.0.eb
Labels: new

#11015 {data}[GCCcore/7.3.0,GCCcore/8.3.0] datamash v1.5
  easybuild/easyconfigs/d/datamash/datamash-1.5-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/datamash/datamash-1.5-GCCcore-8.3.0.eb
Labels: update

#10994 {bio}[foss/2018b] OpenMS v2.4.0
  easybuild/easyconfigs/c/Cbc/Cbc-2.10.3-foss-2018b.eb
  easybuild/easyconfigs/c/Cgl/Cgl-0.60.2-foss-2018b.eb
  easybuild/easyconfigs/c/Clp/Clp-1.17.3-foss-2018b.eb
  easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.3-foss-2018b.eb
  easybuild/easyconfigs/o/OpenMS/OpenMS-2.4.0-foss-2018b.eb
  easybuild/easyconfigs/o/Osi/Osi-0.108.5-GCCcore-7.3.0.eb
  easybuild/easyconfigs/o/Osi/Osi-0.108.5-foss-2018b.eb
  easybuild/easyconfigs/s/SYMPHONY/SYMPHONY-5.6.16-foss-2018b.eb
Labels: new

#11017 {tools}[GCCcore/8.3.0] Emacs v26.3
  easybuild/easyconfigs/e/Emacs/Emacs-26.3-GCCcore-8.3.0.eb
Labels: update

#11021 add FlowSorted.Blood.EPIC extension to R-bundle-Bioconductor-3.11
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#10993 {devel}[foss/2018b] libosmium v2.15.4
  easybuild/easyconfigs/l/libosmium/libosmium-2.15.4-foss-2018b-Python-3.6.6.eb
Labels: new

#11020 Use is_generic_easyblock from filetools
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#11022 {cae}[foss/2020a] OpenFOAM v8
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8-foss-2020a.eb
Labels: update

#11016 {bio}[foss/2018b,foss/2019b] EIGENSOFT v7.2.1
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2018b.eb
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2019b.eb
Labels: update

#11013 {chem}[foss/2020a,intel/2020a] RDKit v2020.03.3 w/ Python 3.8.2
  easybuild/easyconfigs/r/RDKit/RDKit-2020.03.3-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/r/RDKit/RDKit-2020.03.3-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/r/RDKit/RDKit-2020.03.3_skip_tests.patch
Labels: update

#11005 {data}[foss/2020a,intel/2020a] netcdf4-python v1.5.3 w/ Python 3.8.2
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.3-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.3-intel-2020a-Python-3.8.2.eb
Labels: update

#11036 added only gomkl, iomkl, iompi, and imkl compiled at the MPI level
  easybuild/easyconfigs/g/gomkl/gomkl-2020a.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.1.217-gompi-2020a.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.1.217-iompi-2020a.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2020a.eb
  easybuild/easyconfigs/i/iompi/iompi-2020a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-iccifort-2020.1.217.eb
Labels: update

#11028 {bio}[GCC/8.3.0] segemehl v0.3.4
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-8.3.0.eb
Labels: update

#11024 {devel}[GCCcore/8.3.0,foss/2019b] libosmium v2.15.6, protozero v1.7.0
  easybuild/easyconfigs/l/libosmium/libosmium-2.15.6-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/protozero/protozero-1.7.0-GCCcore-8.3.0.eb
Labels: update
