Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-03, with the labels that each got.

#9938 {compiler}[system/system] ispc v1.12.0
  easybuild/easyconfigs/i/ispc/ispc-1.12.0.eb
Labels: update

#9559 {bio}[foss-2019a] Trinity-2.9.0
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-8.3.0.eb
  easybuild/easyconfigs/s/Salmon/Salmon-1.0.0-gompi-2019b.eb
  easybuild/easyconfigs/t/Trinity/Trinity-2.9.0-foss-2019b.eb
Labels: update

#9939 {cae,vis}[GCCcore/8.3.0,foss/2019b] occt v7.3.0p4, FreeImage v3.18.0
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/occt/occt-7.3.0p4-foss-2019b.eb
Labels: new, update

#9538 {math}[foss/2019b,fosscuda/2019b] Keras v2.3.1, TensorFlow v2.1.0, libgpuarray v0.7.6, Theano v1.0.4, R-keras v2.2.5.0 w/ Python 3.7.4
  easybuild/easyconfigs/k/Keras/Keras-2.3.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/k/Keras/Keras-2.3.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/R-keras/R-keras-2.2.5.0-foss-2019b-Python-3.7.4-R-3.6.2.eb
  easybuild/easyconfigs/r/R-keras/R-keras-2.2.5.0-fosscuda-2019b-Python-3.7.4-R-3.6.2.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/Theano/Theano-1.0.4-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/Theano/Theano-1.0.4-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9901 [GCCcore-8.3.0] Perl-5.30.0: Added Term::ReadLine::Gnu, which requires ncurses as a dependency.
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
Labels: enhancement

#9798 {bio}[system/system] manta v1.6.0
  easybuild/easyconfigs/m/manta/manta-1.6.0.eb
Labels: new

#9947 fix broken tests due to multile TensorFlow versions being used as dependency in 2019b generation by using TensorFlow 2.1.0 as dep for PlasFlow
  easybuild/easyconfigs/p/PlasFlow/PlasFlow-1.1.0-foss-2019b-Python-3.7.4.eb
Labels: bug fix, change

#9904 {math}[foss/2019b] polymake v4.0r1
  easybuild/easyconfigs/p/polymake/polymake-4.0r1-foss-2019b.eb
Labels: new

#9689 {bio}[system/system] gubbins v2.4.0
  easybuild/easyconfigs/g/gubbins/gubbins-2.4.0.eb
Labels: new

#9953 {bio}[gompi/2019b] Salmon v1.1.0
  easybuild/easyconfigs/s/Salmon/Salmon-1.1.0-gompi-2019b.eb
Labels: update

#9949 {lang}[GCCcore/9.2.0] Python v3.8.2 (+ deps)
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-9.2.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-GCCcore-9.2.0.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-GCCcore-9.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.0-GCCcore-9.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.2.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.31.1-GCCcore-9.2.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-GCCcore-9.2.0.eb
Labels: 2020a, update

#9959 {vis}[intel/2019b] OpenPIV v0.21.8 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenPIV/OpenPIV-0.21.8-intel-2019b-Python-3.7.4.eb
Labels: new

#9956 {bio}[foss/2019b] kallisto v0.46.1
  easybuild/easyconfigs/k/kallisto/kallisto-0.46.1-foss-2019b.eb
Labels: update

#9960 {bio}[GCC/8.3.0] GMAP-GSNAP v2019-09-12
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2019-09-12-GCC-8.3.0.eb
Labels: update

#9893 {bio}[iimpi/2019b] RAxML v8.2.12
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-iimpi-2019b-hybrid-avx2.eb
Labels: update

#9872 {bio}[GCC/8.2.0-2.31.1] BBMap v38.76
  easybuild/easyconfigs/b/BBMap/BBMap-38.76-GCC-8.2.0-2.31.1.eb
Labels: update

#9914 {cae}[intel/2019b] OpenFOAM v2.3.1
  easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1-intel-2019b.eb
Labels: update

#5104 {bio}[system] manta v1.1.1
  easybuild/easyconfigs/m/manta/manta-1.1.1.eb
Labels: new

#9773 add Lua as a dependency to gnuplot
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-foss-2018a.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-intel-2018a.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.5-foss-2018b.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6-foss-2018b.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.6-fosscuda-2018b.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.8-GCCcore-8.3.0.eb
Labels: bug fix

#9954 fix source URLs for rgeos after source tarball was moved to CRAN archive
  easybuild/easyconfigs/r/rgeos/rgeos-0.3-17-intel-2016a-R-3.2.3.eb
  easybuild/easyconfigs/r/rgeos/rgeos-0.5-1-foss-2019a-R-3.6.0.eb
  easybuild/easyconfigs/r/rgeos/rgeos-0.5-2-foss-2019b-R-3.6.2.eb
Labels: bug fix

#9965 update to OpenMPI 4.0.3rc4 in gompi/2020a-rc2 + foss/2020a-rc2
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020a-rc2.eb
  easybuild/easyconfigs/f/foss/foss-2020a-rc2.eb
  easybuild/easyconfigs/g/gompi/gompi-2020a-rc2.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2020a-rc2.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3rc4-GCC-9.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a-rc2.eb
Labels: 2020a, change, update

#9958 {tools}[GCCcore/8.3.0] UnZip v6.0, Zip v3.0
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-8.3.0.eb
Labels: new, update

#9971 {tools}[GCCcore/8.2.0] Zip v3.0
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-8.2.0.eb
Labels: new

#9749 {bio}[foss/2018b] split-seq v20190717 w/ Python 3.6.6
  easybuild/easyconfigs/s/split-seq/split-seq-20190717-foss-2018b-Python-3.6.6.eb
Labels: new

#9132 {math}[iimpi/2019a] Ray v2.3.1
  easybuild/easyconfigs/r/Ray/Ray-2.3.1-iimpi-2019a.eb
Labels: new

#9955 {geo}[foss/2019a] OCNet v0.2.0, SSN v1.1.14
  easybuild/easyconfigs/o/OCNet/OCNet-0.2.0-foss-2019a-R-3.6.0.eb
  easybuild/easyconfigs/s/SSN/SSN-1.1.14-foss-2019a-R-3.6.0.eb
Labels: new

#9952 {vis}[GCCcore/8.3.0,foss/2019b,intel/2019b] Grace v5.1.25, motif v2.3.8
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2019b-5build1.eb
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2019b-5build1.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-GCCcore-8.3.0.eb
Labels: update

#9966 Patch GCC lisanitizer for glibc 2.31
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.2.0-fix-glibc-2.31-libsanitizer.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.2.0.eb
Labels: bug fix

#9970 {vis}[GCCcore/8.3.0] GObject-Introspection v1.58.3, PyGObject v3.34.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.58.3-GCCcore-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.34.0-GCCcore-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.34.0-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9862 {vis}[foss/2019b] Ferret v7.5.0
  easybuild/easyconfigs/f/Ferret/Ferret-7.5.0-foss-2019b.eb
Labels: update

#9969 {vis}[foss/2019b] pygraphviz v1.5 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/p/pygraphviz/pygraphviz-1.5-foss-2019b.eb
Labels: new

#9974 {lib}[foss/2019b] RDFlib v4.2.2 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/r/RDFlib/RDFlib-4.2.2-foss-2019b.eb
Labels: update

#9975 stick to GCCcore toolchain for RDFlib, no need for a full toolchain
  easybuild/easyconfigs/r/RDFlib/RDFlib-4.2.2-GCCcore-8.3.0.eb
Labels: change

#9972 add Zip as build dependency for recent Bazel versions
  easybuild/easyconfigs/b/Bazel/Bazel-0.20.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.25.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-1.1.0-GCCcore-8.3.0.eb
Labels: bug fix

#9920 candidate definition for intel/2020a common toolchain (rc1)
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2020a-rc1.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2020a-rc1.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.0.166-iimpi-2020a-rc1.eb
  easybuild/easyconfigs/i/intel/intel-2020a-rc1.eb
Labels: 2020a, update

#9979 {devel,tools}[GCCcore/9.2.0] CMake v3.16.4, cURL v7.69.0
  easybuild/easyconfigs/c/CMake/CMake-3.16.4-GCCcore-9.2.0.eb
  easybuild/easyconfigs/c/cURL/cURL-7.69.0-GCCcore-9.2.0.eb
Labels: 2020a, update

#9980 {bio}[foss/2018b] StringTie v2.1.0
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.0-foss-2018b.eb
Labels: update

#9968 {lib}[foss/2019b] igraph v0.8.0, python-igraph v0.8.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/i/igraph/igraph-0.8.0-foss-2019b.eb
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.8.0-foss-2019b.eb
Labels: update

#9977 {vis}[GCC/8.3.0] igv-reports v0.9.8 w/ Python 3.7.4
  easybuild/easyconfigs/i/igv-reports/igv-reports-0.9.8-GCC-8.3.0-Python-3.7.4.eb
Labels: new

#9976 {devel}[foss/2019b] PyTorch-Geometric v1.3.2 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-1.3.2-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#9985 switch to final release of OpenMPI 4.0.3 for foss/2020a-rc3
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020a-rc3.eb
  easybuild/easyconfigs/f/foss/foss-2020a-rc3.eb
  easybuild/easyconfigs/g/gompi/gompi-2020a-rc3.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2020a-rc3.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-GCC-9.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a-rc3.eb
Labels: 2020a, update

#9992 {bio}[GCC/8.3.0] BLAT v3.5
  easybuild/easyconfigs/b/BLAT/BLAT-3.5-GCC-8.3.0.eb
Labels: update

#9423 {chem}[intel/2019a] OpenBabel v2.4.1 w/ Python 3.7.2
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-2.4.1-intel-2019a-Python-3.7.2.eb
Labels: update

#9937 {math}[GCCcore/7.3.0] CoinUtils v2.11.3
  easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.3-GCCcore-7.3.0.eb
Labels: new

#9997 {bio}[GCC/8.2.0-2.31.1,GCC/8.3.0] Jellyfish v2.3.0: fix checksums
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-8.3.0.eb
Labels: bug fix

#9999 {lib}[foss/2020a-rc3] SciPy-bundle v2020.02, pybind11 v2.4.3 w/ Python 3.8.2
  easybuild/easyconfigs/p/pybind11/pybind11-2.4.3-GCCcore-9.2.0-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.02-foss-2020a-rc3-Python-3.8.2.eb
Labels: 2020a, update

#10007 {math}[GCCcore/7.3.0] Osi v0.108.5
  easybuild/easyconfigs/o/Osi/Osi-0.108.5-GCCcore-7.3.0.eb
Labels: new

#9694 Removing intel-specific sanity check for libdrm
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.97-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.99-GCCcore-8.3.0.eb
Labels: bug fix, change

#10010 add pthread patch for scipy 1.4.1 in SciPy-bundle to fix issue on ppc64le
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.02-foss-2020a-rc3-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/scipy-1.4.1-fix-pthread.patch
Labels: 2020a, bug fix

#9981 {devel}[gompi/2020a-rc3] Boost v1.72.0
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-gompi-2020a-rc3.eb
Labels: 2020a, update

#10019 fix source URLs for ParMGridGen easyconfigs
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gimkl-2.11.5.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-iimpi-2019b.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-intel-2016a.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-intel-2017a.eb
Labels: bug fix

#10015 {tools}[foss/2020a-rc3] networkx v2.4 w/ Python 3.8.2
  easybuild/easyconfigs/n/networkx/networkx-2.4-foss-2020a-rc3-Python-3.8.2.eb
Labels: 2020a, update

#10014 {lib}[foss/2020a-rc3] scikit-build v0.10.0 w/ Python 3.8.2
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.10.0-foss-2020a-rc3-Python-3.8.2.eb
Labels: 2020a, update

#9988 PRSice EB file created
  easybuild/easyconfigs/p/PRSice/PRSice-2.2.12-GCCcore-8.3.0.eb
Labels: new

#10020 fix homepage/description for PyTorch-Geometric
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-1.3.2-foss-2019b-Python-3.7.4.eb
Labels: change

#10018 use https in homepage/source_urls of zlib-1.2.11.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb
Labels: change

#9987 {bio}[system/system] IGV v2.8.0
  easybuild/easyconfigs/i/IGV/IGV-2.8.0-Java-11.eb
Labels: update

#10021 {lang}[GCCcore/8.3.0] Mono v6.8.0.105
  easybuild/easyconfigs/m/Mono/Mono-6.8.0.105-GCCcore-8.3.0.eb
Labels: update

#10005 {bio}[GCC/8.3.0] Winnowmap v1.0
  easybuild/easyconfigs/w/Winnowmap/Winnowmap-1.0-GCC-8.3.0.eb
Labels: new

#9996 {bio,devel}[foss/2019b] Sailfish v0.10.1
  easybuild/easyconfigs/g/g2log/g2log-1.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1-gompi-2019b.eb
Labels: update

#9983 {data}[intel/2019b] PartitionFinder v2.1.1, PyTables v3.5.2, pyparsing v2.4.6, ... w/ Python 2.7.16
  easybuild/easyconfigs/n/numexpr/numexpr-2.7.1-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/p/PartitionFinder/PartitionFinder-2.1.1-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.5.2-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/p/pyparsing/pyparsing-2.4.6-GCCcore-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.4-intel-2019b-Python-2.7.16.eb
Labels: new, update

#10035 {math}[foss/2018b] MUMPS v5.2.1
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.2.1-foss-2018b-metis.eb
Labels: update

#10034 {vis}[foss/2019a] mayavi v4.7.1 w/ Python 2.7.15
  easybuild/easyconfigs/m/mayavi/mayavi-4.7.1-foss-2019a-Python-2.7.15.eb
Labels: update

#10030 {math}[system/system] Singular v4.1.2
  easybuild/easyconfigs/s/Singular/Singular-4.1.2.eb
Labels: new

#10033 {math}[foss/2018b] Clp v1.17.3
  easybuild/easyconfigs/c/Clp/Clp-1.17.3-foss-2018b.eb
Labels: new

#9995 {devel}[foss/2019b] PyTorch-Geometric v1.4.2 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-1.4.2-foss-2019b-Python-3.7.4-PyTorch-1.4.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#10036 {data}[foss/2019a] ADIOS v1.13.1 w/ Python 2.7.15
  easybuild/easyconfigs/a/ADIOS/ADIOS-1.13.1-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/a/ADIOS/ADIOS-1.13.1_fix_missing_thread_lib.patch
  easybuild/easyconfigs/a/ADIOS/ADIOS-1.13.1_fix_search_for_szip.patch
  easybuild/easyconfigs/a/ADIOS/ADIOS-1.13.1_force_use_of_mpi.patch
  easybuild/easyconfigs/m/Mini-XML/Mini-XML-2.9-GCCcore-8.2.0.eb
Labels: new

#10025 {bio}[system/system] BLAST v2.10.0
  easybuild/easyconfigs/b/BLAST/BLAST-2.10.0-Linux_x86_64.eb
Labels: update

#10042 {bio}[foss/2019b] Seaborn v0.10.0 w/ Python 3.7.4
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.10.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10024 Kraken2 updated to version 2.0.8, together with dependencies
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.8-beta-gompi-2019b-Perl-5.30.0.eb
  easybuild/easyconfigs/l/libidn/libidn-1.35-GCCcore-8.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.20.1-GCCcore-8.3.0.eb
Labels: change, update

#10043 {lib}[foss/2019b] XGBoost v0.90 w/ Python 3.7.4
  easybuild/easyconfigs/x/XGBoost/XGBoost-0.90-foss-2019b-Python-3.7.4.eb
Labels: update

#10048 {math}[foss/2018b] Cgl v0.60.2
  easybuild/easyconfigs/c/Cgl/Cgl-0.60.2-foss-2018b.eb
Labels: new

#9964 {lib}[foss/2019b] rstanarm v2.19.3 w/ R 3.6.2
  easybuild/easyconfigs/r/rstanarm/rstanarm-2.19.3-foss-2019b-R-3.6.2.eb
Labels: new

#10046 {bio}[system/system] SeqAn v1.4.2
  easybuild/easyconfigs/s/SeqAn/SeqAn-1.4.2-library.eb
Labels: update

#9957 {bio}[foss-2019b] Trinity v2.9.1: add dependencies on Python 3 and SciPy-bundle
  easybuild/easyconfigs/t/Trinity/Trinity-2.9.1-foss-2019b-Python-3.7.4.eb
Labels: bug fix, change, update

#10041 {lib}[GCCcore/8.3.0,foss/2019b] pyaml v19.12.0, scikit-optimize v0.7.4 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/p/pretty-yaml/pretty-yaml-19.12.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/scikit-optimize/scikit-optimize-0.7.4-foss-2019b-Python-3.7.4.eb
Labels: new, update

#10044 {math}[foss/2018b] WildMagic v5.17
  easybuild/easyconfigs/w/WildMagic/WildMagic-5.17-foss-2018b.eb
Labels: new

#9998 {tools}[system] binutils v2.34
  easybuild/easyconfigs/b/Bison/Bison-3.5.2.eb
  easybuild/easyconfigs/b/binutils/binutils-2.34-readd-avx512-vmovd.patch
  easybuild/easyconfigs/b/binutils/binutils-2.34.eb
Labels: update

#10051 {lib}[foss/2019b] pylift v0.1.5 w/ Python 3.7.4
  easybuild/easyconfigs/p/pylift/pylift-0.1.5-foss-2019b-Python-3.7.4.eb
Labels: new

#9963 {cae}[intel/2019b] OpenFOAM-Extend v4.1-20191120 w/ Python 2.7.16
  easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.1-20191120-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.1_comp-mpi.patch
  easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.1_fix-icpc-error.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#10049 {lang}[GCCcore/8.2.0,GCCcore/8.3.0] Perl v5.28.1, v5.30.0: add modules URI::Escape and Set::IntervalTree
  easybuild/easyconfigs/p/Perl/Perl-5.28.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/STAR-Fusion/STAR-Fusion-1.6.0-GCC-8.2.0-2.31.1-Perl-5.28.1-Python-3.7.2.eb
Labels: change, enhancement

#10050 {compiler}[system/system] GCCcore v9.3.0
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0_gmp-c99.patch
Labels: update

#9730 {tools}[system/system] Nextflow v19.12.0
  easybuild/easyconfigs/n/Nextflow/Nextflow-19.12.0.eb
Labels: update

#10061 binutils 2.34 to use Bison 3.5.3 as build dep
  easybuild/easyconfigs/b/Bison/Bison-3.5.3.eb
  easybuild/easyconfigs/b/binutils/binutils-2.34.eb
Labels: update

#10055 {data}[intel/2019b] Arrow v0.16.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/Arrow/Arrow-0.16.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.16.0_fix-intel.patch
Labels: update

#10062 {tools}[GCCcore/9.3.0] binutils v2.34
  easybuild/easyconfigs/b/Bison/Bison-3.5.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.34-GCCcore-9.3.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.12-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-9.3.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-9.3.0.eb
Labels: update

#9680 {math}[foss/2019a] Octave 5.1.0 w/ updated dependencies
  easybuild/easyconfigs/b/Bison/Bison-3.3.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.0-foss-2019a.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.34-foss-2019a.eb
  easybuild/easyconfigs/o/Octave/Octave-5.1.0-foss-2019a.eb
  easybuild/easyconfigs/q/Qhull/Qhull-2019.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCC-8.2.0-2.31.1.eb
Labels: update

#10069 {tools}[dummy/dummy] EasyBuild v4.1.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.1.2.eb
Labels: update

#10066 {mpi}[GCC/9.3.0] OpenMPI v4.0.3
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GCC/GCC-9.3.0.eb
  easybuild/easyconfigs/h/hwloc/hwloc-2.1.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.16-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.13-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-GCC-9.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-9.3.0.eb
Labels: update

#10063 {chem}[foss/2019b] RDKit v2019.09.3 w/ Python 3.7.4
  easybuild/easyconfigs/r/RDKit/RDKit-2019.09.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/RDKit/RDKit-2019.09.3_fix_tests.patch
Labels: update

#10073 {devel}[GCCcore/9.3.0] pkg-config v0.29.2
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-9.3.0.eb
Labels: update

#9993 {chem}[GCCcore/8.3.0] xtb v6.2.3
  easybuild/easyconfigs/x/xtb/xtb-6.2.3-foss-2019b.eb
Labels: update

#10074 {tools}[GCCcore/9.3.0] gettext v0.20.1
  easybuild/easyconfigs/g/gettext/gettext-0.20.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-9.3.0.eb
Labels: update

#10075 {tools}[GCCcore/9.3.0] libffi v3.3, bzip2 v1.0.8, Tcl v8.6.10, ...
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/cURL/cURL-7.69.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-GCCcore-9.3.0.eb
Labels: update

#10077 {devel}[GCCcore/9.3.0] CMake v3.16.4, libreadline v8.0, SQLite v3.31.1
  easybuild/easyconfigs/c/CMake/CMake-3.16.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.31.1-GCCcore-9.3.0.eb
Labels: update

#10039 {bio}[iccifort/2019.5.281] BSseeker2 v2.1.8, Bowtie v1.2.3, Bowtie2 v2.3.5.1 w/ Python 2.7.16
  easybuild/easyconfigs/b/BSseeker2/BSseeker2-2.1.8-GCC-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/b/BSseeker2/BSseeker2-2.1.8-iccifort-2019.5.281-Python-2.7.16.eb
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.2.3-iccifort-2019.5.281.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.5.1-iccifort-2019.5.281.eb
Labels: new, update

#10081 {lib}[GCCcore/9.3.0] pybind11 v2.4.3 w/ Python 3.8.2
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.4.3-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#10080 {math}[GCCcore/9.3.0] MPFR v4.0.2
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.2_include_float.patch
Labels: 2020a

#10084 temporarily limit test configurations during 2020a sprint
  .github/workflows/unit_tests.yml
  .travis.yml
Labels: change

#10083 add -GCCcore-9.2.0 versionsuffix for intel/2020.00 components
  easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2020.00.eb
  easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/i/intel/intel-2020.00.eb
Labels: 2020a

#10082 intel-2020.00: use iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2020.00.eb
  easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/i/intel/intel-2020.00.eb
Labels: 2020a

#10072 Switch to GCC 9.3.0 for foss/2020a and intel/2020a release
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-gompi-2020a.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020a.eb
  easybuild/easyconfigs/f/foss/foss-2020a.eb
  easybuild/easyconfigs/g/gompi/gompi-2020a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2020a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2020a.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2020a.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.0.166-iimpi-2020a.eb
  easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166.eb
  easybuild/easyconfigs/i/intel/intel-2020a.eb
  easybuild/easyconfigs/n/networkx/networkx-2.4-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.3.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.02-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.10.0-foss-2020a-Python-3.8.2.eb
Labels: update

#10089 {lang,lib}[GCCcore/9.3.0] libjpeg-turbo v2.0.4, NASM v2.14.02
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.14.02-GCCcore-9.3.0.eb
Labels: 2020a, update

#10090 {lib}[GCCcore/9.3.0] libpng v1.6.37
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-GCCcore-9.3.0.eb
Labels: update

#10098 avoid relying on system toolchain for Eigen build dep required by pybind11
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.7-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.4.3-GCCcore-9.3.0-Python-3.8.2.eb
Labels: 2020a, change

#10093 {math}[GCCcore/9.3.0] METIS v5.1.0
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10092 {tools}[GCCcore/9.3.0] libarchive v3.4.2
  easybuild/easyconfigs/l/libarchive/libarchive-3.4.2-GCCcore-9.3.0.eb
Labels: 2020a, update

#10087 {devel}[GCCcore/9.3.0] libunwind v1.3.1, glog v0.4.0, gflags v2.2.2
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/glog/glog-0.4.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-9.3.0.eb
Labels: 2020a

#10096 {lib}[GCCcore/9.3.0] LibTIFF v4.1.0
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.1.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10099 {devel}[iimpi/2020a] Boost v1.72.0
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-iimpi-2020a.eb
Labels: 2020a, update

#10097 {lang,tools}[GCCcore/9.3.0] Perl v5.30.2, expat v2.2.9
  easybuild/easyconfigs/e/expat/expat-2.2.9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: 2020a, update

#10094 {bio}[GCCcore/9.3.0] SeqAn v2.4.0
  easybuild/easyconfigs/s/SeqAn/SeqAn-2.4.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10103 {math}[gompi/2020a,iimpi/2020a] ParMETIS v4.0.3
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2020a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2020a.eb
Labels: 2020a, update

#10101 {vis}[GCCcore/9.3.0] freetype v2.10.1, fontconfig v2.13.1
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.92-GCCcore-9.3.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.35-GCCcore-9.3.0.eb
Labels: 2020a, update

#10106 {devel,tools}[GCCcore/9.3.0] intltool v0.51.0
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10111 Update SciPy-bundle-2020.02 with numpy-1.18.2
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.02-foss-2020a-Python-3.8.2.eb
Labels: 2020a

#10112 {lang}[intel/2020a] SciPy-bundle v2020.02 w/ Python 3.8.2
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.02-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.18.2-mkl.patch
Labels: 2020a, update

#10027 disable unintended octave support in all libsndfile easyconfigs
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-intel-2017a.eb
Labels: bug fix

#10114 {tools}[GCCcore/9.3.0] Meson v0.53.2 w/ Python 3.8.2
  easybuild/easyconfigs/m/Meson/Meson-0.53.2-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10105 {tools}[GCCcore/9.3.0] gzip v1.10
  easybuild/easyconfigs/g/gzip/gzip-1.10-GCCcore-9.3.0.eb
Labels: 2020a, update

#10107 {devel}[GCCcore/9.3.0] Doxygen v1.8.17
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.17-GCCcore-9.3.0.eb
Labels: 2020a, update

#10121 {lib}[GCCcore/9.3.0] oneTBB v2020.1
  easybuild/easyconfigs/o/oneTBB/oneTBB-2020.1-GCCcore-9.3.0.eb
Labels: 2020a, new

#10109 {numlib}[GCC/9.3.0,iccifort/2020.0.166] GSL v2.6
  easybuild/easyconfigs/g/GSL/GSL-2.6-GCC-9.3.0.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-iccifort-2020.0.166.eb
Labels: 2020a, update

#10113 {vis}[GCCcore/9.3.0] X11 v20200222
  easybuild/easyconfigs/x/X11/X11-20200222-GCCcore-9.3.0.eb
Labels: 2020a, update

#10095 {lib}[intel/2019b] PyRe v5.0.3-20190221, IPython v7.9.0 w/ Python 3.7.4
  easybuild/easyconfigs/i/IPython/IPython-7.9.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyRe/PyRe-5.0.3-20190221-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyRe/PyRe-5.0.3-20190221-intel-2019b-Python-3.7.4.eb
Labels: new, update

#10123 {tools}[GCCcore/9.3.0] Szip v2.1.1
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-9.3.0.eb
Labels: 2020a, update

#10124 {devel}[GCCcore/9.3.0] PCRE v8.44
  easybuild/easyconfigs/p/PCRE/PCRE-8.44-GCCcore-9.3.0.eb
Labels: 2020a, update

#10122 {tools}[GCCcore/9.3.0] hypothesis v5.6.0 w/ Python 3.8.2
  easybuild/easyconfigs/h/hypothesis/hypothesis-5.6.0-GCCcore-9.3.0-Python-3.8.2.eb
Labels: 2020a, update

#10120 {tools}[GCCcore/9.3.0] archspec v0.1.0 w/ Python 3.8.2
  easybuild/easyconfigs/a/archspec/archspec-0.1.0-GCCcore-9.3.0-Python-3.8.2.eb
Labels: 2020a, update

#10118 Update version number for SciPy-bundle to 2020.03 due to updated numpy.
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-intel-2020a-Python-3.8.2.eb
Labels: 2020a, update

#10108 {lib}[gompi/2020a,iimpi/2020a] lwgrp v1.0.2
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.2-gompi-2020a.eb
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.2-iimpi-2020a.eb
Labels: 2020a, new

#10128 Python-3.8.2: Update OpenSSL to 1.1.1e in comment.
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
Labels: 2020a

#10116 {lib}[gompi/2020a,iimpi/2020a] libcircle v0.3
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-gompi-2020a.eb
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-iimpi-2020a.eb
Labels: 2020a, update

#10119 networkx: Update SciPy version to 2020.03.
  easybuild/easyconfigs/n/networkx/networkx-2.4-foss-2020a-Python-3.8.2.eb
Labels: 2020a, update

#10127 {vis}[GCCcore/9.3.0] Tk v8.6.10
  easybuild/easyconfigs/t/Tk/Tk-8.6.10-GCCcore-9.3.0.eb
Labels: 2020a, update

#10126 {tools}[GCCcore/8.3.0] gperftools v2.7.90
  easybuild/easyconfigs/g/gperftools/gperftools-2.7.90-GCCcore-8.3.0.eb
Labels: update

#10117 {system}[GCCcore/9.3.0] OpenSSL v1.1.1e
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.1e-GCCcore-9.3.0.eb
Labels: 2020a, update

#10129 {vis}[GCCcore/9.3.0] FFmpeg v4.2.2, FriBidi v1.0.9, LAME v3.100, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20191217-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10131 {data}[gompi/2020a,iimpi/2020a] HDF5 v1.12.0
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.0-gompi-2020a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.0-iimpi-2020a.eb
Labels: 2020a, update

#10110 {lib}[gompi/2020a,iimpi/2020a] dtcmp v1.1.0
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.0-gompi-2020a.eb
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.0-iimpi-2020a.eb
Labels: 2020a, update

#10136 {math}[gompi/2020a,iimpi/2020a] SCOTCH v6.0.9
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-gompi-2020a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-iimpi-2020a.eb
Labels: 2020a, update

#10137 {vis}[GCCcore/9.3.0] Pillow v7.0.0 w/ Python 3.8.2
  easybuild/easyconfigs/p/Pillow/Pillow-7.0.0-GCCcore-9.3.0-Python-3.8.2.eb
Labels: 2020a, update

#10135 {data}[gompi/2020a,iimpi/2020a] netCDF v4.7.3, netCDF-C++4 v4.3.1, netCDF-Fortran v4.5.2
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-gompi-2020a.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-iimpi-2020a.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompi-2020a.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-iimpi-2020a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.3-gompi-2020a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.3-iimpi-2020a.eb
Labels: 2020a, update

#10088 {lib}[GCCcore/9.3.0] CLISP v2.49, DB v18.1.32, libffcall v2.2, ...
  easybuild/easyconfigs/c/CLISP/CLISP-2.49-GCCcore-9.3.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.32-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libffcall/libffcall-2.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libsigsegv/libsigsegv-2.12-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PCRE/PCRE-8.43-GCCcore-9.3.0.eb
Labels: 2020a, update

#9659 [double-conversion] Use CMake for building
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.0.3-foss-2018a.eb
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.4-GCCcore-8.3.0.eb
Labels: bug fix, change

#10140 {numlib}[foss/2020a,intel/2020a] SuiteSparse v5.7.1
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.7.1-foss-2020a-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.7.1-intel-2020a-METIS-5.1.0.eb
Labels: 2020a, update

#10144 {tools}[gompi/2020a,iimpi/2020a] mpifileutils v0.10
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.10-gompi-2020a.eb
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.10-iimpi-2020a.eb
Labels: 2020a, update

#10142 ELPA for 2020a
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-foss-2020a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-intel-2020a.eb
Labels: 2020a, update

#10143 {devel}[GCCcore/9.3.0] GObject-Introspection v1.64.0 w/ Python 3.8.2
  easybuild/easyconfigs/c/cairo/cairo-1.16.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.64.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.64.0-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/p/pixman/pixman-0.38.4-GCCcore-9.3.0.eb
Labels: 2020a, update

#10145 {lang}[GCCcore/9.3.0] Python v2.7.17
  easybuild/easyconfigs/p/Python/Python-2.7.17-GCCcore-9.3.0.eb
Labels: 2020a, update
