Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-05, with the labels that each got.

#10520 {lang}[foss/2020a] R v4.0.0
  easybuild/easyconfigs/g/GLPK/GLPK-4.65-GCCcore-9.3.0.eb
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: 2020a, update

#10546 add MCE::Mutex extension to Perl 5.28.1 + 5.30.x
  easybuild/easyconfigs/p/Perl/Perl-5.28.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: enhancement

#10553 {vis}[foss/2020a,intel/2020a] VTK v8.2.0 w/ Python 3.8.2
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0_python_3.8_compatibility.patch
Labels: 2020a, update

#10554 {data}[foss/2020a,intel/2020a] GDAL v3.0.4, GEOS v3.8.1 w/ Python 3.8.2
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.4-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.4-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.8.1-iccifort-2020.1.217-Python-3.8.2.eb
Labels: 2020a, update

#10555 {chem}[foss/2020a,intel/2020a] PLUMED v2.6.0 w/ Python 3.8.2
  easybuild/easyconfigs/g/GSL/GSL-2.6-iccifort-2020.1.217.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.0-intel-2020a-Python-3.8.2.eb
Labels: 2020a, update

#10369 {vis}[foss/2020a, intel/2020a] ParaView v5.8.0
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-foss-2020a-Python-3.8.2-mpi.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-intel-2020a-Python-3.8.2-mpi.eb
Labels: 2020a, update

#10560 {chem,data,math}[foss/2020a,intel/2020a] molmod v1.4.5, yaff v1.6.0, h5py v2.10.0 w/ Python 3.8.2
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.5-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.5-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.5_deprecated_time_method.patch
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-intel-2020a-Python-3.8.2.eb
Labels: 2020a, update

#10569 {tools}[gompi/2019b] YAXT v0.6.2
  easybuild/easyconfigs/y/YAXT/YAXT-0.6.2-gompi-2019b.eb
Labels: update

#10570 {tools}[foss/2019b] ecCodes v2.17.0 w/ Python 3.7.4
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.17.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10566 {tools}[foss/2018b] YAXT v0.6.2
  easybuild/easyconfigs/y/YAXT/YAXT-0.6.2-foss-2018b.eb
Labels: update

#10567 {tools}[foss/2018b] ecCodes v2.17.0 w/ Python 3.6.6
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.17.0-foss-2018b-Python-3.6.6.eb
Labels: update

#10565 remove FFTW dependencies from LAMMPS easyconfigs, no longer needed (MKL can be used too now)
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos.eb
Labels: bug fix, change

#10588 {bio}[GCC/8.3.0] HMMER2 v2.3.2
  easybuild/easyconfigs/h/HMMER2/HMMER2-2.3.2-GCC-8.3.0.eb
Labels: new

#10587 {bio}[GCC/8.3.0] GlimmerHMM v3.0.4c
  easybuild/easyconfigs/g/GlimmerHMM/GlimmerHMM-3.0.4c-GCC-8.3.0.eb
Labels: update

#10571 {bio}[foss/2019b] FastViromeExplorer v20180422
  easybuild/easyconfigs/f/FastViromeExplorer/FastViromeExplorer-20180422-foss-2019b.eb
Labels: new

#10583 {tools}[system/system] Nextflow v20.04.1
  easybuild/easyconfigs/n/Nextflow/Nextflow-20.04.1.eb
Labels: update

#10584 {math}[intel/2019b] LMfit v1.0.0 w/ Python 3.7.4
  easybuild/easyconfigs/l/LMfit/LMfit-1.0.0-intel-2019b-Python-3.7.4.eb
Labels: update

#10548 {bio}[GCC/8.3.0,iccifort/2019.5.281] cdbfasta v0.99
  easybuild/easyconfigs/c/cdbfasta/cdbfasta-0.99-GCC-8.3.0.eb
  easybuild/easyconfigs/c/cdbfasta/cdbfasta-0.99-iccifort-2019.5.281.eb
Labels: new

#10547 {bio}[iccifort/2019.1.144-GCC-8.2.0-2.31.1] cdbfasta v0.99
  easybuild/easyconfigs/c/cdbfasta/cdbfasta-0.99-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: new

#10577 {lang}[GCCcore/8.2.0] Rust v1.42.0
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-8.2.0.eb
Labels: update

#10562 {data}[GCCcore/8.3.0] openpyxl v3.0.3 w/ Python 3.7.4
  easybuild/easyconfigs/o/openpyxl/openpyxl-3.0.3-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10572 {bio}[foss/2019b] Taiyaki v5.0.1-20200316 w/ Python 3.7.4
  easybuild/easyconfigs/t/Taiyaki/Taiyaki-5.0.1-20200316-foss-2019b-Python-3.7.4.eb
Labels: new

#10561 {data,math}[fosscuda/2019b] PyTables v3.6.1, numexpr v2.7.1 w/ Python 3.7.4
  easybuild/easyconfigs/n/numexpr/numexpr-2.7.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10515 {bio}[GCC/8.3.0] FLASH v1.2.11
  easybuild/easyconfigs/f/FLASH/FLASH-1.2.11-GCC-8.3.0.eb
Labels: update

#10574 {chem}[iccifort/2019.5.281] NCIPLOT v4.0-20200106
  easybuild/easyconfigs/n/NCIPLOT/NCIPLOT-4.0-20200106-iccifort-2019.5.281.eb
Labels: update

#10544 {bio}[foss/2019b] CITE-seq-Count v1.4.3, UMI-tools v1.0.1, python-Levenshtein v0.12.0 w/ Python 3.7.4
  easybuild/easyconfigs/c/CITE-seq-Count/CITE-seq-Count-1.4.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/python-Levenshtein/python-Levenshtein-0.12.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/u/UMI-tools/UMI-tools-1.0.1-foss-2019b-Python-3.7.4.eb
Labels: update

#10585 add additional extensions to R 3.6.2 + R-bundle-Bioconductor 3.10 easyconfigs
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.10-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: enhancement

#10586 add additional extensions to R 3.6.3 & R 4.0.0 extensions
  easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#10573 {bio}[fosscuda/2019b] Taiyaki v5.0.1-20200316, Biopython v1.75 w/ Python 3.7.4
  easybuild/easyconfigs/b/Biopython/Biopython-1.75-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/Taiyaki/Taiyaki-5.0.1-20200316-fosscuda-2019b-Python-3.7.4.eb
Labels: new, update

#10501 {lib}[intel/2019b] PyWavelets v1.1.1 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyWavelets/PyWavelets-1.1.1-intel-2019b-Python-3.7.4.eb
Labels: new

#10491 Create libffcall-2.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libffcall/libffcall-2.2-GCCcore-8.3.0.eb
Labels: update

#10507 {bio}[fosscuda/2019b] Bonito v0.1.4 w/ Python 3.7.4
  easybuild/easyconfigs/b/Bonito/Bonito-0.1.4-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10591 Archive old Singularity configs
  easybuild/easyconfigs/__archive__/s/Singularity/Singularity-1.0-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/__archive__/s/Singularity/Singularity-2.2.1-GCC-6.3.0-2.27.eb
  easybuild/easyconfigs/__archive__/s/Singularity/Singularity-2.3.1-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/__archive__/s/Singularity/Singularity-2.4.2-GCC-5.4.0-2.26.eb
Labels: change

#10596 add diffcyt extension to R-bundle-Bioconductor 3.10
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.10-foss-2019b.eb
Labels: enhancement

#10592 Fix building [foss/2019b] ITK v5.0.1 (locale & libjpeg)
  easybuild/easyconfigs/i/ITK/ITK-5.0.1-foss-2019b-Python-3.7.4.eb
Labels: bug fix

#10590 {tools}[foss/2019b] MEM v20191023
  easybuild/easyconfigs/m/MEM/MEM-20191023-foss-2019b.eb
Labels: new

#10428 {math}[GCC/8.2.0-2.31.1] nauty v2.6r12
  easybuild/easyconfigs/n/nauty/nauty-2.6r12-GCC-8.2.0-2.31.1.eb
Labels: new

#10597 {chem,math}[GCC/8.3.0,foss/2019b] MESS v0.1.6, SLATEC v4.1
  easybuild/easyconfigs/m/MESS/MESS-0.1.6-foss-2019b.eb
  easybuild/easyconfigs/s/SLATEC/SLATEC-4.1-GCC-8.3.0.eb
Labels: new, update

#10599 {bio}[foss/2020a] R-bundle-Bioconductor v3.11
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-3.1.7-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/ncdf4/ncdf4-1.17-foss-2020a-R-4.0.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: update

#10389 {tools}[foss/2019b] Ray v0.8.4 w/ Python 3.7.4
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.10.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/Ray/Ray-0.8.4-foss-2019b-Python-3.7.4.eb
Labels: new, update

#10607 Add alternate checksum for EMBOSS
  easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-GCC-8.3.0-Java-11.eb
Labels: update

#10608 fix OS dependency for rstudio for Debian-based systems
  easybuild/easyconfigs/r/rstudio/rstudio-1.2.5033-fosscuda-2019b-Java-11.eb
Labels: bug fix

#10606 Fix missing const qualifiers for ncurses
  easybuild/easyconfigs/n/ncurses/ncurses-5.9.eb
  easybuild/easyconfigs/n/ncurses/ncurses-5.9_fix-missing-const.patch
Labels: bug fix

#10601 {bio}[GCCcore/9.3.0] minimap2 v2.17
  easybuild/easyconfigs/m/minimap2/minimap2-2.17-GCCcore-9.3.0.eb
Labels: update

#10612 FastQTL/2.184 - fix Rmath paths
  easybuild/easyconfigs/f/FastQTL/FastQTL-2.184-foss-2018b.eb
Labels: bug fix

#10610 {tools}[GCCcore/8.3.0] csvkit v1.0.5 w/ Python 3.7.4
  easybuild/easyconfigs/c/csvkit/csvkit-1.0.5-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10623 add additional extensions to Perl-5.30.2 easyconfig
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: enhancement

#10626 add patch for h5py 2.10.0 with 2020a toolchains to avoid MPI_Init at import
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0_fix-import-mpi.patch
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-intel-2020a-Python-3.8.2.eb
Labels: 2020a

#10593 {bio}[foss/2019b] CaSpER v2.0
  easybuild/easyconfigs/c/CaSpER/CaSpER-2.0-foss-2019b.eb
Labels: new

#10579 {lib,vis}[foss/2019a] libcroco v0.6.13, librsvg v2.48.4
  easybuild/easyconfigs/l/libcroco/libcroco-0.6.13-foss-2019a.eb
  easybuild/easyconfigs/l/librsvg/librsvg-2.48.4-foss-2019a.eb
Labels: update

#10603 {bio}[foss/2020a] DoubletFinder v2.0.3
  easybuild/easyconfigs/d/DoubletFinder/DoubletFinder-2.0.3-foss-2020a-R-4.0.0.eb
Labels: new

#10304 {data}[foss/2019b] rioxarray v0.0.24 w/ Python 3.7.4
  easybuild/easyconfigs/r/rioxarray/rioxarray-0.0.24-foss-2019b-Python-3.7.4.eb
Labels: update

#10478 {bio}[iccifort/2019.5.281] BRAKER v2.1.5, spaln v2.4.03, Exonerate v2.4.0, ...
  easybuild/easyconfigs/b/BRAKER/BRAKER-2.1.5-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-iccifort-2019.5.281.eb
  easybuild/easyconfigs/g/GeneMark-ET/GeneMark-ET-4.57-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GenomeThreader/GenomeThreader-1.7.3-Linux_x86_64-64bit.eb
  easybuild/easyconfigs/s/spaln/spaln-2.4.03-iccifort-2019.5.281.eb
Labels: update

#10628 {lang}[system/system] Julia v1.4.1
  easybuild/easyconfigs/j/Julia/Julia-1.4.1-linux-x86_64.eb
Labels: update

#10502 {bio}[GCC/8.3.0] RNA-Bloom v1.2.3, minimap2 v2.17, ntCard v1.2.1
  easybuild/easyconfigs/m/minimap2/minimap2-2.17-GCC-8.3.0.eb
  easybuild/easyconfigs/n/ntCard/ntCard-1.2.1-GCC-8.3.0.eb
  easybuild/easyconfigs/r/RNA-Bloom/RNA-Bloom-1.2.3-GCC-8.3.0.eb
Labels: new, update

#10029 {bio}[intel/2019b] NLMpy v0.1.5 w/ Python 3.7.4
  easybuild/easyconfigs/n/NLMpy/NLMpy-0.1.5-intel-2019b-Python-3.7.4.eb
Labels: new

#10438 {bio}[GCCcore/8.3.0] GffCompare v0.11.6
  easybuild/easyconfigs/g/GffCompare/GffCompare-0.11.6-GCCcore-8.3.0.eb
Labels: update

#10519 {bio}[intel/2019b] MultiQC v1.8 w/ Python 3.7.4
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.8-intel-2019b-Python-3.7.4.eb
Labels: update

#10616 {lib}[GCCcore/9.3.0] libfabric v1.10.1
  easybuild/easyconfigs/l/libfabric/libfabric-1.10.1-GCCcore-9.3.0.eb
Labels: update

#10614 Update ALL, pRolocdata and geneLenDataBase extensions in Bioconductor/3.11
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: update

#10582 Meme updated to version 5.1.1
  easybuild/easyconfigs/m/MEME/MEME-5.1.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/MEME/MEME-5.1.1-intel-2019b-Python-3.7.4.eb
Labels: update

#10615 {compiler}[system/system] GCC v10.1.0
  easybuild/easyconfigs/b/Bison/Bison-3.6.1-GCCcore-10.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.34-GCCcore-10.1.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-10.1.0.eb
  easybuild/easyconfigs/g/GCC/GCC-10.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.1.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.15-GCCcore-10.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-10.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-10.1.0.eb
Labels: update

#10630 don't use harmful patch for h5py 2.10.0 with foss/2020a + pull out h5py 2.10.0 easyconfig using intel/2020a
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0_fix-import-mpi.patch
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-intel-2020a-Python-3.8.2.eb
Labels: change

#10621 [foss/2020a] add extensions to R 4.0.0 and Bioconductor 3.11 easyconfigs
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#10627 fix Mako easyconfigs using a 2016 & 2017 toolchain
  easybuild/easyconfigs/m/Mako/Mako-1.0.4-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.4-intel-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.6-foss-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.6-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intelcuda-2017b-Python-2.7.14.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#10516 {tools}[foss/2019b,fosscuda/2019b] torchaudio v0.5.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/torchaudio/torchaudio-0.5.0-foss-2019b-Python-3.7.4-PyTorch-1.4.0.eb
  easybuild/easyconfigs/t/torchaudio/torchaudio-0.5.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.4.0.eb
Labels: new

#10188 {debugger}[gompi/2020a,iimpi/2020a] Valgrind v3.15
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.15.0-gompi-2020a.eb
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.15.0-iimpi-2020a.eb
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.15.0-no-MPI-1.patch
Labels: 2020a, update

#10632 {tools}[GCCcore/9.3.0] parallel v20200422
  easybuild/easyconfigs/p/parallel/parallel-20200422-GCCcore-9.3.0.eb
Labels: update

#10635 stop using old hpcugent URL for cloning framework/easyblocks repos in CI
  .github/workflows/unit_tests.yml
  .travis.yml
Labels: bug fix

#9742 {bio}[GCCcore/8.2.0] netMHCIIpan v3.2
  easybuild/easyconfigs/n/netMHCIIpan/netMHCIIpan-3.2-GCCcore-8.2.0.eb
Labels: update

#10429 {math}[gompi/2019a] Normaliz v3.7.4 and deps E-ANTIC, Arb, FLINT, CoCoALib, cddlib, nauty
  easybuild/easyconfigs/a/Arb/Arb-2.16.0-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/c/CoCoALib/CoCoALib-0.99601-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/c/cddlib/cddlib-0.94i-GCCcore-8.2.0.eb
  easybuild/easyconfigs/e/E-ANTIC/E-ANTIC-0.1.2-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/f/FLINT/FLINT-2.5.2-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/n/Normaliz/Normaliz-3.7.4-gompi-2019a.eb
  easybuild/easyconfigs/n/nauty/nauty-2.7rc2-GCC-8.2.0-2.31.1.eb
Labels: new, update

#10598 {bio,lib}[GCCcore/8.3.0,foss/2019b] nifti2dicom v0.4.11, TCLAP v1.2.2
  easybuild/easyconfigs/n/nifti2dicom/nifti2dicom-0.4.11-foss-2019b.eb
  easybuild/easyconfigs/n/nifti2dicom/nifti2dicom-0.4.11-no_GUI.patch
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.2-GCCcore-8.3.0.eb
Labels: new

#10521 {bio}[intel/2019b] MultiQC v1.8 w/ Python 2.7.16
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.8-intel-2019b-Python-2.7.16.eb
Labels: update

#10163 {bio}[intel/2019b] HDDM v0.7.5 w/ Python 3.7.4
  easybuild/easyconfigs/h/HDDM/HDDM-0.7.5-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/h/HDDM/pymc-2.3.7_rename-await.patch
Labels: update

#10536 {data}[foss/2018b] HDF-EOS5 v1.16
  easybuild/easyconfigs/h/HDF-EOS5/HDF-EOS5-1.16-foss-2018b.eb
Labels: new

#10421 {perf}[gompi/2020a, GCCcore/9.3.0] Scalasca v2.5, Score-P v.6.0, CubeGUI v.4.4, CubeLib v.4.4, CubeW v4.4.3, PAPI v6.0, OPARI2 v2.0.5, OTF2 v2.2, PDT v3.25.1, SIONlib v1.7.6
  easybuild/easyconfigs/c/CubeGUI/CubeGUI-4.4.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.4.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.4.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PAPI/PAPI-6.0.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.6-GCCcore-9.3.0-tools.eb
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.5-gompi-2020a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompi-2020a.eb
Labels: 2020a

#10537 {*}[*/2020a] VTK v8.2.0, LAMMPS 3Mar2020, PLUMED v2.6.0, GDAL v3.0.4 + more w/ Python 3.8.2
  easybuild/easyconfigs/k/kim-api/kim-api-2.1.3-foss-2020a.eb
  easybuild/easyconfigs/k/kim-api/kim-api-2.1.3-intel-2020a.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2020a-Python-3.8.2-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/lammps-stable_3Mar2020_hack_openmp_gcc9.patch
  easybuild/easyconfigs/n/networkx/networkx-2.4-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/ScaFaCoS/ScaFaCoS-1.0.1-foss-2020a.eb
  easybuild/easyconfigs/s/ScaFaCoS/ScaFaCoS-1.0.1-intel-2020a.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.10.0-foss-2020a-Python-3.8.2.eb
Labels: 2020a, new, update

#10180 {tools}[GCCcore/9.3.0] patchelf-0.10
  easybuild/easyconfigs/p/patchelf/patchelf-0.10-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.10-force-rpath.patch
Labels: 2020a, update

#10431 {math}[GCC/8.2.0-2.31.1] Singular v4.1.2, NTL v11.3.4, 4ti2 v1.6.9
  easybuild/easyconfigs/0/4ti2/4ti2-1.6.9-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/n/NTL/NTL-11.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/s/Singular/Singular-4.1.2-GCC-8.2.0-2.31.1.eb
Labels: new, update

#10432 {math}[foss/2019a,gompi/2019a] lrslib v7.0a, gap v4.11.0
  easybuild/easyconfigs/g/gap/gap-4.11.0-foss-2019a.eb
  easybuild/easyconfigs/l/lrslib/lrslib-7.0a-gompi-2019a.eb
  easybuild/easyconfigs/l/lrslib/lrslib-7.0a-use-EB-values.patch
Labels: update

#10600 {lib}[fosscuda/2019b] TensorFlow v2.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/b/Bazel/Bazel-2.0.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10224 {bio}[GCCcore/9.3.0] MUMmer v3.23, MUMmer v4.0.0beta2
  easybuild/easyconfigs/m/MUMmer/MUMmer-3.23-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0beta2-GCCcore-9.3.0.eb
Labels: 2020a, update

#10640 replace /path/to with actual installation prefix in FuSeq scripts
  easybuild/easyconfigs/f/FuSeq/FuSeq-1.1.2-gompi-2019b.eb
Labels: bug fix

#10633 Fix binutils for Fedora 32 / GCC 10
  easybuild/easyconfigs/b/binutils/binutils-2.28.eb
  easybuild/easyconfigs/b/binutils/binutils-2.30.eb
  easybuild/easyconfigs/b/binutils/binutils-2.31.1.eb
  easybuild/easyconfigs/b/binutils/binutils-2.31.1_fix_gcc10.patch
  easybuild/easyconfigs/b/binutils/binutils-2.32.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32_gold-include-cpp-headers.patch
Labels: bug fix

#10642 {bio}[GCC/8.3.0] HyPo v1.0.3, KMC v3.1.2rc1, SDSL v2.1.1-20191211 w/ Python 3.7.4
  easybuild/easyconfigs/h/HyPo/HyPo-1.0.3-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/k/KMC/KMC-3.1.2rc1-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/s/SDSL/SDSL-2.1.1-20191211-GCC-8.3.0.eb
Labels: new, update

#10589 {bio}[foss/2019b] antiSMASH v5.1.2 w/ Python 3.7.4
  easybuild/easyconfigs/a/antiSMASH/antiSMASH-5.1.2-foss-2019b-Python-3.7.4.eb
Labels: new

#10641 {chem}[intel/2019b] rickflow v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/r/rickflow/rickflow-0.7.0-intel-2019b-Python-3.7.4.eb
Labels: new

#10617 Create Stacks-2.53-foss-2019b.eb
  easybuild/easyconfigs/s/Stacks/Stacks-2.53-foss-2019b.eb
Labels: update

#10551 {bio}[GCC/8.3.0] bcl2fastq2 v2.20.0
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-8.3.0.eb
Labels: update

#10550 {bio}[foss/2019b] popscle v0.1-beta
  easybuild/easyconfigs/p/popscle/popscle-0.1-beta-foss-2019b.eb
  easybuild/easyconfigs/p/popscle/popscle-0.1-beta_fix-compilation-GCC-8.3.patch
Labels: new

#10549 {bio}[iccifort/2019.1.144-GCC-8.2.0-2.31.1] ProtHint v2.4.0 w/ Python 3.7.2
  easybuild/easyconfigs/p/ProtHint/ProtHint-2.4.0-iccifort-2019.1.144-GCC-8.2.0-2.31.1-Python-3.7.2.eb
  easybuild/easyconfigs/p/ProtHint/ProtHint-2.4.0-iccifort-2019.5.281-Python-3.7.4.eb
Labels: new

#10026 {bio}[foss/2020a] GROMACS v2020.1 w/ Python 3.8.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.1_dont_override_pythonpath_in_tests.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020_fix_gmxapi_gmx_allowed_cmd_name.patch
  easybuild/easyconfigs/g/GROMACS/gmxapi-0.1.0.1_drop_cmake_requirement.patch
Labels: 2020a, update

#10644 {tools}[system/system] worker v1.6.12
  easybuild/easyconfigs/w/worker/worker-1.6.12-foss-2019a.eb
Labels: update

#10638 Fix missing use of SYSTEM variable
  easybuild/easyconfigs/g/gettext/gettext-0.20.1.eb
  easybuild/easyconfigs/r/rclone/rclone-1.42-amd64.eb
Labels: code cleanup

#10620 add symlink for Arlequin commands + fix sanity check commands
  easybuild/easyconfigs/a/Arlequin/Arlequin-3.5.2.2-foss-2019b.eb
Labels: bug fix

#10625 {bio}[GCC/8.3.0,iccifort/2019.5.281] angsd v0.933
  easybuild/easyconfigs/a/angsd/angsd-0.933-GCC-8.3.0.eb
  easybuild/easyconfigs/a/angsd/angsd-0.933-iccifort-2019.5.281.eb
Labels: update

#10605 {tools}[foss/2020a] MEM v20191023
  easybuild/easyconfigs/m/MEM/MEM-20191023-foss-2020a-R-4.0.0.eb
Labels: update

#10604 {data}[foss/2020a] harmony v1.0.0-20200224
  easybuild/easyconfigs/h/harmony/harmony-1.0.0-20200224-foss-2020a-R-4.0.0.eb
Labels: new

#10581 {bio}[foss/2018b] Kraken2 v2.0.9-beta
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.9-beta-foss-2018b-Perl-5.28.0.eb
Labels: update

#10564 add missing PyVCF dependency for BAMSurgeon
  easybuild/easyconfigs/b/BAMSurgeon/BAMSurgeon-1.2-GCC-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/p/PyVCF/PyVCF-0.6.8-GCC-8.3.0.eb
Labels: bug fix, new

#10619 {lang}[foss/2019b] rstudio v1.2.5042
  easybuild/easyconfigs/r/rstudio/rstudio-1.2.5042-foss-2019b-Java-11.eb
Labels: update

#10545 {bio}[foss/2019b,intel/2019b] MDAnalysis v0.20.1 w/ Python 3.7.4
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-0.20.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-0.20.1-intel-2019b-Python-3.7.4.eb
Labels: new

#10534 {data}[GCCcore/7.3.0] HDF-EOS v2.20
  easybuild/easyconfigs/h/HDF-EOS/HDF-EOS-2.20-GCCcore-7.3.0.eb
Labels: new

#10559 use https in homepage for Mathematica 12.0.0 + clean up sanity check commands (now done by easyblock)
  easybuild/easyconfigs/m/Mathematica/Mathematica-12.0.0.eb
Labels: bug fix

#10645 {bio}[foss/2020a] GROMACS v2020.1 w/ Python 3.8.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.1_dont_override_pythonpath_in_tests.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020_fix_gmxapi_gmx_allowed_cmd_name.patch
  easybuild/easyconfigs/g/GROMACS/gmxapi-0.1.0.1_drop_cmake_requirement.patch
Labels: update

#10540 PyTorch 1.4.0 : Added ibverbs dependencies via constants.
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix

#10647 {chem}[system/system] ADF v2019.303
  easybuild/easyconfigs/a/ADF/ADF-2019.303-intelmpi.eb
Labels: update

#8870 fix incorrect checksums for Amber patches
  easybuild/easyconfigs/a/Amber/Amber-16-foss-2018b-AmberTools-17-patchlevel-10-15.eb
  easybuild/easyconfigs/a/Amber/Amber-16-fosscuda-2018b-AmberTools-17-patchlevel-10-15.eb
  easybuild/easyconfigs/a/Amber/Amber-16-intel-2017b-AmberTools-17-patchlevel-8-12.eb
  easybuild/easyconfigs/a/Amber/Amber-16-intel-2018b-AmberTools-17-patchlevel-10-15.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#10648 {lib}[foss/2019b] TensorFlow v2.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10649 bump version and update release notes for EasyBuild v4.2.1
  RELEASE_NOTES
  setup.py
Labels: documentation, update

#10653 {tools}[dummy/dummy] EasyBuild v4.2.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.2.1.eb
Labels: update

#10646 {bio}[foss/2019b] Tombo v1.5.1 w/ Python 3.7.4
  easybuild/easyconfigs/t/Tombo/Tombo-1.5.1-foss-2019b-Python-3.7.4.eb
Labels: new

#10512 {vis}[GCCcore/8.3.0] Xvfb v1.20.8
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/Xvfb/xvfb-run
Labels: new

#10655 sync develop with master + bump version to 4.2.2dev
  RELEASE_NOTES
  setup.py
Labels: update

#10651 {cae}[foss/2019b] OpenFOAM-Extend 4.1-20200408
  easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.1-20200408-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gompi-2019b.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0_gompiOpenFOAM-Extend.patch
Labels: update

#10662 fix Togl configure patch so that it completely ignores TCL_SRC_DIR and TK_SRC_DIR
  easybuild/easyconfigs/t/Togl/Togl-2.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/Togl/Togl-2.0_configure.patch
Labels: bug fix

#10668 {tools}[GCCcore/9.3.0] tcsh v6.22.02
  easybuild/easyconfigs/t/tcsh/tcsh-6.22.02-GCCcore-9.3.0.eb
Labels: update

#10667 {vis}[GCCcore/9.3.0] motif v2.3.8
  easybuild/easyconfigs/m/motif/motif-2.3.8-GCCcore-9.3.0.eb
Labels: update

#10659 {tools}[GCCcore/10.1.0] XZ v5.2.5
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.1.0.eb
Labels: update

#10664 Change Xerces-C++ to official CMakeMake build. Fixes missing links to curl
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.2-GCCcore-8.2.0.eb
Labels: bug fix

#10672 {numlib,toolchain}[GCC/9.3.0,system/system] golf v2020a, FFTW v3.3.8
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-GCC-9.3.0-serial.eb
  easybuild/easyconfigs/g/golf/golf-2020a.eb
Labels: update

#10058 {tools}[foss/2018b] SYMPHONY v5.6.16
  easybuild/easyconfigs/s/SYMPHONY/SYMPHONY-5.6.16-foss-2018b.eb
Labels: new

#10669 {geo}[foss/2020a] rgdal v1.4-8 w/ R 4.0.0
  easybuild/easyconfigs/r/rgdal/rgdal-1.4-8-foss-2020a-R-4.0.0.eb
Labels: update

#10685 {geo}[foss/2019b] Cartopy v0.18.0 w/ Python 3.7.4
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.18.0-foss-2019b-Python-3.7.4.eb
Labels: new

#10675 {astro,data}[GCCcore/8.3.0,foss/2019b] astropy v4.0.1, BeautifulSoup v4.9.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/a/astropy/astropy-4.0.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.9.1-GCCcore-8.3.0.eb
Labels: update

#10673 {data}[GCCcore/8.3.0] python-hl7 v0.3.4 w/ Python 3.7.4
  easybuild/easyconfigs/p/python-hl7/python-hl7-0.3.4-GCCcore-8.3.0-Python-3.7.4.eb
Labels: new

#10676 {astro,lib}[GCCcore/8.3.0,foss/2019b] OpenJPEG v2.3.1, SunPy v1.1.3 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.3.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/SunPy/SunPy-1.1.3-foss-2019b-Python-3.7.4.eb
Labels: new, update

#10688 {tools}[GCCcore/9.3.0] libMemcached v1.0.18
  easybuild/easyconfigs/l/libMemcached/libMemcached-1.0.18-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libMemcached/libMemcached-1.0.18-bugfix-comparison.patch
Labels: update

#10689 {devel}[GCCcore/9.3.0] Boost v1.72.0
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb
Labels: update

#10695 Fix missing m4
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompi-2020a.eb
Labels: bug fix

#10691 {bio}[GCCcore/8.3.0] MARS v20191101, sdsl-lite v2.1.1, SeqAn v2.4.0
  easybuild/easyconfigs/m/MARS/MARS-20191101-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/SeqAn/SeqAn-2.4.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/sdsl-lite/sdsl-lite-2.1.1-GCCcore-8.3.0.eb
Labels: new, update

#10697 Fix missing M4
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-iimpi-2020a.eb
Labels: bug fix

#10699 {geo}[foss/2020a] ESMF v8.0.1
  easybuild/easyconfigs/e/ESMF/ESMF-8.0.1-foss-2020a.eb
Labels: update

#10703 {lib}[GCCcore/8.3.0] Flask v1.1.2 w/ Python 3.7.4
  easybuild/easyconfigs/f/Flask/Flask-1.1.2-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10698 {bio}[intel/2019a] WHAM v2.0.9.1
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.9.1-change_units.patch
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.9.1-intel-2019a-kj_mol.eb
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.9.1-intel-2019a.eb
Labels: new

#10715 {chem}[intel/2019b] ParmEd v3.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/ParmEd/ParmEd-3.2.0-intel-2019b-Python-3.7.4.eb
Labels: update

#10661 {lang}[GCCcore/10.1.0] dotNET-SDK v3.1.300
  easybuild/easyconfigs/d/dotNET-SDK/dotNET-SDK-3.1.300-linux-x64.eb
Labels: new

#10702 {data,tools}[GCCcore/9.3.0] MDBM v4.13.0, CppUnit v1.15.1
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/MDBM/MDBM-4.13.0-GCCcore-9.3.0.eb
Labels: update

#10686 update: libGLU source URL: use https
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016a-Mesa-11.2.1.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2017a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2017b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2018a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2018b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-fosscuda-2017b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-fosscuda-2018a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-fosscuda-2018b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-gimkl-2.11.5.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2016a-Mesa-11.2.1.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2016a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2016b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2017a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2017b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2018a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2018b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intelcuda-2017b.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-iomkl-2018a.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-9.3.0.eb
Labels: bug fix

#10700 {numlib}[foss/2020a] Armadillo v9.880.1, arpack-ng v3.7.0
  easybuild/easyconfigs/a/Armadillo/Armadillo-9.880.1-foss-2020a.eb
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.7.0-foss-2020a.eb
Labels: update

#10704 {devel}[system/system] Saxon-HE v9.9.1.7
  easybuild/easyconfigs/s/Saxon-HE/Saxon-HE-9.9.1.7-Java-13.eb
Labels: update

#9848 {tools}[system/system] IntelDAAL v2019.4.007
  easybuild/easyconfigs/i/IntelDAAL/IntelDAAL-2019.4.007.eb
Labels: new

#10678 {bio}[foss/2018b] BEDTools v2.28.0
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.28.0-foss-2018b.eb
Labels: update

#10720 SuiteSparse: has a build dep for M4.
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.6.0-foss-2019b-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.6.0-intel-2019b-METIS-5.1.0.eb
Labels: bug fix

#9919 {bio}[GCC/8.3.0] AmrPlusPlus v2.0
  easybuild/easyconfigs/a/AmrPlusPlus/AmrPlusPlus-2.0-20200114-GCC-8.3.0.eb
Labels: new

#10694 {bio}[foss/2020a] MRtrix v3.0.0 w/ Python 3.8.2
  easybuild/easyconfigs/m/MRtrix/MRtrix-3.0.0-foss-2020a-Python-3.8.2.eb
Labels: update

#10693 update UDUNITS source_urls to https sources
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.24-intel-2017a.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.25-foss-2017b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.25-intel-2017b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.2.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.3.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-9.3.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2018a.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2018b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2017b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018a.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-iomkl-2018b.eb
Labels: bug fix

#9792 {lib}[system] XALT v2.8.4
  easybuild/easyconfigs/x/XALT/XALT-2.8.4.eb
Labels: new

#10721 {bio}[foss/2020a] Seurat v3.1.5 w/ R 4.0.0
  easybuild/easyconfigs/s/Seurat/Seurat-3.1.5-foss-2020a-R-4.0.0.eb
Labels: update

#10692 add alternative checksum for pkgmaker, doRNG, cobs extension in R 3.6.0
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
Labels: bug fix
