Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-10, with the labels that each got.

#11251 {devel}[foss/2019b] PyTorch v1.6.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-foss-2019b-Python-3.7.4.eb
Labels: update

#11412 fix broken worker easyconfigs
  easybuild/easyconfigs/w/worker/worker-1.6.11-intel-2019b.eb
  easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2016b.eb
  easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2017a.eb
  easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2017b.eb
  easybuild/easyconfigs/w/worker/worker-1.6.8-intel-2018a.eb
  easybuild/easyconfigs/w/worker/worker-1.6.8-intel-2018b.eb
Labels: bug fix

#11388 add patch for LAME configure script to make it check for correct ncurses symbol
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-intel-2017b.eb
  easybuild/easyconfigs/l/LAME/LAME-3.99.5-foss-2016b.eb
  easybuild/easyconfigs/l/LAME/LAME-3.99.5-intel-2017a.eb
  easybuild/easyconfigs/l/LAME/LAME-3.99.5_check-tgetent.patch
Labels: EESSI, bug fix

#11415 Add ncurses runtime dependency to Clang
  easybuild/easyconfigs/c/Clang/Clang-10.0.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/Clang/Clang-8.0.1-GCC-8.3.0-CUDA-10.1.243.eb
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCCcore-8.3.0.eb
Labels: enhancement

#11416 Add ncurses runtime dependency to Clang
  easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCCcore-8.2.0-CUDA-10.1.105.eb
  easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/c/Clang/Clang-8.0.1-GCC-8.2.0-2.31.1-CUDA-10.1.105.eb
Labels: enhancement

#11414 {chem}[intel/2020a] DIRAC v19.0 w/ Python 2.7.18
  easybuild/easyconfigs/d/DIRAC/DIRAC-19.0-intel-2020a-Python-2.7.18-int64.eb
  easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_remove-broken-tests-intel.patch
Labels: update

#11409 fix OpenFOAM 2.3.1-intel-2019b installation on RHEL8
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1-intel-2019b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1_RHEL8.patch
Labels: bug fix

#11295 Added CUDA 11.0.2 and related recipes, incl. gompic/2020a and iccifortcuda/2020a
  easybuild/easyconfigs/c/CUDA/CUDA-11.0.2-GCC-9.3.0.eb
  easybuild/easyconfigs/c/CUDA/CUDA-11.0.2-iccifort-2020.1.217.eb
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.0.2.eb
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.1-GCCcore-9.3.0-CUDA-11.0.2.eb
  easybuild/easyconfigs/g/gcccuda/gcccuda-2020a.eb
  easybuild/easyconfigs/g/gompic/gompic-2020a.eb
  easybuild/easyconfigs/i/iccifortcuda/iccifortcuda-2020a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-gcccuda-2020a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-iccifortcuda-2020a.eb
  easybuild/easyconfigs/u/UCX/UCX-1.8.0-GCCcore-9.3.0-CUDA-11.0.2.eb
Labels: update

#11413 {lang}[GCCcore/9.3.0] SBCL v2.0.9
  easybuild/easyconfigs/s/SBCL/SBCL-2.0.9-GCCcore-9.3.0.eb
Labels: new

#11419 Add ncurses runtime dependency to Clang
  easybuild/easyconfigs/c/Clang/Clang-10.0.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/Clang/Clang-10.0.1-GCCcore-9.3.0.eb
Labels: enhancement

#11375 in-place update of TensorFlow 2.3.0 easyconfigs to version 2.3.1
  easybuild/easyconfigs/h/Horovod/Horovod-0.20.0-fosscuda-2019b-TensorFlow-2.3.1-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11421 Add patch to libunwind fixing a failure on POWER
  easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1_fix_ppc64_fpreg_t.patch
Labels: bug fix

#11386 stick to Python 2 as build dep for Qt5 5.13.1
  easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb
Labels: bug fix

#11427 {tools}[gompi/2020a] mpifileutils v0.10.1
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.10.1-gompi-2020a.eb
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.10.1_fix_acl_xattr_problem.patch
Labels: bug fix, update

#11407 {lib}[foss/2020a] igraph v0.8.2, leidenalg v0.8.2, PyCairo v1.18.2, ... w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/i/igraph/igraph-0.8.2-foss-2020a.eb
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.18.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.8.0-foss-2020a.eb
Labels: new, update

#11437 fix PyVCF easyconfig, only supports Python 2
  easybuild/easyconfigs/b/BAMSurgeon/BAMSurgeon-1.2-GCC-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/p/PyVCF/PyVCF-0.6.8-GCC-8.3.0-Python-2.7.16.eb
Labels: bug fix

#11428 R 4.0.0 - Fix infinite loop build bug on ppc64le
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
  easybuild/easyconfigs/r/R/R-4.0.0_ppc64le-build-fix.patch
Labels: bug fix

#11425 {toolchain} intelcuda/2020a
  easybuild/easyconfigs/h/HPL/HPL-2.3-intelcuda-2020a.eb
  easybuild/easyconfigs/i/iimpic/iimpic-2020a.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.1.217-iimpic-2020a.eb
  easybuild/easyconfigs/i/impi/impi-2019.7.217-iccifortcuda-2020a.eb
  easybuild/easyconfigs/i/intelcuda/intelcuda-2020a.eb
Labels: update

#11426 {bio}[system/system] BLAST v2.10.1
  easybuild/easyconfigs/b/BLAST/BLAST-2.10.1-Linux_x86_64.eb
Labels: update

#11430 add dbarts extension to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11397 {perf}[gompic/2020a,iimpic/2020a] OSU-Micro-Benchmarks v5.6.3
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-gompic-2020a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-iimpic-2020a.eb
Labels: update

#11424 {toolchain} fosscuda/2020a
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompic-2020a.eb
  easybuild/easyconfigs/f/fosscuda/fosscuda-2020a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-fosscuda-2020a.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompic-2020a.eb
Labels: update

#11429 remove extentions from R-bundle-Bioconductor 3.11 easyconfigs that are also included in R 4.0.0
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: code cleanup

#11408 {tools}[intel/2018a] hypothesis v3.66.18 w/ Python 3.6.4
  easybuild/easyconfigs/h/hypothesis/hypothesis-4.39.3-intel-2018a-Python-3.6.4.eb
Labels: update

#11436 {data}[foss/2020a] causallift v1.0.6, kedro v0.16.5 w/ Python 3.8.2
  easybuild/easyconfigs/c/causallift/causallift-1.0.6-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/k/kedro/kedro-0.16.5-foss-2020a-Python-3.8.2.eb
Labels: new

#11433 {lib}[foss/2020a] pylift v0.1.5, XGBoost v1.2.0, pretty-yaml v20.4.0, ... w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/p/pretty-yaml/pretty-yaml-20.4.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/pylift/pylift-0.1.5-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/scikit-optimize/scikit-optimize-0.8.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/x/XGBoost/XGBoost-1.2.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11431 {math}[foss/2020a] treatSens v3.0-20201002 w/ R 4.0.0
  easybuild/easyconfigs/t/treatSens/treatSens-3.0-20201002-foss-2020a-R-4.0.0.eb
Labels: new

#11398 {bio}[fosscuda/2019b] GROMACS v2020.3
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-fosscuda-2019b.eb
Labels: update

#11440 {bio}[fosscuda/2019b] GROMACS v2019.6
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.6-fosscuda-2019b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019_fix_omp_num_threads_inc_threadmpi_and_google_test_death_style_in_tests.patch
Labels: bug fix, update

#11438 {bio,lib}[GCC/8.3.0] pyspoa v0.0.4, spoa v4.0.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.4-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.4_use-spoa-dep.patch
  easybuild/easyconfigs/s/spoa/spoa-4.0.0-GCC-8.3.0.eb
Labels: new, update

#11443 add patches for OpenBLAS easyconfigs using GCC/8.2.0-2.31.1 toolchain to fix miscomputation and performance issues
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.3-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.3_fix-dscal-inline-asm.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7_fix-missing-sync-on-power.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7_reinit-threads-after-fork.patch
Labels: bug fix

#11442 in-place update of easyconfig Horovod v0.20.0 to v0.20.3
  easybuild/easyconfigs/h/Horovod/Horovod-0.20.3-fosscuda-2019b-TensorFlow-2.3.1-Python-3.7.4.eb
Labels: bug fix, update

#10391 {bio,lang}[GCCcore/8.3.0] Longshot v0.4.1, Rust v1.42.0
  easybuild/easyconfigs/l/Longshot/Longshot-0.4.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-8.3.0.eb
Labels: update

#11448 {tools}[GCCcore/9.3.0] awscli v2.0.55 w/ Python 3.8.2
  easybuild/easyconfigs/a/awscli/awscli-2.0.55-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11404 {bio}[GCC/9.3.0] SiNVICT v1.0-20180817
  easybuild/easyconfigs/s/SiNVICT/SiNVICT-1.0-20180817-GCC-9.3.0.eb
Labels: new

#11451 add missing DB dependency to easyconfigs for Perl 5.28.1, 5.30.0 and 5.30.2 (required for DB_File)
  easybuild/easyconfigs/p/Perl/Perl-5.28.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: bug fix

#11453 fix dbarts extension in R v4.0.0 easyconfigs for non-x86_64
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
  easybuild/easyconfigs/r/R/dbarts-0.9-18_fix-simd-on-non-x86.patch
Labels: bug fix

#11452 add missing DB dependency to easyconfig for Perl 5.32.0
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-10.2.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.40_fix_doc_install.patch
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Labels: bug fix

#11450 {tools}[gcccuda/2019b] wandb v0.8.30 w/ Python 3.7.4
  easybuild/easyconfigs/w/wandb/wandb-0.8.30-gcccuda-2019b-Python-3.7.4.eb
Labels: new

#11457 {tools}[GCCcore/9.3.0] UnZip v6.0
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-9.3.0.eb
Labels: update

#5808 {chem}[intel/2017b] Dalton 2016
  easybuild/easyconfigs/d/Dalton/Dalton-2016-fix-bad-includepath-add.patch
  easybuild/easyconfigs/d/Dalton/Dalton-2016-fix-cmake-install.patch
  easybuild/easyconfigs/d/Dalton/Dalton-2016-fix-uninits.patch
  easybuild/easyconfigs/d/Dalton/Dalton-2016-intel-2017b-i8.eb
  easybuild/easyconfigs/d/Dalton/Dalton-2016-use-EB-install-for-dalton-script.patch
  easybuild/easyconfigs/d/Dalton/Dalton-2016_cmake-obey-EB-variables.patch
  easybuild/easyconfigs/d/Dalton/Dalton-2016_intel_lowopt.patch
Labels: new

#11464 Add support for building OpenBLAS on ARM TSV110 with GCC 8.3
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7-GCC-8.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7_fix-build-on-arm-tsv110.patch
Labels: bug fix

#11461 {phys}[foss/2020a] UDUNITS v2.2.26
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2020a.eb
Labels: update

#11469 cache M4 source tarball to avoid test failures because of download problems
  .github/workflows/unit_tests.yml
Labels: enhancement

#11458 add missing UnZip dependency for Python 3.8.2
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
Labels: bug fix

#11439 {bio}[foss/2019b] medaka v1.1.1, edlib v1.3.8.post1, Pysam v0.16.0.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/e/edlib/edlib-1.3.8.post1-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/m/medaka/medaka-1.1.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/medaka/medaka-1.1.1_use-SAMtools-dep.patch
  easybuild/easyconfigs/p/Pysam/Pysam-0.16.0.1-GCC-8.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#11417 fix installation of Bioconductor 3.11 bundle on aarch64
  easybuild/easyconfigs/r/R-bundle-Bioconductor/LEA-3.0.0_support_aarch64_and_ppc64le.patch
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/dada2-1.16.0-remove-sse-on-aarch64.patch
  easybuild/easyconfigs/r/R-bundle-Bioconductor/mzR-2.22.0_use-external-boost.patch
Labels: EESSI, aarch64, bug fix

#11454 use Homebrew source mirror to auto-download sources for DB v18.1.25 and v18.1.32
  easybuild/easyconfigs/d/DB/DB-18.1.25-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.32-GCCcore-8.2.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.32-GCCcore-8.3.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.32-GCCcore-9.3.0.eb
Labels: bug fix, change

#11475 {bio}[GCCcore/9.3.0] MEGAHIT v1.2.9: add missing moduleclass
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-9.3.0.eb
Labels: bug fix

#11474 {bio}[GCCcore/8.2.0] MEGAHIT v1.2.8: add missing moduleclass
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.8-GCCcore-8.2.0.eb
Labels: bug fix

#11344 {tools}[foss/2020a] IRkernel v1.1 w/ Python 3.8.2
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-foss-2020a-R-3.6.3-Python-3.8.2.eb
Labels: 2020a, update

#11484 {vis}[GCCcore/9.3.0] Xvfb v1.20.9, nettle v3.6
  easybuild/easyconfigs/n/nettle/nettle-3.6-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.9-GCCcore-9.3.0.eb
Labels: update

#11486 {lib}[GCCcore/10.2.0] libffi v3.3
  easybuild/easyconfigs/l/libffi/libffi-3.3-GCCcore-10.2.0.eb
Labels: update

#11483 Fix source for SQLite 3.31.1
  easybuild/easyconfigs/s/SQLite/SQLite-3.31.1-GCCcore-9.3.0.eb
Labels: bug fix

#11482 {lang}[GCCcore/10.2.0] Tcl v8.6.10
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-GCCcore-10.2.0.eb
Labels: 2020b, update

#11434 fix compilation of Qt5 v5.12.3 and v5.13.1 on Ubuntu 20.04
  easybuild/easyconfigs/q/Qt5/Qt5-5.12.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.12.3_fix-socketcan.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.12.3_fix-webrtc.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.13.1_fix-webrtc.patch
Labels: bug fix

#11470 {geo}[foss/2020a] geopandas v0.8.1 w/ Python 3.8.2
  easybuild/easyconfigs/g/geopandas/geopandas-0.8.1-foss-2020a-Python-3.8.2.eb
Labels: update

#11494 {tools}[GCCcore/9.3.0] Subversion v1.14.0
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/Subversion/Subversion-1.14.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-9.3.0.eb
Labels: update

#11480 {tools}[GCCcore/10.2.0] bzip2 v1.0.8
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-10.2.0.eb
Labels: 2020b, update

#11485 {math}[GCCcore/10.2.0] GMP v6.2.0
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-GCCcore-10.2.0.eb
Labels: update

#11481 {devel}[GCCcore/10.2.0] SQLite v3.33.0
  easybuild/easyconfigs/s/SQLite/SQLite-3.33.0-GCCcore-10.2.0.eb
Labels: 2020b, update

#11491 {devel}[GCCcore/10.2.0] intltool v0.51.0
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-10.2.0.eb
Labels: update

#11495 {vis}[GCCcore/10.2.0] libpng v1.6.37, freetype v2.10.3, util-linux v2.36, ...
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.92-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-GCCcore-10.2.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.36-GCCcore-10.2.0.eb
Labels: update

#11492 {tools}[GCCcore/10.2.0] CMake v3.18.4, cURL v7.72.0, libarchive v3.4.3
  easybuild/easyconfigs/c/CMake/CMake-3.18.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/c/cURL/cURL-7.72.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.4.3-GCCcore-10.2.0.eb
Labels: update

#10745 add Python 3 as build dep for Xvfb 1.20.8 easyconfigs
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/Xvfb/xkeyboard-config-2.29_fix-shebang-map-variants.patch
Labels: bug fix

#11500 disable libunwind + add xauth component for Xvfb 1.20.9
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.9-GCCcore-9.3.0.eb
Labels: bug fix

#11473 {bio}[foss/2019b] Arlequin v3.5.2.2: add missing moduleclass
  easybuild/easyconfigs/a/Arlequin/Arlequin-3.5.2.2-foss-2019b.eb
Labels: bug fix

#11467 {geo}[foss/2020a] PyGEOS v0.8 w/ Python 3.8.2
  easybuild/easyconfigs/p/PyGEOS/PyGEOS-0.8-foss-2020a-Python-3.8.2.eb
Labels: update

#11468 {geo}[foss/2020a] rasterstats v0.15.0, rasterio v1.1.7 w/ Python 3.8.2
  easybuild/easyconfigs/r/rasterio/rasterio-1.1.7-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/r/rasterstats/rasterstats-0.15.0-foss-2020a-Python-3.8.2.eb
Labels: new

#11471 Allow Kent_tools to build when MySQL installed at the OS level
  easybuild/easyconfigs/k/Kent_tools/Kent_tools-401-gompi-2019b.eb
Labels: bug fix

#11487 add reader, elementR, ie2misc, assertive, rdrop2 as extensions to R v4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11349 {bio}[GCCcore/9.3.0] MUMmer v3.23
  easybuild/easyconfigs/m/MUMmer/MUMmer-3.23-GCCcore-9.3.0.eb
Labels: 2020a, update

#11389 {geo}[intel/2019b] WRF v4.1.3
  easybuild/easyconfigs/w/WRF/WRF-4.1.3-intel-2019b-dm+sm.eb
Labels: update

#11410 {bio}[foss/2020a] OPERA-MS v0.9.0
  easybuild/easyconfigs/o/OPERA-MS/OPERA-MS-0.9.0-20200802-foss-2020a-Python-3.8.2.eb
Labels: new

#11499 {bio}[iccifort/2019.5.281] Structure v2.3.4
  easybuild/easyconfigs/s/Structure/Structure-2.3.4-iccifort-2019.5.281.eb
Labels: update

#11418 {bio}[intel/2020a] chewBBACA v2.5.5, Biopython v1.78, BLAST+ v2.10.1, ... w/ Python 3.8.2
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.10.1-iimpi-2020a.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.10.1_fix-64-icc.patch
  easybuild/easyconfigs/b/Biopython/Biopython-1.78-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/c/ClustalW2/ClustalW2-2.1-intel-2020a.eb
  easybuild/easyconfigs/c/chewBBACA/chewBBACA-2.5.5-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.453-iimpi-2020a-with-extensions.eb
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.471-iimpi-2020a-with-extensions.eb
Labels: new

#11151 {chem}[intel/2019b] PSI4 v1.3.2 w/ Python 3.7.4
  easybuild/easyconfigs/c/CheMPS2/CheMPS2-1.8.9-intel-2019b.eb
  easybuild/easyconfigs/d/deepdiff/deepdiff-5.0.2-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/PCMSolver/PCMSolver-1.2.3-iimpi-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PSI4/PSI4-1.3.2-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PSI4/PSI4-1.3.2_fix_cmake_release.patch
  easybuild/easyconfigs/p/Pint/Pint-0.14-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/pydantic/pydantic-1.6.1-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/pytest/pytest-6.0.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#11497 {chem}[intel/2020a] ABINIT v9.2.1
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.2.1-intel-2020a.eb
Labels: update

#9892 {bio}[iimpi/2019b] MMseqs2 v11-e1a1c
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-11-e1a1c-iimpi-2019b.eb
Labels: update

#11507 {data}[intel/2020a] xarray v0.16.1 w/ Python 3.8.2
  easybuild/easyconfigs/x/xarray/xarray-0.16.1-intel-2020a-Python-3.8.2.eb
Labels: update

#11472 add missing ncurses dep for Clang 5.0.x, 6.0.1, 7.0.x
  easybuild/easyconfigs/c/Clang/Clang-5.0.0-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/c/Clang/Clang-5.0.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/c/Clang/Clang-6.0.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/c/Clang/Clang-6.0.1-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/c/Clang/Clang-7.0.0-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/c/Clang/Clang-7.0.1-GCC-7.3.0-2.30.eb
Labels: bug fix

#11513 {phys}[dummy/] COMSOL v5.4.0.225
  easybuild/easyconfigs/c/COMSOL/COMSOL-5.4.0.225.eb
Labels: new

#4247 {chem}[dummy/dummy] Gaussian v09.e.01-AVX, Gaussian v16.A.03-AVX2
  easybuild/easyconfigs/g/Gaussian/Gaussian-09.e.01-AVX.eb
  easybuild/easyconfigs/g/Gaussian/Gaussian-16.A.03-AVX2.eb
Labels: new

#11510 {cae}[system] FLUENT v18.2
  easybuild/easyconfigs/f/FLUENT/FLUENT-18.2.eb
Labels: update

#11511 {lib,lang}[foss/2017b] Boost.Python v1.65.1, PyCUDA v2017.1.1 w/ Python 2.7.14 (+ build Boost with -std=c++11)
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.65.1-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/b/Boost/Boost-1.65.1-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyCUDA/PyCUDA-2017.1.1-foss-2017b-CUDA-9.0.176-Python-2.7.14.eb
Labels: update

#6067 {bio}[foss/2016b] ReMatCh 3.2
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.3.1-foss-2016b.eb
  easybuild/easyconfigs/r/ReMatCh/ReMatCh-3.2-foss-2016b-Python-2.7.12.eb
Labels: new, update

#9978 {lang}[intel/2019a] SciPy-bundle v2019.10 w/ Python 3.7.2
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-intel-2019a-Python-3.7.2.eb
Labels: update

#6066 {bio} [foss/2016b] Genome_Profiler v2.1
  easybuild/easyconfigs/g/Genome_Profiler/Genome_Profiler-2.1-foss-2016b-Perl-5.24.0.eb
Labels: new

#6194 {vis}[GCCcore/6.4.0] libav v11.10
  easybuild/easyconfigs/l/libav/libav-11.10-GCCcore-6.4.0.eb
Labels: new

#6329 {geo}[intel/2017b] ESMValTool 1.1.0 w/ Python 2.7.14
  easybuild/easyconfigs/c/check/check-0.12.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/e/ESMValTool/ESMValTool-1.1.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/e/ESMValTool/basemap-1.1.0_GEOS.patch
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.7.3-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/l/libmo_unpack/libmo_unpack-3.1.2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libmo_unpack/libmo_unpack-3.1.2_cmake_have_stdint.patch
  easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023-HDF5-1.8.19.eb
Labels: new, update

#6202 {vis}[GCCcore/6.4.0] SDL_image v1.2.12
  easybuild/easyconfigs/s/SDL/SDL-1.2.15-91ad7b43317a.patch
  easybuild/easyconfigs/s/SDL/SDL-1.2.15-GCCcore-6.4.0.eb
  easybuild/easyconfigs/s/SDL_image/SDL_image-1.2.12-GCCcore-6.4.0.eb
Labels: new

#11509 {lib}[system/system] GitPython v2.1.15
  easybuild/easyconfigs/g/GitPython/GitPython-2.1.15.eb
Labels: update

#6203 {vis}[GCCcore/6.4.0] SDL2_image v2.0.3
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.8-GCCcore-6.4.0.eb
  easybuild/easyconfigs/s/SDL2_image/SDL2_image-2.0.3-GCCcore-6.4.0.eb
Labels: new, update

#6206 {devel}[GCCcore/6.4.0] PCRE v8.42
  easybuild/easyconfigs/p/PCRE/PCRE-8.42-GCCcore-6.4.0.eb
Labels: update

#6151 {chem}[foss/2016b] NAMD v2.12
  easybuild/easyconfigs/n/NAMD/NAMD-2.12-foss-2016b-CUDA-8.0.61.eb
Labels: update

#6207 {bio}[GCC/6.4.0] HTSlib v1.8
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.8-GCC-6.4.0-2.28.eb
Labels: update

#11490 {lang}[GCCcore/10.2.0] Python v2.7.18, Python v3.8.4
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-10.2.0.eb
Labels: update

#11502 {lib}[GCCcore/9.3.0] fmt v7.0.3
  easybuild/easyconfigs/f/fmt/fmt-7.0.3-GCCcore-9.3.0.eb
Labels: update

#11505 {base}[GCCcore/9.3.0] CCfits v2.5
  easybuild/easyconfigs/c/CCfits/CCfits-2.5-GCCcore-9.3.0.eb
Labels: new

#11515 fix checksum in NAMD 2.12 easyconfigs + add source URL
  easybuild/easyconfigs/n/NAMD/NAMD-2.12-foss-2017a-mpi.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.12-foss-2017b-mpi.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.12-intel-2017a-mpi.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.12-intel-2017b-mpi.eb
Labels: bug fix

#6341 update README on constructing source file for MATLAB
  easybuild/easyconfigs/m/MATLAB/README
  easybuild/easyconfigs/m/MATLAB/README.md
Labels: documentation

#6210 {bio}[GCC/6.4.0] BCFtools v1.8
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.8-GCC-6.4.0-2.28.eb
Labels: update

#6368 {bio}[foss/2016b] HyPhy v2.3.13
  easybuild/easyconfigs/h/HyPhy/HyPhy-2.3.13-foss-2016b.eb
Labels: new

#11520 {lib}[foss/2018a] libepoxy v1.5.2
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.2-foss-2018a.eb
Labels: update

#11514 {chem}[foss/2020a] TINKER v8.8.1
  easybuild/easyconfigs/t/TINKER/TINKER-8.8.1-foss-2020a.eb
Labels: update

#11488 add crossmeta extension to Bioconductor 3.11 bundle
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#6171 {devel}[intel/2017a] pbs_python v4.6.0 w/ Python-2.7.13
  easybuild/easyconfigs/p/pbs_python/pbs_python-4.6.0-intel-2017a-Python-2.7.13.eb
Labels: new, update

#6408 {cae}[intel/2018a] Nek5000 v17.0
  easybuild/easyconfigs/n/Nek5000/Nek5000-17.0-intel-2018a.eb
  easybuild/easyconfigs/n/Nek5000/Nek5000-17.0_hypre_blas.patch
  easybuild/easyconfigs/n/Nek5000/Nek5000-17.0_sundials.patch
Labels: new

#6885 {bio}[SYSTEM] SeqKit v0.8.1
  easybuild/easyconfigs/s/SeqKit/SeqKit-0.8.1.eb
  easybuild/easyconfigs/s/SeqKit/SeqKit-0.8.1_go-mod.patch
Labels: new

#6609 {bio}[intel-2018a] trimAl v1.4.1
  easybuild/easyconfigs/t/trimAl/trimAl-1.4.1-intel-2018a.eb
Labels: update

#11521 {tools}[GCCcore/9.3.0] ExifTool v12.00
  easybuild/easyconfigs/e/ExifTool/ExifTool-12.00-GCCcore-9.3.0.eb
Labels: new

#11518 {tools}[GCCcore/10.2.0] Meson v0.55.3, Ninja v1.10.1 w/ Python 3.8.6
  easybuild/easyconfigs/m/Meson/Meson-0.55.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.1-GCCcore-10.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#6558 {cae}[intel/2018a] OpenFOAM v2.2.2
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.2.2-intel-2018a.eb
Labels: update

#6465 {cae}[foss/2018a] CFDEMcoupling v3.8.0
  easybuild/easyconfigs/c/CFDEMcoupling/CFDEMcoupling-3.8.0-foss-2018a.eb
Labels: new

#11517 {tools}[foss/2019b] silx 0.13.2, nanomax-analysis-utils 0.4 with Python 3.7.4
  easybuild/easyconfigs/f/FabIO/FabIO-0.10.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/f/FabIO/FabIO-0.10.2-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/n/nanomax-analysis-utils/nanomax-analysis-utils-0.4-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/n/nanomax-analysis-utils/nanomax-analysis-utils-0.4-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyOpenCL/PyOpenCL-2020.2.2-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/q/QtPy/QtPy-1.9.0-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/q/Qtconsole/Qtconsole-4.7.7-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/q/Qtconsole/Qtconsole-4.7.7-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/silx/silx-0.13.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/silx/silx-0.13.2-fosscuda-2019b-Python-3.7.4.eb
Labels: new

#6551 {bio}[foss/2017b] Bsoft v2.0.2
  easybuild/easyconfigs/b/Bsoft/Bsoft-2.0.2-foss-2017b.eb
  easybuild/easyconfigs/b/Bsoft/Bsoft-2.0.2_use-eb-packages.patch
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-foss-2017b.eb
Labels: update

#6613 {tools}[intel/2018a] Fortran Unit Test Framework, FRUIT v3.4.3 and dependencies, on top of Ruby 2.5.1
  easybuild/easyconfigs/f/FRUIT/FRUIT-3.4.3-foss-2018a-Ruby-2.5.1.eb
  easybuild/easyconfigs/f/FRUIT/FRUIT-3.4.3-intel-2018a-Ruby-2.5.1.eb
  easybuild/easyconfigs/f/FRUIT/fruit_3.4.3-gfortran-fPIC.patch
  easybuild/easyconfigs/f/FRUIT/fruit_3.4.3-ifort-external.patch
  easybuild/easyconfigs/f/FRUIT/fruit_3.4.3-mpi-tests.patch
  easybuild/easyconfigs/f/FRUIT_processor/FRUIT_processor-3.4.3-foss-2018a-Ruby-2.5.1.eb
  easybuild/easyconfigs/f/FRUIT_processor/FRUIT_processor-3.4.3-intel-2018a-Ruby-2.5.1.eb
  easybuild/easyconfigs/r/Ruby-Tk/Ruby-Tk-0.2.0-foss-2018a-Ruby-2.5.1.eb
  easybuild/easyconfigs/r/Ruby-Tk/Ruby-Tk-0.2.0-intel-2018a-Ruby-2.5.1.eb
  easybuild/easyconfigs/r/Ruby/Ruby-2.5.1-foss-2018a.eb
Labels: new

#11503 {vis}[GCCcore/9.3.0] PyQt5 v5.15.1 w/ Python 3.8.2
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.1-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#6028 {chem}[foss/2018a] AmberTools v17
  easybuild/easyconfigs/a/AmberTools/AmberTools-17-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/a/AmberTools/AmberTools-17_fixes-foss.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-17_fixes.patch
Labels: update

#11528 {vis}[GCCcore/10.2.0] gettext v0.21, X11 v20201008, Tk v8.6.10, ... w/ Python 3.8.6
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.10-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.8.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/X11/X11-20201008-GCCcore-10.2.0.eb
Labels: update

#11529 {tools}[GCCcore/10.2.0] Szip v2.1.1, pigz v2.4, gzip v1.10, ...
  easybuild/easyconfigs/g/gzip/gzip-1.10-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.9.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/pigz/pigz-2.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.4.5-GCCcore-10.2.0.eb
Labels: update

#6663 {lang}[foss/2018b] R v3.5.1 (bare)
  easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-bare.eb
Labels: update

#11508 {tools}[foss/2020a] Spyder v4.1.5 w/ Python 3.8.2
  easybuild/easyconfigs/s/Spyder/Spyder-4.1.5-foss-2020a-Python-3.8.2.eb
Labels: update

#11527 build LibTIFF with -fPIC
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.10-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.10-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-GCCcore-5.4.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-foss-2016a.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-foss-2016b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-intel-2016a.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-intel-2016b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.7-foss-2016b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.7-intel-2017a.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.8-intel-2017a.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.8-intel-2017b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-intel-2017b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-intel-2018.01.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-intel-2018b.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.1.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.1.0-GCCcore-9.3.0.eb
Labels: enhancement

#6811 {data}[intel/2018a] BDBag v1.4.1 w/ Python 3.6.4
  easybuild/easyconfigs/b/BDBag/BDBag-1.4.1-intel-2018a-Python-3.6.4.eb
Labels: update

#6821 {lib} [GCCcore/6.4.0] libxcb v1.13
  easybuild/easyconfigs/l/libXau/libXau-1.0.8-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libXdmcp/libXdmcp-1.1.2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libxcb/libxcb-1.13-GCCcore-6.4.0.eb
  easybuild/easyconfigs/x/xcb-proto/xcb-proto-1.13.eb
Labels: update

#7031 {bio}[system] ORFfinder 0.4.3
  easybuild/easyconfigs/o/ORFfinder/ORFfinder-0.4.3.eb
Labels: new

#11523 add BLAS/LAPACK check to GPAW patch adding EasyBuild configuration files
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Add-Easybuild-configuration-files.patch
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-intel-2019b-Python-3.7.4.eb
Labels: bug fix

#6229 {phys}[foss/2017b] Siesta v4.0
  easybuild/easyconfigs/s/Siesta/Siesta-4.0-foss-2017b.eb
Labels: update

#6856 {math}[intel/2018a] lavaan v0.6-2 w/ R 3.4.4
  easybuild/easyconfigs/l/lavaan/lavaan-0.6-2-intel-2018a-R-3.4.4.eb
Labels: new

#11512 {bio}[intel/2020a] GBprocesS v2.3 w/ Python 3.8.2
  easybuild/easyconfigs/g/GBprocesS/GBprocesS-2.3-intel-2020a-Python-3.8.2.eb
Labels: new

#11498 fix worker-1.6.11-intel-2019b installation on RHEL 8.2
  easybuild/easyconfigs/w/worker/worker-1.6.11-intel-2019b.eb
Labels: bug fix

#11539 Push FLTK-1.3.5 to GCCcore level
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.5-GCCcore-9.3.0.eb
Labels: change

#11531 {tools}[GCCcore/10.2.0] git v2.28.0
  easybuild/easyconfigs/g/git/git-2.28.0-GCCcore-10.2.0-nodocs.eb
Labels: update

#11530 {lib}[GCCcore/10.2.0] re2c v2.0.3, PCRE2 v10.35, double-conversion v3.1.5, ...
  easybuild/easyconfigs/d/DBus/DBus-1.13.18-GCCcore-10.2.0.eb
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.66.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/NSPR/NSPR-4.29-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.57-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PCRE/PCRE-8.44-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.35-GCCcore-10.2.0.eb
  easybuild/easyconfigs/r/re2c/re2c-2.0.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/snappy/snappy-1.1.8-GCCcore-10.2.0.eb
Labels: update

#11541 {lang}[foss/2019b] V8 v3.2.0
  easybuild/easyconfigs/v/V8/V8-3.2.0-foss-2019b-R-3.6.2.eb
Labels: update

#11526 {devel,lib,system,tools}[GCCcore/10.2.0] OpenPGM v5.2.122, ZeroMQ v4.3.3, IPython v7.18.1, JupyterLab v2.2.8 ... w/ Python 3.8.6
  easybuild/easyconfigs/i/IPython/IPython-7.18.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-2.2.8-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-GCCcore-10.2.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-10.2.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.3-GCCcore-10.2.0.eb
Labels: update

#11532 {vis}[GCCcore/10.2.0] Pango v1.47.0, at-spi2-atk v2.38.0, HarfBuzz v2.6.7, ... w/ Python 3.8.6
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.38.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/c/cairo/cairo-1.16.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.10-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.66.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.40.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.6.7-GCCcore-10.2.0.eb
  easybuild/easyconfigs/i/ICU/ICU-67.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.47.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/pixman/pixman-0.40.0-GCCcore-10.2.0.eb
Labels: update

#11535 {tools}[GCCcore/10.2.0] APR v1.7.0, APR-util v1.6.1, utf8proc v2.5.0, ... w/ Python 3.8.6
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/SCons/SCons-4.0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9_python3_scons.patch
  easybuild/easyconfigs/s/Subversion/Subversion-1.14.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-10.2.0.eb
Labels: update

#11538 {bio}[system/system] SeqKit v0.13.2
  easybuild/easyconfigs/s/SeqKit/SeqKit-0.13.2.eb
  easybuild/easyconfigs/s/SeqKit/SeqKit-0.13.2_go-mod.patch
Labels: update

#11533 {compiler}[GCCcore/10.2.0] LLVM v11.0.0
  easybuild/easyconfigs/l/LLVM/LLVM-11.0.0-GCCcore-10.2.0.eb
Labels: update

#11540 {perf}[gompi/2020a] Backported fixes for Score-P v6.0
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompi-2020a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompic-2019b.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0_binutils_2.34_api_change.patch
  easybuild/easyconfigs/s/Score-P/Score-P-6.0_no_PDT_for_CUDA.patch
Labels: bug fix

#11501 {lib}[GCCcore/9.3.0] fmt v6.2.1
  easybuild/easyconfigs/f/fmt/fmt-6.2.1-GCCcore-9.3.0.eb
Labels: update

#11537 {bio}[GCC/9.3.0] Bsoft v2.0.7
  easybuild/easyconfigs/b/Bsoft/Bsoft-2.0.7-GCC-9.3.0.eb
  easybuild/easyconfigs/b/Bsoft/Bsoft-2.0.7_use-eb-packages.patch
Labels: update

#11478 {bio}[GCCcore/8.3.0,GCCcore/9.3.0] pyEGA3 v3.4.0 w/ Python 3.7.4 + 3.8.2
  easybuild/easyconfigs/p/pyEGA3/pyEGA3-3.4.0-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/pyEGA3/pyEGA3-3.4.0-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11550 {perf}[gompi/2019b] OSU-Micro-Benchmarks v5.6.3
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-gompi-2019b.eb
Labels: update

#11547 {tools}[system/system] OpenRefine v3.4.1
  easybuild/easyconfigs/o/OpenRefine/OpenRefine-3.4.1-Java-11.eb
Labels: update

#11543 {devel}[GCCcore/9.3.0] Bazel v3.6.0
  easybuild/easyconfigs/b/Bazel/Bazel-3.6.0-GCCcore-9.3.0.eb
Labels: update

#11556 libarchive: add XZ builddep
  easybuild/easyconfigs/l/libarchive/libarchive-3.4.3-GCCcore-10.2.0.eb
Labels: bug fix

#11554 {devel}[system/system] ReFrame v3.2
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.2.eb
Labels: update
