Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-09, with the labels that each got.

#11189 pkg-config is required as a build dependency for libglvnd
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.2.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.2.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.2.0-GCCcore-9.3.0.eb
Labels: bug fix

#11185 {devel}[foss/2018b] Spark v3.0.0 w/ Python 2.7.15
  easybuild/easyconfigs/s/Spark/Spark-3.0.0-foss-2018b-Python-2.7.15.eb
Labels: update

#11088 Update checksums for R 3.6.0 packages and add patch for ppc
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
Labels: bug fix

#11186 Adding an easyconfig for cellranger-atac
  easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-1.2.0.eb
Labels: new

#11191 add missing libiconv build dep in recent Doxygen easyconfigs
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.15-GCCcore-8.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.16-GCCcore-8.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.17-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.15-GCCcore-7.2.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.16-GCCcore-9.3.0.eb
Labels: EESSI, bug fix

#11192 enhance Java/11 wrapper to also support for aarch64/Arm
  easybuild/easyconfigs/j/Java/Java-11.0.8-aarch64.eb
  easybuild/easyconfigs/j/Java/Java-11.eb
Labels: aarch64, bug fix, update

#11126 extend timeout for libxc-4.3.4 to avoid failing tests
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-9.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.5.281.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2020.1.217.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4_fix-timeout.patch
Labels: change

#11187 fix failing 'make check' for MPFR 4.x when installing with 'eb --rpath'
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.0.2-GCCcore-9.3.0.eb
Labels: EESSI, bug fix

#11188 fix failing 'make check' for recent GMP easyconfigs when installing with 'eb --rpath'
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-GCCcore-9.3.0.eb
Labels: EESSI, bug fix

#11196 {lang}[system/system] Julia v1.5.1
  easybuild/easyconfigs/j/Julia/Julia-1.5.1-linux-x86_64.eb
Labels: update

#11155 {data}[GCC/9.3.0,iccifort/2020.1.217] HDF5.Serial v1.10.6
  easybuild/easyconfigs/h/HDF5.Serial/HDF5.Serial-1.10.6-GCC-9.3.0.eb
  easybuild/easyconfigs/h/HDF5.Serial/HDF5.Serial-1.10.6-iccifort-2020.1.217.eb
Labels: update

#10312 {lib}[foss/2019b] tensorflow-probability v0.9.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/tensorflow-probability/tensorflow-probability-0.9.0-foss-2019b-Python-3.7.4.eb
Labels: new

#11213 fix installation of R v3.6.3 and v4.0.0 with foss/2020a on Arm (aarch64)
  easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
  easybuild/easyconfigs/r/R/ff-2.2-14.2_aarch64_support.patch
  easybuild/easyconfigs/r/R/liquidSVM-1.2.4-fix_ppc_and_aarch64_build.patch
Labels: aarch64, bug fix

#11216 {math}[fosscuda/2019b] scipy v1.4.1 w/ Python 3.7.4
  easybuild/easyconfigs/s/scipy/scipy-1.4.1-fix-pthread.patch
  easybuild/easyconfigs/s/scipy/scipy-1.4.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11157 [R 3.6.0] Add missing pocl dependency
  easybuild/easyconfigs/p/pocl/pocl-1.3-gcccuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
Labels: bug fix

#11202 add patch for pycrypto extension in recent Python easyconfigs to remove hardcoded /usr/include which causes problems when 'eb --sysroot' is used
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.7.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.7.4-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Python/pycrypto-2.6.1_remove-usr-include.patch
Labels: EESSI, bug fix

#10948 {vis}[fosscuda/2019b] VMD 1.9.4a43 and updated versions of ACTC and OptiX
  easybuild/easyconfigs/a/ACTC/ACTC-1.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/OptiX/OptiX-6.5.0.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a43-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a43_configure.patch
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a43_extra_colors.patch
Labels: update

#10470 {bio}[intel/2019b] minibar v20200326, edlib v1.3.8.post1 w/ Python 3.7.4
  easybuild/easyconfigs/e/edlib/edlib-1.3.8.post1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/minibar/minibar-20200326-intel-2019b-Python-3.7.4.eb
Labels: new

#11208 Prefer gc GitHub site for source downloads
  easybuild/easyconfigs/g/gc/gc-7.4.4-GCC-4.9.3-2.25.eb
  easybuild/easyconfigs/g/gc/gc-7.4.4-foss-2016a.eb
  easybuild/easyconfigs/g/gc/gc-7.6.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/gc/gc-7.6.10-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/gc/gc-7.6.12-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/gc/gc-7.6.12-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/gc/gc-7.6.4-GCCcore-7.3.0.eb
Labels: change

#11217 {base}[fosscuda/2019b] PyCUDA v2019.1.2 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyCUDA/PyCUDA-2019.1.2-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11218 {math}[foss/2019b] scipy v1.4.1 w/ Python 3.7.4
  easybuild/easyconfigs/s/scipy/scipy-1.4.1-foss-2019b-Python-3.7.4.eb
Labels: update

#11206 add additional extensions to R 4.0.0 easyconfigs: celestial + fasterize
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11215 {lib}[foss/2020a] stars v0.4-3 + sf 0.9-5 w/ R 4.0.0
  easybuild/easyconfigs/s/stars/stars-0.4-3-foss-2020a-R-4.0.0-Python-3.8.2.eb
Labels: new

#11136 {bio}[foss/2020a] immunedeconv v2.0.2 w/ R 4.0.0
  easybuild/easyconfigs/i/immunedeconv/immunedeconv-2.0.2-foss-2020a-R-4.0.0.eb
Labels: new

#11212 {compiler,lib}[GCC/9.3.0,GCCcore/9.3.0] Clang v10.0.1, pocl v1.5
  easybuild/easyconfigs/c/Clang/Clang-10.0.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/pocl/pocl-1.5-GCC-9.3.0.eb
  easybuild/easyconfigs/p/pocl/pocl-1.5_fix-examples.patch
Labels: update

#11109 update TensorFlow 2.1.0 easyconfigs to provide more dependencies via EasyBuild
  easybuild/easyconfigs/f/flatbuffers/flatbuffers-1.12.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.3-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/nsync/nsync-1.24.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-collective-all-reduce-strategy.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-flatbuffers.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-jsoncpp.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-nasm.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-protobuf.patch
Labels: change, enhancement, new, update

#11000 update easyconfig for PyTorch 1.4 to use custom easyblock and run on Power
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-add-cuda11-support.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fix-test-prec.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-check-cpp-extension.py
Labels: bug fix, change

#11204 {bio}[intel/2020a] Flye v2.8.1 w/ Python 3.8.2
  easybuild/easyconfigs/f/Flye/Flye-2.8.1-intel-2020a-Python-3.8.2.eb
Labels: update

#11211 {data}[fosscuda/2019b] pycocotools v2.0.1 w/ Python 3.7.4
  easybuild/easyconfigs/p/pycocotools/pycocotools-2.0.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11222 {devel}[GCCcore/9.3.0] protobuf v3.10.0
  easybuild/easyconfigs/p/protobuf/protobuf-3.10.0-GCCcore-9.3.0.eb
Labels: update

#11223 {tools}[GCCcore/9.3.0] git v2.23.0
  easybuild/easyconfigs/g/git/git-2.23.0-GCCcore-9.3.0-nodocs.eb
Labels: update

#11225 {math}[foss/2020a] sympy v1.6.2 w/ Python 3.8.2
  easybuild/easyconfigs/g/gmpy2/gmpy2-2.1.0b5-GCC-9.3.0.eb
  easybuild/easyconfigs/m/MPC/MPC-1.1.0-GCC-9.3.0.eb
  easybuild/easyconfigs/s/sympy/sympy-1.6.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/sympy/sympy-1.6.2_allpython.patch
Labels: update

#11219 update PyTorch 1.4 easyconfigs to use custom easyblock (and do less downloading during installations)
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0_add-cuda11-support.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0_fix-missing-source-dir.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0_fix-system-pybind11.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0_fix-test-prec.patch
Labels: bug fix, change

#11227 {data}[foss/2020a] Cartopy v0.18.0, Fiona v1.8.16, pyproj v2.6.1.post1, ... w/ Python 3.8.2
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.18.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/f/Fiona/Fiona-1.8.16-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/pyproj/pyproj-2.6.1.post1-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/s/Shapely/Shapely-1.7.1-GCC-9.3.0-Python-3.8.2.eb
Labels: update

#11229 {geo}[foss/2020a] rgdal v1.5-16 w/ R 4.0.0
  easybuild/easyconfigs/r/rgdal/rgdal-1.5-16-foss-2020a-R-4.0.0.eb
Labels: update

#11230 {geo}[foss/2020a] rgeos v0.5-5 with R 4.0.0
  easybuild/easyconfigs/r/rgeos/rgeos-0.5-5-foss-2020a-R-4.0.0.eb
Labels: update

#11221 {math}[foss/2020a] Theano v1.0.4 w/ Python 3.8.2
  easybuild/easyconfigs/t/Theano/Theano-1.0.4-foss-2020a-Python-3.8.2.eb
Labels: update

#11201 {lang}[GCCcore/10.2.0] Perl v5.32.0
  easybuild/easyconfigs/e/expat/expat-2.2.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Labels: update

#11233 update TensorFlow 2.0.0 easyconfigs to use more EasyBuild provided dependencies
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0_fix-system-flatbuffers.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0_fix-system-nasm.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.1-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix, change

#11194 Ghostscript fails to build on aarch64/arm without pkg-config as a build dependency
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.52-GCCcore-9.3.0.eb
Labels: aarch64, bug fix

#11210 {vis}[GCCcore/8.3.0] Graphviz v2.42.2, GTS v0.7.6
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.42.2-GCCcore-8.3.0-Java-11.eb
Labels: update

#11085 {chem}[intel/2019b] QuantumESPRESSO v6.6
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-intel-2019b.eb
Labels: update

#11244 prefer https over ftp in source_urls of IgBLAST easyconfig
  easybuild/easyconfigs/i/IgBLAST/IgBLAST-1.15.0-x64-linux.eb
Labels: change

#11241 add CUDA compute capabilities to torchvision-0.5.0
  easybuild/easyconfigs/t/torchvision/torchvision-0.5.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.4.0.eb
Labels: enhancement

#11167 {mpi}[GCC/9.3.0] OpenMPI v4.0.5
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-GCC-9.3.0.eb
Labels: update

#11207 {bio}[foss/2020a] Trycycler v0.3.3, edlib v1.3.8.post1 w/ Python 3.8.2
  easybuild/easyconfigs/e/edlib/edlib-1.3.8.post1-GCC-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/t/Trycycler/Trycycler-0.3.3-foss-2020a-Python-3.8.2.eb
Labels: new

#11246 move edlib and minibar down to iccifort toolchain
  easybuild/easyconfigs/e/edlib/edlib-1.3.8.post1-iccifort-2019.5.281-Python-3.7.4.eb
  easybuild/easyconfigs/m/minibar/minibar-20200326-iccifort-2019.5.281-Python-3.7.4.eb
Labels: bug fix, change

#10944 {vis}[intel/2018a, foss/2018b] fix source URL for Graphviz v2.40.1
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-foss-2018b.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-intel-2018a.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_skip-install-data-hook.patch
Labels: bug fix

#11248 create separate easyconfig for sf R package, so it can be used as a dependency of other bundles of R packages
  easybuild/easyconfigs/s/sf/sf-0.9-5-foss-2020a-R-4.0.0-Python-3.8.2.eb
  easybuild/easyconfigs/s/stars/stars-0.4-3-foss-2020a-R-4.0.0-Python-3.8.2.eb
Labels: change, new

#11249 {lib}[foss/2020a] hierfstat v0.5-7
  easybuild/easyconfigs/h/hierfstat/hierfstat-0.5-7-foss-2020a-R-4.0.0-Python-3.8.2.eb
Labels: new

#11257 fix recent Doxygen easyconfigs by promoting libiconv to runtime dependency
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-6.4.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.15-GCCcore-8.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.16-GCCcore-8.3.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.17-GCCcore-9.3.0.eb
Labels: bug fix

#11260 disable building the C++ extension in the protobuf-python v3.10.0 easyconfigs
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.10.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.10.0-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix

#11255 prepare release notes for EasyBuild v4.3.0
  RELEASE_NOTES
  setup.py
Labels: update

#11259 {bio,tools}[GCCcore/9.3.0] Trim_Galore v0.6.6, pigz v2.4 w/ Python 3.8.2
  easybuild/easyconfigs/p/pigz/pigz-2.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.6-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11262 {tools}[dummy/dummy] EasyBuild v4.3.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.0.eb
Labels: update

#11263 sync with master + bump version to 4.3.0dev
  RELEASE_NOTES
  setup.py
Labels: update

#11273 add pocl dependency to GDAL easyconfig using fosscuda/2019b toolchain to make sure it builds on POWER
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix

#10941 {vis}[GCCcore/8.3.0,foss/2019b] PyOpenGL v3.1.5, PyQtGraph v0.11.0 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/p/PyOpenGL/PyOpenGL-3.1.5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.11.0-foss-2019b-Python-3.7.4.eb
Labels: update

#8362 {chem}[foss/2019a] PSI4 v1.3.1 w/ Python 3.7.2
  easybuild/easyconfigs/p/PSI4/PSI4-1.3.1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PSI4/PSI4-1.3.1_fix_cmake_release.patch
Labels: update

#11198 {math}[intel/2019b] FHI-aims v200112_2
  easybuild/easyconfigs/f/FHI-aims/FHI-aims-200112_2-intel-2019b.eb
Labels: new

#11238 {bio}[GCCcore/9.3.0] GTDB-Tk v1.3.0, HMMER v3.3.1, FastANI v1.31, ... w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.4.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/f/FastANI/FastANI-1.31-iccifort-2020.1.217.eb
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-1.3.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.1-iimpi-2020a.eb
  easybuild/easyconfigs/p/prodigal/prodigal-2.6.3-GCCcore-9.3.0.eb
Labels: update

#11291 {tools} [GCCcore/8.2.0] Ghostscript 9.27: LIBS change to fix ZLIB error
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.27-GCCcore-8.2.0.eb
Labels: bug fix

#11282 fix build problems with make 4.2.1 on RHEL8
  easybuild/easyconfigs/a/Automake/Automake-1.15.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.15.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/make/make-4.2.1-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/m/make/make-4.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/make/make-4.2.1_RHEL8.patch
Labels: bug fix

#11299 {bio}[GCCcore/9.3.0] fetchMG v1.0
  easybuild/easyconfigs/f/fetchMG/fetchMG-1.0-GCCcore-9.3.0.eb
Labels: new

#11300 {lang}[GCCcore/9.3.0] Tkinter v2.7.18 w/ Python 2.7.18
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.18-GCCcore-9.3.0.eb
Labels: update

#11265 {numlib}[intel/2019b,intel/2020a] CBLAS v20110120
  easybuild/easyconfigs/c/CBLAS/CBLAS-20110120-intel-2019b.eb
  easybuild/easyconfigs/c/CBLAS/CBLAS-20110120-intel-2020a.eb
Labels: update

#11236 {tools}[gompi/2020a] phonemizer 2.2.1 w/ Python-3.8.2 + deps
  easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.50-gompi-2020a.eb
  easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.50_mbrola_location.patch
  easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.50_sonic_fftw.patch
  easybuild/easyconfigs/f/festival/festival-2.5.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/f/festival/festival-2.5.0_speech_tools.patch
  easybuild/easyconfigs/m/MBROLA/MBROLA-3.3-GCCcore-9.3.0-voices-20200330.eb
  easybuild/easyconfigs/m/MBROLA/MBROLA-3.3_makefile.patch
  easybuild/easyconfigs/p/phonemizer/phonemizer-2.2.1-gompi-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/sonic/sonic-20180202-gompi-2020a.eb
  easybuild/easyconfigs/s/sonic/sonic-20180202.patch
  easybuild/easyconfigs/s/speech_tools/speech_tools-2.5.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/speech_tools/speech_tools-2.5.0_easybuild.patch
Labels: new

#8598 {lang}[foss/2019a,intel/2019a] V8 v2.3
  easybuild/easyconfigs/v/V8/V8-2.3-foss-2019a-R-3.6.0.eb
  easybuild/easyconfigs/v/V8/V8-2.3-intel-2019a-R-3.6.0.eb
Labels: update

#11027 {bio}[GCC/8.3.0] IDBA-UD v1.1.3
  easybuild/easyconfigs/i/IDBA-UD/IDBA-UD-1.1.3-GCC-8.3.0.eb
Labels: update

#11307 PyQt5: remove --no-dist-info
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.12.1-GCCcore-8.2.0-Python-2.7.15.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.12.1-GCCcore-8.2.0-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.13.2-GCCcore-8.3.0-Python-3.7.4.eb
Labels: bug fix

#11298 {lang}[intel/2019b] R v3.6.2
  easybuild/easyconfigs/r/R/R-3.6.2-intel-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2_fix-intel-recent-glibc.patch
Labels: update

#11311 {base}[GCCcore/9.3.0] MEGAHIT v1.2.9 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-9.3.0.eb
Labels: update

#11309 {geo}[foss/2020a] ILAMB v2.5 w/ Python 3.8.2
  easybuild/easyconfigs/i/ILAMB/ILAMB-2.5-foss-2020a-Python-3.8.2.eb
Labels: new

#11308 {astro}[intel/2020a] astropy v4.0.1 w/ Python 3.8.2
  easybuild/easyconfigs/a/astropy/astropy-4.0.1-intel-2020a-Python-3.8.2.eb
Labels: update

#11317 {lang}[GCCcore/9.3.0] CCL v1.12
  easybuild/easyconfigs/c/CCL/CCL-1.12-GCCcore-9.3.0.eb
Labels: update

#11318 {bio}[GCC/9.3.0] BLAT v3.5
  easybuild/easyconfigs/b/BLAT/BLAT-3.5-GCC-9.3.0.eb
Labels: update

#10705 {data}[GCCcore/9.3.0] MDSplus v7.96.12, MDSplus-Java v7.96.12, MDSplus-Python v7.96.12 w/ Python 3.8.2
  easybuild/easyconfigs/m/MDSplus-Java/MDSplus-Java-7.96.12-GCCcore-9.3.0-Java-13.eb
  easybuild/easyconfigs/m/MDSplus-Java/MDSplus-Java-7.96.12_classpath.patch
  easybuild/easyconfigs/m/MDSplus-Python/MDSplus-Python-7.96.12-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/MDSplus/MDSplus-7.96.12-GCCcore-9.3.0.eb
Labels: update

#11319 make sure correct zlib is used in recent Ghostscript easyconfigs
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.23-GCCcore-6.4.0-cairo-1.14.12.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.23-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.23-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.50-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.52-GCCcore-9.3.0.eb
Labels: bug fix

#11301 remove easyconfigs for Taiyaki that depend on PyTorch 1.3.1, since latest version still requires PyTorch 1.2.0
  easybuild/easyconfigs/t/Taiyaki/Taiyaki-5.0.1-20200316-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/Taiyaki/Taiyaki-5.0.1-20200316-fosscuda-2019b-Python-3.7.4.eb
Labels: change

#11315 {lib}[foss/2020a] pandas v1.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/b/Bottleneck/Bottleneck-1.3.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/pandas/pandas-1.1.2-foss-2020a-Python-3.8.2.eb
Labels: update

#11276 {phys}[foss/2020a] Clang-Python-bindings v10.0.1, TRIQS v3.0.0, TRIQS-dft_tools v3.0.0, ... w/ Python 3.8.2
  easybuild/easyconfigs/c/Clang-Python-bindings/Clang-Python-bindings-10.0.1-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/n/NFFT/NFFT-3.5.2-foss-2020a.eb
  easybuild/easyconfigs/t/TRIQS-cthyb/TRIQS-cthyb-3.0.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/TRIQS-dft_tools/TRIQS-dft_tools-3.0.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/TRIQS-tprf/TRIQS-tprf-3.0.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/TRIQS/TRIQS-3.0.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11326 {bio}[GCC/9.3.0] SAMtools v1.11
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.11-GCC-9.3.0.eb
Labels: update

#11254 {devel}[GCCcore/10.2.0] Autotools v20200321
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20200321-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-10.2.0.eb
Labels: update

#11297 {bio}[foss/2019a,fosscuda/2019a] Taiyaki v5.1.0-20200617
  easybuild/easyconfigs/t/Taiyaki/Taiyaki-5.1.0-20200617-foss-2019a-Python-3.7.2-PyTorch-1.2.0.eb
  easybuild/easyconfigs/t/Taiyaki/Taiyaki-5.1.0-20200617-fosscuda-2019a-Python-3.7.2-PyTorch-1.2.0.eb
Labels: update

#11296 {vis}[GCC/9.3.0] FLTK v1.3.5
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.5-GCC-9.3.0.eb
  easybuild/easyconfigs/x/xprop/xprop-1.2.4-GCCcore-9.3.0.eb
Labels: update

#11302 {chem}[intel/2020a] PyRETIS v2.5.0 w/ Python 3.8.2
  easybuild/easyconfigs/p/PyRETIS/PyRETIS-2.5.0-intel-2020a-Python-3.8.2.eb
Labels: update

#11303 {chem}[foss/2020a] PyRETIS v2.5.0, MDTraj v1.9.4 w/ Python 3.8.2
  easybuild/easyconfigs/m/MDTraj/MDTraj-1.9.4-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/PyRETIS/PyRETIS-2.5.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11320 {lib}[GCCcore/10.2.0] UCX v1.9.0
  easybuild/easyconfigs/n/numactl/numactl-2.0.13-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.9.0-GCCcore-10.2.0.eb
Labels: update

#11324 {tools}[foss/2019a] Spyder v4.1.5 w/ Python 3.7.2
  easybuild/easyconfigs/s/Spyder/Spyder-4.1.5-foss-2019a-Python-3.7.2.eb
Labels: update

#11338 {bio}[GCCcore/9.3.0] GATK v4.1.8.1 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/g/GATK/GATK-4.1.8.1-GCCcore-9.3.0-Java-1.8.eb
Labels: update

#11327 Remove GLog and GFlags from PyTorch 1.2.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-fosscuda-2019a-Python-3.7.2.eb
Labels: bug fix

#11322 Remove GLog and GFlags from PyTorch 1.4.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix, change

#11314 Make CI sanity check messages less confusing ("is" -> "should be")
  test/easyconfigs/easyconfigs.py
Labels: change

#11354 {debugger}[gompi/2020a,iimpi/2020a] Valgrind v3.16.1
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.15.0-no-MPI-1.patch
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.16.1-gompi-2020a.eb
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.16.1-iimpi-2020a.eb
Labels: 2020a, update

#11353 {bio}[system/system] picard v2.22.1
  easybuild/easyconfigs/p/picard/picard-2.22.1-Java-11.eb
Labels: 2020a, update

#11352 {math}[gompi/2020a,iimpi/2020a] ParMETIS v4.0.3
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2020a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2020a.eb
Labels: 2020a, update

#11350 {bio}[GCCcore/9.3.0] MUMmer v4.0.0beta2
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0beta2-GCCcore-9.3.0.eb
Labels: 2020a, update

#11348 {perf}[gompi/2020a,iimpi/2020a] OSU-Micro-Benchmarks v5.6.3
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-gompi-2020a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-iimpi-2020a.eb
Labels: 2020a, update

#11347 {lib,tools}[gompi/2020a,iimpi/2020a] mpifileutils v0.10, libcircle v0.3
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-gompi-2020a.eb
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-iimpi-2020a.eb
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.10-gompi-2020a.eb
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.10-iimpi-2020a.eb
Labels: 2020a, update

#11346 {math}[GCC/9.3.0] libxsmm v1.16.1
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-GCC-9.3.0.eb
Labels: 2020a, update

#11330 fix HDF 4.2.14 easyconfigs for RHEL8
  easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-7.3.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-8.2.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-8.3.0.eb
Labels: bug fix

#11356 {chem}[foss/2020a] ASE v3.19.0 w/ Python 3.8.2
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11357 {chem}[intel/2020a] ASE v3.19.0 w/ Python 3.8.2
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-intel-2020a-Python-3.8.2.eb
Labels: update

#11328 add missing git build dependency for OpenImageIO 2.0.12
  easybuild/easyconfigs/o/OpenImageIO/OpenImageIO-2.0.12-gompi-2019b.eb
  easybuild/easyconfigs/o/OpenImageIO/OpenImageIO-2.0.12-iimpi-2019b.eb
Labels: bug fix

#11355 Make libtirpc easier to use as replacement of rpc in glibc (for RHEL8)
  easybuild/easyconfigs/l/libtirpc/libtirpc-1.2.6-GCCcore-8.3.0.eb
Labels: enhancement

#11334 add patch to fix installation of LAMMPS 7Aug2019 on AMD Epyc systems
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019_EPYC.patch
Labels: bug fix

#11283 {bio}[intel/2019b] MyCC v2017-03-01, tsne v0.1.8 w/ Python 2.7.16 + fetchMG v1.0, CD-HIT v4.8.1
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-iccifort-2019.5.281.eb
  easybuild/easyconfigs/f/fetchMG/fetchMG-1.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/MyCC/MyCC-2017-03-01-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/m/MyCC/MyCC-2017-03-01_fix_paths.patch
  easybuild/easyconfigs/t/tsne/tsne-0.1.8-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/t/tsne/tsne-0.1.8_fix-setup-py-imkl.patch
Labels: new, update

#11358 fix installation of Hadoop v2.10.0 on RHEL8
  easybuild/easyconfigs/h/Hadoop/HADOOP-14597.04.patch
  easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0-GCCcore-8.3.0-native.eb
  easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0_tirpc.patch
Labels: bug fix

#11351 {lib}[gompi/2020a,iimpi/2020a] OpenImageIO v2.1.12.0
  easybuild/easyconfigs/o/OpenImageIO/OpenImageIO-2.1.12.0-gompi-2020a.eb
  easybuild/easyconfigs/o/OpenImageIO/OpenImageIO-2.1.12.0-iimpi-2020a.eb
Labels: 2020a, update

#11040 {lib}[fosscuda/2019b] TensorFlow v2.3.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_fix-json-include-style.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_fix-protoc-build.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_fix-system-protobuf.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_fix-system-protobuf2.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_fix-system_absl_py.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_revert-tools-to-exectools-renaming.patch
Labels: update

#11335 {lib}[foss/2020a] tidybayes v2.1.1 w/ R 4.0.0
  easybuild/easyconfigs/t/tidybayes/tidybayes-2.1.1-foss-2020a-R-4.0.0.eb
Labels: new

#11340 add additional extensions to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11359 {tools}[fosscuda/2019b] Horovod v0.20.0 w/ Python 3.7.4 + TensorFlow v2.3.0
  easybuild/easyconfigs/h/Horovod/Horovod-0.20.0-fosscuda-2019b-TensorFlow-2.3.0-Python-3.7.4.eb
Labels: update

#11362 {lang}[system/system] Anaconda3 v2020.07
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2020.07.eb
Labels: update

#11343 {math}[foss/2020a,intel/2020a] ELPA v2019.11.001
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-foss-2020a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-intel-2020a.eb
Labels: update

#11368 {devel}[GCCcore/8.3.0,GCCcore/9.3.0] makeinfo v6.7
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-GCCcore-9.3.0.eb
Labels: new

#11332 {system}[GCCcore/10.2.0] hwloc 2.2.0 + deps
  easybuild/easyconfigs/g/gettext/gettext-0.21.eb
  easybuild/easyconfigs/h/hwloc/hwloc-2.2.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.16-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-10.2.0.eb
Labels: 2020b, update

#11341 add additional extensions to Bioconductor 3.11 bundle
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#11371 Really fix make 4.2.1 on RHEL 8
  easybuild/easyconfigs/m/make/make-4.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/make/make-4.2.1_RHEL8.patch
Labels: bug fix

#11366 {numlib}[iimpi/2020a] CGAL v4.14.3 w/ Python 3.8.2
  easybuild/easyconfigs/c/CGAL/CGAL-4.14.3-iimpi-2020a-Python-3.8.2.eb
Labels: update

#11200 add missing groff build dependency for Perl (provides nroff tool requires to install man pages)
  easybuild/easyconfigs/g/groff/groff-1.22.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: EESSI, bug fix, new

#11345 {chem}[gompi/2020a] Libint v2.6.0
  easybuild/easyconfigs/l/Libint/Libint-2.6.0-gompi-2020a-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/Libint/Libint-2.6.0_remove-test-eri.patch
Labels: 2020a, update

#11224 use more EasyBuild installed dependencies for TensorFlow 2.2.0
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb
Labels: change, enhancement

#11274 {data}[foss/2020a] Statistics-R v0.34
  easybuild/easyconfigs/s/Statistics-R/Statistics-R-0.34-foss-2020a.eb
Labels: new

#11382 {lang}[GCCcore/9.3.0] Guile v2.2.4
  easybuild/easyconfigs/g/Guile/Guile-2.2.4-GCCcore-9.3.0.eb
Labels: update

#11070 {chem}[intel/2019b] LAMMPS v7Aug2019 w/ Python 3.7.4 w/ OCTP
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos-OCTP.eb
Labels: update

#11370 {lib}[GCCcore/9.3.0] Xerces-C++ v3.2.3
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.3-GCCcore-9.3.0.eb
Labels: update

#11361 {vis}[GCCcore/9.3.0] VirtualGL v2.6.2
  easybuild/easyconfigs/v/VirtualGL/VirtualGL-2.6.2-GCCcore-9.3.0.eb
Labels: update

#11323 Remove GLog and GFlags from PyTorch 1.6.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix, change

#11360 {vis}[foss/2020a] OpenCV v4.2.0 w/ Python 3.8.2
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.2.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11281 {data,geo,tools}[fosscuda/2019b] Fiona v1.8.13, geopandas v0.7.0, networkx v2.4 w/ Python 3.7.4
  easybuild/easyconfigs/f/Fiona/Fiona-1.8.13-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/geopandas/geopandas-0.7.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/n/networkx/networkx-2.4-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11280 {math}[foss/2019b] Pingouin v0.3.8 w/ Python 3.7.4
  easybuild/easyconfigs/p/Pingouin/Pingouin-0.3.8-foss-2019b-Python-3.7.4.eb
Labels: new

#11279 add libtirpc as a build dep for HDF to fix installation on RHEL8
  easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libtirpc/libtirpc-1.2.6-GCCcore-9.3.0.eb
Labels: bug fix

#11258 {bio}[GCCcore/9.3.0] PAML v4.9j
  easybuild/easyconfigs/p/PAML/PAML-4.9j-GCCcore-9.3.0.eb
Labels: update

#11266 {vis}[fosscuda/2019b] torchvision v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/torchvision/torchvision-0.7.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.6.0.eb
Labels: update

#11365 add patch to fix installation of FuSeq v1.1.2 on RHEL8
  easybuild/easyconfigs/f/FuSeq/FuSeq-1.1.2-gompi-2019b.eb
  easybuild/easyconfigs/f/FuSeq/FuSeq-1.1.2_RHEL8.patch
Labels: bug fix

#11364 add patch to fix installation of Sailfish v0.10.1 on RHEL8
  easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1-gompi-2019b.eb
  easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1_RHEL8.patch
Labels: bug fix

#11232 {chem}[intel/2020a] ASE v3.20.1 w/ Python 3.8.2
  easybuild/easyconfigs/a/ASE/ASE-3.20.1-intel-2020a-Python-3.8.2.eb
Labels: update

#11242 {chem}[intel/2020a] TAMkin v1.2.6 w/ Python 3.8.2
  easybuild/easyconfigs/t/TAMkin/TAMkin-1.2.6-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/TAMkin/TAMkin-1.2.6_fix-python38.patch
Labels: update

#11240 {chem}[intel/2020a] QuickFF v2.2.4 w/ Python 3.8.2
  easybuild/easyconfigs/q/QuickFF/QuickFF-2.2.4-intel-2020a-Python-3.8.2.eb
Labels: update

#11231 {chem}[intel/2020a] phonopy v2.7.1 + spglib-python v1.16.0 w/ Python 3.8.2
  easybuild/easyconfigs/p/phonopy/phonopy-2.7.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.0-intel-2020a-Python-3.8.2.eb
Labels: update

#11234 {chem,tools}[intel/2020a] nglview v2.7.7, IPython v7.15.0 w/ Python 3.8.2
  easybuild/easyconfigs/i/IPython/IPython-7.15.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/nglview/nglview-2.7.7-intel-2020a-Python-3.8.2.eb
Labels: update

#11387 add libevent, libfabric and PMIx dependencies to OpenMPI 4.0.3 (for foss/2020a & iomkl/2020a)
  easybuild/easyconfigs/l/libfabric/libfabric-1.11.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-GCC-9.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-iccifort-2020.1.217.eb
Labels: EESSI, enhancement, update

#11339 fix dependency on Bowtie of v0.x in seq2HLA easyconfigs
  easybuild/easyconfigs/s/seq2HLA/seq2HLA-2.3-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/seq2HLA/seq2HLA-2.3-intel-2018a-Python-2.7.14.eb
Labels: bug fix

#11321 {chem}[intel/2020a] libobjcryst v2017.2.3, pyobjcryst v2.1.0.post2 w/ Python 3.8.2
  easybuild/easyconfigs/l/libobjcryst/libobjcryst-2017.2.3-intel-2020a.eb
  easybuild/easyconfigs/l/libobjcryst/libobjcryst-2017.2.3_sconscript_local.patch
  easybuild/easyconfigs/p/pyobjcryst/pyobjcryst-2.1.0.post2-intel-2020a-Python-3.8.2.eb
Labels: new

#11385 fix installation of Qt5 5.14.1 on top of zlib provided by Gentoo + stick to Python 2 as build dep
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.1_fix-OF-Gentoo.patch
Labels: EESSI, bug fix

#11390 Add protobuf-python as a dependency and corresponding sanity check to PyTorch 1.6
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix

#11179 update bx-python
  easybuild/easyconfigs/b/bx-python/bx-python-0.8.8-foss-2019b-Python-3.7.4.eb
Labels: update

#11158 {bio}[foss/2019b] CAVIAR 2.2-20190419
  easybuild/easyconfigs/c/CAVIAR/CAVIAR-2.2-20190419-foss-2019b.eb
  easybuild/easyconfigs/c/CAVIAR/CAVIAR-20200820-openblas.patch
Labels: new

#11380 {math}[intel/2020a] Harminv v1.4.1
  easybuild/easyconfigs/h/Harminv/Harminv-1.4.1-intel-2020a.eb
Labels: update
