Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-01, with the labels that each got.

#9500 {cae}[intel/2019b] OpenFOAM-Extend v4.0 (+ deps)
  easybuild/easyconfigs/m/Mesquite/Mesquite-2.3.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.0-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2019b.eb
  easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-iimpi-2019b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-iimpi-2019b.eb
Labels: update

#9594 use alias to ensure the OpenBLAS library is used for pythran
  easybuild/easyconfigs/p/pythran/pythran-0.9.4.post1-foss-2019b-Python-3.7.4.eb
Labels: enhancement

#9530 {devel}[GCCcore/8.2.0] Meld v3.20.1 w/ Python 3.7.2
  easybuild/easyconfigs/m/Meld/Meld-3.20.1-GCCcore-8.2.0-Python-3.7.2.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#9586 add SSL OS dependencies for GDAL 3.0.0
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-intel-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-intel-2019a-Python-3.7.2.eb
Labels: bug fix

#9589 {compiler}[GCCcore/8.3.0] Clang v9.0.1
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/Clang/libcxx-9.0.1-ppc64le.patch
Labels: update

#9591 patch for GCCcore 8.2.0 to fix '__float128 is not supported on this target' on ppc64le
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0_fix_float128_ppc64le.patch
Labels: bug fix

#7449 {chem}[foss/2018b,intel/2018b] horton 2.1.1 w/ Python 2.7.15 (+ deps)
  easybuild/easyconfigs/h/horton/horton-2.1.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/h/horton/horton-2.1.1-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/l/Libint/Libint-2.0.3-foss-2018b.eb
  easybuild/easyconfigs/l/Libint/Libint-2.0.3-intel-2018b.eb
  easybuild/easyconfigs/l/Libint/Libint-2.0.3-stable-fma.patch
  easybuild/easyconfigs/l/libxc/libxc-2.2.2-foss-2018b.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.2-intel-2018b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#9590 patch libcxx (Clang 8.0.0) on pcc64le for incomplete IBM128 long double in GCC
  easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCCcore-8.2.0-CUDA-10.1.105.eb
  easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/c/Clang/libcxx-8.0.0-ppc64le.patch
Labels: bug fix

#9543 build CMake in parallel
  easybuild/easyconfigs/c/CMake/CMake-3.1.3.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.2-GCCcore-7.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.10.3-GCCcore-7.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.11.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.11.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.11.4-GCCcore-7.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-7.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.12.1.eb
  easybuild/easyconfigs/c/CMake/CMake-3.13.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.3.1.eb
  easybuild/easyconfigs/c/CMake/CMake-3.5.2.eb
  easybuild/easyconfigs/c/CMake/CMake-3.6.1.eb
  easybuild/easyconfigs/c/CMake/CMake-3.7.1-GCCcore-6.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.7.2-GCCcore-6.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.8.0-GCCcore-6.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.8.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.8.2-GCCcore-6.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.9.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.9.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.9.1.eb
  easybuild/easyconfigs/c/CMake/CMake-3.9.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.9.5-GCCcore-6.4.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.9.6.eb
Labels: enhancement, performance

#9596 {data}[GCCcore/8.2.0] DCMTK-3.6.5
  easybuild/easyconfigs/d/DCMTK/DCMTK-3.6.5-GCCcore-8.2.0.eb
Labels: update

#9592 {compiler}[GCCcore/8.3.0] Clang v9.0.1 with CUDA 10.1.243
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb
Labels: update

#9593 {lib}[GCC/8.3.0 and gcccuda/2019b] pocl v1.4
  easybuild/easyconfigs/p/pocl/pocl-1.4-GCC-8.3.0.eb
  easybuild/easyconfigs/p/pocl/pocl-1.4-gcccuda-2019b.eb
  easybuild/easyconfigs/p/pocl/pocl-1.4_undef-bool-and-vector-from-altivec.patch
Labels: update

#9598 update copyright statements for 2020
  setup.py
  test/__init__.py
  test/easyconfigs/easyconfigs.py
  test/easyconfigs/styletests.py
  test/easyconfigs/suite.py
Labels: update

#9597 {bio}[GCCcore/8.2.0] ConnectomeWorkbench-1.3.2
  easybuild/easyconfigs/c/ConnectomeWorkbench/ConnectomeWorkbench-1.3.2-GCCcore-8.2.0.eb
Labels: update

#9554 {bio}[foss/2019a,fosscuda/2019a] mhcflurry v1.2.4 w/ Python 3.7.2
  easybuild/easyconfigs/m/mhcflurry/mhcflurry-1.2.4-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/m/mhcflurry/mhcflurry-1.2.4-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.3-fosscuda-2019a.eb
Labels: new, update

#9564 {tools}[fosscuda/2019b] Horovod v0.18.2 w/ Python 3.7.4
  easybuild/easyconfigs/h/Horovod/Horovod-0.18.2-fosscuda-2019b-TensorFlow-1.15.0-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#9599 fix name for plotly extension in plotly.py v4.4.1 easyconfig
  easybuild/easyconfigs/p/plotly.py/plotly.py-4.4.1-intel-2019b.eb
Labels: bug fix

#9595 {bio}[GCC/8.2.0-2.31.1] Beast v1.10.4
  easybuild/easyconfigs/b/Beast/Beast-1.10.4-GCC-8.2.0-2.31.1.eb
Labels: update

#9476 {vis}[foss/2019a] mayavi v4.7.1 w/ Python 3.7.2
  easybuild/easyconfigs/m/mayavi/mayavi-4.7.1-foss-2019a-Python-3.7.2.eb
Labels: update

#9486 {devel,lib}[GCCcore/8.3.0] glibc v2.30, make v4.2.1
  easybuild/easyconfigs/g/glibc/glibc-2.30-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/make/make-4.2.1-GCCcore-8.3.0.eb
Labels: update

#9581 {chem}[intel/2019b] PLUMED v2.5.3 w/ Python 3.7.4
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.3-intel-2019b-Python-3.7.4.eb
Labels: update

#9475 {bio}[foss/2018b] FSL 6.0.2 w/ CUDA 9.2.88
  easybuild/easyconfigs/f/FSL/FSL-6.0.2-foss-2018b-Python-2.7.15-CUDA-9.2.88.eb
  easybuild/easyconfigs/f/FSL/FSL-6.0.2_Enable_GPU_build.patch
  easybuild/easyconfigs/f/FSL/FSL-6.0.2_probtrackx2_gpu_large_mri_support.patch
Labels: update

#9601 fix broken easyconfigs for cyvcf2 v0.11.5 by adding missing 'monotonic' extension
  easybuild/easyconfigs/c/cyvcf2/cyvcf2-0.11.5-foss-2019a.eb
  easybuild/easyconfigs/c/cyvcf2/cyvcf2-0.11.5-intel-2019a.eb
Labels: bug fix

#9561 {bio}[foss/2019b] MRtrix v3.0_RC4 w/ Python 3.7.4
  easybuild/easyconfigs/m/MRtrix/MRtrix-3.0_RC4-foss-2019b-Python-3.7.4.eb
Labels: update

#9465 {math}[system/system] Gurobi v9.0.0
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.0.eb
Labels: update

#9609 {vis}[GCCcore/8.3.0] xprop v1.2.4
  easybuild/easyconfigs/x/xprop/xprop-1.2.4-GCCcore-8.3.0.eb
Labels: update

#9608 {lang}[system/system] Julia v1.3.1
  easybuild/easyconfigs/j/Julia/Julia-1.3.1-linux-x86_64.eb
Labels: update

#9604 Use absolute path for extraction to allow relocating the build dir for g2log-1.0
  easybuild/easyconfigs/g/g2log/g2log-1.0-foss-2016b.eb
Labels: bug fix

#9612 {cae}[foss/2019b] OpenFOAM v1912
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1912-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1912-foss-2019b.eb
Labels: update

#9603 {bio}[intel/2019a] breseq v0.35.0
  easybuild/easyconfigs/b/breseq/breseq-0.35.0-intel-2019a-R-3.6.0.eb
Labels: new

#9607 {vis}[GCC/8.3.0] FLTK v1.3.5
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.5-GCC-8.3.0.eb
Labels: update

#9606 {tools}[GCCcore/9.2.0] libxml2 v2.9.10, XZ v5.2.4
  easybuild/easyconfigs/g/gettext/gettext-0.20.1.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-9.2.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.4-GCCcore-9.2.0.eb
Labels: update

#9605 {devel}[GCCcore/9.2.0] Autotools v20180311
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-9.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-9.2.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-9.2.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-9.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#9618 {math}[GCCcore/8.3.0] libcerf v1.13
  easybuild/easyconfigs/l/libcerf/libcerf-1.13-GCCcore-8.3.0.eb
Labels: update

#9611 Update checksum for kallisto-0.43.1
  easybuild/easyconfigs/k/kallisto/kallisto-0.43.1-foss-2016b.eb
  easybuild/easyconfigs/k/kallisto/kallisto-0.43.1-intel-2017a.eb
  easybuild/easyconfigs/k/kallisto/kallisto-0.43.1-intel-2017b.eb
Labels: bug fix

#9621 add additional valid checksum for MASS 7.3-51.4 extension in R 3.6.0 easyconfigs
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
Labels: bug fix

#9622 ctffind website has moved
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.13-foss-2019a.eb
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.13-fosscuda-2019a.eb
Labels: bug fix

#9613 {bio}[foss/2019b,intel/2019b] OpenMM v7.4.1 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.4.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.4.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.4.1_fix-Doxygen.patch
Labels: update

#9614 {bio}[foss/2019a] gradunwarp 1.1.0 (HCP fork)
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.1.0-foss-2019a-HCP-Python-2.7.15.eb
Labels: new

#9630 {tools}[GCCcore/8.2.0] ownCloud 2.5.4
  easybuild/easyconfigs/o/ownCloud/ownCloud-2.5.4-GCCcore-8.2.0.eb
Labels: update

#9426 {bio}[system/system] Sambamba v0.7.1
  easybuild/easyconfigs/s/Sambamba/Sambamba-0.7.1.eb
Labels: update

#9637 {bio}[foss/2019a] gradunwarp 1.1.0 (HCP fork): Use PIP to install
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.1.0-foss-2019a-HCP-Python-2.7.15.eb
Labels: bug fix

#9634 Allow missing python versionsuffix for existing easyconfig files changed in PRs
  test/easyconfigs/easyconfigs.py
Labels: bug fix, change

#9515 {data,lib}[GCCcore/8.3.0,intel/2019b] NCL v6.6.2, libiconv v1.16
  easybuild/easyconfigs/l/libiconv/libiconv-1.16-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/NCL/NCL-6.6.2-intel-2019b.eb
Labels: update

#9644 {lang}[foss/2019a] R 3.6.0: Add second checksum for rda_1.0.2-2.1.tar.gz
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
Labels: bug fix

#9624 pocl: make sure we use easybuild Clang
  easybuild/easyconfigs/p/pocl/pocl-1.2-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/p/pocl/pocl-1.3-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/p/pocl/pocl-1.4-GCC-8.3.0.eb
  easybuild/easyconfigs/p/pocl/pocl-1.4-gcccuda-2019b.eb
Labels: bug fix

#9638 use latest master as release candidate of MRtrix 3.0 (since 3.0_RC4 is not an official release)
  easybuild/easyconfigs/m/MRtrix/MRtrix-3.0-rc-20191217-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/m/MRtrix/MRtrix-3.0-rc-20191217-foss-2019b-Python-3.7.4.eb
Labels: bug fix, change

#9632 [libsodium] Update source_urls to include old releases folder
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.11-foss-2016b.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.11-intel-2016b.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.12-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.12-intel-2017a.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.13-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.13-foss-2017a.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.16-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.16-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.17-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.6-intel-2016a.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.8-foss-2016a.eb
Labels: bug fix

#9635 [libxc] Update URLs to new location
  easybuild/easyconfigs/l/libxc/libxc-2.2.2-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.3-foss-2016b.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2016a.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2016b.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2017b.eb
  easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.0-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.0-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2016a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2016b.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2017a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2017b.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-foss-2016b.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-foss-2017a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-foss-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-foss-2018b.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-gimkl-2017a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-intel-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-intel-2018b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.0.1-foss-2017b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.0.1-intel-2017b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.0.3-foss-2016b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.0.3-foss-2017a.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-foss-2017b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-foss-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-foss-2018b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-gimkl-2017a.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-intel-2018a.eb
  easybuild/easyconfigs/l/libxc/libxc-4.2.3-intel-2018b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: bug fix

#9631 {bio}[foss-2019a]Mothur-1.43.0
  easybuild/easyconfigs/m/Mothur/Mothur-1.43.0-foss-2019a-Python-3.7.2.eb
Labels: update

#9648 {bio}[foss/2019a] gradunwarp v1.1.0 w/ Python 3.7.2
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.1.0-foss-2019a-HCP-Python-3.7.2.eb
Labels: update

#9519 {lang}[foss/2019b and fosscuda/2019b] R v3.6.2
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.50-GCCcore-8.3.0.eb
  easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.9-5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LittleCMS/LittleCMS-2.9-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: update

#9650 Fix tesseract 4.1.0 dependencies
  easybuild/easyconfigs/t/tesseract/tesseract-4.1.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/t/tesseract/tesseract-4.1.0-add-glib-dependency.patch
Labels: bug fix

#9649 fix Python 3.5.1 easyconfig (bitstring 3.1.3 sources no longer available on PyPI)
  easybuild/easyconfigs/p/Python/Python-3.5.1-foss-2016a.eb
Labels: bug fix

#9652 {lib}[GCCcore/8.2.0-8.3.0] ICU 64.2 - Depend on Python3 instead of 2
  easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.3.0.eb
Labels: bug fix

#9642 {vis}[foss/2019b] GTS v0.7.6
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-foss-2019b.eb
Labels: update

#9425 {numlib}[system/system] cuDNN v7.6.4.38
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.6.4.38-CUDA-10.0.130.eb
Labels: update

#9628 Make postinstallcmds independent of PWD in OpenCV 3.1.0 easyconfigs
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016b.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016b.eb
Labels: bug fix

#9647 [QCA 2.1.0] Update source URLs as old ones are not available anymore
  easybuild/easyconfigs/q/QCA/QCA-2.1.0-foss-2016a.eb
  easybuild/easyconfigs/q/QCA/QCA-2.1.0-intel-2016b.eb
Labels: bug fix

#9655 {tools}[GCCcore/8.2.0] tcsh 6.22.02
  easybuild/easyconfigs/t/tcsh/tcsh-6.22.02-GCCcore-8.2.0.eb
Labels: update

#9636 {mpi}[GCC/9.2.0-2.32] OpenMPI v4.0.2
  easybuild/easyconfigs/h/hwloc/hwloc-2.1.0-GCCcore-9.2.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.16-GCCcore-9.2.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.13-GCCcore-9.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-GCC-9.2.0-2.32.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-9.2.0.eb
Labels: update

#9658 {devel}[GCCcore/8.2.0] Autoconf-archive v2019.01.06
  easybuild/easyconfigs/a/Autoconf-archive/Autoconf-archive-2019.01.06-GCC-8.2.0-2.31.1.eb
Labels: new

#9641 PyCharm 2019.3.1 easyconfig
  easybuild/easyconfigs/p/PyCharm/PyCharm-2019.3.1.eb
Labels: update

#9633 fix source URLs for ant v1.10.5 - v1.10.7
  easybuild/easyconfigs/a/ant/ant-1.10.2-fix-doclint-error.patch
  easybuild/easyconfigs/a/ant/ant-1.10.5-Java-1.8.eb
  easybuild/easyconfigs/a/ant/ant-1.10.6-Java-1.8.eb
  easybuild/easyconfigs/a/ant/ant-1.10.7-Java-11.eb
Labels: bug fix

#9674 {math}[intel/2019b] SUNDIALS v5.1.0
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.1.0-intel-2019b.eb
Labels: update

#9683 remove gradunwarp easyconfig with Python 3 (since it needs a patch)
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.1.0-foss-2019a-HCP-Python-3.7.2.eb
Labels: change

#9646 {lib}[fosscuda/2019b] TensorFlow v2.1.0 + pybind11 v2.4.3 w/ Python 3.7.4
  easybuild/easyconfigs/p/pybind11/pybind11-2.4.3-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-build-tf-lite-avx512.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-cuda-build.patch
  easybuild/easyconfigs/t/TensorFlow/scipy-1.4.1-fix-pthread.patch
Labels: update

#9682 {lang}[GCCcore/8.2.0] units v2.19
  easybuild/easyconfigs/u/units/units-2.19-GCCcore-8.2.0.eb
Labels: new

#9687 fix pyfits easyconfig by adding missing d2to1 extension
  easybuild/easyconfigs/p/pyfits/pyfits-3.5-intel-2018b-Python-2.7.15.eb
Labels: bug fix

#9681 update release notes for EasyBuild v4.1.1
  RELEASE_NOTES
  setup.py
Labels: update

#9691 {tools}[dummy/dummy] EasyBuild v4.1.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.1.1.eb
Labels: update

#9697 sync develop with master and bump version to 4.1.2dev
  RELEASE_NOTES
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.1.0-foss-2019a-HCP-Python-3.7.2.eb
  easybuild/easyconfigs/p/pyfits/pyfits-3.5-intel-2018b-Python-2.7.15.eb
  setup.py
Labels: update

#9696 {math}[foss/2018b] dtcwt v0.12.0 w/ Python 2.7.15
  easybuild/easyconfigs/d/dtcwt/dtcwt-0.12.0-foss-2018b-Python-2.7.15.eb
Labels: new

#9695 {math}[intel/2019b] dtcwt v0.12.0 w/ Python 3.7.4
  easybuild/easyconfigs/d/dtcwt/dtcwt-0.12.0-intel-2019b-Python-3.7.4.eb
Labels: new

#9672 {bio}[intel/2019b] CheckM v1.1.2, DendroPy v4.4.0 w/ Python 3.7.4
  easybuild/easyconfigs/c/CheckM/CheckM-1.1.2-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.4.0-GCCcore-8.3.0.eb
Labels: update

#9673 {bio}[intel/2019b] GTDB-Tk v1.0.2 w/ Python 3.7.4 + FastANI v1.3, FastTree v2.1.11
  easybuild/easyconfigs/f/FastANI/FastANI-1.3-iccifort-2019.5.281.eb
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.11-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-1.0.2-intel-2019b-Python-3.7.4.eb
Labels: update

#9701 add alternate checksum for OpenMolcas 18.09
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-18.09-intel-2018b-Python-3.6.6.eb
Labels: bug fix

#9702 use Github to download releases for MariaDB-connector-c
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.4-intel-2017b.eb
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-intel-2018a.eb
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-iomkl-2018a.eb
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.7-GCCcore-8.2.0.eb
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.7-foss-2018b.eb
Labels: bug fix, change

#9699 {vis}[foss/2019b] matplotlib v2.2.4 w/ Python 2.7.16
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.16-GCCcore-8.3.0.eb
Labels: update

#9693 {bio,lib}[GCCcore/8.2.0] dcm2niix v1.0.20190902, CharLS v2.1.0
  easybuild/easyconfigs/c/CharLS/CharLS-2.1.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/d/dcm2niix/dcm2niix-1.0.20190902-GCCcore-8.2.0.eb
Labels: update

#9685 {lang}[foss/2019a, intel/2019a, fosscuda/2019a, foss/2019b, fosscuda/2019b] Add R package HiddenMarkov to R v3.6.0 + v3.6.2
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: enhancement

#9617 {devel}[GCCcore/8.3.0] GObject-Introspection v1.63.1 w/ Python 3.7.4
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.63.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9713 {bio}[foss/2019b] LASTZ v1.04.03
  easybuild/easyconfigs/l/LASTZ/LASTZ-1.04.03-foss-2019b.eb
  easybuild/easyconfigs/l/LASTZ/LASTZ-1.04.03_Makefile.patch
Labels: update

#9708 {bio}[foss/2019b] Biopython v1.75 w/ Python 2.7.16
  easybuild/easyconfigs/b/Biopython/Biopython-1.75-foss-2019b-Python-2.7.16.eb
Labels: update

#9726 {vis}[GCCcore/8.3.0] HarfBuzz v2.6.4
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.6.4-GCCcore-8.3.0.eb
Labels: update

#9734 {vis}[GCCcore/8.3.0] Pango v1.44.7
  easybuild/easyconfigs/p/Pango/Pango-1.44.7-GCCcore-8.3.0.eb
Labels: update

#9716 {bio}[GCC/8.3.0] SAMtools v1.10
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.10-GCC-8.3.0.eb
Labels: update

#9670 {bio}[foss/2019b] GROMACS v2020
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020-foss-2019b.eb
Labels: update

#9677 {bio}[fosscuda/2019b] GROMACS v2020
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020-fosscuda-2019b.eb
Labels: update

#9746 {tools}[foss/2019b] JupyterLab v1.2.5 w/ Python 3.7.4
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-1.2.5-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-1.2.5_set-app-path-for-easybuild.patch
Labels: new

#9747 {data,tools}[foss/2019b] ITK v5.0.1, SimpleITK v1.2.4 w/ Python 3.7.4
  easybuild/easyconfigs/i/ITK/ITK-5.0.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/l/Lua/Lua-5.1.5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/SimpleITK/SimpleITK-1.2.4-foss-2019b-Python-3.7.4.eb
Labels: update

#9707 {bio}[foss/2019b] ABySS v2.1.5
  easybuild/easyconfigs/a/ABySS/ABySS-2.1.5-foss-2019b.eb
  easybuild/easyconfigs/s/sparsehash/sparsehash-2.0.3-GCCcore-8.3.0.eb
Labels: update

#9709 {bio}[system/system] picard v2.21.6
  easybuild/easyconfigs/p/picard/picard-2.21.6-Java-11.eb
Labels: update

#9710 {bio}[foss/2019b] BCFtools v1.10.2
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.10.2-foss-2019b.eb
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.10.2-GCC-8.3.0.eb
Labels: update

#9712 {bio}[system/system] FastQC v0.11.9
  easybuild/easyconfigs/f/FastQC/FastQC-0.11.9-Java-11.eb
Labels: update

#9714 {bio}[GCC/8.3.0] MAFFT v7.453
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.453-GCC-8.3.0-with-extensions.eb
Labels: update

#9715 {bio}[GCC/8.3.0] MUSCLE v3.8.1551
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.1551-GCC-8.3.0.eb
Labels: update

#9711 {bio}[GCC/8.3.0] EMBOSS v6.6.0
  easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-GCC-8.3.0-Java-11.eb
  easybuild/easyconfigs/l/libharu/libharu-2.3.0-GCCcore-8.3.0.eb
Labels: update

#9719 {bio}[GCC/8.3.0] Trinity v2.8.5
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.2.3-GCC-8.3.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.5.1-GCC-8.3.0.eb
  easybuild/easyconfigs/t/Trinity/Trinity-2.8.5-GCC-8.3.0-Java-11.eb
Labels: update

#9718 {bio}[system/system] Trimmomatic v0.39
  easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.39-Java-11.eb
Labels: update

#9717 {bio}[GCC/8.3.0] seqtk v1.3
  easybuild/easyconfigs/s/seqtk/seqtk-1.3-GCC-8.3.0.eb
Labels: update

#9720 {bio}[GCC/8.3.0] BWA v0.7.17
  easybuild/easyconfigs/b/BWA/BWA-0.7.17-GCC-8.3.0.eb
Labels: update

#9721 {bio}[foss/2019b] SECAPR v1.1.15 w/ Python 2.7.16
  easybuild/easyconfigs/s/SECAPR/SECAPR-1.1.15-foss-2019b-Python-2.7.16.eb
Labels: new

#9723 {bio}[GCCcore/8.3.0] GATK v4.1.4.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/g/GATK/GATK-4.1.4.1-GCCcore-8.3.0-Java-11.eb
Labels: update

#9722 {bio}[GCC/8.3.0] VCFtools v0.1.16
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-GCC-8.3.0.eb
Labels: update

#9748 {bio}[foss/2019b] MedPy v0.4.0 w/ Python 3.7.4
  easybuild/easyconfigs/m/MedPy/MedPy-0.4.0-foss-2019b-Python-3.7.4.eb
Labels: new

#9784 stick to http:// source URLS for ISL in GCCcore easyconfigs, since https:// doesn't work
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#9783 {bio}[GCC/8.2.0-2.31.1] SPAdes v3.14.0 w/ Python 3.7.2
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.14.0-GCC-8.2.0-2.31.1-Python-3.7.2.eb
Labels: update

#9770 {math}[intel/2019b] statsmodels v0.11.0 w/ Python 3.7.4
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.11.0-intel-2019b-Python-3.7.4.eb
Labels: update

#9757 {bio}[iccifort/2019.5.281] Stacks v2.5
  easybuild/easyconfigs/s/Stacks/Stacks-2.5-iccifort-2019.5.281.eb
Labels: update

#9753 {data}[foss/2019b] ANTs v2.3.2 w/ Python 3.7.4
  easybuild/easyconfigs/a/ANTs/ANTs-2.3.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/ANTs/ANTs-2.3.2_fix-antsRegistration-iterations.patch
  easybuild/easyconfigs/a/ANTs/ANTs-2.3.2_fix-undefined-versions.patch
Labels: update

#9776 {tools}[GCCcore/8.3.0] pigz v2.4
  easybuild/easyconfigs/p/pigz/pigz-2.4-GCCcore-8.3.0.eb
Labels: update

#9772 {lang}[GCCcore/8.3.0] Lua v5.3.5
  easybuild/easyconfigs/l/Lua/Lua-5.3.5-GCCcore-8.3.0.eb
Labels: update

#9626 New EB files for autopep8 and pycodestyle for Python/3.6.4-intel-2018a
  easybuild/easyconfigs/a/autopep8/autopep8-1.4.4-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/pycodestyle/pycodestyle-2.5.0-intel-2018a-Python-3.6.4.eb
Labels: new

#9785 {tools}[GCCcore/7.3.0, GCCcore/8.2.0, GCCcore/8.3.0] Ghostscript: build shared libs and install header files
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.23-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.27-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.50-GCCcore-8.3.0.eb
Labels: enhancement

#9775 {bio}[GCCcore/8.3.0] cutadapt v1.18, cutadapt v2.7 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.18-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.7-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9779 {chem}[foss/2018b,intel/2018b] ASE v3.19.0 w/ Python 3.6.6
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-intel-2018b-Python-3.6.6.eb
Labels: update

#9786 {chem}[foss/2019b,intel/2019b] ASE v3.19.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/ASE/ASE-3.19.0-intel-2019b-Python-3.7.4.eb
Labels: update

#9777 {bio}[GCCcore/8.3.0] Trim_Galore v0.6.5 w/ Python 3.7.4
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.5-GCCcore-8.3.0-Java-11-Python-3.7.4.eb
Labels: update

#9789 add alternative checksums for farver/fracdiff/pkgmaker/rngtools/doRNG/cobs extensions in R 3.6.2 easyconfigs
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: bug fix

#9763 {lib}[foss/2018b,intel/2018b] tqdm v4.41.1 w/ Python 3.6.6
  easybuild/easyconfigs/t/tqdm/tqdm-4.41.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.41.1-intel-2018b-Python-3.6.6.eb
Labels: update

#9768 {bio}[GCC/8.3.0] STAR v2.7.3a
  easybuild/easyconfigs/s/STAR/STAR-2.7.3a-GCC-8.3.0.eb
Labels: update

#9769 {devel}[gompic/2019b] Boost v1.71.0
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-gompic-2019b.eb
Labels: update

#9756 {tools}[foss/2018b,foss/2019a] networkx v2.2 w/ Python 2.7.15
  easybuild/easyconfigs/n/networkx/networkx-2.2-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/n/networkx/networkx-2.2-foss-2019a-Python-2.7.15.eb
Labels: update

#9737 {vis}[GCCcore/8.3.0] gnuplot v5.2.8
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.8-GCCcore-8.3.0.eb
Labels: update

#9745 {geo}[foss/2019b] GDAL v3.0.2, GEOS v3.8.0, rgdal v1.4-8, ... w/ Python 3.7.4
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.8.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/rgdal/rgdal-1.4-8-foss-2019b-R-3.6.2.eb
  easybuild/easyconfigs/r/rgeos/rgeos-0.5-2-foss-2019b-R-3.6.2.eb
Labels: update

#9736 {bio}[foss/2018b,foss/2019a] stpipeline v1.7.3, stpipeline v1.7.6 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/s/stpipeline/stpipeline-1.7.3-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/stpipeline/stpipeline-1.7.6-foss-2019a-Python-3.7.2.eb
Labels: new

#9733 {math}[GCCcore/8.3.0] Qhull v2019.1
  easybuild/easyconfigs/q/Qhull/Qhull-2019.1-GCCcore-8.3.0.eb
Labels: update

#9732 {numlib}[GCCcore/8.3.0] qrupdate v1.1.2
  easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCCcore-8.3.0.eb
Labels: update

#9731 {vis}[foss/2019b] GraphicsMagick v1.3.34
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.34-foss-2019b.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick_pkgconfig_libtiff.patch
Labels: update

#9724 {numlib}[foss/2019b] Hypre v2.18.2
  easybuild/easyconfigs/h/Hypre/Hypre-2.18.2-foss-2019b.eb
Labels: update

#9704 {math}[foss/2019b] python-weka-wrapper3 v0.1.11 w/ Python 3.7.4
  easybuild/easyconfigs/p/python-weka-wrapper3/python-weka-wrapper3-0.1.11-foss-2019b-Python-3.7.4.eb
Labels: new

#9688 {bio}[GCC/8.2.0-2.31.1] Structure v2.3.4
  easybuild/easyconfigs/s/Structure/Structure-2.3.4-GCC-8.2.0-2.31.1.eb
Labels: update

#9760 {tools}[GCCcore/8.3.0] awscli v1.17.7 w/ Python 3.7.4
  easybuild/easyconfigs/a/awscli/awscli-1.17.7-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9684 {math}[foss/2019a] JAGS v4.3.0, rjags v4-9
  easybuild/easyconfigs/j/JAGS/JAGS-4.3.0-foss-2019a.eb
  easybuild/easyconfigs/r/rjags/rjags-4-9-foss-2019a-R-3.6.0.eb
Labels: update

#9794 {math}[GCCcore/8.3.0] Gurobi v9.0.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.0-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9728 {vis}[GCCcore/8.3.0] GL2PS v1.4.0
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.0-GCCcore-8.3.0.eb
Labels: update

#9686 {bio}[foss/2019a] inferCNV v1.0.4 w/ Python 3.7.2
  easybuild/easyconfigs/i/inferCNV/inferCNV-1.0.4-foss-2019a-Python-3.7.2-R-3.6.0.eb
Labels: new

#9787 {vis}[GCCcore/8.3.0] Gdk-Pixbuf v2.38.2
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.2-GCCcore-8.3.0.eb
Labels: update

#9767 {math}[foss/2019b] spatialreg v1.1-5
  easybuild/easyconfigs/s/spatialreg/spatialreg-1.1-5-foss-2019b-R-3.6.2.eb
Labels: new

#9727 {tools}[GCCcore/8.3.0] GLPK v4.65
  easybuild/easyconfigs/g/GLPK/GLPK-4.65-GCCcore-8.3.0.eb
Labels: update

#9700 {bio}[intel/2019b] LAST v1045
  easybuild/easyconfigs/l/LAST/LAST-1045-intel-2019b.eb
Labels: update

#9806 {devel}[system/system] ReFrame v2.21
  easybuild/easyconfigs/r/ReFrame/ReFrame-2.21.eb
Labels: update

#9796 {numlib}[foss/2019b] PETSc v3.12.3
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.3-foss-2019b.eb
Labels: update

#9808 {devel}[system/system] Gradle v6.1.1
  easybuild/easyconfigs/g/Gradle/Gradle-6.1.1.eb
Labels: update

#9803 {lib}[GCCcore/8.3.0] tqdm v4.41.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/t/tqdm/tqdm-4.41.1-GCCcore-8.3.0.eb
Labels: update

#9804 {math}[foss/2019b] statsmodels v0.11.0 w/ Python 3.7.4
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.11.0-foss-2019b-Python-3.7.4.eb
Labels: update

#9802 {data,devel,lib,math}[GCCcore/8.3.0,foss/2019b] Blosc v1.17.1, LZO v2.10, numexpr v2.7.1, ... w/ Python 3.7.4
  easybuild/easyconfigs/b/Blosc/Blosc-1.17.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/numexpr/numexpr-2.7.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-fix-libs.patch
  easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-foss-2019b-Python-3.7.4.eb
Labels: update

#9812 {tools}[foss/2019b] IRkernel v1.1 w/ Python 3.7.4
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-foss-2019b-R-3.6.2-Python-3.7.4.eb
Labels: update

#9762 {lib}[intel/2018b,foss/2018b] scikit-build v0.10.0 w/ Python 3.6.6
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.10.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.10.0-intel-2018b-Python-3.6.6.eb
Labels: new
