Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-02, with the labels that each got.

#9816 {bio}[GCC/8.3.0] FastME v2.1.6.1
  easybuild/easyconfigs/f/FastME/FastME-2.1.6.1-GCC-8.3.0.eb
Labels: update

#9765 {vis}[intel/2018b] PyQtGraph v0.10.0, PyQt5 v5.11.3, Qt5 v5.10.1 w/ Python 3.6.6
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.11.3-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.10.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-intel-2018b.eb
Labels: update

#9705 {bio}[GCC/7.3.0-2.30] medaka v0.11.4 w/ Python 3.6.6
  easybuild/easyconfigs/m/medaka/medaka-0.11.4-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/medaka/medaka-0.11.4_use-SAMtools-dep.patch
  easybuild/easyconfigs/r/Racon/Racon-1.4.10-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/s/spoa/spoa-3.0.1-GCC-7.3.0-2.30.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#9782 {vis}[foss/2018b] Graphviz v2.40.1 w/ Python 2.7.15
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-foss-2018b.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_CVE-2018-10196.patch
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_CVE-2019-11023.patch
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1_coverity-scan-fixes.patch
Labels: update

#9811 {chem}[GCC/8.3.0,iccifort/2019.5.281] libxc v4.3.4
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.5.281.eb
Labels: update

#9815 {bio}[GCC/8.3.0] DIAMOND v0.9.30
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.30-GCC-8.3.0.eb
Labels: update

#9797 {bio}[GCC/8.3.0,foss/2018b] GenomeTools v1.5.10, GenomeTools v1.6.1 w/ Python 2.7.15 + 2.7.16
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.5.10-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.5.10-foss-2018b.eb
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.6.1-GCC-8.3.0-Python-2.7.16.eb
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.6.1-GCC-8.3.0.eb
Labels: new

#9817 {bio}[GCCcore/8.3.0] MCL v14.137
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-8.3.0.eb
Labels: update

#9818 {bio}[gompi/2019b] MMseqs2 v10-6d92c
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-10-6d92c-gompi-2019b.eb
Labels: update

#9824 {bio}[foss/2019a] Seurat v3.1.2
  easybuild/easyconfigs/s/Seurat/Seurat-3.1.2-foss-2019a-R-3.6.0.eb
Labels: update

#9831 {lib}[GCCcore/8.3.0] libepoxy v1.5.4
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.4-GCCcore-8.3.0.eb
Labels: update

#9371 Java 11.0.6 on ppc64le and alter the Java 11 wrapper to support both x86_64 and ppc64le
  easybuild/easyconfigs/j/Java/Java-11.0.6-ppc64le.eb
  easybuild/easyconfigs/j/Java/Java-11.eb
Labels: enhancement

#9829 {vis}[GCCcore/8.3.0] ATK v2.34.1, at-spi2-core v2.34.0, at-spi2-atk v2.34.1
  easybuild/easyconfigs/a/ATK/ATK-2.34.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.34.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.34.1_add-time-header-test.patch
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.34.0-GCCcore-8.3.0.eb
Labels: update

#9821 {bio}[GCCcore/8.3.0] gsport v1.4.2 w/ Python 3.7.4
  easybuild/easyconfigs/g/gsport/gsport-1.4.2-GCCcore-8.3.0-Python-3.7.4.eb
Labels: new

#9807 {bio}[intel/2019b] Flye v2.6 w/ Python 3.7.4
  easybuild/easyconfigs/f/Flye/Flye-2.6-intel-2019b-Python-3.7.4.eb
Labels: update

#9838 {bio}[foss/2018b] BUStools v0.40.0
  easybuild/easyconfigs/b/BUStools/BUStools-0.40.0-foss-2018b.eb
Labels: new

#9814 {math}[foss/2019b,intel/2019b] ELPA v2019.11.001
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-foss-2019b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-intel-2019b.eb
Labels: update

#9845 {bio}[GCCcore/8.3.0] cutadapt v2.8 w/ Python 3.7.4
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.8-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9844 {vis}[GCCcore/8.3.0] GTK+ v3.24.13
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.13-GCCcore-8.3.0.eb
Labels: enhancement, update

#9842 {vis} [GCCcore/8.3.0] HarfBuzz v2.6.4: downgrade dependency on ICU to 64.2
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.6.4-GCCcore-8.3.0.eb
Labels: bug fix

#7529 {math} [GCC/6.4.0-2.28, iccifort/2018.1.163-GCC-6.4.0-2.28] SLATEC v4.1
  easybuild/easyconfigs/s/SLATEC/SLATEC-4.1-GCC-6.4.0-2.28.eb
  easybuild/easyconfigs/s/SLATEC/SLATEC-4.1-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
Labels: new

#9836 {bio}[iccifort/2018.3.222-GCC-7.3.0-2.30] ntEdit v1.3.1
  easybuild/easyconfigs/n/ntEdit/ntEdit-1.3.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/n/ntEdit/ntEdit-1.3.1_fix_Makefile_to_take_CXXFLAGS_from_eb.patch
Labels: new

#9833 {bio}[iccifort/2018.3.222-GCC-7.3.0-2.30] ntHits v0.0.1
  easybuild/easyconfigs/n/ntHits/ntHits-0.0.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/n/ntHits/ntHits-0.0.1_fix_broken_configure.ac.patch
Labels: new

#9809 {devel}[system/system] Groovy v2.5.9
  easybuild/easyconfigs/g/Groovy/Groovy-2.5.9-Java-11.eb
Labels: new

#9853 add lmerTest extension to R 3.6.2 easyconfigs
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: enhancement

#9852 {numlib}[GCC/9.2.0] OpenBLAS v0.3.8
  easybuild/easyconfigs/g/GCC/GCC-9.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.2.0.eb
Labels: update

#9851 {vis}[GCCcore/8.2.0] OpenSlide v3.4.1: use Autotools and simplify preconfigopts
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1-GCCcore-8.2.0.eb
Labels: code cleanup

#9849 {data}[gompi/2019b] netCDF-Fortran v4.5.2
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompi-2019b.eb
Labels: update

#9780 {chem}[foss/2019b,intel/2019b] kim-api v2.1.3, openkim-models v20190725
  easybuild/easyconfigs/k/kim-api/kim-api-2.1.3-foss-2019b.eb
  easybuild/easyconfigs/k/kim-api/kim-api-2.1.3-intel-2019b.eb
  easybuild/easyconfigs/o/openkim-models/openkim-models-20190725-foss-2019b.eb
  easybuild/easyconfigs/o/openkim-models/openkim-models-20190725-intel-2019b.eb
Labels: update

#9761 {bio}[GCCcore/8.3.0] canu v1.9
  easybuild/easyconfigs/c/canu/canu-1.9-GCCcore-8.3.0-Java-11.eb
Labels: update

#9834 {chem}[foss/2019b,intel/2019b] GPAW v20.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Add-Easybuild-configuration-files.patch
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Wrap-pragma-omp-simd-in-ifdef-_OPENMP-blocks.patch
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/l/libvdwxc/libvdwxc-0.4.0-foss-2019b.eb
Labels: update

#9825 {bio}[foss/2019a] Monocle3 v0.2.0 w/ Python 3.7.2
  easybuild/easyconfigs/m/Monocle3/Monocle3-0.2.0-foss-2019a-Python-3.7.2-R-3.6.0.eb
Labels: new

#7934 {tools}[system] rclone v1.42
  easybuild/easyconfigs/r/rclone/rclone-1.42-amd64.eb
Labels: new

#9820 {bio}[foss/2019b] OrthoFinder v2.3.8 w/ Python 2.7.16
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.3.8-foss-2019b-Python-2.7.16.eb
Labels: update

#9850 {bio,lib}[GCC/8.3.0,GCCcore/8.3.0] argtable v2.13, Clustal-Omega v1.2.4
  easybuild/easyconfigs/a/argtable/argtable-2.13-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/Clustal-Omega/Clustal-Omega-1.2.4-GCC-8.3.0.eb
Labels: update

#9750 {vis}[fosscuda/2019b] matplotlib v3.1.1 w/ Python 3.7.4
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.1.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9822 {data}[fosscuda/2019b] scikit-learn v0.21.3 w/ Python 3.7.4
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.21.3-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9828 {data,tools,vis}[fosscuda/2019b] scikit-image v0.16.2, dask v2.8.0, bokeh v1.4.0 w/ Python 3.7.4
  easybuild/easyconfigs/b/bokeh/bokeh-1.4.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/d/dask/dask-2.8.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.16.2-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9751 {tools}[fosscuda/2019b] IPython v7.9.0 w/ Python 3.7.4
  easybuild/easyconfigs/i/IPython/IPython-7.9.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9752 {tools}[fosscuda/2019b] JupyterLab v1.2.5 w/ Python 3.7.4
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-1.2.5-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9867 OpenBLAS 0.3.8: Fix inline asm in dscal: mark x, x1 as clobbered.
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8_fix-dscal-inline-asm.patch
Labels: bug fix

#9832 {vis}[foss/2019a,intel/2019a] Grace v5.1.25, motif v2.3.8
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2019a-5build1.eb
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2019a-5build1.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2019a.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-intel-2019a.eb
Labels: update

#9874 {numlib}[foss/2019b,intel/2019b] PETSc v3.12.4, SLEPc v3.12.2
  easybuild/easyconfigs/h/Hypre/Hypre-2.18.2-intel-2019b.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-foss-2019b.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-intel-2019b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.12.2-foss-2019b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.12.2-intel-2019b.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.6.0-intel-2019b-METIS-5.1.0.eb
Labels: update

#9873 {bio,lang}[intel/2019b] FALCON v1.8.8, SciPy-bundle v2019.10 w/ Python 2.7.16
  easybuild/easyconfigs/f/FALCON/FALCON-1.8.8-intel-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-intel-2019b-Python-2.7.16.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#9855 {phys}[foss/2019b,intel/2019b] BerkeleyGW v2.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.1.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.1.0_missing_file.patch
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-2.1.0_tests.patch
Labels: update

#9869 {bio}[GCCcore/8.3.0] cutadapt v1.18, cutadapt v2.7: add missing sanity_check_commands
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.18-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.7-GCCcore-8.3.0-Python-3.7.4.eb
Labels: bug fix

#9875 don't overwrite configopts in BLAST+ easyconfigs, append to it
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-intel-2018a.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-intel-2018b.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0-iimpi-2019a.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0_fix-64-icc.patch
Labels: bug fix

#9871 use custom easyblock for installing CMake in easyconfig for CMake 3.15.3
  easybuild/easyconfigs/c/CMake/CMake-3.15.3-GCCcore-8.3.0.eb
Labels: change

#9885 {chem}[iccifort/2019.5.281] aNCI v2.0
  easybuild/easyconfigs/a/aNCI/aNCI-2.0-iccifort-2019.5.281.eb
Labels: new

#9880 add MUMPS to PETSc
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.2.1-foss-2019b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.2.1-intel-2019b-metis.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-foss-2019b.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-intel-2019b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#9795 {bio}[intel/2019b] OrthoFinder 2.3.11 (+ deps) w/ Python 3.7.4
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0-iimpi-2019b.eb
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.30-iccifort-2019.5.281.eb
  easybuild/easyconfigs/f/FastME/FastME-2.1.6.1-iccifort-2019.5.281.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-10-6d92c-iimpi-2019b.eb
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.3.11-intel-2019b-Python-3.7.4.eb
Labels: update

#9879 add alternate checksum for LaplacesDemon in R 3.6.2 easyconfigs
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: bug fix

#9856 {bio}[intel/2019a] Red v2015-05-22
  easybuild/easyconfigs/r/Red/Red-2015-05-22-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Labels: new

#9805 {bio,compiler,lang}[foss/2019b] scVelo v0.1.24, numba v0.47.0, LLVM v8.0.1 w/ Python 3.7.4
  easybuild/easyconfigs/l/LLVM/LLVM-8.0.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/numba/llvmlite-0.31.0_fix-ffi-Makefile.patch
  easybuild/easyconfigs/n/numba/numba-0.47.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/scVelo/scVelo-0.1.24-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/scVelo/scanpy-1.4.5.post2_fix_h5py_version.patch
  easybuild/easyconfigs/s/scVelo/scanpy-1.4.5.post2_fix_matplotlib_version.patch
  test/easyconfigs/easyconfigs.py
Labels: new, update

#9895 fix redefining of preconfigopts in OpenCV easyconfigs
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016b.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017b-Python-3.6.3.eb
Labels: bug fix

#9891 add back direct dependency on METIS in PETSc 3.12.4 easyconfigs
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-foss-2019b.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-intel-2019b.eb
Labels: bug fix

#9866 binutils: Revert removal of AVX512 vmovd with 64-bit operands
  easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-9.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-9.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.32-readd-avx512-vmovd.patch
  easybuild/easyconfigs/b/binutils/binutils-2.32.eb
Labels: bug fix

#9876 check for redefined easyconfig parameters in easyconfig tests
  easybuild/easyconfigs/c/Caffe/Caffe-1.0-intel-2017b-CUDA-9.1.85-Python-2.7.14.eb
  easybuild/easyconfigs/g/Glade/Glade-3.8.6-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.3.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.1.0.eb
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.1.14-foss-2016a.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/o/opencv_contrib/opencv_contrib-3.4.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/p/picard/picard-2.6.0-Java-1.8.0_131.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix, enhancement

#9865 add patch for OpenBLAS 0.3.4 w/ GCC/8.2.0-2.31.1 to fix broken tests
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.4_disable_AVX512_dgemm_kernel.patch
Labels: bug fix

#9870 {cae,numlib,vis}[intel/2019b] OpenFOAM v1912, CGAL v4.14.1, ParaView v5.6.2 w/ Python 3.7.4
  easybuild/easyconfigs/c/CGAL/CGAL-4.14.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1912-intel-2019b.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.6.2-intel-2019b-Python-3.7.4-mpi.eb
Labels: update

#9857 {math}[intel/2019b] ELSI v2.5.0
  easybuild/easyconfigs/e/ELSI/ELSI-2.5.0-intel-2019b-PEXSI.eb
  easybuild/easyconfigs/e/ELSI/ELSI-2.5.0-intel-2019b.eb
Labels: new

#9840 {chem}[intel/2019a] QuantumESPRESSO v6.5
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-intel-2019a.eb
Labels: update

#9898 {tools}[GCCcore/8.3.0] archspec v0.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/archspec/archspec-0.1.0-GCCcore-8.3.0-Python-3.7.4.eb
Labels: new

#9890 {vis}[foss/2019b] matplotlib v2.2.5 w/ Python 2.7.16
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.5-foss-2019b-Python-2.7.16.eb
Labels: update

#9882 {bio}[gompi/2019b] Kaiju v1.7.3 w/ Python 3.7.4
  easybuild/easyconfigs/k/Kaiju/Kaiju-1.7.3-gompi-2019b-Python-3.7.4.eb
Labels: update

#9915 fix NCIPLOT build flags
  easybuild/easyconfigs/n/NCIPLOT/NCIPLOT-4.0-20190718-iccifort-2019.5.281.eb
Labels: bug fix

#9799 {math}[foss/2019b] Octave v5.1.0
  easybuild/easyconfigs/o/Octave/Octave-5.1.0-foss-2019b.eb
Labels: update

#9758 {lang}[foss/2019b and fosscuda/2019b] R v3.6.2, added rstan as a core package.
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: update

#9907 {devel}[GCCcore/9.2.0] pkg-config v0.29.2
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-9.2.0.eb
Labels: update

#9912 ncurses-6.1: Use symlinks for terminfo files instead of hard links.
  easybuild/easyconfigs/n/ncurses/ncurses-6.1.eb
Labels: bug fix, change

#9913 {devel}[GCCcore/9.2.0,system/system] ncurses v6.2
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-9.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2.eb
Labels: update

#9905 {data}[foss/2019b] SVG v2.84
  easybuild/easyconfigs/s/SVG/SVG-2.84-foss-2019b-Perl-5.30.0.eb
Labels: new

#9877 {lib}[GCCcore/7.2.0,GCCcore/7.3.0] PMIx v2.2.1, PMIx v2.2.3
  easybuild/easyconfigs/l/libevent/libevent-2.1.11-GCCcore-7.2.0.eb
  easybuild/easyconfigs/l/libevent/libevent-2.1.11-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libevent/libevent-2.1.8-GCCcore-7.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.1.3-GCCcore-7.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.2.1-GCCcore-7.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.2.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.2.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.2.1_fix-PMIX_SYSTEM_EVENT-typo.patch
  easybuild/easyconfigs/p/PMIx/PMIx-2.2.3-GCCcore-7.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-2.2.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-7.2.0.eb
Labels: update

#9868 {vis}[GCCcore/8.3.0] XCrySDen v1.6.2, Togl v2.0, bwidget v1.9.14
  easybuild/easyconfigs/b/bwidget/bwidget-1.9.14-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/Togl/Togl-2.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/Togl/Togl-2.0_configure.patch
  easybuild/easyconfigs/t/Togl/Togl-2.0_decl.patch
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2-foss-2019b.eb
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2-intel-2019b.eb
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2_no-bwidget.patch
Labels: new, update

#9908 {lib}[GCCcore/9.2.0] libevent v2.1.11
  easybuild/easyconfigs/l/libevent/libevent-2.1.11-GCCcore-9.2.0.eb
Labels: update

#9906 candidate definition for foss/2020a common toolchain (rc1)
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020a-rc1.eb
  easybuild/easyconfigs/f/foss/foss-2020a-rc1.eb
  easybuild/easyconfigs/g/gompi/gompi-2020a-rc1.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2020a-rc1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3rc3-GCC-9.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a-rc1.eb
Labels: update

#9910 {lib}[GCCcore/9.2.0] UCX v1.7.0
  easybuild/easyconfigs/u/UCX/UCX-1.7.0-GCCcore-9.2.0.eb
Labels: update

#9918 add missing patch to iccifort libxc easyconfigs
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.5.281.eb
Labels: bug fix

#9888 {lib}[foss/2018b] pyFFTW v0.11.1 w/ Python 3.6.6
  easybuild/easyconfigs/p/pyFFTW/pyFFTW-0.11.1-foss-2018b-Python-3.6.6.eb
Labels: update

#9897 {bio}[GCC/8.3.0] BayeScEnv v1.1
  easybuild/easyconfigs/b/BayeScEnv/BayeScEnv-1.1-GCC-8.3.0.eb
Labels: update

#9889 {math}[intel/2018b] LMfit v0.9.14 w/ Python 2.7.15
  easybuild/easyconfigs/l/LMfit/LMfit-0.9.14-intel-2018b-Python-2.7.15.eb
Labels: update

#9858 {chem}[intel/2019b] Siesta v4.1-MaX-1.0
  easybuild/easyconfigs/l/libGridXC/libGridXC-0.8.5-iimpi-2019b.eb
  easybuild/easyconfigs/l/libPSML/libPSML-1.1.8-iccifort-2019.5.281.eb
  easybuild/easyconfigs/s/Siesta/Siesta-4.1-MaX-1.0-intel-2019b-PEXSI.eb
  easybuild/easyconfigs/s/Siesta/Siesta-4.1-MaX-1.0-intel-2019b.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.4-iccifort-2019.5.281.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#9887 {lib}[intel/2018b] mkl_fft v1.0.14 w/ Python 3.6.6
  easybuild/easyconfigs/m/mkl_fft/mkl_fft-1.0.14-intel-2018b-Python-3.6.6.eb
Labels: new

#9926 use M4-1.4.18.eb for test installation in easyconfigs test suite
  .github/workflows/unit_tests.yml
  .travis.yml
Labels: change

#9921 {tools}[GCCcore/8.3.0] gzip v1.10
  easybuild/easyconfigs/g/gzip/gzip-1.10-GCCcore-8.3.0.eb
Labels: update

#9925 use checkout@v2 in GitHub Actions to fix broken re-triggered tests
  .github/workflows/unit_tests.yml
Labels: bug fix

#9896 {chem}[foss/2019b] GRASP v2018
  easybuild/easyconfigs/g/GRASP/GRASP-2018-foss-2019b.eb
Labels: new

#9894 {bio}[GCCcore/8.2.0] fastq-pair v1.0
  easybuild/easyconfigs/f/fastq-pair/fastq-pair-1.0-GCCcore-8.2.0.eb
Labels: new

#9899 {vis}[foss/2019b] pydot v1.4.1 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/p/pydot/pydot-1.4.1-foss-2019b.eb
Labels: new

#9881 {bio}[gompi/2019b] Kraken2 v2.0.8-beta
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.8-beta-gompi-2019b-Perl-5.30.0.eb
Labels: update

#9860 {debugger}[GCCcore/8.3.0] GDB v9.1 w/ Python 3.7.4
  easybuild/easyconfigs/g/GDB/GDB-9.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#9930 {lib}[GCCcore/9.2.0] PMIx v3.1.5
  easybuild/easyconfigs/p/PMIx/PMIx-3.1.5-GCCcore-9.2.0.eb
Labels: update

#9929 add dat directory to aNCI
  easybuild/easyconfigs/a/aNCI/aNCI-2.0-iccifort-2019.5.281.eb
Labels: enhancement

#9933 {vis}[GCCcore/8.3.0] PyCairo v1.18.2 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.18.2-GCCcore-8.3.0.eb
Labels: update

#9931 {devel}[foss/2019b] PyTorch v1.4.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0_fix-missing-sleef_h.patch
Labels: update

#9883 {chem}[intel/2019b] LAMMPS v7Aug2019, Voro++ v0.4.6 w/ Python 3.7.4
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-intel-2019b.eb
Labels: new

#9922 {cae}[foss/2019b] ngspice v31
  easybuild/easyconfigs/n/ngspice/ngspice-31-foss-2019b.eb
Labels: new

#9884 {chem}[foss/2019b] LAMMPS v7Aug2019, Voro++ v0.4.6, molmod v1.4.5, ... w/ Python 3.7.4
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.5-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-foss-2019b.eb
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-foss-2019b-Python-3.7.4.eb
Labels: new

#9942 {tools}[GCCcore/8.3.0] DB v18.1.32
  easybuild/easyconfigs/d/DB/DB-18.1.32-GCCcore-8.3.0.eb
Labels: update

#9932 {devel}[fosscuda/2019b] PyTorch v1.4.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9940 {compiler}[system/system] Go v1.14
  easybuild/easyconfigs/g/Go/Go-1.14.eb
Labels: update

#9943 fix homepage and source URLs in SLEPc easyconfigs by using https
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.11.0-foss-2018b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.12.2-foss-2019b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.12.2-intel-2019b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.8.3-foss-2017b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.9.2-foss-2018a.eb
Labels: bug fix

#9936 re-enable building utils in Siesta 4.1-MaX-1.0 release
  easybuild/easyconfigs/s/Siesta/Siesta-4.1-MaX-1.0-intel-2019b-PEXSI.eb
  easybuild/easyconfigs/s/Siesta/Siesta-4.1-MaX-1.0-intel-2019b.eb
Labels: bug fix

#9945 {tools}[GCCcore/8.3.0] CppUnit v1.15.1
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-8.3.0.eb
Labels: update

#9941 {bio}[foss/2019b] PlasFlow v1.1.0, ncdf4 v1.17, rpy2 v3.2.6 w/ Python 3.7.4 + R-bundle-Bioconductor v3.10
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/ncdf4/ncdf4-1.17-foss-2019b.eb
  easybuild/easyconfigs/p/PlasFlow/PlasFlow-1.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.10-foss-2019b.eb
  easybuild/easyconfigs/r/rpy2/rpy2-3.2.6-foss-2019b-Python-3.7.4.eb
Labels: new, update

#9878 {chem,tools}[intel/2017b] Meson v0.53.1, xtb v6.2.2-hotfix w/ Python 3.6.3
  easybuild/easyconfigs/m/Meson/Meson-0.53.1-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/x/xtb/xtb-6.2.2-hotfix-intel-2017b-Python-3.6.3.eb
Labels: new, update
