Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-12, with the labels that each got.

#11792 disable broken numpy test in SciPy-bundle 2020.11 easyconfig using intel/2020b
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-intel-2020b.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.19.4_disable-broken-test.patch
Labels: bug fix

#11788 stick to http download URL in fetchMG easyconfig (https doesn't work)
  easybuild/easyconfigs/f/fetchMG/fetchMG-1.0-GCCcore-8.3.0.eb
Labels: bug fix

#11791 Rename Sumo to SUMO for consistency
  easybuild/easyconfigs/s/SUMO/SUMO-1.3.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: bug fix, change

#11563 {vis}[GCCcore/10.2.0] PyQt5 v5.15.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.1-GCCcore-10.2.0.eb
Labels: update

#11793 {data}[gompi/2020a,iimpi/2020a] PnetCDF v1.12.1
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.1-gompi-2020a.eb
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.1-iimpi-2020a.eb
Labels: update

#11780 {lang}[system/system] BCEL v6.5.0
  easybuild/easyconfigs/b/BCEL/BCEL-6.5.0-Java-1.8.eb
Labels: update

#11783 {lib}[GCCcore/9.3.0] elfutils v0.182, libmicrohttpd v0.9.71
  easybuild/easyconfigs/e/elfutils/elfutils-0.182-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libmicrohttpd/libmicrohttpd-0.9.71-GCCcore-9.3.0.eb
Labels: new

#11779 {geo}[system/system] WCT v4.6.0
  easybuild/easyconfigs/w/WCT/WCT-4.6.0-Java-11.eb
Labels: new

#11795 {tools}[GCCcore/9.3.0] DMTCP v2.6.0
  easybuild/easyconfigs/d/DMTCP/DMTCP-2.6.0-GCCcore-9.3.0.eb
Labels: update

#11794 {tools}[GCCcore/8.2.0] DMTCP v2.6.0
  easybuild/easyconfigs/d/DMTCP/DMTCP-2.6.0-GCCcore-8.2.0.eb
Labels: update

#11797 {lib}[GCCcore/8.3.0] neon v0.31.2
  easybuild/easyconfigs/n/neon/neon-0.31.2-GCCcore-8.3.0.eb
Labels: new

#11697 {numlib}[system/system] cuDNN v8.0.4.30
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.0.4.30-CUDA-11.0.2.eb
Labels: update

#11805 {lib}[GCCcore/10.2.0] giflib v5.2.1
  easybuild/easyconfigs/g/giflib/giflib-5.2.1-GCCcore-10.2.0.eb
Labels: update

#11806 {lib}[GCCcore/10.2.0] JsonCpp v1.9.4
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.4-GCCcore-10.2.0.eb
Labels: update

#11807 {lib}[GCCcore/10.2.0] LMDB v0.9.24
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.24-GCCcore-10.2.0.eb
Labels: update

#11808 {devel}[GCCcore/10.2.0] nsync v1.24.0
  easybuild/easyconfigs/n/nsync/nsync-1.24.0-GCCcore-10.2.0.eb
Labels: update

#11809 {devel}[GCCcore/10.2.0] SWIG v4.0.2
  easybuild/easyconfigs/s/SWIG/SWIG-4.0.2-GCCcore-10.2.0.eb
Labels: update

#11811 {vis}[GCCcore/10.2.0] Pillow v8.0.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/Pillow/Pillow-8.0.1-GCCcore-10.2.0.eb
Labels: update

#11816 {lib}[GCCcore/10.2.0] PyYAML v5.3.1, libyaml v0.2.5 w/ Python 2.7.18 + 3.8.6
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-5.3.1-GCCcore-10.2.0.eb
Labels: update

#11815 {math}[GCCcore/10.2.0] MPFR v4.1.0
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-10.2.0.eb
Labels: update

#11799 {tools}[GCCcore/8.3.0] cctools v7.0.22 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/c/cctools/cctools-7.0.22-GCCcore-8.3.0.eb
Labels: new

#11819 {devel}[GCCcore/10.2.0] pkgconfig v1.5.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.5.1-GCCcore-10.2.0-python.eb
Labels: update

#11818 {lang}[fosscuda/2020b,intelcuda/2020a,intelcuda/2020b] SciPy-bundle v2020.03, SciPy-bundle v2020.11 w/ Python 3.8.2 + 3.8.6
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-intelcuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-fosscuda-2020b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-intelcuda-2020b.eb
Labels: update

#11748 {bio}[system/system] CellRanger v5.0.0
  easybuild/easyconfigs/c/CellRanger/CellRanger-5.0.0.eb
Labels: update

#11820 {data}[fosscuda/2020a,gompic/2020a,iimpic/2020a,intelcuda/2020a] HDF5 v1.10.6, h5py v2.10.0 w/ Python 3.8.2
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.6-gompic-2020a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.6-iimpic-2020a.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-intelcuda-2020a-Python-3.8.2.eb
Labels: update

#11822 {debugger,lib}[GCCcore/9.3.0] LLDB v11.0.0, libedit v20191231 w/ Python 3.8
  easybuild/easyconfigs/l/LLDB/LLDB-11.0.0-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/l/libedit/libedit-20191231-GCCcore-9.3.0.eb
Labels: new, update

#11827 {vis}[GCCcore/9.3.0] Pillow-SIMD v7.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-7.1.2-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11828 {data}[gompic/2020b,iimpic/2020b] HDF5 v1.10.7
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-gompic-2020b.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-iimpic-2020b.eb
Labels: update

#11830 {devel,lib}[GCCcore/10.2.0] libidn v1.36, wget v1.20.3
  easybuild/easyconfigs/l/libidn/libidn-1.36-GCCcore-10.2.0.eb
  easybuild/easyconfigs/w/wget/wget-1.20.3-GCCcore-10.2.0.eb
Labels: update

#11829 {data}[foss/2020b,fosscuda/2020b,intel/2020b,intelcuda/2020b] h5py v3.1.0 w/ Python 3.8.6
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-foss-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-fosscuda-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-intel-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-intelcuda-2020b.eb
Labels: update

#11831 {tools}[GCCcore/10.2.0] hypothesis v5.41.5 w/ Python 3.8.6
  easybuild/easyconfigs/h/hypothesis/hypothesis-5.41.5-GCCcore-10.2.0.eb
Labels: update

#11817 {devel}[GCCcore/10.2.0,foss/2020b] protobuf-python v3.14.0, protobuf v3.14.0 w/ Python 3.8.6
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.14.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/protobuf/protobuf-3.14.0-GCCcore-10.2.0.eb
Labels: update

#11800 add gnuplot dependency for OpenFOAM v1606 to v2006
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1606+-foss-2018b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1612+-foss-2018b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1712-foss-2017b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1712-intel-2017b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1806-foss-2018b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1812-foss-2018b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1906-foss-2019b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1912-foss-2019b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1912-intel-2019b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2006-foss-2020a.eb
Labels: bug fix

#11620 {bio}[intel/2020a] Metagenome-Atlas v2.4.3 w/ Python 3.8.2
  easybuild/easyconfigs/m/Metagenome-Atlas/Metagenome-Atlas-2.4.3-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/Metagenome-Atlas/Metagenome-Atlas-2.4.3_remove-hardcoded-conda.patch
Labels: new

#11767 add missing PEAR dependency in easyconfig for GBprocesS v2.3 + enhance sanity check
  easybuild/easyconfigs/g/GBprocesS/GBprocesS-2.3-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/PEAR/PEAR-0.9.11-GCCcore-9.3.0.eb
Labels: bug fix

#11838 {tools}[binary] Aspera-CLI 3.9.6
  easybuild/easyconfigs/a/Aspera-CLI/Aspera-CLI-3.9.6.1467.159c5b1.eb
Labels: update

#11778 {tools}[system/system] code-server v3.7.3
  easybuild/easyconfigs/c/code-server/code-server-3.7.3.eb
Labels: new

#11841 add packages mitools survey tableone jstable to R-4.0.0
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11834 {vis}[intelcuda/2020a] matplotlib v3.2.1 w/ Python 3.8.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.2.1-intelcuda-2020a-Python-3.8.2.eb
Labels: update

#11803 {lib}[system/system] NCCL v2.8.3
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.3-CUDA-11.0.2.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.3-CUDA-11.1.1.eb
Labels: update

#11802 {numlib}[system/system] cuDNN v8.0.4.30
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.0.4.30-CUDA-11.1.1.eb
Labels: update

#11832 {data}[fosscuda/2020a,intelcuda/2020a] scikit-learn v0.23.1 w/ Python 3.8.2
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.1-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.1-intelcuda-2020a-Python-3.8.2.eb
Labels: update

#11835 {vis}[foss/2020b,fosscuda/2020b,intel/2020b,intelcuda/2020b] matplotlib v3.3.3 w/ Python 3.8.6
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.3-foss-2020b.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.3-fosscuda-2020b.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.3-intel-2020b.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.3.3-intelcuda-2020b.eb
Labels: update

#11833 {data}[foss/2020b,fosscuda/2020b,intel/2020b,intelcuda/2020b] scikit-learn v0.23.2 w/ Python 3.8.6
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.2-foss-2020b.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.2-fosscuda-2020b.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.2-intel-2020b.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.23.2-intelcuda-2020b.eb
Labels: update

#11845 don't add include/node to $CPATH in nodejs easyconfigs + tweak V8 easyconfigs accordingly
  easybuild/easyconfigs/n/nodejs/nodejs-10.15.1-foss-2018b.eb
  easybuild/easyconfigs/n/nodejs/nodejs-10.15.3-GCCcore-8.2.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-12.19.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/v/V8/V8-2.2-foss-2018b-R-3.5.1.eb
  easybuild/easyconfigs/v/V8/V8-2.3-foss-2019a-R-3.6.0.eb
  easybuild/easyconfigs/v/V8/V8-2.3-intel-2019a-R-3.6.0.eb
  easybuild/easyconfigs/v/V8/V8-3.2.0-foss-2019b-R-3.6.2.eb
Labels: bug fix, change

#11849 {data}[foss/2019b,fosscuda/2019b] pyFAI 0.19.0 w/ Python 3.7.4
  easybuild/easyconfigs/p/pyFAI/pyFAI-0.19.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/pyFAI/pyFAI-0.19.0-fosscuda-2019b-Python-3.7.4.eb
Labels: new

#11848 {data}[foss/2019b,fosscuda/2019b] pymca 5.6.3 w/ Python 3.7.4
  easybuild/easyconfigs/p/pymca/pymca-5.6.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/pymca/pymca-5.6.3-fosscuda-2019b-Python-3.7.4.eb
Labels: new

#11761 {toolchain} gobff/2020.11 + gobff/2020.06-amd (toolchains with BLIS + libFLAME)
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.0-GCC-9.3.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-2.2-GCC-9.3.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-2.2-amd_fix-undefined-reference-blist-abort.patch
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020a-amd.eb
  easybuild/easyconfigs/g/gobff/gobff-2020.06-amd.eb
  easybuild/easyconfigs/g/gobff/gobff-2020.11.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-gobff-2020.06-amd.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-gobff-2020.11.eb
  easybuild/easyconfigs/l/libFLAME/libFLAME-2.2-GCC-9.3.0-amd.eb
  easybuild/easyconfigs/l/libFLAME/libFLAME-5.2.0-GCC-9.3.0.eb
  easybuild/easyconfigs/m/make/make-4.3-GCC-9.3.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a-bf.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2-gompi-2020a-amd.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#11850 prepare release notes for EasyBuild v4.3.2 + bump version to 4.3.2
  RELEASE_NOTES
  setup.py
Labels: update

#11853 {tools} EasyBuild v4.3.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.2.eb
Labels: update

#11854 sync with master + bump version to v4.3.3.dev0
  RELEASE_NOTES
  setup.py
Labels: update

#11851 {tools}[system] gh v1.3.1 (GitHub CLI)
  easybuild/easyconfigs/g/gh/gh-1.3.1.eb
Labels: new

#11858 {bio}[system/system] PLINK v1.9b_6.21-x86_64
  easybuild/easyconfigs/p/PLINK/PLINK-1.9b_6.21-x86_64.eb
Labels: update

#6445 {bio}[intel/2018a] CNVkit v0.9.3, Biopython v1.71, hmmlearn 0.2.0
  easybuild/easyconfigs/b/Biopython/Biopython-1.71-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/c/CNVkit/CNVkit-0.9.3-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/c/CNVkit/CNVkit-0.9.3_disable-hanging-test.patch
  easybuild/easyconfigs/h/hmmlearn/hmmlearn-0.2.0-intel-2018a-Python-3.6.4.eb
Labels: update

#7026 {phys}[{intel,foss}/2018a] Meep v1.6.0, MPB v1.6.2, Harminv 1.4.1
  easybuild/easyconfigs/h/Harminv/Harminv-1.4.1-foss-2018a.eb
  easybuild/easyconfigs/h/Harminv/Harminv-1.4.1-intel-2018a.eb
  easybuild/easyconfigs/l/libGDSII/libGDSII-0.21-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libctl/libctl-4.1.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/MPB/MPB-1.6.2-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/MPB/MPB-1.6.2-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Meep/Meep-1.6.0-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Meep/Meep-1.6.0-intel-2018a-Python-2.7.14.eb
Labels: new, update

#11863 {bio}[system/system] ConnectomeWorkbench v1.4.2
  easybuild/easyconfigs/c/ConnectomeWorkbench/ConnectomeWorkbench-1.4.2-rh_linux64.eb
Labels: update

#6928 {data}[gmpolf/2017.10] HDF5 v1.8.20
  easybuild/easyconfigs/h/HDF5/HDF5-1.8.20-gmpolf-2017.10.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1-gmpolf-2017.10.eb
Labels: update

#7262 {bio}[intel/2018b] RNAmmer v1.2 w/ Perl 5.28.0
  easybuild/easyconfigs/r/RNAmmer/RNAmmer-1.2-intel-2018b-Perl-5.28.0.eb
Labels: new, update

#11862 {bio}[system] SignalP v5.0b
  easybuild/easyconfigs/s/SignalP/SignalP-5.0b-Linux.eb
Labels: new

#7141 {phys}[intel/2018a] CHERAB v1.2.0 and Raysect v0.6.0 for Python/3.6.6
  easybuild/easyconfigs/c/CHERAB/CHERAB-1.2.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/r/Raysect/Raysect-0.6.0-intel-2018b-Python-3.6.6.eb
Labels: new

#7129 {phys}[foss/2017b] Meep v1.6.0
  easybuild/easyconfigs/h/Harminv/Harminv-1.4.1-foss-2017b.eb
  easybuild/easyconfigs/l/libctl/libctl-4.1.3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/MPB/MPB-1.6.2-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/m/Meep/Meep-1.6.0-foss-2017b-Python-2.7.14.eb
Labels: new, update

#7378 {bio}[foss/2018b] samblaster v0.1.24
  easybuild/easyconfigs/s/samblaster/samblaster-0.1.24-foss-2018b.eb
Labels: new

#7272 {bio}[intel/2018b] bcgTree v1.1.0, RAxML v8.2.12, Gblocks 0.91b
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.1.0-intel-2018b-Perl-5.28.0.eb
  easybuild/easyconfigs/g/Gblocks/Gblocks-0.91b.eb
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-intel-2018b-hybrid-avx2.eb
Labels: update

#7559 {compiler}[dummy/] Go v1.11.5
  easybuild/easyconfigs/g/Go/Go-1.11.5.eb
Labels: update

#7277 {bio}[GCCcore/10.20] ack v3.4.0 w/ Perl 5.32.0
  easybuild/easyconfigs/a/ack/ack-3.4.0-GCCcore-10.2.0.eb
Labels: update

#6615 {numlib}[GCC/7.3.0-2.30,dummy/dummy,goblf/2018b,gompi/2018b] goblf v2018b, HPL v2.2, LAPACK v3.8.0, ...
  easybuild/easyconfigs/g/goblf/goblf-2018b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.2-goblf-2018b.eb
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.8.0-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018b-BLIS-0.3.2.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#6092 {toolchain} iimkl/2018a + Python 3.6.4 installed with iimkl/2018a
  easybuild/easyconfigs/i/iimkl/iimkl-2018a.eb
  easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iccifort-2018.1.163-GCC-6.4.0-2.28-serial.eb
  easybuild/easyconfigs/p/Python/Python-3.6.4-iimkl-2018a.eb
Labels: new, update

#7688 {bio}[GCC/7.3.0-2.30] wtdbg2 v2.3
  easybuild/easyconfigs/w/wtdbg2/wtdbg2-2.3-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/w/wtdbg2/wtdbg2-2.3-makefile-hardcoding.patch
Labels: new

#7345 {vis}[foss/2018b] mayavi v4.6.2 w/ Python 3.6.6
  easybuild/easyconfigs/m/mayavi/mayavi-4.6.2-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/mayavi/mayavi-4.6.2_disable-docs.patch
  easybuild/easyconfigs/v/VTK/VTK-8.1.1-foss-2018b-Python-3.6.6.eb
Labels: update

#11869 Add missing builddep on M4 to recent SuiteSparse versions
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.4.0-foss-2019a-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.4.0-intel-2018b-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.4.0-intel-2019a-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.7.1-foss-2020a-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.7.1-intel-2020a-METIS-5.1.0.eb
Labels: bug fix

#11870 {mpi}[gompi/2020a] OpenCoarrays v2.9.2
  easybuild/easyconfigs/o/OpenCoarrays/OpenCoarrays-2.9.2-gompi-2020a.eb
Labels: update

#11842 {lib}[GCCcore/10.2.0] tbb v2020.3
  easybuild/easyconfigs/t/tbb/tbb-2020.3-GCCcore-10.2.0.eb
Labels: update

#11840 {tools}[GCCcore/9.3.0] Emacs v27.1
  easybuild/easyconfigs/e/Emacs/Emacs-27.1-GCCcore-9.3.0.eb
Labels: update

#11873 LLVM 6 fails to export LLVMInitializeInstCombine symbol
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-6.0.0_missing_LLVMInitializeInstCombine.patch
Labels: bug fix

#11871 {system}[GCCcore/6.4.0,GCCcore/10.2.0] libpci v3.7.0
  easybuild/easyconfigs/l/libpci/libpci-3.7.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libpci/libpci-3.7.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libpci/libpci-3.7.0_fix-install-lib-symlinks.patch
Labels: new

#11710 {bio}[intel/2020a] OpenSees v3.2.0 w/ Python 3.8.2 (paralllel support)
  easybuild/easyconfigs/o/OpenSees/OpenSees-3.2.0-add_Makefile_def_parallel.patch
  easybuild/easyconfigs/o/OpenSees/OpenSees-3.2.0-fix_superlu_dist.patch
  easybuild/easyconfigs/o/OpenSees/OpenSees-3.2.0-intel-2020a-Python-3.8.2-parallel.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-5.4.0-intel-2020a-trisolve-merge.eb
Labels: update

#7302 enable building of QtWebEngine in Qt5 easyconfig using foss/2017b or intel/2017b
  easybuild/easyconfigs/q/Qt5/Qt5-5.8.0-foss-2017b.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.9.3-foss-2017b.eb
Labels: enhancement

#11877 {devel}[GCCcore/9.3.0] libgit2 v1.1.0
  easybuild/easyconfigs/l/libgit2/libgit2-1.1.0-GCCcore-9.3.0.eb
Labels: update

#11881 {devel}[foss/2020a,fosscuda/2020a] NLTK v3.5 w/ Python 3.8.2
  easybuild/easyconfigs/n/NLTK/NLTK-3.5-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/NLTK/NLTK-3.5-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#11823 {bio}[foss/2020a] NanopolishComp v0.6.11, nanopolish v0.13.2 w/ Python 3.8.2
  easybuild/easyconfigs/b/Biopython/Biopython-1.78-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/NanopolishComp/NanopolishComp-0.6.11-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/nanopolish/nanopolish-0.13.2-foss-2020a-Python-3.8.2.eb
Labels: new, update

#7194 {geo}[foss/2018b] SeisSol v201703 w/ Python 2.7.15
  easybuild/easyconfigs/g/GLM/GLM-0.9.8.3-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.10-foss-2018b.eb
  easybuild/easyconfigs/s/SCons/SCons-3.0.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/s/SeisSol/SeisSol-201703-foss-2018b-Python-2.7.15.eb
Labels: new, update

#11887 fix sources of GDRCopy
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.1-GCCcore-10.2.0-CUDA-11.1.1.eb
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.1-GCCcore-9.3.0-CUDA-11.0.2.eb
Labels: bug fix

#11885 {data,geo}[intel/2019b] geopandas v0.8.1, Fiona v1.8.13 w/ Python 3.7.4
  easybuild/easyconfigs/f/Fiona/Fiona-1.8.13-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/geopandas/geopandas-0.8.1-intel-2019b-Python-3.7.4.eb
Labels: update

#11884 {numlib}[gcccuda/2020a] cuDNN v8.0.4.30
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.0.4.30-gcccuda-2020a.eb
Labels: update

#11878 {bio}[intel/2020a] nanofilt v2.6.0 w/ Python 3.8.2
  easybuild/easyconfigs/n/nanofilt/nanofilt-2.6.0-intel-2020a-Python-3.8.2.eb
Labels: update

#11889 {mpi}[GCC/10.2.0] MPICH v3.3.2
  easybuild/easyconfigs/m/MPICH/MPICH-3.3.2-GCC-10.2.0.eb
Labels: update

#11888 {mpi}[GCC/9.3.0] MPICH v3.3.2
  easybuild/easyconfigs/m/MPICH/MPICH-3.3.2-GCC-9.3.0.eb
Labels: update

#8630 {bio}[gompi/2018b] FIt-SNE v1.1.0
  easybuild/easyconfigs/f/FIt-SNE/FIt-SNE-1.1.0-gompi-2018b.eb
Labels: new

#11693 {numlib}[foss/2020a,intel/2020a] SuperLU_DIST v6.4.0
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-6.4.0-foss-2020a.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-6.4.0-intel-2020a.eb
Labels: new

#11879 {bio}[iccifort/2020.1.217] minibar v20200326, edlib v1.3.8.post2 w/ Python 3.8.2
  easybuild/easyconfigs/e/edlib/edlib-1.3.8.post2-iccifort-2020.1.217-Python-3.8.2.eb
  easybuild/easyconfigs/m/minibar/minibar-20200326-iccifort-2020.1.217-Python-3.8.2.eb
Labels: update

#11880 {bio}[intel/2020a] qcat v1.1.0, python-parasail v1.2.2, parasail v2.4.2 w/ Python 3.8.2
  easybuild/easyconfigs/p/parasail/parasail-2.4.2-iccifort-2020.1.217.eb
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.2.2-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/q/qcat/qcat-1.1.0-intel-2020a-Python-3.8.2.eb
Labels: update

#11883 {tools}[foss/2020b] pytest-xdist v2.1.0 w/ Python 3.8.6
  easybuild/easyconfigs/p/pytest-xdist/pytest-xdist-2.1.0-foss-2020b.eb
Labels: new

#11886 {lib}[foss/2020a] preCICE v2.1.1 w/ Python 3.8.2
  easybuild/easyconfigs/p/preCICE/preCICE-2.1.1-foss-2020a-Python-3.8.2.eb
Labels: new

#11837 Fix miscompilation bug on POWER with GCC
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0_fix-xsmin-ppc.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0.eb
Labels: bug fix

#11893 fix toolchain for pytest-xdist v2.1.0 w/ Python 3.8.6, should be GCCcore
  easybuild/easyconfigs/p/pytest-xdist/pytest-xdist-2.1.0-GCCcore-10.2.0.eb
Labels: bug fix

#11892 Fix Tombo to work with rpy2 v3 when creating DataFrames
  easybuild/easyconfigs/t/Tombo/Tombo-1.5.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/Tombo/Tombo-1.5.1_rpy2-v3.patch
Labels: bug fix

#11874 {bio}[system] QIIME2 v2020.8
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.8.3.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2020.8.eb
Labels: update

#11875 {bio}[system] QIIME2 v2020.11
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.9.2.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2020.11.eb
Labels: update

#10707 {bio}[foss/2019b] GraPhlAn v1.1.3 w/ Python 2.7.16
  easybuild/easyconfigs/g/GraPhlAn/GraPhlAn-1.1.3-foss-2019b-Python-2.7.16.eb
Labels: new

#10988 {bio}[foss/2019b] RSEM v1.3.3
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.3.0-GCC-9.3.0.eb
  easybuild/easyconfigs/r/RSEM/RSEM-1.3.3-foss-2019b.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.5b-GCC-9.3.0.eb
Labels: update

#11861 Backport SM specification to magma for fosscuda/2019b
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2019b.eb
  easybuild/easyconfigs/m/magma/magma-2.5.4_allow-all-sms.patch
Labels: enhancement

#11839 GCCcore-9.3.0: enable NVPTX offload
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0.eb
Labels: enhancement

#11899 {chem}[foss/2020b,intel/2020b] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-foss-2020b.eb
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-intel-2020b.eb
Labels: update

#11903 {bio}[GCCcore/9.3.0] LSD2 v1.9.7
  easybuild/easyconfigs/l/LSD2/LSD2-1.9.7-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/LSD2/LSD2-1.9.7_fix_cmake_to_build_lib_and_binary.patch
Labels: new

#11905 QuantumESPRESSO 6.6: enable gipaw
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-foss-2019b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-intel-2019b.eb
Labels: enhancement

#11866 disable building of manpages for GDCM to fix installation problem with docbook
  easybuild/easyconfigs/g/GDCM/GDCM-2.8.8-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GDCM/GDCM-2.8.9-GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/GDCM/GDCM-3.0.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GDCM/GDCM-3.0.5-GCCcore-8.3.0.eb
Labels: bug fix

#11906 {bio}[foss/2020a] IQ-TREE v2.1.2
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.1.2-foss-2020a.eb
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.1.2_use_EB_LSD2.patch
Labels: update

#11896 GCC 8.1.0 - fix for removed sys/ustat.h in glibc 2.28
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0-fix-glibc-2.28-libsanitizer.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0.eb
Labels: bug fix

#11891 {bio}[foss/2019b] decona v0.1.2 (+ dependencies) w/ Python 3.7.4
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-GCC-8.3.0.eb
  easybuild/easyconfigs/d/decona/decona-0.1.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/n/nanofilt/nanofilt-2.6.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/parasail/parasail-2.4.1-foss-2019b.eb
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/q/qcat/qcat-1.1.0-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#11665 {chem}[gompi/2020b,iimpi/2020b] Libint v2.6.0
  easybuild/easyconfigs/l/Libint/Libint-2.6.0-GCC-10.2.0-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/Libint/Libint-2.6.0-iccifort-2020.4.304-lmax-6-cp2k.eb
Labels: 2020b, update

#11904 {lang}[foss/2020a] numba v0.52.0 w/ Python 3.8.2
  easybuild/easyconfigs/n/numba/numba-0.52.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11844 {bio}[foss/2018b] MEGAHIT v1.2.9 w/ Python 2.7.15 + 3.6.6
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-foss-2018b.eb
Labels: update

#11826 {bio}[GCCcore/8.3.0] dcm2niix v1.0.20200331, dcm2niix v1.0.20201102
  easybuild/easyconfigs/c/CharLS/CharLS-2.1.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/d/dcm2niix/dcm2niix-1.0.20200331-GCCcore-8.3.0.eb
  easybuild/easyconfigs/d/dcm2niix/dcm2niix-1.0.20201102-GCCcore-8.3.0.eb
Labels: update

#11763 {data,math}[foss/2020a] causalml v0.8.0-20200909, Keras v2.3.1 w/ Python 3.8.2
  easybuild/easyconfigs/c/causalml/causalml-0.8.0-20200909-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/k/Keras/Keras-2.3.1-foss-2020a-Python-3.8.2.eb
Labels: update

#11912 {bio}[gompi/2020b] Salmon v1.4.0
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.2.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/Salmon/Salmon-1.4.0-gompi-2020b.eb
Labels: update

#11911 {bio}[GCC/9.3.0] Bowtie2 v2.4.2
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.2-GCC-9.3.0.eb
Labels: update

#11910 {bio}[foss/2020a] Stacks v2.54
  easybuild/easyconfigs/s/Stacks/Stacks-2.54-foss-2020a.eb
Labels: update

#11916 add CESM-deps to whitelist in check for custom sanity_check_paths
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#11898 {numlib}[system/system] cuDNN v8.0.5.39
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.0.5.39-CUDA-11.1.1.eb
Labels: update

#11915 {math}[system/system] Gurobi v9.1.0
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.1.0.eb
Labels: update

#11914 {lib}[gcccuda/2019b] cuTENSOR v1.2.2.5
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-1.2.2.5-gcccuda-2019b.eb
Labels: new

#11856 {math}[fosscuda/2020a,fosscuda/2020b] magma v2.5.4
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2020a.eb
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2020b.eb
Labels: update

#11919 {lib}[GCCcore/9.3.0] Flask v1.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/f/Flask/Flask-1.1.2-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11749 {lib}[fosscuda/2019b] CuPy v8.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/c/CuPy/CuPy-8.2.0-fosscuda-2019b-Python-3.7.4.eb
Labels: new

#11668 {chem}[foss/2020b,intel/2020b] PLUMED v2.6.2
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.2-foss-2020b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.2-intel-2020b.eb
Labels: 2020b, update

#11663 {lang}[foss/2020b] R v4.0.3
  easybuild/easyconfigs/r/R/HWxtest-1.1.9_add-fcommon.patch
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
Labels: 2020b, update

#11902 {tools} Added git as a dependency to GitPython version 3.x
  easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-foss-2018b.eb
  easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-intel-2018b.eb
  easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-iomkl-2018b.eb
  easybuild/easyconfigs/g/GitPython/GitPython-2.1.11-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/g/GitPython/GitPython-2.1.11-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/g/GitPython/GitPython-3.0.3-GCCcore-8.2.0-Python-3.7.2.eb
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.0-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.9-GCCcore-9.3.0-Python-3.8.2.eb
Labels: bug fix

#11859 Fix TF 2.3.1 compilation with GLIBC 2.26 on POWER
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1_disable-float128-on-power.patch
Labels: bug fix

#11922 add additional extensions to R v4.0.3 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
Labels: enhancement

#11921 add RCAL + sensemakr extensions to R 4.0.0
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11609 replace easyconfigs for bpp-core/bpp-phyl/bpp-seq v2.4.1 with a single easyconfig for BioPP v2.4.1 (using Bundle easyblock)
  easybuild/easyconfigs/b/BioPP/BioPP-2.4.1-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/b/bpp-core/bpp-core-2.4.1-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/b/bpp-phyl/bpp-phyl-2.4.1-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/b/bpp-seq/bpp-seq-2.4.1-GCC-8.2.0-2.31.1.eb
Labels: change

#11927 libgit2 GCCcore-10.2.0
  easybuild/easyconfigs/l/libgit2/libgit2-1.1.0-GCCcore-10.2.0.eb
Labels: update

#11925 {math}[foss/2020b,intel/2020b] ELPA v2020.11.001
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-foss-2020b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-intel-2020b.eb
Labels: update

#11924 {bio}[intel/2020b] FIGARO v1.1.2 w/ Python 3.8.6
  easybuild/easyconfigs/f/FIGARO/FIGARO-1.1.2-intel-2020b.eb
Labels: new

#11926 {bio}[foss/2019b] FLAIR v1.5.1-20200630 w/ Python 3.7.4
  easybuild/easyconfigs/f/FLAIR/FLAIR-1.5.1-20200630-foss-2019b-Python-3.7.4.eb
Labels: update

#11929 {numlib}[GCC/9.3.0] AMD-LibM v3.6.0-4, AMD-RNG v2.2, AMD-SecureRNG v2.2
  easybuild/easyconfigs/a/AMD-LibM/AMD-LibM-3.6.0-4-GCC-9.3.0.eb
  easybuild/easyconfigs/a/AMD-RNG/AMD-RNG-2.2-GCC-9.3.0.eb
  easybuild/easyconfigs/a/AMD-SecureRNG/AMD-SecureRNG-2.2-GCC-9.3.0.eb
Labels: update

#11669 {chem}[foss/2020b] CP2K v7.1
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-foss-2020b.eb
Labels: 2020b, update

#11670 {chem}[intel/2020b] CP2K v7.1
  easybuild/easyconfigs/c/CP2K/CP2K-7.1-intel-2020b.eb
Labels: update

#11890 {chem}[foss,intel/2020b] ASE v3.20.1, GPAW v20.10.0, spglib-python v1.16.0, ... w/ Python 3.8.6
  easybuild/easyconfigs/a/ASE/ASE-3.20.1-foss-2020b.eb
  easybuild/easyconfigs/a/ASE/ASE-3.20.1-intel-2020b.eb
  easybuild/easyconfigs/f/Flask/Flask-1.1.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-foss-2020b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-intel-2020b.eb
  easybuild/easyconfigs/l/libvdwxc/libvdwxc-0.4.0-foss-2020b.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.0-foss-2020b.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.0-intel-2020b.eb
Labels: update

#11918 {bio}[foss/2019b] NGSpeciesID v0.1.1.1 w/ Python 3.7.4
  easybuild/easyconfigs/n/NGSpeciesID/NGSpeciesID-0.1.1.1-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#11933 improve sanity_check_paths for AMD-LibM
  easybuild/easyconfigs/a/AMD-LibM/AMD-LibM-3.2.2-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/a/AMD-LibM/AMD-LibM-3.6.0-4-GCC-9.3.0.eb
Labels: enhancement

#11934 include '-4' in version for AMD-RNG v2.2-4, symlink include/lib subdirs, enhance sanity_check_paths
  easybuild/easyconfigs/a/AMD-RNG/AMD-RNG-2.2-4-GCC-9.3.0.eb
Labels: change, enhancement

#11935 improve sanity_check_paths for AMD-SecureRNG + include '-4' in version for AMD-SecureRNG v2.2-4
  easybuild/easyconfigs/a/AMD-SecureRNG/AMD-SecureRNG-1.0-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/a/AMD-SecureRNG/AMD-SecureRNG-2.2-4-GCC-9.3.0.eb
Labels: change, enhancement

#11928 update Java/1.8 wrapper to JDK 8u271
  easybuild/easyconfigs/j/Java/Java-1.8.0_271.eb
  easybuild/easyconfigs/j/Java/Java-1.8.eb
Labels: change, update

#11936 PyTorch: fix __ieee128 is undefined on ppc64le with glibc 2.26
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_el8_ppc64le.patch
Labels: bug fix

#11930 magma: fix __ieee128 is undefined on ppc64le with glibc 2.26
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2019a.eb
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2019b.eb
  easybuild/easyconfigs/m/magma/magma-2.5.4_el8-ppc64le.patch
Labels: bug fix

#11937 switch to using python-parasail and tqdm dependencies in Bonito easyconfigs
  easybuild/easyconfigs/b/Bonito/Bonito-0.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/Bonito/Bonito-0.1.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/Bonito/Bonito-0.1.4-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/Bonito/Bonito-0.2.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/Bonito/Bonito-0.2.2-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/parasail/parasail-2.4.1-GCC-8.3.0.eb
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.2-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix, update

#10395 {bio}[SYSTEM] GSEA v4.0.3
  easybuild/easyconfigs/g/GSEA/GSEA-4.0.3.eb
Labels: new

#11868 {compiler}[GCCcore/9.3.0] AOCC v2.3.0
  easybuild/easyconfigs/a/AOCC/AOCC-2.3.0-GCCcore-9.3.0.eb
Labels: new

#11750 {bio}[fosscuda/2019b] Bonito v0.3.2 w/ Python 3.7.4
  easybuild/easyconfigs/b/Bonito/Bonito-0.3.2-fosscuda-2019b-Python-3.7.4.eb
Labels: update
