Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-11, with the labels that each got.

#7982 {bio}[foss/2018a] Minimac4 1.0.0 + libStatGen 20190330
  easybuild/easyconfigs/l/libStatGen/libStatGen-20190330-GCCcore-6.4.0.eb
  easybuild/easyconfigs/m/Minimac4/Minimac4-1.0.0-foss-2018a.eb
Labels: bug fix, new

#11600 add alternate checksum for KernSmooth 2.23-17 extension in R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: bug fix

#11603 rename XCfun to XCFun
  easybuild/easyconfigs/p/PySCF/PySCF-1.6.3-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/x/XCFun/XCFun-20180122-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/x/XCFun/XCFun-20180122-shared_library-intel.patch
  easybuild/easyconfigs/x/XCFun/XCFun-20190127-foss-2019a-Python-3.7.2.eb
Labels: change

#11567 {chem}[GCCcore/9.3.0] XCFun 2.1.0
  easybuild/easyconfigs/x/XCFun/XCFun-2.1.0-GCCcore-9.3.0.eb
Labels: update

#11596 fix source_urls in Geant4 easyconfigs
  easybuild/easyconfigs/g/Geant4/Geant4-10.01.p03-intel-2016a.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.02.p01-intel-2016a.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.03.p03-foss-2017b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.03.p03-intel-2017b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.04-intel-2017b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.5-foss-2017b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.5-foss-2018b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.5-intel-2017b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.5-intel-2018b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.6-foss-2019b.eb
  easybuild/easyconfigs/g/Geant4/Geant4-9.5.p02-intel-2016a.eb
  easybuild/easyconfigs/g/Geant4/Geant4-9.6.p04-intel-2016a.eb
Labels: bug fix

#11604 {chem}[foss/2020a] MRChem v1.0.0 w/ Python-3.8.2
  easybuild/easyconfigs/m/MRChem/MRChem-1.0.0-foss-2020a-Python-3.8.2.eb
Labels: new

#11587 add coloc, Exact, lmom, gld, and DescTools extensions to R-4.0.0
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11605 {vis}[GCCcore/9.3.0] JasPer v2.0.16
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.16-GCCcore-9.3.0.eb
Labels: update

#11597 {numlib,phys}[foss/2020a] Geant4 v10.6.2, CLHEP v2.4.1.3
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.1.3-foss-2020a.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.6.2-foss-2020a.eb
Labels: update

#11592 {chem}[intel/2020a] CP2K v5.1
  easybuild/easyconfigs/c/CP2K/CP2K-5.1-intel-2020a.eb
  easybuild/easyconfigs/l/Libint/Libint-1.1.6-intel-2020a.eb
  easybuild/easyconfigs/l/libxc/libxc-3.0.1-intel-2020a.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#11586 add snpStats extension to R-bundle-Bioconductor
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#11608 {bio}[foss/2019b] fix BBMap version check in FusionCatcher v1.20
  easybuild/easyconfigs/f/FusionCatcher/FusionCatcher-1.20-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/f/FusionCatcher/FusionCatcher-1.20_fix_bbmap_check.patch
Labels: bug fix

#11594 {chem}[intel/2020a] CP2K v6.1
  easybuild/easyconfigs/c/CP2K/CP2K-6.1-intel-2020a.eb
Labels: update

#11613 {bio}[intel/2020a] OpenSees v3.2.0 w/ Python 3.8.2
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.7.0-intel-2020a.eb
  easybuild/easyconfigs/o/OpenSees/OpenSees-3.2.0-add_Makefile_def_sequential.patch
  easybuild/easyconfigs/o/OpenSees/OpenSees-3.2.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SuperLU/SuperLU-5.2.2-intel-2020a.eb
Labels: new

#11270 {bio}[foss/2020a] carputils v20200915, meshtool v16, meshalyzer 2.0 w/ Python 3.8.2
  easybuild/easyconfigs/c/carputils/carputils-20200915-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/meshalyzer/meshalyzer-2.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/meshalyzer/meshalyzer-2.0_fix-VTK-linking.patch
  easybuild/easyconfigs/m/meshtool/meshtool-16-GCC-9.3.0.eb
Labels: new

#11617 {bio}[iccifort/2020.1.217] BBMap v38.87
  easybuild/easyconfigs/b/BBMap/BBMap-38.87-iccifort-2020.1.217.eb
Labels: update

#11616 add alternative checksum for codetools 0.2-16 in R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: bug fix

#11615 {geo}[GCC/9.3.0] SWAT+ v60.4.1
  easybuild/easyconfigs/s/SWAT+/SWAT+-60.4.1-GCC-9.3.0.eb
  easybuild/easyconfigs/s/SWAT+/SWAT+-60.4.1_fix-implicits.patch
  easybuild/easyconfigs/s/SWAT+/SWAT+_add-cmakelists.patch
Labels: new

#11622 {math}[GCCcore/10.2.0] Eigen v3.3.8
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.8-GCCcore-10.2.0.eb
Labels: update

#11607 {bio}[foss/2020a] SplAdder v2.4.2 w/ Python 3.8.2
  easybuild/easyconfigs/s/SplAdder/SplAdder-2.4.2-foss-2020a-Python-3.8.2.eb
Labels: new

#11623 {lib}[GCCcore/10.2.0] pybind11 v2.6.0 w/ Python 3.8.6
  easybuild/easyconfigs/p/pybind11/pybind11-2.6.0-GCCcore-10.2.0.eb
Labels: update

#11565 {geo}[foss/2020a] PEST++ v5.0.5
  easybuild/easyconfigs/p/PEST++/PEST++-5.0.5-foss-2020a.eb
Labels: new

#11610 {phys}[system/system] Geant4-data v20201103
  easybuild/easyconfigs/g/Geant4-data/Geant4-data-20201103.eb
Labels: new

#11578 {tools}[system/system] vsc-mympirun v5.2.2
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.2.eb
Labels: update

#11624 {bio}[GCC/8.3.0,GCC/9.3.0] StringTie v2.1.4
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.4-GCC-8.3.0.eb
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.4-GCC-9.3.0.eb
Labels: update

#11627 add patch for GCCcore 10.2 to fix __has_include regression
  easybuild/easyconfigs/g/GCCcore/GCC-10.2_fix-has-include-Fortran.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb
Labels: bug fix

#11634 {numlib}[GCCcore/10.2.0] NLopt v2.6.2
  easybuild/easyconfigs/n/NLopt/NLopt-2.6.2-GCCcore-10.2.0.eb
Labels: update

#11633 {tools}[GCCcore/10.2.0] GLPK v4.65
  easybuild/easyconfigs/g/GLPK/GLPK-4.65-GCCcore-10.2.0.eb
Labels: update

#11632 {lib}[GCCcore/10.2.0] libsndfile v1.0.28
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-10.2.0.eb
Labels: update

#11631 {phys}[GCCcore/10.2.0] UDUNITS v2.2.26
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-10.2.0.eb
Labels: update

#11635 {lib,vis}[GCCcore/10.2.0] Xvfb v1.20.9, nettle v3.6
  easybuild/easyconfigs/n/nettle/nettle-3.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.9-GCCcore-10.2.0.eb
Labels: update

#11630 {vis}[GCCcore/10.2.0] ImageMagick v7.0.10-35, Ghostscript v9.53.3, LittleCMS v2.11
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.53.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.53.3_fix-freetype-callback.patch
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.10-35-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/LittleCMS/LittleCMS-2.11-GCCcore-10.2.0.eb
Labels: update

#11489 {toolchain} foss/2020b
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020b.eb
  easybuild/easyconfigs/f/foss/foss-2020b.eb
  easybuild/easyconfigs/g/gompi/gompi-2020b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2020b.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.12-GCC-10.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0_fix-GCC-10.patch
Labels: 2020b, update

#11337 {toolchain} intel/2020b
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2020b.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2020.4.304.eb
  easybuild/easyconfigs/i/iccifort/iccifort-2020.4.304_no_mpi_rt_dependency.patch
  easybuild/easyconfigs/i/iimpi/iimpi-2020b.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.4.304-iimpi-2020b.eb
  easybuild/easyconfigs/i/impi/impi-2019.9.304-iccifort-2020.4.304.eb
  easybuild/easyconfigs/i/intel/intel-2020b.eb
Labels: 2020b, update

#11625 {bio}[foss/2020a] GROMACS v2020.4
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-foss-2020a.eb
Labels: update

#11626 {geo}[foss/2020a,intel/2020a] WRF v3.9.1.1
  easybuild/easyconfigs/t/time/time-1.9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-foss-2020a-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-intel-2020a-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1_libtirpc.patch
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1_netCDF-Fortran_separate_path.patch
Labels: update

#11650 {numlib}[GCC/10.2.0,iccifort/2020.4.304] GSL v2.6
  easybuild/easyconfigs/g/GSL/GSL-2.6-GCC-10.2.0.eb
  easybuild/easyconfigs/g/GSL/GSL-2.6-iccifort-2020.4.304.eb
Labels: update

#11649 {tools}[foss/2020a,intel/2020a,GCCcore-10.2.0] Set JUPYTER_PATH to make Jupyter find the ipywidgets extension
  easybuild/easyconfigs/i/IPython/IPython-7.13.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.13.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.15.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.15.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/IPython/IPython-7.18.1-GCCcore-10.2.0.eb
Labels: bug fix

#11640 Add python gmx to GROMACS 2020.4
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.4-foss-2020a.eb
Labels: update

#11638 add SCANVIS to R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
Labels: enhancement

#11639 {data}[gompi/2020b,iimpi/2020b] HDF5 v1.10.7, netCDF v4.7.4, netCDF-Fortran v4.5.3
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.20-GCCcore-10.2.0.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-gompi-2020b.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-iimpi-2020b.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.16-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.3-gompi-2020b.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.3-iimpi-2020b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-gompi-2020b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-iimpi-2020b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.4_fix-ocdebug.patch
Labels: 2020b, update

#11654 add missing extensions for QIIME2 to Perl 5.30.2 and 5.32.0 easyconfigs
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Labels: enhancement

#11647 {tools}[system/system] vsc-mympirun v5.2.3
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.3.eb
Labels: update

#11612 {system}[system/system] CUDA v11.1.1, CUDAcore v11.1.1, gcccuda v2020b
  easybuild/easyconfigs/c/CUDA/CUDA-11.1.1-GCC-10.2.0.eb
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.1.1.eb
  easybuild/easyconfigs/g/gcccuda/gcccuda-2020b.eb
Labels: 2020b, update

#11645 {tools}[foss/2020a] Change default bitmaptype for IRkernel to cairo
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-foss-2020a-R-3.6.3-Python-3.8.2.eb
Labels: bug fix

#11674 {perf}[gompi/2020b,iimpi/2020b] OSU-Micro-Benchmarks v5.6.3
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-gompi-2020b.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-iimpi-2020b.eb
Labels: 2020b, update

#11679 use Python 2 build dep for nodejs 12.19.0
  easybuild/easyconfigs/n/nodejs/nodejs-12.19.0-GCCcore-10.2.0.eb
Labels: bug fix

#11618 {bio,tools}[iccifort/2020.1.217,intel/2020a] CheckM v1.1.3, Pysam v0.16.0.1 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/c/CheckM/CheckM-1.1.3-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.16.0.1-iccifort-2020.1.217.eb
Labels: update

#11619 {tools}[intel/2020a] snakemake v5.26.1 (+ GitPython v3.1.9) w/ Python 3.8.2
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.9-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/s/snakemake/snakemake-5.26.1-intel-2020a-Python-3.8.2.eb
Labels: update

#11678 {tools}[system/system] Nextflow v20.10.0
  easybuild/easyconfigs/n/Nextflow/Nextflow-20.10.0.eb
Labels: update

#11672 {math}[GCCcore/10.2.0] METIS v5.1.0
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-10.2.0.eb
Labels: 2020b, update

#11671 {vis}[GCCcore/10.2.0] FFmpeg v4.3.1
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.3.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/x264/x264-20201026-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/x265/x265-3.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-10.2.0.eb
Labels: 2020b, update

#11667 {math}[GCC/10.2.0,iccifort/2020.4.304] libxsmm v1.16.1
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-GCC-10.2.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-iccifort-2020.4.304.eb
Labels: update

#11658 {lib}[GCCcore/9.3.0] alsa-lib v1.2.4
  easybuild/easyconfigs/a/alsa-lib/alsa-lib-1.2.4-GCCcore-9.3.0.eb
Labels: new

#11659 {vis}[GCCcore/9.3.0] bwidget v1.9.14
  easybuild/easyconfigs/b/bwidget/bwidget-1.9.14-GCCcore-9.3.0.eb
Labels: update

#11664 {numlib}[intel/2020b] FFTW v3.3.8
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-intel-2020b.eb
Labels: 2020b, update

#11673 {math}[gompi/2020b,iimpi/2020b] SCOTCH v6.1.0
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2020b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-iimpi-2020b.eb
Labels: 2020b, update

#11662 add missing dependencies + fix moduleclass in CheckM easyconfigs (should be bio)
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.13-intel-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.18-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.1.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.1.2-intel-2019b-Python-3.7.4.eb
Labels: bug fix, change

#11660 {bio}[foss/2020a] scikit-bio v0.5.6 w/ Python 3.8.2
  easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.5.6-foss-2020a-Python-3.8.2.eb
Labels: new

#11656 {math}[fosscuda/2019a,fosscuda/2019b] magma v2.5.4
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2019a.eb
  easybuild/easyconfigs/m/magma/magma-2.5.4-fosscuda-2019b.eb
Labels: update

#11687 {devel}[gompi/2019b] libzeep v5.0.1
  easybuild/easyconfigs/l/libzeep/libzeep-5.0.1-gompi-2019b.eb
Labels: new

#11691 {tools}[system/system] vsc-mympirun v5.2.4
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.4.eb
Labels: update

#11655 {chem,lib}[intel/2020a] GlobalArrays v5.8, OpenMolcas v20.10 w/ Python 3.8.2
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-intel-2020a.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-20.10-intel-2020a-Python-3.8.2.eb
Labels: update

#11690 {bio}[intel/2020a] nanocompore v1.0.0rc3-2, Seaborn v0.10.1, statsmodels v0.11.1, tqdm v4.51.0 w/ Python 3.8.2
  easybuild/easyconfigs/n/nanocompore/nanocompore-1.0.0rc3-2-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.10.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.11.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.51.0-intel-2020a-Python-3.8.2.eb
Labels: new, update

#11680 {lib}[GCCcore/9.3.0] RapidJSON v1.1.0
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-9.3.0.eb
Labels: update

#11641 {bio}[foss/2019b] EMU v0.66 w/ Python 3.7.4
  easybuild/easyconfigs/e/EMU/EMU-0.66-foss-2019b-Python-3.7.4.eb
Labels: new

#11692 {lang}[fosscuda/2020a] SciPy-bundle v2020.03 w/ Python 3.8.2
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#11699 {devel}[GCC/8.3.0] FreeSASA v2.0.3
  easybuild/easyconfigs/f/FreeSASA/FreeSASA-2.0.3-GCC-8.3.0.eb
Labels: new

#11709 {data}[foss/2020a] xarray v0.16.1 w/ Python 3.8.2
  easybuild/easyconfigs/x/xarray/xarray-0.16.1-foss-2020a-Python-3.8.2.eb
Labels: update

#11702 Use correct OS deps in UCX
  easybuild/easyconfigs/u/UCX/UCX-1.8.0-GCCcore-9.3.0-CUDA-11.0.2.eb
Labels: bug fix

#11711 {data}[gompi/2020b] netCDF-C++4 v4.3.1
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-gompi-2020b.eb
Labels: update

#11704 {tools}[fosscuda/2020a] networkx v2.4 w/ Python 3.8.2
  easybuild/easyconfigs/n/networkx/networkx-2.4-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#11707 {vis}[fosscuda/2020a] matplotlib v3.2.1 w/ Python 3.8.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.2.1-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#11708 {lib}[GCCcore/9.3.0] psycopg2 v2.8.6 w/ Python 3.8.2
  easybuild/easyconfigs/p/psycopg2/psycopg2-2.8.6-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11705 {bio}[foss/2020a] pySCENIC v0.10.3 w/ Python 3.8.2
  easybuild/easyconfigs/p/pySCENIC/pySCENIC-0.10.3-foss-2020a-Python-3.8.2.eb
Labels: update

#11703 {phys}[intel/2020a] FDS v6.7.5
  easybuild/easyconfigs/f/FDS/FDS-6.7.5-intel-2020a.eb
Labels: update

#11712 {geo}[foss/2020a] rioxarray v0.1.1 w/ Python 3.8.2
  easybuild/easyconfigs/r/rioxarray/rioxarray-0.1.1-foss-2020a-Python-3.8.2.eb
Labels: update

#11713 {geo}[foss/2020a] Open-Data-Cube-Core v1.8.3 w/ Python 3.8.2
  easybuild/easyconfigs/o/Open-Data-Cube-Core/Open-Data-Cube-Core-1.8.3-foss-2020a-Python-3.8.2.eb
Labels: new

#11716 {tools}[GCCcore/9.3.0] gperftools v2.8
  easybuild/easyconfigs/g/gperftools/gperftools-2.8-GCCcore-9.3.0.eb
Labels: update

#11714 {bio}[foss/2020a] geocube v0.0.14 w/ Python 3.8.2
  easybuild/easyconfigs/g/geocube/geocube-0.0.14-foss-2020a-Python-3.8.2.eb
Labels: new

#11614 add patch for TensorFlow 2.3.1 to fix installation on Arm64
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1_fix-aarch64.patch
Labels: EESSI, bug fix

#11642 {devel}[GCC/10.2.0,iccifort/2020.4.304] Boost v1.74.0
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-GCC-10.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-iccifort-2020.4.304.eb
Labels: 2020b, update

#11696 {data}[foss/2020a,fosscuda/2020a] pycocotools v2.0.2 w/ Python 3.8.2
  easybuild/easyconfigs/p/pycocotools/pycocotools-2.0.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/pycocotools/pycocotools-2.0.2-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#11717 {lib}[GCC/9.3.0] SentencePiece v0.1.94 w/ Python 3.8.2
  easybuild/easyconfigs/s/SentencePiece/SentencePiece-0.1.94-GCC-9.3.0-Python-3.8.2.eb
Labels: update

#11718 {lib,tools}[GCCcore/8.3.0,foss/2019b] RE2 v2020-07-01, torchtext v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/r/RE2/RE2-2020-07-01-GCCcore-8.3.0.eb
  easybuild/easyconfigs/t/torchtext/torchtext-0.7.0-foss-2019b-Python-3.7.4-PyTorch-1.6.0.eb
Labels: new, update

#11701 {lib}[GCCcore/10.2.0] fosscuda v2020b, Check v0.15.2, GDRCopy v2.1, UCX v1.9.0, ...
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompic-2020b.eb
  easybuild/easyconfigs/f/fosscuda/fosscuda-2020b.eb
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.1-GCCcore-10.2.0-CUDA-11.1.1.eb
  easybuild/easyconfigs/g/gompic/gompic-2020b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-gcccuda-2020b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompic-2020b.eb
  easybuild/easyconfigs/u/UCX/UCX-1.9.0-GCCcore-10.2.0-CUDA-11.1.1.eb
Labels: update

#11728 {lang}[foss/2020a] rstudio v1.3.1093
  easybuild/easyconfigs/r/rstudio/rstudio-1.3.1093-foss-2020a-Java-11-R-4.0.0.eb
Labels: update

#11706 {chem}[foss/2019b,intel/2019b] GPAW v20.10.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/ASE/ASE-3.20.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/ASE/ASE-3.20.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-foss-2019b-ASE-3.20.1-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-intel-2019b-ASE-3.20.1-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-test-mpi.patch
Labels: update

#11519 {bio}[system/system] fgbio v1.3.0
  easybuild/easyconfigs/f/fgbio/fgbio-1.3.0.eb
Labels: new

#11268 {vis}[foss/2019b] torchvision v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/torchvision/torchvision-0.7.0-foss-2019b-Python-3.7.4-PyTorch-1.6.0.eb
Labels: update

#11732 Adding missing Java dep to Prokka
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019b.eb
Labels: bug fix

#11729 {compiler}[GCCcore/9.3.0] Clang v11.0.0
  easybuild/easyconfigs/c/Clang/Clang-11.0.0-GCCcore-9.3.0.eb
Labels: update

#11734 {bio}[foss/2020a] RSeQC v4.0.0, bx-python v0.8.9, pyBigWig v0.3.17 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/b/bx-python/bx-python-0.8.9-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/pyBigWig/pyBigWig-0.3.17-GCCcore-9.3.0.eb
  easybuild/easyconfigs/r/RSeQC/RSeQC-4.0.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11733 add nlsem extension to R 4.0.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb
Labels: enhancement

#11736 add alternative checksum for codetools 0.2-16 in R 3.6.x easyconfigs
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-intel-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb
Labels: bug fix

#11735 {tools}[system/system] vsc-mympirun v5.2.5
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.5.eb
Labels: update

#11145 {devel}[GCC/9.3.0] Boost.Serial v1.72.0
  easybuild/easyconfigs/b/Boost.Serial/Boost.Serial-1.72.0-GCC-9.3.0.eb
  easybuild/easyconfigs/b/Boost.Serial/Boost.Serial-1.72.0-iccifort-2020.1.217.eb
Labels: feature

#11585 {vis}[foss/2020a] NiBabel v3.2.0 w/ Python 3.8.2
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.2.0-foss-2020a-Python-3.8.2.eb
Labels: update

#11666 {chem}[GCC/10.2.0,iccifort/2020.4.304] libxc v4.3.4
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-10.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2020.4.304.eb
Labels: 2020b, update

#11584 {vis}[foss/2019b] NiBabel v3.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.1.0-foss-2019b-Python-3.7.4.eb
Labels: update

#11739 {bio}[gompi/2020a] HMMER v3.3.1
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.1-gompi-2020a.eb
Labels: update

#11740 {bio}[foss/2020a] IQ-TREE v1.6.12
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-1.6.12-foss-2020a.eb
Labels: update

#11726 in-place update to magma 2.5.4 for PyTorch easyconfigs using fosscuda/2019b toolchain
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0_add-cuda11-support.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.3.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb
Labels: bug fix, change

#11743 foss 2019b Quantum Espresso 6.6
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-foss-2019b.eb
Labels: update

#11764 Change 'rstudio' name to 'RStudio-Server' to agree with official name and better reflect what it provides
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-1.2.5033-fosscuda-2019b-Java-11.eb
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-1.2.5042-foss-2019b-Java-11.eb
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-1.3.1093-foss-2020a-Java-11-R-4.0.0.eb
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-1.3.959-foss-2020a-Java-11-R-4.0.0.eb
  easybuild/easyconfigs/r/RStudio-Server/rstudio-1.2.5033_fix_boost_170_compat.patch
  easybuild/easyconfigs/r/RStudio-Server/rstudio-1.2.5033_update_gwt.patch
  easybuild/easyconfigs/r/RStudio-Server/rstudio-1.3.959_fix-rslave.patch
Labels: bug fix, change

#11769 {lib}[GCCcore/8.3.0] mxml v3.2
  easybuild/easyconfigs/m/mxml/mxml-3.2-GCCcore-8.3.0.eb
Labels: new

#11768 {perf}[gompi/2020a,iimpi/2020a,iompi/2020a] IPM v2.0.6
  easybuild/easyconfigs/i/IPM/IPM-2.0.6-gompi-2020a.eb
  easybuild/easyconfigs/i/IPM/IPM-2.0.6-iimpi-2020a.eb
  easybuild/easyconfigs/i/IPM/IPM-2.0.6-iompi-2020a.eb
Labels: new

#11775 {bio}[foss/2019b] CRISPResso2 v2.0.44, Seaborn v0.9.1 w/ Python 2.7.16
  easybuild/easyconfigs/c/CRISPResso2/CRISPResso2-2.0.44-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/c/CRISPResso2/CRISPResso2-2.0.44_relax_requirements.patch
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.9.1-foss-2019b-Python-2.7.16.eb
Labels: new, update

#11773 {perf}[iimpi/2019a,iimpi/2019b] OSU-Micro-Benchmarks v5.6.3
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-iimpi-2019a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-iimpi-2019b.eb
Labels: update

#11772 {perf}[gompi/2019b,iimpi/2019b] IPM v2.0.6
  easybuild/easyconfigs/i/IPM/IPM-2.0.6-gompi-2019b.eb
  easybuild/easyconfigs/i/IPM/IPM-2.0.6-iimpi-2019b.eb
Labels: update

#11771 {lib}[GCC/9.3.0] mxmlplus v0.9.2
  easybuild/easyconfigs/m/mxmlplus/libmxmlplus-0.9.2_stdcpp_compliance.patch
  easybuild/easyconfigs/m/mxmlplus/mxmlplus-0.9.2-GCC-9.3.0.eb
Labels: new

#11766 {bio}[gompi/2019b] RAxML-NG v1.0.1
  easybuild/easyconfigs/r/RAxML-NG/RAxML-NG-1.0.1-gompi-2019b.eb
Labels: update

#11760 {numlib}[gompi/2019b] imkl v2019.5.281
  easybuild/easyconfigs/i/imkl/imkl-2019.5.281-gompi-2019b.eb
Labels: update

#11759 {vis}[GCCcore/8.3.0] assimp v5.0.1
  easybuild/easyconfigs/a/assimp/assimp-5.0.1-GCCcore-8.3.0.eb
Labels: new

#11747 {devel}[system/system] Flink v1.11.2
  easybuild/easyconfigs/f/Flink/Flink-1.11.2-bin-scala_2.11.eb
Labels: new

#11727 Renamed ambiguous Ray easyconfigs to Ray-assembler and Ray-project
  easybuild/easyconfigs/r/Ray-assembler/Ray-assembler-2.3.1-iimpi-2019a.eb
  easybuild/easyconfigs/r/Ray-project/Ray-project-0.8.4-foss-2019b-Python-3.7.4.eb
Labels: bug fix, change

#11776 {bio}[GCC/9.3.0] SpaceRanger v1.1.0
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-9.3.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.1.0-GCC-9.3.0.eb
Labels: new

#11757 {tools}[system/system] zsh v5.8
  easybuild/easyconfigs/z/zsh/zsh-5.8.eb
Labels: update

#11744 {bio}[intel/2020a] velocyto v0.17.17 w/ Python 3.8.2
  easybuild/easyconfigs/v/velocyto/velocyto-0.17.17-intel-2020a-Python-3.8.2.eb
Labels: new

#11730 {toolchain}[system/system] intelcuda v2020b, CUDA v11.1.1, iccifortcuda v2020b, impi v2019.9.304, ...
  easybuild/easyconfigs/c/CUDA/CUDA-11.1.1-iccifort-2020.4.304.eb
  easybuild/easyconfigs/i/iccifortcuda/iccifortcuda-2020b.eb
  easybuild/easyconfigs/i/iimpic/iimpic-2020b.eb
  easybuild/easyconfigs/i/imkl/imkl-2020.4.304-iimpic-2020b.eb
  easybuild/easyconfigs/i/impi/impi-2019.9.304-iccifortcuda-2020b.eb
  easybuild/easyconfigs/i/intelcuda/intelcuda-2020b.eb
Labels: 2020b, update

#11720 enable NVPTX offload support in GCCcore 10.2.0 easyconfig
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb
Labels: enhancement

#11629 {lang}[foss/2020b,intel/2020b] SciPy-bundle v2020.11 w/ Python 3.8.6
  easybuild/easyconfigs/h/hypothesis/hypothesis-5.41.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-foss-2020b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-intel-2020b.eb
Labels: 2020b, update

#11758 {tools}[fosscuda/2019b] Ray-project v1.0.1 w/ Python 3.7.4
  easybuild/easyconfigs/r/Ray-project/Ray-project-1.0.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#11745 Add patch to fix possible memory leak in OpenBLAS 0.3.3+
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.3-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.4-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.6-GCC-8.3.0-2.32.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7-GCC-8.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7_fix-possible-memory-leak-after-fork.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.9-GCC-9.3.0.eb
Labels: bug fix

#11755 do not treat warnings as errors in Java v1.8_191-b26-OpenJDK (POWER)
  easybuild/easyconfigs/j/Java/Java-1.8_191-b26-OpenJDK.eb
Labels: bug fix

#11782 consistently add Java as a dep for prokka 1.14.5
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019a.eb
Labels: bug fix

#11770 add missing gnuplot dependency in easyconfig for OpenFOAM 7 and 8
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-foss-2019b-20200508.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-foss-2019b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8-foss-2020a.eb
Labels: bug fix

#11555 {devel}[GCCcore/10.2.0] Qt5 v5.14.2
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.2_fix-missing-stdint.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.2_fix-webengine-bison.patch
Labels: update
