Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2020-04, with the labels that each got.

#10291 {bio}[foss/2018b] iVar v1.0.1
  easybuild/easyconfigs/i/iVar/iVar-1.0.1-foss-2018b.eb
Labels: new

#10298 add BSgenome.Hsapiens.UCSC.hg38 + MEDIPS extensions to R-bundle-Bioconductor v3.10
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.10-foss-2019b.eb
Labels: enhancement

#9738 make installing independent of build folder in pybind11 easyconfig
  easybuild/easyconfigs/p/pybind11/pybind11-2.2.4-intel-2018b-Python-3.6.6.eb
Labels: change

#10300 ensure separate_build_dir is set to False for ITK and elastix components in SimpleElastix easyconfig
  easybuild/easyconfigs/s/SimpleElastix/SimpleElastix-1.1.0-foss-2019b-Python-3.7.4.eb
Labels: bug fix

#10287 {bio}[foss/2019b] Trinity v2.10.0 w/ Python 3.7.4
  easybuild/easyconfigs/t/Trinity/Trinity-2.10.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10272 {bio,devel}[iccifort/2019.5.281,system/system] ABRA2 v2.22, Maven v3.6.3
  easybuild/easyconfigs/a/ABRA2/ABRA2-2.22-iccifort-2019.5.281.eb
  easybuild/easyconfigs/a/ABRA2/ABRA2-2.22_fix-Makefile.patch
  easybuild/easyconfigs/m/Maven/Maven-3.6.3.eb
Labels: new, update

#10299 {data}[foss/2019b] GraphMap2 v0.6.4
  easybuild/easyconfigs/g/GraphMap2/GraphMap2-0.6.4-foss-2019b.eb
Labels: new

#10310 {bio,tools}[GCCcore/8.3.0,gompi/2019b] ABRicate v0.9.9, any2fasta v0.4.2
  easybuild/easyconfigs/a/ABRicate/ABRicate-0.9.9-gompi-2019b.eb
  easybuild/easyconfigs/a/any2fasta/any2fasta-0.4.2-GCCcore-8.3.0.eb
Labels: update

#10319 {bio}[iccifort/2019.5.281] MAFFT v7.453
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.453-iccifort-2019.5.281-with-extensions.eb
Labels: update

#10317 {math}[system/system] Gurobi v9.0.1
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.1.eb
Labels: update

#10253 {vis}[foss/2020a,intel/2020a] VTK v8.2.0 w/ Python 3.8.2
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0_python_3.8_compatibility.patch
Labels: 2020a, update

#10250 {bio}[GCC/9.3.0] Bowtie2 v2.4.1
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.1-GCC-9.3.0.eb
Labels: 2020a, update

#10247 {bio}[system/system] picard v2.22.1
  easybuild/easyconfigs/p/picard/picard-2.22.1-Java-11.eb
Labels: 2020a, update

#10226 {vis}[foss/2019b] OpenCV v4.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.2.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10211 {lib}[foss/2019b,fosscuda/2019b] segmentation-models v1.0.1 w/ Python 3.7.4
  easybuild/easyconfigs/s/segmentation-models/segmentation-models-1.0.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/segmentation-models/segmentation-models-1.0.1-fosscuda-2019b-Python-3.7.4.eb
Labels: new

#10210 {vis}[GCCcore/8.3.0] pydicom v1.4.2 w/ Python 2.7.16 + 3.7.4
  easybuild/easyconfigs/p/pydicom/pydicom-1.4.2-GCCcore-8.3.0.eb
Labels: update

#10161 {math}[intel/2018b] statsmodels v0.9.0 w/ Python 3.6.6
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.9.0-intel-2018b-Python-3.6.6.eb
Labels: update

#10151 adding easyconfigs: SPAdes-3.14.0-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.14.0-GCC-8.3.0-Python-3.7.4.eb
Labels: update

#10307 {compiler}[system/system] Go v1.14.1
  easybuild/easyconfigs/g/Go/Go-1.14.1.eb
Labels: update

#10228 {vis}[foss/2019b] motionSegmentation v2.7.9, medImgProc v2.5.7 w/ Python 3.7.4
  easybuild/easyconfigs/m/medImgProc/medImgProc-2.5.7-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/motionSegmentation/motionSegmentation-2.7.9-foss-2019b-Python-3.7.4.eb
Labels: new

#10328 stick to using GCC/8.3.0 as toolchain for BCFtools
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.10.2-GCC-8.3.0.eb
Labels: update

#10323 {bio}[foss/2019b] BatMeth2 v2.1, SAMtools v0.1.20
  easybuild/easyconfigs/b/BatMeth2/BatMeth2-2.1-foss-2019b.eb
  easybuild/easyconfigs/b/BatMeth2/BatMeth2-2.1_fix-automake-rerun.patch
  easybuild/easyconfigs/f/fastp/fastp-0.20.0-GCC-8.3.0.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-0.1.20-GCC-8.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#10309 {math}[intel/2019b] Shapely v1.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/GEOS/GEOS-3.8.0-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/s/Shapely/Shapely-1.7.0-GCC-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/s/Shapely/Shapely-1.7.0-iccifort-2019.5.281-Python-3.7.4.eb
Labels: new

#9991 {lib}[fosscuda/2019b] TensorFlow v1.15.2, TensorFlow v2.0.1 w/ Python 3.7.2 + 3.7.4
  easybuild/easyconfigs/h/Horovod/Horovod-0.18.2-fosscuda-2019b-TensorFlow-1.15.2-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.2-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10336 re-enable 'apt-get update' + use '-o Acquire::Retries=3' to dance around Azure connectivity issues
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#10311 {compiler}[GCCcore/8.3.0] LLVM v9.0.1
  easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-GCCcore-8.3.0.eb
Labels: update

#10313 {compiler}[GCCcore/8.3.0] LLVM v10.0.0
  easybuild/easyconfigs/l/LLVM/LLVM-10.0.0-GCCcore-8.3.0.eb
Labels: update

#10340 disable apt-get update (again) in GA workflow
  .github/workflows/unit_tests.yml
Labels: change

#10305 {lang}[system/system] Java v1.8.0_241
  easybuild/easyconfigs/j/Java/Java-1.8.0_241.eb
  easybuild/easyconfigs/j/Java/Java-1.8.eb
Labels: update

#10289 {lang}[GCCcore/9.3.0] Rust v1.42.0
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10320 {tools}[GCCcore/8.3.0] likwid v5.0.1
  easybuild/easyconfigs/l/likwid/likwid-5.0.1-GCCcore-8.3.0.eb
Labels: update

#10306 {lang}[system/system] Java v13.0.2
  easybuild/easyconfigs/j/Java/Java-13.0.2.eb
  easybuild/easyconfigs/j/Java/Java-13.eb
Labels: update

#10341 use apt-spy2 before using apt in GitHub Actions
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#10294 {compiler}[system/system] PGI v19.10
  easybuild/easyconfigs/p/PGI/PGI-19.10-GCC-8.3.0-2.32.eb
Labels: update

#10301 {math}[system/system] MATLAB v2019b
  easybuild/easyconfigs/m/MATLAB/MATLAB-2019b.eb
Labels: update

#10347 {tools}[foss/2019b] OpenAI-Gym v0.17.1 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenAI-Gym/OpenAI-Gym-0.17.1-foss-2019b-Python-3.7.4.eb
Labels: new

#10343 {bio}[intel/2019b] LtrDetector v1.0 w/ Python 3.7.4
  easybuild/easyconfigs/l/LtrDetector/LtrDetector-1.0-intel-2019b-Python-3.7.4.eb
Labels: new

#10315 {devel,lib,tools}[GCCcore/8.3.0] davix v0.7.5, LibUUID v1.0.3, gSOAP v2.8.100
  easybuild/easyconfigs/d/davix/davix-0.7.5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/d/davix/davix-0.7.5_fix_version.patch
  easybuild/easyconfigs/g/gSOAP/gSOAP-2.8.100-GCCcore-8.3.0.eb
Labels: update

#10337 STEAK recipe
  easybuild/easyconfigs/s/STEAK/STEAK-2019.09.12-foss-2019b-Python-2.7.16.eb
Labels: new

#10357 {bio}[GCC/8.3.0] BamTools v2.5.1
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-GCC-8.3.0.eb
Labels: update

#10356 fix undefined reference error due to libxc 4.3.4 built with CMake
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.5.281.eb
Labels: bug fix

#10354 {bio}[intel/2019b] Porechop v0.2.4 w/ Python 3.7.4
  easybuild/easyconfigs/p/Porechop/Porechop-0.2.4-intel-2019b-Python-3.7.4.eb
Labels: update

#10303 {data}[GCCcore/8.3.0] pyproj v2.4.2 w/ Python 3.7.4
  easybuild/easyconfigs/p/pyproj/pyproj-2.4.2-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10352 {bio,tools}[intel/2019b] BiG-SCAPE v1.0.1, networkx v2.4 w/ Python 3.7.4
  easybuild/easyconfigs/b/BiG-SCAPE/BiG-SCAPE-1.0.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/n/networkx/networkx-2.4-intel-2019b-Python-3.7.4.eb
Labels: new, update

#10350 {vis}[fosscuda/2019b] OpenCV v4.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.2.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10355 add VSURF + Rborist extensions to R 3.6.2 easyconfig
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
Labels: enhancement

#10345 {chem}[GCC/8.3.0] DFT-D3 v3.2.0
  easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-GCC-8.3.0.eb
Labels: update

#10321 {data}[foss/2019b] Fiona v1.8.13 w/ Python 3.7.4
  easybuild/easyconfigs/f/Fiona/Fiona-1.8.13-foss-2019b-Python-3.7.4.eb
Labels: new

#10316 {compiler}[GCCcore/8.3.0] Clang v10.0.0
  easybuild/easyconfigs/c/Clang/Clang-10.0.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/Clang/libcxx-10.0.0-ppc64le.patch
Labels: update

#10346 {numlib}[intel/2019b] arpack-ng v3.7.0
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.7.0-add_include_CheckSymbolExists_CMakeLists_txt.patch
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.7.0-intel-2019b.eb
Labels: update

#10302 {data}[foss/2019b,intel/2019b] xarray v0.15.1 w/ Python 3.7.4
  easybuild/easyconfigs/x/xarray/xarray-0.15.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/x/xarray/xarray-0.15.1-intel-2019b-Python-3.7.4.eb
Labels: update

#10331 {bio}[foss/2018b] medaka v0.12.0 w/ Python 3.6.6
  easybuild/easyconfigs/m/medaka/medaka-0.12.0-foss-2018b-Python-3.6.6.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#10362 {lib}[GCCcore/8.3.0] tbb v2020.2
  easybuild/easyconfigs/t/tbb/tbb-2020.2-GCCcore-8.3.0.eb
Labels: update

#10361 [TBB] Official Threading Building Blocks (TBB) GitHub repository update for the sources
  easybuild/easyconfigs/t/tbb/tbb-2017_U5-GCCcore-5.4.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2017_U5-foss-2016b.eb
  easybuild/easyconfigs/t/tbb/tbb-2017_U5-intel-2017a.eb
  easybuild/easyconfigs/t/tbb/tbb-2017_U6-GCCcore-6.3.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2017_U6-intel-2017a.eb
  easybuild/easyconfigs/t/tbb/tbb-2018_U1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2018_U2-GCCcore-6.4.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2018_U3-GCCcore-6.4.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2018_U5-GCCcore-6.4.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2018_U5-GCCcore-7.3.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2019_U4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/t/tbb/tbb-2019_U9-GCCcore-8.3.0.eb
Labels: change

#10349 {vis}[GCCcore/9.3.0] GTK+ v3.24.17, ATK v2.36.0, Pango v1.44.7, ...
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.34.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.36.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.17-GCCcore-9.3.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.6.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.44.7-GCCcore-9.3.0.eb
Labels: 2020a, update

#10333 {lang}[GCCcore/8.3.0] Ruby v2.7.1
  easybuild/easyconfigs/r/Ruby/Ruby-2.7.1-GCCcore-8.3.0.eb
Labels: update

#10358 {bio}[GCC/8.3.0] BEDTools v2.29.2
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.29.2-GCC-8.3.0.eb
Labels: update

#10001 {bio}[foss/2019b] BinSanity v0.3.5, CheckM v1.1.2, subread v1.6.5 w/ Python 3.7.4
  easybuild/easyconfigs/b/BinSanity/BinSanity-0.3.5-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/c/CheckM/CheckM-1.1.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/Subread/Subread-2.0.0-GCC-8.3.0.eb
Labels: new, update

#10258 {lib}[fosscuda/2019b] Racon v1.4.7
  easybuild/easyconfigs/r/Racon/Racon-1.4.7-gcccuda-2019b.eb
  easybuild/easyconfigs/r/Racon/Racon-1.4.7_patch_bioparsers_zlib.patch
Labels: update

#10367 PyTorch: fix checksums of Intel sources that moved to oneAPI
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-fosscuda-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.3.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.3.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0-fosscuda-2019b-Python-3.7.4.eb
Labels: change, enhancement

#10047 {bio}[foss/2019b] BUSCO v4.0.5, AUGUSTUS v3.3.3, SEPP v4.3.10, ... w/ Python 3.7.4
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.3-foss-2019b.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.3_fix-hardcoding.patch
  easybuild/easyconfigs/b/BUSCO/BUSCO-4.0.5-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-GCC-8.3.0.eb
  easybuild/easyconfigs/s/SEPP/SEPP-4.3.10-foss-2019b-Python-3.7.4.eb
Labels: new, update

#10374 stop using apt-spy2 to pick an alternative mirror, it's expensive and may result in picking a faulty mirror...
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#10270 {bio}[foss/2019b] Bonito v0.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/b/Bonito/Bonito-0.1.0-foss-2019b-Python-3.7.4.eb
Labels: new

#10368 {bio}[intel/2019b] IQ-TREE v1.6.12
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-1.6.12-intel-2019b.eb
Labels: update

#10360 {lang}[foss/2020a] R v3.6.3: add Rborist, VSURF and dHSIC
  easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb
Labels: 2020a, enhancement

#10353 {lang}[fosscuda/2019b] numba v0.47.0 w/ Python 3.7.4
  easybuild/easyconfigs/n/numba/numba-0.47.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10366 {math}[intel/2019b] ArviZ v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.7.0-intel-2019b-Python-3.7.4.eb
Labels: new

#9827 {tools}[fosscuda/2019b] IRkernel v1.1 w/ Python 3.7.4
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-fosscuda-2019b-R-3.6.2-Python-3.7.4.eb
Labels: update

#10067 {chem,lib}[gompi/2019b,GCCcore/8.3.0] OpenBabel v3.0.0, RapidJSON v1.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.0.0-gompi-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-8.3.0.eb
Labels: update

#10276 add comment informing about manually setting Gallium drivers in easyconfigs for Mesa v19.1.7 and v19.2.1
  easybuild/easyconfigs/m/Mesa/Mesa-19.1.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.2.1-GCCcore-8.3.0.eb
Labels: change

#9982 {bio}[GCC/8.3.0,foss/2019b] STAR-Fusion v1.8.1, STAR v2.7.2b w/ Python 3.7.4
  easybuild/easyconfigs/s/SECAPR/SECAPR-1.1.15-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/s/STAR-Fusion/STAR-Fusion-1.8.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.2b-GCC-8.3.0.eb
  easybuild/easyconfigs/t/Trinity/Trinity-2.9.1-foss-2019b-Python-2.7.16.eb
Labels: change, update

#10324 {data}[foss/2018b] ROOT v6.14.06 w/ Python 3.6.6
  easybuild/easyconfigs/r/ROOT/ROOT-6.14.06-foss-2018b-Python-3.6.6.eb
Labels: update

#10371 {chem}[foss/2019b,intel/2019b] LAMMPS v3Mar2020 w/ Python 3.7.4
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2019b-Python-3.7.4-kokkos.eb
Labels: update

#8734 {bio}[foss/2019a] EnsEMBLCoreAPI v96.0-r20190601
  easybuild/easyconfigs/b/BLAT/BLAT-3.5-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/e/EnsEMBLCoreAPI/EnsEMBLCoreAPI-96.0-r20190601-foss-2019a-Perl-5.28.1.eb
Labels: change, new

#10326 ensure that CVS easyconfigs are included in source tarball produced by 'python setup.py sdist'
  .github/workflows/unit_tests.yml
  .gitignore
  MANIFEST.in
  setup.cfg
Labels: bug fix

#10382 also add alternative checksum for LaplacesDemon extension in R 3.6.0 easyconfigs
  easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
  easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
Labels: bug fix

#10380 {devel}[GCCcore/8.3.0] GObject-Introspection 1.63.1 w/ Python 3.7.4 missing build dep. pkg-config.
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.63.1-GCCcore-8.3.0-Python-3.7.4.eb
Labels: bug fix

#10383 fix Perl shebang for RepeatMasker
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.0.9-p2-gompi-2019b-HMMER.eb
Labels: bug fix

#10370 {bio}[foss/2019b] AutoMap v1.0
  easybuild/easyconfigs/a/AutoMap/AutoMap-1.0-foss-2019b-20200324.eb
Labels: new

#10385 bump version and update release notes for EasyBuild v4.2.0
  RELEASE_NOTES
  setup.py
Labels: documentation

#10392 {tools}[dummy/dummy] EasyBuild v4.2.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.2.0.eb
Labels: update

#10338 PLINK version 2.00a2.3LM
  easybuild/easyconfigs/p/PLINK/PLINK-2.00a2.3_x86_64.eb
Labels: update

#10394 sync develop with master after EasyBuild v4.2.0 release + bump version to 4.2.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#10322 {geo}[foss/2019b] geopandas v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/geopandas/geopandas-0.7.0-foss-2019b-Python-3.7.4.eb
Labels: new

#10282 {lib}[GCCcore/8.3.0] GitPython v3.1.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.0-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10365 {bio}[SYSTEM] New EB build file King-2.2.4
  easybuild/easyconfigs/k/king/king-2.2.4.eb
Labels: new

#10263 {tools}[foss/2020a] IRkernel v1.1 w/ Python 3.8.2
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-foss-2020a-R-3.6.3-Python-3.8.2.eb
Labels: 2020a, update

#9826 {lang}[fosscuda/2019b] rstudio v1.2.5033
  easybuild/easyconfigs/r/rstudio/rstudio-1.2.5033-fosscuda-2019b-Java-11.eb
  easybuild/easyconfigs/r/rstudio/rstudio-1.2.5033_fix_boost_170_compat.patch
  easybuild/easyconfigs/r/rstudio/rstudio-1.2.5033_update_gwt.patch
Labels: new

#10359 {lang}[foss/2019b, fosscuda/2019b] R v3.6.2: add mRMRe and dHSIC and sync easyconfig in fosscuda
  easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb
  easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Labels: enhancement

#10407 update to XZ 5.2.5 in 2020a easyconfigs
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-gompi-2020a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-iimpi-2020a.eb
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.10.2-GCC-9.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.4.4-GCCcore-9.3.0.eb
Labels: 2020a, update

#9645 {bio}[foss/2019a] FIX 1.06.12 (Octave) w/ FSL 6.0.2
  easybuild/easyconfigs/f/FIX/FIX-1.06.12-foss-2019a-Octave-Python-3.7.2.eb
  easybuild/easyconfigs/f/FSL/FSL-6.0.2-foss-2019a-Python-3.7.2.eb
Labels: new, update

#10386 {tools}[GCCcore/8.3.0] GDCM v3.0.5
  easybuild/easyconfigs/g/GDCM/GDCM-3.0.5-GCCcore-8.3.0.eb
Labels: update

#10351 {phys}[foss/2019b] dftd3-lib v0.9, DFTB+ v19.1 w/ Python 2.7.16
  easybuild/easyconfigs/d/DFTB+/DFTB+-19.1-foss-2019b-Python-2.7.16-mpi.eb
  easybuild/easyconfigs/d/DFTB+/DFTB+-19.1-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.9-GCC-8.3.0.eb
  easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.9_fix-extras-syntax.patch
Labels: new, update

#10411 {lang}[GCCcore/9.3.0] Perl v5.30.2
  easybuild/easyconfigs/e/expat/expat-2.2.9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: 2020a, update

#10415 {bio}[GCC/8.3.0] StringTie v2.1.1
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.1-GCC-8.3.0.eb
Labels: update

#10408 [GCCCore/8.3.0] add Perl as a build dependency for Autoconf/Automake
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-8.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-8.3.0.eb
Labels: bug fix

#10414 add patch for AutoMap to avoid that it to create a log file in installation directory
  easybuild/easyconfigs/a/AutoMap/AutoMap-1.0-foss-2019b-20200324.eb
  easybuild/easyconfigs/a/AutoMap/AutoMap-1.0-foss-2019b-20200324_fix-log.patch
Labels: bug fix

#10419 AutoMap v1.0: remove patch leftovers
  easybuild/easyconfigs/a/AutoMap/AutoMap-1.0-foss-2019b-20200324.eb
Labels: change

#10410 {lang}[GCCcore/9.3.0] Python v3.8.2
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-9.3.0.eb
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libffi/libffi-3.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.31.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-9.3.0.eb
Labels: 2020a, update

#10388 Check sdist with different python versions
  .github/workflows/unit_tests.yml
Labels: bug fix

#10342 {tools}[GCC/8.3.0] Create zsh-5.8-GCC-8.3.0.eb
  easybuild/easyconfigs/z/zsh/zsh-5.8-GCC-8.3.0.eb
Labels: update

#10405 {bio}[intel/2019b] augur v7.0.2, CVXOPT v1.1.9, VCFtools 0.1.16 w/ Python 3.7.4
  easybuild/easyconfigs/a/augur/augur-7.0.2-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/c/CVXOPT/CVXOPT-1.2.4-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-iccifort-2019.5.281.eb
Labels: new, update

#10393 {chem}[intel/2019b] QuantumESPRESSO v6.5
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-intel-2019b.eb
Labels: update

#10297 {bio}[gompi/2019b] RMBlast v2.9.0
  easybuild/easyconfigs/r/RMBlast/BLAST+-2.9.0_fix_boost.patch
  easybuild/easyconfigs/r/RMBlast/RMBlast-2.9.0-gompi-2019b.eb
Labels: update

#10412 add Mozilla::CA, Test::RequiresInternet and LWP::Protocol::https extensions to Perl 5.30.x
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
Labels: enhancement

#10416 {bio}[GCCcore/8.3.0] Racon v1.4.13
  easybuild/easyconfigs/r/Racon/Racon-1.4.13-GCCcore-8.3.0.eb
Labels: update

#10426 add Perl build dep for Autoconf/Automake using GCCcore/7.3.0 and GCCcore/8.2.0 toolchains
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-7.3.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-8.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-8.2.0.eb
Labels: bug fix

#10399 {data,math}[foss/2019b] PyMC3 v3.8, netcdf4-python v1.5.3 w/ Python 3.7.4
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyMC3/PyMC3-3.8-foss-2019b-Python-3.7.4.eb
Labels: update

#10379 {data}[foss/2019b] SHAP v0.35.0 w/ Python 3.7.4
  easybuild/easyconfigs/s/SHAP/SHAP-0.35.0-foss-2019b-Python-3.7.4.eb
Labels: new

#10373 {bio}[foss/2019a] gradunwarp v1.2.0 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/f/FSL/FSL-6.0.2-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.2.0-foss-2019a-HCP-Python-2.7.15.eb
  easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.2.0-foss-2019a-HCP-Python-3.7.2.eb
Labels: update

#10425 Fix undefined reference to 'qfloat16::mantissatable' in Qt5-5.13.1-GCCcore-8.3.0
  easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.13.1_fix-mantissatable.patch
Labels: bug fix

#10401 {math}[foss/2019b] ArviZ v0.7.0 w/ Python 3.7.4
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.7.0-foss-2019b-Python-3.7.4.eb
Labels: update

#10418 disable USER-INTEL package in LAMMPS easyconfigs using intel/2019b, since it results in an installation that produces incorrect results
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/lammps_vs_yaff_test_single_point_energy.py
Labels: bug fix

#10329 {lib}[GCCcore/9.3.0] UCX v1.8.0
  easybuild/easyconfigs/u/UCX/UCX-1.8.0-GCCcore-9.3.0.eb
Labels: 2020a, update

#10280 impi v2019.6: add dependency on UCX
  easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166.eb
Labels: 2020a, enhancement

#10403 use Bison 3.3.2 as build dep for flex 2.6.4
  easybuild/easyconfigs/f/flex/flex-2.6.4.eb
Labels: change

#10446 {data}[GCCcore/8.3.0] DCMTK v3.6.5
  easybuild/easyconfigs/d/DCMTK/DCMTK-3.6.5-GCCcore-8.3.0.eb
Labels: update

#10449 {lang}[system/system] Anaconda3 version 2020.02
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2020.02.eb
Labels: update

#10447 {data}[intel/2018b] PyTables v3.4.4, numexpr v2.6.5, LZO v2.10 w/ Python 3.6.6
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/numexpr/numexpr-2.6.5-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.4.4-intel-2018b-Python-3.6.6.eb
Labels: update

#10445 {lib}[GCCcore/8.3.0] utf8proc v2.5.0
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-8.3.0.eb
Labels: update

#10053 {bio}[GCC/8.3.0] BBMap v38.79
  easybuild/easyconfigs/b/BBMap/BBMap-38.79-GCC-8.3.0.eb
Labels: update

#10444 {lib}[GCCcore/8.3.0] libuv v1.37.0
  easybuild/easyconfigs/l/libuv/libuv-1.37.0-GCCcore-8.3.0.eb
Labels: new

#10439 mention http:// Pfam website rather than ftp:// in load message of BiG-SCAPE easyconfig
  easybuild/easyconfigs/b/BiG-SCAPE/BiG-SCAPE-1.0.1-intel-2019b-Python-3.7.4.eb
Labels: change

#10417 fix source_urls in ICU easyconfigs
  easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.3.0.eb
Labels: bug fix

#10277 Mesa v20.0.2: add comment informing about manually setting Gallium drivers
  easybuild/easyconfigs/m/Mesa/Mesa-20.0.2-GCCcore-9.3.0.eb
Labels: 2020a, change

#10458 Clang 7.0.1 on GCC 7.3.0-2.30 - included LLVM linker
  easybuild/easyconfigs/c/Clang/Clang-7.0.1-GCC-7.3.0-2.30.eb
Labels: enhancement

#10456 update extensions in Python 3.8.2 easyconfig
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
Labels: update

#10452 {tools}[foss/2019b] pysndfx v0.3.6, SoX v14.4.2 w/ Python 3.7.4
  easybuild/easyconfigs/p/pysndfx/pysndfx-0.3.6-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCC-8.3.0.eb
Labels: new

#10422 {lib}[intel/2019a] GlobalArrays v5.7.2
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.7.2-intel-2019a-peigs.eb
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.7.2-intel-2019a.eb
Labels: update

#10398 {chem}[intel/2019b] Multiwfn v3.6
  easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.6-intel-2019b.eb
Labels: update

#10457 update to Python 2.7.18 + minor updates for extensions
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-gompi-2020a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-iimpi-2020a.eb
  easybuild/easyconfigs/g/GATK/GATK-4.1.5.0-GCCcore-9.3.0-Java-11.eb
  easybuild/easyconfigs/m/Mako/Mako-1.1.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-5.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-9.3.0.eb
  easybuild/easyconfigs/s/SCons/SCons-3.1.2-GCCcore-9.3.0.eb
Labels: 2020a, update

#10453 {devel}[GCCcore/8.3.0] libgit2 v1.0.0
  easybuild/easyconfigs/l/libgit2/libgit2-1.0.0-GCCcore-8.3.0.eb
Labels: new

#10464 minimap2 (foss-2018b and GCC-8.2.0*) include static lib and header
  easybuild/easyconfigs/m/minimap2/minimap2-2.13-foss-2018b.eb
  easybuild/easyconfigs/m/minimap2/minimap2-2.17-GCC-8.2.0-2.31.1.eb
Labels: enhancement

#7735 {bio}[foss/2018b] MitoZ v2.3, ETE v3.1.1, tbl2asn v20190117
  easybuild/easyconfigs/e/ETE/ETE-3.1.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/MitoZ/MitoZ-2.3-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/t/tbl2asn/tbl2asn-20200302-linux64.eb
Labels: new, update

#10472 avoid double - in versionsuffix of torchtext easyconfig
  easybuild/easyconfigs/t/torchtext/torchtext-0.5.0-fosscuda-2019b-PyTorch-1.4.0-Python-3.7.4.eb
Labels: bug fix

#10463 {chem}[foss/2019b] MDTraj v1.9.3 w/ Python 3.7.4
  easybuild/easyconfigs/m/MDTraj/MDTraj-1.9.3-foss-2019b-Python-3.7.4.eb
Labels: update

#10455 {math}[GCCcore/8.3.0] CPLEX v12.10 w/ Python 3.7.4
  easybuild/easyconfigs/c/CPLEX/CPLEX-12.10-GCCcore-8.3.0-Python-3.7.4.eb
Labels: update

#10473 Move new GlobalArrays configs to 2019b
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.7.2-intel-2019b-peigs.eb
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.7.2-intel-2019b.eb
Labels: update

#10070 {bio}[gompi/2019b] NGS v2.10.4, ncbi-vdb v2.10.4, SRA-Toolkit v2.10.4, ... w/ Python 2.7.16
  easybuild/easyconfigs/f/file/file-5.38-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/NGS-Python/NGS-Python-2.10.4-gompi-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/n/NGS-Python/NGS-Python-2.10.4_fix-prefix.patch
  easybuild/easyconfigs/n/NGS/NGS-2.10.4-GCCcore-8.3.0-Java-11.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-2.10.4-gompi-2019b.eb
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-2.10.4-gompi-2019b.eb
Labels: update

#10134 {bio}[foss/2019b] FusionCatcher v1.20 w/ Python 2.7.16
  easybuild/easyconfigs/f/FusionCatcher/FusionCatcher-1.20-foss-2019b-Python-2.7.16.eb
Labels: new

#10248 {bio}[foss/2020a] SAMtools v1.10
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.10-GCC-9.3.0.eb
Labels: 2020a, update

#10424 Two new ROOT-based Python numeric modules, for use with HEP analysis code
  easybuild/easyconfigs/r/root_numpy/root_numpy-4.8.0-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/r/rootpy/rootpy-1.0.1-foss-2018b-Python-3.6.6.eb
Labels: new, update

#10387 {tools}[fosscuda/2019b] gpustat v0.6.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/gpustat/gpustat-0.6.0-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#10434 {bio}[system/system] SRA-Toolkit v2.10.5
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-2.10.5-centos_linux64.eb
Labels: update

#10397 {perf}[gompic/2019b] Score-P 6.0 and dependencies
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.4.4-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.4.3-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/PAPI/PAPI-6.0.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.6-GCCcore-8.3.0-tools.eb
  easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompic-2019b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#10481 update hwloc to 2.2.0 for 2020a easyconfigs
  easybuild/easyconfigs/h/hwloc/hwloc-2.2.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-GCC-9.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.1.5-GCCcore-9.3.0.eb
Labels: 2020a, update

#10480 fix Mako easyconfigs using a */2018* toolchain
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018.01-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/m/Mako/Mako-1.0.7-iomkl-2018a-Python-2.7.14.eb
Labels: bug fix

#10406 {chem}[foss/2020a] LAMMPS v3Mar2020 w/ Python 3.8.2
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2020a-Python-3.8.2-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/lammps-stable_3Mar2020_hack_openmp_gcc9.patch
Labels: 2020a, update

#10475 {vis}[GCC/8.3.0] wxWidgets v3.1.3
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.16.2-GCC-8.3.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.16.2-GCC-8.3.0.eb
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.10-GCCcore-8.3.0.eb
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.1.3-GCC-8.3.0.eb
Labels: update

#10420 {vis}[GCCcore/9.3.0] gnuplot v5.2.8, Lua v5.3.5, libcerf v1.13, libgd v2.3.0
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.8-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/Lua/Lua-5.3.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libcerf/libcerf-1.13-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libgd/libgd-2.3.0-GCCcore-9.3.0.eb
Labels: 2020a, update
