Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-06, with the labels that each got.

#12995 use version of Fujitsu compiler instead of our version for the Fujitsu toolchain
  easybuild/easyconfigs/b/buildenv/buildenv-default-FCC-4.5.0.eb
  easybuild/easyconfigs/f/FCC/FCC-4.5.0.eb
Labels: Fujitsu, change

#12996 {lang,tools}[FCC/4.5.0] binutils v2.36.1, Bison v3.7.6, flex v2.6.4, ...
  easybuild/easyconfigs/b/Bison/Bison-3.7.6-FCC-4.5.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1-FCC-4.5.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-FCC-4.5.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.48.3-FCC-4.5.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-FCC-4.5.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-FCC-4.5.0.eb
Labels: Fujitsu, update

#12993 {bio}[foss/2020b] SeuratData v20210514
  easybuild/easyconfigs/s/SeuratData/SeuratData-20210514-foss-2020b-R-4.0.3.eb
Labels: new

#12753 Add patches for PyTorch 1.7.1 avoiding failures on POWER and A100
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-foss-2020b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-fosscuda-2020b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_disable-failing-cuda-11.2-tests.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_disable-tf32-in-distributed-tests.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_fix-alias-violation-in-bitwise-ops.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_fix-err-variable.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_relax_precision_in_test_nn.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_run-large-tests-on-GPU.patch
Labels: bug fix

#12997 {tools}[FCC/4.5.0] Perl v5.32.1, DB v18.1.40, expat v2.2.9, groff v1.22.4, ...
  easybuild/easyconfigs/d/DB/DB-18.1.40-FCC-4.5.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.9-FCC-4.5.0.eb
  easybuild/easyconfigs/g/groff/groff-1.22.4-FCC-4.5.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-FCC-4.5.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-FCC-4.5.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-FCC-4.5.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.32.1-FCC-4.5.0.eb
Labels: Fujitsu, update

#12994 {bio}[foss/2020b] SeuratWrappers v20210528
  easybuild/easyconfigs/s/SeuratWrappers/SeuratWrappers-20210528-foss-2020b-R-4.0.3.eb
Labels: new

#12998 {devel}[FCC/4.5.0] Autoconf v2.71, Automake v1.16.3, Autotools v20210128, ...
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-FCC-4.5.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.3-FCC-4.5.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20210128-FCC-4.5.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-FCC-4.5.0.eb
Labels: Fujitsu, update

#13000 {perf,toolchain}[ffmpi/4.5.0,system/system] ffmpi v4.5.0, OSU-Micro-Benchmarks v5.7.1
  easybuild/easyconfigs/f/ffmpi/ffmpi-4.5.0.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-ffmpi-4.5.0.eb
Labels: Fujitsu, new, update

#12999 {numlib}[FCC/4.5.0] FFTW v1.0.0-fujitsu
  easybuild/easyconfigs/f/FFTW/FFTW-1.0.0-FCC-4.5.0-fujitsu.eb
Labels: Fujitsu, update

#13001 {devel,toolchain,tools}[Fujitsu/21.05] Fujitsu v21.05, HPL v2.3, buildenv vdefault
  easybuild/easyconfigs/b/buildenv/buildenv-default-Fujitsu-21.05.eb
  easybuild/easyconfigs/f/Fujitsu/Fujitsu-21.05.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-Fujitsu-21.05.eb
Labels: Fujitsu, new, update

#13005 add lslx, regsem, semPLS extensions to R v4.0.3 and v4.0.4
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
Labels: enhancement

#13009 prepare release notes for EasyBuild v4.4.0 + bump version to 4.4.0
  RELEASE_NOTES
  setup.py
Labels: update

#12972 {tools}[GCCcore/10.2.0] patchelf v0.12
  easybuild/easyconfigs/p/patchelf/patchelf-0.12-GCCcore-10.2.0.eb
Labels: update

#13012 {tools}[dummy/dummy] EasyBuild v4.4.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.0.eb
Labels: update

#13013 sync with main + bump version to 4.4.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#13014 add checksum for aarch64 installation file for CUDAcore 11.1.1
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.1.1.eb
Labels: EESSI, bug fix

#12989 {bio}[foss/2020b] WhatsHap v1.1 w/ Python 3.8.6
  easybuild/easyconfigs/w/WhatsHap/WhatsHap-1.1-foss-2020b.eb
Labels: new

#13008 add elfutils as build dependency for Clang 11.0.1 built with gcccuda toolchain
  easybuild/easyconfigs/c/Clang/Clang-11.0.1-gcccuda-2020b.eb
Labels: bug fix

#12572 {compiler}[system/system] NVHPC v21.3
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.3.eb
Labels: update

#13028 {compiler}[system/system] NVHPC v21.5
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.5.eb
Labels: update

#13029 {devel}[system/system] M4 v1.4.19
  easybuild/easyconfigs/m/M4/M4-1.4.19.eb
Labels: update

#13026 {phys}[GCCcore/10.3.0] UDUNITS v2.2.28
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28-GCCcore-10.3.0.eb
Labels: update

#13024 {numlib}[GCC/10.3.0] GSL v2.7
  easybuild/easyconfigs/g/GSL/GSL-2.7-GCC-10.3.0.eb
Labels: update

#13021 Update R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
Labels: enhancement

#13020 {lang}[foss/2020b] add new cheksum of mvabund to R v4.0.4
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
Labels: enhancement

#13010 {geo}[foss/2020b] microctools v0.1.0-20201209, rgdal v1.5-23 w/ R v4.0.4
  easybuild/easyconfigs/m/microctools/microctools-0.1.0-20201209-foss-2020b-R-4.0.4.eb
  easybuild/easyconfigs/r/rgdal/rgdal-1.5-23-foss-2020b-R-4.0.4.eb
Labels: new, update

#13004 {compiler}[system/system] GCC v9.4.0
  easybuild/easyconfigs/b/Bison/Bison-3.7.6-GCCcore-9.4.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1-GCCcore-9.4.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-9.4.0.eb
  easybuild/easyconfigs/g/GCC/GCC-9.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.4.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.48.3-GCCcore-9.4.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-9.4.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-9.4.0.eb
Labels: update

#13019 {phys}[GCC/10.2.0] Geant4 v10.7.1 add missing cmake option to actually use external CLHEP
  easybuild/easyconfigs/g/Geant4/Geant4-10.7.1-GCC-10.2.0.eb
Labels: bug fix

#12971 {devel,lib}[GCCcore/10.2.0] dSFMT v2.2.5, Autoconf-archive v2021.02.19
  easybuild/easyconfigs/a/Autoconf-archive/Autoconf-archive-2021.02.19-GCCcore-10.2.0.eb
  easybuild/easyconfigs/d/dSFMT/dSFMT-2.2.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/d/dSFMT/dSFMT-2.2.5_autotools.patch
Labels: new, update

#12969 {bio}[GCCcore/10.2.0] OBITools3 v3.0.1b8 w/ Python 3.8.6
  easybuild/easyconfigs/o/OBITools3/OBITools3-3.0.1b8-GCCcore-10.2.0.eb
Labels: new

#12970 {lib}[GCCcore/10.2.0] MbedTLS v2.26.0
  easybuild/easyconfigs/m/MbedTLS/MbedTLS-2.26.0-GCCcore-10.2.0.eb
Labels: new

#13025 {lang}[GCCcore/10.3.0] nodejs v14.17.0
  easybuild/easyconfigs/n/nodejs/nodejs-14.17.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-14.17.0_fix-argument-list-too-long.patch
Labels: update

#13022 {lib}[GCCcore/10.3.0] ICU v69.1
  easybuild/easyconfigs/i/ICU/ICU-69.1-GCCcore-10.3.0.eb
Labels: update

#12990 {bio}[GCC/10.2.0] bcl2fastq2 v2.20.0
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-10.2.0.eb
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-find-boost.patch
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-fix-cmake-target-libs.patch
Labels: update

#13027 {vis}[GCCcore/10.3.0] Ghostscript v9.54.0, ImageMagick v7.0.11-14, LittleCMS v2.12
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.54.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.11-14-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LittleCMS/LittleCMS-2.12-GCCcore-10.3.0.eb
Labels: update

#13031 {vis}[GCCcore/10.3.0] Xvfb v1.20.11
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.11-GCCcore-10.3.0.eb
Labels: update

#13023 {vis}[GCCcore/10.3.0] Tk v8.6.11
  easybuild/easyconfigs/t/Tk/Tk-8.6.11-GCCcore-10.3.0.eb
Labels: update

#12898 {bio}[GCCcore/9.3.0] snpEff v5.0 w/ Python 3.8.2
  easybuild/easyconfigs/s/snpEff/snpEff-5.0-GCCcore-9.3.0-Java-13-Python-3.8.2.eb
Labels: update

#12901 {bio}[GCCcore/9.3.0] canu v2.1.1
  easybuild/easyconfigs/c/canu/canu-2.1.1-GCCcore-9.3.0-Java-11.eb
Labels: update

#12947 {math}[foss/2020b] CVXOPT v1.2.6 w/ Python 3.8.6
  easybuild/easyconfigs/c/CVXOPT/CVXOPT-1.2.6-foss-2020b.eb
Labels: update

#12949 {tools}[foss/2020b] Quandl v3.6.1 w/ Python 3.8.6
  easybuild/easyconfigs/q/Quandl/Quandl-3.6.1-foss-2020b.eb
Labels: update

#12956 {bio}[GCC/10.2.0] pyspoa v0.0.8, spoa v4.0.7 w/ Python 3.8.6
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.8-GCC-10.2.0.eb
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.8_use-spoa-dep.patch
  easybuild/easyconfigs/s/spoa/spoa-4.0.7-GCC-10.2.0.eb
Labels: update

#13037 {compiler}[system/system] Go v1.16.5
  easybuild/easyconfigs/g/Go/Go-1.16.5.eb
Labels: update

#13041 remove misleading comment from Python >= 3.7 easyconfigs, libffi is now also required for python itself (no longer bundled)
  easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.0-iomkl-2018b.eb
  easybuild/easyconfigs/p/Python/Python-3.7.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.7.4-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.9.5-GCCcore-10.3.0.eb
Labels: change

#13035 add bare Python 3.9.5 easyconfig and use that as builddep for LLVM 11.1.0
  easybuild/easyconfigs/l/LLVM/LLVM-11.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.9.5-GCCcore-10.3.0-bare.eb
Labels: change, update

#13042 add patch to fix numpy test_ccompiler_opt in SciPy-bundle v2021.05
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-foss-2021a.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.20.3_fix-target-test-ccompiler-opt.patch
Labels: bug fix

#9902 {cae}[foss/2019b] FreeFEM v4.5
  easybuild/easyconfigs/f/FreeFEM/FreeFEM-4.5-foss-2019b-Python-3.7.4.eb
Labels: new

#13033 {bio}[foss/2020b] ont-fast5-api v3.3.0 w/ Python 3.8.6
  easybuild/easyconfigs/o/ont-fast5-api/ont-fast5-api-3.3.0-foss-2020b.eb
Labels: new

#13053 {lib}[system/system] NCCL v2.9.9
  easybuild/easyconfigs/n/NCCL/NCCL-2.9.9-CUDA-11.3.1.eb
Labels: update

#13059 add patch to fix installation of HDF 4.2.15 on aarch64
  easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-10.2.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-9.3.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.15_fix-aarch64.patch
Labels: bug fix

#13056 {data}[iimpi/2021a] netCDF v4.8.0, HDF5 v1.10.7
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-iimpi-2021a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.8.0-iimpi-2021a.eb
Labels: update

#13030 {data}[foss/2021a] GDAL v3.3.0, GEOS v3.9.1, HDF v4.2.15, ... w/ Python 3.9.5
  easybuild/easyconfigs/g/GDAL/GDAL-3.3.0-foss-2021a.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.9.1-GCC-10.3.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-10.3.0.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-gompi-2021a.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.6.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libtirpc/libtirpc-1.3.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.8.0-gompi-2021a.eb
  easybuild/easyconfigs/p/PROJ/PROJ-8.0.1-GCCcore-10.3.0.eb
Labels: update

#13061 make sure that MbedTLS' Makefile uses 'python' rather than 'python2'
  easybuild/easyconfigs/m/MbedTLS/MbedTLS-2.26.0-GCCcore-10.2.0.eb
Labels: bug fix

#13051 {perf}[GCCcore/10.3.0] PAPI v6.0.0.1
  easybuild/easyconfigs/p/PAPI/PAPI-6.0.0.1-GCCcore-10.3.0.eb
Labels: update

#13039 Add GxEScanR extension to R/4.0.3, R/4.0.4 foss/2020b
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
Labels: enhancement

#13049 {chem}[GCCcore/10.2.0] openkim-models v20210128
  easybuild/easyconfigs/o/openkim-models/openkim-models-20210128-GCCcore-10.2.0.eb
Labels: update

#12877 {bio}[foss/2020b] CSB v1.2.5 w/ Python 3.8.6
  easybuild/easyconfigs/c/CSB/CSB-1.2.5-foss-2020b.eb
Labels: new

#13036 {bio}[system/system] picard v2.25.5
  easybuild/easyconfigs/p/picard/picard-2.25.5-Java-13.eb
Labels: update

#13034 disable debuginfod for elfutils to minimize required dependencies
  easybuild/easyconfigs/e/elfutils/elfutils-0.182-GCCcore-9.3.0.eb
  easybuild/easyconfigs/e/elfutils/elfutils-0.183-GCCcore-10.2.0.eb
Labels: change

#12957 {chem}[GCCcore/10.2.0] XCFun v2.1.1
  easybuild/easyconfigs/x/XCFun/XCFun-2.1.1-GCCcore-10.2.0.eb
Labels: update

#12864 {phys}[foss/2020b,intel/2020b] PSolver v1.8.3
  easybuild/easyconfigs/f/futile/futile-1.8.3-foss-2020b.eb
  easybuild/easyconfigs/f/futile/futile-1.8.3-intel-2020b.eb
  easybuild/easyconfigs/f/futile/futile_intel_bug.patch
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-foss-2020b.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-intel-2020b.eb
Labels: new, update

#12789 {tools}[foss/2020a] IRkernel v1.2 w/ Python 3.8.2
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.2-foss-2020a-R-4.0.0-Python-3.8.2.eb
Labels: update

#13003 {bio}[GCC/10.2.0] AMPHORA2 v20190730, EMBOSS v6.6.0, libharu v2.3.0, ...
  easybuild/easyconfigs/a/AMPHORA2/AMPHORA2-20190730-gompi-2020b-Java-13-pthreads-avx2.eb
  easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-GCC-10.2.0-Java-13.eb
  easybuild/easyconfigs/l/libharu/libharu-2.3.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-GCC-10.2.0-pthreads-avx2.eb
Labels: new, update

#13062 fix checksum for snpEff 5.0
  easybuild/easyconfigs/s/snpEff/snpEff-5.0-Java-13.eb
Labels: bug fix

#13015 add elfutils as build dependency for Clang 8.0.x and 9.0.1 easyconfigs that have a CUDA dependency
  easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCCcore-8.2.0-CUDA-10.1.105.eb
  easybuild/easyconfigs/c/Clang/Clang-8.0.1-GCC-8.2.0-2.31.1-CUDA-10.1.105.eb
  easybuild/easyconfigs/c/Clang/Clang-8.0.1-GCC-8.3.0-CUDA-10.1.243.eb
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb
  easybuild/easyconfigs/e/elfutils/elfutils-0.185-GCCcore-8.2.0.eb
  easybuild/easyconfigs/e/elfutils/elfutils-0.185-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libmicrohttpd/libmicrohttpd-0.9.73-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libmicrohttpd/libmicrohttpd-0.9.73-GCCcore-8.3.0.eb
Labels: bug fix

#13068 {bio}[GCCcore/10.2.0] minimap2 v2.20
  easybuild/easyconfigs/m/minimap2/minimap2-2.20-GCCcore-10.2.0.eb
Labels: update

#13048 {bio}[foss/2020b] RegTools v0.4.2
  easybuild/easyconfigs/r/RegTools/RegTools-0.4.2-foss-2020b.eb
Labels: update

#13063 {tools}[GCCcore/10.3.0] git v2.32.0
  easybuild/easyconfigs/g/git/git-2.32.0-GCCcore-10.3.0-nodocs.eb
Labels: update

#12921 {compiler}[system/system] futhark v0.19.5
  easybuild/easyconfigs/f/futhark/futhark-0.19.5.eb
Labels: new

#6880 download sources via git for XGBoost 20171120 easyconfig due to use of submodules
  easybuild/easyconfigs/x/XGBoost/XGBoost-20171120-intel-2017b-Java-1.8.0_152.eb
Labels: bug fix, change

#12539 {lang}[foss/2020b,fosscuda/2020b] R v4.0.5
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
Labels: update

#13032 {lang}[foss/2021a] R v4.1.0
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
  easybuild/easyconfigs/r/R/R-4.1.0_identify-flexiblas-in-configure.patch
Labels: update

#12414 {vis}[foss/2020b,fosscuda/2020b] VMD v1.9.4a51
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a51-foss-2020b.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a51-fosscuda-2020b.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a51_configure.patch
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a51_extra_colors.patch
Labels: update

#12664 {cae}[foss/2020b] Nektar++ v5.0.1
  easybuild/easyconfigs/n/Nektar++/Nektar++-5.0.1-foss-2020b.eb
Labels: new

#12961 {devel}[gcccuda/2020b] hipify-clang 4.2.0
  easybuild/easyconfigs/h/hipify-clang/hipify-clang-4.2.0-gcccuda-2020b.eb
Labels: new

#13086 add patch for GCC 10.2.0 to fix internal compiler error on aarch64
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0_fix-ice-on-arm.patch
Labels: bug fix

#13080 Add preinstallopts for minimap2 to fix installation on aarch64
  easybuild/easyconfigs/f/Flye/Flye-2.8.3-GCC-10.2.0.eb
Labels: aarch64, bug fix

#13087 Add gipaw to QuantumESPRESSO/6.7
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-foss-2019b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-intel-2019b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-iomkl-2019b.eb
Labels: enhancement

#13089 {devel}[GCCcore/10.3.0] glew v2.1.0
  easybuild/easyconfigs/g/glew/glew-2.1.0-GCCcore-10.3.0.eb
Labels: update

#13066 {math}[gompi/2021a] SCOTCH v6.1.0
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2021a.eb
Labels: update

#13083 {bio}[fosscuda/2020b] Bonito v0.4.0 + GenomeWorks v2021.02.2
  easybuild/easyconfigs/b/Bonito/Bonito-0.4.0-fosscuda-2020b.eb
  easybuild/easyconfigs/g/GenomeWorks/GenomeWorks-2021.02.2-fosscuda-2020b.eb
  easybuild/easyconfigs/o/ont-fast5-api/ont-fast5-api-3.3.0-fosscuda-2020b.eb
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.8-GCC-10.2.0.eb
Labels: new, update

#13090 {lib}[GCCcore/10.3.0] freeglut v3.2.1
  easybuild/easyconfigs/f/freeglut/freeglut-3.2.1-GCCcore-10.3.0.eb
Labels: update

#13076 Use github source for LIBSVM 3.24
  easybuild/easyconfigs/l/LIBSVM/LIBSVM-3.24-GCCcore-9.3.0.eb
Labels: update

#13093 {data}[gompi/2021a,iimpi/2021a] netCDF-Fortran v4.5.3
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.3-gompi-2021a.eb
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.3-iimpi-2021a.eb
Labels: update

#13071 {lib}[GCCcore/10.2.0] NCCL v2.8.3
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.3-GCCcore-10.2.0-CUDA-11.1.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.3_fix-isend-irecv.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#13064 {chem}[GCC/10.3.0,intel-compilers/2021.2.0] libxc v4.3.4, libxc v5.1.4
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.4-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.4-intel-compilers-2021.2.0.eb
Labels: update

#12553 {bio}[GCC/10.2.0] VEP 103.1
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/v/VEP/VEP-103.1-GCC-10.2.0.eb
Labels: update

#13091 {math}[foss/2021a,intel/2021a] ELPA v2021.05.001
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.001-foss-2021a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.001-intel-2021a.eb
Labels: update

#13109 {chem}[foss/2021a,intel/2021a] QuantumESPRESSO v6.7
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-foss-2021a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-intel-2021a.eb
Labels: update

#13122 {lib}[GCCcore/10.3.0] Judy v1.0.5
  easybuild/easyconfigs/j/Judy/Judy-1.0.5-GCCcore-10.3.0.eb
Labels: update

#13121 {tools}[GCCcore/10.3.0] Z3 v4.8.11
  easybuild/easyconfigs/z/Z3/Z3-4.8.11-GCCcore-10.3.0.eb
Labels: update

#12909 {compiler}[GCCcore/10.2.0,gcccuda/2020b] AOMP v13.0.2
  easybuild/easyconfigs/a/AOMP/AOMP-13.0-2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/AOMP/AOMP-13.0-2-gcccuda-2020a.eb
  easybuild/easyconfigs/a/AOMP/AOMP-13.0-2_remove_hardcoded_paths.patch
Labels: new

#13102 use new custom easyblock in torchvision easyconfigs
  easybuild/easyconfigs/t/torchvision/torchvision-0.3.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.4.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.4.2-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.5.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.4.0.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.7.0-foss-2019b-Python-3.7.4-PyTorch-1.6.0.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.7.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.6.0-imkl.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.7.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.6.0.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.8.2-fosscuda-2019b-Python-3.7.4-PyTorch-1.7.1.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.8.2-fosscuda-2020b-PyTorch-1.7.1.eb
Labels: code cleanup

#13092 add missing source URL for sortedcollections in GenomeWorks easyconfig
  easybuild/easyconfigs/g/GenomeWorks/GenomeWorks-2021.02.2-fosscuda-2020b.eb
Labels: bug fix

#13104 {bio}[GCC/10.2.0] GenomeTools v1.6.1
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.6.1-GCC-10.2.0.eb
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.6.1_fix-GCC-10.patch
Labels: update

#13096 {devel}[system] ReFrame v3.6.2
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.6.2.eb
Labels: update

#13135 {compiler}[system/system] ispc v1.16.0
  easybuild/easyconfigs/i/ispc/ispc-1.16.0.eb
Labels: update

#10719 {math}[foss/2019b] FEniCS v2019.1.0, DOLFIN v2019.1.0.post0, FFC v2019.1.0.post0, ... w/ Python 3.7.4
  easybuild/easyconfigs/d/DOLFIN/DOLFIN-2019.1.0.post0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/d/dijitso/dijitso-2019.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/f/FEniCS/FEniCS-2019.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/f/FFC/FFC-2019.1.0.post0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/f/FIAT/FIAT-2019.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PLY/PLY-3.11-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/petsc4py/petsc4py-3.12.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/slepc4py/slepc4py-3.12.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/u/UFL/UFL-2019.1.0-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#13103 switch to NCCL 2.8.3 built from source for CuPy, Horovod, libgpuarray, PyTorch and TensorFlow using fosscuda/2020b (+ add missing astor extension for TensorFlow)
  easybuild/easyconfigs/c/CuPy/CuPy-8.5.0-fosscuda-2020b.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.3-fosscuda-2020a-TensorFlow-2.3.1-Python-3.8.2.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.3-fosscuda-2020b-PyTorch-1.7.1.eb
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2020b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-fosscuda-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fosscuda-2020b.eb
Labels: bug fix, change

#13129 {compiler,lang,tools}[GCCcore/8.4.0] GCC v8.4.0, binutils v2.32, flex v2.6.4, ...
  easybuild/easyconfigs/b/Bison/Bison-3.3.2-GCCcore-8.4.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1-GCCcore-8.4.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.4.0.eb
  easybuild/easyconfigs/g/GCC/GCC-8.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.4.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.47.8-GCCcore-8.4.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.4.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-8.4.0.eb
Labels: update

#11252 {bio}[gcccuda/2019b] Beast v2.6.3, beagle-lib v3.1.2, MrBayes v3.2.7
  easybuild/easyconfigs/b/Beast/Beast-2.6.3-gcccuda-2019b.eb
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.1.2-gcccuda-2019b.eb
  easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.7-gompic-2019b.eb
Labels: update

#13145 {chem}[GCC/10.3.0] libxc v5.1.5
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-GCC-10.3.0.eb
Labels: update

#13170 {bio}[gompi/2020b,GCC/10.2.0] MrBayes v3.2.7, Beast v2.6.4, beagle-lib v3.1.2
  easybuild/easyconfigs/b/Beast/Beast-2.6.4-GCC-10.2.0.eb
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.1.2-GCC-10.2.0.eb
  easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.7-gompi-2020b.eb
Labels: update

#13146 {tools}[GCCcore/10.3.0] Mercurial v5.8 w/ Python 3.9.5
  easybuild/easyconfigs/m/Mercurial/Mercurial-5.8-GCCcore-10.3.0.eb
Labels: update

#13098 {data}[GCCcore/10.3.0] LAME v3.100
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-10.3.0.eb
Labels: update

#13176 {lib}[GCCcore/10.2.0] RE2 v2021-06-01
  easybuild/easyconfigs/r/RE2/RE2-2021-06-01-GCCcore-10.2.0.eb
Labels: update

#13169 {bio}[GCC/10.2.0] tabixpp v1.1.0
  easybuild/easyconfigs/t/tabixpp/tabixpp-1.1.0-GCC-10.2.0.eb
Labels: update

#13173 {tools}[GCCcore/10.2.0] gperftools v2.9.1
  easybuild/easyconfigs/g/gperftools/gperftools-2.9.1-GCCcore-10.2.0.eb
Labels: update

#13171 {vis}[foss/2020b] tensorboardX v2.2, torchvision v0.8.2 w/ Python 3.8.6
  easybuild/easyconfigs/t/tensorboardX/tensorboardX-2.2-foss-2020b-PyTorch-1.7.1.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.8.2-foss-2020b-PyTorch-1.7.1.eb
Labels: update

#13177 {vis}[fosscuda/2020b] tensorboardX v2.2 w/ Python 3.8.6
  easybuild/easyconfigs/t/tensorboardX/tensorboardX-2.2-fosscuda-2020b-PyTorch-1.7.1.eb
Labels: update

#13167 {math}[foss/2020b,intel/2020b] LMfit v1.0.2 w/ Python 3.8.6
  easybuild/easyconfigs/l/LMfit/LMfit-1.0.2-foss-2020b.eb
  easybuild/easyconfigs/l/LMfit/LMfit-1.0.2-intel-2020b.eb
Labels: update

#13157 {tools}[gompi/2020b] IOR v3.3.0
  easybuild/easyconfigs/i/IOR/IOR-3.3.0-gompi-2020b.eb
Labels: update

#12906 {lib}[foss/2020b,fosscuda/2020b] TensorFlow v2.5.0 w/ Python 3.8.6
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-fix-alias-violation-in-absl.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-foss-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-fosscuda-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_add-default-shell-env.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_add-protobuf-deps.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_add-support-for-large-core-systems.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_disable-avx512-extensions.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix-alignment-in-matmul-test.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix-arm-vector-intrinsics.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_remove-duplicate-gpu-tests.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_remove-keras-nightly-dependency.patch
Labels: update

#12985 {chem}[foss/2020a,fosscuda/2020a] Amber v20.11-AmberTools-20.15 w/ Python 3.8.2
  easybuild/easyconfigs/a/Amber/Amber-20.11-foss-2020a-AmberTools-20.15-Python-3.8.2.eb
  easybuild/easyconfigs/a/Amber/Amber-20.11-fosscuda-2020a-AmberTools-20.15-Python-3.8.2.eb
  easybuild/easyconfigs/a/Amber/AmberTools-20_cmake-locate-netcdf.patch
  easybuild/easyconfigs/a/Amber/AmberTools-20_fix_missing_MPI_LIBRARY_error.patch
Labels: update

#13185 {numlib}[intel/2021a] FFTW v3.3.9
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.9-intel-2021a.eb
Labels: update

#13187 {data}[gompi/2020b,gompic/2020b] PnetCDF v1.12.2
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.2-gompi-2020b.eb
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.2-gompic-2020b.eb
Labels: update

#13184 {mpi}[GCC/10.3.0] OpenMPI v4.0.6
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.6-GCC-10.3.0.eb
Labels: update

#13156 {devel}[system/system] CMake v3.18.4
  easybuild/easyconfigs/c/CMake/CMake-3.18.4.eb
Labels: update

#13072 {lang}[GCCcore/10.3.0] FriBidi v1.0.10
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.10-GCCcore-10.3.0.eb
Labels: update

#13181 Fix uniq operation in TensorFlow 2.4.1
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fix-alias-violation-in-absl.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1_skip-unique-string-test.patch
Labels: bug fix

#13193 {vis}[GCCcore/10.3.0] FFmpeg v4.3.2
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.3.2-GCCcore-10.3.0.eb
Labels: update

#13206 {bio}[GCC/10.2.0] Exonerate v2.4.0
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-10.2.0.eb
Labels: update

#13203 {system}[GCCcore/10.3.0] GnuTLS v3.7.2
  easybuild/easyconfigs/g/GnuTLS/GnuTLS-3.7.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/Guile/Guile-2.2.7-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gc/gc-8.0.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libtasn1/libtasn1-4.17.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libunistring/libunistring-0.9.10-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/p11-kit/p11-kit-0.24.0-GCCcore-10.3.0.eb
Labels: update

#13192 {devel}[GCCcore/10.3.0] GObject-Introspection v1.68.0 w/ Python 3.9.5
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.68.0-GCCcore-10.3.0.eb
Labels: update

#13191 {math}[system/system] MCR vR2021a
  easybuild/easyconfigs/m/MCR/MCR-R2021a.3.eb
Labels: update

#13194 {devel}[GCCcore/10.3.0] nsync v1.24.0
  easybuild/easyconfigs/n/nsync/nsync-1.24.0-GCCcore-10.3.0.eb
Labels: update

#13067 {math}[GCCcore/10.3.0] METIS v5.1.0
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-10.3.0.eb
Labels: update

#13095 {vis}[GCCcore/10.3.0] GL2PS v1.4.2
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.2-GCCcore-10.3.0.eb
Labels: update

#13110 {vis}[foss/2021a] VTK v9.0.1 w/ Python 3.9.5
  easybuild/easyconfigs/v/VTK/VTK-9.0.1-foss-2021a.eb
Labels: update

#13140 {devel}[GCCcore/10.3.0] flatbuffers v2.0.0
  easybuild/easyconfigs/f/flatbuffers/flatbuffers-2.0.0-GCCcore-10.3.0.eb
Labels: update

#13154 {tools}[gompi/2021a] IOR v3.3.0
  easybuild/easyconfigs/i/IOR/IOR-3.3.0-gompi-2021a.eb
Labels: update

#13161 {devel}[GCCcore/10.3.0] pkgconfig v1.5.4 w/ Python 3.9.5
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.5.4-GCCcore-10.3.0-python.eb
Labels: update

#13143 {tools}[GCCcore/9.3.0] Coreutils v8.32
  easybuild/easyconfigs/c/Coreutils/Coreutils-8.32-GCCcore-9.3.0.eb
Labels: update

#13183 PnetCDF requires Perl as builddep
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.1-gompi-2020a.eb
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.1-gompic-2020a.eb
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.1-iimpi-2020a.eb
Labels: bug fix

#13211 {data}[GCCcore/10.3.0] dill v0.3.4 w/ Python 3.9.5
  easybuild/easyconfigs/d/dill/dill-0.3.4-GCCcore-10.3.0.eb
Labels: update

#13209 {vis}[GCCcore/10.3.0] Pango v1.48.0
  easybuild/easyconfigs/p/Pango/Pango-1.48.0-GCCcore-10.3.0.eb
Labels: update

#13151 {geo}[GCCcore/10.2.0] geopy v2.1.0 w/ Python 3.8.6
  easybuild/easyconfigs/g/geopy/geopy-2.1.0-GCCcore-10.2.0.eb
Labels: update

#13144 {chem}[foss/2020b] libcint v4.4.0
  easybuild/easyconfigs/l/libcint/libcint-4.4.0-foss-2020b.eb
  easybuild/easyconfigs/l/libcint/libcint-4.4.0_remove_pyscftest.patch
Labels: new

#13136 {vis}[fosscuda/2020b] NiBabel v3.2.1 w/ Python 3.8.6
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.2.1-fosscuda-2020b.eb
Labels: update

#13134 {tools}[GCCcore/10.2.0] nvtop v1.2.1
  easybuild/easyconfigs/n/nvtop/nvtop-1.2.1-GCCcore-10.2.0.eb
Labels: update

#13197 {chem}[foss/2020b] PySCF v1.7.6 w/ Python 3.8.6
  easybuild/easyconfigs/p/PySCF/PySCF-1.7.6-foss-2020b.eb
Labels: update

#13212 {data}[foss/2021a] h5py v3.2.1 w/ Python 3.9.5
  easybuild/easyconfigs/h/h5py/h5py-3.2.1-foss-2021a.eb
Labels: update

#13215 disable own avx detection of libfabric v1.12.1
  easybuild/easyconfigs/l/libfabric/libfabric-1.12.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.12.1_disable-psm3-avx-config.patch
Labels: bug fix

#13213 {data}[foss/2021a] scikit-learn v0.24.2 w/ Python 3.9.5
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.24.2-foss-2021a.eb
Labels: update

#13158 {math}[foss/2021a] MUMPS v5.4.0
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-foss-2021a-metis.eb
Labels: update

#13208 add cSEM extension to R 4.0.x + 4.1.0 easyconfigs (+ sync extension list)
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13202 {vis}[GCCcore/10.3.0] GTK+ v2.24.33
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-2.24.33-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.48.5-GCCcore-10.3.0.eb
Labels: update

#13217 {tools}[GCCcore/10.3.0] gperftools v2.9.1
  easybuild/easyconfigs/g/gperftools/gperftools-2.9.1-GCCcore-10.3.0.eb
Labels: update

#13196 {vis}[GCCcore/10.3.0] Graphviz v2.47.2 w/ Python 3.9.5
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.47.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libgd/libgd-2.3.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/SWIG/SWIG-4.0.2-GCCcore-10.3.0.eb
Labels: update

#13070 {numlib}[foss/2021a] Hypre v2.21.0
  easybuild/easyconfigs/h/Hypre/Hypre-2.21.0-foss-2021a.eb
Labels: update
