Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-04, with the labels that each got.

#12481 fix numpy tests for recent SciPy-bundle easyconfig on POWER
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-foss-2019a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-fosscuda-2019a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-foss-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-fosscuda-2019b-Python-2.7.16.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-foss-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-foss-2020b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-fosscuda-2020b.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.16.2_relax-long-complex-test.patch
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.19.4_skip-ppc-long-complex-test.patch
Labels: bug fix

#12508 {bio}[GCC/10.2.0] STAR bumped to 2.7.8a
  easybuild/easyconfigs/s/STAR/STAR-2.7.8a-GCC-10.2.0.eb
Labels: update

#12507 {data}[foss/2020b,intel/2020b] PyOD v0.8.7 w/ Python 3.8.6
  easybuild/easyconfigs/n/numba/numba-0.52.0-intel-2020b.eb
  easybuild/easyconfigs/p/PyOD/PyOD-0.8.7-foss-2020b.eb
  easybuild/easyconfigs/p/PyOD/PyOD-0.8.7-intel-2020b.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.12.1-foss-2020b.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#12495 {lib}[system/system] cuTENSOR v1.2.2.5
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-1.2.2.5-CUDA-11.1.1.eb
Labels: update

#12510 add extensions OUTRIDER and FRASER + dependencies to R-bundle-Bioconductor-3.12
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb
Labels: enhancement

#12503 {lib}[foss/2020b,fosscuda/2020b] NFFT v3.1.3
  easybuild/easyconfigs/n/NFFT/NFFT-3.1.3-foss-2020b.eb
  easybuild/easyconfigs/n/NFFT/NFFT-3.1.3-fosscuda-2020b.eb
Labels: update

#12513 {math}[system/system] MCR vR2021a
  easybuild/easyconfigs/m/MCR/MCR-R2021a.0.eb
Labels: update

#12501 {bio}[java] Picard bumped up to latest 2.25.1
  easybuild/easyconfigs/p/picard/picard-2.25.1-Java-11.eb
Labels: update

#12502 {vis}[foss/2020b,fosscuda/2020b] PyQtGraph v0.11.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.11.1-foss-2020b.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.11.1-fosscuda-2020b.eb
Labels: update

#12511 {devel}[system/system] ReFrame v3.5.1
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.5.1.eb
Labels: update

#12497 {bio}[foss/2020b] mrcfile v1.3.0, voltools v0.4.2 w/ Python 3.8.6
  easybuild/easyconfigs/m/mrcfile/mrcfile-1.3.0-foss-2020b.eb
  easybuild/easyconfigs/m/mrcfile/mrcfile-1.3.0-fosscuda-2020b.eb
  easybuild/easyconfigs/v/voltools/voltools-0.4.2-foss-2020b.eb
Labels: new

#12381 {toolchain} goblf/2020b (incl. LAPACK 3.9.0)
  easybuild/easyconfigs/g/goblf/goblf-2020b.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-goblf-2020b.eb
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.9.0-GCC-10.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020b-bl.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#12514 {vis}[GCCcore/10.2.0] GTS v0.7.6
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-GCCcore-10.2.0.eb
Labels: update

#12519 avoid 0.0.0 version for carputils 20200915
  easybuild/easyconfigs/c/carputils/carputils-20200915-foss-2020a-Python-3.8.2.eb
Labels: bug fix

#12522 avoid 0.0.0 install version for various Python apps
  easybuild/easyconfigs/d/deepdiff/deepdiff-5.0.2-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/e/EMU/EMU-0.66-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/maze/maze-20170124-foss-2020b.eb
  easybuild/easyconfigs/o/Open-Data-Cube-Core/Open-Data-Cube-Core-1.8.3-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/pytest/pytest-6.0.1-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/s/Spyder/Spyder-4.1.5-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/s/Spyder/Spyder-4.1.5-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/suave/suave-20160529-foss-2020b.eb
Labels: bug fix

#12535 update to LAPACK 3.9.1 for goblf/2020b
  easybuild/easyconfigs/g/goblf/goblf-2020b.eb
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.9.1-GCC-10.2.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020b-bl.eb
Labels: change, update

#12436 Make sure that path to eb is always found by tests
  test/easyconfigs/easyconfigs.py
Labels: bug fix, tests

#12364 {compiler}[GCCcore/10.2.0] AOCC v2.3.0
  easybuild/easyconfigs/a/AOCC/AOCC-2.3.0-GCCcore-10.2.0.eb
Labels: update

#12536 add Python 3 build dep for HMMER 3.3.x test step
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.1-gompi-2020a.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.1-iimpi-2020a.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.2-gompi-2019b.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.2-gompi-2020a.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.2-gompi-2020b.eb
Labels: bug fix

#12527 Enable USER_SDPD package and disable building docs in LAMMPS 3Mar2020
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2020a-Python-3.8.2-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2020a-Python-3.8.2-kokkos.eb
Labels: bug fix, enhancement

#12532 {lib}[GCCcore/10.2.0] GitPython v3.1.14 w/ Python 3.8.6
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.14-GCCcore-10.2.0.eb
Labels: update

#12525 {bio}[GCC/10.2.0,iccifort/2020.4.304] Flye v2.8.3 w/ Python 3.8.6
  easybuild/easyconfigs/f/Flye/Flye-2.8.3-GCC-10.2.0.eb
  easybuild/easyconfigs/f/Flye/Flye-2.8.3-iccifort-2020.4.304.eb
Labels: update

#12524 {math}[intel/2020b] GPyOpt v1.2.6 w/ Python 3.8.6
  easybuild/easyconfigs/g/GPyOpt/GPyOpt-1.2.6-intel-2020b.eb
Labels: new

#12523 {chem}[GCC/10.2.0] libxc bumped up to version 5.1.3
  easybuild/easyconfigs/l/libxc/libxc-5.1.3-GCC-10.2.0.eb
Labels: update

#12530 {lib}[foss/2019b] TensorFlow v2.2.2 w/ Python 3.7.4
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2019b-Python-3.7.4.eb
Labels: update

#12540 {data}[foss/2020a] NCL v6.6.2
  easybuild/easyconfigs/n/NCL/NCL-6.6.2-foss-2020a.eb
Labels: update

#12538 prepare release notes for EasyBuild v4.3.4 + bump version to 4.3.4
  RELEASE_NOTES
  setup.py
Labels: update

#12529 {bio}[foss/2020b] garnett v0.1.20
  easybuild/easyconfigs/g/garnett/garnett-0.1.20-foss-2020b-R-4.0.3.eb
Labels: new

#12541 {numlib,phys}[GCC/10.2.0] Geant4 v10.7.1, CLHEP v2.4.4.0
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.4.0-GCC-10.2.0.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.7.1-GCC-10.2.0.eb
Labels: update

#12554 {tools} EasyBuild v4.3.4
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.4.eb
Labels: update

#12438 {math}[foss/2020b] Keras v2.4.3, Theano v1.1.2 w/ Python 3.8.6
  easybuild/easyconfigs/k/Keras/Keras-2.4.3-foss-2020b.eb
  easybuild/easyconfigs/t/Theano/Theano-1.1.2-foss-2020b-PyMC.eb
Labels: update

#12547 {chem}[intel/2020a] ABINIT v9.4.1
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.4.1-intel-2020a.eb
Labels: update

#12515 {vis}[GCCcore/10.2.0] Graphviz v2.47.0 w/ Python 3.8.6
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.47.0-GCCcore-10.2.0-Java-11.eb
Labels: update

#12555 sync with main branch + bump version to 4.3.5dev
  RELEASE_NOTES
  setup.py
Labels: update

#12509 {lang,lib}[GCCcore/10.2.0,fosscuda/2020b] CuPy v8.5.0, Cython v0.29.22 w/ Python 3.8.6
  easybuild/easyconfigs/c/CuPy/CuPy-8.5.0-fosscuda-2020b.eb
  easybuild/easyconfigs/c/CuPy/CuPy-8.5.0_sanitycheck_fix.patch
  easybuild/easyconfigs/c/Cython/Cython-0.29.22-GCCcore-10.2.0.eb
Labels: update

#12551 Add fix to scipy to handle NaN arguments to "vi" function.
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-foss-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/scipy-1.2.3_fix_nan_problem_in_vi.patch
Labels: bug fix

#12565 update setup.py to indicate compatibility with Python 3.8 and 3.9
  setup.py
Labels: update

#12558 {bio}[GCCcore/10.2.0] GATK v4.2.0.0 w/ Python 3.8.6
  easybuild/easyconfigs/g/GATK/GATK-4.2.0.0-GCCcore-10.2.0-Java-11.eb
Labels: update

#12557 {tools}[foss/2020b] snakemake v6.1.0 w/ Python 3.8.6
  easybuild/easyconfigs/s/snakemake/snakemake-6.1.0-foss-2020b.eb
  snakemake-6.1.0_fix_jobs.patch
Labels: update

#12407 {bio}[foss/2020b] Octopus-vcf v0.7.1 w/ Python 3.8.6
  easybuild/easyconfigs/o/Octopus-vcf/Octopus-vcf-0.7.1-foss-2020b.eb
Labels: new

#12528 {bio}[GCC/10.2.0] NewHybrids v1.1_Beta3
  easybuild/easyconfigs/n/NewHybrids/NewHybrids-1.1_Beta3-GCC-10.2.0.eb
Labels: new

#12492 {tools}[system/system] rclone v1.54.1
  easybuild/easyconfigs/r/rclone/rclone-1.54.1-amd64.eb
Labels: update

#12568 {math}[fosscuda/2020b] Keras v2.4.3 w/ Python 3.8.6
  easybuild/easyconfigs/k/Keras/Keras-2.4.3-fosscuda-2020b.eb
Labels: update

#12521 {toolchain} GCC 10.3.0
  easybuild/easyconfigs/b/Bison/Bison-3.7.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/Bison/Bison-3.7.6.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.36.1.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GCC/GCC-10.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.3.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.48.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-10.3.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-10.3.0.eb
Labels: update

#12496 {math}[system/system] MATLAB v2020a, MATLAB v2020b, MATLAB v2021a
  easybuild/easyconfigs/m/MATLAB/MATLAB-2020a.eb
  easybuild/easyconfigs/m/MATLAB/MATLAB-2020b.eb
  easybuild/easyconfigs/m/MATLAB/MATLAB-2021a.eb
Labels: update

#12595 add libvdwxc-0.4.0-foss-2020a.eb
  easybuild/easyconfigs/l/libvdwxc/libvdwxc-0.4.0-foss-2020a.eb
Labels: update

#12592 {tools}[GCCcore/10.2.0] tcsh v6.22.03
  easybuild/easyconfigs/t/tcsh/tcsh-6.22.03-GCCcore-10.2.0.eb
Labels: update

#12589 {tools}[GCCcore/10.3.0] bzip2 v1.0.8
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-10.3.0.eb
Labels: 2021a, update

#12590 {tools}[GCCcore/10.3.0] libarchive v3.5.1, XZ v5.2.5
  easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.3.0.eb
Labels: 2021a, update

#12591 {tools}[GCCcore/10.3.0] cURL v7.76.0
  easybuild/easyconfigs/c/cURL/cURL-7.76.0-GCCcore-10.3.0.eb
Labels: 2021a, update

#12598 {bio}[foss/2020b] Octopus-vcf v0.7.2 w/ Python 3.8.6
  easybuild/easyconfigs/o/Octopus-vcf/Octopus-vcf-0.7.2-foss-2020b.eb
Labels: update

#12584 {vis}[GCC/10.2.0] GST-plugins-base v1.18.4
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.18.4-GCC-10.2.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.4-GCC-10.2.0.eb
Labels: update

#12576 {devel}[GCCcore/10.2.0] glew v2.2.0
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-10.2.0-egl.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-10.2.0-glx.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-10.2.0-osmesa.eb
Labels: update

#12578 {lib}[GCCcore/10.2.0] freeglut v3.2.1
  easybuild/easyconfigs/f/freeglut/freeglut-3.2.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/freeglut/freeglut-3.2.1_gcc10_fix-1.patch
Labels: update

#12593 BUSCO v5.1.2
  easybuild/easyconfigs/b/BUSCO/BUSCO-5.1.2-foss-2020b.eb
Labels: update

#12599 add setuptools_scm and pytest-runner extensions to Pylint easyconfigs
  easybuild/easyconfigs/p/Pylint/Pylint-1.9.3-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/Pylint/Pylint-1.9.3-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/Pylint/Pylint-1.9.3-iomkl-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/p/Pylint/Pylint-1.9.5-GCCcore-8.2.0-Python-2.7.15.eb
  easybuild/easyconfigs/p/Pylint/Pylint-1.9.5-GCCcore-8.3.0-Python-2.7.16.eb
Labels: bug fix

#12604 {devel}[GCCcore/10.3.0] CMake v3.20.1, pkg-config v0.29.2, ncurses v6.2
  easybuild/easyconfigs/c/CMake/CMake-3.20.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-10.3.0.eb
Labels: 2021a, update

#12610 {tools}[GCCcore/10.3.0] expat v2.2.9
  easybuild/easyconfigs/e/expat/expat-2.2.9-GCCcore-10.3.0.eb
Labels: update

#11675 {geo}[foss/2020b,intel/2020b] WRF v3.9.1.1
  easybuild/easyconfigs/t/time/time-1.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-foss-2020b-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-intel-2020b-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-3.9.1.1_GCC-10-allow-argument-mismatch.patch
Labels: update

#12580 {lib}[GCCcore/10.2.0] mmtf-cpp v1.0.0, msgpack-c v3.3.0
  easybuild/easyconfigs/m/mmtf-cpp/mmtf-cpp-1.0.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/msgpack-c/msgpack-c-3.3.0-GCCcore-10.2.0.eb
Labels: new

#12633 Fix typo in Delly config, make it actually OMP parallel
  easybuild/easyconfigs/d/Delly/Delly-0.8.7-gompi-2020b.eb
Labels: bug fix

#12628 {data}[gompic/2020a] netCDF-Fortran v4.5.2
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompic-2020a.eb
Labels: update

#12629 {data}[gompic/2020b] netCDF-Fortran v4.5.3
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.3-gompic-2020b.eb
Labels: update

#12549 {bio}[foss/2019b] p4-phylogenetics v1.4-20210322 w/ Python 3.7.4
  easybuild/easyconfigs/p/p4-phylogenetics/p4-phylogenetics-1.4-20210322-foss-2019b-Python-3.7.4.eb
Labels: new

#12607 {tools}[GCCcore/10.3.0] DB v18.1.40
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-10.3.0.eb
Labels: update

#12579 {lib}[GCCcore/10.2.0] GLM v0.9.9.8
  easybuild/easyconfigs/g/GLM/GLM-0.9.9.8-GCCcore-10.2.0.eb
Labels: update

#12614 {lang}[GCCcore/10.3.0] Tcl v8.6.11
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.11-GCCcore-10.3.0.eb
Labels: update

#12647 Create tmux-3.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/tmux/tmux-3.2-GCCcore-10.2.0.eb
Labels: update

#12608 {lib}[GCCcore/10.3.0] libreadline v8.1
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-10.3.0.eb
Labels: update

#12649 Fix potential memory leak in OpenBLAS 0.3.12
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.12-GCC-10.2.0.eb
Labels: bug fix

#12594 Backport Charm++ patch for NAMD/2.14 on intel/2020a to handle newer glibc
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-intel-2020a-mpi.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-use_system_mremap_decl.patch
Labels: bug fix

#12616 {system}[GCCcore/10.3.0] libpci v3.7.0
  easybuild/easyconfigs/l/libpci/libpci-3.7.0-GCCcore-10.3.0.eb
Labels: update

#12615 {lib}[GCCcore/10.3.0] LMDB v0.9.28
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.28-GCCcore-10.3.0.eb
Labels: update

#12617 {lib}[GCCcore/10.3.0] libffi v3.3
  easybuild/easyconfigs/l/libffi/libffi-3.3-GCCcore-10.3.0.eb
Labels: update

#12619 {devel}[GCCcore/10.3.0] make v4.3, imake v1.0.8
  easybuild/easyconfigs/i/imake/imake-1.0.8-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/make/make-4.3-GCCcore-10.3.0.eb
Labels: update

#12606 {system}[GCCcore/10.3.0] libgcrypt v1.9.2, libgpg-error v1.42
  easybuild/easyconfigs/l/libgcrypt/libgcrypt-1.9.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.42-GCCcore-10.3.0.eb
Labels: update

#12601 {devel}[GCCcore/10.3.0] PCRE2 v10.36, PCRE v8.44
  easybuild/easyconfigs/p/PCRE/PCRE-8.44-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.36-GCCcore-10.3.0.eb
Labels: update

#12625 {lib}[GCCcore/10.3.0] libunwind v1.5.0
  easybuild/easyconfigs/l/libunwind/libunwind-1.5.0-GCCcore-10.3.0.eb
Labels: update

#12652 Replace bintray source url for Groovy
  easybuild/easyconfigs/g/Groovy/Groovy-2.5.9-Java-11.eb
Labels: bug fix

#12556 {devel}[foss/2020a] line_profiler v3.1.0 w/ Python 3.8.2
  easybuild/easyconfigs/l/line_profiler/line_profiler-3.1.0-foss-2020a-Python-3.8.2.eb
Labels: new

#12559 {bio}[foss/2020b] DROP v1.0.3, tMAE v1.0.0 w/ Python 3.8.6
  easybuild/easyconfigs/d/DROP/DROP-1.0.3-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/t/tMAE/tMAE-1.0.0-foss-2020b-R-4.0.3.eb
Labels: new

#12560 {bio}[foss/2020b] CNVkit v0.9.8 w/ Python 3.8.6
  easybuild/easyconfigs/c/CNVkit/CNVkit-0.9.8-foss-2020b-R-4.0.3.eb
Labels: update

#12624 {devel}[GCCcore/10.3.0] SQLite v3.35.4
  easybuild/easyconfigs/s/SQLite/SQLite-3.35.4-GCCcore-10.3.0.eb
Labels: update

#12657 {devel}[GCCcore/10.3.0] makeinfo v6.7
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-GCCcore-10.3.0.eb
Labels: update

#12643 {vis}[GCCcore/10.3.0] pixman v0.40.0
  easybuild/easyconfigs/p/pixman/pixman-0.40.0-GCCcore-10.3.0.eb
Labels: update

#12620 {math}[GCCcore/10.3.0] Eigen v3.3.9
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.9-GCCcore-10.3.0.eb
Labels: update

#12618 {devel,lib}[GCCcore/10.3.0] Doxygen v1.9.1, libiconv v1.16
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.9.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.16-GCCcore-10.3.0.eb
Labels: update

#12622 {numlib}[GCCcore/10.3.0] NLopt v2.7.0
  easybuild/easyconfigs/n/NLopt/NLopt-2.7.0-GCCcore-10.3.0.eb
Labels: update

#12603 {lib}[GCCcore/10.3.0] libsndfile v1.0.31, libvorbis v1.3.7, libogg v1.3.4, ...
  easybuild/easyconfigs/f/FLAC/FLAC-1.3.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libogg/libogg-1.3.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.31-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libvorbis/libvorbis-1.3.7-GCCcore-10.3.0.eb
  easybuild/easyconfigs/v/vorbis-tools/vorbis-tools-1.4.2-GCCcore-10.3.0.eb
Labels: update

#12651 {tools}[GCCcore/10.2.0] Archive-Zip v1.68
  easybuild/easyconfigs/a/Archive-Zip/Archive-Zip-1.68-GCCcore-10.2.0.eb
Labels: new

#12609 {lib}[GCCcore/10.3.0] giflib v5.2.1, libjpeg-turbo v2.0.6, libpng v1.6.37, ...
  easybuild/easyconfigs/g/giflib/giflib-5.2.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.28-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libwebp/libwebp-1.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-GCCcore-10.3.0.eb
  easybuild/easyconfigs/o/OpenEXR/OpenEXR-3.0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.4.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20210414-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-10.3.0.eb
Labels: update

#12543 {tools}[foss/2020a,fosscuda/2020a] Horovod v0.21.0 w/ Python 3.8.2
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.3-foss-2020a-TensorFlow-2.3.1-Python-3.8.2.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.3-fosscuda-2020a-TensorFlow-2.3.1-Python-3.8.2.eb
Labels: update

#12641 {devel}[GCCcore/10.3.0] DBus v1.13.18
  easybuild/easyconfigs/d/DBus/DBus-1.13.18-GCCcore-10.3.0.eb
Labels: update

#12642 {lib}[GCCcore/10.3.0] libyaml v0.2.5
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.5-GCCcore-10.3.0.eb
Labels: update

#12645 {lib}[GCCcore/10.3.0] snappy v1.1.8
  easybuild/easyconfigs/s/snappy/snappy-1.1.8-GCCcore-10.3.0.eb
Labels: update

#12621 {devel}[GCCcore/10.3.0] libgit2 v1.1.0
  easybuild/easyconfigs/l/libgit2/libgit2-1.1.0-GCCcore-10.3.0.eb
Labels: update

#12602 {tools}[GCCcore/10.3.0] zstd v1.4.9, Zip v3.0, Szip v2.1.1, ...
  easybuild/easyconfigs/g/gzip/gzip-1.10-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libzip/libzip-1.7.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.9.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/p7zip/p7zip-17.04-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/pigz/pigz-2.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/pigz/pigz-2.6_makefile.patch
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.4.9-GCCcore-10.3.0.eb
Labels: update

#12644 {lib}[GCCcore/10.3.0] libidn v1.36
  easybuild/easyconfigs/l/libidn/libidn-1.36-GCCcore-10.3.0.eb
Labels: update

#12623 {lib}[GCCcore/10.3.0] double-conversion v3.1.5
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.5-GCCcore-10.3.0.eb
Labels: update

#12612 {vis}[GCCcore/10.3.0] fontconfig v2.13.93, freetype v2.10.4, util-linux v2.36, ...
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.93-GCCcore-10.3.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.36-GCCcore-10.3.0.eb
Labels: update

#12665 {lib}[GCCcore/10.3.0] libidn2 v2.3.0
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.0-GCCcore-10.3.0.eb
Labels: new

#12640 {devel}[foss/2020a] Spark v3.1.1 w/ Python 3.8.2 (+ fix Arrow 0.17.1 on aarch64)
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-fosscuda-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1_fix-arm.patch
  easybuild/easyconfigs/s/Spark/Spark-3.1.1-foss-2020a-Python-3.8.2.eb
Labels: EESSI, update

#12627 add Compress::Raw::Zlib to Perl v5.32.0
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Labels: enhancement

#12632 {tools}[foss/2020{a,b}] mongolite w/ R-4.0.{0,3,4}
  easybuild/easyconfigs/m/mongolite/mongolite-2.3.0-foss-2020a-R-4.0.0.eb
  easybuild/easyconfigs/m/mongolite/mongolite-2.3.0-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/m/mongolite/mongolite-2.3.0-foss-2020b-R-4.0.4.eb
Labels: new

#12646 {bio}[fosscuda/2020a] OpenMM v7.5.0 w/ Python 3.8.2
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.0-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.0_fix_path_to_nvcc.patch
Labels: update

#12542 {devel}[system] ReFrame v3.5.2
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.5.2.eb
Labels: update

#12585 {vis}[GCC/10.2.0] wxWidgets v3.1.4
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.1.4-GCC-10.2.0.eb
Labels: update

#12631 {vis}[fosscuda/2020a] matplotlib v2.2.5 w/ Python 2.7.18
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.5-fosscuda-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-fosscuda-2020a-Python-2.7.18.eb
Labels: update

#12586 {bio}[fosscuda/2020b] ctffind v4.1.14
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-fosscuda-2020b.eb
Labels: update

#12512 {bio}[GCCcore/10.2.0] GATK v4.2.0.0 w/ Python 3.8.6
  easybuild/easyconfigs/g/GATK/GATK-4.2.0.0-GCCcore-10.2.0-Java-1.8.eb
Labels: update

#12570 {math,phys}[foss/2019b] georges v2019.2 + LMfit v1.0.0 w/ Python 3.7.4
  easybuild/easyconfigs/g/georges/georges-2019.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/l/LMfit/LMfit-1.0.0-foss-2019b-Python-3.7.4.eb
Labels: new, update

#12469 {bio}[GCC/10.2.0] segemehl v0.3.4
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-10.2.0.eb
Labels: update

#12662 Add Python dependency to AUGUSTUS-3.4.0-foss-2020b.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.4.0-foss-2020b.eb
Labels: bug fix

#12674 {bio}[GCCcore/10.2.0] canu v2.1.1
  easybuild/easyconfigs/c/canu/canu-2.1.1-GCCcore-10.2.0.eb
Labels: update

#12683 {lang}[foss/2020b] SciPy-bundle v2020.11 w/ Python 2.7.18
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.11-foss-2020b-Python-2.7.18.eb
Labels: update

#12676 {bio}[GCC/10.2.0] CIRCexplorer2 v2.3.8, Cufflinks v20190706, TopHat v2.1.2 w/ Python 2.7.18
  easybuild/easyconfigs/c/CIRCexplorer2/CIRCexplorer2-2.3.8-foss-2020b-Python-2.7.18.eb
  easybuild/easyconfigs/c/Cufflinks/Cufflinks-20190706-GCC-10.2.0.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.16.0.1-GCC-10.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/p/pybedtools/pybedtools-0.8.2-GCC-10.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/t/TopHat/TopHat-2.1.2-GCC-10.2.0-Python-2.7.18.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#10477 {lib}[foss/2019b] librosa v0.7.2 w/ Python 3.7.4
  easybuild/easyconfigs/l/librosa/librosa-0.7.2-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#12685 {bio}[fosscuda/2019b] BirdNET v20201214 w/ Python 3.7.4
  easybuild/easyconfigs/b/BirdNET/BirdNET-20201214-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BirdNET/BirdNET-20201214_add-model-path-envvar.patch
  easybuild/easyconfigs/l/librosa/librosa-0.7.2-fosscuda-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#12692 {lang}[GCCcore/10.2.0] LDC v1.25.1
  easybuild/easyconfigs/l/LDC/LDC-0.17.6-x86_64.eb
  easybuild/easyconfigs/l/LDC/LDC-1.25.1-GCCcore-10.2.0.eb
Labels: new

#12688 {devel}[GCCcore/10.2.0] SCons v4.1.0.post1 w/ Python 3.8.6
  easybuild/easyconfigs/s/SCons/SCons-4.1.0.post1-GCCcore-10.2.0.eb
Labels: update

#12705 {cae}[GCCcore/10.2.0] PySAT v0.1.7.dev1, DFA v2.1.2, pydot v1.4.2, ... w/ Python 3.8.6
  easybuild/easyconfigs/d/DFA/DFA-2.1.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PySAT/PySAT-0.1.7.dev1-GCC-10.2.0.eb
  easybuild/easyconfigs/p/py-aiger/py-aiger-6.1.14-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/pydot/pydot-1.4.2-GCCcore-10.2.0.eb
Labels: update

#12701 Override host compiler check in CUDAcore
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.0.2.eb
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.1.1.eb
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.2.1.eb
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.2.2.eb
Labels: bug fix

#12678 {lib}[foss/2020b] pygmo v2.16.1, pagmo v2.17.0 w/ Python 3.8.6
  easybuild/easyconfigs/p/pagmo/pagmo-2.17.0-foss-2020b.eb
  easybuild/easyconfigs/p/pygmo/pygmo-2.16.1-foss-2020b.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#12695 {tools}[GCC/10.2.0] gawk v5.1.0
  easybuild/easyconfigs/g/gawk/gawk-5.1.0-GCC-10.2.0.eb
Labels: new

#12693 {bio}[GCC/10.2.0] Sambamba v0.8.0
  easybuild/easyconfigs/s/Sambamba/Sambamba-0.8.0-GCC-10.2.0.eb
Labels: update

#12694 {bio}[GCC/10.2.0] samblaster v0.1.26
  easybuild/easyconfigs/s/samblaster/samblaster-0.1.26-GCC-10.2.0.eb
Labels: update

#12671 {lang,tools}[GCCcore/10.2.0] onedrive v2.4.11, LDC v1.25.1
  easybuild/easyconfigs/o/onedrive/onedrive-2.4.11-GCCcore-10.2.0.eb
Labels: new

#12709 add -Java versionsuffix for Hadoop easyconfig using GCCcore/10.2.0 toolchain, since it depends on Java 1.8
  easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0-GCCcore-10.2.0-native-Java-1.8.eb
Labels: change

#12715 libpsl 0.21.0 has a build dependency on Python.
  easybuild/easyconfigs/l/libpsl/libpsl-0.21.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libpsl/libpsl-0.21.0-GCCcore-8.3.0.eb
Labels: bug fix

#12700 fix source URLs for recent ELPA versions
  easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-foss-2018b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-intel-2018a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-intel-2018b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2018.05.001-foss-2018b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2018.05.001-intel-2018b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2018.11.001-intel-2019a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-foss-2019b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-foss-2020a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-intel-2019b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-intel-2020a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-iomkl-2019b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.05.001-intel-2020a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-foss-2020b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-intel-2020b.eb
Labels: bug fix

#12681 Revert "add Compress::Raw::Zlib to Perl v5.32.0"
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Labels: change

#12672 {system}[system/system] CUDAcore v11.3.0
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.3.0.eb
Labels: update

#12716 Fix error in libgpg-error 1.36 with gawk builtin.
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.36-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.36_fix_use_of_gawk_builtin.patch
Labels: bug fix

#12714 {vis}[GCCcore/10.2.0] Molden 6.8
  easybuild/easyconfigs/m/Molden/Molden-6.8-GCCcore-10.2.0.eb
Labels: update

#12712 fix BirdNET patch: don't use relative paths to files in installation directory
  easybuild/easyconfigs/b/BirdNET/BirdNET-20201214-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BirdNET/BirdNET-20201214_add-model-path-envvar.patch
Labels: bug fix

#12711 {vis}[foss/2020a] ETE v3.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/e/ETE/ETE-3.1.2-foss-2020a-Python-3.8.2.eb
Labels: update

#12611 {lang}[GCCcore/10.3.0] Perl v5.32.1
  easybuild/easyconfigs/g/groff/groff-1.22.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.32.1-GCCcore-10.3.0.eb
Labels: update

#12737 Fix wrong variable name in BirdNET patch
  easybuild/easyconfigs/b/BirdNET/BirdNET-20201214-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/b/BirdNET/BirdNET-20201214_add-model-path-envvar.patch
Labels: bug fix

#12735 {lang}[foss/2020b,fosscuda/2020b] R v4.0.x: add miceadds, visdat, UpSetR, naniar, stringdist, image.binarization
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
Labels: enhancement

#12718 {vis}[foss/2020b] matplotlib v2.2.5, Tkinter v2.7.18 w/ Python 2.7.18
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.5-foss-2020b-Python-2.7.18.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.18-GCCcore-10.2.0.eb
Labels: update

#12719 {bio}[GCCcore/10.2.0] DendroPy v4.5.2 w/ Python 2.7.18
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.5.2-GCCcore-10.2.0-Python-2.7.18.eb
Labels: update

#12721 {bio}[foss/2020b] Biopython v1.76 w/ Python 2.7.18
  easybuild/easyconfigs/b/Biopython/Biopython-1.76-foss-2020b-Python-2.7.18.eb
Labels: update

#12722 {tools}[GCCcore/10.2.0] parallel v20210322
  easybuild/easyconfigs/p/parallel/parallel-20210322-GCCcore-10.2.0.eb
Labels: update

#12723 {data}[foss/2020b] scikit-learn v0.20.4 w/ Python 2.7.18
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.4-foss-2020b-Python-2.7.18.eb
Labels: update

#12724 {bio}[GCCcore/10.2.0] MEGAHIT v1.2.9 w/ Python 2.7.18
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-10.2.0-Python-2.7.18.eb
Labels: update

#12741 Add libtool build dependency to leidenalg
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.3-fosscuda-2020b.eb
Labels: bug fix

#12729 {bio}[GCC/10.2.0] Trim_Galore v0.6.6, pigz v2.6, cutadapt v1.18 w/ Python 2.7.18
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.18-GCC-10.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/p/pigz/pigz-2.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.6-GCC-10.2.0-Python-2.7.18.eb
Labels: update

#12738 {lang}[GCCcore/10.2.0] Nim v1.4.6
  easybuild/easyconfigs/n/Nim/Nim-1.4.6-GCCcore-10.2.0.eb
Labels: update

#12696 {bio}[foss/2020b] LUMPY v0.3.1 w/ Python 3.8.6
  easybuild/easyconfigs/l/LUMPY/LUMPY-0.3.1-foss-2020b.eb
Labels: update

#12734 {bio}[system/system] IGV v2.9.4
  easybuild/easyconfigs/i/IGV/IGV-2.9.4-Java-11.eb
Labels: update
