Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-01, with the labels that each got.

#11940 {tools}[GCCcore/10.2.0] PyClone v2020.9b2
  easybuild/easyconfigs/p/PyClone/PyClone-2020.9b2-GCCcore-10.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#11847 also build shared library in recent HDF easyconfigs
  easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-8.3.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-9.3.0.eb
Labels: change, enhancement

#11855 add support for HDF4 to GDAL v3.0.2 and v3.0.4
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.2-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.4-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.0.4-intel-2020a-Python-3.8.2.eb
Labels: enhancement

#11942 {lib}[GCCcore/10.2.0] libwebp v1.1.0
  easybuild/easyconfigs/l/libwebp/libwebp-1.1.0-GCCcore-10.2.0.eb
Labels: update

#8667 {bio}[foss/2018b] PHANOTATE v20190724
  easybuild/easyconfigs/p/PHANOTATE/PHANOTATE-20190724-foss-2018b.eb
Labels: new

#11943 {mpi}[GCC/10.2.0] OpenMPI v4.1.0
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.0-GCC-10.2.0.eb
Labels: update

#8674 {bio}[system] webin-cli v1.8.9
  easybuild/easyconfigs/w/webin-cli/webin-cli-1.8.9.eb
Labels: new

#8654 {devel}[ssytem] CMake v3.15.1
  easybuild/easyconfigs/c/CMake/CMake-3.15.1.eb
Labels: update

#8601 {lib}[gompi/2019a,gompic/2019a,iimpic/2019a] Boost.Python v1.70.0 w/ Python 2.7.15 + 3.7.2
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.70.0-gompic-2019a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.70.0-iimpic-2019a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.70.0-gompic-2019a.eb
Labels: update

#7895 {numlib}[system] cuDNN v7.5.0.56
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.5.0.56-CUDA-10.0.130.eb
Labels: update

#11944 {lib}[gompi/2020b] fftlib v20170628
  easybuild/easyconfigs/f/fftlib/fftlib-20170628-gompi-2020b.eb
Labels: new

#11908 Remove cuDNN-8.0.4.30-gcccuda-2020a
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.0.4.30-gcccuda-2020a.eb
Labels: change

#11946 {chem}[foss/2020b] QuantumESPRESSO v6.6
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-foss-2020b.eb
Labels: update

#11950 {lib}[GCCcore/10.2.0] OpenJPEG v2.4.0
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.4.0-GCCcore-10.2.0.eb
Labels: update

#11947 update Hypre git location for PETSc 3.11.0 using downloaded dependencies
  easybuild/easyconfigs/p/PETSc/PETSc-3.11.0-foss-2018b-downloaded-deps.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.11.0_hypre-git-moved.patch
Labels: bug fix

#11814 don't disable optarch for Clang 11.0.0
  easybuild/easyconfigs/c/Clang/Clang-11.0.0-GCCcore-9.3.0.eb
Labels: enhancement

#11785 {devel,vis}[fosscuda/2019b] PyTorch v1.6.0, torchvision v0.7.0 w/ Python 3.7.4, with MKL
  easybuild/easyconfigs/i/imkl/imkl-2019.5.281-gompic-2019b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4-imkl.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.7.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.6.0-imkl.eb
Labels: update

#11952 {vis}[GCCcore/9.3.0] pydicom v2.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/p/pydicom/pydicom-2.1.2-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#11882 {chem}[foss/2019b] RDKit v2020.09.3 w/ Python 3.7.4
  easybuild/easyconfigs/r/RDKit/RDKit-2020.09.3-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/r/RDKit/RDKit-2020.09.3_skip-broken-test.patch
Labels: update

#11948 {tools}[foss/2020a] GetOrganelle v1.7.2 w/ Python 3.8.2
  easybuild/easyconfigs/g/GetOrganelle/GetOrganelle-1.7.2-foss-2020a-Python-3.8.2.eb
Labels: new

#10525 {data}[foss/2019b] NLTK v3.5 v/ Python 3.7.4
  easybuild/easyconfigs/n/NLTK/NLTK-3.5-foss-2019b-Python-3.7.4.eb
Labels: update

#11955 {lib}[foss/2020a] dicom2nifti v2.2.12 w/ Python 3.8.2 and unbundle pydicom from NiBabel v3.2.0
  easybuild/easyconfigs/d/dicom2nifti/dicom2nifti-2.2.12-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.2.0-foss-2020a-Python-3.8.2.eb
Labels: change, new

#11958 update copyright statements for 2021
  setup.py
  test/__init__.py
  test/easyconfigs/easyconfigs.py
  test/easyconfigs/styletests.py
  test/easyconfigs/suite.py
Labels: update

#10430 {math}[GCC/8.3.0] Normaliz v3.8.4 and deps E-ANTIC, Arb, FLINT, CoCoALib, cddlib, nauty
  easybuild/easyconfigs/a/Arb/Arb-2.17.0-GCC-8.3.0.eb
  easybuild/easyconfigs/c/CoCoALib/CoCoALib-0.99700-GCC-8.3.0.eb
  easybuild/easyconfigs/c/cddlib/cddlib-0.94j-GCCcore-8.3.0.eb
  easybuild/easyconfigs/e/E-ANTIC/E-ANTIC-0.1.5-GCC-8.3.0.eb
  easybuild/easyconfigs/f/FLINT/FLINT-2.5.2-GCC-8.3.0.eb
  easybuild/easyconfigs/n/Normaliz/Normaliz-3.8.4-GCC-8.3.0.eb
  easybuild/easyconfigs/n/nauty/nauty-2.7rc5-GCC-8.3.0.eb
Labels: new, update

#11960 fix source URL in expat easyconfigs (and consistently add custom sanity_check_paths)
  easybuild/easyconfigs/e/expat/expat-2.1.0-GCC-4.9.2.eb
  easybuild/easyconfigs/e/expat/expat-2.1.0-foss-2016a.eb
  easybuild/easyconfigs/e/expat/expat-2.1.0-intel-2016a.eb
  easybuild/easyconfigs/e/expat/expat-2.1.1-foss-2016a.eb
  easybuild/easyconfigs/e/expat/expat-2.1.1-intel-2016a.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-GCCcore-4.9.3.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-GCCcore-5.4.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-GCCcore-6.3.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-foss-2016a.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-foss-2016b.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-gimkl-2017a.eb
  easybuild/easyconfigs/e/expat/expat-2.2.0-intel-2016b.eb
  easybuild/easyconfigs/e/expat/expat-2.2.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.5-GCCcore-6.4.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.5-GCCcore-7.3.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.6-GCCcore-8.2.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/e/expat/expat-2.2.9-GCCcore-9.3.0.eb
Labels: bug fix

#11957 {lang,vis}[foss/2020a,intel/2020a] SciPy-bundle v2020.03, matplotlib v2.2.5 w/ Python 2.7.18
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.5-foss-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.5-intel-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-foss-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2020.03-intel-2020a-Python-2.7.18.eb
Labels: update

#11949 ubuntu requires pkg-config
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.66.1-GCCcore-10.2.0.eb
Labels: bug fix

#11963 {numlib}[GCC/9.3.0] MiniCARD v1.2
  easybuild/easyconfigs/m/MiniCARD/MiniCARD-1.2-GCC-9.3.0.eb
Labels: new

#11964 {numlib}[GCC/9.3.0] Lingeling vbcp
  easybuild/easyconfigs/l/Lingeling/Lingeling-bcp-GCC-9.3.0.eb
Labels: new

#11965 {numlib}[GCC/9.3.0] Glucose v4.1
  easybuild/easyconfigs/g/Glucose/Glucose-4.1-GCC-9.3.0.eb
Labels: new

#11966 {numlib}[GCC/9.3.0] CaDiCaL v1.3.0
  easybuild/easyconfigs/c/CaDiCaL/CaDiCaL-1.3.0-GCC-9.3.0.eb
Labels: new

#11967 add missing orca dependency for NanoPlot
  easybuild/easyconfigs/n/NanoPlot/NanoPlot-1.28.4-intel-2019b-Python-3.7.4.eb
Labels: bug fix

#11961 {data}[foss/2020a] ITK v5.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/i/ITK/ITK-5.1.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/ITK/ITK-5.1.2_fix_wrap_vtkglue.patch
Labels: update

#11962 {numlib}[GCC/9.3.0] MiniSat v20130925, MiniSat v2.2.0
  easybuild/easyconfigs/m/MiniSat/MiniSat-2.2.0-GCC-9.3.0.eb
  easybuild/easyconfigs/m/MiniSat/MiniSat-20130925-GCC-9.3.0.eb
Labels: new

#11971 {tools}[foss/2020b,fosscuda/2020b] networkx v2.5 w/ Python 3.8.6
  easybuild/easyconfigs/n/networkx/networkx-2.5-foss-2020b.eb
  easybuild/easyconfigs/n/networkx/networkx-2.5-fosscuda-2020b.eb
Labels: update

#10989 added missing space in 'configopts' in ParaView 5.8.0 easyconfigs using 2020a toolchain
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-foss-2020a-Python-3.8.2-mpi.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-intel-2020a-Python-3.8.2-mpi.eb
Labels: bug fix

#11969 {vis}[GCCcore/9.3.0] Graphviz v2.44.1, GTS v0.7.6 w/ Python 3.8.2
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.44.1-GCCcore-9.3.0-Java-11-Python-3.8.2.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.44.1-GCCcore-9.3.0-Java-11.eb
Labels: update

#11787 {devel}[system] ReFrame v3.3
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.3.eb
Labels: update

#11968 {bio}[GCC/10.2.0] Pysam v0.16.0.1
  easybuild/easyconfigs/p/Pysam/Pysam-0.16.0.1-GCC-10.2.0.eb
Labels: update

#11973 {lib}[foss/2020b,fosscuda/2020b] scikit-build v0.11.1 w/ Python 3.8.6
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.11.1-foss-2020b.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.11.1-fosscuda-2020b.eb
Labels: update

#11636 {bio,devel}[fosscuda/2019b] PyTorch v1.7.1, typing-extensions v3.7.4.3 w/ Python 3.7.4
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.0_avoid-nan-in-test-torch.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.0_disable-dev-shm-test.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.0_fix-fbgemm-not-implemented-issue.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.0_fix_altivec_defines.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.0_fix_test_DistributedDataParallel.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.0_increase-distributed-test-timeout.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1_el8_ppc64le.patch
  easybuild/easyconfigs/t/typing-extensions/typing-extensions-3.7.4.3-fosscuda-2019b-Python-3.7.4.eb
Labels: new, update

#11742 {chem}[intel/2020a] YANK v0.25.2, AmberTools v20, packmol v20.2.2, pymbar v3.0.3 w/ Python 3.8.2
  easybuild/easyconfigs/a/AmberTools/Amber-20_fix-hardcoding.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-20-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/packmol/packmol-v20.2.2-iccifort-2020.1.217.eb
  easybuild/easyconfigs/p/pymbar/pymbar-3.0.3-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/y/YANK/YANK-0.25.2-intel-2020a-Python-3.8.2.eb
Labels: new, update

#11986 {tools}[GCCcore/9.3.0] likwid v5.1.0
  easybuild/easyconfigs/l/likwid/likwid-5.1.0-GCCcore-9.3.0.eb
Labels: update

#11984 {lang}[system/system] Anaconda3 v2020.11
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2020.11.eb
Labels: update

#11953 {bio}[foss/2019b] FusionCatcher v1.30 w/ Python 2.7.16
  easybuild/easyconfigs/f/FusionCatcher/FusionCatcher-1.30-foss-2019b-Python-2.7.16.eb
Labels: update

#11985 {tools}[foss/2020a] neptune-client v0.4.129 w/ Python 3.8.2
  easybuild/easyconfigs/n/neptune-client/neptune-client-0.4.129-foss-2020a-Python-3.8.2.eb
Labels: new

#11977 {vis}[GCCcore/9.3.0] pydot v1.4.1 w/ Python 2.7.18 + 3.8.2
  easybuild/easyconfigs/p/pydot/pydot-1.4.1-GCCcore-9.3.0.eb
Labels: update

#11979 {cae}[GCCcore/9.3.0] DFA v0.3.4 w/ Python 3.8.2
  easybuild/easyconfigs/d/DFA/DFA-0.3.4-GCCcore-9.3.0-Python-3.8.2.eb
Labels: new

#11978 {cae}[foss/2020a] dd v0.5.6 w/ Python 3.8.2
  easybuild/easyconfigs/d/dd/cudd-3.0.0_disable-pdf-docs.patch
  easybuild/easyconfigs/d/dd/dd-0.5.6-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/d/dd/dd-0.5.6_fix-sylvan-linking.patch
Labels: new

#11972 {chem}[intel/2020a] WHAM v2.0.10.2
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.10.2-intel-2020a-kj_mol.eb
  easybuild/easyconfigs/w/WHAM/WHAM-2.0.10.2-intel-2020a.eb
Labels: update

#11980 {bio}[gompi/2020a] fpocket v3.1.4.2
  easybuild/easyconfigs/f/fpocket/fpocket-3.1.4.2-gompi-2020a.eb
Labels: new

#11990 use EB libpng in VTK to fix build issue on ppc64le
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2019a-Python-2.7.15.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2020a-Python-3.8.2.eb
Labels: bug fix

#11993 {bio}[iccifort/2020.4.304] Pysam v0.16.0.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/Pysam/Pysam-0.16.0.1-iccifort-2020.4.304.eb
Labels: update

#11994 {bio}[intel/2020b] Seaborn v0.11.1 w/ Python 3.8.6
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.11.1-intel-2020b.eb
Labels: update

#11995 {bio}[intel/2020b] Biopython v1.78 w/ Python 3.8.6
  easybuild/easyconfigs/b/Biopython/Biopython-1.78-intel-2020b.eb
Labels: update

#11997 {math}[intel/2020b] statsmodels v0.12.1 w/ Python 3.8.6
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.12.1-intel-2020b.eb
Labels: update

#11999 {cae}[GCCcore/9.3.0,foss/2020a] py-aiger v6.1.1, py-aiger-bdd v3.0.0 w/ Python 3.8.2
  easybuild/easyconfigs/p/py-aiger-bdd/py-aiger-bdd-3.0.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/p/py-aiger/py-aiger-6.1.1-GCCcore-9.3.0-Python-3.8.2.eb
Labels: new

#12000 {cae}[GCC/9.3.0] PySAT v0.1.6.dev11 w/ Python 3.8.2
  easybuild/easyconfigs/p/PySAT/PySAT-0.1.6.dev11-GCC-9.3.0-Python-3.8.2.eb
Labels: new

#12007 add patch for Boost 1.74.0 to fix missing include file
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-GCC-10.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-iccifort-2020.4.304.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-library_version_type_serialization.patch
Labels: bug fix

#12001 fix silly typo in description for Arrow easyconfigs
  easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.16.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020a-Python-3.8.2.eb
Labels: bug fix

#11992 {data}[intel/2020b] Arrow v0.17.1 w/ Python 3.8.6
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020b.eb
Labels: update

#11991 {lib}[GCCcore/10.2.0] MariaDB v10.5.8, MariaDB-connector-c v3.1.11, Judy v1.0.5, ...
  easybuild/easyconfigs/j/Judy/Judy-1.0.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libaio/libaio-0.3.112-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-3.1.11-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.5.8-GCC-10.2.0.eb
Labels: update

#11715 {bio,lib}[fosscuda/2020a] scikit-build v0.10.0, GROMACS v2020.5 w/ Python 3.8.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.5-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.5_fix_threads_gpu_Gmxapitests.patch
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020_disable_hardware_topology_tests.patch
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.10.0-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#11996 {math}[intel/2020b] pauvre v0.1924 w/ Python 3.8.6
  easybuild/easyconfigs/p/pauvre/pauvre-0.1924-intel-2020b.eb
Labels: update

#11392 {vis}[GCCcore/9.3.0] orca v1.3.1
  easybuild/easyconfigs/o/orca/orca-1.3.1-GCCcore-9.3.0.eb
Labels: update

#12008 {devel}[foss/2020b] PyTorch v1.7.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.7.1-foss-2020b.eb
  easybuild/easyconfigs/t/typing-extensions/typing-extensions-3.7.4.3-GCCcore-10.2.0.eb
Labels: update

#11998 {bio,vis}[intel/2020b] NanoComp v1.13.1, NanoPlot v1.33.0, Kaleido v0.1.0, ... w/ Python 3.8.6
  easybuild/easyconfigs/j/joypy/joypy-0.2.4-intel-2020b.eb
  easybuild/easyconfigs/k/Kaleido/Kaleido-0.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/NanoComp/NanoComp-1.13.1-intel-2020b.eb
  easybuild/easyconfigs/n/NanoPlot/NanoPlot-1.33.0-intel-2020b.eb
  easybuild/easyconfigs/n/nanoget/nanoget-1.15.0-intel-2020b.eb
  easybuild/easyconfigs/n/nanomath/nanomath-1.2.0-intel-2020b.eb
  easybuild/easyconfigs/o/orca/orca-1.3.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/plotly.py/plotly.py-4.14.3-GCCcore-10.2.0.eb
Labels: new, update

#12012 fix for "error: 'runtime_error' is not a member of 'std'" in qtlocation for Qt5 v5.14.2
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.14.2_fix-std-runtime_error.patch
Labels: bug fix

#11682 {bio}[GCCcore/9.3.0] DIAMOND v0.9.36
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.36-GCC-9.3.0.eb
Labels: update

#11683 {bio}[GCCcore/9.3.0] DIAMOND v2.0.4
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.0.4-GCC-9.3.0.eb
Labels: update

#11894 Enable tests for most recent Bazel versions (3.x)
  easybuild/easyconfigs/b/Bazel/Bazel-3.4.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-3.6.0-GCCcore-9.3.0.eb
Labels: enhancement

#12029 Add Inline extension to recent Perl easyconfigs (5.30+)
  easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Labels: enhancement

#12034 {chem}[intel/2020a] QuickFF v2.2.7 w/ Python 3.8.2
  easybuild/easyconfigs/q/QuickFF/QuickFF-2.2.7-intel-2020a-Python-3.8.2.eb
Labels: update

#12040 {tools}[GCCcore/10.2.0] bpytop v1.0.60 w/ Python 3.8.6
  easybuild/easyconfigs/b/bpytop/bpytop-1.0.60-GCCcore-10.2.0.eb
Labels: new

#12041 {lib}[GCC/10.2.0] libcroco 0.6.13
  easybuild/easyconfigs/l/libcroco/libcroco-0.6.13-GCC-10.2.0.eb
Labels: update

#12042 {tools}[system/system] Nsight-Systems v2020.5.1
  easybuild/easyconfigs/n/Nsight-Systems/Nsight-Systems-2020.5.1.eb
Labels: new

#12043 {tools}[system/system] Nsight-Compute v2020.3.0
  easybuild/easyconfigs/n/Nsight-Compute/Nsight-Compute-2020.3.0.eb
Labels: new

#12019 {bio}[foss/2020a] HH-suite v3.3.0
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-foss-2020a.eb
Labels: update

#12047 {vis} gnuplot 5.2.8, ssl not reachable, changed back to non-ssl
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.8-GCCcore-9.3.0.eb
Labels: bug fix

#12031 {lib}[foss/2020b,intel/2020b] gensim v3.8.3 w/ Python 3.8.6
  easybuild/easyconfigs/g/gensim/gensim-3.8.3-foss-2020b.eb
  easybuild/easyconfigs/g/gensim/gensim-3.8.3-intel-2020b.eb
Labels: update

#12033 {bio}[GCC,9.3.0] STAR v2.6.7a, v2.7.7a
  easybuild/easyconfigs/s/STAR/STAR-2.7.6a-GCC-9.3.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.7a-GCC-9.3.0.eb
Labels: update

#12032 {math}[foss/2020a] Transformers v4.2.1 w/ Python 3.8.2
  easybuild/easyconfigs/t/Transformers/Transformers-4.2.1-foss-2020a-Python-3.8.2.eb
Labels: new

#12039 {chem}[foss,intel/2020b] ASE v3.21.1, GPAW v21.1.0 w/ Python 3.8.6
  easybuild/easyconfigs/a/ASE/ASE-3.21.1-foss-2020b.eb
  easybuild/easyconfigs/a/ASE/ASE-3.21.1-intel-2020b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.1.0-foss-2020b-ASE-3.21.1.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.1.0-intel-2020b-ASE-3.21.1.eb
Labels: update

#12010 {lib}[foss/2020b] GPyTorch v1.3.0 w/ Python 3.8.6
  easybuild/easyconfigs/g/GPyTorch/GPyTorch-1.3.0-foss-2020b.eb
Labels: new

#12050 STAR version 2.7.6a and 2.7.7a for gcc-10.2.0 Easyconfig files created, see also PR#12033
  easybuild/easyconfigs/s/STAR/STAR-2.7.6a-GCC-10.2.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.7a-GCC-10.2.0.eb
Labels: update

#12046 {bio}[foss/2020a] inferCNV v1.3.3 w/ Python 3.8.2
  easybuild/easyconfigs/i/inferCNV/inferCNV-1.3.3-foss-2020a-Python-3.8.2.eb
Labels: update

#12024 {data}[fosscuda/2020a] ITK v5.1.2 w/ Python 3.8.2
  easybuild/easyconfigs/i/ITK/ITK-5.1.2-fosscuda-2020a-Python-3.8.2.eb
Labels: update

#12045 {lang}[gompi/2020a] SOCI v4.0.1
  easybuild/easyconfigs/s/SOCI/SOCI-4.0.1-GCCcore-9.3.0.eb
Labels: new

#12009 {toolchain}[system/system] iomkl v2020b, imkl v2020.4.304, iompi v2020b, ...
  easybuild/easyconfigs/i/imkl/imkl-2020.4.304-iompi-2020b.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2020b.eb
  easybuild/easyconfigs/i/iompi/iompi-2020b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-iccifort-2020.4.304.eb
Labels: update

#11981 {toolchain}[system/system] imkl v2019.5.281, iomkl v2019b, iompi v2019b, ...
  easybuild/easyconfigs/i/imkl/imkl-2019.5.281-iompi-2019b.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2019b.eb
  easybuild/easyconfigs/i/iompi/iompi-2019b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-iccifort-2019.5.281.eb
Labels: update

#12020 fix download url for UDUNITS 2.2.26
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-10.2.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.2.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.3.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-9.3.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2018a.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2018b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2020a.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2017b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018a.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018b.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-iomkl-2018b.eb
Labels: bug fix

#12049 {chem}[foss/2019b,intel/2019b] QuantumESPRESSO v6.7
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-foss-2019b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-intel-2019b.eb
Labels: update

#12038 {bio}[foss/2019b] medaka v1.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/m/medaka/medaka-1.2.0-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#12051 {lang,lib,math,vis}[GCCcore/10.2.0] gnuplot v5.4.1, libcerf v1.14, libgd v2.3.0, ...
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/Lua/Lua-5.4.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libcerf/libcerf-1.14-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libgd/libgd-2.3.0-GCCcore-10.2.0.eb
Labels: update

#12057 ad fmri and AnalyzeFMRI extensions to R v4.0.3
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
Labels: enhancement

#12056 {bio}[foss/2020a] Teneto v0.5.1 w/ Python 3.8.2
  easybuild/easyconfigs/n/Nilearn/Nilearn-0.7.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/Teneto/Teneto-0.5.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/t/Teneto/templateflow-0.7.1_fix_egg_version.patch
Labels: new
