Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-12, with the labels that each got.

#14460 {devel}[foss/2021a] PyTorch v1.10.0 w/ Python 3.9.5 (CPU-only)
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.0-foss-2021a.eb
Labels: update

#14461 {phys}[intel/2021a] Yambo v5.0.4
  easybuild/easyconfigs/y/Yambo/Yambo-5.0.4-intel-2021a.eb
Labels: update

#14304 {lib}[GCCcore/11.2.0] tbb v2020.3
  easybuild/easyconfigs/t/tbb/tbb-2020.3-GCCcore-11.2.0.eb
Labels: update

#14462 {vis}[foss/2021a] torchvision v0.11.1 w/ Python 3.9.5
  easybuild/easyconfigs/t/torchvision/torchvision-0.11.1-foss-2021a.eb
Labels: update

#14459 {*}[foss/2021b] NCO v5.0.3, ESMF v8.2.0, netCDF-C++4 v4.3.1, ...
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-11.2.0-Java-11.eb
  easybuild/easyconfigs/e/ESMF/ESMF-8.2.0-foss-2021b.eb
  easybuild/easyconfigs/l/libdap/libdap-3.20.8-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/NCO/NCO-5.0.3-foss-2021b.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-gompi-2021b.eb
Labels: update

#14443 {bio}[foss/2020b] Relate v20211123
  easybuild/easyconfigs/r/Relate/Relate-20211123-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/r/Relate/Relate-20211123_add-cmake-install-targets.patch
Labels: new

#14470 {perf}[GCCcore/11.2.0] PAPI v6.0.0.1
  easybuild/easyconfigs/p/PAPI/PAPI-6.0.0.1-GCCcore-11.2.0.eb
Labels: update

#14466 debugger,devel}[GCCcore/11.2.0] GDB v11.1, makeinfo v6.8 w/ Python 3.9.6
  easybuild/easyconfigs/g/GDB/GDB-11.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.8-GCCcore-11.2.0.eb
Labels: update

#14471 {lang}[system/system] Julia v1.7.0
  easybuild/easyconfigs/j/Julia/Julia-1.7.0-linux-x86_64.eb
Labels: update

#14270 {math}[GCCcore/10.3.0] jupyter-matlab-proxy v0.3.4 w/ Python 3.9.5
  easybuild/easyconfigs/j/jupyter-matlab-proxy/jupyter-matlab-proxy-0.3.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/jupyter-matlab-proxy/jupyter-matlab-proxy-0.3.4_eb-matlab-license-file.patch
Labels: new

#14256 {bio}[fosscuda/2020b] Megalodon v2.3.5 w/ Python 3.8.6
  easybuild/easyconfigs/m/Megalodon/Megalodon-2.3.5-fosscuda-2020b.eb
Labels: update

#14483 {devel}[intel-compilers/2021.4.0] Boost v1.77.0
  easybuild/easyconfigs/b/Boost/Boost-1.77.0-intel-compilers-2021.4.0.eb
Labels: update

#14475 {bio}[GCC/10.3.0] FastANI v1.33
  easybuild/easyconfigs/f/FastANI/FastANI-1.33-GCC-10.3.0.eb
Labels: update

#14473 {bio}[GCCcore/10.3.0] prodigal v2.6.3
  easybuild/easyconfigs/p/prodigal/prodigal-2.6.3-GCCcore-10.3.0.eb
Labels: update

#14472 {tools}[intel/2021b] NCO v5.0.3
  easybuild/easyconfigs/e/ESMF/ESMF-8.2.0-intel-2021b.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-intel-compilers-2021.4.0.eb
  easybuild/easyconfigs/n/NCO/NCO-5.0.3-intel-2021b.eb
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-iimpi-2021b.eb
Labels: update

#14484 add covsim extension to R v4.1.2 easyconfig
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: enhancement

#14485 {chem}[intel/2021b] ABINIT v9.6.2
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.6.2-intel-2021b.eb
Labels: update

#14476 {bio}[foss/2021a] CheckM v1.1.3 w/ Python 3.9.5
  easybuild/easyconfigs/c/CheckM/CheckM-1.1.3-foss-2021a.eb
Labels: update

#14478 {bio}[GCCcore/10.3.0] ANIcalculator v1.0
  easybuild/easyconfigs/a/ANIcalculator/ANIcalculator-1.0-GCCcore-10.3.0.eb
Labels: new

#14492 improve sanity_check_paths in pugixml easyconfig
  easybuild/easyconfigs/p/pugixml/pugixml-1.11.4-GCCcore-10.3.0.eb
Labels: enhancement

#14093 {chem}[foss/2021a] ABINIT v9.4.2
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.4.2-foss-2021a.eb
Labels: update

#14305 {bio}[gompi/2021b] UShER v0.5.0 w/ Python 3.9.6
  easybuild/easyconfigs/u/UShER/UShER-0.5.0-gompi-2021b.eb
  easybuild/easyconfigs/u/UShER/UShER-0.5.0_external-tbb.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#14494 add dependency on libnsl for ANIcalculator
  easybuild/easyconfigs/a/ANIcalculator/ANIcalculator-1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libnsl/libnsl-1.3.0-GCCcore-10.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: enhancement, new

#14499 {bio}[GCCcore/10.2.0] idemux v0.1.6 w/ Python 3.8.6
  easybuild/easyconfigs/i/idemux/idemux-0.1.6-GCCcore-10.2.0.eb
Labels: new

#14497 add patch to fix CVE-2021-43527 in NSS
  easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.42.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.42.1_CVE-2021-43527.patch
  easybuild/easyconfigs/n/NSS/NSS-3.45-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.51-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.57-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.65-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.65_CVE-2021-43527.patch
  easybuild/easyconfigs/n/NSS/NSS-3.69-GCCcore-11.2.0.eb
Labels: bug fix

#14310 {bio}[foss/2021b] pangolin v3.1.16 w/ Python 3.9.6 + pangoLEARN v2021-10-18 and v2021-11-25
  easybuild/easyconfigs/p/pangolin/pangolin-3.1.16-foss-2021b-pangoLEARN-2021-10-18.eb
  easybuild/easyconfigs/p/pangolin/pangolin-3.1.16-foss-2021b-pangoLEARN-2021-11-25.eb
Labels: update

#14487 {devel}[GCCcore/10.3.0] cxxopts v3.0.0
  easybuild/easyconfigs/c/cxxopts/cxxopts-3.0.0-GCCcore-10.3.0.eb
Labels: new

#14488 {devel}[GCCcore/10.3.0] ELFIO v3.9
  easybuild/easyconfigs/e/ELFIO/ELFIO-3.9-GCCcore-10.3.0.eb
Labels: new

#14489 {devel}[GCCcore/10.3.0] termcolor v2.0.0
  easybuild/easyconfigs/t/termcolor/termcolor-2.0.0-GCCcore-10.3.0.eb
Labels: new

#14498 {perf}[foss/2021a] MUST v1.7.2 w/ Python 3.9.5
  easybuild/easyconfigs/m/MUST/MUST-1.7.2-foss-2021a.eb
Labels: update

#14319 {tools}[foss/2020b] pmx v2.0 w/ Python 2.7.18
  easybuild/easyconfigs/p/pmx/pmx-2.0-foss-2020b-Python-2.7.18.eb
Labels: new

#14295 {geo}[foss/2021a] WPS v4.3.1
  easybuild/easyconfigs/w/WPS/WPS-4.3.1-foss-2021a-dmpar.eb
Labels: update

#14269 Bazel (0.25.2, 0.26.1, 0.29.1, and 1.1.0) fix gettid nameclash with glibc 2.30
  easybuild/easyconfigs/b/Bazel/Bazel-0.25.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.25.2_rename_gettid.patch
  easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-9.3.0-Java-1.8.eb
  easybuild/easyconfigs/b/Bazel/Bazel-1.1.0-GCCcore-8.3.0.eb
Labels: bug fix

#14495 {bio}[foss/2021b] DUBStepR v1.2.0
  easybuild/easyconfigs/d/DUBStepR/DUBStepR-1.2.0-foss-2021b-R-4.1.2.eb
Labels: new

#14503 {perf}[GCC/11.2.0] BabelStream v3.4
  easybuild/easyconfigs/b/BabelStream/BabelStream-3.4-GCC-11.2.0-omp.eb
Labels: new

#14380 {tools}[foss/2021b] GPy v1.10.0 w/ Python 3.9.6
  easybuild/easyconfigs/g/GPy/GPy-1.10.0-foss-2021b.eb
Labels: new

#14510 Correctly set execute permissions for ANIcalculator binaries
  easybuild/easyconfigs/a/ANIcalculator/ANIcalculator-1.0-GCCcore-10.3.0.eb
Labels: bug fix

#14511 add patch to fix broken (hanging) Mash binaries
  easybuild/easyconfigs/m/Mash/Mash-2.0-foss-2018a.eb
  easybuild/easyconfigs/m/Mash/Mash-2.1-foss-2018b.eb
  easybuild/easyconfigs/m/Mash/Mash-2.2-GCC-9.3.0.eb
  easybuild/easyconfigs/m/Mash/Mash-2.2_fix-hardcoding.patch
  easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-10.3.0.eb
Labels: enhancement, bug fix

#14512 {bio}[system/system] CellRanger v6.1.2, CellRanger v6.0.2
  easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.2.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-6.1.2.eb
Labels: update

#14504 move cxxopts, termcolor and ELFIO header only libraries to SYSTEM toolchain
  easybuild/easyconfigs/c/cxxopts/cxxopts-3.0.0.eb
  easybuild/easyconfigs/e/ELFIO/ELFIO-3.9.eb
  easybuild/easyconfigs/t/termcolor/termcolor-2.0.0.eb
Labels: change

#14474 {bio}[GCCcore/10.3.0] MUMmer v3.23
  easybuild/easyconfigs/m/MUMmer/MUMmer-3.23-GCCcore-10.3.0.eb
Labels: update

#14479 {bio}[foss/2021a] dRep v3.0.0 w/ Python 3.9.5
  easybuild/easyconfigs/d/dRep/dRep-3.0.0-foss-2021a.eb
Labels: new

#14368 {math}[GCCcore/10.3.0] Gurobi v9.5.0 w/ Python 3.9.5
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.5.0-GCCcore-10.3.0.eb
Labels: update

#11983 {math}[GCCcore/9.3.0] Gurobi v9.0.1 w/ Python 3.8.2
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.1-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#14502 pass tests on A* GPUs by setting 'NVIDIA_TF32_OVERRIDE=0' in jax 0.2.19
  easybuild/easyconfigs/j/jax/jax-0.2.19-fosscuda-2020b.eb
Labels: bug fix

#14514 {bio}[GCCcore/11.2.0] Bracken v2.6.2
  easybuild/easyconfigs/b/Bracken/Bracken-2.6.2-GCCcore-11.2.0.eb
Labels: update

#14334 {tools}[foss/2021a] jax v0.2.24 w/ Python 3.9.5 + with/without CUDA v11.3.1
  easybuild/easyconfigs/j/jax/TensorFlow-2.7.0_cuda-noncanonical-include-paths.patch
  easybuild/easyconfigs/j/jax/jax-0.2.24-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/j/jax/jax-0.2.24-foss-2021a.eb
  easybuild/easyconfigs/j/jax/jax-0.2.24-foss-2021a_unimplemented.patch
  easybuild/easyconfigs/j/jax/jaxlib_local-tensorflow-repo.sed
Labels: update

#14513 {bio}[GCC/11.2.0] BCFtools v1.14
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.14-GCC-11.2.0.eb
Labels: update

#14507 {math}[GCCcore/11.2.0] Gurobi v9.5.0 w/ Python 3.9.6
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.5.0-GCCcore-11.2.0.eb
Labels: update

#14354 {tools}[GCCcore/11.2.0] rocm-smi v4.5.0
  easybuild/easyconfigs/r/rocm-smi/rocm-smi-4.5.0-GCCcore-11.2.0.eb
Labels: new

#14263 specify to use Python provided as dependency, remove separate_build_dir, and fix URL in comment for Arrow 0.17.1
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-fosscuda-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020b.eb
Labels: bug fix

#14501 {tools}[GCCcore/10.3.0] libtree v2.0.0
  easybuild/easyconfigs/l/libtree/libtree-2.0.0-GCCcore-10.3.0.eb
Labels: new

#14271 {compiler}[GCCcore/11.2.0] AOCC v3.1.0
  easybuild/easyconfigs/a/AOCC/AOCC-3.1.0-GCCcore-11.2.0.eb
Labels: update

#14415 don't add bin subdir to $PATH via modextrapaths in ReFrame easyconfigs
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.0.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.2.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.3.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.4.1.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.5.0.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.5.1.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.5.2.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.6.2.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.6.3.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.7.3.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.8.0.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.9.0.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.9.1.eb
Labels: bug fix

#14327 {tools}[GCCcore/11.2.0] Clang-AOMP v4.5.0, rocm-cmake v4.5.0, rocminfo v4.5.0, ROCR-Runtime v4.5.0, ...
  easybuild/easyconfigs/c/Clang-AOMP/Clang-AOMP-4.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/Clang-AOMP/clang-aomp-rocm-4.5.0-aomp-extras-remove-hardcoded-devicelib-path.patch
  easybuild/easyconfigs/c/Clang-AOMP/clang-aomp-rocm-4.5.0-openmp-remove-hardcoded-source-paths.patch
  easybuild/easyconfigs/r/ROCR-Runtime/ROCR-Runtime-4.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/ROCT-Thunk-Interface/ROCT-Thunk-Interface-4.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/ROCm-CompilerSupport/ROCm-CompilerSupport-4.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/rocm-cmake/rocm-cmake-4.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/rocminfo/rocminfo-4.5.0-GCCcore-11.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#14535 add missing Perl build dependency for Longshot
  easybuild/easyconfigs/l/Longshot/Longshot-0.3.4-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/Longshot/Longshot-0.4.1-GCC-7.3.0-2.30.eb
  easybuild/easyconfigs/l/Longshot/Longshot-0.4.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/Longshot/Longshot-0.4.3-GCCcore-10.2.0.eb
Labels: bug fix

#14528 {bio}[GCCcore/10.3.0] Brotli-python v1.0.9 w/ Python 3.9.5
  easybuild/easyconfigs/b/Brotli-python/Brotli-python-1.0.9-GCCcore-10.3.0.eb
Labels: new

#14536 add googletest build dependency for Highway
  easybuild/easyconfigs/h/Highway/Highway-0.12.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/h/Highway/Highway-0.12.2-GCCcore-10.3.0.eb
Labels: bug fix

#14533 {math}[GCCcore/10.2.0] Eigen v3.4.0
  easybuild/easyconfigs/e/Eigen/Eigen-3.4.0-GCCcore-10.2.0.eb
Labels: update

#14326 {bio}[foss/2020a] CMSeq v1.0.3 w/ Python 3.8.2
  easybuild/easyconfigs/c/CMSeq/CMSeq-1.0.3-foss-2020a-Python-3.8.2.eb
Labels: new

#14537 seed in PCRE2 sources to fix broken MariaDB 10.5.8 + 10.6.4 easyconfigs
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.5.8-GCC-10.2.0.eb
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.6.4-GCC-10.3.0.eb
Labels: bug fix

#14339 {tools}[GCCcore/11.2.0] HIP v4.5.0
  easybuild/easyconfigs/h/HIP/HIP-4.5.0-GCCcore-11.2.0-amd.eb
  easybuild/easyconfigs/h/HIP/hipamd-rocm-4.5.0-remove-testing.patch
Labels: new

#14355 {tools}[GCCcore/11.2.0] ROCm v4.5.0
  easybuild/easyconfigs/r/ROCm/ROCm-4.5.0-GCCcore-11.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#11857 {bio}[foss/2019a] ANGEL v3.0 w/ Python 3.7.2
  easybuild/easyconfigs/a/ANGEL/ANGEL-3.0-foss-2019a-Python-3.7.2.eb
Labels: new

#14538 prepare release notes for EasyBuild v4.5.1 + bump version to 4.5.1
  RELEASE_NOTES
  setup.py
Labels: update

#14545 {tools}[dummy/dummy] EasyBuild v4.5.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.1.eb
Labels: update

#14522 {chem}[gompi/2021a] ORCA v5.0.2
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.2-gompi-2021a-static.eb
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.2-gompi-2021a.eb
Labels: update

#13199 {bio}[GCC/9.3.0] RAPSearch2 v2.24
  easybuild/easyconfigs/r/RAPSearch2/RAPSearch2-2.24-GCC-9.3.0.eb
Labels: new

#14549 {bio}[foss/2021a] MicrobeAnnotator v2.0.5 w/ Python 3.9.5
  easybuild/easyconfigs/m/MicrobeAnnotator/MicrobeAnnotator-2.0.5-foss-2021a.eb
Labels: new

#14565 use proper Perl dependency for worker 1.6.12 with foss/2019a (fixes installation on RHEL8 OS)
  easybuild/easyconfigs/w/worker/worker-1.6.12-foss-2019a.eb
Labels: bug fix

#14567 {tools}[foss/2021b] worker v1.6.12
  easybuild/easyconfigs/w/worker/worker-1.6.12-foss-2021b.eb
Labels: update

#14575 {lang}[foss/2021b] numba v0.54.1 w/ Python 3.9.6 (on top of LLVM 12.0.1)
  easybuild/easyconfigs/n/numba/llvmlite-0.37.0_fix-LLVM-12.patch
  easybuild/easyconfigs/n/numba/numba-0.54.1-foss-2021b.eb
  easybuild/easyconfigs/n/numba/numba-0.54.1_fix-numpy-1.21.patch
Labels: update

#14574 {math}[foss/2021b,intel/2021b] statsmodels v0.13.1 w/ Python 3.9.6
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.13.1-foss-2021b.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.13.1-intel-2021b.eb
Labels: update

#14573 {data}[foss/2021b,intel/2021b] h5py v3.6.0 w/ Python 3.9.6
  easybuild/easyconfigs/h/h5py/h5py-3.6.0-foss-2021b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.6.0-intel-2021b.eb
Labels: update

#14578 include output of failing code style check in message produced by failing easyconfigs style test
  test/easyconfigs/styletests.py
Labels: enhancement, tests

#14577 {bio}[GCCcore/11.2.0] annovar v20191024
  easybuild/easyconfigs/a/annovar/annovar-20191024-GCCcore-11.2.0-Perl-5.34.0.eb
Labels: update

#14572 {*}[foss/2021b] leidenalg v0.8.8, python-igraph v0.9.8, arpack-ng v3.8.0, PyCairo v1.20.1 (+ deps) w/ Python 3.9.6
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.8.0-foss-2021b.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.4.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/i/igraph/igraph-0.9.5-foss-2021b.eb
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.8-foss-2021b.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.20.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.9.8-foss-2021b.eb
Labels: update

#14576 {bio}[foss/2021b] scanpy v1.8.2 w/ Python 3.9.6
  easybuild/easyconfigs/s/scanpy/scanpy-1.8.2-foss-2021b.eb
Labels: update

#14569 {lib}[foss/2020b] phonopy v2.12.0 w/ Python 3.8.6
  easybuild/easyconfigs/p/phonopy/phonopy-2.12.0-foss-2020b.eb
Labels: update

#14586 retain version in filename for cromwell sources
  easybuild/easyconfigs/c/cromwell/cromwell-56-Java-11.eb
Labels: bug fix

#14481 {vis,math}[foss/2021a] FMPy v0.3.2, PyOpenGL v3.1.5, PyQtGraph v0.12.3 w/ Python 3.9.5
  easybuild/easyconfigs/f/FMPy/FMPy-0.3.2-foss-2021a.eb
  easybuild/easyconfigs/p/PyOpenGL/PyOpenGL-3.1.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.12.3-foss-2021a.eb
Labels: new, update

#14583 {bio}[GCCcore/11.2.0] genozip v13.0.5
  easybuild/easyconfigs/g/genozip/genozip-13.0.5-GCCcore-11.2.0.eb
Labels: new

#14550 {bio}[GCC/11.2.0] Bowtie2 v2.4.4 w/ Python 3.9.6
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.4-GCC-11.2.0.eb
Labels: update

#14557 {phys}[foss/2021a] ShengBTE v1.1.1
  easybuild/easyconfigs/s/ShengBTE/ShengBTE-1.1.1-foss-2021a.eb
Labels: new

#14555 {bio}[GCC/11.2.0] MAGMA v1.09b
  easybuild/easyconfigs/m/MAGMA/MAGMA-1.09b-GCC-11.2.0.eb
Labels: update

#14585 {bio}[GCCcore/11.2.0,foss/2021b] SEPP v4.5.0, DendroPy v4.5.2 w/ Python 3.9.6
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.5.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/SEPP/SEPP-4.5.1-foss-2021b.eb
Labels: update

#14582 {numlib}[foss/2021a] Armadillo v10.7.5
  easybuild/easyconfigs/a/Armadillo/Armadillo-10.7.5-foss-2021a.eb
Labels: update

#14562 {bio}[foss/2020a] PhyloPhlAn v3.0 w/ Python 3.8.2
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.31-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PhyloPhlAn/PhyloPhlAn-3.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/SEPP/SEPP-4.3.10-foss-2020a-Python-3.8.2.eb
Labels: new

#14553 {system}[GCCcore/11.2.0] libdeflate v1.8
  easybuild/easyconfigs/l/libdeflate/libdeflate-1.8-GCCcore-11.2.0.eb
Labels: update

#14552 {lib}[GCCcore/11.2.0] ISA-L v2.30.0
  easybuild/easyconfigs/i/ISA-L/ISA-L-2.30.0-GCCcore-11.2.0.eb
Labels: update

#14580 {data}[gompi/2019b] CDO v1.9.10
  easybuild/easyconfigs/c/CDO/CDO-1.9.10-gompi-2019b.eb
Labels: update

#14551 {bio}[foss/2021b] Bismark v0.23.1
  easybuild/easyconfigs/b/Bismark/Bismark-0.23.1-foss-2021b.eb
Labels: update

#14554 {bio}[GCC/11.2.0] fastp v0.23.2
  easybuild/easyconfigs/f/fastp/fastp-0.23.2-GCC-11.2.0.eb
Labels: update

#14518 {tools}[foss/2021b] SCopeLoomR v0.13.0
  easybuild/easyconfigs/s/SCopeLoomR/SCopeLoomR-0.13.0-foss-2021b-R-4.1.2.eb
Labels: new

#12917 {bio}[foss/2020a] MetaPhlAn v3.0.9 w/ Python 3.8.2
  easybuild/easyconfigs/m/MetaPhlAn/MetaPhlAn-3.0.9-foss-2020a-Python-3.8.2.eb
Labels: update

#14593 {lang}[system/system] Anaconda3 v2021.11
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2021.11.eb
Labels: update

#14581 {tools}[foss/2021a] PuLP v2.5.1 w/ Python 3.9.5
  easybuild/easyconfigs/p/PuLP/PuLP-2.5.1-foss-2021a.eb
Labels: new

#14587 {bio}[GCCcore/10.3.0,gompi/2021a] IQ-TREE v2.1.3, LSD2 v2.3
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.1.3-gompi-2021a.eb
  easybuild/easyconfigs/l/LSD2/LSD2-2.3-GCCcore-10.3.0.eb
Labels: update

#14541 {vis}[gompi/2021a] ncview v2.1.8
  easybuild/easyconfigs/n/ncview/ncview-2.1.8-gompi-2021a.eb
Labels: update

#14539 {compiler}[system/system] NVHPC v21.11
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.11.eb
Labels: update

#14529 {bio}[gompi/2021a] RAxML v8.2.12
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-gompi-2021a-hybrid-avx2.eb
Labels: update

#14531 {bio}[GCC/10.3.0] TreeMix v1.13
  easybuild/easyconfigs/t/TreeMix/TreeMix-1.13-GCC-10.3.0.eb
Labels: new

#14170 {tools}[fosscuda/2020b] Horovod v0.23.0 w/ Python 3.8.6 + TensorFlow 2.5.0
  easybuild/easyconfigs/h/Horovod/Horovod-0.23.0-fosscuda-2020b-TensorFlow-2.5.0.eb
Labels: update

#14519 {vis}[fosscuda/2020b] PyOpenCL v2021.1.2
  easybuild/easyconfigs/p/PyOpenCL/PyOpenCL-2021.1.2-fosscuda-2020b.eb
Labels: update

#14564 {bio}[foss/2021a] PhyloPhlAn v3.0.2 w/ Python 3.9.5
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.11-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.31-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/PhyloPhlAn/PhyloPhlAn-3.0.2-foss-2021a.eb
  easybuild/easyconfigs/s/SEPP/SEPP-4.5.0-foss-2021a.eb
  easybuild/easyconfigs/t/trimAl/trimAl-1.4.1-GCCcore-10.3.0.eb
Labels: new

#14075 {bio}[fosscuda/2020b] IsoNet v0.1_20210822_04_674f67f w/ Python 3.8.6
  easybuild/easyconfigs/i/IsoNet/IsoNet-0.1_20210822_04_674f67f-fosscuda-2020b.eb
Labels: new

#14251 {tools}[GCCcore/11.2.0] mold v0.9.6, xxHash v0.8.0
  easybuild/easyconfigs/m/mold/mold-0.9.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/xxHash/xxHash-0.8.0-GCCcore-11.2.0.eb
Labels: new

#14589 {devel}[fosscuda/2020b] PyTorch v1.10.0, CMake v3.20.1, expecttest v0.1.3 w/ Python 3.8.6
  easybuild/easyconfigs/c/CMake/CMake-3.20.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/e/expecttest/expecttest-0.1.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.0-fosscuda-2020b.eb
Labels: update

#14556 {lib}[foss/2021a] OpenFace v2.2.0, dlib v19.22
  easybuild/easyconfigs/d/dlib/dlib-19.22-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/d/dlib/dlib-19.22-foss-2021a.eb
  easybuild/easyconfigs/o/OpenFace/OpenFace-2.2.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/OpenFace/OpenFace-2.2.0-foss-2021a.eb
  easybuild/easyconfigs/o/OpenFace/OpenFace-2.2.0_avoid-hardcoded-OpenBLAS.patch
Labels: new

#14595 {tools}[GCCcore/11.2.0] mold v1.0.0
  easybuild/easyconfigs/m/mold/mold-1.0.0-GCCcore-11.2.0.eb
Labels: update

#14584 add patch for Rust 1.52.2 and 1.54.0 to fix build when using alternate sysroot
  easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.52.1_sysroot-fix-interpreter.patch
  easybuild/easyconfigs/r/Rust/Rust-1.54.0-GCCcore-11.2.0.eb
Labels: bug fix, EESSI

#14594 specify compiler to use in WildMagic easyconfig
  easybuild/easyconfigs/w/WildMagic/WildMagic-5.17-foss-2018b.eb
Labels: bug fix

#14570 {data}[GCCcore/11.2.0] dill v0.3.4 w/ Python 3.9.6
  easybuild/easyconfigs/d/dill/dill-0.3.4-GCCcore-11.2.0.eb
Labels: update

#14597 {perf}[GCCcore/11.2.0] Austin v3.2.0 w/ Python 3.9.6
  easybuild/easyconfigs/a/Austin/Austin-3.2.0-GCCcore-11.2.0.eb
Labels: new

#14526 {bio}[foss/2021a] cDNA_Cupcake v26.0.0 w/ Python 3.9.5
  easybuild/easyconfigs/c/cDNA_Cupcake/cDNA_Cupcake-26.0.0-foss-2021a.eb
Labels: update

#14596 {perf}[system/system] Austin v3.2.0
  easybuild/easyconfigs/a/Austin/Austin-3.2.0.eb
Labels: new

#14520 {bio}[GCC/10.3.0] DIAMOND v2.0.13
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.0.13-GCC-10.3.0.eb
Labels: update

#14530 {bio}[gompi/2021a] ExaML v3.0.22
  easybuild/easyconfigs/e/ExaML/ExaML-3.0.22-gompi-2021a-hybrid-avx.eb
Labels: new

#14523 {chem}[foss/2020b] yaff 1.6.0
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2020b.eb
  easybuild/easyconfigs/y/yaff/h5py-2.10.0_avoid-mpi-init.patch
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-foss-2020b.eb
Labels: update

#7471 {vis}[iccifort/2018.1.163-GCC-6.4.0-2.28] Embree v3.4.0
  easybuild/easyconfigs/e/Embree/Embree-3.4.0-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
Labels: new

#8995 {bio}[foss/2018b] RaGOO v1.11, intervaltree v3.0.2 w/ Python 3.6.6
  easybuild/easyconfigs/i/intervaltree-python/intervaltree-python-3.0.2-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/r/RaGOO/RaGOO-1.11-foss-2018b-Python-3.6.6.eb
Labels: new, update

#14599 {bio}[foss/2021a] MultiQC v1.11 w/ Python 3.9.5
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.11-foss-2021a.eb
Labels: update

#14600 {bio}[foss/2020b] MultiQC v1.10.1 w/ Python 3.8.6
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.10.1-foss-2020b.eb
Labels: update

#14571 {math}[system/system] MATLAB v2021b
  easybuild/easyconfigs/m/MATLAB/MATLAB-2021b.eb
Labels: update

#14602 {lang}[system/system] Julia v1.6.5
  easybuild/easyconfigs/j/Julia/Julia-1.6.5-linux-x86_64.eb
Labels: update

#14605 Add git as build dependency to x265
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.2.0.eb
Labels: bug fix

#14017 {devel}[GCCcore/11.2.0] Qt5 v5.15.2
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.2_fix-gcc11.patch
Labels: update

#14588 {bio}[GCCcore/10.3.0] MUSCLE v5.0.1428
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-5.0.1428-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-5.0.1428_add-ver-counter-header.patch
Labels: update

#14609 {tools}[GCCcore/10.2.0] numdiff v5.9.0
  easybuild/easyconfigs/n/numdiff/numdiff-5.9.0-GCCcore-10.2.0.eb
Labels: new

#14606 {lib,vis}[GCCcore/11.2.0] gnuplot v5.4.2, libgd v2.3.3
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libgd/libgd-2.3.3-GCCcore-11.2.0.eb
Labels: update

#13264 {tools}[system/system] itac v2021.2.0
  easybuild/easyconfigs/i/itac/itac-2021.2.0.eb
Labels: update

#13301 {system}[GCC/10.3.0,system/system] CUDAcore v11.4.0
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.4.0.eb
Labels: update

#14608 {cae,math,vis}[foss/2021a] gmsh v4.9.0, occt v7.5.0p1, FreeImage v3.18.0 w/ Python 3.9.5
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.9.0-foss-2021a.eb
  easybuild/easyconfigs/o/occt/occt-7.5.0p1-foss-2021a.eb
Labels: update

#13055 {devel}[GCCcore/10.3.0] Extrae v3.8.3, libdwarf v20210305, libelf v0.8.13
  easybuild/easyconfigs/e/Extrae/Extrae-3.8.3-gompi-2021a.eb
  easybuild/easyconfigs/l/libdwarf/libdwarf-20210305-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libelf/libelf-0.8.13-GCCcore-10.3.0.eb
Labels: update

#14610 {tools}[system/system] JUBE v2.4.2
  easybuild/easyconfigs/j/JUBE/JUBE-2.4.2.eb
Labels: update

#7488 {phys}[intel/2018a] Calcam v2.1.0 w/ Python 2.7.14 + 3.6.4
  easybuild/easyconfigs/c/Calcam/Calcam-2.1.0-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/c/Calcam/Calcam-2.1.0-intel-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.9.2-intel-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/s/SIP/SIP-4.19.8-intel-2018a-Python-2.7.14.eb
Labels: new, update

#10731 {lang}[foss/2020a] numba v0.50.1 w/ Python 3.8.2
  easybuild/easyconfigs/n/numba/numba-0.50.1-foss-2020a-Python-3.8.2.eb
Labels: update

#12708 {devel}[foss/2020b] Spark 3.1.1
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020b.eb
  easybuild/easyconfigs/s/Spark/Spark-3.1.1-foss-2020b.eb
Labels: update

#14615 {tools}[foss/2021b] DyMat v0.7 w/ Python 3.9.6
  easybuild/easyconfigs/d/DyMat/DyMat-0.7-foss-2021b-2020-12-12.eb
Labels: new

#14617 {bio}[GCCcore/11.2.0] alevin-fry v0.4.3
  easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.4.3-GCCcore-11.2.0.eb
Labels: new

#14521 {bio}[GCCcore/10.3.0,foss/2021a] GTDB-Tk v1.7.0 w/ Python 3.9.5
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-1.7.0-foss-2021a.eb
Labels: update

#14622 {devel}[system/system] Spack v0.17.0
  easybuild/easyconfigs/s/Spack/Spack-0.17.0.eb
Labels: update

#14619 fix broken patch file for recent GPAW versions
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Add-Easybuild-configuration-files.patch
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-foss-2019b-ASE-3.20.1-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-foss-2020b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-intel-2019b-ASE-3.20.1-Python-3.7.4.eb
  easybuild/easyconfigs/g/GPAW/GPAW-20.10.0-intel-2020b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.1.0-foss-2020b-ASE-3.21.1.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.1.0-intel-2020b-ASE-3.21.1.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.6.0-foss-2020b-ASE-3.22.0.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.6.0-foss-2021a.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.6.0-intel-2020b-ASE-3.22.0.eb
Labels: bug fix

#14620 {toolchain} intel/2022.00
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2022.00.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2022.00.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2022.0.1-iimpi-2022.00.eb
  easybuild/easyconfigs/i/imkl/imkl-2022.0.1.eb
  easybuild/easyconfigs/i/impi/impi-2021.5.0-intel-compilers-2022.0.1.eb
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2022.0.1.eb
  easybuild/easyconfigs/i/intel/intel-2022.00.eb
Labels: update

#14627 {tools}[system/system] VTune v2022.0.0
  easybuild/easyconfigs/v/VTune/VTune-2022.0.0.eb
Labels: update

#14616 {tools}[foss/2021b] PyCalib v0.1.0.dev0 w/ Python 3.9.6
  easybuild/easyconfigs/p/PyCalib/PyCalib-0.1.0.dev0-foss-2021b.eb
Labels: new

#14629 {tools}[system/system] itac v2021.5.0
  easybuild/easyconfigs/i/itac/itac-2021.5.0.eb
Labels: update

#14630 {tools}[system/system] Inspector v2022.0.0
  easybuild/easyconfigs/i/Inspector/Inspector-2022.0.0.eb
Labels: update

#14626 {perf}[system/system] AMD-uProf v3.4.502
  easybuild/easyconfigs/a/AMD-uProf/AMD-uProf-3.4.502.eb
Labels: new

#7580 {bio}[intel/2018b] atropos v1.1.21 w/ Python 3.6.6 (+ deps)
  easybuild/easyconfigs/a/atropos/atropos-1.1.21-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/n/NGS-Python/NGS-Python-2.9.3-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/n/NGS-Python/NGS-Python-2.9.3_fix-python-install-prefix.patch
  easybuild/easyconfigs/p/Pysam/Pysam-0.15.1-intel-2018b-Python-3.6.6.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update
