Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-08, with the labels that each got.

#13534 {tools}[foss/2021a] Quandl v3.6.1 w/ Python 3.9.5
  easybuild/easyconfigs/q/Quandl/Quandl-3.6.1-foss-2021a.eb
Labels: update

#13530 {tools}[GCCcore/11.2.0] binutils v2.37, GCCcore v11.2.0, zlib v1.2.11, ...
  easybuild/easyconfigs/b/Bison/Bison-3.7.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.37-GCCcore-11.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.37.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GCC/GCC-11.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.2.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.48.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-11.2.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-11.2.0.eb
Labels: update

#13537 {chem}[foss/2021a] PLUMED v2.7.2 w/ Python 3.9.5
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-foss-2021a.eb
Labels: update

#13536 nanopore 0.13.3 add VBZ compress capability to nanopore 0.13.3 (for fast5 files)
  easybuild/easyconfigs/n/nanopolish/nanopolish-0.13.3-foss-2020b.eb
  easybuild/easyconfigs/v/VBZ-Compression/VBZ-Compression-1.0.1-gompi-2020b.eb
Labels: enhancement, new

#13544 add cobalt extension for recent R 4.0.x and 4.1.0 easyconfigs
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13545 {vis}[GCCcore/10.2.0] almosthere v2.0.2
  easybuild/easyconfigs/a/almosthere/almosthere-2.0.2-GCCcore-10.2.0.eb
Labels: update

#13547 {bio}[GCCcore/10.2.0] bgen v4.1.3
  easybuild/easyconfigs/b/bgen/bgen-4.1.3-GCCcore-10.2.0.eb
Labels: update

#13549 add CBPS extension for recent R 4.0.x and 4.1.0 easyconfigs
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13407 {numlib}[foss/2021a] petsc4py v3.14.0, SLEPc v3.15.1, slepc4py v3.15.1
  easybuild/easyconfigs/p/petsc4py/petsc4py-3.15.0-foss-2021a.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.15.1-foss-2021a.eb
  easybuild/easyconfigs/s/slepc4py/slepc4py-3.15.1-foss-2021a.eb
Labels: update

#13532 {mpi}[GCC/10.3.0] MPICH v3.4.2
  easybuild/easyconfigs/m/MPICH/MPICH-3.4.2-GCC-10.3.0.eb
Labels: update

#13554 {tools}[GCCcore/10.3.0] archspec v0.1.2 w/ Python 3.9.5
  easybuild/easyconfigs/a/archspec/archspec-0.1.2-GCCcore-10.3.0.eb
Labels: update

#13542 Fix p7zip path issues (Issue #13540)
  easybuild/easyconfigs/p/p7zip/p7zip-17.03-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/p7zip/p7zip-17.04-GCCcore-10.3.0.eb
Labels: bug fix

#13555 {math}[GCCcore/10.3.0] Voro++ v0.4.6
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-10.3.0.eb
Labels: update

#13558 {math}[foss/2021a] molmod v1.4.8 w/ Python 3.9.5
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2021a.eb
Labels: update

#13556 {chem}[GCCcore/10.3.0] kim-api v2.2.1
  easybuild/easyconfigs/k/kim-api/kim-api-2.2.1-GCCcore-10.3.0.eb
Labels: update

#13557 {math}[foss/2021a] ScaFaCoS v1.0.1
  easybuild/easyconfigs/s/ScaFaCoS/ScaFaCoS-1.0.1-foss-2021a.eb
Labels: update

#13413 {vis}[GCC/10.3.0] wxWidgets v3.1.5, GST-plugins-base v1.18.4, GStreamer v1.18.4, ...
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.18.4-GCC-10.3.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.4-GCC-10.3.0.eb
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.1.5-GCC-10.3.0.eb
Labels: update

#13561 {tools}[GCCcore/11.2.0] libarchive v3.5.1, XZ v5.2.5
  easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-11.2.0.eb
Labels: update

#13562 {tools}[GCCcore/11.2.0] cURL v7.78.0
  easybuild/easyconfigs/c/cURL/cURL-7.78.0-GCCcore-11.2.0.eb
Labels: update

#13527 {perf}[foss/2021a] Paraver v4.9.2
  easybuild/easyconfigs/p/Paraver/Paraver-4.9.2-foss-2021a.eb
Labels: update

#13567 {system}[GCCcore/11.2.0] libgcrypt v1.9.3, libgpg-error v1.42
  easybuild/easyconfigs/l/libgcrypt/libgcrypt-1.9.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.42-GCCcore-11.2.0.eb
Labels: update

#13565 add SBdecomp extension for recent R 4.0.x and 4.1.0 easyconfigs
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13579 Add missing zlib dependency to libarchive
  easybuild/easyconfigs/l/libarchive/libarchive-3.4.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.4.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.4.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-8.3.0.eb
Labels: bug fix

#13563 {devel}[GCCcore/11.2.0] PCRE v8.45, PCRE2 v10.37
  easybuild/easyconfigs/p/PCRE/PCRE-8.45-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.37-GCCcore-11.2.0.eb
Labels: update

#13564 {devel}[GCCcore/11.2.0] CMake v3.21.1, ncurses v6.2, pkg-config v0.29.2
  easybuild/easyconfigs/c/CMake/CMake-3.21.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-11.2.0.eb
Labels: update

#13583 {system}[system/system] CUDAcore v11.4.1
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.4.1.eb
Labels: update

#13584 {bio}[GCC/10.3.0] bioawk v1.0
  easybuild/easyconfigs/b/bioawk/bioawk-1.0-GCC-10.3.0.eb
Labels: update

#13585 {lib}[GCC/10.3.0] CharLS v2.2.0
  easybuild/easyconfigs/c/CharLS/CharLS-2.2.0-GCCcore-10.2.0.eb
Labels: update

#13566 {tools}[GCCcore/11.2.0] zstd v1.5.0, gzip v1.10, LZO v2.10, ...
  easybuild/easyconfigs/g/gzip/gzip-1.10-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libzip/libzip-1.7.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.9.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/p7zip/p7zip-17.04-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/pigz/pigz-2.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.5.0-GCCcore-11.2.0.eb
Labels: update

#13575 {lib}[GCCcore/11.2.0] giflib v5.2.1, JasPer v2.0.33, LibTIFF v4.3.0, ...
  easybuild/easyconfigs/g/giflib/giflib-5.2.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/j/JasPer/JasPer-2.0.33-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.3.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.37-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libwebp/libwebp-1.2.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-GCCcore-11.2.0.eb
  easybuild/easyconfigs/o/OpenEXR/OpenEXR-3.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.4.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/x264/x264-20210613-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-11.2.0.eb
Labels: update

#13452 {bio}[foss-2020b,fosscuda-2020b] OpenMM v7.5.1
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.1-foss-2020b.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.1-fosscuda-2020b.eb
Labels: update

#13551 patch so that MaxBin2 uses the EB provided Perl and not the system Perl
  easybuild/easyconfigs/m/MaxBin/MaxBin-2.2.7-gompi-2020b.eb
Labels: bug fix

#13570 {chem,data}[intel/2020a] horton v2.1.1, h5py v2.10.0 w/ Python 2.7.18
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-intel-2020a-Python-2.7.18.eb
  easybuild/easyconfigs/h/horton/horton-2.1.1-intel-2020a-Python-2.7.18.eb
Labels: update

#13580 {numlib}[GCC/11.2.0] OpenBLAS v0.3.17
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.17-GCC-11.2.0.eb
Labels: update

#13591 {lang}[GCCcore/11.2.0] Tcl v8.6.11
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.11-GCCcore-11.2.0.eb
Labels: update

#13592 {lib}[GCCcore/11.2.0] LMDB v0.9.29
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.29-GCCcore-11.2.0.eb
Labels: update

#13593 {system}[GCCcore/11.2.0] libpci v3.7.0
  easybuild/easyconfigs/l/libpci/libpci-3.7.0-GCCcore-11.2.0.eb
Labels: update

#13595 {devel,lib}[GCCcore/11.2.0] Doxygen v1.9.1, libiconv v1.16
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.9.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.16-GCCcore-11.2.0.eb
Labels: update

#13594 {lib}[GCCcore/11.2.0] libffi v3.4.2
  easybuild/easyconfigs/l/libffi/libffi-3.4.2-GCCcore-11.2.0.eb
Labels: update

#13600 {math}[GCCcore/11.2.0] Eigen v3.3.9
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.9-GCCcore-11.2.0.eb
Labels: update

#13601 {devel}[GCCcore/11.2.0] libgit2 v1.1.1
  easybuild/easyconfigs/l/libgit2/libgit2-1.1.1-GCCcore-11.2.0.eb
Labels: update

#13602 {numlib}[GCCcore/11.2.0] NLopt v2.7.0
  easybuild/easyconfigs/n/NLopt/NLopt-2.7.0-GCCcore-11.2.0.eb
Labels: update

#13603 {lib}[GCCcore/11.2.0] double-conversion v3.1.5
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.5-GCCcore-11.2.0.eb
Labels: update

#13605 {lib}[GCCcore/11.2.0] libunwind v1.5.0
  easybuild/easyconfigs/l/libunwind/libunwind-1.5.0-GCCcore-11.2.0.eb
Labels: update

#13608 {lib}[GCCcore/11.2.0] libyaml v0.2.5
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.5-GCCcore-11.2.0.eb
Labels: update

#13609 {vis}[GCCcore/11.2.0] pixman v0.40.0
  easybuild/easyconfigs/p/pixman/pixman-0.40.0-GCCcore-11.2.0.eb
Labels: update

#13610 {lib}[GCCcore/11.2.0] libidn v1.38, libidn2 v2.3.2
  easybuild/easyconfigs/l/libidn/libidn-1.38-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-11.2.0.eb
Labels: update

#13282 {perf}[gompi/2021a] OSU-Micro-Benchmarks v5.7.1, NCCL v2.10.3, magma v2.6.1 with CUDA 11.3.1
  easybuild/easyconfigs/m/magma/magma-2.6.1-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/m/magma/magma-2.6.1_allow-all-sms.patch
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-10.3.0-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-gompi-2021a-CUDA-11.3.1.eb
Labels: update

#13408 {bio}[foss/2021a] CellRank 1.4.0
  easybuild/easyconfigs/c/CellRank/CellRank-1.4.0-foss-2021a.eb
  easybuild/easyconfigs/c/CellRank/cellrank-1.4.0_numba.patch
Labels: new

#13625 add patch for OpenBLAS v0.3.17 to workaround problem in C/ZBLAS3 tests with GCC 11.x and -ftree-vectorize
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.17-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.17_workaround-gcc11-miscompiling-C-ZBLAS3-tests.patch
Labels: enhancement

#13438 {chem}[intel/2021a] OpenMolcas 21.06
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-intel-2021a.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-21.06-intel-2021a.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-21.06_mcpdft_deps.patch
Labels: update

#13616 Update Hypre URLs and checksums (moved)
  easybuild/easyconfigs/h/Hypre/Hypre-2.15.1-foss-2019a.eb
  easybuild/easyconfigs/h/Hypre/Hypre-2.15.1-intel-2019a.eb
Labels: bug fix

#13626 {tools}[foss/2021a] IRkernel v1.2 w/ Python 3.9.5
  easybuild/easyconfigs/i/IRkernel/IRkernel-1.2-foss-2021a-R-4.1.0.eb
Labels: update

#13612 {vis}[GCCcore/10.2.0] FreeImage v3.18.0
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-10.2.0.eb
Labels: update

#13613 fix build of DIRAC 19.0 easyconfig with high compiler optimizations
  easybuild/easyconfigs/d/DIRAC/DIRAC-19.0-intel-2020a-Python-2.7.18-int64.eb
  easybuild/easyconfigs/d/DIRAC/DIRAC-19.0-intel-2020a-Python-2.7.18-mpi-int64.eb
  easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_use_easybuild_opts.patch
  easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_use_easybuild_opts_intel.patch
Labels: bug fix

#13629 don't include unversioned go-basic.odo and goslin_generic.odo files in GOATOOLS installation (renamed from goatools)
  easybuild/easyconfigs/g/GOATOOLS/GOATOOLS-1.1.6-foss-2020b.eb
  easybuild/easyconfigs/g/goatools/goatools-1.1.6-foss-2020b.eb
Labels: bug fix, change

#13573 {tools}[GCCcore/11.2.0] Perl v5.34.0, expat v2.4.1, ...
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-11.2.0.eb
  easybuild/easyconfigs/e/expat/expat-2.4.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/groff/groff-1.22.4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.34.0-GCCcore-11.2.0.eb
Labels: new, update

#13576 {devel}[GCCcore/11.2.0] libtool v2.4.6, Autoconf v2.71, Automake v1.16.4, ...
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20210726-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-11.2.0.eb
Labels: update

#13607 {devel}[GCCcore/11.2.0] DBus v1.13.18
  easybuild/easyconfigs/d/DBus/DBus-1.13.18-GCCcore-11.2.0.eb
Labels: update

#13578 {vis}[GCCcore/11.2.0] fontconfig v2.13.94, freetype v2.11.0, gperf v3.1, ...
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.94-GCCcore-11.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.11.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.37-GCCcore-11.2.0.eb
Labels: update

#13631 {lib}[GCCcore/11.2.0] snappy v1.1.9
  easybuild/easyconfigs/s/snappy/snappy-1.1.9-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/snappy/snappy-1.1.9_inline-functions.patch
Labels: update

#13599 {devel}[GCCcore/11.2.0] make v4.3, imake v1.0.8, xproto v7.0.31
  easybuild/easyconfigs/i/imake/imake-1.0.8-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/make/make-4.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-11.2.0.eb
Labels: update

#13590 {math}[GCCcore/11.2.0] GLPK v5.0, GMP v6.2.1, ISL v0.24, ...
  easybuild/easyconfigs/g/GLPK/GLPK-5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/i/ISL/ISL-0.24-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/MPC/MPC-1.2.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/nettle/nettle-3.7.3-GCCcore-11.2.0.eb
Labels: update

#13604 {devel}[GCCcore/11.2.0] SQLite v3.36
  easybuild/easyconfigs/s/SQLite/SQLite-3.36-GCCcore-11.2.0.eb
Labels: update

#13606 {system}[GCCcore/11.2.0] libpciaccess v0.16
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.16-GCCcore-11.2.0.eb
Labels: update

#13617 Add new Mesa URLs to 2017b ECs
  easybuild/easyconfigs/m/Mesa/Mesa-17.2.5-foss-2017b.eb
  easybuild/easyconfigs/m/Mesa/Mesa-17.2.5-fosscuda-2017b.eb
Labels: code cleanup

#13635 {devel}[GCCcore/10.2.0] gflags v2.2.2
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.2.0.eb
Labels: update

#13632 {lib}[GCC/10.3.0] SymEngine v0.7.0
  easybuild/easyconfigs/s/SymEngine/SymEngine-0.7.0-GCC-10.3.0.eb
Labels: update

#13628 add upstream patch for GCC 9.x, 10.x, 11.x to avoid spurious FPE on avx512 (affects UCX)
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.x-11.x_fix-unsigned-fpe-traps.patch
Labels: bug fix

#13392 {compiler}[system/system] intel-compilers v2021.3.0
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2021.3.0.eb
Labels: update

#13620 use build_type instead of -DCMAKE_BUILD_TYPE=RELEASE in configopts in MMseqs2 easyconfigs
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-1-c7a89-foss-2016b.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-10-6d92c-gompi-2019b.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-10-6d92c-iimpi-2019b.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-11-e1a1c-iimpi-2019b.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-13-45111-gompi-2020b.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-5-9375b-intel-2018a.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-8-fac81-intel-2018b.eb
Labels: code cleanup

#13640 {math}[foss/2021a,intel/2021a] HPCG v3.1
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2021a.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2021a.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1_fix-loop-upper-bound-variable-to-be-explicitly-designated-as-shared.patch
Labels: update

#13646 {bio}[system/system] MiXCR v3.0.13
  easybuild/easyconfigs/m/MiXCR/MiXCR-3.0.13-Java-11.eb
Labels: update

#13485 {bio}[GCC/10.2.0] Metal v2020.05.05
  easybuild/easyconfigs/m/Metal/Metal-2020-05-05-GCC-10.2.0.eb
Labels: update

#10339 {bio}[foss/2019b] tabix-0-2-6 updated to foss-2019b tool chain
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-8.3.0.eb
Labels: update

#13648 {chem}[intel/2021a] CREST v2.11
  easybuild/easyconfigs/c/CREST/CREST-2.11-intel-2021a.eb
  easybuild/easyconfigs/c/CREST/CREST-2.11_fix-install-targets.patch
Labels: new

#13647 Improvements to SymEngine easyconfig
  easybuild/easyconfigs/s/SymEngine/SymEngine-0.7.0-GCC-10.3.0.eb
Labels: enhancement

#13505 {bio}[foss/2020b] DROP v1.1.0 w/ Python 3.8.6
  easybuild/easyconfigs/d/DROP/DROP-1.1.0-foss-2020b-R-4.0.3.eb
Labels: update

#13633 {lang}[GCCcore/11.2.0] Python v3.9.6, Rust v1.54.0
  easybuild/easyconfigs/p/Python/Python-3.9.6-GCCcore-11.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-3.9.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.54.0-GCCcore-11.2.0.eb
Labels: update

#13509 {chem}[gompi/2021a] ORCA v5.0.1
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.1-gompi-2021a-static.eb
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.1-gompi-2021a.eb
Labels: update

#13649 {chem}[intel/2021a] xTB v6.4.1
  easybuild/easyconfigs/x/xTB/xTB-6.4.1-intel-2021a.eb
Labels: new

#12834 {data}[foss/2019b] h5py v2.10.0 w/ Python 3.7.4 (serial)
  easybuild/easyconfigs/h/h5py/h5py-2.10.0-foss-2019b-serial-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#13348 use orca easyblock in easyconfigs of ORCA v4.x
  easybuild/easyconfigs/o/ORCA/ORCA-4.0.0.2-OpenMPI-2.0.2.eb
  easybuild/easyconfigs/o/ORCA/ORCA-4.0.1-OpenMPI-2.0.2.eb
  easybuild/easyconfigs/o/ORCA/ORCA-4.1.0-OpenMPI-3.1.3.eb
  easybuild/easyconfigs/o/ORCA/ORCA-4.2.0-gompi-2019b.eb
  easybuild/easyconfigs/o/ORCA/ORCA-4.2.1-gompi-2019b.eb
Labels: change

#13654 {tools}[GCCcore/11.2.0] Meson v0.58.2, Ninja v1.10.2 w/ Python 3.9.6
  easybuild/easyconfigs/m/Meson/Meson-0.58.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-GCCcore-11.2.0.eb
Labels: update

#13220 {numlib}[fosscuda/2020b] Hypre v2.21.0
  easybuild/easyconfigs/h/Hypre/Hypre-2.21.0-fosscuda-2020b.eb
  easybuild/easyconfigs/h/Hypre/Hypre-2.21.0_use-c++14-for-nvcc.patch
Labels: update

#13652 {lib}[GCC/10.3.0] SymEngine-python v0.7.2 w/ Python 3.9.5
  easybuild/easyconfigs/s/SymEngine-python/SymEngine-python-0.7.2-GCC-10.3.0.eb
Labels: new

#13651 {bio}[GO] gofasta v0.0.5 created
  easybuild/easyconfigs/g/gofasta/gofasta-0.0.5.eb
Labels: new

#13658 create relative symlinks in the lib folder for ncurses (with system toolchain)
  easybuild/easyconfigs/n/ncurses/ncurses-6.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2.eb
Labels: change request

#13660 create libtinfo symlinks in easyconfigs for ncurses 6.2
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-FCC-4.5.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2-GCCcore-9.3.0.eb
Labels: change request

#13634 {lib}[GCCcore/11.2.0] libevent v2.1.12, numactl v2.0.14, UCX v1.11.0, ...
  easybuild/easyconfigs/h/hwloc/hwloc-2.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libevent/libevent-2.1.12-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.13.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.13.0_psm3-version.patch
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-11.2.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.14-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.11.0-GCCcore-11.2.0.eb
Labels: update

#13641 {geo,tools}[GCCcore/10.3.0,foss/2021a] tcsh v6.22.04, WRF v4.3
  easybuild/easyconfigs/t/tcsh/tcsh-6.22.04-GCCcore-10.3.0.eb
  easybuild/easyconfigs/w/WRF/WRF-4.3-foss-2021a-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-4.3_netCDF-Fortran_separate_path.patch
Labels: update

#13661 create libtinfo symlinks in easyconfigs for ncurses 6.1
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-7.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-8.3.0.eb
Labels: change request

#13663 {lib}[GCCcore/10.3.0] ISA-L v2.30.0, python-isal v0.11.0 w/ Python 3.9.5
  easybuild/easyconfigs/i/ISA-L/ISA-L-2.30.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/python-isal/python-isal-0.11.0-GCCcore-10.3.0.eb
Labels: new

#13659 {perf}[gompi/2021a] DistributedStream v1.0
  easybuild/easyconfigs/d/DistributedStream/DistributedStream-1.0-gompi-2021a.eb
  easybuild/easyconfigs/m/Mini-XML/Mini-XML-3.2-GCCcore-10.3.0.eb
Labels: new, update

#13586 {bio}[GCC/10.3.0] ClustalW2 v2.1
  easybuild/easyconfigs/c/ClustalW2/ClustalW2-2.1-GCC-10.3.0.eb
Labels: update

#13664 {bio}[GCCcore/10.3.0] cutadapt v3.4 w/ Python 3.9.5
  easybuild/easyconfigs/c/cutadapt/cutadapt-3.4-GCCcore-10.3.0.eb
Labels: update

#13656 {devel,tools,vis}[GCCcore/11.2.0] gettext v0.21, intltool v0.51.0, X11 v20210802
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-11.2.0.eb
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/X11/X11-20210802-GCCcore-11.2.0.eb
Labels: update

#13677 {tools}[GCCcore/11.2.0] googletest v1.11.0
  easybuild/easyconfigs/g/googletest/googletest-1.11.0-GCCcore-11.2.0.eb
Labels: update

#13679 {lib}[GCCcore/11.2.0] pybind11 v2.7.1 w/ Python 3.9.6
  easybuild/easyconfigs/p/pybind11/pybind11-2.7.1-GCCcore-11.2.0.eb
Labels: update

#13667 {lib}[GCCcore/11.2.0] UCX-CUDA v1.11.0, GDRCopy v2.3
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.11.0-GCCcore-11.2.0-CUDA-11.4.1.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.11.0_link_against_existing_UCX_libs.patch
Labels: update

#13680 {tools}[GCCcore/11.2.0] hypothesis v6.14.6 w/ Python 3.9.6
  easybuild/easyconfigs/h/hypothesis/hypothesis-6.14.6-GCCcore-11.2.0.eb
Labels: update

#13672 {math}[foss/2021a] Pyomo v6.0.1 w/ Python 3.9.5
  easybuild/easyconfigs/p/Pyomo/Pyomo-6.0.1-foss-2021a.eb
Labels: update

#11698 {bio}[system/system] Schrodinger v2020-4
  easybuild/easyconfigs/s/Schrodinger/Schrodinger-2020-4.eb
Labels: new

#13517 {bio}[GCC/10.3.0] fumi_tools v0.18.2 w/ Python 3.9.5
  easybuild/easyconfigs/f/fumi_tools/fumi_tools-0.18.2-GCC-10.3.0.eb
Labels: update

#13662 {tools}[foss/2020b,fosscuda/2020b] torchinfo v1.5.2 w/ Python 3.8.6
  easybuild/easyconfigs/t/torchinfo/torchinfo-1.5.2-foss-2020b-PyTorch-1.7.1.eb
  easybuild/easyconfigs/t/torchinfo/torchinfo-1.5.2-fosscuda-2020b-PyTorch-1.7.1.eb
Labels: new

#13645 {perf}[GCCcore/10.3.0] CubeGUI v4.6
  easybuild/easyconfigs/c/CubeGUI/CubeGUI-4.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/c/CubeGUI/CubeGUI-4.6_qtlibs_symlink_realpath.patch
Labels: update

#13686 {data}[GCCcore/10.2.0,GCCcore/10.3.0] openpyxl v3.0.7 w/ Python 3.8.6 + 3.9.5
  easybuild/easyconfigs/o/openpyxl/openpyxl-3.0.7-GCCcore-10.2.0.eb
  easybuild/easyconfigs/o/openpyxl/openpyxl-3.0.7-GCCcore-10.3.0.eb
Labels: update

#13650 {chem}[system/system] QCxMS v5.0.3
  easybuild/easyconfigs/q/QCxMS/QCxMS-5.0.3.eb
Labels: new

#13671 Create libffcall-2.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libffcall/libffcall-2.4-GCCcore-10.2.0.eb
Labels: update

#13674 add lwgeom extension to R 4.1.0 easyconfig
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13687 {data}[foss/2020b] pandapower v2.7.0 w/ Python 3.8.6
  easybuild/easyconfigs/p/pandapower/pandapower-2.7.0-foss-2020b.eb
Labels: new

#13682 {data}[foss/2021a] xarray v0.19.0 w/ Python 3.9.5
  easybuild/easyconfigs/x/xarray/xarray-0.19.0-foss-2021a.eb
Labels: update

#13675 {bio}[gompi/2020b] RAxML v8.2.12
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-gompi-2020b-hybrid-avx2.eb
Labels: update

#13685 {data}[foss/2020b,foss/2021a] netcdf4-python v1.5.5.1, netcdf4-python v1.5.7 w/ Python 3.8.6 + 3.9.5
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.5.1-foss-2020b.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.7-foss-2021a.eb
Labels: update

#13688 {data}[foss/2020b] xarray v0.16.2 w/ Python 3.8.6
  easybuild/easyconfigs/x/xarray/xarray-0.16.2-foss-2020b.eb
Labels: update

#13689 {data}[foss/2020b] PYPOWER v5.1.15 w/ Python 3.8.6
  easybuild/easyconfigs/p/PYPOWER/PYPOWER-5.1.15-foss-2020b.eb
Labels: new

#13684 Enable EGL in recent libepoxy ECs
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.8-GCCcore-10.3.0.eb
Labels: bug fix

#13690 {math}[GCC/10.2.0] Shapely v1.8a1 w/ Python 3.8.6
  easybuild/easyconfigs/s/Shapely/Shapely-1.8a1-GCC-10.2.0.eb
Labels: update

#13691 {data}[GCCcore/10.2.0] pyshp v2.1.3 w/ Python 3.8.6
  easybuild/easyconfigs/p/pyshp/pyshp-2.1.3-GCCcore-10.2.0.eb
Labels: update

#13697 {numlib}[gompic/2020b] imkl v2020.4.304
  easybuild/easyconfigs/i/imkl/imkl-2020.4.304-gompic-2020b.eb
Labels: update

#13695 {bio}[GCC/10.3.0,intel-compilers/2021.2.0] Dsuite v20210718
  easybuild/easyconfigs/d/Dsuite/Dsuite-20210718-GCC-10.3.0.eb
  easybuild/easyconfigs/d/Dsuite/Dsuite-20210718-intel-compilers-2021.2.0.eb
Labels: update

#13676 {devel,lib,system,tools}[GCCcore/11.2.0] libsodium v1.0.18, OpenPGM v5.2.122, ZeroMQ v4.3.4, ... w/ Python 3.9.6
  easybuild/easyconfigs/i/IPython/IPython-7.26.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-GCCcore-11.2.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-11.2.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.4-GCCcore-11.2.0.eb
Labels: update

#13696 {geo}[foss/2021a] rgeos v0.5-5, rgdal v1.5-23, spatialreg v1.1-8
  easybuild/easyconfigs/r/rgdal/rgdal-1.5-23-foss-2021a-R-4.1.0.eb
  easybuild/easyconfigs/r/rgeos/rgeos-0.5-5-foss-2021a-R-4.1.0.eb
  easybuild/easyconfigs/s/spatialreg/spatialreg-1.1-8-foss-2021a-R-4.1.0.eb
Labels: update

#13666 {bio}[foss/2021a] RSeQC v4.0.0, bx-python v0.8.11, pyBigWig v0.3.18 w/ Python 3.9.5
  easybuild/easyconfigs/b/bx-python/bx-python-0.8.11-foss-2021a.eb
  easybuild/easyconfigs/p/pyBigWig/pyBigWig-0.3.18-foss-2021a.eb
  easybuild/easyconfigs/r/RSeQC/RSeQC-4.0.0-foss-2021a.eb
Labels: update

#12852 {vis}[system/system] OSPRay v2.5.0
  easybuild/easyconfigs/o/OSPRay/OSPRay-2.5.0.eb
Labels: new

#13236 {data}[GCCcore/10.2.0] HDF-EOS v2.20, h4toh5 v2.2.3
  easybuild/easyconfigs/h/HDF-EOS/HDF-EOS-2.20-GCCcore-10.2.0.eb
  easybuild/easyconfigs/h/HDF-EOS5/HDF-EOS5-1.16-gompi-2020b.eb
  easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.3-gompi-2020b.eb
Labels: update

#13701 {bio}[GCC/10.3.0] SpaceRanger v1.3.0, bcl2fastq2 v2.20.0
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-10.3.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.0-GCC-10.3.0.eb
Labels: update

#13644 {tools}[GCCcore/10.2.0] OpenStackClient v5.5.0 w/ Python 3.8.6
  easybuild/easyconfigs/o/OpenStackClient/OpenStackClient-5.5.0-GCCcore-10.2.0.eb
Labels: new

#13702 Also build shared libs for MUMPS 5.3.5
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-foss-2020b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-intel-2020b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5_shared-mumps.patch
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5_shared-pord.patch
Labels: enhancement

#13705 Also build shared libs for MUMP 5.4.0
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-foss-2021a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0_shared-mumps.patch
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0_shared-pord.patch
Labels: enhancement

#13692 {math}[foss/2020b] Clp v1.17.6, Cgl v0.60.3, Cbc v2.10.5, ...
  easybuild/easyconfigs/c/Cbc/Cbc-2.10.5-foss-2020b.eb
  easybuild/easyconfigs/c/Cgl/Cgl-0.60.3-foss-2020b.eb
  easybuild/easyconfigs/c/Clp/Clp-1.17.6-foss-2020b.eb
  easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/o/Osi/Osi-0.108.6-GCCcore-10.2.0.eb
Labels: update

#13704 Add CMake to tbb 2020.03
  easybuild/easyconfigs/t/tbb/tbb-2020.3-GCCcore-10.2.0.eb
Labels: enhancement

#13709 {tools}[GCCcore/10.3.0] aria2 v1.35.0, CppUnit v1.15.1, c-ares v1.17.2
  easybuild/easyconfigs/a/aria2/aria2-1.35.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/c/c-ares/c-ares-1.17.2-GCCcore-10.3.0.eb
Labels: new, update

#13719 {devel}[GCCcore/11.2.0] SWIG v4.0.2
  easybuild/easyconfigs/s/SWIG/SWIG-4.0.2-GCCcore-11.2.0.eb
Labels: update

#13718 {tools}[GCCcore/11.2.0] APR v1.7.0, APR-util v1.6.1, utf8proc v2.6.1, ... w/ Python 3.9.6
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/SCons/SCons-4.2.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/Subversion/Subversion-1.14.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.6.1-GCCcore-11.2.0.eb
Labels: update

#13721 {bio,data}[GCC/10.3.0] MariaDB v10.6.4, Kent_tools v418
  easybuild/easyconfigs/k/Kent_tools/Kent_tools-418-GCC-10.3.0.eb
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.6.4-GCC-10.3.0.eb
Labels: update

#13720 remove unused buildcmd from libgpuarray easyconfigs
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2019a.eb
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/l/libgpuarray/libgpuarray-0.7.6-fosscuda-2020b.eb
Labels: bug fix, code cleanup

#13717 {lib}[GCCcore/11.2.0] Mako v1.1.4, LLVM v12.0.1, libdrm v2.4.107, ... w/ Python 3.9.6
  easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.107-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/Mako/Mako-1.1.4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.2.0-GCCcore-11.2.0.eb
Labels: update

#13723 {data,lang,vis}[GCCcore/11.2.0] FriBidi v1.0.10, LAME v3.100, FFmpeg v4.3.2
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.3.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.10-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-11.2.0.eb
Labels: update

#13724 {lib}[GCCcore/11.2.0] libogg v1.3.5, libvorbis v1.3.7, FLAC v1.3.3, ...
  easybuild/easyconfigs/f/FLAC/FLAC-1.3.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libogg/libogg-1.3.5-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.31-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libvorbis/libvorbis-1.3.7-GCCcore-11.2.0.eb
  easybuild/easyconfigs/v/vorbis-tools/vorbis-tools-1.4.2-GCCcore-11.2.0.eb
Labels: update

#13725 {vis}[GCCcore/11.2.0] Pillow v8.3.1, Pillow-SIMD v8.3.1 w/ Python 3.9.6
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-8.3.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.1-GCCcore-11.2.0.eb
Labels: update

#13726 {lib}[GCCcore/11.2.0] mimalloc v1.7.2, jemalloc v5.2.1, gperftools v2.9.1
  easybuild/easyconfigs/g/gperftools/gperftools-2.9.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.2.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/mimalloc/mimalloc-1.7.2-GCCcore-11.2.0.eb
Labels: update

#13727 {lib,tools}[GCCcore/11.2.0] elfutils v0.185, patchelf v0.13
  easybuild/easyconfigs/e/elfutils/elfutils-0.185-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.13-GCCcore-11.2.0.eb
Labels: update

#13722 {lang,vis}[GCCcore/11.2.0] Tkinter v3.9.6, Tk v8.6.11 w/ Python 3.9.6
  easybuild/easyconfigs/t/Tk/Tk-8.6.11-GCCcore-11.2.0.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.9.6-GCCcore-11.2.0.eb
Labels: update

#13729 {vis}[GCCcore/11.2.0] xprop v1.2.5, FLTK v1.3.7, libGLU v9.0.2
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.7-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/xprop/xprop-1.2.5-GCCcore-11.2.0.eb
Labels: update

#13714 {compiler}[GCCcore/10.3.0] Clang v12.0.1
  easybuild/easyconfigs/c/Clang/Clang-12.0.1-GCCcore-10.3.0.eb
Labels: update

#13642 {bio}[foss/2021a] ctffind v4.1.14
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2021a-CUDA-11.3.1.eb
Labels: update

#13728 {tools}[GCCcore/11.2.0] JupyterLab v3.1.6 w/ Python 3.9.6
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.1.6-GCCcore-11.2.0.eb
Labels: update

#13712 {vis}[GCCcore/10.3.0] PyCairo v1.20.1 w/ Python 3.9.5
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.20.1-GCCcore-10.3.0.eb
Labels: update

#13711 {lib}[foss/2021a] igraph v0.9.4
  easybuild/easyconfigs/i/igraph/igraph-0.9.4-foss-2021a.eb
Labels: update
