Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-07, with the labels that each got.

#13306 {tools}[system/system] vsc-mympirun v5.2.6
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.6.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#13189 {chem}[foss/2020b] Amber v20.11 w/ Python 3.8.6
  easybuild/easyconfigs/a/Amber/Amber-20.11-foss-2020b-AmberTools-21.3.eb
  easybuild/easyconfigs/a/Amber/AmberTools-20_fix_xblas_missing_make_dependency.patch
Labels: update

#13285 {perf}[GCCcore/10.2.0] CubeWriter v4.4.3, OPARI2 v2.0.6, OTF2 v2.3, ...
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.4.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-2.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.6-GCCcore-10.2.0-tools.eb
  easybuild/easyconfigs/s/Score-P/Score-P-7.0-gompic-2020b.eb
Labels: update

#13288 {math}[GCCcore/9.3.0] GDB v10.2, MPC v1.1.0, ISL v0.23 w/ Python 3.8.2
  easybuild/easyconfigs/g/GDB/GDB-10.2-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/i/ISL/ISL-0.23-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/MPC/MPC-1.1.0-GCCcore-9.3.0.eb
Labels: update

#13190 {chem}[fosscuda/2020b] Amber v20.11 w/ Python 3.8.6
  easybuild/easyconfigs/a/Amber/Amber-20.11-fosscuda-2020b-AmberTools-21.3.eb
Labels: update

#13309 {tools}[GCCcore/10.3.0] tmux v3.2a
  easybuild/easyconfigs/t/tmux/tmux-3.2a-GCCcore-10.3.0.eb
Labels: update

#13308 {devel,lib,system,tools}[GCCcore/10.3.0] IPython v7.25.0, ZeroMQ v4.3.4, OpenPGM v5.2.122, ... w/ Python 3.9.5
  easybuild/easyconfigs/i/IPython/IPython-7.25.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-GCCcore-10.3.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-10.3.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.4-GCCcore-10.3.0.eb
Labels: update

#13310 add patch for GCCcore 10.3.0 to prevent issues when compiling with nvcc
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GCCcore/gcc-10.3.0_fix-ice-in-tsubst.patch
Labels: bug fix

#13324 {lib}[GCCcore/10.3.0] libepoxy v1.5.8, GLM v0.9.9.8
  easybuild/easyconfigs/g/GLM/GLM-0.9.9.8-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.8-GCCcore-10.3.0.eb
Labels: update

#13325 {devel}[GCCcore/10.3.0] protobuf v3.17.3, protobuf-python v3.17.3 w/ Python 3.9.5
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.17.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/protobuf/protobuf-3.17.3-GCCcore-10.3.0.eb
Labels: update

#13323 {tools}[GCCcore/10.3.0] parallel v20210622
  easybuild/easyconfigs/p/parallel/parallel-20210622-GCCcore-10.3.0.eb
Labels: update

#13315 {tools}[GCCcore/10.3.0] nvtop v1.2.1
  easybuild/easyconfigs/n/nvtop/nvtop-1.2.1-GCCcore-10.3.0.eb
Labels: update

#13316 {lib}[GCCcore/10.3.0] GitPython v3.1.18 w/ Python 3.9.5
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.18-GCCcore-10.3.0.eb
Labels: update

#13314 {vis}[GCCcore/10.3.0] GLFW v3.3.4
  easybuild/easyconfigs/g/GLFW/GLFW-3.3.4-GCCcore-10.3.0.eb
Labels: update

#13313 {vis}[GCCcore/10.3.0] Pillow v8.2.0 w/ Python 3.9.5
  easybuild/easyconfigs/p/Pillow/Pillow-8.2.0-GCCcore-10.3.0.eb
Labels: update

#13320 {vis}[GCCcore/10.3.0] FLTK v1.3.6, xprop v1.2.5
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.6_fix-LDFLAGS.patch
  easybuild/easyconfigs/x/xprop/xprop-1.2.5-GCCcore-10.3.0.eb
Labels: update

#13319 {lib}[GCCcore/10.3.0] Check v0.15.2, googletest v1.11.0, JsonCpp v1.9.4
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/googletest/googletest-1.11.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.4-GCCcore-10.3.0.eb
Labels: update

#13317 {lang,math,vis}[GCCcore/10.3.0] gnuplot v5.4.2, libcerf v1.17, Lua v5.4.3
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/Lua/Lua-5.4.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libcerf/libcerf-1.17-GCCcore-10.3.0.eb
Labels: update

#13284 add twang + xgboost extensions to recent R easyconfigs
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13307 avoid using PMIx from system instead of PMIx dependency specified via --with-pmix for OpenMPI 4.x
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1-GCC-8.3.0-2.32.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1_remove-pmix-check-in-pmi-switch.patch
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-GCC-9.2.0-2.32.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-GCC-9.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-gcccuda-2020a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-iccifort-2020.1.217.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-iccifortcuda-2020a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-GCC-10.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-GCC-9.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-gcccuda-2020b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-iccifort-2020.4.304.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.6-GCC-10.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.6_remove-pmix-check-in-pmi-switch.patch
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.0-GCC-10.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-GCC-10.3.0.eb
Labels: bug fix

#13166 makeinfo requires Perl as a dependency
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.7-GCCcore-9.3.0.eb
Labels: enhancement, feature

#13330 add neuralnet extension to recent R 4.x easyconfigs
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#12679 {chem}[foss/2020a] ASE v3.21.1, spglib-python v1.16.0 w/ Python 3.8.2
  easybuild/easyconfigs/a/ASE/ASE-3.21.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.0-foss-2020a-Python-3.8.2.eb
Labels: update

#13322 {lang}[GCCcore/10.3.0] Ruby v3.0.1
  easybuild/easyconfigs/r/Ruby/Ruby-3.0.1-GCCcore-10.3.0.eb
Labels: update

#13327 {lang}[GCCcore/10.3.0] LDC v1.26.0
  easybuild/easyconfigs/l/LDC/LDC-1.26.0-GCCcore-10.3.0.eb
Labels: update

#13332 {devel,lib}[GCCcore/10.3.0] PyYAML v5.4.1, typing-extensions v3.10.0.0 w/ Python 3.9.5
  easybuild/easyconfigs/p/PyYAML/PyYAML-5.4.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/typing-extensions/typing-extensions-3.10.0.0-GCCcore-10.3.0.eb
Labels: update

#13179 Add missing rgdal dep to R-INLA
  easybuild/easyconfigs/r/R-INLA/R-INLA-21.05.02-foss-2020b-R-4.0.4.eb
Labels: bug fix

#13097 add checksum for aarch64 installation file for CUDAcore 11.2.1
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.2.1.eb
Labels: enhancement

#12597 update README with instructions for MATLAB easyconfigs
  easybuild/easyconfigs/m/MATLAB/README.md
Labels: update

#13329 add patch for OpenMPI 4.0.x to fix building against (system) UCX version > 1.7
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1-GCC-8.3.0-2.32.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1_add-support-for-ucx-1.7.patch
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-GCC-9.2.0-2.32.eb
Labels: bug fix

#13334 {devel}[GCCcore/10.3.0] flatbuffers-python v2.0 w/ Python 3.9.5
  easybuild/easyconfigs/f/flatbuffers-python/flatbuffers-python-2.0-GCCcore-10.3.0.eb
Labels: update

#13111 Add astor to TensorFlow 2019b dependencies
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2019b-Python-3.7.4.eb
Labels: bug fix

#13336 revert to using a bundle of components to install PyQt5, rather than a bundle of extensions
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.1-GCCcore-9.3.0-Python-3.8.2.eb
Labels: bug fix

#13328 {tools}[GCCcore/10.3.0] JupyterLab v3.0.16 w/ Python 3.9.5
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.0.16-GCCcore-10.3.0.eb
Labels: update

#13311 {tools}[GCCcore/10.3.0] Subversion v1.14.1, Serf v1.3.9, SCons v4.1.0.post1, ... w/ Python 3.9.5
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/SCons/SCons-4.1.0.post1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/Subversion/Subversion-1.14.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.6.1-GCCcore-10.3.0.eb
Labels: update

#13226 {math,vis}[GCCcore/10.2.0] Octave v6.2.0, GL2PS v1.4.2, Qhull v2020.2, ...
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.36-foss-2020b.eb
  easybuild/easyconfigs/o/Octave/Octave-6.2.0-foss-2020b.eb
  easybuild/easyconfigs/q/Qhull/Qhull-2020.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCCcore-10.2.0.eb
Labels: update

#13338 fix build of manta 1.6.0 on top of Boost 1.74.0
  easybuild/easyconfigs/m/manta/manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb
Labels: bug fix

#13321 {lang}[GCCcore/10.3.0] Nim v1.4.8
  easybuild/easyconfigs/n/Nim/Nim-1.4.8-GCCcore-10.3.0.eb
Labels: update

#13333 {data,math}[iccifort/2020.4.304,intel/2020b] GDAL v3.2.1, GEOS v3.9.1 w/ Python 3.8.6
  easybuild/easyconfigs/g/GDAL/GDAL-3.2.1-intel-2020b.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.2.1_cpp-conformance.patch
  easybuild/easyconfigs/g/GEOS/GEOS-3.9.1-iccifort-2020.4.304.eb
Labels: update

#13141 {lang}[system/system] Java v1.8.0_292
  easybuild/easyconfigs/j/Java/Java-1.8.0_292-OpenJDK.eb
Labels: update

#13339 prepare release notes for EasyBuild v4.4.1 + bump version to 4.4.1
  RELEASE_NOTES
  setup.py
Labels: update

#13342 fix recent taxator-tk easyconfigs by adding (back) -DBoost_NO_BOOST_CMAKE=ON configure option
  easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-GCC-10.2.0.eb
  easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-gompi-2019a.eb
Labels: bug fix

#13344 {tools}[dummy/dummy] EasyBuild v4.4.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.1.eb
Labels: update

#13346 sync with main + bump version to 4.4.2dev
  RELEASE_NOTES
  easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-GCC-10.2.0.eb
  easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-gompi-2019a.eb
  setup.py
Labels: update

#13335 {tools}[GCCcore/10.3.0] configurable-http-proxy v4.4.0, nodejs v14.17.2, JupyterHub v1.4.1 w/ Python 3.9.5
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.4.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/JupyterHub/JupyterHub-1.4.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-14.17.2-GCCcore-10.3.0.eb
Labels: update

#13351 {math}[GCCcore/10.2.0] LADR v2009-11A
  easybuild/easyconfigs/l/LADR/LADR-2009-11A-GCCcore-10.2.0.eb
Labels: new

#13352 {math}[GCCcore/10.2.0] Vampire v4.5.1
  easybuild/easyconfigs/v/Vampire/Vampire-4.5.1-GCCcore-10.2.0.eb
Labels: new

#13356 {system}[GCCcore/10.3.0] file v5.40
  easybuild/easyconfigs/f/file/file-5.40-GCCcore-10.3.0.eb
Labels: update

#13355 {lib}[GCCcore/10.3.0] SDL2 v2.0.14
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.14-GCCcore-10.3.0.eb
Labels: update

#13354 {vis}[foss/2020b] freud-analysis v2.6.2 w/ Python 3.8.6
  easybuild/easyconfigs/f/freud-analysis/freud-analysis-2.6.2-foss-2020b.eb
Labels: new

#13358 {lib}[GCCcore/10.3.0] ack v3.5.0, Archive-Zip v1.68, Blosc v1.21.0, ... w/ Python 3.9.5
  easybuild/easyconfigs/a/Archive-Zip/Archive-Zip-1.68-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/ack/ack-3.5.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/Blosc/Blosc-1.21.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/bpytop/bpytop-1.0.67-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.2.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/json-c/json-c-0.15-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libpsl/libpsl-0.21.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/lxml/lxml-4.6.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/q/Qhull/Qhull-2020.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/time/time-1.9-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.61.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/XlsxWriter/XlsxWriter-1.4.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/y/YACS/YACS-0.1.8-GCCcore-10.3.0.eb
Labels: update

#13359 {data,lib}[GCCcore/10.3.0] MariaDB-connector-c v3.2.2, PostgreSQL v13.3
  easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-3.2.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-13.3-GCCcore-10.3.0.eb
Labels: update

#13363 {numlib}[foss/2020b] Armadillo v10.5.3
  easybuild/easyconfigs/a/Armadillo/Armadillo-10.5.3-foss-2020b.eb
Labels: update

#13365 {math}[foss/2021a] lavaan 0.6-9 /w R-4.1.0
  easybuild/easyconfigs/l/lavaan/lavaan-0.6-9-foss-2021a-R-4.1.0.eb
Labels: update

#13364 {bio}[foss/2020b] goatools v1.1.6 w/ Python 3.8.6
  easybuild/easyconfigs/g/goatools/goatools-1.1.6-foss-2020b.eb
Labels: new

#13369 {phys}[foss/2021a] Elk v7.2.42
  easybuild/easyconfigs/e/Elk/Elk-7.2.42-foss-2021a.eb
Labels: update

#13368 {data}[GCCcore/10.3.0] XML-Parser v2.46
  easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.46-GCCcore-10.3.0-Perl-5.32.1.eb
Labels: update

#13374 {math}[GCCcore/10.2.0] Voro++ v0.4.6
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-10.2.0.eb
Labels: update

#13376 {bio}[GCC/10.3.0] BEDTools v2.30.0, BamTools v2.5.2
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.30.0-GCC-10.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-10.3.0.eb
Labels: update

#13373 {tools}[GCCcore/10.2.0] archspec v0.1.2 w/ Python 3.8.6
  easybuild/easyconfigs/a/archspec/archspec-0.1.2-GCCcore-10.2.0.eb
Labels: update

#13378 {tools}[GCCcore/10.3.0] patchelf v0.12
  easybuild/easyconfigs/p/patchelf/patchelf-0.12-GCCcore-10.3.0.eb
Labels: update

#13349 remove Python 2.6 from list of supported Python versions in setup.py
  setup.py
Labels: bug fix

#13381 {bio}[GCCcore/10.3.0] PRSice v2.3.3
  easybuild/easyconfigs/p/PRSice/PRSice-2.3.3-GCCcore-10.3.0.eb
Labels: update

#13379 {bio}[GCC/10.3.0] BCFtools v1.12, HTSlib v1.12, SAMtools v1.12
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.12-GCC-10.3.0.eb
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.12-GCC-10.3.0.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.12-GCC-10.3.0.eb
Labels: update

#13341 {bio}[GCC/10.2.0] Control-FREEC v11.6
  easybuild/easyconfigs/c/Control-FREEC/Control-FREEC-11.6-GCC-10.2.0.eb
Labels: update

#13382 {vis}[GCCcore/10.3.0] Pillow-SIMD v8.2.0 w/ Python 3.9.5
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-8.2.0-GCCcore-10.3.0.eb
Labels: update

#13345 {bio}[foss/2018b] fumi_tools v0.18.2 w/ Python 3.6.6
  easybuild/easyconfigs/f/fumi_tools/fumi_tools-0.18.2-foss-2018b-Python-3.6.6.eb
Labels: new

#13370 {math}[GCC/10.3.0] Shapely v1.8a1 w/ Python 3.9.5
  easybuild/easyconfigs/s/Shapely/Shapely-1.8a1-GCC-10.3.0.eb
Labels: update

#13387 {data}[gompi/2021a] netCDF-C++4 v4.3.1
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-gompi-2021a.eb
Labels: update

#13403 {data}[gompi/2021a] PnetCDF v1.12.2
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.2-gompi-2021a.eb
Labels: update

#13386 {lang}[system/system] Anaconda3 v2021.05
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2021.05.eb
Labels: update

#13401 {tools}[gompi/2021a] CDO v1.9.10, ecCodes v2.22.1, YAXT v0.9.1
  easybuild/easyconfigs/c/CDO/CDO-1.9.10-gompi-2021a.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.22.1-gompi-2021a.eb
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.1-gompi-2021a.eb
Labels: update

#13394 {bio}[GCC/10.3.0] STAR v2.7.9a
  easybuild/easyconfigs/s/STAR/STAR-2.7.9a-GCC-10.3.0.eb
Labels: update

#13371 Fix PyQt 5.15.1 ECs
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.1-GCCcore-9.3.0-Python-3.8.2.eb
Labels: bug fix

#13366 {vis}[GCCcore/10.3.0] PyQt5 v5.15.4 w/ Python 3.9.5
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.4-GCCcore-10.3.0.eb
Labels: update

#13357 {vis}[GCCcore/10.3.0] GTK+ v3.24.29, at-spi2-core v2.40.2, at-spi2-atk v2.38.0
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.40.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.29-GCCcore-10.3.0.eb
Labels: update

#13410 Disable building man pages in Gdk-Pixbuf
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.40.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.40.0-GCCcore-9.3.0.eb
Labels: bug fix

#13399 Fix Rust v1.52.1 EC
  easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.3.0.eb
Labels: bug fix

#13409 patch out __asm__ use in ctffind to avoid build failure on ppc64le
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2019b.eb
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-fosscuda-2019b.eb
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-fosscuda-2020b.eb
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14_asm-fix.patch
Labels: bug fix

#13383 fix the libxml2 dependency (like #13030) which was broken due to #11065
  easybuild/easyconfigs/g/GDAL/GDAL-3.2.1-foss-2020b.eb
Labels: bug fix

#13416 {lang}[system/system] Java v16.0.1, Java v16
  easybuild/easyconfigs/j/Java/Java-16.0.1.eb
  easybuild/easyconfigs/j/Java/Java-16.eb
Labels: update

#13414 {lib}[gompi/2020b] lwgrp v1.0.3
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.3-gompi-2020b.eb
Labels: update

#13411 {tools}[GCCcore/10.3.0] gpustat v0.6.0 w/ Python 3.9.5
  easybuild/easyconfigs/g/gpustat/gpustat-0.6.0-GCCcore-10.3.0.eb
Labels: update

#13406 {perf}[system/system] Advisor v2021.2.0
  easybuild/easyconfigs/a/Advisor/Advisor-2021.2.0.eb
Labels: update

#13395 {devel}[system] ReFrame v3.6.3
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.6.3.eb
Labels: update

#13418 {bio}[gompi/2020b] barrnap 0.9
  easybuild/easyconfigs/b/barrnap/barrnap-0.9-gompi-2020b.eb
Labels: update

#12499 {vis}[foss/2020b] IMOD v4.11.5
  easybuild/easyconfigs/i/IMOD/IMOD-4.11.5-foss-2020b.eb
  easybuild/easyconfigs/i/IMOD/IMOD-4.11.5-fosscuda-2020b.eb
Labels: update

#13422 Move archive files to correct folder
  easybuild/easyconfigs/__archive__/i/ictce/ictce-5.2.0.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-5.3.0.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-5.4.0.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-5.5.0.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-6.1.5.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-6.2.5.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-7.1.2.eb
  easybuild/easyconfigs/__archive__/i/ictce/ictce-7.3.5.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2014.06.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2014.10.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2014.11.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2014b.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2015.02.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2015.08.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2015a.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2015b.eb
Labels: code cleanup

#13159 {tools}[foss/2021a] networkx v2.5.1 w/ Python 3.9.5
  easybuild/easyconfigs/n/networkx/networkx-2.5.1-foss-2021a.eb
  easybuild/easyconfigs/n/networkx/networkx-2.5.1_decorator.patch
Labels: update

#13400 Fix order of cffi in Python ECs
  easybuild/easyconfigs/p/Python/Python-2.7.12-foss-2016b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-foss-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-fosscuda-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2017b.eb
  easybuild/easyconfigs/p/Python/Python-3.6.3-intelcuda-2017b.eb
Labels: bug fix

#13433 {bio}[foss/2021a] Biopython v1.79 w/ Python 3.9.5
  easybuild/easyconfigs/b/Biopython/Biopython-1.79-foss-2021a.eb
Labels: update

#13430 {lib}[gompi/2020b] dtcmp v1.1.2
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.2-gompi-2020b.eb
Labels: update

#13398 {bio}[foss/2021a] scVelo 0.2.3 w/ deps
  easybuild/easyconfigs/n/numba/numba-0.53.1-foss-2021a.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-foss-2021a.eb
  easybuild/easyconfigs/s/scVelo/scVelo-0.2.3-foss-2021a.eb
  easybuild/easyconfigs/s/scVelo/umap-learn-0.4.6_numba.patch
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.12.2-foss-2021a.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.61.2-GCCcore-10.3.0.eb
Labels: update

#13402 {compiler}[GCCcore/10.3.0] LLVM v12.0.1
  easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-10.3.0.eb
Labels: update

#12977 {devel}[GCC/10.3.0,intel-compilers/2021.2.0] Boost v1.76.0
  easybuild/easyconfigs/b/Boost/Boost-1.76.0-GCC-10.3.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.76.0-intel-compilers-2021.2.0.eb
Labels: update

#13421 {numlib}[GCC/10.3.0] OpenBLAS v0.3.17
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.17-GCC-10.3.0.eb
Labels: update

#13440 {bio}[GCC/10.3.0] VCFtools v0.1.16
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-GCC-10.3.0.eb
Labels: update

#13428 avoid downloading old numpy version during install for h5py
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-foss-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-fosscuda-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-intel-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.1.0-intelcuda-2020b.eb
  easybuild/easyconfigs/h/h5py/h5py-3.2.1-foss-2021a.eb
Labels: bug fix

#13420 {bio}[{foss,fosscuda}/2020b] mhcnuggets 2.3
  easybuild/easyconfigs/m/mhcnuggets/mhcnuggets-2.3-foss-2020b.eb
  easybuild/easyconfigs/m/mhcnuggets/mhcnuggets-2.3-fosscuda-2020b.eb
Labels: update

#13419 prokka needs Bio-Search-hmmer, but it is not part of BioPerl>1.7.3
  easybuild/easyconfigs/b/Bio-SearchIO-hmmer/Bio-SearchIO-hmmer-1.7.3-GCC-10.2.0.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2020b.eb
Labels: bug fix, new

#13449 Avoid dependency on system GTK+ in GTK+ themes
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.13-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.17-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.23-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.29-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GTK+/adwaita-icon-theme-3.34.3_disable-svg-conversion.patch
Labels: bug fix

#13444 {perf}[gompic/2020b] Scalasca v2.6
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.6-gompic-2020b.eb
Labels: update

#13450 {bio}[foss/2020b] Qualimap 2.2.1
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2020b-R-4.0.3.eb
Labels: update

#13265 {numlib}[foss/2021a] PETSc v3.15.1 w/ Python 3.9.5
  easybuild/easyconfigs/p/PETSc/PETSc-3.15.1-foss-2021a.eb
Labels: update

#13425 {perf}[GCCcore/10.3.0] CubeLib v4.6
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.6-GCCcore-10.3.0.eb
Labels: update

#13429 {perf}[GCCcore/10.3.0] OTF2 v2.3, SIONlib v1.7.6
  easybuild/easyconfigs/o/OTF2/OTF2-2.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.6-GCCcore-10.3.0-tools.eb
Labels: update

#13436 {lib}[gompi/2020b] libcircle v0.3
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-gompi-2020b.eb
Labels: update

#13347 {chem}[gompi/2021a] ORCA v5.0.0
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.0-gompi-2021a-static.eb
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.0-gompi-2021a.eb
Labels: update

#13467 {compiler}[system/system] Go v1.16.6
  easybuild/easyconfigs/g/Go/Go-1.16.6.eb
Labels: update

#13443 {tools}[fosscuda/2020b] torchtext v0.9.1 w/ Python 3.8.6
  easybuild/easyconfigs/t/torchtext/torchtext-0.9.1-fosscuda-2020b-PyTorch-1.8.1.eb
Labels: update

#13437 avoid downloading and building freetype and qhull for matplotlib 3.4.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.4.2-foss-2021a.eb
Labels: bug fix

#13471 {bio}[GCC/10.3.0] PEAR v0.9.11
  easybuild/easyconfigs/p/PEAR/PEAR-0.9.11-GCC-10.3.0.eb
Labels: update

#13478 {tools}[GCC/10.3.0] ncdu v1.16
  easybuild/easyconfigs/n/ncdu/ncdu-1.16-GCC-10.3.0.eb
Labels: update

#13482 {tools}[system/system] VTune v2021.6.0
  easybuild/easyconfigs/v/VTune/VTune-2021.6.0.eb
Labels: update

#13479 {bio}[GCC/10.3.0] KronaTools v2.8
  easybuild/easyconfigs/k/KronaTools/KronaTools-2.8-GCC-10.3.0.eb
Labels: update

#13480 {bio}[GCC/10.3.0] DIAMOND v2.0.11
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.0.11-GCC-10.3.0.eb
Labels: update

#13466 {lang}[system/system] Julia v1.6.2
  easybuild/easyconfigs/j/Julia/Julia-1.6.2-linux-x86_64.eb
Labels: update

#13484 BAli-Phy 3.6.0
  easybuild/easyconfigs/b/BAli-Phy/BAli-Phy-3.6.0.eb
Labels: new

#13488 {bio}[GCC/10.3.0] Bowtie2 v2.4.4
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.4-GCC-10.3.0.eb
Labels: update

#13489 {math}[GCC/10.3.0] Arb v2.19.0, FLINT v2.7.1
  easybuild/easyconfigs/a/Arb/Arb-2.19.0-GCC-10.3.0.eb
  easybuild/easyconfigs/f/FLINT/FLINT-2.7.1-GCC-10.3.0.eb
Labels: update

#13495 {data}[gompi/2021a] HDF5 v1.12.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.1-gompi-2021a.eb
Labels: update

#13472 {lib}[GCCcore/10.2.0] libdeflate v1.7, libRmath v4.1.0, LIBSVM v3.25, ...
  easybuild/easyconfigs/l/LIBSVM/LIBSVM-3.25-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libRmath/libRmath-4.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libdeflate/libdeflate-1.7-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/v/vt/vt-0.57721-GCC-10.2.0.eb
  easybuild/easyconfigs/v/vt/vt-0.57721_update_htsutils.patch
Labels: update

#13498 {bio}[GCC/10.2.0] Jellyfish 2.3.0
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-10.2.0.eb
Labels: update

#13497 {tools}[GCCcore/10.2.0,GCCcore/9.3.0] GDCM v3.0.8
  easybuild/easyconfigs/g/GDCM/GDCM-3.0.8-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GDCM/GDCM-3.0.8-GCCcore-9.3.0.eb
Labels: update

#13441 {data}[GCC/8.3.0] bitarray v1.5.3 w/ Python 2.7.16
  easybuild/easyconfigs/b/bitarray/bitarray-1.5.3-GCC-8.3.0-Python-2.7.16.eb
Labels: update

#13448 Add PCAmatchR to recent R
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: enhancement

#13490 {bio}[GCC/10.3.0] Arriba v2.1.0
  easybuild/easyconfigs/a/Arriba/Arriba-2.1.0-GCC-10.3.0.eb
Labels: update

#13503 {chem}[GCC/10.3.0] TRAVIS-Analyzer v210521
  easybuild/easyconfigs/t/TRAVIS-Analyzer/TRAVIS-Analyzer-210521-GCC-10.3.0.eb
Labels: new

#13510 {bio}[gompi/2021a] HMMER v3.3.2
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.2-gompi-2021a.eb
Labels: update

#13500 {lib,phys}[fosscuda/2020b] FBPIC v0.20.3, pyFFTW v0.12.0 w/ Python 3.8.6
  easybuild/easyconfigs/f/FBPIC/FBPIC-0.20.3-fosscuda-2020b.eb
  easybuild/easyconfigs/p/pyFFTW/pyFFTW-0.12.0-fosscuda-2020b.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#13504 {tools}[foss/2021a] snakemake v6.6.1 w/ Python 3.9.5
  easybuild/easyconfigs/s/snakemake/snakemake-6.6.1-foss-2021a.eb
  easybuild/easyconfigs/s/snakemake/snakemake-6.6.1_fix_jobs.patch
Labels: update

#13501 allow for non-x86_64 in postinstallcmds for CuPy
  easybuild/easyconfigs/c/CuPy/CuPy-8.5.0-fosscuda-2020b.eb
Labels: bug fix

#13514 {numlib}[foss/2021a] arpack-ng v3.8.0
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.8.0-foss-2021a.eb
Labels: update

#13486 {bio}[GCC/10.3.0] GffCompare v0.12.2
  easybuild/easyconfigs/g/GffCompare/GffCompare-0.12.2-GCC-10.3.0.eb
Labels: update

#13512 {numlib}[GCCcore/10.2.0] BLIS v3.0.1
  easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-GCCcore-10.2.0-amd.eb
Labels: update

#13511 {bio}[foss/2020b] QTLtools v1.3.1
  easybuild/easyconfigs/q/QTLtools/QTLtools-1.3.1-foss-2020b.eb
Labels: update

#13227 {numlib}[intel/2020b] PETSc v3.14.4 w/ Python 3.8.6
  easybuild/easyconfigs/h/Hypre/Hypre-2.20.0-intel-2020b.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-intel-2020b-metis.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.14.4-intel-2020b.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.8.1-intel-2020b-METIS-5.1.0.eb
Labels: update

#13515 {lib}[GCCcore/10.3.0] mimalloc v1.7.2
  easybuild/easyconfigs/m/mimalloc/mimalloc-1.7.2-GCCcore-10.3.0.eb
Labels: new

#13494 {numlib}[GCCcore/10.3.0] BLIS v3.0.1
  easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-GCCcore-10.3.0-amd.eb
Labels: update

#13508 {bio}[GCC/10.3.0] preseq v3.1.2
  easybuild/easyconfigs/p/preseq/preseq-3.1.2-GCC-10.3.0.eb
Labels: update

#13507 {bio}[GCC/10.3.0] segemehl v0.3.4
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-10.3.0.eb
Labels: update

#13506 {toolchain}[system/system] iomkl v2021a, iompi v2021a, imkl v2021.2.0
  easybuild/easyconfigs/i/imkl/imkl-2021.2.0-iompi-2021a.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2021a.eb
  easybuild/easyconfigs/i/iompi/iompi-2021a.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-intel-compilers-2021.2.0.eb
Labels: update

#13516 disable default EULA acceptance in n/NVHPC/NVHPC-21.5.eb
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.5.eb
Labels: bug fix

#13492 {compiler}[system/system] NVHPC v21.7
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.7.eb
Labels: update

#13521 {perf,tools}[iomkl/2021a,iompi/2021a] OSU-Micro-Benchmarks v5.7.1, HPL v2.3
  easybuild/easyconfigs/h/HPL/HPL-2.3-iomkl-2021a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-iompi-2021a.eb
Labels: update

#13491 {compiler}[GCCcore/10.2.0,GCCcore/10.3.0] AOCC v3.1.0
  easybuild/easyconfigs/a/AOCC/AOCC-3.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/AOCC/AOCC-3.1.0-GCCcore-10.3.0.eb
Labels: update

#13487 {bio}[GCC/10.3.0] gffread v0.12.6
  easybuild/easyconfigs/g/gffread/gffread-0.12.7-GCC-10.3.0.eb
Labels: update

#13481 {bio}[GCCcore-10.3.0] minimap2 bumped to 2.20
  easybuild/easyconfigs/m/minimap2/minimap2-2.20-GCCcore-10.3.0.eb
Labels: update

#13470 {bio}[GCC/10.3.0] StringTie v2.1.7
  easybuild/easyconfigs/s/StringTie/StringTie-2.1.7-GCC-10.3.0.eb
Labels: update

#13469 {devel}[system/system] Spack v0.16.2
  easybuild/easyconfigs/s/Spack/Spack-0.16.2.eb
Labels: update
