Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-09, with the labels that each got.

#13868 {lib}[GCCcore/11.2.0] NCCL v2.10.3
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-11.2.0-CUDA-11.4.1.eb
Labels: update

#13866 {bio}[gompi/2020b] Centrifuge v1.0.4
  easybuild/easyconfigs/c/Centrifuge/Centrifuge-1.0.4-gompi-2020b.eb
Labels: update

#13865 {data}[foss/2021a] ANTs v2.3.5 w/ Python 3.9.5
  easybuild/easyconfigs/a/ANTs/ANTs-2.3.5-foss-2021a.eb
Labels: update

#12517 fix sanity check error for OpenCV v4.5.1
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.5.1-foss-2020b-contrib.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.5.1-fosscuda-2020b-contrib.eb
Labels: bug fix

#13864 {geo}[foss/2019b,foss/2020b] GMT v6.2.0
  easybuild/easyconfigs/g/GMT/GMT-6.2.0-foss-2019b.eb
  easybuild/easyconfigs/g/GMT/GMT-6.2.0-foss-2020b.eb
Labels: update

#13874 rename CUDAcore to CUDA for v11.3.1 and v11.4.1 after merging foss/fosscuda, to ensure that get_software_root('CUDA') used in easyblocks works
  easybuild/easyconfigs/c/CUDA/CUDA-11.3.1.eb
  easybuild/easyconfigs/c/CUDA/CUDA-11.4.1.eb
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.2.1.32-CUDA-11.3.1.eb
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.2.2.26-CUDA-11.4.1.eb
  easybuild/easyconfigs/m/magma/magma-2.6.1-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-10.3.0-CUDA-11.3.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-11.2.0-CUDA-11.4.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.9.9-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-gompi-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.10.0-GCCcore-10.3.0-CUDA-11.3.1.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.11.0-GCCcore-11.2.0-CUDA-11.4.1.eb
Labels: change

#13875 Use CUDA instead of CUDAcore in recent NVHPC comments
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.5.eb
  easybuild/easyconfigs/n/NVHPC/NVHPC-21.7.eb
Labels: change

#12600 {geo}[foss/2020b] WPS v4.2, WRF v4.2.2
  easybuild/easyconfigs/w/WPS/WPS-4.2-foss-2020b-dmpar.eb
  easybuild/easyconfigs/w/WPS/WPS-4.2_GCC-10-allow-argument-mismatch.patch
  easybuild/easyconfigs/w/WPS/WPS-4.2_netCDF-Fortran_seperate_path.patch
  easybuild/easyconfigs/w/WRF/WRF-4.2.2-foss-2020b-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-4.2.2_netCDF-Fortran_separate_path.patch
Labels: update

#13619 fix ITK easyconfigs: switch to CMakePythonPackage easyblock, also enable -DITK_USE_SYSTEM_HDF5 configuration option, fix download URLs
  easybuild/easyconfigs/i/ITK/ITK-4.12.2-foss-2016b-Python-2.7.12.eb
  easybuild/easyconfigs/i/ITK/ITK-4.12.2_update-download-URLs.patch
  easybuild/easyconfigs/i/ITK/ITK-4.13.0-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/i/ITK/ITK-4.13.0-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/i/ITK/ITK-4.13.0_update-download-URLs.patch
  easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018a-Python-2.7.14.eb
  easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/i/ITK/ITK-5.0.1-foss-2019a-Python-3.7.2.eb
  easybuild/easyconfigs/i/ITK/ITK-5.0.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/i/ITK/ITK-5.0b01-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/i/ITK/ITK-5.1.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/ITK/ITK-5.1.2-foss-2020a.eb
  easybuild/easyconfigs/i/ITK/ITK-5.1.2-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/i/ITK/ITK-5.1.2-fosscuda-2020a.eb
Labels: code cleanup

#13434 Fix compile failure in Qt5
  easybuild/easyconfigs/q/Qt5/Qt5-5.8.0-foss-2017b.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.8.0_fix-template-compile-failure-in-webkit.patch
Labels: bug fix

#13878 stick to intel-compilers toolchain for DFT-D3 v3.2.0
  easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-intel-compilers-2021.2.0.eb
Labels: bug fix, change

#13877 {lib}[foss/2021a] TensorFlow v2.6.0 w/ Python 3.9.5
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix_numpy_1.20_compatibility.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix_protobuf_error_message.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0_add-default-shell-env.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0_downgrade-required-versions.patch
Labels: update

#13884 add missing flex build dependency for leidenalg
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.2-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.3-foss-2020b.eb
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.3-fosscuda-2020b.eb
Labels: bug fix

#13883 {lib}[foss/2021a] TensorFlow v2.6.0 w/ Python 3.9.5
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a.eb
Labels: update

#13885 {devel}[system/system] ReFrame v3.8.0
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.8.0.eb
Labels: update

#13879 {devel}[GCCcore/11.2.0] protobuf v3.17.3, protobuf-python v3.17.3, nsync v1.24.0 w/ Python 3.9.6
  easybuild/easyconfigs/n/nsync/nsync-1.24.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.17.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/protobuf/protobuf-3.17.3-GCCcore-11.2.0.eb
Labels: update

#13881 {tools}[foss/2021a] Horovod v0.22.1 w/ Python 3.9.5 + CUDA 11.3.1 on top of TensorFlow 2.6.0
  easybuild/easyconfigs/h/Horovod/Horovod-0.22.1-foss-2021a-CUDA-11.3.1-TensorFlow-2.6.0.eb
Labels: update

#13889 update CMake build dependency for Eigen 3.3.4 + 3.3.5
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.4.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.5.eb
Labels: bug fix, change

#13615 Arrow: Remove superflous CMAKE_BUILD_TYPE
  easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-intel-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-intel-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.16.0-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.16.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-fosscuda-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.7.1-intel-2017b-Python-3.6.3.eb
Labels: code cleanup

#13882 Remove UCX-CUDA dependency from TensorFlow 2.6 easyconfig (not needed as direct dependency)
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a-CUDA-11.3.1.eb
Labels: bug fix, change

#13456 fix Python 2.7.13 easyconfigs by adding missing extensions
  easybuild/easyconfigs/p/Python/Python-2.7.13-foss-2017a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.13-intel-2017a.eb
Labels: bug fix

#13898 strip out custom sanity check paths from VTune 2021.6.0 easyconfig
  easybuild/easyconfigs/v/VTune/VTune-2021.6.0.eb
Labels: code cleanup

#13899 remove SHA256 checksum for IMOD 4.11.5 source tarball + fix installation on top of Python 3
  easybuild/easyconfigs/i/IMOD/IMOD-4.11.5-foss-2020b.eb
  easybuild/easyconfigs/i/IMOD/IMOD-4.11.5-fosscuda-2020b.eb
  easybuild/easyconfigs/i/IMOD/IMOD-4.11.5_fix-csvtohtml-py3.patch
Labels: bug fix

#13893 {vis}[GCCcore/10.3.0] GTK2 v2.24.33, GTK3 v3.24.29
  easybuild/easyconfigs/g/GTK2/GTK2-2.24.33-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GTK2/adwaita-icon-theme-3.34.3_disable-svg-conversion.patch
  easybuild/easyconfigs/g/GTK3/GTK3-3.24.29-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GTK3/adwaita-icon-theme-3.34.3_disable-svg-conversion.patch
Labels: update, change

#11577 fix LAMMPS 3Mar2020 easyconfigs using intel toolchain on AMD CPUs by patching out hardcoded -xHost
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2020a-Python-3.8.2-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2019b-Python-3.7.4-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2020a-Python-3.8.2-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/lammps-stable_3Mar2020_intel_ebflag.patch
Labels: bug fix

#13114 {chem}[intel/2021a] ABINIT v9.4.2
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.4.2-intel-2021a.eb
Labels: update

#13901 fix source URL for Yasm 1.3.0 (+ add missing checksum)
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-6.4.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-foss-2016a.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-foss-2016b.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-foss-2017a.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-gimkl-2.11.5.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-gimkl-2017a.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-intel-2016a.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-intel-2016b.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-intel-2017a.eb
Labels: bug fix

#13900 use GTK2 and GTK3 as dependencies rather than GTK+ for easyconfigs using GCC/10.3.0 toolchain
  easybuild/easyconfigs/g/GIMP/GIMP-2.10.24-GCC-10.3.0.eb
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.18.4-GCC-10.3.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.4-GCC-10.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.29-GCCcore-10.3.0.eb
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.1.5-GCC-10.3.0.eb
Labels: change

#13896 {vis}[GCCcore-10.2.0] GtkSourceView v3.24.11
  easybuild/easyconfigs/g/GtkSourceView/GtkSourceView-3.24.11-GCCcore-10.2.0.eb
Labels: update

#13891 {devel}[system/system] Gradle v6.9.1
  easybuild/easyconfigs/g/Gradle/Gradle-6.9.1.eb
Labels: update

#13829 update to libjxl 0.5 + disable building of man pages
  easybuild/easyconfigs/l/libjxl/libjxl-0.3.7_openexr-3.0_compat.patch
  easybuild/easyconfigs/l/libjxl/libjxl-0.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libjxl/libjxl-0.5_remove-broken-test.patch
Labels: bug fix, change

#13623 Avoid MPICXX dependency in SimpleElastics ITK
  easybuild/easyconfigs/s/SimpleElastix/SimpleElastix-1.1.0-foss-2019b-Python-3.7.4.eb
Labels: code cleanup

#13614 CLHEP: Remove superflous configopts and add sanity-checks/checksums
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.1.3.1-intel-2016a.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.2.0.8-intel-2016a.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.3.1.1-intel-2016a.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.3.4.3-foss-2017b.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.3.4.3-intel-2017b.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.0.0-intel-2017b.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.1.0-foss-2017b.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.1.0-foss-2018b.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.1.0-intel-2017b.eb
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.1.0-intel-2018b.eb
Labels: code cleanup

#11220 {devel}[GCCcore/9.3.0] Bazel v0.29.1
  easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-9.3.0-Java-1.8.eb
Labels: update

#11367 {cae}[intel/2020a] OpenFOAM v2006
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2006-intel-2020a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2006_fix-setAlphaField-compilation.patch
Labels: update

#13892 {devel}[system/system] ant v1.10.11 w/ Java 13
  easybuild/easyconfigs/a/ant/ant-1.10.11-Java-13.eb
Labels: update

#13904 {numlib}[foss/2020b] SLEPc v3.14.2
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.14.2-foss-2020b.eb
Labels: update

#13906 {tools}[GCCcore/10.2.0] Yices v2.6.2
  easybuild/easyconfigs/y/Yices/Yices-2.6.2-GCCcore-10.2.0.eb
Labels: new

#13907 {tools}[GCCcore/10.2.0] BuDDy v2.4
  easybuild/easyconfigs/b/BuDDy/BuDDy-2.4-GCCcore-10.2.0.eb
Labels: new

#13908 {tools}[GCCcore/10.2.0] libtecla v1.6.3
  easybuild/easyconfigs/l/libtecla/libtecla-1.6.3-GCCcore-10.2.0.eb
Labels: new

#13910 update to more recent Meson build dependency for easyconfigs to fix failing RPATH sanity check
  easybuild/easyconfigs/a/ATK/ATK-2.34.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.34.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.34.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.62.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.63.1-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.16.2-GCC-8.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/LibSoup/LibSoup-2.70.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.4-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.1.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-19.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/Meson/Meson-0.59.1-GCCcore-8.3.0-Python-3.7.4.eb
  easybuild/easyconfigs/p/Pango/Pango-1.44.7-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/xtb/xtb-6.2.3-foss-2019b.eb
Labels: bug fix, update

#13909 {tools}[GCCcore/10.2.0] Maude v3.1
  easybuild/easyconfigs/m/Maude/Maude-3.1-GCCcore-10.2.0.eb
Labels: new

#13911 fix shebang for RepeatMasker 4.1.2-p1 Perl script
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.1.2-p1-foss-2020b.eb
Labels: bug fix

#13624 remove -DCMAKE_BUILD_TYPE=RELEASE configure option and add checksums in LLVM easyconfigs
  easybuild/easyconfigs/l/LLVM/LLVM-3.9.0-foss-2016b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-3.9.0-intel-2016b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-3.9.1-foss-2017a.eb
  easybuild/easyconfigs/l/LLVM/LLVM-4.0.0-foss-2017a.eb
  easybuild/easyconfigs/l/LLVM/LLVM-4.0.0-intel-2017a.eb
  easybuild/easyconfigs/l/LLVM/LLVM-4.0.1-intel-2017a.eb
  easybuild/easyconfigs/l/LLVM/LLVM-4.0.1-intel-2017b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-5.0.0-foss-2017b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-5.0.0-fosscuda-2017b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-5.0.0-intel-2017b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-5.0.0-intelcuda-2017b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-5.0.1-GCCcore-6.4.0.eb
Labels: code cleanup

#13621 avoid using system GTK+3 and remove -DCMAKE_BUILD_TYPE=RELEASE configure option in OpenCV easyconfigs
  easybuild/easyconfigs/o/OpenCV/OpenCV-2.4.12-intel-2016a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016b.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016b.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-3.6.3.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017a-Python-2.7.13.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017a-Python-3.6.1.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017b-Python-2.7.14.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017b-Python-3.6.3.eb
Labels: code cleanup

#13903 {bio}[foss/2020b] AutoGeneS v1.0.4 w/ Python 3.8.6
  easybuild/easyconfigs/a/AutoGeneS/AutoGeneS-1.0.4-foss-2020b.eb
Labels: new

#13913 fix software name for Snippy to snippy
  easybuild/easyconfigs/s/snippy/snippy-4.6.0-GCC-9.3.0-Java-13-Python-3.8.2.eb
Labels: bug fix, change

#13914 fix software name for xTB to xtb
  easybuild/easyconfigs/x/xtb/xtb-6.4.1-intel-2021a.eb
Labels: bug fix, change

#13912 prepare release notes for EasyBuild v4.4.2 + bump version to 4.4.2
  RELEASE_NOTES
  setup.py
Labels: update

#13918 {tools}[dummy/dummy] EasyBuild v4.4.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.2.eb
Labels: update

#13919 sync with main + bump version to 4.4.3dev
  RELEASE_NOTES
  easybuild/easyconfigs/s/snippy/snippy-4.6.0-GCC-9.3.0-Java-13-Python-3.8.2.eb
  easybuild/easyconfigs/x/xtb/xtb-6.4.1-intel-2021a.eb
  setup.py
Labels: update

#13922 Drop help2man from flex at SYSTEM level. help2man depends on Perl and we do not want Perl at SYSTEM level.
  easybuild/easyconfigs/f/flex/flex-2.6.3.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4.eb
Labels: enhancement, bug fix

#13923 add patch for OpenBLAS 0.3.15 to fix failing numpy tests on aarch64
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.15-GCC-10.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.15_fix-aarch64.patch
Labels: bug fix

#13924 {bio}[GCC/10.3.0] HMMER2 v2.3.2
  easybuild/easyconfigs/h/HMMER2/HMMER2-2.3.2-GCC-10.3.0.eb
Labels: update

#11383 {chem}[intel/2020a] libctl v4.0.0
  easybuild/easyconfigs/l/libctl/libctl-4.0.0-intel-2020a.eb
Labels: update

#13925 {bio}[gompi/2021a] BLAST+ v2.11.0
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.11.0-gompi-2021a.eb
Labels: update

#11384 {phys}[intel/2020a] Meep v1.4.3
  easybuild/easyconfigs/m/Meep/Meep-1.4.3-intel-2020a.eb
Labels: update

#13931 {tools}[GCCcore/8.3.0] DB v18.1.40
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-8.3.0.eb
Labels: update

#13932 {tools}[GCCcore/8.2.0] DB v18.1.40
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-8.2.0.eb
Labels: update

#13930 {tools}[GCCcore/10.2.0] python-docx v0.8.11 w/ Python 3.8.6
  easybuild/easyconfigs/p/python-docx/python-docx-0.8.11-GCCcore-10.2.0.eb
Labels: new

#13929 {tools}[GCC/10.2.0,iccifort/2020.4.304] TOML-Fortran v0.2.2
  easybuild/easyconfigs/t/TOML-Fortran/TOML-Fortran-0.2.2-GCC-10.2.0.eb
  easybuild/easyconfigs/t/TOML-Fortran/TOML-Fortran-0.2.2-iccifort-2020.4.304.eb
Labels: new

#13939 {lib}[foss/2021a] libharu v2.3.0
  easybuild/easyconfigs/l/libharu/libharu-2.3.0-foss-2021a.eb
Labels: update

#13949 {lib}[GCCcore/10.3.0] RapidJSON v1.1.0
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-10.3.0.eb
Labels: update

#13938 just use cp to copy stereo_chemical_props.txt to AlphaFold installation directory
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.0.0-foss-2020b.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.0.0-fosscuda-2020b.eb
Labels: bug fix

#13946 {lib}[GCCcore/8.3.0] LibUUID v1.0.3
  easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-GCCcore-8.3.0.eb
Labels: update

#13942 {vis}[GCCcore/10.3.0] bashplotlib v0.6.5 w/ Python 3.9.5
  easybuild/easyconfigs/b/bashplotlib/bashplotlib-0.6.5-GCCcore-10.3.0.eb
Labels: new

#13941 {data}[GCCcore/10.3.0] DB_File v1.856
  easybuild/easyconfigs/d/DB_File/DB_File-1.856-GCCcore-10.3.0.eb
Labels: update

#13937 {tools}[system/system] rclone v1.56.0
  easybuild/easyconfigs/r/rclone/rclone-1.56.0-amd64.eb
Labels: update

#13944 {bio}[foss/2021a] EMBOSS v6.6.0
  easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-foss-2021a.eb
Labels: update

#13936 {bio}[foss/2020b] AdapterRemoval v2.3.2
  easybuild/easyconfigs/a/AdapterRemoval/AdapterRemoval-2.3.2-GCC-10.2.0.eb
Labels: update

#13962 add JASPAR2020 to R-bundle-Bioconductor 3.13
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.13-foss-2021a-R-4.1.0.eb
Labels: enhancement

#13961 add missing Python dependency for WIEN2k 21.1 + patch to fix build failure for lapw0_mpi with libxc
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-21.1-intel-2021a.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-21.1_fix_libxc_for_lapw0_mpi.patch
Labels: bug fix

#13969 add additional valid checksum for lhs 1.1.1 extension in recent R 4.0.x and 4.1.0 easyconfigs
  easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb
  easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
Labels: bug fix

#13960 add UnZip build dependency to TensorFlow 2.6.0 easyconfigs
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a.eb
Labels: enhancement

#13958 add UnZip build dependency to TensorFlow 2.4.1 easyconfigs
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-foss-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fosscuda-2020b.eb
Labels: enhancement

#13959 add UnZip build dependency to TensorFlow 2.5.0 easyconfigs
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-foss-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-fosscuda-2020b.eb
Labels: enhancement

#13966 {data}[GCCcore/10.3.0] XML-LibXML v2.0207
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0207-GCCcore-10.3.0.eb
Labels: update

#13258 {chem}[foss/2020b,intel/2020b] ASE v3.22.0, GPAW v21.6.0 w/ Python 3.8.6
  easybuild/easyconfigs/a/ASE/ASE-3.22.0-foss-2020b.eb
  easybuild/easyconfigs/a/ASE/ASE-3.22.0-intel-2020b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.6.0-foss-2020b-ASE-3.22.0.eb
  easybuild/easyconfigs/g/GPAW/GPAW-21.6.0-intel-2020b-ASE-3.22.0.eb
Labels: update

#13972 Fix WIEN2k Fortran system call stdout/err redirection.
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-21.1-intel-2021a.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-21.1_fix_system_stderr_redirection.patch
Labels: bug fix

#13963 {bio}[foss/2021a] scGeneFit v1.0.2 w/ Python 3.9.5
  easybuild/easyconfigs/s/scGeneFit/scGeneFit-1.0.2-foss-2021a.eb
Labels: new

#13970 {bio}[foss/2021a] scanpy v1.8.1, Seaborn v0.11.2, leidenalg v0.8.7 w/ Python 3.9.5
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.8.7-foss-2021a.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.11.2-foss-2021a.eb
  easybuild/easyconfigs/s/scanpy/scanpy-1.8.1-foss-2021a.eb
Labels: update

#12080 {bio}[foss/2020b] OrthoFinder v2.5.2, FastME v2.1.6.1, MCL v14.137, ... w/ Python 3.8.6
  easybuild/easyconfigs/f/FastME/FastME-2.1.6.1-GCC-10.2.0.eb
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-10.2.0.eb
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.5.2-foss-2020b.eb
Labels: update

#13933 fix source URL for ADMIXTURE
  easybuild/easyconfigs/a/ADMIXTURE/ADMIXTURE-1.3.0.eb
Labels: bug fix

#12803 {chem,tools}[GCCcore/8.3.0,intel/2019b] Meson v0.58.0, DFT-D4 v3.2.0 w/ Python 3.7.4
  easybuild/easyconfigs/d/DFT-D4/DFT-D4-3.2.0-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/d/DFT-D4/DFT-D4-3.2.0-remove_module_id.patch
Labels: new, update

#13980 {bio}[foss/2020b] OrthoFinder v2.5.4 w/ Python 3.8.6
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.5.4-foss-2020b.eb
Labels: update

#13957 {lib}[GCC/10.3.0] Boost.Python v1.76.0 w/ Python 3.9.5
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.76.0-GCC-10.3.0.eb
Labels: update

#13915 add missing brotli dependency to freetype
  easybuild/easyconfigs/b/Brotli/Brotli-1.0.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.10.4-GCCcore-10.3.0.eb
Labels: bug fix, update

#13984 {bio}[foss/2020b] CIRI-long v1.0.2 w/ Python 3.8.6
  easybuild/easyconfigs/c/CIRI-long/CIRI-long-1.0.2-foss-2020b.eb
Labels: new

#13862 {lib}[foss/2021a] QD v0.8.9 w/ Python 3.9.5
  easybuild/easyconfigs/q/QD/QD-0.8.9-foss-2021a.eb
  easybuild/easyconfigs/q/QD/QD-0.8.9_remove_pybind_requirement.patch
Labels: new

#13965 {bio}[GCCcore/10.3.0] GD v2.73
  easybuild/easyconfigs/g/GD/GD-2.73-GCCcore-10.3.0.eb
Labels: update

#13982 {bio}[foss/2020b] isoCirc v1.0.4 w/ Python 3.8.6
  easybuild/easyconfigs/i/isoCirc/isoCirc-1.0.4-foss-2020b.eb
Labels: new

#13993 {bio}[GCCcore/10.3.0] BioPerl v1.7.8
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-10.3.0.eb
Labels: update

#13990 {VIS}[foss/2020b] ETE bumped to 3.1.2, required for artic
  easybuild/easyconfigs/e/ETE/ETE-3.1.2-foss-2020b.eb
Labels: update

#13992 {bio}[GCCcore/10.2.0] LSD2 bumped to 2.2, required for artic #13852
  easybuild/easyconfigs/l/LSD2/LSD2-2.2-GCCcore-10.2.0.eb
Labels: update

#13994 {bio}[foss/2021a] ClustalW2 v2.1
  easybuild/easyconfigs/c/ClustalW2/ClustalW2-2.1-foss-2021a.eb
Labels: update

#13989 Add OpenSSL dependency to Kent_tools 418 easyconfig to fix a link error
  easybuild/easyconfigs/k/Kent_tools/Kent_tools-418-GCC-10.3.0.eb
Labels: bug fix

#13854 {lib}[foss/2020b] TensorFlow v2.2.3
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.3-foss-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.3_fix-__tensorflow_core_graph_mkl_related_tests.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.3_fix-numpy-UFunc-sig-change.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.3_fix-source_utils_test-in-python38.patch
Labels: update

#14000 {tools}[foss/2020b] networkx v2.6.2
  easybuild/easyconfigs/n/networkx/networkx-2.6.2-foss-2020b.eb
Labels: update

#13997 {bio}[GCCcore/10.2.0] Racon v1.4.21
  easybuild/easyconfigs/r/Racon/Racon-1.4.21-GCCcore-10.2.0.eb
Labels: update

#13999 {bio}[GCCcore/10.2.0] edlib v1.3.9
  easybuild/easyconfigs/e/edlib/edlib-1.3.9-GCC-10.2.0.eb
Labels: update

#14010 Fix Racon-1.4.7-gcccuda-2019b.eb
  easybuild/easyconfigs/r/Racon/Racon-1.4.7-gcccuda-2019b.eb
Labels: bug fix

#13998 {lang}[GCCcore/10.2.0] Rust v1.52.1
  easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.2.0.eb
Labels: update

#13853 {bio}[foss/2020b] medaka v1.4.3 w/ Python 3.8.6
  easybuild/easyconfigs/m/medaka/medaka-1.4.3-foss-2020b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#14013 fix source URL for KEGG.db extension in R-bundle-Bioconductor 3.13 easyconfig (since it's a deprecated library now)
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.13-foss-2021a-R-4.1.0.eb
Labels: bug fix

#14018 add patch for BLIS 0.8.1 to fix dgemm FPE signalling on Broadwell
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1_fix_dgemm-fpe-signalling-on-broadwell.patch
Labels: bug fix

#14016 {devel}[GCCcore/11.2.0] glew v2.2.0
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-11.2.0-egl.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-11.2.0-glx.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-11.2.0-osmesa.eb
Labels: update

#14004 make binutils a build-only dependency for Brotli + add sanity check command
  easybuild/easyconfigs/b/Brotli/Brotli-1.0.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/b/Brotli/Brotli-1.0.9-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/Brotli/Brotli-1.0.9-GCCcore-8.3.0.eb
Labels: enhancement

#14009 {math}[GCCcore/10.2.0] Eigen v3.3.9
  easybuild/easyconfigs/e/Eigen/Eigen-3.3.9-GCCcore-10.2.0.eb
Labels: update

#14012 {bio}[foss/2021a] pycoQC v2.5.2 w/ Python 3.9.5
  easybuild/easyconfigs/p/pycoQC/pycoQC-2.5.2-foss-2021a.eb
Labels: new

#14015 {bio}[foss/2020b] PhyML v3.3.20200621
  easybuild/easyconfigs/p/PhyML/PhyML-3.3.20200621-foss-2020b.eb
Labels: update

#13991 {bio}[gompi/2020b] IQ-TREE v2.1.2
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.1.2-gompi-2020b.eb
Labels: update

#14022 {math}[GCCcore/10.3.0] Gurobi v9.1.2 w/ Python 3.9.5
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.1.2-GCCcore-10.3.0.eb
Labels: update

#14001 {bio}[system/system] QIIME2 v2021.8
  easybuild/easyconfigs/q/QIIME2/QIIME2-2021.8.eb
Labels: update

#14027 {bio}[gompi/2021a] MAFFT v7.487
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.487-gompi-2021a-with-extensions.eb
Labels: update

#13995 {bio}[GCCcore/10.2.0] Longshot v0.4.3
  easybuild/easyconfigs/l/Longshot/Longshot-0.4.3-GCCcore-10.2.0.eb
Labels: update

#14026 {bio}[GCC/10.3.0] CD-HIT v4.8.1
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-GCC-10.3.0.eb
Labels: update

#14019 {toolchain}[system/system] gobff v2021a with HPL/2.3
  easybuild/easyconfigs/g/gobff/gobff-2021a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-gobff-2021a.eb
  easybuild/easyconfigs/l/libFLAME/libFLAME-5.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2021a-bf.eb
Labels: update

#14003 {tools}[foss/2021a] jax v0.2.20 w/ Python 3.9.5
  easybuild/easyconfigs/j/jax/jax-0.2.20-foss-2021a.eb
  easybuild/easyconfigs/j/jax/jaxlib-0.1.71_fix-llvm-env.patch
  easybuild/easyconfigs/j/jax/jaxlib-0.1.71_no-tensorflow-download.patch
Labels: update

#14002 add missing Brotli dependency for freetype 2.11.0 + add sanity check command
  easybuild/easyconfigs/b/Brotli/Brotli-1.0.9-GCCcore-11.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.11.0-GCCcore-11.2.0.eb
Labels: bug fix

#14014 {bio}[foss/2020b] python-parasail v1.2.4 w/ Python 3.8.6
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.2.4-foss-2020b.eb
Labels: update

#13996 {bio}[GCCcore/10.2.0] Muscle bumped to 3.8.31, required for artic #13852
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.31-GCCcore-10.2.0.eb
Labels: update

#14007 {bio}[foss/2020b] rampart v1.2.0 w/ Python 3.8.6
  easybuild/easyconfigs/r/rampart/rampart-1.2.0-foss-2020b.eb
Labels: update

#13890 {bio}[foss/2020b] scanpy v1.8.1 w/ Python 3.8.6
  easybuild/easyconfigs/s/scanpy/scanpy-1.8.1-foss-2020b.eb
Labels: update

#14037 Update to include artic-ncov2019-2021.06.24
  test/easyconfigs/easyconfigs.py
Labels: tests

#14038 Move BLIS/libFLAME to GCC level in gobff/2021a
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1-GCC-10.3.0.eb
  easybuild/easyconfigs/g/gobff/gobff-2021a.eb
  easybuild/easyconfigs/l/libFLAME/libFLAME-5.2.0-GCC-10.3.0.eb
Labels: bug fix

#14025 Fix TensorFlow 2.2.3 on PPC
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.3-foss-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.3_fix-bfloat16-alias-violation.patch
Labels: bug fix

#13396 {mpi}[intel-compilers/2021.3.0] impi v2021.3.0
  easybuild/easyconfigs/i/impi/impi-2021.3.0-intel-compilers-2021.3.0.eb
Labels: update

#13876 {chem}[intel/2021a] NWChem v7.0.2
  easybuild/easyconfigs/n/NWChem/NWChem-7.0.2-intel-2021a.eb
  easybuild/easyconfigs/n/NWChem/NWChem-7.0.2_fix_gnumakefile.patch
Labels: update

#14042 {data}[foss/2021a] Cartopy v0.20.0, Fiona v1.8.20, pyproj v3.1.0 w/ Python 3.9.5
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.20.0-foss-2021a.eb
  easybuild/easyconfigs/f/Fiona/Fiona-1.8.20-foss-2021a.eb
  easybuild/easyconfigs/p/pyproj/pyproj-3.1.0-GCCcore-10.3.0.eb
Labels: update

#14043 {perf}[gompi/2021a] Scalasca v2.6
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.6-gompi-2021a.eb
Labels: update

#14045 {bio}[GCC/10.3.0] MEME v5.4.1 w/ Python 3.9.5
  easybuild/easyconfigs/m/MEME/MEME-5.4.1-GCC-10.3.0.eb
Labels: update

#14052 Dropping the h5py dep so Keras just uses h5py through the TensorFlow (req. h5py~=2.1.0) dep
  easybuild/easyconfigs/k/Keras/Keras-2.4.3-foss-2020b.eb
  easybuild/easyconfigs/k/Keras/Keras-2.4.3-fosscuda-2020b.eb
Labels: bug fix

#14023 {bio,data}[foss/2019b] ITK v4.13.1, VMTK v1.4.0 w/ Python 3.7.4
  easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/v/VMTK/VMTK-1.4.0-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#14055 {bio}[GCCcore/10.3.0] Kalign v3.3.1
  easybuild/easyconfigs/k/Kalign/Kalign-3.3.1-GCCcore-10.3.0.eb
Labels: update

#14056 {bio}[gompi/2021a] HH-suite v3.3.0 w/ Python 3.9.5
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-gompi-2021a.eb
Labels: update

#14060 {bio}[foss/2020b] nanopolish v0.13.3
  easybuild/easyconfigs/n/nanopolish/nanopolish-0.13.3-foss-2020b.eb
Labels: enhancement

#14050 {bio}[GCC/10.3.0] libSBML v5.19.0
  easybuild/easyconfigs/l/libSBML/libSBML-5.19.0-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libSBML/libsbml-fix_install_libpaths.patch
  easybuild/easyconfigs/l/libSBML/libsbml-fix_perl_auto_case.patch
Labels: new

#14053 Adding Nextflow v21.08.0 easyconfig, with Java/13
  easybuild/easyconfigs/n/Nextflow/Nextflow-21.08.0.eb
Labels: update

#14049 {chem}[system/system] RInChI v1.00
  easybuild/easyconfigs/r/RInChI/RInChI-1.00-x86_64.eb
Labels: new

#14035 {bio}[system/system] TRUST4 v1.0.5.1
  easybuild/easyconfigs/t/TRUST4/TRUST4-1.0.5.1.eb
Labels: new

#13175 {chem}[GCC/10.3.0] Libint v2.6.0
  easybuild/easyconfigs/l/Libint/Libint-2.6.0-GCC-10.3.0-lmax-6-cp2k.eb
Labels: update

#14062 {data}[foss/2021a] HDBSCAN v0.8.27 w/ Python 3.9.5
  easybuild/easyconfigs/h/HDBSCAN/HDBSCAN-0.8.27-foss-2021a.eb
Labels: new

#14048 {devel}[GCCcore/10.3.0,GCCcore/11.2.0] gflags v2.2.2
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-11.2.0.eb
Labels: update

#14063 Fix environment variable that should have been renamed CUDACORE -> CUDA when we renamed the easyconfigs
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-gompi-2021a-CUDA-11.3.1.eb
Labels: bug fix

#14047 {data}[GCCcore/11.2.0] PostgreSQL v13.4
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-13.4-GCCcore-11.2.0.eb
Labels: update

#14061 {math}[GCC/10.3.0,intel-compilers/2021.2.0] libxsmm v1.16.2
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.2-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.2-intel-compilers-2021.2.0.eb
Labels: update

#14032 {chem}[GCC/11.2.0] libxc v5.1.6
  easybuild/easyconfigs/l/libxc/libxc-5.1.6-GCC-11.2.0.eb
Labels: update

#14031 {math}[foss/2021.07] ELPA v2021.05.001
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.001-foss-2021.07.eb
Labels: update

#14033 {chem}[foss/2021a,intel/2021a] QuantumESPRESSO v6.8
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8-foss-2021a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8-intel-2021a.eb
Labels: update

#14065 {tools}[fosscuda/2020b] Horovod v0.22.0 w/ Python 3.8.6
  easybuild/easyconfigs/h/Horovod/Horovod-0.22.1-fosscuda-2020b-TensorFlow-2.5.0.eb
Labels: update
