Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2021-10, with the labels that each got.

#14092 Updated source_urls since the old one stopped working.
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.1.0-foss-2019b.eb
Labels: bug fix

#14095 {lib}[fosscuda/2020b] PyTorch-Geometric v2.0.1 w/ Python 3.8.6
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-2.0.1-fosscuda-2020b-PyTorch-1.9.0.eb
Labels: update

#14097 Add Perl and Python runtime dependencies to Bowtie2
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.4-GCC-10.3.0.eb
Labels: enhancement

#14096 fix source URL for SUNDIALS 5.x
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.1.0-intel-2019b.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.7.0-foss-2020b.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.7.0-fosscuda-2020b.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-5.7.0-intel-2020b.eb
Labels: bug fix

#14074 {bio}[GCCcore/10.2.0] MotionCor2 v1.4.4
  easybuild/easyconfigs/m/MotionCor2/MotionCor2-1.4.4-GCCcore-10.2.0.eb
Labels: update

#14099 New download urls for SCOTCH 6.1.0
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2020b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2021a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-iimpi-2020b.eb
Labels: bug fix

#14104 {bio}[foss/2020b,foss/2021a] SHAPEIT4 v4.2.2
  easybuild/easyconfigs/s/SHAPEIT4/SHAPEIT4-4.2.2-foss-2020b.eb
  easybuild/easyconfigs/s/SHAPEIT4/SHAPEIT4-4.2.2-foss-2021a.eb
  easybuild/easyconfigs/s/SHAPEIT4/SHAPEIT4_4.2.2_use_EB_settings.patch
Labels: update

#14105 {numlib}[GCC/11.2.0] OpenBLAS v0.3.18
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.18-GCC-11.2.0.eb
Labels: update

#14232 {astro}[foss/2021a,intel/2021a] astropy v4.3.1 w/ Python 3.9.5
  easybuild/easyconfigs/a/astropy/astropy-4.3.1-foss-2021a.eb
  easybuild/easyconfigs/a/astropy/astropy-4.3.1-intel-2021a.eb
Labels: update

#14235 {vis}[foss/2021a] scikit-image v0.18.3 w/ Python 3.9.5
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.18.3-foss-2021a.eb
Labels: update

#14227 {vis}[foss/2020b] Pillow v6.2.2 w/ Python 2.7.18
  easybuild/easyconfigs/p/Pillow/Pillow-6.2.2-foss-2020b-Python-2.7.18.eb
Labels: update

#14224 Create PyTables-3.5.2-foss-2020b-Python-2.7.18.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.5.2-foss-2020b-Python-2.7.18.eb
Labels: update

#13902 {chem}[GCC/10.3.0] InChI v1.06
  easybuild/easyconfigs/i/InChI/InChI-1.06-GCC-10.3.0.eb
  easybuild/easyconfigs/i/InChI/InChI-1.06_fedora-build-fixes.patch
Labels: new

#14255 {lang}[intel/2021b] SciPy-bundle v2021.10 w/ Python 3.9.6
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-intel-2021b.eb
Labels: update

#14157 {vis}[iccifort/2020.4.304] SMV 6.7.17 (smokeview)
  easybuild/easyconfigs/l/LPeg/LPeg-1.0.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/SMV/SMV-6.7.17-iccifort-2020.4.304.eb
  easybuild/easyconfigs/s/SMV/SMV-6.7.17_missing-includes.patch
  easybuild/easyconfigs/s/SMV/example.smv
Labels: new
