Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-02, with the labels that each got.

#14790 {bio,lib}[GCCcore/11.2.0] cutadapt v3.5, python-isal v0.11.1 w/ Python 3.9.6
  easybuild/easyconfigs/c/cutadapt/cutadapt-3.5-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/python-isal/python-isal-0.11.1-GCCcore-11.2.0.eb
Labels: update

#14881 trim test configurations for easyconfigs test suite: only test with Python 2.7 + 3.6 and Lmod 7.x + 8.x
  .github/workflows/unit_tests.yml
Labels: change, tests

#14791 {bio}[GCC/11.2.0] Bowtie v1.3.1
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.3.1-GCC-11.2.0.eb
Labels: update

#14866 {vis}[foss/2021a] VTK v8.2.0 w/ Python 3.9.5
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2021a.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0_gcc10-fix.patch
Labels: update

#14863 {vis}[GCCcore/11.2.0] Graphviz v2.50.0 w/ Python 3.9.6
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.50.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.50.0_skip-install-data-hook.patch
Labels: update

#14809 {devel}[GCCcore/11.2.0] typing-extensions v3.10.0.2 w/ Python 3.9.6
  easybuild/easyconfigs/t/typing-extensions/typing-extensions-3.10.0.2-GCCcore-11.2.0.eb
Labels: update

#14890 {data}[intel/2021b] netcdf4-python v1.5.7 w/ Python 3.9.6
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.7-intel-2021b.eb
Labels: update

#14814 {lib}[GCCcore/11.2.0] namedlist v1.8 w/ Python 3.9.6
  easybuild/easyconfigs/n/namedlist/namedlist-1.8-GCCcore-11.2.0.eb
Labels: new

#14892 {lang}[GCCcore/11.2.0] Perl v5.34.0
  easybuild/easyconfigs/p/Perl/Perl-5.34.0-GCCcore-11.2.0-minimal.eb
Labels: update

#14899 {data}[GCCcore/11.2.0] BeautifulSoup v4.10.0 w/ Python 3.9.6
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.10.0-GCCcore-11.2.0.eb
Labels: update

#14895 {astro}[foss/2021b] astropy v4.3.1 w/ Python 3.9.6
  easybuild/easyconfigs/a/astropy/astropy-4.3.1-foss-2021b.eb
Labels: update

#14900 {lib}[foss/2021b] PyEVTK v2.0.0 w/ Python 3.9.6
  easybuild/easyconfigs/p/PyEVTK/PyEVTK-2.0.0-foss-2021b.eb
Labels: new

#14889 Fix Kraken2 ncbi ftp/https check in rsync_from_ncbi.pl for versions 2.0.9-2.1.1 (taken from Kraken2 2.1.2)
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.9-beta-foss-2018b-Perl-5.28.0.eb
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.0.9-beta-gompi-2020a-Perl-5.30.2.eb
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.1-gompi-2020b.eb
Labels: bug fix

#14885 {system}[GCCcore/11.2.0] file v5.41
  easybuild/easyconfigs/f/file/file-5.41-GCCcore-11.2.0.eb
Labels: update

#14867 {tools}[foss/2020b, fosscuda/2020b] nanomax-analysis-utils 0.4.3
  easybuild/easyconfigs/f/FabIO/FabIO-0.11.0-fosscuda-2020b.eb
  easybuild/easyconfigs/n/nanomax-analysis-utils/nanomax-analysis-utils-0.4.3-foss-2020b.eb
  easybuild/easyconfigs/n/nanomax-analysis-utils/nanomax-analysis-utils-0.4.3-fosscuda-2020b.eb
  easybuild/easyconfigs/p/pyFAI/pyFAI-0.20.0-foss-2020b.eb
  easybuild/easyconfigs/p/pyFAI/pyFAI-0.20.0-fosscuda-2020b.eb
  easybuild/easyconfigs/p/pymca/pymca-5.6.3-fosscuda-2020b.eb
  easybuild/easyconfigs/s/silx/silx-0.14.0-fosscuda-2020b.eb
Labels: update

#14859 add missing UCX-CUDA dep to GROMACS for foss-2021a-CUDA-11.3.1
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-foss-2021a-CUDA-11.3.1-PLUMED-2.7.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-foss-2021a-CUDA-11.3.1.eb
Labels: bug fix

#14886 {bio}[GCCcore/11.2.0] NGS v2.11.2
  easybuild/easyconfigs/n/NGS/NGS-2.11.2-GCCcore-11.2.0.eb
Labels: update

#14882 {vis}[GCC/11.2.0] GST-plugins-base v1.18.5, GStreamer v1.18.5
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.18.5-GCC-11.2.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.5-GCC-11.2.0.eb
Labels: update

#14848 {tools}[GCCcore/11.2.0] pytest-xdist v2.5.0 w/ Python 3.9.6
  easybuild/easyconfigs/p/pytest-xdist/pytest-xdist-2.5.0-GCCcore-11.2.0.eb
Labels: update

#14810 {math}[intel/2021b] ArviZ v0.11.4 w/ Python 3.9.6
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.11.4-intel-2021b.eb
Labels: update

#14777 {data,tools}[foss/2021b] dask v2022.1.0, bokeh v2.4.2 w/ Python 3.9.6
  easybuild/easyconfigs/b/bokeh/bokeh-2.4.2-foss-2021b.eb
  easybuild/easyconfigs/d/dask/dask-2022.1.0-foss-2021b.eb
Labels: update

#14775 {vis}[foss/2021b] imageio v2.13.5 w/ Python 3.9.6
  easybuild/easyconfigs/i/imageio/imageio-2.13.5-foss-2021b.eb
Labels: update

#14846 {tools}[GCCcore/10.2.0,GCCcore/10.3.0,GCCcore/11.2.0] xxd v8.2.4220
  easybuild/easyconfigs/x/xxd/xxd-8.2.4220-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/xxd/xxd-8.2.4220-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/xxd/xxd-8.2.4220-GCCcore-11.2.0.eb
Labels: new

#14784 {lib}[GCCcore/10.3.0,GCCcore/11.2.0] aiohttp v3.8.1 w/ Python 3.9.5 + 3.9.6
  easybuild/easyconfigs/a/aiohttp/aiohttp-3.8.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/aiohttp/aiohttp-3.8.1-GCCcore-11.2.0.eb
Labels: update

#14851 {bio}[foss/2019b] pyradiomics v3.0.1 w/ Python 3.7.4
  easybuild/easyconfigs/p/pyradiomics/pyradiomics-3.0.1-foss-2019b-Python-3.7.4.eb
Labels: new

#14772 {lib}[GCC/11.2.0] Boost.Python v1.77.0 w/ Python 3.9.6
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.77.0-GCC-11.2.0.eb
Labels: update

#14849 {tools}[GCCcore/10.3.0] atools v1.4.8 w/ Python 2.7.18
  easybuild/easyconfigs/a/atools/atools-1.4.8-GCCcore-10.3.0-Python-2.7.18.eb
Labels: update

#14883 {vis}[GCC/11.2.0] wxWidgets v3.1.5
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.1.5-GCC-11.2.0.eb
Labels: update

#14853 {lib}[GCCcore/11.2.0] intervaltree v0.1
  easybuild/easyconfigs/i/intervaltree/intervaltree-0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/i/intervaltree/intervaltree-0.1_fix-numeric_limits.patch
Labels: update

#14878 {system}[system/system] CUDA v11.5.1
  easybuild/easyconfigs/c/CUDA/CUDA-11.5.1.eb
Labels: update

#14802 add missing dependencies on graphite2, HarfBuzz to Qt5
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.2-GCCcore-11.2.0.eb
Labels: bug fix

#14735 {system}[GCCcore/11.2.0] OpenSSL v1.1.1k
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.1k-GCCcore-11.2.0.eb
Labels: update

#14800 {bio}[foss/2021b] methylpy v1.2.9 w/ Python 3.9.6
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.3.1-GCC-11.2.0.eb
  easybuild/easyconfigs/m/methylpy/methylpy-1.2.9-foss-2021b.eb
Labels: update

#13774 {phys}[foss/2020a] Siesta v4.1.5
  easybuild/easyconfigs/s/Siesta/Siesta-4.1.5-foss-2020a.eb
Labels: update

#14797 update TALYS sources to (hopefully) ensure constant checksums
  easybuild/easyconfigs/t/TALYS/TALYS-1.95-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/TALYS/TALYS-1.95-GCCcore-9.3.0.eb
Labels: bug fix

#14808 {data,math}[intel/2021b] mkl-service v2.3.0, PyMC3 v3.11.1, Theano v1.1.2 w/ Python 3.9.6
  easybuild/easyconfigs/m/mkl-service/mkl-service-2.3.0-intel-2021b.eb
  easybuild/easyconfigs/p/PyMC3/PyMC3-3.11.1-intel-2021b.eb
  easybuild/easyconfigs/t/Theano/Theano-1.1.2-intel-2021b-PyMC.eb
Labels: update

#14910 {compiler}[GCCcore/11.2.0] AOCC v3.2.0
  easybuild/easyconfigs/a/AOCC/AOCC-3.2.0-GCCcore-11.2.0.eb
Labels: update

#14904 {bio}[system/system] SeqKit v2.1.0
  easybuild/easyconfigs/s/SeqKit/SeqKit-2.1.0.eb
Labels: update

#14894 {data}[gompi/2021b] HDF5 v1.10.8
  easybuild/easyconfigs/h/HDF5/HDF5-1.10.8-gompi-2021b.eb
Labels: update

#14893 also install Python bindings for SHTns 3.5.1
  easybuild/easyconfigs/s/SHTns/SHTns-3.5.1-foss-2021b.eb
Labels: enhancement

#14884 {bio}[foss/2021b] ctffind v4.1.14
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2021b.eb
Labels: update

#14865 {bio}[foss/2021b] DROP v1.1.1, tMAE v1.0.1 w/ Python 3.9.6
  easybuild/easyconfigs/d/DROP/DROP-1.1.1-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/t/tMAE/tMAE-1.0.1-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/t/tMAE/tMAE_1.0.1_remove_early_closing_brace.patch
Labels: update

#14854 {bio}[GCCcore/11.2.0] multichoose v1.0.3
  easybuild/easyconfigs/m/multichoose/multichoose-1.0.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/multichoose/multichoose-1.0.3_improve-build-system.patch
Labels: update

#14907 {lib}[GCCcore/11.2.0] GnuTLS v3.7.3, libtasn1 v4.18.0, libunistring v1.0, ...
  easybuild/easyconfigs/g/GnuTLS/GnuTLS-3.7.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/Guile/Guile-3.0.7-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libtasn1/libtasn1-4.18.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libunistring/libunistring-1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/p11-kit/p11-kit-0.24.1-GCCcore-11.2.0.eb
Labels: update

#14842 {chem}[GCC/11.2.0] NCIPLOT v4.0-20200624
  easybuild/easyconfigs/n/NCIPLOT/NCIPLOT-4.0-20200624-GCC-11.2.0.eb
Labels: update

#14736 {bio}[GCC/11.2.0] PRANK v170427
  easybuild/easyconfigs/p/PRANK/PRANK-170427-GCC-11.2.0.eb
Labels: update

#14906 {bio}[foss/2021b] GEMMA v0.98.5
  easybuild/easyconfigs/g/GEMMA/GEMMA-0.98.5-foss-2021b.eb
Labels: update

#14759 {bio}[GCC/11.2.0] ClustalW2 v2.1
  easybuild/easyconfigs/c/ClustalW2/ClustalW2-2.1-GCC-11.2.0.eb
Labels: update

#14903 {vis}[GCCcore/11.2.0] OpenSlide v3.4.1, openslide-python v1.1.2 w/ Python 3.9.6
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/o/openslide-python/openslide-python-1.1.2-GCCcore-11.2.0.eb
Labels: update

#14818 {bio}[GCCcore/11.2.0] MinPath v1.6 w/ Python 3.9.6
  easybuild/easyconfigs/m/MinPath/MinPath-1.6-GCCcore-11.2.0.eb
Labels: update

#14805 {vis}[GCC/11.2.0] SoQt v1.6.0
  easybuild/easyconfigs/s/SoQt/SoQt-1.6.0-GCC-11.2.0.eb
Labels: update

#14057 {bio}[foss/2021a] pftoolsV3 v3.2.11
  easybuild/easyconfigs/p/pftoolsV3/pftoolsV3-3.2.11-foss-2021a.eb
Labels: update

#14879 {system}[system/system] CUDA v11.6.0
  easybuild/easyconfigs/c/CUDA/CUDA-11.6.0.eb
Labels: update

#14811 {bio}[intel/2021b] Bambi v0.7.1 w/ Python 3.9.6
  easybuild/easyconfigs/b/Bambi/Bambi-0.7.1-intel-2021b.eb
Labels: new

#14845 {bio}[foss/2021a] ConnectomeWorkbench v1.5.0
  easybuild/easyconfigs/c/ConnectomeWorkbench/ConnectomeWorkbench-1.5.0-GCCcore-10.3.0.eb
Labels: update

#14887 {bio}[gompi/2021b] ncbi-vdb v2.11.2
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-2.11.2-gompi-2021b.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-cstdlib.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#14920 {bio}[gompi/2021b] BLAST+ v2.9.0
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0-gompi-2021b.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0_fix-GCC-10.patch
Labels: update

#14785 {bio}[GCC/11.2.0] Crumble v0.8.3
  easybuild/easyconfigs/c/Crumble/Crumble-0.8.3-GCC-11.2.0.eb
Labels: new

#14855 {bio,lib}[GCCcore/11.2.0] vcflib v1.0.3, tabixpp v1.1.0, fastahack v1.0.0, ... w/ Python 3.9.6
  easybuild/easyconfigs/f/fastahack/fastahack-1.0.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/f/filevercmp/filevercmp-20191210-GCCcore-11.2.0.eb
  easybuild/easyconfigs/f/fsom/fsom-20141119-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/smithwaterman/smithwaterman-20160702-GCCcore-11.2.0.eb
  easybuild/easyconfigs/t/tabixpp/tabixpp-1.1.0-GCC-11.2.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.3-GCC-11.2.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.3_use-external-deps.patch
Labels: update

#14938 {bio}[foss/2021b] histolab v0.4.1 w/ Python 3.9.6
  easybuild/easyconfigs/h/histolab/histolab-0.4.1-foss-2021b.eb
Labels: new

#14940 add catlearn extension to easyconfig for R v4.1.2
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: enhancement

#14888 {bio}[gompi/2021b] HISAT2 v2.2.1
  easybuild/easyconfigs/h/HISAT2/HISAT2-2.2.1-gompi-2021b.eb
  easybuild/easyconfigs/h/HISAT2/hisat2-libname-fix.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#14911 {lib}[foss/2021b] PyEVTK v1.4.1 w/ Python 3.9.6
  easybuild/easyconfigs/p/PyEVTK/PyEVTK-1.4.1-foss-2021b.eb
Labels: update

#14914 {lib}[GCCcore/11.2.0] libRmath v4.1.2
  easybuild/easyconfigs/l/libRmath/libRmath-4.1.2-GCCcore-11.2.0.eb
Labels: update

#14913 {bio}[GCCcore/11.2.0] tabix v0.2.6
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-11.2.0.eb
Labels: update

#14918 {debugger}[gompi/2021b,iimpi/2021b] Valgrind v3.18.1
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.18.1-gompi-2021b.eb
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.18.1-iimpi-2021b.eb
Labels: update

#14921 {compiler}[GCCcore/11.2.0] Clang v13.0.1
  easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.2.0.eb
Labels: update

#14923 disable building of tests/benchmarks for snappy 1.1.8 to avoid failing build
  easybuild/easyconfigs/s/snappy/snappy-1.1.8-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/snappy/snappy-1.1.8-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/snappy/snappy-1.1.8-GCCcore-9.3.0.eb
Labels: bug fix

#14924 disable use of -Werror for recent NSS versions
  easybuild/easyconfigs/n/NSS/NSS-3.42.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.45-GCCcore-8.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.51-GCCcore-9.3.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.57-GCCcore-10.2.0.eb
Labels: bug fix

#14926 {lib}[foss/2021a] PyTorch-Lightning v1.5.9, tensorboard v2.8.0 w/ Python 3.9.5
  easybuild/easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-1.5.9-foss-2021a.eb
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.8.0-foss-2021a.eb
Labels: new

#14915 {bio}[GCC/11.2.0] FastQTL v2.184
  easybuild/easyconfigs/f/FastQTL/FastQTL-2.184-GCC-11.2.0.eb
  easybuild/easyconfigs/f/FastQTL/FastQTL-makefile.patch
Labels: update

#14927 {tools}[GCCcore/11.2.0] atools v1.4.8 w/ Python 2.7.18
  easybuild/easyconfigs/a/atools/atools-1.4.8-GCCcore-11.2.0-Python-2.7.18.eb
Labels: update

#14928 {chem}[foss/2021b] CheMPS2 v1.8.11
  easybuild/easyconfigs/c/CheMPS2/CheMPS2-1.8.11-foss-2021b.eb
Labels: update

#14929 {tools}[GCCcore/11.2.0] deepdiff v5.7.0 w/ Python 3.9.6
  easybuild/easyconfigs/d/deepdiff/deepdiff-5.7.0-GCCcore-11.2.0.eb
Labels: update

#14930 {tools}[intel/2021b] YAXT v0.9.2
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.2-intel-2021b.eb
Labels: update

#14943 {tools}[GCCcore/11.2.0] lftp v4.9.2
  easybuild/easyconfigs/l/lftp/lftp-4.9.2-GCCcore-11.2.0.eb
Labels: update

#14944 {lib}[foss/2021b] xtensor v0.24.0 w/ Python 3.9.6
  easybuild/easyconfigs/x/xtensor/xtensor-0.24.0-foss-2021b.eb
Labels: new

#14935 {tools}[iimpi/2021b] ecCodes v2.24.2
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.24.2-iimpi-2021b.eb
Labels: update

#14945 {bio,vis}[GCCcore/10.3.0,foss/2021a] histolab v0.4.1, openslide-python v1.1.2 w/ Python 3.9.5
  easybuild/easyconfigs/h/histolab/histolab-0.4.1-foss-2021a.eb
  easybuild/easyconfigs/o/openslide-python/openslide-python-1.1.2-GCCcore-10.3.0.eb
Labels: new, update

#14946 {vis}[foss/2021a] torchvision v0.11.3 w/ Python 3.9.5
  easybuild/easyconfigs/t/torchvision/torchvision-0.11.3-foss-2021a.eb
Labels: update

#14948 {tools}[GCCcore/10.3.0] JupyterLab v3.2.8 w/ Python 3.9.5
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.2.8-GCCcore-10.3.0.eb
Labels: update

#14835 {math}[foss/2021b] ScaFaCoS v1.0.1
  easybuild/easyconfigs/s/ScaFaCoS/ScaFaCoS-1.0.1-foss-2021b.eb
Labels: update

#14833 {system}[GCCcore/10.3.0] libdeflate v1.8
  easybuild/easyconfigs/l/libdeflate/libdeflate-1.8-GCCcore-10.3.0.eb
Labels: update

#14774 {vis}[foss/2021b] OpenCV v4.5.5 w/ Python 3.9.6
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.5.5-foss-2021b-contrib.eb
Labels: update

#14933 {lib}[foss/2021a] PyTorch-Lightning v1.5.9 w/ Python 3.9.5 + CUDA 11.3.1
  easybuild/easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-1.5.9-foss-2021a-CUDA-11.3.1.eb
Labels: update

#14947 {vis}[GCCcore/10.3.0,foss/2021a] NiBabel v3.2.1, pydicom v2.2.2 w/ Python 3.9.5
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.2.1-foss-2021a.eb
  easybuild/easyconfigs/p/pydicom/pydicom-2.2.2-GCCcore-10.3.0.eb
Labels: update

#14934 {bio}[foss/2021b] GROMACS v2021.5 w/ Python 3.9.6
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-foss-2021b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5_fix_threads_gpu_Gmxapitests.patch
Labels: update

#14776 {lib,phys}[GCCcore/11.2.0,foss/2021b] GLFW v3.3.4, MuJoCo v2.1.1, mujoco-py v2.1.2.14 w/ Python 3.9.6
  easybuild/easyconfigs/g/GLFW/GLFW-3.3.4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/MuJoCo/MuJoCo-2.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/mujoco-py/mujoco-py-2.1.2.14-foss-2021b.eb
  easybuild/easyconfigs/m/mujoco-py/mujoco-py-2.1.2.14_fix-builder.patch
Labels: new

#14949 {data,lang,tools}[foss/2021a] SimpleITK v2.1.1, ITK v5.2.1 w/ Python 3.9.5
  easybuild/easyconfigs/i/ITK/ITK-5.2.1-foss-2021a.eb
  easybuild/easyconfigs/s/SimpleITK/SimpleITK-2.1.1-allow-lua54-for-code-generation.patch
  easybuild/easyconfigs/s/SimpleITK/SimpleITK-2.1.1-foss-2021a.eb
Labels: update

#14936 {data}[intel/2021b] CDO v1.9.10 and downgrade YAXT from intel/2021b to iimpi/2021b
  easybuild/easyconfigs/c/CDO/CDO-1.9.10-iimpi-2021b.eb
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.2-iimpi-2021b.eb
Labels: bug fix, update

#14861 {lib}[GCC/10.2.0] librsb v1.2.0.10, v1.2.0.11, v1.3.0.0
  easybuild/easyconfigs/l/librsb/librsb-1.2.0.10-GCC-10.2.0.eb
  easybuild/easyconfigs/l/librsb/librsb-1.2.0.11-GCC-10.2.0.eb
  easybuild/easyconfigs/l/librsb/librsb-1.3.0.0-GCC-10.2.0.eb
Labels: new

#14781 {lib}[GCCcore/11.2.0] Flask v2.0.2 w/ Python 3.9.6
  easybuild/easyconfigs/f/Flask/Flask-2.0.2-GCCcore-11.2.0.eb
Labels: update

#14780 {lib}[GCCcore/10.3.0,GCCcore/11.2.0] dm-tree v0.1.6 w/ Python 3.9.5 + 3.9.6
  easybuild/easyconfigs/d/dm-tree/dm-tree-0.1.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/d/dm-tree/dm-tree-0.1.6-GCCcore-11.2.0.eb
Labels: update

#14831 {bio}[foss/2021b] Qualimap v2.2.1
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2021b-R-4.1.2.eb
Labels: update

#14837 {lib}[GCCcore/11.2.0] OpenCensus-python v0.8.0 w/ Python 3.9.6
  easybuild/easyconfigs/o/OpenCensus-python/OpenCensus-python-0.8.0-GCCcore-11.2.0.eb
Labels: new

#14825 {bio}[GCC/10.3.0] fastp 0.23.2
  easybuild/easyconfigs/f/fastp/fastp-0.23.2-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libdeflate/libdeflate-1.7-GCCcore-10.3.0.eb
Labels: update

#14843 {numlib,phys}[GCC/11.2.0] CLHEP v2.4.4.0, Geant4 v10.7.1
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.4.0-GCC-11.2.0.eb
  easybuild/easyconfigs/g/Geant4/Geant4-10.7.1-GCC-11.2.0.eb
Labels: update

#14753 {tools}[foss/2021b] Arcade-Learning-Environment v0.7.3 w/ Python 3.9.6
  easybuild/easyconfigs/a/Arcade-Learning-Environment/Arcade-Learning-Environment-0.7.3-foss-2021b.eb
Labels: new

#14953 {data}[foss/2021a] deepmedic v0.8.2 w/ Python 3.9.5
  easybuild/easyconfigs/d/deepmedic/deepmedic-0.8.2-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/d/deepmedic/deepmedic-0.8.2-foss-2021a.eb
Labels: new

#14782 {tools}[GCCcore/11.2.0] gpustat v1.0.0b1 w/ Python 3.9.6
  easybuild/easyconfigs/g/gpustat/gpustat-1.0.0b1-GCCcore-11.2.0.eb
Labels: update

#14959 {tools}[system/system] Nextflow v21.10.6
  easybuild/easyconfigs/n/Nextflow/Nextflow-21.10.6.eb
Labels: update

#14960 {bio}[GCC/11.2.0] Pysam v0.18.0 w/ Python 3.9.6
  easybuild/easyconfigs/p/Pysam/Pysam-0.18.0-GCC-11.2.0.eb
Labels: update

#14816 {bio,lib}[GCC/11.2.0,GCCcore/11.2.0] MethylDackel v0.6.1, libBigWig v0.4.6
  easybuild/easyconfigs/l/libBigWig/libBigWig-0.4.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/MethylDackel/MethylDackel-0.6.1-GCC-11.2.0.eb
  easybuild/easyconfigs/m/MethylDackel/MethylDackel_fix_version.h_target.patch
Labels: update

#14799 {bio}[gompi/2021b] RAxML v8.2.12
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-gompi-2021b-hybrid-avx2.eb
Labels: update

#14787 {bio}[GCCcore/11.2.0] Racon v1.5.0
  easybuild/easyconfigs/r/Racon/Racon-1.5.0-GCCcore-11.2.0.eb
Labels: update

#14795 {system}[system/system] CUDAcore v11.5.1
  easybuild/easyconfigs/c/CUDAcore/CUDAcore-11.5.1.eb
Labels: update

#14952 {vis}[foss/2021a] rising v0.2.2 w/ Python 3.9.5
  easybuild/easyconfigs/r/rising/rising-0.2.2-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/r/rising/rising-0.2.2-foss-2021a.eb
Labels: new

#14788 {bio}[GCC/11.2.0] Iris v1.0.5
  easybuild/easyconfigs/i/Iris/Iris-1.0.5-GCC-11.2.0-Java-15.eb
Labels: new

#14789 {bio}[GCC/11.2.0] Jasmine v1.1.4
  easybuild/easyconfigs/j/Jasmine/Jasmine-1.1.4-GCC-11.2.0-Java-15.eb
Labels: new

#14532 {bio,lib}[foss/2021a] mapDamage v2.2.1, inline v0.3.19, seqtk v1.3, ... w/ Python 3.9.5
  easybuild/easyconfigs/m/mapDamage/mapDamage-2.2.1-foss-2021a-R-4.1.0.eb
  easybuild/easyconfigs/m/mapDamage/mapDamage-2.2.1_use-external-seqtk.patch
  easybuild/easyconfigs/s/seqtk/seqtk-1.3-GCC-10.3.0.eb
Labels: new, update

#14823 {lib}[GCCcore/11.2.0] Mono v6.12.0.122, libgdiplus v6.1, libexif v0.6.24 w/ Python 3.9.6
  easybuild/easyconfigs/l/libexif/libexif-0.6.24-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libgdiplus/libgdiplus-6.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libgdiplus/libgdiplus-6.1_use-external-googletest.patch
  easybuild/easyconfigs/m/Mono/Mono-6.12.0.122-GCCcore-11.2.0.eb
Labels: new, update

#14862 {data,lib}[GCCcore/11.2.0,foss/2021b] CFITSIO v3.49, ROOT v6.24.06 w/ Python 3.9.6
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.49-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.24.06-foss-2021b.eb
Labels: update

#14961 consistently apply patch for mapDamage 2.2.1 to use external seqtk
  easybuild/easyconfigs/m/mapDamage/mapDamage-2.2.1-foss-2020b-R-4.0.4.eb
  easybuild/easyconfigs/m/mapDamage/mapDamage-2.2.1-foss-2021b.eb
Labels: bug fix

#14962 fix typo in templated source URL in RcppGSL 0.3.8 easyconfig: $(name)s should be %(name)s
  easybuild/easyconfigs/r/RcppGSL/RcppGSL-0.3.8-foss-2020b-R-4.0.4.eb
Labels: bug fix

#14817 {bio}[foss/2021b] SqueezeMeta v1.5.0 w/ Python 3.9.6
  easybuild/easyconfigs/s/SqueezeMeta/SqueezeMeta-1.5.0-foss-2021b.eb
Labels: update

#14869 {cae}[foss/2021b] GATE v9.1
  easybuild/easyconfigs/g/GATE/GATE-9.1-foss-2021b.eb
Labels: update

#14824 {bio}[GCCcore/11.2.0] MaxQuant v2.0.3.0
  easybuild/easyconfigs/m/MaxQuant/MaxQuant-2.0.3.0-GCCcore-11.2.0.eb
Labels: update

#14766 {bio}[intel/2021b] Biopython v1.79 w/ Python 3.9.6
  easybuild/easyconfigs/b/Biopython/Biopython-1.79-intel-2021b.eb
Labels: update

#14767 {tools}[intel/2021b] networkx v2.6.3 w/ Python 3.9.6
  easybuild/easyconfigs/n/networkx/networkx-2.6.3-intel-2021b.eb
Labels: update

#14773 {bio}[GCC/11.2.0] Pindel v0.2.5b9-20170508
  easybuild/easyconfigs/p/Pindel/Pindel-0.2.5b9-20170508-GCC-11.2.0.eb
Labels: update

#14786 {bio}[GCC/11.2.0] SURVIVOR v1.0.7-19-ged1ca51
  easybuild/easyconfigs/s/SURVIVOR/SURVIVOR-1.0.7-19-ged1ca51-GCC-11.2.0.eb
Labels: new

#14760 {bio}[GCCcore/11.2.0] MUSCLE v5.1
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-5.1-GCCcore-11.2.0.eb
Labels: update

#14747 {bio}[system/system] MEGA v11.0.10
  easybuild/easyconfigs/m/MEGA/MEGA-11.0.10.eb
Labels: update

#14749 {tools}[GCCcore/11.2.0] Emacs v27.2
  easybuild/easyconfigs/e/Emacs/Emacs-27.2-GCCcore-11.2.0.eb
Labels: update

#14764 {numlib,phys}[GCC/11.2.0] Geant4 v11.0.0, CLHEP v2.4.5.1
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.5.1-GCC-11.2.0.eb
  easybuild/easyconfigs/g/Geant4/Geant4-11.0.0-GCC-11.2.0.eb
Labels: update

#14739 {phys}[intel/2021b] FDS v6.7.7
  easybuild/easyconfigs/f/FDS/FDS-6.7.7-intel-2021b.eb
Labels: update

#14723 {phys}[ GCC/10.3.0,GCC/11.2.0,intel-compilers/2021.2.0,intel-compilers/2021.4.0] libpsml v1.1.10, xmlf90 v1.5.4
  easybuild/easyconfigs/l/libpsml/libpsml-1.1.10-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libpsml/libpsml-1.1.10-GCC-11.2.0.eb
  easybuild/easyconfigs/l/libpsml/libpsml-1.1.10-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/l/libpsml/libpsml-1.1.10-intel-compilers-2021.4.0.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.4-GCC-10.3.0.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.4-GCC-11.2.0.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.4-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.4-intel-compilers-2021.4.0.eb
Labels: update

#14686 {phys}[foss/2021a,foss/2021b,intel/2021a,intel/2021b] libGridXC v0.9.6
  easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-gompi-2021a.eb
  easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-gompi-2021b.eb
  easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-iimpi-2021a.eb
  easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-iimpi-2021b.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-11.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-intel-compilers-2021.4.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#14771 {devel}[GCCcore/10.3.0] FoBiS v3.0.5 w/ Python 3.9.5
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.10.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/f/FORD/FORD-6.1.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/f/FoBiS/FoBiS-3.0.5-GCCcore-10.3.0.eb
Labels: new, update

#14420 {phys}[Cray*,foss/2019b,intel/2019b,iomkl/2019b] CASTEP v21.1.1
  easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-CrayCCE-19.06.eb
  easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-CrayGNU-19.06.eb
  easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-foss-2019b.eb
  easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-intel-2019b.eb
  easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-iomkl-2019b.eb
Labels: new

#14762 {bio}[system/system] picard v2.26.10
  easybuild/easyconfigs/p/picard/picard-2.26.10-Java-15.eb
Labels: update

#14965 fix location of lock file in mujoco-py v2.1.2.14
  easybuild/easyconfigs/m/mujoco-py/mujoco-py-2.1.2.14-foss-2021b.eb
  easybuild/easyconfigs/m/mujoco-py/mujoco-py-2.1.2.14_fix-builder-lib-paths.patch
  easybuild/easyconfigs/m/mujoco-py/mujoco-py-2.1.2.14_fix-builder-lockfile.patch
Labels: bug fix

#14954 fix download URL in UDUNITS v2.2.28 easyconfigs
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28-GCCcore-10.3.0.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28-GCCcore-11.2.0.eb
Labels: bug fix

#14979 {tools}[dummy/dummy] EasyBuild v4.5.3
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.3.eb
Labels: update

#14975 Add config Clang-Python-bindings-13.0.1-GCCcore-11.2.0
  easybuild/easyconfigs/c/Clang-Python-bindings/Clang-Python-bindings-13.0.1-GCCcore-11.2.0.eb
Labels: update

#14982 sync with main + bump version to 4.5.4dev
  RELEASE_NOTES
  setup.py
Labels: update

#14981 {lang}[system/system] Julia v1.7.2
  easybuild/easyconfigs/j/Julia/Julia-1.7.2-linux-x86_64.eb
Labels: update

#14964 {math}[foss/2021b,intel/2021b] ELPA v2021.11.001
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-foss-2021b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-intel-2021b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001_fix_hardcoded_perl_path.patch
Labels: update

#14768 {bio}[foss/2021b,intel/2021b] MDAnalysis v2.0.0 w/ Python 3.9.6
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-2.0.0-foss-2021b.eb
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-2.0.0-intel-2021b.eb
Labels: update

#14796 {perf}[system/system] IntelClusterChecker v2021.5.0
  easybuild/easyconfigs/i/IntelClusterChecker/IntelClusterChecker-2021.5.0.eb
Labels: update

#14977 {math}[foss/2021a] numexpr v2.8.1 w/ Python 3.9.5
  easybuild/easyconfigs/n/numexpr/numexpr-2.8.1-foss-2021a.eb
Labels: update

#13388 {bio}[foss/2020b] MDAnalysis v1.1.1 w/ Python 3.8.6
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-1.1.1-foss-2020b.eb
Labels: update

#14988 {math}[intel/2021a] numexpr v2.8.1 w/ Python 3.9.5
  easybuild/easyconfigs/n/numexpr/numexpr-2.8.1-intel-2021a.eb
Labels: update

#14970 {lib}[foss/2021a] TensorFlow v2.4.4 w/ Python 3.9.5
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4-foss-2021a.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4_fix-assertion-bijector-test.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4_fix-compatibility-with-numpy-1.20.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4_fix-compatibility-with-protobuf-3.17.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4_relax-required-versions.patch
Labels: update

#14987 add additional valid checksum for norm 1.0-9.5 extension in R 4.1.0 and 4.1.2 easyconfigs
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: bug fix

#14989 avoid pollution in the tmp directory when running the AlphaFold tests
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.1.1-fosscuda-2020b.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.1_fix-alphafold-tests.patch
Labels: bug fix

#14858 {lib}[foss/2021a] XGBoost v1.5.0 w/ Python 3.9.5
  easybuild/easyconfigs/x/XGBoost/XGBoost-1.5.0-foss-2021a.eb
Labels: update

#14813 {bio,data,math}[foss/2021b] Bambi v0.7.1, netcdf4-python v1.5.7, ArviZ v0.11.4 w/ Python 3.9.6, PyMC3 v3.11.1, Theano v1.1.2
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.11.4-foss-2021b.eb
  easybuild/easyconfigs/b/Bambi/Bambi-0.7.1-foss-2021b.eb
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.5.7-foss-2021b.eb
  easybuild/easyconfigs/p/PyMC3/PyMC3-3.11.1-foss-2021b.eb
  easybuild/easyconfigs/t/Theano/Theano-1.1.2-foss-2021b-PyMC.eb
Labels: new, update

#14996 {chem}[gompi/2021b] ORCA v5.0.3
  easybuild/easyconfigs/o/ORCA/ORCA-5.0.3-gompi-2021b.eb
Labels: update

#14997 {devel}[foss/2021a,foss/2021b] NLTK v3.6.7, NLTK v3.7 w/ Python 3.9.5 + 3.9.6
  easybuild/easyconfigs/n/NLTK/NLTK-3.6.7-foss-2021a.eb
  easybuild/easyconfigs/n/NLTK/NLTK-3.7-foss-2021b.eb
Labels: update
