Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-04, with the labels that each got.

#15229 Add easyconfig for Julia 1.6.6
  easybuild/easyconfigs/j/Julia/Julia-1.6.6-linux-x86_64.eb
Labels: update

#15227 {devel}[system] CMake 3.18.4
  easybuild/easyconfigs/c/CMake/CMake-3.18.4.eb
Labels: enhancement, change

#15260 {bio}[GCC/11.2.0] SAMtools v1.15.1
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.15.1-GCC-11.2.0.eb
Labels: update

#15259 {lang}[GCCcore/8.2.0,GCCcore/8.3.0,GCCcore/9.3.0] Python v2.7.15, Python v2.7.16, Python v2.7.18
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-9.3.0-bare.eb
Labels: update

#15265 {bio,devel}[GCC/11.2.0] Cufflinks v20190706, Boost v1.75.0
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-GCC-11.2.0.eb
  easybuild/easyconfigs/c/Cufflinks/Cufflinks-20190706-GCC-11.2.0.eb
Labels: update

#15211 use x.py to boostrap Rust so that build options are properly passed through
  easybuild/easyconfigs/r/Rust/Rust-1.35.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.37.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-7.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.42.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.54.0-GCCcore-11.2.0.eb
Labels: bug fix

#15268 {vis}[GCCcore/9.3.0] XGrafix v2.41
  easybuild/easyconfigs/x/XGrafix/XGrafix-2.41-GCCcore-9.3.0.eb
Labels: new

#15261 {bio}[GCC/11.2.0] StringTie v2.2.1
  easybuild/easyconfigs/s/StringTie/StringTie-2.2.1-GCC-11.2.0.eb
Labels: update

#15232 {chem}[iccifort/2020.4.304] Bader v1.04
  easybuild/easyconfigs/b/Bader/Bader-1.04-iccifort-2020.4.304.eb
Labels: update

#15236 {tools}[GCCcore/11.2.0] i7z v0.27.2
  easybuild/easyconfigs/i/i7z/i7z-0.27.2_fix_gcc-10.patch
  easybuild/easyconfigs/i/i7z/i7z-20131012-GCCcore-11.2.0.eb
Labels: new

#15234 {math}[intel/2020b] EigenExa v2.11
  easybuild/easyconfigs/e/EigenExa/EigenExa-2.11-intel-2020b.eb
Labels: new

#15283 {bio}[gompi/2021b] Kraken2 v2.1.2
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.2-gompi-2021b.eb
Labels: update

#15221 {bio}[GCCcore/11.2.0] snpEff v5.0e w/ Python 3.9.6
  easybuild/easyconfigs/s/snpEff/snpEff-5.0e-GCCcore-11.2.0-Java-11.eb
Labels: update

#15219 {lib}[GCCcore/11.2.0] vt v0.57721, TCLAP v1.2.5, LIBSVM v3.25
  easybuild/easyconfigs/l/LIBSVM/LIBSVM-3.25-GCCcore-11.2.0.eb
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.5-GCCcore-11.2.0.eb
  easybuild/easyconfigs/v/vt/vt-0.57721-GCC-11.2.0.eb
Labels: update

#15217 {bio}[GCC/11.2.0,GCCcore/11.2.0] SeqLib v1.2.0, fermi-lite v20190320, SSW v1.1
  easybuild/easyconfigs/f/fermi-lite/fermi-lite-20190320-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/SSW/SSW-1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-11.2.0.eb
Labels: update

#15216 add R dependency to vcflib 1.0.3, and move to foss
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.3-foss-2021b-R-4.1.2.eb
Labels: update, change

#15218 {bio}[foss/2021b] freebayes v1.3.6 w/ Python 3.9.6
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.6-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.6_find-external-libs.patch
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.6_install-libs-headers.patch
Labels: update

#15220 {bio}[GCCcore/11.2.0] snippy v4.6.0, any2fasta v0.4.2, Check v0.15.2, ...
  easybuild/easyconfigs/a/any2fasta/any2fasta-0.4.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/snippy/snippy-4.6.0-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/s/snp-sites/snp-sites-2.5.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/w/wgsim/wgsim-20111017-GCC-11.2.0.eb
Labels: update

#15295 {bio}[foss/2021b] RSeQC v4.0.0, bx-python v0.8.13 w/ Python 3.9.6
  easybuild/easyconfigs/b/bx-python/bx-python-0.8.13-foss-2021b.eb
  easybuild/easyconfigs/r/RSeQC/RSeQC-4.0.0-foss-2021b.eb
Labels: update

#15262 {phys,vis}[GCC/11.2.0,GCCcore/11.2.0] ARGoS v3.0.0-beta59, FreeImage v3.18.0
  easybuild/easyconfigs/a/ARGoS/ARGoS-3.0.0-beta59-GCC-11.2.0.eb
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-11.2.0.eb
Labels: update

#15135 {perf}[gompi/2021b] IMB v2021.3
  easybuild/easyconfigs/i/IMB/IMB-2021.3-gompi-2021b.eb
Labels: update

#15286 {bio}[GCC/11.2.0] segemehl v0.3.4
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-11.2.0.eb
Labels: update

#15282 {bio}[foss/2021b] ViennaRNA v2.5.0 w/ Python 3.9.6
  easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.5.0-foss-2021b.eb
Labels: update

#15278 {bio}[GCC/11.2.0] bioawk v1.0
  easybuild/easyconfigs/b/bioawk/bioawk-1.0-GCC-11.2.0.eb
Labels: update

#15281 {bio}[gompi/2021b] crb-blast v0.6.9
  easybuild/easyconfigs/c/crb-blast/crb-blast-0.6.9-gompi-2021b.eb
Labels: update

#15287 {bio}[GCC/11.2.0] SpaceRanger v1.3.1
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.1-GCC-11.2.0.eb
Labels: update

#15284 {bio}[foss/2021b] QUAST v5.0.2 w/ Python 3.9.6
  easybuild/easyconfigs/q/QUAST/QUAST-5.0.2-foss-2021b.eb
Labels: update

#15298 {bio}[GCCcore/11.2.0] TRF v4.09.1
  easybuild/easyconfigs/t/TRF/TRF-4.09.1-GCCcore-11.2.0.eb
Labels: update

#15271 {bio}[foss/2020b] MIRA v5.0rc2
  easybuild/easyconfigs/m/MIRA/MIRA-5.0rc2-foss-2020b.eb
Labels: update

#15299 {bio}[system/system] VarScan v2.4.4
  easybuild/easyconfigs/v/VarScan/VarScan-2.4.4-Java-11.eb
Labels: update

#15300 {bio}[GCC/11.2.0] NextGenMap v0.5.5
  easybuild/easyconfigs/n/NextGenMap/NextGenMap-0.5.5-GCC-11.2.0.eb
Labels: update

#15306 {bio}[foss/2021b] HTSeq v0.11.3 w/ Python 3.9.6
  easybuild/easyconfigs/h/HTSeq/HTSeq-0.11.3-foss-2021b.eb
Labels: update

#15307 {bio}[GCC/11.2.0] fumi_tools v0.18.2 w/ Python 3.9.6
  easybuild/easyconfigs/f/fumi_tools/fumi_tools-0.18.2-GCC-11.2.0.eb
Labels: update

#15308 {bio}[GCC/11.2.0] FASTX-Toolkit v0.0.14
  easybuild/easyconfigs/f/FASTX-Toolkit/FASTX-Toolkit-0.0.14-GCC-11.2.0.eb
Labels: update

#15309 {bio}[GCC/11.2.0] fastq-tools v0.8.3
  easybuild/easyconfigs/f/fastq-tools/fastq-tools-0.8.3-GCC-11.2.0.eb
Labels: update

#15291 {data,lib,vis}[GCCcore/11.2.0] OpenSceneGraph v3.6.5, librsvg v2.52.8, DCMTK v3.6.6
  easybuild/easyconfigs/d/DCMTK/DCMTK-3.6.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/librsvg/librsvg-2.52.8-GCCcore-11.2.0.eb
  easybuild/easyconfigs/o/OpenSceneGraph/OpenSceneGraph-3.6.5-foss-2021b.eb
Labels: update

#15296 {tools}[GCC/11.2.0] ncdu v1.16
  easybuild/easyconfigs/n/ncdu/ncdu-1.16-GCC-11.2.0.eb
Labels: update

#15277 {math}[GCC/11.2.0] Arb v2.22.1, FLINT v2.8.4
  easybuild/easyconfigs/a/Arb/Arb-2.22.1-GCC-11.2.0.eb
  easybuild/easyconfigs/f/FLINT/FLINT-2.8.4-GCC-11.2.0.eb
Labels: update

#15317 {bio}[intel/2021b] GTDB-Tk v2.0.0, HMMER v3.3.2, FastANI v1.33, FastTree v2.1.11 w/ Python 3.9.6
  easybuild/easyconfigs/f/FastANI/FastANI-1.33-intel-compilers-2021.4.0.eb
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.11-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-2.0.0-intel-2021b.eb
  easybuild/easyconfigs/h/HMMER/HMMER-3.3.2-iimpi-2021b.eb
  easybuild/easyconfigs/m/Mash/Mash-2.3-intel-compilers-2021.4.0.eb
Labels: update

#15324 define $HHLIB as path to HH-suite installation directory, required by Perl scripts
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-gompi-2020b.eb
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-gompi-2021a.eb
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-gompic-2020b.eb
Labels: bug fix

#15316 Remove pkg-config use from SeqLib configure patch
  easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-10.2.0.eb
  easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-11.2.0.eb
  easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-9.3.0.eb
  easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0_use-external-deps.patch
Labels: bug fix

#15325 {bio}[GCC/11.2.0] TreeMix v1.13
  easybuild/easyconfigs/t/TreeMix/TreeMix-1.13-GCC-11.2.0.eb
Labels: update

#15290 {vis}[foss/2021b] Grace v5.1.25
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2021b.eb
Labels: update

#15315 {bio}[foss/2021a] GTDB-Tk v2.0.0 w/ Python 3.9.5
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-2.0.0-foss-2021a.eb
Labels: update

#15326 {math}[intel/2021b] SPOTPY v1.5.14 w/ Python 3.9.6
  easybuild/easyconfigs/s/SPOTPY/SPOTPY-1.5.14-intel-2021b.eb
Labels: new

#15322 {devel}[GCC/11.2.0] texlive v20220321
  easybuild/easyconfigs/t/texlive/texlive-20220321-GCC-11.2.0.eb
Labels: update

#15323 {tools} YAXT: URL updated to fallback as original URL for source code is broken right now
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.0-gompi-2020b.eb
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.1-gompi-2021a.eb
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.2-iimpi-2021b.eb
Labels: bug fix

#15304 {bio}[system/system] SeqKit v2.2.0
  easybuild/easyconfigs/s/SeqKit/SeqKit-2.2.0.eb
Labels: update

#15314 {bio}[GCC/10.3.0] panito v0.0.1
  easybuild/easyconfigs/p/panito/panito-0.0.1-GCC-10.3.0.eb
Labels: new

#15289 {numlib}[GCC/11.2.0] LAPACK v3.10.1
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.10.1-GCC-11.2.0.eb
Labels: update

#15332 {bio}[GCC/10.3.0] Fastaq v3.17.0, SAMtools v0.1.19 w/ Python 3.9.5
  easybuild/easyconfigs/f/Fastaq/Fastaq-3.17.0-GCC-10.3.0.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-0.1.19-GCC-10.3.0.eb
Labels: new, update

#15340 {vis}[GCCcore/10.3.0] Pillow v9.1.0 w/ Python 3.9.5
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.0-GCCcore-10.3.0.eb
Labels: update

#15334 {bio}[GCCcore/10.3.0] Roary v3.13.0, Kraken v1.1.1, MCL v14.137
  easybuild/easyconfigs/k/Kraken/Kraken-1.1.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/MCL/MCL-14.137-GCCcore-10.3.0.eb
  easybuild/easyconfigs/r/Roary/Roary-3.13.0-foss-2021a.eb
Labels: update

#15065 {bio}[foss/2021b] SCGid v0.9b0
  easybuild/easyconfigs/s/SCGid/SCGid-0.9-fixPrintToPython3.patch
  easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
  easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-initEdit.patch
Labels: new

#15341 {bio}[system/system] IGV v2.12.3
  easybuild/easyconfigs/i/IGV/IGV-2.12.3-Java-11.eb
Labels: update

#15350 {bio}[foss/2021b] FreeBarcodes v3.0.a5 w/ Python 3.9.6
  easybuild/easyconfigs/f/FreeBarcodes/FreeBarcodes-3.0.a5-foss-2021b.eb
Labels: new

#15347 also build BLIS backend for FlexiBLAS v3.0.4 with GCC/10.3.0
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.0.4-GCC-10.3.0.eb
Labels: enhancement

#15311 {toolchain} GCC 11.3.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.38-GCCcore-11.3.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.38.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GCC/GCC-11.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.3.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12_fix-CC-logic-in-configure.patch
Labels: update

#15320 update source URL for isl in GCCcore easyconfigs
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-5.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-5.5.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-6.5.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-7.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-7.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-7.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-7.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-8.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.4.0.eb
Labels: bug fix

#15342 {bio}[foss/2021b] MultiQC v1.12 w/ Python 3.9.6
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.12-foss-2021b.eb
Labels: update

#15354 {bio}[foss/2021b] breseq v0.36.1
  easybuild/easyconfigs/b/breseq/breseq-0.36.1-foss-2021b.eb
Labels: update

#15360 add missing parallel dependency for prokka 1.14.5
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019a.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019b.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2020b.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2021a.eb
Labels: bug fix

#8888 {bio,numlib}[iccifort/2019.1.144-GCC-8.2.0-2.31.1,iimpi/2019a] beagle-lib v3.1.2, MrBayes v3.2.7a
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.1.2-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.7a-iimpi-2019a.eb
Labels: update

#15361 {devel}[foss/2021b] Spark v3.2.1 w/ Python 3.9.6
  easybuild/easyconfigs/s/Spark/Spark-3.2.1-foss-2021b.eb
Labels: update

#15368 {devel}[system/system] ReFrame v3.11.0
  easybuild/easyconfigs/r/ReFrame/ReFrame-3.11.0.eb
Labels: update

#15365 {compiler}[system/system] Go v1.18.1
  easybuild/easyconfigs/g/Go/Go-1.18.1.eb
Labels: update

#15367 {vis}[system/system] Blender v3.1.2
  easybuild/easyconfigs/b/Blender/Blender-3.1.2-linux-x64.eb
Labels: update

#15371 {bio}[gompi/2020b] parallel-fastq-dump v0.6.7 w/ Python 3.8.6
  easybuild/easyconfigs/p/parallel-fastq-dump/parallel-fastq-dump-0.6.7-gompi-2020b.eb
Labels: update

#15313 pkg-config-0.29.2 easyconfig: "find /usr" should not descend into other filesystems
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2.eb
Labels: change

#15318 {tools}[gompi/2021b] YAXT v0.9.2.1
  easybuild/easyconfigs/y/YAXT/YAXT-0.9.2.1-gompi-2021b.eb
Labels: update

#15352 {lib}[GCC/11.2.0] FoX v4.1.2
  easybuild/easyconfigs/f/FoX/FoX-4.1.2-GCC-11.2.0.eb
Labels: update

#15355 {lang}[GCCcore/11.2.0] Rust v1.56.0
  easybuild/easyconfigs/r/Rust/Rust-1.56.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.56_sysroot-fix-interpreter.patch
Labels: update

#15357 {tools}[system/system] Nextflow v22.04.0
  easybuild/easyconfigs/n/Nextflow/Nextflow-22.04.0.eb
Labels: update

#15369 {tools}[GCCcore/11.3.0] Perl v5.34.1, expat v2.4.8, ncurses v6.3, ...
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-11.3.0.eb
  easybuild/easyconfigs/e/expat/expat-2.4.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/groff/groff-1.22.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.34.1-GCCcore-11.3.0.eb
Labels: update

#15381 add missing tbl2asn dependency for prokka 1.14.5
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019a.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2019b.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2020b.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2021a.eb
  easybuild/easyconfigs/t/tbl2asn/tbl2asn-20220427-linux64.eb
Labels: bug fix

#15393 add Hmsc extension to R v4.1.2 easyconfig
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: enhancement

#15383 {devel}[GCCcore/11.3.0] Autotools v20220317, Autoconf v2.71, Automake v1.16.5, libtool v2.4.7
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20220317-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.7-GCCcore-11.3.0.eb
Labels: update

#15386 {tools}[GCCcore/11.3.0] bzip2 v1.0.8, CMake v3.23.1, cURL v7.83.0, libarchive v3.6.1, XZ v5.2.5
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.23.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/cURL/cURL-7.83.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.6.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-11.3.0.eb
Labels: update

#15387 {system}[GCCcore/11.3.0] OpenSSL v1.1.1n
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.1n-GCCcore-11.3.0.eb
Labels: update

#15394 {math}[GCCcore/11.3.0] GMP v6.2.1
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-GCCcore-11.3.0.eb
Labels: update

#15392 {tools}[GCCcore/11.3.0] git v2.36.0
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/git/git-2.36.0-GCCcore-11.3.0-nodocs.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.9.13-GCCcore-11.3.0.eb
Labels: update

#15389 {lib}[GCCcore/11.3.0] UnZip v6.0, Tcl v8.6.12, SQLite v3.38.3, libffi v3.4.2
  easybuild/easyconfigs/l/libffi/libffi-3.4.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.38.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-11.3.0.eb
Labels: update

#15390 {lang}[GCCcore/11.3.0] Python v3.10.4 (bare)
  easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0-bare.eb
Labels: update

#15372 {perf}[system/system] AMD-uProf v3.5.671
  easybuild/easyconfigs/a/AMD-uProf/AMD-uProf-3.5.671.eb
Labels: update

#15375 {bio}[GCC/11.2.0] GMAP-GSNAP-2021-21-17
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2021-21-17-GCC-11.2.0.eb
Labels: update

#15343 {perf}[gompi/2021a] OSU-Micro-Benchmarks v5.9
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.9-gompi-2021a-CUDA-11.3.1.eb
Labels: update

#15395 {tools}[GCC/11.2.0] libheif v1.12.0, libde265 v1.0.8
  easybuild/easyconfigs/l/libde265/libde265-1.0.8-GCC-11.2.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.12.0-GCC-11.2.0.eb
Labels: new
