Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-05, with the labels that each got.

#15391 {lang}[GCCcore/11.3.0] Rust v1.60.0
  easybuild/easyconfigs/r/Rust/Rust-1.60.0-GCCcore-11.3.0.eb
Labels: update

#15385 {bio}[foss/2021b] purge_dups v1.2.5 w/ Python 3.9.6
  easybuild/easyconfigs/p/purge_dups/purge_dups-1.2.5-foss-2021b.eb
Labels: new

#15400 {system}[GCCcore/11.3.0] hwloc v2.7.1, numactl v2.0.14, libpciaccess v0.16, ...
  easybuild/easyconfigs/h/hwloc/hwloc-2.7.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.16-GCCcore-11.3.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.14-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.3-GCCcore-11.3.0.eb
Labels: update

#15399 {numlib}[GCC/11.3.0] OpenBLAS v0.3.20, FlexiBLAS v3.1.3, BLIS v0.9.0
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0-GCC-11.3.0.eb
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.1.3-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.3.0.eb
Labels: update

#15377 {bio}[gompi/2021b] MEME v5.4.1 w/ Python 3.9.6
  easybuild/easyconfigs/m/MEME/MEME-5.4.1-gompi-2021b.eb
Labels: update

#15405 add DNABarcodes to R-bundle-Bioconductor 3.14 easyconfig
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.14-foss-2021b-R-4.1.2.eb
Labels: enhancement

#15378 {bio}[GCC/11.2.0] ntCard-1.2.1
  easybuild/easyconfigs/n/ntCard/ntCard-1.2.1-GCC-11.2.0.eb
Labels: update

#15379 {bio}[GCC/11.2.0] RNA-Bloom-1.4.3
  easybuild/easyconfigs/r/RNA-Bloom/RNA-Bloom-1.4.3-GCC-11.2.0.eb
Labels: update

#15403 {lib}[GCC/10.2.0] librsb v1.3.0.1
  easybuild/easyconfigs/l/librsb/librsb-1.3.0.1-GCC-10.2.0.eb
Labels: update

#15384 {devel}[GCC/11.2.0] Boost v1.79.0
  easybuild/easyconfigs/b/Boost/Boost-1.79.0-GCC-11.2.0.eb
Labels: update

#15374 {geo}[foss/2020a] xESMF v0.3.0, ESMPy v8.0.1 w/ Python 3.8.2
  easybuild/easyconfigs/e/ESMPy/ESMPy-8.0.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/x/xESMF/xESMF-0.3.0-foss-2020a-Python-3.8.2.eb
Labels: update

#15364 {math}[system/system] MCR vR2022a.1
  easybuild/easyconfigs/m/MCR/MCR-R2022a.1.eb
Labels: update

#15363 {devel}[system/system] Spack v0.17.2
  easybuild/easyconfigs/s/Spack/Spack-0.17.2.eb
Labels: update

#15397 {tools}[GCC/11.2.0] hector v2.5.0
  easybuild/easyconfigs/h/hector/hector-2.5.0-GCC-11.2.0.eb
Labels: new

#15353 {data}[foss/2021b] SUMO v1.12.0 w/ Python 3.9.6
  easybuild/easyconfigs/s/SUMO/SUMO-1.12.0-foss-2021b.eb
Labels: update

#15328 {tools}[foss/2020b,intel/2020b] ToFu v1.5.0 w/ Python 3.8.6
  easybuild/easyconfigs/t/ToFu/ToFu-1.5.0-foss-2020b.eb
  easybuild/easyconfigs/t/ToFu/ToFu-1.5.0-intel-2020b.eb
Labels: update

#15404 {lang}[GCCcore/11.3.0] Python v3.10.4
  easybuild/easyconfigs/p/Python/Python-3.10-bist-1.3.6-compatibility.patch
  easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb
Labels: update

#15413 {lib}[GCCcore/11.3.0] Z3 v4.8.16, zstd v1.5.2, gzip v1.12, ...
  easybuild/easyconfigs/e/elfutils/elfutils-0.187-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/gzip/gzip-1.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/gzip/gzip-1.12_fix-gnulib-strndup-redeclaration.patch
  easybuild/easyconfigs/l/lz4/lz4-1.9.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/Z3/Z3-4.8.16-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.5.2-GCCcore-11.3.0.eb
Labels: update

#15376 {bio}[foss/2021a] rnaQUAST v2.2.2 w/ Python 3.9.6
  easybuild/easyconfigs/r/rnaQUAST/rnaQUAST-2.2.2-foss-2021b.eb
Labels: update

#15273 {tools}[GCCcore/10.3.0] coverage v5.5 w/ Python 3.9.5
  easybuild/easyconfigs/c/coverage/coverage-5.5-GCCcore-10.3.0.eb
Labels: update

#15274 {geo}[foss/2021a] geopandas v0.10.2 w/ Python 3.9.5
  easybuild/easyconfigs/g/geopandas/geopandas-0.10.2-foss-2021a.eb
Labels: update

#15362 {lib}[GCCcore/11.2.0] libedit v20210910
  easybuild/easyconfigs/l/libedit/libedit-20210910-GCCcore-11.2.0.eb
Labels: update

#15235 {math}[intel/2020b] ELPA v2021.05.002
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-intel-2020b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002_fix_hardcoded_perl_path.patch
Labels: update

#15238 {math}[intel/2020b] NTPoly v2.7.1
  easybuild/easyconfigs/n/NTPoly/NTPoly-2.7.1-intel-2020b.eb
Labels: update

#15427 {bio,lang,lib,system}[GCCcore/11.3.0] fastp v0.23.2, ISA-L v2.30.0, libdeflate v1.10, ...
  easybuild/easyconfigs/f/fastp/fastp-0.23.2-GCC-11.3.0.eb
  easybuild/easyconfigs/i/ISA-L/ISA-L-2.30.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libdeflate/libdeflate-1.10-GCCcore-11.3.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.15.05-GCCcore-11.3.0.eb
Labels: update

#15429 {tools}[GCCcore/11.3.0] Meson v0.62.1, Ninja v1.10.2 w/ Python 3.10.4
  easybuild/easyconfigs/m/Meson/Meson-0.62.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-GCCcore-11.3.0.eb
Labels: update

#15430 {devel,vis}[GCCcore/11.3.0] Brotli v1.0.9, fontconfig v2.14.0, freetype v2.12.1, ...
  easybuild/easyconfigs/b/Brotli/Brotli-1.0.9-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.14.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.12.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.38-GCCcore-11.3.0.eb
Labels: update

#14703 {chem}[intel/2021b,foss/2021b] libvdwxc v0.4.0
  easybuild/easyconfigs/l/libvdwxc/libvdwxc-0.4.0-foss-2021b.eb
  easybuild/easyconfigs/l/libvdwxc/libvdwxc-0.4.0-intel-2021b.eb
Labels: update

#15431 {vis}[GCCcore/11.3.0] X11 v20220504
  easybuild/easyconfigs/x/X11/X11-20220504-GCCcore-11.3.0.eb
Labels: update

#15432 {lib}[GCCcore/11.3.0] libdrm v2.4.110, libglvnd v1.4.0, libunwind v1.6.2, ... w/ Python 3.10.4
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.110-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.4.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.6.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/Mako/Mako-1.2.0-GCCcore-11.3.0.eb
Labels: update

#15356 {lang}[foss/2021b] R 4.2.0
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: update

#15437 {devel}[GCCcore/11.3.0] PCRE2 v10.40, PCRE v8.45
  easybuild/easyconfigs/p/PCRE/PCRE-8.45-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.40-GCCcore-11.3.0.eb
Labels: update

#15438 add MonteCarlo and RhpcBLASctl extensions to R v4.1.2 + v4.2.0 easyconfigs
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: enhancement

#15433 {compiler}[GCCcore/11.3.0] LLVM v14.0.3
  easybuild/easyconfigs/l/LLVM/LLVM-14.0.3-GCCcore-11.3.0.eb
Labels: update

#15449 {compiler}[system/system] intel-compilers v2022.0.2
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2022.0.2.eb
Labels: update

#15436 {lib,vis}[GCCcore/11.3.0] freeglut v3.2.2, libGLU v9.0.2
  easybuild/easyconfigs/f/freeglut/freeglut-3.2.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.3.0.eb
Labels: update

#14623 {math}[system/system] MCR vR2021b.1
  easybuild/easyconfigs/m/MCR/MCR-R2021b.1.eb
Labels: update

#15470 {toolchain} GCC 12.1.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-12.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.38-GCCcore-12.1.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-12.1.0.eb
  easybuild/easyconfigs/g/GCC/GCC-12.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.2-GCCcore-12.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-12.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12-GCCcore-12.1.0.eb
Labels: update

#15302 {vis}[foss/2021b] Albumentations v1.1.0 w/ Python 3.9.6
  easybuild/easyconfigs/a/Albumentations/Albumentations-1.1.0-foss-2021b.eb
  easybuild/easyconfigs/i/imgaug/imgaug-0.4.0-foss-2021b.eb
  easybuild/easyconfigs/s/Shapely/Shapely-1.8.1.post1-GCC-11.2.0.eb
Labels: new, update

#15276 {lib}[foss/2021a] pygmo v2.18.0, pagmo v2.18.0 w/ Python 3.9.5
  easybuild/easyconfigs/p/pagmo/pagmo-2.18.0-foss-2021a.eb
  easybuild/easyconfigs/p/pygmo/pygmo-2.18.0-foss-2021a.eb
Labels: update

#15439 {vis}[GCCcore/11.3.0] cairo v1.17.4, GObject-Introspection v1.72.0, GLib v2.72.1, ... w/ Python 3.10.4
  easybuild/easyconfigs/c/cairo/cairo-1.17.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.72.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.72.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pixman/pixman-0.40.0-GCCcore-11.3.0.eb
Labels: update

#15440 {vis}[GCCcore/11.3.0] ATK v2.38.0, at-spi2-atk v2.38.0, at-spi2-core v2.44.1, ...
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.44.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.14.0-GCCcore-11.3.0.eb
Labels: update

#15441 {vis}[GCCcore/11.3.0] Pango v1.50.7, FriBidi v1.0.12, ICU v71.1, ...
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-4.2.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/ICU/ICU-71.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.50.7-GCCcore-11.3.0.eb
Labels: update

#15483 {compiler}[system/system] intel-compilers v2022.1.0
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2022.1.0.eb
Labels: update

#15444 {bio,tools}[foss/2021b] R-bundle-Bioconductor v3.15, arrow-R v6.0.0.2
  easybuild/easyconfigs/a/arrow-R/arrow-R-6.0.0.2-foss-2021b-R-4.2.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2021b-R-4.2.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/RProtoBufLib-2.8.0_fix-protobuf-build.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#15411 use redist source_urls for cuDNN > 7.5
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.5.0.56-CUDA-10.0.130.eb
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.6.2.24-CUDA-10.1.243.eb
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.6.4.38-CUDA-10.0.130.eb
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.6.4.38-gcccuda-2019a.eb
  easybuild/easyconfigs/c/cuDNN/cuDNN-7.6.4.38-gcccuda-2019b.eb
Labels: enhancement

#15445 {vis}[GCCcore/11.3.0] GTK3 v3.24.33, Gdk-Pixbuf v2.42.8, libepoxy v1.5.10, LibTIFF v4.3.0, jbigkit v2.1
  easybuild/easyconfigs/g/GTK3/GTK3-3.24.33-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.3.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.10-GCCcore-11.3.0.eb
Labels: update

#15453 {mpi}[intel-compilers/2022.1.0] impi v2021.6.0
  easybuild/easyconfigs/i/impi/impi-2021.6.0-intel-compilers-2022.1.0.eb
Labels: update

#15484 {numlib}[system/system] imkl v2022.1.0
  easybuild/easyconfigs/i/imkl/imkl-2022.1.0.eb
Labels: update

#15485 {numlib,toolchain}[iimpi/2022.05,system/system] iimpi v2022.05, imkl-FFTW v2022.1.0, intel v2022.05
  easybuild/easyconfigs/i/iimpi/iimpi-2022.05.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2022.1.0-iimpi-2022.05.eb
  easybuild/easyconfigs/i/intel/intel-2022.05.eb
Labels: update

#15408 add missing dependencies for libheif (libpng, libjpeg-turbo) + switch to configuring build with CMake so libde265 dependency is picked up
  easybuild/easyconfigs/l/libheif/libheif-1.12.0-GCC-11.2.0.eb
Labels: bug fix

#15446 {vis}[GCC/11.3.0,GCCcore/11.3.0] GSL v2.7, Wayland v1.20.0, PyCairo v1.21.0, ... w/ Python 3.10.4
  easybuild/easyconfigs/g/GSL/GSL-2.7-GCC-11.3.0.eb
  easybuild/easyconfigs/g/GST-plugins-bad/GST-plugins-bad-1.20.2-GCC-11.3.0.eb
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.20.2-GCC-11.3.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.20.2-GCC-11.3.0.eb
  easybuild/easyconfigs/g/Graphene/Graphene-1.10.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.21.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.42.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.20.0-GCCcore-11.3.0.eb
Labels: new, update

#15418 {bio}[GCC/11.2.0] Salmon-1.4.0
  easybuild/easyconfigs/s/Salmon/Salmon-1.4.0-GCC-11.2.0.eb
Labels: update

#15351 {bio}[GCC/11.2.0] bam-readcount v0.8.0
  easybuild/easyconfigs/b/bam-readcount/bam-readcount-0.8.0-GCC-11.2.0.eb
Labels: update

#15472 {tools}[iimpi/2021b] worker 1.6.13
  easybuild/easyconfigs/w/worker/worker-1.6.13-iimpi-2021b.eb
  easybuild/easyconfigs/w/worker/worker-1.6.13_fixintel.patch
Labels: update

#15422 {tools}[foss/2021a] jax v0.3.9 w/ Python 3.9.5
  easybuild/easyconfigs/j/jax/jax-0.3.9-foss-2021a.eb
Labels: update

#15487 {data}[GCC/11.2.0] DBD-mysql v4.050
  easybuild/easyconfigs/d/DBD-mysql/DBD-mysql-4.050-GCC-11.2.0.eb
Labels: update

#15345 {bio}[GCC/11.2.0] Arriba v2.2.1
  easybuild/easyconfigs/a/Arriba/Arriba-2.2.1-GCC-11.2.0.eb
Labels: update

#15481 {tools}[GCCcore/10.3.0] parameterized v0.8.1 w/ Python 3.9.5
  easybuild/easyconfigs/p/parameterized/parameterized-0.8.1-GCCcore-10.3.0.eb
Labels: new

#15457 {data}[gompi/2021b] slow5tools v0.4.0
  easybuild/easyconfigs/s/slow5tools/slow5tools-0.4.0-gompi-2021b.eb
Labels: new

#15407 {lib,vis}[GCC/11.2.0] tmap v20220502, OGDF vdogwood-202202 w/ Python 3.9.6
  easybuild/easyconfigs/o/OGDF/OGDF-dogwood-202202-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OGDF/OGDF-dogwood-202202_fix_lib_install_dir.patch
  easybuild/easyconfigs/t/tmap/tmap-20220502-GCC-11.2.0.eb
  easybuild/easyconfigs/t/tmap/tmap-20220502_add_install.patch
Labels: new

#15490 {system}[system/system] CUDA v11.7.0
  easybuild/easyconfigs/c/CUDA/CUDA-11.7.0.eb
Labels: update

#15501 {lang}[system/system] Anaconda3 v2022.05
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2022.05.eb
Labels: update

#15509 {tools}[foss/2021a] neptune-client v0.16.2 w/ Python 3.9.5
  easybuild/easyconfigs/n/neptune-client/neptune-client-0.16.2-foss-2021a.eb
Labels: update

#15511 {math}[foss/2021a] MUMPS v5.5.0
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.0-foss-2021a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.0_shared-mumps.patch
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.0_shared-pord.patch
Labels: update

#15522 {lib,math}[GCCcore/11.3.0] Eigen v3.4.0, pybind11 v2.9.2 w/ Python 3.10.4
  easybuild/easyconfigs/e/Eigen/Eigen-3.4.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.9.2-GCCcore-11.3.0.eb
Labels: update

#15521 {tools}[GCCcore/11.3.0] hypothesis v6.46.7 w/ Python 3.10.4
  easybuild/easyconfigs/h/hypothesis/hypothesis-6.46.7-GCCcore-11.3.0.eb
Labels: update

#15514 {math}[GCCcore/10.3.0] muParser v2.3.3
  easybuild/easyconfigs/m/muParser/muParser-2.3.3-GCCcore-10.3.0.eb
Labels: update

#15507 {tools}[GCCcore/11.2.0] gsutil 5.10 w/ Python 3.9.6
  easybuild/easyconfigs/g/gsutil/gsutil-5.10-GCCcore-11.2.0.eb
Labels: new

#15525 {devel}[GCCcore/11.2.0] Bazel v4.2.2
  easybuild/easyconfigs/b/Bazel/Bazel-4.2.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-4.2.2_ftbs-gcc11-2.patch
  easybuild/easyconfigs/b/Bazel/Bazel-4.2.2_ftbs-gcc11-3.patch
  easybuild/easyconfigs/b/Bazel/Bazel-4.2.2_ftbs-gcc11-4.patch
  easybuild/easyconfigs/b/Bazel/Bazel-4.2.2_remove-illegal-reflective.patch
Labels: update

#15512 update Arrow to use EB versions of some dependencies and enable all compression codecs
  easybuild/easyconfigs/a/Arrow/Arrow-6.0.0-foss-2021a.eb
  easybuild/easyconfigs/a/Arrow/Arrow-6.0.0-foss-2021b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-6.0.1-foss-2021a.eb
  easybuild/easyconfigs/r/RE2/RE2-2022-02-01-GCCcore-10.3.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-11.2.0.eb
Labels: enhancement

#15529 Add local::lib and Module::Path to Perl 5.34.1 (2022a)
  easybuild/easyconfigs/p/Perl/Perl-5.34.1-GCCcore-11.3.0.eb
Labels: enhancement

#15527 {lib}[GCCcore/11.3.0] UCC v1.0.0
  easybuild/easyconfigs/u/UCC/UCC-1.0.0-GCCcore-11.3.0.eb
Labels: new

#15423 {cae}[system/system] ABAQUS v2022
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022.eb
Labels: update

#15443 {tools}[system/system] gcloud v382.0.0
  easybuild/easyconfigs/g/gcloud/gcloud-382.0.0.eb
Labels: new

#15473 {tools}[GCCcore/10.3.0] num2words v0.5.10 w/ Python 3.9.5
  easybuild/easyconfigs/n/num2words/num2words-0.5.10-GCCcore-10.3.0.eb
Labels: new

#15442 {vis}[GCCcore/10.3.0,foss/2021a] pydot v1.4.2, detectron2 v0.6 w/ Python 3.9.5 + CUDA 11.3.1
  easybuild/easyconfigs/d/detectron2/detectron2-0.6-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/p/pydot/pydot-1.4.2-GCCcore-10.3.0.eb
Labels: new, update

#14717 {bio}[GCC/11.2.0] VEP v105
  easybuild/easyconfigs/v/VEP/VEP-105-GCC-11.2.0.eb
Labels: update

#15539 {bio}[GCC/10.2.0] MUSCLE v3.8.1551
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.1551-GCC-10.2.0.eb
Labels: update

#15506 {base}[foss/2021a] smooth-topk v1.0-20210817 w/ Python 3.9.5
  easybuild/easyconfigs/s/smooth-topk/smooth-topk-1.0-20210817-foss-2021a.eb
Labels: new

#15206 fix installation with setuptools>=61 by explicitly declaring there are no Python packages
  setup.py
Labels: bug fix

#15540 add chkptstanr extension to R v4.2.0
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: enhancement

#15541 {bio}[GCC/11.2.0] RAxML-NG v1.1.0
  easybuild/easyconfigs/r/RAxML-NG/RAxML-NG-1.1.0-GCC-11.2.0.eb
Labels: update

#15542 {lang}[foss/2021b] numba v0.54.1 w/ Python 3.9.6 + CUDA 11.4.1
  easybuild/easyconfigs/n/numba/numba-0.54.1-foss-2021b-CUDA-11.4.1.eb
Labels: update

#15452 {cae}[system/system] ABAQUS v2022 (incl. 2214 hotfix)
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022-hotfix-2214.eb
Labels: update

#15533 {bio}[GCC/11.2.0] mosdepth v0.3.3, Nim v1.6.6
  easybuild/easyconfigs/m/mosdepth/mosdepth-0.3.3-GCC-11.2.0.eb
  easybuild/easyconfigs/n/Nim/Nim-1.6.6-GCCcore-11.2.0.eb
Labels: update

#15528 OpenMPI 4.1.1: patch and build --with-cuda=internal
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-GCC-10.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1_build-with-internal-cuda-header.patch
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1_opal-datatype-cuda-performance.patch
Labels: bug fix

#15552 {devel}[foss/2021b] buildenv vdefault
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2021b.eb
Labels: update

#15456 {lib}[GCCcore/11.3.0] libevent v2.1.12, libfabric v1.15.1, PMIx v4.1.2
  easybuild/easyconfigs/l/libevent/libevent-2.1.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.15.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.15.1_disable-OPX-if-unsupported.patch
  easybuild/easyconfigs/p/PMIx/PMIx-4.1.2-GCCcore-11.3.0.eb
Labels: update

#15554 {lib}[GCCcore/11.3.0] json-c v0.16
  easybuild/easyconfigs/j/json-c/json-c-0.16-GCCcore-11.3.0.eb
Labels: update

#15426 {mpi}[GCC/11.3.0] OpenMPI v4.1.4
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-11.3.0.eb
Labels: update

#15553 {toolchain} gompi/2022.05 (+ OSU-Micro-Benchmarks v5.9)
  easybuild/easyconfigs/g/gompi/gompi-2022.05.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.9-gompi-2022.05.eb
Labels: update

#15560 {toolchain} GCC v9.5.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-9.5.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.38-GCCcore-9.5.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-9.5.0.eb
  easybuild/easyconfigs/g/GCC/GCC-9.5.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-9.5.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.2-GCCcore-9.5.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-9.5.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12-GCCcore-9.5.0.eb
Labels: update

#15523 {lang}[intel/2022.05] SciPy-bundle v2022.05 w/ Python 3.10.4
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-intel-2022.05.eb
  easybuild/easyconfigs/s/SciPy-bundle/deap-1.3.1_no_2to3.patch
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.22.3_disable-broken-override-test.patch
Labels: update

#15549 {devel,tools}[GCCcore/11.3.0] Bazel v5.1.1, Zip v3.0
  easybuild/easyconfigs/b/Bazel/Bazel-5.1.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-11.3.0.eb
Labels: update

#15406 {numlib}[GCC/11.3.0] FFTW v3.3.10
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-GCC-11.3.0.eb
Labels: new, update

#15558 {math}[foss/2021b] magma v2.6.2
  easybuild/easyconfigs/m/magma/magma-2.6.2-foss-2021b-CUDA-11.4.1.eb
Labels: update

#15545 {lib}[foss/2021a] smooth-topk v1.0-20210817 w/ Python 3.9.5
  easybuild/easyconfigs/s/smooth-topk/smooth-topk-1.0-20210817-foss-2021a-CUDA-11.3.1.eb
Labels: update

#15548 {tools}[GCCcore/11.2.0] OpenStackClient v5.8.0 w/ Python 3.9.6
  easybuild/easyconfigs/o/OpenStackClient/OpenStackClient-5.8.0-GCCcore-11.2.0.eb
Labels: update

#15564 PMIx 4.1.2: remove unused libfabric dep
  easybuild/easyconfigs/p/PMIx/PMIx-4.1.2-GCCcore-11.3.0.eb
Labels: bug fix

#15294 add hwloc dependency to easyconfig for tbb v2021.4.0
  easybuild/easyconfigs/t/tbb/tbb-2021.4.0-GCCcore-11.2.0.eb
Labels: bug fix

#13367 {bio}[GCCcore 10.3.0] InterProScan 5.52-86.0
  easybuild/easyconfigs/i/InterProScan/InterProScan-5.52-86.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libharu/libharu-2.3.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/pftoolsV3/pftoolsV3-3.2.11-GCCcore-10.3.0.eb
Labels: update

#15570 {bio}[GCC/10.3.0] Jellyfish v2.3.0
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-10.3.0.eb
Labels: update

#15579 Fix gmsh 4.9.0 lib and python bindings
  easybuild/easyconfigs/g/gmsh/gmsh-4.9.0-foss-2021a.eb
Labels: bug fix

#15573 add chkptstanr + MLmetrics + renv extensions to R v4.1.2 + v4.2.0 easyconfigs
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: enhancement
