Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-07, with the labels that each got.

#15775 {vis}[GCCcore/10.3.0] tesseract v4.1.0
  easybuild/easyconfigs/t/tesseract/tesseract-4.1.0-GCCcore-10.3.0.eb
Labels: update

#15804 {vis}[GCCcore/11.3.0] Pillow v9.1.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.3.0.eb
Labels: update

#15808 {lib}[GCCcore/11.3.0] jemalloc v5.3.0
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-11.3.0.eb
Labels: update

#15813 {bio}[GCCcore/11.2.0] Bracken v2.7
  easybuild/easyconfigs/b/Bracken/Bracken-2.7-GCCcore-11.2.0.eb
Labels: update

#15811 {bio}[foss/2021a] MaSuRCA v4.0.9
  easybuild/easyconfigs/m/MaSuRCA/MaSuRCA-4.0.9-foss-2021a-Perl-5.32.1.eb
Labels: update

#15807 {bio}[GCCcore/10.3.0] hifiasm v0.16.1
  easybuild/easyconfigs/h/hifiasm/hifiasm-0.16.1-GCCcore-10.3.0.eb
Labels: update

#15817 {devel}[GCCcore/10.2.0] makedepend v1.0.6
  easybuild/easyconfigs/m/makedepend/makedepend-1.0.6-GCCcore-10.2.0.eb
Labels: update

#15818 {data}[GCCcore/10.2.0] g2lib v3.2.0
  easybuild/easyconfigs/g/g2lib/g2lib-3.2.0-GCCcore-10.2.0.eb
Labels: update

#15812 {bio}[GCC/10.3.0] MetaEuk v5
  easybuild/easyconfigs/m/MetaEuk/MetaEuk-5-GCC-10.3.0.eb
Labels: update

#15810 add geeM extension to R v4.2.0
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: enhancement

#15801 {lib}[GCCcore/10.2.0] gdbm v1.21
  easybuild/easyconfigs/g/gdbm/gdbm-1.21-GCCcore-10.2.0.eb
Labels: update

#15820 {data}[foss/2020b] NCL v6.6.2
  easybuild/easyconfigs/n/NCL/NCL-6.6.2-foss-2020b.eb
Labels: update

#15815 {chem}[GCC/11.2.0] IGMPlot v2.6.9b
  easybuild/easyconfigs/i/IGMPlot/IGMPlot-2.6.9b-GCC-11.2.0.eb
Labels: update

#15715 add patch for GCCcore 11.3.0 to support using -fuse-ld=mold
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.3.0_fuse-ld-mold.patch
Labels: enhancement

#15767 {lang}[foss/2022a] R v4.2.1
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
Labels: update

#15600 {bio}[GCCcore/10.3.0] NGS v2.10.9
  easybuild/easyconfigs/n/NGS/NGS-2.10.9-GCCcore-10.3.0.eb
Labels: update

#15735 {lib}[GCCcore/10.2.0] RapidJSON v1.1.0
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-10.2.0.eb
Labels: update

#15828 prepare release notes for EasyBuild v4.6.0 + bump version to 4.6.0
  RELEASE_NOTES
  setup.py
Labels: update

#15831 sync with main + bump version to 4.6.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#15826 Fix BLIS build on PPC
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1-GCC-10.3.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1-GCC-11.2.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-0.8.1_enable_ppc_autodetect.patch
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0-GCC-11.3.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0_enable_ppc_autodetect.patch
  easybuild/easyconfigs/b/BLIS/BLIS-2.2-GCCcore-9.3.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-3.0-GCCcore-10.3.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-GCC-11.2.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-GCCcore-10.2.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-GCCcore-10.3.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-3.1-GCCcore-11.2.0-amd.eb
Labels: enhancement, change

#15806 {bio}[GCCcore/11.2.0] MUMmer v4.0.0rc1
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0rc1-GCCcore-11.2.0.eb
Labels: update

#15822 add Autotools build dependency to R 4.2.0 w/ foss 2021b
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: bug fix

#15797 {bio}[foss/2021a] AUGUSTUS v3.4.0
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.4.0-foss-2021a.eb
Labels: update

#15712 {data}[GCCcore/10.2.0] Globus-CLI v3.1.1 w/ Python 3.8.6
  easybuild/easyconfigs/g/Globus-CLI/Globus-CLI-3.1.1-GCCcore-10.2.0.eb
Labels: update

#15843 explicitly enable HDF5 from kallisto v0.46.2 onwards
  easybuild/easyconfigs/k/kallisto/kallisto-0.46.2-foss-2020b.eb
  easybuild/easyconfigs/k/kallisto/kallisto-0.48.0-gompi-2021b.eb
Labels: bug report, bug fix

#15863 {bio}[foss/2021b] RNA-SeQC v2.4.2 w/ Python 3.9.6
  easybuild/easyconfigs/r/RNA-SeQC/RNA-SeQC-2.4.2-foss-2021b.eb
Labels: update

#15033 {vis}[foss/2021a] Detectron2 v0.6 w/ Python 3.9.5
  easybuild/easyconfigs/d/Detectron2/Detectron2-0.6-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/d/Detectron2/Detectron2-0.6-foss-2021a.eb
  easybuild/easyconfigs/d/detectron2/detectron2-0.6-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/t/topaz/topaz-0.2.5-foss-2021a.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.11.3-foss-2021a-CUDA-11.3.1.eb
Labels: new, update, change

#15862 {bio}[gompi/2021b] Unicycler v0.5.0 w/ Python 3.9.6
  easybuild/easyconfigs/u/Unicycler/Unicycler-0.5.0-gompi-2021b.eb
Labels: update

#15859 use build enviroment from EB and add missing dependency on zlib to minimap2
  easybuild/easyconfigs/m/minimap2/minimap2-2.17-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/minimap2/minimap2-2.18-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/minimap2/minimap2-2.20-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/minimap2/minimap2-2.20-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/minimap2/minimap2-2.22-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/minimap2/minimap2-2.24-GCCcore-11.2.0.eb
Labels: bug fix

#15858 {bio}[GCCcore/10.3.0,GCCcore/11.2.0] miniasm v0.3-20191007
  easybuild/easyconfigs/m/miniasm/miniasm-0.3-20191007-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/miniasm/miniasm-0.3-20191007-GCCcore-11.2.0.eb
Labels: new

#15864 add missing dependencies and execute tests on Trycycler v0.5.2
  easybuild/easyconfigs/t/Trycycler/Trycycler-0.5.2-foss-2021a.eb
Labels: bug fix

#15865 {bio}[foss/2021b] Trycycler v0.5.3 w/ Python 3.9.6
  easybuild/easyconfigs/t/Trycycler/Trycycler-0.5.3-foss-2021b.eb
Labels: update

#15861 {bio}[GCCcore/11.3.0] CapnProto v0.10.2
  easybuild/easyconfigs/c/CapnProto/CapnProto-0.10.2-GCCcore-11.3.0.eb
Labels: update

#15866 Stripy-2.1.0-foss-2021a
  easybuild/easyconfigs/s/stripy/stripy-2.1.0-foss-2021a.eb
Labels: new

#14838 {tools}[foss/2021b] Ray-project v1.9.2 w/ Python 3.9.6
  easybuild/easyconfigs/r/Ray-project/Ray-project-1.9.2-foss-2021b.eb
Labels: update

#15825 {bio,lang}[GCCcore/10.3.0] dotNET-Core-Runtime v5.0.17, MetaMorpheus v0.0.320
  easybuild/easyconfigs/d/dotNET-Core-Runtime/dotNET-Core-Runtime-5.0.17-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/MetaMorpheus/MetaMorpheus-0.0.320-GCCcore-10.3.0.eb
Labels: new, update

#15851 {math}[foss/2021b] molmod v1.4.8 w/ Python 3.9.6
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2021b.eb
Labels: update

#15838 {lib}[foss/2021a] scikit-optimize 0.9.0
  easybuild/easyconfigs/p/pretty-yaml/pretty-yaml-21.10.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/scikit-optimize/scikit-optimize-0.9.0-foss-2021a.eb
Labels: update

#15875 {lib}[foss/2021b] pagmo v2.18.0, pygmo v2.18.0 w/ Python 3.9.6
  easybuild/easyconfigs/p/pagmo/pagmo-2.18.0-foss-2021b.eb
  easybuild/easyconfigs/p/pygmo/pygmo-2.18.0-foss-2021b.eb
Labels: update

#15187 {chem}[foss/2021b] xtb v6.4.1
  easybuild/easyconfigs/x/xtb/xtb-6.4.1-foss-2021b.eb
Labels: update

#15879 {geo}[gompi/2021b] GLM-AED v3.3.0a5
  easybuild/easyconfigs/g/GLM-AED/GLM-AED-3.3.0a5-gompi-2021b.eb
  easybuild/easyconfigs/g/GLM-AED/GLM-AED-3.3.0a5_disable-deb-pkg.patch
Labels: new

#15883 {math}[foss/2021b] Dakota v6.16.0 w/ Python 3.9.6
  easybuild/easyconfigs/d/Dakota/Dakota-6.16.0-boost177-dllimport.patch
  easybuild/easyconfigs/d/Dakota/Dakota-6.16.0-foss-2021b.eb
Labels: new

#15884 {perf}[system/system] Advisor v2022.1.0
  easybuild/easyconfigs/a/Advisor/Advisor-2022.1.0.eb
Labels: update

#15887 {bio}[GCC/10.3.0] STAR v2.7.10a_alpha_220601
  easybuild/easyconfigs/s/STAR/STAR-2.7.10a_alpha_220601-GCC-10.3.0.eb
Labels: update

#15888 {tools}[GCCcore/11.3.0] patchelf v0.15.0
  easybuild/easyconfigs/p/patchelf/patchelf-0.15.0-GCCcore-11.3.0.eb
Labels: update

#15890 {compiler}[GCCcore/11.3.0] AOCC v3.2.0
  easybuild/easyconfigs/a/AOCC/AOCC-3.2.0-GCCcore-11.3.0.eb
Labels: update

#15876 {chem}[foss/2021a] LAMMPS v23Jun2022 w/ Python 3.9.5
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos.eb
Labels: update

#15877 {chem}[foss/2021b] LAMMPS v23Jun2022, Voro++ v0.4.6 w/ Python 3.9.6
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-11.2.0.eb
Labels: update

#15898 Add alternate download URL for Voro++
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-6.4.0.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-9.3.0.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-foss-2016a.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-foss-2019b.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-intel-2016a.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-intel-2019b.eb
Labels: enhancement

#15893 {lib,tools}[GCCcore/11.3.0] aria2 v1.36.0, c-ares v1.18.1
  easybuild/easyconfigs/a/aria2/aria2-1.36.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/c-ares/c-ares-1.18.1-GCCcore-11.3.0.eb
Labels: update

#15881 {bio}[GCCcore/11.2.0] GATK v4.2.6.1 w/ Python 3.9.6
  easybuild/easyconfigs/g/GATK/GATK-4.2.6.1-GCCcore-11.2.0-Java-11.eb
Labels: update

#15894 {bio}[foss/2022a] MDAnalysis v2.2.0, tqdm v4.64.0, Biopython v1.79 w/ Python 3.10.4
  easybuild/easyconfigs/b/Biopython/Biopython-1.79-foss-2022a.eb
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-2.2.0-foss-2022a.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.5.2-foss-2022a.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.64.0-GCCcore-11.3.0.eb
Labels: update

#15905 {math}[GCCcore/11.3.0] GDB v12.1, ISL v0.24, MPC v1.2.1, ... w/ Python 3.10.4
  easybuild/easyconfigs/g/GDB/GDB-12.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/ISL/ISL-0.24-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/MPC/MPC-1.2.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-6.8-GCCcore-11.3.0.eb
Labels: update

#15847 {data}[GCCcore/10.3.0,GCCcore/11.2.0] Globus-CLI v3.2.0, Globus-CLI v3.6.0 w/ Python 3.9.5 + 3.9.6
  easybuild/easyconfigs/g/Globus-CLI/Globus-CLI-3.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/Globus-CLI/Globus-CLI-3.6.0-GCCcore-11.2.0.eb
Labels: update

#15020 {tools}[foss/2021a,foss/2021b] fastparquet v0.7.2, fastparquet v0.8.0 w/ Python 3.9.5 + 3.9.6
  easybuild/easyconfigs/f/fastparquet/fastparquet-0.7.2-foss-2021a.eb
  easybuild/easyconfigs/f/fastparquet/fastparquet-0.8.0-foss-2021b.eb
Labels: new

#15909 {bio}[gompi/2022a] BLAST+ v2.13.0
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.13.0-gompi-2022a.eb
Labels: update

#15911 {bio}[GCC/11.3.0] BEDTools v2.30.0, BamTools v2.5.2
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.30.0-GCC-11.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-11.3.0.eb
Labels: update

#15913 {bio}[GCC/11.3.0] SAMtools v1.15.1
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.15.1-GCC-11.3.0.eb
Labels: update

#15912 {bio}[GCC/11.3.0] BCFtools v1.15.1, HTSlib v1.15.1
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.15.1-GCC-11.3.0.eb
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.15.1-GCC-11.3.0.eb
Labels: update

#15914 {bio}[GCCcore/11.3.0] PRSice v2.3.5
  easybuild/easyconfigs/p/PRSice/PRSice-2.3.5-GCCcore-11.3.0.eb
Labels: update

#15915 {bio}[GCC/11.3.0] Bowtie2 v2.4.5 w/ Python 3.10.4
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.5-GCC-11.3.0.eb
Labels: update

#15932 exclude Binary, PackedBinary and JAR easyblocks from binutils build requirements
  test/easyconfigs/easyconfigs.py
Labels: bug fix, tests

#15916 {bio}[GCC/10.3.0] BBMap v38.96
  easybuild/easyconfigs/b/BBMap/BBMap-38.96-GCC-10.3.0.eb
Labels: update

#15922 {tools}[GCCcore/11.3.0] expecttest v0.1.3 w/ Python 3.10.4
  easybuild/easyconfigs/e/expecttest/expecttest-0.1.3-GCCcore-11.3.0.eb
Labels: update

#15925 {geo}[foss/2021b] Cartopy v0.20.3 w/ Python 3.9.6
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.20.3-foss-2021b.eb
Labels: update

#15926 {tools}[GCCcore/11.3.0] p7zip v17.04
  easybuild/easyconfigs/p/p7zip/p7zip-17.04-GCCcore-11.3.0.eb
Labels: update

#15927 {debugger}[gompi/2022a] Valgrind v3.19.0
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.19.0-gompi-2022a.eb
Labels: update

#15928 {data}[GCCcore/11.3.0] XML-Parser v2.46
  easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.46-GCCcore-11.3.0-Perl-5.34.1.eb
Labels: update

#15929 {tools}[system/system] itac v2021.6.0
  easybuild/easyconfigs/i/itac/itac-2021.6.0.eb
Labels: update

#15930 {tools}[GCCcore/11.3.0] parallel v20220722
  easybuild/easyconfigs/p/parallel/parallel-20220722-GCCcore-11.3.0.eb
Labels: update

#15931 {devel}[GCCcore/11.3.0] libdwarf v0.4.1, libelf v0.8.13
  easybuild/easyconfigs/l/libdwarf/libdwarf-0.4.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libelf/libelf-0.8.13-GCCcore-11.3.0.eb
Labels: update

#15917 {tools}[foss/2021a] Ray-project v1.13.0
  easybuild/easyconfigs/r/Ray-project/Ray-project-1.13.0-foss-2021a.eb
Labels: update

#15918 {vis}[GCCcore/11.3.0] x264 v20220620, x265 v3.5, Yasm v1.3.0, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20220620-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-11.3.0.eb
Labels: update
