Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-08, with the labels that each got.

#15899 {data}[system] Stata v17
  easybuild/easyconfigs/l/libpng/libpng-1.5.30.eb
  easybuild/easyconfigs/s/Stata/Stata-17.eb
Labels: update

#15910 {cae}[GCCcore/11.2.0,system/system] MATSim v14.0
  easybuild/easyconfigs/m/MATSim/MATSim-14.0-GCCcore-11.2.0-Java-11.eb
  easybuild/easyconfigs/m/MATSim/MATSim-14.0-Java-11.eb
Labels: update

#15942 {devel}[foss/2022a,intel/2021b,intel/2022a] buildenv vdefault
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2022a.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-intel-2021b.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-intel-2022a.eb
Labels: update

#15920 {lib}[GCCcore/11.3.0] libyaml v0.2.5, PyYAML v6.0 w/ Python 3.10.4
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-6.0-GCCcore-11.3.0.eb
Labels: update

#15944 {tools}[GCC/11.3.0] gawk v5.1.1
  easybuild/easyconfigs/g/gawk/gawk-5.1.1-GCC-11.3.0.eb
Labels: update

#15935 {compiler}[GCCcore/10.2.0, 11.2.0] Clang v11.0.1, v12.0.1
  easybuild/easyconfigs/c/Clang/Clang-11.0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/c/Clang/Clang-12.0.1-GCCcore-11.2.0.eb
Labels: bug fix

#15946 {lang}[GCCcore/11.3.0] Lua v5.4.4
  easybuild/easyconfigs/l/Lua/Lua-5.4.4-GCCcore-11.3.0.eb
Labels: update

#15947 {lib}[GCCcore/11.3.0] libgd v2.3.3
  easybuild/easyconfigs/l/libgd/libgd-2.3.3-GCCcore-11.3.0.eb
Labels: update

#15951 {devel}[GCCcore/11.3.0] SWIG v4.0.2
  easybuild/easyconfigs/s/SWIG/SWIG-4.0.2-GCCcore-11.3.0.eb
Labels: update

#15952 {vis}[GCCcore/11.3.0] GTS v0.7.6
  easybuild/easyconfigs/g/GTS/GTS-0.7.6-GCCcore-11.3.0.eb
Labels: update

#15359 adding easyconfigs: CellRanger-ATAC-2.1.0.eb
  easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-2.1.0.eb
Labels: update

#15945 {lib}[GCCcore/10.3.0] libQGLViewer v2.8.0
  easybuild/easyconfigs/l/libQGLViewer/libQGLViewer-2.8.0-GCCcore-10.3.0.eb
Labels: update

#15874 add patch for AlphaFold v2.2.2 to fix NaN problem with jax 0.3.9
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.2.2-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.2.2-foss-2021a.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.2.2_jax038_NaN.patch
Labels: bug fix

#15032 {cae}[foss/2021b] OpenFAST v3.0.0
  easybuild/easyconfigs/o/OpenFAST/OpenFAST-3.0.0-foss-2021b.eb
Labels: new

#15983 add sanity check command for OpenFAST
  easybuild/easyconfigs/o/OpenFAST/OpenFAST-3.0.0-foss-2021b.eb
Labels: enhancement

#15889 fix tests on POWER9 for BLIS 0.9.0 + fix auto-detect for POWER10 for BLIS (AMD) v2.0 + v3.0
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0-GCC-11.3.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0_disable_power9_kernels.patch
  easybuild/easyconfigs/b/BLIS/BLIS-2.2-GCCcore-9.3.0-amd.eb
  easybuild/easyconfigs/b/BLIS/BLIS-2.2_enable-ppc-autodetect.patch
  easybuild/easyconfigs/b/BLIS/BLIS-3.0-GCCcore-10.3.0-amd.eb
Labels: bug fix

#15992 {devel}[system/system] ant v1.10.12
  easybuild/easyconfigs/a/ant/ant-1.10.12-Java-17.eb
Labels: update

#15988 add missing SciPy-bundle dependency for rMATS-turbo
  easybuild/easyconfigs/r/rMATS-turbo/rMATS-turbo-4.1.1-foss-2020b.eb
Labels: bug fix

#15373 {cae}[foss/2021b] GATE v9.2, Geant4 v11.0.1
  easybuild/easyconfigs/g/GATE/GATE-9.2-foss-2021b.eb
  easybuild/easyconfigs/g/GATE/GATE-9.2_fix-Geant4-11.0.patch
  easybuild/easyconfigs/g/Geant4/Geant4-11.0.1-GCC-11.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#15969 {phys}[GCC/11.2.0] Geant4 v11.0.2
  easybuild/easyconfigs/g/Geant4/Geant4-11.0.2-GCC-11.2.0.eb
Labels: update

#15990 {data}[gompi/2022a] netCDF-Fortran v4.6.0
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.6.0-gompi-2022a.eb
Labels: update

#15906 stick to Java/11 as dependency for Bazel 5.1.1 (which is available for x86_64, aarch64, ppc64le)
  easybuild/easyconfigs/b/Bazel/Bazel-5.1.1-GCCcore-11.3.0.eb
Labels: change

#15997 {bio}[foss/2022a] Stacks v2.62
  easybuild/easyconfigs/s/Stacks/Stacks-2.62-foss-2022a.eb
Labels: update

#15998 {math}[foss/2021b] Transformers v4.21.1 w/ Python 3.9.6
  easybuild/easyconfigs/t/Transformers/Transformers-4.21.1-foss-2021b.eb
Labels: update

#15993 Explicitly get the wannier source from the wannier github
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-foss-2022a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-intel-2022a.eb
Labels: bug fix

#15999 Update LAMMPS 23Jun2022 for latest bugfix sources
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos.eb
Labels: change

#15996 restore ploteig in EIGENSOFT 7.2.1
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2018b.eb
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2019a.eb
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2019b.eb
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2021a.eb
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-intel-2019a.eb
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1_restore-ploteig.patch
Labels: bug fix

#16000 {tools}[GCCcore/11.3.0] ANTLR v2.7.7
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-11.3.0-Java-11.eb
Labels: update

#15995 {vis}[system/system] Embree v3.13.4
  easybuild/easyconfigs/e/Embree/Embree-3.13.4.eb
Labels: update

#15985 {compiler,tools}[GCCcore/11.3.0] Clang v13.0.1, Z3 v4.10.2
  easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/Z3/Z3-4.10.2-GCCcore-11.3.0.eb
Labels: update

#15961 {lib}[GCCcore/11.3.0] libzip v1.9.2
  easybuild/easyconfigs/l/libzip/libzip-1.9.2-GCCcore-11.3.0.eb
Labels: update

#15948 {math}[GCCcore/11.3.0] libcerf v2.1
  easybuild/easyconfigs/l/libcerf/libcerf-2.1-GCCcore-11.3.0.eb
Labels: update

#15871 {bio}[foss/2021b] Phantompeakqualtools 1.2.2
  easybuild/easyconfigs/p/Phantompeakqualtools/Phantompeakqualtools-1.2.2-foss-2021b.eb
Labels: new

#16001 update Java/11 to 11.0.16 and Java/17 to 17.0.4
  easybuild/easyconfigs/j/Java/Java-11.0.16.eb
  easybuild/easyconfigs/j/Java/Java-11.eb
  easybuild/easyconfigs/j/Java/Java-17.0.4.eb
  easybuild/easyconfigs/j/Java/Java-17.eb
Labels: update

#16005 {lib}[GCCcore/11.3.0] lxml v4.9.1 w/ Python 3.10.4
  easybuild/easyconfigs/l/lxml/lxml-4.9.1-GCCcore-11.3.0.eb
Labels: update

#15956 {lib}[GCCcore/11.3.0] UCC-CUDA v1.0.0
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.0.0-GCCcore-11.3.0-CUDA-11.7.0.eb
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.0.0_link_against_existing_UCC_libs.patch
Labels: new

#15975 {bio}[system/system] Schrodinger v2022-3
  easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-3.eb
Labels: update

#14841 {chem}[foss/2021b,intel/2021b] QuantumESPRESSO v7.0
  easybuild/easyconfigs/e/ELPA/ELPA-2021.05.001-intel-2021b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-foss-2021b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-intel-2021b.eb
Labels: update

#15962 {data}[gompi/2022a] netCDF-C++4 v4.3.1, PnetCDF v1.12.3
  easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.1-gompi-2022a.eb
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.3-gompi-2022a.eb
Labels: update

#15954 {vis}[GCCcore/11.3.0] gifsicle v1.93
  easybuild/easyconfigs/g/gifsicle/gifsicle-1.93-GCCcore-11.3.0.eb
Labels: update

#15943 {numlib}[foss/2022a] Hypre v2.25.0
  easybuild/easyconfigs/h/Hypre/Hypre-2.25.0-foss-2022a.eb
Labels: update

#15960 {bio}[foss/2021a] BUSCO v5.4.2 w/ Python 3.9.5
  easybuild/easyconfigs/b/BUSCO/BUSCO-5.4.2-foss-2021a.eb
Labels: update

#15963 {lib}[GCCcore/10.2.0] Blitz++ v1.0.2
  easybuild/easyconfigs/b/Blitz++/Blitz++-1.0.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/b/Blitz++/Blitz++-1.0.2-GCCcore-11.3.0.eb
Labels: update

#15941 {lib,perf}[GCCcore/11.3.0] OTF2 v3.0, SIONlib v1.7.7
  easybuild/easyconfigs/o/OTF2/OTF2-3.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-11.3.0-tools.eb
Labels: update

#16011 Fix new checksum for plot3Drgl
  easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
Labels: bug fix

#8407 {phys}[foss/2019a,intel/2019a] CrystFEL v0.8.0
  easybuild/easyconfigs/c/CrystFEL/CrystFEL-0.8.0-foss-2019a.eb
  easybuild/easyconfigs/c/CrystFEL/CrystFEL-0.8.0-intel-2019a.eb
Labels: new

#15045 {bio}[system/system] Schrodinger v2022-1
  easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-1.eb
Labels: update

#16015 {bio}[GCC/11.3.0] Pysam v0.19.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/Pysam/Pysam-0.19.1-GCC-11.3.0.eb
Labels: update

#15468 {vis}[foss/2021b] PyOpenCL v2021.2.13 w/ Python 3.9.6
  easybuild/easyconfigs/p/PyOpenCL/PyOpenCL-2021.2.13-foss-2021b.eb
Labels: update

#15699 {tools}[system/system] git-lfs v3.2.0
  easybuild/easyconfigs/g/git-lfs/git-lfs-3.2.0.eb
Labels: update

#14822 {data}[foss/2021b] scikit-learn v1.0.2 w/ Python 3.9.6
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.0.2-foss-2021b.eb
Labels: update

#15885 work around miscompilation of OpenBLAS on POWER by compiling with -fstack-protector-strong
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.15-GCC-10.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.15_workaround-gcc-miscompilation.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.17-GCC-10.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.17-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.18-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.3.0.eb
Labels: bug fix

#15741 {geo}[foss/2021b] CESM-deps v2 w/ Python 3.9.6
  easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-foss-2021b.eb
Labels: update

#16024 {lib}[GCCcore/10.2.0,GCCcore/10.3.0,GCCcore/11.2.0,GCCcore/11.3.0] scikit-build v0.15.0 w/ Python 3.8.6 + 3.9.5 + 3.9.6 + 3.10.4
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.15.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.15.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.15.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.15.0-GCCcore-11.3.0.eb
Labels: update

#15994 {vis}[foss/2022a] VTK v9.2.0.rc2 w/ Python 3.10.4
  easybuild/easyconfigs/v/VTK/VTK-9.2.0.rc2-foss-2022a.eb
Labels: update

#16016 {data}[foss/2022a] scikit-learn v1.1.2 w/ Python 3.10.4
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.1.2-foss-2022a.eb
Labels: update

#16028 {tools}[GCCcore/11.3.0] Mercurial v6.2 w/ Python 3.10.4
  easybuild/easyconfigs/m/Mercurial/Mercurial-6.2-GCCcore-11.3.0.eb
Labels: update

#16017 {bio}[foss/2022a] SMC++ v1.15.4 w/ Python 3.10.4
  easybuild/easyconfigs/s/SMC++/SMC++-1.15.4-foss-2022a.eb
Labels: new

#16029 {data}[GCCcore/11.3.0] HDF5 v1.13.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.13.1-GCCcore-11.3.0-serial.eb
Labels: update

#16027 add patch to fix missing sync in LINCS and SETTLE CUDA kernels for GROMACS 2020 versions
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020-fosscuda-2019b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.3-fosscuda-2019b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020.5-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2020_add-missing-sync.patch
Labels: bug fix

#16026 add patch to fix missing sync in LINCS and SETTLE CUDA kernels for GROMACS 2021 versions
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021-fosscuda-2020b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.2-fosscuda-2020b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-foss-2021a-CUDA-11.3.1-PLUMED-2.7.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021_add-missing-sync.patch
Labels: bug fix

#16030 remove unecessary patch in recent JupyterLab
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-2.2.8-GCCcore-10.2.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.0.16-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.1.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.2.8-GCCcore-10.3.0.eb
Labels: code cleanup

#16036 {bio}[GCC/11.2.0] BBMap v38.98
  easybuild/easyconfigs/b/BBMap/BBMap-38.98-GCC-11.2.0.eb
Labels: update

#15856 add CVE patch for XZ 5.2.5 + attempt to fix symbol patch for all OSs
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.1.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.2.5_compat-libs.patch
  easybuild/easyconfigs/x/XZ/xz-5.2.5-cve-2022-1271.patch
Labels: bug fix

#16013 {bio}[GCCcore/11.2.0] Kalign v3.3.2
  easybuild/easyconfigs/k/Kalign/Kalign-3.3.2-GCCcore-11.2.0.eb
Labels: update

#16043 {lib}[GCCcore/11.2.0,GCCcore/11.3.0] libaec v1.0.6
  easybuild/easyconfigs/l/libaec/libaec-1.0.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.6-GCCcore-11.3.0.eb
Labels: update

#15978 {phys}[gompi/2021b] QuickPIC v20210224
  easybuild/easyconfigs/q/QuickPIC/QuickPIC-20210224-gompi-2021b.eb
  easybuild/easyconfigs/q/QuickPIC/QuickPIC-20210224_fix_paths_in_makefile.patch
Labels: new

#16048 {lib}[GCCcore/9.3.0] zfp v1.0.0
  easybuild/easyconfigs/z/zfp/zfp-1.0.0-GCCcore-9.3.0.eb
Labels: update

#16046 {lib}[GCCcore/11.2.0,GCCcore/9.3.0] Mini-XML v2.12, Mini-XML v3.3
  easybuild/easyconfigs/m/Mini-XML/Mini-XML-2.12-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/Mini-XML/Mini-XML-3.3.1-GCCcore-11.2.0.eb
Labels: update

#15675 {bio}[GCCcore/11.2.0,foss/2021b] medaka v1.6.0, intervaltree-python v3.1.0 w/ Python 3.9.6
  easybuild/easyconfigs/i/intervaltree-python/intervaltree-python-3.1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/medaka/medaka-1.6.0-foss-2021b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#16050 Skip NASA performance test in netCDF
  easybuild/easyconfigs/n/netCDF/netCDF-4.9.0-gompi-2022a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.9.0_skip-nasa-test.patch
Labels: bug fix

#15647 PLUMED version 2.8.0 added for GROMACS-2021.5
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-foss-2021a-PLUMED-2.7.2.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-foss-2021b-CUDA-11.4.1-PLUMED-2.8.0.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-foss-2021b-PLUMED-2.8.0.eb
Labels: update

#16047 {lang}[GCC/9.3.0] LuaJIT2-OpenResty v2.1-20220411
  easybuild/easyconfigs/l/LuaJIT2-OpenResty/LuaJIT2-OpenResty-2.1-20220411-GCC-9.3.0.eb
Labels: new

#16054 {lang}[GCCcore/11.2.0] CUnit v2.1-3
  easybuild/easyconfigs/c/CUnit/CUnit-2.1-3-GCCcore-11.2.0.eb
Labels: update

#16051 {devel}[foss/2022a] buildenv foss-2022a-CUDA-11.7.0
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2022a-CUDA-11.7.0.eb
Labels: update

#16058 {vis}[system/system] Blender v3.2.2
  easybuild/easyconfigs/b/Blender/Blender-3.2.2-linux-x64.eb
Labels: update

#16056 cutadapt: add pigz as dependency
  easybuild/easyconfigs/c/cutadapt/cutadapt-3.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-3.4-GCCcore-10.3.0.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-3.5-GCCcore-11.2.0.eb
Labels: enhancement

#16040 Include some EC constants in flake8 config
  setup.cfg
Labels: enhancement

#16041 {bio}[foss/2021b] GetOrganelle v1.7.6.1 w/ Python 3.9.6
  easybuild/easyconfigs/g/GetOrganelle/GetOrganelle-1.7.6.1-foss-2021b.eb
Labels: update

#16055 {data}[GCCcore/11.3.0] SoX w/ GCCcore/11.3.0 + additional format support
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-11.3.0.eb
Labels: update

#15949 {vis}[GCCcore/11.3.0] gnuplot v5.4.4
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.4-GCCcore-11.3.0.eb
Labels: update

#16070 update CI workflows to use Ubuntu 20.04 (since Ubuntu 18.04 is deprecated)
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: update, change, tests

#16065 {toolchain} GCC 12.2.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.39-GCCcore-12.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.39.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GCC/GCC-12.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-12.2.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12-GCCcore-12.2.0.eb
Labels: update

#16034 {devel}[system/system] ant v1.10.12
  easybuild/easyconfigs/a/ant/ant-1.10.12-Java-11.eb
Labels: update

#16067 {lib}[GCCcore/11.3.0] libmad v0.15.1b
  easybuild/easyconfigs/l/libmad/libmad-0.15.1b-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libmad/libmad-0.15.1b-remove-depreciated-gcc-option.patch
Labels: new

#16057 {bio}[system/system] FreeSurfer v7.3.2
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.3.2-centos8_x86_64.eb
Labels: update

#13375 use correct Matlab Runtime Compiler (v8.4) for FreeSurfer v7.1.1
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.1.1-centos6_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.1.1-centos7_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.1.1-centos8_x86_64.eb
Labels: bug fix

#16068 {bio}[GCC/11.3.0] Satsuma2 v20220304
  easybuild/easyconfigs/s/Satsuma2/Satsuma2-20220304-GCC-11.3.0.eb
  easybuild/easyconfigs/s/Satsuma2/Satsuma2-20220304_fix-GCC-11.patch
Labels: new

#16063 {data}[GCCcore/11.2.0] pugixml v1.12.1
  easybuild/easyconfigs/p/pugixml/pugixml-1.12.1-GCCcore-11.2.0.eb
Labels: update

#16074 {bio}[foss/2021b] BUSCO v5.4.3, MetaEuk v6 w/ Python 3.9.6
  easybuild/easyconfigs/b/BUSCO/BUSCO-5.4.3-foss-2021b.eb
  easybuild/easyconfigs/m/MetaEuk/MetaEuk-6-GCC-11.2.0.eb
Labels: update

#15973 refactor checksum test for extensions to use collect_exts_file_info
  test/easyconfigs/easyconfigs.py
Labels: bug fix, tests

#16012 {bio}[gompi/2021b] HH-suite v3.3.0
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-gompi-2021b.eb
Labels: update

#8583 {bio}[system] AptaSUITE v0.9.4 + JavaFX v11.0.2
  easybuild/easyconfigs/a/AptaSUITE/AptaSUITE-0.9.4-Java-11.eb
  easybuild/easyconfigs/j/JavaFX/JavaFX-11.0.2_linux-x64_bin-sdk.eb
Labels: new

#15953 {vis}[GCCcore/11.3.0] Graphviz v5.0.0 w/ Python 3.10.4
  easybuild/easyconfigs/g/Graphviz/Graphviz-5.0.0-GCCcore-11.3.0.eb
Labels: update

#16075 {bio}[foss/2021b] scikit-bio v0.5.7
  easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.5.7-foss-2021b.eb
Labels: update

#16091 add sanity check commands for recent gettext versions (>= 0.20.x)
  easybuild/easyconfigs/g/gettext/gettext-0.20.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.20.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.20.1.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.21.eb
Labels: enhancement

#16112 {tools/vis}[GCCcore/11.3.0] Ghostscript v9.56.1, GTK2 v2.24.33
  easybuild/easyconfigs/g/GTK2/GTK2-2.24.33-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.56.1-GCCcore-11.3.0.eb
Labels: update, change

#16111 {tools}[GCCcore/11.3.0] gperftools v2.10
  easybuild/easyconfigs/g/gperftools/gperftools-2.10-GCCcore-11.3.0.eb
Labels: update

#16107 add missing BCFtools dependency for recent medaka versions
  easybuild/easyconfigs/m/medaka/medaka-1.4.3-foss-2020b.eb
  easybuild/easyconfigs/m/medaka/medaka-1.5.0-foss-2021a.eb
  easybuild/easyconfigs/m/medaka/medaka-1.6.0-foss-2021b.eb
Labels: bug fix

#16042 Exclude failing test in TensorFlow 2.4.1
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-foss-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1-fosscuda-2020b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.1_add-ldl.patch
Labels: bug fix

#16108 {bio}[foss/2021b] NGSpeciesID v0.1.2.1 w/ Python 3.9.6
  easybuild/easyconfigs/n/NGSpeciesID/NGSpeciesID-0.1.2.1-foss-2021b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#16113 {bio}[GCC/11.3.0] PLINK v2.00a3.6
  easybuild/easyconfigs/p/PLINK/PLINK-2.00a3.6-GCC-11.3.0.eb
Labels: update

#16094 {vis}[GCCcore/11.3.0] bwidget v1.9.15, Togl v2.0, XCrySDen v1.6.2
  easybuild/easyconfigs/b/bwidget/bwidget-1.9.15-GCCcore-11.3.0.eb
  easybuild/easyconfigs/t/Togl/Togl-2.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2-foss-2022a.eb
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2-intel-2022a.eb
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2-no-bwidget-tcl-download.patch
Labels: update

#16119 {chem}[foss/2022a] ASE v3.22.1, Flask v2.2.2, spglib-python v2.0.0 w/ Python 3.10.4
  easybuild/easyconfigs/a/ASE/ASE-3.22.1-foss-2022a.eb
  easybuild/easyconfigs/f/Flask/Flask-2.2.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-2.0.0-foss-2022a.eb
Labels: update

#16073 {chem}[GCC/11.3.0] Libint 2.7.2 (lmax-6-cp2k variant)
  easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-11.3.0-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/Libint/Libint-2.7.2_remove-test-eri.patch
  easybuild/easyconfigs/l/Libint/Libint-2.7.2_remove-test-permute.patch
Labels: update

#14386 {chem}[foss/2021a] AmberTools v21 w/ Python 3.9.5
  easybuild/easyconfigs/a/AmberTools/AmberTools-21-foss-2021a.eb
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_CMake-FlexiBLAS.patch
Labels: update

#16077 {cae}[foss/2019b] RheoTool v5.0
  easybuild/easyconfigs/r/RheoTool/RheoTool-5.0-foss-2019b.eb
Labels: new

#15971 {bio}[foss/2021a] OpenFold v1.0.0, colossalai v0.1.8, einops v0.4.1, OpenMM 7.5.1 (incl. AlphaFold patch) w/ Python 3.9.5 + CUDA 11.3.1
  easybuild/easyconfigs/c/colossalai/colossalai-0.1.8-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/e/einops/einops-0.4.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/o/OpenFold/OpenFold-1.0.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.1-foss-2021a-DeepMind-patch.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.1_DeepMind.patch
Labels: new, update

#16126 make check for toolchain value in dependency spec in easyconfigs test suite aware that dumped easyconfig uses SYSTEM constant
  test/easyconfigs/easyconfigs.py
Labels: bug fix, change, tests

#16138 {bio}[GCC/11.3.0] VCFtools v0.1.16
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-GCC-11.3.0.eb
Labels: update

#16137 {chem}[foss/2021b] RDKit v2022.03.5 w/ Python 3.9.6
  easybuild/easyconfigs/r/RDKit/RDKit-2022.03.5-foss-2021b.eb
Labels: update

#16045 {data,phys}[foss/2020a] ADIOS v1.13.1, ADIOS v20210804 w/ Python 3.8.2
  easybuild/easyconfigs/a/ADIOS/ADIOS-1.13.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/ADIOS/ADIOS-20210804-foss-2020a-Python-3.8.2.eb
Labels: update

#16114 {lib}[GCCcore/11.3.0] tbb v2021.5.0
  easybuild/easyconfigs/t/tbb/tbb-2021.5.0-GCCcore-11.3.0.eb
Labels: update

#16115 {bio}[foss/2022a] muMerge v1.1.0 w/ Python 3.10.4
  easybuild/easyconfigs/m/muMerge/muMerge-1.1.0-foss-2022a.eb
Labels: new

#16120 {chem,phys}[foss/2022a] Elk v8.5.2, Wannier90 v3.1.0
  easybuild/easyconfigs/e/Elk/Elk-8.5.2-foss-2022a.eb
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-foss-2022a.eb
Labels: update

#16143 {bio}[foss/2021b] pyGenomeTracks v3.7 w/ Python 3.9.6
  easybuild/easyconfigs/p/pyGenomeTracks/pyGenomeTracks-3.7-foss-2021b.eb
Labels: new

#16105 {vis}[GCCcore/11.3.0] GLFW v3.3.8
  easybuild/easyconfigs/g/GLFW/GLFW-3.3.8-GCCcore-11.3.0.eb
Labels: update

#15972 {bio}[foss/2021a] FastFold v20220729 w/ Python 3.9.5
  easybuild/easyconfigs/f/FastFold/FastFold-20220729-foss-2021a-CUDA-11.3.1.eb
Labels: new

#15968 Numpy: Fix broken test on PPC
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-foss-2022a.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.22.3_skip-ppc-long-complex-test.patch
Labels: bug fix

#15957 speed up OpenMPI 4.1.4 configure by not running "autogen.pl --force", but only running required Autotools commands
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-11.3.0.eb
Labels: change, performance

#16149 {chem}[gomkl/2021a] Wannier90 3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-gomkl-2021a.eb
Labels: update

#15900 {chem}[foss/2021a,foss/2021b] LAMMPS v23Jun2022 w/ Python 3.9.5 + 3.9.6 and CUDA
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos-CUDA-11.3.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos-CUDA-11.4.1.eb
Labels: update

#16158 disable remote server tests for netCDF 4.9.0
  easybuild/easyconfigs/n/netCDF/netCDF-4.9.0-gompi-2022a.eb
Labels: bug fix

#16127 {math}[foss/2021b] PyStan v3.5.0
  easybuild/easyconfigs/p/PyStan/PyStan-3.5.0-foss-2021b.eb
Labels: update

#16142 {math}[foss/2020b]PyStan v2.19.1.1
  easybuild/easyconfigs/p/PyStan/PyStan-2.19.1.1-foss-2020b.eb
Labels: update

#16146 {tools}[GCCcore/12.1.0] cURL v7.84.0
  easybuild/easyconfigs/c/cURL/cURL-7.84.0-GCCcore-12.1.0.eb
Labels: update

#16148 {chem}[foss/2021b] AmberTools v21.12 w/ Python 3.9.6
  easybuild/easyconfigs/a/AmberTools/AmberTools-21.12-foss-2021b.eb
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_dont_include_config.h_in_top_Makefile.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_DGESVD_workspace_query.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_incorrect_dvout_call.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_incorrect_mexit_calls.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_more_blas_argument_problems.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_multiple_definition.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_potential_use_before_init.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_rism_argument_mismatch.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-21_fix_xray_fftpack_arg_mismatch.patch
  easybuild/easyconfigs/a/AmberTools/AmberTools-22_fix_test_missing_cuda_dir.patch
Labels: update

#15464 {numlib}[GCCcore/11.2.0] qrupdate v1.1.2
  easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCCcore-11.2.0.eb
Labels: update

#16087 {lib}[GCCcore/11.2.0] libpsl v0.21.1
  easybuild/easyconfigs/l/libpsl/libpsl-0.21.1-GCCcore-11.2.0.eb
Labels: update

#15046 {devel,lib}[GCCcore/10.3.0] wxPython v4.1.1, WebKitGTK+ v2.27.4, GConf v3.2.6, ... w/ Python 3.9.5
  easybuild/easyconfigs/d/dbus-glib/dbus-glib-0.112-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GConf/GConf-3.2.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LibSoup/LibSoup-2.74.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.27.4-GCC-10.3.0.eb
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.27.4_icuBOOL.patch
  easybuild/easyconfigs/w/wxPython/wxPython-4.1.1-foss-2021a.eb
  easybuild/easyconfigs/w/wxPython/wxPython-4.1.1_fix_install_path.patch
  easybuild/easyconfigs/w/wxPython/wxPython-4.1.1_use_bang_env_python.patch
Labels: update

#15834 {tools}[GCCcore/10.3.0] jupyter-resource-usage v0.6.1 w/ Python 3.9.5
  easybuild/easyconfigs/j/jupyter-resource-usage/jupyter-resource-usage-0.6.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/jupyter-resource-usage/jupyter-resource-usage-0.6.1_compatibility.patch
Labels: new

#15836 {lib}[system/system] cuTENSOR v1.6.0.3
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-1.6.0.3-CUDA-11.3.1.eb
Labels: update

#15827 {bio}[foss/2021a] Megalodon v2.5.0, ont-remora v1.0.0 w/ Python 3.9.5
  easybuild/easyconfigs/m/Megalodon/Megalodon-2.5.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/m/Megalodon/Megalodon-2.5.0-foss-2021a.eb
  easybuild/easyconfigs/m/Megalodon/Megalodon-2.5.0_fix-samtools-test.patch
  easybuild/easyconfigs/o/ont-remora/ont-remora-1.0.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/ont-remora/ont-remora-1.0.0-foss-2021a.eb
Labels: update

#16062 {lang}[system} Java/8 (OpenJDK)
  easybuild/easyconfigs/j/Java/Java-8.345.eb
  easybuild/easyconfigs/j/Java/Java-8.eb
Labels: update
