Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-09, with the labels that each got.

#16134 fix checksum for Stacks v2.62 (due to silent re-release without version bump)
  easybuild/easyconfigs/s/Stacks/Stacks-2.62-foss-2022a.eb
Labels: bug fix

#16153 replace HDF5 v1.13.1 with v1.12.1 as dependency, since we shouldn't use odd minor versions of HDF5 which are not stable releases
  easybuild/easyconfigs/g/GDAL/GDAL-3.5.0-foss-2022a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.2-GCCcore-11.3.0-serial.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.2-gompi-2022a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.12.2-iimpi-2022a.eb
  easybuild/easyconfigs/h/h5py/h5py-3.7.0-foss-2022a.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.9.0-gompi-2022a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-foss-2022a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-intel-2022a.eb
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix, update, change

#15939 {chem}[foss/2021b] cclib v1.7.2 w/ Python 3.9.6
  easybuild/easyconfigs/c/cclib/cclib-1.7.2-foss-2021b.eb
Labels: update

#15934 {numlib}[GCC/11.3.0] LAPACK v3.10.1
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.10.1-GCC-11.3.0.eb
Labels: update

#15940 {chem,devel}[GCCcore/11.3.0,gompi/2022a] OpenBabel v3.1.1, w/ Python 3.10.4
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2022a.eb
Labels: update

#16151 update AmberTools 21 for foss with EasyBuild set of patches for AT 21.12
  easybuild/easyconfigs/a/AmberTools/AmberTools-21-foss-2021a.eb
Labels: bug fix

#16152 update AmberTools 21 for intel with EasyBuild set of patches for AT 21.12
  easybuild/easyconfigs/a/AmberTools/AmberTools-21-intel-2021b.eb
Labels: bug fix

#16136 {chem}[foss/2021b] AmberTools v22.3 w/ Python 3.9.6
  easybuild/easyconfigs/a/AmberTools/AmberTools-22.3-foss-2021b.eb
  easybuild/easyconfigs/a/AmberTools/AmberTools-22_fix_missing_error_check_on_test_run.patch
Labels: update

#16176 {math}[GCCcore/11.3.0] Gurobi v9.5.2 w/ Python 3.10.4
  easybuild/easyconfigs/g/Gurobi/Gurobi-9.5.2-GCCcore-11.3.0.eb
Labels: update

#16175 {vis}[gompi/2022a] ncview v2.1.8
  easybuild/easyconfigs/n/ncview/ncview-2.1.8-gompi-2022a.eb
Labels: update

#16021 {cae}[foss/2021b] olaFlow v20210820
  easybuild/easyconfigs/o/olaFlow/olaFlow-20210820-foss-2021b.eb
Labels: new

#16071 {tools}[GCCcore/11.2.0] hiredis v1.0.2
  easybuild/easyconfigs/h/hiredis/hiredis-1.0.2-GCCcore-11.2.0.eb
Labels: new

#16085 {lib}[GCCcore/11.2.0] glib-networking v2.72.1
  easybuild/easyconfigs/g/glib-networking/glib-networking-2.72.1-GCCcore-11.2.0.eb
Labels: update

#16086 {lib}[GCC/11.2.0] libev v4.33
  easybuild/easyconfigs/l/libev/libev-4.33-GCC-11.2.0.eb
Labels: new

#16097 {lib}[GCCcore/11.2.0] nghttp3 v0.6.0
  easybuild/easyconfigs/n/nghttp3/nghttp3-0.6.0-GCCcore-11.2.0.eb
Labels: new

#16072 {tools}[GCCcore/11.2.0] ccache v4.6.1
  easybuild/easyconfigs/c/ccache/ccache-4.6.1-GCCcore-11.2.0.eb
Labels: update

#16053 {devel}[GCC/11.2.0,GCC/11.3.0] Jansson v2.13 + v2.14
  easybuild/easyconfigs/j/Jansson/Jansson-2.13.1-GCC-11.2.0.eb
  easybuild/easyconfigs/j/Jansson/Jansson-2.14-GCC-11.3.0.eb
Labels: update

#15938 {math,vis}[GCCcore/11.3.0] OpenFOAM v2206, ParaView v5.10.1, CGAL v4.14.3, ... w/ Python 3.10.4
  easybuild/easyconfigs/c/CGAL/CGAL-4.14.3-gompi-2022a.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2206-foss-2022a.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.10.1-foss-2022a-mpi.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.1-gompi-2022a.eb
Labels: update

#16167 remove modextrapaths to add top-level install directory to $PATH for recent InterProScan easyconfigs (now done by default by Binary easyblock)
  easybuild/easyconfigs/i/InterProScan/InterProScan-5.52-86.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/i/InterProScan/InterProScan-5.55-88.0-foss-2021a.eb
Labels: bug fix, code cleanup

#16121 {bio}[GCCcore/11.2.0] Porechop-0.2.4 w/Python/3.9.6
  easybuild/easyconfigs/p/Porechop/Porechop-0.2.4-GCCcore-11.2.0.eb
Labels: update

#16177 {bio}[GCC/11.2.0] Flye v2.9.1 w/ Python 3.9.6
  easybuild/easyconfigs/f/Flye/Flye-2.9.1-GCC-11.2.0.eb
Labels: update

#16168 {math}[foss/2022a] MUMPS v5.5.1
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.1-foss-2022a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.1_shared-mumps.patch
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.1_shared-pord.patch
Labels: update

#16197 {tools}[GCCcore/11.3.0] fio v3.32
  easybuild/easyconfigs/f/fio/fio-3.32-GCCcore-11.3.0.eb
Labels: update

#15860 {phys}[foss/2021b] BigDFT v1.9.1
  easybuild/easyconfigs/b/BigDFT/BigDFT-1.9.1-foss-2021b.eb
  easybuild/easyconfigs/b/BigDFT/BigDFT-1.9.1_fix-index-bug.patch
Labels: new

#15331 {mpi}[GCC/10.2.0] OpenMPI v4.1.2
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-GCC-10.2.0.eb
Labels: update

#16076 {lang}[GCCcore/12.1.0] Perl v5.36.0
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-12.1.0.eb
  easybuild/easyconfigs/e/expat/expat-2.4.8-GCCcore-12.1.0.eb
  easybuild/easyconfigs/g/groff/groff-1.22.4-GCCcore-12.1.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1.2-GCCcore-12.1.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.3-GCCcore-12.1.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.36.0-GCCcore-12.1.0.eb
Labels: update

#13040 {lib}[GCCcore/9.3.0] libplinkio v0.9.8
  easybuild/easyconfigs/l/libplinkio/libplinkio-0.9.8-GCCcore-9.3.0.eb
Labels: new

#16210 add sanity check commands for Dakota v6.16.0
  easybuild/easyconfigs/d/Dakota/Dakota-6.16.0-foss-2021b.eb
Labels: enhancement

#16192 {perf}[gompi/2021b,gompi/2022a] OSU-Micro-Benchmarks v5.9
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.9-gompi-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.9-gompi-2022a-CUDA-11.7.0.eb
Labels: update

#16191 {bio}[GCCcore/11.2.0] pftoolsV3 v3.2.12
  easybuild/easyconfigs/l/libharu/libharu-2.3.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/pftoolsV3/pftoolsV3-3.2.12-GCCcore-11.2.0.eb
Labels: update

#16219 fix sources + source URL + homepage for Molekel v5.4.0
  easybuild/easyconfigs/m/Molekel/Molekel-5.4.0-Linux_x86_64.eb
Labels: bug fix

#16208 {lib}[GCCcore/11.3.0] fmt v9.1.0
  easybuild/easyconfigs/f/fmt/fmt-9.1.0-GCCcore-11.3.0.eb
Labels: update

#16217 {vis}[system/system] VESTA v3.5.8
  easybuild/easyconfigs/v/VESTA/VESTA-3.5.8-gtk3.eb
Labels: new

#16064 Use versioned syms in system level ncurses
  easybuild/easyconfigs/n/ncurses/ncurses-6.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.1.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.2.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.3.eb
Labels: bug fix

#15743 fix set-alias statements for MaxQuant v2.0.3.0
  easybuild/easyconfigs/m/MaxQuant/MaxQuant-2.0.3.0-GCCcore-11.2.0.eb
Labels: bug fix

#15908 {bio}[GCCcore/10.3.0] alevin-fry v0.6.0
  easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.6.0-GCCcore-10.3.0.eb
Labels: update

#16198 {tools}[GCCcore/11.3.0] nano v6.4
  easybuild/easyconfigs/n/nano/nano-6.4-GCCcore-11.3.0.eb
Labels: new

#16102 add patch to fix pkgconfig file for Blitz++ v1.0.2
  easybuild/easyconfigs/b/Blitz++/Blitz++-1.0.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/b/Blitz++/Blitz++-1.0.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/b/Blitz++/blitz-1.0.2_pkgconfig.patch
Labels: bug fix

#14706 {chem}[iimpi/2020a] OpenBabel v3.1.1 w/ Python 3.8.2
  easybuild/easyconfigs/c/CoordgenLibs/CoordgenLibs-3.0.1-iimpi-2020a.eb
  easybuild/easyconfigs/m/maeparser/maeparser-1.3.0-iimpi-2020a.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-iimpi-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1_fix-CoordgenLibs-no-templates.patch
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1_fix-testobconv_writers.patch
Labels: update

#16220 {bio}[foss/2021b] how_are_we_stranded_here v1.0.1 w/ Python 3.9.6
  easybuild/easyconfigs/h/how_are_we_stranded_here/how_are_we_stranded_here-1.0.1-foss-2021b.eb
  easybuild/easyconfigs/h/how_are_we_stranded_here/kallisto-0.44.0-include_limits.patch
Labels: new

#16124 {tools}[GCCcore/10.2.0] Emacs v28.1
  easybuild/easyconfigs/e/Emacs/Emacs-28.1-GCCcore-10.2.0.eb
Labels: update

#15981 simplify AlphaFold foss/2021a easyconfigs by using a fleshed out patched OpenMM dependency
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.1.2-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.1.2-foss-2021a.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.2.2-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.2.2-foss-2021a.eb
Labels: change

#16023 {data,lib}[GCCcore/11.3.0] BeautifulSoup v4.10.0, FORD v6.1.15 + add patch & missing deps for Graphviz
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.10.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/FORD/FORD-6.1.15-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-5.0.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-5.0.0_skip-install-data-hook.patch
Labels: update

#16225 consistently add libffi + elfutils dependencies to recent Clang easyconfigs
  easybuild/easyconfigs/c/Clang/Clang-11.0.1-gcccuda-2020b.eb
  easybuild/easyconfigs/c/Clang/Clang-12.0.1-GCCcore-10.3.0-CUDA-11.3.1.eb
  easybuild/easyconfigs/c/Clang/Clang-12.0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb
  easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.3.0.eb
Labels: bug fix

#16145 fix libsanitzer for glibc 2.36 to build GCCcore 11.3.0
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11_fix-libsanitzer-glibc-2.36.patch
Labels: bug fix

#16227 also update $PYTHONPATH for how_are_we_stranded_here + add sanity check command
  easybuild/easyconfigs/h/how_are_we_stranded_here/how_are_we_stranded_here-1.0.1-foss-2021b.eb
Labels: bug fix

#16228 {math}[foss/2022a] Pyomo v6.4.2 w/ Python 3.10.4
  easybuild/easyconfigs/p/Pyomo/Pyomo-6.4.2-foss-2022a.eb
Labels: update

#16150 fix top level Makefile for AmberTools 20 and enable tests
  easybuild/easyconfigs/a/AmberTools/AmberTools-20-intel-2020a-Python-3.8.2.eb
Labels: bug fix

#15829 {bio,tools}[foss/2022a] R-bundle-Bioconductor v3.15, arrow-R v8.0.0
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2022a.eb
  easybuild/easyconfigs/a/arrow-R/arrow-R-8.0.0-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2022a-R-4.2.1.eb
Labels: update

#15919 add and fix patches for PyTorch 1.9.0 on POWER
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0-foss-2020b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0-fosscuda-2020b-imkl.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0-fosscuda-2020b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0_fix-kineto-crash.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0_fix-vsx-vector-functions.patch
Labels: bug fix

#16234 fix checksum for CUDA 11.4.1 aarch64 installer
  easybuild/easyconfigs/c/CUDA/CUDA-11.4.1.eb
Labels: bug fix

#16209 {tools}[GCCcore/11.3.0] indicators v2.2
  easybuild/easyconfigs/i/indicators/indicators-2.2-GCCcore-11.3.0.eb
Labels: new

#16229 {bio}[system/system] Chimera v1.16
  easybuild/easyconfigs/c/Chimera/Chimera-1.16-linux_x86_64.eb
Labels: update

#16231 consistently add maeparser + CoordgenLibs dependencies to OpenBabel v3.1.1 easyconfigs
  easybuild/easyconfigs/c/CoordgenLibs/CoordgenLibs-3.0.1-gompi-2019b.eb
  easybuild/easyconfigs/c/CoordgenLibs/CoordgenLibs-3.0.1-gompi-2021a.eb
  easybuild/easyconfigs/c/CoordgenLibs/CoordgenLibs-3.0.1-gompi-2022a.eb
  easybuild/easyconfigs/m/maeparser/maeparser-1.3.0-gompi-2019b.eb
  easybuild/easyconfigs/m/maeparser/maeparser-1.3.0-gompi-2021a.eb
  easybuild/easyconfigs/m/maeparser/maeparser-1.3.0-gompi-2022a.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2021a.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2022a.eb
Labels: bug fix

#15882 exclude (flaky) fault_tolerance_test and fix non-x86 build for TensorFlow 2.7.1
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1_remove-io-gcs-dependency.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1_remove-libclang-dependency.patch
Labels: bug fix

#16238 remove incorrect comment for Boost dependency in OpenBabel 3.1.1 easyconfigs
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2021a.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-gompi-2022a.eb
  easybuild/easyconfigs/o/OpenBabel/OpenBabel-3.1.1-iimpi-2020a-Python-3.8.2.eb
Labels: bug fix

#16226 {bio}[system/system] mgltools v1.5.7
  easybuild/easyconfigs/m/mgltools/mgltools-1.5.7.eb
Labels: new

#16214 {cae}[system/system] STAR-CCM+ v17.02.008, STAR-CCM+ v17.04.008
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.02.008-r8.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.02.008.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.04.008-r8.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.04.008.eb
Labels: update

#16237 add direct Pango dependency in recent ImageMagick easyconfigs
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.10-1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.10-35-GCCcore-10.2.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.11-14-GCCcore-10.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.9-5-GCCcore-8.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-37-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-4-GCCcore-11.2.0.eb
Labels: bug fix

#16232 prepare release notes for EasyBuild v4.6.1 + bump version to 4.6.1
  RELEASE_NOTES
  setup.py
Labels: update

#16240 {tools}[system/system] EasyBuild v4.6.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.6.1.eb
Labels: update

#16243 sync with main + bump version to 4.6.2dev
  RELEASE_NOTES
  setup.py
Labels: update

#16223 {compiler}[system/system] Go v1.18.3
  easybuild/easyconfigs/g/Go/Go-1.18.3.eb
Labels: update

#16221 {tools}[system/system] Miller v6.4.0
  easybuild/easyconfigs/m/Miller/Miller-6.4.0.eb
Labels: new

#16244 {data}[GCCcore/11.3.0] BioPerl v1.7.8, DB_File v1.858, XML-LibXML v2.0207
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.858-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0207-GCCcore-11.3.0.eb
Labels: update

#16195 {devel}[GCCcore/11.3.0] xproto v7.0.31
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-11.3.0.eb
Labels: update

#16252 {bio}[foss/2021b] AutoDock-Vina v1.2.3 w/ Python 3.9.6
  easybuild/easyconfigs/a/AutoDock-Vina/AutoDock-Vina-1.2.3-foss-2021b.eb
Labels: update

#16189 {bio}[GCC/11.2.0,GCC/11.3.0] SAMtools v1.16.1
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.16.1-GCC-11.2.0.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.16.1-GCC-11.3.0.eb
Labels: update

#16186 {math}[foss/2022a] SUNDIALS v6.3.0
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-6.3.0-foss-2021b.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-6.3.0-foss-2022a.eb
Labels: update

#16194 {devel}[GCCcore/11.3.0] xtrans v1.3.5
  easybuild/easyconfigs/x/xtrans/xtrans-1.3.5-GCCcore-11.3.0.eb
Labels: update

#16254 {devel}[gompi/2022a] NVSHMEM v2.5.0
  easybuild/easyconfigs/n/NVSHMEM/NVSHMEM-2.5.0-gompi-2022a-CUDA-11.7.0.eb
Labels: new

#16262 {chem}[foss/2022a] libcint v5.1.6
  easybuild/easyconfigs/l/libcint/libcint-5.1.6-foss-2022a.eb
Labels: update

#16275 {numlib}[foss/2022a] SuiteSparse v5.13.0
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.13.0-foss-2022a-METIS-5.1.0.eb
Labels: update

#15921 {math}[foss/2022a] magma v2.6.2
  easybuild/easyconfigs/m/magma/magma-2.6.2-foss-2022a-CUDA-11.7.0.eb
Labels: update

#16199 Fix miscomputation in OpenBLAS on POWER
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.12-GCC-10.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.12_add-missing-params-for-power.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7-GCC-8.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.7_add-missing-params-for-power.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.9-GCC-9.3.0.eb
Labels: bug fix

#16293 {vis}[GCCcore/11.3.0] Pillow-SIMD v9.2.0 w/ Python 3.10.4
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-9.2.0-GCCcore-11.3.0.eb
Labels: update

#16297 {chem}[foss/2021b,intel/2021b] GPAW v22.8.0, ASE v3.22.1, spglib-python v1.16.3 w/ Python 3.9.6
  easybuild/easyconfigs/a/ASE/ASE-3.22.1-foss-2021b.eb
  easybuild/easyconfigs/a/ASE/ASE-3.22.1-intel-2021b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-22.8.0-Remove-MPI-compiler-hack.patch
  easybuild/easyconfigs/g/GPAW/GPAW-22.8.0-foss-2021b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-22.8.0-intel-2021b.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.3-foss-2021b.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.3-intel-2021b.eb
Labels: update

#16305 {phys}[intel/2022a] FDS v6.7.9
  easybuild/easyconfigs/f/FDS/FDS-6.7.9-intel-2022a.eb
Labels: update

#14011 {phys}[foss/2020b,fosscuda/2020b] pyqstem v1.0.3 w/ Python 3.8.6
  easybuild/easyconfigs/p/pyqstem/pyqstem-1.0.3-foss-2020b-ASE-3.22.0.eb
  easybuild/easyconfigs/p/pyqstem/pyqstem-1.0.3-fosscuda-2020b-ASE-3.22.0.eb
Labels: update

#16301 {vis}[intel/2022a] matplotlib v3.5.2 w/ Python 3.10.4
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.5.2-intel-2022a.eb
Labels: update

#16098 {lib}[GCCcore/11.2.0] ngtcp2 v0.7.0
  easybuild/easyconfigs/n/ngtcp2/ngtcp2-0.7.0-GCC-11.2.0.eb
Labels: new

#16096 {lib}[GCC/11.2.0] nghttp2 v1.48.0 w/ Python 3.9.6
  easybuild/easyconfigs/n/nghttp2/nghttp2-1.48.0-GCC-11.2.0.eb
Labels: new

#16089 {vis}[GCCcore/11.2.0] Wayland v1.21.0
  easybuild/easyconfigs/w/Wayland/Wayland-1.21.0-GCCcore-11.2.0.eb
Labels: update

#16095 {lib}[GCC/11.2.0] LibSoup v3.0.7
  easybuild/easyconfigs/l/LibSoup/LibSoup-3.0.7-GCC-11.2.0.eb
Labels: update

#16083 {tools}[GCCcore/11.2.0] hunspell v1.7.1
  easybuild/easyconfigs/h/hunspell/hunspell-1.7.1-GCCcore-11.2.0.eb
Labels: update

#16092 {lib}[GCCcore/11.2.0] Waylandpp v1.0.0
  easybuild/easyconfigs/w/Waylandpp/Waylandpp-1.0.0-GCCcore-11.2.0.eb
Labels: new

#16164 {tools}[GCC/11.2.0] gawk v5.1.1
  easybuild/easyconfigs/g/gawk/gawk-5.1.1-GCC-11.2.0.eb
Labels: update

#16082 {tools}[GCCcore/11.2.0] enchant-2 v2.3.3
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.3.3-GCCcore-11.2.0.eb
Labels: new

#16290 {tools}[GCC/11.3.0] likwid v5.2.2
  easybuild/easyconfigs/l/likwid/likwid-5.2.2-GCC-11.3.0.eb
Labels: update

#8441 {phys}[foss/2019a] PRISMS-PF v2.1.1, p4est v2.2, deal.II v9.1.1
  easybuild/easyconfigs/d/deal.II/deal.II-9.1.1-foss-2019a.eb
  easybuild/easyconfigs/p/PRISMS-PF/PRISMS-PF-2.1.1-foss-2019a.eb
  easybuild/easyconfigs/p/p4est/p4est-2.2-foss-2019a.eb
Labels: new

#16306 {data}[GCC/11.3.0] MariaDB v10.9.3, libaio v0.3.112, LZO v2.10, Judy v1.0.5
  easybuild/easyconfigs/j/Judy/Judy-1.0.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libaio/libaio-0.3.112-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.9.3-GCC-11.3.0.eb
Labels: update

#15798 {bio,lib,numlib}[GCC/10.3.0] Beast v2.6.7, beagle-lib v3.1.2, pocl v1.8
  easybuild/easyconfigs/b/Beast/Beast-2.6.7-GCC-10.3.0.eb
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.1.2-GCC-10.3.0.eb
  easybuild/easyconfigs/p/pocl/pocl-1.8-GCC-10.3.0.eb
Labels: update

#16285 {tools}[GCCcore/11.2.0] expecttest v0.1.3 w/ Python 3.9.6
  easybuild/easyconfigs/e/expecttest/expecttest-0.1.3-GCCcore-11.2.0.eb
Labels: update

#16283 {lib}[foss/2021a] imgaug v0.4.0 w/ Python 3.9.5
  easybuild/easyconfigs/i/imgaug/imgaug-0.4.0-foss-2021a.eb
Labels: update

#16277 {tools}[GCC/11.3.0] ncdu v1.17
  easybuild/easyconfigs/n/ncdu/ncdu-1.17-GCC-11.3.0.eb
Labels: update

#16279 {lib}[system/system] libtool v2.4.7
  easybuild/easyconfigs/l/libtool/libtool-2.4.7.eb
Labels: update

#16307 {bio}[GCC/11.3.0] VEP v107, Archive-Zip v1.68, DBD-mysql v4.050, ...
  easybuild/easyconfigs/a/Archive-Zip/Archive-Zip-1.68-GCCcore-11.3.0.eb
  easybuild/easyconfigs/b/Bio-DB-HTS/Bio-DB-HTS-3.01-GCC-11.3.0.eb
  easybuild/easyconfigs/c/Compress-Raw-Zlib/Compress-Raw-Zlib-2.202-GCCcore-11.3.0.eb
  easybuild/easyconfigs/d/DBD-mysql/DBD-mysql-4.050-GCC-11.3.0.eb
  easybuild/easyconfigs/v/VEP/VEP-107-GCC-11.3.0.eb
Labels: new, update

#16292 {lib,vis}[GCC/11.3.0,GCCcore/11.3.0] SDL2 v2.0.22, wxWidgets v3.2.1
  easybuild/easyconfigs/s/SDL2/SDL2-2.0.22-GCCcore-11.3.0.eb
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.2.1-GCC-11.3.0.eb
Labels: update

#16310 {data}[intel/2022a] scikit-learn v1.1.2 w/ Python 3.10.4
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.1.2-intel-2022a.eb
Labels: update

#16308 {lib,tools}[GCCcore/11.3.0,foss/2022a] GitPython v3.1.27, buildingspy v4.0.0 w/ Python 3.10.4
  easybuild/easyconfigs/b/buildingspy/buildingspy-4.0.0-foss-2022a.eb
  easybuild/easyconfigs/g/GitPython/GitPython-3.1.27-GCCcore-11.3.0.eb
Labels: new, update

#16309 {numlib}[foss/2020b,foss/2022a,intel/2020b,intel/2022a] SuperLU v5.3.0
  easybuild/easyconfigs/s/SuperLU/SuperLU-5.3.0-foss-2020b.eb
  easybuild/easyconfigs/s/SuperLU/SuperLU-5.3.0-foss-2022a.eb
  easybuild/easyconfigs/s/SuperLU/SuperLU-5.3.0-intel-2020b.eb
  easybuild/easyconfigs/s/SuperLU/SuperLU-5.3.0-intel-2022a.eb
Labels: update

#16315 {math}[foss/2022a,intel/2022a] LMfit v1.0.3 w/ Python 3.10.4
  easybuild/easyconfigs/l/LMfit/LMfit-1.0.3-foss-2022a.eb
  easybuild/easyconfigs/l/LMfit/LMfit-1.0.3-intel-2022a.eb
Labels: update

#16312 {chem}[intel/2022a] spglib-python v2.0.0 w/ Python 3.10.4
  easybuild/easyconfigs/s/spglib-python/spglib-python-2.0.0-intel-2022a.eb
Labels: update

#16311 {chem}[intel/2022a] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-intel-2022a.eb
Labels: update

#16319 add missing build dep pkg-config to enchant-2
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.3.3-GCCcore-11.2.0.eb
Labels: bug fix

#16182 {geo}[foss/2022a] ESMF v8.3.0
  easybuild/easyconfigs/e/ESMF/ESMF-8.3.0-foss-2022a.eb
Labels: update

#16303 {lib}[foss/2021a] umap-learn v0.5.3 w/ Python 3.9.5
  easybuild/easyconfigs/u/umap-learn/umap-learn-0.5.3-foss-2021a.eb
Labels: update

#16323 {data}[GCCcore/11.3.0] PostgreSQL v14.4
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-14.4-GCCcore-11.3.0.eb
Labels: update

#16300 {lib}[GCCcore/11.2.0] python-irodsclient v1.1.4 w/ Python 3.9.5
  easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-11.2.0.eb
Labels: new

#16295 {lib}[foss/2022a] tensorboard v2.10.0 w/ Python 3.10.4
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.10.0-foss-2022a.eb
Labels: update

#16321 {numlib}[iimpi/2022a] FFTW v3.3.10
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-iimpi-2022a.eb
Labels: update

#16257 {vis}[system/system] Avogadro2 v1.97.0
  easybuild/easyconfigs/a/Avogadro2/Avogadro2-1.97.0-linux-x86_64.eb
Labels: new

#16320 {bio}[GCCcore/10.3.0,GCCcore/11.2.0] paladin v1.4.6
  easybuild/easyconfigs/p/paladin/paladin-1.4.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/paladin/paladin-1.4.6-GCCcore-11.2.0.eb
Labels: new

#16334 {vis}[GCCcore/11.3.0] xprop v1.2.5, FLTK v1.3.8
  easybuild/easyconfigs/f/FLTK/FLTK-1.3.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/xprop/xprop-1.2.5-GCCcore-11.3.0.eb
Labels: update

#16331 {bio}[foss/2021a] pairsnp v0.0.7 w/ Python 3.9.5
  easybuild/easyconfigs/p/pairsnp/pairsnp-0.0.7-foss-2021a.eb
Labels: new

#16328 add new python-irodsclient easyconfig
  easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-10.3.0.eb
Labels: update

#16261 {bio}[GCC/11.2.0] AGAT 0.9.2
  easybuild/easyconfigs/a/AGAT/AGAT-0.9.2-GCC-11.2.0.eb
Labels: new

#16333 {bio}[GCC/11.3.0] TRUST4 v1.0.7 w/ Python 3.10.4
  easybuild/easyconfigs/t/TRUST4/TRUST4-1.0.7-GCC-11.3.0.eb
Labels: update

#16335 {perf}[gompi/2021a] Score-P v7.1
  easybuild/easyconfigs/s/Score-P/Score-P-7.1-gompi-2021a-CUDA-11.3.1.eb
Labels: update

#16324 {devel}[system/system] PyCharm v2022.2.2
  easybuild/easyconfigs/p/PyCharm/PyCharm-2022.2.2.eb
Labels: update

#15503 {bio}[foss/2021a] OpenMM v7.7.0 w/ Python 3.9.5
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.7.0-foss-2021a-CUDA-11.3.1.eb
Labels: update

#16338 {tools}[GCCcore/11.3.0,system/system] ccache v4.6.3, hiredis v1.0.2
  easybuild/easyconfigs/c/ccache/ccache-4.6.3.eb
  easybuild/easyconfigs/h/hiredis/hiredis-1.0.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/h/hiredis/hiredis-1.0.2_build-also-static-library.patch
  easybuild/easyconfigs/h/hiredis/hiredis-1.0.2_use-same-name-for-static-lib.patch
Labels: update

#16340 {tools}[system/system] htop v3.2.1
  easybuild/easyconfigs/h/htop/htop-3.2.1.eb
Labels: update
