Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2022-03, with the labels that each got.

#15016 {math}[system/system] MCR vR2021b
  easybuild/easyconfigs/m/MCR/MCR-R2021b.2.eb
Labels: update

#15062 {bio}[GCCcore/11.2.0,foss/2021b] GetOrganelle v1.7.5.3, Bandage v0.9.0 w/ Python 3.9.6
  easybuild/easyconfigs/b/Bandage/Bandage-0.9.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GetOrganelle/GetOrganelle-1.7.5.3-foss-2021b.eb
Labels: update

#13983 {cae}[system/system] FLUENT v2021R2
  easybuild/easyconfigs/f/FLUENT/FLUENT-2021R2.eb
Labels: update

#15067 {cae}[foss/2020a] porefoam v2021-09-21
  easybuild/easyconfigs/p/porefoam/porefoam-2021-09-21-foss-2020a.eb
  easybuild/easyconfigs/p/porefoam/porefoam-2021-09-21_fix-scotch-linking.patch
Labels: new

#13888 {cae}[system/system] ABAQUS v2021 (hotfix 2132)
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2021-hotfix-2132.eb
Labels: update

#15064 {bio}[system/system] MEGAN v6.22.0
  easybuild/easyconfigs/m/MEGAN/MEGAN-6.22.0-Java-17.eb
Labels: new

#15071 {bio}[foss/2020b] Infernal v1.1.4
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-foss-2020b.eb
Labels: update

#15081 {tools}[system/system] vsc-mympirun v5.2.9
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.9.eb
Labels: update

#15078 {bio,lib}[GCC/10.3.0] spoa v4.0.7, pyspoa v0.0.8 w/ Python 3.9.5
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.8-GCC-10.3.0.eb
  easybuild/easyconfigs/s/spoa/spoa-4.0.7-GCC-10.3.0.eb
Labels: update

#15077 {bio}[foss/2021a] WhatsHap v1.1 w/ Python 3.9.5
  easybuild/easyconfigs/w/WhatsHap/WhatsHap-1.1-foss-2021a.eb
Labels: update

#15076 {bio}[GCCcore/10.3.0] intervaltree-python v3.1.0 w/ Python 3.9.5
  easybuild/easyconfigs/i/intervaltree-python/intervaltree-python-3.1.0-GCCcore-10.3.0.eb
Labels: update

#15079 {bio}[foss/2021a] ont-fast5-api v4.0.0 w/ Python 3.9.5
  easybuild/easyconfigs/o/ont-fast5-api/ont-fast5-api-4.0.0-foss-2021a.eb
Labels: update

#14942 downgrade dependency on nodejs + use jupyter-server-proxy in jupyter-matlab-proxy and configurable-http-proxy easyconfigs using GCCcore/10.3.0 toolchain
  easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.4.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/jupyter-matlab-proxy/jupyter-matlab-proxy-0.3.4-GCCcore-10.3.0.eb
Labels: bug fix, change

#15024 {lang}[GCCcore/10.3.0] CCL v1.12.1, SBCL v2.2.1
  easybuild/easyconfigs/c/CCL/CCL-1.12.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/SBCL/SBCL-2.2.1-GCCcore-10.3.0.eb
Labels: update

#15085 {bio}[foss/2020b] BUSCO v4.0.6 w/ Python 3.8.6
  easybuild/easyconfigs/b/BUSCO/BUSCO-4.0.6-foss-2020b.eb
Labels: update

#15086 libffi 3.4.2 - disable-exec-static-tramp
  easybuild/easyconfigs/l/libffi/libffi-3.4.2-GCCcore-11.2.0.eb
Labels: bug fix

#10448 {bio}[iccifort/2019.5.281] Stacks v2.53
  easybuild/easyconfigs/s/Stacks/Stacks-2.53-iccifort-2019.5.281.eb
Labels: update

#15087 {bio}[GCCcore/11.2.0] GATK 4.2.5.0 w/Java-11
  easybuild/easyconfigs/g/GATK/GATK-4.2.5.0-GCCcore-11.2.0-Java-11.eb
Labels: update

#15088 {tools}[system/system] vsc-mympirun v5.2.10
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.10.eb
Labels: update

#15098 add hash R library as extension to R v4.1.2 easyconfig
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: enhancement

#15084 {vis}[GCCcore/10.2.0] matplotlib-inline v0.1.3
  easybuild/easyconfigs/m/matplotlib-inline/matplotlib-inline-0.1.3-GCCcore-10.2.0.eb
Labels: new

#15102 {lib}[GCCcore/11.2.0] Abseil v20210324.2
  easybuild/easyconfigs/a/Abseil/Abseil-20210324.2-GCCcore-11.2.0.eb
Labels: new

#15097 set XLA_PYTHON_CLIENT_ALLOCATOR=platform in jax CUDA easyconfigs
  easybuild/easyconfigs/j/jax/jax-0.2.19-fosscuda-2020b.eb
  easybuild/easyconfigs/j/jax/jax-0.2.24-foss-2021a-CUDA-11.3.1.eb
Labels: bug fix

#15101 {lib}[GCCcore/11.2.0] c-ares v1.18.1
  easybuild/easyconfigs/c/c-ares/c-ares-1.18.1-GCCcore-11.2.0.eb
Labels: update

#15099 remove disable flag for RTTI in snappy v1.1.9
  easybuild/easyconfigs/s/snappy/snappy-1.1.9-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/snappy/snappy-1.1.9_use-default-rtti.patch
Labels: bug fix

#15117 add nabor + harmony extensions to R v4.1.2 easyconfig
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: enhancement

#15114 {math}[foss/2021b] update toolchain for JAGS-4.3.0
  easybuild/easyconfigs/j/JAGS/JAGS-4.3.0-foss-2021b.eb
Labels: update

#15107 update deepTools
  easybuild/easyconfigs/d/deepTools/deepTools-3.5.1-foss-2021b.eb
Labels: update

#15108 {devel}[GCC/10.3.0] texlive v20210324
  easybuild/easyconfigs/g/graphite2/graphite2-1.3.14-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/texlive/texlive-20210324-GCC-10.3.0.eb
Labels: update

#15095 {vis}[foss/2020b,intel/2020b] matplotlib v3.5.1 w/ Python 3.8.6
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.5.1-foss-2020b.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.5.1-intel-2020b.eb
Labels: update

#15082 {bio}[foss/2021a] MAGeCK v0.5.9.4 w/ Python 3.9.5
  easybuild/easyconfigs/m/MAGeCK/MAGeCK-0.5.9.4-foss-2021a.eb
Labels: new

#15019 {lib}[foss/2021a] TensorFlow v2.5.3 w/ Python 3.9.5
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix-compatibility-with-CUDA-11.3.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix-compatibility-with-protobuf-3.17.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.3-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.3-foss-2021a.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.3_relax-required-versions.patch
Labels: update

#15092 {numlib}[GCC/11.2.0] OpenBLAS v0.3.20
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.2.0.eb
Labels: update

#15103 {lib}[GCCcore/11.2.0] gRPC v1.44.0
  easybuild/easyconfigs/g/gRPC/gRPC-1.44.0-GCCcore-11.2.0.eb
Labels: new

#15113 add rMATS_P cli tools
  easybuild/easyconfigs/r/rMATS-turbo/rMATS-turbo-4.1.1-foss-2020b.eb
Labels: enhancement

#15112 update SOCI
  easybuild/easyconfigs/s/SOCI/SOCI-4.0.3-GCC-11.2.0.eb
Labels: update

#15115 {tools}[system/system] tmux v3.2a
  easybuild/easyconfigs/l/libevent/libevent-2.1.12.eb
  easybuild/easyconfigs/t/tmux/tmux-3.2a.eb
Labels: update

#15126 consistently use system toolchain in EasyBuild easyconfigs
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.9.4.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.0.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.0.1.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.1.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.1.1.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.1.2.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.2.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.2.1.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.2.2.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.1.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.2.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.3.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.3.4.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.1.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.2.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.1.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.2.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.3.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix, change

#15080 {bio}[foss/2021a] medaka v1.5.0 w/ Python 3.9.5
  easybuild/easyconfigs/m/medaka/medaka-1.5.0-foss-2021a.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#15131 {bio}[foss/2021b] loompy v3.0.7 w/ Python 3.9.6
  easybuild/easyconfigs/l/loompy/loompy-3.0.7-foss-2021b.eb
Labels: update

#15132 {bio,lang}[intel/2021b] loompy v3.0.7, numba v0.54.1 w/ Python 3.9.6
  easybuild/easyconfigs/l/loompy/loompy-3.0.7-intel-2021b.eb
  easybuild/easyconfigs/n/numba/numba-0.54.1-intel-2021b.eb
Labels: update

#15118 add chromVAR extension to easyconfig for Bioconductor v3.14
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.14-foss-2021b-R-4.1.2.eb
Labels: enhancement

#15141 add apcluster, DataCombine, docstring, gdalUtils, openair, mstate, SNFtool, and deps to R v4.1.2 ec
  easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb
Labels: enhancement

#12286 {bio}[GCCcore/9.3.0] parallel-fastq-dump v0.6.6 w/ Python 3.8.2
  easybuild/easyconfigs/p/parallel-fastq-dump/parallel-fastq-dump-0.6.6-GCCcore-9.3.0-Python-3.8.2.eb
Labels: update

#15154 add EnsDb.Hsapiens.v79 extension to R-bundle-Bioconductor v3.14
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.14-foss-2021b-R-4.1.2.eb
Labels: enhancement

#15156 {tools}[system/system] VTune v2022.2.0
  easybuild/easyconfigs/v/VTune/VTune-2022.2.0.eb
Labels: update

#15160 {bio}[GCCcore/10.3.0] canu v2.2
  easybuild/easyconfigs/c/canu/canu-2.2-GCCcore-10.3.0-Java-11.eb
Labels: update

#15119 {bio,math}[foss/2021b] ArchR v1.0.1, presto v1.0.0-20200718 w/ R v4.1.2
  easybuild/easyconfigs/a/ArchR/ArchR-1.0.1-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/p/presto/presto-1.0.0-20200718-foss-2021b-R-4.1.2.eb
Labels: new

#15158 {devel}[foss/2021a] ONNX v1.11.0, ONNX-Runtime v1.10.0 w/ Python 3.9.5
  easybuild/easyconfigs/o/ONNX-Runtime/ONNX-Runtime-1.10.0-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/ONNX-Runtime/ONNX-Runtime-1.10.0-foss-2021a.eb
  easybuild/easyconfigs/o/ONNX/ONNX-1.11.0-foss-2021a.eb
Labels: new

#15161 {bio}[foss/2021a] ont-fast5-api v4.0.2 w/ Python 3.9.5
  easybuild/easyconfigs/o/ont-fast5-api/ont-fast5-api-4.0.2-foss-2021a.eb
Labels: update

#15138 {math}[system/system] MCR vR2022a
  easybuild/easyconfigs/m/MCR/MCR-R2022a.eb
Labels: update

#15178 add WGCNA extension to R-bundle-BioConductor v3.14
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.14-foss-2021b-R-4.1.2.eb
Labels: enhancement

#15175 {data}[foss/2021a] skorch v0.11.0 w/ Python 3.9.5
  easybuild/easyconfigs/s/skorch/skorch-0.11.0-foss-2021a-PyTorch-1.10.0.eb
Labels: new

#15176 add Sys::Info, HTML::Template, Log::Report extensions to Perl v5.34.0
  easybuild/easyconfigs/p/Perl/Perl-5.34.0-GCCcore-11.2.0.eb
Labels: enhancement

#13155 {chem}[iimpi/2020b] AMS v2020.102
  easybuild/easyconfigs/a/AMS/AMS-2020.102-iimpi-2020b-intelmpi.eb
Labels: new

#15136 {bio}[gompi/2021b] kallisto v0.48.0
  easybuild/easyconfigs/k/kallisto/kallisto-0.48.0-gompi-2021b.eb
Labels: update

#15173 {vis}[foss/2021b] NiBabel v3.2.2 w/ Python 3.9.6
  easybuild/easyconfigs/n/NiBabel/NiBabel-3.2.2-foss-2021b.eb
  easybuild/easyconfigs/p/pydicom/pydicom-2.2.2-GCCcore-11.2.0.eb
Labels: update

#15174 {math}[foss/2021a] MNE-Python v0.24.1 w/ Python 3.9.5
  easybuild/easyconfigs/m/MNE-Python/MNE-Python-0.24.1-foss-2021a.eb
Labels: new

#15177 {data}[GCCcore/11.2.0] XML-Compile v1.63
  easybuild/easyconfigs/x/XML-Compile/XML-Compile-1.63-GCCcore-11.2.0.eb
Labels: new

#15172 {vis}[foss/2021b] VTK v9.1.0 w/ Python 3.9.6
  easybuild/easyconfigs/v/VTK/VTK-9.1.0-foss-2021b.eb
Labels: update

#14252 {phys}[intel/2021a] DFTB+ v21.1 w/ Python 3.9.5
  easybuild/easyconfigs/d/DFTB+/DFTB+-21.1-intel-2021a.eb
  easybuild/easyconfigs/d/DFTB+/DFTB+-21.1_drop_intel_failing_tests.patch
  easybuild/easyconfigs/d/DFTB+/DFTB+-21.1_fix_intel_omp_linking.patch
  easybuild/easyconfigs/d/DFTB+/DFTB+-21.1_use_dftd3_from_EB.patch
  easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.9-intel-compilers-2021.2.0.eb
Labels: update

#15008 {chem}[foss/2021a,intel/2021a] DIRAC v22.0
  easybuild/easyconfigs/d/DIRAC/DIRAC-22.0-foss-2021a.eb
  easybuild/easyconfigs/d/DIRAC/DIRAC-22.0-intel-2021a.eb
Labels: update

#15169 {bio}[gompi/2021b] MEME v5.4.1 w/ Python 2.7.18
  easybuild/easyconfigs/m/MEME/MEME-5.4.1-gompi-2021b-Python-2.7.18.eb
Labels: update

#15185 {bio}[GCCcore/11.2.0] MUSCLE v3.8.31
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-3.8.31-GCCcore-11.2.0.eb
Labels: update

#15184 {chem}[intel/2020b] PyFrag v2019-20220216 w/ Python 3.8.6
  easybuild/easyconfigs/p/PyFrag/PyFrag-2019-20220216-intel-2020b-ASA.eb
  easybuild/easyconfigs/p/PyFrag/PyFrag-2019_fix_flaky_input_fetch.patch
Labels: new

#15180 {chem}[intel/2021b] AmberTools v21 w/ Python 3.9.6
  easybuild/easyconfigs/a/AmberTools/AmberTools-21-intel-2021b.eb
Labels: update

#15162 {bio}[foss/2021a] ont-remora v0.1.2 w/ Python 3.9.5
  easybuild/easyconfigs/o/ont-remora/ont-remora-0.1.2-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/o/ont-remora/ont-remora-0.1.2-foss-2021a.eb
Labels: new

#15148 cleanup PSolver and futile easyconfigs and add dynamic libs.
  easybuild/easyconfigs/f/futile/futile-1.8.3-foss-2020b.eb
  easybuild/easyconfigs/f/futile/futile-1.8.3-foss-2021a.eb
  easybuild/easyconfigs/f/futile/futile-1.8.3-foss-2021b.eb
  easybuild/easyconfigs/f/futile/futile-1.8.3-intel-2020b.eb
  easybuild/easyconfigs/f/futile/futile-1.8.3-intel-2021a.eb
  easybuild/easyconfigs/f/futile/futile-1.8.3-intel-2021b.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-foss-2020b.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-foss-2021a.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-foss-2021b.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-intel-2020b.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-intel-2021a.eb
  easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-intel-2021b.eb
Labels: enhancement, bug fix, code cleanup

#15149 use EasyBuild hwloc in likwid and move to GCC/intel-compiler level due to Fortran modules
  easybuild/easyconfigs/l/likwid/likwid-5.2.0-GCC-10.2.0.eb
  easybuild/easyconfigs/l/likwid/likwid-5.2.0-GCC-10.3.0.eb
  easybuild/easyconfigs/l/likwid/likwid-5.2.0-GCC-11.2.0.eb
  easybuild/easyconfigs/l/likwid/likwid-5.2.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/likwid/likwid-5.2.0-iccifort-2020.4.304.eb
  easybuild/easyconfigs/l/likwid/likwid-5.2.0-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/l/likwid/likwid-5.2.0_use_EB_hwloc.patch
  easybuild/easyconfigs/l/likwid/likwid-5.2.1-GCC-11.2.0.eb
Labels: update

#15166 {bio}[system] IgBLAST v1.18.0
  easybuild/easyconfigs/i/IgBLAST/IgBLAST-1.18.0-x64-linux.eb
Labels: update

#15182 {numlib}[GCCcore/11.2.0] BLIS v3.1 (AMD fork)
  easybuild/easyconfigs/b/BLIS/BLIS-3.1-GCCcore-11.2.0-amd.eb
Labels: update

#15190 add Sys::Info::Driver::Unknown + Sys::Info::Driver::Linux extensions to Perl v5.34.0
  easybuild/easyconfigs/p/Perl/Perl-5.34.0-GCCcore-11.2.0.eb
Labels: enhancement

#15191 enable running of tests for MEME with gompi/2021b
  easybuild/easyconfigs/m/MEME/MEME-5.4.1-gompi-2021b-Python-2.7.18.eb
Labels: enhancement

#14834 {bio}[GCC/10.3.0,GCC/11.2.0] PLINK v2.00a2.3
  easybuild/easyconfigs/p/PLINK/PLINK-2.00a2.3-GCC-10.3.0.eb
  easybuild/easyconfigs/p/PLINK/PLINK-2.00a2.3-GCC-11.2.0.eb
Labels: update

#14281 {tools}[GCCcore/11.2.0] archspec v0.1.3 w/ Python 3.9.6
  easybuild/easyconfigs/a/archspec/archspec-0.1.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/archspec/archspec-0.1.3_click_8.patch
Labels: update

#14847 add missing xxd build dependency for recent PLUMED versions (2.6.2, 2.7.x)
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.2-foss-2020b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.2-intel-2020b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.0-foss-2020b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-foss-2021a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-intel-2021a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-foss-2021b.eb
Labels: bug fix

#15048 fix GBprocesS easyconfig by switching to source tarball created using git_config
  easybuild/easyconfigs/g/GBprocesS/GBprocesS-2.3-intel-2020a-Python-3.8.2.eb
Labels: bug fix

#15093 {lib}[GCC/11.2.0] FlexiBLAS v3.1.3
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.1.3-GCC-11.2.0.eb
Labels: update

#15121 fix grconvert build for Grace/5.1.25 with foss/2021a by adding libtirpc dependency + related patch
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2021a.eb
  easybuild/easyconfigs/g/Grace/Grace-5.1.25-tirpc-dependency.patch
Labels: bug fix

#15193 {bio}[GCC/11.2.0] RevBayes v1.1.1
  easybuild/easyconfigs/r/RevBayes/RevBayes-1.1.1-GCC-11.2.0.eb
Labels: update

#15194 {tools}[gompi/2021b] ecCodes v2.24.2
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.24.2-gompi-2021b.eb
Labels: update

#15198 {bio}[foss/2021b] CmdStanR v0.5.0
  easybuild/easyconfigs/c/CmdStanR/CmdStanR-0.5.0-foss-2021b-R-4.1.2.eb
Labels: new

#15199 allow oversubscription of MPI ranks to cores when running MEME test suite
  easybuild/easyconfigs/m/MEME/MEME-5.4.1-gompi-2021b-Python-2.7.18.eb
Labels: bug fix

#15200 update copyright lines for 2022
  setup.py
  test/__init__.py
  test/easyconfigs/easyconfigs.py
  test/easyconfigs/styletests.py
  test/easyconfigs/suite.py
Labels: update, documentation

#15203 add patch to fix shared linking in vcflib
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-10.2.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-10.3.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2_fix-shared-linking.patch
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.3-GCC-11.2.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.3_fix-shared-linking.patch
Labels: bug fix

#15142 {bio}[GCCcore/11.2.0] pyEGA3 v4.0.0 w/ Python 3.9.6
  easybuild/easyconfigs/p/pyEGA3/pyEGA3-4.0.0-GCCcore-11.2.0.eb
Labels: update

#15181 enhance vcflib easyconfigs to also install scripts
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-10.2.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-10.3.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.3-GCC-11.2.0.eb
Labels: bug fix

#15205 fix failing sanity check for PRINSEQ
  easybuild/easyconfigs/p/PRINSEQ/PRINSEQ-0.20.4-foss-2018b-Perl-5.28.0.eb
  easybuild/easyconfigs/p/PRINSEQ/PRINSEQ-0.20.4-foss-2020b-Perl-5.32.0.eb
  easybuild/easyconfigs/p/PRINSEQ/PRINSEQ-0.20.4-foss-2021b-Perl-5.34.0.eb
Labels: bug fix

#15210 prepare release notes for EasyBuild v4.5.4 + bump version to 4.5.4
  RELEASE_NOTES
  setup.py
Labels: update

#15207 {tools}[system/system] vsc-mympirun v5.2.11
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.11.eb
Labels: update

#15214 {tools}[system/system] EasyBuild v4.5.4
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.4.eb
Labels: update

#15215 sync with main + bump version to 4.5.5dev
  RELEASE_NOTES
  setup.py
Labels: update

#15213 {bio}[foss/2021b] eggnog-mapper v2.1.7 w/ Python 3.9.6
  easybuild/easyconfigs/e/eggnog-mapper/eggnog-mapper-2.1.7-foss-2021b.eb
Labels: update

#15222 {bio}[GCC/11.2.0] FastANI v1.33
  easybuild/easyconfigs/f/FastANI/FastANI-1.33-GCC-11.2.0.eb
Labels: update

#15224 {bio}[gompi/2021b] barrnap v0.9
  easybuild/easyconfigs/b/barrnap/barrnap-0.9-gompi-2021b.eb
Labels: update

#15225 {data}[intel/2021b] BDBag v1.6.3 w/ Python 3.9.6
  easybuild/easyconfigs/b/BDBag/BDBag-1.6.3-intel-2021b.eb
Labels: update
