Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2023-11, with the labels that each got.

#19116 {bio}[GCC/12.2.0] Arriba v2.4.0
  easybuild/easyconfigs/a/Arriba/Arriba-2.4.0-GCC-12.2.0.eb
Labels: update

#19110 only set flag `--enable-asmjit` for PLUMED when installing on `x86_64`
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.2-foss-2020b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.0-foss-2020b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-foss-2021a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-foss-2021b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-foss-2021b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.1-foss-2022a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2022b.eb
Labels: bug fix, EESSI

#19129 {chem}[intel-compilers/2022.2.1] DFT-D3 v3.2.0
  easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-intel-compilers-2022.2.1.eb
Labels: update

#19106 {bio}[GCCcore/10.3.0] mdust v20150102
  easybuild/easyconfigs/m/mdust/mdust-20150102-GCC-10.3.0.eb
Labels: new

#19088 {bio}[foss/2022a] PICRUSt2 v2.5.2 w/ Python 3.10.4
  easybuild/easyconfigs/p/PICRUSt2/PICRUSt2-2.5.2-foss-2022a.eb
Labels: update

#19118 Add Miniconda3-23.9.0-0
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-23.9.0-0.eb
Labels: update

#19122 {bio}[foss/2022b] ctffind v4.1.14
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2022b.eb
Labels: update

#19099 {tools}[GCCcore/13.2.0] virtualenv v20.24.6, setuptools-rust v1.8.0, scikit-build v0.17.6, ...
  easybuild/easyconfigs/c/cryptography/cryptography-41.0.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/h/hatchling/hatchling-1.18.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/maturin/maturin-1.3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/poetry/poetry-1.6.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.17.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.8.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/v/virtualenv/virtualenv-20.24.6-GCCcore-13.2.0.eb
Labels: update

#19082 {lib}[GCCcore/12.3.0] boto3 v1.28.70
  easybuild/easyconfigs/b/boto3/boto3-1.28.70-GCCcore-12.3.0.eb
Labels: update

#19068 {bio}[foss/2022b] Seurat v4.4.0 w/ R 4.2.2
  easybuild/easyconfigs/s/Seurat/Seurat-4.4.0-foss-2022b-R-4.2.2.eb
Labels: update

#19139 {phys}[gompi/2022a] HepMC v2.06.11
  easybuild/easyconfigs/h/HepMC/HepMC-2.06.11-gompi-2022a.eb
Labels: new

#19143 {lang}[GCCcore/13.2.0] Python-bundle-PyPI v2023.10
  easybuild/easyconfigs/f/flit/flit-3.9.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2023.10-GCCcore-13.2.0.eb
Labels: update

#18836 {math}[gfbf/2022b] FLINT v2.9.0
  easybuild/easyconfigs/f/FLINT/FLINT-2.9.0-gcc-12.patch
  easybuild/easyconfigs/f/FLINT/FLINT-2.9.0-gfbf-2022b.eb
Labels: update

#19145 {system}[system/system] CUDA v12.3.0
  easybuild/easyconfigs/c/CUDA/CUDA-12.3.0.eb
Labels: update

#19146 {vis}[GCCcore/13.2.0] pixman v0.42.2, GLib v2.78.1, cairo v1.18.0, ...
  easybuild/easyconfigs/c/cairo/cairo-1.18.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.78.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.78.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/pixman/pixman-0.42.2-GCCcore-13.2.0.eb
Labels: update

#19153 {lib}[GCCcore/13.2.0] re2c v3.1, JasPer v4.0.0, graphite2 v1.3.14, ...
  easybuild/easyconfigs/g/graphite2/graphite2-1.3.14-GCCcore-13.2.0.eb
  easybuild/easyconfigs/j/JasPer/JasPer-4.0.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/NSPR/NSPR-4.35-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/NSS/NSS-3.94-GCCcore-13.2.0.eb
  easybuild/easyconfigs/r/re2c/re2c-3.1-GCCcore-13.2.0.eb
Labels: update

#19151 {lang,lib}[GCCcore/13.2.0] ICU v74.1, nodejs v20.9.0
  easybuild/easyconfigs/i/ICU/ICU-74.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/nodejs/nodejs-20.9.0-GCCcore-13.2.0.eb
Labels: update

#19147 Remove outdated configure option from FriBidi-1.0.12
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.12-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.12-GCCcore-12.3.0.eb
Labels: bug fix

#19149 {devel}[GCCcore/11.3.0] Autoconf-archive v2023.02.20
  easybuild/easyconfigs/a/Autoconf-archive/Autoconf-archive-2023.02.20-GCCcore-11.3.0.eb
Labels: update

#19126 {lib,tools,vis}[GCCcore/13.2.0] LittleCMS v2.15, libjxl v0.8.2, gperftools v2.13
  easybuild/easyconfigs/g/gperftools/gperftools-2.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LittleCMS/LittleCMS-2.15-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libjxl/libjxl-0.8.2-GCCcore-13.2.0.eb
Labels: update

#19152 {data,lang,lib,vis}[GCCcore/13.2.0] FFmpeg v6.0, LAME v3.100, FriBidi v1.0.13, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-6.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-12.1.14.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.28.5-GCCcore-13.2.0.eb
Labels: update

#19155 add libiconv dependency to gettext
  easybuild/easyconfigs/g/gettext/gettext-0.22-GCCcore-13.2.0.eb
Labels: bug fix

#19144 {tools}[GCCcore/12.2.0] FPM v1.15.1 w/ Ruby 3.2.2
  easybuild/easyconfigs/f/FPM/FPM-1.15.1-GCCcore-12.2.0.eb
Labels: update

#19156 sync with main + bump version to 4.9.0dev
  RELEASE_NOTES
  setup.py
Labels: update

#19142 Fix some typos found in software descriptions
  easybuild/easyconfigs/a/AutoDock-GPU/AutoDock-GPU-1.5.3-GCC-10.3.0-CUDA-11.3.1.eb
  easybuild/easyconfigs/a/AutoDock-GPU/AutoDock-GPU-1.5.3-GCC-11.3.0-CUDA-11.7.0.eb
  easybuild/easyconfigs/b/BayesTraits/BayesTraits-3.0.2-Linux.eb
  easybuild/easyconfigs/e/EZC3D/EZC3D-1.5.2-foss-2022a.eb
  easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.8-foss-2021a.eb
  easybuild/easyconfigs/g/garnett/garnett-0.1.20-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.11.1-foss-2022a.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.7.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.7.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.9.0-foss-2021a.eb
  easybuild/easyconfigs/k/KMC/KMC-3.2.1-GCC-11.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/k/KMC/KMC-3.2.1-GCC-11.2.0.eb
  easybuild/easyconfigs/k/KMC/KMC-3.2.2-GCC-12.2.0.eb
  easybuild/easyconfigs/m/meshtool/meshtool-16-GCC-10.2.0.eb
  easybuild/easyconfigs/m/meshtool/meshtool-16-GCC-9.3.0.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.5-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.5-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2020b.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2021a.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2021b.eb
  easybuild/easyconfigs/p/Paraver/Paraver-4.11.1-foss-2022a.eb
  easybuild/easyconfigs/p/Paraver/Paraver-4.9.2-foss-2021a.eb
  easybuild/easyconfigs/p/popscle/popscle-0.1-beta-20210505-GCC-11.3.0.eb
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.4-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.5-GCCcore-11.2.0.eb
Labels: bug fix

#19141 add patch to fix detection of newer Intel CPUs in OpenBLAS 0.3.20-0.3.23
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-NVHPC-22.7-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20_fix-x86-cpuid.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.21-GCC-12.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23-GCC-12.3.0.eb
Labels: bug fix

#19154 {vis}[GCCcore/13.2.0] Wayland v1.22.0, PyCairo v1.25.1, ATK v2.38.0, ...
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.50.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.15.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/e/elfutils/elfutils-0.190-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.10-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/Graphene/Graphene-1.10.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-8.2.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.10-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.51.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.25.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.46.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.22.0-GCCcore-13.2.0.eb
Labels: update

#19064 {lib}[foss/2022a] scikit-lego v0.6.16 w/ Python 3.10.4
  easybuild/easyconfigs/s/scikit-lego/scikit-lego-0.6.16-foss-2022a.eb
Labels: new

#19100 {cae}[system/system] STAR-CCM+ v18.06.006 w/ r8
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-18.06.006-r8.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-18.06.006.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-2310-r8.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-2310.eb
Labels: update

#19158 {cae}[system/system] STAR-CCM+ v2302 w/ r8
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-2302-r8.eb
  easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-2302.eb
Labels: update

#19159 fix OpenBLAS on newer Intel CPUs
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-NVHPC-22.7-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20_use-xASUM-microkernels-on-new-intel-cpus.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.21-GCC-12.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23-GCC-12.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.24-GCC-13.2.0.eb
Labels: bug fix

#19167 {bio}[foss/2022a] mrcfile v1.4.3
  easybuild/easyconfigs/m/mrcfile/mrcfile-1.4.3-foss-2022a.eb
Labels: update

#19071 {base}[foss/2022a] GFF3-toolkit v2.1.0
  easybuild/easyconfigs/g/GFF3-toolkit/GFF3-toolkit-2.1.0-foss-2022a.eb
  easybuild/easyconfigs/g/GFF3-toolkit/GFF3-toolkit-2.1.0-remove-hardcode.patch
Labels: new

#19091 {data}[foss/2023a] dynesty v2.1.3, pytest v7.4.2, pytest-xdist v3.3.1
  easybuild/easyconfigs/d/dynesty/dynesty-2.1.3-foss-2023a.eb
  easybuild/easyconfigs/p/pytest-xdist/pytest-xdist-3.3.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pytest/pytest-7.4.2-GCCcore-12.3.0.eb
Labels: new, update

#19131 {bio}[GCC/12.3.0] Oases v20180312
  easybuild/easyconfigs/o/Oases/Oases-20180312-GCC-12.3.0.eb
Labels: update

#19172 {tools}[system/system] Nextflow v23.10.0
  easybuild/easyconfigs/n/Nextflow/Nextflow-23.10.0.eb
Labels: update

#18857 {numlib}[foss/2023a] Suitesparse v7.1.0
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.1.0-foss-2023a.eb
Labels: update

#18675 {tools}[GCCcore/12.2.0] datalad v0.18.4
  easybuild/easyconfigs/d/datalad/datalad-0.18.4-GCCcore-12.2.0.eb
Labels: new

#19133 add patch to work around potential crash in PyTorch 1.13.1 caused by GCC 12 compiler bug
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1-foss-2022b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-duplicate-kDefaultTimeout-definition.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_workaround-gcc12-destructor-exception-bug.patch
Labels: bug fix

#19180 fix regression in GCC 12+ on AVX512 systems
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0_fix-avx512-misoptimization.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
Labels: bug fix

#19169 {tools}[foss/2022a] Horovod v0.28.1 w/ PyTorch 1.12.0
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2022a-PyTorch-1.12.0.eb
Labels: update

#19162 {lib}[GCCcore/13.2.0] libxslt v1.1.38, nettle v3.9.1, Xvfb v21.1.9, ...
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.38-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/nettle/nettle-3.9.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-21.1.9-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-13.2.0.eb
Labels: update

#19192 {math}[GCC/11.3.0] 4ti2 v1.6.9
  easybuild/easyconfigs/0/4ti2/4ti2-1.6.9-GCC-11.3.0.eb
Labels: update

#19193 {math}[GCCcore/11.3.0] cddlib v0.94m
  easybuild/easyconfigs/c/cddlib/cddlib-0.94m-GCCcore-11.3.0.eb
Labels: update

#19217 {bio}[foss/2022a] EUKulele v2.0.6
  easybuild/easyconfigs/e/EUKulele/EUKulele-2.0.6-foss-2022a.eb
Labels: new

#19195 {math}[GCCcore/11.3.0] Givaro v4.2.0
  easybuild/easyconfigs/g/Givaro/Givaro-4.2.0-GCCcore-11.3.0.eb
Labels: update

#19196 {math}[gompi/2022a] lrslib v7.2
  easybuild/easyconfigs/l/lrslib/lrslib-7.2-gompi-2022a.eb
  easybuild/easyconfigs/l/lrslib/lrslib-7.2-use-EB-values.patch
Labels: update

#19194 {math}[GCC/11.3.0] CoCoALib v0.99818
  easybuild/easyconfigs/c/CoCoALib/CoCoALib-0.99818-GCC-11.3.0.eb
Labels: update

#19198 {math}[GCCcore/11.3.0] PARI-GP v2.15.4
  easybuild/easyconfigs/p/PARI-GP/PARI-GP-2.15.4-GCCcore-11.3.0.eb
Labels: update

#19197 {math}[GCC/11.3.0] nauty v2.8.6
  easybuild/easyconfigs/n/nauty/nauty-2.8.6-GCC-11.3.0.eb
Labels: update

#19216 {bio}[foss/2022a] solo v1.3
  easybuild/easyconfigs/s/solo/solo-1.3-foss-2022a.eb
Labels: new

#19201 {math}[gfbf/2022a] IML v1.0.5
  easybuild/easyconfigs/i/IML/IML-1.0.5-gfbf-2022a.eb
Labels: new

#18932 {chem}[foss/2021a] waLBerla v6.1
  easybuild/easyconfigs/w/waLBerla/waLBerla-6.1-foss-2021a.eb
  easybuild/easyconfigs/w/waLBerla/waLBerla-6.1_fix_cmakelist_for_easybuild.patch
Labels: new

#19203 {math}[gfbf/2022a] ANTIC v0.2.5
  easybuild/easyconfigs/a/ANTIC/ANTIC-0.2.5-gfbf-2022a.eb
Labels: new

#19202 {math}[gfbf/2022a] LinBox v1.7.0
  easybuild/easyconfigs/l/LinBox/LinBox-1.7.0-gfbf-2022a.eb
Labels: update

#19226 Make Pillow easyconfigs aware of sysroot
  easybuild/easyconfigs/p/Pillow/Pillow-10.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-7.0.0-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.2.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.4.0-GCCcore-12.2.0.eb
Labels: update

#19199 {math}[gfbf/2022a] Singular v4.3.2p10
  easybuild/easyconfigs/s/Singular/Singular-4.3.2p10-gfbf-2022a.eb
Labels: update

#19211 {lang}[GCCcore/11.3.0] ECL v23.9.9
  easybuild/easyconfigs/e/ECL/ECL-23.9.9-GCCcore-11.3.0.eb
Labels: new

#19214 {bio}[foss/2022a] vaeda v0.0.30
  easybuild/easyconfigs/t/tensorflow-probability/tensorflow-probability-0.19.0-foss-2022a.eb
  easybuild/easyconfigs/v/vaeda/vaeda-0.0.30-foss-2022a.eb
Labels: new, update

#19186 add pkgconf build dependency to libGLU
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-13.2.0.eb
Labels: bug fix

#19189 Sidestep some build issues with CUDA-Samples 12.1
  easybuild/easyconfigs/c/CUDA-Samples/CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb
Labels: bug fix

#19209 {math}[GCC/11.3.0] eclib v20230424
  easybuild/easyconfigs/e/eclib/eclib-20230424-GCC-11.3.0.eb
Labels: new

#19229 {bio}[foss/2022a] GROMACS v2023.3 w/ CUDA 11.7.0
  easybuild/easyconfigs/g/GROMACS/GROMACS-2023.3-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2023.3-foss-2022a.eb
Labels: update

#19227 {system}[GCCcore/12.2.0] strace v6.6
  easybuild/easyconfigs/s/strace/strace-6.6-GCCcore-12.2.0.eb
Labels: update

#16281 {lib}[foss/2021a] DeepLabCut v2.2.0.6 w/ Python 3.9.5
  easybuild/easyconfigs/d/DeepLabCut/DeepLabCut-2.2.0.6-foss-2021a.eb
Labels: update

#19191 {lib}[GCCcore/12.2.0] json-fortran v8.3.0
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-GCCcore-12.2.0.eb
Labels: update

#19181 {bio}[foss/2022b] SUPPA v2.3-20231005
  easybuild/easyconfigs/s/SUPPA/SUPPA-2.3-20231005-foss-2022b.eb
Labels: new

#19164 only use ScaFaCos as dependency for LAMMPS 23Jun2022 on `x86_64`
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos.eb
Labels: bug fix, EESSI, aarch64

#19183 {bio}[foss/2022a] RFdiffusion v1.1.0, e3nn v0.3.3 w/ CUDA 11.7.0
  easybuild/easyconfigs/e/e3nn/e3nn-0.3.3-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/r/RFdiffusion/RFdiffusion-1.1.0-foss-2022a-CUDA-11.7.0.eb
Labels: update

#19176 {bio}[foss/2022a] castor v1.7.11
  easybuild/easyconfigs/c/castor/castor-1.7.11-foss-2022a.eb
Labels: new

#19236 {bio}[GCC/12.2.0] STAR v2.7.11a
  easybuild/easyconfigs/s/STAR/STAR-2.7.11a-GCC-12.2.0.eb
Labels: update

#19231 fix possible error/crash in NCCL on x86 due to cpuid
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-10.3.0-CUDA-11.3.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-11.2.0-CUDA-11.4.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-11.2.0-CUDA-11.5.2.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.11.4-gcccuda-2019b.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.12.12-GCCcore-11.3.0-CUDA-11.7.0.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.16.2-GCCcore-12.2.0-CUDA-12.0.0.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.16.2_fix-cpuid.patch
  easybuild/easyconfigs/n/NCCL/NCCL-2.18.3-GCCcore-12.3.0-CUDA-12.1.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.3-GCCcore-10.2.0-CUDA-11.1.1.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.8.3-GCCcore-9.3.0-CUDA-11.0.2.eb
Labels: bug fix

#19246 reduce timestep to fix sanity check commands in LAMMPS 23Jun2022
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos-CUDA-11.3.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos-CUDA-11.4.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2022a-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23June2022_fix-timestep-balance-example.patch
Labels: bug fix, EESSI

#19249 add aarch64 and ppc64le checksums to NVHPC 23.7
  easybuild/easyconfigs/n/NVHPC/NVHPC-23.7-CUDA-12.1.1.eb
  easybuild/easyconfigs/n/NVHPC/NVHPC-23.7-CUDA-12.2.0.eb
Labels: enhancement

#19245 {tools}[GCCcore/10.2.0] xxHash v0.8.1
  easybuild/easyconfigs/x/xxHash/xxHash-0.8.1-GCCcore-10.2.0.eb
Labels: update

#19237 {data}[GCC/11.3.0] libfdf v0.5.0
  easybuild/easyconfigs/l/libfdf/libfdf-0.5.0-GCC-11.3.0.eb
Labels: update

#19243 {devel}[foss/2023a] Spark v3.5.0, Arrow v14.0.1, RapidJSON v1.1.0-20230928
  easybuild/easyconfigs/a/Arrow/Arrow-14.0.1-gfbf-2023a.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-20230928-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/Spark/Spark-3.5.0-foss-2023a.eb
Labels: update

#19259 {tools}[system/system] iperf v3.15
  easybuild/easyconfigs/i/iperf/iperf-3.15.eb
Labels: new

#19258 {tools}[GCCcore/11.3.0] xxHash v0.8.1, python-xxhash v3.1.0 w/ Python 3.10.4
  easybuild/easyconfigs/p/python-xxhash/python-xxhash-3.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/xxHash/xxHash-0.8.1-GCCcore-11.3.0.eb
Labels: update

#19228 {bio}[foss/2022a] topaz v0.2.5.230926 w/ CUDA 11.7.0 w/ PyTorch 1.12.0
  easybuild/easyconfigs/t/topaz/topaz-0.2.5.20230926-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/t/topaz/topaz-0.2.5_install_relion3_wrappers.patch
Labels: update

#19254 {chem}[foss/2022a] nglview v3.0.3
  easybuild/easyconfigs/n/nglview/nglview-3.0.3-foss-2022a.eb
Labels: update

#19256 replace format tag with explicit extension name in Optuna v3.0.3
  easybuild/easyconfigs/o/Optuna/Optuna-3.1.0-foss-2022a.eb
Labels: bug fix

#19261 enhance easyconfigs for gnuplot 5.4.x to make sure that Lua dependency is always used
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.6-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.8-GCCcore-12.3.0.eb
Labels: bug fix, EESSI

#19253 fix GCC 12+ miscompiling C++ code causing double-free in case of exceptions
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0_fix-double-destruct.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
Labels: bug fix

#19262 {bio}[GCCcore/10.3.0] Bracken v2.9
  easybuild/easyconfigs/b/Bracken/Bracken-2.9-GCCcore-10.3.0.eb
Labels: update

#19190 {chem}[GCCcore/12.2.0,intel-compilers/2022.2.1] mctc-lib v0.3.1
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-intel-compilers-2022.2.1.eb
Labels: update

#19232 {bio}[GCCcore/12.2.0] Restrander v20230713
  easybuild/easyconfigs/r/Restrander/Restrander-20230713-GCCcore-12.2.0.eb
Labels: new

#19267 patch Pillow's setup.py rather than hardcoding system paths in `$CPATH` and `$LIBRARY_PATH`
  easybuild/easyconfigs/p/Pillow/Pillow-10.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-7.0.0-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.2.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.4.0-GCCcore-12.2.0.eb
Labels: bug fix, EESSI

#19269 {tools}[GCCcore/11.3.0] jedi v0.18.1, jedi-language-server v0.39.0
  easybuild/easyconfigs/j/jedi-language-server/jedi-language-server-0.39.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/j/jedi/jedi-0.18.1-GCCcore-11.3.0.eb
Labels: new

#19271 {tools}[GCCcore/12.3.0] pigz v2.8
  easybuild/easyconfigs/p/pigz/pigz-2.8-GCCcore-12.3.0.eb
Labels: update

#19275 SUPPA v2.3-20231005 - fix link creation and sanity check
  easybuild/easyconfigs/s/SUPPA/SUPPA-2.3-20231005-foss-2022b.eb
Labels: bug fix

#19272 {lib}[GCCcore/12.3.0] python-isal v1.1.0, ISA-L v2.30.0
  easybuild/easyconfigs/i/ISA-L/ISA-L-2.30.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/python-isal/python-isal-1.1.0-GCCcore-12.3.0.eb
Labels: update

#19279 use existing patch in pybind11 2.6.2 and 2.7.1 to fix failing test due to extra whitespace
  easybuild/easyconfigs/p/pybind11/pybind11-2.6.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.7.1-GCCcore-11.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.7.1-GCCcore-11.2.0.eb
Labels: bug fix

#19283 `json-fortran` creates Fortran modules, so must be at compiler level
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-GCC-11.2.0.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-GCC-11.3.0.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-GCC-12.2.0.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-intel-compilers-2022.2.1.eb
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCC-11.3.0.eb
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCC-12.2.0.eb
  easybuild/easyconfigs/m/mstore/mstore-0.2.0-GCC-11.3.0.eb
Labels: bug fix

#19248 json-fortran-8.3.0-GCC-10.3.0.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-GCC-10.3.0.eb
Labels: update

#19284 {lib}[intel-compilers/2022.0.1,intel-compilers/2022.2.1] json-fortran v8.3.0
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-intel-compilers-2022.0.1.eb
Labels: bug fix, update

#19285 {phys}[foss/2022a] pythermalcomfort v2.8.10
  easybuild/easyconfigs/p/pythermalcomfort/pythermalcomfort-2.8.10-foss-2022a.eb
Labels: new

#19257 {chem}[foss-2023a] CP2K 2023.1
  easybuild/easyconfigs/c/CP2K/CP2K-2023.1-foss-2023a.eb
  easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-12.3.0-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/libvori/libvori-220621-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-12.3.0.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2023a.eb
  easybuild/easyconfigs/x/xxd/xxd-9.0.2112-GCCcore-12.3.0.eb
Labels: update

#19294 {compiler}[system/system] intel-compilers v2024.0.0
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2024.0.0.eb
Labels: update

#19297 {lang}[foss/2022a] CVXPY v1.3.0
  easybuild/easyconfigs/c/CVXPY/CVXPY-1.3.0-foss-2022a.eb
Labels: update

#19315 {lib}[foss/2022a] AICSImageIO v4.14.0
  easybuild/easyconfigs/a/AICSImageIO/AICSImageIO-4.14.0-foss-2022a.eb
Labels: new

#19316 {devel}[GCC/13.2.0] Boost v1.83.0
  easybuild/easyconfigs/b/Boost/Boost-1.83.0-GCC-13.2.0.eb
Labels: update, 2023b

#19317 {lib}[GCCcore/13.2.0] pybind11 v2.11.1, Catch2 v2.13.9
  easybuild/easyconfigs/c/Catch2/Catch2-2.13.9-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.11.1-GCCcore-13.2.0.eb
Labels: update, 2023b

#19318 {lang}[gfbf/2023.09] SciPy-bundle v2023.11
  easybuild/easyconfigs/h/hypothesis/hypothesis-6.90.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/meson-python/meson-python-0.15.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.11-gfbf-2023.09.eb
Labels: update, 2023b

#19309 {bio}[foss/2022a] HiC-Pro v3.1.0, hic-straw v1.3.1, iced v0.5.10, ... w/ R 4.2.1
  easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/h/hic-straw/hic-straw-1.3.1-foss-2022a.eb
  easybuild/easyconfigs/i/iced/iced-0.5.10-foss-2022a.eb
  easybuild/easyconfigs/m/MACS2/MACS2-2.2.9.1-foss-2022a.eb
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-11.3.0.eb
Labels: new, update

#19323 {math}[gfbf/2022a] giac v1.9.0-69
  easybuild/easyconfigs/c/cliquer/cliquer-1.21-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GMP-ECM/GMP-ECM-7.0.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/giac/giac-1.9.0-69-gfbf-2022a.eb
  easybuild/easyconfigs/m/MPFI/MPFI-1.5.4-GCCcore-11.3.0.eb
Labels: new, change

#19208 {math}[GCC/11.3.0] BRiAl v1.2.12, m4ri v20200125, m4rie v20200125
  easybuild/easyconfigs/b/BRiAl/BRiAl-1.2.12-GCC-11.3.0.eb
  easybuild/easyconfigs/c/CUDD/CUDD-3.0.0-GCC-11.3.0.eb
  easybuild/easyconfigs/m/m4ri/m4ri-20200125-GCC-11.3.0.eb
  easybuild/easyconfigs/m/m4rie/m4rie-20200125-GCC-11.3.0.eb
Labels: new

#19204 {lang}[GCCcore/11.3.0] cppyy v3.0.0
  easybuild/easyconfigs/c/cppyy/cppyy-3.0.0-GCCcore-11.3.0.eb
Labels: new

#19327 remove Boost build dependency from pybind11 2.11.1
  easybuild/easyconfigs/p/pybind11/pybind11-2.11.1-GCCcore-13.2.0.eb
Labels: enhancement

#19207 {math}[foss/2022a] gap v4.12.2
  easybuild/easyconfigs/g/gap/gap-4.12.2-foss-2022a.eb
Labels: update

#19289 {data}[foss/2022b] ANTs v2.5.0
  easybuild/easyconfigs/a/ANTs/ANTs-2.5.0-foss-2022b.eb
Labels: update

#19299 {phys}[foss/2022a] futile v1.8.3
  easybuild/easyconfigs/f/futile/futile-1.8.3-foss-2022a.eb
Labels: update

#19329 {math}[GCCcore/11.3.0] lcalc v2.0.5
  easybuild/easyconfigs/l/lcalc/lcalc-2.0.5-GCCcore-11.3.0.eb
Labels: new

#19301 {lib}[GCCcore/11.3.0] Parallel-Hashmap v1.36
  easybuild/easyconfigs/p/Parallel-Hashmap/Parallel-Hashmap-1.36-GCCcore-11.3.0.eb
Labels: update

#19306 {math}[foss/2022a] PySINDy v1.7.3
  easybuild/easyconfigs/p/PySINDy/PySINDy-1.7.3-foss-2022a.eb
Labels: new

#19302 {chem}[foss/2022a] pycubescd v20220704
  easybuild/easyconfigs/p/pycubescd/pycubescd-20220704-foss-2022a.eb
Labels: new

#19295 {phys}[system/system] BOPTEST v0.3.0
  easybuild/easyconfigs/b/BOPTEST/BOPTEST-0.3.0.eb
Labels: new

#19298 {lib}[foss/2022a] epct v3.2.0
  easybuild/easyconfigs/e/epct/epct-3.2.0-foss-2022a.eb
Labels: new

#19296 {bio}[foss/2022a] CellBender v0.2.2
  easybuild/easyconfigs/c/CellBender/CellBender-0.2.2-foss-2022a.eb
Labels: new

#19332 {lib}[GCCcore/12.3.0] freeglut v3.4.0
  easybuild/easyconfigs/f/freeglut/freeglut-3.4.0-GCCcore-12.3.0.eb
Labels: update

#19333 Fix failing tokenizers with cargopythonpackage
  easybuild/easyconfigs/t/tokenizers/tokenizers-0.13.3-GCCcore-12.2.0.eb
Labels: bug fix

#19221 {chem}[gfbf/2022b,iimkl/2022b] multicharge v0.2.0
  easybuild/easyconfigs/m/multicharge/multicharge-0.2.0-gfbf-2022b.eb
  easybuild/easyconfigs/m/multicharge/multicharge-0.2.0-iimkl-2022b.eb
Labels: new

#19223 {chem}[gfbf/2022b,iimkl/2022b] dftd4 v3.4.0
  easybuild/easyconfigs/d/dftd4/dftd4-3.4.0-gfbf-2022b.eb
  easybuild/easyconfigs/d/dftd4/dftd4-3.4.0-iimkl-2022b.eb
Labels: new

#19337 {vis}[system/system] OMERO.insight v5.8.3 w/ Java 11
  easybuild/easyconfigs/o/OMERO.insight/OMERO.insight-5.8.3-Java-11.eb
Labels: new

#19339 define $GTKDOCIZE as 'echo' before generating configure script for new HarfBuzz versions
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-5.3.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-5.3.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-8.2.2-GCCcore-13.2.0.eb
Labels: bug fix, EESSI
