Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2023-07, with the labels that each got.

#18166 {phys}[GCC/11.3.0] Geant4 v11.1.2
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.6.2-GCC-11.3.0.eb
  easybuild/easyconfigs/g/Geant4-data/Geant4-data-11.1.eb
  easybuild/easyconfigs/g/Geant4/Geant4-11.1.2-GCC-11.3.0.eb
  easybuild/easyconfigs/g/Geant4/Geant4-11.1.2_use_data_env_vars_from_Geant4-data_module.patch
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.4-GCCcore-11.3.0.eb
Labels: update

#18235 Fix CUDA build of TensorFlow when using compiler symlinks
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.11.0-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1-foss-2022a-CUDA-11.7.0.eb
Labels: bug fix

#18243 {astro}[foss/2021b] emcee v3.1.4 w/ Python 3.9.6
  easybuild/easyconfigs/e/emcee/emcee-3.1.4-foss-2021b.eb
Labels: update

#18240 {bio}[GCC/10.3.0] DIAMOND v2.1.8
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.1.8-GCC-10.3.0.eb
Labels: update

#18245 add extra packages to recent R easyconfigs
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#18246 add extra packages to recent R-bundle-Bioconductor easyconfigs
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
Labels: enhancement

#18254 {bio}[foss/2022a] dorado v0.3.1 w/ CUDA 11.7.0
  easybuild/easyconfigs/d/dorado/dorado-0.3.1-foss-2022a-CUDA-11.7.0.eb
Labels: update

#18197 {phys}[foss/2022a] KerasTuner v1.3.5
  easybuild/easyconfigs/k/KerasTuner/KerasTuner-1.3.5-foss-2022a.eb
Labels: new

#16135 {tools}[foss/2021a] Horovod v0.25.0 w/ Python 3.9.5 + CUDA 11.3.1 + PyTorch 1.10.0
  easybuild/easyconfigs/h/Horovod/Horovod-0.25.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0.eb
Labels: update

#16161 {math}[system/system] MCR vR2022a
  easybuild/easyconfigs/m/MCR/MCR-R2022a.5.eb
Labels: update

#16671 {tools}[GCCcore/11.3.0] ITSTool v2.0.7 w/ Python 3.10.4
  easybuild/easyconfigs/i/ITSTool/ITSTool-2.0.7-GCCcore-11.3.0.eb
Labels: update

#16689 {tools}[GCCcore/11.3.0] Subversion v1.14.2
  easybuild/easyconfigs/s/Subversion/Subversion-1.14.2-GCCcore-11.3.0.eb
Labels: update

#18120 {devel}[foss/2022a] gemelli v0.0.9 w/ Python 3.10.4
  easybuild/easyconfigs/g/gemelli/gemelli-0.0.9-foss-2022a.eb
Labels: new

#18198 {bio}[GCC/11.3.0] MView v1.67
  easybuild/easyconfigs/m/MView/MView-1.67-GCC-11.3.0.eb
Labels: new

#14008 Add CI check for CMAKE_BUILD_TYPE
  test/easyconfigs/easyconfigs.py
Labels: enhancement, tests

#18224 {phys}[foss/2022a] HOOMD-blue v4.0.1 w/ Python 3.10.4
  easybuild/easyconfigs/h/HOOMD-blue/HOOMD-blue-4.0.1-foss-2022a.eb
Labels: new

#18255 Create DMTCP-3.0.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/d/DMTCP/DMTCP-3.0.0-GCCcore-11.3.0.eb
Labels: update

#15982 {*}[foss/2022a] GATE v9.2, Geant4 v11.0.2, ROOT v6.26.06, CLHEP v2.4.5.3 (+ deps)
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.5.3-GCC-11.3.0.eb
  easybuild/easyconfigs/g/GATE/GATE-9.2-foss-2022a.eb
  easybuild/easyconfigs/g/Geant4/Geant4-11.0.2-GCC-11.3.0.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.26.06-foss-2022a.eb
Labels: update

#14381 {system}[GCCcore/11.2.0] strace v5.14
  easybuild/easyconfigs/s/strace/strace-5.14-GCCcore-11.2.0.eb
Labels: new

#18261 {bio}[GCC/11.3.0] popscle v0.1-beta-20210505
  easybuild/easyconfigs/p/popscle/popscle-0.1-beta-20210505-GCC-11.3.0.eb
  easybuild/easyconfigs/p/popscle/popscle-0.1-beta-20210505_fix-limits.patch
Labels: update

#18253 {lib}[GCCcore/11.3.0] python-mujoco v2.2.2, MuJoCo v2.2.2, glew v2.2.0, ... w/ Python 3.10.4
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-11.3.0-osmesa.eb
  easybuild/easyconfigs/m/MuJoCo/MuJoCo-2.2.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/python-mujoco/python-mujoco-2.2.2-foss-2022a.eb
  easybuild/easyconfigs/p/python-mujoco/python-mujoco-2.2.2_use_eb_deps.patch
Labels: new, update

#18027 {vis}[GCCcore/12.3.0] X11 v20230603, gperf v3.1, intltool v0.51.0, ...
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.14.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.13.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20230603-GCCcore-12.3.0.eb
Labels: update, 2023a

#18260 remove incorrect '-Dgallium-drivers=swrast' configure option in ROOT easyconfigs
  easybuild/easyconfigs/r/ROOT/ROOT-6.22.08-foss-2020b.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.24.06-foss-2021b.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.26.10-foss-2022b.eb
Labels: code cleanup

#18264 {toolchain} foss/2023a
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2023a.eb
  easybuild/easyconfigs/f/foss/foss-2023a.eb
  easybuild/easyconfigs/g/gfbf/gfbf-2023a.eb
  easybuild/easyconfigs/g/gompi/gompi-2023a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2023a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.1-1-gompi-2023a.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gompi-2023a-fb.eb
Labels: change, 2023a

#18268 {system}[system/system] CUDA v12.2.0
  easybuild/easyconfigs/c/CUDA/CUDA-12.2.0.eb
Labels: update

#17155 {ai}[foss/2022a] PyTorch v1.13.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1-foss-2022a.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-pytest-args.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-test-ops-conf.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_increase-tolerance-test_ops.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_install-vsx-vec-headers.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_no-cuda-stubs-rpath.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_remove-flaky-test-in-testnn.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_skip-ao-sparsity-test-without-fbgemm.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_skip-failing-grad-test.patch
Labels: update

#18271 update source url for pkgconf
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.4-GCCcore-13.1.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.5-GCCcore-12.3.0.eb
Labels: bug fix

#18263 change base for intel/2023.03 to GCCcore/12.3.0
  easybuild/easyconfigs/i/impi/impi-2021.9.0-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/i/intel/intel-2023.03.eb
Labels: change, 2023a

#18272 {lib}[GCCcore/11.3.0] CppHeaderParser v2.7.4
  easybuild/easyconfigs/c/CppHeaderParser/CppHeaderParser-2.7.4-GCCcore-11.3.0.eb
Labels: new

#17365 {math}[intel/2022b] ELPA v2021.11.001
  easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-intel-2022b.eb
Labels: update

#18275 {toolchain} intel/2023a
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2023a.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2023a.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2023.1.0-iimpi-2023a.eb
  easybuild/easyconfigs/i/intel/intel-2023a.eb
Labels: update

#17996 {tools}[GCCcore/12.2.0] expecttest v0.1.3 w/ Python 3.10.8
  easybuild/easyconfigs/e/expecttest/expecttest-0.1.3-GCCcore-12.2.0.eb
Labels: update

#18273 {lib}[foss/2022a] centerline v1.0.1 w/ Python 3.10.4
  easybuild/easyconfigs/c/centerline/centerline-1.0.1-foss-2022a.eb
Labels: new

#18276 prepare release notes for EasyBuild v4.8.0 + bump version to 4.8.0
  RELEASE_NOTES
  setup.py
Labels: update, documentation

#18282 {tools}[system/system] EasyBuild v4.8.0
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.8.0.eb
Labels: update

#18283 sync with main + bump version to 4.8.1dev
  RELEASE_NOTES
  setup.py
Labels: update

#18281 add UCell extension to R-bundle-Bioconductor 3.16
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
Labels: enhancement

#18218 {phys}[foss/2022a] HOOMD-blue v4.0.1 w/ Python 3.10.4 + CUDA 11.7.0
  easybuild/easyconfigs/h/HOOMD-blue/HOOMD-blue-4.0.1-foss-2022a-CUDA-11.7.0.eb
Labels: new

#18265 {tools}[foss/2021b,foss/2022a] Horovod w/ TensorFlow
  easybuild/easyconfigs/h/Horovod/Horovod-0.22.1-foss-2021a-CUDA-11.3.1-TensorFlow-2.5.3.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2021b-CUDA-11.4.1-TensorFlow-2.7.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2021b-CUDA-11.4.1-TensorFlow-2.8.4.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2022a-CUDA-11.7.0-TensorFlow-2.11.0.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2022a-CUDA-11.7.0-TensorFlow-2.9.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1_support_flatbuffers_2.0.6.patch
Labels: update

#18266 {tools}[foss/2022a] Horovod v0.28.1 w/ PyTorch
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2021a-CUDA-11.3.1-PyTorch-1.11.0.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2021a-CUDA-11.3.1-PyTorch-1.12.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2021b-CUDA-11.5.2-PyTorch-1.12.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2022a-CUDA-11.7.0-PyTorch-1.12.0.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2022a-CUDA-11.7.0-PyTorch-1.12.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-fosscuda-2020b-PyTorch-1.9.0.eb
Labels: update

#18262 Remove superflous dependencies from Horovod
  easybuild/easyconfigs/h/Horovod/Horovod-0.21.3-fosscuda-2020b-PyTorch-1.7.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.22.0-fosscuda-2020b-PyTorch-1.8.1.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.22.1-foss-2021a-CUDA-11.3.1-TensorFlow-2.6.0.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.23.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0.eb
  easybuild/easyconfigs/h/Horovod/Horovod-0.25.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0.eb
Labels: bug fix

#18285 {bio}[GCC/12.2.0] Cluster-Buster v20200507
  easybuild/easyconfigs/c/Cluster-Buster/Cluster-Buster-20200507-GCC-12.2.0.eb
Labels: update

#18284 {tools}[GCCcore/11.3.0] Z3 v4.10.2, Z3 v4.8.16, Z3 v4.8.12, ... w/ Python 3.10.4 + 3.9.6 + 3.9.5 + 3.8.6
  easybuild/easyconfigs/z/Z3/Z3-4.10.2-GCCcore-11.3.0-Python-3.10.4.eb
  easybuild/easyconfigs/z/Z3/Z3-4.8.10-GCCcore-10.2.0-Python-3.8.6.eb
  easybuild/easyconfigs/z/Z3/Z3-4.8.11-GCCcore-10.3.0-Python-3.9.5.eb
  easybuild/easyconfigs/z/Z3/Z3-4.8.12-GCCcore-11.2.0-Python-3.9.6.eb
  easybuild/easyconfigs/z/Z3/Z3-4.8.16-GCCcore-11.3.0-Python-3.10.4.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#18295 {bio}[GCC/12.2.0] Delly v1.1.6
  easybuild/easyconfigs/d/Delly/Delly-1.1.6-GCC-12.2.0.eb
Labels: update

#18294 {bio}[foss/2022b] kma v1.4.12a
  easybuild/easyconfigs/k/kma/kma-1.4.12a-GCC-12.2.0.eb
Labels: update

#18290 {ai}[foss/2022a] segment-anything v1.0
  easybuild/easyconfigs/s/segment-anything/segment-anything-1.0-foss-2022a.eb
Labels: new

#18291 {math}[foss/2022a] Rhodium v1.2.0, Platypus-Opt v1.1.0
  easybuild/easyconfigs/p/Platypus-Opt/Platypus-Opt-1.1.0-foss-2022a.eb
  easybuild/easyconfigs/r/Rhodium/Rhodium-1.2.0-foss-2022a.eb
Labels: new

#18293 {devel}[GCCcore/12.2.0] libnsl v2.0.0
  easybuild/easyconfigs/l/libnsl/libnsl-2.0.0-GCCcore-12.2.0.eb
Labels: update

#18296 {data}[foss/2022a] h5netcdf v1.2.0 w/ Python 3.10.4
  easybuild/easyconfigs/h/h5netcdf/h5netcdf-1.2.0-foss-2022a.eb
Labels: update

#18297 {data}[GCCcore/11.3.0,gompi/2022a] h4toh5 v2.2.5, HDF-EOS2 v3.0
  easybuild/easyconfigs/h/HDF-EOS2/HDF-EOS2-3.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.5-gompi-2022a.eb
Labels: new, update

#18303 use MCR dependency in FreeSurfer 7.3.2 and 7.4.0
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.3.2-centos7_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.3.2-centos8_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.0-centos8_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.0-ubuntu20_amd64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.0-ubuntu22_amd64.eb
Labels: bug fix

#18301 disable building documentation for libsigc++ 2.10.x
  easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.8-GCCcore-10.3.0.eb
Labels: bug fix

#18286 {bio}[foss/2022a] kb-python v0.27.3 w/ Python 3.10.4
  easybuild/easyconfigs/k/kb-python/kb-python-0.27.3-foss-2022a.eb
Labels: update

#18252 {lib}[GCCcore/11.3.0] PortMidi v2.0.4, SDL2_image v2.6.3, SDL2_mixer v2.6.3, ... w/ Python 3.10.4
  easybuild/easyconfigs/p/PortMidi/PortMidi-2.0.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pygame/pygame-2.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/SDL2_image/SDL2_image-2.6.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/SDL2_mixer/SDL2_mixer-2.6.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/SDL2_ttf/SDL2_ttf-2.20.2-GCCcore-11.3.0.eb
Labels: new, update

#18313 {lang}[system/system] Julia v1.9.2 w/ linux x86_64
  easybuild/easyconfigs/j/Julia/Julia-1.9.2-linux-x86_64.eb
Labels: update

#18312 {lang}[GCCcore/12.3.0] Lua v5.4.6
  easybuild/easyconfigs/l/Lua/Lua-5.4.6-GCCcore-12.3.0.eb
Labels: update

#18306 {lib}[foss/2022a] ruptures v1.1.8 w/ Python 3.10.4
  easybuild/easyconfigs/r/ruptures/ruptures-1.1.8-foss-2022a.eb
  easybuild/easyconfigs/r/ruptures/ruptures-1.1.8_fix-scipy-version.patch
Labels: new

#18311 {tools}[GCCcore/12.3.0] Mercurial v6.4.5
  easybuild/easyconfigs/m/Mercurial/Mercurial-6.4.5-GCCcore-12.3.0.eb
Labels: update

#18289 {data}[foss/2022b] connected-components-3d v3.12.1
  easybuild/easyconfigs/c/connected-components-3d/connected-components-3d-3.12.1-foss-2022b.eb
Labels: new

#18217 {tools}[GCCcore/12.2.0,gfbf/2022b] fastparquet v2023.4.0, patchelf v0.17.2 w/ Python 3.10.8
  easybuild/easyconfigs/f/fastparquet/fastparquet-2023.4.0-gfbf-2022b.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.17.2-GCCcore-12.2.0.eb
Labels: update

#17916 {bio}[system/system] T-Coffee v13.45.61.3c310a9
  easybuild/easyconfigs/t/T-Coffee/T-Coffee-13.45.61.3c310a9.eb
Labels: new

#18304 {bio}[foss/2022a] RFdiffusion v1.1.0, e3nn v0.3.3, Hydra v1.3.2 w/ Python 3.10.4
  easybuild/easyconfigs/e/e3nn/e3nn-0.3.3-foss-2022a.eb
  easybuild/easyconfigs/h/Hydra/Hydra-1.3.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/r/RFdiffusion/RFdiffusion-1.1.0-foss-2022a.eb
  easybuild/easyconfigs/r/RFdiffusion/RFdiffusion-1.1.0_fix-find-packages.patch
Labels: new, update

#18314 {lib}[GCCcore/12.3.0] Guile v3.0.9, gc v8.2.4, libunistring v1.1
  easybuild/easyconfigs/g/Guile/Guile-3.0.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/gc/gc-8.2.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libunistring/libunistring-1.1-GCCcore-12.3.0.eb
Labels: update

#17976 set JULIA_DEPOT_PATH in Julia easyconfigs with default value
  easybuild/easyconfigs/j/Julia/Julia-1.6.5-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.6-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.7-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.1-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.2-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.3-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.8.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.8.2-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.8.5-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.9.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.9.2-linux-x86_64.eb
Labels: bug fix

#18317 {tools}[intel/2022a] HPL v2.3
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2022a.eb
Labels: update

#18326 {math}[foss/2022b,gompi/2022b] CalculiX-CrunchiX v2.20, SPOOLES v2.2
  easybuild/easyconfigs/c/CalculiX-CrunchiX/CalculiX-CrunchiX-2.20-foss-2022b.eb
  easybuild/easyconfigs/s/SPOOLES/SPOOLES-2.2-gompi-2022b.eb
Labels: update

#17459 {math}[gompi/2022b] SCOTCH v7.0.3
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.3-gompi-2022b.eb
Labels: update

#18208 {tools}[GCCcore/12.3.0] Python-bundle-PyPI v2023.06, hatchling v1.18.0, virtualenv v20.23.1, ... w/ Python 3.11.3
  easybuild/easyconfigs/b/bcrypt/bcrypt-4.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/c/cffi/cffi-1.15.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/c/cryptography/cryptography-41.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/f/flit/flit-3.9.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/h/hatchling/hatchling-1.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-3.10-bist-1.3.6-compatibility.patch
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-3.11-bist-1.3.6-compatibility.patch
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-3_9-blist-1.3.6-fix-undefined_symbol_PyObject_GC_IS_TRACKED.patch
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2023.06-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/paramiko/paramiko-3.2.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/poetry/poetry-1.5.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.17.6-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.6.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/v/virtualenv/virtualenv-20.23.1-GCCcore-12.3.0.eb
Labels: new, update, 2023a

#18316 {bio}[system/system] T-Coffee v13.46.0.919e8c6b
  easybuild/easyconfigs/t/T-Coffee/T-Coffee-13.46.0.919e8c6b.eb
Labels: update

#18333 {bio}[foss/2022b] PICRUSt2 v2.5.2, biom-format v2.1.15
  easybuild/easyconfigs/b/biom-format/biom-format-2.1.15-foss-2022b.eb
  easybuild/easyconfigs/p/PICRUSt2/PICRUSt2-2.5.2-foss-2022b.eb
Labels: new, update

#18378 {lib}[GCCcore/12.2.0] libwebp v1.3.1
  easybuild/easyconfigs/l/libwebp/libwebp-1.3.1-GCCcore-12.2.0.eb
Labels: update

#18381 {vis}[foss/2022b] OpenCV v4.8.0 w/ contrib
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.0-foss-2022b-contrib.eb
Labels: update

#18377 {vis}[foss/2022b] scikit-plot v0.3.7
  easybuild/easyconfigs/s/scikit-plot/scikit-plot-0.3.7-foss-2022b.eb
Labels: new

#18367 {lib}[GCCcore/11.3.0] sentinelsat v1.2.1 w/ Python 3.10.4
  easybuild/easyconfigs/s/sentinelsat/sentinelsat-1.2.1-GCCcore-11.3.0.eb
Labels: new

#18342 {bio}[GCC/12.2.0] Sabre v2013-09-28
  easybuild/easyconfigs/s/Sabre/Sabre-2013-09-28-GCC-12.2.0.eb
Labels: new

#18366 {tools}[GCCcore/12.2.0] Pylint v2.17.4
  easybuild/easyconfigs/p/Pylint/Pylint-2.17.4-GCCcore-12.2.0.eb
Labels: update

#18334 {data,tools}[foss/2022b] pyodbc v4.0.39, unixODBC v2.3.11
  easybuild/easyconfigs/p/pyodbc/pyodbc-4.0.39-foss-2022b.eb
  easybuild/easyconfigs/u/unixODBC/unixODBC-2.3.11-foss-2022b.eb
Labels: new, update

#18390 Fix batchspawner for JupyterHub 3.0
  easybuild/easyconfigs/j/JupyterHub/JupyterHub-3.0.0-GCCcore-11.3.0.eb
Labels: bug fix

#18408 {tools}[GCCcore/11.3.0] Parsl v2023.7.17
  easybuild/easyconfigs/p/Parsl/Parsl-2023.7.17-GCCcore-11.3.0.eb
Labels: new

#18401 {bio}[foss/2022a] scGSVA v0.0.14
  easybuild/easyconfigs/s/scGSVA/scGSVA-0.0.14-foss-2022a-R-4.2.1.eb
Labels: new

#17558 {numlib}[iompi/2020b] FFTW v3.3.8
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-iompi-2020b.eb
Labels: update

#18422 {devel}[GCCcore/12.3.0] libdwarf v0.7.0
  easybuild/easyconfigs/l/libdwarf/libdwarf-0.7.0-GCCcore-12.3.0.eb
Labels: update

#18423 {devel,lib}[GCC/12.3.0,GCCcore/12.3.0] Boost v1.82.0, ICU v73.2
  easybuild/easyconfigs/b/Boost/Boost-1.82.0-GCC-12.3.0.eb
  easybuild/easyconfigs/i/ICU/ICU-73.2-GCCcore-12.3.0.eb
Labels: update

#18404 {lib}[GCCcore/12.2.0] aiohttp v3.8.5
  easybuild/easyconfigs/a/aiohttp/aiohttp-3.8.5-GCCcore-12.2.0.eb
Labels: update

#18417 {toolchain} GCC 13.2.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.40-GCCcore-13.2.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GCC/GCC-13.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-13.2.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.13-GCCcore-13.2.0.eb
Labels: update, 2023b

#18405 {tools}[GCCcore/12.2.0] maturin v1.1.0
  easybuild/easyconfigs/m/maturin/maturin-1.1.0-GCCcore-12.2.0.eb
Labels: new

#18418 {perf}[GCCcore/12.2.0] Score-P v8.1, SIONlib v1.7.7, PDT v3.25.1, ... w/ CUDA 12.0.0, tools
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.8.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.8.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.7-GCCcore-12.2.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/PAPI/PAPI-7.0.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-12.2.0-tools.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.0_fix-race-in-CUDA-adapter.patch
  easybuild/easyconfigs/s/Score-P/Score-P-8.1-gompi-2022b-CUDA-12.0.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.1-gompi-2022b.eb
Labels: update

#18414 {bio}[GCCcore/12.2.0] Hybpiper v2.1.6, DIAMOND v2.1.8, parallel v20230722, ...
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.1.8-GCC-12.2.0.eb
  easybuild/easyconfigs/h/Hybpiper/Hybpiper-2.1.6-foss-2022b.eb
  easybuild/easyconfigs/p/parallel/parallel-20230722-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/psutil/psutil-5.9.5-GCCcore-12.2.0.eb
Labels: new, update

#18416 {bio}[system/system] FreeSurfer v7.4.1 w/ centos7_x86_64, centos8_x86_64, ...
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.1-centos7_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.1-centos8_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.1-ubuntu20_amd64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.1-ubuntu22_amd64.eb
  easybuild/easyconfigs/f/FreeSurfer/freesurfer-7.4.1-hardcoded-path.patch
Labels: update
