Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2023-10, with the labels that each got.

#18849 {phys}[gompi/2022a] XBeach v20230831
  easybuild/easyconfigs/x/XBeach/XBeach-20230831-gompi-2022a.eb
  easybuild/easyconfigs/x/XBeach/XBeach-20230831_fix-gfortran-compilation.patch
Labels: new

#18893 {perf}[gompi/2023.09] OSU-Micro-Benchmarks v7.2
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.2-gompi-2023.09.eb
Labels: update, 2023b

#18894 {math}[foss/2022a,foss/2022b,foss/2023a,intel/2022a,intel/2022b,intel/2023a] HPCG v3.1
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2022a.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2022b.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2023a.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2022a.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2022b.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2023a.eb
Labels: update

#16356 {bio}[GCC/11.2.0] CIRCexplorer2 v2.3.8, Pysam v0.18.0, TopHat v2.1.0, pybedtools 0.8.2 w/ Python 2.7.18
  easybuild/easyconfigs/c/CIRCexplorer2/CIRCexplorer2-2.3.8-foss-2021b-Python-2.7.18.eb
  easybuild/easyconfigs/p/pybedtools/pybedtools-0.8.2-GCC-11.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/t/TopHat/TopHat-2.1.2-GCC-11.2.0-Python-2.7.18.eb
Labels: update

#18688 {bio}[foss/2022a] biobakery-workflows v3.1
  easybuild/easyconfigs/a/anadama2/anadama2-0.10.0-foss-2022a.eb
  easybuild/easyconfigs/b/biobakery-workflows/biobakery-workflows-3.1-foss-2022a.eb
  easybuild/easyconfigs/k/kneaddata/kneaddata-0.12.0-foss-2022a.eb
  easybuild/easyconfigs/l/LevelDB/LevelDB-1.22-GCCcore-11.3.0.eb
Labels: new, update

#18889 {data}[gfbf/2023a] scikit-learn v1.3.1
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.3.1-gfbf-2023a.eb
Labels: update

#18898 bump OpenMPI to v4.1.6 in gompi/2023.09
  easybuild/easyconfigs/g/gompi/gompi-2023.09.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.6-GCC-13.2.0.eb
Labels: update

#18891 {chem}[intel-compilers/2023.1.0] libxc v6.2.2
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-intel-compilers-2023.1.0.eb
Labels: update

#18900 bump UCX to 1.15.0 and PMIx to 4.2.6 in OpenMPI-4.1.6-GCC-13.2.0.eb and impi-2021.10.0-intel-compilers-2023.2.1.eb
  easybuild/easyconfigs/i/impi/impi-2021.10.0-intel-compilers-2023.2.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.6-GCC-13.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.2.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UCC/UCC-1.2.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.14.1_fix-type-conflict-uct_md_mem_advise.patch
  easybuild/easyconfigs/u/UCX/UCX-1.15.0-GCCcore-13.2.0.eb
Labels: update, change

#18890 {chem}[foss/2023a,intel/2023a] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-foss-2023a.eb
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-intel-2023a.eb
Labels: update

#18897 {math}[intel/2023a] ELPA v2023.05.001
  easybuild/easyconfigs/e/ELPA/ELPA-2023.05.001-intel-2023a.eb
Labels: update

#18777 {chem}[foss/2023a] ASE v3.22.1, Flask v2.3.3, scikit-build-core v0.5.0, spglib-python v2.1.0
  easybuild/easyconfigs/a/ASE/ASE-3.22.1-foss-2023a.eb
  easybuild/easyconfigs/f/Flask/Flask-2.3.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/scikit-build-core/scikit-build-core-0.5.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-2.1.0-gfbf-2023a.eb
Labels: new, update, 2023a

#18775 {chem}[foss/2023a] QuantumESPRESSO v7.2
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2023a.eb
Labels: update

#18901 {lib}[GCC/12.3.0] poppler v23.09.0
  easybuild/easyconfigs/p/poppler/poppler-23.09.0-GCC-12.3.0.eb
Labels: update

#18903 {bio}[foss/2022b] SignalP v6.0h w/ fast
  easybuild/easyconfigs/s/SignalP/SignalP-6.0h-foss-2022b-fast.eb
Labels: update

#18881 avoid use of hardcoded paths for Pillow by using `--disable-platform-guessing` option
  easybuild/easyconfigs/p/Pillow/Pillow-10.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.0.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-6.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-7.0.0-GCCcore-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.2.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-8.3.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.1.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.2.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-9.4.0-GCCcore-12.2.0.eb
Labels: bug fix

#18906 {lib}[GCCcore/12.3.0] NCCL v2.18.3, add additional checksum
  easybuild/easyconfigs/n/NCCL/NCCL-2.18.3-GCCcore-12.3.0-CUDA-12.1.1.eb
Labels: update, 2023a

#18907 {bio}[foss/2023a] OpenMM v8.0.0
  easybuild/easyconfigs/o/OpenMM/OpenMM-8.0.0-foss-2023a.eb
Labels: update

#18895 bump OpenSSL 1.1 wrapper fallback to 1.1.1w
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb
Labels: update, change

#18912 {lib}[foss/2022a] PyTorch-Ignite v0.4.12 w/ CUDA 11.7.0
  easybuild/easyconfigs/p/PyTorch-Ignite/PyTorch-Ignite-0.4.12-foss-2022a-CUDA-11.7.0.eb
Labels: update

#18916 {chem}[foss/2023a] QuantumESPRESSO v7.2
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2023a.eb
Labels: update

#18909 {compiler}[system/system] Go v1.21.1
  easybuild/easyconfigs/g/Go/Go-1.21.1.eb
Labels: update

#18794 {chem}[GCC/10.2.0,GCC/10.3.0,GCC/11.2.0,GCC/11.3.0,GCC/12.2.0,GCC/9.3.0] NBO v7.0.10
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-10.2.0.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-10.3.0.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-11.2.0.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-9.3.0.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2022a.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2022b.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10_make.patch
Labels: update

#16357 {bio}[foss/2021b] CLEAR v20210117, StringTie v2.2.1 w/ Python 2.7.18
  easybuild/easyconfigs/c/CLEAR/CLEAR-20210117-foss-2021b-Python-2.7.18.eb
  easybuild/easyconfigs/s/StringTie/StringTie-2.2.1-GCC-11.2.0-Python-2.7.18.eb
Labels: new, update

#18917 {lib}[GCCcore/12.2.0] Cereal v1.3.2
  easybuild/easyconfigs/c/Cereal/Cereal-1.3.2-GCCcore-12.2.0.eb
Labels: update

#18910 {lib}[system/system] Circuitscape v5.12.3 w/ Julia 1.9.2
  easybuild/easyconfigs/c/Circuitscape/Circuitscape-5.12.3-Julia-1.9.2.eb
Labels: update

#18731 {data}[foss/2023a] netcdf4-python v1.6.4
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.6.4-foss-2023a.eb
Labels: update

#18586 {lib}[GCCcore/10.3.0] libedit v20210910
  easybuild/easyconfigs/l/libedit/libedit-20210910-GCCcore-10.3.0.eb
Labels: update

#18924 add ridge extension to R 4.2.2
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#18920 {vis}[fosscuda/2020b] imutils v0.5.4
  easybuild/easyconfigs/i/imutils/imutils-0.5.4-fosscuda-2020b.eb
Labels: new

#18923 {lib}[foss/2021b] uncertainties v3.1.7
  easybuild/easyconfigs/u/uncertainties/uncertainties-3.1.7-foss-2021b.eb
Labels: new

#18918 {geo}[foss/2022a] rasterstats v0.19.0 w/ Python 3.10.4
  easybuild/easyconfigs/r/rasterstats/rasterstats-0.19.0-foss-2022a.eb
Labels: update

#18927 {data}[foss/2023a] ArviZ v0.16.1, h5netcdf v1.2.0, xarray v2023.9.0
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.16.1-foss-2023a.eb
  easybuild/easyconfigs/h/h5netcdf/h5netcdf-1.2.0-foss-2023a.eb
  easybuild/easyconfigs/x/xarray/xarray-2023.9.0-gfbf-2023a.eb
Labels: update

#18926 {bio,lib}[GCC/12.3.0] biobambam2 v2.0.185, libmaus2 v2.0.813
  easybuild/easyconfigs/b/biobambam2/biobambam2-2.0.185-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libmaus2/libmaus2-2.0.813-GCC-12.3.0.eb
Labels: update

#18929 {math}[foss/2023a] PyMC v5.9.0
  easybuild/easyconfigs/p/PyMC/PyMC-5.9.0-foss-2023a.eb
Labels: new

#18922 also build Python bindings for ITK 5.2.1 with foss/2022a
  easybuild/easyconfigs/i/ITK/ITK-5.2.1-foss-2022a.eb
Labels: enhancement, change

#18935 {data}[foss/2022a] SHAP v0.42.1
  easybuild/easyconfigs/s/SHAP/SHAP-0.42.1-foss-2022a.eb
Labels: update

#18937 {bio}[GCC/12.3.0] FastANI v1.34
  easybuild/easyconfigs/f/FastANI/FastANI-1.34-GCC-12.3.0.eb
Labels: update

#18938 {bio}[gompi/2023a] HMMER v3.4
  easybuild/easyconfigs/h/HMMER/HMMER-3.4-gompi-2023a.eb
Labels: update

#18940 {compiler}[system/system] Go v1.21.2
  easybuild/easyconfigs/g/Go/Go-1.21.2.eb
Labels: update

#18936 {bio}[GCC/12.3.0] fasta-reader v3.0.2
  easybuild/easyconfigs/f/fasta-reader/fasta-reader-3.0.2-GCC-12.3.0.eb
Labels: new

#18947 {bio}[GCCcore/12.3.0] EDirect v20.5.20231006
  easybuild/easyconfigs/e/EDirect/EDirect-20.5.20231006-GCCcore-12.3.0.eb
Labels: update

#18939 {bio}[GCC/12.3.0] Mash v2.3, CapnProto v1.0.1
  easybuild/easyconfigs/c/CapnProto/CapnProto-1.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-12.3.0.eb
Labels: update

#18941 remove `'cstd': 'c++17'` as this is default in GCC 11 for Mash
  easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-11.2.0.eb
  easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-11.3.0.eb
Labels: code cleanup

#18943 remove `'cstd': 'c++17'` as this is default in GCC 11 for Abseil
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.3-GCCcore-12.3.0.eb
Labels: code cleanup

#18944 remove `'cstd': 'c++17'` as this is default in GCC 11 for GLIMPSE
  easybuild/easyconfigs/g/GLIMPSE/GLIMPSE-2.0.0-GCC-11.3.0.eb
  easybuild/easyconfigs/g/GLIMPSE/GLIMPSE-2.0.0-GCC-12.2.0.eb
Labels: code cleanup

#18942 remove `'cstd': 'c++17'` as this is default in GCC 11 and no longer needed `lowopt` for CapnProto
  easybuild/easyconfigs/c/CapnProto/CapnProto-0.10.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/CapnProto/CapnProto-0.10.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/c/CapnProto/CapnProto-0.9.1-GCCcore-11.2.0.eb
Labels: code cleanup

#18946 remove `'cstd': 'c++17'` as this is default in GCC 11 for OGDF
  easybuild/easyconfigs/o/OGDF/OGDF-dogwood-202202-GCC-11.2.0.eb
Labels: code cleanup

#18953 {bio}[foss/2022b] CopyKAT v1.1.0 w/ R 4.2.2
  easybuild/easyconfigs/c/CopyKAT/CopyKAT-1.1.0-foss-2022b-R-4.2.2.eb
Labels: update

#18954 {data}[GCCcore/12.3.0] XML-Parser v2.46 w/ Perl 5.36.1
  easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.46-GCCcore-12.3.0-Perl-5.36.1.eb
Labels: update

#18955 {bio}[foss/2023a] ctffind v4.1.14
  easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2023a.eb
Labels: update

#18949 {bio}[foss/2021a] scCODA v0.1.9, tensorflow-probability v0.14.0, scikit-bio v0.5.7, rpy2 v3.4.5, ArviZ v0.12.1
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.12.1-foss-2021a.eb
  easybuild/easyconfigs/r/rpy2/rpy2-3.4.5-foss-2021a.eb
  easybuild/easyconfigs/s/scCODA/scCODA-0.1.9-foss-2021a.eb
  easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.5.7-foss-2021a.eb
  easybuild/easyconfigs/t/tensorflow-probability/tensorflow-probability-0.14.0-foss-2021a.eb
Labels: new, update

#18952 {bio}[foss/2022b] plot1cell v0.0.1, DoubletFinder v2.0.3-20230819, loomR v0.2.0-20180425 w/ R 4.2.2
  easybuild/easyconfigs/d/DoubletFinder/DoubletFinder-2.0.3-20230819-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/l/loomR/loomR-0.2.0-20180425-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/p/plot1cell/plot1cell-0.0.1-foss-2022b-R-4.2.2.eb
Labels: update

#18950 {lib}[gompi/2023a] mpifileutils v0.11.1, attr v2.5.1, dtcmp v1.1.4, ...
  easybuild/easyconfigs/a/attr/attr-2.5.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.4-gompi-2023a.eb
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-gompi-2023a.eb
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.5-gompi-2023a.eb
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.11.1-gompi-2023a.eb
Labels: update

#18951 {bio}[foss/2022b] alleleIntegrator v0.8.8, alleleCount v4.3.0, ASCAT v3.1.2 w/ R 4.2.2
  easybuild/easyconfigs/a/ASCAT/ASCAT-3.1.2-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/a/alleleCount/alleleCount-4.3.0-GCC-12.2.0.eb
  easybuild/easyconfigs/a/alleleIntegrator/alleleIntegrator-0.8.8-foss-2022b-R-4.2.2.eb
Labels: update

#18957 {bio}[foss/2022b] Monocle3 v1.3.1 w/ R 4.2.2
  easybuild/easyconfigs/m/Monocle3/Monocle3-1.3.1-foss-2022b-R-4.2.2.eb
Labels: update

#18959 {data}[iimpi/2023a] netCDF-Fortran v4.6.1
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.6.1-iimpi-2023a.eb
Labels: update

#18931 {data}[foss/2019b] SHAP v0.42.1 w/ Python 3.7.4
  easybuild/easyconfigs/s/SHAP/SHAP-0.42.1-foss-2019b-Python-3.7.4.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#18919 {data}[GCCcore/10.3.0] Raptor v2.0.16
  easybuild/easyconfigs/r/Raptor/Raptor-2.0.16-GCCcore-10.3.0.eb
Labels: new

#18981 {bio}[GCC/12.3.0] MAFFT v7.520 w/ with extensions
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.520-GCC-12.3.0-with-extensions.eb
Labels: update

#18075 {lib}[foss/2022b] CuPy v12.1.0 w/ Python 3.10.8 + CUDA 12.0.0
  easybuild/easyconfigs/c/CuPy/CuPy-12.1.0-foss-2022b-CUDA-12.0.0.eb
Labels: update

#18854 add patch to improve CUDA 11 compatibility of `GCCcore/12.2.0` and `GCCcore/12.3.0`
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0_improve-cuda-compatibility.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb
Labels: enhancement

#18963 make sure Python dependency included for ESPResSo is actually used by specifying `-DPYTHON_EXECUTABLE`
  easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2021a.eb
  easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2022a-CUDA-11.8.0.eb
  easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2022a.eb
Labels: bug fix, EESSI

#18934 scripts to archive easyconfigs
  scripts/archive_old
  scripts/archive_toolchain
Labels: EasyBuild-5.0

#18930 {lib}[foss/2022a] segmentation-models-pytorch v0.3.3 w/ Python 3.10.4
  easybuild/easyconfigs/s/segmentation-models-pytorch/segmentation-models-pytorch-0.3.3-foss-2022a.eb
Labels: new

#18994 {lang}[GCC/11.3.0] CUDA-Samples v11.6 w/ CUDA 11.7.0
  easybuild/easyconfigs/c/CUDA-Samples/CUDA-Samples-11.6-GCC-11.3.0-CUDA-11.7.0.eb
Labels: update

#18933 {bio,tools}[foss/2022a] ResistanceGA v4.2-5, RCall v0.13.17 w/ R 4.2.1 Julia 1.9.2
  easybuild/easyconfigs/r/RCall/RCall-0.13.17-disable_gpu_test.patch
  easybuild/easyconfigs/r/RCall/RCall-0.13.17-foss-2022a-R-4.2.1-Julia-1.9.2.eb
  easybuild/easyconfigs/r/ResistanceGA/JuliaCall-0.17.5-top_level_macro.patch
  easybuild/easyconfigs/r/ResistanceGA/ResistanceGA-4.2-5-foss-2022a-R-4.2.1-Julia-1.9.2.eb
Labels: new

#18988 {tools}[system/system] Jmol v16.1.41
  easybuild/easyconfigs/j/Jmol/Jmol-16.1.41-Java-11.eb
Labels: new

#18997 {lib}[GCCcore/12.3.0] LMDB v0.9.31
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.31-GCCcore-12.3.0.eb
Labels: update

#18987 {vis}[GCC/12.3.0,GCCcore/12.3.0] GST-plugins-bad v1.22.5, GTK4 v4.13.1, PyCairo v1.25.0, ...
  easybuild/easyconfigs/g/GST-plugins-bad/GST-plugins-bad-1.22.5-GCC-12.3.0.eb
  easybuild/easyconfigs/g/GTK4/GTK4-4.13.1-GCC-12.3.0.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.25.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.46.0-GCCcore-12.3.0.eb
Labels: update

#19001 detect the correct Python for vcflib
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.9-foss-2022a-R-4.2.1.eb
Labels: bug fix

#18983 {chem}[foss/2021a] RDKit v2023.03.3 w/ Python 3.9.5
  easybuild/easyconfigs/r/RDKit/RDKit-2023.03.3-foss-2021a.eb
Labels: update

#19003 {bio}[GCCcore/12.3.0] GATK v4.4.0.0 w/ Java 17
  easybuild/easyconfigs/g/GATK/GATK-4.4.0.0-GCCcore-12.3.0-Java-17.eb
Labels: update

#18962 {chem,lib}[intel/2023a] GlobalArrays v5.8.2, OpenMolcas v23.06
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-intel-2023a.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-23.06-intel-2023a.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-23.06_mcpdft_deps.patch
Labels: update, 2023a

#19008 Archive remaining toolchains from before 2020a
  easybuild/easyconfigs/__archive__/a/Autoconf/Autoconf-2.69-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/a/Automake/Automake-1.16.1-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/a/Autotools/Autotools-20180311-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/b/Bison/Bison-3.3.2-GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/b/Bison/Bison-3.3.2-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/b/binutils/binutils-2.32-GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/b/binutils/binutils-2.32-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/f/flex/flex-2.6.4-GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/f/flex/flex-2.6.4-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/g/GCC/GCC-9.1.0-2.32.eb
  easybuild/easyconfigs/__archive__/g/GCC/GCC-9.2.0-2.32.eb
  easybuild/easyconfigs/__archive__/g/GCC/GCC-9.2.0.eb
  easybuild/easyconfigs/__archive__/g/GCCcore/GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/g/GCCcore/GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/h/HPL/HPL-2.3-intel-2020.00.eb
  easybuild/easyconfigs/__archive__/h/help2man/help2man-1.47.10-GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/h/help2man/help2man-1.47.10-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/h/hwloc/hwloc-2.1.0-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/i/iccifort/iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/__archive__/i/iccifort/iccifort-2020.0.166.eb
  easybuild/easyconfigs/__archive__/i/iimpi/iimpi-2020.00.eb
  easybuild/easyconfigs/__archive__/i/imkl/imkl-2020.0.166-iimpi-2020.00.eb
  easybuild/easyconfigs/__archive__/i/impi/impi-2019.6.166-iccifort-2020.0.166-GCC-9.2.0.eb
  easybuild/easyconfigs/__archive__/i/intel/intel-2020.00.eb
  easybuild/easyconfigs/__archive__/l/libpciaccess/libpciaccess-0.16-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/l/libtool/libtool-2.4.6-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/l/libxml2/libxml2-2.9.10-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/m/M4/M4-1.4.18-GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/m/M4/M4-1.4.18-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/n/numactl/numactl-2.0.13-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.2.0.eb
  easybuild/easyconfigs/__archive__/o/OpenMPI/OpenMPI-4.0.2-GCC-9.2.0-2.32.eb
  easybuild/easyconfigs/__archive__/x/XZ/XZ-5.2.4-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/x/xorg-macros/xorg-macros-1.19.2-GCCcore-9.2.0.eb
  easybuild/easyconfigs/__archive__/z/zlib/zlib-1.2.11-GCCcore-9.1.0.eb
  easybuild/easyconfigs/__archive__/z/zlib/zlib-1.2.11-GCCcore-9.2.0.eb
Labels: EasyBuild-5.0

#19011 {tools}[GCCcore/11.3.0,GCCcore/12.2.0] Scalene v1.5.26
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.20-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.26-GCCcore-12.2.0.eb
Labels: update

#18784 {bio}[foss/2021a] BgeeCall v1.16.0
  easybuild/easyconfigs/b/BgeeCall/BgeeCall-1.16.0-foss-2021a-R-4.1.0.eb
Labels: new

#19007 {bio}[GCC/12.3.0] RAxML-NG v1.2.0
  easybuild/easyconfigs/r/RAxML-NG/RAxML-NG-1.2.0-GCC-12.3.0.eb
Labels: update

#19016 {data}[GCCcore/12.2.0] synapseclient v3.0.0
  easybuild/easyconfigs/s/synapseclient/synapseclient-3.0.0-GCCcore-12.2.0.eb
Labels: new

#18999 {vis}[foss/2023a] OpenCV v4.8.1 w/ contrib
  easybuild/easyconfigs/a/ant/ant-1.10.14-Java-11.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.1-foss-2023a-contrib.eb
Labels: update, 2023a

#18974 {vis}[GCCcore/12.3.0] OpenSlide v3.4.1, openslide-python v1.3.1 w/ largefiles
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1-GCCcore-12.3.0-largefiles.eb
  easybuild/easyconfigs/o/openslide-python/openslide-python-1.3.1-GCCcore-12.3.0.eb
Labels: update

#18986 {numlib}[foss/2022a] Trilinos v13.4.1 w/ Python 3.10.4 Zoltan-F90-API
  easybuild/easyconfigs/t/Trilinos/Trilinos-13.4.1-foss-2022a-zoltan.eb
Labels: update

#19017 {tools}[foss/2022a] cpio v2.14
  easybuild/easyconfigs/c/cpio/cpio-2.14-GCCcore-11.3.0.eb
Labels: new

#19027 add escape extesion to Bioconductor 3.16 bundle
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
Labels: enhancement

#19023 fix invalid pointer access in UCX 1.11-1.14
  easybuild/easyconfigs/u/UCX/UCX-1.11.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.11.0_fix-implicit-odp-release.patch
  easybuild/easyconfigs/u/UCX/UCX-1.11.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.12.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.13.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.14.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.14.1-GCCcore-12.3.0.eb
Labels: bug fix

#19024 disable `threadedmpi` in recent SCOTCH easyconfigs using `gompi` toolchain
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-gompi-2020a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2020b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2021a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.2-gompi-2021b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.1-gompi-2022a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.3-gompi-2023a.eb
Labels: bug fix, change

#19020 {bio}[system/system] Coot v0.9.8.92 w/ binary Linux x86_64 scientific linux 7.6 python gtk2
  easybuild/easyconfigs/c/Coot/Coot-0.9.8.92-binary-Linux-x86_64-scientific-linux-7.6-python-gtk2.eb
Labels: update

#19026 {tools}[foss/2022a] GSD v3.2.0
  easybuild/easyconfigs/g/GSD/GSD-3.2.0-foss-2022a.eb
Labels: new

#19018 {lib}[foss/2022a] TensorRT v8.6.1 w/ CUDA 11.7.0 Python 3.10.4
  easybuild/easyconfigs/t/TensorRT/TensorRT-8.6.1-foss-2022a-CUDA-11.7.0.eb
Labels: update

#18965 {bio}[foss/2022a] starparser-1.49-foss-2022a.eb
  easybuild/easyconfigs/s/starparser/starparser-1.49-foss-2022a.eb
Labels: new

#18980 {bio}[foss/2023a] OrthoFinder v2.5.5, BLAST+ v2.14.1, DIAMOND v2.1.8, FastME v2.1.6.3, MCL v22.282, MMseqs2 v14-7e284, cimfomfa v22.273 + enhanced sanity check for LMDB v0.9.31
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.1-gompi-2023a.eb
  easybuild/easyconfigs/c/cimfomfa/cimfomfa-22.273-GCCcore-12.3.0.eb
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.1.8-GCC-12.3.0.eb
  easybuild/easyconfigs/f/FastME/FastME-2.1.6.3-GCC-12.3.0.eb
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.31-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MCL/MCL-22.282-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-14-7e284-gompi-2023a.eb
  easybuild/easyconfigs/o/OrthoFinder/OrthoFinder-2.5.5-foss-2023a.eb
Labels: update

#13198 {geo}[SYSTEM] SNAP-ESA v8.0 and python interface with Python-2.7.18/GCCcore-10.2.0
  easybuild/easyconfigs/s/SNAP-ESA-python/SNAP-ESA-python-8.0-GCCcore-10.2.0-Java-1.8-Python-2.7.18.eb
  easybuild/easyconfigs/s/SNAP-ESA/SNAP-ESA-8.0-Java-1.8.eb
  easybuild/easyconfigs/s/SNAP-ESA/SNAP-ESA-8.0-response.varfile
Labels: new

#19035 {tools}[GCCcore/13.2.0] expat v2.5.0, groff v1.23.0
  easybuild/easyconfigs/e/expat/expat-2.5.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/groff/groff-1.23.0-GCCcore-13.2.0.eb
Labels: update

#19034 {bio}[GCCcore/12.3.0] pyEGA3 v5.0.2
  easybuild/easyconfigs/p/pyEGA3/pyEGA3-5.0.2-GCCcore-12.3.0.eb
Labels: update

#19032 {astro}[foss/2022a] emcee v3.1.4
  easybuild/easyconfigs/e/emcee/emcee-3.1.4-foss-2022a.eb
Labels: update

#19033 {lib}[foss/2022a] zeus-mcmc v2.5.4
  easybuild/easyconfigs/z/zeus-mcmc/zeus-mcmc-2.5.4-foss-2022a.eb
Labels: new

#19040 Move ASE from foss/2023a tol gfbf/2023a
  easybuild/easyconfigs/a/ASE/ASE-3.22.1-gfbf-2023a.eb
Labels: change

#19045 Build Qt5 with Python 3 instead of 2
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.10-GCCcore-12.3.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.10_webengine-chromium-drop-catapult.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.10_webengine-chromium-python3.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.10_webengine-drop-catapult.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.10_webengine-python3.11.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.10_webengine-python3.patch
Labels: update

#19042 Adding missing GSL dependency to casacore-3.4.0-foss-2021b
  easybuild/easyconfigs/c/casacore/casacore-3.4.0-foss-2021b.eb
Labels: bug fix

#19043 {perf}[iimpi/2022b] OSU-Micro-Benchmarks v6.2
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-6.2-iimpi-2022b.eb
Labels: update

#19010 {astro,lib}[foss/2022a] DP3-6.0, WSClean 3.3-b6b995c7 and deps
  easybuild/easyconfigs/a/AOFlagger/AOFlagger-3.4.0-foss-2022a.eb
  easybuild/easyconfigs/c/casacore/casacore-3.5.0-foss-2022a.eb
  easybuild/easyconfigs/d/DP3/DP3-6.0-foss-2022a.eb
  easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.5.2-foss-2022a.eb
  easybuild/easyconfigs/p/PGPLOT/PGPLOT-5.2.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/w/WCSLIB/WCSLIB-7.11-GCC-11.3.0.eb
  easybuild/easyconfigs/w/WSClean/WSClean-3.4-foss-2022a.eb
Labels: new, update

#19029 {bio,vis}[foss/2022a] n2v v0.3.2, CSBDeep v0.7.4
  easybuild/easyconfigs/c/CSBDeep/CSBDeep-0.7.4-foss-2022a.eb
  easybuild/easyconfigs/n/n2v/n2v-0.3.2-foss-2022a.eb
Labels: update

#19047 fix pybind11 incompatibility with some CUDA versions and add Catch2 dependency for tests
  easybuild/easyconfigs/c/Catch2/Catch2-2.13.9.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.10.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.10.3_fix-nvcc-compat.patch
  easybuild/easyconfigs/p/pybind11/pybind11-2.10.3_require-catch.patch
  easybuild/easyconfigs/p/pybind11/pybind11-2.11.1-GCCcore-12.3.0.eb
Labels: bug fix

#19015 {ai}[foss/2022a] PyTorch-bundle v1.13.1
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-1.13.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch-bundle/torchtext-0.14.1_use-system-libs.patch
Labels: update

#18998 {lang}[GCC/12.3.0] CUDA-Samples v12.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/c/CUDA-Samples/CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb
Labels: update

#19050 {data}[GCCcore/12.3.0] HDF v4.2.16
  easybuild/easyconfigs/h/HDF/HDF-4.2.16-GCCcore-12.3.0.eb
Labels: update

#19025 {bio}[foss/2022a] GTDB-Tk v2.3.2
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-2.3.2-foss-2022a.eb
Labels: update

#18964 {math}[gfbf/2022b,GCC/12.2.0] sympy v1.12, gmpy2 v2.1.5
  easybuild/easyconfigs/g/gmpy2/gmpy2-2.1.5-GCC-12.2.0.eb
  easybuild/easyconfigs/s/sympy/sympy-1.12-gfbf-2022b.eb
Labels: update

#19048 {chem}[GCCcore/12.3.0] ASAP3 v3.13.2, kim-api v2.3.0, openkim-models v20210811, ...
  easybuild/easyconfigs/a/ASAP3/ASAP3-3.13.2-foss-2023a.eb
  easybuild/easyconfigs/k/kim-api/kim-api-2.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/openkim-models/openkim-models-20210811-GCCcore-12.3.0.eb
Labels: update

#19038 {tools}[GCCcore/13.2.0] patchelf v0.18.0, Ninja v1.11.1, git v2.42.0
  easybuild/easyconfigs/g/git/git-2.42.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.11.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0-GCCcore-13.2.0.eb
Labels: update

#19053 {lib,vis}[GCCcore/13.2.0] gperf v3.1, libpng v1.6.40, util-linux v2.39, Brotli v1.1.0, fontconfig v2.14.2, freetype v2.13.2
  easybuild/easyconfigs/b/Brotli/Brotli-1.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.14.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.13.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.40-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.39-GCCcore-13.2.0.eb
Labels: update

#19037 {lang}[GCCcore/13.2.0] Perl-bundle-CPAN v5.38.0
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb
Labels: update

#19054 {devel,math}[GCCcore/13.2.0] Doxygen v1.9.8, GDRCopy v2.4, Eigen v3.4.0, GMP v6.3.0, libiconv v1.17, MPFR v4.2.1, PCRE2 v10.42, SWIG v4.1.1
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.9.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/e/Eigen/Eigen-3.4.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.3.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.17-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.2.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.42-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SWIG/SWIG-4.1.1-GCCcore-13.2.0.eb
Labels: update

#19051 {lib,tools}[GCCcore/13.2.0] cffi v1.15.1, gzip v1.13, libyaml v0.2.5, lz4 v1.9.4, Mako v1.2.4, Meson v1.2.3, PyYAML v6.0.1, Zip v3.0, zstd v1.5.5
  easybuild/easyconfigs/c/cffi/cffi-1.15.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/gzip/gzip-1.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libyaml/libyaml-0.2.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.9.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/Mako/Mako-1.2.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/Meson/Meson-1.2.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-6.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.5.5-GCCcore-13.2.0.eb
Labels: update

#19055 {devel,lib,system}[GCCcore/13.2.0] ZeroMQ v4.3.5, OpenPGM v5.2.122, libsodium v1.0.19
  easybuild/easyconfigs/l/libsodium/libsodium-1.0.19-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-13.2.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.5-GCCcore-13.2.0.eb
Labels: update

#19052 {lang}[GCCcore/13.2.0] Rust v1.73.0
  easybuild/easyconfigs/r/Rust/Rust-1.73.0-GCCcore-13.2.0.eb
Labels: update

#19044 {perf}[gompi/2022b] OSU-Micro-Benchmarks v6.2 w/ CUDA 12.0.0
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-6.2-gompi-2022b-CUDA-12.0.0.eb
Labels: update

#19046 {perf}[gompi/2023a] OSU-Micro-Benchmarks v7.2 w/ CUDA 12.1.1
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.2-gompi-2023a-CUDA-12.1.1.eb
Labels: update

#18467 don't disable building of third and fourth derivates in libxc 6.1.0
  easybuild/easyconfigs/l/libxc/libxc-6.1.0-GCC-12.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.1.0-intel-compilers-2022.2.1.eb
Labels: enhancement

#18478 {data}[system/system] Jblob v3.0
  easybuild/easyconfigs/j/Jblob/Jblob-3.0.eb
Labels: new

#19056 {devel,vis}[GCCcore/13.2.0] X11 v20231019, intltool v0.51.0
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/X11/X11-20231019-GCCcore-13.2.0.eb
Labels: update

#18382 rename ACT to Artemis
  easybuild/easyconfigs/a/ACT/ACT-18.0.2-Java-11.eb
  easybuild/easyconfigs/a/ACT/ACT-18.0.3-Java-11.eb
  easybuild/easyconfigs/a/Artemis/Artemis-18.0.2-Java-11.eb
  easybuild/easyconfigs/a/Artemis/Artemis-18.0.3-Java-11.eb
Labels: bug fix, change

#18392 {bio}[system/system] Artemis v18.2.0
  easybuild/easyconfigs/a/Artemis/Artemis-18.2.0-Java-11.eb
Labels: update

#12813 {bio}[foss/2020a] GEMMA v0.98.5
  easybuild/easyconfigs/g/GEMMA/GEMMA-0.98.5-foss-2020a.eb
Labels: update

#18354 {bio}[foss/2022b] MACS3 v3.0.0b2
  easybuild/easyconfigs/h/hmmlearn/hmmlearn-0.3.0-foss-2022b.eb
  easybuild/easyconfigs/m/MACS3/MACS3-3.0.0b2-foss-2022b.eb
Labels: new

#13045 {data}[foss/2020b] harmony v0.1.0-20210528
  easybuild/easyconfigs/h/harmony/harmony-0.1.0-20210528-foss-2020b-R-4.0.3.eb
Labels: update

#12319 {lib}[GCCcore/10.2.0] libbaseencode v1.0.11, libcotp v1.2.3
  easybuild/easyconfigs/l/libbaseencode/libbaseencode-1.0.11-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libcotp/libcotp-1.2.3-GCCcore-10.2.0.eb
Labels: new

#15230 {tools}[GCCcore/11.2.0] indicators v2.2
  easybuild/easyconfigs/i/indicators/indicators-2.2-GCCcore-11.2.0.eb
Labels: update

#15226 {lib}[GCCcore/11.2.0] fmt v8.1.1
  easybuild/easyconfigs/f/fmt/fmt-8.1.1-GCCcore-11.2.0.eb
Labels: update

#18287 {tools}[GCCcore/12.2.0] MUSCLE3 v0.7.0, QCG-PilotJob v0.13.1, Kaleido v0.2.1, msgpack-c v6.0.0, PyZMQ v25.1.0 w/ Python 3.10.8
  easybuild/easyconfigs/k/Kaleido/Kaleido-0.2.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MUSCLE3/MUSCLE3-0.7.0-foss-2022b.eb
  easybuild/easyconfigs/m/msgpack-c/msgpack-c-6.0.0-GCC-12.2.0.eb
  easybuild/easyconfigs/p/PyZMQ/PyZMQ-25.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/q/QCG-PilotJob/QCG-PilotJob-0.13.1-gfbf-2022b.eb
Labels: new, update

#17755 {bio}[GCCcore/12.2.0] dxpy v0.345.0 w/ Python 3.10.4
  easybuild/easyconfigs/d/dxpy/dxpy-0.345.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/d/dxpy/fusepy-3.0.1_fix-libfuse.patch
Labels: update

#16196 {tools}[GCC/11.3.0] plotutils v2.6
  easybuild/easyconfigs/p/plotutils/plotutils-2.6-GCC-11.3.0.eb
  easybuild/easyconfigs/p/plotutils/plotutils-2.6-png.patch
Labels: new

#15269 {phys}[foss/2020a] XOOPIC v20210302
  easybuild/easyconfigs/x/XOOPIC/XOOPIC-20210302-foss-2020a.eb
Labels: new

#18249 {chem}[foss/2022a] xtb v6.6.0
  easybuild/easyconfigs/x/xtb/xtb-6.6.0-foss-2022a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.6.0-foss-2022a_fix-custom-libraries.patch
Labels: update

#19031 {geo}[GCCcore/11.2.0] SNAP-ESA v9.0.0 + SNAP-ESA-python v9.0 w/ Python 2.7.18
  easybuild/easyconfigs/s/SNAP-ESA-python/SNAP-ESA-python-9.0.0-GCCcore-11.2.0-Java-11-Python-2.7.18.eb
  easybuild/easyconfigs/s/SNAP-ESA/SNAP-ESA-9.0.0-Java-11.eb
Labels: new, update

#19057 {lib}[GCCcore/13.2.0] Mesa v23.19, libunwind v1.6.2, LLVM v17.0.3, libdrm v2.4.117, libGLU v9.0.3, libglvnd v1.7.0
  easybuild/easyconfigs/l/LLVM/LLVM-16.0.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.117-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.6.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-23.1.9-GCCcore-13.2.0.eb
Labels: update

#19069 {bio}[system/system] MEGAN v6.25.3 w/ Java 17
  easybuild/easyconfigs/m/MEGAN/MEGAN-6.25.3-Java-17.eb
Labels: update

#18971 {lib}[foss/2022b] ALL v0.9.2
  easybuild/easyconfigs/a/ALL/ALL-0.9.2-foss-2022b.eb
Labels: new

#18985 Rename CVS to ConcurrentVersionsSystem
  .github/workflows/unit_tests.yml
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/CVS-1.11.23-getline.patch
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/CVS-1.11.23-zlib-1.patch
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCC-4.8.2.eb
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-4.9.3.eb
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-6.4.0.eb
  easybuild/easyconfigs/j/jhbuild/jhbuild-3.15.92-GCCcore-4.9.3.eb
  setup.cfg
Labels: bug fix, change

#19066 {ai}[foss/2022a] PyTorch v2.0.1
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1-foss-2022a.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_add-missing-vsx-vector-shift-functions.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_avoid-test_quantization-failures.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_disable-test-sharding.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-numpy-compat.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-shift-ops.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-skip-decorators.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-test-ops-conf.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-test_memory_profiler.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-torch.compile-on-ppc.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-ub-in-inductor-codegen.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_fix-vsx-loadu.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_ignore_unexpected_success_in_test_torchinductor_opinfo.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_no-cuda-stubs-rpath.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_remove-test-requiring-online-access.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_skip-diff-test-on-ppc.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_skip-failing-gradtest.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_skip-test_shuffle_reproducibility.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.0.1_skip-tests-skipped-in-subprocess.patch
Labels: update

#18009 also run easyconfigs test suite with Python 3.11
  .github/workflows/unit_tests.yml
Labels: enhancement, tests

#19080 use `sysroot` template in `wget` easyconfigs to define `PKG_CONFIG_PATH`
  easybuild/easyconfigs/w/wget/wget-1.19.4-GCCcore-6.4.0.eb
  easybuild/easyconfigs/w/wget/wget-1.20.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.20.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.20.3-GCCcore-10.2.0.eb
  easybuild/easyconfigs/w/wget/wget-1.20.3-GCCcore-9.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.21.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.21.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/w/wget/wget-1.21.3-GCCcore-11.3.0.eb
Labels: EESSI

#19036 {devel}[foss/2023a] buildenv vdefault w/ CUDA 12.1.1
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2023a.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-intel-2023a.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-nvompi-2022.07.eb
Labels: update

#18732 {data}[foss/2023a] GDAL v3.7.1
  easybuild/easyconfigs/g/GDAL/GDAL-3.7.1-foss-2023a.eb
Labels: update

#19074 {lib}[GCCcore/13.2.0] OpenEXR v3.2.0, Imath v3.1.9, libwebp v1.3.2, ...
  easybuild/easyconfigs/g/giflib/giflib-5.2.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/i/Imath/Imath-3.1.9-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libwebp/libwebp-1.3.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenEXR/OpenEXR-3.2.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.5.0-GCCcore-13.2.0.eb
Labels: update

#19076 {lib}[GCCcore/13.2.0] LZO v2.10, googletest v1.14.0, Highway v1.0.7
  easybuild/easyconfigs/g/googletest/googletest-1.14.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/h/Highway/Highway-1.0.7-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-13.2.0.eb
Labels: update

#19098 Enable PIC in recent libwebp build
  easybuild/easyconfigs/l/libwebp/libwebp-1.3.2-GCCcore-13.2.0.eb
Labels: bug fix

#19073 {lang,vis}[GCCcore/13.2.0] Tk v8.6.13, Tkinter v3.11.5
  easybuild/easyconfigs/t/Tk/Tk-8.6.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-3.11.5-GCCcore-13.2.0.eb
Labels: update

#19075 {vis}[GCCcore/13.2.0] Yasm v1.3.0, x264 v20231019, x265 v3.5
  easybuild/easyconfigs/x/x264/x264-20231019-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-13.2.0.eb
Labels: update

#19072 {math}[GCCcore/13.2.0] GDB v13.2, MPC v1.3.1, ISL v0.26, makeinfo v7.1
  easybuild/easyconfigs/g/GDB/GDB-13.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/i/ISL/ISL-0.26-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/MPC/MPC-1.3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-7.1-GCCcore-13.2.0.eb
Labels: update
