Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2023-09, with the labels that each got.

#18626 {tools}[GCCcore/12.3.0] Ghostscript v10.01.2
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-10.01.2-GCCcore-12.3.0.eb
Labels: update

#18484 consistently use ON/OFF for -DBUILD_SHARED_LIBS
  easybuild/easyconfigs/b/BUFRLIB/BUFRLIB-11.3.0.2-iccifort-2020.1.217.eb
  easybuild/easyconfigs/c/crossguid/crossguid-20190529-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.1.2-foss-2016a.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.1-intel-2017a.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.1-intel-2017b.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/LEMON/LEMON-1.3.1-GCC-8.2.0-2.31.1.eb
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/mstore/mstore-0.2.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/n/NTPoly/NTPoly-2.5.1-foss-2020b.eb
  easybuild/easyconfigs/n/NTPoly/NTPoly-2.5.1-intel-2020b.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.3.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.6.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.6.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.7.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.8.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.8.0-GCCcore-12.3.0.eb
Labels: bug fix

#18624 {tools}[gompi/2023a] CDO v2.2.2, ecBuild v3.8.0, ecCodes v2.31.0, libaec v1.0.6
  easybuild/easyconfigs/c/CDO/CDO-2.2.2-gompi-2023a.eb
  easybuild/easyconfigs/e/ecBuild/ecBuild-3.8.0.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.31.0-gompi-2023a.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.6-GCCcore-12.3.0.eb
Labels: update

#18698 remove html5lib-1.1-GCCcore-12.3.0.eb as html5lib is in Python-bundle-PyPI/2023.06-GCCcore-12.3.0
  easybuild/easyconfigs/h/html5lib/html5lib-1.1-GCCcore-12.3.0.eb
Labels: code cleanup

#18645 adding easyconfigs: GHC-9.2.2-x86_64.eb
  easybuild/easyconfigs/g/GHC/GHC-9.2.2-x86_64.eb
Labels: update

#18590 {vis}[GCCcore/12.3.0] graphviz-python v0.20.1, Graphviz v8.1.0, SWIG v4.1.1
  easybuild/easyconfigs/g/Graphviz/Graphviz-8.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/graphviz-python/graphviz-python-0.20.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/SWIG/SWIG-4.1.1-GCCcore-12.3.0.eb
Labels: update

#18599 {vis}[GCC/12.3.0] wxWidgets v3.2.2.1, GST-plugins-base v1.22.5, GStreamer v1.22.5, Graphene v1.10.8
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.22.5-GCC-12.3.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.22.5-GCC-12.3.0.eb
  easybuild/easyconfigs/g/Graphene/Graphene-1.10.8-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.2.2.1-GCC-12.3.0.eb
Labels: update

#18695 {bio,math}[foss/2022b] inferCNV v1.14.2, rjags v4-13 w/ R 4.2.2
  easybuild/easyconfigs/i/inferCNV/inferCNV-1.14.2-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/r/rjags/rjags-4-13-foss-2022b-R-4.2.2.eb
Labels: update

#18600 {vis}[GCCcore/12.3.0] gnuplot v5.4.8
  easybuild/easyconfigs/g/gnuplot/gnuplot-5.4.8-GCCcore-12.3.0.eb
Labels: update

#18591 {ai}[gfbf/2023a] CatBoost v1.2, conan v1.60.2, plotly.py v5.16.0
  easybuild/easyconfigs/c/CatBoost/CatBoost-1.2-gfbf-2023a.eb
  easybuild/easyconfigs/c/CatBoost/CatBoost-1.2_disable-widget.patch
  easybuild/easyconfigs/c/conan/conan-1.60.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/plotly.py/plotly.py-5.16.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/plotly.py/tenacity-8.2.3-fix_version.patch
Labels: new, update

#18676 {lib}[foss/2022a] tensorflow-compression v2.11.0 w/ CUDA 11.7.0
  easybuild/easyconfigs/t/tensorflow-compression/compression_local-tensorflow-repo.sed
  easybuild/easyconfigs/t/tensorflow-compression/tensorflow-compression-2.11.0-foss-2022a-CUDA-11.7.0.eb
Labels: new

#18692 {bio}[foss/2021b] GAPPadder v20170601, Biopython v1.76, KMC v3.2.1 w/ Python 2.7.18
  easybuild/easyconfigs/b/Biopython/Biopython-1.76-foss-2021b-Python-2.7.18.eb
  easybuild/easyconfigs/g/GAPPadder/GAPPadder-20170601-foss-2021b-Python-2.7.18.eb
  easybuild/easyconfigs/k/KMC/KMC-3.2.1-GCC-11.2.0-Python-2.7.18.eb
Labels: new, update

#18712 {system}[system/system] CUDA v12.2.2
  easybuild/easyconfigs/c/CUDA/CUDA-12.2.2.eb
Labels: update

#18616 {perf}[iimpi/2023a] OSU-Micro-Benchmarks v7.1-1
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.1-1-iimpi-2023a.eb
Labels: update, 2023a

#18647 add test for easyconfig file permissions
  test/easyconfigs/easyconfigs.py
Labels: enhancement, tests

#18703 {devel}[GCCcore/13.2.0] Perl v5.38.0, Autoconf v2.71, Automake v1.16.5, ...
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20220317-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.7-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.38.0-GCCcore-13.2.0.eb
Labels: update, 2023b

#18706 {devel}[GCCcore/13.2.0] pkgconf v2.0.3
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.0.3-GCCcore-13.2.0.eb
Labels: update, 2023b

#18704 {tools}[GCCcore/13.2.0] XZ v5.4.4, libxml2 v2.11.5, gettext v0.22, ...
  easybuild/easyconfigs/g/gettext/gettext-0.22-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/gettext/gettext-0.22.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.11.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.4.4-GCCcore-13.2.0.eb
Labels: update, 2023b

#18709 {lib,tools}[GCCcore/13.2.0] numactl v2.0.16, libfabric v1.19.0
  easybuild/easyconfigs/l/libfabric/libfabric-1.19.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.16-GCCcore-13.2.0.eb
Labels: update, 2023b

#18714 {tools}[system/system] ccache v4.8.3
  easybuild/easyconfigs/c/ccache/ccache-4.8.3.eb
Labels: update

#18705 {devel,system}[GCCcore/13.2.0] libpciaccess v0.17, xorg-macros v1.20.0
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.17-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.20.0-GCCcore-13.2.0.eb
Labels: update, 2023b

#18708 {lib}[GCCcore/13.2.0] libevent v2.1.12
  easybuild/easyconfigs/l/libevent/libevent-2.1.12-GCCcore-13.2.0.eb
Labels: update, 2023b

#18636 {bio}[GCCcore/11.3.0,foss/2022a] vcflib v1.0.9, WFA2 v2.3.3 w/ R 4.2.1
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.9-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.9_dep-fix.patch
  easybuild/easyconfigs/w/WFA2/WFA2-2.3.3-GCCcore-11.3.0.eb
Labels: new, update

#18707 {system}[GCCcore/13.2.0] hwloc v2.9.2
  easybuild/easyconfigs/h/hwloc/hwloc-2.9.2-GCCcore-13.2.0.eb
Labels: update, 2023b

#18614 {lib}[GCCcore/12.2.0,foss/2022b] Mikado v2.3.4, Greenlet v2.0.2, drmaa-python v0.7.9, slurm-drmaa v1.1.3
  easybuild/easyconfigs/d/drmaa-python/drmaa-python-0.7.9-GCCcore-12.2.0-slurm.eb
  easybuild/easyconfigs/g/Greenlet/Greenlet-2.0.2-foss-2022b.eb
  easybuild/easyconfigs/m/Mikado/Mikado-2.3.4-foss-2022b.eb
  easybuild/easyconfigs/s/slurm-drmaa/slurm-drmaa-1.1.3-GCCcore-12.2.0.eb
Labels: new, update

#18686 {mpi}[intel-compilers/2023.1.0] OpenMPI v4.1.5
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-intel-compilers-2023.1.0.eb
Labels: update

#18630 remove appending of `$__EGL_VENDOR_LIBRARY_DIRS` in recent Mesa easyconfigs, since Mesa easyblock now appends to it
  easybuild/easyconfigs/m/Mesa/Mesa-19.2.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-20.0.2-GCCcore-9.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-20.2.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.1.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.1.7-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-22.0.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-22.2.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-23.1.4-GCCcore-12.3.0.eb
Labels: change

#18725 strip out hardcoded `-march=native` used by RapidJSON 1.1.0
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-8.2.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-8.3.0.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-9.3.0.eb
Labels: bug fix, EESSI

#18727 disable detection of Dbus broker for `at-spi2-core` (+ bump at-spi2-core v2.49.90 to v2.49.91)
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.36.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.38.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.40.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.40.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.44.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.46.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.49.91-GCCcore-12.3.0.eb
Labels: bug fix, change

#18669 {devel,lib}[GCCcore/12.2.0] TensorFlow v2.13.0, dill v0.3.7, nsync v1.26.0, ...
  easybuild/easyconfigs/b/Bazel/Bazel-6.3.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-6.3.1_add-symlinks-in-runfiles.patch
  easybuild/easyconfigs/d/dill/dill-0.3.7-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/flatbuffers-python/flatbuffers-python-23.1.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.5-GCCcore-12.2.0.eb
  easybuild/easyconfigs/n/nsync/nsync-1.26.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0-foss-2022b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_add-default-shell-env.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_add-missing-snappy-function.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_add-missing-system-absl-py-target.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_add-missing-system-protobuf-targets.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_exclude-xnnpack-on-ppc.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_fix-protobuf-compatibility.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_remove-io-gcs-filesystem-dep.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_remove-libclang-dep.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_revert-to-flatbuffers-2.0.6.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.13.0_unpin-gast-version.patch
Labels: update

#18715 {bio}[GCC/11.3.0] Structure v2.3.4
  easybuild/easyconfigs/s/Structure/Structure-2.3.4-GCC-11.3.0.eb
Labels: update

#18734 {bio}[foss/2021a] scib-metrics v0.3.3, anndata v0.9.2
  easybuild/easyconfigs/a/anndata/anndata-0.9.2-foss-2021a.eb
  easybuild/easyconfigs/s/scib-metrics/scib-metrics-0.3.3-foss-2021a.eb
Labels: new, update

#18726 {bio}[foss/2022a,system/system] NanoCaller v3.4.1, RTG-Tools v3.12.1 w/ Java 11
  easybuild/easyconfigs/n/NanoCaller/NanoCaller-3.4.1-foss-2022a.eb
  easybuild/easyconfigs/r/RTG-Tools/RTG-Tools-3.12.1-Java-11.eb
Labels: new, update

#18735 rename `notebook` to `JupyterNotebook`
  easybuild/easyconfigs/j/JupyterNotebook/JupyterNotebook-7.0.2-GCCcore-12.3.0.eb
Labels: change

#18719 add `flextables` extension to R v4.2.1 + v4.2.2
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#18634 {tools}[GCCcore/12.3.0] Jupyter-bundle v20230823, jupyter-resource-usage v1.0.0, jupyterlmod v4.0.3
  easybuild/easyconfigs/j/Jupyter-bundle/Jupyter-bundle-20230823-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/jupyter-resource-usage/jupyter-resource-usage-1.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/jupyterlmod/jupyterlmod-4.0.3-GCCcore-12.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update, 2023a

#18739 make sure that 'moduleclass' is set in all easyconfig files (and is not set to default 'base' moduleclass)
  easybuild/easyconfigs/c/CCfits/CCfits-2.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/gdbm/gdbm-1.18.1-foss-2020a.eb
  easybuild/easyconfigs/g/gdbm/gdbm-1.21-GCCcore-10.2.0.eb
  easybuild/easyconfigs/h/humann/humann-3.6-foss-2022a.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-12.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: enhancement, bug fix, tests

#18733 {chem}[foss/2022b] ALAMODE v1.4.2
  easybuild/easyconfigs/a/ALAMODE/ALAMODE-1.4.2-foss-2022b.eb
  easybuild/easyconfigs/s/spglib/spglib-2.0.2-GCCcore-12.2.0.eb
Labels: update

#18701 {tools}[GCCcore/12.3.0] Scalene v1.5.26
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.26-GCCcore-12.3.0.eb
Labels: update

#18746 add patch for MPFR 4.1.0 to fix failing tsprintf test with glibc >= 2.37
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.1.0_patch-fix-tsprintf-test.patch
Labels: bug fix, EESSI

#18736 {lib}[GCCcore/12.3.0] libsndfile v1.2.2
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.2.2-GCCcore-12.3.0.eb
Labels: update

#18737 {vis}[GCCcore/12.3.0] ImageMagick v7.1.1-15
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-15-GCCcore-12.3.0.eb
Labels: update

#18751 {perf}[system/system] Advisor v2023.0.0, Advisor v2023.2.0
  easybuild/easyconfigs/a/Advisor/Advisor-2023.0.0.eb
  easybuild/easyconfigs/a/Advisor/Advisor-2023.2.0.eb
Labels: update

#18743 {bio}[foss/2021a] BgeeDB v2.26.0
  easybuild/easyconfigs/b/BgeeDB/BgeeDB-2.26.0-foss-2021a-R-4.1.0.eb
Labels: new

#18740 {tools}[GCCcore/12.3.0] tcsh v6.24.10
  easybuild/easyconfigs/t/tcsh/tcsh-6.24.10-GCCcore-12.3.0.eb
Labels: update

#18723 {tools}[GCCcore/12.3.0] gperftools v2.12
  easybuild/easyconfigs/g/gperftools/gperftools-2.12-GCCcore-12.3.0.eb
Labels: update

#18752 move wrapt from `foss/2022b` to `gfbf/2022b`
  easybuild/easyconfigs/w/wrapt/wrapt-1.15.0-gfbf-2022b.eb
Labels: bug fix, change

#18687 {lib}[GCCcore/12.3.0] CFITSIO v4.3.0
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-4.3.0-GCCcore-12.3.0.eb
Labels: update

#18730 {data}[gompi/2023a] PnetCDF v1.12.3
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.12.3-gompi-2023a.eb
Labels: update

#18753 filter out template + archived easyconfigs when determining changed easyconfigs in PRs
  test/easyconfigs/easyconfigs.py
Labels: tests

#18750 simplify build and install options for Ghostscript
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-10.0.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/Ghostscript/Ghostscript-10.01.2-GCCcore-12.3.0.eb
Labels: enhancement

#18329 {numlib}[foss/2022b] SuperLU_DIST v8.1.2
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-foss-2022b.eb
Labels: update

#18373 {lib}[GCCcore/11.3.0] json-fortran v8.3.0
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.3.0-GCCcore-11.3.0.eb
Labels: update

#18351 {numlib}[GCCcore/12.2.0] CGAL v5.5.2
  easybuild/easyconfigs/c/CGAL/CGAL-5.5.2-GCCcore-12.2.0.eb
Labels: update

#18364 {lib}[GCCcore/11.2.0] spdlog v1.10.0
  easybuild/easyconfigs/s/spdlog/spdlog-1.10.0-GCCcore-11.2.0.eb
Labels: update

#18755 add patch for PMIx 4.x to use lchown so links are not followed
  easybuild/easyconfigs/p/PMIx/PMIx-4.1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.1.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.2.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.2.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.x_lchown.patch
Labels: bug fix

#18372 {tools}[gompi/2022a] pFUnit v4.7.3
  easybuild/easyconfigs/p/pFUnit/pFUnit-4.7.3-gompi-2022a.eb
Labels: update

#18710 {lib}[GCCcore/13.2.0] OpenMPI v4.1.5, UCX v1.15.0-rc4, UCC v1.2.0, ...
  easybuild/easyconfigs/g/gompi/gompi-2023b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-13.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.2.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UCC/UCC-1.2.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.15.0-rc4-GCCcore-13.2.0.eb
Labels: update, 2023b

#18718 {tools}[GCCcore/12.2.0] numdiff v5.9.0
  easybuild/easyconfigs/n/numdiff/numdiff-5.9.0-GCCcore-12.2.0.eb
Labels: update

#18744 {vis}[GCCcore/12.2.0] motif v2.3.8
  easybuild/easyconfigs/m/motif/motif-2.3.8-GCCcore-12.2.0.eb
Labels: update

#18745 {chem}[foss/2022b,intel/2022b] DL_POLY_4 v5.1.0
  easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.1.0-foss-2022b.eb
  easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.1.0-intel-2022b.eb
Labels: update

#18716 {devel}[GCC/11.3.0] texlive v20230313
  easybuild/easyconfigs/t/texlive/texlive-20230313-GCC-11.3.0.eb
Labels: update

#17891 {tools}[intel/2022a] HPL v2.0.15 w/ CUDA 11.7.0
  easybuild/easyconfigs/h/HPL/HPL-2.0.15-intel-2022a-CUDA-11.7.0.eb
Labels: update

#18471 {chem}[GCC/12.3.0] libxc v6.2.2
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-GCC-12.3.0.eb
Labels: update

#18754 prepare release notes for EasyBuild v4.8.1 + bump version to 4.8.1
  RELEASE_NOTES
  setup.py
Labels: update, documentation

#18756 include additional PRs that got merged last-minute in v4.8.1 release notes
  RELEASE_NOTES
Labels: bug fix, documentation

#18738 {tools}[GCCcore/12.2.0] JupyterNotebook v7.0.3
  easybuild/easyconfigs/j/JupyterNotebook/JupyterNotebook-7.0.3-GCCcore-12.2.0.eb
Labels: update

#18758 {lib}[foss/2022a] scikit-optimize v0.9.0, pretty-yaml v23.9.5, photontorch v0.4.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/photontorch/photontorch-0.4.1-foss-2022a.eb
  easybuild/easyconfigs/p/pretty-yaml/pretty-yaml-23.9.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/scikit-optimize/scikit-optimize-0.9.0-foss-2022a.eb
Labels: update

#18761 {tools}[system/system] EasyBuild v4.8.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.8.1.eb
Labels: update

#18673 {base}[GCCcore/12.2.0] git-annex v10.20230802
  easybuild/easyconfigs/g/git-annex/git-annex-10.20230802-GCCcore-12.2.0.eb
Labels: new

#18762 sync with main + bump version to 4.8.2dev
  RELEASE_NOTES
  setup.py
Labels: update

#18763 {devel}[system/system] ReFrame v4.3.2
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.2.eb
Labels: update

#18764 {chem}[gfbf/2023a] libcint v5.4.0
  easybuild/easyconfigs/l/libcint/libcint-5.4.0-gfbf-2023a.eb
Labels: update

#18729 {tools}[foss/2023a] wrapt v1.15.0
  easybuild/easyconfigs/w/wrapt/wrapt-1.15.0-gfbf-2023a.eb
Labels: update

#18765 {tools}[system/system] VTune v2023.2.0
  easybuild/easyconfigs/v/VTune/VTune-2023.2.0.eb
Labels: update

#18766 {bio}[GCCcore/10.3.0] tabix v0.2.6
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-10.3.0.eb
Labels: update

#18773 {bio}[GCC/12.3.0] VCFtools v0.1.16
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-GCC-12.3.0.eb
Labels: update, 2023a

#18768 {numlib}[system/system] cuDNN v8.9.2.26 w/ CUDA 12.2.0
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.9.2.26-CUDA-12.2.0.eb
Labels: update

#18748 {bio}[foss/2022a] Clair3 v1.0.4
  easybuild/easyconfigs/c/Clair3/Clair3-1.0.4-foss-2022a.eb
  easybuild/easyconfigs/c/Clair3/Clair3-remove_htslib.patch
  easybuild/easyconfigs/c/cffi/cffi-1.15.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/mpath/mpath-1.1.3-GCCcore-11.3.0.eb
Labels: new, update

#18759 backport lchown patch to PMIx 3.1.x + 3.2.x
  easybuild/easyconfigs/p/PMIx/PMIx-3.1.4-GCCcore-8.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.1.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.1.5-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.1.x_lchown.patch
  easybuild/easyconfigs/p/PMIx/PMIx-3.2.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-3.2.x_lchown.patch
Labels: bug fix

#18778 {bio,lib}[foss/2022a,gompi/2022a] nanopolish v0.14.0, VBZ-Compression v1.0.3
  easybuild/easyconfigs/n/nanopolish/nanopolish-0.14.0-foss-2022a.eb
  easybuild/easyconfigs/v/VBZ-Compression/VBZ-Compression-1.0.3-gompi-2022a.eb
Labels: update

#18790 add patch for OpenBLAS 0.3.23 to fix hanging tests
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23-GCC-12.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23_fix-tests-hang.patch
Labels: bug fix, EESSI

#18779 {tools}[iimpi/2022b] worker v1.6.13
  easybuild/easyconfigs/w/worker/worker-1.6.13-iimpi-2022b.eb
Labels: update

#18776 {tools}[system/system] itac v2021.10.0
  easybuild/easyconfigs/i/itac/itac-2021.10.0.eb
Labels: update

#18785 rename isoseq3 after download for IsoSeq 3.8.2 + fix permissions
  easybuild/easyconfigs/i/IsoSeq/IsoSeq-3.8.2-linux-x86_64.eb
Labels: bug fix

#18786 {bio}[system/system] IsoSeq v4.0.0 w/ linux x86_64
  easybuild/easyconfigs/i/IsoSeq/IsoSeq-4.0.0-linux-x86_64.eb
Labels: update

#18787 {tools}[system/system] Inspector v2023.2.0
  easybuild/easyconfigs/i/Inspector/Inspector-2023.2.0.eb
Labels: update

#18783 also copy scripts directory for Clair3
  easybuild/easyconfigs/c/Clair3/Clair3-1.0.4-foss-2022a.eb
Labels: bug fix

#18370 {bio}[foss/2021a] MACS2 v2.2.7.1
  easybuild/easyconfigs/m/MACS2/MACS2-2.2.7.1-foss-2021a.eb
Labels: update

#18421 {ai}[foss/2022b] PyTorch v1.13.1
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1-foss-2022b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_disable-test-sharding.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-gcc-12-missing-includes.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-gcc-12-warning-in-fbgemm.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-numpy-deprecations.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-protobuf-dependency.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-python-3.11-compat.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_fix-warning-in-test-cpp-api.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_skip-failing-singular-grad-test.patch
  easybuild/easyconfigs/p/pytest-rerunfailures/pytest-rerunfailures-12.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pytest-shard/pytest-shard-0.1.2-GCCcore-12.2.0.eb
Labels: update

#18774 {bio}[GCC/12.3.0] Bowtie2 v2.5.1
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.1-GCC-12.3.0.eb
Labels: update

#18797 Ignore EasyConfig cache file
  .gitignore
Labels: enhancement

#18799 {devel}[GCCcore/10.3.0] pkgconf v1.8.0
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0-GCCcore-10.3.0.eb
Labels: update

#18803 {devel}[GCCcore/12.3.0] SCons v4.5.2
  easybuild/easyconfigs/s/SCons/SCons-4.5.2-GCCcore-12.3.0.eb
Labels: update

#18410 {chem}[foss/2022a] Amber v22.4 with AmberTools v22.5 + CUDA 11.7.0
  easybuild/easyconfigs/a/Amber/Amber-22.4-foss-2022a-AmberTools-22.5-CUDA-11.7.0.eb
Labels: update

#18813 {tools}[GCCcore/12.3.0] XlsxWriter v3.1.3
  easybuild/easyconfigs/x/XlsxWriter/XlsxWriter-3.1.3-GCCcore-12.3.0.eb
Labels: update

#18814 {data}[GCCcore/12.3.0] openpyxl v3.1.2
  easybuild/easyconfigs/o/openpyxl/openpyxl-3.1.2-GCCcore-12.3.0.eb
Labels: update

#18804 {chem}[foss/2023a] Cantera v3.0.0, SUNDIALS v6.6.0, HighFive v2.7.1, fmt v10.1.0, pygraphviz v1.11, ruamel.yaml v0.17.32
  easybuild/easyconfigs/c/Cantera/Cantera-3.0.0-foss-2023a.eb
  easybuild/easyconfigs/f/fmt/fmt-10.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/h/HighFive/HighFive-2.7.1-gompi-2023a.eb
  easybuild/easyconfigs/p/pygraphviz/pygraphviz-1.11-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/ruamel.yaml/ruamel.yaml-0.17.32-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-6.6.0-foss-2023a.eb
Labels: update

#18728 {data}[GCCcore/12.3.0] HDF v4.2.16-2
  easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-12.3.0.eb
Labels: update

#18817 {bio}[gompi/2021a] kallisto v0.48.0
  easybuild/easyconfigs/k/kallisto/kallisto-0.48.0-gompi-2021a.eb
Labels: update

#18833 add patch to fix Open MPI 4.1.5 with PMIx >= 4.2.3
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-13.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5_fix-pmix3x.patch
Labels: bug fix

#18801 {chem}[foss/2022a,intel/2022a] GPAW v23.9.1
  easybuild/easyconfigs/g/GPAW/GPAW-23.9.1-foss-2022a.eb
  easybuild/easyconfigs/g/GPAW/GPAW-23.9.1-intel-2022a.eb
Labels: update

#18834 fix permission issues when copying xvfb-run script in Xvfb easyconfigs
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.11-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.13-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.8-GCCcore-8.3.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.9-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-1.20.9-GCCcore-9.3.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-21.1.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-21.1.6-GCCcore-12.2.0.eb
  easybuild/easyconfigs/x/Xvfb/Xvfb-21.1.8-GCCcore-12.3.0.eb
Labels: bug fix, EESSI

#18819 {bio}[GCC/10.3.0] BLAT v3.7
  easybuild/easyconfigs/b/BLAT/BLAT-3.7-GCC-10.3.0.eb
Labels: update

#18821 {bio}[GCC/10.3.0] GMAP-GSNAP v2023-04-20
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2023-04-20-GCC-10.3.0.eb
Labels: update

#18822 {bio}[gompi/2021a] HISAT2 v2.2.1
  easybuild/easyconfigs/h/HISAT2/HISAT2-2.2.1-gompi-2021a.eb
Labels: update

#18825 {bio}[system/system] SMRT-Link v12.0.0.177059 w/ cli tools only
  easybuild/easyconfigs/s/SMRT-Link/SMRT-Link-12.0.0.177059-cli-tools-only.eb
Labels: update

#18800 {data}[foss/2021a] Arrow v8.0.0
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2021a.eb
Labels: update

#18841 {tools}[system/system] code-server v4.16.1
  easybuild/easyconfigs/c/code-server/code-server-4.16.1.eb
Labels: update

#18837 {math}[GCC/12.2.0] NTL v11.5.1
  easybuild/easyconfigs/n/NTL/NTL-11.5.1-GCC-12.2.0.eb
Labels: update

#18838 {data}[GCC/12.2.0] SVG v2.87
  easybuild/easyconfigs/s/SVG/SVG-2.87-GCC-12.2.0.eb
Labels: update

#18815 {bio}[foss/2021b] CIRIquant v1.1.2-20221201, scikit-learn v0.20.4, Pysam v0.17.0, PyYAML v5.4.1 w/ Python 2.7.18
  easybuild/easyconfigs/c/CIRIquant/CIRIquant-1.1.2-20221201-foss-2021b-Python-2.7.18.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-5.4.1-GCCcore-11.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/p/Pysam/Pysam-0.17.0-GCC-11.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.3_fix-cd_fast.patch
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.20.4-foss-2021b-Python-2.7.18.eb
Labels: new, update

#18846 {lib}[GCCcore/12.3.0] RDFlib v7.0.0
  easybuild/easyconfigs/r/RDFlib/RDFlib-7.0.0-GCCcore-12.3.0.eb
Labels: update

#18840 {math}[system/system] MATLAB v2023b
  easybuild/easyconfigs/m/MATLAB/MATLAB-2023b.eb
Labels: update

#18843 statically link Boost 1.75 in Cufflinks v20190706 installed with GCC/11.2.0, so Boost can be changed to build dependency
  easybuild/easyconfigs/c/Cufflinks/Cufflinks-20190706-GCC-11.2.0.eb
Labels: bug fix

#18851 {devel}[system/system] ReFrame v4.3.3
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.3.eb
Labels: update

#18855 Make util-linux build on CentOS 7 (issue #18519).
  easybuild/easyconfigs/u/util-linux/util-linux-2.39-GCCcore-12.3.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.39-fix-build-centos7.patch
Labels: enhancement, bug fix

#18767 {tools}[GCCcore/12.3.0] pytest-rerunfailures v12.0
  easybuild/easyconfigs/p/pytest-rerunfailures/pytest-rerunfailures-12.0-GCCcore-12.3.0.eb
Labels: update

#18850 {data,tools}[foss/2023a] dask v2023.9.2, bokeh v3.2.2
  easybuild/easyconfigs/b/bokeh/bokeh-3.2.2-foss-2023a.eb
  easybuild/easyconfigs/d/dask/dask-2023.9.2-foss-2023a.eb
Labels: update, 2023a

#18683 {devel}[GCCcore/12.3.0] Qt6 v6.5.2
  easybuild/easyconfigs/q/Qt6/Qt6-6.5.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/q/Qt6/Qt6-6.5.2_fix_OF-Gentoo.patch
Labels: new

#18869 {tools}[GCCcore/12.3.0] p7zip v17.04
  easybuild/easyconfigs/p/p7zip/p7zip-17.04-GCCcore-12.3.0.eb
Labels: update

#18866 {bio}[system/system] bases2fastq v1.5.1
  easybuild/easyconfigs/b/bases2fastq/bases2fastq-1.5.1.eb
Labels: new

#18830 {bio}[gompi/2022b] ProBiS v20230403
  easybuild/easyconfigs/p/ProBiS/ProBiS-20230403-gompi-2022b.eb
Labels: new

#18870 add patch to fix issue with automatic detection of NeoverseV1 CPU architecture in OpenBLAS v0.3.20
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.20_fix-cpuid-neoverse-v1-n2.patch
Labels: bug fix, EESSI, aarch64

#18861 {chem}[intel/2023a] DIRAC v23.0 w/ int64
  easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-intel-2023a-int64.eb
Labels: update

#18845 {chem}[intel/2023a] DIRAC v23.0
  easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-intel-2023a.eb
Labels: update

#18871 {devel}[GCCcore/12.3.0] xproto v7.0.31
  easybuild/easyconfigs/x/xproto/xproto-7.0.31-GCCcore-12.3.0.eb
Labels: update

#18863 {bio}[foss/2021a] BMTK v1.0.8
  easybuild/easyconfigs/b/BMTK/BMTK-1.0.8-foss-2021a.eb
Labels: new

#18860 {debugger,devel,math}[GCCcore/12.2.0] GDB v13.2, ISL v0.26, makeinfo v7.0.3
  easybuild/easyconfigs/g/GDB/GDB-13.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/i/ISL/ISL-0.26-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MPC/MPC-1.3.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/makeinfo/makeinfo-7.0.3-GCCcore-12.2.0.eb
Labels: update

#18872 {devel}[GCCcore/12.3.0] makedepend v1.0.7
  easybuild/easyconfigs/m/makedepend/makedepend-1.0.7-GCCcore-12.3.0.eb
Labels: update

#18847 add missing required PyPy dependency for Clair3, also copy preprocess and shared subdirectories, and enhance sanity check for provided libclair3 Python package
  easybuild/easyconfigs/c/Clair3/Clair3-1.0.4-foss-2022a.eb
  easybuild/easyconfigs/c/Clair3/Clair3-remove_htslib.patch
  easybuild/easyconfigs/p/PyPy/PyPy-7.3.12-3.10.eb
Labels: bug fix, new

#18876 {tools}[GCCcore/13.2.0] CMake v3.27.6, bzip2 v1.0.8, cURL v8.3.0, libarchive v3.7.2
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.27.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/cURL/cURL-8.3.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.7.2-GCCcore-13.2.0.eb
Labels: update

#18362 {chem}[system/system] Chemaxon-Marvin v23.9
  easybuild/easyconfigs/c/Chemaxon-Marvin/Chemaxon-Marvin-23.9.eb
Labels: update

#18216 {bio}[foss/2021a,gompi/2021a] RMBlast v2.14.0, RepeatMasker v4.1.5 w/ Python 3.9.5
  easybuild/easyconfigs/r/RMBlast/RMBlast-2.14.0-gompi-2021a.eb
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.1.5-foss-2021a.eb
Labels: update

#18631 {vis}[foss/2022b] Paraview 5.11.1 fat build compatible with hardware rendering, software rendering, headless server mode, as well as interactive mode.
  easybuild/easyconfigs/p/ParaView/ParaView-5.11.1-fix_thrust_vtk_m.patch
  easybuild/easyconfigs/p/ParaView/ParaView-5.11.1-foss-2022b-CUDA-12.2.0.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.11.1-foss-2022b.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.11.1-remove_glew_init_warning.patch
Labels: enhancement, update

#18878 fix source URL for segemehl 0.3.4
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-10.2.0.eb
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-10.3.0.eb
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-11.2.0.eb
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-GCC-8.3.0.eb
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-foss-2018b.eb
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-iccifort-2020.4.304.eb
Labels: bug fix

#18439 {toolchain} intel/2023.07
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2023.07.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2023.07.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2023.2.0-iimpi-2023.07.eb
  easybuild/easyconfigs/i/imkl/imkl-2023.2.0.eb
  easybuild/easyconfigs/i/impi/impi-2021.10.0-intel-compilers-2023.2.1.eb
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2023.2.1.eb
  easybuild/easyconfigs/i/intel/intel-2023.07.eb
Labels: update

#18879 {lang}[GCCcore/13.2.0] Python v3.11.5
  easybuild/easyconfigs/l/libffi/libffi-3.4.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.11.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.43.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-13.2.0.eb
Labels: update

#18880 {numlib}[GCC/13.2.0] OpenBLAS v0.3.24
  easybuild/easyconfigs/m/make/make-4.4.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.24-GCC-13.2.0.eb
Labels: update

#18882 {numlib}[GCC/13.2.0] BLIS v0.9.0
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0-GCC-13.2.0.eb
Labels: update

#18888 change gompi/2023b to gompi/2023.09 for now
  easybuild/easyconfigs/g/gompi/gompi-2023.09.eb
Labels: change, 2023b

#18868 {devel}[GCCcore/12.2.0] line_profiler v4.1.1
  easybuild/easyconfigs/l/line_profiler/line_profiler-4.1.1-GCCcore-12.2.0.eb
Labels: update

#18883 {lib}[GCC/13.2.0] FlexiBLAS v3.3.1
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.3.1-GCC-13.2.0.eb
Labels: update

#18887 add patch to disable flaky DDRGES3 LAPACK test in OpenBLAS 0.3.23 + 0.3.24
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23-GCC-12.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23_disable-DDRGES3-LAPACK-test.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.24-GCC-13.2.0.eb
Labels: bug fix

#18885 {numlib}[gompi/2023.09] ScaLAPACK v2.2.0 w/ fb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gompi-2023.09-fb.eb
Labels: update, 2023b

#18884 {numlib}[GCC/13.2.0,gompi/2023.09] FFTW v3.3.10, FFTW.MPI v3.3.10
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2023.09.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-GCC-13.2.0.eb
Labels: update, 2023b

#18796 {tools}[foss/2022a] Horovod v0.28.1 w/ CUDA 11.7.0 PyTorch 1.13.1
  easybuild/easyconfigs/h/Horovod/Horovod-0.28.1-foss-2022a-CUDA-11.7.0-PyTorch-1.13.1.eb
Labels: update
