Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2023-06, with the labels that each got.

#18006 stop running easyconfig unit tests with Python 2.7
  .github/workflows/unit_tests.yml
Labels: bug fix, change, tests

#17955 {lang}[GCCcore/12.3.0] Python v3.11.3
  easybuild/easyconfigs/p/Python/Python-3.11.3-GCCcore-12.3.0.eb
Labels: update, change, 2023a

#17999 {bio}[foss/2022a] WhatsHap v1.7 w/ Python 3.10.4
  easybuild/easyconfigs/w/WhatsHap/WhatsHap-1.7-foss-2022a.eb
Labels: update

#17946 {lang}[GCCcore/12.3.0] Perl v5.36.1 (with minimal set of extensions) + Autotools v20220317
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-12.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.5-GCCcore-12.3.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20220317-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.36.1-GCCcore-12.3.0.eb
Labels: update, change, 2023a

#18015 {numlib}[GCC/12.3.0] BLIS v0.9.0
  easybuild/easyconfigs/b/BLIS/BLIS-0.9.0-GCC-12.3.0.eb
Labels: update, 2023a

#17993 {toolchain} GCC v11.4.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-11.4.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.40-GCCcore-11.4.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-11.4.0.eb
  easybuild/easyconfigs/g/GCC/GCC-11.4.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.4.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.3-GCCcore-11.4.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-11.4.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.13-GCCcore-11.4.0.eb
Labels: update

#17293 {cae}[foss/2022a] ngspice v39
  easybuild/easyconfigs/n/ngspice/ngspice-39-foss-2022a.eb
Labels: update

#17055 {tools}[GCCcore/11.3.0] xdotool v3.20211022.1, xclip v0.13
  easybuild/easyconfigs/x/xclip/xclip-0.13-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/xdotool/xdotool-3.20211022.1-GCCcore-11.3.0.eb
Labels: new

#17294 {phys}[foss/2020b,intel/2020b] CHERAB v1.4.0 w/ Python 3.8.6
  easybuild/easyconfigs/c/CHERAB/CHERAB-1.4.0-foss-2020b.eb
  easybuild/easyconfigs/c/CHERAB/CHERAB-1.4.0-intel-2020b.eb
Labels: update

#18014 {bio}[GCCcore/11.3.0,foss/2022a] GetOrganelle v1.7.7.0, Bandage v0.9.0 w/ Python 3.10.4
  easybuild/easyconfigs/b/Bandage/Bandage-0.9.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GetOrganelle/GetOrganelle-1.7.7.0-foss-2022a.eb
Labels: update

#18011 {tools}[GCC/11.3.0] AutoDock-GPU v1.5.3
  easybuild/easyconfigs/a/AutoDock-GPU/AutoDock-GPU-1.5.3-GCC-11.3.0-CUDA-11.7.0.eb
Labels: update

#17806 {devel}[GCCcore/13.1.0] Perl v5.36.1 (with minimal set of extensions) + Autotools v20220317
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-13.1.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.16.5-GCCcore-13.1.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20220317-GCCcore-13.1.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.4.7-GCCcore-13.1.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.36.1-GCCcore-13.1.0.eb
Labels: update

#18018 {tools}[GCCcore/12.3.0] Ninja v1.11.1
  easybuild/easyconfigs/n/Ninja/Ninja-1.11.1-GCCcore-12.3.0.eb
Labels: update, 2023a

#18021 {devel,tools}[GCCcore/12.3.0] Meson v1.1.1, xorg-macros v1.20.0 w/ Python 3.11.3
  easybuild/easyconfigs/m/Meson/Meson-1.1.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.20.0-GCCcore-12.3.0.eb
Labels: update, 2023a

#18020 {math}[GCCcore/12.3.0] GMP v6.2.1, GSL v2.7, MPFR v4.2.0
  easybuild/easyconfigs/g/GMP/GMP-6.2.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.2.0-GCCcore-12.3.0.eb
Labels: update, 2023a

#18019 {numlib}[GCC/12.3.0] FFTW v3.3.10
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-GCC-12.3.0.eb
Labels: update, 2023a

#18022 {system}[GCCcore/12.3.0] hwloc v2.9.1, libpciaccess v0.17
  easybuild/easyconfigs/h/hwloc/hwloc-2.9.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.17-GCCcore-12.3.0.eb
Labels: update, 2023a

#18023 {tools}[GCCcore/12.3.0] util-linux v2.39
  easybuild/easyconfigs/u/util-linux/util-linux-2.39-GCCcore-12.3.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.39_fix_waitpid.patch
Labels: update, 2023a

#18024 {lib}[GCCcore/12.3.0] Yasm v1.3.0, yaml-cpp v0.7.0, Xerces-C++ v3.2.4, ... w/ Python 3.11.3
  easybuild/easyconfigs/l/lxml/lxml-4.9.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PyYAML/PyYAML-6.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/y/yaml-cpp/yaml-cpp-0.7.0-GCCcore-12.3.0.eb
Labels: update, 2023a

#18025 {lib}[GCCcore/12.3.0] libfabric v1.18.0
  easybuild/easyconfigs/l/libfabric/libfabric-1.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.18.0_disable-psm3-avx-config.patch
Labels: update, 2023a

#18031 {perf}[foss/2022a,gompi/2022a] Extrae v4.0.4, Paraver v4.11.1
  easybuild/easyconfigs/e/Extrae/Extrae-4.0.4-change_libdwarf_path.patch
  easybuild/easyconfigs/e/Extrae/Extrae-4.0.4-gompi-2022a.eb
  easybuild/easyconfigs/p/Paraver/Paraver-4.11.1-foss-2022a.eb
Labels: update

#18033 {bio}[GCC/11.3.0] samblaster v0.1.26
  easybuild/easyconfigs/s/samblaster/samblaster-0.1.26-GCC-11.3.0.eb
Labels: update

#18030 fix exec permissions for all binaries & scripts of L_RNA_scaffolder 20190530
  easybuild/easyconfigs/l/L_RNA_scaffolder/L_RNA_scaffolder-20190530-GCC-11.3.0.eb
Labels: bug fix

#18002 {tools}[GCCcore/11.3.0] libheif v1.16.2, libde265 v1.0.11, libjxl v0.8.1, Highway v1.0.4, Zopfli v1.0.3, zlib-ng v2.0.7
  easybuild/easyconfigs/h/Highway/Highway-1.0.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libde265/libde265-1.0.11-GCC-11.3.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.16.2-GCC-11.3.0.eb
  easybuild/easyconfigs/l/libjxl/libjxl-0.8.1-foss-2022a.eb
  easybuild/easyconfigs/z/Zopfli/Zopfli-1.0.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/z/zlib-ng/zlib-ng-2.0.7-GCCcore-11.3.0.eb
Labels: update

#9258 {bio}[GCCcore/8.2.0,foss/2019a] 3d-dna v180922, LASTZ v1.02.00 w/ Python 2.7.15
  easybuild/easyconfigs/0/3d-dna/3d-dna-180922-GCCcore-8.2.0-Python-2.7.15.eb
  easybuild/easyconfigs/l/LASTZ/LASTZ-1.02.00-GCCcore-8.2.0.eb
Labels: new, update

#18035 {lang}[system/system] Anaconda3 v2023.03-1
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2023.03-1.eb
Labels: update

#18010 {chem}[foss/2022b] Dalton v2020.1
  easybuild/easyconfigs/d/Dalton/Dalton-2020.1-foss-2022b.eb
Labels: update

#18037 {vis}[foss/2022a] PyQtGraph v0.13.3 w/ Python 3.10.4
  easybuild/easyconfigs/p/PyQtGraph/PyQtGraph-0.13.3-foss-2022a.eb
Labels: update

#18038 {lib}[GCCcore/11.3.0] psycopg2 v2.9.6 w/ Python 3.10.4
  easybuild/easyconfigs/p/psycopg2/psycopg2-2.9.6-GCCcore-11.3.0.eb
Labels: update

#18036 {bio}[system/system] FreeSurfer v7.4.0
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.0-centos8_x86_64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.0-ubuntu20_amd64.eb
  easybuild/easyconfigs/f/FreeSurfer/FreeSurfer-7.4.0-ubuntu22_amd64.eb
Labels: update

#18003 {lib}[GCCcore/11.3.0] jxrlib v1.1, imagecodecs v2022.9.26, LERC v4.0.0, LibLZF v3.6, libavif v0.11.1, zfp v1.0.0 w/ Python 3.10.4
  easybuild/easyconfigs/i/imagecodecs/imagecodecs-2022.9.26-foss-2022a.eb
  easybuild/easyconfigs/j/jxrlib/jxrlib-1.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LibLZF/LibLZF-3.6-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libavif/libavif-0.11.1-foss-2022a.eb
  easybuild/easyconfigs/z/zfp/zfp-1.0.0-GCCcore-11.3.0.eb
Labels: update

#18044 {math}[foss/2022a] pyMannKendall v1.4.3 w/ Python 3.10.4
  easybuild/easyconfigs/p/pyMannKendall/pyMannKendall-1.4.3-foss-2022a.eb
Labels: new

#18043 {math}[foss/2022a] mannkendall v1.1.1 w/ Python 3.10.4
  easybuild/easyconfigs/m/mannkendall/mannkendall-1.1.1-foss-2022a.eb
Labels: new

#18032 {bio}[GCCcore/10.3.0] subset-bam v1.1.0
  easybuild/easyconfigs/s/subset-bam/subset-bam-1.1.0-GCCcore-10.3.0.eb
Labels: new

#18045 {lib}[foss/2022a] pypmt v1.1.0 w/ Python 3.10.4
  easybuild/easyconfigs/p/pypmt/pypmt-1.1.0-foss-2022a.eb
Labels: new

#18052 {lib}[GCCcore/11.3.0] pmt v1.1.0
  easybuild/easyconfigs/p/pmt/pmt-1.1.0-GCCcore-11.3.0.eb
Labels: new

#18041 {chem}[foss/2022a] Cantera v2.6.0 w/ Python 3.10.4
  easybuild/easyconfigs/c/Cantera/Cantera-2.6.0-foss-2022a.eb
Labels: bug fix

#17000 {tools}[GCCcore/11.3.0] ccache v4.6.3
  easybuild/easyconfigs/c/ccache/ccache-4.6.3-GCCcore-11.3.0.eb
Labels: update

#18012 {numlib}[GCC/12.3.0] OpenBLAS v0.3.23
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23-GCC-12.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23_fix-lapack-test.patch
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23_fix-parallel-build.patch
Labels: update, 2023a

#18053 {lib}[GCCcore/12.3.0] PMIx v4.2.3, UCC v1.1.0, OpenMPI v4.1.5
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.2.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/u/UCC/UCC-1.1.0-GCCcore-12.3.0.eb
Labels: update, 2023a

#18048 {tools}[foss/2022a] Sniffles v2.0.7 w/ Python 3.10.4
  easybuild/easyconfigs/s/Sniffles/Sniffles-2.0.7-GCC-11.3.0.eb
Labels: new

#18062 Remove unused PyTorch patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1_use-predefined-data-in-test-optim.patch
Labels: change

#18042 {bio}[gfbf/2022b] MAGeCK v0.5.9.5 w/ Python 3.10.8
  easybuild/easyconfigs/m/MAGeCK/MAGeCK-0.5.9.5-gfbf-2022b.eb
Labels: update

#16162 {chem}[foss/2022a] LAMMPS v23Jun2022, ScaFaCoS v1.0.4, Voro++ v0.4.6, kim-api v2.3.0, archspec v0.1.4
  easybuild/easyconfigs/k/kim-api/kim-api-2.3.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2022a-kokkos.eb
  easybuild/easyconfigs/s/ScaFaCoS/ScaFaCoS-1.0.4-foss-2022a.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-11.3.0.eb
Labels: update

#18064 enable building static libs and check for libexslt.* in libxslt
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.37-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libxslt/libxslt-1.1.38-GCCcore-12.3.0.eb
Labels: bug fix

#18056 {lib}[GCC/12.3.0] FlexiBLAS v3.3.1
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.3.1-GCC-12.3.0.eb
Labels: update, 2023a

#18051 {tools}[foss/2022a,intel/2022a] affinity v20230524
  easybuild/easyconfigs/a/affinity/affinity-20230524-foss-2022a.eb
  easybuild/easyconfigs/a/affinity/affinity-20230524-intel-2022a.eb
Labels: new

#18066 {numlib,toolchain,tools}[foss/2023.05,gompi/2023.05,system/system] ScaLAPACK v2.2.0, foss v2023.05, HPL v2.3
  easybuild/easyconfigs/f/foss/foss-2023.05.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2023.05.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gompi-2023.05-fb.eb
Labels: update, 2023a

#18072 add -pthread flag for dorado
  easybuild/easyconfigs/d/dorado/dorado-0.1.1-foss-2022a-CUDA-11.7.0.eb
Labels: bug fix

#18013 {lib}[foss/2021a] dm-haiku v0.0.9 w/ Python 3.9.5
  easybuild/easyconfigs/d/dm-haiku/dm-haiku-0.0.9-foss-2021a-CUDA-11.3.1.eb
Labels: new

#18055 {astro}[system/system] CASA v6.5.5-21
  easybuild/easyconfigs/c/CASA/CASA-6.5.5-21-py3.8.eb
Labels: new

#18069 {lang}[GCC/11.3.0] LuaJIT v2.1.0-beta3_20230602
  easybuild/easyconfigs/l/LuaJIT/LuaJIT-2.1.0-beta3_20230602-GCC-11.3.0.eb
Labels: update

#18073 {lib}[GCCcore/11.3.0] LuaRocks v3.9.2
  easybuild/easyconfigs/l/LuaRocks/LuaRocks-3.9.2-GCCcore-11.3.0.eb
Labels: new

#18077 {bio}[foss/2022a] cuteSV v2.0.3 w/ Python 3.10.4
  easybuild/easyconfigs/c/cuteSV/cuteSV-2.0.3-foss-2022a.eb
  easybuild/easyconfigs/c/cuteSV/cuteSV-2.0.3_dep-fix.patch
Labels: new

#18074 {lib}[system/system] cuTENSOR v1.7.0.1
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-1.7.0.1-CUDA-12.0.0.eb
Labels: update

#17977 {lang}[system/system] Julia v1.9.0
  easybuild/easyconfigs/j/Julia/Julia-1.9.0-linux-x86_64.eb
Labels: update

#18005 {bio}[gompi/2021a] BGC-Bayesian-genomic-clines v1.03
  easybuild/easyconfigs/b/BGC-Bayesian-genomic-clines/BGC-Bayesian-genomic-clines-1.03-gompi-2021a.eb
  easybuild/easyconfigs/b/BGC-Bayesian-genomic-clines/BGC-Bayesian-genomic-clines-1.03_Makefile.patch
Labels: new

#18085 {bio}[foss/2022a] pySCENIC v0.12.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/pySCENIC/pySCENIC-0.12.1-foss-2022a.eb
Labels: update

#18071 {bio}[GCC/11.3.0] SVIM v2.0.0, pyspoa v0.0.9, spoa v4.0.7 w/ Python 3.10.4
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.9-GCC-11.3.0.eb
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.9_use-spoa-dep.patch
  easybuild/easyconfigs/s/SVIM/SVIM-2.0.0-foss-2022a.eb
  easybuild/easyconfigs/s/spoa/spoa-4.0.7-GCC-11.3.0.eb
Labels: new, update

#18087 add missing patch files for Qt5 5.15.2 to fix build problems with glibc 2.34
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.2-GCCcore-10.3.0.eb
Labels: bug fix

#17283 {vis}[foss/2021b] stardist v0.8.3, PyOpenCL v2021.2.13 w/ Python 3.9.6
  easybuild/easyconfigs/p/PyOpenCL/PyOpenCL-2021.2.13-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/s/stardist/stardist-0.8.3-foss-2021b-CUDA-11.4.1.eb
Labels: update

#18092 {system}[system/system] CUDA v12.1.1
  easybuild/easyconfigs/c/CUDA/CUDA-12.1.1.eb
Labels: update, 2023a

#18115 {bio}[GCCcore/12.2.0,foss/2022b] MUMmer v4.0.0rc1, MultiQC v1.14 w/ Python 3.10.8
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0rc1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.14-foss-2022b.eb
Labels: update

#18096 {bio}[GCC/12.2.0] BBMap v39.01
  easybuild/easyconfigs/b/BBMap/BBMap-39.01-GCC-12.2.0.eb
Labels: update

#18112 {bio}[GCC/12.2.0] GenomeTools v1.6.2
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.6.2-GCC-12.2.0.eb
Labels: update

#18095 {lib}[GCCcore/12.3.0] GDRCopy v2.3.1
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.3.1-GCCcore-12.3.0.eb
Labels: update, 2023a

#18091 {lib}[GCCcore/12.3.0] UCC v1.2.0
  easybuild/easyconfigs/u/UCC/UCC-1.2.0-GCCcore-12.3.0.eb
Labels: update, 2023a

#18103 {tools}[GCCcore/12.2.0] Emacs v28.2
  easybuild/easyconfigs/e/Emacs/Emacs-28.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-12.2.0.eb
Labels: update

#18094 {bio,math,numlib}[foss/2022b] AUGUSTUS v3.5.0, lpsolve v5.5.2.11, SuiteSparse v5.13.0
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.5.0-foss-2022b.eb
  easybuild/easyconfigs/l/lpsolve/lpsolve-5.5.2.11-GCC-12.2.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.13.0-foss-2022b-METIS-5.1.0.eb
Labels: update

#18128 {chem}[foss/2022a] DIRAC v23.0
  easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-foss-2022a.eb
Labels: update

#18129 {chem}[intel/2022a] DIRAC v23.0
  easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-intel-2022a.eb
Labels: update

#18122 add FKSUM + haldensify extensions to R 4.2.2
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#18110 {bio}[GCCcore/12.2.0] GATK v4.4.0.0 w/ Python 3.10.8
  easybuild/easyconfigs/g/GATK/GATK-4.4.0.0-GCCcore-12.2.0-Java-17.eb
Labels: update

#18106 {bio}[GCC/12.2.0] Exonerate v2.4.0
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-12.2.0.eb
Labels: update

#18102 {bio}[GCC/12.2.0] CD-HIT v4.8.1
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-GCC-12.2.0.eb
Labels: update

#18093 {bio}[GCCcore/12.2.0] AGAT v1.1.0, BioPerl v1.7.8, XML-LibXML v2.0208
  easybuild/easyconfigs/a/AGAT/AGAT-1.1.0-GCC-12.2.0.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-12.2.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0208-GCCcore-12.2.0.eb
Labels: update

#18121 {bio}[foss/2022b] tidymodels v1.1.0 w/ R 4.2.2
  easybuild/easyconfigs/t/tidymodels/tidymodels-1.1.0-foss-2022b.eb
Labels: update

#18124 {bio}[foss/2022a] Trinotate v4.0.1, PyBioLib v1.1.988, MMseqs2 v14-7e284, Transdecoder v5.5.0 ... w/ Python 3.10.4
  easybuild/easyconfigs/e/eggnog-mapper/eggnog-mapper-2.1.9-foss-2022a.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-foss-2022a.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-14-7e284-gompi-2022a.eb
  easybuild/easyconfigs/p/PyBioLib/PyBioLib-1.1.988-GCCcore-11.3.0.eb
  easybuild/easyconfigs/t/TransDecoder/TransDecoder-5.5.0-GCC-11.3.0.eb
  easybuild/easyconfigs/t/Trinotate/Trinotate-4.0.1-foss-2022a.eb
Labels: new, update

#18099 {bio,lib}[GCCcore/12.2.0,gompi/2022b] BLAST+ v2.14.0, LMDB v0.9.29
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.0-gompi-2022b.eb
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.29-GCCcore-12.2.0.eb
Labels: update

#18118 {bio}[GCCcore/12.2.0] canu v2.2, cutadapt v4.4, python-isal v1.1.0, ... w/ Python 3.10.8
  easybuild/easyconfigs/c/canu/canu-2.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-4.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/fastp/fastp-0.23.4-GCC-12.2.0.eb
  easybuild/easyconfigs/g/gffread/gffread-0.12.7-GCCcore-12.2.0.eb
  easybuild/easyconfigs/i/ISA-L/ISA-L-2.30.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pigz/pigz-2.7-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/python-isal/python-isal-1.1.0-GCCcore-12.2.0.eb
Labels: update

#18133 {bio}[GCC/12.2.0] seqtk v1.4
  easybuild/easyconfigs/s/seqtk/seqtk-1.4-GCC-12.2.0.eb
Labels: update

#18126 {lib}[GCCcore/12.3.0] UCX-CUDA v1.14.1, NCCL v2.18.3, UCC-CUDA v1.2.0
  easybuild/easyconfigs/n/NCCL/NCCL-2.18.3-GCCcore-12.3.0-CUDA-12.1.1.eb
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.2.0-GCCcore-12.3.0-CUDA-12.1.1.eb
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.2.0_link_against_existing_UCC_libs.patch
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.14.1-GCCcore-12.3.0-CUDA-12.1.1.eb
Labels: update, 2023a

#18127 Use UCC 1.2.0 in 2023a toolchain
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.3.0.eb
Labels: change, 2023a

#18135 {numlib}[system/system] cuDNN v8.9.2.26
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.9.2.26-CUDA-12.1.1.eb
Labels: update

#18144 Use PMIx 4.2.4 in 2023a toolchain
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.3.0.eb
  easybuild/easyconfigs/p/PMIx/PMIx-4.2.4-GCCcore-12.3.0.eb
Labels: update, 2023a

#17989 {bio}[gompi/2021a] DaliLite v4.1
  easybuild/easyconfigs/d/DaliLite/DaliLite-4.1-gompi-2021a.eb
  easybuild/easyconfigs/d/DaliLite/DaliLite-4.1_fix-labels-without-statements.patch
Labels: new

#18145 remove old UCC (1.1.0) from GCCcore 12.3.0
  easybuild/easyconfigs/u/UCC/UCC-1.1.0-GCCcore-12.3.0.eb
Labels: change

#18139 {tools}[foss/2022a] torchaudio v0.12.0 w/ Python 3.10.4
  easybuild/easyconfigs/t/torchaudio/torchaudio-0.12.0-foss-2022a-PyTorch-1.12.0-CUDA-11.7.0.eb
  easybuild/easyconfigs/t/torchaudio/torchaudio-0.12.0-foss-2022a-PyTorch-1.12.0.eb
Labels: update

#18004 {vis}[foss/2022a] Cellpose v2.2.2 w/ Python 3.10.4
  easybuild/easyconfigs/c/Cellpose/Cellpose-2.2.2-foss-2022a.eb
Labels: new, update

#16720 {lib}[system/system] Circuitscape v5.12.3
  easybuild/easyconfigs/c/Circuitscape/Circuitscape-5.12.3-Julia-1.7.2.eb
Labels: new

#18152 {bio}[foss/2022a] Cellpose v2.2.2 w/ Python 3.10.4 + CUDA 11.7.0
  easybuild/easyconfigs/c/Cellpose/Cellpose-2.2.2-foss-2022a-CUDA-11.7.0.eb
Labels: update

#18150 {tools}[GCCcore/11.3.0] gengetopt v2.23
  easybuild/easyconfigs/g/gengetopt/gengetopt-2.23-GCCcore-11.3.0.eb
Labels: update

#18153 {bio}[GCC/12.2.0] GLIMPSE v2.0.0
  easybuild/easyconfigs/g/GLIMPSE/GLIMPSE-2.0.0-GCC-12.2.0.eb
Labels: update

#18149 {bio}[gfbf/2022a] GCTA v1.94.1
  easybuild/easyconfigs/g/GCTA/GCTA-1.94.1-gfbf-2022a.eb
Labels: update

#18142 {lib}[foss/2022a] pygmo v2.18.0, pagmo v2.18.0 w/ Python 3.10.4
  easybuild/easyconfigs/p/pagmo/pagmo-2.18.0-foss-2022a.eb
  easybuild/easyconfigs/p/pygmo/pygmo-2.18.0-foss-2022a.eb
Labels: update

#18140 {bio}[GCC/12.2.0] edlib v1.3.9, pyspoa v0.0.9, spoa v4.0.7 w/ Python 3.10.8
  easybuild/easyconfigs/e/edlib/edlib-1.3.9-GCC-12.2.0.eb
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.0.9-GCC-12.2.0.eb
  easybuild/easyconfigs/s/spoa/spoa-4.0.7-GCC-12.2.0.eb
Labels: update

#18146 {math}[GCCcore/11.3.0] Gurobi v10.0.1 w/ Python 3.10.4
  easybuild/easyconfigs/g/Gurobi/Gurobi-10.0.1-GCCcore-11.3.0.eb
Labels: update

#18138 {bio}[GCCcore/12.2.0] pyfaidx v0.7.2.1 w/ Python 3.10.8
  easybuild/easyconfigs/p/pyfaidx/pyfaidx-0.7.2.1-GCCcore-12.2.0.eb
Labels: update

#18137 {bio}[GCC/12.2.0] Pysam v0.21.0 w/ Python 3.10.8
  easybuild/easyconfigs/p/Pysam/Pysam-0.21.0-GCC-12.2.0.eb
Labels: update

#18136 plinkliftover
  easybuild/easyconfigs/p/plinkliftover/plinkliftover-0.3.0-foss-2022b.eb
Labels: new

#18155 {bio}[foss/2022a] dorado v0.3.0 w/ CUDA 11.7.0
  easybuild/easyconfigs/d/dorado/dorado-0.3.0-foss-2022a-CUDA-11.7.0.eb
Labels: update

#18108 {bio}[GCCcore/12.2.0] FLASH v2.2.00
  easybuild/easyconfigs/f/FLASH/FLASH-2.2.00-GCCcore-12.2.0.eb
Labels: update

#18083 {bio}[foss/2022a] CmdStanR v0.5.2
  easybuild/easyconfigs/c/CmdStanR/CmdStanR-0.5.2-foss-2022a-R-4.2.1.eb
Labels: update

#18007 add pkgconfig as build dependency for nodejs , required for finding ICU dependency
  easybuild/easyconfigs/n/nodejs/nodejs-18.12.1-GCCcore-12.2.0.eb
Labels: bug fix

#18098 allow multiply dependency variants of ncbi-vdb for SRA-Toolkit per easyconfigs generation, as long as versions match
  test/easyconfigs/easyconfigs.py
Labels: change, tests

#18065 {bio}[gompi/2021a] SRA-Toolkit v3.0.5, ncbi-vdb v3.0.5
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.0.5-gompi-2021a.eb
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-3.0.5-gompi-2021a.eb
Labels: update

#9678 {tools}[GCCcore/8.3.0] AutoDock v4.2.6, AutoGrid v4.2.6
  easybuild/easyconfigs/a/AutoDockSuite/AutoDockSuite-4.2.6-GCCcore-8.3.0.eb
Labels: update

#9482 {bio}[fosscuda/2019b] CuCLARK v1.1
  easybuild/easyconfigs/c/CuCLARK/CuCLARK-1.1-fosscuda-2019b.eb
  easybuild/easyconfigs/c/CuCLARK/CuCLARK-1.1_fix-shfl.patch
Labels: new

#18148 Added config for Nextflow 23.04.2
  easybuild/easyconfigs/n/Nextflow/Nextflow-23.04.2.eb
Labels: update

#16798 {bio,vis}[foss/2019b] MOB-suite v3.1.0, ETE v3.1.2 w/ Python 3.7.4
  easybuild/easyconfigs/e/ETE/ETE-3.1.2-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/MOB-suite/MOB-suite-3.1.0-foss-2019b-Python-3.7.4.eb
Labels: new, update

#18131 {bio}[foss/2022b] parasail v2.6.2, python-parasail v1.3.4, qcat v1.1.0 w/ Python 3.10.8
  easybuild/easyconfigs/p/parasail/parasail-2.6.2-GCC-12.2.0.eb
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.3.4-foss-2022b.eb
  easybuild/easyconfigs/q/qcat/qcat-1.1.0-foss-2022b.eb
Labels: update

#18163 {bio}[GCC/10.3.0] GLIMPSE v2.0.0
  easybuild/easyconfigs/g/GLIMPSE/GLIMPSE-2.0.0-GCC-10.3.0.eb
Labels: update

#9620 {bio}[fosscuda/2019b] OpenMM v7.4.1 w/ Python 3.7.4
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.4.1-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#9800 Add CPU/GPU builds for GROMACS/2019.4 with PLUMED/2.5.4
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-foss-2019b-PLUMED-2.5.4.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-fosscuda-2019b-PLUMED-2.5.4.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2019.4-fosscuda-2019b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.4-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.4-fosscuda-2019b-Python-3.7.4.eb
Labels: update

#18154 {bio}[foss/2022a] duplex-tools v0.3.3 w/ Python 3.10.4
  easybuild/easyconfigs/d/duplex-tools/duplex-tools-0.3.3-foss-2022a.eb
Labels: update

#18156 {bio}[GCC-12.2.0] easel 0.48
  easybuild/easyconfigs/e/easel/easel-0.48-GCC-12.2.0.eb
Labels: new

#18107 {bio}[foss/2022b] FASTA v36.3.8i
  easybuild/easyconfigs/f/FASTA/FASTA-36.3.8i-GCC-12.2.0.eb
Labels: update

#18159 add missing pkgconf build dependency for XML-LibXML v2.0208
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0208-GCCcore-12.2.0.eb
Labels: bug fix

#10973 {numlib}[GCCcore/9.3.0] Triangle v1.6 {REVIEW}
  easybuild/easyconfigs/t/Triangle/Triangle-1.6-GCCcore-9.3.0.eb
Labels: update

#15336 {bio}[foss/2021a] pastml v1.9.34 w/ Python 3.9.5
  easybuild/easyconfigs/p/pastml/pastml-1.9.34-foss-2021a.eb
Labels: new

#12888 {bio}[foss/2020a] SortMeRNA v2.1
  easybuild/easyconfigs/s/SortMeRNA/SortMeRNA-2.1-GCC-9.3.0.eb
Labels: update

#18016 {lang}[GCCcore/12.3.0] Rust v1.70.0
  easybuild/easyconfigs/r/Rust/Rust-1.70.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.70_sysroot-fix-interpreter.patch
Labels: update, 2023a

#17923 {bio}[GCC/11.3.0,foss/2022a] alleleCount v4.2.1, ASCAT v3.1.2, alleleIntegrator v0.8.8
  easybuild/easyconfigs/a/ASCAT/ASCAT-3.1.2-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/a/alleleCount/alleleCount-4.2.1-GCC-11.3.0.eb
  easybuild/easyconfigs/a/alleleIntegrator/alleleIntegrator-0.8.8-foss-2022a-R-4.2.1.eb
Labels: new, update

#18161 {bio}[system/system] FragPipe v20.0
  easybuild/easyconfigs/f/FragPipe/FragPipe-20.0-Java-11.eb
Labels: new

#17825 {bio}[GCCcore/10.2.0] cutadapt v2.10 w/ Python 3.8.6
  easybuild/easyconfigs/c/cutadapt/cutadapt-2.10-GCCcore-10.2.0.eb
Labels: update

#11245 {chem}[intel/2020a] QuantumESPRESSO v6.6
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-intel-2020a.eb
Labels: update

#15414 {lib}[GCC/10.2.0] popt v1.16
  easybuild/easyconfigs/p/popt/popt-1.16-GCC-10.2.0.eb
Labels: update

#15720 {bio}[foss/2020b] EIGENSOFT v7.2.1
  easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-7.2.1-foss-2020b.eb
Labels: update

#15711 {lib}[GCCcore/10.2.0] graphite2 v1.3.14
  easybuild/easyconfigs/g/graphite2/graphite2-1.3.14-GCCcore-10.2.0.eb
Labels: update

#15718 {bio}[system/system] BayesTraits v3.0.2
  easybuild/easyconfigs/b/BayesTraits/BayesTraits-3.0.2-Linux.eb
Labels: update

#17663 {data}[iompi/2020a] netCDF v4.7.4
  easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-iompi-2020a.eb
Labels: update

#18160 {bio}[system/system] MaxQuant v2.4.2.0
  easybuild/easyconfigs/m/MaxQuant/MaxQuant-2.4.2.0.eb
Labels: update

#17092 {lib}[foss/2022a] TensorFlow v2.9.1 w/ Python 3.10.4
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4_fix-PPC-JIT.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1-foss-2022a.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1_fix-PPC-Eigen-build.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1_fix-check-for-MKL.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1_remove-libclang-and-io-gcs-deps.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1_support_flatbuffers_2.0.6.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1_support_flatbuffers_2.0.patch
Labels: update

#17997 {bio}[foss/2022a,foss/2022b] GEM v1.5.1
  easybuild/easyconfigs/g/GEM/GEM-1.5.1-foss-2022a.eb
  easybuild/easyconfigs/g/GEM/GEM-1.5.1-foss-2022b.eb
  easybuild/easyconfigs/g/GEM/GEM-1.5.1-makefile-thirdparty.patch
Labels: new

#18084 {bio}[foss-2022b] SVclone 1.1.2 w/Python/3.10.8
  easybuild/easyconfigs/s/SVclone/SVclone-1.1.2-foss-2022b.eb
Labels: new

#11243 {tools}[intel/2020a] pyiron v0.3.0 w/ Python 3.8.2
  easybuild/easyconfigs/p/pyiron/pyiron-0.3.0-intel-2020a-Python-3.8.2.eb
Labels: update

#18169 {tools}[GCCcore/12.3.0] patchelf v0.18.0
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0-GCCcore-12.3.0.eb
Labels: update, 2023a

#17982 update JupyterLab v3.5.0 to set JUPYTERLAB_SETTINGS_DIR and JUPYTERLAB_WORKSPACES_DIR on module load
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.5.0-GCCcore-11.3.0.eb
Labels: enhancement

#18111 {bio,lang}[GCCcore/12.2.0,foss/2022b] Ruby v3.0.5, GEMMA v0.98.5
  easybuild/easyconfigs/g/GEMMA/GEMMA-0.98.5-foss-2022b.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.2.2-GCCcore-12.2.0.eb
Labels: update

#18170 {bio}[foss/2021b] GRIDSS v2.13.2
  easybuild/easyconfigs/g/GRIDSS/GRIDSS-2.13.2-foss-2021b-Java-11.eb
Labels: new

#15724 {tools}[GCCcore/10.2.0] jq v1.5
  easybuild/easyconfigs/j/jq/jq-1.5-GCCcore-10.2.0.eb
Labels: update

#15725 {bio}[GCC/10.2.0] libSBML v5.19.0
  easybuild/easyconfigs/l/libSBML/libSBML-5.19.0-GCC-10.2.0.eb
Labels: update

#10378 {cae}[system] FLUENT v2019R3
  easybuild/easyconfigs/f/FLUENT/FLUENT-2019R3.eb
Labels: update

#18067 {chem,lib}[GCCcore/11.2.0,foss/2021b] PSI4 v1.7, psutil v5.9.4 w/ Python 3.9.6
  easybuild/easyconfigs/p/PSI4/PSI4-1.7-foss-2021b.eb
  easybuild/easyconfigs/p/PSI4/PSI4-1.7_fix_cmake_release.patch
  easybuild/easyconfigs/p/PSI4/PSI4-1.7_fix_snsmp2_version.patch
  easybuild/easyconfigs/p/psutil/psutil-5.9.4-GCCcore-11.2.0.eb
Labels: update

#15726 {math}[GCCcore/10.2.0] Mesquite v2.3.0
  easybuild/easyconfigs/m/Mesquite/Mesquite-2.3.0-GCCcore-10.2.0.eb
Labels: update

#16117 {chem}[foss/2022a] NAMD v2.14
  easybuild/easyconfigs/n/NAMD/NAMD-2.14-foss-2022a-mpi.eb
  easybuild/easyconfigs/n/NAMD/NAMD-2.14_fix-LJCorrection.patch
  easybuild/easyconfigs/n/NAMD/NAMD-2.14_fix-constant-pH.patch
Labels: update

#12470 {bio}[iccifort/2020.4.304] segemehl v0.3.4
  easybuild/easyconfigs/s/segemehl/segemehl-0.3.4-iccifort-2020.4.304.eb
Labels: update

#15728 {perf}[foss/2020b] MUST v1.7.1 w/ Python 3.8.6
  easybuild/easyconfigs/m/MUST/MUST-1.7.1-foss-2020b.eb
Labels: update

#18101 {bio}[GCCcore/12.2.0,foss/2022b] HMMER v3.3.2, BUSCO v5.4.7, prodigal v2.6.3, ... w/ Python 3.10.8
  easybuild/easyconfigs/b/BUSCO/BUSCO-5.4.7-foss-2022b.eb
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.5.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MetaEuk/MetaEuk-6-GCC-12.2.0.eb
  easybuild/easyconfigs/p/prodigal/prodigal-2.6.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/SEPP/SEPP-4.5.1-foss-2022b.eb
Labels: update

#18125 {tools}[foss/2022a,intel/2022a] wrapt v1.15.0 w/ Python 3.10.4
  easybuild/easyconfigs/w/wrapt/wrapt-1.15.0-foss-2022a.eb
  easybuild/easyconfigs/w/wrapt/wrapt-1.15.0-intel-2022a.eb
Labels: new
