Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2023-04, with the labels that each got.

#17636 {tools}[GCCcore/12.2.0] nano v7.2
  easybuild/easyconfigs/n/nano/nano-7.2-GCCcore-12.2.0.eb
Labels: update

#17637 {tools}[GCCcore/12.2.0] fio v3.34
  easybuild/easyconfigs/f/fio/fio-3.34-GCCcore-12.2.0.eb
Labels: update

#17635 {bio}[gompi/2022a] LoRDEC v0.9, GATB-Core v1.4.2
  easybuild/easyconfigs/g/GATB-Core/GATB-Core-1.4.2-gompi-2022a.eb
  easybuild/easyconfigs/g/GATB-Core/GATB-Core-1.4.2_no-thirdparty-boost-hdf5.patch
  easybuild/easyconfigs/l/LoRDEC/LoRDEC-0.9-gompi-2022a.eb
  easybuild/easyconfigs/l/LoRDEC/LoRDEC-0.9_GATB.patch
  easybuild/easyconfigs/l/LoRDEC/LoRDEC-0.9_GraphVector.patch
Labels: new

#16983 {system}[GCCcore/11.3.0] libgcrypt v1.10.1
  easybuild/easyconfigs/l/libgcrypt/libgcrypt-1.10.1-GCCcore-11.3.0.eb
Labels: update

#17477 {bio}[system/system] ont-guppy v6.4.6
  easybuild/easyconfigs/o/ont-guppy/ont-guppy-6.4.6-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/ont-guppy/ont-guppy-6.4.6.eb
Labels: new

#17640 add dlm extension to R 4.2.1 + 4.2.2
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#17285 {numlib}[intel/2021a] Hypre v2.21.0, MUMPS v5.4.0, PETSc v3.15.1, ... w/ Python 3.9.5
  easybuild/easyconfigs/h/Hypre/Hypre-2.21.0-intel-2021a.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-intel-2021a-metis.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.15.1-intel-2021a.eb
  easybuild/easyconfigs/p/PETSc/PETSc_remove-mpiicc-show-quotes.patch
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.10.1-intel-2021a-METIS-5.1.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse_disable-qopt-report.patch
Labels: update

#17646 {bio}[foss/2022a] CopyKAT v1.1.0
  easybuild/easyconfigs/c/CopyKAT/CopyKAT-1.1.0-foss-2022a-R-4.2.1.eb
Labels: new

#17642 {math}[foss/2021b] R-transport v0.13-0
  easybuild/easyconfigs/r/R-transport/R-transport-0.13-0-foss-2021b.eb
Labels: new

#17644 {tools}[GCCcore/12.2.0] Vim v9.0.1434 w/ Python 3.10.8
  easybuild/easyconfigs/v/Vim/Vim-9.0.1434-GCCcore-12.2.0.eb
Labels: update

#17647 {math}[foss/2022a] powerlaw v1.5 w/ Python 3.10.4
  easybuild/easyconfigs/p/powerlaw/powerlaw-1.5-foss-2022a.eb
Labels: new

#17641 remove LLVM build dependency from TensorFlow easyconfigs
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4-foss-2021b.eb
Labels: code cleanup

#17638 disable mpi/python in Boost (intel-compilers/2021.4.0)
  easybuild/easyconfigs/b/Boost/Boost-1.77.0-intel-compilers-2021.4.0.eb
Labels: bug fix

#17648 {data}[foss/2021a] scib v1.1.3, Deprecated v1.2.13 w/ Python 3.9.5
  easybuild/easyconfigs/d/Deprecated/Deprecated-1.2.13-foss-2021a.eb
  easybuild/easyconfigs/s/scib/scib-1.1.3-foss-2021a.eb
Labels: update

#17584 {math}[foss/2022a] Bottleneck v1.3.7 w/ Python 3.10.4
  easybuild/easyconfigs/b/Bottleneck/Bottleneck-1.3.7-foss-2022a.eb
Labels: update

#17649 {vis}[system/system] Blender v3.5.0
  easybuild/easyconfigs/b/Blender/Blender-3.5.0-linux-x86_64-CUDA-11.7.0.eb
Labels: update

#17574 {math}[GCCcore/11.2.0] CPLEX v22.1.1 w/ Python 3.9.6
  easybuild/easyconfigs/c/CPLEX/CPLEX-22.1.1-GCCcore-11.2.0.eb
Labels: update

#17659 {lib}[GCCcore/10.2.0] c-ares v1.17.2
  easybuild/easyconfigs/c/c-ares/c-ares-1.17.2-GCCcore-10.2.0.eb
Labels: update

#17660 {tools}[GCCcore/10.2.0] CppUnit v1.15.1
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-10.2.0.eb
Labels: update

#17654 {compiler}[system/system] NAGfor v7.1
  easybuild/easyconfigs/n/NAGfor/NAGfor-7.1.eb
Labels: update

#17656 {lib}[GCCcore/10.2.0] argtable v2.13
  easybuild/easyconfigs/a/argtable/argtable-2.13-GCCcore-10.2.0.eb
Labels: update

#17661 {data}[foss/2022b] geopandas v0.12.2, pyproj v3.5.0, Fiona v1.9.2 w/ Python 3.10.8
  easybuild/easyconfigs/f/Fiona/Fiona-1.9.2-foss-2022b.eb
  easybuild/easyconfigs/g/geopandas/geopandas-0.12.2-foss-2022b.eb
  easybuild/easyconfigs/p/pyproj/pyproj-3.5.0-GCCcore-12.2.0.eb
Labels: update

#17655 {compiler}[gompi/2022b] NAG v7.1
  easybuild/easyconfigs/n/NAG/NAG-7.1-gompi-2022b.eb
Labels: update

#17643 {lib}[GCCcore/12.2.0] PostgreSQL v15.2, libaio v0.3.113, LZO v2.10, ...
  easybuild/easyconfigs/j/Judy/Judy-1.0.5-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libaio/libaio-0.3.113-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MariaDB/MariaDB-10.11.2-GCC-12.2.0.eb
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-15.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/sysbench/sysbench-1.0.20-GCC-12.2.0.eb
Labels: new, update

#17657 {bio}[GCC/10.2.0] Clustal-Omega v1.2.4
  easybuild/easyconfigs/c/Clustal-Omega/Clustal-Omega-1.2.4-GCC-10.2.0.eb
Labels: update

#17667 {math}[foss/2021b] R-MXM v1.5.5
  easybuild/easyconfigs/r/R-MXM/R-MXM-1.5.5-foss-2021b.eb
Labels: new

#16347 {tools}[GCCcore/10.3.0] jupyter-resource-usage v0.6.2 w/ Python 3.9.5
  easybuild/easyconfigs/j/jupyter-resource-usage/jupyter-resource-usage-0.6.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/j/jupyter-resource-usage/jupyter-resource-usage-0.6.2_fix_update_cpu.patch
Labels: update

#17553 {phys}[foss/2022b] TOPAS v3.9, CLHEP v2.4.6.4, GDCM v3.0.21
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.6.4-GCC-12.2.0.eb
  easybuild/easyconfigs/g/GDCM/GDCM-3.0.21-GCCcore-12.2.0.eb
  easybuild/easyconfigs/t/TOPAS/TOPAS-3.9-foss-2022b.eb
Labels: new, update

#17652 {bio}[foss/2022a] FunGAP v1.1.1 w/ Python 3.10.4
  easybuild/easyconfigs/f/FunGAP/FunGAP-1.1.1-foss-2022a.eb
  easybuild/easyconfigs/f/FunGAP/FunGAP-1.1.1_fix-augustus-calls-in-runbreaker.patch
  easybuild/easyconfigs/f/FunGAP/FunGAP-1.1.1_fix-maker-exes.patch
  easybuild/easyconfigs/f/FunGAP/FunGAP-1.1.1_fix-snap-detection.patch
  easybuild/easyconfigs/f/FunGAP/FunGAP-1.1.1_relax-dependency-checks.patch
  easybuild/easyconfigs/f/FunGAP/FunGAP-1.1.1_replace-deprecated-pa-repeatmodeler.patch
Labels: new

#17569 {bio}[foss/2022b] KrakenUniq-1.0.3-GCC-11.3.0.eb
  easybuild/easyconfigs/k/KrakenUniq/KrakenUniq-1.0.3-GCC-11.3.0.eb
Labels: new

#17609 {tools}[system/system] zsh v5.9
  easybuild/easyconfigs/z/zsh/zsh-5.9.eb
Labels: update

#17625 {numlib}[intel/2021b] SuiteSparse v5.8.1, PETSc v3.18.4, SLEPc v3.18.2 w/ Python 3.9.6
  easybuild/easyconfigs/p/PETSc/PETSc-3.18.4-intel-2021b.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.18.2-intel-2021b.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.10.1-intel-2021b-METIS-5.1.0.eb
Labels: update

#17669 {bio}[foss/2022a] Seurat v4.3.0
  easybuild/easyconfigs/s/Seurat/Seurat-4.3.0-foss-2022a-R-4.2.1.eb
Labels: update

#17671 Bump version to 5.0.0.dev0
  setup.py
Labels: EasyBuild-5.0

#17670 {bio}[GCC/11.3.0] bwa-meth v0.2.6 w/ Python 3.10.4
  easybuild/easyconfigs/b/bwa-meth/bwa-meth-0.2.6-GCC-11.3.0.eb
Labels: update

#17672 {bio}[foss/2022a] SMAP v4.6.5 w/ Python 3.10.4
  easybuild/easyconfigs/s/SMAP/SMAP-4.6.5-foss-2022a.eb
  easybuild/easyconfigs/s/SMAP/SMAP-4.6.5_no-bin-bedtools.patch
Labels: new

#17255 {lib}[GCCcore/12.2.0] UCC-CUDA v1.1.0 + UCC patch for component paths
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.1.0-GCCcore-12.2.0-CUDA-12.0.0.eb
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.1.0_cuda_12_mem_ops.patch
  easybuild/easyconfigs/u/UCC/UCC-1.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/u/UCC/UCC-1.1.0-multiple_component_paths.patch
Labels: update

#17679 add local::lib extension to Perl 5.34.0
  easybuild/easyconfigs/p/Perl/Perl-5.34.0-GCCcore-11.2.0.eb
Labels: enhancement

#17676 {toolchain} intel/2023.03
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2023.03.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2023.03.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2023.1.0-iimpi-2023.03.eb
  easybuild/easyconfigs/i/imkl/imkl-2023.1.0.eb
  easybuild/easyconfigs/i/impi/impi-2021.9.0-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/i/intel/intel-2023.03.eb
  easybuild/easyconfigs/u/UCX/UCX-1.14.0-GCCcore-12.2.0.eb
Labels: update

#17681 {bio}[GCC/11.2.0] tantan v40
  easybuild/easyconfigs/t/tantan/tantan-40-GCC-11.2.0.eb
Labels: new

#17687 {bio}[GCC/11.2.0] SNAP v2.0.1
  easybuild/easyconfigs/s/SNAP/SNAP-2.0.1-GCC-11.2.0.eb
Labels: update

#17684 {bio}[gompi/2021b] Proteinortho v6.2.3 w/ Python 3.9.6
  easybuild/easyconfigs/p/Proteinortho/Proteinortho-6.2.3-gompi-2021b.eb
Labels: update

#17606 {bio}[foss/2022a] CASPR v20200730 w/ Python 3.10.4
  easybuild/easyconfigs/c/CASPR/CASPR-20200730-foss-2022a.eb
  easybuild/easyconfigs/m/MAGeCK/MAGeCK-0.5.9.4-foss-2022a.eb
  easybuild/easyconfigs/v/vispr/vispr-0.4.14-foss-2022a.eb
  easybuild/easyconfigs/v/vispr/vispr-0.4.14_fix-imports.patch
  easybuild/easyconfigs/v/vispr/vispr-0.4.14_fix-yaml-load.patch
Labels: new, update

#17688 {bio}[GCC/11.2.0] GlimmerHMM v3.0.4c
  easybuild/easyconfigs/g/GlimmerHMM/GlimmerHMM-3.0.4c-GCC-11.2.0.eb
Labels: update

#17601 Added easyconfig for cppzmq
  easybuild/easyconfigs/c/cppzmq/cppzmq-4.9.0.eb
Labels: new

#17153 {ai}[foss/2021b] PyTorch v1.12.1 w/ Python 3.9.6
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b.eb
Labels: update

#17682 {bio}[foss/2021b] CodingQuarry v2.0
  easybuild/easyconfigs/c/CodingQuarry/CodingQuarry-2.0-foss-2021b.eb
  easybuild/easyconfigs/c/CodingQuarry/CodingQuarry-2.0_python3.patch
Labels: new

#17680 {bio}[GCC/11.2.0] tRNAscan-SE v2.0.12
  easybuild/easyconfigs/t/tRNAscan-SE/tRNAscan-SE-2.0.12-GCC-11.2.0.eb
Labels: new

#17675 {astro}[foss/2020b,gfbf/2022b,intel/2020b] astropy v4.2.1, astropy v5.2.2 w/ Python 3.10.8 + 3.8.6
  easybuild/easyconfigs/a/astropy/astropy-4.2.1-foss-2020b.eb
  easybuild/easyconfigs/a/astropy/astropy-4.2.1-intel-2020b.eb
  easybuild/easyconfigs/a/astropy/astropy-5.2.2-gfbf-2022b.eb
Labels: update

#17397 {vis}[foss/2022a] pp-sketchlib v2.1.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/pp-sketchlib/pp-sketchlib-2.1.1-foss-2022a.eb
Labels: new

#17392 {devel}[GCCcore/11.3.0] libsigc++ v3.4.0
  easybuild/easyconfigs/l/libsigc++/libsigc++-3.4.0-GCCcore-11.3.0.eb
Labels: update

#15497 {geo}[GCC/11.2.0] WCSLIB v7.11
  easybuild/easyconfigs/w/WCSLIB/WCSLIB-7.11-GCC-11.2.0.eb
Labels: new

#17685 {bio}[foss/2021b] SignalP v6.0g w/ Python 3.9.6
  easybuild/easyconfigs/s/SignalP/SignalP-6.0g-foss-2021b-fast.eb
Labels: update

#17695 add PMA/unikn/ppcor extensions to R 4.2.x easyconfigs
  easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#17694 {bio}[GCC/11.3.0] biobambam2 v2.0.87, libmaus2 v2.0.499
  easybuild/easyconfigs/b/biobambam2/biobambam2-2.0.87-GCC-11.3.0.eb
  easybuild/easyconfigs/l/libmaus2/libmaus2-2.0.499-GCC-11.3.0.eb
Labels: update

#17677 {bio}[foss/2022a] sceasy v0.0.7, loompy v3.0.7, anndata v0.8.0 w/ Python 3.10.4
  easybuild/easyconfigs/a/anndata/anndata-0.8.0-foss-2022a.eb
  easybuild/easyconfigs/l/loompy/loompy-3.0.7-foss-2022a.eb
  easybuild/easyconfigs/s/sceasy/sceasy-0.0.7-foss-2022a-R-4.2.1.eb
Labels: new, update

#17697 fix homepage in ELPA easyconfigs (due to switch to new domain)
  easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-foss-2022a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-intel-2022a.eb
Labels: bug fix

#17698 {math}[foss/2022b,intel/2022b] ELPA v2022.05.001
  easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-foss-2022b-CUDA-12.0.0.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-foss-2022b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-intel-2022b.eb
Labels: update

#16472 {tools}[GCCcore/11.2.0] Scalene v1.5.13 w/ Python 3.9.6
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.13-GCCcore-11.2.0.eb
Labels: new

#17700 {tools}[foss/2022a] jax v0.3.25 w/ Python 3.10.4 (+ CUDA 11.7.0)
  easybuild/easyconfigs/j/jax/jax-0.3.25-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/j/jax/jax-0.3.25-foss-2022a.eb
  easybuild/easyconfigs/j/jax/jax-0.3.25_skip-qdwh-test-rank-deficient-deficient.patch
  easybuild/easyconfigs/j/jax/jax-0.3.25_skip-test-bcoo-dot-general-cusparse.patch
Labels: update

#17703 {chem}[foss/2022a] spglib v2.0.2, ShengBTE v1.5.0, thirdorder v1.1.1 w/ Python 3.10.4
  easybuild/easyconfigs/s/ShengBTE/ShengBTE-1.5.0-foss-2022a.eb
  easybuild/easyconfigs/s/spglib/spglib-2.0.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/t/thirdorder/thirdorder-1.1.1-foss-2022a.eb
Labels: new, update

#17706 {chem}[GCC/12.2.0,intel-compilers/2022.2.1] libxc v6.1.0
  easybuild/easyconfigs/l/libxc/libxc-6.1.0-GCC-12.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.1.0-intel-compilers-2022.2.1.eb
Labels: update

#17665 {tools}[system/system] unicore-uftp v1.4.2
  easybuild/easyconfigs/u/unicore-uftp/unicore-uftp-1.4.2-Java-11.eb
Labels: new

#15499 {lib}[foss/2021b] casacore v3.4.0
  easybuild/easyconfigs/c/casacore/casacore-3.4.0-foss-2021b.eb
Labels: new

#17566 {bio}[foss/2022b] R-bundle-Bioconductor v3.16
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
Labels: update

#17604 {bio}[foss/2022a] AlphaFold v2.3.1, HH-suite v3.3.0, Kalign v3.3.5 w/ Python 3.10.4
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.1_use_openmm_7.7.0.patch
  easybuild/easyconfigs/h/HH-suite/HH-suite-3.3.0-gompi-2022a.eb
  easybuild/easyconfigs/k/Kalign/Kalign-3.3.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-8.0.0-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-8.0.0_add_no_tree_vectorize.patch
Labels: update

#17713 add patch for scipy 1.10.1 extension in SciPy-bundle 2023.02 to fix broken test
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.02-gfbf-2022b.eb
  easybuild/easyconfigs/s/SciPy-bundle/scipy-1.10.1_fix-lobpcg-test.patch
Labels: bug fix

#17696 {bio}[foss/2021b] DIALOGUE v1.0-20230228
  easybuild/easyconfigs/d/DIALOGUE/DIALOGUE-1.0-20230228-foss-2021b-R-4.2.0.eb
Labels: new

#17710 {cae}[foss/2022a] PICI-LIGGGHTS v3.8.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/PICI-LIGGGHTS/PICI-LIGGGHTS-3.8.1-foss-2022a.eb
Labels: new

#17720 {bio}[GCC/12.2.0] Structure v2.3.4
  easybuild/easyconfigs/s/Structure/Structure-2.3.4-GCC-12.2.0.eb
Labels: update

#17721 install shared libraries for tesseract
  easybuild/easyconfigs/t/tesseract/tesseract-5.3.0-GCCcore-11.3.0.eb
Labels: bug fix

#17723 {bio}[GCC/11.3.0,gompi/2022a] prokka v1.14.5, Bio-SearchIO-hmmer v1.7.3
  easybuild/easyconfigs/b/Bio-SearchIO-hmmer/Bio-SearchIO-hmmer-1.7.3-GCC-11.3.0.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2022a.eb
Labels: update

#17724 {bio}[GCC/11.3.0] Subread v2.0.4
  easybuild/easyconfigs/s/Subread/Subread-2.0.4-GCC-11.3.0.eb
Labels: update

#17725 {bio}[gompi/2022a] Kraken2 v2.1.2
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.2-gompi-2022a.eb
Labels: update

#17729 add tvem extension to R 4.2.1
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
Labels: enhancement

#17711 {lib}[GCCcore/11.3.0] ruffus v2.8.4 w/ Python 3.10.4
  easybuild/easyconfigs/r/ruffus/ruffus-2.8.4-GCCcore-11.3.0.eb
Labels: update

#17714 {bio,numlib}[foss/2022a] phyx v1.3, Armadillo v11.4.3
  easybuild/easyconfigs/a/Armadillo/Armadillo-11.4.3-foss-2022a.eb
  easybuild/easyconfigs/p/phyx/phyx-1.3-foss-2022a.eb
  easybuild/easyconfigs/p/phyx/phyx-1.3_link_flexiblas.patch
Labels: update

#17717 use CUDA variant of OpenMM 7.5.1 as dependency for AlphaFold 2.3.0
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.0-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-7.5.1-foss-2021b-CUDA-11.4.1-DeepMind-patch.eb
Labels: bug fix

#17726 PyTorch-1.12.1-foss-2022a-CUDA-11.7.0 fix flaky test optim test
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1_use-predefined-data-in-test-optim.patch
Labels: bug fix

#17722 {vis}[foss/2022a] R-tesseract v5.1.0
  easybuild/easyconfigs/r/R-tesseract/R-tesseract-5.1.0-foss-2022a-R-4.2.1.eb
Labels: update

#17730 use patch to fix flaky test optim test in PyTorch 1.12.1 w/ foss/2022a
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2022a.eb
Labels: bug fix

#17731 use patch to fix flaky test optim test in PyTorch 1.12.1 w/ foss/2021b
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b.eb
Labels: bug fix

#17735 {bio}[foss/2022a] Casanovo v3.3.0 w/ Python 3.10.4
  easybuild/easyconfigs/c/Casanovo/Casanovo-3.3.0-foss-2022a.eb
Labels: new

#17736 {bio}[foss/2022a] Casanovo v3.3.0 w/ Python 3.10.4 + CUDA 11.7.0
  easybuild/easyconfigs/c/Casanovo/Casanovo-3.3.0-foss-2022a-CUDA-11.7.0.eb
Labels: new

#17626 Create Python-bundle-3.10.4-foss-2022a.eb
  easybuild/easyconfigs/p/Python-bundle/Python-bundle-3.10.4-foss-2022a.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#17741 {vis}[GCCcore/12.2.0] GL2PS v1.4.2, freeglut v3.4.0
  easybuild/easyconfigs/f/freeglut/freeglut-3.4.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.2-GCCcore-12.2.0.eb
Labels: update

#17739 {data}[foss/2022a] RPostgreSQL v0.7-5
  easybuild/easyconfigs/r/RPostgreSQL/RPostgreSQL-0.7-5-foss-2022a.eb
Labels: new

#17742 {lib,phys}[foss/2022a] BoltzTraP2 v22.12.1, pyFFTW v0.13.1 w/ Python 3.10.4
  easybuild/easyconfigs/b/BoltzTraP2/BoltzTraP2-22.12.1-foss-2022a.eb
  easybuild/easyconfigs/b/BoltzTraP2/BoltzTraP2-22.12.1_use_EB_spglib+eigen.patch
  easybuild/easyconfigs/p/pyFFTW/pyFFTW-0.13.1-foss-2022a.eb
Labels: new, update

#17740 {bio}[foss/2022a] AlphaFold v2.3.1, OpenMM v8.0.0 w/ Python 3.10.4
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.1-foss-2022a.eb
  easybuild/easyconfigs/o/OpenMM/OpenMM-8.0.0-foss-2022a.eb
Labels: update

#17011 {chem}[foss/2022a] Cantera v2.6.0 w/ Python 3.10.4
  easybuild/easyconfigs/c/Cantera/Cantera-2.6.0-foss-2022a.eb
Labels: update

#17743 {data}[foss/2022b] ROOT v6.26.10 w/ Python 3.10.8
  easybuild/easyconfigs/r/ROOT/ROOT-6.26.10-foss-2022b.eb
Labels: update

#17744 {phys}[foss/2022b] PYTHIA v8.309 w/ Python 3.10.8
  easybuild/easyconfigs/p/PYTHIA/PYTHIA-8.309-foss-2022b.eb
Labels: update

#17737 make excluded tests for PyTorch 1.12.1 consistent + also exclude flaky test_optim rather than adding patch to try and fix it
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021a.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2022a.eb
Labels: bug fix, change

#17645 {tools}[GCCcore/12.2.0] nvtop v3.0.1
  easybuild/easyconfigs/n/nvtop/nvtop-3.0.1-GCCcore-12.2.0.eb
Labels: update

#17750 {lib}[GCCcore/11.3.0] Check v0.15.2
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-11.3.0.eb
Labels: update

#17746 {bio}[GCCcore/11.2.0] GenMap v1.3.0
  easybuild/easyconfigs/g/GenMap/GenMap-1.3.0-GCCcore-11.2.0.eb
Labels: new

#17745 {devel}[GCCcore/12.2.0] make v4.4.1
  easybuild/easyconfigs/m/make/make-4.4.1-GCCcore-12.2.0.eb
Labels: update

#16110 {tools}[GCC/11.2.0] SLiM v4.0
  easybuild/easyconfigs/s/SLiM/SLiM-4.0-GCC-11.2.0.eb
  easybuild/easyconfigs/s/SLiM/SLiM-4.0_use_external_zlib_gsl.patch
Labels: update

#17747 {bio}[foss/2022a] pyslim v1.0.1 w/ Python 3.10.4
  easybuild/easyconfigs/p/pyslim/pyslim-1.0.1-foss-2022a.eb
Labels: update

#17752 {vis}[GCCcore/11.3.0] py3Dmol v2.0.1.post1 w/ Python 3.10.4
  easybuild/easyconfigs/p/py3Dmol/py3Dmol-2.0.1.post1-GCCcore-11.3.0.eb
Labels: new

#17754 {lib}[foss/2022a] FUSE v3.14.1
  easybuild/easyconfigs/f/FUSE/FUSE-3.14.1-foss-2022a.eb
Labels: update

#17749 {tools}[GCC/11.3.0] SLiM v4.0.1
  easybuild/easyconfigs/s/SLiM/SLiM-4.0.1-GCC-11.3.0.eb
Labels: update

#17756 {bio}[SYSTEM] IgBlast 1.21.0 update
  easybuild/easyconfigs/i/IgBLAST/IgBLAST-1.21.0-x64-linux.eb
Labels: update

#16817 {lib}[foss/2022a] PyTorch-Geometric v2.1.0 w/ Python 3.10.4
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-2.1.0-foss-2022a-PyTorch-1.12.0-CUDA-11.7.0.eb
Labels: update

#17759 {lib}[GCCcore/12.2.0] FUSE v3.14.1
  easybuild/easyconfigs/f/FUSE/FUSE-3.14.1-GCCcore-12.2.0.eb
Labels: update

#16007 {chem}[foss/2022a] CP2K v9.1, v2022.1
  easybuild/easyconfigs/c/CP2K/CP2K-2022.1-foss-2022a.eb
  easybuild/easyconfigs/c/CP2K/CP2K-9.1-foss-2022a.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-11.3.0.eb
Labels: update

#17540 {ai}[foss/2022a] PyTorch-bundle v1.12.1
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-1.12.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch-bundle/torchtext-0.13.1_cxx_17.patch
  easybuild/easyconfigs/p/PyTorch-bundle/torchtext-0.13.1_use-system-libs.patch
Labels: new

#17770 {bio}[system/system] picard v3.0.0
  easybuild/easyconfigs/p/picard/picard-3.0.0-Java-17.eb
Labels: update

#17769 {bio}[GCCcore/12.2.0] BWA v0.7.17
  easybuild/easyconfigs/b/BWA/BWA-0.7.17-GCCcore-12.2.0.eb
Labels: update

#17771 {bio}[GCC/12.2.0] BEDTools v2.30.0, BamTools v2.5.2
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.30.0-GCC-12.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-12.2.0.eb
Labels: update

#17772 {bio}[GCC/12.2.0] VCFtools v0.1.16
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-GCC-12.2.0.eb
Labels: update

#17738 update recent R easyconfigs with additional R packages
  easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
Labels: enhancement

#17773 {bio}[system/system] Trimmomatic v0.39
  easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.39-Java-17.eb
Labels: update

#17764 correct the python building of DGL, requires static libs
  easybuild/easyconfigs/d/DGL/DGL-0.9.1-foss-2021a-CUDA-11.3.1.eb
Labels: bug fix

#17775 Version bump Java to latest builds that include ppc
  easybuild/easyconfigs/j/Java/Java-11.0.18.eb
  easybuild/easyconfigs/j/Java/Java-11.eb
  easybuild/easyconfigs/j/Java/Java-17.0.6.eb
  easybuild/easyconfigs/j/Java/Java-17.eb
  easybuild/easyconfigs/j/Java/Java-8.362.eb
  easybuild/easyconfigs/j/Java/Java-8.eb
Labels: update

#17777 {phys}[GCC/11.3.0] OptaDOS v1.2.380
  easybuild/easyconfigs/o/OptaDOS/OptaDOS-1.2.380-GCC-11.3.0.eb
Labels: new

#17778 {bio}[foss/2022a] RepeatMasker v4.1.5 w/ Python 3.10.4
  easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.1.5-foss-2022a.eb
Labels: update

#17765 {data}[GCC/11.3.0] xmlf90 v1.5.6
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.5.6-GCC-11.3.0.eb
Labels: update

#17766 Only use QE gitlab source url for QE itself
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-foss-2022a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-intel-2022a.eb
Labels: bug fix

#17767 {data}[GCC/11.3.0] libPSML v1.1.12
  easybuild/easyconfigs/l/libPSML/libPSML-1.1.12-GCC-11.3.0.eb
Labels: update

#17768 {phys}[gompi/2022a] libGridXC v1.1.0
  easybuild/easyconfigs/l/libGridXC/libGridXC-1.1.0-gompi-2022a.eb
Labels: update

#15551 spektral 1.1.0
  easybuild/easyconfigs/s/spektral/spektral-1.1.0-foss-2021b-CUDA-11.4.1.eb
Labels: new

#17784 {lang}[GCC/12.2.0] SOCI v4.0.3
  easybuild/easyconfigs/s/SOCI/SOCI-4.0.3-GCC-12.2.0.eb
Labels: update

#17785 {tools}[GCCcore/12.2.0] yaml-cpp v0.7.0
  easybuild/easyconfigs/y/yaml-cpp/yaml-cpp-0.7.0-GCCcore-12.2.0.eb
Labels: update

#17751 {bio}[foss/2022a] ColabFold v1.5.2, AlphaFold v2.3.4 w/ Python 3.10.4
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.4-foss-2022a-CUDA-11.7.0-ColabFold.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.4-foss-2022a-ColabFold.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-ColabFold-2.3.4_data-dep-paths.patch
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-ColabFold-2.3.4_fix-scp-path.patch
  easybuild/easyconfigs/c/ColabFold/ColabFold-1.5.2-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/c/ColabFold/ColabFold-1.5.2-foss-2022a.eb
Labels: new, update

#17797 {bio}[foss/2022b] Infernal v1.1.4
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-foss-2022b.eb
Labels: update

#17798 {geo}[foss/2022a] rgdal v1.6-6
  easybuild/easyconfigs/r/rgdal/rgdal-1.6-6-foss-2022a.eb
Labels: update

#17760 {toolchain} GCC 13.1.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-13.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.40-GCCcore-13.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.40.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-13.1.0.eb
  easybuild/easyconfigs/g/GCC/GCC-13.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.3-GCCcore-13.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-13.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.13-GCCcore-13.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.13.eb
Labels: update

#17800 {bio}[foss/2022b] tRNAscan-SE v2.0.12
  easybuild/easyconfigs/t/tRNAscan-SE/tRNAscan-SE-2.0.12-foss-2022b.eb
Labels: update

#17807 {tools}[GCCcore/13.1.0] ncurses v6.4, bzip2 v1.0.8, cURL v8.0.1, ...
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-13.1.0.eb
  easybuild/easyconfigs/c/CMake/CMake-3.26.3-GCCcore-13.1.0.eb
  easybuild/easyconfigs/c/cURL/cURL-8.0.1-GCCcore-13.1.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.6.2-GCCcore-13.1.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.4-GCCcore-13.1.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.4.2-GCCcore-13.1.0.eb
Labels: update

#17811 {devel}[GCCcore/13.1.0] pkgconf v1.9.4
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.4-GCCcore-13.1.0.eb
Labels: update

#17814 {lib}[GCCcore/13.1.0] Tcl v8.6.13, UnZip v6.0, libreadline v8.2, ...
  easybuild/easyconfigs/l/libffi/libffi-3.4.4-GCCcore-13.1.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-13.1.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.41.2-GCCcore-13.1.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.13-GCCcore-13.1.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-13.1.0.eb
Labels: update

#17795 {lib}[GCCcore/11.3.0] libRmath v4.2.1
  easybuild/easyconfigs/l/libRmath/libRmath-4.2.1-GCCcore-11.3.0.eb
Labels: update

#17791 {bio}[system/system] IsoSeq v3.8.2
  easybuild/easyconfigs/i/IsoSeq/IsoSeq-3.8.2-linux-x86_64.eb
Labels: new

#17828 {bio}[system/system] ont-guppy v6.4.8
  easybuild/easyconfigs/o/ont-guppy/ont-guppy-6.4.8-CUDA-11.7.0.eb
Labels: update

#17823 {lib}[GCCcore/12.2.0] lxml v4.9.2 w/ Python 3.10.8
  easybuild/easyconfigs/l/lxml/lxml-4.9.2-GCCcore-12.2.0.eb
Labels: update

#17709 {chem,devel,lang,numlib}[GCCcore/10.3.0] Boost.MPI v1.76.0, ESPResSo v4.2.1, Pint v0.20.1 w/ Python 3.9.5
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.76.0-gompi-2021a.eb
  easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/p/Pint/Pint-0.20.1-GCCcore-10.3.0.eb
Labels: new, update

#17822 {data}[foss/2022b] netcdf4-python v1.6.3 w/ Python 3.10.8
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.6.3-foss-2022b.eb
Labels: update

#17810 {tools}[GCCcore/12.2.0] pyperf v2.6.0 w/ Python 3.10.8
  easybuild/easyconfigs/p/pyperf/pyperf-2.6.0-GCCcore-12.2.0.eb
Labels: update

#17801 {math}[GCCcore/11.3.0] muParser v2.3.4
  easybuild/easyconfigs/m/muParser/muParser-2.3.4-GCCcore-11.3.0.eb
Labels: update

#17794 Replacing AOCC broken link
  easybuild/easyconfigs/a/AOCC/AOCC-4.0.0-GCCcore-12.2.0.eb
Labels: bug fix

#17830 specify source_urls inside exts_default_options to ensure correct name expansion for the archived packages
  easybuild/easyconfigs/s/Seurat/Seurat-4.0.1-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/s/Seurat/Seurat-4.0.3-foss-2020b-R-4.0.3.eb
  easybuild/easyconfigs/s/Seurat/Seurat-4.2.0-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/s/Seurat/Seurat-4.3.0-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/s/Seurat/Seurat-4.3.0-foss-2022a-R-4.2.1.eb
Labels: bug fix
