Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-10, with the labels that each got.

#20846 {tools}[foss/2023a] VASPKIT v1.5.1
  easybuild/easyconfigs/v/VASPKIT/VASPKIT-1.5.1-foss-2023a.eb
  easybuild/easyconfigs/v/VASPKIT/VASPKIT-1.5.1_fix-envvars.patch
Labels: new

#21500 {ai}[foss/2023a] gym-pybullet-drones v2.0.0-3d7b12e w/ CUDA 12.1.1
  easybuild/easyconfigs/g/Gymnasium/Gymnasium-0.29.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/g/gym-pybullet-drones/gym-pybullet-drones-2.0.0-3d7b12e-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/s/Stable-Baselines3/Stable-Baselines3-2.3.2-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21514 {bio}[GCCcore/12.3.0] HOLE2 v2.3.1
  easybuild/easyconfigs/h/HOLE2/HOLE2-2.3.1-GCCcore-12.3.0.eb
Labels: new

#21355 {lib}[system/system] cuQuantum v24.08.0.5 w/ CUDA 12.1.1
  easybuild/easyconfigs/c/cuQuantum/cuQuantum-24.08.0.5-CUDA-12.1.1.eb
Labels: new

#21505 {bio}[GCCcore/13.2.0] GATK v4.6.0.0 w/ Java 17
  easybuild/easyconfigs/g/GATK/GATK-4.6.0.0-GCCcore-13.2.0-Java-17.eb
Labels: update

#21517 {bio}[foss/2023a] read2tree v0.1.5, ngmlr v0.2.7, NextGenMap v0.5.5
  easybuild/easyconfigs/n/NextGenMap/NextGenMap-0.5.5-GCC-12.3.0.eb
  easybuild/easyconfigs/n/ngmlr/ngmlr-0.2.7-foss-2023a.eb
  easybuild/easyconfigs/r/read2tree/read2tree-0.1.5-foss-2023a.eb
Labels: new, update

#21521 {bio}[gfbf/2023a] deepTools v3.5.5
  easybuild/easyconfigs/d/deepTools/deepTools-3.5.5-gfbf-2023a.eb
Labels: update

#21520 {phys}[foss/2023a] ISCE2 v2.6.3
  easybuild/easyconfigs/i/ISCE2/ISCE2-2.6.3-foss-2023a.eb
Labels: new

#20857 {ai}[foss/2023a] Slideflow v3.0.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/s/Slideflow/Slideflow-3.0.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/s/Slideflow/Slideflow-3.0.1_fix-opencv-dep.patch
Labels: new

#21506 {lang}[system/system] Julia v1.10.5 w/ linux x86_64
  easybuild/easyconfigs/j/Julia/Julia-1.10.5-linux-x86_64.eb
Labels: update

#21522 {chem}[GCCcore/12.3.0] XCFun v2.1.1
  easybuild/easyconfigs/x/XCFun/XCFun-2.1.1-GCCcore-12.3.0.eb
Labels: update

#21526 {data}[foss/2021b,2022a,2022b,2023a] ROOT v6.24.06, v6.26.06, v6.26.10, v6.30.6: patch to disable sysroot for cling at runtime
  easybuild/easyconfigs/r/ROOT/ROOT-6.12.06_cling-runtime-sysroot.patch
  easybuild/easyconfigs/r/ROOT/ROOT-6.24.06-foss-2021b.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.26.06-foss-2022a.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.26.10-foss-2022b.eb
  easybuild/easyconfigs/r/ROOT/ROOT-6.30.06-foss-2023a.eb
Labels: update

#21511 {chem}[intel/2024a] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-intel-2024a.eb
Labels: update, 2024a

#21529 {bio}[GCCcore/12.3.0] GeneMark-ET v4.72
  easybuild/easyconfigs/g/GeneMark-ET/GeneMark-ET-4.72-GCCcore-12.3.0.eb
Labels: update

#21535 {bio}[GCC/12.3.0] GMAP-GSNAP v2023-04-20
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2023-04-20-GCC-12.3.0.eb
Labels: update

#21528 link `libOpenCL.so.1` to the `lib` directory for NextGenMap (required when using RPATH linking)
  easybuild/easyconfigs/n/NextGenMap/NextGenMap-0.5.5-GCC-12.3.0.eb
Labels: bug fix

#21430 {bio}[foss/2023b] GROMACS v2024.3
  easybuild/easyconfigs/g/GROMACS/GROMACS-2024.3-foss-2023b.eb
Labels: update

#16608 {chem}[intel-compilers/2022.1.0] NCIPLOT v4.2-20221021
  easybuild/easyconfigs/n/NCIPLOT/NCIPLOT-4.2-20221021-intel-compilers-2022.1.0.eb
Labels: update

#20984 {geo}[foss/2023a] ESMPy v8.6.0
  easybuild/easyconfigs/e/ESMPy/ESMPy-8.6.0-foss-2023a.eb
  easybuild/easyconfigs/e/ESMPy/ESMPy-8.6.0_use-static-version.patch
Labels: update

#21480 {chem}[foss/2023a] MoloVol v1.1.1
  easybuild/easyconfigs/m/MoloVol/MoloVol-1.1.1-GCC-12.3.0.eb
Labels: new

#21543 {chem}[foss/2024a] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-foss-2024a.eb
Labels: update, 2024a

#21545 {chem}[gfbf/2024a] libcint v6.1.2
  easybuild/easyconfigs/l/libcint/libcint-6.1.2-gfbf-2024a.eb
  easybuild/easyconfigs/l/libcint/libcint-6.1.2_fix_tests.patch
Labels: update, 2024a

#21499 {lib}[GCCcore/13.3.0] psutil v6.0.0
  easybuild/easyconfigs/p/psutil/psutil-6.0.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#21486 {bio}[GCC/13.2.0] starcode v1.4
  easybuild/easyconfigs/s/starcode/starcode-1.4-GCC-13.2.0.eb
Labels: new

#21481 {lib}[GCC/13.3.0] OpenImageIO v2.5.15.0
  easybuild/easyconfigs/o/OpenImageIO/OpenImageIO-2.5.15.0-GCC-13.3.0.eb
Labels: update, 2024a

#21490 {bio}[foss/2023a] dorado v0.8.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dorado/dorado-0.8.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/d/dorado/dorado-0.8.0_dont_install_external_libraries.patch
Labels: update

#12209 {lib}[system/system] popt v1.18
  easybuild/easyconfigs/p/popt/popt-1.18.eb
Labels: update

#13361 {vis}[foss/2021a] freud-analysis v2.6.2 w/ Python 3.9.5
  easybuild/easyconfigs/f/freud-analysis/freud-analysis-2.6.2-foss-2021a.eb
Labels: update

#21552 {bio}[foss/2023b] GROMACS v2024.3 w/ PLUMED 2.9.2
  easybuild/easyconfigs/g/GROMACS/GROMACS-2024.3-foss-2023b-PLUMED-2.9.2.eb
Labels: update

#21554 {bio}[gompi/2023a] ABRicate v1.0.0, any2fasta v0.4.2
  easybuild/easyconfigs/a/ABRicate/ABRicate-1.0.0-gompi-2023a.eb
  easybuild/easyconfigs/a/any2fasta/any2fasta-0.4.2-GCCcore-12.3.0.eb
Labels: update

#21551 {bio}[gompi/2023a] AMRFinderPlus v3.12.8
  easybuild/easyconfigs/a/AMRFinderPlus/AMRFinderPlus-3.12.8-gompi-2023a.eb
Labels: update

#21550 add missing (optional) dependency cp2k-input-tools to phonopy 2.20.0
  easybuild/easyconfigs/c/cp2k-input-tools/cp2k-input-tools-0.9.1-foss-2023a.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.20.0-foss-2023a.eb
Labels: enhancement, new

#21557 strip out '-minsize 1' option from umi_binning.sh in longread_umi 0.3.2, since it's not supported by VSEARCH
  easybuild/easyconfigs/l/longread_umi/longread_umi-0.3.2-foss-2023a.eb
Labels: bug fix

#21558 {bio}[GCC/13.3.0] SURVIVOR v1.0.7-20231201
  easybuild/easyconfigs/s/SURVIVOR/SURVIVOR-1.0.7-20231201-GCC-13.3.0.eb
Labels: update

#21562 {math}[gfbf/2024a] sympy v1.13.3
  easybuild/easyconfigs/s/sympy/sympy-1.13.3-gfbf-2024a.eb
Labels: update, 2024a

#21531 {bio}[GCCcore/12.3.0] Trim_Galore v0.6.10
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.10-GCCcore-12.3.0.eb
Labels: update

#21548 {chem}[GCC/13.2.0] json-fortran v9.0.2, mctc-lib v0.3.1, mstore v0.3.0, ...
  easybuild/easyconfigs/c/CREST/CREST-3.0.2-gfbf-2023b.eb
  easybuild/easyconfigs/d/dftd4/dftd4-3.7.0-gfbf-2023b.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-9.0.2-GCC-13.2.0.eb
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCC-13.2.0.eb
  easybuild/easyconfigs/m/mstore/mstore-0.3.0-GCC-13.2.0.eb
  easybuild/easyconfigs/m/multicharge/multicharge-0.3.0-gfbf-2023b.eb
Labels: update

#21539 {bio}[GCC/12.3.0] Subread v2.0.6
  easybuild/easyconfigs/s/Subread/Subread-2.0.6-GCC-12.3.0.eb
Labels: update

#21580 {lang}[foss/2023b] RStudio-Server v2024.09.0+375 w/ Java 11 R 4.4.1
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2024.09.0+375-foss-2023b-Java-11-R-4.4.1.eb
Labels: update

#21583 add goldilocks + gsDesign extensions to R-bundle-CRAN v2024.06
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
Labels: enhancement

#21589 {bio}[gfbf/2023a,gfbf/2023b] QUAST v5.2.0
  easybuild/easyconfigs/q/QUAST/QUAST-5.2.0-gfbf-2023a.eb
  easybuild/easyconfigs/q/QUAST/QUAST-5.2.0-gfbf-2023b.eb
Labels: update

#21536 {bio}[GCC/12.3.0] BLAT v3.7
  easybuild/easyconfigs/b/BLAT/BLAT-3.7-GCC-12.3.0.eb
Labels: update

#21591 {bio}[gompi/2023a,gompi/2023b] kallisto v0.51.1
  easybuild/easyconfigs/k/kallisto/kallisto-0.51.1-gompi-2023a.eb
  easybuild/easyconfigs/k/kallisto/kallisto-0.51.1-gompi-2023b.eb
Labels: update

#21592 {math}[GCC/13.2.0] lpsolve v5.5.2.11
  easybuild/easyconfigs/l/lpsolve/lpsolve-5.5.2.11-GCC-13.2.0.eb
Labels: update

#21594 {bio}[GCC/13.2.0] BamTools v2.5.2
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-13.2.0.eb
Labels: update

#21595 {bio}[GCCcore/12.3.0,GCCcore/13.2.0] NECAT v0.0.1
  easybuild/easyconfigs/n/NECAT/NECAT-0.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/n/NECAT/NECAT-0.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/NECAT/NECAT-0.0.1_add-cstdint-include.patch
Labels: update

#21353 {base}[foss/2023a] PennyLane v0.37.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/p/PennyLane/PennyLane-0.37.0-foss-2023a-CUDA-12.1.1.eb
Labels: new

#21613 remove explicit use of `ld.gold` in recent PLUMED easyconfigs
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-foss-2021a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-intel-2021a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-foss-2021b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-foss-2021b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.1-foss-2022a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2022b.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2023a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.2-foss-2023b.eb
Labels: update, change

#19104 {lib,vis}[foss/2022b] COLMAP v3.8, Ceres-Solver v2.2.0, FLANN v1.9.2, glog v0.6.0, glew v2.2.0, gflags v2.2.2
  easybuild/easyconfigs/c/COLMAP/COLMAP-3.8-foss-2022b.eb
  easybuild/easyconfigs/c/Ceres-Solver/Ceres-Solver-2.2.0-foss-2022b.eb
  easybuild/easyconfigs/f/FLANN/FLANN-1.9.2-foss-2022b.eb
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-12.2.0-egl.eb
  easybuild/easyconfigs/g/glog/glog-0.6.0-GCCcore-12.2.0.eb
Labels: new, update

#21024 {lib}[foss/2023a] Phonopy-Spectroscopy v20240308
  easybuild/easyconfigs/p/Phonopy-Spectroscopy/Phonopy-Spectroscopy-20240308-foss-2023a.eb
Labels: new

#20349 {ai}[foss/2023a] Gradio v4.19.0
  easybuild/easyconfigs/g/Gradio/Gradio-4.19.0-gfbf-2023a.eb
Labels: new

#21601 {chem}[foss/2023a] waLBerla v6.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/w/waLBerla/waLBerla-6.1-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21576 {lib}[GCCcore/13.3.0] tbb v2021.13.0
  easybuild/easyconfigs/t/tbb/tbb-2021.13.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#21600 {chem}[foss/2023a] waLBerla v6.1
  easybuild/easyconfigs/w/waLBerla/waLBerla-6.1-foss-2023a.eb
Labels: update

#19942 {bio}[foss/2023a] AlphaFold v2.3.2, dm-haiku v0.0.12, tensorstore v0.1.65 w/ CUDA v12.1.1
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.2_BioPythonPDBData.patch
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.2_data-dep-paths-shebang-UniRef30.patch
  easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.3.2_use_openmm_8.0.0.patch
  easybuild/easyconfigs/d/dm-haiku/dm-haiku-0.0.12-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.65-foss-2023a.eb
Labels: new, update

#20913 {bio,tools}[foss/2023b] arrow-R v16.1.0, R-bundle-Bioconductor v3.19 w/ R 4.4.1
  easybuild/easyconfigs/a/arrow-R/arrow-R-16.1.0-foss-2023b-R-4.4.1.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.19-foss-2023b-R-4.4.1.eb
Labels: update

#21555 {math}[foss/2023a] KMCLib v2.0-a2, numpy v1.16.6, pytest v4.6.11 w/ Python 2.7.18
  easybuild/easyconfigs/k/KMCLib/KMCLib-2.0-a2-foss-2023a-Python-2.7.18.eb
  easybuild/easyconfigs/n/numpy/numpy-1.16.2_relax-long-complex-test.patch
  easybuild/easyconfigs/n/numpy/numpy-1.16.6-foss-2023a-Python-2.7.18.eb
  easybuild/easyconfigs/n/numpy/numpy-1.16.6_add_flexiblas_detection.patch
  easybuild/easyconfigs/n/numpy/numpy-1.16.6_handle_failing_linalg_test.patch
  easybuild/easyconfigs/n/numpy/numpy-1.20.3_fix-fortran-compiler-error.patch
  easybuild/easyconfigs/p/pytest/pytest-4.6.11-GCC-12.3.0-Python-2.7.18.eb
Labels: new, update

#21602 {bio}[foss/2023a] Stellarscope v1.4.1
  easybuild/easyconfigs/s/Stellarscope/Stellarscope-1.4.1-foss-2023a.eb
Labels: new

#21524 {chem}[foss/2023a] PyCheMPS2 v1.8.12
  easybuild/easyconfigs/p/PyCheMPS2/PyCheMPS2-1.8.12-foss-2023a.eb
Labels: update

#21553 {chem}[foss/2023a] Dice v20240702
  easybuild/easyconfigs/d/Dice/Dice-20240702-foss-2023a.eb
Labels: update

#21525 {phys}[foss/2023a] Block v1.5.3-20200525
  easybuild/easyconfigs/b/Block/Block-1.5.3-20200525-foss-2023a.eb
Labels: update

#21264 {bio}[GCCcore/12.3.0] NextDenovo v2.5.2
  easybuild/easyconfigs/n/NextDenovo/NextDenovo-2.5.2-20240510-GCCcore-12.3.0.eb
Labels: new

#21343 {compiler}[GCCcore/13.3.0] AOCC v4.2.0
  easybuild/easyconfigs/a/AOCC/AOCC-4.2.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#21629 {devel,tools,lib,compiler}[system/system,GCCcore/14.2.0] Add pkgconf 2.3.0, XZ 5.6.3, ncurses 6.5, libxml 2.13.4, AOCC 5.0.0
  easybuild/easyconfigs/a/AOCC/AOCC-5.0.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libxml2/libxml2-2.13.4-GCCcore-14.2.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-6.5-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.3.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.3.0.eb
  easybuild/easyconfigs/x/XZ/XZ-5.6.3-GCCcore-14.2.0.eb
Labels: update, 2024b

#21619 stop using `--buildtype=release` in easyconfigs using `MesonNinja` easyblock
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.36.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.5-GCC-10.2.0.eb
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.6-foss-2021a-R-4.1.0.eb
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.6-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/f/freebayes/freebayes-1.3.7-gfbf-2023a-R-4.3.2.eb
  easybuild/easyconfigs/g/GLib/GLib-2.64.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.66.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.68.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.69.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.72.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.75.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.77.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.78.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GLib/GLib-2.80.4-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.40.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.40.0-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.10-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.10-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.10-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.11-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.8-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.44.7-GCCcore-9.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.47.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.48.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.48.8-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.50.12-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.50.14-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.50.7-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.51.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.54.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PretextMap/PretextMap-0.1.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.20.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.21.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.21.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.22.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.22.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.22.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.23.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/xtb/xtb-6.4.1-foss-2021b.eb
  easybuild/easyconfigs/x/xtb/xtb-6.4.1-intel-2021a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.5.0-foss-2021b.eb
  easybuild/easyconfigs/x/xtb/xtb-6.5.1-foss-2022a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.6.0-foss-2022a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.6.0-intel-2022a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.6.1-gfbf-2022b.eb
  easybuild/easyconfigs/x/xtb/xtb-6.6.1-gfbf-2023a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.7.0-gfbf-2023a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.7.1-gfbf-2023b.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix

#21630 {phys}[GCCcore/13.2.0] Lime 1.3.2
  easybuild/easyconfigs/l/LIME/LIME-1.3.2-GCCcore-12.3.0.eb
Labels: new

#21649 {bio}[GCC/12.3.0,foss/2023a] NanoPack v20230602, kyber v0.4.0
  easybuild/easyconfigs/k/kyber/kyber-0.4.0-GCC-12.3.0.eb
  easybuild/easyconfigs/k/kyber/kyber-0.4.0_requirements.patch
  easybuild/easyconfigs/n/NanoPack/NanoPack-20230602-foss-2023a.eb
Labels: new

#21657 demote hatchling to build-only dependency in easyconfigs for anndata 0.10.5.post1, Cassiopeia 2.0.0, phonemizer 3.2.1, scanpy 1.9.8, wandb 0.16.1
  easybuild/easyconfigs/a/anndata/anndata-0.10.5.post1-foss-2023a.eb
  easybuild/easyconfigs/c/Cassiopeia/Cassiopeia-2.0.0-foss-2023a.eb
  easybuild/easyconfigs/h/hatch-jupyter-builder/hatch-jupyter-builder-0.9.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/phonemizer/phonemizer-3.2.1-gfbf-2023a.eb
  easybuild/easyconfigs/s/scanpy/scanpy-1.9.8-foss-2023a.eb
  easybuild/easyconfigs/w/wandb/wandb-0.16.1-GCC-12.3.0.eb
Labels: bug fix

#21674 Fix alignment bug in patchelf 0.18.0 by adding patch
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0_fix-alignment.patch
Labels: bug fix

#21654 {bio}[GCC/13.3.0] GMAP-GSNAP v2024-09-18
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2024-09-18-GCC-13.3.0.eb
  easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2024-09-18_fix-source-files-for-haswell.patch
Labels: update

#21679 {vis}[gfbf/2023a] mpl-ascii v0.10.0
  easybuild/easyconfigs/m/mpl-ascii/mpl-ascii-0.10.0-gfbf-2023a.eb
Labels: new

#21663 {lib}[GCCcore/13.3.0] tornado v6.4.1
  easybuild/easyconfigs/t/tornado/tornado-6.4.1-GCCcore-13.3.0.eb
Labels: update

#21664 {lib}[GCCcore/13.3.0] utf8proc v2.9.0
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.9.0-GCCcore-13.3.0.eb
Labels: update

#21660 {lib}[GCCcore/13.3.0] snappy v1.1.10
  easybuild/easyconfigs/s/snappy/snappy-1.1.10-GCCcore-13.3.0.eb
Labels: update

#21681 {bio}[GCCcore/12.3.0] Longshot v1.0.0
  easybuild/easyconfigs/l/Longshot/Longshot-1.0.0-GCCcore-12.3.0.eb
Labels: update

#21662 {lib}[gompi/2024a] mpi4py v4.0.1
  easybuild/easyconfigs/m/mpi4py/mpi4py-4.0.1-gompi-2024a.eb
Labels: update

#21668 {tools}[gfbf/2024a] bokeh v3.6.0
  easybuild/easyconfigs/b/bokeh/bokeh-3.6.0-gfbf-2024a.eb
Labels: update

#21661 {data}[gfbf/2024a] dask v2024.9.1
  easybuild/easyconfigs/d/dask/dask-2024.9.1-gfbf-2024a.eb
Labels: update

#21669 {lib}[GCCcore/13.3.0] RE2 v2024-07-02
  easybuild/easyconfigs/r/RE2/RE2-2024-07-02-GCCcore-13.3.0.eb
Labels: update

#21621 {bio}[foss/2023a] Cellformer v20240917 w/ R 4.3.2
  easybuild/easyconfigs/c/Cellformer/Cellformer-20240917-foss-2023a-R-4.3.2.eb
Labels: new

#21659 {data}[GCCcore/13.3.0] redis-py v5.1.1, Redis v7.4.1, Arrow v17.0.0
  easybuild/easyconfigs/a/Arrow/Arrow-17.0.0-gfbf-2024a.eb
  easybuild/easyconfigs/r/Redis/Redis-7.4.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/r/redis-py/redis-py-5.1.1-GCCcore-13.3.0.eb
Labels: update

#21665 {tools}[foss/2024a] Ray-project v2.37.0
  easybuild/easyconfigs/r/Ray-project/Ray-project-2.37.0-foss-2024a.eb
Labels: update

#21682 {phys}[GCCcore/13.2.0,GCCcore/13.3.0] LIME v1.3.2
  easybuild/easyconfigs/l/LIME/LIME-1.3.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LIME/LIME-1.3.2-GCCcore-13.3.0.eb
Labels: update

#21677 {bio}[foss/2023a] phylo-treetime v0.11.4
  easybuild/easyconfigs/p/phylo-treetime/phylo-treetime-0.11.4-foss-2023a.eb
Labels: new

#21680 {geo}[gfbf/2023a] FloPy v3.8.2
  easybuild/easyconfigs/f/FloPy/FloPy-3.8.2-gfbf-2023a.eb
Labels: new

#21686 Remove redundant sanity check from jedi easyconfigs
  easybuild/easyconfigs/j/jedi/jedi-0.18.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/j/jedi/jedi-0.19.1-GCCcore-13.2.0.eb
Labels: bug fix

#21688 {lib}[GCCcore/13.3.0] boto3 v1.35.36
  easybuild/easyconfigs/b/boto3/boto3-1.35.36-GCCcore-13.3.0.eb
Labels: update

#21687 {lib}[GCCcore/13.3.0] aiohttp v3.10.10
  easybuild/easyconfigs/a/aiohttp/aiohttp-3.10.10-GCCcore-13.3.0.eb
Labels: update

#21633 {lang}[GCCcore/13.3.0] Rust v1.81.0
  easybuild/easyconfigs/r/Rust/Rust-1.81.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#21695 {tools}[gfbf/2024a] wrapt v1.16.0
  easybuild/easyconfigs/w/wrapt/wrapt-1.16.0-gfbf-2024a.eb
Labels: update, 2024a

#21645 {data}[GCCcore/13.3.0] XML-Parser v2.47 w/ Perl 5.38.2
  easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.47-GCCcore-13.3.0-Perl-5.38.2.eb
Labels: update, 2024a

#21644 {lang}[system/system] Miniconda3 v24.7.1-0
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-24.7.1-0.eb
Labels: update

#21685 {tools}[GCCcore/13.3.0] hatch-jupyter-builder v0.9.1, PyZMQ v26.2.0, IPython v8.28.0, ...
  easybuild/easyconfigs/h/hatch-jupyter-builder/hatch-jupyter-builder-0.9.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/i/IPython/IPython-8.28.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.2.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/j/jedi/jedi-0.19.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/j/jupyter-server/jupyter-server-2.14.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PyZMQ/PyZMQ-26.2.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#21689 {tools}[foss/2024a] s3fs v2024.9.0
  easybuild/easyconfigs/s/s3fs/s3fs-2024.9.0-foss-2024a.eb
Labels: update, 2024a

#21702 fix the zero division bug of `networkx-3.1`
  easybuild/easyconfigs/n/networkx/networkx-3.1-gfbf-2023a.eb
  easybuild/easyconfigs/n/networkx/networkx-3.1_zero_division.patch
Labels: bug fix

#21704 Add `trimmomatic` wrapper script for recent Trimmomatic 0.39 easyconfigs
  easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.39-Java-11.eb
  easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.39-Java-17.eb
Labels: enhancement

#21569 {bio}[foss/2023a] EVidenceModeler v2.1.0, FASTA v36.3.8i, PASA v2.5.3, pblat v2.5.1
  easybuild/easyconfigs/e/EVidenceModeler/EVidenceModeler-2.0.0_set-correct-CFlags-for-ParaFly.patch
  easybuild/easyconfigs/e/EVidenceModeler/EVidenceModeler-2.1.0-foss-2023a.eb
  easybuild/easyconfigs/f/FASTA/FASTA-36.3.8i-GCC-12.3.0.eb
  easybuild/easyconfigs/p/PASA/PASA-2.5.3-foss-2023a.eb
  easybuild/easyconfigs/p/pblat/pblat-2.5.1-foss-2023a.eb
Labels: new, update

#21642 {vis}[GCCcore/13.3.0] Kaleido v0.2.1, plotly.py v5.24.1, QCG-PilotJob v0.14.1 ...
  easybuild/easyconfigs/k/Kaleido/Kaleido-0.2.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/plotly.py/plotly.py-5.24.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/plotly.py/tenacity-9.0.0_fix_version.patch
  easybuild/easyconfigs/q/QCG-PilotJob/QCG-PilotJob-0.14.1-gfbf-2024a.eb
  easybuild/easyconfigs/q/QCG-PilotJob/trove-classifiers-2024.10.13_fix_setup.patch
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.14.4-gfbf-2024a.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.14.4_fix_setup.patch
Labels: update, 2024a

#21510 {data,tools}[GCCcore/13.3.0,iimpi/2024a] HDF5 v1.14.5, Szip v2.1.1
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.5-iimpi-2024a.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-13.3.0.eb
Labels: update

#21560 {math}[foss/2024a] ELPA v2024.05.001
  easybuild/easyconfigs/e/ELPA/ELPA-2024.05.001-foss-2024a.eb
Labels: update, 2024a

#21707 {vis}[gfbf/2023b] mpl-ascii v0.10.0
  easybuild/easyconfigs/m/mpl-ascii/mpl-ascii-0.10.0-gfbf-2023b.eb
Labels: update

#21706 {tools}[GCC/13.3.0] columba v1.2-20240326, sparsehash v2.0.4
  easybuild/easyconfigs/c/columba/columba-1.2-20240326-GCC-13.3.0.eb
  easybuild/easyconfigs/s/sparsehash/sparsehash-2.0.4-GCCcore-13.3.0.eb
Labels: new, update

#21708 {bio}[system/system] SNPTEST v2.5.6
  easybuild/easyconfigs/s/SNPTEST/SNPTEST-2.5.6.eb
Labels: new

#21700 fix CI check for extension patches using `alt_location`
  test/easyconfigs/easyconfigs.py
Labels: bug fix, tests

#21417 {lib, data, numlib, tools, math}[GCCcore/13.3.0, foss/2024a, gfbf/2024a] libmad-0.15.1b, SoX-14.4.2, SuiteSparse-7.8.2, Szip-2.1.1, sympy-1.13.2, trimesh-4.4.9, Voro++-0.4.6, Xerces-C++-3.2.5, zsh-5.9
  easybuild/easyconfigs/l/libmad/libmad-0.15.1b-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.8.2-foss-2024a-METIS-5.1.0.eb
  easybuild/easyconfigs/t/trimesh/trimesh-4.4.9-gfbf-2024a.eb
  easybuild/easyconfigs/v/Voro++/Voro++-0.4.6-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/z/zsh/zsh-5.9-GCCcore-13.3.0.eb
Labels: update, 2024a

#21433 {vis, data, tools, lib}[GCCcore/13.3.0] at-spi2-atk-2.38.0, at-spi2-core-2.54.0, exiv2-0.28.3, GraphicsMagick-1.3.45, HDF-4.3.0, IPython-8.27.0, inih-58, libgeotiff-1.7.3
  easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.54.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/e/exiv2/exiv2-0.28.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.45-GCCcore-13.3.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.3.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/i/IPython/IPython-8.27.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/i/inih/inih-58-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.7.3-GCCcore-13.3.0.eb
Labels: update, 2024a

#21744 {bio}[gompi/2023a] MEME v5.5.7, XML-Compile v1.63, XML-LibXML v2.0210
  easybuild/easyconfigs/m/MEME/MEME-5.5.7-gompi-2023b.eb
  easybuild/easyconfigs/x/XML-Compile/XML-Compile-1.63-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0210-GCCcore-13.2.0.eb
Labels: update

#21731 {ai}[foss/2022a] Dask-ML v2022.5.27
  easybuild/easyconfigs/d/Dask-ML/Dask-ML-2022.5.27-foss-2022a.eb
Labels: new

#21734 {ai}[foss/2022a] SciKeras v0.12.0
  easybuild/easyconfigs/s/SciKeras/SciKeras-0.12.0-foss-2022a.eb
Labels: new

#21561 {math}[gfbf/2024a] Shapely v2.0.6
  easybuild/easyconfigs/s/Shapely/Shapely-2.0.6-gfbf-2024a.eb
Labels: update, 2024a

#21748 use new checksum for source tarball of SIONlib 1.7.7
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-11.2.0-tools.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-11.3.0-tools.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-12.2.0-tools.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-12.3.0-tools.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-13.2.0-tools.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-13.3.0-tools.eb
Labels: bug fix

#21750 {chem}[GCC/12.3.0] CPPE v0.3.1
  easybuild/easyconfigs/c/CPPE/CPPE-0.3.1-GCC-12.3.0.eb
Labels: update

#21606 {chem}[foss/2023a] Solids4foam v2.1
  easybuild/easyconfigs/s/Solids4foam/Solids4foam-2.1-foss-2023a.eb
Labels: new

#21703 {bio}[foss/2023a] CIRCE v0.3.4
  easybuild/easyconfigs/c/CIRCE/CIRCE-0.3.4-foss-2023a.eb
Labels: new

#21716 {tools}[GCCcore/12.3.0] PyBioLib v1.2.205
  easybuild/easyconfigs/p/PyBioLib/PyBioLib-1.2.205-GCCcore-12.3.0.eb
Labels: update

#21725 {bio}[GCCcore/12.3.0] modkit v0.3.3
  easybuild/easyconfigs/m/modkit/modkit-0.3.3-GCCcore-12.3.0.eb
Labels: update

#21767 {bio}[gompi/2023a] MrBayes v3.2.7
  easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.7-gompi-2023a.eb
Labels: update

#21757 {bio}[GCCcore/12.3.0] PoPoolation-TE2 v1.10.03
  easybuild/easyconfigs/p/PoPoolation-TE2/PoPoolation-TE2-1.10.03-GCCcore-12.3.0.eb
Labels: new

#21742 {bio}[GCC/13.3.0] BEDTools v2.31.1, BamTools v2.5.2
  easybuild/easyconfigs/b/BEDTools/BEDTools-2.31.1-GCC-13.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-13.3.0.eb
Labels: update, 2024a

#21776 add missing perl-bundle-cpan to recent parallel versions
  easybuild/easyconfigs/p/parallel/parallel-20230722-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/parallel/parallel-20240322-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/parallel/parallel-20240722-GCCcore-13.3.0.eb
Labels: bug fix
