Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-07, with the labels that each got.

#20941 {bio}[foss/2023b] biom-format v2.1.16
  easybuild/easyconfigs/b/biom-format/biom-format-2.1.16-foss-2023b.eb
Labels: update

#20933 {bio,vis}[foss/2023a] n2v v0.3.3, CSBDeep v0.7.4
  easybuild/easyconfigs/c/CSBDeep/CSBDeep-0.7.4-foss-2023a.eb
  easybuild/easyconfigs/n/n2v/n2v-0.3.3-foss-2023a.eb
Labels: update

#20880 {lib}[GCCcore/12.3.0] orjson v3.9.15
  easybuild/easyconfigs/o/orjson/orjson-3.9.15-GCCcore-12.3.0.eb
Labels: new

#20929 {math}[gompi/2023b] ParMETIS v4.0.3
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2023b.eb
Labels: update

#20930 {math}[foss/2023b] MUMPS v5.6.1 w/ metis
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2023b-metis.eb
Labels: update

#20567 fix typo in description of SuiteSparse v7.7.0
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.7.0-foss-2023b-METIS-5.1.0.eb
Labels: bug fix

#20566 {numlib}[foss/2023b] SuperLU_DIST v8.2.1
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.2.1-foss-2023b.eb
Labels: update

#20564 {cae}[foss/2023b] meshio v5.3.5
  easybuild/easyconfigs/m/meshio/meshio-5.3.5-foss-2023b.eb
Labels: update

#20950 {data}[foss/2023a] SHAP v0.43.0
  easybuild/easyconfigs/s/SHAP/SHAP-0.43.0-foss-2023a.eb
Labels: update

#20952 {chem}[GCC/12.3.0] packmol v20.14.4
  easybuild/easyconfigs/p/packmol/packmol-20.14.4-GCC-12.3.0.eb
Labels: update

#20940 {tools}[GCCcore/13.2.0] Pylint v3.2.5
  easybuild/easyconfigs/p/Pylint/Pylint-3.2.5-GCCcore-13.2.0.eb
Labels: update

#20944 {bio}[foss/2022b] Qualimap v2.3 w/ R 4.2.2
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.3-foss-2022b-R-4.2.2.eb
Labels: update

#20831 {vis}[GCCcore/13.2.0] Sphinx-RTD-Theme v2.0.0
  easybuild/easyconfigs/s/Sphinx-RTD-Theme/Sphinx-RTD-Theme-2.0.0-GCCcore-13.2.0.eb
Labels: update

#20487 remove `CMAKE_INSTALL_LIBDIR` settings from `configopts` + add test to enfore use of `install_libdir` instead
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-fosscuda-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/a/Arrow/Arrow-0.17.1-intel-2020b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-11.0.0-gfbf-2022b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-14.0.1-gfbf-2023a.eb
  easybuild/easyconfigs/a/Arrow/Arrow-6.0.0-foss-2021a.eb
  easybuild/easyconfigs/a/Arrow/Arrow-6.0.0-foss-2021b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-6.0.1-foss-2021a.eb
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2021a.eb
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2021b.eb
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2022.05.eb
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2022a.eb
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.7.0-intel-2020a.eb
  easybuild/easyconfigs/b/Brunsli/Brunsli-0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/b/Brunsli/Brunsli-0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/b/Brunsli/Brunsli-0.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/b/Brunsli/Brunsli-0.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/b/Brunsli/Brunsli-0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/f/Faiss/Faiss-1.7.4-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/f/flatbuffers/flatbuffers-2.0.7-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LERC/LERC-3.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/LERC/LERC-3.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/Lab-Streaming-Layer/Lab-Streaming-Layer-1.16.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.1.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.1.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.1.5.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-3.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenMEEG/OpenMEEG-2.5.7-foss-2023a.eb
  easybuild/easyconfigs/q/QtKeychain/QtKeychain-0.13.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/ROCT-Thunk-Interface/ROCT-Thunk-Interface-4.5.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-foss-2021a.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-fosscuda-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-8.2.0-intel-2020a-Python-3.8.2.eb
  easybuild/easyconfigs/v/VTK/VTK-9.0.1-foss-2020b.eb
  easybuild/easyconfigs/v/VTK/VTK-9.0.1-foss-2021a.eb
  easybuild/easyconfigs/v/VTK/VTK-9.0.1-fosscuda-2020b.eb
  easybuild/easyconfigs/v/VTK/VTK-9.1.0-foss-2021b.eb
  easybuild/easyconfigs/v/VTK/VTK-9.2.0.rc2-foss-2022a.eb
  easybuild/easyconfigs/v/VTK/VTK-9.2.2-foss-2022a.eb
  easybuild/easyconfigs/v/VTK/VTK-9.2.6-foss-2022b.eb
  easybuild/easyconfigs/v/VTK/VTK-9.3.0-foss-2023a.eb
  easybuild/easyconfigs/v/VTK/VTK-9.3.0-foss-2023b.eb
  test/easyconfigs/easyconfigs.py
Labels: code cleanup, EasyBuild-5.0

#20103 add wrapper for Julia with linking safeguards and delegate environment setup to JuliaPackage
  easybuild/easyconfigs/j/Julia/Julia-1.10.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.0-linux-aarch64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.5-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.6-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.6.7-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.1-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.2-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.7.3-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.8.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.8.2-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.8.5-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.9.0-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.9.2-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/Julia-1.9.3-linux-x86_64.eb
  easybuild/easyconfigs/j/Julia/julia.wrapper
Labels: bug fix

#20957 Set `SATSUMA2_PATH` so Satsuma2 can locate executables
  easybuild/easyconfigs/s/Satsuma2/Satsuma2-20220304-GCC-11.3.0.eb
Labels: bug fix

#20847 add patch to SciPy-bundle 2024.05 that fixes numpy test failures on RISC-V
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024.05.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.26.4_fix-riscv64-test-failures.patch
Labels: bug fix, EESSI, riscv

#20919 {mpi,perf,toolchain}[iimpi/2024.06,intel-compilers/2024.2.0,system/system] impi v2021.13.0, iimpi v2024.06, OSU-Micro-Benchmarks v7.4
  easybuild/easyconfigs/i/iimpi/iimpi-2024.06.eb
  easybuild/easyconfigs/i/impi/impi-2021.13.0-intel-compilers-2024.2.0.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.4-iimpi-2024.06.eb
Labels: update

#20879 use PyYAML 6.0.1 instead of 6.0 for recent ReFrame versions
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.2.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.3.eb
Labels: bug fix, EESSI

#20926 {numlib,toolchain,tools}[iimpi/2024.06,intel/2024.06,system/system] imkl-FFTW v2024.2.0, intel v2024.06, HPL v2.3
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2024.06.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2024.2.0-iimpi-2024.06.eb
  easybuild/easyconfigs/i/intel/intel-2024.06.eb
Labels: update, 2024a

#20953 {bio}[gfbf/2023a] PyBEL v0.15.5
  easybuild/easyconfigs/p/PyBEL/PyBEL-0.15.5-gfbf-2023a.eb
Labels: new

#20763 {data}[gfbf/2023b] xarray v2024.5.0
  easybuild/easyconfigs/x/xarray/xarray-2024.5.0-gfbf-2023b.eb
Labels: update

#20761 {devel}[GCCcore/13.2.0] makedepend v1.0.9
  easybuild/easyconfigs/m/makedepend/makedepend-1.0.9-GCCcore-13.2.0.eb
Labels: update

#20949 add patch to fix implicit function declaration in OpenMPI 4.1.4
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-12.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-NVHPC-22.7-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4_fix-implicit-cuda-function-declaration.patch
Labels: bug fix

#20865 {bio}[foss/2023a] medaka v1.12.0
  easybuild/easyconfigs/m/medaka/medaka-1.12.0-foss-2023a.eb
Labels: update

#20955 {bio}[gompi/2023a] IQ-TREE v2.3.5
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.3.5-gompi-2023a.eb
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.3.5_use_EB_LSD2.patch
Labels: update

#17820 {lib}[foss/2022b] pygmo v2.19.5, pagmo v2.19.0, tbb v2021.9.0 w/ Python 3.10.8
  easybuild/easyconfigs/p/pagmo/pagmo-2.19.0-gfbf-2022b.eb
  easybuild/easyconfigs/p/pygmo/pygmo-2.19.5-gfbf-2022b.eb
  easybuild/easyconfigs/t/tbb/tbb-2021.9.0-GCCcore-12.2.0.eb
Labels: update

#18100 {bio}[GCC/12.2.0] Bowtie v1.3.1
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.3.1-GCC-12.2.0.eb
Labels: update

#20958 disable auto-vectorizer (`-ftree-vectorize`) for OpenFOAM v10 + v11 when using toolchain that with GCC >= 11
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-foss-2022a-20230119-int64.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-foss-2022a-20230119.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-foss-2022a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-foss-2023a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-11-foss-2022a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-11-foss-2023a.eb
Labels: bug fix

#20882 {numlib,toolchain}[gmpflf/2024.06,gmpich/2024.06] gmpflf v2024.06, FFTW.MPI v3.3.10, ScaLAPACK v2.2.0
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gmpich-2024.06.eb
  easybuild/easyconfigs/g/gmpflf/gmpflf-2024.06.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-gmpflf-2024.06.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gmpich-2024.06-fb.eb
Labels: new, update

#20951 only use libxsmm as dependency for CP2K 2023.1 on x86_64
  easybuild/easyconfigs/c/CP2K/CP2K-2023.1-foss-2023a.eb
Labels: bug fix, aarch64

#20968 add RISC-V support to x264-20231019/GCCcore-13.2.0
  easybuild/easyconfigs/x/x264/x264-20231019-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/x264/x264-20231019_add-riscv-support.patch
Labels: enhancement, EESSI, riscv

#20116 {bio}[foss/2023a] Single-cell-python-bundle v2024.02
  easybuild/easyconfigs/c/cairomm/cairomm-1.16.2-GCC-12.3.0.eb
  easybuild/easyconfigs/g/gawk/gawk-5.3.0-GCC-12.3.0.eb
  easybuild/easyconfigs/g/graph-tool/graph-tool-2.59-foss-2023a.eb
  easybuild/easyconfigs/p/Pyomo/Pyomo-6.7.3-foss-2023a.eb
  easybuild/easyconfigs/s/Single-cell-python-bundle/Single-cell-python-bundle-2024.02-foss-2023a.eb
Labels: new

#20971 enable PIC in recent x265 easyconfigs to solve compilation errors on RISC-V
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-12.2.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-13.2.0.eb
Labels: enhancement, EESSI, riscv

#20934 {vis}[foss/2023a] napari-denoiseg v0.0.1
  easybuild/easyconfigs/n/napari-denoiseg/napari-denoiseg-0.0.1-foss-2023a.eb
Labels: new

#20790 {lib}[GCCcore/12.3.0] PretextMap v0.1.9
  easybuild/easyconfigs/p/PretextMap/PretextMap-0.1.9-GCCcore-12.3.0.eb
Labels: new

#20855 {bio}[GCC/12.3.0] SVDSS2 v2.0.0-alpha.3
  easybuild/easyconfigs/s/SVDSS2/SVDSS2-2.0.0-alpha.3-GCC-12.3.0.eb
Labels: new

#20907 {vis}[foss/2023a] scCustomize v2.1.2 w/ R 4.3.2
  easybuild/easyconfigs/s/scCustomize/scCustomize-2.1.2-foss-2023a-R-4.3.2.eb
Labels: new

#20916 {lib}[foss/2023a] rMATS-long v1.0.0-20240502 w/ R 4.3.2
  easybuild/easyconfigs/r/rMATS-long/rMATS-long-1.0.0-20240502-foss-2023a-R-4.3.2.eb
Labels: new

#20921 {geo}[gfbf/2023a] meteogrid v20240627 w/ R 4.3.2
  easybuild/easyconfigs/m/meteogrid/meteogrid-20240627-gfbf-2023a-R-4.3.2.eb
Labels: new

#20924 {bio}[GCCcore/12.3.0,foss/2023a] Trycycler v0.5.5, miniasm v0.3-20191007 w/ R 4.3.2
  easybuild/easyconfigs/m/miniasm/miniasm-0.3-20191007-GCCcore-12.3.0.eb
  easybuild/easyconfigs/t/Trycycler/Trycycler-0.5.5-foss-2023a-R-4.3.2.eb
Labels: update

#20963 whitelist ConfigureMakePythonPackage for sanity_check_paths CI check
  test/easyconfigs/easyconfigs.py
Labels: code cleanup

#20373 {tools}[foss/2023a] Ray-project v2.9.1
  easybuild/easyconfigs/r/Ray-project/Ray-project-2.9.1-foss-2023a.eb
Labels: update

#20967 {bio}[GCC/12.3.0] Bowtie v1.3.1
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.3.1-GCC-12.3.0.eb
Labels: update

#20954 {bio,devel}[GCCcore/13.2.0,foss/2023b] MultiQC v1.22.3, pydantic v2.7.4
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.22.3-foss-2023b.eb
  easybuild/easyconfigs/p/pydantic/pydantic-2.7.4-GCCcore-13.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#20975 {lang,tools}[GCCcore/13.3.0] Perl-bundle-CPAN v5.38.2, groff v1.23.0
  easybuild/easyconfigs/g/groff/groff-1.23.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb
Labels: update, 2024a

#20970 add RISC-v support to recent LAME easyconfigs by removing workaround for finding libncurses
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-13.2.0.eb
Labels: enhancement, EESSI, riscv

#20939 {math}[iimpi/2023b,intel/2023b] MUMPS v5.7.2, ParMETIS v4.0.3 w/ parmetis
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-intel-2023b-parmetis.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2023b.eb
Labels: update

#20976 {tools}[system/system] gh v2.52.0
  easybuild/easyconfigs/g/gh/gh-2.52.0.eb
Labels: update

#20977 {devel,vis}[GCCcore/13.3.0] X11 v20240607, intltool v0.51.0
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/X11/X11-20240607-GCCcore-13.3.0.eb
Labels: update

#20979 {vis}[GCCcore/13.3.0] Wayland v1.23.0
  easybuild/easyconfigs/w/Wayland/Wayland-1.23.0-GCCcore-13.3.0.eb
Labels: update

#20995 rename `gubbins-2.4.0.eb` to `Gubbins-2.4.0.eb`
  easybuild/easyconfigs/g/Gubbins/Gubbins-2.4.0.eb
Labels: bug fix

#21000 {lib}[GCCcore/13.3.0] LLVM v18.1.8, Mesa v24.1.3, ...
  easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.122-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.8.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-24.1.3-GCCcore-13.3.0.eb
Labels: update, 2024a

#20994 {vis}[gfbf/2023b] imageio v2.34.1
  easybuild/easyconfigs/i/imageio/imageio-2.34.1-gfbf-2023b.eb
Labels: update

#21006 {chem}[foss/2022a] ESIpy v20240709
  easybuild/easyconfigs/e/ESIpy/ESIpy-20240709-foss-2022a.eb
Labels: new

#20690 Add Extrae-4.2.0-gompi-2023b.eb
  easybuild/easyconfigs/e/Extrae/Extrae-4.2.0-debug_add_event.patch
  easybuild/easyconfigs/e/Extrae/Extrae-4.2.0-detect_binutils.patch
  easybuild/easyconfigs/e/Extrae/Extrae-4.2.0-fix-hw-counters-checks.patch
  easybuild/easyconfigs/e/Extrae/Extrae-4.2.0-gompi-2023b.eb
Labels: update

#20138 {chem} [foss/2023a + intel/2023a] QuantumESPRESSO 7.3.1 with cmake
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3.1-foss-2023a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3.1-intel-2023a.eb
Labels: update

#21010 {lib}[foss/2022a] GPflow v2.9.2 w/ CUDA 11.7.0
  easybuild/easyconfigs/g/GPflow/GPflow-2.9.2-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/g/GPflow/GPflow-2.9.2-foss-2022a.eb
Labels: new

#20824 {chem}[foss/2023a] RDKit v2024.03.3
  easybuild/easyconfigs/r/RDKit/RDKit-2024.03.3-foss-2023a.eb
Labels: update

#20878 {chem,devel,numlib}[GCCcore/13.2.0,foss/2023b,gompi/2023b] ESPResSo v4.2.2, Boost.MPI v1.83.0, Pint v0.24
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.83.0-gompi-2023b.eb
  easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.2-foss-2023b.eb
  easybuild/easyconfigs/p/Pint/Pint-0.24-GCCcore-13.2.0.eb
Labels: update

#21034 {chem}[foss/2023b] pyMBE v0.8.0
  easybuild/easyconfigs/p/pyMBE/pyMBE-0.8.0-foss-2023b.eb
Labels: new

#20070 Correct configuration of QuantumESPRESSO for 6.7/6.8/7.0/7.1/7.2/7.3
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-foss-2021a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-intel-2021a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8-foss-2021b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.8-intel-2021a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-foss-2021b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-intel-2021b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-foss-2022a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-intel-2022a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2022b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2023a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-intel-2022b.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3-foss-2023a.eb
Labels: enhancement

#21014 update homepage in phonopy easyconfigs
  easybuild/easyconfigs/p/phonopy/phonopy-2.12.0-foss-2020b.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.16.3-foss-2022a.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.20.0-foss-2023a.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.7.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.7.1-intel-2020a-Python-3.8.2.eb
Labels: bug fix

#21032 {bio}[gfbf/2023a] cyvcf2 v0.31.1
  easybuild/easyconfigs/c/cyvcf2/cyvcf2-0.31.1-gfbf-2023a.eb
Labels: update

#21025 {bio}[foss/2023b] Biopython v1.84
  easybuild/easyconfigs/b/Biopython/Biopython-1.84-foss-2023b.eb
Labels: update

#21013 {data,geo}[GCCcore/13.2.0,foss/2023b] ESMF v8.6.1, g2lib v3.2.0
  easybuild/easyconfigs/e/ESMF/ESMF-8.6.1-foss-2023b.eb
  easybuild/easyconfigs/g/g2lib/g2lib-3.2.0-GCCcore-13.2.0.eb
Labels: update

#20409 {tools}[foss/2023a] OpenAI-Gym v0.26.2, Arcade-Learning-Environment v0.8.1
  easybuild/easyconfigs/a/Arcade-Learning-Environment/Arcade-Learning-Environment-0.8.1-foss-2023a.eb
  easybuild/easyconfigs/o/OpenAI-Gym/OpenAI-Gym-0.26.2-foss-2023a.eb
Labels: update

#21035 remove ignored `toolchainopts` from `SYSTEM` toolchain easyconfigs
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4.eb
  easybuild/easyconfigs/l/libevent/libevent-2.1.12.eb
  easybuild/easyconfigs/l/libffi/libffi-3.2.1.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.0.eb
  easybuild/easyconfigs/n/ncurses/ncurses-5.9.eb
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.eb
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-3.eb
  easybuild/easyconfigs/p/Perl/Perl-5.38.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.12.eb
  easybuild/easyconfigs/z/zlib/zlib-1.2.13.eb
  easybuild/easyconfigs/z/zlib/zlib-1.3.1.eb
Labels: code cleanup

#20503 {tools}[GCCcore/12.2.0] fsm-lite v1.0, sdsl-lite v2.0.3
  easybuild/easyconfigs/f/fsm-lite/fsm-lite-1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/sdsl-lite/sdsl-lite-2.0.3-GCCcore-12.2.0.eb
Labels: new

#20898 {lang}[foss/2023b,gfbf/2023b] R v4.4.1, R-bundle-CRAN v2024.06
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
  easybuild/easyconfigs/r/R/R-4.4.1-gfbf-2023b.eb
Labels: update

#21054 {bio}[GCCcore/12.2.0] snpEff v5.2c w/ Java 11
  easybuild/easyconfigs/s/snpEff/snpEff-5.2c-GCCcore-12.2.0-Java-11.eb
Labels: update

#21055 {math}[foss/2022b] Platypus-Opt v1.2.0
  easybuild/easyconfigs/p/Platypus-Opt/Platypus-Opt-1.2.0-foss-2022b.eb
Labels: update

#20413 {bio}[GCCcore/12.2.0] Gubbins v3.3.5, rapidNJ v2.3.3, FastTree v2.1.11, ...
  easybuild/easyconfigs/a/Autoconf-archive/Autoconf-archive-2023.02.20-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/FastTree/FastTree-2.1.11-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/Gubbins/Gubbins-3.3.5-foss-2022b.eb
  easybuild/easyconfigs/m/multiprocess/multiprocess-0.70.15-gfbf-2022b.eb
  easybuild/easyconfigs/r/rapidNJ/rapidNJ-2.3.3-GCCcore-12.2.0.eb
Labels: new, update

#21086 {lang}[GCC/12.3.0,gfbf/2023a] RStudio-Server v2023.09.1+494, SOCI v4.0.3 w/ Java 11 R 4.3.2
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.09.1+494-gfbf-2023a-Java-11-R-4.3.2.eb
  easybuild/easyconfigs/s/SOCI/SOCI-4.0.3-GCC-12.3.0.eb
Labels: update

#21089 {tools}[GCCcore/13.3.0] parallel v20240722
  easybuild/easyconfigs/p/parallel/parallel-20240722-GCCcore-13.3.0.eb
Labels: update, 2024a

#21088 {vis}[GCCcore/13.3.0] GLib v2.80.4
  easybuild/easyconfigs/g/GLib/GLib-2.80.4-GCCcore-13.3.0.eb
Labels: update, 2024a

#21070 {bio}[foss/2022b] chewBBACA v3.3.9
  easybuild/easyconfigs/c/chewBBACA/chewBBACA-3.3.9-foss-2022b.eb
Labels: update

#21087 {bio,lib}[foss/2023a,gompi/2023a] nanopolish v0.14.0, VBZ-Compression v1.0.3
  easybuild/easyconfigs/n/nanopolish/nanopolish-0.14.0-foss-2023a.eb
  easybuild/easyconfigs/v/VBZ-Compression/VBZ-Compression-1.0.3-gompi-2023a.eb
Labels: update

#21081 {chem}[gfbf/2023b] spglib-python v2.5.0
  easybuild/easyconfigs/s/spglib-python/spglib-python-2.5.0-gfbf-2023b.eb
Labels: update

#21075 {devel,lib}[GCCcore/13.3.0] elfutils v0.191, libdwarf v0.10.1
  easybuild/easyconfigs/e/elfutils/elfutils-0.191-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libdwarf/libdwarf-0.10.1-GCCcore-13.3.0.eb
Labels: update, 2024a

#21077 {data}[GCCcore/13.3.0] BeautifulSoup v4.12.3
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.12.3-GCCcore-13.3.0.eb
Labels: update, 2024a

#21076 {lib}[GCCcore/13.3.0] gc v8.2.6, libunistring v1.2, Guile v3.0.10
  easybuild/easyconfigs/g/Guile/Guile-3.0.10-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/gc/gc-8.2.6-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libunistring/libunistring-1.2-GCCcore-13.3.0.eb
Labels: update, 2024a

#21060 {numlib}[GCC/12.3.0] beagle-lib v4.0.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-4.0.1-GCC-12.3.0-CUDA-12.1.1.eb
Labels: update

#20942 {lib}[GCCcore/12.3.0] Highway 1.0.4 fix for failing test on zen4
  easybuild/easyconfigs/h/Highway/Highway-1.0.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/h/Highway/Highway-1.0.4-zen4-fix-TruncateTo-bug.patch
Labels: bug fix
