Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-04, with the labels that each got.

#19814 {bio}[GCCcore/12.3.0] medaka v1.11.3, intervaltree-python v3.1.0
  easybuild/easyconfigs/i/intervaltree-python/intervaltree-python-3.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/medaka/medaka-1.11.3-foss-2023a.eb
Labels: update

#20257 adding easyconfigs: ParaView-5.12.0-foss-2023b.eb and Qt6-6.6.3-GCCcore
  easybuild/easyconfigs/a/assimp/assimp-5.3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-foss-2023b.eb
  easybuild/easyconfigs/q/Qt6/Qt6-6.6.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/q/Qt6/Qt6-6.6.3_fix_OF-Gentoo.patch
Labels: update

#19107 {lib}[GCCcore/12.2.0] nf-core v2.10, psycopg2 v2.9.9, pydantic v1.10.13, ...
  easybuild/easyconfigs/m/Markdown/Markdown-3.6-GCCcore-12.2.0.eb
  easybuild/easyconfigs/n/nf-core/nf-core-2.10-foss-2022b.eb
  easybuild/easyconfigs/p/prompt-toolkit/prompt-toolkit-3.0.36-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pytest-workflow/pytest-workflow-2.0.1-GCCcore-12.2.0.eb
Labels: update

#19622 {devel}[system/system] ant v1.10.14 w/ Java 21
  easybuild/easyconfigs/a/ant/ant-1.10.14-Java-21.eb
Labels: update

#19624 {devel}[system/system] Saxon-HE v12.4 w/ Java 21
  easybuild/easyconfigs/s/Saxon-HE/Saxon-HE-12.4-Java-21.eb
Labels: update

#19550 {bio,lib}[GCC/11.2.0,GCCcore/11.2.0] Clustal-Omega v1.2.4, argtable v2.13
  easybuild/easyconfigs/a/argtable/argtable-2.13-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/Clustal-Omega/Clustal-Omega-1.2.4-GCC-11.2.0.eb
Labels: update

#19681 {bio}[GCCcore/12.3.0] AreTomo2 v1.0.0 and MotionCor3 v1.0.1 w/CUDA 12.1.1
  easybuild/easyconfigs/a/AreTomo2/AreTomo2-1.0.0-GCCcore-12.3.0-CUDA-12.1.1.eb
  easybuild/easyconfigs/a/AreTomo2/AreTomo2-1.0.0_makefile.patch
  easybuild/easyconfigs/m/MotionCor3/MotionCor3-1.0.1-GCCcore-12.3.0-CUDA-12.1.1.eb
  easybuild/easyconfigs/m/MotionCor3/MotionCor3-1.0.1_makefile.patch
Labels: new

#19709 Add Java version 8u402b06
  easybuild/easyconfigs/j/Java/Java-8.402.eb
Labels: update

#19815 {bio}[foss/2023a] NGSpeciesID v0.3.0
  easybuild/easyconfigs/n/NGSpeciesID/NGSpeciesID-0.3.0-foss-2023a.eb
Labels: update

#20261 Update Java-8 wrapper to 8.402
  easybuild/easyconfigs/j/Java/Java-8.eb
Labels: update

#20260 add GCCcore-13.2.0_fix-unguarded-is_convertible-builtin.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0_fix-unguarded-is_convertible-builtin.patch
Labels: bug fix

#20205 Improve test for validity of easyconfig files
  test/easyconfigs/easyconfigs.py
Labels: enhancement, tests

#19807 {geo}[GCCcore/12.3.0,foss/2023a] geopy v2.4.1, contextily v1.5.0
  easybuild/easyconfigs/c/contextily/contextily-1.5.0-foss-2023a.eb
  easybuild/easyconfigs/g/geopy/geopy-2.4.1-GCCcore-12.3.0.eb
Labels: new, update

#20263 fix download for python-parasail 1.3.4 by adding missing source URL
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.3.4-foss-2023a.eb
Labels: bug fix

#20268 {lang}[system/system] Java v19.0.2, Java v19
  easybuild/easyconfigs/j/Java/Java-19.0.2.eb
  easybuild/easyconfigs/j/Java/Java-19.eb
Labels: update

#20080 {bio}[foss/2023a] pySCENIC v0.12.1-20240311
  easybuild/easyconfigs/p/pySCENIC/pySCENIC-0.12.1-20240311-foss-2023a.eb
Labels: update

#20276 update copyright lines to 2024
  setup.py
  test/__init__.py
  test/easyconfigs/easyconfigs.py
  test/easyconfigs/styletests.py
  test/easyconfigs/suite.py
Labels: update

#20096 {ai}[GCCcore/11.3.0] GKlib-METIS v5.1.1
  easybuild/easyconfigs/g/GKlib-METIS/GKlib-METIS-5.1.1-GCCcore-11.3.0.eb
Labels: new

#20264 {tools}[foss/2023a] Optuna v3.5.0
  easybuild/easyconfigs/g/Greenlet/Greenlet-3.0.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/Optuna/Optuna-3.5.0-foss-2023a.eb
  easybuild/easyconfigs/r/Redis/Redis-7.2.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/redis-py/redis-py-5.0.1-GCCcore-12.3.0.eb
Labels: update

#19654 {bio}[foss/2023a] AFNI v24.0.02
  easybuild/easyconfigs/a/AFNI/AFNI-24.0.02-foss-2023a.eb
Labels: update

#18853 {lib}[GCCcore/12.2.0,foss/2022b] PyTorch v1.13.1, cuDNN v8.5.0.96, magma v2.7.1, ... w/ CUDA 11.7.0
  easybuild/easyconfigs/c/cuDNN/cuDNN-8.5.0.96-CUDA-11.7.0.eb
  easybuild/easyconfigs/m/magma/magma-2.7.1-foss-2022b-CUDA-11.7.0.eb
  easybuild/easyconfigs/n/NCCL/NCCL-2.16.2-GCCcore-12.2.0-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1-foss-2022b-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_allow-GCC-12-for-CUDA-11.7.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.13.1_skip-test_find_unused_parameters-detail.patch
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.13.1-GCCcore-12.2.0-CUDA-11.7.0.eb
Labels: update

#19878 {bio}[foss/2022a] dorado v0.5.3 w/ CUDA 11.7.0
  easybuild/easyconfigs/d/dorado/dorado-0.5.3-foss-2022a-CUDA-11.7.0.eb
Labels: update

#20284 prepare release notes for EasyBuild v4.9.1 + bump version to 4.9.1
  RELEASE_NOTES
  setup.py
Labels: update, documentation

#20259 Remove dead dotNET codes.
  easybuild/easyconfigs/c/Canvas/Canvas-1.39.0.1598.eb
  easybuild/easyconfigs/d/dotNET-Core-Runtime/dotNET-Core-Runtime-5.0.17-GCCcore-10.3.0.eb
  easybuild/easyconfigs/d/dotNET-Core-Runtime/dotNET-Core-Runtime-6.0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/d/dotNET-SDK/dotNET-SDK-3.1.300-linux-x64.eb
  easybuild/easyconfigs/d/dotNET-SDK/dotNET-SDK-6.0.101-linux-x64.eb
  easybuild/easyconfigs/m/MSPC/MSPC-3.3.1.eb
  easybuild/easyconfigs/m/MaxQuant/MaxQuant-2.4.2.0.eb
  easybuild/easyconfigs/m/MetaMorpheus/MetaMorpheus-0.0.320-GCCcore-10.3.0.eb
  easybuild/easyconfigs/n/Net-core/Net-core-2.1.8.eb
  easybuild/easyconfigs/n/Net-core/Net-core-2.2.5.eb
  easybuild/easyconfigs/n/Net-core/Net-core-3.0.0.eb
Labels: code cleanup, EasyBuild-5.0

#20095 {bio}[foss/2022a] e3nn v0.3.3 w/ PyTorch 1.13.1 CUDA 11.7.0
  easybuild/easyconfigs/e/e3nn/e3nn-0.3.3-foss-2022a-PyTorch-1.13.1-CUDA-11.7.0.eb
Labels: update

#20299 {tools}[system/system] EasyBuild v4.9.1
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.9.1.eb
Labels: update

#20301 add alternate checksum to OpenMolcas v23.06
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-23.06-intel-2023a.eb
Labels: bug fix

#20300 replace incorrect scikit-bio 0.5.9 with scikit-bio 0.6.0 as dependency for scCODA
  easybuild/easyconfigs/b/biom-format/biom-format-2.1.15-foss-2023a.eb
  easybuild/easyconfigs/s/scCODA/scCODA-0.1.9-foss-2023a.eb
  easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.6.0-foss-2023a.eb
Labels: bug fix, update, change

#20313 sync with main + bump version to 4.9.2dev
  RELEASE_NOTES
  setup.py
Labels: update

#20297 update CellRanger
  easybuild/easyconfigs/c/CellRanger/CellRanger-8.0.0.eb
Labels: update

#20310 {bio}[GCC/12.2.0] KrakenUniq v1.0.4, Jellyfish v2.3.0
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-12.2.0.eb
  easybuild/easyconfigs/k/KrakenUniq/KrakenUniq-1.0.4-GCC-12.2.0.eb
Labels: update

#20308 {data}[gfbf/2023a] pyGAM v0.9.1
  easybuild/easyconfigs/p/pyGAM/pyGAM-0.9.1-gfbf-2023a.eb
Labels: new

#20290 {math}[GCCcore/12.3.0] Mesquite v2.3.0
  easybuild/easyconfigs/m/Mesquite/Mesquite-2.3.0-GCCcore-12.3.0.eb
Labels: update

#19980 {math,phys}[foss/2023a] deal.II v9.5.2, p4est v2.8.6
  easybuild/easyconfigs/d/deal.II/deal.II-9.5.2-foss-2023a.eb
  easybuild/easyconfigs/p/p4est/p4est-2.8.6-foss-2023a.eb
Labels: update

#20109 {bio,data,geo}[foss/2023a] Squidpy v1.4.1, PyGEOS v0.14, zarr v2.17.1
  easybuild/easyconfigs/p/PyGEOS/PyGEOS-0.14-gfbf-2023a.eb
  easybuild/easyconfigs/s/Squidpy/Squidpy-1.4.1-foss-2023a.eb
  easybuild/easyconfigs/z/zarr/zarr-2.17.1-foss-2023a.eb
Labels: update

#20281 assembly-stats/1.0.1-GCCcore-11.3.0
  easybuild/easyconfigs/a/assembly-stats/assembly-stats-1.0.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/assembly-stats/assembly-stats-1.0.1_fix_str_cast.patch
Labels: new

#20286 {chem}[gfbf/2023a] CREST v20240319
  easybuild/easyconfigs/c/CREST/CREST-20240319-gfbf-2023a.eb
Labels: update

#20289 {bio}[foss/2023a] Cassiopeia v2.0.0
  easybuild/easyconfigs/c/Cassiopeia/Cassiopeia-2.0.0-foss-2023a.eb
Labels: new

#20256 {lang}[system/system] dotNET-Core v6.0.420, dotNET-Core v8.0, dotNET-Core v8.0.203
  easybuild/easyconfigs/d/dotNET-Core/dotNET-Core-6.0.420.eb
  easybuild/easyconfigs/d/dotNET-Core/dotNET-Core-6.0.eb
  easybuild/easyconfigs/d/dotNET-Core/dotNET-Core-8.0.203.eb
  easybuild/easyconfigs/d/dotNET-Core/dotNET-Core-8.0.eb
Labels: new

#20258 {bio}[system/system] MetaMorpheus v1.0.5
  easybuild/easyconfigs/m/MetaMorpheus/MetaMorpheus-1.0.5.eb
Labels: update

#20330 {bio}[foss/2023a] PhyML v3.3.20220408
  easybuild/easyconfigs/p/PhyML/PhyML-3.3.20220408-foss-2023a.eb
  easybuild/easyconfigs/p/PhyML/PhyML-3.3.20220408_mcmc.c-fix.patch
Labels: update

#20331 BCFtools v1.19, HTSlib v1.19.1, SAMtools v1.19.2 for GCC/13.2.0
  easybuild/easyconfigs/b/BCFtools/BCFtools-1.19-GCC-13.2.0.eb
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.19.1-GCC-13.2.0.eb
  easybuild/easyconfigs/s/SAMtools/SAMtools-1.19.2-GCC-13.2.0.eb
Labels: update

#20334 {data}[foss/2023b] h5py-3.11.0
  easybuild/easyconfigs/h/h5py/h5py-3.11.0-foss-2023b.eb
Labels: update

#19954 {tools}[foss/2023a] ICON
  easybuild/easyconfigs/i/ICON/ICON-2024.01-foss-2023a.eb
  easybuild/easyconfigs/i/ICON/ICON-2024.01_lzacc-undefined.patch
  easybuild/easyconfigs/l/libfyaml/libfyaml-0.9-GCCcore-12.3.0.eb
Labels: new, update

#19987 {lib}[GCCcore/12.3.0] PyTorch-bundle v2.1.2, SoX v14.4.2, libmad v0.15.1b, ... w/ CUDA 12.1.1
  easybuild/easyconfigs/l/libmad/libmad-0.15.1b-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch-bundle/torch-ignite-0.4.13_dont_destroy_python_path_in_test_launcher.patch
  easybuild/easyconfigs/p/PyTorch-bundle/torchaudio-2.1.2_transform_test_tol.patch
  easybuild/easyconfigs/p/PyTorch-bundle/torchaudio-2.1.2_use-external-sox.patch
  easybuild/easyconfigs/p/PyTorch-bundle/torchtext-0.16.2_download-to-project-root.patch
  easybuild/easyconfigs/p/PyTorch-bundle/torchvision-0.16.2_ffmpeg-6.0-fix.patch
  easybuild/easyconfigs/p/PyTorch-bundle/torchvision-0.16.2_quantized_tol.patch
  easybuild/easyconfigs/s/SentencePiece/SentencePiece-0.2.0-GCC-12.3.0.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-12.3.0.eb
Labels: update

#20342 {bio}[foss/2022b] nanomath 1.3.0
  easybuild/easyconfigs/n/nanomath/nanomath-1.3.0-foss-2022b.eb
Labels: update

#20353 {lib}[foss/2022a] Optax v0.1.7, dm-haiku v0.0.9 w/ CUDA 11.7.0
  easybuild/easyconfigs/d/dm-haiku/dm-haiku-0.0.9-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/Optax/Optax-0.1.7-foss-2022a-CUDA-11.7.0.eb
Labels: update

#20303 {data}[iimpi/2023a] PnetCDF v1.13.0
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.13.0-iimpi-2023a.eb
Labels: update

#20293 {math}[GCCcore/13.2.0] CGAL v5.6.1, METIS v5.1.0, SCOTCH v7.0.4
  easybuild/easyconfigs/c/CGAL/CGAL-5.6.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.4-gompi-2023b.eb
Labels: update

#20292 {numlib}[GCC/13.2.0] LAPACK v3.12.0
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.12.0-GCC-13.2.0.eb
Labels: update

#20355 {bio,tools}[GCC/13.2.0] STAR v2.7.11b, xxd v9.1.0307
  easybuild/easyconfigs/s/STAR/STAR-2.7.11b-GCC-13.2.0.eb
  easybuild/easyconfigs/x/xxd/xxd-9.1.0307-GCCcore-13.2.0.eb
Labels: update

#20347 {cae}[GCCcore/12.3.0,system/system] MATSim v15.0 w/ Java 17
  easybuild/easyconfigs/m/MATSim/MATSim-15.0-GCCcore-12.3.0-Java-17.eb
  easybuild/easyconfigs/m/MATSim/MATSim-15.0-Java-17.eb
Labels: update

#20352 {lib}[GCCcore/12.3.0] attrdict3 v2.0.2
  easybuild/easyconfigs/a/attrdict3/attrdict3-2.0.2-GCCcore-12.3.0.eb
Labels: update

#20328 {vis}[GCC/12.3.0] POV-Ray v3.7.0.10
  easybuild/easyconfigs/p/POV-Ray/POV-Ray-3.7.0.10-GCC-12.3.0.eb
Labels: update

#19866 {math}[foss/2023a] gmsh v4.12.2
  easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023a.eb
Labels: update

#20368 {chem}[foss/2022b] VAMPIRE-ASM v6.0
  easybuild/easyconfigs/v/VAMPIRE-ASM/VAMPIRE-ASM-6.0-foss-2022b.eb
Labels: new

#20321 {chem,math}[gomkl/2023a] FDMNES v2024-02-29, MUMPS v5.6.2 w/ metis seq
  easybuild/easyconfigs/f/FDMNES/FDMNES-2024-02-29-gomkl-2023a.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-gomkl-2023a-metis-seq.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.2_shared-pord.patch
  test/easyconfigs/easyconfigs.py
Labels: new, update

#20344 {vis}[foss/2023b] Giza v1.4.1
  easybuild/easyconfigs/g/Giza/Giza-1.4.1-GCCcore-13.2.0.eb
Labels: update

#20278 {lib}[GCCcore/12.3.0] orthAgogue v20141105, cmph v2.0, tbb v2020.3
  easybuild/easyconfigs/c/cmph/cmph-2.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/orthAgogue/orthAgogue-20141105-gompi-2023a.eb
  easybuild/easyconfigs/t/tbb/tbb-2020.3-GCCcore-12.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#20367 {bio}[foss/2023a] WGDgc v1.3 w/ R 4.3.2
  easybuild/easyconfigs/w/WGDgc/WGDgc-1.3-foss-2023a-R-4.3.2.eb
Labels: new

#20312 {astro}[intel/2022a] astropy v5.1.1, plc v3.10
  easybuild/easyconfigs/a/astropy/astropy-5.1.1-intel-2022a.eb
  easybuild/easyconfigs/p/plc/plc-3.10-intel-2022a.eb
Labels: update

#20013 {lib}[foss/2023a] PyTorch-Geometric v2.5.0 w/ PyTorch 2.1.2 CUDA 12.1.1
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-2.5.0-foss-2023a-PyTorch-2.1.2-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch-Geometric/plyfile-1.0.3_use_pdm_backend.patch
  easybuild/easyconfigs/y/YACS/YACS-0.1.8-GCCcore-12.3.0.eb
Labels: update

#20255 {lib}[GCCcore/12.3.0,foss/2023a] AMGX v2.4.0, CCCL v2.3.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/a/AMGX/AMGX-2.4.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/a/AMGX/AMGX-2.4.0_external-thrust.patch
  easybuild/easyconfigs/a/AMGX/AMGX-2.4.0_fix-openmp-linking.patch
  easybuild/easyconfigs/c/CCCL/CCCL-2.3.0-GCCcore-12.3.0-CUDA-12.1.1.eb
Labels: new

#20324 change arrow-R dependency of Bioconductor v3.18 to v14.0.1 (which depends on required matching Arrow v14.0.1)
  easybuild/easyconfigs/a/arrow-R/arrow-R-11.0.0.3-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/a/arrow-R/arrow-R-14.0.1-foss-2023a-R-4.3.2.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb
Labels: bug fix, change, EESSI

#20378 add patch to fix hardcoded `/bin/mv` path in Rhdf5lib extension included in R-bundle-Bioconductor v3.16 + v3.18
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/Rhdf5lib-1.20.0_fix_hardcoded_path_to_mv.patch
Labels: bug fix, EESSI

#20288 {chem}[gfbf/2023a] xtb v6.7.0
  easybuild/easyconfigs/x/xtb/xtb-6.7.0-gfbf-2023a.eb
Labels: update

#20348 {lib}[GCCcore/12.3.0] premailer v3.10.0
  easybuild/easyconfigs/p/premailer/premailer-3.10.0-GCCcore-12.3.0.eb
Labels: new

#20381 {data}[foss/2023a] PyTables v3.8.0
  easybuild/easyconfigs/p/PyTables/PyTables-3.8.0-foss-2023a.eb
Labels: update

#20383 {bio}[foss/2023a] pybedtools v0.9.1
  easybuild/easyconfigs/p/pybedtools/pybedtools-0.9.1-foss-2023a.eb
Labels: update

#20115 {bio}[foss/2023a] CellRank v2.0.2
  easybuild/easyconfigs/c/CellRank/CellRank-2.0.2-foss-2023a.eb
Labels: update

#20351 {devel}[gfbf/2023a] ONNX v1.15.0
  easybuild/easyconfigs/o/ONNX/ONNX-1.15.0-gfbf-2023a.eb
Labels: update

#20386 make sure that libjpeg-turbo libraries are installed in 'lib' subdirectory
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.4-GCCcore-9.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.6-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.1.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.1.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.1.5.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-3.0.1-GCCcore-13.2.0.eb
Labels: bug fix, change

#20393 {tools}[GCCcore/12.3.0] nvtop v3.1.0
  easybuild/easyconfigs/n/nvtop/nvtop-3.1.0-GCCcore-12.3.0.eb
Labels: update

#20309 {phys}[system/system] AEDT v2024R1
  easybuild/easyconfigs/a/AEDT/AEDT-2024R1.eb
Labels: new

#20372 {data}[gfbf/2023a] RPostgreSQL v0.7-6
  easybuild/easyconfigs/r/RPostgreSQL/RPostgreSQL-0.7-6-gfbf-2023a.eb
Labels: update

#20390 {tools}[GCCcore/13.2.0] parallel v20240322
  easybuild/easyconfigs/p/parallel/parallel-20240322-GCCcore-13.2.0.eb
Labels: update

#20377 {bio}[gompi/2022b] HISAT2 v2.2.1, SRA-Toolkit v3.0.5, file v5.43
  easybuild/easyconfigs/f/file/file-5.43-GCCcore-12.2.0.eb
  easybuild/easyconfigs/h/HISAT2/HISAT2-2.2.1-gompi-2022b.eb
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-3.0.5-gompi-2022b.eb
Labels: update

#20376 {bio}[gompi/2022b] kallisto v0.50.1
  easybuild/easyconfigs/k/kallisto/kallisto-0.50.1-gompi-2022b.eb
Labels: update

#20396 add patch for Libint 2.7.2 to fix compiler error with glibc >= 2.34
  easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-11.3.0-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-12.2.0-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-12.3.0-lmax-6-cp2k.eb
  easybuild/easyconfigs/l/Libint/Libint-2.7.2_update-catch-hpp-fix-MINSIGSTKSZ.patch
Labels: bug fix

#18811 {tools}[GCC/12.3.0] likwid v5.2.2
  easybuild/easyconfigs/l/likwid/likwid-5.2.2-GCC-12.3.0.eb
Labels: update

#20379 remove dependency on HDF5 in recent Bioconductor easyconfigs
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.13-foss-2021a-R-4.1.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.14-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2021b-R-4.2.0.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2022a-R-4.2.1.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb
Labels: bug fix, change

#20389 add hatch-requirements-txt extension to hatchling easyconfigs
  easybuild/easyconfigs/h/hatchling/hatchling-1.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/h/hatchling/hatchling-1.18.0-GCCcore-13.2.0.eb
Labels: enhancement, change

#20397 {tools}[GCC/13.2.0] likwid v5.3.0
  easybuild/easyconfigs/l/likwid/likwid-5.3.0-GCC-13.2.0.eb
Labels: update

#20307 {lib,math,vis}[foss/2022a] EasyMocap v0.2, freetype-py v2.4.0, PortAudio v19.7.0
  easybuild/easyconfigs/e/EasyMocap/EasyMocap-0.2-foss-2022a.eb
  easybuild/easyconfigs/f/freetype-py/freetype-py-2.4.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PortAudio/PortAudio-19.7.0-foss-2022a.eb
Labels: new, update

#20382 {ai}[foss/2023a] PyTorch-bundle v2.1.2
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a.eb
Labels: update

#20391 add missing (optional) dependency pyproject-metadata to scikit-build-core
  easybuild/easyconfigs/s/scikit-build-core/scikit-build-core-0.5.0-GCCcore-12.3.0.eb
Labels: enhancement

#20371 {bio}[intel/2023a] CAMPARI v4.0
  easybuild/easyconfigs/c/CAMPARI/CAMPARI-4.0-intel-2023a.eb
Labels: update

#20341 {bio}[foss/2022b] nanoget 1.18.1
  easybuild/easyconfigs/n/nanoget/nanoget-1.18.1-foss-2022b.eb
Labels: update

#19983 {tools}[gfbf/2023a] PyEXR v0.3.10
  easybuild/easyconfigs/p/PyEXR/OpenEXR-1.3.9_fix-openexr-inc-lib-searching.patch
  easybuild/easyconfigs/p/PyEXR/PyEXR-0.3.10-gfbf-2023a.eb
Labels: new

#20068 {bio}[gompi/2022a] HyPhy v2.5.60
  easybuild/easyconfigs/h/HyPhy/HyPhy-2.5.60-gompi-2022a.eb
Labels: update

#20040 [system] fgbio 2.2.1
  easybuild/easyconfigs/f/fgbio/fgbio-2.2.1-Java-8.eb
  easybuild/easyconfigs/s/sbt/sbt-1.3.13-Java-8.eb
  easybuild/easyconfigs/s/sbt/sbt-1.6.2-Java-8.eb
Labels: update

#20401 {devel,phys,vis}[GCCcore/12.3.0] MuJoCo v3.1.4, glew v2.2.0, GLFW v3.4 w/ osmesa
  easybuild/easyconfigs/g/GLFW/GLFW-3.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-12.3.0-osmesa.eb
  easybuild/easyconfigs/m/MuJoCo/MuJoCo-3.1.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/python-mujoco/python-mujoco-3.1.4-foss-2023a.eb
  easybuild/easyconfigs/p/python-mujoco/python-mujoco-3.1.4_use_eb_deps.patch
Labels: update

#20412 {lib,tools}[GCCcore/12.2.0] subunit v1.4.3, Check v0.15.2, CppUnit v1.15.1
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/subunit/subunit-1.4.3-GCCcore-12.2.0.eb
Labels: new, update

#20410 {bio}[GCC/12.2.0,gompi/2022b] RAxML v8.2.12, RAxML-NG v1.2.0 w/ avx2
  easybuild/easyconfigs/r/RAxML-NG/RAxML-NG-1.2.0-GCC-12.2.0.eb
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.12-gompi-2022b-avx2.eb
Labels: update

#20357 {phys}[GCCcore/12.3.0] PyAEDT v0.8.7
  easybuild/easyconfigs/p/PyAEDT/PyAEDT-0.8.7-GCCcore-12.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#20415 {devel}[system/system] VSCode v1.88.1
  easybuild/easyconfigs/v/VSCode/VSCode-1.88.1.eb
Labels: update

#20343 {math}[foss/2022b] pauvre v0.2.3
  easybuild/easyconfigs/p/pauvre/pauvre-0.2.3-foss-2022b.eb
Labels: update

#20426 {math}[foss/2023a] pauvre v0.2.3
  easybuild/easyconfigs/p/pauvre/pauvre-0.2.3-foss-2023a.eb
Labels: update

#20429 add RISC-V support to UCX 1.15.0
  easybuild/easyconfigs/u/UCX/UCX-1.15.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.15.0-add_riscv_support.patch
Labels: enhancement, EESSI, riscv

#20432 add RISC-V support to UCC 1.2.0
  easybuild/easyconfigs/u/UCC/UCC-1.2.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/UCC/UCC-1.2.0_add-riscv-support.patch
Labels: enhancement, EESSI, riscv

#20445 add cmna extension to R-bundle-CRAN v2023.12
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
Labels: enhancement

#20439 add patch for GROMACS 2024.1 to fix filesystem race in tests
  easybuild/easyconfigs/g/GROMACS/GROMACS-2024.1-foss-2023b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2024.1_fix-tests-filesystem-race.patch
Labels: bug fix
