Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-03, with the labels that each got.

#19989 {lib,tools}[GCCcore/12.3.0] python-xxhash v3.4.1, xxHash v0.8.2
  easybuild/easyconfigs/p/python-xxhash/python-xxhash-3.4.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/xxHash/xxHash-0.8.2-GCCcore-12.3.0.eb
Labels: update

#20003 Fix Clang 9.0.1 patch
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/c/Clang/Clang-9.0.1-GCCcore-9.3.0.eb
  easybuild/easyconfigs/c/Clang/libcxx-9.0.1-ppc64le.patch
Labels: bug fix

#20008 unpack SCG database to 'db' subdirectory for DAS_Tool
  easybuild/easyconfigs/d/DAS_Tool/DAS_Tool-1.1.1-foss-2021b-R-4.1.2.eb
  easybuild/easyconfigs/d/DAS_Tool/DAS_Tool-1.1.3-foss-2021a-R-4.1.0.eb
Labels: bug fix

#19981 {lib}[foss/2023a] CellTypist v1.6.2, igraph v0.10.10, python-igraph v0.11.4, leidenalg v0.10.2, libleidenalg v0.11.0
  easybuild/easyconfigs/c/CellTypist/CellTypist-1.6.2-foss-2023a.eb
  easybuild/easyconfigs/i/igraph/igraph-0.10.10-foss-2023a.eb
  easybuild/easyconfigs/l/leidenalg/leidenalg-0.10.2-foss-2023a.eb
  easybuild/easyconfigs/l/libleidenalg/libleidenalg-0.11.1-foss-2023a.eb
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.11.4-foss-2023a.eb
Labels: update

#19994 {data}[foss/2023a] scib v1.1.4, pyparsing v3.1.1, pydot v2.0.0, Deprecated 1.2.14, scikit-misc v0.3.1
  easybuild/easyconfigs/d/Deprecated/Deprecated-1.2.14-foss-2023a.eb
  easybuild/easyconfigs/p/pydot/pydot-2.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pyparsing/pyparsing-3.1.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/scib/scib-1.1.4-foss-2023a.eb
  easybuild/easyconfigs/s/scikit-misc/scikit-misc-0.3.1-foss-2023a.eb
Labels: update

#20012 {lib}[GCCcore/12.3.0] PDM v2.12.4
  easybuild/easyconfigs/p/PDM/PDM-2.12.4-GCCcore-12.3.0.eb
Labels: new

#20007 {vis}[GCCcore/12.3.0] PyOpenGL v3.1.7: add PyOpenGL-accelerate extension
  easybuild/easyconfigs/p/PyOpenGL/PyOpenGL-3.1.7-GCCcore-12.3.0.eb
Labels: enhancement

#20016 use system architecture template in GDGraph
  easybuild/easyconfigs/g/GDGraph/GDGraph-1.56-GCCcore-11.3.0.eb
Labels: enhancement, aarch64

#20015 use system architecture template in GD
  easybuild/easyconfigs/g/GD/GD-2.71-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GD/GD-2.73-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GD/GD-2.75-GCCcore-11.3.0.eb
Labels: enhancement, aarch64

#20014 use system architecture template in DB_File
  easybuild/easyconfigs/d/DB_File/DB_File-1.835-GCCcore-9.3.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.855-GCCcore-10.2.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.856-GCCcore-10.3.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.857-GCCcore-11.2.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.858-GCCcore-11.3.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.859-GCCcore-12.3.0.eb
Labels: enhancement, aarch64

#20018 update homepage and source_urls for SPAdes
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.13.0-GCC-10.3.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.14.1-GCC-9.3.0-Python-3.8.2.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.2-GCC-10.2.0-Python-2.7.18.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.2-GCC-10.2.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.3-GCC-10.3.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.3-GCC-11.2.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.4-GCC-12.2.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.4-GCC-12.3.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.5-GCC-11.3.0.eb
Labels: bug fix

#20011 Add AMOS dependency to let 'toAmos' and 'minimus2' works
  easybuild/easyconfigs/a/AMOS/AMOS-3.1.0-foss-2023a.eb
  easybuild/easyconfigs/c/Circlator/Circlator-1.5.5-foss-2023a.eb
Labels: enhancement, update

#19997 {lang,tools}[GCC/11.3.0] OCaml v4.14.0, snape-pooled v20150707
  easybuild/easyconfigs/o/OCaml/OCaml-4.14.0-GCC-11.3.0.eb
  easybuild/easyconfigs/s/SNAPE-pooled/SNAPE-pooled-20150707-GCC-11.3.0.eb
Labels: update

#20023 remove easyconfig for zlib 1.3 w/ intel toolchain, should be using GCCcore
  easybuild/easyconfigs/z/zlib/zlib-1.3-intel-2023a.eb
Labels: bug fix, change

#20027 Fix GDAL 3.5.0 install on high-core-count machines
  easybuild/easyconfigs/g/GDAL/GDAL-3.5.0-foss-2022a.eb
Labels: bug fix

#20024 fix source URL for xpdf 4.04
  easybuild/easyconfigs/x/xpdf/xpdf-4.04-GCCcore-12.3.0.eb
Labels: bug fix

#20028 Remove disable-visibility configure flag from GTK3
  easybuild/easyconfigs/g/GTK+/GTK+-3.22.30-fosscuda-2018b.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.13-GCCcore-8.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.17-GCCcore-9.3.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.23-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/GTK+/GTK+-3.24.8-GCCcore-8.2.0.eb
  easybuild/easyconfigs/g/GTK3/GTK3-3.24.29-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GTK3/GTK3-3.24.31-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/GTK3/GTK3-3.24.33-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GTK3/GTK3-3.24.35-GCCcore-12.2.0.eb
Labels: bug fix

#20033 Remove unknown configure option from HDF-EOS2-3.0
  easybuild/easyconfigs/h/HDF-EOS2/HDF-EOS2-3.0-GCCcore-11.3.0.eb
Labels: bug fix

#20042 gcsfs v2023.12.2.post1: move poetry to builddeps and bump poetry version
  easybuild/easyconfigs/g/gcsfs/gcsfs-2023.12.2.post1-foss-2023a.eb
Labels: bug fix

#20041 Remove hdf5 configure option from MDSplus 7.96.12
  easybuild/easyconfigs/m/MDSplus/MDSplus-7.96.12-GCCcore-9.3.0.eb
Labels: bug fix

#20043 Fix python configure option of MEME
  easybuild/easyconfigs/m/MEME/MEME-5.1.1-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/m/MEME/MEME-5.1.1-foss-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/MEME/MEME-5.1.1-intel-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/m/MEME/MEME-5.4.1-GCC-10.3.0.eb
Labels: bug fix

#20039 fgbio 1.3.0 fix: invocation typo and unneeded folder change on invocation
  easybuild/easyconfigs/f/fgbio/fgbio-1.3.0.eb
Labels: bug fix

#20037 {lib}[GCCcore/12.3.0] python-irodsclient v2.0.0
  easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-2.0.0-GCCcore-12.3.0.eb
Labels: update

#19811 {bio}[system/system] MSFragger v4.0 w/ Java 11
  easybuild/easyconfigs/m/MSFragger/MSFragger-4.0-Java-11.eb
Labels: new

#19812 {bio}[system/system] IonQuant v1.10.12 w/ Java 11
  easybuild/easyconfigs/i/IonQuant/IonQuant-1.10.12-Java-11.eb
Labels: new

#19792 {data}[gompi/2023b] CDO v2.2.2, UDUNITS v2.2.28 , PROJ v9.3.1, ecCodes v2.31.0 , libaec v1.0.6, nlohmann_json v3.11.3, pkgconfig v1.5.5
  easybuild/easyconfigs/c/CDO/CDO-2.2.2-gompi-2023b.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.31.0-gompi-2023b.eb
  easybuild/easyconfigs/l/libaec/libaec-1.0.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/nlohmann_json/nlohmann_json-3.11.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PROJ/PROJ-9.3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.5.5-GCCcore-13.2.0-python.eb
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28-GCCcore-13.2.0.eb
Labels: update

#20066 {devel}[GCCcore/13.2.0] SCons v4.6.0
  easybuild/easyconfigs/s/SCons/SCons-4.6.0-GCCcore-13.2.0.eb
Labels: update

#20065 Remove unknown configure option from GnuTLS 3.7.2
  easybuild/easyconfigs/g/GnuTLS/GnuTLS-3.7.2-GCCcore-10.3.0.eb
Labels: bug fix

#20046 {devel}[GCCcore/13.2.0] libgit2 v1.7.2
  easybuild/easyconfigs/l/libgit2/libgit2-1.7.2-GCCcore-13.2.0.eb
Labels: update

#20056 find the correct Python in xtensor
  easybuild/easyconfigs/x/xtensor/xtensor-0.24.0-foss-2021b.eb
Labels: bug fix

#20054 {tools}[system/system] iperf v3.16
  easybuild/easyconfigs/i/iperf/iperf-3.16.eb
Labels: update

#20053 {tools}[GCCcore/12.3.0] fio v3.36
  easybuild/easyconfigs/f/fio/fio-3.36-GCCcore-12.3.0.eb
Labels: update

#20048 {vis}[gfbf/2023a] noise v1.2.2
  easybuild/easyconfigs/n/noise/noise-1.2.2-gfbf-2023a.eb
Labels: new

#20067 {bio}[foss/2023a] scCODA v0.1.9, rpy2 v3.5.15, scikit-bio v0.5.9, ...
  easybuild/easyconfigs/r/rpy2/rpy2-3.5.15-foss-2023a.eb
  easybuild/easyconfigs/s/scCODA/scCODA-0.1.9-foss-2023a.eb
  easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.5.9-foss-2023a.eb
  easybuild/easyconfigs/t/tensorflow-probability/tensorflow-probability-0.20.0-foss-2023a.eb
Labels: update

#19986 {lib}[GCCcore/12.3.0,gfbf/2023a] multiprocess v0.70.15
  easybuild/easyconfigs/m/multiprocess/multiprocess-0.70.15-gfbf-2023a.eb
Labels: update

#20071 {chem}[intel/2022a] DFT-D4 v3.6.0
  easybuild/easyconfigs/d/DFT-D4/DFT-D4-3.6.0-intel-2022a.eb
  easybuild/easyconfigs/m/multicharge/multicharge-0.2.0-iimkl-2022a.eb
Labels: update

#20063 fix GUIDANCE installation
  easybuild/easyconfigs/g/GUIDANCE/GUIDANCE-2.02-GCC-12.3.0.eb
Labels: bug fix

#20061 Fix configure option and gpertools dependency of MIRA 5.0
  easybuild/easyconfigs/m/MIRA/MIRA-5.0rc2-foss-2020b.eb
Labels: bug fix

#19710 {lang}[system/system] Java v21.0.2
  easybuild/easyconfigs/j/Java/Java-21.0.2.eb
Labels: update

#20074 {toolchain}[system/system] iimkl v2023b
  easybuild/easyconfigs/i/iimkl/iimkl-2023b.eb
Labels: update

#19798 {devel}[foss/2023b,intel/2023b] buildenv vdefault
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2023b.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-intel-2023b.eb
Labels: update, 2023a

#20078 {lang}[system/system] Java v21.0.2, Java v21
  easybuild/easyconfigs/j/Java/Java-21.0.2.eb
  easybuild/easyconfigs/j/Java/Java-21.eb
Labels: update

#19840 {astro,lib}[foss/2023b] DP3-6.0, WSClean 3.4 and deps
  easybuild/easyconfigs/a/AOFlagger/AOFlagger-3.4.0-foss-2023b.eb
  easybuild/easyconfigs/a/Armadillo/Armadillo-12.8.0-foss-2023b.eb
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.9.0-foss-2023b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.83.0-GCC-13.2.0.eb
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-4.3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/casacore/casacore-3.5.0-add-C-style-header-for-GCC-13.1.patch
  easybuild/easyconfigs/c/casacore/casacore-3.5.0-foss-2023b.eb
  easybuild/easyconfigs/d/DP3/DP3-6.0-foss-2023b.eb
  easybuild/easyconfigs/d/DP3/DP3-6.0_fix-for-xsimd-error-on-neoverse-v1.patch
  easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.5.2-foss-2023b.eb
  easybuild/easyconfigs/i/IDG/IDG-1.2.0-foss-2023b.eb
  easybuild/easyconfigs/i/IDG/IDG-1.2.0_fix-for-xsimd-error-on-neoverse-v1.patch
  easybuild/easyconfigs/l/Lua/Lua-5.4.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PCRE/PCRE-8.45-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PGPLOT/PGPLOT-5.2.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/w/WCSLIB/WCSLIB-7.11-GCC-13.2.0.eb
  easybuild/easyconfigs/w/WSClean/WSClean-3.4-foss-2023b.eb
  easybuild/easyconfigs/w/wget/wget-1.21.4-GCCcore-13.2.0.eb
Labels: update, EESSI

#20062 Fix confgure options in GRASS
  easybuild/easyconfigs/g/GRASS/GRASS-7.8.3-fosscuda-2019b-Python-3.7.4.eb
  easybuild/easyconfigs/g/GRASS/GRASS-8.2.0-foss-2021b.eb
Labels: bug fix

#20047 {lang}[gfbf/2023b] R v4.3.3
  easybuild/easyconfigs/r/R/R-4.3.3-gfbf-2023b.eb
Labels: update

#20090 add patch to fix failing tests with OpenSSL 3.x for Net-SSLeay v1.92 extension in Perl-bundle-CPAN v5.36.1
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Net-SSLeay-1.92_fix.patch
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
Labels: bug fix

#20088 {bio}[GCC/12.3.0] STAR v2.7.11b
  easybuild/easyconfigs/s/STAR/STAR-2.7.11b-GCC-12.3.0.eb
Labels: update

#20083 find correct Python for MDI
  easybuild/easyconfigs/m/MDI/MDI-1.4.16-gompi-2022b.eb
  easybuild/easyconfigs/m/MDI/MDI-1.4.26-gompi-2023a.eb
Labels: bug fix

#20055 add fixest with deps to R-bundle-CRAN
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
Labels: new

#20069 Add support for Vulkan software rendering in Mesa v23.1.9
  easybuild/easyconfigs/m/Mesa/Mesa-23.1.9-GCCcore-13.2.0.eb
Labels: enhancement

#20052 Fix configure options of FFLAS-FFPACK
  easybuild/easyconfigs/f/FFLAS-FFPACK/FFLAS-FFPACK-2.2.0-foss-2016a.eb
  easybuild/easyconfigs/f/FFLAS-FFPACK/FFLAS-FFPACK-2.5.0-gfbf-2022a.eb
Labels: bug fix

#20101 {lang}[system/system] Anaconda3 version 2024.02-1
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2024.02-1.eb
Labels: update

#20110 {lib}[system/system] cuTENSOR v2.0.1.2 w/ CUDA 12.2.2
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-2.0.1.2-CUDA-12.2.2.eb
Labels: update

#20104 {lib}[foss/2023b] HeFFTe v2.4.0
  easybuild/easyconfigs/h/HeFFTe/HeFFTe-2.4.0-foss-2023b.eb
Labels: update

#20057 Fix geotiff configure option in GDAL 2.2.3
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018a-Python-3.6.4.eb
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018b-Python-2.7.15.eb
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018b-Python-3.6.6.eb
  easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-intel-2018b-Python-3.6.6.eb
Labels: bug fix

#19859 {lib}[GCCcore/13.2.0] MATIO v1.5.26
  easybuild/easyconfigs/m/MATIO/MATIO-1.5.26-GCCcore-13.2.0.eb
Labels: update

#19605 {tools}[GCCcore/12.3.0] ccache v4.9
  easybuild/easyconfigs/c/ccache/ccache-4.9-GCCcore-12.3.0.eb
Labels: update

#19648 {lib}[foss/2023a] PyTorch-Lightning v2.2.1, deepdiff v6.7.1, tensorboardX v2.6.2.2
  easybuild/easyconfigs/d/deepdiff/deepdiff-6.7.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-2.2.1-foss-2023a.eb
  easybuild/easyconfigs/t/tensorboardX/tensorboardX-2.6.2.2-foss-2023a.eb
Labels: update

#20111 {bio}[foss/2023a] infercnvpy v0.4.3
  easybuild/easyconfigs/i/infercnvpy/infercnvpy-0.4.3-foss-2023a.eb
Labels: update

#20094 {lib}[GCC/11.3.0] DMLC-Core v0.5
  easybuild/easyconfigs/d/DMLC-Core/DMLC-Core-0.5-GCC-11.3.0.eb
Labels: update

#20034 Remove mpi configure option from libfdf 0.2.2
  easybuild/easyconfigs/l/libfdf/libfdf-0.2.2-GCC-10.2.0-serial.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.2.2-GCC-10.3.0-serial.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.2.2-GCC-11.2.0-serial.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.2.2-iccifort-2020.4.304-serial.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.2.2-intel-compilers-2021.2.0-serial.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.2.2-intel-compilers-2021.4.0-serial.eb
Labels: bug fix

#20025 {bio}[foss/2023a] epiScanpy v0.4.0
  easybuild/easyconfigs/e/epiScanpy/epiScanpy-0.4.0-foss-2023a.eb
Labels: update

#20044 {lib}[GCCcore/12.3.0] Parallel-Hashmap v1.3.12
  easybuild/easyconfigs/p/Parallel-Hashmap/Parallel-Hashmap-1.3.12-GCCcore-12.3.0.eb
Labels: update

#20114 add patches for minimus2 in AMOS-3.1.0
  easybuild/easyconfigs/a/AMOS/AMOS-3.1.0-foss-2023a.eb
  easybuild/easyconfigs/a/AMOS/AMOS-3.1.0_fix_deprecated_maxmatch-flag.patch
  easybuild/easyconfigs/a/AMOS/AMOS-3.1.0_link_correctly_to_DELTAFILER_SHOWCOORDS.patch
Labels: bug fix

#20118 add patch to fix failing tests with OpenSSL 3.x for Net-SSLeay v1.92 extension in Perl-bundle-CPAN v5.36.1
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb
Labels: bug fix

#20120 {bio}[GCC/13.2.0] DIAMOND v2.1.9
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.1.9-GCC-13.2.0.eb
Labels: update

#20123 {bio}[foss/2023b] MetaDecoder v1.0.19
  easybuild/easyconfigs/m/MetaDecoder/MetaDecoder-1.0.19-foss-2023b.eb
Labels: new

#20002 {bio}[foss/2023a] scVelo v0.3.1, loompy v3.0.7
  easybuild/easyconfigs/l/loompy/loompy-3.0.7-foss-2023a.eb
  easybuild/easyconfigs/s/scVelo/scVelo-0.3.1-foss-2023a.eb
  easybuild/easyconfigs/s/scVelo/scVelo-0.3.1_dep-fix.patch
Labels: update

#20087 {ai}[foss/2022a] denseweight v0.1.2
  easybuild/easyconfigs/d/denseweight/denseweight-0.1.2-foss-2022a.eb
Labels: new

#20124 {bio}[foss/2023a] hdWGCNA v0.3.00 w/ R 4.3.2
  easybuild/easyconfigs/h/hdWGCNA/hdWGCNA-0.3.00-foss-2023a-R-4.3.2.eb
Labels: new

#20125 {lib}[foss/2023a] PyTables v3.9.2, Blosc v1.21.5, Blosc2 v2.13.2, py-cpuinfo v9.0.0
  easybuild/easyconfigs/b/Blosc/Blosc-1.21.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/b/Blosc2/Blosc2-2.13.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.9.2-foss-2023b.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.9.2_fix-find-blosc2-dep.patch
  easybuild/easyconfigs/p/py-cpuinfo/py-cpuinfo-9.0.0-GCCcore-13.2.0.eb
Labels: update

#20113 add MODIStsp extension (+ required dependencies) to R 4.2.2
  easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
  easybuild/easyconfigs/r/R/protolite-2.3.0_use-c++17.patch
Labels: enhancement

#19863 {numlib}[foss/2023a] SLEPc v3.20.1
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.20.1-foss-2023a.eb
Labels: update

#20121 {tools}[GCCcore/12.3.0] Vim v9.1.0004
  easybuild/easyconfigs/v/Vim/Vim-9.1.0004-GCCcore-12.3.0.eb
Labels: update

#20102 {bio,tools}[foss/2023b] GROMACS v2024.1, networkx v3.2.1
  easybuild/easyconfigs/g/GROMACS/GROMACS-2024.1-foss-2023b.eb
  easybuild/easyconfigs/n/networkx/networkx-3.2.1-gfbf-2023b.eb
Labels: update

#20126 {tools}[foss/2023a] ipympl v0.9.3
  easybuild/easyconfigs/i/ipympl/ipympl-0.9.3-foss-2023a.eb
Labels: update

#20035 add multiarch support for RISC-V to all GCCcore 12.x and 13.x easyconfigs
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.x_riscv_multiarch_support.patch
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
Labels: bug fix, EESSI, riscv

#19793 {bio}[GCC/10.3.0] Flye v2.9.3
  easybuild/easyconfigs/f/Flye/Flye-2.9.3-GCC-10.3.0.eb
Labels: update

#19600 Remove osdependencies from GCCcore ccache
  easybuild/easyconfigs/c/ccache/ccache-4.6.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/ccache/ccache-4.6.3-GCCcore-11.3.0.eb
Labels: bug fix

#19623 {system}[system/system] OpenSSL v3
  easybuild/easyconfigs/o/OpenSSL/OpenSSL-3.eb
Labels: update

#20134 {devel}[foss/2023a] Spark v3.5.1 w/ Java 17
  easybuild/easyconfigs/s/Spark/Spark-3.5.1-foss-2023a-Java-17.eb
Labels: update

#20091 {bio}[GCCcore/11.3.0] CSBLAST v2.2.4
  easybuild/easyconfigs/c/CSBLAST/CSBLAST-2.2.4-GCCcore-11.3.0.eb
Labels: update

#20147 {tools}[GCC/12.3.0] likwid v5.3.0
  easybuild/easyconfigs/l/likwid/likwid-5.3.0-GCC-12.3.0.eb
Labels: update

#20137 {lib}[foss/2023a] librosa v0.10.1
  easybuild/easyconfigs/l/librosa/librosa-0.10.1-foss-2023a.eb
Labels: update

#20139 {ai}[foss/2023a] denseweight v0.1.2
  easybuild/easyconfigs/d/denseweight/denseweight-0.1.2-foss-2023a.eb
Labels: update

#20143 {devel}[foss/2023a] NLTK v3.8.1
  easybuild/easyconfigs/n/NLTK/NLTK-3.8.1-foss-2023a.eb
Labels: update

#19864 {cae,vis}[GCCcore/12.3.0] occt v7.8.0, FreeImage v3.18.0
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/occt/occt-7.8.0-GCCcore-12.3.0.eb
Labels: update

#20136 {bio}[GCC/11.3.0] add libSBML 5.19.7
  easybuild/easyconfigs/l/libSBML/libSBML-5.19.7-GCC-11.3.0.eb
Labels: update

#20149 {math}[gfbf/2023a] Clarabel.rs v0.7.1
  easybuild/easyconfigs/c/Clarabel.rs/Clarabel.rs-0.7.1-gfbf-2023a.eb
Labels: new

#20141 {lib}[foss/2023a] scikit-lego v0.7.4
  easybuild/easyconfigs/s/scikit-lego/scikit-lego-0.7.4-foss-2023a.eb
Labels: update

#19832 {perf}[GCCcore/13.2.0] Score-P v8.4, CubeLib v4.8.2, CubeWriter v4.8.2, OPARI2 v2.0.8, ... tools
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.8.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.8.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PAPI/PAPI-7.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-13.2.0-tools.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2023b.eb
Labels: update

#20144 {lang}[foss/2023a] CVXPY v1.4.2
  easybuild/easyconfigs/c/CVXPY/CVXPY-1.4.2-foss-2023a.eb
Labels: update

#20152 {lib}[foss/2023a] PyTorch-Lightning v2.2.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-2.2.1-foss-2023a-CUDA-12.1.1.eb
Labels: update

#20146 {perf}[gompi/2023b] Score-P v8.4 w/ CUDA 12.4.0
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2023b-CUDA-12.4.0.eb
Labels: update

#20142 {geo}[foss/2023a] MODFLOW v6.4.4
  easybuild/easyconfigs/m/MODFLOW/MODFLOW-6.4.4-foss-2023a.eb
Labels: new

#20158 Remove UCX-CUDA with incompatible CUDA-GCC-combination
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.15.0-GCCcore-13.2.0-CUDA-12.3.0.eb
Labels: bug fix

#20122 {geo}[foss/2023a] SCENIC v1.3.0 w/ R 4.3.2
  easybuild/easyconfigs/s/SCENIC/SCENIC-1.3.0-foss-2023a-R-4.3.2.eb
Labels: update

#20151 {tools}[GCCcore/12.3.0,gfbf/2023a] phonemizer v3.2.1, eSpeak-NG v1.51, festival v2.5.0, ... w/ voices 20200330
  easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.51-gfbf-2023a.eb
  easybuild/easyconfigs/f/festival/festival-2.5.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MBROLA/MBROLA-3.3-GCCcore-12.3.0-voices-20200330.eb
  easybuild/easyconfigs/p/phonemizer/phonemizer-3.2.1-gfbf-2023a.eb
  easybuild/easyconfigs/s/sonic/sonic-20180202-gfbf-2023a.eb
  easybuild/easyconfigs/s/speech_tools/speech_tools-2.5.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/speech_tools/speech_tools-2.5.0_siodeditline.patch
Labels: update

#20157 {phys}[foss/2022a] BerkeleyGW v4.0
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-4.0-foss-2022a.eb
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-4.0_makefile.patch
  easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-4.0_tests.patch
Labels: update

#20159 {lib}[GCCcore/13.2.0] Abseil v20240116.1, gRPC v1.62.1, protobuf-python v4.25.3, ...
  easybuild/easyconfigs/a/Abseil/Abseil-20240116.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/c-ares/c-ares-1.27.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/gRPC/gRPC-1.62.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/protobuf-python/protobuf-python-4.25.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/protobuf/protobuf-25.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/r/RE2/RE2-2024-03-01-GCCcore-13.2.0.eb
Labels: update

#20172 Remove whitespace in protobuf-25.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/protobuf/protobuf-25.3-GCCcore-13.2.0.eb
Labels: bug fix

#20165 {tools}[GCCcore/13.2.0] Z3 v4.13.0
  easybuild/easyconfigs/z/Z3/Z3-4.13.0-GCCcore-13.2.0.eb
Labels: update

#20168 {tools}[GCCcore/13.2.0] expecttest v0.2.1
  easybuild/easyconfigs/e/expecttest/expecttest-0.2.1-GCCcore-13.2.0.eb
Labels: update

#20167 {math}[GCC/13.2.0,gfbf/2023b] sympy v1.12, gmpy2 v2.1.5
  easybuild/easyconfigs/g/gmpy2/gmpy2-2.1.5-GCC-13.2.0.eb
  easybuild/easyconfigs/s/sympy/sympy-1.12-gfbf-2023b.eb
Labels: update

#20163 Switch libxc sources to gitlab
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-10.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-11.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-9.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2020.1.217.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2020.4.304.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-4.3.4-intel-compilers-2021.4.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.2-GCC-10.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.3-GCC-10.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.5-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.6-GCC-11.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.1.6-intel-compilers-2021.4.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.2.3-GCC-11.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-5.2.3-intel-compilers-2022.1.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.1.0-GCC-12.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.1.0-intel-compilers-2022.2.1.eb
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-GCC-13.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-intel-compilers-2023.2.1.eb
Labels: bug fix

#20173 Fix duplicate dict entries
  .github/workflows/linting.yml
  easybuild/easyconfigs/__archive__/l/libunwind/libunwind-1.1-foss-2015a.eb
  easybuild/easyconfigs/__archive__/l/libunwind/libunwind-1.1-goolf-1.4.10.eb
  easybuild/easyconfigs/__archive__/l/libunwind/libunwind-1.1-ictce-5.3.0.eb
  easybuild/easyconfigs/i/IntelDAAL/IntelDAAL-2019.4.007.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.1-GCC-4.9.2.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.1-foss-2016a.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.1-intel-2016b.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-foss-2016b.eb
  easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb
Labels: bug fix, feature

#20161 Remove flake8 suppressions for invalid escape sequences
  easybuild/easyconfigs/d/Delft3D/Delft3D-4.04.01-foss-2022a-FLOW.eb
  easybuild/easyconfigs/o/OmegaFold/OmegaFold-1.1.0-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/r/ReaxFF/ReaxFF-2.0-GCC-11.3.0-sim.eb
Labels: bug fix

#20174 Enable download_dep_fail for Pythonpackage ECs where it was wrongly disabled
  easybuild/easyconfigs/p/pytest-cpp/pytest-cpp-2.3.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pytest-flakefinder/pytest-flakefinder-1.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pytest-flakefinder/pytest-flakefinder-1.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pytest-flakefinder/pytest-flakefinder-1.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pytest-rerunfailures/pytest-rerunfailures-11.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pytest-rerunfailures/pytest-rerunfailures-12.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pytest-rerunfailures/pytest-rerunfailures-12.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pytest-shard/pytest-shard-0.1.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pytest-shard/pytest-shard-0.1.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pytest-shard/pytest-shard-0.1.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
Labels: bug fix

#20162 SuperLU_DIST fix issue in case library prefix is lib instead of lib64
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.0-foss-2022a.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-foss-2022b.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-foss-2023a.eb
Labels: bug fix

#20170 {devel}[GCCcore/13.2.0] pydantic v2.6.4, Rust v1.76.0, maturin v1.5.0, ... w/ Rust 1.76.0
  easybuild/easyconfigs/m/maturin/maturin-1.5.0-GCCcore-13.2.0-Rust-1.76.0.eb
  easybuild/easyconfigs/p/pydantic/pydantic-2.6.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.76.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/typing-extensions/typing-extensions-4.10.0-GCCcore-13.2.0.eb
Labels: update

#20169 {data}[foss/2021b] Arrow v8.0.0
  easybuild/easyconfigs/a/Arrow/Arrow-8.0.0-foss-2021b.eb
Labels: update

#20075 {math}[foss/2023a] SUNDIALS v6.6.0: Use 32-bit indexing to enable sunmatrix-cusparse
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-6.6.0-foss-2023a-CUDA-12.1.1.eb
Labels: bug fix

#20185 {compiler,tools}[system/system] Go v1.22.1, git-lfs v3.5.1
  easybuild/easyconfigs/g/Go/Go-1.22.1.eb
  easybuild/easyconfigs/g/git-lfs/git-lfs-3.5.1.eb
Labels: update

#20184 {chem}[foss/2023a] LAMMPS v2Aug2023_update2 w/ kokkos CUDA 12.1.1
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update2-foss-2023a-kokkos-CUDA-12.1.1.eb
Labels: update

#20127 update version and toolchain for GLFW
  easybuild/easyconfigs/g/GLFW/GLFW-3.4-GCCcore-12.2.0.eb
Labels: update

#20188 Fix several typos in GlobalArrays 5.8 configure step
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-intel-2021a.eb
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.1-intel-2022a.eb
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-intel-2022a.eb
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-intel-2023a.eb
Labels: bug fix

#20193 Drop dead homepage from source_urls in GCCcore 10-11
  easybuild/easyconfigs/g/GCCcore/GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-11.2.0.eb
Labels: bug fix

#20194 [GCCcore/8.2.0] Fix package installation in Python ECs
  easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.7.2-GCCcore-8.2.0.eb
Labels: bug fix

#20192 Fix broken homepage from older SCOTCH easyconfigs
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-gompi-2021a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.0-iimpi-2021a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.2-gompi-2021b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.1.2-iimpi-2021b.eb
Labels: bug fix

#20187 Drop Time::HiRes tests
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
Labels: bug fix

#19868 {lang}[GCCcore/13.2.0] CCL v1.12.2
  easybuild/easyconfigs/c/CCL/CCL-1.12.2-GCCcore-13.2.0.eb
Labels: update

#19867 {tools}[GCCcore/13.2.0] atools v1.5.1
  easybuild/easyconfigs/a/atools/atools-1.5.1-GCCcore-13.2.0.eb
Labels: update

#19858 {tools}[GCC/12.2.0,GCC/13.2.0] gawk v5.3.0
  easybuild/easyconfigs/g/gawk/gawk-5.3.0-GCC-12.2.0.eb
  easybuild/easyconfigs/g/gawk/gawk-5.3.0-GCC-13.2.0.eb
Labels: update

#20160 {bio}[GCC/12.3.0] PSASS v3.1.0
  easybuild/easyconfigs/p/PSASS/PSASS-3.1.0-GCC-12.3.0.eb
Labels: new

#20195 Enable LittleCMS2 and WebP support in recent Pillow
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-9.5.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-10.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pillow/Pillow-10.2.0-GCCcore-13.2.0.eb
Labels: enhancement

#20129 Fix download url for cuSPARSELt 0.3.0.3
  easybuild/easyconfigs/c/cuSPARSELt/cuSPARSELt-0.3.0.3-CUDA-11.4.1.eb
Labels: bug fix

#20128 {lib}[system/system] cuTENSOR v2.0.1.2 w/ CUDA 12.1.1
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-2.0.1.2-CUDA-12.1.1.eb
Labels: update

#20130 {lib}[system/system] cuSPARSELt v0.6.0.6 w/ CUDA 12.1.1
  easybuild/easyconfigs/c/cuSPARSELt/cuSPARSELt-0.6.0.6-CUDA-12.1.1.eb
Labels: update

#20196 {lang}[system/system] Mamba v23.11.0-0
  easybuild/easyconfigs/m/Mamba/Mamba-23.11.0-0.eb
Labels: update

#20199 {bio}[foss/2023a] MDAnalysis v2.7.0
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-2.7.0-foss-2023a.eb
Labels: update

#20171 {ai}[foss/2023b] PyTorch v2.1.2
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023b.eb
Labels: update

#20176 fix PyTorch-1.12.0-foss-2022a-CUDA-11.7.0.eb for Linux 6+
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.0-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.0_fix-Gloo-compatibility-with-newer-kernel.patch
Labels: bug fix

#20198 {devel}[foss/2023b] NLTK v3.8.1, tqdm v4.66.2
  easybuild/easyconfigs/n/NLTK/NLTK-3.8.1-foss-2023b.eb
  easybuild/easyconfigs/t/tqdm/tqdm-4.66.2-GCCcore-13.2.0.eb
Labels: update

#20200 Drop hatchling builddep from tqdm 4.66.1 as well
  easybuild/easyconfigs/t/tqdm/tqdm-4.66.1-GCCcore-12.3.0.eb
Labels: enhancement

#20202 librsvg update version and toolchain
  easybuild/easyconfigs/l/librsvg/librsvg-2.58.0-GCCcore-13.2.0.eb
Labels: update

#20156 Fix test issues in PyTorch-2.1.2-foss-2023a-CUDA-12.1.1
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_fix-locale-issue-in-nvrtcCompileProgram.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_fix-with_temp_dir-decorator.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_fix-wrong-device-mesh-size-in-tests.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_skip-test_fsdp_tp_checkpoint_integration.patch
Labels: bug fix

#20209 {lib}[GCCcore/12.3.0] RapidJSON v1.1.0
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-GCCcore-12.3.0.eb
Labels: update

#20211 {chem}[gompi/2023a] CoordgenLibs v3.0.2
  easybuild/easyconfigs/c/CoordgenLibs/CoordgenLibs-3.0.2-gompi-2023a.eb
Labels: update

#20215 {tools}[system/system] code-server v4.22.1
  easybuild/easyconfigs/c/code-server/code-server-4.22.1.eb
Labels: update

#20214 Add missing deps to Ruby easyconfigs
  easybuild/easyconfigs/r/Ruby/Ruby-3.0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.0.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.0.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.2.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.3.0-GCCcore-12.3.0.eb
Labels: bug fix

#19872 {tools}[system/system] code-server v4.21.1
  easybuild/easyconfigs/c/code-server/code-server-4.21.1.eb
Labels: update

#19789 {tools}[system/system] git-lfs v3.4.1
  easybuild/easyconfigs/g/git-lfs/git-lfs-3.4.1.eb
Labels: update

#19737 Add patch for jupyter_core to set jupyter path by `EB_ENV_JUPYTER_ROOT`
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.0.5-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/JupyterNotebook/JupyterNotebook-7.0.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/JupyterNotebook/JupyterNotebook-7.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/jupyter-resource-usage/jupyter-resource-usage-1.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/jupyter-server-proxy/jupyter-server-proxy-3.2.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/jupyter-server-proxy/jupyter-server-proxy-4.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/jupyter-server/jupyter-core-5.3.1_fix_jupyter_path.patch
  easybuild/easyconfigs/j/jupyter-server/jupyter-server-2.7.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/jupyter-server/jupyter-server-2.7.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/jupyterlmod/jupyterlmod-4.0.3-GCCcore-12.3.0.eb
Labels: bug fix

#20203 {lib}[foss/2023a] CuPy v13.0.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/c/CuPy/CuPy-13.0.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/c/CuPy/cupy-13.0.0_cusparselt_0.6.0.patch
  easybuild/easyconfigs/c/CuPy/cupy-13.0.0_eb_ccc.patch
Labels: update

#19084 {bio}[foss/2023a] UMI-tools v1.1.4
  easybuild/easyconfigs/u/UMI-tools/UMI-tools-1.1.4-foss-2023a.eb
Labels: update

#20218 add patch to fix tree-optimization bug in GCC 12.3.0 and 13.1.0 for ARM architectures with SVE support
  easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb
Labels: bug fix

#20216 Fix cuSPARSELt for aarch64
  easybuild/easyconfigs/c/cuSPARSELt/cuSPARSELt-0.3.0.3-CUDA-11.4.1.eb
  easybuild/easyconfigs/c/cuSPARSELt/cuSPARSELt-0.6.0.6-CUDA-12.1.1.eb
Labels: bug fix

#20219 {vis}[foss/2021b,foss/2022a,foss/2023a] fix napari v0.4.1{5,8} shebang
  easybuild/easyconfigs/n/napari/napari-0.4.15-foss-2021b.eb
  easybuild/easyconfigs/n/napari/napari-0.4.18-foss-2022a.eb
  easybuild/easyconfigs/n/napari/napari-0.4.18-foss-2023a.eb
Labels: bug fix

#20201 {lib}[GCCcore/13.2.0] snappy v1.1.10, double-conversion v3.3.0, Qt5 v5.15.13
  easybuild/easyconfigs/d/double-conversion/double-conversion-3.3.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.13_fix-XKB_KEY_dead.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.13_fix-includes.patch
  easybuild/easyconfigs/s/snappy/snappy-1.1.10-GCCcore-13.2.0.eb
Labels: update

#20206 {math}[GCCcore/12.3.0] SpectrA v1.0.1
  easybuild/easyconfigs/s/SpectrA/SpectrA-1.0.1-GCCcore-12.3.0.eb
Labels: update, 2023a
