Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-08, with the labels that each got.

#21103 {lib}[foss/2023a] submitit v1.2.0
  easybuild/easyconfigs/s/submitit/submitit-1.2.0-foss-2023a.eb
Labels: new

#21094 {geo}[foss/2023a] wradlib v2.0.3
  easybuild/easyconfigs/w/wradlib/wradlib-2.0.3-foss-2023a.eb
Labels: new

#21107 {ai}[foss/2023a] accelerate v0.33.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/a/accelerate/accelerate-0.33.0-foss-2023a-CUDA-12.1.1.eb
Labels: new

#21111 {bio}[GCCcore/12.3.0,foss/2023a] Bandage v0.9.0, GetOrganelle v1.7.7.1
  easybuild/easyconfigs/b/Bandage/Bandage-0.9.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GetOrganelle/GetOrganelle-1.7.7.1-foss-2023a.eb
Labels: update

#21114 {compiler} GCC v14.2.0
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.42-GCCcore-14.2.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/GCC/GCC-14.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-14.2.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-14.2.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.3.1-GCCcore-14.2.0.eb
Labels: update

#21099 {vis}[foss/2023a] CLANS v2.0.8
  easybuild/easyconfigs/c/CLANS/CLANS-2.0.8-foss-2023a.eb
Labels: new

#20858 {geo}[foss/2023a] CESM-deps v2
  easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-foss-2023a.eb
Labels: update

#21129 Szip: Update source and homepage URLs
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-6.3.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-6.4.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-7.3.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-8.2.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-8.3.0.eb
  easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-9.3.0.eb
Labels: bug fix

#21130 HDF v4.2.16-2: Rename source URL
  easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/h/HDF/HDF-4.2.16-GCCcore-12.3.0.eb
Labels: bug fix

#21101 {toolchain}[iimpi/2024a,system/system] Rename intel-2024.06 toolchain to 2024a
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2024a.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2024a.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2024.2.0-iimpi-2024a.eb
  easybuild/easyconfigs/i/intel/intel-2024a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.4-iimpi-2024a.eb
Labels: update, 2024a

#21121 {tools}[GCCcore/13.3.0] archspec v0.2.4
  easybuild/easyconfigs/a/archspec/archspec-0.2.4-GCCcore-13.3.0.eb
Labels: update, 2024a

#21120 {data,tools}[GCCcore/13.3.0] BioPerl v1.7.8, DB v18.1.40, DB_File v1.859, ...
  easybuild/easyconfigs/a/attr/attr-2.5.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-13.3.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.859-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0210-GCCcore-13.3.0.eb
Labels: update, 2024a

#21113 {tools}[foss/2023a] cfgrib v0.9.14.0
  easybuild/easyconfigs/c/cfgrib/cfgrib-0.9.14.0-foss-2023a.eb
Labels: new

#20964 {bio,lib}[GCC/12.3.0] Transrate v1.0.3, crb-blast v0.6.9, colorize v0.7.7, yell v2.2.2
  easybuild/easyconfigs/c/colorize/colorize-0.7.7-GCC-12.3.0.eb
  easybuild/easyconfigs/c/crb-blast/crb-blast-0.6.9-GCC-12.3.0.eb
  easybuild/easyconfigs/t/Transrate/Transrate-1.0.3-GCC-12.3.0.eb
  easybuild/easyconfigs/t/Transrate/Transrate-1.0.3_undefined_method_fix.patch
  easybuild/easyconfigs/y/yell/yell-2.2.2-GCC-12.3.0.eb
Labels: new, update

#21136 Ensure that recent BioPerl easyconfigs use `Bundle` easyblock
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-12.2.0.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-12.3.0.eb
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-13.3.0.eb
Labels: bug fix

#21110 {geo}[foss/2022a] wradlib v2.0.3
  easybuild/easyconfigs/w/wradlib/wradlib-2.0.3-foss-2022a.eb
Labels: update

#21123 {tools}[GCCcore/13.3.0] CFITSIO v4.4.1, CGAL v5.6.1, Coreutils v9.5, ...
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-4.4.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/CGAL/CGAL-5.6.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/Coreutils/Coreutils-9.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-GCCcore-13.3.0.eb
Labels: update, 2024a

#21112 {lang}[GCCcore/13.3.0] Rust v1.79.0
  easybuild/easyconfigs/r/Rust/Rust-1.79.0-GCCcore-13.3.0.eb
Labels: update

#21097 {lib}[foss/2023a] timm v1.0.8 w/ CUDA 12.1.1
  easybuild/easyconfigs/t/timm/timm-1.0.8-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21144 add pkgconf build dependency to scikit-misc v0.3.1
  easybuild/easyconfigs/s/scikit-misc/scikit-misc-0.3.1-foss-2023a.eb
Labels: bug fix

#21151 {lib}[GCCcore/13.2.0] fmt v10.2.1
  easybuild/easyconfigs/f/fmt/fmt-10.2.1-GCCcore-13.2.0.eb
Labels: update

#21149 {lib}[GCCcore/13.2.0] libedit v20240517
  easybuild/easyconfigs/l/libedit/libedit-20240517-GCCcore-13.2.0.eb
Labels: update

#21157 {bio}[GCCcore/12.3.0] miniprot v0.13
  easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-12.3.0.eb
Labels: new

#20852 {bio}[foss/2023a] OpenForceField-Toolkit v0.16.0
  easybuild/easyconfigs/o/OpenForceField-Toolkit/OpenForceField-Toolkit-0.16.0-foss-2023a.eb
Labels: new

#21117 {compiler}[GCCcore/13.3.0] Clang v18.1.8
  easybuild/easyconfigs/c/Clang/Clang-18.1.8-GCCcore-13.3.0.eb
Labels: update, 2024a

#21155 {chem}[foss/2023a] MBX v1.1.0
  easybuild/easyconfigs/m/MBX/MBX-1.1.0-foss-2023a.eb
Labels: new

#21165 {devel}[system/system] PyCharm v2024.1.6
  easybuild/easyconfigs/p/PyCharm/PyCharm-2024.1.6.eb
Labels: update

#21154 {bio}[gompi/2022a] PyRosetta v4.release-384
  easybuild/easyconfigs/p/PyRosetta/PyRosetta-4.release-384-gompi-2022a.eb
Labels: update

#21126 {tools}[GCCcore/13.3.0] APR v1.7.4, APR-util v1.6.3
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.4-GCCcore-13.3.0.eb
Labels: update, 2024a

#20989 {lib}[foss/2023a] SIRIUS v7.5.2, Umpire v2024.02.1, COSTA v2.2.2, ...
  easybuild/easyconfigs/c/COSTA/COSTA-2.2.2-foss-2023a.eb
  easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.5.2-foss-2023a.eb
  easybuild/easyconfigs/s/SpFFT/SpFFT-1.1.0-foss-2023a.eb
  easybuild/easyconfigs/s/spglib/spglib-2.5.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/spla/spla-1.6.1-foss-2023a.eb
  easybuild/easyconfigs/u/Umpire/Umpire-2024.02.1-foss-2023a.eb
Labels: new, update

#21173 {bio}[GCC/12.3.0] Kent_tools v468
  easybuild/easyconfigs/k/Kent_tools/Kent_tools-468-GCC-12.3.0.eb
Labels: update

#21172 Add GPflow v2.9.2 and fix tensorflow-probability to pass pip check
  easybuild/easyconfigs/g/GPflow/GPflow-2.9.2-foss-2023a.eb
  easybuild/easyconfigs/t/tensorflow-probability/tensorflow-probability-0.20.0-foss-2023a.eb
Labels: bug fix, update

#21174 {bio}[foss/2023a] EMMAX v20100310
  easybuild/easyconfigs/e/EMMAX/EMMAX-20100310-foss-2023a.eb
  easybuild/easyconfigs/e/EMMAX/EMMAX-20100310_fix-build.patch
Labels: new

#21167 add missMDA extension to R-bundle-CRAN 2023.12
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
Labels: enhancement

#21175 stop RStudio-Server 2023.09 from installing R packages (+ move to `foss/2023a` toolchain)
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.09.1+494-foss-2023a-Java-11-R-4.3.2.eb
Labels: bug fix, change

#15752 {bio}[GCC/11.2.0] Regenie v3.1.1, BGEN-enkre v1.1.7, Boost v1.55.0
  easybuild/easyconfigs/b/BGEN-enkre/3rd-party-removal.patch
  easybuild/easyconfigs/b/BGEN-enkre/BGEN-enkre-1.1.7-GCC-11.2.0.eb
  easybuild/easyconfigs/b/BGEN-enkre/BGEN-enkre_streampos.patch
  easybuild/easyconfigs/b/Boost/Boost-1.55.0-GCC-11.2.0.eb
  easybuild/easyconfigs/r/Regenie/Regenie-3.1.2-GCC-11.2.0.eb
  easybuild/easyconfigs/r/Regenie/regenie-3.1.2_Makefile.patch
Labels: new, update

#21140 {vis}[GCCcore/12.2.0] MONAI v1.3.0, einops v0.7.0, ITK v5.3.0, ... w/ largefiles
  easybuild/easyconfigs/e/einops/einops-0.7.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/grpcio/grpcio-1.57.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/i/ITK/ITK-5.3.0-foss-2022b.eb
  easybuild/easyconfigs/i/ITK/ITK-5.3.0_vtk-include.patch
  easybuild/easyconfigs/m/MONAI/MONAI-1.3.0-foss-2022b.eb
  easybuild/easyconfigs/n/NiBabel/NiBabel-5.2.0-gfbf-2022b.eb
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-3.4.1-GCCcore-12.2.0-largefiles.eb
  easybuild/easyconfigs/o/openslide-python/openslide-python-1.3.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pydicom/pydicom-2.4.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.15.1-gfbf-2022b.eb
Labels: update

#21100 define `foss/2024a` toolchain (copy of `foss/2024.05`)
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2024a.eb
  easybuild/easyconfigs/f/foss/foss-2024a.eb
  easybuild/easyconfigs/g/gfbf/gfbf-2024a.eb
  easybuild/easyconfigs/g/gompi/gompi-2024a.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2024a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.4-gompi-2024a.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gompi-2024a-fb.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024a.eb
Labels: update, 2024a

#21198 remove `Time::HiRes` from `Perl-bundle-CPAN`
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb
Labels: bug fix

#21036 {cae}[foss/2023a] OpenFOAM v2406
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2406-cleanup.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2406-foss-2023a.eb
Labels: update

#21177 {lang}[system/system] Julia v1.10.4 w/ linux x86_64
  easybuild/easyconfigs/j/Julia/Julia-1.10.4-linux-x86_64.eb
Labels: update

#21163 {bio}[GCC/12.3.0] Salmon v1.10.3
  easybuild/easyconfigs/s/Salmon/Salmon-1.10.3-GCC-12.3.0.eb
Labels: update

#21028 Add `OPENSSL_ENABLE_SHA1_SIGNATURES` for building `ansys-pythonnet`
  easybuild/easyconfigs/p/PyAEDT/PyAEDT-0.8.7-GCCcore-12.3.0.eb
Labels: bug fix

#21200 fix build of STAR 2.7.11a + 2.7.11b on non-x86 architectures by avoiding use of `-maxv2` + add missing `xxd` build dependency
  easybuild/easyconfigs/s/STAR/STAR-2.7.11a-GCC-12.2.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.11a-GCC-12.3.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.11b-GCC-12.3.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.11b-GCC-13.2.0.eb
Labels: bug fix, EESSI, aarch64

#21209 {bio}[foss/2023a] IsoQuant v3.5.0, gffutils v0.13
  easybuild/easyconfigs/g/gffutils/gffutils-0.13-foss-2023a.eb
  easybuild/easyconfigs/i/IsoQuant/IsoQuant-3.5.0-foss-2023a.eb
Labels: update

#21206 {math}[GCC/13.2.0] bliss v0.77
  easybuild/easyconfigs/b/bliss/bliss-0.77-GCC-13.2.0.eb
  easybuild/easyconfigs/b/bliss/bliss-0.77_install_fix.patch
Labels: new

#20444 {bio}[foss/2023a] dorado v0.6.1, kineto v0.4.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dorado/dorado-0.6.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/d/dorado/dorado-0.6.1_include-fstream.patch
  easybuild/easyconfigs/k/kineto/kineto-0.4.0-GCC-12.3.0.eb
Labels: update

#21184 {lib}[foss/2023a] CUTLASS v3.4.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/c/CUTLASS/CUTLASS-3.4.0-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21211 Add missing cairo dependency for python-igraph v0.10.6
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.10.6-foss-2022b.eb
Labels: bug fix

#21083 {lib}[foss/2023a] flash-attention v2.6.3 w/ CUDA 12.1.1
  easybuild/easyconfigs/f/flash-attention/flash-attention-2.6.3-foss-2023a-CUDA-12.1.1.eb
Labels: new

#21210 {bio}[foss/2023a] medaka v1.12.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/m/medaka/medaka-1.12.0-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21166 {bio}[foss/2023a] dictys v1.1.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dictys/dictys-1.1.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/d/dictys/dictys-1.1.0-foss-2023a.eb
  easybuild/easyconfigs/j/junos-eznc/junos-eznc-2.7.1-GCCcore-12.3.0.eb
Labels: new

#21214 {bio}[foss/2023a] medaka v1.12.1
  easybuild/easyconfigs/m/medaka/medaka-1.12.1-foss-2023a.eb
Labels: update

#21215 {bio}[foss/2023a] medaka v1.12.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/m/medaka/medaka-1.12.1-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21212 {bio}[GCC/10.2.0] VSEARCH v2.28.1
  easybuild/easyconfigs/v/VSEARCH/VSEARCH-2.28.1-GCC-10.2.0.eb
Labels: update

#21213 {bio}[foss/2023a] longread_umi v0.3.2, cutadapt v4.9, Filtlong v0.2.1
  easybuild/easyconfigs/c/cutadapt/cutadapt-4.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/f/Filtlong/Filtlong-0.2.1-GCC-12.3.0.eb
  easybuild/easyconfigs/l/longread_umi/longread_umi-0.3.2-foss-2023a.eb
Labels: update

#21016 {bio}[GCC/12.3.0] SingleM v0.16.0, smafa v0.8.0, psycopg v3.2.1, ...
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-GCC-12.3.0.eb
  easybuild/easyconfigs/p/psycopg/psycopg-3.2.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/SingleM/SingleM-0.16.0-foss-2023a.eb
  easybuild/easyconfigs/s/smafa/smafa-0.8.0-GCC-12.3.0.eb
Labels: update

#21207 {tools}[GCCcore/12.3.0] Rasqal v0.9.33, gtk-doc v1.34.0, Pygments v2.18.0, ...
  easybuild/easyconfigs/d/dblatex/dblatex-0.3.12-foss-2023a.eb
  easybuild/easyconfigs/g/gtk-doc/gtk-doc-1.34.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Pygments/Pygments-2.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/Raptor/Raptor-2.0.16-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/Rasqal/Rasqal-0.9.33-GCCcore-12.3.0.eb
Labels: new, update

#21001 {vis}[foss/2023b] ParaView v5.12.0 w/ Qt5
  easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-foss-2023b-Qt5.eb
Labels: update

#21002 add patch to fix Qt6 issues with ParaView v5.12.0, e.g. representation selection
  easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-foss-2023b.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-qt6_fixes.patch
Labels: bug fix

#21233 remove Cython dependency from Python-bundle-PyPI 2024.06 + standalone easyconfig for Cython 3.0.10
  easybuild/easyconfigs/c/Cython/Cython-3.0.10-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb
Labels: update, change

#21234 {bio}[foss/2023a] dorado v0.7.3 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dorado/dorado-0.7.3-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/d/dorado/dorado-0.7.3_include-fstream.patch
Labels: update

#21235 add Cython builddep for SciPy-bundle
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024.05.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024a.eb
Labels: change

#21229 {bio}[foss/2023a] MATES v0.1.2-20240813 (w/ CUDA 12.1.1)
  easybuild/easyconfigs/m/MATES/MATES-0.1.2-20240813-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/m/MATES/MATES-0.1.2-20240813-foss-2023a.eb
Labels: new

#20362 {bio}[foss/2023a] OpenMM v8.0.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/o/OpenMM/OpenMM-8.0.0-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21183 add missMDA extension to R-bundle-CRAN 2024.06
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
Labels: enhancement

#21106 {bio}[GCC/12.3.0,gompi/2023a] EvidentialGene v2023.07.15, Exonerate v2.4.0
  easybuild/easyconfigs/e/EvidentialGene/EvidentialGene-2023.07.15-gompi-2023a.eb
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-12.3.0.eb
Labels: update

#21179 {bio}[foss/2022a] AlphaPulldown v2.0.0b4, Uni-Core v0.0.3
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.0b2_fix-import-protein_letters_3to1.patch
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.0b4-foss-2022a.eb
  easybuild/easyconfigs/u/Uni-Core/Uni-Core-0.0.3-foss-2022a.eb
Labels: new, update

#21182 {bio}[foss/2022a] AlphaPulldown v2.0.0b4, Uni-Core v0.0.3 w/ CUDA 11.7.0
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.0b4-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/u/Uni-Core/Uni-Core-0.0.3-foss-2022a-CUDA-11.7.0.eb
Labels: new, update

#21242 {ai}[fosscuda/2020b] spektral v1.2.0
  easybuild/easyconfigs/s/spektral/spektral-1.2.0-fosscuda-2020b-TensorFlow-2.5.0.eb
Labels: update

#21247 {bio}[GCC/12.3.0] STAR v2.7.11b_alpha_2024-02-09
  easybuild/easyconfigs/s/STAR/STAR-2.7.11b_alpha_2024-02-09-GCC-12.3.0.eb
Labels: update

#21237 {bio}[foss/2023a] inferCNV v1.21.0 w/ R 4.3.2
  easybuild/easyconfigs/i/inferCNV/inferCNV-1.21.0-foss-2023a-R-4.3.2.eb
Labels: update

#21241 {vis}[GCCcore/13.3.0] FFmpeg v7.0.2, FriBidi v1.0.15, ffnvcodec v12.2.72.0, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-7.0.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.15-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-12.2.72.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.30.6-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20240513-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/x265/x265-3.6-GCCcore-13.3.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#21236 {lib}[GCC/13.2.0] SentencePiece v0.2.0
  easybuild/easyconfigs/s/SentencePiece/SentencePiece-0.2.0-GCC-13.2.0.eb
Labels: update

#21255 add patch for xtb 6.7.0 to fix build failure due to changes in tblite
  easybuild/easyconfigs/x/xtb/xtb-6.7.0-gfbf-2023a.eb
  easybuild/easyconfigs/x/xtb/xtb-6.7.0_fix-tblite-pr1072.patch
Labels: bug fix

#21227 {data,lib,math}[GCC/12.3.0,GCCcore/12.3.0,foss/2023a] PEcAn v1.7.2.9000, Redland v1.0.17, unixODBC v2.3.12 w/ R 4.3.2
  easybuild/easyconfigs/p/PEcAn/PEcAn-1.8.0.9000-foss-2023a-R-4.3.2.eb
  easybuild/easyconfigs/p/PEcAn/PEcAn-1.8.0.9000_duckdb.patch
  easybuild/easyconfigs/r/Redland/Redland-1.0.17-GCC-12.3.0.eb
  easybuild/easyconfigs/u/unixODBC/unixODBC-2.3.12-GCCcore-12.3.0.eb
Labels: new, update

#21221 add Qt support to VTK 9.3.0
  easybuild/easyconfigs/v/VTK/VTK-9.3.0-foss-2023a.eb
  easybuild/easyconfigs/v/VTK/VTK-9.3.0-foss-2023b.eb
Labels: enhancement

#20981 {vis}[foss/2023a] Visit v3.4.1, VTK v9.2.6, Qwt v6.3.0
  easybuild/easyconfigs/q/Qwt/Qwt-6.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/v/VTK/VTK-9.2.6-foss-2023a.eb
  easybuild/easyconfigs/v/Visit/Visit-3.4.1-foss-2023a.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#21138 {system}[system/system] CUDA v12.6.0
  easybuild/easyconfigs/c/CUDA/CUDA-12.6.0.eb
Labels: update

#21265 {bio}[GCCcore/12.3.0] NextPolish v1.4.1
  easybuild/easyconfigs/n/NextPolish/NextPolish-1.4.1-GCCcore-12.3.0.eb
Labels: new

#21267 {vis}[foss/2023a] nellie v0.3.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/n/nellie/nellie-0.3.1-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21004 make pytest v7.4.2 independent of Python-bundle-PyPI
  easybuild/easyconfigs/p/pytest/pytest-7.4.2-GCCcore-12.3.0.eb
Labels: change

#21253 {bio}[system/system] SeqKit v2.8.2
  easybuild/easyconfigs/s/SeqKit/SeqKit-2.8.2.eb
Labels: update

#21272 add performance, datwizard and bayestestR to R-bundle-CRAN 2024.06
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
Labels: enhancement

#21232 {lib}[foss/2023a] PyWavelets v1.7.0
  easybuild/easyconfigs/p/PyWavelets/PyWavelets-1.7.0-foss-2023a.eb
Labels: update

#21230 {lib}[GCCcore/12.3.0] prompt-toolkit v3.0.36
  easybuild/easyconfigs/p/prompt-toolkit/prompt-toolkit-3.0.36-GCCcore-12.3.0.eb
Labels: update

#21246 {chem}[foss/2023b] ORCA v6.0.0
  easybuild/easyconfigs/o/ORCA/ORCA-6.0.0-foss-2023b-avx2.eb
  easybuild/easyconfigs/o/ORCA/ORCA-6.0.0-foss-2023b.eb
Labels: update

#21064 {bio}[SYSTEM] BayesTraits v4.1.2
  easybuild/easyconfigs/b/BayesTraits/BayesTraits-4.1.2-Linux.eb
Labels: update

#21263 remove unnecessary use of an easyblock for BamTools
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-GCC-10.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-GCC-9.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.1-iccifort-2020.4.304.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-10.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-11.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-11.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-12.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-12.3.0.eb
Labels: change, EasyBuild-5.0

#21085 {bio,vis}[foss/2023a] SCENICplus v1.0a1-20240513, gensim v4.3.2, pyfasta v0.5.2, numexpr v2.9.0, Kaleido v0.2.1, Sphinx-RTD-Theme v2.0.0, scrublet v0.2.3
  easybuild/easyconfigs/g/gensim/gensim-4.3.2-foss-2023a.eb
  easybuild/easyconfigs/k/Kaleido/Kaleido-0.2.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/n/numexpr/numexpr-2.9.0-foss-2023a.eb
  easybuild/easyconfigs/p/pyfasta/pyfasta-0.5.2-foss-2023a.eb
  easybuild/easyconfigs/s/SCENICplus/SCENICplus-1.0a1-20240513-foss-2023a.eb
  easybuild/easyconfigs/s/Sphinx-RTD-Theme/Sphinx-RTD-Theme-2.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/scrublet/scrublet-0.2.3-foss-2023a.eb
Labels: new, update

#21254 {math}[GCCcore/13.2.0] coxeter v20180226
  easybuild/easyconfigs/c/coxeter/coxeter-20180226-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/coxeter/coxeter-20180226_makefile.patch
  easybuild/easyconfigs/c/coxeter/coxeter-20180226_sage_interface.patch
Labels: new

#20665 {bio}[foss/2022b] TF-COMB v1.1, TOBIAS v0.16.1, svist4get v1.3.1, ...
  easybuild/easyconfigs/a/adjustText/adjustText-0.7.3-foss-2022b.eb
  easybuild/easyconfigs/g/GOATOOLS/GOATOOLS-1.4.5-foss-2022b.eb
  easybuild/easyconfigs/p/pydot/pydot-2.0.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/python-louvain/python-louvain-0.16-foss-2022b.eb
  easybuild/easyconfigs/q/qnorm/qnorm-0.8.1-foss-2022b.eb
  easybuild/easyconfigs/s/svist4get/svist4get-1.3.1-foss-2022b.eb
  easybuild/easyconfigs/t/TF-COMB/TF-COMB-1.1-foss-2022b.eb
  easybuild/easyconfigs/t/TOBIAS/TOBIAS-0.16.1-foss-2022b.eb
Labels: update

#21287 {ai}[gfbf/2023b] XGBoost v2.1.1
  easybuild/easyconfigs/x/XGBoost/XGBoost-2.1.1-gfbf-2023b.eb
Labels: update

#21285 correct extension order in R-bundle-CRAN 2024.06
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
Labels: bug fix

#21280 adding patch: HDF5-1.14.3_suppress_fp_exceptions.patch
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.3-gompi-2023b.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.3-iimpi-2023b.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.3_suppress_fp_exceptions.patch
Labels: bug fix

#21286 {devel, tools, lib}[GCCcore/13.3.0] ConcurrentVersionsSystem-1.11.23, DBus-1.15.8, ecBuild-3.8.5, FLAC-1.4.3, flatbuffers-24.3.25, flatbuffers-python-24.3.25
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-13.3.0.eb
  easybuild/easyconfigs/d/DBus/DBus-1.15.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/e/ecBuild/ecBuild-3.8.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/FLAC/FLAC-1.4.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/flatbuffers-python/flatbuffers-python-24.3.25-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/flatbuffers/flatbuffers-24.3.25-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libogg/libogg-1.3.5-GCCcore-13.3.0.eb
Labels: update

#21271 update fastp
  easybuild/easyconfigs/f/fastp/fastp-0.23.4-GCC-13.2.0.eb
Labels: update
