Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-06, with the labels that each got.

#20698 Use external PRRTE 3.1.5 in OpenMPI 5.0.3
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3-GCC-13.3.0.eb
  easybuild/easyconfigs/p/PRRTE/PRRTE-3.0.5-GCCcore-13.3.0.eb
Labels: new, 2024a

#20646 {numlib,toolchain}[gompi/2024.05,system/system] foss v2024.05, gompi v2024.05, FFTW.MPI v3.3.10, ... w/ fb
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2024.05.eb
  easybuild/easyconfigs/f/foss/foss-2024.05.eb
  easybuild/easyconfigs/g/gompi/gompi-2024.05.eb
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2024.05.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gompi-2024.05-fb.eb
Labels: update, 2024a

#20676 {perf}[gompi/2024.05] OSU-Micro-Benchmarks v7.4
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.4-gompi-2024.05.eb
Labels: update, 2024a

#20682 {bio}[foss/2023a] GTDB-Tk v2.4.0
  easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-2.4.0-foss-2023a.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#20673 {bio}[system/system] CellRanger v8.0.1
  easybuild/easyconfigs/c/CellRanger/CellRanger-8.0.1.eb
Labels: update

#20663 {lib}[foss/2023a] imagecodecs v2024.1.1
  easybuild/easyconfigs/i/imagecodecs/imagecodecs-2024.1.1-foss-2023a.eb
  easybuild/easyconfigs/i/imagecodecs/imagecodecs-2024.1.1_fix-aec-version.patch
Labels: update

#20707 {tools}[gfbf/2023a] ml_dtypes v0.3.2
  easybuild/easyconfigs/m/ml_dtypes/ml_dtypes-0.3.2-gfbf-2023a.eb
  easybuild/easyconfigs/m/ml_dtypes/ml_dtypes-0.3.2_EigenAvx512.patch
Labels: new

#20695 {math}[GCCcore/12.3.0] matlab-proxy v0.18.1, jupyter-matlab-proxy v0.12.2
  easybuild/easyconfigs/j/jupyter-matlab-proxy/jupyter-matlab-proxy-0.12.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/matlab-proxy/matlab-proxy-0.18.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/matlab-proxy/matlab-proxy-0.18.1_use_lic_from_eb_installed_matlab.patch
Labels: update

#20686 add `--disable-htmlpages` to recent FFmpeg easyconfigs
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.1.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-6.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-6.0-GCCcore-13.2.0.eb
Labels: bug fix

#20551 {tools}[foss/2023a] CellBender v0.3.0, jupyter-contrib-nbextensions v0.7.0, pyro-ppl v1.9.0
  easybuild/easyconfigs/c/CellBender/CellBender-0.3.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/c/CellBender/CellBender-0.3.0-foss-2023a.eb
  easybuild/easyconfigs/j/jupyter-contrib-nbextensions/jupyter-contrib-nbextensions-0.7.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pyro-ppl/pyro-ppl-1.9.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/pyro-ppl/pyro-ppl-1.9.0-foss-2023a.eb
Labels: update

#20721 {bio}[system/system] CellRanger-ARC v2.0.2
  easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.2.eb
Labels: update

#20399 {bio}[foss/2022b] CheckM2 v1.0.2
  easybuild/easyconfigs/c/CheckM2/CheckM2-1.0.2-foss-2022b.eb
  easybuild/easyconfigs/c/CheckM2/CheckM2-1.0.2_fileManager.py-database-fix.patch
Labels: new

#20702 {ai}[foss/2023a] LangChain v0.2.1
  easybuild/easyconfigs/l/LangChain/LangChain-0.2.1-foss-2023a.eb
Labels: new

#20719 {phys}[foss/2022b] mumott v2.1
  easybuild/easyconfigs/m/mumott/mumott-2.1-foss-2022b.eb
Labels: update

#20747 Move all libavifs to GCCcore only, fix deps
  easybuild/easyconfigs/l/libavif/libavif-0.11.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libavif/libavif-0.11.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libavif/libavif-0.11.1-foss-2022a.eb
  easybuild/easyconfigs/l/libavif/libavif-1.0.4-GCCcore-12.3.0.eb
Labels: bug fix, update

#20191 {lib} [foss/2023a] Bazel v6.1.0, grpcio v1.57.0, TensorFlow v2.15.1
  easybuild/easyconfigs/b/Bazel/Bazel-6.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/grpcio/grpcio-1.57.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/grpcio/grpcio-1.57.0_use-ebroot.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.15.1-foss-2023a.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.15.1_add-default-shell-env.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.15.1_fix-flatbuffer-license.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.15.1_fix-pybind11-build.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.15.1_remove-io-gcs-filesystem-dep.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.15.1_remove-libclang-dep.patch
Labels: new, update

#20752 {lib}[GCCcore/11.3.0] LIBSVM-MATLAB v3.30 w/ MATLAB 2022b r5
  easybuild/easyconfigs/l/LIBSVM-MATLAB/LIBSVM-MATLAB-3.30-GCCcore-11.3.0-MATLAB-2022b-r5.eb
Labels: new

#20590 {bio}[foss/2023a] HOMER v4.11 w/ R 4.3.2, libidn2 v2.3.7, wget v1.24.5
  easybuild/easyconfigs/h/HOMER/HOMER-4.11-foss-2023a-R-4.3.2.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.7-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.24.5-GCCcore-12.3.0.eb
Labels: new

#20538 {bio}[foss/2023a] MOFA2 v1.14.0 w/ R 4.3.2
  easybuild/easyconfigs/m/MOFA2/MOFA2-1.14.0-foss-2023a-R-4.3.2.eb
Labels: new

#20406 {devel,lib}[GCC/13.2.0] poppler v24.04.0, texlive v20230313
  easybuild/easyconfigs/g/gnupg-bundle/gnupg-bundle-20240306-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/poppler/poppler-24.04.0-GCC-13.2.0.eb
  easybuild/easyconfigs/t/texlive/texlive-20230313-GCC-13.2.0.eb
Labels: update

#20616 [foss/2023a] dependencies for RoseTTAFold-All-Atom
  easybuild/easyconfigs/b/Brotli-python/Brotli-python-1.0.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/c/CUnit/CUnit-2.1-3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/e/e3nn/e3nn-0.3.3-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/g/GnuTLS/GnuTLS-3.7.8-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/Jansson/Jansson-2.14-GCC-12.3.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/LAPACK/LAPACK-3.12.0-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libedit/libedit-20191231-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libev/libev-4.33-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libgcrypt/libgcrypt-1.10.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libgpg-error/libgpg-error-1.48-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libnsl/libnsl-2.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libtasn1/libtasn1-4.19.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libuv/libuv-1.48.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/Markdown/Markdown-3.6-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/mpmath/mpmath-1.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/n/nghttp2/nghttp2-1.58.0-GCC-12.3.0.eb
  easybuild/easyconfigs/n/nghttp3/nghttp3-1.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/n/ngtcp2/ngtcp2-1.2.0-GCC-12.3.0.eb
  easybuild/easyconfigs/p/PSIPRED/PSIPRED-4.02-GCC-12.3.0.eb
  easybuild/easyconfigs/p/p11-kit/p11-kit-0.25.3-GCCcore-12.3.0.eb
Labels: update

#16792 {geo}[foss/2022a] SciTools-Iris v3.2.1 w/ Python 3.10.4
  easybuild/easyconfigs/s/SciTools-Iris/SciTools-Iris-3.2.1-foss-2022a.eb
Labels: new

#20744 {bio}[GCCcore/12.3.0,foss/2023a] EVcouplings v0.1.1, plmc v20230121 w/ 32bit
  easybuild/easyconfigs/e/EVcouplings/EVcouplings-0.1.1-foss-2023a.eb
  easybuild/easyconfigs/e/EVcouplings/EVcouplings-0.1.1_fix-import-Iterable-Mapping.patch
  easybuild/easyconfigs/p/plmc/plmc-20230121-GCCcore-12.3.0-32bit.eb
Labels: new

#20771 use `libidn2/2.3.7` as dependency for `GnuTLS/3.7.8` and delete `libidn2/2.3.2` (`GCCcore/12.3.0`)
  easybuild/easyconfigs/g/GnuTLS/GnuTLS-3.7.8-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-12.3.0.eb
Labels: bug fix

#20753 {lib}[GCC/13.2.0] planarity v3.0.2.0
  easybuild/easyconfigs/p/planarity/planarity-3.0.2.0-GCC-13.2.0.eb
Labels: new

#20446 {vis}[foss/2022a] EasyMocap v0.2 w/ CUDA 11.7.0
  easybuild/easyconfigs/e/EasyMocap/EasyMocap-0.2-foss-2022a-CUDA-11.7.0.eb
Labels: update

#17690 add missing dependencies for funannotate
  easybuild/easyconfigs/f/funannotate/funannotate-1.8.13-foss-2021b.eb
Labels: bug fix

#20746 {ai,base}[GCCcore/12.3.0,foss/2023a] langchain-anthropic v0.1.15, jiter v0.4.1
  easybuild/easyconfigs/j/jiter/jiter-0.4.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/langchain-anthropic/langchain-anthropic-0.1.15-foss-2023a.eb
Labels: new

#20754 {lib}[foss/2023a] autopep8 v2.2.0, pycodestyle v2.11.1
  easybuild/easyconfigs/a/autopep8/autopep8-2.2.0-foss-2023a.eb
  easybuild/easyconfigs/p/pycodestyle/pycodestyle-2.11.1-foss-2023a.eb
Labels: update

#20757 build both static and shared libs for Brotli 1.1.0
  easybuild/easyconfigs/b/Brotli/Brotli-1.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/b/Brotli/Brotli-1.1.0-GCCcore-13.3.0.eb
Labels: enhancement

#20758 {bio}[GCCcore/13.2.0] alevin-fry v0.9.0
  easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.9.0-GCCcore-13.2.0.eb
Labels: update

#20735 {devel}[GCCcore/12.3.0] glew v2.2.0 w/ egl
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-12.3.0-egl.eb
Labels: update

#20687 Removed timm-0.9.7-foss-2022a-CUDA-11.7.0.eb crate duplicates
  easybuild/easyconfigs/t/timm/timm-0.9.7-foss-2022a-CUDA-11.7.0.eb
Labels: bug fix

#20517 Fix detection of CC/CXX compilers for `wmake` in OpenFOAM v2306 + v2312
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2212-wmake-OpenMPI.patch
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2306-foss-2022b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2312-foss-2023a.eb
Labels: bug fix

#20669 {bio}[foss/2023a] ctffind5 v5.0.2
  easybuild/easyconfigs/c/ctffind5/ctffind5-5.0.2-foss-2023a.eb
Labels: update

#20500 {bio}[foss/2021b] Compass v2024.04, anndata v0.9.2, python-libsbml v5.20.2
  easybuild/easyconfigs/a/anndata/anndata-0.9.2-foss-2021b.eb
  easybuild/easyconfigs/c/Compass/Compass-2024.04-foss-2021b.eb
  easybuild/easyconfigs/p/python-libsbml/python-libsbml-5.20.2-foss-2021b.eb
Labels: new, update

#20587 rename tornado-timeouts.patch and add missing authorship
  easybuild/easyconfigs/t/tornado/tornado-6.1_increase-default-timeouts.patch
  easybuild/easyconfigs/t/tornado/tornado-6.3.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/t/tornado/tornado-6.4-GCCcore-13.2.0.eb
Labels: code cleanup

#20346 {devel}[gompi/2023a] amdahl v0.3.1
  easybuild/easyconfigs/a/amdahl/amdahl-0.3.1-gompi-2023a.eb
Labels: new

#20619 {lib}[GCCcore/12.3.0] makefun 1.15.2
  easybuild/easyconfigs/m/makefun/makefun-1.15.2-GCCcore-12.3.0.eb
Labels: new

#20696 {bio}[foss/2023a] lil-aretomo v0.1.1
  easybuild/easyconfigs/l/lil-aretomo/lil-aretomo-0.1.1-foss-2023a.eb
Labels: new

#20722 remove easyconfigs for CellBender v0.3.1, since this version has been redacted due to a serious bug
  easybuild/easyconfigs/c/CellBender/CellBender-0.3.1-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/c/CellBender/CellBender-0.3.1-foss-2022a.eb
Labels: bug fix, change

#20705 {bio}[foss/2022a] ProteinMPNN v1.0.1_20230627
  easybuild/easyconfigs/p/ProteinMPNN/ProteinMPNN-1.0.1-20230627-foss-2022a-CUDA-11.7.0.eb
Labels: new

#20298 Fix Highway 1.0.3 on some systems by disabling `AVX3_DL`
  easybuild/easyconfigs/h/Highway/Highway-1.0.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/h/Highway/Highway-1.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/h/Highway/Highway-1.0.3_disable_AVX3_DL.patch
Labels: bug fix

#20131 {math}[foss/2023a] JAGS v4.3.2
  easybuild/easyconfigs/j/JAGS/JAGS-4.3.2-foss-2023a.eb
Labels: update

#20304 {devel}[GCCcore/13.2.0] line_profiler v4.1.2
  easybuild/easyconfigs/l/line_profiler/line_profiler-4.1.2-GCCcore-13.2.0.eb
Labels: update

#20775 Fix fastparquet v2023.4.0 using `CargoPythonBundle` easyblock
  easybuild/easyconfigs/f/fastparquet/fastparquet-2023.4.0-gfbf-2022b.eb
Labels: bug fix

#19914 {ai}[foss/2023a] skorch v0.15.0, Braindecode v0.8.1 w/ PyTorch 2.1.2 CUDA 12.1.1
  easybuild/easyconfigs/b/Braindecode/Braindecode-0.8.1-foss-2023a-PyTorch-2.1.2-CUDA-12.1.1.eb
  easybuild/easyconfigs/s/skorch/skorch-0.15.0-foss-2023a-PyTorch-2.1.2-CUDA-12.1.1.eb
Labels: update

#20751 prevent configure script of recent BLAST+ versions from prepending system paths to $PATH
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.13.0-gompi-2022a.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.0-gompi-2022b.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.1-gompi-2023a.eb
Labels: bug fix, EESSI

#20404 [foss/2023a] PLINK-2.00a3.7 bugfix
  easybuild/easyconfigs/p/PLINK/PLINK-2.00a3.7-foss-2022a.eb
  easybuild/easyconfigs/p/PLINK/PLINK-2.00a3.7-gfbf-2023a.eb
Labels: bug fix

#19776 {compiler,tools}[GCCcore/13.2.0] Clang v17.0.6
  easybuild/easyconfigs/c/Clang/Clang-17.0.6-GCCcore-13.2.0.eb
Labels: update

#20434 add patch to increase compatibility with AVX512 platforms for bwa-mem2 v2.2.1
  easybuild/easyconfigs/b/bwa-mem2/bwa-mem2-2.2.1-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/b/bwa-mem2/bwa-mem2-2.2.1_common_avx512_flags.patch
Labels: bug fix

#20678 {bio}[GCCcore/12.2.0] preseq 3.2.0
  easybuild/easyconfigs/p/preseq/preseq-3.2.0-GCC-12.2.0.eb
Labels: update

#20749 make sure mummerplot can use gnuplot if available for recent MUMmer
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0rc1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0rc1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0rc1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MUMmer/MUMmer-4.0.0rc1-GCCcore-12.3.0.eb
Labels: bug fix

#20710 add missing HDF5 dependency in recent Armadillo easyconfigs (>= 11.4.3)
  easybuild/easyconfigs/a/Armadillo/Armadillo-11.4.3-foss-2022a.eb
  easybuild/easyconfigs/a/Armadillo/Armadillo-11.4.3-foss-2022b.eb
  easybuild/easyconfigs/a/Armadillo/Armadillo-12.6.2-foss-2023a.eb
  easybuild/easyconfigs/a/Armadillo/Armadillo-12.8.0-foss-2023b.eb
Labels: bug fix

#20778 {tools}[system/system] Nextflow v24.04.2
  easybuild/easyconfigs/n/Nextflow/Nextflow-24.04.2.eb
Labels: update

#20504 remove TORCHVISION_INCLUDE from PyTorch-bundle easyconfigs
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a.eb
Labels: enhancement

#19398 {tools}[foss/2023a] pyiron v0.5.1 w/ Python 3.11.3
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.1-foss-2023a.eb
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.1_fix-atomistics-requirements.patch
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.1_fix-pyiron-atomistics-version.patch
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.1_fix-pyiron-base-version.patch
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.1_fix-pylammpsmpi.patch
  easybuild/easyconfigs/q/QuickFF/QuickFF-2.2.7-foss-2023a.eb
  easybuild/easyconfigs/t/TAMkin/TAMkin-1.2.6-foss-2023a.eb
Labels: update

#20792 {debugger}[gompi/2023b] Valgrind v3.23.0
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.23.0-gompi-2023b.eb
Labels: update

#20791 {bio}[GCCcore/12.3.0] currentNe v1.0.0
  easybuild/easyconfigs/c/currentNe/currentNe-1.0.0-GCCcore-12.3.0.eb
Labels: new

#20785 {tools}[foss/2023a] adjustText v1.1.1
  easybuild/easyconfigs/a/adjustText/adjustText-1.1.1-foss-2023a.eb
Labels: update

#20767 {geo}[foss/2023a] SciTools-Iris v3.9.0
  easybuild/easyconfigs/s/SciTools-Iris/SciTools-Iris-3.9.0-foss-2023a.eb
Labels: new

#20794 comment out PSM2 dependency in recent libfabric easyconfigs, since it pulls in CUDA as dependency
  easybuild/easyconfigs/l/libfabric/libfabric-1.12.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.13.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.13.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.13.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.15.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.16.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.18.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.19.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-1.21.0-GCCcore-13.3.0.eb
Labels: change

#20795 add patch to fix build of pdsh 2.34 with Slurm 23.x
  easybuild/easyconfigs/p/pdsh/pdsh-2.34-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pdsh/pdsh-2.34-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pdsh/pdsh-2.34-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pdsh/pdsh-2.34_fix-slurm-23.x.patch
Labels: bug fix

#20784 remove `--with-64` from `configopts` for recent BLAST+ versions
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.13.0-gompi-2022a.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.0-gompi-2022b.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.1-gompi-2023a.eb
Labels: bug fix, EESSI, aarch64

#20764 {geo}[foss/2023a] regionmask v0.12.1
  easybuild/easyconfigs/r/regionmask/regionmask-0.12.1-foss-2023a.eb
Labels: update

#20786 {chem}[foss/2023a] DL_POLY_4 v5.1.0
  easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.1.0-foss-2023a.eb
Labels: update

#20765 {lib}[GCC/13.2.0,intel-compilers/2023.2.1] json-fortran v8.5.2
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.5.2-GCC-13.2.0.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-8.5.2-intel-compilers-2023.2.1.eb
Labels: update

#20789 add 'pic' flag to IML
  easybuild/easyconfigs/i/IML/IML-1.0.5-gfbf-2023b.eb
Labels: bug fix

#20513 {bio}[system/system] bcl-convert v4.2.7-2 w/ el7.x86_64
  easybuild/easyconfigs/b/bcl-convert/bcl-convert-4.2.7-2el7.x86_64.eb
Labels: update

#20781 archive outdated example easyconfigs for Fujitsu toolchain
  easybuild/easyconfigs/__archive__/a/Autoconf/Autoconf-2.71-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/a/Automake/Automake-1.16.3-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/a/Autotools/Autotools-20210128-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/b/Bison/Bison-3.7.6-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/b/binutils/binutils-2.36.1-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/b/buildenv/buildenv-default-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/b/buildenv/buildenv-default-Fujitsu-21.05.eb
  easybuild/easyconfigs/__archive__/d/DB/DB-18.1.40-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/e/expat/expat-2.2.9-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/f/FCC/FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/f/FFTW/FFTW-1.0.0-FCC-4.5.0-fujitsu.eb
  easybuild/easyconfigs/__archive__/f/Fujitsu/Fujitsu-21.05.eb
  easybuild/easyconfigs/__archive__/f/ffmpi/ffmpi-4.5.0.eb
  easybuild/easyconfigs/__archive__/f/flex/flex-2.6.4-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/g/groff/groff-1.22.4-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/h/HPL/HPL-2.3-Fujitsu-21.05.eb
  easybuild/easyconfigs/__archive__/h/help2man/help2man-1.48.3-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/l/libreadline/libreadline-8.1-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/l/libtool/libtool-2.4.6-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/m/M4/M4-1.4.18-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/m/makeinfo/makeinfo-6.7-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/n/ncurses/ncurses-6.2-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-ffmpi-4.5.0.eb
  easybuild/easyconfigs/__archive__/p/Perl/Perl-5.32.1-FCC-4.5.0.eb
  easybuild/easyconfigs/__archive__/z/zlib/zlib-1.2.11-FCC-4.5.0.eb
Labels: change, code cleanup

#20796 prepare release notes for EasyBuild v4.9.2 + bump version to 4.9.2
  RELEASE_NOTES
  setup.py
Labels: update, documentation

#20777 {bio}[foss/2023a] scFEA v1.1-20221109, MAGIC v3.0.0
  easybuild/easyconfigs/m/MAGIC/MAGIC-3.0.0-foss-2023a.eb
  easybuild/easyconfigs/s/scFEA/scFEA-1.1-20221109-foss-2023a.eb
Labels: new

#20801 {tools}[system/system] EasyBuild v4.9.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.9.2.eb
Labels: update

#20812 sync with main + bump version to 4.9.3dev
  RELEASE_NOTES
  setup.py
Labels: update

#20803 {bio}[foss/2023a] CellOracle v0.18.0, velocyto v0.17.17, genomepy v0.16.1, ...
  easybuild/easyconfigs/c/CellOracle/CellOracle-0.18.0-foss-2023a.eb
  easybuild/easyconfigs/g/GimmeMotifs/GimmeMotifs-0.17.2-foss-2023a.eb
  easybuild/easyconfigs/g/genomepy/genomepy-0.16.1-foss-2023a.eb
  easybuild/easyconfigs/h/HTSeq/HTSeq-2.0.7-foss-2023a.eb
  easybuild/easyconfigs/m/mygene/mygene-3.2.2-foss-2023a.eb
  easybuild/easyconfigs/v/velocyto/velocyto-0.17.17-foss-2023a.eb
Labels: update

#20804 Add internal CUDA header patch for PSM2
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PSM2/PSM2-12.0.1_build-with-internal-cuda-header.patch
Labels: enhancement

#20818 rename unpacked sources for components of EasyBuild v4.9.2, to ensure that '`--install-latest-eb-release`' works with older EasyBuild versions
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.9.2.eb
Labels: bug fix

#20819 {chem}[system/system] DL_POLY_Classic_GUI v1.10
  easybuild/easyconfigs/d/DL_POLY_Classic_GUI/DL_POLY_Classic_GUI-1.10.eb
Labels: new

#20813 {devel}[system/system] Maven v3.9.7
  easybuild/easyconfigs/m/Maven/Maven-3.9.7.eb
Labels: update

#20806 {vis}[GCC/12.3.0] MeshLab v2023.12
  easybuild/easyconfigs/m/MeshLab/MeshLab-2023.12-GCC-12.3.0.eb
Labels: new

#18741 {geo}[foss/2023a] WRF v4.5.1 w/ dmpar
  easybuild/easyconfigs/w/WRF/WRF-4.5.1-foss-2023a-dmpar.eb
  easybuild/easyconfigs/w/WRF/WRF-4.5.1_netCDF-Fortran_separate_path.patch
Labels: update

#20820 fix build of OpenBLAS 0.3.24 on A64FX
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.24-GCC-13.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.24_fix-A64FX.patch
Labels: bug fix, EESSI, aarch64

#20808 {bio}[foss/2023a] IEntropy v2024.06.12 w/ R 4.3.2
  easybuild/easyconfigs/i/IEntropy/IEntropy-2024.06.12-foss-2023a-R-4.3.2.eb
Labels: new

#20822 {lib}[foss/2023a] PyTorch-Geometric v2.5.0 w/ PyTorch 2.1.2
  easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-2.5.0-foss-2023a-PyTorch-2.1.2.eb
Labels: update

#20810 {system}[system/system] CUDA v12.5.0
  easybuild/easyconfigs/c/CUDA/CUDA-12.5.0.eb
Labels: update

#20802 {chem}[foss/2023a,gfbf/2023a] GPAW v24.6.0, ASE v3.23.0
  easybuild/easyconfigs/a/ASE/ASE-3.23.0-gfbf-2023a.eb
  easybuild/easyconfigs/g/GPAW/GPAW-24.6.0-foss-2023a-ASE-3.23.0.eb
Labels: update

#20821 {bio}[GCCcore/12.2.0] NanoCaller v3.6.0, WFA2 v2.3.4, vcflib v1.0.9, ... w/ R 4.2.2
  easybuild/easyconfigs/f/fastahack/fastahack-1.0.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/filevercmp/filevercmp-20191210-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/fsom/fsom-20151117-GCCcore-12.2.0.eb
  easybuild/easyconfigs/i/intervaltree/intervaltree-0.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-5.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/multichoose/multichoose-1.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/n/NanoCaller/NanoCaller-3.6.0-foss-2022b.eb
  easybuild/easyconfigs/s/smithwaterman/smithwaterman-20160702-GCCcore-12.2.0.eb
  easybuild/easyconfigs/t/tabixpp/tabixpp-1.1.2-GCC-12.2.0.eb
  easybuild/easyconfigs/v/vcflib/vcflib-1.0.9-foss-2022b-R-4.2.2.eb
  easybuild/easyconfigs/w/WFA2/WFA2-2.3.4-GCCcore-12.2.0.eb
Labels: update

#20741 {tools}[GCCcore/13.2.0] jupyter-collaboration v2.1.1
  easybuild/easyconfigs/j/jupyter-collaboration/jupyter-collaboration-2.1.1-GCCcore-13.2.0.eb
Labels: new

#20759 {ai}[foss/2023a] langchain-mistralai v0.1.8
  easybuild/easyconfigs/l/langchain-mistralai/langchain-mistralai-0.1.8-foss-2023a.eb
Labels: new

#20811 {lib}[GCCcore/13.2.0] UCX-CUDA v1.15.0 w/ CUDA 12.5.0
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.15.0-GCCcore-13.2.0-CUDA-12.5.0.eb
Labels: update

#20711 {lib}[foss/2023a] langchain-openai v0.1.8, openai-python v1.30.5, tiktoken v0.7.0
  easybuild/easyconfigs/l/langchain-openai/langchain-openai-0.1.8-foss-2023a.eb
  easybuild/easyconfigs/o/openai-python/openai-python-1.30.5-foss-2023a.eb
  easybuild/easyconfigs/t/tiktoken/tiktoken-0.7.0-GCCcore-12.3.0.eb
Labels: new, update

#20823 add support for JupyterHub to TensorBoard
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.10.0-foss-2022a.eb
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.10_jupyterhub-support.patch
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.15.1-gfbf-2023a.eb
Labels: enhancement

#20826 {tools}[GCCcore/13.3.0] poetry v1.8.3, hatchling v1.24.2, virtualenv v20.26.2, ...
  easybuild/easyconfigs/c/cryptography/cryptography-42.0.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/h/hatchling/hatchling-1.24.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/maturin/maturin-1.6.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/poetry/poetry-1.8.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/scikit-build/scikit-build-0.17.6-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.9.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/v/virtualenv/virtualenv-20.26.2-GCCcore-13.3.0.eb
Labels: update, 2024a

#20827 {lang,tools}[GCCcore/13.3.0] Python-bundle-PyPI v2024.06, flit v3.9.0
  easybuild/easyconfigs/f/flit/flit-3.9.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb
Labels: update, 2024a

#20825 Remove maturin build dependency from langchain-antropic
  easybuild/easyconfigs/l/langchain-anthropic/langchain-anthropic-0.1.15-foss-2023a.eb
Labels: bug fix

#20829 {lib}[GCC/13.3.0] pybind11 v2.12.0, Catch2 v2.13.10
  easybuild/easyconfigs/c/Catch2/Catch2-2.13.10-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.12.0-GCC-13.3.0.eb
Labels: update

#20830 {lang}[gfbf/2024.05] SciPy-bundle v2024.05, meson-python v0.16.0, hypothesis v6.103.1
  easybuild/easyconfigs/h/hypothesis/hypothesis-6.103.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/meson-python/meson-python-0.16.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024.05.eb
  easybuild/easyconfigs/s/SciPy-bundle/numexpr-2.10.0_fix-numpy-1.x.patch
Labels: update, 2024a

#20435 add 'archive' extra to optionally install easybuild-easyconfigs-archive
  setup.py
Labels: EasyBuild-5.0

#20837 {math}[foss/2023b] PaStiX v6.3.2
  easybuild/easyconfigs/p/PaStiX/PaStiX-6.3.2-foss-2023b.eb
Labels: update

#20838 {math}[iimpi/2023b,intel/2023b] SCOTCH v7.0.4, PaStiX v6.3.2
  easybuild/easyconfigs/p/PaStiX/PaStiX-6.3.2-intel-2023b.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.4-iimpi-2023b.eb
Labels: update

#20833 {chem}[foss/2023a] Critic2 v1.2
  easybuild/easyconfigs/c/Critic2/Critic2-1.2-foss-2023a.eb
Labels: new

#20642 {ai}[gfbf/2023a] Safetensors v0.4.3
  easybuild/easyconfigs/s/Safetensors/Safetensors-0.4.3-gfbf-2023a.eb
Labels: update

#20817 Fix build error with numpy with some compilers
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-foss-2021a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-gomkl-2021a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-intel-2021a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-foss-2021b-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-foss-2021b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-intel-2021b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-foss-2022.05.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-foss-2022a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-intel-2022.05.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-intel-2022a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.02-gfbf-2022b.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.07-gfbf-2023a.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.07-iimkl-2023a.eb
  easybuild/easyconfigs/s/SciPy-bundle/numpy-1.20.3_fix-fortran-compiler-error.patch
Labels: bug fix

#20774 {data}[foss/2023a] spaCy v3.7.4
  easybuild/easyconfigs/s/spaCy/spaCy-3.7.4-foss-2023a.eb
Labels: update

#20842 {tools}[GCCcore/12.2.0,GCCcore/12.3.0,GCCcore/13.2.0] DMTCP v3.0.0
  easybuild/easyconfigs/d/DMTCP/DMTCP-3.0.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/d/DMTCP/DMTCP-3.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/d/DMTCP/DMTCP-3.0.0-GCCcore-13.2.0.eb
Labels: update

#20788 {lib,math}[foss/2023b] rankwidth v0.9, igraph v0.10.12
  easybuild/easyconfigs/i/igraph/igraph-0.10.12-foss-2023b.eb
  easybuild/easyconfigs/r/rankwidth/rankwidth-0.9-foss-2023b.eb
Labels: new, update

#20840 {chem}[foss/2023a] AmberTools v23.6
  easybuild/easyconfigs/a/AmberTools/AmberTools-23.6-foss-2023a.eb
Labels: update

#20420 {tools}[foss/2023a] Gymnasium v0.29.1
  easybuild/easyconfigs/g/Gymnasium/Gymnasium-0.29.1-foss-2023a.eb
Labels: new

#20650 {geo}[gmpich/2024.06] GeoDict v2024.SP2
  easybuild/easyconfigs/g/GeoDict/GeoDict-2024.SP2-gmpich-2024.06.eb
  easybuild/easyconfigs/g/gmpich/gmpich-2024.06.eb
  easybuild/easyconfigs/m/MPICH/MPICH-4.2.1-GCC-12.3.0.eb
Labels: new, update

#20845 {bio}[GCC/13.2.0,foss/2023b] python-parasail v1.3.4, parasail v2.6.2
  easybuild/easyconfigs/p/parasail/parasail-2.6.2-GCC-13.2.0.eb
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.3.4-foss-2023b.eb
Labels: update

#20844 {bio,lib}[GCC/13.2.0] pyspoa v0.2.1, spoa v4.1.0
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.2.1-GCC-13.2.0.eb
  easybuild/easyconfigs/s/spoa/spoa-4.1.0-GCC-13.2.0.eb
Labels: update

#20841 add GMP and MPFR as dependencies to OpenFOAM v2306 and v2312
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2306-foss-2022b.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2312-foss-2023a.eb
Labels: bug fix, EESSI

#20848 {tools}[gfbf/2023a] imbalanced-learn v0.12.3
  easybuild/easyconfigs/i/imbalanced-learn/imbalanced-learn-0.12.3-gfbf-2023a.eb
Labels: update

#20636 {vis}[foss/2023a] micro-sam v1.0.1, torch_em v0.7.1, affogato v0.3.3, ...
  easybuild/easyconfigs/a/affogato/affogato-0.3.3-foss-2023a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.82.0-GCC-12.3.0.eb
  easybuild/easyconfigs/m/micro-sam/micro-sam-1.0.1-foss-2023a.eb
  easybuild/easyconfigs/n/nifty/nifty-1.2.1-foss-2023a.eb
  easybuild/easyconfigs/p/pycocotools/pycocotools-2.0.7-foss-2023a.eb
  easybuild/easyconfigs/p/python-blosc/python-blosc-1.11.0-foss-2023a.eb
  easybuild/easyconfigs/p/python-elf/python-elf-0.5.1-foss-2023a.eb
  easybuild/easyconfigs/s/segment-anything/segment-anything-1.0-foss-2023a.eb
  easybuild/easyconfigs/t/torch-em/torch-em-0.7.1-foss-2023a.eb
  easybuild/easyconfigs/v/vigra/vigra-1.11.2-foss-2023a.eb
  easybuild/easyconfigs/x/xtensor/xtensor-0.24.7-foss-2023a.eb
  easybuild/easyconfigs/z/z5py/z5py-2.0.17-foss-2023a.eb
Labels: new, update

#20387 {devel}[GCCcore/11.3.0,GCCcore/12.2.0,GCCcore/12.3.0,GCCcore/13.2.0] mm-common v1.0.6, libsigc++ v3.6.0, GLibmm v2.72.1
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.72.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.75.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.77.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GLibmm/GLibmm-2.78.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-3.6.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-3.6.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libsigc++/libsigc++-3.6.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/mm-common/mm-common-1.0.6-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/mm-common/mm-common-1.0.6-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/mm-common/mm-common-1.0.6-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/mm-common/mm-common-1.0.6-GCCcore-13.2.0.eb
Labels: update

#20454 {vis}[foss/2023a] empanada-napari v1.1.0, empanada-dl v0.1.7, connected-components-3d v3.14.1, Albumentations v1.4.0
  easybuild/easyconfigs/a/Albumentations/Albumentations-1.4.0-foss-2023a.eb
  easybuild/easyconfigs/c/connected-components-3d/connected-components-3d-3.14.1-foss-2023a.eb
  easybuild/easyconfigs/e/empanada-dl/empanada-dl-0.1.7-foss-2023a.eb
  easybuild/easyconfigs/e/empanada-napari/empanada-napari-1.1.0-foss-2023a.eb
Labels: new, update

#20861 {tools}[system/system] rpmrebuild v2.18
  easybuild/easyconfigs/b/bcl-convert/bcl-convert-4.2.7-2el7.x86_64.eb
  easybuild/easyconfigs/r/rpmrebuild/rpmrebuild-2.18.eb
Labels: update, change

#20864 Switch transformers to use external Safetensor dep
  easybuild/easyconfigs/t/Transformers/Transformers-4.39.3-gfbf-2023a.eb
Labels: change

#20876 {tools}[GCCcore/12.3.0,system/system] jupyter-vscode-proxy v0.6, code-server v4.90.2
  easybuild/easyconfigs/c/code-server/code-server-4.90.2.eb
  easybuild/easyconfigs/j/jupyter-vscode-proxy/jupyter-vscode-proxy-0.6-GCCcore-12.3.0.eb
Labels: new, update

#20800 {bio}[foss/2022b] HOMER v4.11.1, IMAGE v1.1, Kent_tools v461, weblogo v2.8.2
  easybuild/easyconfigs/h/HOMER/HOMER-4.11.1-foss-2022b.eb
  easybuild/easyconfigs/i/IMAGE/IMAGE-1.1-foss-2022b.eb
  easybuild/easyconfigs/k/Kent_tools/Kent_tools-461-GCC-12.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/w/weblogo/weblogo-2.8.2-foss-2022b.eb
  easybuild/easyconfigs/w/wget/wget-1.21.4-GCCcore-12.2.0.eb
Labels: new, update

#20856 {cae}[foss/2022a] OpenFOAM v10 w/ 20230119 int64
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-foss-2022a-20230119-int64.eb
Labels: update

#20862 {numlib}[foss/2023b] SuiteSparse v7.7.0 w/ METIS 5.1.0
  easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.7.0-foss-2023b-METIS-5.1.0.eb
Labels: update

#20870 {tools}[GCC/12.3.0] ega-quickview v20240620, FUSE v3.16.2, crypt4gh v1.7
  easybuild/easyconfigs/c/crypt4gh/crypt4gh-1.7-GCC-12.3.0.eb
  easybuild/easyconfigs/e/ega-quickview/ega-quickview-20240620-GCC-12.3.0.eb
  easybuild/easyconfigs/f/FUSE/FUSE-3.16.2-GCCcore-12.3.0.eb
Labels: new

#20675 {lib}[GCCcore/13.2.0] Brunsli v0.1, GDAL v3.9.0, libgeotiff v1.7.3, ...
  easybuild/easyconfigs/b/Brunsli/Brunsli-0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.9.0-foss-2023b.eb
  easybuild/easyconfigs/g/GEOS/GEOS-3.12.1-GCC-13.2.0.eb
  easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.7.3-GCCcore-13.2.0.eb
Labels: update

#20853 {tools}[GCCcore/12.3.0] pyperf v2.7.0
  easybuild/easyconfigs/p/pyperf/pyperf-2.7.0-GCCcore-12.3.0.eb
Labels: update

#20874 Skip unreliable memory leak test in PyTorch 2.1.2
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2022a.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2022b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_skip-memory-leak-test.patch
Labels: bug fix

#20849 {numlib}[GCCcore/13.2.0] Triangle v1.6
  easybuild/easyconfigs/t/Triangle/Triangle-1.6-GCCcore-13.2.0.eb
Labels: update

#20884 {math}[foss/2023a] Stable-Baselines3 v2.3.2
  easybuild/easyconfigs/s/Stable-Baselines3/Stable-Baselines3-2.3.2-foss-2023a.eb
Labels: new

#20887 {lib}[GCCcore/13.2.0] JsonCpp v1.9.5
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.5-GCCcore-13.2.0.eb
Labels: update

#20860 {math}[system/system] MCR vR2024a w/ .4
  easybuild/easyconfigs/m/MCR/MCR-R2024a.4.eb
Labels: update

#20888 rename ega-quickview to EGA-QuickView
  easybuild/easyconfigs/e/EGA-QuickView/EGA-QuickView-20240620-GCC-12.3.0.eb
Labels: bug fix, change

#20886 {vis}[foss/2023a] histolab v0.7.0
  easybuild/easyconfigs/h/histolab/histolab-0.7.0-foss-2023a.eb
Labels: update

#20889 {math}[gfbf/2023b] pystencils v1.3.4
  easybuild/easyconfigs/p/pystencils/pystencils-1.3.4-gfbf-2023b.eb
Labels: new

#20893 {lib}[GCCcore/13.2.0] FLAC v1.4.3, libogg v1.3.5, libopus v1.5.2, ...
  easybuild/easyconfigs/f/FLAC/FLAC-1.4.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libogg/libogg-1.3.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libopus/libopus-1.5.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.2.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libvorbis/libvorbis-1.3.7-GCCcore-13.2.0.eb
Labels: update

#20895 {vis}[foss/2022a] histolab v0.6.0
  easybuild/easyconfigs/h/histolab/histolab-0.6.0-foss-2022a.eb
Labels: update

#20892 {vis}[GCCcore/13.2.0] ImageMagick v7.1.1-34
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-34-GCCcore-13.2.0.eb
Labels: update

#20900 make sure that recent ImageMagick versions pick up the right pkgconf and improve the sanity checks
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-37-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-53-GCCcore-12.2.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-15-GCCcore-12.3.0.eb
Labels: enhancement

#20891 {lib}[GCCcore/13.2.0] Arrow v16.1.0, utf8proc v2.9.0, RapidJSON v1.1.0-20240409
  easybuild/easyconfigs/a/Arrow/Arrow-16.1.0-gfbf-2023b.eb
  easybuild/easyconfigs/r/RapidJSON/RapidJSON-1.1.0-20240409-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/utf8proc/utf8proc-2.9.0-GCCcore-13.2.0.eb
Labels: update

#20787 {math}[foss/2023b,gfbf/2023b] gap v4.13.0, Normaliz v3.10.3
  easybuild/easyconfigs/g/gap/gap-4.13.0-foss-2023b.eb
  easybuild/easyconfigs/n/Normaliz/Normaliz-3.10.3-gfbf-2023b.eb
Labels: update

#20881 {bio}[foss/2023a] pyGenomeTracks v3.9, cooler v0.10.2, HiCMatrix v17.2 + use PyPI source tarball and `gfbf/2023a` toolchain for pyBigWig
  easybuild/easyconfigs/c/cooler/cooler-0.10.2-foss-2023a.eb
  easybuild/easyconfigs/h/HiCMatrix/HiCMatrix-17.2-foss-2023a.eb
  easybuild/easyconfigs/p/pyBigWig/pyBigWig-0.3.22-foss-2023a.eb
  easybuild/easyconfigs/p/pyBigWig/pyBigWig-0.3.22-gfbf-2023a.eb
  easybuild/easyconfigs/p/pyGenomeTracks/pyGenomeTracks-3.9-foss-2023a.eb
  easybuild/easyconfigs/t/TOBIAS/TOBIAS-0.16.1-foss-2023a.eb
Labels: bug fix, update

#20814 {bio}[foss/2023a] scArches v0.6.1, scib-metrics v0.5.1, scvi-tools v1.1.2, ...
  easybuild/easyconfigs/j/jax/jax-0.4.25-foss-2023a.eb
  easybuild/easyconfigs/j/jax/jax-0.4.25_fix-pybind11-systemlib.patch
  easybuild/easyconfigs/j/jax/jax-0.4.25_fix_env_test_no_log_spam.patch
  easybuild/easyconfigs/m/ml-collections/ml-collections-0.1.1-foss-2023a.eb
  easybuild/easyconfigs/o/Optax/Optax-0.2.2-foss-2023a.eb
  easybuild/easyconfigs/s/scArches/scArches-0.6.1-foss-2023a.eb
  easybuild/easyconfigs/s/scib-metrics/scib-metrics-0.5.1-foss-2023a.eb
  easybuild/easyconfigs/s/scvi-tools/scvi-tools-1.1.2-foss-2023a.eb
Labels: update

#20903 {compiler}[system/system] intel-compilers v2024.2.0
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2024.2.0.eb
Labels: update

#20904 {numlib}[system/system] imkl v2024.2.0
  easybuild/easyconfigs/i/imkl/imkl-2024.2.0.eb
Labels: update

#20917 {perf}[intel-compilers/2024.2.0] STREAM v5.10
  easybuild/easyconfigs/s/STREAM/STREAM-5.10-intel-compilers-2024.2.0.eb
Labels: update

#20918 also install utilities for recent versions of FUSE 3.x
  easybuild/easyconfigs/f/FUSE/FUSE-3.14.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/FUSE/FUSE-3.14.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/FUSE/FUSE-3.16.2-GCCcore-12.3.0.eb
Labels: enhancement

#20905 Remove CMake Arrow flag as there is no Arrow dependency in recent GDAL easyconfigs
  easybuild/easyconfigs/g/GDAL/GDAL-3.6.2-foss-2022b.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.7.1-foss-2023a.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.9.0-foss-2023b.eb
Labels: code cleanup

#20915 {bio}[system/system] IGV v2.17.4 w/ Java 17
  easybuild/easyconfigs/i/IGV/IGV-2.17.4-Java-17.eb
Labels: update

#20909 {bio}[gompi/2023b] file v5.43, ncbi-vdb v3.1.1, SRA-Toolkit v3.1.1
  easybuild/easyconfigs/f/file/file-5.43-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.1.1-gompi-2023b.eb
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-3.1.1-gompi-2023b.eb
Labels: update

#20923 {numlib}[foss/2023b] SuperLU v6.0.1
  easybuild/easyconfigs/s/SuperLU/SuperLU-6.0.1-foss-2023b.eb
Labels: update

#20925 {lang}[system/system] Miniconda3 v23.10.0-1
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-23.10.0-1.eb
Labels: update
