Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2024-12, with the labels that each got.

#21916 {tools}[GCCcore/13.3.0] time v1.9
  easybuild/easyconfigs/t/time/time-1.9-GCCcore-13.3.0.eb
Labels: update

#21883 {bio}[gompi/2023a] IQ-TREE v2.3.6
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.3.6-gompi-2023a.eb
Labels: update

#21944 use original sources for enchant-2
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.6.5-GCCcore-12.3.0.eb
Labels: change

#21888 {tools,geo,lib}[foss/2024a] ANTLR v2.7.7, ESMF 8.7.0, libdap v3.21.0-131, NCO v5.2.9
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-13.3.0-Java-21.0.2.eb
  easybuild/easyconfigs/e/ESMF/ESMF-8.7.0-foss-2024a.eb
  easybuild/easyconfigs/l/libdap/libdap-3.21.0-131-GCCcore-13.3.0.eb
  easybuild/easyconfigs/n/NCO/NCO-5.2.9-foss-2024a.eb
Labels: update

#21953 {bio}[GCC/13.3.0] Bio-DB-HTS v3.01
  easybuild/easyconfigs/b/Bio-DB-HTS/Bio-DB-HTS-3.01-GCC-13.3.0.eb
Labels: update

#21952 {tools}[GCCcore/13.2.0,GCCcore/13.3.0] Archive-Zip v1.68
  easybuild/easyconfigs/a/Archive-Zip/Archive-Zip-1.68-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/Archive-Zip/Archive-Zip-1.68-GCCcore-13.3.0.eb
Labels: update

#21955 {bio}[GCC/13.3.0] VEP v113.3
  easybuild/easyconfigs/v/VEP/VEP-113.3-GCC-13.3.0.eb
Labels: update

#21866 {chem}[foss/2024a] QuantumESPRESSO v7.4
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-d3q.patch
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-foss-2024a.eb
Labels: update

#21817 {tools}[foss/2024a] Optuna v4.1.0
  easybuild/easyconfigs/o/Optuna/Optuna-4.1.0-foss-2024a.eb
Labels: update

#19524 {perf}[gompi/2022a,gompi/2022b,gompi/2023a] CubeLib v4.8.2, CubeWriter v4.8.2, Score-P v8.3 w/ CUDA 11.7.0, CUDA 12.0.0, ...
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.8.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.8.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.8.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.8.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2022a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2022b-CUDA-12.0.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2022b.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-gompi-2023a.eb
Labels: update

#21951 {math}[foss/2023b] Cbc v2.10.11, Cgl v0.60.8, Clp v1.17.9, CoinUtils v2.11.10, Osi v0.108.9
  easybuild/easyconfigs/c/Cbc/Cbc-2.10.11-foss-2023b.eb
  easybuild/easyconfigs/c/Cgl/Cgl-0.60.8-foss-2023b.eb
  easybuild/easyconfigs/c/Clp/Clp-1.17.9-foss-2023b.eb
  easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.10-GCC-13.2.0.eb
  easybuild/easyconfigs/o/Osi/Osi-0.108.9-GCC-13.2.0.eb
Labels: update

#21967 {lang}[GCCcore/13.3.0] Rust v1.83.0
  easybuild/easyconfigs/r/Rust/Rust-1.83.0-GCCcore-13.3.0.eb
Labels: update

#21915 {vis}[GCC/13.2.0] GST-plugins-base v1.24.8, GStreamer v1.24.8, Paraver v4.11.4, wxWidets v3.2.6
  easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.24.8-GCC-13.2.0.eb
  easybuild/easyconfigs/g/GStreamer/GStreamer-1.24.8-GCC-13.2.0.eb
  easybuild/easyconfigs/p/Paraver/Paraver-4.11.4-GCC-13.2.0.eb
  easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.2.6-GCC-13.2.0.eb
Labels: update

#21925 {bio}[foss/2023a] Tombo v1.5.1
  easybuild/easyconfigs/t/Tombo/Tombo-1.5.1-foss-2023a.eb
Labels: update

#21982 add missing cutadapt dependency for decona 1.4-20240731
  easybuild/easyconfigs/d/decona/decona-1.4-20240731-foss-2023a.eb
Labels: bug fix

#21983 add missing (optional) pyabpoa dependency as extension to medaka 1.11.3
  easybuild/easyconfigs/m/medaka/medaka-1.11.3-foss-2022a.eb
  easybuild/easyconfigs/m/medaka/medaka-1.11.3-foss-2023a.eb
Labels: bug fix

#20834 {vis}[GCCcore/13.2.0] gnuplot v6.0.1, libcerf v2.4
  easybuild/easyconfigs/g/gnuplot/gnuplot-6.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libcerf/libcerf-2.4-GCCcore-13.2.0.eb
Labels: update

#21762 {lib}[GCCcore/13.2.0] orjson v3.10.10
  easybuild/easyconfigs/o/orjson/orjson-3.10.10-GCCcore-13.2.0.eb
Labels: update

#21839 {tools}[GCCcore/12.3.0] fsm-lite v1.0, sdsl-lite v2.0.3
  easybuild/easyconfigs/f/fsm-lite/fsm-lite-1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/sdsl-lite/sdsl-lite-2.0.3-GCCcore-12.3.0.eb
Labels: update

#21608 {data,numlib}[foss/2024a] Armadillo v14.0.3, arpack-ng v3.9.1
  easybuild/easyconfigs/a/Armadillo/Armadillo-14.0.3-foss-2024a.eb
  easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.9.1-foss-2024a.eb
Labels: update, 2024a

#21966 {vis}[gompi/2024a] ncview v2.1.11
  easybuild/easyconfigs/n/ncview/ncview-2.1.11-gompi-2024a.eb
Labels: update

#21918 {bio}[foss/2023a] Monocle3 v1.3.1 w/ R 4.3.2
  easybuild/easyconfigs/m/Monocle3/Monocle3-1.3.1-foss-2023a-R-4.3.2.eb
Labels: update

#21907 {data}[foss/2024a] GDAL v3.10.0
  easybuild/easyconfigs/g/GDAL/GDAL-3.10.0-foss-2024a.eb
Labels: update

#21988 {devel}[foss/2024a] buildenv vdefault w/ CUDA 12.4.0, CUDA 12.6.0
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2023b-CUDA-12.4.0.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2024a-CUDA-12.6.0.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2024a.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-intel-2024a.eb
Labels: update

#21927 {vis}[GCCcore/13.3.0] Graphviz v12.2.0
  easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0.eb
Labels: update

#21614 {data}[foss/2024a] Fiona v1.10.1
  easybuild/easyconfigs/f/Fiona/Fiona-1.10.1-foss-2024a.eb
Labels: update, 2024a

#21950 Fix Boost 1.85 build on PPC
  easybuild/easyconfigs/b/Boost/Boost-1.85.0-GCC-13.3.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.85.0_fix-ppc-charconv.patch
Labels: bug fix

#21848 {lib,tools}[foss/2023a] sdsl-lite v2.1.1, libdivsufsort v2.0.1
  easybuild/easyconfigs/l/libdivsufsort/libdivsufsort-2.0.1-foss-2023a.eb
  easybuild/easyconfigs/s/sdsl-lite/sdsl-lite-2.1.1-foss-2023a.eb
Labels: update

#21897 {tools}[system/system] HyperQueue v0.20.0
  easybuild/easyconfigs/h/HyperQueue/HyperQueue-0.20.0.eb
Labels: update

#21829 {bio}[foss/2023a] HOMER v5.1 w/ R 4.3.2
  easybuild/easyconfigs/h/HOMER/HOMER-5.1-foss-2023a-R-4.3.2.eb
Labels: update

#21995 {geo}[gfbf/2023a] SPEI v0.6.0
  easybuild/easyconfigs/s/SPEI/SPEI-0.6.0-gfbf-2023a.eb
Labels: update

#21989 {devel}[GCCcore/14.2.0] Autotools v20240712, Perl v5.40.0, ...
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.72-GCCcore-14.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.17-GCCcore-14.2.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.17_perl_env_space.patch
  easybuild/easyconfigs/a/Autotools/Autotools-20240712-GCCcore-14.2.0.eb
  easybuild/easyconfigs/e/expat/expat-2.6.4-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/groff/groff-1.23.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.5.4-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Crypt-DES-2.07_expose-perl_des_expand_key-and-perl_des_crypt.patch
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.40.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/XML-Bare-0.53_c99.patch
  easybuild/easyconfigs/p/Perl/Perl-5.40.0-GCCcore-14.2.0.eb
Labels: update

#21990 {bio}[GCC/13.2.0] L_RNA_scaffolder v20190530
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-13.2.0.eb
  easybuild/easyconfigs/d/DB_File/DB_File-1.859-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/L_RNA_scaffolder/L_RNA_scaffolder-20190530-GCC-13.2.0.eb
Labels: update

#21992 {bio}[GCC/13.2.0] KMC v3.2.4
  easybuild/easyconfigs/k/KMC/KMC-3.2.4-GCC-13.2.0.eb
  easybuild/easyconfigs/k/KMC/KMC-3.2.4_use_EB_pybind11_and_libs.patch
Labels: update

#21834 {bio}[gompi/2023a] Kraken2 v2.1.3
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.3-gompi-2023a.eb
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.3_fix_installation_for_easybuild.patch
Labels: update

#21998 use proper release of MATES v0.1.5
  easybuild/easyconfigs/m/MATES/MATES-0.1.5-foss-2023b.eb
Labels: bug fix, change

#21801 {bio}[GCC/12.3.0] VEP v113.0, Archive-Zip v1.68, Bio-DB-HTS v3.01, Compress-Raw-Zlib v2.213
  easybuild/easyconfigs/a/Archive-Zip/Archive-Zip-1.68-GCCcore-12.3.0.eb
  easybuild/easyconfigs/b/Bio-DB-HTS/Bio-DB-HTS-3.01-GCC-12.3.0.eb
  easybuild/easyconfigs/c/Compress-Raw-Zlib/Compress-Raw-Zlib-2.213-GCCcore-12.3.0.eb
  easybuild/easyconfigs/v/VEP/VEP-113.0-GCC-12.3.0.eb
Labels: update

#21811 {chem}[foss/2023a] iodata v1.0.0a5
  easybuild/easyconfigs/i/iodata/iodata-1.0.0a5-foss-2023a.eb
Labels: update

#21873 Fix confliction platformdirs dependency in Pylint-3.2.5-GCCcore-13.2.0
  easybuild/easyconfigs/p/Pylint/Pylint-3.2.5-GCCcore-13.2.0.eb
Labels: bug fix

#21996 {bio}[foss/2023a] dorado v0.8.3 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dorado/dorado-0.8.3-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22009 add wayland-utils to Wayland-1.23.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.23.0-GCCcore-13.3.0.eb
Labels: enhancement, change, 2024a

#22005 Set PKG_CONFIG variable to pkgconf
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-37-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-4-GCCcore-11.2.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-53-GCCcore-12.2.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-15-GCCcore-12.3.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-34-GCCcore-13.2.0.eb
  easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-38-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.8.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.4-GCCcore-13.1.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-1.9.5-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.0.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.2.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.3.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pkgconf/pkgconf-2.3.0.eb
Labels: bug fix, change

#21204 {bio}[foss/2023a] AlphaPulldown v2.0.0 Uni-Core v0.0.3 w/ CUDA v12.1.1
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/u/Uni-Core/Uni-Core-0.0.3-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22022 {phys}[system/system] COMSOL v6.3.0.290
  easybuild/easyconfigs/c/COMSOL/COMSOL-6.3.0.290.eb
Labels: update

#22024 {lib}[foss/2023b] HeFFTe v2.4.1 w/ CUDA 12.4.0
  easybuild/easyconfigs/h/HeFFTe/HeFFTe-2.4.1-foss-2023b-CUDA-12.4.0.eb
Labels: update

#22026 {bio}[GCC/13.2.0] Mashtree v1.4.6, Mash v2.3
  easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-13.2.0.eb
  easybuild/easyconfigs/m/Mash/Mash-2.3_fix_missing_cstdint.patch
  easybuild/easyconfigs/m/Mashtree/Mashtree-1.4.6-GCC-13.2.0.eb
  easybuild/easyconfigs/q/QuickTree/QuickTree-2.5-GCC-13.2.0.eb
Labels: update

#22016 Fix for using rpath wrapper with LASTZ-1.04.22
  easybuild/easyconfigs/l/LASTZ/LASTZ-1.04.22-GCC-12.3.0.eb
  easybuild/easyconfigs/l/LASTZ/LASTZ-1.04.22_fix-rpath-wrapper-compat.patch
Labels: change

#21956 {ai}[foss/2023a] dm-control v1.0.18
  easybuild/easyconfigs/d/dm-control/dm-control-1.0.18-foss-2023a.eb
  easybuild/easyconfigs/d/dm-control/labmaze-1.0.6_use-bazel-v6.patch
Labels: new

#21941 {chem}[GCCcore/13.3.0] Molden v7.3
  easybuild/easyconfigs/m/Molden/Molden-7.3-GCCcore-13.3.0.eb
Labels: update

#21942 {bio}[foss/2023a] mlst v2.23.0
  easybuild/easyconfigs/m/mlst/mlst-2.23.0-foss-2023a.eb
Labels: new

#22029 {bio}[GCCcore/13.2.0] hifiasm v0.23.0
  easybuild/easyconfigs/h/hifiasm/hifiasm-0.23.0-GCCcore-13.2.0.eb
Labels: update

#22012 {bio}[GCCcore/13.3.0] rDock v24.03.192
  easybuild/easyconfigs/r/rDock/rDock-24.03.192-GCCcore-13.3.0.eb
Labels: new

#21959 {tools}[gfbf/2023a] llama-cpp-python v0.3.2 w/ CUDA 12.1.1
  easybuild/easyconfigs/l/llama-cpp-python/llama-cpp-python-0.3.2-gfbf-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/l/llama-cpp-python/llama-cpp-python-0.3.2-gfbf-2023a.eb
Labels: new

#21991 {bio}[foss/2023b] purge_dups v1.2.6
  easybuild/easyconfigs/p/purge_dups/KMC-dfguan-c05a5f9_use_EB_pybind11_and_libs.patch
  easybuild/easyconfigs/p/purge_dups/purge_dups-1.2.6-foss-2023b.eb
Labels: update

#21993 add frbs + gcmr extensions to recent R-bundle-CRAN easyconfigs
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
Labels: enhancement

#21947 add tblite for DFTB+
  easybuild/easyconfigs/d/DFTB+/DFTB+-24.1-foss-2023a.eb
Labels: enhancement, change

#22027 {bio}[foss/2023b] Parsnp v2.1.1
  easybuild/easyconfigs/f/FastANI/FastANI-1.34-GCC-13.2.0.eb
  easybuild/easyconfigs/h/harvest-tools/harvest-tools-1.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/h/harvest-tools/harvest-tools-1.3_adapt_to_newer-gcc_protobuf_and_EB.patch
  easybuild/easyconfigs/p/Parsnp/Parsnp-2.1.1-foss-2023b.eb
  easybuild/easyconfigs/p/Parsnp/Parsnp-2.1.1_fix_configure_search_for_libMUSCLE.patch
  easybuild/easyconfigs/p/PhiPack/PhiPack-2016.06.14-GCC-13.2.0.eb
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.13-gompi-2023b-avx2.eb
Labels: new, update

#22036 {vis}[GCCcore/12.3.0] SMV v6.9.5
  easybuild/easyconfigs/s/SMV/SMV-6.9.5-GCCcore-12.3.0.eb
Labels: update

#22039 move `hatchling` from deps to build deps for `BindCraft`
  easybuild/easyconfigs/b/BindCraft/BindCraft-1.1.0-foss-2023a.eb
Labels: bug fix

#21775 {bio}[GCC/12.3.0,gompi/2023a] Bio-SearchIO-hmmer v1.7.3, prokka v1.14.5
  easybuild/easyconfigs/b/Bio-SearchIO-hmmer/Bio-SearchIO-hmmer-1.7.3-GCC-12.3.0.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2023a.eb
Labels: update

#21891 {tools}[GCCcore/13.2.0] datalad v1.1.0, git-annex v10.20240531, libnsl v2.0.1
  easybuild/easyconfigs/d/datalad/datalad-1.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/git-annex/git-annex-10.20240531-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libnsl/libnsl-2.0.1-GCCcore-13.2.0.eb
Labels: update

#21958 {bio}[foss/2023a] BindCraft v1.1.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/b/BindCraft/BindCraft-1.1.0-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21938 {geo}[foss/2024a] WRF 4.6.1, WPS 4.6.0
  easybuild/easyconfigs/w/WPS/WPS-4.6.0-foss-2024a-dmpar.eb
  easybuild/easyconfigs/w/WPS/WPS-4.6.0_fix_jasper_decode.patch
  easybuild/easyconfigs/w/WPS/WPS-4.6.0_netCDF-Fortran_separate_path.patch
  easybuild/easyconfigs/w/WRF/WRF-4.6.1-foss-2024a-dmpar.eb
Labels: update

#21869 {bio,tools,vis}[foss/2023a] bin2cell v0.3.2, fastparquet v2024.11.0, stardist v0.8.5
  easybuild/easyconfigs/b/bin2cell/bin2cell-0.3.2-foss-2023a.eb
  easybuild/easyconfigs/f/fastparquet/fastparquet-2024.11.0-gfbf-2023a.eb
  easybuild/easyconfigs/s/stardist/stardist-0.8.5-foss-2023a.eb
Labels: new, update

#22000 add TorchRL to PyTorch-bundle v2.1.2
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a.eb
Labels: enhancement

#22020 update homepage for DFTB+
  easybuild/easyconfigs/d/DFTB+/DFTB+-21.1-intel-2021a.eb
  easybuild/easyconfigs/d/DFTB+/DFTB+-24.1-foss-2023a.eb
Labels: bug fix, change

#22025 {bio}[gompi/2023b] ABRicate v1.0.0, BLAST+ v2.16.0, BWA v0.7.18, ... w/ _saute.1.3.0_2
  easybuild/easyconfigs/a/ABRicate/ABRicate-1.0.0-gompi-2023b.eb
  easybuild/easyconfigs/a/any2fasta/any2fasta-0.4.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.16.0-gompi-2023b.eb
  easybuild/easyconfigs/b/BWA/BWA-0.7.18-GCCcore-13.2.0.eb
  easybuild/easyconfigs/b/Bio-SearchIO-hmmer/Bio-SearchIO-hmmer-1.7.3-GCC-13.2.0.eb
  easybuild/easyconfigs/p/prokka/prokka-1.14.5-gompi-2023b.eb
  easybuild/easyconfigs/s/SKESA/SKESA-2.4.0-gompi-2023b_saute.1.3.0_2.eb
  easybuild/easyconfigs/t/tbl2asn/tbl2asn-20230713-GCCcore-13.2.0.eb
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.16-GCC-13.2.0.eb
Labels: update

#22017 {bio}[GCCcore/12.3.0,foss/2023a] MitoFinder v1.4.2, IDBA-UD v1.1.3 w/ Python 2.7.18
  easybuild/easyconfigs/i/IDBA-UD/IDBA-UD-1.1.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MitoFinder/MitoFinder-1.4.2-foss-2023a-Python-2.7.18.eb
Labels: new, update

#21564 promote pybind11 to runtime dependency for CPPE (to fix `pip check` failure)
  easybuild/easyconfigs/c/CPPE/CPPE-0.3.1-GCC-11.3.0.eb
  easybuild/easyconfigs/c/CPPE/CPPE-0.3.1-GCC-12.2.0.eb
Labels: bug fix, EasyBuild-5.0

#22054 add Doxygen build dep to libheif, and drop libheif and libde265 to GCCcore
  easybuild/easyconfigs/l/libde265/libde265-1.0.11-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libde265/libde265-1.0.15-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libde265/libde265-1.0.8-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libde265/libde265-1.0.8-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.12.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.12.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.16.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.17.6-GCCcore-12.3.0.eb
Labels: change

#22043 {bio}[system/system] IGV v2.19.1 w/ Java 17
  easybuild/easyconfigs/i/IGV/IGV-2.19.1-Java-17.eb
Labels: update

#21962 {chem}[system/system] GPAW-setups v24.11.0
  easybuild/easyconfigs/g/GPAW-setups/GPAW-setups-24.11.0.eb
Labels: update

#21643 {lang}[system/system] Anaconda3 v2024.06-1
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2024.06-1.eb
Labels: update

#21985 {math}[GCCcore/13.2.0] Gurobi v12.0.0
  easybuild/easyconfigs/g/Gurobi/Gurobi-12.0.0-GCCcore-13.2.0.eb
Labels: update

#22031 {ai}[foss/2023a] Whisper v20240930 w/ CUDA 12.1.1
  easybuild/easyconfigs/w/Whisper/Whisper-20240930-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22063 Fix checksums for Safetensors-0.4.4-gfbf-2023b.eb
  easybuild/easyconfigs/s/Safetensors/Safetensors-0.4.4-gfbf-2023b.eb
Labels: bug fix

#22066 swap 2024a generation of ANTLR to use `Java/17` and switch `NCO-5.2.9-foss-2024a.eb` to use it
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-13.3.0-Java-17.eb
  easybuild/easyconfigs/n/NCO/NCO-5.2.9-foss-2024a.eb
Labels: change

#22068 remove `easybuild_version = '3.5.0'` from `R/4.3.3-gfbf-2023b`
  easybuild/easyconfigs/r/R/R-4.3.3-gfbf-2023b.eb
Labels: change, EasyBuild-5.0

#20869 Use external deps for safetensors and tokenizers in Transformers-4.30.2
  easybuild/easyconfigs/s/Safetensors/Safetensors-0.4.3-gfbf-2022b.eb
  easybuild/easyconfigs/t/Transformers/Transformers-4.30.2-gfbf-2022b.eb
Labels: update, EasyBuild-5.0

#21908 {lang}[foss/2024a,gfbf/2024a] R v4.4.2, R-bundle-CRAN v2024.11
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.11-foss-2024a.eb
  easybuild/easyconfigs/r/R/R-4.4.2-gfbf-2024a.eb
Labels: update, 2024a

#22045 {tools}[GCCcore/13.3.0] SlurmViewer v1.0.2
  easybuild/easyconfigs/s/SlurmViewer/SlurmViewer-1.0.2-GCCcore-13.3.0.eb
Labels: update

#21977 {data}[foss/2023a] Hydra v1.3.2 w/ with plugins
  easybuild/easyconfigs/h/Hydra/Hydra-1.3.2-foss-2023a-with-plugins.eb
Labels: update

#21976 {ai}[foss/2023a] OpenNMT-py v3.5.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/o/OpenNMT-py/OpenNMT-py-3.5.1-foss-2023a-CUDA-12.1.1.eb
Labels: new

#21986 {bio}[GCCcore/12.3.0] Wengan v0.2
  easybuild/easyconfigs/w/Wengan/Wengan-0.2-GCCcore-12.3.0.eb
Labels: new

#21979 {bio}[foss/2023a] Bonito v0.8.1, ont-remora v3.3.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/b/Bonito/Bonito-0.8.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/o/ont-remora/ont-remora-3.3.0-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21901 {ai}[foss/2023a] vLLM v0.4.0, xformers v0.0.23.post1 w/ CUDA 12.1.1
  easybuild/easyconfigs/v/vLLM/vLLM-0.4.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/x/xformers/xformers-0.0.23.post1-foss-2023a-CUDA-12.1.1.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#21895 {lang}[GCCcore/12.3.0] juliaup v1.17.9
  easybuild/easyconfigs/j/juliaup/juliaup-1.17.9-GCCcore-12.3.0.eb
Labels: new

#21957 {vis}[system/system] Fiji v2.14.0 w/ Java 11
  easybuild/easyconfigs/f/Fiji/Fiji-2.14.0-Java-11.eb
Labels: update

#21854 {tools}[foss/2023b] kaggle v1.6.17
  easybuild/easyconfigs/k/kaggle/kaggle-1.6.17-foss-2023b.eb
Labels: new

#21724 Switch to using new spaces as delimiters for TCLLIBPATH
  easybuild/easyconfigs/b/BLT/BLT-20181223-GCCcore-11.2.0.eb
  easybuild/easyconfigs/b/bwidget/bwidget-1.9.14-GCCcore-10.2.0.eb
  easybuild/easyconfigs/b/bwidget/bwidget-1.9.15-GCCcore-11.2.0.eb
  easybuild/easyconfigs/b/bwidget/bwidget-1.9.15-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.47.0-GCCcore-10.2.0-Java-11.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.47.2-GCCcore-10.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-2.50.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-5.0.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-8.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-8.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.10-GCCcore-10.2.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.11-GCCcore-10.3.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.11-GCCcore-11.2.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.12-GCCcore-11.3.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.12-GCCcore-12.2.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.13-GCCcore-12.3.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/Tk/Tk-8.6.14-GCCcore-13.3.0.eb
Labels: bug fix, change, EasyBuild-5.0

#22092 fix incorrect keys in checksums for jaxlib component in jax 0.4.25 easyconfig
  easybuild/easyconfigs/j/jax/jax-0.4.25-gfbf-2023a-CUDA-12.1.1.eb
Labels: bug fix, change

#22091 Expand templates in checksum keys
  easybuild/easyconfigs/c/CFITSIO/CFITSIO-4.3.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/CellBender/CellBender-0.2.1-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/d/duplex-tools/duplex-tools-0.3.1-foss-2022a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2023.05.001-foss-2023a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2023.05.001-intel-2023a.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2023.11.001-foss-2023b.eb
  easybuild/easyconfigs/e/ELPA/ELPA-2023.11.001-intel-2023b.eb
  easybuild/easyconfigs/g/Gurobi/Gurobi-11.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/Gurobi/Gurobi-11.0.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-16.0.6-GCCcore-12.3.0.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.9.2-gompi-2024a.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.1-foss-2023a-CUDA-12.1.1-contrib.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.1-foss-2023a-contrib.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-11-foss-2022a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-11-foss-2023a.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.1-foss-2023a.eb
  easybuild/easyconfigs/p/pytesseract/pytesseract-0.3.10-GCCcore-11.3.0.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2023a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3-foss-2023a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3-intel-2023a.eb
  easybuild/easyconfigs/r/Ray-project/Ray-project-2.9.1-foss-2023a.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.11a-GCC-12.2.0.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.11a-GCC-12.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.21.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/w/wget/wget-1.21.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/w/wget/wget-1.24.5-GCCcore-12.3.0.eb
Labels: bug fix, EasyBuild-5.0

#22095 remove duplicate Sys::Info extensions from Perl-bundle-CPAN
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.40.0-GCCcore-14.2.0.eb
Labels: code cleanup, EasyBuild-5.0

#22049 {tools}[system] EasyBuild v0.5.0.0beta1 (initial beta release of EasyBuild v5.0.0)
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-0.5.0.0beta1.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#22056 Revert "{bio}[GCCcore/13.3.0] rDock v24.03.192"
  easybuild/easyconfigs/r/rDock/rDock-24.03.192-GCCcore-13.3.0.eb
Labels: change

#22096 replace easybuild templates with f-strings on Java easyconfigs
  easybuild/easyconfigs/j/Java/Java-11.0.16.eb
  easybuild/easyconfigs/j/Java/Java-11.0.18.eb
  easybuild/easyconfigs/j/Java/Java-11.0.20.eb
  easybuild/easyconfigs/j/Java/Java-16.0.1.eb
  easybuild/easyconfigs/j/Java/Java-17.0.1.eb
  easybuild/easyconfigs/j/Java/Java-17.0.2.eb
  easybuild/easyconfigs/j/Java/Java-17.0.4.eb
  easybuild/easyconfigs/j/Java/Java-17.0.6.eb
  easybuild/easyconfigs/j/Java/Java-19.0.2.eb
  easybuild/easyconfigs/j/Java/Java-21.0.2.eb
  easybuild/easyconfigs/j/Java/Java-21.0.5.eb
  easybuild/easyconfigs/j/Java/Java-8.345.eb
  easybuild/easyconfigs/j/Java/Java-8.362.eb
  easybuild/easyconfigs/j/Java/Java-8.402.eb
Labels: change, code cleanup, EasyBuild-5.0

#22083 {perf}[gompi/2024a] OSU-Micro-Benchmarks v7.5 w/ CUDA 12.6.0
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.5-gompi-2024a-CUDA-12.6.0.eb
Labels: update

#22098 sync with develop (20241226)
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-13.3.0-Java-17.eb
  easybuild/easyconfigs/b/Bonito/Bonito-0.8.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/d/DjVuLibre/DjVuLibre-3.5.28-GCCcore-12.3.0.eb
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-0.5.0.0beta1.eb
  easybuild/easyconfigs/f/Fiji/Fiji-2.14.0-Java-11.eb
  easybuild/easyconfigs/h/Hydra/Hydra-1.3.2-foss-2023a-with-plugins.eb
  easybuild/easyconfigs/j/juliaup/juliaup-1.17.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/k/kaggle/kaggle-1.6.17-foss-2023b.eb
  easybuild/easyconfigs/n/NCO/NCO-5.2.9-foss-2024a.eb
  easybuild/easyconfigs/o/OPEN-SURFEX/OPEN-SURFEX-8.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/OpenNMT-py/OpenNMT-py-3.5.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/o/ont-remora/ont-remora-3.3.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.11-foss-2024a.eb
  easybuild/easyconfigs/r/R/R-4.4.2-gfbf-2024a.eb
  easybuild/easyconfigs/r/rDock/rDock-24.03.192-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SlurmViewer/SlurmViewer-1.0.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/v/vLLM/vLLM-0.4.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/w/Wengan/Wengan-0.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/xformers/xformers-0.0.23.post1-foss-2023a-CUDA-12.1.1.eb
  test/easyconfigs/easyconfigs.py
Labels: update, EasyBuild-5.0
