Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-04, with the labels that each got.

#22419 {lib}[GCCcore/14.2.0] GDRCopy v2.4.4, UCX-CUDA v1.18.0 w/ CUDA 12.8.0
  easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.4.4-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.18.0-GCCcore-14.2.0-CUDA-12.8.0.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.18.0_link_against_existing_UCX_libs.patch
Labels: update

#22461 {devel,lib}[GCCcore/14.2.0] GOTCHA v1.0.8, Check v0.15.2
  easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.8-GCCcore-14.2.0.eb
Labels: update

#22223 {bio}[foss/2023a] UFCG v1.0.6
  easybuild/easyconfigs/u/UFCG/UFCG-1.0.6-foss-2023a.eb
  easybuild/easyconfigs/u/UFCG/UFCG-1.0.6_fix-ping.patch
Labels: new

#22637 {devel}[foss/2023a] SQUID v1.0.0 w/ R 4.3.2
  easybuild/easyconfigs/s/SQUID/SQUID-1.0.0-foss-2023a-R-4.3.2.eb
Labels: new

#22618 {cae}[foss/2023a] OpenFOAM v6-20190620
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-20190620-foss-2023a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-20190620_cleanup.patch
Labels: update

#22679 {math}[gfbf/2023b] Shapely v2.0.6
  easybuild/easyconfigs/s/Shapely/Shapely-2.0.6-gfbf-2023b.eb
Labels: update

#22356 {bio}[GCCcore/12.3.0,foss/2023a] SQuIRE v0.9.9.9a-beta, pyfaidx v0.7.1 w/ Python 2.7.18
  easybuild/easyconfigs/p/pyfaidx/pyfaidx-0.7.1-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/s/SQuIRE/SQuIRE-0.9.9.9a-beta-20220620-foss-2023a-Python-2.7.18.eb
Labels: new, update

#22561 {bio}[foss/2023a] QIIME2 v2024.10.1, UniFrac v1.4 w/ amplicon
  easybuild/easyconfigs/q/QIIME2/QIIME2-2024.10.1-foss-2023a-amplicon.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2024.10.1_parallel-fix.patch
  easybuild/easyconfigs/u/UniFrac/UniFrac-1.4-foss-2023a.eb
  easybuild/easyconfigs/u/UniFrac/UniFrac-1.4_fix-makefiles.patch
Labels: update

#22250 {bio}[GCC/12.3.0] RepeatModeler v2.0.6, RepeatScout v1.0.7, RECON v1.08, ...
  easybuild/easyconfigs/g/GenomeTools/GenomeTools-1.6.5-GCC-12.3.0.eb
  easybuild/easyconfigs/l/LTR_retriever/LTR_retriever-3.0.1-foss-2023a.eb
  easybuild/easyconfigs/r/RECON/RECON-1.08-GCC-12.3.0.eb
  easybuild/easyconfigs/r/RepeatModeler/RepeatModeler-2.0.6-foss-2023a.eb
  easybuild/easyconfigs/r/RepeatScout/RepeatScout-1.0.7-GCC-12.3.0.eb
  easybuild/easyconfigs/t/TWL-NINJA/TWL-NINJA-1.00-cluster_only-GCC-12.3.0.eb
Labels: update

#22625 Update URLs for libGLU
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-13.3.0.eb
Labels: bug fix, change

#22673 {numlib}[GCCcore/12.3.0] TetGen v1.6.0
  easybuild/easyconfigs/t/TetGen/TetGen-1.6.0-GCCcore-12.3.0.eb
Labels: update

#22252 {bio}[foss/2023a] TEtrimmer v1.4.0, PfamScan v1.6, EMBOSS v6.6.0, ...
  easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-foss-2023a.eb
  easybuild/easyconfigs/l/libharu/libharu-2.3.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PfamScan/PfamScan-1.6-gompi-2023a.eb
  easybuild/easyconfigs/t/TEtrimmer/TEtrimmer-1.4.0-foss-2023a.eb
Labels: new, update

#22674 {numlib}[GCCcore/12.3.0] Triangle v1.6
  easybuild/easyconfigs/t/Triangle/Triangle-1.6-GCCcore-12.3.0.eb
Labels: update

#22689 fix OpenCASCADEConfig.cmake to correctly deal with `lib64` directory
  easybuild/easyconfigs/o/occt/occt-7.8.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/occt/occt-7.8.0_fix-cmake-config.patch
Labels: change

#22690 {lib}[GCCcore/12.3.0] TinyXML v2.6.2
  easybuild/easyconfigs/t/TinyXML/TinyXML-2.6.2-GCCcore-12.3.0.eb
Labels: update

#22703 use `SHLIB_EXT` in `TinyXML`
  easybuild/easyconfigs/t/TinyXML/TinyXML-2.6.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/t/TinyXML/TinyXML-2.6.2-GCCcore-11.3.0.eb
Labels: change

#22691 {lib}[gfbf/2023a] Boost.Python-NumPy v1.82.0
  easybuild/easyconfigs/b/Boost.Python-NumPy/Boost.Python-NumPy-1.82.0-gfbf-2023a.eb
Labels: update

#22525 {bio}[foss/2023b] STITCH v1.7.3
  easybuild/easyconfigs/f/fermi-lite/fermi-lite-20190320-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SSW/SSW-1.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/STITCH/STITCH-1.7.3-foss-2023b.eb
  easybuild/easyconfigs/s/STITCH/STITCH-1.7.3_use_external_hts_and_seqlib.patch
  easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-13.2.0.eb
Labels: new, update

#22372 {chem}[foss/2024a] koopmans v1.1.0, koopmans-kcp v0.2.0, koopmans-qe-utils v 9.1.0 w/ minimal QuantumESPRESSO 7.4
  easybuild/easyconfigs/k/koopmans-kcp/koopmans-kcp-0.2.0-fix-pzheevd_drv.patch
  easybuild/easyconfigs/k/koopmans-kcp/koopmans-kcp-0.2.0-foss-2024a.eb
  easybuild/easyconfigs/k/koopmans-qe-utils/koopmans-qe-utils-0.1.0-fix-cmake-qe-7.4-deps.patch
  easybuild/easyconfigs/k/koopmans-qe-utils/koopmans-qe-utils-0.1.0-fix-cmake-scalapack.patch
  easybuild/easyconfigs/k/koopmans-qe-utils/koopmans-qe-utils-0.1.0-foss-2024a.eb
  easybuild/easyconfigs/k/koopmans/koopmans-1.1.0-foss-2024a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-foss-2024a-minimal.eb
Labels: new, update

#22695 {cae}[foss/2023a] Nektar++ v5.7.0
  easybuild/easyconfigs/n/Nektar++/Nektar++-5.7.0-foss-2023a.eb
Labels: update

#22706 update `pRolocdata` and `RnBeads.hg38` versions in `R-bundle-Bioconductor/3.20` (since source tarball for previous versions are no longer available)
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.20-foss-2024a-R-4.4.2.eb
Labels: change

#22707 fix incompatibility of `bcgTree-1.2.1` with `MUSCLE-5.x`
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.2.1-foss-2023a.eb
Labels: bug fix, change

#21637 {tools}[GCCcore/13.3.0] uv v0.2.30
  easybuild/easyconfigs/u/uv/uv-0.2.30-GCCcore-13.3.0.eb
Labels: new

#22685 use HTTP rather than FTP in source URLs of 'file' easyconfigs
  easybuild/easyconfigs/f/file/file-5.39-GCCcore-10.2.0.eb
  easybuild/easyconfigs/f/file/file-5.40-GCCcore-10.3.0.eb
  easybuild/easyconfigs/f/file/file-5.41-GCCcore-11.2.0.eb
  easybuild/easyconfigs/f/file/file-5.43-GCCcore-11.3.0.eb
  easybuild/easyconfigs/f/file/file-5.43-GCCcore-12.2.0.eb
  easybuild/easyconfigs/f/file/file-5.43-GCCcore-12.3.0.eb
  easybuild/easyconfigs/f/file/file-5.43-GCCcore-13.2.0.eb
  easybuild/easyconfigs/f/file/file-5.46-GCCcore-13.3.0.eb
Labels: change

#22314 {perf,toolchain}[gompi/2025.02,system/system] gompi v2025.02, OSU-Micro-Benchmarks v7.5
  easybuild/easyconfigs/g/gompi/gompi-2025.02.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.5-gompi-2025.02.eb
Labels: update, 2025a

#22420 {mpi}[GCC/14.2.0] MPICH v4.3.0
  easybuild/easyconfigs/m/MPICH/MPICH-4.3.0-GCC-14.2.0.eb
Labels: update, 2025a

#22421 {mpi}[GCC/14.2.0] MPICH v4.3.0 w/ CUDA 12.8.0
  easybuild/easyconfigs/m/MPICH/MPICH-4.3.0-GCC-14.2.0-CUDA-12.8.0.eb
Labels: update, 2025a

#22675 {perf}[GCCcore/14.2.0] CubeLib v4.9, CubeWriter v4.9, libunwind v1.8.1, ... w/ CUDA 12.8.0, tools
  easybuild/easyconfigs/c/CubeLib/CubeLib-4.9-GCCcore-14.2.0.eb
  easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.9-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libunwind/libunwind-1.8.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.9-GCCcore-14.2.0.eb
  easybuild/easyconfigs/o/OTF2/OTF2-3.1.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-14.2.0-tools.eb
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.2-gompi-2025.02.eb
  easybuild/easyconfigs/s/Score-P/Score-P-9.0-gompi-2025.02-CUDA-12.8.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-9.0-gompi-2025.02.eb
Labels: update, 2025a

#22681 {vis}[GCCcore/13.3.0] OpenSlide v4.0.0
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-4.0.0-GCCcore-13.3.0.eb
Labels: update

#22662 {chem}[gfbf/2024a] MOPAC v23.1.2
  easybuild/easyconfigs/m/MOPAC/MOPAC-23.1.2-gfbf-2024a.eb
Labels: new

#22646 make sure Siesta's tests can use 4 MPI processes
  easybuild/easyconfigs/s/Siesta/Siesta-5.2.2-foss-2023a.eb
Labels: change

#22720 Re-add build of shared libs for LLVM [GCCcore 10.3.0]
  easybuild/easyconfigs/l/LLVM/LLVM-11.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-10.3.0.eb
Labels: bug fix

#22709 Add sgdGMF to R-bundle-CRANs
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.11-foss-2024a.eb
Labels: change

#22677 {chem}[foss/2023b,gfbf/2023b] Critic2 v1.2, libcint v5.4.0
  easybuild/easyconfigs/c/Critic2/Critic2-1.2-foss-2023b.eb
  easybuild/easyconfigs/l/libcint/libcint-5.4.0-gfbf-2023b.eb
Labels: update

#22716 {bio}[GCCcore/13.3.0,foss/2024a,gompi/2024a] eggnog-mapper v2.1.12, MMseqs2 v17-b804f, prodigal v2.6.3
  easybuild/easyconfigs/e/eggnog-mapper/eggnog-mapper-2.1.12-foss-2024a.eb
  easybuild/easyconfigs/m/MMseqs2/MMseqs2-17-b804f-gompi-2024a.eb
  easybuild/easyconfigs/p/prodigal/prodigal-2.6.3-GCCcore-13.3.0.eb
Labels: update

#22724 {vis}[GCCcore/13.3.0] ETE v3.1.3, PyQt5 v5.15.11, PyQt-builder v1.18.1
  easybuild/easyconfigs/e/ETE/ETE-3.1.3-foss-2024a.eb
  easybuild/easyconfigs/p/PyQt-builder/PyQt-builder-1.18.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.11-GCCcore-13.3.0.eb
Labels: update

#22671 {bio}[GCCcore/13.3.0] canu v2.3
  easybuild/easyconfigs/c/canu/canu-2.3-GCCcore-13.3.0-Java-11.eb
Labels: update

#22676 {bio}[foss/2023a] AlphaPulldown v2.0.3 w/ CUDA 12.1.1
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.3-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22669 {tools}[GCCcore/12.3.0,GCCcore/13.3.0] ninja-python v1.10.2.4, ninja-python v1.11.1.4
  easybuild/easyconfigs/n/ninja-python/ninja-python-1.10.2.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/n/ninja-python/ninja-python-1.11.1.4-GCCcore-13.3.0.eb
Labels: new

#22131 {geo}[foss/2023a] momepy v0.9.1
  easybuild/easyconfigs/m/momepy/momepy-0.9.1-foss-2023a.eb
Labels: new

#22194 {bio}[foss/2022a] ProLaTherm v20240613 w/ CUDA 11.7.0
  easybuild/easyconfigs/p/ProLaTherm/ProLaTherm-20240613-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/p/ProLaTherm/ProLaTherm-20240613_fix_path.patch
Labels: new

#22423 {bio}[foss/2023a] fastStructure v1.0 w/ Python 2.7.18
  easybuild/easyconfigs/c/Cython/Cython-0.27.3-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/f/fastStructure/fastStructure-1.0-foss-2023a-Python-2.7.18.eb
Labels: new, update

#22302 {bio,tools}[foss/2022a] ProTstab2 v2.0.2, rpy2 v3.5.15
  easybuild/easyconfigs/p/ProTstab2/ProTstab2-2.0.2-foss-2022a.eb
  easybuild/easyconfigs/p/ProTstab2/ProTstab2-2.0.2_various_fixes.patch
  easybuild/easyconfigs/r/rpy2/rpy2-3.5.15-foss-2022a.eb
Labels: new, update

#22224 {chem}[gomkl/2023a] Tinker-HP v20230803
  easybuild/easyconfigs/t/Tinker-HP/Tinker-HP-20230803-gomkl-2023a.eb
Labels: new

#22666 {lang}[GCCcore/13.3.0] SBCL v2.5.3, CCL v1.13
  easybuild/easyconfigs/c/CCL/CCL-1.13-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SBCL/SBCL-2.5.3-GCCcore-13.3.0.eb
Labels: update

#22726 {math}[GCCcore/13.3.0] Gurobi v12.0.1
  easybuild/easyconfigs/g/Gurobi/Gurobi-12.0.1-GCCcore-13.3.0.eb
Labels: update

#22316 {geo}[foss/2023a] PySAL v25.1
  easybuild/easyconfigs/p/PySAL/PySAL-25.1-foss-2023a.eb
Labels: new

#22663 {cae}[foss/2023a] OpenFOAM vv2206
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2206-foss-2023a.eb
Labels: update

#22727 {bio,lib}[GCCcore/13.3.0,foss/2024a] MultiQC v1.28, tiktoken v0.9.0
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.28-foss-2024a.eb
  easybuild/easyconfigs/t/tiktoken/tiktoken-0.9.0-GCCcore-13.3.0.eb
Labels: update

#22721 Add lsb_release as builddependency to all ABAQUS-2022 easyconfigs
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022-hotfix-2214.eb
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022-hotfix-2223.eb
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022.eb
  easybuild/easyconfigs/l/lsb_release/lsb_release-2.0.eb
Labels: bug fix, new, change

#22657 {compiler,mpi}[intel-compilers/2025.1.0,system/system] intel-compilers v2025.1.0, impi v2021.15.0
  easybuild/easyconfigs/i/impi/impi-2021.15.0-intel-compilers-2025.1.0.eb
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2025.1.0.eb
Labels: update

#22711 {bio}[gfbf/2023b] PLINK v2.0.0-a.6.9
  easybuild/easyconfigs/p/PLINK/PLINK-2.0.0-a.6.9-gfbf-2023b.eb
Labels: update

#22125 {numlib}[GCC/14.2.0] OpenBLAS v0.3.29, FlexiBLAS v3.4.5, BLIS v1.1, AOCL-BLAS v5.0
  easybuild/easyconfigs/a/AOCL-BLAS/AOCL-BLAS-5.0-GCC-14.2.0.eb
  easybuild/easyconfigs/b/BLIS/BLIS-1.1-GCC-14.2.0.eb
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.4.5-GCC-14.2.0.eb
  easybuild/easyconfigs/m/make/make-4.4.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.29-GCC-14.2.0.eb
Labels: update, 2025a

#22748 {geo}[foss/2024a] rasterio v1.4.3
  easybuild/easyconfigs/r/rasterio/rasterio-1.4.3-foss-2024a.eb
Labels: update

#22742 Avoid OpenCV searching for Python 2
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.6.0-foss-2022a-CUDA-11.7.0-contrib.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.6.0-foss-2022a-contrib.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.6.0_dont_use_python2.patch
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.0-foss-2022b-contrib.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.1-foss-2023a-CUDA-12.1.1-contrib.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.8.1-foss-2023a-contrib.eb
Labels: change

#22753 ensure `Infernal` is built with MPI support, and drop toolchain to gompi
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2020b.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2021a.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2021b.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2022a.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2022b.eb
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.5-gompi-2023a.eb
Labels: bug fix, change

#22438 {bio}[GCC/13.3.0] InterProScan v5.73-104.0
  easybuild/easyconfigs/i/InterProScan/InterProScan-5.73-104.0-GCC-13.3.0.eb
Labels: update

#22754 Ensure `Proteinortho` links against `FlexiBLAS`, and bump to `foss`
  easybuild/easyconfigs/p/Proteinortho/Proteinortho-6.2.3-foss-2021b.eb
  easybuild/easyconfigs/p/Proteinortho/Proteinortho-6.3.2-foss-2023a.eb
Labels: bug fix, change

#22741 {math}[foss/2024a] h5netcdf v1.6.1, PyTensor v2.30.3, ArviZ v0.21.0, ...
  easybuild/easyconfigs/a/ArviZ/ArviZ-0.21.0-foss-2024a.eb
  easybuild/easyconfigs/h/h5netcdf/h5netcdf-1.6.1-foss-2024a.eb
  easybuild/easyconfigs/p/PyMC/PyMC-5.22.0-foss-2024a.eb
  easybuild/easyconfigs/p/PyTensor/PyTensor-2.30.3-gfbf-2024a.eb
Labels: update

#22745 {bio}[GCC/13.3.0] SNAP-HMM v20221022, StringTie v3.0.0, tantan v51
  easybuild/easyconfigs/s/SNAP-HMM/SNAP-HMM-20221022-GCC-13.3.0.eb
  easybuild/easyconfigs/s/StringTie/StringTie-3.0.0-GCC-13.3.0.eb
  easybuild/easyconfigs/t/tantan/tantan-51-GCC-13.3.0.eb
Labels: update

#22680 {lib}[GCCcore/13.3.0] MATIO v1.5.28
  easybuild/easyconfigs/m/MATIO/MATIO-1.5.28-GCCcore-13.3.0.eb
Labels: update

#22596 {lib}[GCCcore/13.2.0] libfyaml v0.9
  easybuild/easyconfigs/l/libfyaml/libfyaml-0.9-GCCcore-13.2.0.eb
Labels: update

#22678 {lib}[GCC/13.2.0] libvips v8.16.1
  easybuild/easyconfigs/l/libvips/libvips-8.16.1-GCC-13.2.0.eb
Labels: update

#22682 {lib}[GCC/13.3.0] libvips v8.16.1
  easybuild/easyconfigs/l/libvips/libvips-8.16.1-GCC-13.3.0.eb
Labels: update

#22746 {bio}[foss/2023a] Evo v0.4 w/ CUDA 12.1.1
  easybuild/easyconfigs/e/Evo/Evo-0.4-foss-2023a-CUDA-12.1.1.eb
Labels: new

#22349 {tools}[GCCcore/14.2.0] cryptography v44.0.2, cffi v1.17.1, setuptools-rust v1.11.0, hatchling v1.27.0, maturin v1.8.3, Rust v1.85.1, virtualenv v20.29.2
  easybuild/easyconfigs/c/cffi/cffi-1.17.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/c/cryptography/cryptography-44.0.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/h/hatchling/hatchling-1.27.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/m/maturin/maturin-1.8.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.85.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.11.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/v/virtualenv/virtualenv-20.29.2-GCCcore-14.2.0.eb
Labels: update, 2025a

#22755 update LST-AI v1.1.0-20250324 easyconfigs - prepare lst to run in postainstallcmds
  easybuild/easyconfigs/l/LST-AI/LST-AI-1.1.0-20250324-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/l/LST-AI/LST-AI-1.1.0-20250324-foss-2023a.eb
Labels: enhancement, bug fix, change

#22749 {bio}[foss/2023a] PICRUSt2 v2.6.1
  easybuild/easyconfigs/p/PICRUSt2/PICRUSt2-2.6.1-foss-2023a.eb
Labels: update

#22756 {geo}[gmpich/2025.04] GeoDict v2025.SP2
  easybuild/easyconfigs/g/GeoDict/GeoDict-2025.SP2-gmpich-2025.04.eb
  easybuild/easyconfigs/g/gmpich/gmpich-2025.04.eb
Labels: update

#22427 {phys}[system/system] AEDT v2025R1
  easybuild/easyconfigs/a/AEDT/AEDT-2025R1.eb
Labels: update

#22762 {tools}[foss/2023a] THOP v0.1.1.post2209072238
  easybuild/easyconfigs/t/THOP/THOP-0.1.1.post2209072238-foss-2023a.eb
Labels: new

#22759 {bio}[GCC/13.2.0] MetaBAT v2.17
  easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.17-GCC-13.2.0.eb
Labels: update

#22670 {ai}[foss/2023a] Mamba-SSM v2.2.4 w/ PyTorch 2.1.2 CUDA 12.1.1
  easybuild/easyconfigs/m/Mamba-SSM/Mamba-SSM-2.2.4-foss-2023a-PyTorch-2.1.2-CUDA-12.1.1.eb
Labels: new

#22740 {bio}[GCCcore/12.3.0] mpath v1.1.3
  easybuild/easyconfigs/m/mpath/mpath-1.1.3-GCCcore-12.3.0.eb
Labels: update

#22770 {devel}[intel-compilers/2024.2.0] Boost v1.85.0
  easybuild/easyconfigs/b/Boost/Boost-1.85.0-intel-compilers-2024.2.0.eb
Labels: update

#21185 {astro}[gompi/2023a] grackle v3.3.0
  easybuild/easyconfigs/g/grackle/grackle-3.3.0-gompi-2023a.eb
Labels: new

#21472 {data,lib}[GCCcore/12.3.0,foss/2023a] FOX-Toolkit v1.6.58, SUMO v1.20.0
  easybuild/easyconfigs/f/FOX-Toolkit/FOX-Toolkit-1.6.58-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/SUMO/SUMO-1.20.0-foss-2023a.eb
Labels: update

#22772 {tools}[GCCcore/14.2.0] poetry v2.1.2
  easybuild/easyconfigs/p/poetry/poetry-2.1.2-GCCcore-14.2.0.eb
Labels: update, 2025a

#22733 {chem}[foss/2023a] LAMMPS v29Aug2024_update2 w/ kokkos
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Aug2024_update2-foss-2023a-kokkos.eb
Labels: update

#22728 {bio}[foss/2023a] bcbio-gff v0.7.1, CMSeq v1.0.4
  easybuild/easyconfigs/b/bcbio-gff/bcbio-gff-0.7.1-foss-2023a.eb
  easybuild/easyconfigs/c/CMSeq/CMSeq-1.0.4-foss-2023a.eb
Labels: update

#22722 {math,tools}[GCCcore/13.2.0,gfbf/2023b] parameterized v0.9.0, sympy v1.13.3
  easybuild/easyconfigs/p/parameterized/parameterized-0.9.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/sympy/sympy-1.13.3-gfbf-2023b.eb
Labels: update

#22126 {numlib,toolchain}[GCC/14.2.0,system/system] gfbf v2025.02, FFTW v3.3.10
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-GCC-14.2.0.eb
  easybuild/easyconfigs/g/gfbf/gfbf-2025.02.eb
Labels: update, 2025a

#22710 {bio}[GCC/13.2.0] GCTB v2.5.2
  easybuild/easyconfigs/g/GCTB/GCTB-2.5.2-GCC-13.2.0.eb
Labels: new

#22784 {geo,math}[foss/2024a] RHEIA v1.1.13, rioxarray v0.19.0
  easybuild/easyconfigs/r/RHEIA/RHEIA-1.1.13-foss-2024a.eb
  easybuild/easyconfigs/r/rioxarray/rioxarray-0.19.0-foss-2024a.eb
Labels: update

#22780 add patch to fix installation of MUSCLE 5.1.0 on aarch64 systems
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-5.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MUSCLE/MUSCLE-5.1.0-add_Aarch64_support.patch
Labels: bug fix, aarch64

#22773 AFNI/25.1.01 and motif/2.3.8 for 2024a
  easybuild/easyconfigs/a/AFNI/AFNI-25.1.01-foss-2024a.eb
  easybuild/easyconfigs/m/motif/motif-2.3.8-GCCcore-13.3.0.eb
Labels: update

#22790 {data}[foss/2023a] BDBag v1.7.3
  easybuild/easyconfigs/b/BDBag/BDBag-1.7.3-foss-2023a.eb
Labels: update

#22794 {bio}[system/system] Lep-MAP3 v20250312 w/ Java 21
  easybuild/easyconfigs/l/Lep-MAP3/Lep-MAP3-20250312-Java-21.eb
Labels: new

#22798 {devel}[system/system] Set C standard for system M4 1.4.19
  easybuild/easyconfigs/m/M4/M4-1.4.19.eb
Labels: bug fix

#22714 {bio}[GCC/13.3.0] Jellyfish v2.3.1, kallisto v0.51.1, RSEM v1.3.3, ...
  easybuild/easyconfigs/b/Bowtie/Bowtie-1.3.1-GCC-13.3.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.4-GCC-13.3.0.eb
  easybuild/easyconfigs/h/HISAT2/HISAT2-2.2.1-gompi-2024a.eb
  easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.1-GCC-13.3.0.eb
  easybuild/easyconfigs/k/kallisto/kallisto-0.51.1-gompi-2024a.eb
  easybuild/easyconfigs/r/RSEM/RSEM-1.3.3-foss-2024a.eb
  easybuild/easyconfigs/s/STAR/STAR-2.7.11b-GCC-13.3.0.eb
  easybuild/easyconfigs/s/Salmon/Salmon-1.10.3-GCC-13.3.0.eb
  easybuild/easyconfigs/x/xxd/xxd-9.1.1275-GCCcore-13.3.0.eb
Labels: update

#22743 {bio}[GCCcore/13.3.0] GeneMark-ET v4.72, trimAl v1.5.0
  easybuild/easyconfigs/g/GeneMark-ET/GeneMark-ET-4.72-GCCcore-13.3.0.eb
  easybuild/easyconfigs/t/trimAl/trimAl-1.5.0-GCCcore-13.3.0.eb
Labels: update

#22805 Build static libraries of Abseil
  easybuild/easyconfigs/a/Abseil/Abseil-20210324.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20230125.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20240116.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/Abseil/Abseil-20240722.0-GCCcore-13.3.0.eb
Labels: change

#19291 {chem}[gfbf/2022a] multicharge v0.2.0
  easybuild/easyconfigs/m/multicharge/multicharge-0.2.0-gfbf-2022a.eb
Labels: update

#22807 {devel}[system/system] Set C standard for ncurses 6.5
  easybuild/easyconfigs/n/ncurses/ncurses-6.5.eb
Labels: bug fix

#21910 change default data location in snpEff v5.2c
  easybuild/easyconfigs/s/snpEff/snpEff-5.2c-GCCcore-12.2.0-Java-11.eb
  easybuild/easyconfigs/s/snpEff/snpEff-5.2c-GCCcore-12.3.0-Java-11.eb
Labels: change

#22804 add `groff` build dependency to `enchant-2` easyconfigs
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.3.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.3.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.6.5-GCCcore-12.3.0.eb
Labels: bug fix, change

#22482 {data}[GCCcore/13.2.0] HDF v4.2.16-2 w/ w fortran no netCDF
  easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-13.2.0-w-fortran-no-netCDF.eb
Labels: update

#22485 {data}[GCCcore/13.2.0] HDF-EOS2 v3.0
  easybuild/easyconfigs/h/HDF-EOS2/HDF-EOS2-3.0-GCCcore-13.2.0.eb
Labels: update

#22483 {geo}[intel/2023b] ESMF v8.6.1
  easybuild/easyconfigs/e/ESMF/ESMF-8.6.1-intel-2023b.eb
Labels: update

#22484 {tools}[iimpi/2023b] ecCodes v2.31.0
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.31.0-iimpi-2023b.eb
Labels: update

#22771 {bio,toolchain}[iimkl/2024a] iimkl v2024a, BOLT-LMM v2.4.1
  easybuild/easyconfigs/b/BOLT-LMM/BOLT-LMM-2.4.1-iimkl-2024a.eb
  easybuild/easyconfigs/i/iimkl/iimkl-2024a.eb
Labels: new, update

#22819 {lib}[GCCcore/12.3.0] python-isal v1.6.1
  easybuild/easyconfigs/p/python-isal/python-isal-1.6.1-GCCcore-12.3.0.eb
Labels: update
