Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-08, with the labels that each got.

#23269 {data,tools}[gfbf/2025a] dask v2025.5.1, dask-labextension v7.0.0
  easybuild/easyconfigs/b/bokeh/bokeh-3.7.3-gfbf-2025a.eb
  easybuild/easyconfigs/d/dask-labextension/dask-labextension-7.0.0-gfbf-2025a.eb
  easybuild/easyconfigs/d/dask/dask-2025.5.1-gfbf-2025a.eb
Labels: update

#23525 {lang}[gfbf/2025.07] SciPy-bundle v2025.07, pybind11 v3.0.0, meson-python v0.18.0, spin v0.14, hypothesis v6.136.6, Catch2 v2.13.10
  easybuild/easyconfigs/c/Catch2/Catch2-2.13.10-GCCcore-14.3.0.eb
  easybuild/easyconfigs/h/hypothesis/hypothesis-6.136.6-GCCcore-14.3.0.eb
  easybuild/easyconfigs/m/meson-python/meson-python-0.18.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-3.0.0-GCC-14.3.0.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2025.07-gfbf-2025.07.eb
  easybuild/easyconfigs/s/SciPy-bundle/scipy-1.16.1_bump-orth-memory-efficiency-tolerance.patch
  easybuild/easyconfigs/s/spin/spin-0.14-GCCcore-14.3.0.eb
Labels: update, 2025b

#23561 {devel}[foss/2024a] NLTK v3.9.1
  easybuild/easyconfigs/n/NLTK/NLTK-3.9.1-foss-2024a.eb
Labels: update, 2024a

#23257 {devel,tools}[GCCcore/14.2.0] Bazel v7.4.1, Zip v3.0 w/ Java 21
  easybuild/easyconfigs/b/Bazel/Bazel-7.4.1-GCCcore-14.2.0-Java-21.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/z/Zip/Zip-3.0_gcc-14-compability.patch
Labels: update, 2025a

#23549 {lib}[GCCcore/14.2.0] tbb v2022.2.0
  easybuild/easyconfigs/t/tbb/tbb-2022.2.0-GCCcore-14.2.0.eb
Labels: update, 2025a

#23537 {ai}[GCC/13.3.0] wandb v0.20.1
  easybuild/easyconfigs/w/wandb/wandb-0.20.1-GCC-13.3.0.eb
Labels: update

#23567 {lib}[GCCcore/14.3.0] aiohttp v3.12.15, boto3 v1.39.8, Flask v3.1.1, ...
  easybuild/easyconfigs/a/aiohttp/aiohttp-3.12.15-GCCcore-14.3.0.eb
  easybuild/easyconfigs/b/boto3/boto3-1.39.8-GCCcore-14.3.0.eb
  easybuild/easyconfigs/f/Flask/Flask-3.1.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/i/IPython/IPython-9.4.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.5-GCCcore-14.3.0.eb
Labels: update, 2025b

#23570 {lib}[GCCcore/14.3.0] libtommath v1.3.0
  easybuild/easyconfigs/l/libtommath/libtommath-1.3.0-GCCcore-14.3.0.eb
Labels: new, 2025b

#23568 {lang}[GCCcore/14.3.0] Add libtommath dep to Tcl v9.0.1
  easybuild/easyconfigs/t/Tcl/Tcl-9.0.1-GCCcore-14.3.0.eb
Labels: bug fix, change, 2025b

#23469 {numlib}[system/system] NVPL v25.5
  easybuild/easyconfigs/n/NVPL/NVPL-25.5.eb
Labels: new, aarch64

#23055 Use LLVM easyblock for Clang 18 easyconfigs
  easybuild/easyconfigs/c/Clang/Clang-18.1.8-GCCcore-13.3.0-CUDA-12.6.0.eb
  easybuild/easyconfigs/c/Clang/Clang-18.1.8-GCCcore-13.3.0.eb
Labels: change

#23388 {tools}[GCCcore/14.3.0] Cling v1.2
  easybuild/easyconfigs/c/Cling/Cling-1.2-GCCcore-14.3.0.eb
  easybuild/easyconfigs/c/Cling/Cling-1.2_disable-demo.patch
  easybuild/easyconfigs/c/Cling/Cling-1.2_fix-resource-path.patch
Labels: new, 2025b

#23574 {tools}[GCCcore/14.3.0] bcrypt v4.3.0, imageio v2.37.0, paramiko v4.0.0, ...
  easybuild/easyconfigs/b/bcrypt/bcrypt-4.3.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/i/imageio/imageio-2.37.0-gfbf-2025.07.eb
  easybuild/easyconfigs/p/PDM/PDM-2.25.5-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/paramiko/paramiko-4.0.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/pyproj/pyproj-3.7.1-GCCcore-14.3.0.eb
Labels: update, 2025b

#23576 {system}[system/system] CUDA v13.0.0
  easybuild/easyconfigs/c/CUDA/CUDA-13.0.0.eb
Labels: update

#23531 {data}[GCCcore/13.2.0] MDSplus v7.153.3
  easybuild/easyconfigs/m/MDSplus/MDSplus-7.153.3-GCCcore-13.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#23539 {vis}[GCC/13.3.0,GCCcore/13.3.0] OpenCV v4.11.0, GTK4 v4.17.1, GST-plugins-bad v1.24.8, ... w/ contrib
  easybuild/easyconfigs/g/GST-plugins-bad/GST-plugins-bad-1.24.8-GCC-13.3.0.eb
  easybuild/easyconfigs/g/GTK4/GTK4-4.17.1-GCC-13.3.0.eb
  easybuild/easyconfigs/o/OpenCV/OpenCV-4.11.0-foss-2024a-contrib.eb
  easybuild/easyconfigs/p/PyCairo/PyCairo-1.28.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PyGObject/PyGObject-3.52.3-GCCcore-13.3.0.eb
Labels: update

#23564 disable flaky `LWP::Simple` test in `Perl-bundle-CPAN`
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.40.0-GCCcore-14.2.0.eb
Labels: bug fix

#23571 Panoply/5.6.2
  easybuild/easyconfigs/p/Panoply/Panoply-5.6.2.eb
Labels: update

#23522 {devel,lib}[GCC/13.2.0,GCCcore/13.2.0] OpenColorIO v2.4.2, glew v2.2.0 w/ egl
  easybuild/easyconfigs/g/glew/glew-2.2.0-GCCcore-13.2.0-egl.eb
  easybuild/easyconfigs/m/minizip-ng/minizip-ng-4.0.10-GCC-13.2.0.eb
  easybuild/easyconfigs/o/OpenColorIO/OpenColorIO-2.4.2-GCC-13.2.0.eb
  easybuild/easyconfigs/p/pystring/pystring-1.1.4-GCC-13.2.0.eb
  easybuild/easyconfigs/p/pystring/pystring-1.1.4-include-header-files.patch
Labels: new, update

#23583 {lib}[GCCcore/14.3.0] NCCL v2.27.7, UCC-CUDA v1.4.4, UCC v1.4.4, ... w/ CUDA 12.9.1
  easybuild/easyconfigs/n/NCCL/NCCL-2.27.7-GCCcore-14.3.0-CUDA-12.9.1.eb
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.4.4-GCCcore-14.3.0-CUDA-12.9.1.eb
  easybuild/easyconfigs/u/UCC/UCC-1.4.4-GCCcore-14.3.0.eb
  easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.19.0-GCCcore-14.3.0-CUDA-12.9.1.eb
  easybuild/easyconfigs/u/UCX/UCX-1.19.0-GCCcore-14.3.0.eb
Labels: update, 2025b

#23575 fix installation of xtb 6.7.1 w/ `gfbf/2023b` by adding missing dependencies (mctc-lib, tblite, mstore, numsa, CPCM-X, dftd4, Simple-DFTD3)
  easybuild/easyconfigs/c/CPCM-X/CPCM-X-1.1.0-gfbf-2023b.eb
  easybuild/easyconfigs/n/numsa/numsa-0.2.0-gfbf-2023b.eb
  easybuild/easyconfigs/s/Simple-DFTD3/Simple-DFTD3-1.2.1-gfbf-2023b.eb
  easybuild/easyconfigs/t/TOML-Fortran/TOML-Fortran-0.4.2-GCC-13.2.0.eb
  easybuild/easyconfigs/t/tblite/tblite-0.4.0-gfbf-2023b.eb
  easybuild/easyconfigs/x/xtb/xtb-6.7.1-gfbf-2023b.eb
Labels: bug fix, new, update

#23592 {tools}[foss/2025a] HPL v2.3
  easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2025a.eb
Labels: update, 2025a

#23604 {compiler} GCC 15.2.0 + binutils 2.45
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-15.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.45-GCCcore-15.2.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.45.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-15.2.0.eb
  easybuild/easyconfigs/g/GCC/GCC-15.2.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-15.2.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.3-GCCcore-15.2.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.20-GCCcore-15.2.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.3.1-GCCcore-15.2.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#23619 disable `lseq` tests when building Tcl 9.0.1 on RISC-V systems (to avoid hang in test step)
  easybuild/easyconfigs/t/Tcl/Tcl-9.0.1-GCCcore-14.3.0.eb
Labels: bug fix, riscv, 2025b

#23609 {compiler}[GCCcore/13.2.0,GCCcore/13.3.0] Add libxml2/libffi/zstd dependencies to minimal/llvmlite LLVM
  easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-13.2.0-llvmlite.eb
  easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-13.3.0-llvmlite.eb
  easybuild/easyconfigs/l/LLVM/LLVM-16.0.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0-minimal.eb
Labels: bug fix, 2023b, 2024a

#23613 {compiler}[GCCcore/14.3.0] Add libxml2 and zstd dependencies to LLVM 20.1.8
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.8-GCCcore-14.3.0.eb
Labels: bug fix, 2025b

#23625 fix version information for `cppy`
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.2.1-manual_version.patch
  easybuild/easyconfigs/c/cppy/cppy-1.3.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/c/cppy/cppy-1.3.1-GCCcore-14.3.0.eb
Labels: bug fix

#23623 {perf}[system/system] Advisor v2025.2.0
  easybuild/easyconfigs/a/Advisor/Advisor-2025.2.0.eb
Labels: update

#23201 {chem}[iomkl/2023a] autoCAS v2.3.1, OpenMolcas v25.02, QCMaquis v3.1.4, ... w/ serial
  easybuild/easyconfigs/a/autoCAS/autoCAS-2.3.1-iomkl-2023a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.82.0-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/g/GSL/GSL-2.7-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.0-intel-compilers-2023.1.0-serial.eb
  easybuild/easyconfigs/h/h5py/h5py-3.9.0-iomkl-2023a-serial.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-25.02-iomkl-2023a-DMRG-no-MPI.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-25.02_fix-nevpt2.cmake.patch
  easybuild/easyconfigs/q/QCMaquis/QCMaquis-3.1.4-iomkl-2023a.eb
  test/easyconfigs/easyconfigs.py
Labels: new, update

#23556 Add additional patches for OpenMPI-5.0.7 from 2025a
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7-GCC-14.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7_build-with-internal-cuda-header.patch
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7_fix_gpfs_compatibility.patch
Labels: bug fix, change, 2025a

#23645 {tools}[gfbf/2024a] SLiM v5.0
  easybuild/easyconfigs/s/SLiM/SLiM-5.0-gfbf-2024a.eb
  easybuild/easyconfigs/s/SLiM/SLiM-5.0_cmake_use_external_zlib_gsl.patch
Labels: update, 2024a

#23611 {compiler}[GCCcore/13.3.0] Add libxml2 and zstd dependencies to LLVM 20.1.4/20.1.5
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.4-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.3.0.eb
Labels: bug fix, 2024a

#23119 {devel}[foss/2023b] Triton v2.3.1 w/ CUDA 12.4.0
  easybuild/easyconfigs/t/Triton/Triton-2.3.1-foss-2023b-CUDA-12.4.0.eb
  easybuild/easyconfigs/t/Triton/Triton-2.3.1_disable-dependency-download.patch
Labels: update

#23622 {math,numlib}[foss/2025a] Hypre v2.33.0, MUMPS v5.8.1, PETSc v3.23.5, ... w/ metis
  easybuild/easyconfigs/h/Hypre/Hypre-2.33.0-foss-2025a.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.8.1-foss-2025a-metis.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.23.5-foss-2025a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2025a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.8-gompi-2025a.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-9.1.0-foss-2025a.eb
Labels: update, 2025a

#23621 {lang}[system/system] Anaconda3 v2025.06-1
  easybuild/easyconfigs/a/Anaconda3/Anaconda3-2025.06-1.eb
Labels: update, 2025a

#23660 add missing ASE versionsuffix for MACE and remove redundant ASE exception from alt_dep_versions
  easybuild/easyconfigs/m/MACE/MACE-0.3.8-foss-2023a-CUDA-12.1.1-ASE-3.24.0.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix, change

#23646 {lang}[system/system] Miniconda3 v25.5.1-1
  easybuild/easyconfigs/m/Miniconda3/Miniconda3-25.5.1-1.eb
Labels: update

#23677 Add Java-21.0.8.eb and update Java-21.eb
  easybuild/easyconfigs/j/Java/Java-21.0.8.eb
  easybuild/easyconfigs/j/Java/Java-21.eb
Labels: update, change

#23650 {bio}[GCC/14.2.0,GCCcore/14.2.0] BWA v0.7.19, Bowtie2 v2.5.4
  easybuild/easyconfigs/b/BWA/BWA-0.7.19-GCCcore-14.2.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.4-GCC-14.2.0.eb
Labels: update, 2025a

#23644 {math}[GCCcore/14.2.0] libcerf v3.0
  easybuild/easyconfigs/l/libcerf/libcerf-3.0-GCCcore-14.2.0.eb
Labels: update, 2025a

#23648 {bio,lib}[GCC/14.2.0,GCCcore/14.2.0] BamTools v2.5.3, JsonCpp v1.9.6
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.3-GCC-14.2.0.eb
  easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.6-GCCcore-14.2.0.eb
Labels: update, 2025a

#23630 {bio}[GCC/14.2.0] HTSlib v1.22.1
  easybuild/easyconfigs/h/HTSlib/HTSlib-1.22.1-GCC-14.2.0.eb
Labels: update, 2025a

#23640 {lib}[GCCcore/14.2.0] libgd v2.3.3
  easybuild/easyconfigs/l/libgd/libgd-2.3.3-GCCcore-14.2.0.eb
Labels: update, 2025a

#23673 {cae,math,vis}[GCCcore/13.3.0] gmsh v4.14.0, occt v7.8.0, FreeImage v3.18.0
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/gmsh/gmsh-4.14.0-foss-2024a.eb
  easybuild/easyconfigs/o/occt/occt-7.8.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#23597 {tools}[GCCcore/14.2.0] time v1.9
  easybuild/easyconfigs/t/time/time-1.9-GCCcore-14.2.0.eb
Labels: update, 2025a

#23699 {bio,lib,tools}[foss/2025.07,gfbf/2025.07,gompi/2025.07] GROMACS v2025.2, mpi4py v4.1.0, networkx v3.5
  easybuild/easyconfigs/g/GROMACS/GROMACS-2025.2-foss-2025.07.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2025.2_gmxapi-remove-builddependencies.patch
  easybuild/easyconfigs/m/mpi4py/mpi4py-4.1.0-gompi-2025.07.eb
  easybuild/easyconfigs/n/networkx/networkx-3.5-gfbf-2025.07.eb
Labels: update, 2025b

#23672 {chem}[gfbf/2023a] MOKIT v1.2.6
  easybuild/easyconfigs/m/MOKIT/MOKIT-1.2.6-gfbf-2023a.eb
Labels: update, 2023a, 2023b, ready-to-review

#23707 {math}[foss/2025.07,intel/2025.08] HPCG v3.1
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2025.07.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2025.08.eb
Labels: update, 2025b

#23708 Establish `2025b` toolchain (and rename / remove candidate toolchains 2025.07 / 2025.08 )
  easybuild/easyconfigs/a/ASE/ASE-3.25.0-gfbf-2025b.eb
  easybuild/easyconfigs/b/bokeh/bokeh-3.7.3-gfbf-2025b.eb
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2025b.eb
  easybuild/easyconfigs/f/FLINT/FLINT-3.3.1-gfbf-2025b.eb
  easybuild/easyconfigs/f/foss/foss-2025b.eb
  easybuild/easyconfigs/g/GROMACS/GROMACS-2025.2-foss-2025b.eb
  easybuild/easyconfigs/g/gfbf/gfbf-2025b.eb
  easybuild/easyconfigs/g/gompi/gompi-2025b.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2025b.eb
  easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2025b.eb
  easybuild/easyconfigs/h/hmmlearn/hmmlearn-0.3.3-gfbf-2025b.eb
  easybuild/easyconfigs/i/iimkl/iimkl-2025b.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2025b.eb
  easybuild/easyconfigs/i/imageio/imageio-2.37.0-gfbf-2025b.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2025.2.0-iimpi-2025b.eb
  easybuild/easyconfigs/i/intel/intel-2025b.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.10.5-gfbf-2025b.eb
  easybuild/easyconfigs/m/mpi4py/mpi4py-4.1.0-gompi-2025b.eb
  easybuild/easyconfigs/n/networkx/networkx-3.5-gfbf-2025b.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.2-gompi-2025b-fb.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2025.07-gfbf-2025b.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.7.1-gfbf-2025b.eb
  easybuild/easyconfigs/s/spglib-python/spglib-python-2.6.0-gfbf-2025b.eb
Labels: change, 2025b

#23683 {math}[gfbf/2025b] RDFlib v7.1.4, ruamel.yaml v0.18.14, Seaborn v0.13.2, ...
  easybuild/easyconfigs/r/RDFlib/RDFlib-7.1.4-GCCcore-14.3.0.eb
  easybuild/easyconfigs/r/ruamel.yaml/ruamel.yaml-0.18.14-GCCcore-14.3.0.eb
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.13.2-gfbf-2025b.eb
  easybuild/easyconfigs/s/Shapely/Shapely-2.1.1-gfbf-2025b.eb
  easybuild/easyconfigs/s/sympy/sympy-1.14.0-gfbf-2025b.eb
Labels: update, 2025b

#22829 {numlib}[foss/2024a] muParser v2.3.5, Rmath v4.4.2
  easybuild/easyconfigs/m/muParser/muParser-2.3.5-GCC-13.3.0.eb
  easybuild/easyconfigs/r/Rmath/Rmath-4.4.2-foss-2024a.eb
Labels: update, 2024a, ready-to-review

#23681 {vis}[GCCcore/14.3.0] HDF v4.3.1, Leptonica v1.85.0, libcint v6.1.2, ...
  easybuild/easyconfigs/h/HDF/HDF-4.3.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/Leptonica/Leptonica-1.85.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libcint/libcint-6.1.2-gfbf-2025b.eb
  easybuild/easyconfigs/l/libcroco/libcroco-0.6.13-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.56.4-GCCcore-14.3.0.eb
Labels: update, 2025b

#23540 {geo}[foss/2024a] pyOpenRiverCam v0.8.6
  easybuild/easyconfigs/p/pyOpenRiverCam/pyOpenRiverCam-0.8.6-foss-2024a.eb
Labels: new, 2024a

#23732 Fix incorrect configopts for GOTCHA
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.7-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.7-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.8-GCCcore-14.2.0.eb
Labels: bug fix, change, 2024a, 2025a, 2022b

#23703 {data}[iimpi/2025b] HDF5 v1.14.6
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.6-iimpi-2025b.eb
Labels: update, 2025b

#23739 {data}[iimpi/2025b] netCDF v4.9.3, netCDF-Fortran v4.6.2
  easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.6.2-iimpi-2025b.eb
  easybuild/easyconfigs/n/netCDF/netCDF-4.9.3-iimpi-2025b.eb
Labels: update, 2025b

#23746 {lib,vis}[GCCcore/14.3.0] libdrm v2.4.125, Wayland v1.24.0
  easybuild/easyconfigs/l/libdrm/libdrm-2.4.125-GCCcore-14.3.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.24.0-GCCcore-14.3.0.eb
Labels: update, 2025b

#23740 {tools,vis}[GCCcore/14.3.0] JasPer v4.2.8, libheif v1.20.2, libde265 v1.0.16, Gdk-Pixbuf v2.42.12
  easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.12-GCCcore-14.3.0.eb
  easybuild/easyconfigs/j/JasPer/JasPer-4.2.8-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libde265/libde265-1.0.16-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.20.2-GCCcore-14.3.0.eb
Labels: update, 2025b

#23669 PyCharm/2025.2.0.1
  easybuild/easyconfigs/p/PyCharm/PyCharm-2025.2.0.1.eb
Labels: update

#23710 {bio}[foss/2024a] Qualimap v2.3 w/ R 4.4.2
  easybuild/easyconfigs/q/Qualimap/Qualimap-2.3-foss-2024a-R-4.4.2.eb
Labels: update, 2024a

#23711 {ai}[foss/2023a] pytorch-3dunet v1.9.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/p/pytorch-3dunet/pytorch-3dunet-1.9.1-foss-2023a-CUDA-12.1.1.eb
Labels: update, 2023a

#23666 {chem}[GCCcore/12.3.0] GPAW v25.7.0, ASE v3.26.0, gpaw-data v1.0.1, ... w/ ASE 3.26.0
  easybuild/easyconfigs/a/ASE/ASE-3.26.0-gfbf-2023a.eb
  easybuild/easyconfigs/g/GPAW/GPAW-25.7.0-foss-2023a-ASE-3.26.0.eb
  easybuild/easyconfigs/g/gpaw-data/gpaw-data-1.0.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/setuptools/setuptools-80.9.0-GCCcore-12.3.0.eb
Labels: new, update, 2023a

#23734 {tools}[iimpi/2025a] ecCodes v2.43.0
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.43.0-iimpi-2025a.eb
  easybuild/easyconfigs/e/ecCodes/ecCodes-2.43.0_fix-conflicting-types-sigsetjmp.patch
Labels: update, 2025a

#23714 {chem}[foss/2024a] Cantera v3.1.0-20250816
  easybuild/easyconfigs/c/Cantera/Cantera-3.1.0-20250816-foss-2024a.eb
  easybuild/easyconfigs/h/HighFive/HighFive-2.10.1-gompi-2024a.eb
  easybuild/easyconfigs/p/pygraphviz/pygraphviz-1.14-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-7.3.0-foss-2024a.eb
Labels: update, 2024a

#23718 {math}[foss/2024a] R-INLA v25.06.22
  easybuild/easyconfigs/r/R-INLA/R-INLA-25.06.22-foss-2024a.eb
  easybuild/easyconfigs/r/R-INLA/R-INLA-25.06.22_fix-hardcoded-deps.patch
  easybuild/easyconfigs/r/R-INLA/R-INLA-25.06.22_fix-undefined-functions.patch
  easybuild/easyconfigs/r/R-INLA/R-INLA-25.06.22_remove-hardcoding.patch
Labels: update, 2024a

#23753 {devel,lang}[intel-compilers/2025.2.0] Boost v1.88.0, SOCI v4.1.2
  easybuild/easyconfigs/b/Boost/Boost-1.88.0-intel-compilers-2025.2.0.eb
  easybuild/easyconfigs/s/SOCI/SOCI-4.1.2-intel-compilers-2025.2.0.eb
Labels: update, 2025b

#23641 {toolchain}[system/system] iomkl v2023b, iompi v2023b, OpenMPI v4.1.6, ...
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2023.2.0-iompi-2023b.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2023b.eb
  easybuild/easyconfigs/i/iompi/iompi-2023b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.6-intel-compilers-2023.2.1.eb
Labels: update, 2023b, ready-to-merge
