Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-02, with the labels that each got.

#20997 {bio}[GCC/13.2.0] Bowtie2 2.5.4
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.4-GCC-13.2.0.eb
Labels: update

#22227 {vis}[GCCcore/13.3.0] XCrySDen v1.6.2, Togl v2.0, bwidget v1.10.1
  easybuild/easyconfigs/b/bwidget/bwidget-1.10.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/q/quarto/quarto-1.5.57-x64.eb
  easybuild/easyconfigs/s/Sabre/Sabre-2013-09-28-GCC-13.3.0.eb
  easybuild/easyconfigs/t/Togl/Togl-2.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/XCrySDen/XCrySDen-1.6.2-foss-2024a.eb
Labels: update

#22238 {lib}[GCCcore/12.3.0] webvtt-py v0.5.1
  easybuild/easyconfigs/w/webvtt-py/webvtt-py-0.5.1-GCCcore-12.3.0.eb
Labels: new

#22239 {lib}[foss/2023a] fastText v0.9.2-20240313
  easybuild/easyconfigs/f/fastText/fastText-0.9.2-20240313-foss-2023a.eb
Labels: new

#21987 {perf}[gfbf/2023a] HolisticTraceAnalysis v0.2.0
  easybuild/easyconfigs/h/HolisticTraceAnalysis/HolisticTraceAnalysis-0.2.0-gfbf-2023a.eb
Labels: new

#22140 {chem}[foss/2024a] GPAW v25.1.0 w/ ASE 3.24.0
  easybuild/easyconfigs/g/GPAW/GPAW-25.1.0-foss-2024a-ASE-3.24.0.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#20998 {bio}[foss/2023b] CRISPResso2 2.3.1
  easybuild/easyconfigs/c/CRISPResso2/CRISPResso2-2.3.1-foss-2023b.eb
  easybuild/easyconfigs/c/CRISPResso2/CRISPResso2-2.3.1_fix_tests.patch
Labels: update

#22061 Fix test failure due to unresolved template
  test/easyconfigs/easyconfigs.py
Labels: bug fix, tests, EasyBuild-5.0

#22240 Change source_urls for Boost from boostorg.jfrog.io to archives.boost.io
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.76.0-gompi-2021a.eb
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.77.0-gompi-2021b.eb
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.79.0-gompi-2022a.eb
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.79.0-gompi-2022b.eb
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.81.0-gompi-2022b.eb
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.82.0-gompi-2023a.eb
  easybuild/easyconfigs/b/Boost.MPI/Boost.MPI-1.83.0-gompi-2023b.eb
  easybuild/easyconfigs/b/Boost.Python-NumPy/Boost.Python-NumPy-1.79.0-foss-2022a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-gompi-2019b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-gompic-2019b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-iimpi-2019b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.71.0-iimpic-2019b.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-gompi-2020a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-gompic-2020a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-iimpi-2020a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.74.0-GCC-10.2.0.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.76.0-GCC-10.3.0.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.77.0-GCC-11.2.0.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.79.0-GCC-11.3.0.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.82.0-GCC-12.3.0.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.83.0-GCC-13.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-gompi-2019b.eb
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-gompic-2019b.eb
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-iimpi-2019b.eb
  easybuild/easyconfigs/b/Boost/Boost-1.71.0-iimpic-2019b.eb
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-gompi-2020a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-gompic-2020a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.72.0-iimpi-2020a.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-GCC-10.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-GCC-12.3.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.74.0-iccifort-2020.4.304.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-GCC-11.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.75.0-GCC-12.3.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.76.0-GCC-10.3.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.76.0-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.77.0-GCC-11.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.77.0-intel-compilers-2021.4.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.79.0-GCC-11.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.79.0-GCC-11.3.0.eb
Labels: change

#22264 {bio}[foss/2024a] CodingQuarry v2.0
  easybuild/easyconfigs/c/CodingQuarry/CodingQuarry-2.0-foss-2024a.eb
Labels: update

#21765 {astro,lib}[foss/2023b] EveryBeam v0.6.1, WSClean v3.5, DP3 v6.2
  easybuild/easyconfigs/d/DP3/DP3-6.2-foss-2023b.eb
  easybuild/easyconfigs/d/DP3/DP3-6.2_fix-for-xsimd-error-on-neoverse-v1.patch
  easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.5.4_python_metadata.patch
  easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.6.1-foss-2023b.eb
  easybuild/easyconfigs/w/WSClean/WSClean-3.5-foss-2023b.eb
  easybuild/easyconfigs/w/WSClean/WSClean-3.5_cmake-fixes-python-and-boost.patch
  test/easyconfigs/easyconfigs.py
Labels: update

#22271 add include + lib under `grass84` subdirectory to `$CPATH`, `$LD_LIBRARY_PATH`, `$LIBRARY_PATH` for GRASS 8.4.0
  easybuild/easyconfigs/g/GRASS/GRASS-8.4.0-foss-2023a.eb
Labels: bug fix, change

#22201 {astro}[foss/2022a,foss/2023b] Casacore v3.5.0 - move download of data files to source step
  easybuild/easyconfigs/c/casacore/casacore-3.5.0-foss-2022a.eb
  easybuild/easyconfigs/c/casacore/casacore-3.5.0-foss-2023b.eb
Labels: bug fix, change

#22198 {astro}[gfbf/2023b] astropy v7.0.0
  easybuild/easyconfigs/a/astropy-testing/astropy-testing-7.0.0-gfbf-2023b.eb
  easybuild/easyconfigs/a/astropy/astropy-7.0.0-gfbf-2023b.eb
  easybuild/easyconfigs/p/pre-commit/pre-commit-3.7.0-GCCcore-13.2.0.eb
Labels: new, update

#22282 {tools}[system/system] screen v5.0.0
  easybuild/easyconfigs/s/screen/screen-5.0.0.eb
Labels: new

#22278 Remove explicit C++ standard from Bowtie2
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.4-GCC-10.3.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.4-GCC-11.2.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.4.5-GCC-11.3.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.1-GCC-10.3.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.1-GCC-12.2.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.1-GCC-12.3.0.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.4-GCC-13.2.0.eb
Labels: change, code cleanup

#22269 {data}[gompi/2024a] PnetCDF v1.14.0
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.14.0-gompi-2024a.eb
Labels: update

#22286 {bio}[system/system] Baysor v0.7.1
  easybuild/easyconfigs/b/Baysor/Baysor-0.7.1.eb
Labels: new

#22268 {chem}[foss/2023a] LAMMPS v28Oct2024 w/ kokkos CUDA 12.1.1
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-28Oct2024-foss-2023a-kokkos-mace-CUDA-12.1.1.eb
Labels: update

#22288 {vis}[GCCcore/13.3.0] xprop v1.2.8
  easybuild/easyconfigs/x/xprop/xprop-1.2.8-GCCcore-13.3.0.eb
Labels: update

#22257 Avoid using $HOME/.cargo in poetry build
  easybuild/easyconfigs/p/poetry/poetry-1.7.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/poetry/poetry-1.8.3-GCCcore-13.3.0.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix, change

#21760 {tools}[foss/2023a] netket v3.14.3
  easybuild/easyconfigs/n/netket/netket-3.14.3-foss-2023a.eb
Labels: new

#22298 {cae}[foss/2023a] OpenFOAM v5.0-20180606
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180606-foss-2023a.eb
Labels: update

#22283 {lib}[foss/2023b] pymatgen v2024.5.1, paramiko v3.5.1, uncertainties v3.2.2, boto3-1.36.16
  easybuild/easyconfigs/b/boto3/boto3-1.36.16-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/paramiko/paramiko-3.5.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/pymatgen/pymatgen-2024.5.1-foss-2023b.eb
  easybuild/easyconfigs/u/uncertainties/uncertainties-3.2.2-foss-2023b.eb
Labels: update

#22270 {lang}[GCC/13.3.0,GCCcore/13.3.0,foss/2024a] RStudio-Server v2024.12.0+467, SOCI v4.0.3, yaml-cpp v0.8.0 w/ Java 17 R 4.4.2
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2024.12.0+467-foss-2024a-Java-17-R-4.4.2.eb
  easybuild/easyconfigs/s/SOCI/SOCI-4.0.3-GCC-13.3.0.eb
  easybuild/easyconfigs/y/yaml-cpp/yaml-cpp-0.8.0-GCCcore-13.3.0.eb
Labels: update

#21961 {bio}[foss/2023a] InterOp v1.3.2
  easybuild/easyconfigs/i/InterOp/InterOp-1.3.2-foss-2023a.eb
Labels: update

#22294 add missing dependency on pybind11 for contourpy in matplotlib v3.9.2
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.9.2-gfbf-2024a.eb
Labels: bug fix, EasyBuild-5.0

#22258 unset `$BUILD_VERSION` set by `torchvision` easyblock in `preinstallopts` for `torchaudio` in easyconfigs for `PyTorch-bundle` 2.1.2
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a.eb
Labels: bug fix

#22303 {cae}[foss/2023a] OpenFOAM v6 (without ParaView)
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-foss-2023a.eb
Labels: update

#22300 {compiler}[GCCcore/13.3.0] Clang v18.1.8 w/ CUDA 12.6.0
  easybuild/easyconfigs/c/Clang/Clang-18.1.8-GCCcore-13.3.0-CUDA-12.6.0.eb
Labels: update

#22308 {lang}[GCCcore/13.3.0] SIP v6.10.0
  easybuild/easyconfigs/s/SIP/SIP-6.10.0-GCCcore-13.3.0.eb
Labels: update

#22305 {bio}[foss/2023a] dorado v0.9.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dorado/dorado-0.9.1-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22297 {vis}[foss/2023a] ParaView v5.13.2 w/ CUDA 12.1.1
  easybuild/easyconfigs/p/ParaView/ParaView-5.13.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/ParaView/ParaView-5.13.2-remove_glew_init_warning.patch
Labels: update

#22312 {chem}[gfbf/2024a] Atomsk v0.13.1
  easybuild/easyconfigs/a/Atomsk/Atomsk-0.13.1-gfbf-2024a.eb
Labels: new

#22315 {bio}[GCCcore/13.3.0] BWA v0.7.18
  easybuild/easyconfigs/b/BWA/BWA-0.7.18-GCCcore-13.3.0.eb
Labels: update

#22307 {bio,data}[GCC/12.3.0] Minimac4 v4.1.6, savvy v2.1.0, shrinkwrap v1.2.0, ...
  easybuild/easyconfigs/l/libStatGen/libStatGen-1.0.15-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/Minimac4/Minimac4-4.1.6-GCC-12.3.0.eb
  easybuild/easyconfigs/o/omp/omp-1.0.0-GCC-12.3.0.eb
  easybuild/easyconfigs/s/savvy/savvy-2.1.0-GCC-12.3.0.eb
  easybuild/easyconfigs/s/shrinkwrap/shrinkwrap-1.2.0-GCCcore-12.3.0.eb
Labels: new, update

#22262 {bio}[foss/2024a] Pairtools 1.1.2
  easybuild/easyconfigs/p/pairtools/pairtools-1.1.2-gfbf-2024a.eb
Labels: new

#22285 {numlib}[foss/2024a] Hypre v2.32.0
  easybuild/easyconfigs/h/Hypre/Hypre-2.32.0-foss-2024a.eb
Labels: update

#22310 {tools}[system/system] CVX v2.2.2 w/ MATLAB 2024b
  easybuild/easyconfigs/c/CVX/CVX-2.2.2-MATLAB-2024b.eb
Labels: update

#22313 {bio}[foss/2023b] MATES v0.1.8
  easybuild/easyconfigs/m/MATES/MATES-0.1.8-foss-2023b.eb
Labels: update

#22317 {vis}[foss/2023a] ParaView v5.13.2
  easybuild/easyconfigs/p/ParaView/ParaView-5.13.2-foss-2023a.eb
Labels: update

#22295 {chem}[system/system] LOBSTER v5.1.1
  easybuild/easyconfigs/l/LOBSTER/LOBSTER-5.1.1.eb
Labels: new

#22112 {lib}[GCCcore/14.2.0] OpenMPI v5.0.7, libfabric v2.0.0, PMIx v5.0.6, PRRTE v3.0.8, UCX v1.18.0, UCC v1.3.0
  easybuild/easyconfigs/l/libfabric/libfabric-2.0.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.6_build-with-internal-cuda-header.patch
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7-GCC-14.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7_fix-sshmem-build-failure.patch
  easybuild/easyconfigs/p/PMIx/PMIx-5.0.6-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/PRRTE/PRRTE-3.0.8-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/UCC/UCC-1.3.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/UCX/UCX-1.18.0-GCCcore-14.2.0.eb
Labels: update, 2025a

#21937 {vis}[GCCcore/13.2.0,foss/2023b,gfbf/2023b] MONAI v1.4.0, PyAMG v5.2.1, zarr v2.18.3, ...
  easybuild/easyconfigs/c/clearml/clearml-1.16.5-foss-2023b.eb
  easybuild/easyconfigs/e/einops/einops-0.8.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/MLflow/MLflow-2.18.0-gfbf-2023b.eb
  easybuild/easyconfigs/m/MONAI/MONAI-1.4.0-foss-2023b.eb
  easybuild/easyconfigs/n/NiBabel/NiBabel-5.3.2-gfbf-2023b.eb
  easybuild/easyconfigs/o/ONNX/ONNX-1.17.0-gfbf-2023b.eb
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-4.0.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenSlide/OpenSlide-4.0.0_fix-poison.patch
  easybuild/easyconfigs/o/openslide-python/openslide-python-1.4.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PyAMG/PyAMG-5.2.1-gfbf-2023b.eb
  easybuild/easyconfigs/p/pydicom/pydicom-3.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.24.0-foss-2023b.eb
  easybuild/easyconfigs/t/tensorboardX/tensorboardX-2.6.2.2-foss-2023b.eb
  easybuild/easyconfigs/z/zarr/zarr-2.18.3-foss-2023b.eb
Labels: new, update

#22324 migrate easyconfig for NEURON v8.2.6 to use custom easyblock for NEURON
  easybuild/easyconfigs/n/NEURON/NEURON-8.2.6-foss-2023a.eb
Labels: change, EasyBuild-5.0

#22246 {bio}[foss/2023a] Verkko v2.2.1, GraphAligner v1.0.20, Winnowmap v2.03, ...
  easybuild/easyconfigs/g/GraphAligner/GraphAligner-1.0.20-foss-2023a.eb
  easybuild/easyconfigs/g/GraphAligner/GraphAligner-1.0.20_fix-makefile.patch
  easybuild/easyconfigs/m/MashMap/MashMap-3.1.3-GCC-12.3.0.eb
  easybuild/easyconfigs/v/Verkko/Verkko-2.2.1-foss-2023a.eb
  easybuild/easyconfigs/w/Winnowmap/Winnowmap-2.03-GCCcore-12.3.0.eb
Labels: new, update

#22318 {vis}[GCCcore/13.3.0] tesseract v5.5.0, Leptonica v1.85.0
  easybuild/easyconfigs/l/Leptonica/Leptonica-1.85.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/t/tesseract/tesseract-5.5.0-GCCcore-13.3.0.eb
Labels: update

#22320 {bio}[GCC/13.3.0] Flye v2.9.5
  easybuild/easyconfigs/f/Flye/Flye-2.9.5-GCC-13.3.0.eb
Labels: update

#22322 {devel}[GCCcore/13.3.0] line_profiler v4.2.0
  easybuild/easyconfigs/l/line_profiler/line_profiler-4.2.0-GCCcore-13.3.0.eb
Labels: update

#22341 {chem}[foss/2024a] Critic2 v1.2
  easybuild/easyconfigs/c/Critic2/Critic2-1.2-foss-2024a.eb
Labels: update

#22342 {lang}[system/system] Julia v1.11.3 w/ linux x86_64
  easybuild/easyconfigs/j/Julia/Julia-1.11.3-linux-x86_64.eb
Labels: update

#22326 change toolchain of `pytest` 4.6.11 w/ Python 2.7.18 to `GCCcore`
  easybuild/easyconfigs/p/pytest/pytest-4.6.11-GCCcore-12.3.0-Python-2.7.18.eb
Labels: change

#22348 Add correct checksum in libxc-6.2.2-GCC-13.2.0.eb
  easybuild/easyconfigs/l/libxc/libxc-6.2.2-GCC-13.2.0.eb
Labels: bug fix, change

#21845 {lib}[foss/2023b] synthcity v0.2.11, pycodestyle v2.11.1, python-igraph v0.11.8, ... w/ PyTorch 2.1.2, llvmlite, ...
  easybuild/easyconfigs/a/accelerate/accelerate-1.0.1-foss-2023b.eb
  easybuild/easyconfigs/d/DECAF-synthetic-data/DECAF-synthetic-data-0.1.6-foss-2023b.eb
  easybuild/easyconfigs/f/fastai/fastai-2.7.18-foss-2023b.eb
  easybuild/easyconfigs/h/HF-Datasets/HF-Datasets-3.1.0-gfbf-2023b.eb
  easybuild/easyconfigs/i/imbalanced-learn/imbalanced-learn-0.12.4-gfbf-2023b.eb
  easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-13.2.0-llvmlite.eb
  easybuild/easyconfigs/l/lifelines/lifelines-0.29.0-gfbf-2023b.eb
  easybuild/easyconfigs/n/numba/numba-0.60.0-foss-2023b.eb
  easybuild/easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-1.9.5-foss-2023b.eb
  easybuild/easyconfigs/p/pycodestyle/pycodestyle-2.11.1-foss-2023b.eb
  easybuild/easyconfigs/p/python-igraph/python-igraph-0.11.8-foss-2023b.eb
  easybuild/easyconfigs/s/SHAP/SHAP-0.46.0-foss-2023b.eb
  easybuild/easyconfigs/s/spaCy/spaCy-3.7.5-foss-2023b.eb
  easybuild/easyconfigs/s/synthcity/synthcity-0.2.11-foss-2023b.eb
  easybuild/easyconfigs/t/torchdata/torchdata-0.7.1-foss-2023b-PyTorch-2.1.2.eb
  easybuild/easyconfigs/t/torchtext/torchtext-0.16.2-foss-2023b-PyTorch-2.1.2.eb
  easybuild/easyconfigs/t/tsai/tsai-0.3.9-foss-2023b.eb
Labels: new, update

#22352 {bio}[GCCcore/12.3.0] Trim_Galore v0.6.10, cutadapt v1.18 w/ Python 2.7.18
  easybuild/easyconfigs/c/cutadapt/cutadapt-1.18-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.6.10-GCCcore-12.3.0-Python-2.7.18.eb
Labels: update

#22351 {bio}[GCCcore/12.3.0] bmtagger v3.101, SRPRISM v3.3.2, NGS v3.0.1 w/ Java 11
  easybuild/easyconfigs/b/bmtagger/bmtagger-3.101-gompi-2023a-Java-11.eb
  easybuild/easyconfigs/n/NGS/NGS-3.0.1-GCCcore-12.3.0-Java-11.eb
  easybuild/easyconfigs/s/SRPRISM/SRPRISM-3.3.2-GCCcore-12.3.0-Java-11.eb
Labels: update

#22350 {bio}[GCC/12.3.0,GCCcore/12.3.0] taxator-tk v1.5.0, SeqAn v2.4.0 w/ Python 2.7.18
  easybuild/easyconfigs/s/SeqAn/SeqAn-2.4.0-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.5.0-GCC-12.3.0-Python-2.7.18.eb
Labels: update

#22353 {lang,lib,tools}[GCCcore/12.3.0] SciPy-bundle v2024.06, hypothesis v4.57.1, pybind11 v2.9.2 w/ Python 2.7.18
  easybuild/easyconfigs/h/hypothesis/hypothesis-4.57.1-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.9.2-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.06-foss-2023a-Python-2.7.18.eb
Labels: update

#22384 bump version to 5.0.0beta2
  setup.py
Labels: EasyBuild-5.0

#22355 {lang,vis}[GCCcore/12.3.0,foss/2023a] matplotlib v2.2.5, Tkinter v2.7.18 w/ Python 2.7.18
  easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.5-foss-2023a-Python-2.7.18.eb
  easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.18-GCCcore-12.3.0-Python-2.7.18.eb
Labels: update

#22385 {tools}[system] EasyBuild v0.5.0.0beta2 (second beta release of EasyBuild v5.0.0)
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-0.5.0.0beta2.eb
Labels: update

#22393 {bio}[GCC/12.3.0] Bowtie2 v2.5.4 w/ Python 2.7.18
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.4-GCC-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.5.4_python2.patch
Labels: update

#22390 {bio}[foss/2023a] Seaborn v0.9.1 w/ Python 2.7.18
  easybuild/easyconfigs/s/Seaborn/Seaborn-0.9.1-foss-2023a-Python-2.7.18.eb
Labels: update

#22379 {tools}[GCCcore/13.3.0] python-zlib-ng v0.5.1 (+ fix dependency for pytest-workflow 2.1.0)
  easybuild/easyconfigs/p/pytest-workflow/pytest-workflow-2.1.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/python-zlib-ng/python-zlib-ng-0.5.1-GCCcore-13.3.0.eb
Labels: bug fix, new

#22334 enable plugins that require HDF5 + Boost dependencies for Visit v3.4.1
  easybuild/easyconfigs/v/Visit/Visit-3.4.1-foss-2023a.eb
Labels: enhancement

#22391 {bio}[GCC/12.3.0] SPAdes v3.15.5 w/ Python 2.7.18
  easybuild/easyconfigs/s/SPAdes/SPAdes-3.15.5-GCC-12.3.0-Python-2.7.18.eb
Labels: update

#21887 {cae}[system/system] ABAQUS v2024 w/ hotfix 2424, hotfix 2441
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2024-hotfix-2424.eb
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2024-hotfix-2441.eb
Labels: update

#22388 {bio}[gompi/2023a] MaxBin v2.2.7 w/ Python 2.7.18
  easybuild/easyconfigs/m/MaxBin/MaxBin-2.2.7-gompi-2023a-Python-2.7.18.eb
Labels: update

#22389 {bio}[GCC/12.3.0] MetaBAT v2.17
  easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.17-GCC-12.3.0.eb
  easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.17_use_eb_zlib_and_htslib_and_flags.patch
Labels: update

#22396 {bio}[gompi/2023a] Unicycler v0.5.0
  easybuild/easyconfigs/u/Unicycler/Unicycler-0.5.0-gompi-2023a.eb
Labels: update

#22380 avoid using `buildcmd` in PySide2 easyconfig
  easybuild/easyconfigs/p/PySide2/PySide2-5.14.2.3-GCCcore-10.2.0.eb
Labels: change, code cleanup, EasyBuild-5.0
