Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-06, with the labels that each got.

#22989 {bio}[system/system] MIGEC v1.2.9 w/ Java 8
  easybuild/easyconfigs/m/MIGEC/MIGEC-1.2.9-Java-8.eb
Labels: new

#22986 {tools, lib}[GCCcore/14.2.0, gompi/2025a] attr v2.5.2, mpifileutils v0.12, dtcmp v1.1.5, libcircle v0.3, lwgrp v1.0.6
  easybuild/easyconfigs/a/attr/attr-2.5.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.5-gompi-2025a.eb
  easybuild/easyconfigs/l/libcircle/libcircle-0.3-gompi-2025a.eb
  easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.6-gompi-2025a.eb
  easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.12-gompi-2025a.eb
Labels: update

#22987 {tools}[GCCcore/14.2.0] APR v1.7.6, APR-util v1.6.3
  easybuild/easyconfigs/a/APR-util/APR-util-1.6.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/a/APR/APR-1.7.6-GCCcore-14.2.0.eb
Labels: update

#22977 {tools}[system/system] Nextflow v25.04.2
  easybuild/easyconfigs/n/Nextflow/Nextflow-25.04.2.eb
Labels: update

#22590 {tools}[GCCcore/13.2.0] hunspell v1.7.2
  easybuild/easyconfigs/h/hunspell/hunspell-1.7.2-GCCcore-13.2.0.eb
Labels: update

#22050 reorder the enchant-2 easyconfigs
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.3.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.3.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/e/enchant-2/enchant-2-2.6.5-GCCcore-12.3.0.eb
Labels: code cleanup

#22980 make Rust a build dependency for maturin 1.8.3
  easybuild/easyconfigs/m/maturin/maturin-1.8.3-GCCcore-14.2.0.eb
Labels: change

#22981 make Rust a build dependency for maturin 1.6.0
  easybuild/easyconfigs/j/jupyter-server/jupyter-server-2.14.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/maturin/maturin-1.6.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb
Labels: change

#22985 make Rust a build dependency for maturin 1.1.0 (2022b generation)
  easybuild/easyconfigs/f/fastparquet/fastparquet-2023.4.0-gfbf-2022b.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/maturin/maturin-1.1.0-GCCcore-12.2.0.eb
Labels: change

#22990 {devel}[GCCcore/14.3.0] Autotools v20250527, Autoconf v2.72, Automake v1.18, ...
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.72-GCCcore-14.3.0.eb
  easybuild/easyconfigs/a/Automake/Automake-1.18-GCCcore-14.3.0.eb
  easybuild/easyconfigs/a/Autotools/Autotools-20250527-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libtool/libtool-2.5.4-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/Perl/Perl-5.40.2-GCCcore-14.3.0.eb
Labels: update, 2025b

#22528 {bio}[system/system] HiCTools v3.30.00 w/ Java 17
  easybuild/easyconfigs/h/HiCTools/HiCTools-3.30.00-Java-17.eb
Labels: new

#22526 {bio}[gfbf/2023a] SEACR v1.3
  easybuild/easyconfigs/s/SEACR/SEACR-1.3-gfbf-2023a.eb
Labels: new

#22996 add missing fstring in mixed component bundle easyconfig templates
  contrib/easyconfig-templates/2022a/Bundle-mixed-components.eb.tmpl
  contrib/easyconfig-templates/2023a/Bundle-mixed-components.eb.tmpl
  contrib/easyconfig-templates/2024a/Bundle-mixed-components.eb.tmpl
Labels: bug fix

#22998 Fix build failure in M4 1.4.19 when C standard is set
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-15.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19_fix-asm-usage-when-c-std-is-set.patch
Labels: bug fix, change

#22064 {devel}[foss/2024a] Triton v3.1.0 w/ CUDA 12.6.0
  easybuild/easyconfigs/t/Triton/Triton-3.1.0-foss-2024a-CUDA-12.6.0.eb
  easybuild/easyconfigs/t/Triton/Triton-3.1.0_5fe38ff_CUDA-12.6_ptx.patch
  easybuild/easyconfigs/t/Triton/Triton-3.1.0_5fe38ff_eb_env_python_build.patch
Labels: update

#23011 {vis}[system/system] Embree v3.13.5, Embree v4.4.0
  easybuild/easyconfigs/e/Embree/Embree-3.13.5.eb
  easybuild/easyconfigs/e/Embree/Embree-4.4.0.eb
Labels: update

#22938 {vis}[foss/2023a] Kornia v0.7.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/k/Kornia/Kornia-0.7.1-foss-2023a-CUDA-12.1.1.eb
Labels: new

#23016 {cae}[GCC/13.3.0] ngspice v44.2
  easybuild/easyconfigs/n/ngspice/ngspice-44.2-GCC-13.3.0.eb
Labels: update

#22966 {phys}[foss/2023a] Siesta v5.4.0
  easybuild/easyconfigs/s/Siesta/Siesta-5.4.0-foss-2023a.eb
Labels: update

#23030 Fix Perl-bundle-CPAN `IO::Socket::SSL` failing tests
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.40.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-IO-Socket-SSL-OCSP.patch
Labels: priority:high, bug fix, change

#23043 {tools}[gfbf/2024a] dask-labextension v7.0.0
  easybuild/easyconfigs/d/dask-labextension/dask-labextension-7.0.0-gfbf-2024a.eb
Labels: update

#20768 {lib}[GCC/12.3.0,GCCcore/12.3.0] DGL v1.1.3, DLPack v0.8, Parallel-Hashmap v1.36, ... w/ CUDA 12.1.1
  easybuild/easyconfigs/d/DGL/DGL-1.1.3-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/d/DGL/DGL-1.1.3_use_externals_instead_of_submodules.patch
  easybuild/easyconfigs/d/DLPack/DLPack-0.8-GCC-12.3.0.eb
  easybuild/easyconfigs/d/DMLC-Core/DMLC-Core-0.5-GCC-12.3.0.eb
  easybuild/easyconfigs/g/GKlib-METIS/GKlib-METIS-5.1.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Parallel-Hashmap/Parallel-Hashmap-1.36-GCCcore-12.3.0.eb
Labels: update

#22974 {phys}[foss/2024a] pycomlink v0.4.1
  easybuild/easyconfigs/p/pycomlink/pycomlink-0.4.1-foss-2024a.eb
Labels: new

#23019 {tools}[GCC/13.3.0] Netgen v1.5.295
  easybuild/easyconfigs/n/Netgen/Netgen-1.5.295-GCC-13.3.0.eb
Labels: new

#23024 {bio}[foss/2024a] bx-python v0.13.0, pyBigWig v0.3.24, RSeQC v5.0.4
  easybuild/easyconfigs/b/bx-python/bx-python-0.13.0-foss-2024a.eb
  easybuild/easyconfigs/p/pyBigWig/pyBigWig-0.3.24-gfbf-2024a.eb
  easybuild/easyconfigs/r/RSeQC/RSeQC-5.0.4-foss-2024a.eb
Labels: update

#23057 fix source URL for c-ares
  easybuild/easyconfigs/c/c-ares/c-ares-1.17.2-GCCcore-10.3.0.eb
Labels: bug fix

#22997 {chem}[foss/2024a] NAMD v3.0.1 w/ CUDA 12.6.0
  easybuild/easyconfigs/n/NAMD/NAMD-3.0.1-foss-2024a-CUDA-12.6.0.eb
Labels: update

#23058 {chem}[iomkl/2023a] OpenMolcas v24.10, GlobalArrays v5.8.2, HDF5 v1.14.0
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-iomkl-2023a.eb
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.0-iompi-2023a.eb
  easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-24.10-iomkl-2023a.eb
Labels: update

#23056 {tools}[GCCcore/13.3.0] aria2 v1.37.0, c-ares v1.34.5, CppUnit v1.15.1
  easybuild/easyconfigs/a/aria2/aria2-1.37.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/c-ares/c-ares-1.34.5-GCCcore-13.3.0.eb
Labels: update

#22155 {bio}[GCC/13.3.0] dssp v4.4.10, libcifpp v7.0.8, libmcfp v1.3.4, mrc v1.3.13
  easybuild/easyconfigs/d/dssp/dssp-4.4.10-GCC-13.3.0.eb
  easybuild/easyconfigs/l/libcifpp/libcifpp-7.0.8-GCC-13.3.0.eb
  easybuild/easyconfigs/l/libmcfp/libmcfp-1.3.4-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/mrc/mrc-1.3.13-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/mrc/mrc-1.3.13_relax_libmcfp_version.patch
Labels: new

#19225 {chem}[foss/2022b] xtb v6.6.1
  easybuild/easyconfigs/x/xtb/xtb-6.6.1-foss-2022b.eb
Labels: update

#19150 {chem}[GCC/11.2.0,gfbf/2022a,gfbf/2022b] NBO v7.0.10 w/ i4
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-11.2.0-i4.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2022a-i4.eb
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2022b-i4.eb
Labels: update

#23066 {bio}[foss/2023a] ViennaRNA v2.7.0
  easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.7.0-flexiblas-for-RNAxplorer.patch
  easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.7.0-foss-2023a.eb
Labels: update

#23059 {lib}[GCCcore/14.2.0] libdeflate v1.24, libpng v1.6.48, libjpeg-turbo v3.1.0, ...
  easybuild/easyconfigs/j/jbigkit/jbigkit-2.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.7.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libdeflate/libdeflate-1.24-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-3.1.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libpng/libpng-1.6.48-GCCcore-14.2.0.eb
  easybuild/easyconfigs/n/NASM/NASM-2.16.03-GCCcore-14.2.0.eb
Labels: update, 2025a

#23069 {data,math,numlib}[GCCcore/14.2.0] PostgreSQL v17.5, MPFR v4.2.2, GSL v2.8
  easybuild/easyconfigs/g/GSL/GSL-2.8-GCC-14.2.0.eb
  easybuild/easyconfigs/m/MPFR/MPFR-4.2.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-17.5-GCCcore-14.2.0.eb
Labels: update

#23060 {phys}[GCCcore/14.2.0] UDUNITS v2.2.28
  easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28-GCCcore-14.2.0.eb
Labels: update, 2025a

#22524 {bio}[foss/2023a] mOTUlizer v0.3.2
  easybuild/easyconfigs/m/mOTUlizer/mOTUlizer-0.3.2-foss-2023a.eb
  easybuild/easyconfigs/m/mOTUlizer/mOTUlizer-0.3.2_depend_on_igraph_not_python-igraph.patch
Labels: new

#23068 ensure that configure step of Zoltan uses an up-to-date `config.guess`
  easybuild/easyconfigs/z/Zoltan/Zoltan-3.901-foss-2023a.eb
Labels: bug fix, change, EESSI

#21296 {math}[GCCcore/11.3.0,GCCcore/13.2.0] Infomap v2.8.0
  easybuild/easyconfigs/i/Infomap/Infomap-2.8.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/i/Infomap/Infomap-2.8.0-GCCcore-13.2.0.eb
Labels: update

#20529 {numlib}[system/system] cuDNN v9.1.1.17 w/ CUDA 12.4.0
  easybuild/easyconfigs/c/cuDNN/cuDNN-9.1.1.17-CUDA-12.4.0.eb
Labels: update

#21622 {geo}[foss/2023a] geosphere v1.5-20
  easybuild/easyconfigs/g/geosphere/geosphere-1.5-20-foss-2023a.eb
Labels: update

#23071 add patch for porefoam 2023-12-01 to make sure that case directory has user write permissions after copying
  easybuild/easyconfigs/p/porefoam/porefoam-2023-12-01-foss-2023a.eb
  easybuild/easyconfigs/p/porefoam/porefoam-2023-12-01_fix-case-dir-permissions.patch
Labels: bug fix, change

#23065 {vis}[system/system] adding easyconfigs: OSPRay-3.2.0.eb
  easybuild/easyconfigs/o/OSPRay/OSPRay-3.2.0.eb
Labels: update

#23075 update SuperLU_DIST easyconfigs to rely on updated SuperLU easyblock for configure options for ParMETIS
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.0-foss-2022a.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-foss-2022b.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-foss-2023a.eb
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.2.1-foss-2023b.eb
Labels: change, code cleanup

#23073 add patch to fix support for non-x86_64 architectures for MEGAHIT 1.2.9
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.3.0-Python-2.7.18.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9_support-non-x86_64-architectures.patch
Labels: bug fix, EESSI, aarch64

#23040 {math}[foss/2023a] Dakota v6.22.0
  easybuild/easyconfigs/d/Dakota/Dakota-6.22.0-foss-2023a.eb
Labels: update

#23035 {math}[GCCcore/13.3.0] matlab-proxy v0.25.1
  easybuild/easyconfigs/m/matlab-proxy/matlab-proxy-0.25.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/matlab-proxy/matlab-proxy-0.25.1_use_lic_from_eb_installed_matlab.patch
Labels: update

#23079 Fix failing contourpy installation in matplotlib-3.7.2-iimkl-2023a with rpath (EB5 default)
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.7.2-iimkl-2023a.eb
Labels: bug fix

#23081 {devel}[foss/2025a] buildenv vdefault w/ CUDA 12.8.0
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2025a-CUDA-12.8.0.eb
  easybuild/easyconfigs/b/buildenv/buildenv-default-foss-2025a.eb
Labels: update, 2025a

#23078 Ginkgo requires a few MPI slots at configure time, so allow oversubscription
  easybuild/easyconfigs/g/Ginkgo/Ginkgo-1.9.0-gompi-2023b-CUDA-12.8.0.eb
  easybuild/easyconfigs/g/Ginkgo/Ginkgo-1.9.0-gompi-2023b.eb
  easybuild/easyconfigs/g/Ginkgo/ginkgo_1.9.0_increase_test_tolerance.patch
  easybuild/easyconfigs/g/Ginkgo/ginkgo_1.9.0_remove_matrix_statistics_benchmark.patch
Labels: change

#23022 New version of VScode/code-server
  easybuild/easyconfigs/c/code-server/code-server-4.100.2.eb
Labels: update

#23083 {devel}[system/system] Stack v3.5.1
  easybuild/easyconfigs/s/Stack/Stack-3.5.1.eb
Labels: update

#22884 {data}[GCCcore/13.2.0,gfbf/2023b] polars v1.28.1, DeltaLake v0.25.5, maturin v1.8.3, ... w/ Rust 1.86.0
  easybuild/easyconfigs/d/DeltaLake/DeltaLake-0.25.5-gfbf-2023b.eb
  easybuild/easyconfigs/p/polars/polars-1.28.1-gfbf-2023b.eb
  easybuild/easyconfigs/p/polars/polars-1.28.1_polars-utils.patch
  easybuild/easyconfigs/r/Rust/Rust-1.86.0-GCCcore-13.2.0-nightly.eb
Labels: update

#22822 {data}[GCCcore/13.3.0,gfbf/2024a] polars v1.28.1, DeltaLake v0.25.5, maturin v1.8.3, ... w/ Rust 1.86.0
  easybuild/easyconfigs/d/DeltaLake/DeltaLake-0.25.5-gfbf-2024a.eb
  easybuild/easyconfigs/p/polars/polars-1.28.1-gfbf-2024a.eb
  easybuild/easyconfigs/r/Rust/Rust-1.86.0-GCCcore-13.3.0.eb
Labels: update

#22886 {bio}[GCCcore/13.2.0] scNanoGPS v2.0, tabix v0.2.6, Subread v2.1.1, ...
  easybuild/easyconfigs/a/annovar/annovar-20200607-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/gffread/gffread-0.12.7-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LIQA/LIQA-1.3.4-foss-2023b.eb
  easybuild/easyconfigs/s/Subread/Subread-2.1.1-GCC-13.2.0.eb
  easybuild/easyconfigs/s/scNanoGPS/scNanoGPS-2.0-foss-2023b.eb
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-13.2.0.eb
Labels: update

#23095 {bio}[system/system] JACUSA2 v2.0.4 w/ Java 8
  easybuild/easyconfigs/j/JACUSA2/JACUSA2-2.0.4-Java-8.eb
Labels: new

#19241 {chem}[foss/2022b] CENSO v1.2.0
  easybuild/easyconfigs/c/CENSO/CENSO-1.2.0-foss-2022b.eb
Labels: update

#23099 only run easyconfigs test suite with Python 3.11 & Lua module syntax for now (easyconfigs merge sprint)
  .github/workflows/unit_tests.yml
Labels: tests, workflow

#22911 {tools}[GCCcore/13.3.0] tdb v1.4.9
  easybuild/easyconfigs/t/tdb/tdb-1.4.9-GCCcore-13.3.0.eb
Labels: new

#23093 {tools}[GCCcore/14.2.0] xxd v9.1.1457
  easybuild/easyconfigs/x/xxd/xxd-9.1.1457-GCCcore-14.2.0.eb
Labels: update

#23021 {tools}[GCCcore/13.3.0] IcarusVerilog v12.0
  easybuild/easyconfigs/i/IcarusVerilog/IcarusVerilog-12.0-GCCcore-13.3.0.eb
Labels: new

#23094 Update homepage URL for IsoSeq to correct repository link
  easybuild/easyconfigs/i/IsoSeq/IsoSeq-3.8.2-linux-x86_64.eb
  easybuild/easyconfigs/i/IsoSeq/IsoSeq-4.0.0-linux-x86_64.eb
Labels: bug fix

#23097 {lib,tools}[GCCcore/14.2.0] msgpack-c v6.1.0, googletest v1.17.0
  easybuild/easyconfigs/g/googletest/googletest-1.17.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/m/msgpack-c/msgpack-c-6.1.0-GCCcore-14.2.0.eb
Labels: update

#19659 {bio}[GCC/12.3.0,gfbf/2023a] rmats2sashimiplot v3.0.0, Pysam v0.22.0
  easybuild/easyconfigs/r/rmats2sashimiplot/rmats2sashimiplot-3.0.0-gfbf-2023a.eb
Labels: new

#22533 {bio}[foss/2023a] HiC-Pro v3.1.0 w/ R 4.3.2
  easybuild/easyconfigs/b/bx-python/bx-python-0.10.0-gfbf-2023a.eb
  easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0-foss-2023a-R-4.3.2.eb
  easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0_fix_paths.patch
  easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0_fix_slurm_script.patch
  easybuild/easyconfigs/i/iced/iced-0.5.13-gfbf-2023a.eb
Labels: update

#20922 {lib}[foss/2023a] GPyTorch v1.11 w/ CUDA 12.1.1
  easybuild/easyconfigs/g/GPyTorch/GPyTorch-1.11-foss-2023a-CUDA-12.1.1.eb
Labels: update

#21068 {bio}[GCCcore/11.3.0] PAML v4.9j
  easybuild/easyconfigs/p/PAML/PAML-4.9j-GCCcore-11.3.0.eb
Labels: update

#23101 move toolchain from foss to gfbf for bx-python v0.13.0
  easybuild/easyconfigs/b/bx-python/bx-python-0.13.0-gfbf-2024a.eb
Labels: change

#13231 {vis}[system] Gephi v0.9.2
  easybuild/easyconfigs/g/Gephi/Gephi-0.10.1-x86_64.eb
Labels: new

#22999 {math}[foss/2024a,gfbf/2024a,gompi/2024a] FEBio v4.6, Mmg v5.8.0, levmar v2.6
  easybuild/easyconfigs/f/FEBio/FEBio-4.6-foss-2024a.eb
  easybuild/easyconfigs/f/FEBio/FEBio-4.6_fixes.patch
  easybuild/easyconfigs/l/levmar/levmar-2.6-gfbf-2024a.eb
  easybuild/easyconfigs/m/Mmg/Mmg-5.8.0-gompi-2024a.eb
Labels: new, update

#19817 {bio}[GCC/12.3.0] fineSTRUCTURE v2.1.3
  easybuild/easyconfigs/f/fineSTRUCTURE/fineSTRUCTURE-2.1.3-GCC-12.3.0.eb
Labels: new

#22542 Add easyconfig nsync-1.29.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/n/nsync/nsync-1.29.2-GCCcore-13.2.0.eb
Labels: update

#22502 Add easyconfig ncdu-1.20-GCC-13.2.0.eb
  easybuild/easyconfigs/n/ncdu/ncdu-1.20-GCC-13.2.0.eb
Labels: update

#21428 {chem}[gfbf/2023b] NBO v7.0.10
  easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2023b.eb
Labels: update

#19939 {bio}[foss/2023a] EvoDiff v1.1.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/e/EvoDiff/EvoDiff-1.1.0-foss-2023a-CUDA-12.1.1.eb
Labels: new

#23104 {lib}[GCCcore/14.2.0] fmt v11.2.0
  easybuild/easyconfigs/f/fmt/fmt-11.2.0-GCCcore-14.2.0.eb
Labels: update

#22543 Add patch for RISC-V architecture detection to ncbi-vdb 3.1.1
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.1.1-gompi-2023b.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.1.1-riscv.patch
Labels: change, riscv

#23076 {bio}[foss/2023b] openCARP v18.0 w/ Ginkgo CUDA 12.8.0
  easybuild/easyconfigs/o/openCARP/openCARP-18.0-foss-2023b-Ginkgo-CUDA-12.8.0.eb
Labels: update

#22304 {phys}[foss/2023a] DFTB+ v24.1 w/ PLUMED 2.9.0
  easybuild/easyconfigs/d/DFTB+/DFTB+-24.1-foss-2023a-PLUMED-2.9.0.eb
Labels: update

#22836 {perf}[foss/2024a] MUST v1.10.0
  easybuild/easyconfigs/m/MUST/MUST-1.10.0-foss-2024a.eb
Labels: update

#22273 {data},foss/2023b] HDBSCAN v0.8.40
  easybuild/easyconfigs/h/HDBSCAN/HDBSCAN-0.8.40-foss-2023b.eb
Labels: update

#22803 {data}[foss/2023a] spacyr v1.3.0
  easybuild/easyconfigs/s/spacyr/spacyr-1.3.0-foss-2023a.eb
Labels: new

#21084 {bio}[foss/2023b] AUGUSTUS v3.5.0
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.5.0-foss-2023b.eb
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.5.0_fix-gcc13.patch
Labels: update

#21868 build CORSIKA v77550 in installation directory
  easybuild/easyconfigs/c/CORSIKA/CORSIKA-77550-foss-2023a.eb
Labels: bug fix, change

#22496 {bio}[foss/2023b] MDAnalysis v2.7.0, mrcfile v1.5.0
  easybuild/easyconfigs/m/MDAnalysis/MDAnalysis-2.7.0-foss-2023b.eb
  easybuild/easyconfigs/m/mrcfile/mrcfile-1.5.0-gfbf-2023b.eb
Labels: update

#22943 {bio}[foss/2023a] Pychopper v2.7.10
  easybuild/easyconfigs/p/Pychopper/Pychopper-2.7.10-foss-2023a.eb
Labels: new

#23107 {devel}[GCCcore/14.2.0] glog v0.7.1, gflags v2.2.2
  easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/glog/glog-0.7.1-GCCcore-14.2.0.eb
Labels: update

#20664 {lib}[foss/2023a] nnU-Net v2.4.2, MedPy v0.5.1, dicom2nifti v2.4.10, ... w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dicom2nifti/dicom2nifti-2.4.10-gfbf-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/m/MedPy/MedPy-0.5.1-foss-2023a.eb
  easybuild/easyconfigs/n/nnU-Net/nnU-Net-2.4.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/python-gdcm/python-gdcm-3.0.23.1-GCCcore-12.3.0.eb
Labels: new

#22413 {devel}[GCCcore/13.2.0] robin-map v1.3.0
  easybuild/easyconfigs/r/robin-map/robin-map-1.3.0-GCCcore-13.2.0.eb
Labels: new

#23109 remove dependency on Python-bundle-PyPI from pytest v8.3.3
  easybuild/easyconfigs/p/pytest/pytest-8.3.3-GCCcore-13.3.0.eb
Labels: code cleanup

#22642 {lib}[GCCcore/13.2.0] python-glfw v2.8.0, SdfLib v20250125, TinyXML-2 v11.0.0, ...
  easybuild/easyconfigs/a/absl-py/absl-py-2.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/Cereal/Cereal-1.3.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/e/etils/etils-1.12.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GLFW/GLFW-3.4-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GLM/GLM-1.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/python-glfw/python-glfw-2.8.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SdfLib/SdfLib-20250125-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/TinyXML-2/TinyXML-2-11.0.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/tinyobjloader/tinyobjloader-2.0.0rc13-GCCcore-13.2.0.eb
Labels: new, update

#19825 {math}[GCC/13.2.0,intel-compilers/2023.2.1] libcerf v2.4
  easybuild/easyconfigs/l/libcerf/libcerf-2.4-GCC-13.2.0.eb
  easybuild/easyconfigs/l/libcerf/libcerf-2.4-intel-compilers-2023.2.1.eb
Labels: update, 2023b

#20225 {cae}[system/system] FLUENT v2024R1
  easybuild/easyconfigs/f/FLUENT/FLUENT-2024R1.eb
Labels: update

#22414 {devel}[GCCcore/13.2.0] nanobind v2.5.0
  easybuild/easyconfigs/n/nanobind/nanobind-2.5.0-GCCcore-13.2.0.eb
Labels: new

#22407 {bio}[GCCcore/12.3.0] Bracken v2.9
  easybuild/easyconfigs/b/Bracken/Bracken-2.9-GCCcore-12.3.0.eb
Labels: update

#22411 {bio}[GCC/12.3.0] Sniffles v2.4
  easybuild/easyconfigs/s/Sniffles/Sniffles-2.4-GCC-12.3.0.eb
Labels: update

#22266 {bio}[foss/2023a] snipit v1.6
  easybuild/easyconfigs/s/snipit/snipit-1.6-foss-2023a.eb
Labels: new

#22382 {bio}[system/system] Minimac3 v2.0.1
  easybuild/easyconfigs/m/Minimac3/Minimac3-2.0.1.eb
Labels: new

#22516 {data}[GCC/13.2.0] Virtuoso-opensource for 2023b
  easybuild/easyconfigs/v/Virtuoso-opensource/Virtuoso-opensource-7.2.14-GCC-13.2.0.eb
Labels: update

#21384 {compiler}[system/system] NVHPC v24.7 w/ CUDA 12.6.0
  easybuild/easyconfigs/n/NVHPC/NVHPC-24.7-CUDA-12.6.0.eb
Labels: update

#20996 {bio}[GCCcore/12.2.0] snp-dists v0.8.2
  easybuild/easyconfigs/s/snp-dists/snp-dists-0.8.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/snp-dists/snp-dists-0.8.2-fix_cflags.patch
Labels: new

#21421 {tools}[GCCcore/12.3.0] dx-toolkit v0.382.0
  easybuild/easyconfigs/d/dx-toolkit/dx-toolkit-0.382.0-GCCcore-12.3.0.eb
Labels: update

#21774 {bio}[GCCcore/12.3.0] snp-sites v2.5.1
  easybuild/easyconfigs/s/snp-sites/snp-sites-2.5.1-GCCcore-12.3.0.eb
Labels: update

#18862 {devel}[intel-compilers/2022.2.1] Boost v1.81.0
  easybuild/easyconfigs/b/Boost/Boost-1.81.0-intel-compilers-2022.2.1.eb
  easybuild/easyconfigs/b/Boost/Boost-1.81.0_icpx_fix_unsupported_argument.patch
Labels: update

#20991 {lib}[GCCcore/13.2.0] pytest v8.2.2
  easybuild/easyconfigs/p/pytest/pytest-8.2.2-GCCcore-13.2.0.eb
Labels: update

#21468 {tools}[GCCcore/12.3.0] awscli v2.17.54
  easybuild/easyconfigs/a/awscli/awscli-2.17.54-GCCcore-12.3.0.eb
Labels: update

#21162 {numlib}[intel/2023b] SuperLU_DIST v8.2.1
  easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.2.1-intel-2023b.eb
Labels: update, 2023b

#22242 {data}[foss/2023b] zarr v2.18.4
  easybuild/easyconfigs/z/zarr/zarr-2.18.4-foss-2023b.eb
Labels: update

#20766 {vis}[GCCcore/13.2.0] motif v2.3.8
  easybuild/easyconfigs/m/motif/motif-2.3.8-GCCcore-13.2.0.eb
Labels: update, 2023b

#23100 restore test configurations
  .github/workflows/unit_tests.yml
Labels: tests, workflow

#22014 {bio}[GCCcore/12.3.0] metaMDBG v1.1
  easybuild/easyconfigs/m/metaMDBG/metaMDBG-1.1-GCCcore-12.3.0.eb
Labels: new

#22492 {chem}[foss/2023b] MBX v1.1.0
  easybuild/easyconfigs/m/MBX/MBX-1.1.0-foss-2023b.eb
Labels: update

#22180 {phys}[GCC/13.2.0] Geant4 v11.3.0, Geant4-data v11.3, CLHEP v2.4.7.1
  easybuild/easyconfigs/c/CLHEP/CLHEP-2.4.7.1-GCC-13.2.0.eb
  easybuild/easyconfigs/g/Geant4-data/Geant4-data-11.3.eb
  easybuild/easyconfigs/g/Geant4/Geant4-11.3.0-GCC-13.2.0.eb
Labels: update

#22041 {phys}[gompi/2023b] fastjet-contrib v1.053, fastjet v3.4.2, siscone v3.0.6
  easybuild/easyconfigs/f/fastjet-contrib/fastjet-contrib-1.053-gompi-2023b.eb
  easybuild/easyconfigs/f/fastjet/fastjet-3.4.2-gompi-2023b.eb
  easybuild/easyconfigs/s/siscone/siscone-3.0.6-GCCcore-13.2.0.eb
Labels: update

#22073 {lib}[GCCcore/13.2.0] freeglut v3.4.0
  easybuild/easyconfigs/f/freeglut/freeglut-3.4.0-GCCcore-13.2.0.eb
Labels: update, 2023b

#22071 {devel}[GCCcore/13.2.0] flatbuffers-python v24.3.25
  easybuild/easyconfigs/f/flatbuffers-python/flatbuffers-python-24.3.25-GCCcore-13.2.0.eb
Labels: update, 2023b

#22019 {vis}[foss/2023b] ETE v3.1.3
  easybuild/easyconfigs/e/ETE/ETE-3.1.3-foss-2023b.eb
Labels: update, 2023b

#22551 {bio}[GCC/12.3.0] MetaEuk v6
  easybuild/easyconfigs/m/MetaEuk/MetaEuk-6-GCC-12.3.0.eb
Labels: update

#23118 add `zlib` depenendency to `Serf`
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-10.3.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCCcore-11.3.0.eb
Labels: bug fix

#22511 {lang,lib}[GCCcore/13.3.0,foss/2024a] librosa v0.10.2.post1, nanobind v2.5.0
  easybuild/easyconfigs/l/librosa/librosa-0.10.2.post1-foss-2024a.eb
  easybuild/easyconfigs/l/librosa/soxr-0.5.0.post1.patch
  easybuild/easyconfigs/n/nanobind/nanobind-2.5.0-GCCcore-13.3.0.eb
Labels: update

#23082 {devel}[GCCcore/14.2.0] gperf v3.3, util-linux v2.41, intltool v0.51.0, ...
  easybuild/easyconfigs/b/Brotli/Brotli-1.1.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/d/Doxygen/Doxygen-1.14.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/f/fontconfig/fontconfig-2.16.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/f/freetype/freetype-2.13.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/gperf/gperf-3.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.41-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/util-linux/util-linux-2.41_fix-meson-posixipc_libs.patch
Labels: update, 2025a

#22467 {tools}[foss/2023b] LRBinner v0.1
  easybuild/easyconfigs/l/LRBinner/LRBinner-0.1-foss-2023b.eb
Labels: update

#22070 {data}[foss/2023b] Fiona v1.10.1
  easybuild/easyconfigs/f/Fiona/Fiona-1.10.1-foss-2023b.eb
Labels: update, 2023b

#21620 {data,vis}[GCCcore/13.2.0,foss/2023b] basemap v1.4.1, pyproj v3.6.1
  easybuild/easyconfigs/b/basemap/basemap-1.4.1-foss-2023b.eb
  easybuild/easyconfigs/p/pyproj/pyproj-3.6.1-GCCcore-13.2.0.eb
Labels: update, 2023b

#21871 {geo}[foss/2023b] Cartopy v0.22.0
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.22.0-foss-2023b.eb
Labels: update, 2023b

#22211 {chem}[intel/2024a] FHI-aims v240920_2, FHI-aims v240920 w/ ELPA
  easybuild/easyconfigs/f/FHI-aims/FHI-aims-240920-intel-2024a.eb
  easybuild/easyconfigs/f/FHI-aims/FHI-aims-240920_2-intel-2024a-ELPA.eb
  easybuild/easyconfigs/f/FHI-aims/FHI-aims-240920_2-intel-2024a.eb
Labels: update

#23121 add missing checksums for sources from git repos in DGL v1.1.3
  easybuild/easyconfigs/d/DGL/DGL-1.1.3-foss-2023a-CUDA-12.1.1.eb
Labels: change

#22949 {debugger}[gompi/2024a] tmpi v1.0.0
  easybuild/easyconfigs/t/tmpi/tmpi-1.0.0-gompi-2024a.eb
Labels: new

#23117 {chem}[foss/2024a][foss/2023b] LAMMPS v29Aug2024_update2, LAMMPS v2Aug2023_update2, w/ kokkos & CUDA
  easybuild/easyconfigs/a/archspec/archspec-0.2.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/k/kim-api/kim-api-2.4.1-GCC-13.3.0.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Aug2024_update2-foss-2023b-kokkos-CUDA-12.4.0.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Aug2024_update2-foss-2024a-kokkos-CUDA-12.6.0.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Aug2024_update2-foss-2024a-kokkos.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update2-foss-2024a-kokkos-CUDA-12.6.0.eb
  easybuild/easyconfigs/m/MDI/MDI-1.4.26-gompi-2024a.eb
  easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.3-foss-2024a.eb
  easybuild/easyconfigs/s/ScaFaCoS/ScaFaCoS-1.0.4-foss-2024a.eb
Labels: update

#23126 OpenPGM: fix usage of, and dependency on, perl
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-12.2.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-12.3.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-13.2.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-13.3.0.eb
  easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-GCCcore-14.2.0.eb
Labels: bug fix, 2023a, 2023b, 2024a, 2025a, 2022b

#23086 {lib}[GCCcore/14.2.0] nettle v3.10.1, Mako v1.3.10, pixman v0.46.2, ...
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/m/Mako/Mako-1.3.10-GCCcore-14.2.0.eb
  easybuild/easyconfigs/n/nettle/nettle-3.10.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pixman/pixman-0.46.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/w/Wayland/Wayland-1.23.92-GCCcore-14.2.0.eb
Labels: update, 2025a

#12687 improve check for multi-variant dependencies per generation of easyconfigs (for now, only for 2025a & newer)
  test/easyconfigs/easyconfigs.py
Labels: enhancement, bug fix, tests

#23128 {lang}[GCCcore/14.2.0] FriBidi v1.0.16
  easybuild/easyconfigs/f/FriBidi/FriBidi-1.0.16-GCCcore-14.2.0.eb
Labels: update, 2025a

#23048 {chem}[foss/2023a] Amber v24.3 + AmberTools v24.10 w/ CUDA 12.1.1
  easybuild/easyconfigs/a/Amber/Amber-24.3-foss-2023a-AmberTools-24.10-CUDA-12.1.1.eb
  easybuild/easyconfigs/a/Amber/Amber-24_CudaConfig.patch
Labels: update

#22084 {numlib}[foss/2023b] gmsh v4.12.2 and some dependencies
  easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
  easybuild/easyconfigs/o/occt/occt-7.8.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SLEPc/SLEPc-3.22.2-foss-2023b.eb
Labels: update, 2023b

#23122 {chem}[foss/2023b] pyiron v0.5.2, nglview v3.1.4, ...
  easybuild/easyconfigs/c/cp2k-input-tools/cp2k-input-tools-0.9.1-foss-2023b.eb
  easybuild/easyconfigs/i/iodata/iodata-1.0.0a5-foss-2023b.eb
  easybuild/easyconfigs/m/MDTraj/MDTraj-1.10.3-foss-2023b.eb
  easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2023b.eb
  easybuild/easyconfigs/n/nglview/nglview-3.1.4-foss-2023b.eb
  easybuild/easyconfigs/p/phonopy/phonopy-2.22.1-foss-2023b.eb
  easybuild/easyconfigs/p/pyiron-gpl/pyiron-gpl-0.0.5-foss-2023b.eb
  easybuild/easyconfigs/p/pyiron/pyiron-0.5.2-foss-2023b.eb
  easybuild/easyconfigs/q/QuickFF/QuickFF-2.2.8-foss-2023b.eb
  easybuild/easyconfigs/t/TAMkin/TAMkin-1.2.6-foss-2023b.eb
  easybuild/easyconfigs/y/yaff/yaff-1.6.0-foss-2023b.eb
Labels: new, update

#23096 {lib}[GCCcore/14.2.0] Greenlet v3.2.3, psycopg v3.2.9, SQLAlchemy v2.0.41
  easybuild/easyconfigs/g/Greenlet/Greenlet-3.2.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/psycopg/psycopg-3.2.9-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SQLAlchemy/SQLAlchemy-2.0.41-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SQLAlchemy/alembic-1.16.1_old_license_syntax.patch
Labels: update, 2025a

#23136 also make `dssp` and `DAlphaBall.gcc` scripts executable for BindCraft v1.5.1
  easybuild/easyconfigs/b/BindCraft/BindCraft-1.5.1-foss-2023a-CUDA-12.1.1.eb
Labels: bug fix

#23132 use `c-ares` 1.34.5 dependency for `tensorstore` 0.1.72
  easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb
  test/easyconfigs/easyconfigs.py
Labels: change, 2024a

#23145 {vis}[GCCcore/14.2.0] FFmpeg v7.1.1, SDL2 v2.32.8, x265 v4.1, ...
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-7.1.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-13.0.19.0.eb
  easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.32.8-GCCcore-14.2.0.eb
  easybuild/easyconfigs/x/x264/x264-20250619-GCCcore-14.2.0.eb
  easybuild/easyconfigs/x/x265/x265-4.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-GCCcore-14.2.0.eb
Labels: update

#23129 {bio}[gompi/2024a] DaliLite 5 using DSSP
  easybuild/easyconfigs/d/DaliLite/DaliLite-5.0-gompi-2024a.eb
Labels: update

#23147 {tools}[GCCcore/14.2.0] yaml-cpp v0.8.0
  easybuild/easyconfigs/y/yaml-cpp/yaml-cpp-0.8.0-GCCcore-14.2.0.eb
Labels: update, 2025a

#22848 {lib}[foss/2024a] CheckM2 v1.1.0, TensorFlow v2.18.1, Bazel v6.5.0, ...
  easybuild/easyconfigs/b/Bazel/Bazel-6.5.0-GCCcore-13.3.0-Java-11.eb
  easybuild/easyconfigs/c/CheckM2/CheckM2-1.1.0-foss-2024a.eb
  easybuild/easyconfigs/l/LightGBM/LightGBM-4.6.0-foss-2024a.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.6.1-gfbf-2024a.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1-foss-2024a.eb
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1_disable-tf32-in-fused-matmul-tests.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1_fix-AVX512-eigen-compilation-gcc13.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1_fix-patchelf.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1_fix-setup.py.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1_fix-xnnpack.patch
  easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.18.1_fixedpoint.patch
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.18.0-gfbf-2024a.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#22463 {bio}[GCCcore/14.2.0] USalign v20250201
  easybuild/easyconfigs/u/USalign/USalign-20250201-GCCcore-14.2.0.eb
Labels: new

#22907 {perf}[gfbf/2024a] Extra-P v4.2.3
  easybuild/easyconfigs/e/Extra-P/Extra-P-4.2.3-gfbf-2024a.eb
  easybuild/easyconfigs/e/Extra-P/Extra-P-4.2.3_use_PySide6.patch
Labels: new, 2024a

#22081 {vis}[GCCcore/13.2.0] GL2PS v1.4.2
  easybuild/easyconfigs/g/GL2PS/GL2PS-1.4.2-GCCcore-13.2.0.eb
Labels: update, 2023b

#22272 {data}[foss/2023b] h5netcdf v1.5.0
  easybuild/easyconfigs/h/h5netcdf/h5netcdf-1.5.0-foss-2023b.eb
Labels: update, 2023b

#23027 {lang,lib,tools}[GCCcore/14.3.0] Python v3.13.4, libreadline v8.2, Tcl v9.0.1, ...
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libffi/libffi-3.5.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.13.5-GCCcore-14.3.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.50.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-9.0.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-14.3.0.eb
Labels: update, 2025b

#21999 {bio}[GCC/13.2.0] crb-blast v0.6.9
  easybuild/easyconfigs/c/crb-blast/crb-blast-0.6.9-GCC-13.2.0.eb
Labels: update, 2023b

#23159 {lib}[GCCcore/14.2.0] nlohmann_json v3.12.0
  easybuild/easyconfigs/n/nlohmann_json/nlohmann_json-3.12.0-GCCcore-14.2.0.eb
Labels: update, 2025a
