Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-05, with the labels that each got.

#22826 Fix missing space in missing-patch CI error
  test/easyconfigs/easyconfigs.py
Labels: code cleanup

#22814 {bio}[system] King v2.3.2
  easybuild/easyconfigs/k/king/king-2.3.2.eb
Labels: update

#22818 {tools}[GCCcore/12.3.0] zlib-ng v2.1.6, versioningit v3.1.2
  easybuild/easyconfigs/v/versioningit/versioningit-3.1.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/z/zlib-ng/zlib-ng-2.1.6-GCCcore-12.3.0.eb
Labels: enhancement, update

#22783 {astro,geo}[GCCcore/13.3.0,gfbf/2024a] PyEphem v4.2, timezonefinder v6.5.9
  easybuild/easyconfigs/p/PyEphem/PyEphem-4.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/t/timezonefinder/timezonefinder-6.5.9-gfbf-2024a.eb
Labels: new

#22296 {phys}[foss/2024a,intel/2024a] VASP v6.5.0
  easybuild/easyconfigs/v/VASP/VASP-6.5.0-foss-2024a.eb
  easybuild/easyconfigs/v/VASP/VASP-6.5.0-intel-2024a.eb
  easybuild/easyconfigs/v/VASP/VASP-6.5.0_enable_hdf5_wannier90.patch
  easybuild/easyconfigs/v/VASP/VASP-6.5.0_external_vdwkernel.patch
Labels: update

#22811 {bio}[system/system] CellRanger v9.0.1
  easybuild/easyconfigs/c/CellRanger/CellRanger-9.0.1.eb
Labels: update

#22835 {system}[system/system] CUDA v12.9.0
  easybuild/easyconfigs/c/CUDA/CUDA-12.9.0.eb
Labels: update

#17509 {cae}[system/system] ABAQUS v2023
  easybuild/easyconfigs/a/ABAQUS/ABAQUS-2023.eb
Labels: update

#22838 Use Java 21 wrapper instead of specific version for Turbovnc
  easybuild/easyconfigs/t/TurboVNC/TurboVNC-3.1.2-GCCcore-13.3.0.eb
Labels: bug fix, change

#22806 {tools}[system/system] binutils v2.44
  easybuild/easyconfigs/b/binutils/binutils-2.44.eb
Labels: update

#22842 {compiler,lang,tools}[GCCcore/15.1.0] Bison v3.8.2, binutils v2.44, flex v2.6.4, ...
  easybuild/easyconfigs/b/Bison/Bison-3.8.2-GCCcore-15.1.0.eb
  easybuild/easyconfigs/b/binutils/binutils-2.44-GCCcore-15.1.0.eb
  easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-15.1.0.eb
  easybuild/easyconfigs/g/GCC/GCC-15.1.0.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-15.1.0.eb
  easybuild/easyconfigs/h/help2man/help2man-1.49.3-GCCcore-15.1.0.eb
  easybuild/easyconfigs/m/M4/M4-1.4.19-GCCcore-15.1.0.eb
  easybuild/easyconfigs/z/zlib/zlib-1.3.1-GCCcore-15.1.0.eb
Labels: update

#22839 Use Java 21 wrapper instead of specific version for Bazel
  easybuild/easyconfigs/b/Bazel/Bazel-7.4.1-GCCcore-13.3.0.eb
Labels: bug fix, change

#22687 {lang,tools}[GCCcore/12.3.0] Rust v1.81.0, maturin v1.7.8 w/ Rust 1.81.0
  easybuild/easyconfigs/m/maturin/maturin-1.7.8-GCCcore-12.3.0-Rust-1.81.0.eb
  easybuild/easyconfigs/r/Rust/Rust-1.81.0-GCCcore-12.3.0.eb
Labels: update

#22837 {vis}[GCCcore/13.3.0] Update dependencies of Graphviz 12.2.0
  easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0.eb
Labels: bug fix, change

#22363 {tools}[GCCcore/12.3.0] cdsapi v0.7.5
  easybuild/easyconfigs/c/cdsapi/cdsapi-0.7.5-GCCcore-12.3.0.eb
Labels: update

#22698 {lang,tools}[GCCcore/12.3.0] scikit-learn v1.6.1, Meson v1.4.0, meson-python v0.16.0, Cython v3.0.10, pybind11 v2.12.0
  easybuild/easyconfigs/c/Cython/Cython-3.0.10-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/Meson/Meson-1.4.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/meson-python/meson-python-0.16.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pybind11/pybind11-2.12.0-GCC-12.3.0.eb
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.6.1-gfbf-2023a.eb
Labels: update

#22858 use mimalloc instead of jemalloc for Arrow-17.0.0
  easybuild/easyconfigs/a/Arrow/Arrow-17.0.0-gfbf-2024a.eb
Labels: change

#22856 {tools}[system/system] Nsight-Compute v2025.2.0
  easybuild/easyconfigs/n/Nsight-Compute/Nsight-Compute-2025.2.0.eb
Labels: update

#22852 add patch to make bcgTree 1.2.1 compatible with MUSCLE 5
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.2.1-compatible_with_MUSCLE_5.patch
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.2.1-foss-2023a.eb
Labels: bug fix

#22860 {tools}[system/system] MAQAO v2.21.1
  easybuild/easyconfigs/m/MAQAO/MAQAO-2.21.1.eb
Labels: new

#22430 {tools}[system/system] ANSYS v2025R1
  easybuild/easyconfigs/a/ANSYS/ANSYS-2025R1.eb
Labels: update

#22854 Remove PYTHONPATH from OTF2 3.1.1
  easybuild/easyconfigs/o/OTF2/OTF2-3.1.1-GCCcore-14.2.0.eb
Labels: bug fix

#22850 add patch to add zen5 support to OpenBLAS 0.3.27
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.27-GCC-13.3.0.eb
  easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.27_add_zen5_support.patch
Labels: enhancement, change

#22861 Make bcgTree compatible with MUSCLE 5
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.2.1-compatible_with_MUSCLE_5.patch
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.2.1-foss-2023a.eb
Labels: bug fix, change

#22849 {tools}[GCCcore/13.2.0] pytest-subtests v0.13.1
  easybuild/easyconfigs/p/pytest-subtests/pytest-subtests-0.13.1-GCCcore-13.2.0.eb
Labels: new

#22845 {perf}[system/system] AMD-uProf v5.0.1479
  easybuild/easyconfigs/a/AMD-uProf/AMD-uProf-5.0.1479.eb
Labels: update

#20019 {bio}[system/system] RFdiffusion-models v1.1.0, RFdiffusion-schedules v1.1.0
  easybuild/easyconfigs/r/RFdiffusion-models/RFdiffusion-models-1.1.0.eb
  easybuild/easyconfigs/r/RFdiffusion-schedules/RFdiffusion-schedules-1.1.0.eb
  test/easyconfigs/easyconfigs.py
Labels: new

#22864 Incorporate the more detailed description of MAQAO from #22846
  easybuild/easyconfigs/m/MAQAO/MAQAO-2.21.1.eb
Labels: change

#18839 {math}[foss/2022b] polymake v4.10
  easybuild/easyconfigs/p/polymake/polymake-4.10-foss-2022b.eb
Labels: update

#22843 Fix PyTorch 2.3 on systems with disabled SMT
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0-foss-2023b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_fix-cpuinfo-bug-with-smt.patch
Labels: bug fix, change

#22866 {lib}[GCCcore/13.3.0] Xerces-C++ 3.2.5: Do not use system ICU to build
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.5_Change-CXX-standard-to-17.patch
Labels: bug fix

#22867 Fix LM Studio AppImage permission
  easybuild/easyconfigs/l/LM-Studio/LM-Studio-0.3.14-5-x64.eb
Labels: bug fix, change

#22853 Use CargoPythonBundle for Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb
Labels: bug fix

#22869 disable building documentation for jemalloc
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-13.3.0.eb
Labels: bug fix, change

#22870 disable building documentation for jemalloc/5.3.0
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-12.3.0.eb
Labels: bug fix, change

#22868 {devel}[GCCcore/14.2.0] SWIG v4.3.1, PCRE2 v10.45
  easybuild/easyconfigs/p/PCRE2/PCRE2-10.45-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SWIG/SWIG-4.3.1-GCCcore-14.2.0.eb
Labels: update

#22776 {tools}[GCCcore/14.2.0] tree-sitter v0.25.3
  easybuild/easyconfigs/t/tree-sitter/tree-sitter-0.25.3-GCCcore-14.2.0.eb
Labels: new

#17127 {bio}[foss/2022a] stpipeline v1.8.1 w/ Python 3.10.4
  easybuild/easyconfigs/s/stpipeline/stpipeline-1.8.1-foss-2022a.eb
  easybuild/easyconfigs/s/stpipeline/taggd-0.3.6-tp_print.patch
Labels: new

#22874 Update R-bundle-CRAN-2023.12-foss-2023a.eb - add kableExtra
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
Labels: change

#17915 {bio}[system/system] Schrodinger v2023-2
  easybuild/easyconfigs/s/Schrodinger/Schrodinger-2023-2.eb
Labels: update

#19063 {phys}[system/system] COMSOL v6.1.0.357
  easybuild/easyconfigs/c/COMSOL/COMSOL-6.1.0.357.eb
Labels: update

#20542 {cae}[system/system] CAESES v5.2.6
  easybuild/easyconfigs/c/CAESES/CAESES-5.2.6.eb
Labels: new

#20545 {cae}[system/system] HEEDS v2310
  easybuild/easyconfigs/h/HEEDS/HEEDS-2310.eb
Labels: new

#22872 {bio}[GCC/12.3.0] quaqc v1.3d
  easybuild/easyconfigs/q/quaqc/quaqc-1.3d-GCC-12.3.0.eb
Labels: new

#22882 {geo,vis}[GCC/13.3.0,GCCcore/13.3.0] PGPLOT v5.2.2, WCSLIB v8.4
  easybuild/easyconfigs/p/PGPLOT/PGPLOT-5.2.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/w/WCSLIB/WCSLIB-8.4-GCC-13.3.0.eb
Labels: update

#22758 fix `get_good_inter_pae.py` script in AlphaPulldown v2.0.3 + use proper dependency for tokenizers in Uni-Core v0.0.3
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.3-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/u/Uni-Core/Uni-Core-0.0.3-foss-2023a-CUDA-12.1.1.eb
Labels: bug fix

#22892 Add missing extension curly brackets and parentheses
  contrib/easyconfig-templates/2022a/PythonBundle-minimal.eb.tmpl
  contrib/easyconfig-templates/2022a/PythonBundle-scipy.eb.tmpl
  contrib/easyconfig-templates/2023a/PythonBundle-minimal.eb.tmpl
  contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
  contrib/easyconfig-templates/2024a/PythonBundle-minimal.eb.tmpl
  contrib/easyconfig-templates/2024a/PythonBundle-scipy.eb.tmpl
Labels: bug fix

#22873 Update R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb - add hiAnnotator
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb
Labels: change

#22885 {bio}[GCCcore/13.2.0] Longshot v1.0.0
  easybuild/easyconfigs/l/Longshot/Longshot-1.0.0-GCCcore-13.2.0.eb
Labels: update

#22880 Disable XPMEM in libfabric
  easybuild/easyconfigs/l/libfabric/libfabric-1.21.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libfabric/libfabric-2.0.0-GCCcore-14.2.0.eb
Labels: bug fix, change

#22900 Switch JAR to Binary
  easybuild/easyconfigs/b/BCEL/BCEL-6.5.0-Java-1.8.eb
  easybuild/easyconfigs/b/Beagle/Beagle-5.4.22Jul22.46e-Java-11.eb
  easybuild/easyconfigs/c/cromwell/cromwell-56-Java-11.eb
  easybuild/easyconfigs/d/DL_POLY_Classic_GUI/DL_POLY_Classic_GUI-1.10.eb
  easybuild/easyconfigs/g/GRASP-suite/GRASP-suite-2023-05-09-Java-17.eb
  easybuild/easyconfigs/m/MACSE/MACSE-2.06-Java-15.eb
  easybuild/easyconfigs/p/Pilon/Pilon-1.23-Java-11.eb
  easybuild/easyconfigs/p/Pilon/Pilon-1.24-Java-17.eb
  easybuild/easyconfigs/p/PoPoolation-TE2/PoPoolation-TE2-1.10.03-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/picard/picard-2.20.6-Java-1.8.eb
  easybuild/easyconfigs/p/picard/picard-2.21.6-Java-11.eb
  easybuild/easyconfigs/p/picard/picard-2.22.1-Java-11.eb
  easybuild/easyconfigs/p/picard/picard-2.25.0-Java-11.eb
  easybuild/easyconfigs/p/picard/picard-2.25.1-Java-11.eb
  easybuild/easyconfigs/p/picard/picard-2.25.5-Java-13.eb
  easybuild/easyconfigs/p/picard/picard-2.26.10-Java-15.eb
  easybuild/easyconfigs/p/picard/picard-3.0.0-Java-17.eb
  easybuild/easyconfigs/p/picard/picard-3.3.0-Java-17.eb
  easybuild/easyconfigs/r/RNA-SeQC/RNA-SeQC-1.1.8-GCCcore-11.2.0-Java-11.eb
  easybuild/easyconfigs/v/VarScan/VarScan-2.4.4-Java-1.8.eb
  easybuild/easyconfigs/v/VarScan/VarScan-2.4.4-Java-11.eb
Labels: change

#22876 {bio}[foss/2023a] HD-BET v20240529 w/ CUDA 12.1.1
  easybuild/easyconfigs/h/HD-BET/HD-BET-20240529-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22898 add hiAnnotator extension to R-bundle-Bioconductor v3.20
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.20-foss-2024a-R-4.4.2.eb
Labels: enhancement

#22897 add hiAnnotator extension to R-bundle-Bioconductor v3.19
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.19-foss-2023b-R-4.4.1.eb
Labels: enhancement

#22896 {bio}[GCC/13.3.0,foss/2024a] parasail v2.6.2, python-parasail v1.3.4
  easybuild/easyconfigs/p/parasail/parasail-2.6.2-GCC-13.3.0.eb
  easybuild/easyconfigs/p/python-parasail/python-parasail-1.3.4-foss-2024a.eb
Labels: update

#22899 {bio}[GCC/13.3.0] spoa v4.1.0, pyspoa v0.2.1
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.2.1-GCC-13.3.0.eb
  easybuild/easyconfigs/s/spoa/spoa-4.1.0-GCC-13.3.0.eb
Labels: update

#22901 {bio}[foss/2024a] ont-fast5-api v4.1.3
  easybuild/easyconfigs/o/ont-fast5-api/ont-fast5-api-4.1.3-foss-2024a.eb
Labels: update

#22888 {bio}[GCCore-13.3.0] intervaltree-python v3.1.0
  easybuild/easyconfigs/i/intervaltree-python/intervaltree-python-3.1.0-GCCcore-13.3.0.eb
Labels: update

#22877 Create optree-0.14.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/o/optree/optree-0.14.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/o/optree/optree-0.14.1_fix-path-type.patch
Labels: update

#22862 use Java 17 as default Java version in all 2024a generation easyconfigs
  easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-13.3.0.eb
  easybuild/easyconfigs/b/Bazel/Bazel-7.4.1-GCCcore-13.3.0-Java-21.eb
  easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/n/NCO/NCO-5.2.9-foss-2024a.eb
  easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2024.12.0+467-foss-2024a-R-4.4.2.eb
  easybuild/easyconfigs/t/TurboVNC/TurboVNC-3.1.2-GCCcore-13.3.0.eb
Labels: change

#22883 Port ReFrame easyconfigs to EasyBuild 5
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2-Python-3.6.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2.eb
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.3-GCCcore-13.3.0.eb
Labels: change

#22890 {phys}[foss/2024a] Siesta v5.2.2 plus dependencies
  easybuild/easyconfigs/f/flook/flook-0.8.4-GCC-13.3.0.eb
  easybuild/easyconfigs/j/json-fortran/json-fortran-9.0.3-GCC-13.3.0.eb
  easybuild/easyconfigs/l/libGridXC/libGridXC-2.0.2-gompi-2024a.eb
  easybuild/easyconfigs/l/libPSML/libPSML-2.1.0-GCC-13.3.0.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.5.1-GCC-13.3.0.eb
  easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCC-13.3.0.eb
  easybuild/easyconfigs/m/mstore/mstore-0.3.0-GCC-13.3.0.eb
  easybuild/easyconfigs/s/Siesta/Siesta-5.2.2-foss-2024a.eb
  easybuild/easyconfigs/s/Simple-DFTD3/Simple-DFTD3-1.2.1-gfbf-2024a.eb
  easybuild/easyconfigs/t/TOML-Fortran/TOML-Fortran-0.4.2-GCC-13.3.0.eb
  easybuild/easyconfigs/t/test-drive/test-drive-0.5.0-GCC-13.3.0.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.6.3-GCC-13.3.0.eb
Labels: update

#22913 {bio}[GCC/12.3.0] TreeMix v1.13
  easybuild/easyconfigs/t/TreeMix/TreeMix-1.13-GCC-12.3.0.eb
Labels: update

#22916 don't fix shebang line in mympirun script, to make sure it used system Python
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.3.0.eb
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.3.1.eb
  easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.4.0.eb
Labels: bug fix

#22903 {compiler}[GCCcore-13.3.0] LLVM 20.1.5
  easybuild/easyconfigs/l/LLVM/LLVM-18.1.8_envintest.patch
  easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_clang_rpathwrap_test.patch
  easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_libomptarget_tests.patch
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.3.0.eb
Labels: update

#22812 {tools}[foss/2023a] yacrd v1.0.0
  easybuild/easyconfigs/y/yacrd/yacrd-1.0.0-foss-2023a.eb
Labels: new

#22918 define `$CONDA_PREFIX` via `modextravars` in QIIME2
  easybuild/easyconfigs/q/QIIME2/QIIME2-2023.5.1-foss-2022a.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2023.7.0-foss-2022a.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2024.10.1-foss-2023a-amplicon.eb
Labels: bug fix

#22904 stick to QIIME2 2024.2.0 with foss/2023a, since recent versions (like 2024.10.0) require a more recent version of `pandas`
  easybuild/easyconfigs/q/QIIME2/QIIME2-2024.2.0-foss-2023a-amplicon.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2024.2.0_parallel-fix.patch
Labels: bug fix, change

#22905 {bio}[foss/2023b] QIIME2 v2024.10.1, attr v2.5.2, cutadapt v5.0, ... w/ amplicon
  easybuild/easyconfigs/a/attr/attr-2.5.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/c/cutadapt/cutadapt-5.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/gffutils/gffutils-0.13-foss-2023b.eb
  easybuild/easyconfigs/n/nose3/nose3-1.3.8-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Parsl/Parsl-2024.4.22-GCCcore-13.2.0.eb
  easybuild/easyconfigs/q/QIIME2/QIIME2-2024.10.1-foss-2023b-amplicon.eb
  easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.6.2-foss-2023b.eb
  easybuild/easyconfigs/u/UniFrac/UniFrac-1.4-foss-2023b.eb
  easybuild/easyconfigs/u/umap-learn/umap-learn-0.5.7-foss-2023b.eb
  easybuild/easyconfigs/v/VSEARCH/VSEARCH-2.30.0-GCC-13.2.0.eb
Labels: update

#22919 add patch to fix ml_dtypes 0.5.0 on AVX512 CPUs with FP16 support
  easybuild/easyconfigs/m/ml_dtypes/ml_dtypes-0.5.0-gfbf-2024a.eb
  easybuild/easyconfigs/m/ml_dtypes/ml_dtypes-0.5.0_fix-Eigen-Float16-support.patch
Labels: bug fix

#22909 add patch for PMIx 5.0.2 to fix support for IPv6
  easybuild/easyconfigs/p/PMIx/PMIx-5.0.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PMIx/pmix-5.0.2_ipv6.patch
Labels: bug fix, change

#22757 {bio}[foss/2023a] AlphaPulldown v2.0.3
  easybuild/easyconfigs/a/AlphaPulldown/AlphaPulldown-2.0.3-foss-2023a.eb
  easybuild/easyconfigs/u/Uni-Core/Uni-Core-0.0.3-foss-2023a.eb
Labels: update

#22588 control number of parallel processes used by Ninja and add fix for aarch64 in easyconfig for Qt6 6.7.2
  easybuild/easyconfigs/q/Qt6/Qt6-6.7.2-GCCcore-13.3.0.eb
Labels: change, aarch64

#22454 Update fastparquet v2024.11.0 - add patched cramjam as a dependency to fix static linking problem
  easybuild/easyconfigs/f/fastparquet/fastparquet-2024.11.0-gfbf-2023a.eb
Labels: change

#22926 {compiler,mpi}[intel-compilers/2025.1.1,system/system] intel-compilers v2025.1.1, impi v2021.15.0
  easybuild/easyconfigs/i/impi/impi-2021.15.0-intel-compilers-2025.1.1.eb
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2025.1.1.eb
Labels: update

#19220 {chem}[foss/2022b,intel/2022b] Simple-DFTD3 v0.7.0
  easybuild/easyconfigs/s/Simple-DFTD3/Simple-DFTD3-0.7.0-foss-2022b.eb
  easybuild/easyconfigs/s/Simple-DFTD3/Simple-DFTD3-0.7.0-intel-2022b.eb
Labels: update

#19219 {chem}[foss/2022b] tblite v0.4.0
  easybuild/easyconfigs/t/tblite/tblite-0.4.0-foss-2022b.eb
  easybuild/easyconfigs/t/tblite/tblite-0.4.0_failed-test.patch
Labels: new

#19224 {chem}[intel/2022b] tblite v0.4.0
  easybuild/easyconfigs/t/tblite/tblite-0.4.0-intel-2022b.eb
Labels: update

#22801 replace `setenv` commands with environment variables in module footers with `modextravars` in easyconfigs for HIP, JupyterLab, mujoco-py, Triton
  easybuild/easyconfigs/h/HIP/HIP-4.5.0-GCCcore-11.2.0-amd.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-3.5.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.0.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.0.5-GCCcore-12.3.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.2.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.2.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/mujoco-py/mujoco-py-2.1.2.14-foss-2021b.eb
  easybuild/easyconfigs/t/Triton/Triton-2.1.0-foss-2023a-CUDA-12.1.1.eb
Labels: code cleanup

#22851 Use vars instead of paths which supports environment variables soon
  easybuild/easyconfigs/f/funannotate/funannotate-1.8.17-foss-2023a.eb
Labels: bug fix, change

#22920 {lib}[system/system] cuQuantum v25.03.0.11 w/ CUDA 12.6.0
  easybuild/easyconfigs/c/cuQuantum/cuQuantum-25.03.0.11-CUDA-12.6.0.eb
Labels: update

#22924 {compiler}[GCCcore/13.2.0] LLVM-20.1.5 for foss 2023b toolchains
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.2.0.eb
Labels: update

#22895 {lib}[foss/2024a] HeFFTe v2.4.1 w/ CUDA 12.6.0
  easybuild/easyconfigs/h/HeFFTe/HeFFTe-2.4.1-foss-2024a-CUDA-12.6.0.eb
  easybuild/easyconfigs/h/HeFFTe/HeFFTe-2.4.1-foss-2024a.eb
Labels: update

#22934 {numlib}[GCCcore/12.3.0] qrupdate-1.1.2
  easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCCcore-12.3.0.eb
Labels: update

#22863 {phys}[foss/2024a] CrystFEL v0.11.1
  easybuild/easyconfigs/c/CrystFEL/CrystFEL-0.11.1-foss-2024a.eb
Labels: new

#22912 {bio}[foss/2024a] WhatsHap v2.6
  easybuild/easyconfigs/w/WhatsHap/WhatsHap-2.6-foss-2024a.eb
  easybuild/easyconfigs/w/WhatsHap/remove_license_from_pythonproj.patch
Labels: update

#22937 stick to torchrl 0.3.0 in PyTorch-bundle 2.1.2
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a.eb
Labels: bug fix, change

#22827 {lang}[GCCcore/14.2.0] Python-bundle-PyPI v2025.04
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-3.13-blist-1.3.6-compatibility.patch
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2025.04-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/sphinx-8.2.3_license_dict.patch
Labels: update

#22847 {bio}[gompi/2023a] PyHMMER v0.10.15
  easybuild/easyconfigs/p/PyHMMER/PyHMMER-0.10.15-gompi-2023a.eb
Labels: update

#22941 add easyconfigs for `intel/2025a` common toolchain
  easybuild/easyconfigs/h/HPL/HPL-2.3-intel-2025a.eb
  easybuild/easyconfigs/i/iimpi/iimpi-2025a.eb
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2025.1.0-iimpi-2025a.eb
  easybuild/easyconfigs/i/intel/intel-2025a.eb
Labels: update, 2025a

#22713 {base,data}[foss/2023b,gompi/2023b] Amber v24.0, PnetCDF v1.13.0 w/ AmberTools 24.0
  easybuild/easyconfigs/a/Amber/Amber-24.0-foss-2023b-AmberTools-24.0.eb
  easybuild/easyconfigs/a/Amber/Amber-24_reduce_precision_of_kmmd_pmemd_gb_test.patch
  easybuild/easyconfigs/a/Amber/Amber-24_skip-TempRem-tests.patch
  easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.13.0-gompi-2023b.eb
Labels: update

#21837 add missing dependencies (TSEBRA, compleasm) + use more recent AUGUSTUS version for BRAKER v3.0.8
  easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.5.0-20240612-foss-2023a.eb
  easybuild/easyconfigs/b/BRAKER/BRAKER-3.0.8-foss-2023a.eb
  easybuild/easyconfigs/c/compleasm/compleasm-0.2.6-foss-2023a.eb
  easybuild/easyconfigs/t/TSEBRA/TSEBRA-1.1.2.5-gfbf-2023a.eb
  test/easyconfigs/easyconfigs.py
Labels: bug fix, new, update, change

#22871 {devel}[GCCcore/12.2.0] GOTCHA v1.0.7
  easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.7-GCCcore-12.2.0.eb
Labels: update

#22906 {devel}[GCCcore/13.3.0] PySide6 v6.7.2
  easybuild/easyconfigs/p/PySide6/PySide6-6.7.2-GCCcore-13.3.0.eb
Labels: new

#22346 disable check for RPATH section in git-lfs easyconfigs
  easybuild/easyconfigs/g/git-lfs/git-lfs-2.11.0.eb
  easybuild/easyconfigs/g/git-lfs/git-lfs-3.2.0.eb
  easybuild/easyconfigs/g/git-lfs/git-lfs-3.4.0.eb
  easybuild/easyconfigs/g/git-lfs/git-lfs-3.4.1.eb
Labels: bug fix, change

#22879 add easyconfigs for `foss/2025a` common toolchain (and get rid of candidate toolchains like `gompi/2025.02` and `gfbf/2025.02`)
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2025a.eb
  easybuild/easyconfigs/f/foss/foss-2025a.eb
  easybuild/easyconfigs/g/gfbf/gfbf-2025a.eb
  easybuild/easyconfigs/g/gompi/gompi-2025a.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.5-gompi-2025a.eb
  easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.2-gompi-2025a-fb.eb
  easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.2-gompi-2025a.eb
  easybuild/easyconfigs/s/Score-P/Score-P-9.0-gompi-2025a-CUDA-12.8.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-9.0-gompi-2025a.eb
  easybuild/easyconfigs/v/Valgrind/Valgrind-3.25.0-gompi-2025a.eb
Labels: update, change, 2025a

#22665 Delete .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: code cleanup

#22787 add patch to fix bug in unittest-xml-reporting on Python 3.11+
  easybuild/easyconfigs/u/unittest-xml-reporting/unittest-xml-reporting-3.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/u/unittest-xml-reporting/unittest-xml-reporting-3.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/u/unittest-xml-reporting/unittest-xml-reporting-3.1.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/u/unittest-xml-reporting/unittest-xml-reporting-3.1.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/unittest-xml-reporting/unittest-xml-reporting-3.1.0_fix-getDescription-python-3.11.patch
Labels: bug fix

#22696 {bio,numlib}[foss/2023b] openCARP v17.0, PETSc v3.22.5
  easybuild/easyconfigs/o/openCARP/openCARP-17.0-foss-2023b.eb
  easybuild/easyconfigs/p/PETSc/PETSc-3.22.5-foss-2023b.eb
Labels: update, EESSI

#22817 add optional patch file for OpenMPI 4.1.5 to disable OPAL path NFS test
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5_disable_opal_path_nfs_test.patch
Labels: bug fix, tests

#21612 add JsonCpp dependency to recent BamTools easyconfigs
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-10.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-11.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-11.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-12.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-12.3.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-13.2.0.eb
  easybuild/easyconfigs/b/BamTools/BamTools-2.5.2-GCC-13.3.0.eb
Labels: bug fix, change

#22006 add patch for OpenMPI v5.0.3 to fix C90 compliance
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3-GCC-13.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3_fix_c90_compliance.patch
Labels: bug fix, change

#22672 Use `PythonPackage` easyblock for coverage v7.4.4
  easybuild/easyconfigs/c/coverage/coverage-7.4.4-GCCcore-13.2.0.eb
Labels: code cleanup

#22725 add patch to fix dependency check in OPERA-MS
  easybuild/easyconfigs/o/OPERA-MS/OPERA-MS-0.9.0-20240703-foss-2023a.eb
  easybuild/easyconfigs/o/OPERA-MS/OPERA-MS-0.9.0-20240703_fix-perl-dependency-check.patch
Labels: bug fix

#22894 fix MKL ILP64 flags for Global Arrays 5.8.2 w/ `intel/2024a`
  easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-intel-2024a.eb
Labels: bug fix

#22018 add an egg-info file to make RDKit findable by pip
  easybuild/easyconfigs/r/RDKit/RDKit-2024.03.3-foss-2023a.eb
  easybuild/easyconfigs/r/RDKit/rdkit-version.egg-info
Labels: bug fix, change

#22701 Make Python a dependency of GObject-Introspection 1.80.1
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.72.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.74.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.76.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.78.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.80.1-GCCcore-13.3.0.eb
Labels: bug fix

#22950 {vis}[GCCcore/13.3.0] Graphviz v12.2.0-minimal
  easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0-minimal.eb
Labels: update

#22956 {lib}[GCCcore/14.2.0] UCC-CUDA v1.3.0 w/ CUDA 12.8.0
  easybuild/easyconfigs/n/NCCL/NCCL-2.26.6-GCCcore-14.2.0-CUDA-12.8.0.eb
  easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.3.0-GCCcore-14.2.0-CUDA-12.8.0.eb
Labels: update

#22719 {numlib}[foss/2023b] Ginkgo v1.9.0
  easybuild/easyconfigs/g/Ginkgo/Ginkgo-1.9.0-gompi-2023b-CUDA-12.8.0.eb
  easybuild/easyconfigs/g/Ginkgo/Ginkgo-1.9.0-gompi-2023b.eb
Labels: update

#22959 MrBayes: Fix dependency beagle-lib
  easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.7-gompi-2023a.eb
Labels: bug fix

#22410 {bio}[foss/2023a] MetaPhlAn v4.1.1, PhyloPhlAn v3.0.3
  easybuild/easyconfigs/m/MetaPhlAn/MetaPhlAn-4.1.1-foss-2023a.eb
  easybuild/easyconfigs/p/PhyloPhlAn/PhyloPhlAn-3.0.3-foss-2023a.eb
Labels: update

#22935 {data}[foss/2023b] netcdf4-python v1.7.1.post2
  easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.7.1.post2-foss-2023b.eb
Labels: update

#22343 {chem}[foss/2023a] Tinker-HP v20241026 w/ plumed colvars
  easybuild/easyconfigs/t/Tinker-HP/Tinker-HP-20241026-foss-2023a-plumed-colvars.eb
  easybuild/easyconfigs/t/Tinker-HP/tinkerhp.wrapper
Labels: update

#22962 {tools}[GCC/13.3.0] elbencho v3.0-27
  easybuild/easyconfigs/e/elbencho/elbencho-3.0-27-GCC-13.3.0-CUDA-12.6.0.eb
  easybuild/easyconfigs/e/elbencho/elbencho-3.0-27-GCC-13.3.0.eb
Labels: update

#22955 Archive pre-2021 easyconfigs older than 4 years old
  easybuild/easyconfigs/__archive__/a/ABAQUS/ABAQUS-2020.eb
  easybuild/easyconfigs/__archive__/a/ADF/ADF-2019.303-intelmpi.eb
  easybuild/easyconfigs/__archive__/a/ADMIXTURE/ADMIXTURE-1.3.0.eb
  easybuild/easyconfigs/__archive__/a/Anaconda3/Anaconda3-2020.02.eb
  easybuild/easyconfigs/__archive__/a/ant/ant-1.10.11-Java-13.eb
  easybuild/easyconfigs/__archive__/b/BLAST/BLAST-2.10.0-Linux_x86_64.eb
  easybuild/easyconfigs/__archive__/b/Bandage/Bandage-0.8.1_Centos.eb
  easybuild/easyconfigs/__archive__/b/Bison/Bison-3.5.2.eb
  easybuild/easyconfigs/__archive__/b/Bison/Bison-3.5.3.eb
  easybuild/easyconfigs/__archive__/b/binutils/binutils-2.34.eb
  easybuild/easyconfigs/__archive__/e/EasyBuild/EasyBuild-4.1.1.eb
  easybuild/easyconfigs/__archive__/e/EasyBuild/EasyBuild-4.1.2.eb
  easybuild/easyconfigs/__archive__/e/EasyBuild/EasyBuild-4.2.0.eb
  easybuild/easyconfigs/__archive__/e/EasyBuild/EasyBuild-4.2.1.eb
  easybuild/easyconfigs/__archive__/f/FLUENT/FLUENT-2019R3.eb
  easybuild/easyconfigs/__archive__/f/FastQC/FastQC-0.11.9-Java-1.8.eb
  easybuild/easyconfigs/__archive__/g/GSEA/GSEA-4.0.3.eb
  easybuild/easyconfigs/__archive__/g/Gradle/Gradle-6.1.1.eb
  easybuild/easyconfigs/__archive__/g/Groovy/Groovy-2.5.9-Java-11.eb
  easybuild/easyconfigs/__archive__/g/Gurobi/Gurobi-9.0.1.eb
  easybuild/easyconfigs/__archive__/g/goalign/goalign-0.3.2.eb
  easybuild/easyconfigs/__archive__/g/gotree/gotree-0.4.0.eb
  easybuild/easyconfigs/__archive__/i/IGV/IGV-2.8.0-Java-11.eb
  easybuild/easyconfigs/__archive__/i/IntelDAAL/IntelDAAL-2019.4.007.eb
  easybuild/easyconfigs/__archive__/i/ispc/ispc-1.12.0.eb
  easybuild/easyconfigs/__archive__/j/Java/Java-1.8.0_241.eb
  easybuild/easyconfigs/__archive__/j/Java/Java-13.0.2.eb
  easybuild/easyconfigs/__archive__/j/Java/Java-13.eb
  easybuild/easyconfigs/__archive__/j/Julia/Julia-1.3.1-linux-x86_64.eb
  easybuild/easyconfigs/__archive__/j/Julia/Julia-1.4.0-linux-x86_64.eb
  easybuild/easyconfigs/__archive__/j/Julia/Julia-1.4.1-linux-x86_64.eb
  easybuild/easyconfigs/__archive__/k/king/king-2.2.4.eb
  easybuild/easyconfigs/__archive__/l/LS-PrePost/LS-PrePost-4.7.8.eb
  easybuild/easyconfigs/__archive__/l/libpng/libpng-1.2.59.eb
  easybuild/easyconfigs/__archive__/m/manta/manta-1.6.0.eb
  easybuild/easyconfigs/__archive__/n/Nextflow/Nextflow-19.12.0.eb
  easybuild/easyconfigs/__archive__/n/Nextflow/Nextflow-20.01.0.eb
  easybuild/easyconfigs/__archive__/n/Nextflow/Nextflow-20.04.1.eb
  easybuild/easyconfigs/__archive__/n/Nextflow/Nextflow-21.08.0.eb
  easybuild/easyconfigs/__archive__/n/Nextflow/Nextflow-21.10.6.eb
  easybuild/easyconfigs/__archive__/n/netMHCII/netMHCII-2.3.eb
  easybuild/easyconfigs/__archive__/p/PLINK/PLINK-2.00a2.3_x86_64.eb
  easybuild/easyconfigs/__archive__/p/PyCharm/PyCharm-2019.3.1.eb
  easybuild/easyconfigs/__archive__/p/picard/picard-2.20.6-Java-1.8.eb
  easybuild/easyconfigs/__archive__/p/picard/picard-2.21.6-Java-11.eb
  easybuild/easyconfigs/__archive__/p/picard/picard-2.25.5-Java-13.eb
  easybuild/easyconfigs/__archive__/s/SRA-Toolkit/SRA-Toolkit-2.10.5-centos_linux64.eb
  easybuild/easyconfigs/__archive__/s/Saxon-HE/Saxon-HE-9.9.1.7-Java-13.eb
  easybuild/easyconfigs/__archive__/s/SeqAn/SeqAn-1.4.2-library.eb
  easybuild/easyconfigs/__archive__/s/Singular/Singular-4.1.2.eb
  easybuild/easyconfigs/__archive__/s/Stata/Stata-16-legacy.eb
  easybuild/easyconfigs/__archive__/s/snpEff/snpEff-4.3t-Java-1.8.eb
  easybuild/easyconfigs/__archive__/s/snpEff/snpEff-5.0-Java-13.eb
  easybuild/easyconfigs/__archive__/t/Trimmomatic/Trimmomatic-0.39-Java-1.8.eb
  easybuild/easyconfigs/__archive__/t/tbl2asn/tbl2asn-20200302-linux64.eb
  easybuild/easyconfigs/__archive__/v/VarScan/VarScan-2.4.4-Java-1.8.eb
Labels: change
