Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-01, with the labels that each got.

#22100 update copyright lines for 2025
  setup.py
  test/__init__.py
  test/easyconfigs/easyconfigs.py
  test/easyconfigs/styletests.py
  test/easyconfigs/suite.py
Labels: update

#22101 {tools}[GCCcore/14.2.0] SQLite v3.47.2, libffi v3.4.5, bzip2 v1.0.8, ...
  easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libffi/libffi-3.4.5-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SQLite/SQLite-3.47.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/t/Tcl/Tcl-8.6.16-GCCcore-14.2.0.eb
  easybuild/easyconfigs/u/UnZip/UnZip-6.0-GCCcore-14.2.0.eb
Labels: update, 2024b

#22102 {lang}[GCCcore/14.2.0] Python v3.13.1
  easybuild/easyconfigs/p/Python/Python-3.13.1-GCCcore-14.2.0.eb
Labels: update

#22104 {tools}[GCCcore/14.2.0] Meson v1.6.1, Ninja v1.12.1
  easybuild/easyconfigs/m/Meson/Meson-1.6.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/n/Ninja/Ninja-1.12.1-GCCcore-14.2.0.eb
Labels: update, 2024b

#22103 remove `install_pip=True` from Python easyconfigs
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-10.3.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-11.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-11.2.0.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-11.3.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-12.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.10.8-GCCcore-12.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-3.10.8-GCCcore-12.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.11.2-GCCcore-12.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-3.11.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.11.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.12.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.8.6-GCCcore-10.2.0.eb
  easybuild/easyconfigs/p/Python/Python-3.9.5-GCCcore-10.3.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-3.9.5-GCCcore-10.3.0.eb
  easybuild/easyconfigs/p/Python/Python-3.9.6-GCCcore-11.2.0-bare.eb
  easybuild/easyconfigs/p/Python/Python-3.9.6-GCCcore-11.2.0.eb
Labels: change, EasyBuild-5.0

#21948 add SimBu-1.4.3 to R-bundle-Bioconductor-3.18-foss-2023a
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb
Labels: enhancement

#22105 {bio,lang}[system/system] dotNET-Core v8.0.302, MaxQuant v2.6.7.0
  easybuild/easyconfigs/d/dotNET-Core/dotNET-Core-8.0.302.eb
  easybuild/easyconfigs/d/dotNET-Core/dotNET-Core-8.0.eb
  easybuild/easyconfigs/m/MaxQuant/MaxQuant-2.6.7.0.eb
Labels: update, change

#22106 {tools}[GCCcore/14.2.0] GMP v6.3.0, cURL v8.11.1, libarchive v3.7.7, ...
  easybuild/easyconfigs/c/CMake/CMake-3.31.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/c/cURL/cURL-8.11.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/GMP/GMP-6.3.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libarchive/libarchive-3.7.7-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libiconv/libiconv-1.18-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.7-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libpsl/libpsl-0.21.5-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libunistring/libunistring-1.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/z/Z3/Z3-4.13.4-GCCcore-14.2.0.eb
Labels: update, 2024b

#22099 {lib,system}[GCCcore/14.2.0] xorg-macros v1.20.2, numactl v2.0.19, ...
  easybuild/easyconfigs/h/hwloc/hwloc-2.11.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libevent/libevent-2.1.12-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.18.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/n/numactl/numactl-2.0.19-GCCcore-14.2.0.eb
  easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.20.2-GCCcore-14.2.0.eb
Labels: update, 2024b

#22111 {lib}[GCCcore/14.2.0] gzip v1.13, lz4 v1.10.0, zstd v1.5.6, ...
  easybuild/easyconfigs/g/gzip/gzip-1.13-GCCcore-14.2.0.eb
  easybuild/easyconfigs/i/ICU/ICU-76.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/lz4/lz4-1.10.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/patchelf/patchelf-0.18.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/z/zstd/zstd-1.5.6-GCCcore-14.2.0.eb
Labels: update, 2024b

#22109 {bio}[foss/2024a] Biopython v1.84
  easybuild/easyconfigs/b/Biopython/Biopython-1.84-foss-2024a.eb
Labels: update

#22108 {tools}[GCCcore/12.3.0] gpustat v1.1.1
  easybuild/easyconfigs/g/gpustat/gpustat-1.1.1-GCCcore-12.3.0.eb
Labels: update

#22110 {bio,data,tools,vis}[GCCcore/13.3.0] pydot v3.0.3, XlsxWriter v3.2.0, openpyxl v3.1.5, ...
  easybuild/easyconfigs/g/GOATOOLS/GOATOOLS-1.4.12-foss-2024a.eb
  easybuild/easyconfigs/o/openpyxl/openpyxl-3.1.5-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/pydot/pydot-3.0.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/x/XlsxWriter/XlsxWriter-3.2.0-GCCcore-13.3.0.eb
Labels: update

#22116 test suite changes for EB5
  test/easyconfigs/easyconfigs.py
Labels: code cleanup, tests, EasyBuild-5.0

#22065 {bio}[GCC/12.3.0] FastK v1.1.0
  easybuild/easyconfigs/f/FastK/FastK-1.1.0-GCC-12.3.0.eb
Labels: new

#22074 {tools}[GCCcore/12.3.0] hatch v1.9.7
  easybuild/easyconfigs/h/hatch/hatch-1.9.7-GCCcore-12.3.0.eb
Labels: new

#22127 update action/cache
  .github/workflows/unit_tests.yml
Labels: workflow

#22115 {chem}[gfbf/2024a] ASE v3.24.0
  easybuild/easyconfigs/a/ASE/ASE-3.24.0-gfbf-2024a.eb
Labels: update

#22123 {chem}[intel/2023a] ABINIT v10.2.5
  easybuild/easyconfigs/a/ABINIT/ABINIT-10.2.5-intel-2023a.eb
Labels: update

#22121 {ai}[gfbf/2023a] XGBoost v2.1.3
  easybuild/easyconfigs/x/XGBoost/XGBoost-2.1.3-gfbf-2023a.eb
Labels: update

#22122 {ai}[gfbf/2023a] XGBoost v2.1.3 w/ CUDA 12.1.1
  easybuild/easyconfigs/x/XGBoost/XGBoost-2.1.3-gfbf-2023a-CUDA-12.1.1.eb
Labels: update

#21141 {lib}[foss/2022b] synthcity v0.2.10, DECAF-synthetic-data v0.1.6, PyTorch-Lightning v1.8.4, ... w/ PyTorch 1.13.1
  easybuild/easyconfigs/d/DECAF-synthetic-data/DECAF-synthetic-data-0.1.6-foss-2022b.eb
  easybuild/easyconfigs/f/fastai/fastai-2.7.15-foss-2022b.eb
  easybuild/easyconfigs/h/HF-Datasets/HF-Datasets-2.14.4-gfbf-2022b.eb
  easybuild/easyconfigs/i/imbalanced-learn/imbalanced-learn-0.12.3-gfbf-2022b.eb
  easybuild/easyconfigs/l/lifelines/lifelines-0.27.7-foss-2022b.eb
  easybuild/easyconfigs/o/Optuna/Optuna-3.5.0-foss-2022b.eb
  easybuild/easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-1.8.4-foss-2022b.eb
  easybuild/easyconfigs/p/pycodestyle/pycodestyle-2.11.1-foss-2022b.eb
  easybuild/easyconfigs/r/Redis/Redis-7.2.3-GCCcore-12.2.0.eb
  easybuild/easyconfigs/r/redis-py/redis-py-5.0.1-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/SHAP/SHAP-0.43.0-foss-2022b.eb
  easybuild/easyconfigs/s/spaCy/spaCy-3.7.4-foss-2022b.eb
  easybuild/easyconfigs/s/synthcity/synthcity-0.2.10-foss-2022b.eb
  easybuild/easyconfigs/t/torchtext/torchtext-0.14.1-foss-2022b-PyTorch-1.13.1.eb
  easybuild/easyconfigs/x/XGBoost/XGBoost-1.7.2-foss-2022b.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#22113 {chem}[gfbf/2023a] ASE v3.24.0
  easybuild/easyconfigs/a/ASE/ASE-3.24.0-gfbf-2023a.eb
Labels: update

#22118 {bio}[foss/2023a] BEDOPS v2.4.41
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.41-foss-2023a.eb
Labels: update

#22038 {bio}[foss/2023a] chewBBACA v3.3.10
  easybuild/easyconfigs/c/chewBBACA/chewBBACA-3.3.10-foss-2023a.eb
Labels: update

#21932 {geo}[gmpich/2024.06] GeoDict v2024.SP5
  easybuild/easyconfigs/g/GeoDict/GeoDict-2024.SP5-gmpich-2024.06.eb
Labels: update

#21931 {data,devel,tools}[GCCcore/13.2.0] ITK v5.4.0, CastXML v0.6.10, SWIG v4.3.0
  easybuild/easyconfigs/c/CastXML/CastXML-0.6.10-GCCcore-13.2.0.eb
  easybuild/easyconfigs/i/ITK/ITK-5.4.0-foss-2023b.eb
  easybuild/easyconfigs/s/SWIG/SWIG-4.3.0-GCCcore-13.2.0.eb
Labels: update

#22134 {ai,tools}[GCCcore/12.3.0,foss/2023a] CTranslate2 v4.5.0, cpu_features v0.9.0 w/ CUDA 12.6.0
  easybuild/easyconfigs/c/CTranslate2/CTranslate2-4.5.0-foss-2023a-CUDA-12.6.0.eb
  easybuild/easyconfigs/c/CTranslate2/CTranslate2-4.5.0_fix-tests.patch
  easybuild/easyconfigs/c/CTranslate2/CTranslate2-4.5.0_fix-third-party.patch
  easybuild/easyconfigs/c/CTranslate2/CTranslate2-4.5.0_replace-cxxopts.patch
  easybuild/easyconfigs/c/cpu_features/cpu_features-0.9.0-GCCcore-12.3.0.eb
Labels: new, update

#22145 {bio}[GCC/12.3.0] elfx86exts v0.6.2
  easybuild/easyconfigs/e/elfx86exts/elfx86exts-0.6.2-GCC-12.3.0.eb
Labels: new

#22141 {tools}[foss/2024a] snakemake v8.27.0
  easybuild/easyconfigs/c/Cbc/Cbc-2.10.12-foss-2024a.eb
  easybuild/easyconfigs/c/Cgl/Cgl-0.60.8-foss-2024a.eb
  easybuild/easyconfigs/c/Clp/Clp-1.17.10-foss-2024a.eb
  easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.12-GCC-13.3.0.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-foss-2024a-metis.eb
  easybuild/easyconfigs/o/Osi/Osi-0.108.11-GCC-13.3.0.eb
  easybuild/easyconfigs/p/PuLP/PuLP-2.8.0-foss-2024a.eb
  easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.6-gompi-2024a.eb
  easybuild/easyconfigs/s/snakemake/snakemake-8.27.0-foss-2024a.eb
Labels: update

#22130 {tools}[system/system] ImageJ v1.54m w/ Java 11
  easybuild/easyconfigs/i/ImageJ/ImageJ-1.54m-Java-11.eb
Labels: update

#22120 {bio}[GCC/11.2.0] bwa-mem2 v2.2.1
  easybuild/easyconfigs/b/bwa-mem2/bwa-mem2-2.2.1-GCC-11.2.0.eb
  easybuild/easyconfigs/b/bwa-mem2/bwa-mem2-2.2.1_fix_rdtsc_definition.patch
  easybuild/easyconfigs/s/safestringlib/safestringlib-20240228-GCC-11.2.0.eb
Labels: update

#22154 {math}[foss/2024a] bayesian-optimization v2.0.3
  easybuild/easyconfigs/b/bayesian-optimization/bayesian-optimization-2.0.3-foss-2024a.eb
Labels: update

#22033 {bio}[GCCcore/12.3.0,foss/2023a] scNanoGPS v1.1, LIQA v1.3.4, lifelines v0.28.0, annovar v20200607, tabix v0.2.6
  easybuild/easyconfigs/a/annovar/annovar-20200607-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/LIQA/LIQA-1.3.4-foss-2023a.eb
  easybuild/easyconfigs/l/lifelines/lifelines-0.28.0-gfbf-2023a.eb
  easybuild/easyconfigs/s/scNanoGPS/scNanoGPS-1.1-foss-2023a.eb
  easybuild/easyconfigs/t/tabix/tabix-0.2.6-GCCcore-12.3.0.eb
Labels: new, update

#22133 {chem,numlib}[intel/2023a] WIEN2k v24.1, DFT-D3 v3.2.0, FFTW.MPI v3.3.10, ...
  easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-intel-2023a.eb
  easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-iimpi-2023a.eb
  easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-24.1-intel-2023a.eb
Labels: update

#21997 {bio}[GCCcore/13.2.0] EMMAX v20120210
  easybuild/easyconfigs/e/EMMAX/EMMAX-20120210-GCCcore-13.2.0-intel-binary.eb
Labels: update

#21929 {lib}[GCCcore/13.2.0] imagecodecs v2024.6.1, CharLS v2.4.2, jxrlib v1.1, ...
  easybuild/easyconfigs/b/bitshuffle/bitshuffle-0.5.2-foss-2023b.eb
  easybuild/easyconfigs/c/CharLS/CharLS-2.4.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/i/imagecodecs/imagecodecs-2024.6.1-foss-2023b.eb
  easybuild/easyconfigs/j/jxrlib/jxrlib-1.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LibLZF/LibLZF-3.6-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libavif/libavif-1.1.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libde265/libde265-1.0.15-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libheif/libheif-1.19.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libyuv/libyuv-20241125-GCCcore-13.2.0.eb
  easybuild/easyconfigs/z/Zopfli/Zopfli-1.0.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/z/zfp/zfp-1.0.1-GCCcore-13.2.0.eb
Labels: new, update

#22135 {ai,devel,math,vis}[foss/2023a] whisper-ctranslate2 v0.5.2, ONNX-Runtime v1.19.2, PortAudio v19.7.0, ... w/ CUDA 12.6.0
  easybuild/easyconfigs/o/ONNX-Runtime/ONNX-Runtime-1.19.2-foss-2023a-CUDA-12.6.0.eb
  easybuild/easyconfigs/p/PortAudio/PortAudio-19.7.0-foss-2023a.eb
  easybuild/easyconfigs/p/PyAV/PyAV-11.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/whisper-ctranslate2/whisper-ctranslate2-0.5.2-foss-2023a-CUDA-12.6.0.eb
Labels: new, update

#22157 boost source url has changed to archives.boost.io
  easybuild/easyconfigs/b/Boost/Boost-1.81.0-GCC-12.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.82.0-GCC-12.3.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.83.0-GCC-13.2.0.eb
  easybuild/easyconfigs/b/Boost/Boost-1.85.0-GCC-13.3.0.eb
Labels: bug fix, change

#22164 update homepage and source_urls for libxsmm
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-GCC-10.2.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.1-iccifort-2020.4.304.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.2-GCC-10.3.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.16.2-intel-compilers-2021.2.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-11.2.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-11.3.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-12.2.0.eb
  easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-12.3.0.eb
Labels: bug fix, change

#22170 {lang}[gfbf,2024a] SciPy-bundle v2024.05 move pybind11 dependency to builddependencies
  easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024a.eb
Labels: change

#22172 {bio}[gompi/2024a] HMMER v3.4
  easybuild/easyconfigs/h/HMMER/HMMER-3.4-gompi-2024a.eb
Labels: update

#22173 Autoconf: Improve handling for 'llc' flags appearing e.g. with NVHPC on aarch64 systems
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-10.3.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-11.2.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-11.3.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-12.2.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-12.3.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-13.1.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-GCCcore-13.2.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71-Port-better-to-NVHPC.patch
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.71.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.72-GCCcore-13.3.0.eb
  easybuild/easyconfigs/a/Autoconf/Autoconf-2.72-GCCcore-14.2.0.eb
Labels: enhancement, change, aarch64

#22143 {perf}[iimpi/2024a] Add Score-P 8.4 (w/ CUDA 12.6.0)
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-iimpi-2024a-CUDA-12.6.0.eb
  easybuild/easyconfigs/s/Score-P/Score-P-8.4-iimpi-2024a.eb
Labels: update

#22183 fix setuptools issue by sticking to a single version in ReFrame 4.3.3 easyconfig
  easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.3.eb
Labels: bug fix

#22167 {lib}[GCC/13.3.0] pybind11 v2.13.6
  easybuild/easyconfigs/p/pybind11/pybind11-2.13.6-GCC-13.3.0.eb
Labels: update

#22177 Adding the latest Pandoc v.3.6.2
  easybuild/easyconfigs/p/Pandoc/Pandoc-3.6.2.eb
Labels: update

#22168 {lib}[GCCcore/13.3.0] Catch2 v3.8.0
  easybuild/easyconfigs/c/Catch2/Catch2-3.8.0-GCCcore-13.3.0.eb
Labels: update

#22186 {cae}[foss/2023a] OpenFOAM v8
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8-foss-2023a.eb
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8_fix-OSHA1stream.patch
Labels: update

#20418 {phys}[iomkl/2022b] FDS 6.8.0
  easybuild/easyconfigs/f/FDS/FDS-6.8.0-iomkl-2022b.eb
  easybuild/easyconfigs/f/FDS/FDS-6.8.0_intel_ompi.patch
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2022.2.1-iompi-2022b.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2022b.eb
  easybuild/easyconfigs/i/iompi/iompi-2022b.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-intel-compilers-2022.2.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4_intel_iso_c99.patch
Labels: update

#22158 {bio}[foss/2023b] pmx v20241209
  easybuild/easyconfigs/p/pmx/pmx-20241209-foss-2023b.eb
Labels: update

#22179 {bio}[foss/2022a] Biotite v0.41.0
  easybuild/easyconfigs/b/Biotite/Biotite-0.41.0-foss-2022a.eb
Labels: update

#22178 {bio}[GCC/12.3.0] Beast v2.7.7, beagle-lib v4.0.1 w/ CUDA 12.1.1
  easybuild/easyconfigs/b/Beast/Beast-2.7.7-GCC-12.3.0-CUDA-12.1.1.eb
  easybuild/easyconfigs/b/Beast/Beast-2.7.7-GCC-12.3.0.eb
  easybuild/easyconfigs/b/beagle-lib/beagle-lib-4.0.1-GCC-12.3.0.eb
Labels: update

#22059 {lib}[GCCcore/13.3.0] freeglut v3.6.0
  easybuild/easyconfigs/f/freeglut/freeglut-3.6.0-GCCcore-13.3.0.eb
Labels: update

#22189 {phys}[iomkl/2023a] FDS 6.9.1
  easybuild/easyconfigs/f/FDS/FDS-6.9.1-iomkl-2023a.eb
  easybuild/easyconfigs/f/FDS/FDS-6.9.1_intel_ompi.patch
  easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2023.1.0-iompi-2023a.eb
  easybuild/easyconfigs/i/iomkl/iomkl-2023a.eb
  easybuild/easyconfigs/i/iompi/iompi-2023a.eb
Labels: update

#22160 {vis}[GCCcore/13.2.0,foss/2023b,gfbf/2023b] Pillow-SIMD v10.4.0, tensorboard v2.18.0, torchvision v0.17.0, grapcio v1.67.1
  easybuild/easyconfigs/g/grpcio/grpcio-1.67.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/g/grpcio/grpcio-1.67.1_use-ebroot.patch
  easybuild/easyconfigs/p/Pillow-SIMD/Pillow-SIMD-10.4.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/t/tensorboard/tensorboard-2.18.0-gfbf-2023b.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.17.0-foss-2023b.eb
  easybuild/easyconfigs/t/torchvision/torchvision-0.17.0_fix-build-with-FFmpeg6.patch
  easybuild/easyconfigs/t/torchvision/torchvision-0.17.0_quantized_tol.patch
Labels: update

#21909 {bio,tools}[foss/2024a] R-bundle-Bioconductor v3.20, arrow-R v17.0.0 w/ R 4.4.2
  easybuild/easyconfigs/a/arrow-R/arrow-R-17.0.0.1-foss-2024a-R-4.4.2.eb
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.20-foss-2024a-R-4.4.2.eb
Labels: update

#22153 {lib}[GCC/13.3.0] pybind11_abseil v202402.0
  easybuild/easyconfigs/p/pybind11_abseil/pybind11_abseil-202402.0-GCC-13.3.0.eb
  easybuild/easyconfigs/p/pybind11_abseil/pybind11_abseil-202402.0_cmake.patch
Labels: new

#22165 {ai}[foss/2023a] HNOCA-tools v0.1.1 + GPU version (CUDA-12.1.1)
  easybuild/easyconfigs/h/HNOCA-tools/HNOCA-tools-0.1.1-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/h/HNOCA-tools/HNOCA-tools-0.1.1-foss-2023a.eb
Labels: new

#21495 {phys}[foss/2023b] FDS v6.9.1
  easybuild/easyconfigs/f/FDS/FDS-6.9.1-foss-2023b.eb
Labels: update

#22191 {bio}[foss/2023a] NEURON v8.2.6
  easybuild/easyconfigs/n/NEURON/NEURON-8.2.6-foss-2023a.eb
Labels: update

#22197 {geo}[foss/2024a] wrf-python v1.3.4.1-20241111, basemap v1.4.1, Cartopy v0.24.1
  easybuild/easyconfigs/b/basemap/basemap-1.4.1-foss-2024a.eb
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.24.1-foss-2024a.eb
  easybuild/easyconfigs/w/wrf-python/wrf-python-1.3.4.1-20241111-foss-2024a.eb
Labels: update

#21943 {lib}[GCCcore/12.3.0] WebKitGTK+ v2.41.4, Perl v5.36.1, unifdef v2.12, ... w/ minimal
  easybuild/easyconfigs/l/libwpe/libwpe-1.16.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/pugixml/pugixml-1.14-GCCcore-12.3.0.eb
  easybuild/easyconfigs/u/unifdef/unifdef-2.12-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/Waylandpp/Waylandpp-1.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.41.4-foss-2023a.eb
  easybuild/easyconfigs/w/wpebackend-fdo/wpebackend-fdo-1.15.90-GCCcore-12.3.0.eb
Labels: update

#22151 add seqPattern, genomation, ChIPseeker, SimBu extensions to R-bundle-Bioconductor v3.19
  easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.19-foss-2023b-R-4.4.1.eb
Labels: change

#22203 {math}[GCCcore/13.2.0] matlab-proxy v0.23.4
  easybuild/easyconfigs/m/matlab-proxy/matlab-proxy-0.23.4-GCCcore-13.2.0.eb
Labels: update

#22185 {bio}[foss/2023a] dorado v0.9.0 w/ CUDA 12.1.1
  easybuild/easyconfigs/d/dorado/dorado-0.9.0-foss-2023a-CUDA-12.1.1.eb
Labels: update

#22199 {bio}[foss/2024a] YaHS 1.2.2
  easybuild/easyconfigs/y/YaHS/YaHS-1.2.2-foss-2024a.eb
Labels: new

#22193 {tools}[system/system] libtree v3.1.1
  easybuild/easyconfigs/l/libtree/libtree-3.1.1.eb
  easybuild/easyconfigs/l/libtree/libtree-3.1.1_fix_32_bit_test.patch
Labels: update

#22148 {lib}[gfbf/2024a] trimesh v4.5.3
  easybuild/easyconfigs/t/trimesh/trimesh-4.5.3-gfbf-2024a.eb
Labels: update

#22176 {devel}[GCCcore/13.2.0] cython-cmake v0.2.0
  easybuild/easyconfigs/c/cython-cmake/cython-cmake-0.2.0-GCCcore-13.2.0.eb
Labels: new

#22163 {bio}[foss/2023a] vRhyme v1.1.0
  easybuild/easyconfigs/v/vRhyme/vRhyme-1.1.0-foss-2023a.eb
Labels: new

#21949 {bio,vis}[foss/2023a] CellProfiler v4.2.8, wxPython v4.2.1
  easybuild/easyconfigs/c/CellProfiler/CellProfiler-4.2.8-foss-2023a.eb
  easybuild/easyconfigs/c/CellProfiler/CellProfiler-4.2.8_deps.patch
  easybuild/easyconfigs/c/CellProfiler/cellprofiler-core-4.2.8_deps.patch
  easybuild/easyconfigs/c/CellProfiler/centrosome-1.2.3_deps.patch
  easybuild/easyconfigs/w/wxPython/wxPython-4.2.1-foss-2023a.eb
Labels: new, update

#22209 {cae}[foss/2023a] OpenFOAM v9
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-9-foss-2023a.eb
Labels: update

#22169 {lib}[GCC/13.3.0,gfbf/2024a] Boost.Python-NumPy v1.85.0, Boost.Python v1.85.0
  easybuild/easyconfigs/b/Boost.Python-NumPy/Boost.Python-NumPy-1.85.0-gfbf-2024a.eb
  easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.85.0-GCC-13.3.0.eb
Labels: update

#22132 {vis}[foss/2024a] imageio v2.36.1, scikit-image v0.25.0, sisl v0.15.2
  easybuild/easyconfigs/d/dill/dill-0.3.9-GCCcore-13.3.0.eb
  easybuild/easyconfigs/i/imageio/imageio-2.36.1-gfbf-2024a.eb
  easybuild/easyconfigs/m/multiprocess/multiprocess-0.70.17-gfbf-2024a.eb
  easybuild/easyconfigs/p/PyWavelets/PyWavelets-1.8.0-foss-2024a.eb
  easybuild/easyconfigs/p/pathos/pathos-0.3.3-foss-2024a.eb
  easybuild/easyconfigs/s/scikit-image/scikit-image-0.25.0-foss-2024a.eb
  easybuild/easyconfigs/s/sisl/sisl-0.15.2-foss-2024a.eb
Labels: new, update

#22214 {tools}[system/system] tmux v3.5a
  easybuild/easyconfigs/t/tmux/tmux-3.5a.eb
Labels: update

#22210 {chem}[foss/2022a] Critic2 v1.2
  easybuild/easyconfigs/c/Critic2/Critic2-1.2-foss-2022a.eb
Labels: update

#22206 {system}[system/system] CUDA v12.8.0
  easybuild/easyconfigs/c/CUDA/CUDA-12.8.0.eb
Labels: update

#22208 {math}[intel/2024a] ELPA v2024.05.001
  easybuild/easyconfigs/e/ELPA/ELPA-2024.05.001-intel-2024a.eb
Labels: update

#22213 {lib}[GCCcore/12.3.0] squashfs-tools v4.6.1
  easybuild/easyconfigs/s/squashfs-tools/squashfs-tools-4.6.1-GCCcore-12.3.0.eb
Labels: new

#22181 {lib,vis}[GCCcore/12.3.0,foss/2023a] VMD v1.9.4a57, ACTC v1.1
  easybuild/easyconfigs/a/ACTC/ACTC-1.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a57-foss-2023a.eb
Labels: update

#21738 {devel}[system/system] quarto v1.5.57
  easybuild/easyconfigs/q/quarto/quarto-1.5.57-x64.eb
Labels: new

#22222 {bio}[GCC/13.3.0] Sabre v2013-09-28
  easybuild/easyconfigs/s/Sabre/Sabre-2013-09-28-GCC-13.3.0.eb
Labels: update

#22225 {lib}[foss/2024a] zarr 2.18.4, py-cpuinfo 9.0.0
  easybuild/easyconfigs/p/py-cpuinfo/py-cpuinfo-9.0.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/z/zarr/zarr-2.18.4-foss-2024a.eb
Labels: update

#22202 {bio}[GCC/13.3.0] msisensor-pro 1.3.0
  easybuild/easyconfigs/m/msisensor-pro/msisensor-pro-1.3.0-GCC-13.3.0.eb
  easybuild/easyconfigs/m/msisensor-pro/msisensor-pro-1.3.0_makefile.patch
Labels: new

#22232 {bio}[gompi/2023a] parallel-fastq-dump v0.6.7
  easybuild/easyconfigs/p/parallel-fastq-dump/parallel-fastq-dump-0.6.7-gompi-2023a.eb
Labels: update

#22234 add patch for WIEN2k 24.1 to fix bug in symmetry determination
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-24.1-intel-2023a.eb
  easybuild/easyconfigs/w/WIEN2k/WIEN2k-24.1_fix-symmetso-angle.patch
Labels: bug fix

#22235 use latest version (0.2.5) of archspec for LAMMPS 2Aug2023 easyconfigs
  easybuild/easyconfigs/a/archspec/archspec-0.2.5-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update2-foss-2023a-kokkos-CUDA-12.1.1.eb
  easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update2-foss-2023a-kokkos.eb
Labels: enhancement, update, change

#22233 {bio}[foss/2023a] MultiQC v1.20
  easybuild/easyconfigs/m/MultiQC/MultiQC-1.20-foss-2023a.eb
Labels: update

#22231 {bio}[GCC/12.3.0] TopHat v2.1.2 w/ Python 2.7.18
  easybuild/easyconfigs/t/TopHat/TopHat-2.1.2-GCC-12.3.0-Python-2.7.18.eb
Labels: update

#22243 {tools}[foss/2023a] llama.cpp vb4595 w/ CUDA 12.1.1
  easybuild/easyconfigs/l/llama.cpp/llama.cpp-b4595-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/l/llama.cpp/llama.cpp-b4595-foss-2023a.eb
Labels: new

#22244 {bio}[foss/2024a] nichenetr v2.2.0 w/ R 4.4.2
  easybuild/easyconfigs/n/nichenetr/nichenetr-2.2.0-foss-2024a-R-4.4.2.eb
Labels: update

#22159 {lib}[GCCcore/12.3.0] QGIS v3.40.2, QScintilla v2.14.1, draco v1.5.7, ...
  easybuild/easyconfigs/d/draco/draco-1.5.7-foss-2023a.eb
  easybuild/easyconfigs/f/FreeXL/FreeXL-2.0.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/g/GRASS/GRASS-8.4.0-foss-2023a.eb
  easybuild/easyconfigs/l/librttopo/librttopo-1.1.0-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libspatialite/libspatialite-5.1.0-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/minizip/minizip-1.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/PDAL/PDAL-2.8.2-foss-2023a.eb
  easybuild/easyconfigs/q/QCA/QCA-2.3.9-GCCcore-12.3.0.eb
  easybuild/easyconfigs/q/QGIS/QGIS-3.40.2-foss-2023a.eb
  easybuild/easyconfigs/q/QGIS/QGIS-3.40.2_fix-SIP-macro.patch
  easybuild/easyconfigs/q/QScintilla/QScintilla-2.14.1-GCCcore-12.3.0.eb
  easybuild/easyconfigs/q/Qt5Webkit/Qt5Webkit-5.212.0-alpha4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/q/QtKeychain/QtKeychain-0.14.3-GCCcore-12.3.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.0.3-GCCcore-12.3.0.eb
Labels: new, update

#22241 {cae}[foss/2023a] OpenFOAM vv2112
  easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-foss-2023a.eb
Labels: update

#22218 {vis}[foss/2022a] sensormotion v1.1.5
  easybuild/easyconfigs/s/sensormotion/sensormotion-1.1.5-foss-2022a.eb
Labels: new

#22226 Add MathWorksServiceHost dependency to MATLAB
  easybuild/easyconfigs/m/MATLAB/MATLAB-2024b.eb
  easybuild/easyconfigs/m/MathWorksServiceHost/MathWorksServiceHost-2024.13.0.2.eb
Labels: new, change

#22207 {compiler}[system/system] NVHPC v25.1 w/ CUDA 12.6.0
  easybuild/easyconfigs/n/NVHPC/NVHPC-25.1-CUDA-12.6.0.eb
Labels: update
