Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-03, with the labels that each got.

#22291 {numlib}[GCC/13.3.0] AOCL-BLAS v5.0 (+ add hint on AOCL-BLAS backend to FlexiBLAS 3.4.4 easyconfig)
  easybuild/easyconfigs/a/AOCL-BLAS/AOCL-BLAS-5.0-GCC-13.3.0.eb
  easybuild/easyconfigs/f/FlexiBLAS/FlexiBLAS-3.4.4-GCC-13.3.0.eb
Labels: new

#22416 remove deprecated `allow_prepend_abs_path` from libglvnd and SpaceRanger
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.2-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.3-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.3-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.4.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.6.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.6.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.0-GCC-10.3.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.1-GCC-11.2.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.0.0-GCC-11.2.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.0.1-GCC-11.3.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.1.0-GCC-11.3.0.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.1.0-GCC-12.2.0.eb
Labels: change, EasyBuild-5.0

#22362 {bio}[GCCcore/12.3.0,foss/2023a] CheckM v1.0.18, DendroPy v4.5.2 w/ Python 2.7.18
  easybuild/easyconfigs/c/CheckM/CheckM-1.0.18-foss-2023a-Python-2.7.18.eb
  easybuild/easyconfigs/d/DendroPy/DendroPy-4.5.2-GCCcore-12.3.0-Python-2.7.18.eb
Labels: update

#22392 {bio}[foss/2023a] QUAST v5.2.0 w/ Python 2.7.18
  easybuild/easyconfigs/q/QUAST/QUAST-5.2.0-foss-2023a-Python-2.7.18.eb
Labels: update

#22406 {bio}[foss/2023a] Biopython v1.76 w/ Python 2.7.18
  easybuild/easyconfigs/b/Biopython/Biopython-1.76-foss-2023a-Python-2.7.18.eb
Labels: update

#22425 {bio}[GCC/13.3.0, GCCcore/13.3.0] Mash v2.3, CapnProto v1.1.0
  easybuild/easyconfigs/c/CapnProto/CapnProto-1.1.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-13.3.0.eb
Labels: update

#22431 {bio}[GCC/12.3.0,GCCcore/12.3.0,foss/2023a] CONCOCT v1.1.0, MEGAHIT v1.2.9, BEDTools v2.31.0 w/ Python 2.7.18
  easybuild/easyconfigs/c/CONCOCT/CONCOCT-1.1.0-foss-2023a-Python-2.7.18.eb
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.3.0-Python-2.7.18.eb
Labels: update

#22424 {ai}[GCCcore/13.3.0] ollama v0.5.12, Go v1.23.6 w/ CUDA 12.6.0
  easybuild/easyconfigs/g/Go/Go-1.23.6.eb
  easybuild/easyconfigs/o/ollama/ollama-0.5.12-GCCcore-13.3.0-CUDA-12.6.0.eb
  easybuild/easyconfigs/o/ollama/ollama-0.5.12-GCCcore-13.3.0.eb
Labels: update

#22433 {bio,system}[GCCcore/13.3.0,gompi/2024a] SRA-Toolkit v3.2.0, ncbi-vdb v3.2.0, file v5.46
  easybuild/easyconfigs/f/file/file-5.46-GCCcore-13.3.0.eb
  easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.2.0-gompi-2024a.eb
  easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-3.2.0-gompi-2024a.eb
Labels: update

#22435 {bio}[GCC/13.3.0] seqtk v1.4
  easybuild/easyconfigs/s/seqtk/seqtk-1.4-GCC-13.3.0.eb
Labels: update

#22434 {bio}[GCCcore/13.3.0] MEGAHIT v1.2.9
  easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-13.3.0.eb
Labels: update

#22439 Use f-strings for MATLAB download instructions
  easybuild/easyconfigs/m/MATLAB/MATLAB-2023a.eb
  easybuild/easyconfigs/m/MATLAB/MATLAB-2023b.eb
  easybuild/easyconfigs/m/MATLAB/MATLAB-2024b.eb
Labels: change, code cleanup, EasyBuild-5.0

#22325 Fix warning in jax 0.3.x that fails the build by using `-Wno-maybe-uninitialized`
  easybuild/easyconfigs/j/jax/jax-0.3.14-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/j/jax/jax-0.3.23-foss-2021b-CUDA-11.4.1.eb
  easybuild/easyconfigs/j/jax/jax-0.3.23-foss-2022a.eb
  easybuild/easyconfigs/j/jax/jax-0.3.25-foss-2022a-CUDA-11.7.0.eb
  easybuild/easyconfigs/j/jax/jax-0.3.25-foss-2022a.eb
  easybuild/easyconfigs/j/jax/jax-0.3.9-foss-2021a-CUDA-11.3.1.eb
  easybuild/easyconfigs/j/jax/jax-0.3.9-foss-2021a.eb
Labels: bug fix

#22445 {tools}[GCCcore/13.3.0] pigz v2.8
  easybuild/easyconfigs/p/pigz/pigz-2.8-GCCcore-13.3.0.eb
Labels: update

#22441 {devel}[GCCcore/13.3.0] SCons v4.9.0
  easybuild/easyconfigs/s/SCons/SCons-4.9.0-GCCcore-13.3.0.eb
Labels: update

#22457 update workflows to use Ubuntu 22.04
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: bug fix, tests, EasyBuild-5.0, workflow

#22464 {tools}[GCCcore/13.3.0] Brotli-python v1.1.0
  easybuild/easyconfigs/b/Brotli-python/Brotli-python-1.1.0-GCCcore-13.3.0.eb
Labels: update

#22444 {bio}[GCC/13.3.0] Velvet v1.2.10 w/ mt kmer_191
  easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-GCC-13.3.0-mt-kmer_191.eb
Labels: update

#22459 Update GitHub actions runners
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
Labels: bug fix, tests, workflow

#22345 add patch for QuantumESPRESSO 7.4 to fix parallel symmetrization glitch
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-foss-2024a.eb
  easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-parallel-symmetrization.patch
Labels: bug fix

#22212 MFiX/24.4.1-intel-2023b
  easybuild/easyconfigs/m/MFiX/MFiX-24.4.1-intel-2023b.eb
  easybuild/easyconfigs/m/MFiX/MFiX-24.4.1-remove-tab.patch
Labels: new

#22446 {bio}[GCCcore/13.3.0] samclip v0.4.0
  easybuild/easyconfigs/s/samclip/samclip-0.4.0-GCCcore-13.3.0.eb
Labels: update

#22442 {bio}[GCC/13.3.0] Lighter v1.1.3
  easybuild/easyconfigs/l/Lighter/Lighter-1.1.3-GCC-13.3.0.eb
Labels: update

#22440 {bio}[gompi/2024a] SKESA v2.4.0 w/ _saute.1.3.0_2
  easybuild/easyconfigs/s/SKESA/SKESA-2.4.0-gompi-2024a_saute.1.3.0_2.eb
Labels: update

#22480 {data}[foss/2024a] h5py v3.12.1
  easybuild/easyconfigs/h/h5py/h5py-3.12.1-foss-2024a.eb
Labels: update

#22429 add missing Doxygen build dependency for bcl2fastq2
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-10.2.0.eb
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-10.3.0.eb
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-11.2.0.eb
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-11.3.0.eb
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-12.2.0.eb
Labels: bug fix, EasyBuild-5.0

#22493 Pandoc easyconfigs supporting multiple archs must have multiple checksums
  easybuild/easyconfigs/p/Pandoc/Pandoc-3.1.2.eb
  easybuild/easyconfigs/p/Pandoc/Pandoc-3.6.2.eb
Labels: change

#22479 {lib}[foss/2024a] cnvpytor v1.3.1
  easybuild/easyconfigs/c/cnvpytor/cnvpytor-1.3.1-foss-2024a.eb
Labels: new

#22472 Update GitHub actions workflows to use ubuntu-22.04 or ubuntu-24.04
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: tests, EasyBuild-5.0, workflow

#22174 swicth GCC-system and GCCcore-system to SystemCompilerGCC easyblock
  easybuild/easyconfigs/g/GCC/GCC-system.eb
  easybuild/easyconfigs/g/GCCcore/GCCcore-system.eb
  test/easyconfigs/easyconfigs.py
Labels: change, EasyBuild-5.0

#21984 add collection of easyconfig templates organized per generation
  contrib/easyconfig-templates/2022a/Bundle-common-components.eb.tmpl
  contrib/easyconfig-templates/2022a/Bundle-mixed-components.eb.tmpl
  contrib/easyconfig-templates/2022a/CMakeMake-minimal.eb.tmpl
  contrib/easyconfig-templates/2022a/CMakeMake-python-extension-github.eb.tmpl
  contrib/easyconfig-templates/2022a/ConfigureMake-autotools-github-commit.eb.tmpl
  contrib/easyconfig-templates/2022a/ConfigureMake-minimal.eb.tmpl
  contrib/easyconfig-templates/2022a/MakeCp-minimal.eb.tmpl
  contrib/easyconfig-templates/2022a/PackedBinary-java.eb.tmpl
  contrib/easyconfig-templates/2022a/PythonBundle-minimal.eb.tmpl
  contrib/easyconfig-templates/2022a/PythonBundle-scipy.eb.tmpl
  contrib/easyconfig-templates/2022a/Tarball-perl.eb.tmpl
  contrib/easyconfig-templates/2023a/Bundle-common-components.eb.tmpl
  contrib/easyconfig-templates/2023a/Bundle-mixed-components.eb.tmpl
  contrib/easyconfig-templates/2023a/CMakeMake-minimal.eb.tmpl
  contrib/easyconfig-templates/2023a/CMakeMake-python-extension-github.eb.tmpl
  contrib/easyconfig-templates/2023a/ConfigureMake-autotools-github-commit.eb.tmpl
  contrib/easyconfig-templates/2023a/ConfigureMake-minimal.eb.tmpl
  contrib/easyconfig-templates/2023a/MakeCp-minimal.eb.tmpl
  contrib/easyconfig-templates/2023a/PackedBinary-java.eb.tmpl
  contrib/easyconfig-templates/2023a/PythonBundle-minimal.eb.tmpl
  contrib/easyconfig-templates/2023a/PythonBundle-pytest.eb.tmpl
  contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
  contrib/easyconfig-templates/2023a/Tarball-perl.eb.tmpl
  contrib/easyconfig-templates/2024a/Bundle-common-components.eb.tmpl
  contrib/easyconfig-templates/2024a/Bundle-mixed-components.eb.tmpl
  contrib/easyconfig-templates/2024a/CMakeMake-minimal.eb.tmpl
  contrib/easyconfig-templates/2024a/CMakeMake-python-extension-github.eb.tmpl
  contrib/easyconfig-templates/2024a/ConfigureMake-autotools-github-commit.eb.tmpl
  contrib/easyconfig-templates/2024a/ConfigureMake-minimal.eb.tmpl
  contrib/easyconfig-templates/2024a/MakeCp-minimal.eb.tmpl
  contrib/easyconfig-templates/2024a/PackedBinary-java.eb.tmpl
  contrib/easyconfig-templates/2024a/PythonBundle-minimal.eb.tmpl
  contrib/easyconfig-templates/2024a/PythonBundle-pytest.eb.tmpl
  contrib/easyconfig-templates/2024a/PythonBundle-scipy.eb.tmpl
  contrib/easyconfig-templates/2024a/Tarball-perl.eb.tmpl
  contrib/easyconfig-templates/README.rst
  easybuild/easyconfigs/TEMPLATE.eb
  setup.py
  test/easyconfigs/easyconfigs.py
Labels: enhancement, change, EasyBuild-5.0

#22399 {perf}[GCC/13.3.0,gompi/2024a] Extrae v4.2.5, Paraver v4.12.0
  easybuild/easyconfigs/e/Extrae/Extrae-4.2.5-gompi-2024a.eb
  easybuild/easyconfigs/p/Paraver/Paraver-4.12.0-GCC-13.3.0.eb
Labels: update, 2024a

#22292 {phys}[foss/2023a] Siesta v5.2.2
  easybuild/easyconfigs/f/flook/flook-0.8.4-GCC-12.3.0.eb
  easybuild/easyconfigs/f/flook/flook-0.8.4_flook.pc.in.patch
  easybuild/easyconfigs/l/libGridXC/libGridXC-2.0.2-gompi-2023a.eb
  easybuild/easyconfigs/l/libPSML/libPSML-2.1.0-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.5.1-GCC-12.3.0.eb
  easybuild/easyconfigs/s/Siesta/Siesta-5.2.2-foss-2023a.eb
  easybuild/easyconfigs/s/Simple-DFTD3/Simple-DFTD3-1.2.1-gfbf-2023a.eb
  easybuild/easyconfigs/t/TOML-Fortran/TOML-Fortran-0.4.2-GCC-12.3.0.eb
  easybuild/easyconfigs/t/test-drive/test-drive-0.5.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.6.3-GCC-12.3.0.eb
Labels: new, update

#22508 {bio}[system/system] bcl-convert v4.3.13-2 w/ .el8.x86_64
  easybuild/easyconfigs/b/bcl-convert/bcl-convert-4.3.13-2.el8.x86_64.eb
Labels: update

#22522 remove `install_pip = True` from `Python-3.13.1-GCCcore-14.2.0.eb`
  easybuild/easyconfigs/p/Python/Python-3.13.1-GCCcore-14.2.0.eb
Labels: change, code cleanup, EasyBuild-5.0

#22518 {base}[foss/2024a] REViewer v0.2.7
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7-foss-2024a.eb
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7_GraphCoordinates_cpp.patch
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7_graph-tools_CMakeLists.patch
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7_reviewer_CMakeLists.txt.patch
Labels: new

#22523 fix download source for PDT/3.25.2
  easybuild/easyconfigs/p/PDT/PDT-3.25.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/PDT/PDT-3.25.2-GCCcore-13.3.0.eb
Labels: bug fix, change, EasyBuild-5.0

#22477 {tools}[gfbf/2024a] ml_dtypes v0.5.0
  easybuild/easyconfigs/m/ml_dtypes/ml_dtypes-0.5.0-gfbf-2024a.eb
Labels: update

#22521 use `PerlBundle` easyblock for XML-LibXML
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0206-GCCcore-10.2.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0207-GCCcore-10.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0207-GCCcore-11.2.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0207-GCCcore-11.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0208-GCCcore-12.2.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0209-GCCcore-12.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0210-GCCcore-13.2.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0210-GCCcore-13.3.0.eb
Labels: bug fix, change

#22450 use .tar.xz archive for jsonpath_lib sources in polars v0.20.2
  easybuild/easyconfigs/p/polars/polars-0.20.2-gfbf-2023a.eb
Labels: bug fix, change, EasyBuild-5.0

#22555 fix MPICH with-device configuration option
  easybuild/easyconfigs/m/MPICH/MPICH-3.3.2-GCC-10.2.0.eb
  easybuild/easyconfigs/m/MPICH/MPICH-3.4.2-GCC-10.3.0.eb
  easybuild/easyconfigs/m/MPICH/MPICH-4.2.1-GCC-12.3.0.eb
  easybuild/easyconfigs/m/MPICH/MPICH-4.2.2-GCC-13.3.0.eb
Labels: change, EasyBuild-5.0

#22557 add missing pybind11 build dependency for bokeh 3.6.0
  easybuild/easyconfigs/b/bokeh/bokeh-3.6.0-gfbf-2024a.eb
Labels: bug fix, EasyBuild-5.0

#22558 don't use unknown configure options --with-gmp and --with-givaro in easyconfig for FFLAS-FFPACK 2.5.0
  easybuild/easyconfigs/f/FFLAS-FFPACK/FFLAS-FFPACK-2.5.0-gfbf-2023b.eb
Labels: bug fix

#22559 {ai}[GCCcore/13.3.0] ollama v0.6.0 w/ CUDA 12.6.0
  easybuild/easyconfigs/o/ollama/ollama-0.6.0-GCCcore-13.3.0-CUDA-12.6.0.eb
  easybuild/easyconfigs/o/ollama/ollama-0.6.0-GCCcore-13.3.0.eb
Labels: update

#22565 disable keepsymlinks in libStatGen
  easybuild/easyconfigs/l/libStatGen/libStatGen-1.0.15-GCCcore-10.2.0.eb
  easybuild/easyconfigs/l/libStatGen/libStatGen-1.0.15-GCCcore-12.3.0.eb
Labels: bug fix, EasyBuild-5.0

#22564 Add `$TMPDIR` to sandbox mounts for Bazel 7.4.1 tests
  easybuild/easyconfigs/b/Bazel/Bazel-7.4.1-GCCcore-13.3.0.eb
Labels: bug fix, EasyBuild-5.0

#22566 use .tar.xz archive for jsonpath_lib sources in polars v0.19.19
  easybuild/easyconfigs/p/polars/polars-0.19.19-gfbf-2023a.eb
Labels: bug fix, change, EasyBuild-5.0

#22567 add build dependency on git to Scalene
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.13-GCCcore-11.2.0.eb
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.20-GCCcore-11.3.0.eb
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.26-GCCcore-12.2.0.eb
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.26-GCCcore-12.3.0.eb
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.35-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/Scalene/Scalene-1.5.51-gfbf-2024a.eb
Labels: bug fix, EasyBuild-5.0

#22569 don't use unknown configure options in LinBox easyconfig
  easybuild/easyconfigs/l/LinBox/LinBox-1.7.0-gfbf-2023b.eb
Labels: bug fix

#22397 {bio}[gompi/2024a] Unicycler v0.5.1, SPAdes v4.1.0, Racon v1.5.0, BLAST+ v2.16.0
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.16.0-gompi-2024a.eb
  easybuild/easyconfigs/r/Racon/Racon-1.5.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-4.1.0-GCC-13.3.0.eb
  easybuild/easyconfigs/u/Unicycler/Unicycler-0.5.1-gompi-2024a.eb
Labels: update

#22571 consistently use patch in easyconfigs for PRSice 2.3.5 to stop relying on sysctl.h
  easybuild/easyconfigs/p/PRSice/PRSice-2.3.5-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PRSice/PRSice-2.3.5-GCCcore-12.3.0.eb
Labels: bug fix

#22546 dcm2niix for 2024a
  easybuild/easyconfigs/c/CharLS/CharLS-2.4.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/d/dcm2niix/dcm2niix-1.0.20241211-GCCcore-13.3.0.eb
Labels: update

#22572 make CMake a runtime dependency of gemmi
  easybuild/easyconfigs/g/gemmi/gemmi-0.4.5-GCCcore-10.2.0.eb
  easybuild/easyconfigs/g/gemmi/gemmi-0.6.5-GCCcore-12.3.0.eb
Labels: bug fix, EasyBuild-5.0

#22574 switch download source for ffnvcodec
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-11.1.5.2.eb
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-12.0.16.0.eb
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-12.1.14.0.eb
  easybuild/easyconfigs/f/ffnvcodec/ffnvcodec-12.2.72.0.eb
Labels: change

#22570 add patch to fix build failure due to too long filenames in Qt6
  easybuild/easyconfigs/q/Qt6/Qt6-6.5.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/q/Qt6/Qt6-6.5.2_fix_too_long_filenames.patch
  easybuild/easyconfigs/q/Qt6/Qt6-6.6.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/q/Qt6/Qt6-6.7.2-GCCcore-13.3.0.eb
Labels: bug fix, EasyBuild-5.0

#22573 clean up easyconfigs so they don't explicitly enable `keepsymlinks`, since it's now enabled by default
  easybuild/easyconfigs/a/ADF/ADF-2019.303-intelmpi.eb
  easybuild/easyconfigs/a/AMS/AMS-2020.102-iimpi-2020b-intelmpi.eb
  easybuild/easyconfigs/a/AMS/AMS-2022.102-iimpi-2021b-intelmpi.eb
  easybuild/easyconfigs/a/AMS/AMS-2023.101-iimpi-2022a-intelmpi.eb
  easybuild/easyconfigs/a/AMS/AMS-2023.104-iimpi-2022b-intelmpi.eb
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.41-foss-2021b.eb
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.41-foss-2023a.eb
  easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.41-foss-2023b.eb
  easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-1.0.1.eb
  easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.0.eb
  easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.1.eb
  easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.2.eb
  easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-1.2.0.eb
  easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-2.0.0.eb
  easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-2.1.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-4.0.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-5.0.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-5.0.1.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.1.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.2.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-6.1.2.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-7.0.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-7.1.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-7.2.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-8.0.0.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-8.0.1.eb
  easybuild/easyconfigs/c/CellRanger/CellRanger-9.0.0.eb
  easybuild/easyconfigs/n/netMHCII/netMHCII-2.3.eb
  easybuild/easyconfigs/r/RInChI/RInChI-1.00-x86_64.eb
  easybuild/easyconfigs/s/Spack/Spack-0.16.2.eb
  easybuild/easyconfigs/s/Spack/Spack-0.17.0.eb
  easybuild/easyconfigs/s/Spack/Spack-0.17.2.eb
  easybuild/easyconfigs/s/Spack/Spack-0.21.2.eb
  easybuild/easyconfigs/s/SqueezeMeta/SqueezeMeta-1.5.0-foss-2021b.eb
  easybuild/easyconfigs/s/sonic/sonic-20180202-gfbf-2023a.eb
Labels: change, code cleanup, EasyBuild-5.0

#22510 {bio}[GCC/13.3.0] bwa-mem2-2.2.1
  easybuild/easyconfigs/b/bwa-mem2/bwa-mem2-2.2.1-GCC-13.3.0.eb
  easybuild/easyconfigs/s/safestringlib/safestringlib-20240228-GCC-13.3.0.eb
Labels: update

#22576 replace source URLs of Mesa to new location in archive.mesa3d.org
  easybuild/easyconfigs/m/Mesa/Mesa-20.2.1-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.1.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-21.1.7-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-22.0.3-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-22.2.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-23.1.4-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-23.1.9-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/Mesa/Mesa-24.1.3-GCCcore-13.3.0.eb
Labels: bug fix, change, EasyBuild-5.0

#22577 removed unknown configure options for GRASS 8.4.0
  easybuild/easyconfigs/g/GRASS/GRASS-8.4.0-foss-2023a.eb
Labels: bug fix

#22578 sync with develop (20250316)
  easybuild/easyconfigs/b/BLAST+/BLAST+-2.16.0-gompi-2024a.eb
  easybuild/easyconfigs/b/bcl-convert/bcl-convert-4.3.13-2.el8.x86_64.eb
  easybuild/easyconfigs/b/bwa-mem2/bwa-mem2-2.2.1-GCC-13.3.0.eb
  easybuild/easyconfigs/c/CharLS/CharLS-2.4.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/d/dcm2niix/dcm2niix-1.0.20241211-GCCcore-13.3.0.eb
  easybuild/easyconfigs/f/flook/flook-0.8.4-GCC-12.3.0.eb
  easybuild/easyconfigs/f/flook/flook-0.8.4_flook.pc.in.patch
  easybuild/easyconfigs/l/libGridXC/libGridXC-2.0.2-gompi-2023a.eb
  easybuild/easyconfigs/l/libPSML/libPSML-2.1.0-GCC-12.3.0.eb
  easybuild/easyconfigs/l/libfdf/libfdf-0.5.1-GCC-12.3.0.eb
  easybuild/easyconfigs/m/ml_dtypes/ml_dtypes-0.5.0-gfbf-2024a.eb
  easybuild/easyconfigs/m/mrcfile/mrcfile-1.5.4-gfbf-2024a.eb
  easybuild/easyconfigs/o/ollama/ollama-0.6.0-GCCcore-13.3.0-CUDA-12.6.0.eb
  easybuild/easyconfigs/o/ollama/ollama-0.6.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7-foss-2024a.eb
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7_GraphCoordinates_cpp.patch
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7_graph-tools_CMakeLists.patch
  easybuild/easyconfigs/r/REViewer/REViewer-0.2.7_reviewer_CMakeLists.txt.patch
  easybuild/easyconfigs/r/Racon/Racon-1.5.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/s/SPAdes/SPAdes-4.1.0-GCC-13.3.0.eb
  easybuild/easyconfigs/s/Siesta/Siesta-5.2.2-foss-2023a.eb
  easybuild/easyconfigs/s/Simple-DFTD3/Simple-DFTD3-1.2.1-gfbf-2023a.eb
  easybuild/easyconfigs/s/safestringlib/safestringlib-20240228-GCC-13.3.0.eb
  easybuild/easyconfigs/s/spdlog/spdlog-1.12.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/t/TOML-Fortran/TOML-Fortran-0.4.2-GCC-12.3.0.eb
  easybuild/easyconfigs/t/test-drive/test-drive-0.5.0-GCC-12.3.0.eb
  easybuild/easyconfigs/u/Unicycler/Unicycler-0.5.1-gompi-2024a.eb
  easybuild/easyconfigs/x/xmlf90/xmlf90-1.6.3-GCC-12.3.0.eb
Labels: new, update, EasyBuild-5.0

#22582 update homepage and sources of MUMPS with new home at mumps-solver.org
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-foss-2020b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-intel-2020b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-foss-2021a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-intel-2021a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.1-foss-2021b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.1-intel-2021b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.0-foss-2021a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.1-foss-2022a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2022b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2023a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2023b-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-gomkl-2023a-metis-seq.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-foss-2023b-parmetis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-foss-2024a-metis.eb
  easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-intel-2023b-parmetis.eb
Labels: bug fix, change, EasyBuild-5.0

#22538 {bio}[gfbf/2023a] pairtools v1.1.2
  easybuild/easyconfigs/p/pairtools/pairtools-1.1.2-gfbf-2023a.eb
Labels: update

#22537 {bio}[foss/2023a] RSeQC v5.0.1
  easybuild/easyconfigs/r/RSeQC/RSeQC-5.0.1-foss-2023a.eb
Labels: update

#22535 {bio}[GCCcore/12.3.0] idemux v0.1.6
  easybuild/easyconfigs/i/idemux/idemux-0.1.6-GCCcore-12.3.0.eb
Labels: update

#22583 switch webclu.bio.wzw.tum.de to HTTPS in VMD easyconfigs
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a51-foss-2020b.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a51-fosscuda-2020b.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a57-foss-2022a.eb
  easybuild/easyconfigs/v/VMD/VMD-1.9.4a57-foss-2023a.eb
Labels: bug fix, EasyBuild-5.0

#22579 update homepage and sources of METIS and ParMETIS with new home at kaypis.github.io
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-10.2.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.2.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.3.0-int64.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.3.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-12.2.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-12.3.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2020b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2021a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2021b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2022a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2022b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2023a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2023b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2020b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2021a.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2021b.eb
  easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2023b.eb
Labels: bug fix, EasyBuild-5.0

#22585 add new checksum for sources of Stellarscope v1.4.1
  easybuild/easyconfigs/s/Stellarscope/Stellarscope-1.4.1-foss-2023a.eb
Labels: bug fix, change, EasyBuild-5.0

#22581 add new checksum for tantan v50 tarball
  easybuild/easyconfigs/t/tantan/tantan-50-GCC-12.3.0.eb
Labels: bug fix, change, EasyBuild-5.0

#22584 fix Python detection in HepMC3
  easybuild/easyconfigs/h/HepMC3/HepMC3-3.2.5-GCC-11.3.0.eb
  easybuild/easyconfigs/h/HepMC3/HepMC3-3.2.6-GCC-12.3.0.eb
Labels: bug fix, EasyBuild-5.0

#22592 {bio}[foss/2023b] DAS_Tool v1.1.7, CheckM v1.2.3, CompareM v0.1.2 w/ R 4.4.1
  easybuild/easyconfigs/c/CheckM/CheckM-1.2.3-foss-2023b.eb
  easybuild/easyconfigs/c/CompareM/CompareM-0.1.2-gfbf-2023b.eb
  easybuild/easyconfigs/d/DAS_Tool/DAS_Tool-1.1.7-foss-2023b-R-4.4.1.eb
  easybuild/easyconfigs/d/DAS_Tool/DAS_Tool-1.1.7_defaultSearchEngBLAST+.patch
  easybuild/easyconfigs/d/DendroPy/DendroPy-5.0.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/prodigal/prodigal-2.6.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/p/pullseq/pullseq-1.0.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/r/Ruby/Ruby-3.4.2-GCCcore-13.2.0.eb
Labels: update

#20489 {ai}[foss/2023b] PyTorch v2.3.0
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0-foss-2023b.eb
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_avoid_caffe2_test_cpp_jit.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_disable-gcc12-warning.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_disable_DataType_dependent_test_if_tensorboard_is_not_available.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_disable_test_linear_package_if_no_half_types_are_available.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_disable_tests_which_need_network_download.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_fix-mkldnn-avx512-f32-bias.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_fix-test_extension_backend-without-vectorization.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_fix_missing_masked_load_for_int_type.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_no-cuda-stubs-rpath.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_skip-test_init_from_local_shards.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_skip_test_sdpa_nn_functional_scaled_dot_product_attention_cpu.patch
  easybuild/easyconfigs/p/PyTorch/PyTorch-2.3.0_skip_test_var_mean_differentiable.patch
  easybuild/easyconfigs/t/tlparse/tlparse-0.3.5-GCCcore-13.2.0.eb
Labels: new, update

#22593 {bio}[gompi/2023b] MaxBin v2.2.7
  easybuild/easyconfigs/f/FragGeneScan/FragGeneScan-1.32-GCCcore-13.2.0.eb
  easybuild/easyconfigs/i/IDBA-UD/IDBA-UD-1.1.3-GCCcore-13.2.0.eb
  easybuild/easyconfigs/m/MaxBin/MaxBin-2.2.7-gompi-2023b.eb
Labels: update

#22595 bump version to 5.0.0 + update release notes
  RELEASE_NOTES
  setup.py
Labels: EasyBuild-5.0

#22536 {bio}[foss/2023a] cooltools v0.7.1
  easybuild/easyconfigs/c/cooltools/cooltools-0.7.1-foss-2023a.eb
Labels: new

#22605 remove Python 2.7 + Python 3.5 from classifiers in `setup.py`
  setup.py
Labels: bug fix, EasyBuild-5.0

#22609 libavif-1.1.1-GCCcore-13.2.0: Changing libyuv from builddependencies to dependencies
  easybuild/easyconfigs/l/libavif/libavif-1.1.1-GCCcore-13.2.0.eb
Labels: change

#22473 {bio}[foss/2023a] Boltz-1 v0.4.1
  easybuild/easyconfigs/b/Boltz-1/Boltz-1-0.4.1-foss-2023a.eb
Labels: new

#22621 remove Python 2.7 and 3.5 from list of classifiers
  setup.py
Labels: bug fix

#22610 {geo}[foss/2023a] FALL3D v9.0.1
  easybuild/easyconfigs/f/FALL3D/FALL3D-9.0.1-gompi-2023a.eb
Labels: new

#22562 {phys}[foss/2023a] Siesta v5.2.2
  easybuild/easyconfigs/s/Siesta/Siesta-5.2.2-foss-2023a.eb
  easybuild/easyconfigs/s/Siesta/Siesta-5.2.2-no_write_in_test.patch
Labels: change

#22489 {compiler,lang}[GCCcore/13.3.0,foss/2024a] LLVM v14.0.6, numba v0.60.0 w/ llvmlite
  easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-13.3.0-llvmlite.eb
  easybuild/easyconfigs/n/numba/numba-0.60.0-foss-2024a.eb
Labels: update

#22504 {lib}[GCCcore/13.3.0] grpcio v1.70.0
  easybuild/easyconfigs/g/grpcio/grpcio-1.70.0-GCCcore-13.3.0.eb
Labels: update

#22594 Update R-bundle-CRAN-{2024a, 2023b, 2023a} - add modsem and its dependencies
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
  easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.11-foss-2024a.eb
Labels: change

#22589 {bio}[GCC/13.3.0] Hybpiper v2.3.2, BBMap v39.19, Exonerate v2.4.0, ... w/ with extensions
  easybuild/easyconfigs/b/BBMap/BBMap-39.19-GCC-13.3.0.eb
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.1.11-GCC-13.3.0.eb
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-13.3.0.eb
  easybuild/easyconfigs/h/Hybpiper/Hybpiper-2.3.2-foss-2024a.eb
  easybuild/easyconfigs/m/MAFFT/MAFFT-7.526-GCC-13.3.0-with-extensions.eb
Labels: update

#22629 Fix CI failures due to deprecations
  easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-13.3.0.eb
  easybuild/easyconfigs/h/Hybpiper/Hybpiper-2.3.2-foss-2024a.eb
Labels: change

#22628 fix statsmodels 0.14.4 version
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.14.4-gfbf-2024a.eb
  easybuild/easyconfigs/s/statsmodels/statsmodels-0.14.4_fix_setup.patch
Labels: bug fix, change

#22633 {lib,numlib}[GCCcore/13.3.0] Pint v0.24.4, psycopg2 v2.9.10
  easybuild/easyconfigs/p/Pint/Pint-0.24.4-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/psycopg2/psycopg2-2.9.10-GCCcore-13.3.0.eb
Labels: update

#22611 {bio}[GCCcore/13.3.0] Bracken v3.1
  easybuild/easyconfigs/b/Bracken/Bracken-3.1-GCCcore-13.3.0.eb
Labels: update

#22612 {bio,devel,lib}[GCCcore/13.3.0] Kraken2 v2.1.4, libidn2 v2.3.8, wget v1.25.0
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.4-gompi-2024a.eb
  easybuild/easyconfigs/k/Kraken2/Kraken2-2.1.4_fix_installation_for_easybuild.patch
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/w/wget/wget-1.25.0-GCCcore-13.3.0.eb
Labels: update

#22602 Fix regression in pytest 8.2.2
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/pytest-8.2.2-fix-assertion-error-on-rerun.patch
Labels: bug fix, change

#22487 {lib}[GCCcore/13.3.0] Blosc v1.21.6, Blosc2 v2.17.0, PyTables v3.10.2
  easybuild/easyconfigs/b/Blosc/Blosc-1.21.6-GCCcore-13.3.0.eb
  easybuild/easyconfigs/b/Blosc2/Blosc2-2.17.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/PyTables/PyTables-3.10.2-foss-2024a.eb
Labels: update

#22634 {geo}[foss/2024a] geopandas v1.0.1
  easybuild/easyconfigs/g/geopandas/geopandas-1.0.1-foss-2024a.eb
Labels: update

#22635 {geo}[foss/2024a] xclim v0.55.1, clisops v0.15.0
  easybuild/easyconfigs/c/clisops/clisops-0.15.0-foss-2024a.eb
  easybuild/easyconfigs/x/xclim/xclim-0.55.1-foss-2024a.eb
Labels: new

#22600 {bio}[GCC/13.2.0] pairix v0.3.9
  easybuild/easyconfigs/p/pairix/pairix-0.3.9-GCC-13.2.0.eb
  easybuild/easyconfigs/p/pairix/pairix-0.3.9_fix_Makefile.patch
Labels: new

#22654 Fix pairix for CI in a 5.0.x world
  easybuild/easyconfigs/p/pairix/pairix-0.3.9-GCC-13.2.0.eb
Labels: change, code cleanup

#22632 {bio}[GCC/13.2.0] cellsnp-lite v1.2.3
  easybuild/easyconfigs/c/cellsnp-lite/cellsnp-lite-1.2.3-GCC-13.2.0.eb
Labels: new

#22432 {bio}[foss/2023a] metaWRAP v1.4-20230728 w/ Python 2.7.18
  easybuild/easyconfigs/m/metaWRAP/metaWRAP-1.4-20230728-foss-2023a-Python-2.7.18.eb
Labels: update

#22645 {tools}[GCCcore/14.2.0] git v2.49.0, gettext v0.24, psutil v7.0.0
  easybuild/easyconfigs/g/gettext/gettext-0.24-GCCcore-14.2.0.eb
  easybuild/easyconfigs/g/git/git-2.49.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/psutil/psutil-7.0.0-GCCcore-14.2.0.eb
Labels: update, 2025a

#22653 {devel}[GCCcore/13.3.0] Qt5 v5.15.16
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.16-GCCcore-13.3.0.eb
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.16_fix-includes.patch
  easybuild/easyconfigs/q/Qt5/Qt5-5.15.16_fix-python-312.patch
Labels: update

#22655 {compiler}[system/system] NVHPC v25.3 w/ CUDA 12.8.0
  easybuild/easyconfigs/n/NVHPC/NVHPC-25.3-CUDA-12.8.0.eb
Labels: update

#22539 {bio}[GCCcore/13.2.0] KronaTools v2.8.1
  easybuild/easyconfigs/k/KronaTools/KronaTools-2.8.1-GCCcore-13.2.0.eb
Labels: update

#22340 {tools}[foss/2023a] pyannote.audio v3.3.2
  easybuild/easyconfigs/p/pyannote.audio/pyannote.audio-3.3.2-foss-2023a.eb
Labels: update

#22437 {bio}[system/system] Pilon v1.24 w/ Java 17
  easybuild/easyconfigs/p/Pilon/Pilon-1.24-Java-17.eb
Labels: update

#22540 {bio}[foss/2023a,gompi/2023a] bcgTree v1.2.1, RAxML v8.2.13 w/ avx2
  easybuild/easyconfigs/b/bcgTree/bcgTree-1.2.1-foss-2023a.eb
  easybuild/easyconfigs/r/RAxML/RAxML-8.2.13-gompi-2023a-avx2.eb
Labels: new, update

#22469 add patch for astropy 7.0.0 to make one of the tests pass on ARM architectures
  easybuild/easyconfigs/a/astropy/astropy-7.0.0-gfbf-2023b.eb
  easybuild/easyconfigs/a/astropy/astropy-7.0.0_test_quantities_fitting.patch
Labels: bug fix

#22447 {bio}[gompi/2024a] shovill v1.1.0
  easybuild/easyconfigs/s/shovill/shovill-1.1.0-gompi-2024a.eb
Labels: update

#22623 {bio}[GCC/12.3.0] BBMap v39.19
  easybuild/easyconfigs/b/BBMap/BBMap-39.19-GCC-12.3.0.eb
Labels: update

#22541 {bio}[GCC/12.3.0] Bismark v0.24.2
  easybuild/easyconfigs/b/Bismark/Bismark-0.24.2-GCC-12.3.0.eb
Labels: update
