Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-09, with the labels that each got.

#22702 {devel,tools,vis}[GCCcore/13.3.0] Emacs v30.1, GTK+ v3.24.23, pkg-config v0.29.2
  easybuild/easyconfigs/e/Emacs/Emacs-30.1-GCCcore-13.3.0.eb
  easybuild/easyconfigs/g/GnuTLS/GnuTLS-3.7.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libtasn1/libtasn1-4.19.0-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/p11-kit/p11-kit-0.25.3-GCCcore-13.3.0.eb
  easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-13.3.0.eb
Labels: update, 2024a

#23130 {tools}[foss/2023b] IMAS-Python v2.0.1
  easybuild/easyconfigs/i/IMAS-Python/IMAS-Python-2.0.1-foss-2023b.eb
Labels: update, 2023b

#23726 {tools}[foss/2023a] BigStitcher-Spark v0.1.0-2025.08.18 w/ Java 17
  easybuild/easyconfigs/b/BigStitcher-Spark/BigStitcher-Spark-0.1.0-2025.08.18-foss-2023a-Java-17.eb
Labels: new, 2023a

#23767 {devel}[GCCcore/12.3.0] CMake 3.31.8
  easybuild/easyconfigs/c/CMake/CMake-3.31.8-GCCcore-12.3.0.eb
Labels: update, 2023a

#23224 {lib}[foss/2023a] mcpl v2.2.0
  easybuild/easyconfigs/m/mcpl/mcpl-2.2.0-foss-2023a.eb
Labels: new, 2023a

#23664 {lang}[foss/2023b] Fix package dependencies versions for OCaml
  easybuild/easyconfigs/o/OCaml/OCaml-4.14.0-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OCaml/OCaml-5.1.1-GCC-13.2.0.eb
Labels: bug fix, 2023b

#22834 {phys}[foss/2023a] adding easyconfigs: McXtrace-3.5.24-foss-2023a.eb
  easybuild/easyconfigs/m/McXtrace/McXtrace-3.5.24-foss-2023a.eb
Labels: new, 2023a

#23765 add RTree module to SQLite 3.50.1, required by GDAL-3.11.3
  easybuild/easyconfigs/s/SQLite/SQLite-3.50.1-GCCcore-14.3.0.eb
Labels: enhancement, 2025b

#23782 {devel,lib}[GCCcore/13.3.0,foss/2024a] mcpl v2.2.0, CMake v3.31.8
  easybuild/easyconfigs/c/CMake/CMake-3.31.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/m/mcpl/mcpl-2.2.0-foss-2024a.eb
Labels: update

#18781 {mirtrace} [SYSTEM] mirtrace 1.0.1
  easybuild/easyconfigs/m/mirtrace/mirtrace-1.0.1-Java-17.eb
Labels: new

#23788 {tools}[foss/2024a] osmium-tool v1.18.0, libosmium v2.22.0, protozero v1.8.1
  easybuild/easyconfigs/l/libosmium/libosmium-2.22.0-foss-2024a.eb
  easybuild/easyconfigs/o/osmium-tool/osmium-tool-1.18.0-foss-2024a.eb
  easybuild/easyconfigs/p/protozero/protozero-1.8.1-GCCcore-13.3.0.eb
Labels: new

#23662 {math}[foss/2023b] Fix source for PARI-GP
  easybuild/easyconfigs/p/PARI-GP/PARI-GP-2.15.4-GCCcore-11.3.0.eb
  easybuild/easyconfigs/p/PARI-GP/PARI-GP-2.15.5-GCCcore-13.2.0.eb
Labels: bug fix, change, 2023b

#23773 {chem}[foss/2025b] GPAW v25.7.0, ELPA v2025.06.001, libxc v7.0.0, ...
  easybuild/easyconfigs/e/ELPA/ELPA-2025.06.001-foss-2025b.eb
  easybuild/easyconfigs/g/GPAW/GPAW-25.7.0-foss-2025b.eb
  easybuild/easyconfigs/g/gpaw-data/gpaw-data-1.0.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/l/libvdwxc/libvdwxc-0.5.0-foss-2025b.eb
  easybuild/easyconfigs/l/libxc/libxc-7.0.0-GCC-14.3.0.eb
Labels: update, ready-to-merge, 2025b

#20609 {bio}[gfbf/2023a] morphosamplers v0.0.16
  easybuild/easyconfigs/m/morphosamplers/morphosamplers-0.0.16-gfbf-2023a.eb
Labels: update, 2023a

#20885 {chem}[GCCcore/12.3.0] Chargemol v20211229
  easybuild/easyconfigs/c/Chargemol/Chargemol-20211229-GCCcore-12.3.0.eb
Labels: new, 2023a

#20873 {bio}[foss/2023b] Compleasm 0.2.6 foss 2023b
  easybuild/easyconfigs/c/compleasm/compleasm-0.2.6-foss-2023b.eb
  easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SEPP/SEPP-4.5.5-foss-2023b.eb
Labels: update, 2023b

#23709 {perf}[gompi/2025b,iimpi/2025b] OSU-Micro-Benchmarks v7.5.1
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.5.1-gompi-2025b.eb
  easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.5.1-iimpi-2025b.eb
Labels: update, 2025b

#23813 {bio}[GCCcore/13.3.0] GATK v4.6.2.0 w/ Java 17
  easybuild/easyconfigs/g/GATK/GATK-4.6.2.0-GCCcore-13.3.0-Java-17.eb
Labels: update, 2024a

#22739 {chem}[foss/2023b] OpenQP v1.0
  easybuild/easyconfigs/m/mpi4py/mpi4py-4.0.1-gompi-2023b.eb
  easybuild/easyconfigs/o/OpenQP/OpenQP-1.0-foss-2023b.eb
  easybuild/easyconfigs/o/OpenQP/OpenQP-1.0-foss-2023b_fix-libdlfind.patch
  test/easyconfigs/easyconfigs.py
Labels: new, update, 2023b

#23828 {tools}[GCCcore/14.3.0] intel-mbuild v2024.11.04, intel-XED v2025.06.08
  easybuild/easyconfigs/i/intel-XED/intel-XED-2025.06.08-GCCcore-14.3.0.eb
  easybuild/easyconfigs/i/intel-mbuild/intel-mbuild-2024.11.04-GCCcore-14.3.0.eb
Labels: update, 2025b

#23829 {tools}[GCCcore/14.3.0] xxHash v0.8.3, Dyninst v13.0.0, yaml-cpp v0.8.0
  easybuild/easyconfigs/d/Dyninst/Dyninst-13.0.0-GCC-14.3.0.eb
  easybuild/easyconfigs/x/xxHash/xxHash-0.8.3-GCCcore-14.3.0.eb
  easybuild/easyconfigs/y/yaml-cpp/yaml-cpp-0.8.0-GCCcore-14.3.0.eb
Labels: update, 2025b

#23831 add Simple-DFTD3 as dependency for CREST to avoid it being downloaded during the build
  easybuild/easyconfigs/c/CREST/CREST-3.0.2-gfbf-2023b.eb
Labels: bug fix, 2023b

#23603 {compiler}[GCCcore/10.3.0-11.3.0] Add explicit `libxml2` and `libffi` dependencies to LLVM 11.x/12.x/14.x
  easybuild/easyconfigs/l/LLVM/LLVM-11.1.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-14.0.3-GCCcore-11.3.0.eb
Labels: bug fix, change, 2021a, 2021b, 2022a

#23818 {compiler}[system/system] intel-compilers v2025.2.1
  easybuild/easyconfigs/i/intel-compilers/intel-compilers-2025.2.1.eb
Labels: update

#23834 {bio}[system/system] SeqKit v2.10.1
  easybuild/easyconfigs/s/SeqKit/SeqKit-2.10.1.eb
Labels: update

#23171 {compiler}[GCCcore/14.2.0] glslang-SPIRV v15.3.0
  easybuild/easyconfigs/g/glslang-SPIRV/glslang-SPIRV-15.3.0-GCCcore-14.2.0.eb
Labels: new, 2025a, ready-to-review

#23841 use `%%(source)s` in `STREAM` easyconfigs
  easybuild/easyconfigs/s/STREAM/STREAM-5.10-GCC-11.3.0.eb
  easybuild/easyconfigs/s/STREAM/STREAM-5.10-intel-compilers-2022.2.1.eb
  easybuild/easyconfigs/s/STREAM/STREAM-5.10-intel-compilers-2024.2.0.eb
Labels: bug fix, 2024a, 2022a, 2022b

#23835 {tools}[GCCcore/14.3.0] tcsh v6.24.16
  easybuild/easyconfigs/t/tcsh/tcsh-6.24.16-GCCcore-14.3.0.eb
Labels: update, 2025b, ready-to-review

#23864 Fix SuiteSparse options for CVXOPT-1.2.6-foss-2021a.
  easybuild/easyconfigs/c/CVXOPT/CVXOPT-1.2.6-foss-2021a.eb
Labels: change, 2021a

#23872 Fix meson options for matplotlib 3.9+
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.10.3-gfbf-2025a.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.10.5-gfbf-2025b.eb
  easybuild/easyconfigs/m/matplotlib/matplotlib-3.9.2-gfbf-2024a.eb
Labels: bug fix, 2024a, 2025a, 2025b

#23878 replace broken source URL with download instructions in easyconfigs for bcl-convert 4.3.13
  easybuild/easyconfigs/b/bcl-convert/bcl-convert-4.3.13-2.el8.x86_64.eb
Labels: change

#23877 {bio}[GCC/13.2.0] bcl2fastq2 v2.20.0
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-GCC-13.2.0.eb
  easybuild/easyconfigs/b/bcl2fastq2/bcl2fastq2-2.20.0-fix-gcc13.patch
Labels: update, 2023b

#23857 {lib}[foss/2024a] heat v1.6.0
  easybuild/easyconfigs/h/heat/heat-1.6.0-foss-2024a.eb
  easybuild/easyconfigs/h/heat/heat-1.6.0-license-fix.patch
  easybuild/easyconfigs/h/heat/heat-1.6.0-scipy-version.patch
Labels: new, 2024a

#23200 {chem}[gompi/2023b] ORCA v6.1.0 w/ avx2
  easybuild/easyconfigs/o/ORCA/ORCA-6.1.0-gompi-2023b-avx2.eb
  easybuild/easyconfigs/o/ORCA/ORCA-6.1.0-gompi-2023b.eb
Labels: update, 2023b

#23908 consistently apply patch for OpenMPI 5.x to fix compatibility with recent GPFS versions
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3-GCC-13.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3-NVHPC-24.9-CUDA-12.6.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3-intel-compilers-2024.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7-GCC-14.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7-intel-compilers-2025.1.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.8-GCC-14.3.0.eb
Labels: bug fix, 2024a, 2025a, 2025b

#23911 add patch to fix compatibility of OpenMPI 4.1.5+ with recent GPFS
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-intel-compilers-2023.1.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.6-GCC-13.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.6-intel-compilers-2023.2.1.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.x_fix-gpfs.patch
Labels: bug fix

#23853 {bio}[GCC-13.3.0] NextPolish 1.4.1
  easybuild/easyconfigs/n/NextPolish/NextPolish-1.4.1-2025-01-08_relauxtab.patch
  easybuild/easyconfigs/n/NextPolish/NextPolish-1.4.1-GCC-13.3.0-2025-01-08.eb
Labels: update, 2024a

#23916 add patch to fix compatibility of OpenMPI v4.1.2 + v4.1.4 with recent GPFS
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-GCC-11.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-11.3.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-12.2.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-NVHPC-22.7-CUDA-11.7.0.eb
  easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-intel-compilers-2022.2.1.eb
Labels: bug fix

#23918 {lang}[foss/2025a] numba v0.62.0
  easybuild/easyconfigs/n/numba/numba-0.62.0-foss-2025a.eb
Labels: update, 2025a

#23954 {lib}[GCCcore/14.3.0] spdlog v1.15.3
  easybuild/easyconfigs/s/spdlog/spdlog-1.15.3-GCCcore-14.3.0.eb
Labels: update, 2025b, ready-to-review

#19960 {chem}[foss/2022b] DIRAC v24.0
  easybuild/easyconfigs/d/DIRAC/DIRAC-24.0-foss-2022b.eb
Labels: update, 2022b

#21392 switch to `CargoPythonBundle` easyblock for orjson 3.9.15
  easybuild/easyconfigs/o/orjson/orjson-3.9.15-GCCcore-12.3.0.eb
Labels: bug fix, 2023a

#23922 Explicitly disable building documentation in recent `HarfBuzz` easyconfigs
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-11.2.1-GCCcore-14.2.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-11.4.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-9.0.0-GCCcore-13.3.0.eb
Labels: change, 2025a, 2025b

#23801 Remove duplicate Pygments package from Python-bundle-PyPI
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2023.06-GCCcore-12.3.0.eb
  easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2023.10-GCCcore-13.2.0.eb
Labels: bug fix, 2023a, 2023b

#23998 also install Python bindings in recent tblite 0.4.0 easyconfigs
  easybuild/easyconfigs/t/tblite/tblite-0.4.0-gfbf-2023b.eb
  easybuild/easyconfigs/t/tblite/tblite-0.4.0-gfbf-2024a.eb
Labels: enhancement

#24005 {tools}[GCCcore/13.2.0] Vim v9.1.1788
  easybuild/easyconfigs/v/Vim/Vim-9.1.1788-GCCcore-13.2.0.eb
Labels: update, 2023b

#24004 {tools}[GCCcore/13.3.0] cdsapi v0.7.6
  easybuild/easyconfigs/c/cdsapi/cdsapi-0.7.6-GCCcore-13.3.0.eb
Labels: update, 2024a

#24022 get rid of useless empty file
  .force_change
Labels: code cleanup

#24024 {tools}[system/system] EasyBuild v5.1.2
  easybuild/easyconfigs/e/EasyBuild/EasyBuild-5.1.2.eb
  test/easyconfigs/easyconfigs.py
Labels: update

#24023 Force the EasyBuild defined CUDA compute capabilities in LightGBM 4.5.0
  easybuild/easyconfigs/l/LightGBM/LightGBM-4.5.0-foss-2023a-CUDA-12.1.1.eb
  easybuild/easyconfigs/l/LightGBM/lightgbm_v4.5.0_allow_eb_cuda_ccs.patch
  easybuild/easyconfigs/l/LightGBM/lightgbm_v4.5.0_fix_cuda_cmake.patch
Labels: bug fix, change

#24015 {devel}[GCCcore/14.2.0] SCons v4.9.1
  easybuild/easyconfigs/s/SCons/SCons-4.9.1-GCCcore-14.2.0.eb
Labels: update, 2025a

#24009 explicitly disable Poppler in GDAL 3.11.3 to not pick up system one
  easybuild/easyconfigs/g/GDAL/GDAL-3.11.3-foss-2025b.eb
Labels: bug fix, 2025b

#23965 {vis}[GCCcore/14.3.0] DBus v1.16.2, FFmpeg v7.1.2, SDL2 v2.32.10, ...
  easybuild/easyconfigs/d/DBus/DBus-1.16.2-GCCcore-14.3.0.eb
  easybuild/easyconfigs/f/FFmpeg/FFmpeg-7.1.2-GCCcore-14.3.0.eb
  easybuild/easyconfigs/s/SDL2/SDL2-2.32.10-GCCcore-14.3.0.eb
  easybuild/easyconfigs/x/x264/x264-20250831-GCCcore-14.3.0.eb
Labels: update, 2025b

#23947 {bio}[GCCcore/13.2.0] LSD2 v2.4.1
  easybuild/easyconfigs/l/LSD2/LSD2-2.4.1-GCCcore-13.2.0.eb
Labels: update, 2023b

#24043 {lang}[system/system] Java v25
  easybuild/easyconfigs/j/Java/Java-25.eb
Labels: update

#24034 {vis}[system/system] Avogadro2 v1.101.0 w/ linux x86_64
  easybuild/easyconfigs/a/Avogadro2/Avogadro2-1.101.0-linux-x86_64.eb
Labels: update

#24010 explicitly disable Poppler in GDAL 3.9.0, 3.10.0, 3.11.1 to not pick up system one
  easybuild/easyconfigs/g/GDAL/GDAL-3.10.0-foss-2024a.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.11.1-foss-2025a.eb
  easybuild/easyconfigs/g/GDAL/GDAL-3.9.0-foss-2023b.eb
Labels: bug fix, 2023b, 2024a, 2025a

#24003 {tools}[foss/2024a] cfgrib v0.9.15.0
  easybuild/easyconfigs/c/cfgrib/cfgrib-0.9.15.0-foss-2024a.eb
Labels: update, 2024a

#24033 {tools}[system/system] Jmol v16.3.33 w/ Java 17
  easybuild/easyconfigs/j/Jmol/Jmol-16.3.33-Java-17.eb
Labels: update

#23821 {vis}[system/system] OSPRay v2.12.0
  easybuild/easyconfigs/o/OSPRay/OSPRay-2.12.0.eb
Labels: update

#23884 {lib}[GCCcore/13.3.0] Parallel-Hashmap v2.0.0
  easybuild/easyconfigs/p/Parallel-Hashmap/Parallel-Hashmap-2.0.0-GCCcore-13.3.0.eb
Labels: update, 2024a

#24030 Enable GIR in recent Pango
  easybuild/easyconfigs/p/Pango/Pango-1.56.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.56.4-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/Pango/Pango-1.57.0-GCCcore-14.3.0.eb
Labels: bug fix, change, 2025a, 2025b

#24047 {tools}[GCCcore/14.3.0] JupyterLab v4.4.9, JupyterNotebook v7.4.7, jupyter-server v2.17.0, ...
  easybuild/easyconfigs/b/BeautifulSoup/BeautifulSoup-4.14.2-GCCcore-14.3.0.eb
  easybuild/easyconfigs/h/hatch-jupyter-builder/hatch-jupyter-builder-0.9.1-GCCcore-14.3.0.eb
  easybuild/easyconfigs/j/JupyterLab/JupyterLab-4.4.9-GCCcore-14.3.0.eb
  easybuild/easyconfigs/j/JupyterNotebook/JupyterNotebook-7.4.7-GCCcore-14.3.0.eb
  easybuild/easyconfigs/j/jupyter-server/jupyter-server-2.17.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/p/PyZMQ/PyZMQ-27.1.0-GCCcore-14.3.0.eb
Labels: update, 2025b
