Repository easybuilders/easybuild-easyconfigs, pull requests merged in 2025-10, with the labels that each got.

#24077 {tools}[GCCcore/14.3.0] filecheck-python v1.0.3
  easybuild/easyconfigs/f/filecheck-python/filecheck-python-1.0.3-GCCcore-14.3.0.eb
Labels: new, 2025b

#24084 {bio}[GCC/13.3.0] CD-HIT v4.8.1
  easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.8.1-GCC-13.3.0.eb
Labels: update, 2024a

#24002 {data}[GCCcore/14.3.0] BioPerl v1.7.8, Cartopy v0.25.0, Fiona v1.10.1, ...
  easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-14.3.0.eb
  easybuild/easyconfigs/c/Cartopy/Cartopy-0.25.0-foss-2025b.eb
  easybuild/easyconfigs/f/Fiona/Fiona-1.10.1-foss-2025b.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0210-GCCcore-14.3.0.eb
  easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0210_fix-test-failures.patch
Labels: update, 2025b

#23959 {data}[GCC/14.3.0] HDF5 v1.14.6 w/ serial
  easybuild/easyconfigs/h/HDF5/HDF5-1.14.6-GCC-14.3.0-serial.eb
Labels: update, 2025b, ready-to-review

#24086 {bio}[gompi/2024a] PfamScan v1.6
  easybuild/easyconfigs/p/PfamScan/PfamScan-1.6-gompi-2024a.eb
Labels: update, 2024a

#24094 add `-lpthread` to configure options for `Parallel-Hashmap v2.0.0`
  easybuild/easyconfigs/p/Parallel-Hashmap/Parallel-Hashmap-2.0.0-GCCcore-13.3.0.eb
Labels: change, 2024a

#24089 {bio}[GCCcore/13.3.0,gompi/2024a] IQ-TREE v2.4.0, LSD2 v2.4.1
  easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.4.0-gompi-2024a.eb
  easybuild/easyconfigs/l/LSD2/LSD2-2.4.1-GCCcore-13.3.0.eb
Labels: update, 2024a

#23985 {data}[foss/2025b] h5py v3.14.0
  easybuild/easyconfigs/h/h5py/h5py-3.14.0-foss-2025b.eb
Labels: update, 2025b, ready-to-review

#24099 {tools}[system/system] code-server v4.104.2
  easybuild/easyconfigs/c/code-server/code-server-4.104.2.eb
Labels: update

#24103 {lib}[gompi/2025b] SIONfwd v1.0.1, SIONlib v1.7.7
  easybuild/easyconfigs/s/SIONfwd/SIONfwd-1.0.1-gompi-2025b.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-gompi-2025b.eb
  easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7_better-support-aarch64.patch
Labels: new, update, 2025b

#24040 add patch to LLVM 20.1.5 to better support CUDA 13 and Blackwell GPUs
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.3.0.eb
Labels: bug fix, 2023b, 2024a

#23779 {cae}[system/system] HEEDS v2504
  easybuild/easyconfigs/h/HEEDS/HEEDS-2504.eb
Labels: update

#23756 {vis}[GCCcore/14.2.0] libGLU v9.0.3
  easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-14.2.0.eb
Labels: update, 2025a

#24082 {bio}[gomkl/2023a] SDPR v0.9.1
  easybuild/easyconfigs/s/SDPR/SDPR-0.9.1-gomkl-2023a.eb
Labels: new, 2023a, ready-to-review

#24106 {data}[iimkl/2025b] scikit-learn v1.7.1
  easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.7.1-iimkl-2025b.eb
Labels: update, 2025b

#23931 {tools}[system/system] code-server v4.104.0
  easybuild/easyconfigs/c/code-server/code-server-4.104.0.eb
Labels: update

#24080 {lib}[gfbf/2025b] CUDA-Python v12.9.2 w/ CUDA 12.9.1
  easybuild/easyconfigs/c/CUDA-Python/CUDA-Python-12.9.2-gfbf-2025b-CUDA-12.9.1.eb
Labels: update, 2025b

#24059 {system}[GCCcore/14.2.0] gnupg-bundle v20250930
  easybuild/easyconfigs/g/gnupg-bundle/gnupg-bundle-20250930-GCCcore-14.2.0.eb
Labels: update, 2025a

#24105 {chem}[intel/2025b] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-intel-2025b.eb
Labels: update, 2025b

#24071 {numlib}[foss/2025a] preCICE v3.2.0
  easybuild/easyconfigs/p/preCICE/preCICE-3.2.0-foss-2025a.eb
Labels: update, 2025a

#24014 {lib}[SYSTEM] cuTENSOR v2.3.1.0
  easybuild/easyconfigs/c/cuTENSOR/cuTENSOR-2.3.1.0-CUDA-12.9.1.eb
Labels: update, ready-to-review

#24116 use GNU_SOURCE for cpio-2.14-GCCcore-11.3.0.eb
  easybuild/easyconfigs/c/cpio/cpio-2.14-GCCcore-11.3.0.eb
Labels: change

#24117 Use ftpmirror.gnu.org for libidn2
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.0-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.4-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.7-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.7-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.8-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libidn2/libidn2-2.3.8-GCCcore-14.3.0.eb
Labels: change

#24119 Use GNU_SOURCE in plotutils
  easybuild/easyconfigs/p/plotutils/plotutils-2.6-GCC-11.3.0.eb
Labels: change

#24120 Use ftpmirror.gnu.org for CVS
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-11.2.0.eb
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-13.3.0.eb
  easybuild/easyconfigs/c/ConcurrentVersionsSystem/ConcurrentVersionsSystem-1.11.23-GCCcore-14.3.0.eb
Labels: change

#24108 Use GNU_SOURCE for all libreadline
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-10.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-11.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1.2-GCCcore-11.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.1.2-GCCcore-12.1.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-12.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-12.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-13.1.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-13.3.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libreadline/libreadline-8.2-GCCcore-14.3.0.eb
Labels: bug fix, change

#24111 {tools}[GCCcore/14.2.0,GCCcore/14.3.0] pigz v2.8
  easybuild/easyconfigs/p/pigz/pigz-2.8-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pigz/pigz-2.8-GCCcore-14.3.0.eb
Labels: update

#23957 {bio}[GCC/14.2.0] VCFtools v0.1.17
  easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.17-GCC-14.2.0.eb
Labels: update, 2025a

#23910 {lib}[GCCcore/14.2.0] jemalloc v5.3.0, Judy v1.0.5
  easybuild/easyconfigs/j/Judy/Judy-1.0.5-GCCcore-14.2.0.eb
  easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-14.2.0.eb
Labels: update, 2025a, ready-to-review

#23930 {tools}[GCCcore/14.2.0] mallard-ducktype v1.0.2
  easybuild/easyconfigs/m/mallard-ducktype/mallard-ducktype-1.0.2-GCCcore-14.2.0.eb
Labels: update, 2025a

#23934 {vis}[GCCcore/14.2.0] Graphviz v13.1.2 w/ minimal
  easybuild/easyconfigs/g/Graphviz/Graphviz-13.1.2-GCCcore-14.2.0-minimal.eb
Labels: update, 2025a

#24079 {tools}[GCCcore/14.2.0] laspy v2.6.1, lazrs v0.7.0, PDM v2.25.5
  easybuild/easyconfigs/l/laspy/laspy-2.6.1-foss-2025a.eb
  easybuild/easyconfigs/l/laspy/laspy-2.6.1_fix-lasheader.patch
  easybuild/easyconfigs/l/lazrs/lazrs-0.7.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/PDM/PDM-2.25.5-GCCcore-14.2.0.eb
Labels: new, update, 2025a

#24057 {bio}[GCCcore/14.2.0] minimap2 v2.30
  easybuild/easyconfigs/m/minimap2/minimap2-2.30-GCCcore-14.2.0.eb
Labels: update, 2025a

#24078 {tools}[GCCcore/14.2.0] overpy v0.7
  easybuild/easyconfigs/o/overpy/overpy-0.7-GCCcore-14.2.0.eb
Labels: new, 2025a

#23772 {lib}[intel-compilers/2025.2.0] likwid v5.4.1, NTL v11.5.1, pybind11_abseil v202402.0, ...
  easybuild/easyconfigs/l/likwid/likwid-5.4.1-intel-compilers-2025.2.0.eb
  easybuild/easyconfigs/l/likwid/likwid-5.4.1_oneapi-support.patch
  easybuild/easyconfigs/n/NTL/NTL-11.5.1-intel-compilers-2025.2.0.eb
  easybuild/easyconfigs/p/pybind11_abseil/pybind11_abseil-202402.0-intel-compilers-2025.2.0.eb
  easybuild/easyconfigs/p/pyspoa/pyspoa-0.2.1-intel-compilers-2025.2.0.eb
  easybuild/easyconfigs/s/spoa/spoa-4.1.0-intel-compilers-2025.2.0.eb
Labels: update, 2025b

#23953 {data}[gfbf/2025b-serial] h5py v3.14.0
  easybuild/easyconfigs/h/h5py/h5py-3.14.0-gfbf-2025b-serial.eb
Labels: update, 2025b

#23889 {bio}[GCC/14.2.0] seqtk v1.5
  easybuild/easyconfigs/s/seqtk/seqtk-1.5-GCC-14.2.0.eb
Labels: update, 2025a, ready-to-review

#23914 {bio}[GCC/14.2.0] DIAMOND v2.1.14
  easybuild/easyconfigs/d/DIAMOND/DIAMOND-2.1.14-GCC-14.2.0.eb
Labels: update, 2025a, ready-to-review

#24001 {tools} [GCCcore/13.3.0, GCCcore/13.2.0] JupyterLab-git v.0.51.2, JupyterLab-git v.0.51.1
  easybuild/easyconfigs/j/JupyterLab-git/JupyterLab-git-0.51.1-GCCcore-13.2.0.eb
  easybuild/easyconfigs/j/JupyterLab-git/JupyterLab-git-0.51.2-GCCcore-13.3.0.eb
Labels: new, 2023b, 2024a

#24127 update homepage of foss toolchain
  easybuild/easyconfigs/f/foss/foss-2021a.eb
  easybuild/easyconfigs/f/foss/foss-2021b.eb
  easybuild/easyconfigs/f/foss/foss-2022.05.eb
  easybuild/easyconfigs/f/foss/foss-2022.10.eb
  easybuild/easyconfigs/f/foss/foss-2022a.eb
  easybuild/easyconfigs/f/foss/foss-2022b.eb
  easybuild/easyconfigs/f/foss/foss-2023.09.eb
  easybuild/easyconfigs/f/foss/foss-2023a.eb
  easybuild/easyconfigs/f/foss/foss-2023b.eb
  easybuild/easyconfigs/f/foss/foss-2024.05.eb
  easybuild/easyconfigs/f/foss/foss-2024a.eb
  easybuild/easyconfigs/f/foss/foss-2025a.eb
  easybuild/easyconfigs/f/foss/foss-2025b.eb
Labels: change

#24123 fix CMake options in `preCICE/3.2.0-foss-2025a`
  easybuild/easyconfigs/p/preCICE/preCICE-3.2.0-foss-2025a.eb
Labels: bug fix, 2025a

#23417 {bio}[system/system] SpaceRanger v3.1.2, SpaceRanger v3.1.3, SpaceRanger v4.0.1
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-3.1.2.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-3.1.3.eb
  easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-4.0.1.eb
Labels: update

#23861 {tools}[gfbf/2025a,gfbf/2025b] WebDataset v1.0.2
  easybuild/easyconfigs/w/WebDataset/WebDataset-1.0.2-gfbf-2025a.eb
  easybuild/easyconfigs/w/WebDataset/WebDataset-1.0.2-gfbf-2025b.eb
Labels: update, 2025a, 2025b

#23944 {lib}[GCCcore/14.2.0] libopus v1.5.2, LMDB v0.9.31, libvorbis v1.3.7, ...
  easybuild/easyconfigs/l/LMDB/LMDB-0.9.31-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libopus/libopus-1.5.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libsndfile/libsndfile-1.2.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/l/libvorbis/libvorbis-1.3.7-GCCcore-14.2.0.eb
Labels: update, 2025a

#24031 {devel}[GCCcore/14.3.0] SCons v4.9.1
  easybuild/easyconfigs/s/SCons/SCons-4.9.1-GCCcore-14.3.0.eb
Labels: update, 2025b, ready-to-review

#24032 {tools}[GCCcore/14.2.0] ccache v4.11.3
  easybuild/easyconfigs/c/ccache/ccache-4.11.3-GCCcore-14.2.0.eb
  easybuild/easyconfigs/h/hiredis/hiredis-1.3.0-GCCcore-14.2.0.eb
Labels: update, 2025a

#24035 {tools}[GCCcore/14.3.0] zlib-ng v2.2.5, versioningit v3.3.0
  easybuild/easyconfigs/v/versioningit/versioningit-3.3.0-GCCcore-14.3.0.eb
  easybuild/easyconfigs/z/zlib-ng/zlib-ng-2.2.5-GCCcore-14.3.0.eb
Labels: update, 2025b, ready-to-review

#24046 {chem}[foss/2025b] Wannier90 v3.1.0
  easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-foss-2025b.eb
Labels: update, 2025b, ready-to-review

#24048 Expose vulkan ICDs in Mesa 25
  easybuild/easyconfigs/m/Mesa/Mesa-25.1.3-GCCcore-14.2.0.eb
Labels: change, 2025a

#24052 {cae,vis}[GCCcore/14.2.0] FreeImage v3.18.0, occt v7.9.1
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-byteswap-ulong.patch
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-unistd-include.patch
  easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-wchar-include.patch
  easybuild/easyconfigs/o/occt/occt-7.9.1-GCCcore-14.2.0.eb
Labels: update, 2025a

#24063 {math}[system/system] MathWorksServiceHost v2025.9.0.2
  easybuild/easyconfigs/m/MathWorksServiceHost/MathWorksServiceHost-2025.9.0.2.eb
Labels: update

#24053 {math}[system/system] MathWorksServiceHost v2025.5.1.1
  easybuild/easyconfigs/m/MathWorksServiceHost/MathWorksServiceHost-2025.5.1.1.eb
Labels: update

#24110 {vis}[GCCcore/14.2.0] FLTK v1.4.4, xprop v1.2.8
  easybuild/easyconfigs/f/FLTK/FLTK-1.4.4-GCCcore-14.2.0.eb
  easybuild/easyconfigs/x/xprop/xprop-1.2.8-GCCcore-14.2.0.eb
Labels: update, 2025a

#24112 {tools}[GCCcore/14.2.0,GCCcore/14.3.0] DMTCP v4.0.0
  easybuild/easyconfigs/d/DMTCP/DMTCP-4.0.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/d/DMTCP/DMTCP-4.0.0-GCCcore-14.3.0.eb
Labels: update, 2025a, 2025b

#24114 {vis}[GCCcore/14.3.0] Vulkan v1.4.328
  easybuild/easyconfigs/v/Vulkan/Vulkan-1.4.328-GCCcore-14.3.0.eb
Labels: new, 2025b

#24125 Add missing Python dep to h5glance
  easybuild/easyconfigs/h/h5glance/h5glance-0.9.0-foss-2024a.eb
Labels: bug fix, 2024a

#24128 {tools}[GCCcore/14.2.0,GCCcore/14.3.0] coverage v7.10.7
  easybuild/easyconfigs/c/coverage/coverage-7.10.7-GCCcore-14.2.0.eb
  easybuild/easyconfigs/c/coverage/coverage-7.10.7-GCCcore-14.3.0.eb
Labels: update, 2025a, 2025b

#24129 {tools}[GCCcore/14.2.0,GCCcore/14.3.0] pre-commit v4.3.0
  easybuild/easyconfigs/p/pre-commit/pre-commit-4.3.0-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pre-commit/pre-commit-4.3.0-GCCcore-14.3.0.eb
Labels: update, 2025a, 2025b

#24132 {astro}[gfbf/2025b] astropy v7.1.0, astropy-testing v7.1.0
  easybuild/easyconfigs/a/astropy-testing/astropy-testing-7.1.0-gfbf-2025b.eb
  easybuild/easyconfigs/a/astropy/astropy-7.1.0-gfbf-2025b.eb
Labels: update, 2025b

#24149 {data}[GCCcore/14.2.0,GCCcore/14.3.0] pugixml v1.15
  easybuild/easyconfigs/p/pugixml/pugixml-1.15-GCCcore-14.2.0.eb
  easybuild/easyconfigs/p/pugixml/pugixml-1.15-GCCcore-14.3.0.eb
Labels: update, 2025a, 2025b

#24151 {data}[GCCcore/13.2.0,GCCcore/14.2.0,GCCcore/14.3.0] libmad v0.15.1b, SoX v14.4.2
  easybuild/easyconfigs/l/libmad/libmad-0.15.1b-GCCcore-13.2.0.eb
  easybuild/easyconfigs/l/libmad/libmad-0.15.1b-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-13.2.0.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-14.2.0.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-14.3.0.eb
  easybuild/easyconfigs/s/SoX/SoX-14.4.2_include_math.patch
Labels: update, 2023b, 2025a, 2025b

#24066 add post install commands for QCMaquis 4.0.0 to fix `MAQUIS_DMRGConfig.cmake` used by OpenMolcas
  easybuild/easyconfigs/q/QCMaquis/QCMaquis-4.0.0-iomkl-2023a.eb
Labels: bug fix, 2023a

#24159 {tools}[system/system] code-server v4.104.3
  easybuild/easyconfigs/c/code-server/code-server-4.104.3.eb
Labels: update

#24158 addd M4 and Autotools builddependencies to ABINIT
  easybuild/easyconfigs/a/ABINIT/ABINIT-9.10.3-intel-2022a.eb
Labels: change, 2022a
